### ISSUE TITLE
Sugestão de Funções

### ISSUE THREAD

**Issue by hardbrasil** [RamonSilva20/mapos#10]
Sugiro que coloquemos aqui sugestão de funcionalidades no sistema e quem possa contribuir com a adição das mesmas notificar em qual vai trabalhar e sempre testar e mostrar o andamento de tais funcionalidades.

Para Começar eu Sugiro:
*Ao ser impressa a OS esta apareça os dados de Contato Completos do Cliente..
* No Preenchimento da OS Inserção de campos e criação de BD para campos auto selecionáveis como por exemplo: Tipo de Aparelho : Televisor, DVD, Rádio Mp3, Boombox, Computador, Notebook, Vídeo Game
Subcampo Marca = Lenoxx, CCE, Positivo, Dell, HP, Samsung, Cadence, Oster,Phillips, Britania, Eletrolux etc...
Modelo = Descrição do modelo ou cod do modelo
N de Série = Serial de Identificação do Aparelho
Estado do Aparelho = Estado que o mesmo se encontra no ato de abertura de os em balcão
Acessórios: Acessórios e partes deixadas junto com o aparelho
Defeito reclamado = defeito Relatado pelo Cliente
Relatório Técnico = Sugiro mudar o nome do campo laudo para Relatório técnico visando evitar problemas jurídicos.
Ao Criar estes campos creio que seria possível criar Filtros para localização facilitada de aparelhos e ordens exemplo: Por marca, modelo, numero de serie, data de entrada.
Aliás a busca por n de os e número de série é extremamente importante para um bom andamento de os.

* Criação de Tags de Cores para o status de os: Exemplos: Verde = Liberada ok, Vermelha = Entrada, Amarelo = Aguardando Peças, Marrom = Aguardando Aprovação Roxo = Equipamento Abandonado  etc...
* Criação de funcionalidade que envie uma cópia da ordem com os dados de entrada, do cliente e do aparelho para o e-mail cadastrado do cliente e a geração de um código para que este acompanhe apenas o status das ordens e observações ao cliente. 

Bem no momento minhas sugestões são estas.

**Comment by TecSecret** [comment]
@hardbrasil ,

Confira nosso changelog **[Clicando Aqui](https://github.com/TecSecret/TSDC-Assistencia/wiki/Change-Log)**, o mesmo já está implantado em nosso repositório.

Um grande abraço
