### ISSUE TITLE
Não consigo cadastrar uma venda

### ISSUE THREAD

**Issue by TVANDRA** [RamonSilva20/mapos#1001]
Boa tarde a Todos!
Ao tentar cadastrar uma venda, os campos data (já pré selecionada conforme a data em atual), seleciono um dos clientes cadastrados, conforme preenchimento automático e vendedor já selecionado conforme o login feito no sistema. Ao clicar em continuar apresenta o seguinte erro : "Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente e responsável. "  Alguém pode me ajudar por favor?
![Erro venda mapos](https://user-images.githubusercontent.com/72506742/96043598-975e3d00-0e45-11eb-9a6a-12a807352e73.jpg)

**Comment by Pr3d4dor** [comment]
@TVANDRA Já tentou preencher todos os campos e ir deixando eles em branco um a um para ver qual deles está ocasionando o erro?

**Comment by TVANDRA** [comment]
Opa @Pr3d4dor já tentei fazer isso, quando deixo em branco qualquer dos campos, ele seleciona o campo que está em branco e exibe a mensagem de Campos requerido, porém preenchendo o mesmo e depois clicando em continuar exibe a mensagem como se não estivesse preenchido corretamente...
