### ISSUE TITLE
Alertas na Agenda

### ISSUE THREAD

**Issue by JulianoSavino** [RamonSilva20/mapos#1002]
Pessoal, a função da agenda está ótima, mas será que ficaria dificil implementar uma forma de alerta?
Por exemplo:
Crio uma OS com status de **agendamento** por exemplo, daqui a dois dias para data e horario já determinado na abertura da mesma e quando chegar o dia, toda a vez que abrir o sistema ele avisa na tela com uma pop-up dos agendamentos do dia. Pode ter aviso sonoro e/ou a janela abrindo de tempo em tempo caso não feche o sistema. Isso ajudaria pois trabalho bastante com agenda e uso no celular tambem o sistema. Gostaria de poder contribuir mas meus conhecimentos são restritos.
Agradeço

**Comment by Pr3d4dor** [comment]
@JulianoSavino Isso não é tão simples de ser feito, porém iremos implementar assim que possível.
