### ISSUE TITLE
Resolvendo o Bug quando acessa via Smartphone

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#1003]
E aí pessoal blz
quem acessa o sistema via smartphone tem notado dois bugs.
1º o sistema não fica responsivo ,após fazer o Login a tela fica com espaço de 20% para a direita.
para resolver isso vou passar o caminho...
C:\xampp\htdocs\sistema\assets\css\matrix-style.css na altura da linha 1342 tem esse código
#user-nav > ul {
    margin-left:20%!important;
	right: 0px;
	margin-top:0px;
	width:100%;
	background:#000;
	position: relative;
}

Para resolver, basta deixar  "0" como mostrado abaixo
#user-nav > ul {
    margin-left:0%!important;
	right: 0px;
	margin-top:0px;
	width:100%;
	background:#000;
	position: relative;
}
Pronto.. daí só atualizar e testar o smartphone e vai ficar ajustado !
........................................................................................................................................................................................................................................................

2º Bug é quando vai em vendas ou OS  os ícones de impressoras ,editar fica pra fora da tela do smartphone
para resolver ,basta abrir as pastas do sistema  como mostra o exemplo abaixo...
C:\xampp\htdocs\sistema\application\views\clientes\cliente.php
na altura da linha 13 vai encontrar o seguinte código  ...

```
<div class="widget-content nopadding">
logo abaixo desse código vai adicionar o seguinte ... ficando como mostra abaixo
<div class="widget-content nopadding">
	<div class="tab-content">
</div>
     </div>
```

* Lembrando que essa segunda div vai ficar dentro da primeira fechando embaixo...
Desse modo depois de fazer nos arquivos, é só salvar e testar no smartphone que vai está corrigido
isso precisa ser feito em alguns arquivos .
**clientes, produtos, os, relatórios, vendas, financeiro ,serviços**  
e mais em alguma alteração que você tenha feito no seu sistema. 

O sistema de amostra está Online e quem quiser conferir
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
senha: 123456

Desde já agradeço a atenção de vocês!

**Comment by Pr3d4dor** [comment]
@visaotec Obrigado por avisar, consegue fazer uma PR com as correções, a primeira correção eu mesmo vou aplicar mas a segunda parece que ficou sem o código a ser mudado.

**Comment by visaotec** [comment]
> @visaotec Obrigado por avisar, consegue fazer uma PR com as correções, a primeira correção eu mesmo vou aplicar mas a segunda parece que ficou sem o código a ser mudado.

em assets\css\matrix-style.css na linha 1342 somente mudar o  margin-left:20%!important;  para "margin-left:0%!important; "  ou simplesmente remover essa linha "margin-left:20%!important;" 
isso corrige a falha que tem ao acessar pelo celular ...
Abraços

**Comment by visaotec** [comment]
> @visaotec Obrigado por avisar, consegue fazer uma PR com as correções, a primeira correção eu mesmo vou aplicar mas a segunda parece que ficou sem o código a ser mudado.

C:\xampp\htdocs\sistema\application\views\clientes\cliente.php
na altura da linha 13 vai encontrar o seguinte código  ...
<div class="widget-content nopadding">
logo abaixo desse código vai adicionar o seguinte ... ficando como mostra abaixo
<div class="widget-content nopadding">
	<div class="tab-content">
</div>
     </div>

**Comment by visaotec** [comment]
> @visaotec Obrigado por avisar, consegue fazer uma PR com as correções, a primeira correção eu mesmo vou aplicar mas a segunda parece que ficou sem o código a ser mudado.

Corrigi lá no poste ....

**Comment by Pr3d4dor** [comment]
@visaotec Corrigido na versão v4.18.0 conforme suas sugestões, colocado créditos no CHANGELOG.
