### ISSUE TITLE
Campos numéro de serie/imei e campo modelo

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#1004]
* Os campos número de **SÉRIE/IMEI** talvez poderia ser um campo especifico de forma que ao informar um número de série em uma nova ordem de serviço no momento da abertura ao preencher o campo de número de série o sistema realiza a consulta se já existiu OS anterior com esse mesmo número e dar as opções ao usuário de abrir uma OS de revisão ou abrir nova OS.

==> Deste modo quem está cadastrando toma conhecimento se o aparelho já deu entrada na assistência se é a mesma pessoa que esta trazendo, qual foi o defeito anterior e se foi resolvido na assistência, pode facilitar na criação de um filtro por série/imei para localizar aparelhos que tenham perdido sua identificação ou até mesmo se a uma violação na etiqueta do produto.

 * Assim como os campos **MARCA, MODELO e DESCRIÇÃO** também talvez poderiam ser um campos específicos de cadastro de forma a associar cada marca ao seu modelo e também contendo um descrição

----------------------------
**Marca**: *Samsung*
**Modelo**: *UN32j4300AG* - ao digitar um modelo já cadastrado é exibido sua descrição
**Descrição**: *Smart TV* 

------------------------------
==> ***Caso o modelo não tenha sido cadastrado é solicitado o cadastro no momento da abertura da OS***

Um cadastro rápido informando apenas as informações de marca, modelo, descrição e qual a linha que esse aparelho pertence.

-E para agilizar o processo as informações digitadas no momento do cadastro da OS ja podem ser aproveitadas para o preenchimento do cadastro da marca cabendo ao usuário realizar somente as correções necessárias.

--Estas opções facilitaria a criação de novos filtros e gráficos e relatórios para uma melhor visualização quando há na assistência a possibilidade de reparo de produtos de diversas linhas. Isso também pode evitar a digitação incorreta do modelo.

**Comment by Pr3d4dor** [comment]
@lrochawl Obrigado pela sugestão, iremos implementar assim que possível.

**Comment by visaotec** [comment]
> * Os campos número de **SÉRIE/IMEI** talvez poderia ser um campo especifico de forma que ao informar um número de série em uma nova ordem de serviço no momento da abertura ao preencher o campo de número de série o sistema realiza a consulta se já existiu OS anterior com esse mesmo número e dar as opções ao usuário de abrir uma OS de revisão ou abrir nova OS.
> 
> ==> Deste modo quem está cadastrando toma conhecimento se o aparelho já deu entrada na assistência se é a mesma pessoa que esta trazendo, qual foi o defeito anterior e se foi resolvido na assistência, pode facilitar na criação de um filtro por série/imei para localizar aparelhos que tenham perdido sua identificação ou até mesmo se a uma violação na etiqueta do produto.
> 
> * Assim como os campos **MARCA, MODELO e DESCRIÇÃO** também talvez poderiam ser um campos específicos de cadastro de forma a associar cada marca ao seu modelo e também contendo um descrição
> 
> **Marca**: _Samsung_
> **Modelo**: _UN32j4300AG_ - ao digitar um modelo já cadastrado é exibido sua descrição
> **Descrição**: _Smart TV_
> 
> ==> _**Caso o modelo não tenha sido cadastrado é solicitado o cadastro no momento da abertura da OS**_
> 
> Um cadastro rápido informando apenas as informações de marca, modelo, descrição e qual a linha que esse aparelho pertence.
> 
> -E para agilizar o processo as informações digitadas no momento do cadastro da OS ja podem ser aproveitadas para o preenchimento do cadastro da marca cabendo ao usuário realizar somente as correções necessárias.
> 
> --Estas opções facilitaria a criação de novos filtros e gráficos e relatórios para uma melhor visualização quando há na assistência a possibilidade de reparo de produtos de diversas linhas. Isso também pode evitar a digitação incorreta do modelo.

Eu fiz esses campos IMEI   CÓDIGO e outros 
Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by vampiricxx** [comment]
https://github.com/ visaotec eu estou interesado amigo se me poder me poder me explicar como fez 
Meu e-mail vampiricx30@gmail.com
Obrigado
