### ISSUE TITLE
Solicitacao de recurso Relatorio de vendas

### ISSUE THREAD

**Issue by suzannaMoura** [RamonSilva20/mapos#1005]
Gianluca,ou aos demais.bom dia, estou precisando de algumas melhorias no relatório  "vendas" o mesmo não soma no final, nem esta em {real $} pfvr poderia colocar?

se possivel disponibiulizar em excel tbm por gentileza .

Suzanna Moura.

**Comment by Pr3d4dor** [comment]
@suzannaMoura Obrigado pela sugestão, iremos implementar assim que possível.
