### ISSUE TITLE
Incluir Categorias Serviços

### ISSUE THREAD

**Issue by luiscadeira** [RamonSilva20/mapos#1007]
A possibilidade de colocar Categorias no serviços.
Em um relatórios ou gráfico, fica melhor saber qual categoria foi mas vendida no mês ou ano.

**Comment by Pr3d4dor** [comment]
@luiscadeira Obrigado pela sugestão, mas não acho que essa funcionalidade iria ser tanto utilizada, mas talvez iremos implementar no futuro.

**Comment by visaotec** [comment]
> A possibilidade de colocar Categorias no serviços.
> Em um relatórios ou gráfico, fica melhor saber qual categoria foi mas vendida no mês ou ano.

Eu criei essa categoria e subcategoria em produtos
Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by cgarrotti** [comment]
> > A possibilidade de colocar Categorias no serviços.
> > Em um relatórios ou gráfico, fica melhor saber qual categoria foi mas vendida no mês ou ano.
> 
> Eu criei essa categoria e subcategoria em produtos
> Quem quiser testar o sistema segue o link e usuário e senha abaixo
> https://nacionalsistemas.000webhostapp.com/index.php/login
> usuário: [convidado@gmail.com](mailto:convidado@gmail.com)
> Senha: 123456
> abraços

Ficou top em amigo ! Parabéns
