### ISSUE TITLE
Rede Social

### ISSUE THREAD

**Issue by luiscadeira** [RamonSilva20/mapos#1008]
Seria legal coloca no emitente campos para rede social.
Qual imprimir OS, aparecerá no topo.

Site
Facebook
Instagram
Google
LinkedIn

Etc.

**Comment by Pr3d4dor** [comment]
@luiscadeira Obrigado pela sugestão, mas sendo bem sincero eu não acho essa funcionalidade tão útil.

**Comment by jsfachini** [comment]
> Seria legal coloca no emitente campos para rede social.
> Qual imprimir OS, aparecerá no topo.
> 
> Site
> Facebook
> Instagram
> Google
> LinkedIn
> 
> Etc.

eu coloquei na minha logo esses dados, aparece muito bem após imprimir
