### ISSUE TITLE
Erro ao tentar gerar qualquer relatório, desde financeiro, produto e todos os outro.

### ISSUE THREAD

**Issue by WBV-CWB** [RamonSilva20/mapos#1011]
Opa, tudo bem ?

toda vez que tento gerar um relatório ( seja financeiro, produto, os ou seja qual for.)

da o seguinte erro:

![Screen Shot 2020-10-19 at 11 07 16](https://user-images.githubusercontent.com/70992721/96462116-95a4c880-11fb-11eb-86f0-7cb52062912a.png)

Alguém tem uma solução para tal ?

OBS: HOSPEDAGEM É DA HOSTGATOR

OBRIGADO ^^

**Comment by visaotec** [comment]
> Opa, tudo bem ?
> 
> toda vez que tento gerar um relatório ( seja financeiro, produto, os ou seja qual for.)
> 
> da o seguinte erro:
> 
> ![Screen Shot 2020-10-19 at 11 07 16](https://user-images.githubusercontent.com/70992721/96462116-95a4c880-11fb-11eb-86f0-7cb52062912a.png)
> 
> Alguém tem uma solução para tal ?
> 
> OBS: HOSPEDAGEM É DA HOSTGATOR
> 
> OBRIGADO ^^

Bom dia,
isso já aconteceu comigo e eu resolvi carregando uma nova imagem em emitente .... caso seu servidor não permita, é possível fazer direto pelo mando de dados, outra coisa olha a versão do seu PHP da sua Hospedagem... se a versão for antiga.... dá esse erro também.
abraços

**Comment by WBV-CWB** [comment]
> > Opa, tudo bem ?
> > toda vez que tento gerar um relatório ( seja financeiro, produto, os ou seja qual for.)
> > da o seguinte erro:
> > ![Screen Shot 2020-10-19 at 11 07 16](https://user-images.githubusercontent.com/70992721/96462116-95a4c880-11fb-11eb-86f0-7cb52062912a.png)
> > Alguém tem uma solução para tal ?
> > OBS: HOSPEDAGEM É DA HOSTGATOR
> > OBRIGADO ^^
> 
> Bom dia,
> isso já aconteceu comigo e eu resolvi carregando uma nova imagem em emitente .... caso seu servidor não permita, é possível fazer direto pelo banco de dados, outra coisa olha a versão do seu PHP da sua Hospedagem... se a versão for antiga.... dá esse erro também.
> abraços

Cara, obrigado era a logo, estranho, fui no emitente e a logo não tava lá, mas na OS saia... ai troquei resolveu mesmo haha, obrigado ^^
