### ISSUE TITLE
Qual CSS é responsavel para baixar essa parte do menu?

### ISSUE THREAD

**Issue by WBV-CWB** [RamonSilva20/mapos#1012]
Alguém sabe qual arquivo que tenho que editar para aumentar o local da outra logo dento do sistema?

a minha ficou assim:

![Screen Shot 2020-10-19 at 18 35 57](https://user-images.githubusercontent.com/70992721/96515124-277ff600-123b-11eb-85c8-42b0ba5d6724.png)

**Comment by visaotec** [comment]
> Alguém sabe qual arquivo que tenho que editar para aumentar o local da outra logo dento do sistema?
> 
> a minha ficou assim:
> 
> ![Screen Shot 2020-10-19 at 18 35 57](https://user-images.githubusercontent.com/70992721/96515124-277ff600-123b-11eb-85c8-42b0ba5d6724.png)

Uma parte está no matrix-style.css outra parte no matrix-media.css
clica encima do menu e com o botão direito vai em inspecionar, daí você vai ver certinho qual css alterar
abraços
