### ISSUE TITLE
Consigo rodar varios dockers do mapos ?

### ISSUE THREAD

**Issue by cgarrotti** [RamonSilva20/mapos#1013]
Eu consigo em meu servidor da Oracle (Free Tier) rodar varios dockers do mapos ? Por exemplo para cada cliente meu, estou pensando em usar um docker

**Comment by Pr3d4dor** [comment]
@cgarrotti Consegue sim, mas cada docker teria que rodar em uma porta diferente e conectar à um banco de dados diferente.

**Comment by cgarrotti** [comment]
> @cgarrotti Consegue sim, mas cada docker teria que rodar em uma porta diferente e conectar à um banco de dados diferente.

Você tem um exemplo amigo ? Eu sou novo nesse mundo do docker

**Comment by Pr3d4dor** [comment]
@cgarrotti Você já está rodando o mapos no docker?

**Comment by cgarrotti** [comment]
> @cgarrotti Você já está rodando o mapos no docker?

Então, eu tentei rodar do docker-compose up --force-recreate deu o erro:
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

Na minha náquina eu tenho rodando o apache
