### ISSUE TITLE
Migração para o tipo de Banco SqlServer (PDO)

### ISSUE THREAD

**Issue by gambiarraweb1** [RamonSilva20/mapos#1014]
Boa tarde, Fiz algumas edições no conteudo para preparar o ambiente para uma Oficina Mecânica.
Já tenho cliente com mais de 1(carro(s)), também há edições em faturamento e etc. tudo funcional.
porém utilizo outras aplicações (api) , que usam SqlServer, e gostaria se possível uma ajuda para migrar o do_install para SqlServer, eu cheguei a fazer o script que cria todas tabelas igual ao mapos, e implementei o PDO no inicio da instalçaõ validando se o drive existe (settings.json) e ele cria as tabelas no banco normalmente, porém não avança para a tela de finalização (finished.php) não conseguir descobrir o motivo.
mesmo ele dando 'sucess' no modo debug (F12).
então gostaria de saber se é viavel a vocês no instalador a escolha de um tipo de banco de dados ou um auxilio de como eu posso prosseguir para fazer tal alteração.
já tenho alguns scripts que após seus updates eu migro as 'alterações' que não impactam no meu ambiente.

então se você me auxiliar não vou perder o conteudo após updates.

e caso precisem de ajudar com o pdo, após a criação e inicio dessa feature eu posso enviar algumas melhorias (PR).

Obrigado.

**Comment by visaotec** [comment]
> Boa tarde, Fiz algumas edições no conteudo para preparar o ambiente para uma Oficina Mecânica.
> Já tenho cliente com mais de 1(carro(s)), também há edições em faturamento e etc. tudo funcional.
> porém utilizo outras aplicações (api) , que usam SqlServer, e gostaria se possível uma ajuda para migrar o do_install para SqlServer, eu cheguei a fazer o script que cria todas tabelas igual ao mapos, e implementei o PDO no inicio da instalçaõ validando se o drive existe (settings.json) e ele cria as tabelas no banco normalmente, porém não avança para a tela de finalização (finished.php) não conseguir descobrir o motivo.
> mesmo ele dando 'sucess' no modo debug (F12).
> então gostaria de saber se é viavel a vocês no instalador a escolha de um tipo de banco de dados ou um auxilio de como eu posso prosseguir para fazer tal alteração.
> já tenho alguns scripts que após seus updates eu migro as 'alterações' que não impactam no meu ambiente.
> 
> então se você me auxiliar não vou perder o conteudo após updates.
> 
> e caso precisem de ajudar com o pdo, após a criação e inicio dessa feature eu posso enviar algumas melhorias (PR).
> 
> Obrigado.

Dê uma olhada nesse artigo... quem sabe irá te ajudar.
https://www.devmedia.com.br/usando-pdo-php-data-objects-para-aumentar-a-produtividade/28446
abraços
