### ISSUE TITLE
Extensão cURL não encontrada na Pré-instalação.

### ISSUE THREAD

**Issue by cezargf** [RamonSilva20/mapos#1017]
Olá! Primeiramente, gostaria de agradecer e parabenizar os colaboradores do projeto MAPOS.

** Bug **
Na tela de Pré-instalação, a extensão cURL do PHP é apresenta como "Off".

![image](https://user-images.githubusercontent.com/25113573/96627273-007efe00-12e7-11eb-88cb-577eb0c17c25.png)

Perdão se eu estiver errado, mas parece estar habilitada e funcionando.
![image](https://user-images.githubusercontent.com/25113573/96627462-44720300-12e7-11eb-8d82-cf971c16c238.png)

Alguém pode me ajudar?

**Comment by Pr3d4dor** [comment]
@cezargf A extensão curl está habilitada no seu PHP no modo terminal (php-cli), porém também é necessário ativar ela no seu webserver (apache, nginx, outros).

**Comment by cezargf** [comment]
E você sabe como posso ativar ela no Apache?

Não consigo encontrar a forma de fazer isso.
