### ISSUE TITLE
CRONOGRAMA DE OS

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#1018]
galera, seguinto. O sistema esta sendo usando para gerenciar OS de uma Empreeitera, então tenho serviços com data de inicio e final do mesmo. Ja criei a aba de "cronograma", calendário instalado e TUDO OK. ou quase.
Quero puxar os SERVIÇOS somente daquela OS (tabela servicos_os), segue o codigo que eu montei.

CONTROLLER
--------------------------------------------------------------------------------------
`    public function calendario()
    {
        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vOs')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para visualizar O.S.');
            redirect(base_url());
        }

        $status = $this->input->get('status') ?: null;
        $start = $this->input->get('start') ?: null;
        $end = $this->input->get('end') ?: null;
        $idOs = $this->uri->segment(3);

        $allOs = $this->os_model->calendario($start,$end,$status,$idOs);

        $events = array_map(function ($os) {
            return [
                'title' => "OS: {$os->idOs}, Cliente: {$os->nomeCliente}",
                'start' => $os->dataFinal,
                'end' => $os->dataFinal,
                'extendedProps' => [
                    'id' => '<b>OS:</b> ' . $os->idOs,
                    'cliente' => '<b>Cliente:</b> ' . $os->nomeCliente,
                    'dataInicial' => '<b>Data Inicial:</b> ' . $os->dataInicial,
                    'dataFinal' => '<b>Data Final:</b> ' . $os->dataFinal,
                    'garantia' => '<b>Garantia:</b> ' . $os->garantia,
                    'status' => '<b>Status da OS:</b> ' . $os->status,
                    'description' => '<b>Descrição/Produto:</b> ' . $os->descricaoProduto,
                    'defeito' => '<b>Defeito:</b> ' . $os->defeito,
                    'observacoes' => '<b>Observações:</b> ' . $os->observacoes,
                    'total' => '<b>Valor Total:</b> R$ ' . number_format($os->totalProdutos + $os->totalServicos, 2, ',', '.'),
                    'valorFaturado' => '<b>Valor Faturado:</b> R$ ' . number_format($os->valorTotal, 2, ',', '.'),
                ]
            ];
        }, $allOs);

        return $this->output
            ->set_content_type('application/json')
            ->set_status_header(200)
            ->set_output(json_encode($events));
    }`
--------------------------------------------------------------------------------------

OS MODEL
--------------------------------------------------------------------------------------
`    public function calendario($start, $end, $status = null, $idOs)
    {
        $this->db->select('servicos_os.*');
        $this->db->from('servicos_os');
        $this->db->join('servicos', 'servicos.idServicos = servicos_os.servicos_id');
        $this->db->where('servicos_os.os_id =', $idOs);
        $this->db->where('servicos_os.dataFinal >=', $start);
        $this->db->where('servicos_os.dataFinal <=', $end);

        if (!empty($status)) {
            $this->db->where('servicos_os.situacaoServico_os', $status);
        }

        return $this->db->get()->result();
    }`
--------------------------------------------------------------------------------------

EDITAR OS (JS do calendário)
--------------------------------------------------------------------------------------
`        /*CALENDÁRIO START*/
        var srcCalendarEl = document.getElementById('source-calendar');
        var srcCalendar = new FullCalendar.Calendar(srcCalendarEl, {
            initialView: 'listWeek',
            headerToolbar: {
                start: 'today prev,next', // normalmente estará à esquerda. se RTL, estará à direita
                center: 'title', // botões para alternar entre as visualizações
                end: '' // normalmente estará à direita. se RTL, estará à esquerda         
            },
            views: {
            timeGridFourDay: {
                type: 'timeGrid',
                duration: { days: 7 },
                buttonText: 'Semana'
                }
            },
            themeSystem: 'bootstrap',
            locale: 'pt-br',
            height: 500,
            editable: true,
            selectable: true,
            businessHours: {
                daysOfWeek: [ 1, 2, 3, 4, 5, 6 ], // Segunda-feira até sábado
                startTime: '08:00', // um horário de início (8h neste exemplo)
                endTime: '18:00', // an end time (6pm in this example)
            },
            dayMaxEvents: true, // permitir link "mais" quando muitos eventos
            displayEventTime: true,
            events: {
                url: "<?= base_url() . "index.php/os/calendario"; ?>",
                method: 'GET',
                extraParams: function() { // uma função que retorna um objeto
                    return {
                        status: $("#statusOsGet").val(),
                    };
                },
                failure: function() {
                    alert('Falha ao buscar OS de calendário!');
                },
            },
            eventClick: function(info) {
                var eventObj = info.event.extendedProps;
                $('#modalId').html(eventObj.id);
                $('#modalCliente').html(eventObj.cliente);
                $('#modalDataInicial').html(eventObj.dataInicial);
                $('#modalDataFinal').html(eventObj.dataFinal);
                $('#modalGarantia').html(eventObj.garantia);
                $('#modalStatus').html(eventObj.status);
                $('#modalDescription').html(eventObj.description);
                $('#modalDefeito').html(eventObj.defeito);
                $('#modalObservacoes').html(eventObj.observacoes);
                $('#modalTotal').html(eventObj.total);
                $('#modalValorFaturado').html(eventObj.valorFaturado);

                $('#eventUrl').attr('href', event.url);
                $('#calendarModal').modal();
            },
        });

        srcCalendar.render();

        $('#btn-calendar').on('click', function() {
            srcCalendar.refetchEvents();
        });
        /*CALENDÁRIO END*/`

Oq eu to fazendo de errado? Ele não apresenta erro, antes mostrava "falha ao carregar". 
Agora apenas não trás os serviços da OS. 
--------------------------------------------------------------------------------------
PRINT da tela de editar serviço
--------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/68172360/96802601-9185d000-13e0-11eb-84f3-c98868b0f4cd.png)

**Comment by Pr3d4dor** [comment]
@monutb91 Fica um pouco difícil olhar o código dessa maneira, poderia colocar em outro repositório do GitHub e compartilhar?

**Comment by monutb91** [comment]
> 
> 
> @monutb91 Fica um pouco difícil olhar o código dessa maneira, poderia colocar em outro repositório do GitHub e compartilhar?

Desculpa a ignorancia mas pouco uso a plataforma aqui, então não sei como fazer isso ^^"
pode compartilhar email? ai encaminho, se for o caso.
