### ISSUE TITLE
vendas

### ISSUE THREAD

**Issue by suzannaMoura** [RamonSilva20/mapos#1019]
Bom diaaaaa,

no local onde se cadastra uma venda eu queria uma opção pra buscar uma venda retroativa, pois as vezes, quero buscar uma venda antiga e tenho que ficar voltando e as vezes demora, outra coisa o novo campo de observacao nao ficou muito intuitivo, seria possivel colocar apenas 1 campo de observacao dentro da opcao "faturar" pq ali colocava uma breve observacao, ficaria ate mais clean...

Muito obrigada Gianluca !

**Comment by visaotec** [comment]
> Bom diaaaaa,
> 
> no local onde se cadastra uma venda eu queria uma opção pra buscar uma venda retroativa, pois as vezes, quero buscar uma venda antiga e tenho que ficar voltando e as vezes demora, outra coisa o novo campo de observacao nao ficou muito intuitivo, seria possivel colocar apenas 1 campo de observacao dentro da opcao "faturar" pq ali colocava uma breve observacao, ficaria ate mais clean...
> 
> Muito obrigada Gianluca !

Olá tudo bem!
Sobre pesquisar a venda isso já pode ser feito encima no top no campo pesquisa, basta digitar o nome do Cliente ou o CPF do mesmo.
agora o campo Observação e outras modificações eu fiz no meu sistema, caso queira conferir como ficou.

Eu fiz esses campos OBSERVAÇOES, IMEI, CÓDIGO e outros
Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by robsoncrv** [comment]
> > Bom diaaaaa,
> > no local onde se cadastra uma venda eu queria uma opção pra buscar uma venda retroativa, pois as vezes, quero buscar uma venda antiga e tenho que ficar voltando e as vezes demora, outra coisa o novo campo de observacao nao ficou muito intuitivo, seria possivel colocar apenas 1 campo de observacao dentro da opcao "faturar" pq ali colocava uma breve observacao, ficaria ate mais clean...
> > Muito obrigada Gianluca !
> 
> Olá tudo bem!
> Sobre pesquisar a venda isso já pode ser feito encima no top no campo pesquisa, basta digitar o nome do Cliente ou o três primeiros números CPF do mesmo.
> agora o campo Observação e outras modificações eu fiz no meu sistema, caso queira conferir como ficou.
> 
> Eu fiz esses campos OBSERVAÇOES, IMEI, CÓDIGO e outros
> Quem quiser testar o sistema segue o link e usuário e senha abaixo
> https://nacionalsistemas.000webhostapp.com/index.php/login
> usuário: [convidado@gmail.com](mailto:convidado@gmail.com)
> Senha: 123456
> abraços
estas
Boa tarde.
Gostei da modificação que fez em produtos, criando categorias, subcategorias e etc. Como eu poderia ter modificações?

**Comment by visaotec** [comment]
> > > Bom diaaaaa,
> > > no local onde se cadastra uma venda eu queria uma opção pra buscar uma venda retroativa, pois as vezes, quero buscar uma venda antiga e tenho que ficar voltando e as vezes demora, outra coisa o novo campo de observacao nao ficou muito intuitivo, seria possivel colocar apenas 1 campo de observacao dentro da opcao "faturar" pq ali colocava uma breve observacao, ficaria ate mais clean...
> > > Muito obrigada Gianluca !
> > 
> > 
> > Olá tudo bem!
> > Sobre pesquisar a venda isso já pode ser feito encima no top no campo pesquisa, basta digitar o nome do Cliente ou o três primeiros números CPF do mesmo.
> > agora o campo Observação e outras modificações eu fiz no meu sistema, caso queira conferir como ficou.
> > Eu fiz esses campos OBSERVAÇOES, IMEI, CÓDIGO e outros
> > Quem quiser testar o sistema segue o link e usuário e senha abaixo
> > https://nacionalsistemas.000webhostapp.com/index.php/login
> > usuário: [convidado@gmail.com](mailto:convidado@gmail.com)
> > Senha: 123456
> > abraços
> > estas
> > Boa tarde.
> > Gostei da modificação que fez em produtos, criando categorias, subcategorias e etc. Como eu poderia ter modificações?

entre em contato: visaotec.com@gmail.com

**Comment by Pr3d4dor** [comment]
@suzannaMoura A pesquisa pode ser feita como o @robsoncrv comentou, porém a parte das observações já não pode ser desfeita, pois foi uma contribuição da comunidade. Mas poderia explicar melhor o que não ficou claro?
