### ISSUE TITLE
Área de Compras

### ISSUE THREAD

**Issue by robsoncrv** [RamonSilva20/mapos#1020]
Boa tarde.
Primeiramente, agradeçer as pessoas envolvidas no sistema, ele é ótimo e me fez migrar para o mesmo.

Eu gostaria que tivesse a opção de entrada de mercadoria, com os produtos, fornecedor e preço que foi pago.
Com a nota fiscal de compra na mão, fazendo a entrada no sistema das mercadorias e o sistema atualizando o estoque.

Seria interessante esta função, assim teria mais controle financeiro.

**Comment by Pr3d4dor** [comment]
@robsoncrv Obrigado pela sugestão, iremos implementar assim que possível. Porém gostaria que se possível que você desse mais detalhes sobre o funcionamento dessa funcionalidade.

**Comment by robsoncrv** [comment]
@Pr3d4dor Eu usava um sistema comercial que tem a área de compras, onde além do controle financeiro integrado, ou seja, já envia os valores pagos para o financeiro, faz a entrada de mercadoria no estoque atualizando inclusive os valores de venda com base nos valores de compras. Ainda nesta seção há também o cadastro de fornecedores, onde é possível também ter o controle  de "quem" estamos comprando tal mercadoria.
![image](https://user-images.githubusercontent.com/73442647/97435112-c329fa00-18fe-11eb-9c0f-26bf1531be7d.png)

**Comment by robsoncrv** [comment]
Basicamente a mesma tela para a venda de mercadorias, porém ela faz a entrada de mercadoria e os lançamentos no caixa

**Comment by octaralves** [comment]
* Seria interessante seguir com modelo de importação xml.
* Existe recurso no php para fazer a leitura do arquivo xml onde e possível identificar todos os dados de: fornecedor, destinatário, produtos , opções de faturamento, transportadora.
* Tenho um exemplo disso fazendo a leitura e retornando os dados filtrados.
