### ISSUE TITLE
Não grava no banco de dados ( MODIFICANDO O MAPOS, UMA AJUDA.)

### ISSUE THREAD

**Issue by WBV-CWB** [RamonSilva20/mapos#1022]
Fala Pessoal, estou add algumas coisa que queria no MAPOS para meu uso.

Bom, estou tentando add duas colunas, mas não salva no BD ... não sei se tem algum arquivo a mais para modificar e gravar no BD, se alguém puder me ajudar... eu agradeço, essa é a imagem do que estou tentando fazer:

![Screen Shot 2020-10-26 at 01 16 09](https://user-images.githubusercontent.com/70992721/97133462-ed29c380-1728-11eb-8fc0-b6eded2eb134.png)

bom, agradeço, vou deixar abaixo o código como está:

/var/www/html/mapos-master4/application/config/form_validation.php:
235      [
236           'field' => 'tipodeproduto',
237            'label' => 'TipoProduto',
238            'rules' => 'trim',
239        ],

/var/www/html/mapos-master4/application/views/os/adicionarOs.php:

![Screen Shot 2020-10-26 at 01 21 11](https://user-images.githubusercontent.com/70992721/97133680-92449c00-1729-11eb-8ce1-d6e06f05888c.png)

                                                
/var/www/html/mapos-master4/application/views/os/editarOs.php:

![Screen Shot 2020-10-26 at 01 19 33](https://user-images.githubusercontent.com/70992721/97133601-54e00e80-1729-11eb-846f-919f08c83076.png)

Deixei uma imagem que não posso postar o código -.-'... 

Agradeço desde já.

**Comment by marquinhomaquinas** [comment]
Boa tarde, vc adicionou uma tabela no banco de dados ou já esta utilizando uma tabela existente no banco, pois parece que esta tentando gravar em status, mas o programa já esta usando essa tabela.
Pois se não tiver a tabela ou campo, não vai gravar.

**Comment by Pr3d4dor** [comment]
@WBV-CWB Você tem que adicionar as novas colunas na tabela do banco de dados, senão não vai salvar mesmo.

**Comment by WBV-CWB** [comment]
> @WBV-CWB Você tem que adicionar as novas colunas na tabela do banco de dados, senão não vai salvar mesmo.

Já add sim olha:


![Screen Shot 2020-10-26 at 18 46 57](https://user-images.githubusercontent.com/70992721/97232369-c7013380-17bb-11eb-84c4-2a41ebec6a91.png)

**Comment by Pr3d4dor** [comment]
@WBV-CWB Você precisa adicionar o campo no array `data` para que ele consiga salvar no banco: https://github.com/RamonSilva20/mapos/blob/0cbd463a8b756418a8404580e8e903f7327b0097/application/controllers/Os.php#L218

**Comment by WBV-CWB** [comment]
> $data = [

Mesmo assim não foi olha:

![Screen Shot 2020-10-26 at 18 58 47](https://user-images.githubusercontent.com/70992721/97233243-67a42300-17bd-11eb-967b-5f9765c319e6.png)



O código ficou assim lá:

![Screen Shot 2020-10-26 at 18 59 10](https://user-images.githubusercontent.com/70992721/97233256-6ffc5e00-17bd-11eb-913c-1d8d0ba041cd.png)

**Comment by Pr3d4dor** [comment]
@WBV-CWB Você precisa também adicionar o campo no método adicionar() se ele estiver presente na primeira tela de adicionar OS.

**Comment by WBV-CWB** [comment]
> @WBV-CWB Você precisa também adicionar o campo no método adicionar() se ele estiver presente na primeira tela de adicionar OS.


Agora foi sim, obrigado e desculpa a ignorância aqui haha, mas não mexo com anda de programação a tempos, ai to me batendo para entender algumas coisas.


Só uma ultima duvida antes de fechar a issue, cara não consigo tirar aquele... azul das opções quando vocÊ passa o mouse, que tentei achar  e não achei em lugar algum...

ai já fecho a ISSUE... MAS OBRIGADO POR TUDO ^^



![Screen Shot 2020-10-26 at 19 25 42](https://user-images.githubusercontent.com/70992721/97235212-26ae0d80-17c1-11eb-8172-ef57dd6f7ad1.png)

**Comment by Pr3d4dor** [comment]
@WBV-CWB No arquivo `matrix-media.css` na linha 19.

**Comment by WBV-CWB** [comment]
> @WBV-CWB No arquivo `matrix-media.css` na linha 19.

Vlw ... vou ver aqui, só para saber é o meu editor ou esse arquivo  bootstrap.min.css é dessa forma mesmo O,O

![Screen Shot 2020-10-26 at 20 39 05](https://user-images.githubusercontent.com/70992721/97239972-b658b980-17cb-11eb-8361-9a9b048bc986.png)


Porque pelo que vi tenho que add umas linhas ali para deixar alinhado as caixas, né?

![Screen Shot 2020-10-26 at 20 34 21](https://user-images.githubusercontent.com/70992721/97239997-ca042000-17cb-11eb-8965-84324cc273cb.png)

**Comment by Pr3d4dor** [comment]
@WBV-CWB Acho que você abrir o arquivo errado, é o matrix-media.css, não boostrap. Você abriu o arquivo minificado que é o css em uma linha só.

**Comment by WBV-CWB** [comment]
> @WBV-CWB Acho que você abrir o arquivo errado, é o matrix-media.css, não boostrap. Você abriu o arquivo minificado que é o css em uma linha só.


cara, não consegui mesmo, sempre que tento acha essas opções para movimentar ali eu caio nesse botstrapp, até ali no no inject do google ele identifica isso .

![Screen Shot 2020-10-27 at 21 22 59](https://user-images.githubusercontent.com/70992721/97376007-05215480-189b-11eb-9e45-8347dc1a5633.png)


Tentei movimentar pela div ele direto, tirando essa class span, mas ai não consegui fazer...


o outro do mouse também, mudei lá no No arquivo matrix-media.css na linha 19. e continua azul quando passo o mouse... 

mas agora só queria saber como mudar a posição ali das caixas, pois sempre que movo ele move todas de uma só vez =/ se alguém souber como eu agradeço a resposta.... =/
