### ISSUE TITLE
Como rodar o MAPOS para multi locatários ? (Multi Tenancy)

### ISSUE THREAD

**Issue by cgarrotti** [RamonSilva20/mapos#1023]
Pessoal,
Tem como rodar o MAPOS para multi locatários ? (Multi Tenancy)

Att

Charles

**Comment by Pr3d4dor** [comment]
@cgarrotti Nativamente isso não é suportado pelo mapos, o que você terá que fazer é instalar vários mapos no seu servidor e configurar o subdomínio de cada Tenant você mesmo.

**Comment by monutb91** [comment]
E se colocar um select ou um campo no inicio para escolher o nome do "locatario/empresa" e ai inserir os dados de login?
Ai verifica primeiro o dominio e depois o longin ... Estive pensando tbm em como fazer para varios locatarios ... nao escrevi nada ainda mas essa foi a minha logica ^^"

**Comment by cgarrotti** [comment]
> E se colocar um select ou um campo no inicio para escolher o nome do "locatario/empresa" e ai inserir os dados de login?
> Ai verifica primeiro o dominio e depois o longin ... Estive pensando tbm em como fazer para varios locatarios ... nao escrevi nada ainda mas essa foi a minha logica ^^"

Eu pensei em algo assim tb, fazer um tabela de que contenham os usuarios e suas bases, e ai ao logar usando essa tabela de usuarios, ele pegaria o database para esse usuario logado e o usario como base de trabalho, tentei fazer, mas gerou muitos erros

**Comment by seitbnao** [comment]
@cgarrotti, @monutb91 
https://github.com/seitbnao/mapos/tree/mapos_multiusuario
