### ISSUE TITLE
Impossível cadastrar Serviço com valor 0,00 na OS.

### ISSUE THREAD

**Issue by edvaldo-feitosa** [RamonSilva20/mapos#1024]
Ambiente servidor:
   Hardware é uma VPS remota com 2 núcleos de processador, 1GB de RAM e SSD de 40GB.
   Sistema Operacional Debian 9.13
   Banco de dados Mariadb 10.1.47
   Apache2 2.4.25
   PHP 7.3
   Mapos 4.18.1 (instalado via composer)

Ambiente cliente:
   Sistema operacional Ubuntu 20
   Navegador Google Chrome 86.0.4240.111

Obs.: - Sistema Mapos esta plenamente funcional em outras operações testadas até o momento.
          - Foram cadastrados apenas 1 cliente, 2 serviços (um com valor 0,00) e o emitente.

Cadastrei uma OS com um item de serviço com valor > 0,00 e funcionou.

Ao tentar cadastrar um outro item de serviço com valor = 0,00, recebo um pop-up de erro conforme o link:

https://user-images.githubusercontent.com/73499632/97228641-f7de6a00-17b5-11eb-9797-1f04ed07db75.png

Entendo que não há transgressão à integridade de dados ao permitir um item de serviço na OS com valor 0,00.
Penso que em situações peculiares é necessária a existência dessa abertura.

Obrigado,
Edvaldo.

**Comment by Pr3d4dor** [comment]
@edvaldo-feitosa Não é um bug pois o serviços não podem ter valor 0. O bug que existe é ter deixado adicionar o primeiro serviço com valor 0.

**Comment by edvaldo-feitosa** [comment]
Olá Gianluca.
Obrigado pela resposta.
Entendo que uma empresa decide se é permitido ou não um serviço com valor 0.
Sei que parece incoerente, mas penso que posso sim, por minha deliberação como gestor, definir qualquer valor para os serviços.
Pense numa situação em que, numa OS, cadastro vários serviços mas não quero, ou não consigo detalhar ou ratear o valor pra cada um, embora queira listar um a um na OS. Poderia, então, listar todos os serviços na OS mas em apenas um deles especificar um valor correspondente ao total de todos os serviços.
Desculpe a insistência e a longa mensagem mas não vejo que permitir serviços com valor 0 crie alguma "aberração" na integridade do sistema. Ao contrário, quanto menos amarrado, mais ágil e útil o sistema fica. Claro que algumas consistências devem ser preservadas e são inevitáveis.
Mais uma vez agradeço a resposta e espero estar contribuindo pra melhorar o Mapos que vem se elevando a cada dia no meu conceito, embora no momento esteja apenas fazendo avaliações na intenção de adota-lo.
Abraço a todos e meus parabéns pela iniciativa.

**Comment by Pr3d4dor** [comment]
@edvaldo-feitosa Certo, eu posso fazer um ajuste para permitir qualquer valor (incluindo 0), porém bloqueando valores negativos.

**Comment by edvaldo-feitosa** [comment]
Obrigado pela compreensão.
Concordo com bloquear valores negativos. De fato, não fazem sentido em nenhuma situação prática.

Abraço a toda a equipe.
