### ISSUE TITLE
Inserir produto ou serviço na OS por código

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1026]
Boa noite, seria possível incluir na ordem de serviço um campo para poder adicionar tanto produto quanto serviço pelo código deles?
digamos que **formatação notebook** seja o código **34**
e **SSD 240gb** seja o código **98**

Na hora de inserir esses produtos hj você tem que escrever, 
e no caso se tivesse um campo para por o código, só bastava inserir ele 
que já "puxava" o referente.

obrigado e boa noite a todos.

**Comment by visaotec** [comment]
> Boa noite, seria possível incluir na ordem de serviço um campo para poder adicionar tanto produto quanto serviço pelo código deles?
> digamos que **formatação notebook** seja o código **34**
> e **SSD 240gb** seja o código **98**
> 
> Na hora de inserir esses produtos hj você tem que escrever,
> e no caso se tivesse um campo para por o código, só bastava inserir ele
> que já "puxava" o referente.
> 
> obrigado e boa noite a todos.

Olá,
Para inserir o produto na Os, basta você cadastrar o produto com um código de barras, daí só digitar o código no lugar do nome.
Agora pra inserir serviço na Os, só acrescentar um campo  em serviço e puxar ele em Os.
abraços

**Comment by jsfachini** [comment]
ótimo valeu mesmo já me ajudou muito
no produto deu certo da forma que você falou, porem no serviço não tem campo;

detalhe, não manjo de programação

**Comment by jsfachini** [comment]
> Olá,
> Para inserir o produto na Os, basta você cadastrar o produto com um código de barras, daí só digitar o código no lugar do nome.
> Agora pra inserir serviço na Os, só acrescentar um campo tipo código de barras em serviço e puxar ele em Os.
> abraços

ótimo valeu mesmo já me ajudou muito
no produto deu certo da forma que você falou, porem no serviço não tem campo;

detalhe, não manjo de programação

**Comment by jsfachini** [comment]
Em relação ao serviço, 
fiz um teste, coloquei o código junto com o nome do serviço,
quando informo só o código no campo serviço dentro da OS, já adiciona o referente.

por hora agradeço a ajuda @visaotec
