### ISSUE TITLE
Campo Data de Nascimento no cadastro de clientes

### ISSUE THREAD

**Issue by robsoncrv** [RamonSilva20/mapos#1027]
Pessoal, seria muito útil ter o campo de data de nascimento no cadastro de clientes. Seria interessante também, que no calendário estes aniversariantes aparecessem.
Qual a possibilidade de termos este campo?

Percebo, que o sistema esta cada vez mais maduro e quase se tornando um ERP.

**Comment by Pr3d4dor** [comment]
@robsoncrv Sobre ter o campo de data de nascimento nos clientes, sim é possível. Sobre aparecer no calendário eu já julgo que não seria tão útil, pois o calendário é para somente OS.

Pode ser feita uma seção na dashboard com os aniversariantes para que assim seja possível dar uma promoção ou desconto por exemplo.

**Comment by robsoncrv** [comment]
O campo de aniversário eu implementei na minha instalação
Ótima idéia a seção na dashboard. Seria bem útil saber os clientes
aniversariantes.




*Robson Carvalho*

Wazy Tecnologia

+55 42 3277-1026

+55 42 98439-2363

Skype: robson_crv

robson@wazy.com.br

http://wazy.com.br

Avenida Laurindo Barbosa de Macedo, 1629 - Ortigueira - Pr
------------------------------






Em ter., 27 de out. de 2020 às 21:20, Gianluca Bine <
notifications@github.com> escreveu:
