### ISSUE TITLE
Descrição Produto/Serviço

### ISSUE THREAD

**Issue by celsosouzaa** [RamonSilva20/mapos#1028]
Boa noite.

Seria possível incluir na descrição produto/serviços uma caixa de seleção com as opções abaixo?

Conferência Visual :  (  )Arranhado  (  )Mancha de tinta    (  )Quebrado(  )Riscado    (  )Tela danificada    (  )Trincado(  )Amassado   (  )Teclado danificado (  )Oxidado (  )Outros *campo que possa digitar essa informações.

**Comment by Pr3d4dor** [comment]
@celsosouzaa Eu acho que essa modificação é muito específica para assistências de celulares, então acho que não seria bom ter por padrão no mapos (genérico).

Mas podemos te ajudar para customizar o mapos para a sua necessidade específica.
