### ISSUE TITLE
Opção de impressão em 2 vias da OS no A4

### ISSUE THREAD

**Issue by robsoncrv** [RamonSilva20/mapos#1029]
Uma opção que seria muito boa para quem usa o sistema em assistência técnica, seria a impressão da OS em 2 vias. Sendo que a mesma ocuparia uma página A4 com as duas vias. Uma via entrega-se ao cliente para retirar o equipamento e a outra afixamos ao equipamento. Como no antigo sistema que eu usava antes do MAP-OS
![image](https://user-images.githubusercontent.com/73442647/97435597-667b0f00-18ff-11eb-845b-a35ec4cc8ca6.png)

**Comment by jsfachini** [comment]
Ótimo, seria uma boa implantar dessa forma, hoje tenho que imprimir duas OS, uma via para o cliente e outra interna.
poderia ser adicionado um botão para imprimir esse tipo de via junto da OS onde já existe o botão faturar, imprimir A4...
