### ISSUE TITLE
Pagamento parcelado

### ISSUE THREAD

**Issue by wgiacomelli** [RamonSilva20/mapos#103]
Teria alguma forma de não registrar uma OS como paga , mas sim ter opção de 1-Pago, 2-Não Pago, 3-Parcial, para poder registrar o pagamento de parte do valor caso seja necessário o parcelamento.

**Comment by BrunoMichael** [comment]
Prezado bom dia, 

Consegui implementar essa funcionalidade no sistema aqui da seguinte forma.
Primeiro eu criei uma nova tag Faturado Parcial, pois a Faturado já existia, feito isso na função faturar em os, vendas em controllers eu coloquei uma verificação para ver qual opção foi selecionada lá no formulário onde eu coloquei um select option para selecionar se vai faturar total ou parcial. Nisso com a variavel criada lá no option voce faz um if e else para fazer a inserção no banco.

Estou sem tempo por agora, por causa de alguns projetos, vou tentar arrumar um dia para disponibilizar para vocês.

Att,

AwS Bruno

**Comment by wgiacomelli** [comment]
> Teria alguma forma de não registrar uma OS como paga , mas sim ter opção de 1-Pago, 2-Não Pago, 3-Parcial, para poder registrar o pagamento de parte do valor caso seja necessário o parcelamento.

**Comment by wgiacomelli** [comment]
Alguém já conseguiu ajustar essa questão de parcelamento?
