### ISSUE TITLE
Exclusão de Ordem de Serviços e o Valor ainda aparece no Relatório de Receitas

### ISSUE THREAD

**Issue by eduardoleaoinformatica** [RamonSilva20/mapos#1030]
** Descrição do bug **
Gerei algumas ordens de serviços, como instalei para testar o sistema exclui algumas e outras atualizei. As ordens excluídas ainda assim aparecem no relatório financeiro.

**Reprodução**
Gere algumas ordens de serviços, excluía algumas e gere um relatório financeiro. As ordens de serviços excluídas aparecem como receita no relatório

**Comportamento esperado**
Não sei se é erro no meu comportamento, mas eu fiquei em duvida se a ordem tbm não deveria ser exclusa do relatório já que não entrou dinheiro no caixa não teria como contabilizar.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: Hospedado Online - Linux
 - Navegador: Chrome
 - Versão: 4.18.0

** Contexto adicional **
Pode ser que eu esteja errado, mas como não existiu execução do serviço não entraria dinheiro em caixa, o certo seria cancelar a ordem de serviço e retirar a opção de excluir ordem, se a função excluir ordem esta presente teria que apagar da tabela de "lançamentos" do banco de dados automaticamente. Vi que tem a opção de excluir em Financeiro>Lançamentos mas se for um outro tipo de usuário que não seja administrador ele não terá acesso a Lançamentos e excluir a Receita gerada.

**Comment by Pr3d4dor** [comment]
@eduardoleaoinformatica Isso se dá pelo fato de que os lançamentos são salvos em outra tabela `lançamentos`. O que pode ser feito é: ao ser excluído uma OS que esteja faturada, excluir os lançamentos relacionados.

**Comment by iEmersonJr** [comment]
**OPÇÃO APAGAR**
Na nova atualização existe alguma opção para apagar esses valores presente aqui no anexo? 

![image](https://github.com/RamonSilva20/mapos/assets/128086295/4aae64c4-2bb0-4882-8403-995501ad60c4)

Pois, estava testando algumas coisas do financeiro e notei que mesmo apagando eles permanecem, se a resposta for não, por onde consigo apagar/zerar esse relatorio?
