### ISSUE TITLE
Troca de moeda/Gateway SMS/Portal OS para Cliente sem registo

### ISSUE THREAD

**Issue by marcelomartinsIT** [RamonSilva20/mapos#1031]
Boas malta,
Seria possível implementar estas funções?
1) A troca da moeda para €
2) Colocar um gateway de SMS?
3) Portal para consultar OS através do numero da mesma?
Cumprimentos

**Comment by Pr3d4dor** [comment]
@marcelomartinsIT é possível implementar, mas não é tão simples. Sobre a moeda, basta você substituir todos os lugares onde tem R$ por €.

**Comment by marcelomartinsIT** [comment]
Eu não instalei ainda, da para fazer o câmbio por EUR fácil?
Se puder ajudar aí agradeço ;)

O resto das implementações, até acho que o portal do cliente me faz algum sentido sem registo. Nem todo o cliente quer registrar, so consultar.

Obrigado
