### ISSUE TITLE
Indicação de desconto na OS.

### ISSUE THREAD

**Issue by edvaldo-feitosa** [RamonSilva20/mapos#1032]
Durante os testes senti falta da possibilidade de lançamento de um desconto na OS, seja nos serviços e/ou nos produtos.

Creio que seja uma situação bastante comum. Embora possa lançar um valor do serviço/produto com o valor já com o desconto calculado, penso que, pra gestão financeira, seja interessante ter o valor do desconto explícito como um item a mais.

**Comment by robsoncrv** [comment]
Eu iria propor a mesma coisa, mas não só na Ordem de Serviços mas na venda também..
Até porque fica mais transparente para o cliente quando aparece o desconto concedido.

**Comment by jsfachini** [comment]
> Durante os testes senti falta da possibilidade de lançamento de um desconto na OS, seja nos serviços e/ou nos produtos.
> 
> Creio que seja uma situação bastante comum. Embora possa lançar um valor do serviço/produto com o valor já com o desconto calculado, penso que, pra gestão financeira, seja interessante ter o valor do desconto explícito como um item a mais.



Ótima indicação, seria muito bom apresentar na OS e na Venda o desconto concedido.

**Comment by JulianoSavino** [comment]
Acho bem interessante a opção de desconto, quase sempre há negociação na hora do pagamento do produto/serviço. 
Não sei como fica o controle dos demais com relação às taxas de boletos ou cartões, mas eu procuro sempre lançar a venda pelo valor cheio e depois lanço em despesas, os valores cobrados pelo banco (boleto) e pela administradora de cartão, assim sei exatamente o o que entrou. Tento ter o maximo de controle possivel, portanto seria útil, ao menos para quem esse controle, que houvesse uma parte do faturamento que:
* Fosse possível desconto
* Lançamento de taxas diversas, um campo parecido com o da despesa (financeiro). Tipo, um check box que quando marcado, expandisse a janela mostrando os campos de lançamento de:
Descrição
Fornecedor / Empresa
Valor           Data de Vencimento

Ficaria muito pratico

**Comment by giampaulo** [comment]
bahh isso do desconto seria excelente, ja seria hora de ter essa possibilidade no MAPOS, ja foi pedido por diversas vezes em outras issues mas acabou ficando de lado. tenho uns quantos clientes que me perguntam pq nao sai o desconto na OS. acabo escrevendo a mão.
