### ISSUE TITLE
Modificar relatórios

### ISSUE THREAD

**Issue by robsoncrv** [RamonSilva20/mapos#1033]
Pessoal, não sou programador, mas acabo me virando um pouco e consigo fazer várias mudanças no sistema para poder me atender.
Eu gostaria de estar editando alguns relatórios, apenas na parte visual, como fontes, e outras coisas.
Como trabalhar com o código fonte para mim é um pouco complicado, tem alguma ferramenta visual que eu possa usar para fazer estas mudanças? Assim como editar um html no Dreamweaver, tem alguma ferramenta visual para o php?

Se alguém puder ajudar eu fico grato

**Comment by Pr3d4dor** [comment]
@robsoncrv Não conheço nenhuma ferramenta visual que lhe auxilie nisso, você terá mesmo que manipular o HTML para editar os relatórios. Os relatórios são feitos em HTML e CSS e convertidos para PDF. Então você terá que aprender essas tecnologias para realizar as suas adequações.

**Comment by robsoncrv** [comment]
Entendi. Vou pesquisar e procurar aprender um pouco.

Em sáb, 7 de nov de 2020 16:55, Gianluca Bine <notifications@github.com>
escreveu:
