### ISSUE TITLE
espelho de vendas via cliente

### ISSUE THREAD

**Issue by suzannaMoura** [RamonSilva20/mapos#1035]
solicito melhorias no relatório de vendas A4 via cliente, pois o atual tem poucas informações, tenho um exemplo aqui,
acho que essa melhoria seria muito bem vista no sistema pois e uma via cliente, e isso da uma otima visibilidade para o cliente, ja vi umas solicitacoes dessas aqui mais nunca vi exemplos, vou colocar um exemplo que seria muito interessante, muito obrigada pessoa, voces que fazem o mapos sao maravilhoso !
favor se for possivel fazer essa alteração me ajudaria muito de verdade....

![img3D](https://user-images.githubusercontent.com/73032085/98285830-e0f00280-1f81-11eb-8016-ae5939642351.jpg)

**Comment by Pr3d4dor** [comment]
@suzannaMoura Obrigada pelas sugestões, assim que seja possível será implementado, porém os bugs têem prioridades. Também peço um pouco de paciência pois existem outros pedidos de feature na fila.
