### ISSUE TITLE
Botão de busca CNPJ

### ISSUE THREAD

**Issue by robsoncrv** [RamonSilva20/mapos#1036]
Pessoal.
Por padrão o botão BUSCAR INFORMAÇÕES (CNPJ) no formulário de cadastro de clientes, preenche automaticamente o campo "Nome".
Eu criei um campo chamado "razão social" no meu formulário.
Como faço agora para ele seja preenchido com o nome ao invés do campo "nome" ?
![image](https://user-images.githubusercontent.com/73442647/98300485-17387c80-1f98-11eb-8a46-b71b41cef97d.png)

**Comment by Pr3d4dor** [comment]
Verifique a função `buscar_info_cnpj` no arquivo `assets/funcoes.js`, nas linhas 116 à 189.

**Comment by robsoncrv** [comment]
Obrigado, vou fazer isso.

Em sáb, 7 de nov de 2020 17:03, Gianluca Bine <notifications@github.com>
escreveu:
