### ISSUE TITLE
Imprimir garantia junto com o anexo!

### ISSUE THREAD

**Issue by 95jweslley** [RamonSilva20/mapos#1037]
Quando adicionado o anexo na OS, Mostrar o anexo na impressão da garantia! (No caso imagem)

**Comment by Pr3d4dor** [comment]
@95jweslley Obrigado pela sugestão, iremos implementar assim que possível.

**Comment by 95jweslley** [comment]
> Quando adicionado o anexo na OS, Mostrar o anexo na impressão da garantia! (No caso imagem)

É possível?
