### ISSUE TITLE
CAMPO CPF CNPJ

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#1038]
Gostaria de saber como destivar ele para nao ser obrigatório

**Comment by Pr3d4dor** [comment]
Vá no arquivo `form_validation.php` e na linha 13 retire `required`

**Comment by wesley020291** [comment]
Qual o caminho...

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Pr3d4dor** [comment]
`application/config/form_validation.php`

**Comment by gordocosta** [comment]
Também precisa muda o documento \application\views\clientes\adicionarCliente.php linha 130  "required: **false**"

**Comment by wesley020291** [comment]
Fis os 2 procedimentos e nao deu certo. continua exigindo CPF OU CNPJ
________________________________
De: Gianluca Bine <notifications@github.com>
Enviado: sábado, 7 de novembro de 2020 20:18
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: Wesley Oliveira <wesley020291@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] CAMPO CPF CNPJ (#1038)


application/config/form_validation.php

**Comment by wesley020291** [comment]
O campo CPF/CNPJ não é um CPF ou CNPJ válido.
________________________________
De: Luciano Costa <notifications@github.com>
Enviado: segunda-feira, 9 de novembro de 2020 16:25
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: Wesley Oliveira <wesley020291@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] CAMPO CPF CNPJ (#1038)


Também precisa muda o documento \application\views\clientes\adicionarCliente.php linha 130 "required: false"

**Comment by wesley020291** [comment]
BLZ deu certo esclui a linha inteira
________________________________
De: Luciano Costa <notifications@github.com>
Enviado: segunda-feira, 9 de novembro de 2020 16:25
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: Wesley Oliveira <wesley020291@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] CAMPO CPF CNPJ (#1038)


Também precisa muda o documento \application\views\clientes\adicionarCliente.php linha 130 "required: false"
