### ISSUE TITLE
Tem como mudar a composição dos números de telefone? Estou em outro país e precisaria alterar o prefixo do país e tal. Obrigado.

### ISSUE THREAD

**Issue by Sergiong2634** [RamonSilva20/mapos#1040]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Sergiong2634** [comment]
Tem como mudar a composição dos números de telefone? Estou em outro país e precisaria alterar o prefixo do país e tal. Obrigado.

**Comment by Pr3d4dor** [comment]
@Sergiong2634 Onde exatamente que você precisa desse ajuste?

**Comment by Sergiong2634** [comment]
> @Sergiong2634 Onde exatamente que você precisa desse ajuste?

MapOs, precisava de um ajuste geral para cadastro de clientes e tal. Encontrei um arquivo que tinha mask, alterei mas ñ surtiu efeito
