### ISSUE TITLE
Atualização Mapos 4.20.0 Erro ao faturar.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1041]
Bom dia a todos, fiz a atualização do mapos 4.19.0 para 4.20.0 e agora não estou conseguindo faturar. Fiz instalação atualizando e tambem baixando a pasta do sistema novo e não consegui. Alguem mais teve esse problema?

nao consegui achar o logs de erros para colocar aqui.

**Comment by Pr3d4dor** [comment]
@cabralwms Atualizou o banco de dados? Foi adicionado coluna nova na tabela lançamentos

**Comment by cabralwms** [comment]
Muito obrigado meu amigo, eu nao vi esse detalhe grato. Espero que se mais alguem tiver esse problema so ler aqui já vai conseguir resolver. Tenha um otimo dia.
