### ISSUE TITLE
Desconto em % ao faturar uma OS ou Venda

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1042]
Uma bom recurso na hora de faturar uma venda ou OS
Ter opção de um campo de desconto em %
Ex: OS no valor de 100,00
e logo afrente um campo de desconto que vc vai colocar o valor em % do desconto
digamos vc coloque 30% ao clicar em faturar aparece um popup ou janela de confirmação  contendo o novo valor
outra opção seria de na propia os tem um campo de desconto em %%
que ao add um serviço ou produto nas janelas ira aparecer o valor total sem desconto, mas na vizualização geral das OS e na hora de faturar os valores apresentados ja estão deduzidos akela porcentagem

Espero ter conseguido explicar bem

**Comment by Pr3d4dor** [comment]
@hoshikawakun Obrigado pela sugestão, iremos implementar assim que possível.
