### ISSUE TITLE
ERRO AO GERAR RELATORIO EM PDF v4.20.0

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1044]
não consigo gerar nem um tipo de relatório em pdf 

![mapos](https://user-images.githubusercontent.com/31580600/98821473-5fc7be00-240e-11eb-9cd7-21c753908c76.PNG)

porem em xls funciona normal só a ordem q bem meio bagunçada.

testei tento no XAMPP quanto online da o mesmo resultado.

**Comment by Pr3d4dor** [comment]
@marllonferreira Vá em Configurações >> Emitente e atualize a Logo

**Comment by marllonferreira** [comment]
> @marllonferreira Vá em Configurações >> Emitente e atualize a Logo

deu certo valeu amigo

**Comment by zedopicadin** [comment]
Fiz a mudança da imagem e ainda estou tendo esse problema .
