### ISSUE TITLE
Adição de filtro permanente.

### ISSUE THREAD

**Issue by basgelly** [RamonSilva20/mapos#1045]
O sistema esta incrível, super atendeu a minha empresa, porém eu queria solicitar um filtro permanente que eu consiga ver somente as OS em aberto assim que eu logue no sistema e quando eu fosse voltar para a pagina só aparecesse as mesmas. Porque ai facilitaria muito a organização do sistema. 

O ideal é eu conseguir configurar um filtro para cada Login. Por exemplo

Tenho o login Financeiro, assim que ela entrasse no sistema, todos os chamados Faturados ficassem aparentes sem precisar aplicar um filtro.
Login Técnico, Assim que eu entrasse no sistema todos os chamados em Andamento ficassem aparentes sem precisar aplicar um filtro.

E tambem seria legal na Opção de arquivos, eu conseguisse aplicar pastas de separação para tipo, Documentação de cliente X.

**Comment by Pr3d4dor** [comment]
@basgelly Obrigado pelas sugestões, iremos implementar assim que possível.
