### ISSUE TITLE
Valor somado de produtos e serviços

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1046]
Na Pag onde se lista todas as OS do sistema ja apresenta os valores da soma de produtos e serviços dentro da OS
e o valor a qual a mesma foi faturada.

Estou tentando colocar esses valores na area do cliente para que o mesmo não precise visualizar a OS para ver o valor Total da Mesma

Ja coloquei todos os campos nos PHP, so que o Único campo que consegui fazer apresentar os valores Foi o do valor a qual a OS foi Faturada, o outro campo continua em 0

Ja tentei de tudo oque meu conheci8mento permite
conecte/os.php
models/Os_model.php
models/Conecte_model.php
controllers/Mine.php

Em conecte/os.php utilizei essas 2 formas mas nenhuma obtive as leituras

$ValorTotal1 = number_format($r->totalProdutos + $r->totalServicos, 2, ',', '.');
$ValorTotal2 = number_format($totalProdutos + $totalServicos, 2, ',', '.');

**Comment by Pr3d4dor** [comment]
@hoshikawakun Você alterou a query para realizar a soma?

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Você alterou a query para realizar a soma?

fiz assim como coloquei aki 

$ValorTotal1 = number_format($r->totalProdutos + $r->totalServicos, 2, ',', '.');
$ValorTotal2 = number_format($totalProdutos + $totalServicos, 2, ',', '.');

tentei essas 2 alternativas mas nenhuma foi
se puder me falar ode devo fazer as alterações ja ajuda muito

**Comment by Pr3d4dor** [comment]
@hoshikawakun Isso não altera a query, você precisa alterar também o select do banco de dados.

**Comment by hoshikawakun** [comment]
Consegui resolver
Segue os arquivos que alterei e as alterações que eu fiz

application\models\Conecte_model.php

public function getLastOs($cliente)
    {
        
        $this->db->where('clientes_id', $cliente);
		$this->db->join('usuarios', 'os.usuarios_id = usuarios.idUsuarios', 'left');
        $this->db->limit($this->data['configuration']['per_page']);

        return $this->db->get('os')->result();
    }

public function getOs($table, $fields, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array', $cliente)
    {
        
        $this->db->select($fields);
        $this->db->from($table);
		$this->db->select('
	   COALESCE((SELECT SUM(produtos_os.preco * produtos_os.quantidade ) FROM produtos_os WHERE produtos_os.os_id = os.idOs), 0) totalProdutos,
	   COALESCE((SELECT SUM(servicos_os.preco * servicos_os.quantidade ) FROM servicos_os WHERE servicos_os.os_id = os.idOs), 0) totalServicos');
        $this->db->join('usuarios', 'os.usuarios_id = usuarios.idUsuarios', 'left');
        $this->db->where('clientes_id', $cliente);
        $this->db->limit($perpage, $start);
        $this->db->order_by('idOs', 'desc');
        $query = $this->db->get();
        
        $result =  !$one  ? $query->result() : $query->row();
        return $result;
    }

application\views\conecte\os.php

Add  nas tabelas Responsável, Total e Faturado

Os codigos são

<?php foreach ($results as $r) {
$ValorTotal = number_format($r->totalProdutos + $r->totalServicos, 2, ',', '.');


echo '<td>' . $r->nome . '</td>';
echo '<td><div align="center">R$: ' . $ValorTotal . '</div></td>';
echo '<td><div align="center">R$: ' . number_format($r->valorTotal, 2, ',', '.') . '</div></td>';
