### ISSUE TITLE
Sistema Online cliente cria O.S. Envio de email para o tecnico??

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1047]
Bom dia a Todos.
Estou com o sistema rodando online em meu servidor, e agora alguns clientes já estão cadastrando direto no sistema a ordem de serviço ou solicitação. Seria possível quando ele criar essa ordem ser enviado um email para o email do sistema ou direcionar para o técnico?

**Comment by Pr3d4dor** [comment]
@cabralwms Eu não lembro de cabeça agora, mas talvez já era pra enviar, mas se não é só copiar o que já existe e adaptar no controller que o cliente usa pra criar a OS.

**Comment by cabralwms** [comment]
Fiz um teste e realmente quando o cliente cadastra e cria a ordem de serviço nao e enviado um email avisando. Acho que seria legal esse aviso. Eu nao tenho muito conhecimento, mas vou tentar fazer se eu conseguir aviso aqui.

**Comment by cabralwms** [comment]
Não tive sucesso para fazer essa alteração.
