### ISSUE TITLE
Instruçoes para colocar em um Host Online?

### ISSUE THREAD

**Issue by willianrcurcio** [RamonSilva20/mapos#1048]
Olá, vi que no seu arquivo há instruções para servidor local como Xampp : Instalacao_xampp_windows . 
Como faço para hospedar em um Host Free Online, tipo: InifinityFree, 000webhost, etc ??? 
No caso eu fiz Upload da Pasta Mapos para o Host Online Infinity Free , criei o banco de dados, fiz a instalaçao. Porém quando eu tento fazer Login ele entra em Loop. Eu verifiquei o banco de dados nele só tem:  "ci_sessions" .
Poderia ajudar?

**Comment by Pr3d4dor** [comment]
@willianrcurcio Você criou o banco de dados usando o arquivo `banco.sql`?

**Comment by willianrcurcio** [comment]
Nao, eu fiz a instalaçao normalmente como se fosse no xampp. Devo eu fazer Upload do banco.sql primeiro antes de entrar na tela de instalaçao?

**Comment by Pr3d4dor** [comment]
Se você usou o instalador, era pra ter funcionado, mas talvez deu algum erro lá na hospedagem.

**Comment by willianrcurcio** [comment]
Na tela de instalação Mapos, voce colocou na URL : http://www.[seulink].com/mapos/   ???
ou voce colocou : http://www.[seulink].com ???
ou www.[seulink].com ???
Preciso alterar alguma coisa no config.php ? 
No caso de hospedar Online , nao preciso executar o comando : `composer install --no-dev` , correto?

**Comment by Pr3d4dor** [comment]
@willianrcurcio Precisa sim, caso não tenha acesso SSH na hospedagem você precisa enviar a pasta vendor via FTP.
