### ISSUE TITLE
boa noite eu gostaria que associar o quadro da ordem de servico que mudei o nome para titulo ao campo do dashboard

### ISSUE THREAD

**Issue by AOSHIY** [RamonSilva20/mapos#1049]
eu consegui fazer a alteracao dos campos da ordem de servico consultando aqui,mas gostaria que quando entra se na parte do ordem de servico em vez de vizualizar a garantia eu vizualiza se os titulos que colocar na minha ordem de servico

**Comment by Pr3d4dor** [comment]
@AOSHIY Desculpe, não entendi exatamente o que você quer fazer, pode explicar melhor?

**Comment by AOSHIY** [comment]
![titulo](https://user-images.githubusercontent.com/74568823/99432419-e0912900-28ea-11eb-8141-bd8eeca2b2f0.jpg)

eu gostaria de associar este campo a este campo

![campo](https://user-images.githubusercontent.com/74568823/99432462-ed158180-28ea-11eb-906e-af6fa8657206.jpg)

**Comment by AOSHIY** [comment]
e voce sabe me dizer por que agora tem dado este erro mudei mais um campo mas ele vem dando este erro
![680e0691-2cd3-45ee-bc50-4bb1a2655742](https://user-images.githubusercontent.com/74568823/99432529-0c141380-28eb-11eb-88cc-570049f50608.jpg)

**Comment by Pr3d4dor** [comment]
@AOSHIY Você criou esse campo "titulo" no banco de dados?

Sobre o erro em vermelho, como você retirou e modificou os campos você vai precisar revisar os campos obrigatórios do formulário de criação de OS. Fica em: `application/config/form_validation.php`

**Comment by AOSHIY** [comment]
O banco de dados no localhost? Sim criei este campo na parte de os

**Comment by AOSHIY** [comment]
O erro em vermelho era que eu tinha que alterar na pasta controles /os também e não tinha feito

**Comment by AOSHIY** [comment]
eu so alterei este titulo,gostaria de associar ele ao campo lá,para que o nome que for digitado apareça 
![TESTE2](https://user-images.githubusercontent.com/74568823/99601407-16630a00-29de-11eb-81f7-3902a70cd294.png)

**Comment by AOSHIY** [comment]
se puderem me dar uma luz so de como associo uma coisa a outra eu me viro ^^ nao entendo nada de programacao nas estou indo associando as coisas

**Comment by AOSHIY** [comment]
@Pr3d4dor consegue me dar um mine passo a passo do que devo alterar

**Comment by Pr3d4dor** [comment]
@AOSHIY se você passar o código que fez, fica mais fácil pra te ajudar.

**Comment by AOSHIY** [comment]
@Pr3d4dor ,e que este que eu mostro e meu pc particular onde eu faco os teste antes de modificar
neste imagem aparece descricao do produto eu alterei para titulo,pois estou usando para uma grafica pequena eu gostaria que o nome que coloco neste campo
![campo](https://user-images.githubusercontent.com/74568823/100659967-24931d80-3330-11eb-9ce7-d8c9d4cf7492.jpg)

aparecer neste campo aqui substituindo o vencimento da garantia
![ordem de servico](https://user-images.githubusercontent.com/74568823/100660286-94a1a380-3330-11eb-87f5-888a701596c1.jpg)

**Comment by Pr3d4dor** [comment]
@AOSHIY certo, você só renomeou no formulário "Descrição Produto/Serviço" para "Título" e você também alterou a coluna no banco de dados para titulo?

**Comment by AOSHIY** [comment]
Sim

**Comment by AOSHIY** [comment]
@Pr3d4dor Sim alterei na parte da o.s

**Comment by AOSHIY** [comment]
@Pr3d4dor segue a imagem no caso alterei no localhost o produtos 
![banco de dados](https://user-images.githubusercontent.com/74568823/100667730-a6d40f80-3339-11eb-8321-9b4b5c0383d5.png)

**Comment by Pr3d4dor** [comment]
@AOSHIY Mas pela imagem então, você apenas renomeou no formulário. Não mudou o nome da coluna no banco de dados.

**Comment by AOSHIY** [comment]
@Pr3d4dor  pronto xD
![titulo](https://user-images.githubusercontent.com/74568823/100678891-00920500-334d-11eb-8c19-ff63e9675be5.png)

**Comment by Pr3d4dor** [comment]
No arquivo: application/views/os/os.php, na linha 59 mude "Venc. Garantia" para "Título".

E mude a linha 120 de:
```
echo '<td>' . $vencGarantia. '</td>';
```
Para:
```
echo '<td>' . $r->titulo. '</td>';
```

**Comment by AOSHIY** [comment]
@Pr3d4dor muito obrigado cara funcionou
