### ISSUE TITLE
Download novo mapos 

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#105]
Boa noite, já está disponível o novo mapos para download? Se sim, onde consigo.

Obrigado

**Comment by wgiacomelli** [comment]
Opa, pode baixar no link que segue abaixo, mas adianto que o projeto encontra-se bastante incompleto.  https://github.com/RamonSilva20/mapos/tree/novo_mapos

**Comment by acinformatica2004** [comment]
Boa noite, onde está o arquivo banco.sql da versão 4,é o mesmo da versão 3?

**Comment by Henrique-Miranda** [comment]
Está na pasta docs.

**Comment by bernardoari** [comment]
boa tarde, queria ajudar no desenvolvimento da nova versão.... o link que foi passado não existe mais.
