### ISSUE TITLE
Calcular preço de venda c base no preço de compra

### ISSUE THREAD

**Issue by Ronierick** [RamonSilva20/mapos#1050]
Amigos, existe uma forma de quando colocarmos o preço de compra de um produto, o campo preço de venda ser preenchido automaticamente por um percentual acima de ganho? Exemplo de 30%.

Preço de compra 10,00 reais
Preço de venda 13,00 reais(preenchimento automático).

**Comment by Pr3d4dor** [comment]
@Ronierick sim, é possível, mas onde vc acha que esse percentual deveria ser salvo?

**Comment by Ronierick** [comment]
poderia ser nas configurações, sistema. um campo pedindo o percentual de ganho no preço de compra. sendo aplicando o percentual no preço de venda.

**Comment by LipzyLipzy** [comment]
Boa tarde, com essa implementação vais aplicar a mesma percentagem em todos os produtos!
Se for no próprio campo podes sempre aplicar a percentagem que quiseres em cada produto.

Eu já partilhei essa função com o @Pr3d4dor.
Se achar que esta tudo OK pode incorporar no mapos.

Abraço
