### ISSUE TITLE
OS Duplicada na Pag Inicial

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1051]
Estou tendo o seguinte Problema
Digamos
OS Concluida
se a mesma não possue um ou nenhum serviço dentro da mesma ela aparece apenas uma vez
Já se possue mais de um serviço ela ja aparece mais de uma vez

Se na OS tem 5 serviços ela aparece 5X
se na OS tem 2 serviços ela aparece 2X

esse e o arquivo que eu tenho utilizado da tela principal

[Painel.php](https://github.com/hoshikawakun/MasterOS/blob/master/application/views/mapos/painel.php)

**Comment by Pr3d4dor** [comment]
@hoshikawakun Esse erro já foi corrigido, atualize para a versão mais recente do mapos.

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Esse erro já foi corrigido, atualize para a versão mais recente do mapos.

sabe informar onde devo mecher pois ja editei tanta coisa no meu aki que se torna inviavel atualizar

**Comment by hoshikawakun** [comment]
Analizando aki consegui resolver o problema

editei o arquivo application\models\Mapos_model.php

Deletando as seguintes linhas de todos os codigos

$this->db->join('produtos_os', 'produtos_os.os_id = os.idOs', 'left');
$this->db->join('servicos_os', 'servicos_os.os_id = os.idOs', 'left');
