### ISSUE TITLE
Pesquisa

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1052]
No meu sistema fiz algumas personalizações dentre elas Modal de Equipamentos na OS ao qual essas informações ficam em outra tabela

oque eu gostaria de saber e como acrescentar na função pesquisar por exemplo 

chega um aparelho com numero de serie "XXX2ZZ" que o mesmo ja passou outras vezes pela assistência
Cada vez que ele passou foi aberta uma nova OS e em Equipamento o mesmo fora cadastrado
oque eu quero e no campo de pesquisa digitar o serial dele e a pesquisa me informar as OS que esse aparelho ja passou

espero ter conseguido explicar

seria complicado me auxiliar como devo deixar a "public function pesquisar" para que eu consiga oque eu desejo?

Eu ja acrescentei essas linhas

// Buscando equipamento_os
		$this->db->like('idEquipamento', $termo);
		$this->db->or_like('num_serie', $termo);
		$this->db->limit($this->data['configuration']['per_page']);
		$data['equipamento_os'] = $this->db->get('equipamento_os')->result();

Mas não obtive sucesso

**Comment by Pr3d4dor** [comment]
@hoshikawakun Você precisa fazer o join com a tabela equipamentos e realizar o like.
