### ISSUE TITLE
criar pagamento recorrente

### ISSUE THREAD

**Issue by thalysonaraujo** [RamonSilva20/mapos#1053]
boa tarde, 
gostaria de ter pagamento recorrente para emissao de mensalidades.

**Comment by Pr3d4dor** [comment]
@thalysonaraujo Na verdade seriam lançamentos financeiros recorrentes certo? Pois irá criar o lançamento automaticanete e você iria nele para confirmar o recebimento.

**Comment by thalysonaraujo** [comment]
isso mesmo, igual alugo acesso a internet mensal, ae lancaria o nome do cliente e ja criava todo mes a fatura. so baixaria quando pago

**Comment by iEmersonJr** [comment]
Nesse caso, seria possivel criar essas mensalidades recorrentes? 
@Pr3d4dor
