### ISSUE TITLE
No campo Faturamento/editar/

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1054]
Bom dia a Todos. Percebi o campo observação na hora de faturar a O.S, aparece para editar, mas ao clicar em editar no setor faturamento ele não aparece. Seria legal poder editar esse campo se precisar fazer uma alteração.
Grato pela atenção

**Comment by Pr3d4dor** [comment]
@cabralwms Obrigado por reportar, iremos corrigir.
