### ISSUE TITLE
Novos campos

### ISSUE THREAD

**Issue by jonasgeovana** [RamonSilva20/mapos#1055]
Olá! Estou tentando adicionar novos campos para a O.S e até o momento consegui adicionar no HTML  e criar as tabelas no bando de dados. Ao criar a O.S pela primeira vez, os dados são salvos normalmente, mas, ao entrar na parte de edição da O.S, os novos dados dos novos campos não são carregados para os campos como mostra na imagem abaixo.

![Capturar](https://user-images.githubusercontent.com/22485550/100338999-0f2c9500-2fb8-11eb-9423-e81d026cf0eb.PNG)

Já fiz várias alterações nos arquivos e simplesmente não carrega tais dados. Poderia me dizer como carregar tais dados em tais campos? No banco de dados estão como VARCHAR.

**Comment by Pr3d4dor** [comment]
@jonasgeovana Você precisa adicionar esses campos novos na consulta que busca a OS do banco de dados para que eles possam aparecer na tela. Você também alterou para os inputs exibirem os valores vindos do banco?
