### ISSUE TITLE
pesquisa

### ISSUE THREAD

**Issue by AOSHIY** [RamonSilva20/mapos#1059]
gostaria de adicionar estes campos para pesquisa me da uma luz como fazer
![pesquisa](https://user-images.githubusercontent.com/74568823/100785880-0d1b6980-33f0-11eb-9115-c74a79c80066.png)

**Comment by Pr3d4dor** [comment]
@AOSHIY Você vai ter que adicionar or where com esses dois campos.

**Comment by AOSHIY** [comment]
@Pr3d4dor tem como me dar um exemplo para que eu consiga fazer por favor

**Comment by AOSHIY** [comment]
eu nao entendo muito de programacao mas se me explicar eu dou meu jeito

**Comment by AOSHIY** [comment]
@Pr3d4dor Vou ter que adicionar o or where onde... Eu achei vários where na programação mas nenhum que vi que Estava ligado a cliente

**Comment by tonnybarros** [comment]
Eu editei a um tempo atrás para a pesquisa considerar tudo que é importante, como número de OS, etc..
https://github.com/tonnybarros/mapos
Use como exemplo.

Estou baixando hoje a nova versão para modificar como esse https://github.com/tonnybarros/mapos

**Comment by AOSHIY** [comment]
@tonnybarros ao meu ver , o que vc mandou está igual ao o que tenho aqui,porém preciso adicionar aquele campo se pesquisa que está na foto para pesquisar o título e também o número de os

**Comment by tonnybarros** [comment]
Negativo, no meu pode usar a pesquisa no topo geral para pesquisar quase tudo

**Comment by AOSHIY** [comment]
@tonnybarros @Pr3d4dor Só preciso de uma luz de onde fica este where para colocar para pesquisar
