### ISSUE TITLE
Pagamento via Mercado Pago pela area do usuario

### ISSUE THREAD

**Issue by paulohcgs1997** [RamonSilva20/mapos#1060]
desde já agradeço o trabalho incrivel que vocês estão fazendo.
a minha duvida e sobre a implementação da api do mercado pago
na area de visualização das os pelo administrador aparece o botão de pagamento do mercado pago mais na area do cliente não aparece.
queria saber se e assim mesmo ou configurei errado.

**Comment by Pr3d4dor** [comment]
@paulohcgs1997 Na área do cliente realmente o botão não aparece.

**Comment by willph** [comment]
> desde já agradeço o trabalho incrivel que vocês estão fazendo.
> a minha duvida e sobre a implementação da api do mercado pago
> na area de visualização das os pelo administrador aparece o botão de pagamento do mercado pago mais na area do cliente não aparece.
> queria saber se e assim mesmo ou configurei errado.

É assim mesmo. Ainda não foi colocado na área do cliente o botão.

**Comment by willph** [comment]
Adicionado botão de pagamento na área do cliente. 

PR #1093 só aguarda aprovação.
