### ISSUE TITLE
Balanço Mensal 

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1061]
Na pag Inicial tem o Balanço Mensal do Ano xxxx que apresenta apenas a receita liquida, seria possivel que tivesse junto a receita bruta?

Uma barra Azul para a Receita Liquida (Que ja esta assim)
Uma barra Verde ou de outra cor com a receita Bruta?

**Comment by Pr3d4dor** [comment]
@hoshikawakun Sim é possível, porém iria requerer um certo tempo pra fazer.

**Comment by hoshikawakun** [comment]
Onde então que eu poderia mecher para envez de apresentar o liquido, apresentar o Bruto
que pra mim seria mais ´pratico de mometo

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Sim é possível, porém iria requerer um certo tempo pra fazer.

então assim que possivel que seja implementado isso OK
