### ISSUE TITLE
AUTOCOMPLETE PRODUTOS NA ABA VENDAS

### ISSUE THREAD

**Issue by wnjulio** [RamonSilva20/mapos#1063]
Olá a todos!

Como eu faria para colocar para pesquisar pelo codigo de barras o autocomplete  da aba vendas, adicionar produto pelo codbarra?

Gostaria de saber o caminho, pois em vendas_model existe o autocomplete, porem parece que não esta ligado nele e sim em outro, apaguei ele e continuou funcionando.

Grato.

**Comment by Pr3d4dor** [comment]
@wnjulio Você tem que modificar a função autocomplete produto.

**Comment by willph** [comment]
> Olá a todos!
> 
> Como eu faria para colocar para pesquisar pelo codigo de barras o autocomplete da aba vendas, adicionar produto pelo codbarra?
> 
> Gostaria de saber o caminho, pois em vendas_model existe o autocomplete, porem parece que não esta ligado nele e sim em outro, apaguei ele e continuou funcionando.
> 
> Grato.

Já faz. Eu testei aqui no menu Vendas.

![16079779538777129301137445809544](https://user-images.githubusercontent.com/17226802/102132442-6775ea80-3e32-11eb-9909-1f3f7035276f.jpg)
