### ISSUE TITLE
MAPOS 4 ESTA COM ERRO QUANDO VAI IMPRIMIR OS RELATORIOS

### ISSUE THREAD

**Issue by allexsiilva** [RamonSilva20/mapos#1064]
OLA AMIGOS, INSTALEI O MAPOS AI QUANDO FUI FAZER UMA IMPRESSAO DE RELATORIOES A PARTE DE IMPRESSAO DOS RELATORIOS NAO ESTA FUNCIONANDO, TINHA COMO AJEITAR POR FAVOR?

**Comment by Pr3d4dor** [comment]
@allexsiilva Vá em Configurações >> Emitente e atualize o logo da sua empresa. Após isso tente imprimir novamente.

**Comment by allexsiilva** [comment]
JA ESTAR CONFIGURADO COM LOGO E DADOS DA EMPRESA

**Comment by Pr3d4dor** [comment]
@allexsiilva Sim, mas vc precisa mudar o logo, mesmo que já esteja, atualize nem que seja o mesmo.

**Comment by allexsiilva** [comment]
SHOW, DEU CERTO KKK, MUITO OBRIGADO

**Comment by allexsiilva** [comment]
OUTRA COISA, SERA SE VCS TINHA TIPO COMO FAZER A IMPRESSAO NAO FISCAL DA PRA ESCOLHER O FORMATO?

TEM CLIENTE QUE USAR O TAMANHO NORMAL DE NAO FISCAL E OUTARS QUE USAM 58M TINHA COMO VCS ADICIONAR UM CAMPOR PARA AJUSTA O TAMANHO DA BOBINA DA IMPRESSORA NAO FISCAL?

**Comment by Pr3d4dor** [comment]
@allexsiilva Daria, mas não é tão simples, vou deixar na lista de próximas features.
