### ISSUE TITLE
Inserir 'cor status' agenda OS na dashboard

### ISSUE THREAD

**Issue by HSchneiderS** [RamonSilva20/mapos#1065]
Olá a todos,
onde encontro arquivo referente calendario para alterar status da OS na dashboard
tipo colocar cor de status de uma OS.
Muito grato!
![calendario_mapos](https://user-images.githubusercontent.com/52082305/101628786-19f71900-39ff-11eb-821b-4b3b52b4605f.PNG)

**Comment by Pr3d4dor** [comment]
@HSchneiderS Infelizmente essa cor não é customizável

**Comment by hoshikawakun** [comment]
> 
> 
> @HSchneiderS Infelizmente essa cor não é customizável

mas seria possivel customizar a mesma não seria?
com algumas alterações no codigo?

**Comment by willph** [comment]
O que você queria era isso?

![16079791151747740190343557604407](https://user-images.githubusercontent.com/17226802/102134379-2d5a1800-3e35-11eb-9876-509f15eb470e.jpg)

**Comment by HSchneiderS** [comment]
isso mesmo amigo,
cor de status da OS

**Comment by willph** [comment]
> 
> 
> isso mesmo amigo,
> cor de status da OS

Vou fazer a PR e em breve estará disponível.

**Comment by HSchneiderS** [comment]
> > isso mesmo amigo,
> > cor de status da OS
> 
> Vou fazer a PR e em breve estará disponível.

ok vlw

**Comment by willph** [comment]
PR feita, de número #1074.

Agora só aguarda aprovar, assim que aprovar lhe aviso é finalizo essa issue. 
👍

**Comment by willph** [comment]
Pronto. PR #1074 aprovada, já pode baixar.

**Comment by HSchneiderS** [comment]
opa, vlw mmo obrigado
👍👍
