### ISSUE TITLE
Campo Telefone

### ISSUE THREAD

**Issue by winnerinformatica** [RamonSilva20/mapos#1066]
Teria como aumentar o campo telefone nos cadastros de clientes e usuários para 14 Ex: (11)99999-9999

**Comment by Pr3d4dor** [comment]
@winnerinformatica O campo já não aceita celular com 9 dígitos?

**Comment by winnerinformatica** [comment]
No caso então teria como mudar a impressão de OS com o campo celular em vez de telefone. Porque é o que se usa mais nos dias atuais. Grato.

**Comment by hoshikawakun** [comment]
resolver isso e ate bem simples de se fazer,
no meu aki quando eu fiz isso não tinha string de preenchimento do telefone so a de CPF/CNJP
eu dupliquei e alterei alguns nomes pra poder usar com telefone
então ele ja deixa o numero certinho tipo (00) 0000-0000
so que ao vc digitar o proximo digito no caso de for um numero de celular ele alterava a posição do traço ficando (00) 00000-0000
alem de ter limitado a quantidade de digitos, se atingindo o limite ele ja não escreve mais nada

axo que e isso que o amigo esta querendo colocar

**Comment by willph** [comment]
> 
> 
> Teria como aumentar o campo telefone nos cadastros de clientes e usuários para 14 Ex: (11)99999-9999

Criei um script para alterar isso de forma automática.

Aceitando tanto (00)0000-0000 e (00)00000-0000.
Irei fazer a PR com essa alteração.
So aguarda se será aprovada ou não.

**Comment by willph** [comment]
PR aprovada, só baixa código mais recente.

**Comment by winnerinformatica** [comment]
Muito obrigado, era exatamente isso que eu estava precisando para o relatório de OS.
A maioria das pessoas hoje não usam mais telefone fixo, por isso a necessidade de colocar o nº de celular para os relatórios.
