### ISSUE TITLE
Baixa de estoque por status de ordem de serviço

### ISSUE THREAD

**Issue by octaralves** [RamonSilva20/mapos#1067]
** Ao realizar um Orçamento deveria lançar os produtos sem realizar baixa de estoque.

** Ao realizar um outro tipo de ordem de serviço deveria lançar os produtos e realizar baixa de estoque

** Caso tenha feito um orçamento e o mesmo for alterado de orçamento para qualquer outro status o sistema realiza a baixa de estoque dos produto da ordem de serviço durante a troca de status.

** Status alterado de cancelado para orçamento ou orçamento para cancelado não faz alterações de estoque.
** Status se a ordem de serviço estiver cancelada e for alterada para um outro status difere com exceção de orçamento realiza baixa.

**Comment by Pr3d4dor** [comment]
@octaralves Obrigato pela sugestão, iremos implementar assim que possível.
