### ISSUE TITLE
Personalização da notificação por whatsapp

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1075]
olá gostaria de ajuda para altera a notificação por whatsapp

ja fiz algumas alterações mais cheguei em um ponto que não sei como continuar

_______________________________________________________________________________________________________________________
Prezado(a) *fulano de tal*.

Sua *O.S 39* referente ao equipamento *Notebook: CCE ULTRA modelo: THIN U25* foi atualizada para *Faturado*.

*Resumo :*

*Defeito :* HD DANIFICADO*
*LAUDO :* FOI FEITA A SUBSTITUIÇAO DO HD.FOI FEITA A FORMATAÇÃO.FOI FEITA O BECKUP E RESTAURAÇAO DOS AQUIVOS PESSOAS DO CLIENTE.*

Acesse https://intelsystech.com.br/os/cliente/  para saber mais detalhes ou entre em contato.
Atenciosamente, M INTELSYSTECH 98988620000_

**Cheguei ate aqui porem queria q ficasse algo tipo** 

Prezado(a) *fulano de tal*.

Sua *O.S 39* referente ao equipamento *Notebook: CCE ULTRA modelo: THIN U25* foi atualizada para *Faturado*.

Resumo :

Defeito : HD DANIFICADO*
LAUDO : FOI FEITA A SUBSTITUIÇAO DO HD.FOI FEITA A FORMATAÇÃO.FOI FEITA O BECKUP E RESTAURAÇAO DOS AQUIVOS PESSOAS DO CLIENTE.*
Serviço:
SUBSTITUIÇÃO DO HD: Quantidade:1 Preço unit. 30.00 Sub-total R$ 30,00
FORMATAÇÃO: Quantidade:1 Preço unit. 70.00  Sub-total R$ 70.00

Total:	R$ 100,00

Produto:
MEMORIA RAM 4GB DDR3: Quantidade:1 Preço unit. 150.00 Sub-total R$ 150,00
Total:	R$ 150,00

Valor Total: R$250,00

Acesse https://intelsystech.com.br/os/cliente/  para saber mais detalhes ou entre em contato.
Atenciosamente, M INTELSYSTECH 98988623561_

`<?php if ($this->permission->checkPermission($this->session->userdata('permissao'), 'eOs')) {
    $zapnumber = preg_replace("/[^0-9]/", "", $result->celular_cliente);
    echo '<a title="Enviar Por WhatsApp" class="btn btn-mini btn-info" id="enviarWhatsApp" target="_blank" href="https://web.whatsapp.com/send?phone=55' . $zapnumber . '&text=Prezado(a)%20*' . $result->nomeCliente . '*.%0d%0a%0d%0aSua%20*O.S%20' . $result->idOs . '*%20referente%20ao%20equipamento%20*' . strip_tags($result->descricaoProduto) . '*%20foi%20atualizada%20para%20*' . $result->status . '*.%0d%0a%0d%0a*Resumo%20' . ':*%0d%0a%0d%0a*Defeito%20' . ':*%20' . strip_tags($result->defeito)  . '*%0d%0a*LAUDO%20' . ':*%20' . strip_tags($result->laudoTecnico) . '*%0d%0a*test%20' . ':*%20' . strip_tags($result->produtos) . '*.%0d%0a%0d%0aAcesse%20https://intelsystech.com.br/os/cliente/%20%20para%20saber%20mais%20detalhes%20ou%20entre%20em%20contato.%0d%0a%0d%0aAtenciosamente,%20' . ($emitente ? $emitente[0]->nome : '') . '%20' . ($emitente ? $emitente[0]->telefone : '') . '_"><i class="fab fa-whatsapp"></i> Resumo WhatsApp</a>';
} ?>`

**esse e o condigo q to usando mexendo **
 seria possível chega a um resultado parecido?

desse forma a pessoa já teria um resumo bem completo da OS

**Comment by RamonSilva20** [comment]
Olá @marllonferreira, acho que essa uma ideia interessante, poder customizar a mensagem. Vou tentar num futuro próximo implementar algo.

**Comment by hoshikawakun** [comment]
> 
> 
> Olá @marllonferreira, acho essa uma ideia interessante, poder customizar a mensagem. Vou tentar num futuro próximo implementar algo.

no meu ja tenho isso tudo implementado

**Comment by hoshikawakun** [comment]
não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
veja como esta o meu

![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)

e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema

![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)

**Comment by marllonferreira** [comment]
> > Olá @marllonferreira, acho essa uma ideia interessante, poder customizar a mensagem. Vou tentar num futuro próximo implementar algo.
> 
> no meu ja tenho isso tudo implementado

@hoshikawakun seria possível me passa o código?

**Comment by hoshikawakun** [comment]
> 
> 
> > > Olá @marllonferreira, acho essa uma ideia interessante, poder customizar a mensagem. Vou tentar num futuro próximo implementar algo.
> > 
> > 
> > no meu ja tenho isso tudo implementado
> 
> @hoshikawakun seria possível me passa o código?

https://github.com/hoshikawakun/MasterOS

**Comment by marllonferreira** [comment]
> não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> veja como esta o meu
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> 
> e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)

e exatamente isso que eu estava querendo muito bom

**Comment by hoshikawakun** [comment]
para ficar como mandei nas imagens

> 
> 
> não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> veja como esta o meu
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> 
> e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)



> 
> 
> não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> veja como esta o meu
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> 
> e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)

psrs ficar igual eu coloquei nas imagens tive de editar bastante coisa nos PHP alem de algumas Add na DB

**Comment by hoshikawakun** [comment]
> 
> 
> para ficar como mandei nas imagens
> 
> > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > veja como esta o meu
> > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> 
> > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > veja como esta o meu
> > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> 
> para ficar igual eu coloquei nas imagens tive de editar bastante coisa nos PHP alem de algumas Add na DB

**Comment by marllonferreira** [comment]
> > para ficar como mandei nas imagens
> > > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > > veja como esta o meu
> > > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> > 
> > 
> > > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > > veja como esta o meu
> > > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> > 
> > 
> > para ficar igual eu coloquei nas imagens tive de editar bastante coisa nos PHP alem de algumas Add na DB

pra fazer a instalação e os mesmo da mapos normal ?

**Comment by hoshikawakun** [comment]
> 
> 
> > > para ficar como mandei nas imagens
> > > > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > > > veja como esta o meu
> > > > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > > > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > > > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> > > 
> > > 
> > > > não so o conteudo dos campos da OS que vão na MSG mas tmb vai ja a soma dos serviços e produtos da mesa
> > > > veja como esta o meu
> > > > ![Screenshot_9](https://user-images.githubusercontent.com/1253576/102398384-fa8f5b80-3fbd-11eb-871b-d72f7ad207d8.png)
> > > > e algumas das MSG padrão vc tmb pode alterar elas atravez do menu de config do sistema
> > > > ![Screenshot_1](https://user-images.githubusercontent.com/1253576/102398535-2a3e6380-3fbe-11eb-863b-016e95e37954.png)
> > > 
> > > 
> > > para ficar igual eu coloquei nas imagens tive de editar bastante coisa nos PHP alem de algumas Add na DB
> 
> pra fazer a instalação e os mesmo da mapos normal ?
> ou esse sao so os arquivos q vc modificou
vc pode usar o MapOS base pra colocar o meu por cima

unicos arquivos que faltam no meu são
application>>config>>config.php
application>>config>>database.php

que vc pode pegar os do mapos original

**Comment by hoshikawakun** [comment]
vc faz todo o processo normal no mapos primeiro, ate a instalação da pasta vendor
antes de acessar o MapOS e fazer a instalação propriamente dita vc pega o meu e subistitui os arquivos do mapos e segue o processo de instalação

**Comment by hoshikawakun** [comment]
digo isso prq alterei alguns arquivos que ficam na pasta vendor para melhor se adequar as minhas necessidades

**Comment by marllonferreira** [comment]
> digo isso prq alterei alguns arquivos que ficam na pasta vendor para melhor se adequar as minhas necessidades

@hoshikawakun 

não cheguei a instalar a sua versão pq notei que tem muitas alterações ate mesmo no banco de dados como vc falou isso e um pesadelo na hora que sair nova atualizações to usando a v4.20.1 acabou de sair a v4.23.0 ja me interessei kkk

mais copiei o código do whatsapp só fiz algumas pequenas mudanças gostei bastante do resultado.

![zap](https://user-images.githubusercontent.com/31580600/102613493-58808800-4111-11eb-86de-e7e142f9e963.PNG)

muito obrigado pela ajuda valeu mesmo

**Comment by Isaqjonatas** [comment]
Olá, ja foi disponibilizada a atualização com a possibilidade de alteração das mensagens de notificação no whatsapp?
Ou alguem pode informar qual o arquivo .php que preciso editar para implementar essas informações citadas acima?

**Comment by marllonferreira** [comment]
> Olá, ja foi disponibilizada a atualização com a possibilidade de alteração das mensagens de notificação no whatsapp?
> Ou alguem pode informar qual o arquivo .php que preciso editar para implementar essas informações citadas acima?

ainda nao saiu oficial


vou te manda que temos ate agora

[os.zip](https://github.com/RamonSilva20/mapos/files/5775864/os.zip)
o arquivo ta em
mapos/application/views/os/

os.php

faz um backup dele e coloca o que te mandei no lugar da uma olhada nele pra usa como modelo

**Comment by Isaqjonatas** [comment]
Ok, muito obrigado!
