### ISSUE TITLE
Gerar etiquetas

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1076]
Atualmente em Gerar Etiquetas vc escolhe apenas o intervalo de etiquetas a fazer
Ex: produto ID4 ao ID10
seria bom se tivesse como escolher individualmente
Ex: Produto ID04, ID6, ID7, ID9, ID10
Iria gerar apenas etiquetas das ID escritas ao invez de todas dentro de um intervalo

seria possivel implementar isso?

**Comment by Pr3d4dor** [comment]
@hoshikawakun sim, é possível.
