### ISSUE TITLE
Em Dashboard incluir o campo "serviços"

### ISSUE THREAD

**Issue by Loury-Silva** [RamonSilva20/mapos#1077]
Boa tarde!

Como alterar para incluir no script painel em Dashboard, na tabela que mostra os resultados  para "**Ordens de Serviço Em Aberto**" o campo "**serviços**" vinculado a respectiva OS?

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde!
> 
> Como alterar para incluir no script painel em Dashboard, na tabela que mostra os resultados para "**Ordens de Serviço Em Aberto**" o campo "**serviços**" vinculado a respectiva OS?

vc fala desse jeito?

![Screenshot_1](https://user-images.githubusercontent.com/1253576/102406419-4abfeb00-3fc9-11eb-85d7-a7a0d3124195.png)

**Comment by Loury-Silva** [comment]
Estou usando a versão 4.8.2, este teu painel é estranho para mim. Mas o que eu quero é neste painel, logo após o campo do  Nº da OS um outro campo para Serviços, tipo: Nº OS    -    Produto    -   Cliente  -    etc....

**Comment by Loury-Silva** [comment]
Ficaria assim: Nº OS  -  Serviços  -  Produto - Cliente - etc ....

**Comment by Loury-Silva** [comment]
No layout do painel ficaria assim:

![painel](https://user-images.githubusercontent.com/73559534/102409293-8d83c200-3fcd-11eb-8f01-108b2f03a533.png)

**Comment by Loury-Silva** [comment]
Boa tarde!
Alguma luz de como fazer essa alteração?

**Comment by Pr3d4dor** [comment]
@Loury-Silva Essa alteração não é tão trivial pois numa OS existem N serviços e não somente um.
