### ISSUE TITLE
Erro ao adicionar produto em VENDAS

### ISSUE THREAD

**Issue by armeiroairsoft** [RamonSilva20/mapos#1078]
Antes de qualquer coisa quero agradecer pelo trabalho de vocês, simplesmente fantástico! Obrigado!

** Descreva o bug **
Adiciono uma venda, na hora que vou adicionar o produto relacionado a venda aparece a mensagem "Erro ao adicionar produto" e fica uma barra azul direto como se estivesse tentando carregar e não sai disso.
Achei duas pessoas falando do mesmo problema aqui, porém a solução de um não foi informada e do outro os campos que ele disse que faltava no banco de dados, no meu estão normal.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'VENDAS'
2. Clique em 'ADICIONAR VENDA'
3. EM SEGUIDA AO TENTAR ADICIONAR O PRODUTO APRESENTA O ERRO
4. Ver erro

**Comportamento esperado**
Que o produto fosse incluído.

** Capturas de tela **
https://uploaddeimagens.com.br/imagens/sxEjKXg

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo W10]
 - Navegador [Chrome]
 - Versão 87.0.4280.88 (Versão oficial) 64 bits

**Comment by willph** [comment]
O produto está adicionado no banco de dados?

Este campo da erro se escreve manualmente os dados. Sem está adicionado no menu Produtos

**Comment by armeiroairsoft** [comment]
Então, tentei das duas formas, a principio se escrever um produto que esteja cadastrado ele não puxa como faz quando vc adiciona em uma ordem de serviço.

**Comment by willph** [comment]
> Então, tentei das duas formas, a principio se escrever um produto que esteja cadastrado ele não puxa como faz quando vc adiciona em uma ordem de serviço.

Aqui está normal. Amanhã irei testar novamente,  aí te digo de noite.

**Comment by armeiroairsoft** [comment]
Amanhã faço um pequeno vídeo e coloco no YouTube.

**Comment by armeiroairsoft** [comment]
Bom dia Willph, primeiro obrigado por me ajudar, fiz um video pequeno que acho que da pra entender o que está acontecendo.
https://youtu.be/SpJBvqjQBvE
Acabei de enviar 08:57.

**Comment by willph** [comment]
> Bom dia Willph, primeiro obrigado por me ajudar, fiz um video pequeno que acho que da pra entender o que está acontecendo.
> https://youtu.be/SpJBvqjQBvE
> Acabei de enviar 08:57.

Aqui está funcionando tranquilamente. O valor é fake kkkk Só pra teste.
Qual a versão está usando?


![16082065643862077576057659584517](https://user-images.githubusercontent.com/17226802/102485677-b1cfb500-4046-11eb-9756-65893679191d.jpg)

**Comment by armeiroairsoft** [comment]
4.20.2

**Comment by armeiroairsoft** [comment]
Será que está faltando alguma coisa na página?
O form dentro da página está dessa forma:
` <div class="span12 well" style="padding: 1%; margin-left: 0">
                                    <form id="formProdutos" action="<?php echo base_url(); ?>index.php/vendas/adicionarProduto" method="post">
                                        <div class="span6">
                                            <input type="hidden" name="idProduto" id="idProduto" />
                                            <input type="hidden" name="idVendasProduto" id="idVendasProduto" value="<?php echo $result->idVendas ?>" />
                                            <input type="hidden" name="estoque" id="estoque" value="" />
                                            <label for="">Produto</label>
                                            <input type="text" class="span12" name="produto" id="produto" placeholder="Digite o nome do produto" />
                                        </div>
                                        <div class="span2">
                                            <label for="">Preço</label>
                                            <input type="text" placeholder="Preço" id="preco" name="preco" class="span12 money" />
                                        </div>
                                        <div class="span2">
                                            <label for="">Quantidade</label>
                                            <input type="text" placeholder="Quantidade" id="quantidade" name="quantidade" class="span12" />
                                        </div>
                                        <div class="span2">
                                            <label for="">.</label>
                                            <button class="btn btn-success span12" id="btnAdicionarProduto"><i class="fas fa-plus"></i> Adicionar</button>
                                        </div>
                                    </form>`

**Comment by willph** [comment]
> Será que está faltando alguma coisa na página?
> O form dentro da página está dessa forma:
> ` <div class="span12 well" style="padding: 1%; margin-left: 0"> <form id="formProdutos" action="<?php echo base_url(); ?>index.php/vendas/adicionarProduto" method="post"> <div class="span6"> <input type="hidden" name="idProduto" id="idProduto" /> <input type="hidden" name="idVendasProduto" id="idVendasProduto" value="<?php echo $result->idVendas ?>" /> <input type="hidden" name="estoque" id="estoque" value="" /> <label for="">Produto</label> <input type="text" class="span12" name="produto" id="produto" placeholder="Digite o nome do produto" /> </div> <div class="span2"> <label for="">Preço</label> <input type="text" placeholder="Preço" id="preco" name="preco" class="span12 money" /> </div> <div class="span2"> <label for="">Quantidade</label> <input type="text" placeholder="Quantidade" id="quantidade" name="quantidade" class="span12" /> </div> <div class="span2"> <label for="">.</label> <button class="btn btn-success span12" id="btnAdicionarProduto"><i class="fas fa-plus"></i> Adicionar</button> </div> </form>`

A parte do javascript? Não estou vendo nesse código.

**Comment by armeiroairsoft** [comment]
No final da página tem esse código em javascript.
-------------------------------------
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/jquery.validate.js"></script>
<script src="<?php echo base_url(); ?>assets/js/maskmoney.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".money").maskMoney();
        $('#recebido').click(function(event) {
            var flag = $(this).is(':checked');
            if (flag == true) {
                $('#divRecebimento').show();
            } else {
                $('#divRecebimento').hide();
            }
        });
        $(document).on('click', '#btn-faturar', function(event) {
            event.preventDefault();
            valor = $('#total-venda').val();
            valor = valor.replace(',', '');
            $('#valor').val(valor);
        });
        $("#formFaturar").validate({
            rules: {
                descricao: {
                    required: true
                },
                cliente: {
                    required: true
                },
                valor: {
                    required: true
                },
                vencimento: {
                    required: true
                }
            },
            messages: {
                descricao: {
                    required: 'Campo Requerido.'
                },
                cliente: {
                    required: 'Campo Requerido.'
                },
                valor: {
                    required: 'Campo Requerido.'
                },
                vencimento: {
                    required: 'Campo Requerido.'
                }
            },
            submitHandler: function(form) {
                var dados = $(form).serialize();
                $('#btn-cancelar-faturar').trigger('click');
                $.ajax({
                    type: "POST",
                    url: "<?php echo base_url(); ?>index.php/vendas/faturar",
                    data: dados,
                    dataType: 'json',
                    success: function(data) {
                        if (data.result == true) {
                            window.location.reload(true);
                        } else {
                            Swal.fire({
                                type: "error",
                                title: "Atenção",
                                text: "Ocorreu um erro ao tentar faturar venda."
                            });
                            $('#progress-fatura').hide();
                        }
                    }
                });
                return false;
            }
        });
        $("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/os/autoCompleteProdutoSaida",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").focus();
            }
        });
        $("#cliente").autocomplete({
            source: "<?php echo base_url(); ?>index.php/os/autoCompleteCliente",
            minLength: 2,
            select: function(event, ui) {
                $("#clientes_id").val(ui.item.id);
            }
        });
        $("#tecnico").autocomplete({
            source: "<?php echo base_url(); ?>index.php/os/autoCompleteUsuario",
            minLength: 2,
            select: function(event, ui) {
                $("#usuarios_id").val(ui.item.id);
            }
        });
        $("#formVendas").validate({
            rules: {
                cliente: {
                    required: true
                },
                tecnico: {
                    required: true
                },
                dataVenda: {
                    required: true
                }
            },
            messages: {
                cliente: {
                    required: 'Campo Requerido.'
                },
                tecnico: {
                    required: 'Campo Requerido.'
                },
                dataVenda: {
                    required: 'Campo Requerido.'
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            }
        });
        $("#formProdutos").validate({
            rules: {
                quantidade: {
                    required: true
                }
            },
            messages: {
                quantidade: {
                    required: 'Insira a quantidade'
                }
            },
            submitHandler: function(form) {
                var quantidade = parseInt($("#quantidade").val());
                var estoque = parseInt($("#estoque").val());

                <?php if (!$configuration['control_estoque']) {
                                                echo 'estoque = 1000000';
                                            }; ?>

                if (estoque < quantidade) {
                    Swal.fire({
                        type: "warning",
                        title: "Atenção",
                        text: "Você não possui estoque suficiente."
                    });
                } else {
                    var dados = $(form).serialize();
                    $("#divProdutos").html("<div class='progress progress-info progress-striped active'><div class='bar' style='width: 100%'></div></div>");
                    $.ajax({
                        type: "POST",
                        url: "<?php echo base_url(); ?>index.php/vendas/adicionarProduto",
                        data: dados,
                        dataType: 'json',
                        success: function(data) {
                            if (data.result == true) {
                                $("#divProdutos").load("<?php echo current_url(); ?> #divProdutos");
                                $("#quantidade").val('');
                                $("#preco").val('');
                                $("#produto").val('').focus();
                            } else {
                                Swal.fire({
                                    type: "error",
                                    title: "Atenção",
                                    text: "Ocorreu um erro ao tentar adicionar produto."
                                });
                            }
                        }
                    });
                    return false;
                }
            }
        });
        $(document).on('click', 'a', function(event) {
            var idProduto = $(this).attr('idAcao');
            var quantidade = $(this).attr('quantAcao');
            var produto = $(this).attr('prodAcao');
            if ((idProduto % 1) == 0) {
                $("#divProdutos").html("<div class='progress progress-info progress-striped active'><div class='bar' style='width: 100%'></div></div>");
                $.ajax({
                    type: "POST",
                    url: "<?php echo base_url(); ?>index.php/vendas/excluirProduto",
                    data: "idProduto=" + idProduto + "&quantidade=" + quantidade + "&produto=" + produto,
                    dataType: 'json',
                    success: function(data) {
                        if (data.result == true) {
                            $("#divProdutos").load("<?php echo current_url(); ?> #divProdutos");
                        } else {
                            Swal.fire({
                                type: "error",
                                title: "Atenção",
                                text: "Ocorreu um erro ao tentar excluir produto."
                            });
                        }
                    }
                });
                return false;
            }
        });
        $(".datepicker").datepicker({
            dateFormat: 'dd/mm/yy'
        });
        $('.editor').trumbowyg({
            lang: 'pt_br'
        });
    });
</script>

**Comment by willph** [comment]
> ## No final da página tem esse código em javascript.
> <script type="text/javascript" src="assets/js/jquery.validate.js"></script> <script src="assets/js/maskmoney.js"></script> <script type="text/javascript"> $(document).ready(function() { $(".money").maskMoney(); $('#recebido').click(function(event) { var flag = $(this).is(':checked'); if (flag == true) { $('#divRecebimento').show(); } else { $('#divRecebimento').hide(); } }); $(document).on('click', '#btn-faturar', function(event) { event.preventDefault(); valor = $('#total-venda').val(); valor = valor.replace(',', ''); $('#valor').val(valor); }); $("#formFaturar").validate({ rules: { descricao: { required: true }, cliente: { required: true }, valor: { required: true }, vencimento: { required: true } }, messages: { descricao: { required: 'Campo Requerido.' }, cliente: { required: 'Campo Requerido.' }, valor: { required: 'Campo Requerido.' }, vencimento: { required: 'Campo Requerido.' } }, submitHandler: function(form) { var dados = $(form).serialize(); $('#btn-cancelar-faturar').trigger('click'); $.ajax({ type: "POST", url: "index.php/vendas/faturar", data: dados, dataType: 'json', success: function(data) { if (data.result == true) { window.location.reload(true); } else { Swal.fire({ type: "error", title: "Atenção", text: "Ocorreu um erro ao tentar faturar venda." }); $('#progress-fatura').hide(); } } }); return false; } }); $("#produto").autocomplete({ source: "index.php/os/autoCompleteProdutoSaida", minLength: 2, select: function(event, ui) { $("#idProduto").val(ui.item.id); $("#estoque").val(ui.item.estoque); $("#preco").val(ui.item.preco); $("#quantidade").focus(); } }); $("#cliente").autocomplete({ source: "index.php/os/autoCompleteCliente", minLength: 2, select: function(event, ui) { $("#clientes_id").val(ui.item.id); } }); $("#tecnico").autocomplete({ source: "index.php/os/autoCompleteUsuario", minLength: 2, select: function(event, ui) { $("#usuarios_id").val(ui.item.id); } }); $("#formVendas").validate({ rules: { cliente: { required: true }, tecnico: { required: true }, dataVenda: { required: true } }, messages: { cliente: { required: 'Campo Requerido.' }, tecnico: { required: 'Campo Requerido.' }, dataVenda: { required: 'Campo Requerido.' } }, errorClass: "help-inline", errorElement: "span", highlight: function(element, errorClass, validClass) { $(element).parents('.control-group').addClass('error'); }, unhighlight: function(element, errorClass, validClass) { $(element).parents('.control-group').removeClass('error'); $(element).parents('.control-group').addClass('success'); } }); $("#formProdutos").validate({ rules: { quantidade: { required: true } }, messages: { quantidade: { required: 'Insira a quantidade' } }, submitHandler: function(form) { var quantidade = parseInt($("#quantidade").val()); var estoque = parseInt($("#estoque").val()); if (estoque < quantidade) { Swal.fire({ type: "warning", title: "Atenção", text: "Você não possui estoque suficiente." }); } else { var dados = $(form).serialize(); $("#divProdutos").html("
> "); $.ajax({ type: "POST", url: "index.php/vendas/adicionarProduto", data: dados, dataType: 'json', success: function(data) { if (data.result == true) { $("#divProdutos").load(" #divProdutos"); $("#quantidade").val(''); $("#preco").val(''); $("#produto").val('').focus(); } else { Swal.fire({ type: "error", title: "Atenção", text: "Ocorreu um erro ao tentar adicionar produto." }); } } }); return false; } } }); $(document).on('click', 'a', function(event) { var idProduto = $(this).attr('idAcao'); var quantidade = $(this).attr('quantAcao'); var produto = $(this).attr('prodAcao'); if ((idProduto % 1) == 0) { $("#divProdutos").html("
> "); $.ajax({ type: "POST", url: "index.php/vendas/excluirProduto", data: "idProduto=" + idProduto + "&quantidade=" + quantidade + "&produto=" + produto, dataType: 'json', success: function(data) { if (data.result == true) { $("#divProdutos").load(" #divProdutos"); } else { Swal.fire({ type: "error", title: "Atenção", text: "Ocorreu um erro ao tentar excluir produto." }); } } }); return false; } }); $(".datepicker").datepicker({ dateFormat: 'dd/mm/yy' }); $('.editor').trumbowyg({ lang: 'pt_br' }); }); </script>

Sabe visualizar o console no Mozilla Firefox?
Para vê se está ok ou o erro que apresenta.

![16082088297782978341639136172796](https://user-images.githubusercontent.com/17226802/102489256-fdd12880-404b-11eb-9183-893baee02945.jpg)

**Comment by armeiroairsoft** [comment]
comparando o script da página editarOS e o javascript da pagina editarVenda estão com alguns detalhes diferentes, a parte do produto. vou ver isso no mozzila um minuto

**Comment by willph** [comment]
> comparando o script da página editarOS e o javascript da pagina editarVenda estão com alguns detalhes diferentes, a parte do produto. vou ver isso no mozzila um minuto

Olhe o editarvenda daqui do github. 

Ou mas simples, cópia todo o javascript daqui do github e cola no seu. Para testar

**Comment by armeiroairsoft** [comment]
Dentro da página vendas está dessa forma:
type: "POST",
                        url: "<?php echo base_url(); ?>index.php/vendas/adicionarProduto",
                        data: dados,
                        dataType: 'json',
                        success: function(data) {
                            if (data.result == true) {
                                $("#divProdutos").load("<?php echo current_url(); ?> #divProdutos");
                                $("#quantidade").val('');
                                $("#preco").val('');
                                $("#produto").val('').focus();
                            } else {
                                Swal.fire({
                                    type: "error",
                                    title: "Atenção",
                                    text: "Ocorreu um erro ao tentar adicionar produto."
                                });
                                
Dentro da página OS está dessa forma:
type: "POST",
                        url: "<?php echo base_url(); ?>index.php/os/adicionarProduto",
                        data: dados,
                        dataType: 'json',
                        success: function() {
                            $("#divProdutos").load("<?php echo current_url(); ?> #divProdutos");
                            $("#quantidade").val('');
                            $("#preco").val('');
                            $("#produto").val('').focus();
                        },
                        error: function() {
                            $("#divProdutos").load("<?php echo current_url(); ?> #divProdutos");
                            Swal.fire({
                                type: "error",
                                title: "Atenção",
                                text: "Ocorreu um erro ao tentar adicionar produto."
                            });

**Comment by armeiroairsoft** [comment]
O que tentei já:
Copiei todo o código da pagina editar vendas daqui e substitui pelo da minha página, não tive resultado.
Peguei a parte do javascript da página editar OS que funciona, subistitui pelo javascript da página editar vendas, não tive resultado.
Ai fiz o seguinte, peguei toda parte do javscript da pagina editarOS e substitui por toda parte do javascript do EditarVendas, dai funcionou, porém copiei tudo, então acredito que esteja faltando alguma coisa de javascript na pagina editarVendas certo?

**Comment by armeiroairsoft** [comment]
Estou batendo todo o código entre as páginas, depois que terminar coloco aqui o que resolveu.

**Comment by willph** [comment]
Então faz o seguinte, baixa o código do github e testa aí, e me diz se está funcionando, pode ser?

**Comment by armeiroairsoft** [comment]
já baixei o código e não funcionou.
Achei o problema, mas não sei o pq:
Esse código: `$("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteProduto",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").focus();
            }
        });

        $("#servico").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteServico",
            minLength: 2,
            select: function(event, ui) {
                $("#idServico").val(ui.item.id);
                $("#preco_servico").val(ui.item.preco);
                $("#quantidade_servico").focus();
            }
        });


        $("#cliente").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteCliente",
            minLength: 2,
            select: function(event, ui) {
                $("#clientes_id").val(ui.item.id);
            }
        });`
        Funciona, porém quando coloco o código que está na página original que é esse: `$("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteProdutoSaida",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").focus();
            }
        });
        $("#cliente").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteCliente",
            minLength: 2,
            select: function(event, ui) {
                $("#clientes_id").val(ui.item.id);
            }
        });
        $("#tecnico").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteUsuario",
            minLength: 2,
            select: function(event, ui) {
                $("#usuarios_id").val(ui.item.id);
            }
        });` não funciona mais.

**Comment by willph** [comment]
Falo, fazer instalação do zero. Todo o código do github em zip

**Comment by armeiroairsoft** [comment]
mas foi o que fiz.
O código está todo original, não fiz nenhuma alteração.
Mas achei o problema e já está funcionando normal.
Seguinte, esse código aqui funciona: 
`$("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteProduto",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").focus();
            }
        });`
Está vendo essa linha: index.php/vendas/autoCompleteProduto aqui funciona, porém no código da pagina de venda está assim:
`$("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteProdutoSaida",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").focus();
            }
        });`
Olha essa linha: index.php/vendas/autoCompleteProdutoSaida tem a plavra SAIDA é isso que estava dando problema aqui pra mim.

**Comment by armeiroairsoft** [comment]
Will, velho muito obrigado pelo tempo e empenho em me ajudar, se vc não tivesse falado do javascript eu não teria achado o caminho, realmente muito agradecido pela ajuda e pelo tempo empenhado em me ajudar, muito obrigado.

**Comment by willph** [comment]
> Will, velho muito obrigado pelo tempo e empenho em me ajudar, se vc não tivesse falado do javascript eu não teria achado o caminho, realmente muito agradecido pela ajuda e pelo tempo empenhado em me ajudar, muito obrigado.

De nada.

O que me espanta é o meu código Está funcionando e o seu Não. 

A não ser que seja a versão do servidor/xampp que é diferente do meu

**Comment by armeiroairsoft** [comment]
estou hospedando online, no hostgator.
Outra coisa que percebi que não funciona agora é a parte dos campos observação, escrevi ali e não salvou no banco de dados, ou salvou mas nao puxou para a visualização, vou ver primeiro se salvou no banco de dados...

**Comment by armeiroairsoft** [comment]
Não salvou no banco de dados, onde eu acho a pagina que executa esse comando, que pega o post e escreve no mysql?

**Comment by willph** [comment]
Acredito que é no controller `VENDAS.php`

Da uma olhada na pasta

**Comment by armeiroairsoft** [comment]
Quando vc cria a venda se vc escreve ali no campo de observação, salva, porém ao ir em editar ele carrega as primeiras observações salvas, se clicar em atualizar ele salva vazio no bd, ao editar ele altera as infos salvas pra vazio. Vou dar uma olhada no arquivo que me falou.

**Comment by armeiroairsoft** [comment]
Vou fechar, pois o problema de inserir o produto foi resolvido.
