### ISSUE TITLE
Area do cliente

### ISSUE THREAD

**Issue by AOSHIY** [RamonSilva20/mapos#1082]
Boa tarde, poderia me dizer o caminho que faço para alterar a área do cliente não acho a pasta index

**Comment by willph** [comment]
`mapos/application/views/conecte/`

Se não me falhe a memória esse é o caminho das veiws

**Comment by AOSHIY** [comment]
@willph muito obrigado ,me ajudou muito se não for pertubar muito poderia me ajudar com outra coisa

**Comment by willph** [comment]
Depende. Se estiver ao meu alcance 😁

**Comment by AOSHIY** [comment]
@willph Eu abri um novo pedido era como que colocar a área do cliente para receber anexo
