### ISSUE TITLE
Erro ao adicionar descrição na VENDA

### ISSUE THREAD

**Issue by armeiroairsoft** [RamonSilva20/mapos#1083]
Versão do Mapos: 4.20.2
Navegador Chrome: Versão 87.0.4280.88 (Versão oficial) 64 bits

Ao adicionar uma venda, se escrever algum texto nos campos observações e observações para o cliente esse texto é salvo no banco de dados, ao continuar editando, os textos aparecem, porém ao inserir o produto e clicar em atualizar os textos dos campos somem e olhando no banco de dados os mesmos são apagados, os campos ficam como null.

Link do vídeo explicando o que acontece: https://youtu.be/7PfTIpbwlm8
obs: vídeo não tem som.

**Comment by Pr3d4dor** [comment]
@armeiroairsoft Obrigado por reportar, iremos verificar.

**Comment by Pr3d4dor** [comment]
Corrigido na versão 4.23.0
