### ISSUE TITLE
Cliente anexar arquivos

### ISSUE THREAD

**Issue by AOSHIY** [RamonSilva20/mapos#1084]
fiz esta alteraçao na area do cliente mas nao permite colocar arquivo aqui ainda poderia me ajudar?
![anexo](https://user-images.githubusercontent.com/74568823/102534414-7a342d80-4085-11eb-8ad1-fab33e41716f.png)

**Comment by Pr3d4dor** [comment]
@AOSHIY É bloqueado do cliente anexar arquivos pois poderia ser algo inseguro. Por exemplo eles podem enviar arquivos com vírus e etc.

**Comment by AOSHIY** [comment]
@Pr3d4dor teria como habilitar isso? pois trabalhamos recebendo arquivos

**Comment by AOSHIY** [comment]
@Pr3d4dor sabe me orientar?

**Comment by Pr3d4dor** [comment]
@AOSHIY Qual exatamente é o problema que está ocorrendo?

**Comment by willph** [comment]
> @AOSHIY Qual exatamente é o problema que está ocorrendo?

Ele gostaria de liberar a área do cliente o botão para manda arquivos, anexar feito a área do Administrador

**Comment by AOSHIY** [comment]
@willph Bom como está na foto eu coloquei , na área onde o cliente abre ordem de serviço para ele colocar anexo também mas quando eu seleciono os arquivos não anexa

**Comment by AOSHIY** [comment]
@willph exatamente isso liberar o botão para o cliente anexar arquivos

**Comment by AOSHIY** [comment]
@Pr3d4dor entendeu?

**Comment by Pr3d4dor** [comment]
@AOSHIY Sim entendi, mas vc ainda não relatou pra mim exatamente o erro que aparece no navegador, vc apenas disse que não "anexa". Eu preciso da mensagem específica de erro pra conseguir te ajudar.

**Comment by AOSHIY** [comment]
@Pr3d4dor exatamente não dá erro nenhum fica exatamente como a imagem não faz nada

**Comment by guskid** [comment]
@AOSHIY Você conseguiu fazer esta mudança?
Estou querendo fazer também.

**Comment by AOSHIY** [comment]
@guskid Não consegui não T-T
