### ISSUE TITLE
Exclusão de OS / Vendas dando baixa no estoque.

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1086]
Olá pessoal, recentemente notei que meus produtos estavam sumindo, fui perceber isso ao reproduzir os passos quando eu apagava uma OS.

Isso acontece ao apagar uma OS "não finalizada"  que tenha  produto vinculado a ela. Ou uma venda que não tenha sido finalizada também.

Talvez isso poderia ser resolvido, colocando um bloqueio na hora de apagar uma OS. Ele não deixar até que se desvincule os produtos agregados a ela.

![image](https://user-images.githubusercontent.com/73944522/102801948-5118e300-438c-11eb-901b-fb5a6479c7ad.png)
![image](https://user-images.githubusercontent.com/73944522/102802034-74439280-438c-11eb-93ed-45026ec3fc78.png)
![image](https://user-images.githubusercontent.com/73944522/102802066-81f91800-438c-11eb-9f87-80a5423cfdab.png)
![image](https://user-images.githubusercontent.com/73944522/102802085-8b828000-438c-11eb-80bb-07f039fdc106.png)

Versão: 4.22.0

**Comment by Pr3d4dor** [comment]
@R4T0 Obrigado por reportar, iremos analisar e corrigir se possível.

**Comment by R4T0** [comment]
obrigado cara... boas festas pra vocês



Douglas Tecnologia em Redes
Em Gianluca Bine <notifications@github.com>, 27 de dez de 2020 1:02 PM escreveu:

@R4T0<https://github.com/R4T0> Obrigado por reportar, iremos analisar e corrigir se possível.

**Comment by R4T0** [comment]
Obrigado pessoal. A atualização 4.26.0 resolveu o problema. Agora ao apagar a os com o produto vinculado, ele volta automaticamente para o estoque.
