### ISSUE TITLE
Traduzir o texto de chave única do arquivo form_validation

### ISSUE THREAD

**Issue by hdarantes** [RamonSilva20/mapos#1087]
Existe no arquivo form_validation dentro da pasta CONFIG, nele existe a opção de limitar a chave única como no exemplo is_unique[usuarios.cpf], porém, o texto de erro que apresenta sai em ingles, como eu traduzo ele para português?

Texto que apresenta: The campo field must contain a unique value.

**Comment by Pr3d4dor** [comment]
@hdarantes Acho que essa documentação pode lhe ajudar: https://codeigniter.com/userguide3/libraries/form_validation.html#setting-error-messages
