### ISSUE TITLE
Área do Cliente

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1088]
tem algums dados q estão trocado na visualização das os e vendas na Área do Cliente

![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)

 e alguns estão faltando

![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)

**Comment by willph** [comment]
> tem algums dados q estão trocado na visualização das os e vendas na Área do Cliente
> 
> ![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)
> 
> e alguns estão faltando
> 
> ![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)

Qual versão está usando?

**Comment by marllonferreira** [comment]
> > tem algums dados q estão trocado na visualização das os e vendas na Área do Cliente
> > ![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)
> > e alguns estão faltando
> > ![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)
> 
> Qual versão está usando?

@willph to usando a ultima v4.23.0

**Comment by willph** [comment]
> > > tem algums dados q estão trocado na visualização das os e vendas na Área do Cliente
> > > ![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)
> > > e alguns estão faltando
> > > ![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)
> > 
> > 
> > Qual versão está usando?
> 
> @willph to usando a ultima v4.23.0

Ok. Primeira imagem referente a OS e segunda a venda?

**Comment by marllonferreira** [comment]
> > > > tem algums dados q estão trocado na visualização das os e vendas na Área do Cliente
> > > > ![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)
> > > > e alguns estão faltando
> > > > ![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)
> > > 
> > > 
> > > Qual versão está usando?
> > 
> > 
> > @willph to usando a ultima v4.23.0
> 
> Ok. Primeira imagem referente a OS e segunda a venda?

exatamente nos caso o problema está no telefone do responsável e no e-mail

**Comment by willph** [comment]
Em usuário você preencheu o campo telefone?

**Comment by marllonferreira** [comment]
> Em usuário você preencheu o campo telefone?

sim

**Comment by willph** [comment]
Vou analisar, já ja retorno.

**Comment by marllonferreira** [comment]
> Em usuário você preencheu o campo telefone?

nessa primeira imagem na os no responsável está mostrando telefone e e-mail do cliente
![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)



nessa segunda imagem na vendas no responsável está mostrando telefone corretamente mais não mostra o e-mail
![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)

**Comment by willph** [comment]
> > Em usuário você preencheu o campo telefone?
> 
> nessa primeira imagem na os no responsável está mostrando telefone e e-mail do cliente
> ![01](https://user-images.githubusercontent.com/31580600/102995044-fb187c80-44fe-11eb-976e-79fa8b07a887.PNG)
> 
> nessa segunda imagem na vendas no responsável está mostrando telefone corretamente mais não mostra o e-mail
> ![02](https://user-images.githubusercontent.com/31580600/102995372-a5909f80-44ff-11eb-9fdc-0e5141d66045.PNG)

Em breve eu enviarei a correção desse bug. Aguarde.

Obrigado por avisar.

**Comment by willph** [comment]
Feito a PR #1093 com a correção e algumas melhorias. Quando for aprovado por favor testar e vê se esta tudo ok.

**Comment by marllonferreira** [comment]
> Feito a PR #1093 com a correção e algumas melhorias. Quando for aprovado por favor testar e vê se esta tudo ok.

já testei deu certinho muito obrigado

e parabéns pelas melhorias ficou show

**Comment by willph** [comment]
> > Feito a PR #1093 com a correção e algumas melhorias. Quando for aprovado por favor testar e vê se esta tudo ok.
> 
> já testei deu certinho muito obrigado
> 
> e parabéns pelas melhorias ficou show

De nada. Que bom que conseguiu baixar as atualizações sem a aprovação da PR.
