### ISSUE TITLE
Edita cpf

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1089]
quero sugerir que em Editar Meus Dados na área do cliente
seja desativado a opção de edita Documento

todas as lojas e sites q conheço não tem a opção de edita cpf.

outros dados tudo bem vc pode atualiza a gora cpf e meio difícil só abre a possibilidade para o cliente agir de má fé além do mais se realmente for preciso o cliente pode fazer isso na loja de forma presencial

minha opinião

**Comment by willph** [comment]
> 
> 
> quero sugerir que em Editar Meus Dados na área do cliente
> seja desativado a opção de edita Documento
> 
> todas as lojas e sites q conheço não tem a opção de edita cpf.
> 
> outros dados tudo bem vc pode atualiza a gora cpf e meio difícil só abre a possibilidade para o cliente agir de má fé além do mais se realmente for preciso o cliente pode fazer isso na loja de forma presencial
> 
> minha opinião

Criado uma função em JavaScript para quando for CPF fica desabilitado, mas quando for CNPJ continuar habilitado, pois CNPJ a pessoa pode dar baixa e criar outro novamente.

Esta na PR #1093. Aguarde se vai ser aprovado ou não.

**Comment by marllonferreira** [comment]
> > quero sugerir que em Editar Meus Dados na área do cliente
> > seja desativado a opção de edita Documento
> > todas as lojas e sites q conheço não tem a opção de edita cpf.
> > outros dados tudo bem vc pode atualiza a gora cpf e meio difícil só abre a possibilidade para o cliente agir de má fé além do mais se realmente for preciso o cliente pode fazer isso na loja de forma presencial
> > minha opinião
> 
> Criado uma função em JavaScript para quando for CPF fica desabilitado, mas quando for CNPJ continuar habilitado, pois CNPJ a pessoa pode dar baixa e criar outro novamente.
> 
> Esta na PR #1093. Aguarde se vai ser aprovado ou não.

da um pouco de trabalho copiar o código um por um mais sou meio ansioso kkkk
já testei fichou show muito obrigo

**Comment by willph** [comment]
> > > quero sugerir que em Editar Meus Dados na área do cliente
> > > seja desativado a opção de edita Documento
> > > todas as lojas e sites q conheço não tem a opção de edita cpf.
> > > outros dados tudo bem vc pode atualiza a gora cpf e meio difícil só abre a possibilidade para o cliente agir de má fé além do mais se realmente for preciso o cliente pode fazer isso na loja de forma presencial
> > > minha opinião
> > 
> > 
> > Criado uma função em JavaScript para quando for CPF fica desabilitado, mas quando for CNPJ continuar habilitado, pois CNPJ a pessoa pode dar baixa e criar outro novamente.
> > Esta na PR #1093. Aguarde se vai ser aprovado ou não.
> 
> da um pouco de trabalho copiar o código um por um mais sou meio ansioso kkkk
> já testei fichou show muito obrigo

Que bom que conseguiu baixar tudo.

Agora cuidado, se faltar alguns trechos de código, vai da pau o sistema(bug).
