### ISSUE TITLE
Tem como implementar NFE?

### ISSUE THREAD

**Issue by desmodos** [RamonSilva20/mapos#1090]
Sou Mei e gostaria de um gerenciador financeiro com nfe, é possivel implementar nfe nesse sistema?

**Comment by R4T0** [comment]
Tenho interesse nisso futuramente, mesmo que seja um recurso pago. Gostaria de adquitir futuramente.

**Comment by Pr3d4dor** [comment]
@desmodos É uma coisa útil, porém muito difícil de implementar, pois cada cidade tem uma regra diferente.

Você pode dar uma olhada em: https://github.com/nfephp-org/sped-nfe

**Comment by hoshikawakun** [comment]
algo que poderia ser interessante que ja ajudaria, sei que aki no meu estado (GO) tem o site que vc entra especifico pra emitir a NFCe.
O sistema ti dar tipo em PDF um esboço com as infos da NFCe que vc iria usar pra preencher no site

**Comment by phsilvasantos** [comment]
> Sou Mei e gostaria de um gerenciador financeiro com nfe, é possivel implementar nfe nesse sistema?

me chama no email do github
