### ISSUE TITLE
Adicionar relatório de receitas brutas de Microempreendedor individual

### ISSUE THREAD

**Issue by seitbnao** [RamonSilva20/mapos#1091]
Muitos microempreendedores tem dificuldades de preencher esses relatório em que a SEBRAE disponibiliza.
Segue em anexo o modelo usado pelas prefeituras de SP e outros estados juntamente com o SEBRAE
[relatoriomensal_MEI.pdf](https://github.com/RamonSilva20/mapos/files/5735880/relatoriomensal_MEI.pdf)

**Comment by Pr3d4dor** [comment]
@seitbnao Obrigado pela sugestão, iremos implementar assim que possível.
