### ISSUE TITLE
Login na área do cliente e no administrador

### ISSUE THREAD

**Issue by seitbnao** [RamonSilva20/mapos#1092]
Não sei dizer ao certo se é um bug, mas nos testes me trouxe um desconforto que provavelmente pode ser de outras pessoas:
Quando você esta logado como adm e abre uma nova aba e logue na área do cliente, algumas informações na área do administrador são preenchidas com informações do login do cliente segue em anexo.

Logado no administrador normalmente(antes de logar no cliente)
![Screenshot_3](https://user-images.githubusercontent.com/11374956/103012610-99fea200-451a-11eb-9ee5-94214126fa66.png)

Logado no administrador normalmente(após logar no cliente)
![Screenshasdasdasdot_1](https://user-images.githubusercontent.com/11374956/103012734-c87c7d00-451a-11eb-9fe9-3c10a0aba17b.png)

como pode notar algumas informações na viewer do adm é substituída por informações do cliente logado em outra aba do navegador

**Comment by willph** [comment]
> Não sei dizer ao certo se é um bug, mas nos testes me trouxe um desconforto que provavelmente pode ser de outras pessoas:
> Quando você esta logado como adm e abre uma nova aba e logue na área do cliente, algumas informações na área do administrador são preenchidas com informações do login do cliente segue em anexo.
> 
> Logado no administrador normalmente(antes de logar no cliente)
> ![Screenshot_3](https://user-images.githubusercontent.com/11374956/103012610-99fea200-451a-11eb-9ee5-94214126fa66.png)
> 
> Logado no administrador normalmente(após logar no cliente)
> ![Screenshasdasdasdot_1](https://user-images.githubusercontent.com/11374956/103012734-c87c7d00-451a-11eb-9fe9-3c10a0aba17b.png)
> 
> como pode notar algumas informações na viewer do adm é substituída por informações do cliente logado em outra aba do navegador

É um bug simples.
Mas isso não quer dizer que o cliente tem acesso como administrador. 
É apenas o nome que vem errado mesmo.

**Comment by seitbnao** [comment]
Tranquilo, reportei só pelo desconforto mesmo.

**Comment by willph** [comment]
> Tranquilo, reportei só pelo desconforto mesmo.

Eu ainda não resolve esse bug. 😁
