### ISSUE TITLE
Servicos e produtos mais vendidos

### ISSUE THREAD

**Issue by luiscadeira** [RamonSilva20/mapos#1094]
Ola,

A possibilidade de implementar no painel, os 10 produtos e serviços mais vendidos?

**Comment by Pr3d4dor** [comment]
@luiscadeira sim é possível, iremos colocar na lista de features

**Comment by willph** [comment]
> Ola,
> 
> A possibilidade de implementar no painel, os 10 produtos e serviços mais vendidos?

Seria em formato de gráficos, feito o relatório de vendas?

**Comment by luiscadeira** [comment]
@willph ele pode ficar no Painel mesmo.
tipo a lista 5 ou 10 produtos e serviços mais vendido.

ideal seria coluna 

Produtos outra ao lado serviços
![lista](https://user-images.githubusercontent.com/60495545/103254779-7c3f9b80-4965-11eb-9388-b9dd54cacfa0.jpg)

**Comment by luiscadeira** [comment]
[ordem .zip](https://github.com/RamonSilva20/mapos/files/5749407/ordem.zip)

Olha esse sistema anexo
