### ISSUE TITLE
Geração de boleto quando o usuário é uma PJ ou MEI

### ISSUE THREAD

**Issue by seitbnao** [RamonSilva20/mapos#1095]
Fiz alguns teste de validação e há um erro, quando o cliente é uma pessoa jurídica o CNPJ é enviado no campo cpf da api do boleto, informando um código de erro:

Codigo: | 3500034
validation_error
[object Object]

o link de pagamento funcionou. Só a geração de boleto que ocorreu o erro

**Comment by willph** [comment]
Cadastro como CNPJ no Gerencianet?

**Comment by willph** [comment]
Como não tinha conta com CNPJ esse erro poderia ocorre mesmo.

va no arquivo gerencianetsdk.php e altere a linha    63         

`'cpf' => $cpfClient, // cpf válido do cliente`

para

`'cnpj' => $cpfClient, // cpf válido do cliente`

e me diga se funcionou.

Ja ja envio a correção.

**Comment by willph** [comment]
Confunde as bolas kkkk

O cadastro do cliente é CNPJ?

Vou fazer a correção, porque só testei cadastro do cliente com CPF e esquece que pode ser CNPJ.

**Comment by willph** [comment]
Corrigido, só aguarda aprovação da PR #1096.

Obrigado por nós avisar sobre essa falha.

**Comment by cabralwms** [comment]
Como gerar o link de pagamento ou boleto o meu nao consegui fazer. Será que faltou algo para implantar isso?

**Comment by willph** [comment]
> Como gerar o link de pagamento ou boleto o meu nao consegui fazer. Será que faltou algo para implantar isso?

Tem que ter cadastro na Gerencianet. 

E pegar os dados da API, client id e client secret é cadastrar no menu pagamento no Mapos

**Comment by willph** [comment]
Lembrando que ainda está em modo sandbox, para todos irem testando afim de corrigir todos os bugs que apareça, para que depois mude o endpoint para produção. 

Agora se você quiser alterar já para o modo produção é só falar que te digo onde é, caso não encontre. Ok @seitbnao

**Comment by cabralwms** [comment]
Esse Gerencianet, tem algum custo?

**Comment by willph** [comment]
> Esse Gerencianet, tem algum custo?

Sim e pode ser conferido no site deles. E dependendo do seu fluxo, você pode negociar uma tarifa melhor. 

https://gerencianet.com.br/tarifas/

**Comment by seitbnao** [comment]
@willph  complicado por que não tenho uma noção de como vocês vão ou querem está organizando esses pagamentos, vou ver oque posso fazer para contribuir

**Comment by willph** [comment]
> @willph complicado por que não tenho uma noção de como vocês vão ou querem está organizando esses pagamentos, vou ver oque posso fazer para contribuir

Tem alguma sugestão?

Prototipa sua idéia, que eu levo pra turma.
Se cada um de nós dermos um tempinho do nosso tempo livre, vai da pra deixar esses sistema TOP.

Obrigado desde já, por disponibilizar um pouco do seu tempo com o sistema.

**Comment by seitbnao** [comment]
@willph , não sei se aqui é o local correto para tirar esta dúvida, estou trabalhando no protótipo para organizar estes pagamentos
e estou incluindo retorno de status, cancelamento e baixa pela api da Genrencianet, só q estou me deparando com esse erro e não consigo visualizar oque tá errado [ 
![Screenshot_1](https://user-images.githubusercontent.com/11374956/103287952-8b086b80-49c2-11eb-9689-ec1010981c86.png)


código utilizado

`public function retornarStatus($charge_id,$client_Id,$client_Secret)
    {
        $clientId = $client_Id;
        $clientSecret = $client_Secret;
        $options = [
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'sandbox' => true
        ];

        $options_parms = [
            
            'id' => (int)$charge_id,
             
        ];
 
          try {
            $api = new Gerencianet($options);
            $charge = $api->detailCharge([],$options_parms);
            return json_encode($charge);
        } catch (GerencianetException $e) {
            $error = array("code" => $e->code, "error" => $e->error, "errorDescription" => $e->errorDescription);
            return json_encode($error);
        } catch (Exception $e) {
            $error = array("error" => "Error", "errorDescription" => $e->getMessage());
            return json_encode($error);
        }
    
    }`

**Comment by willph** [comment]
O campo tem que ser inteiro. Só converter a string para INT

Em ter, 29 de dez de 2020 10:43, SeiTbNao - Djunio <notifications@github.com>
escreveu:

**Comment by willph** [comment]
Obrigado de ante mão. 
Toda a ajuda é bem vinda.

**Comment by seitbnao** [comment]
@willph , eu estava passando o parm no local errado rsr, já tive alguns avanços

![Screenshot_3](https://user-images.githubusercontent.com/11374956/103306369-25c97000-49ec-11eb-9f0b-4eb55534df10.png)
![Screenshot_4](https://user-images.githubusercontent.com/11374956/103306373-26fa9d00-49ec-11eb-8889-09ee8c8a8c8c.png)

**Comment by willph** [comment]
Olha ai que maravilha. Show de bola

**Comment by willph** [comment]
> @willph , eu estava passando o parm no local errado rsr, já tive alguns avanços
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/11374956/103306373-26fa9d00-49ec-11eb-8889-09ee8c8a8c8c.png)

Criado no menu pagamento um Submenu Ou foi feito em outro local?

**Comment by seitbnao** [comment]
@willph  foi um submenu do financeiro

**Comment by willph** [comment]
> @willph foi um submenu do financeiro

Certo.
Aguarda sua PR com as alterações.

**Comment by seitbnao** [comment]
> > @willph foi um submenu do financeiro
> 
> Certo.
> Aguarda sua PR com as alterações.

Nice, já enviei a PR #1102

**Comment by willph** [comment]
Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?

**Comment by willph** [comment]
> > > @willph foi um submenu do financeiro
> > 
> > 
> > Certo.
> > Aguarda sua PR com as alterações.
> 
> Nice, já enviei a PR #1102

Muito obrigado por sua contribuição ao projeto.

**Comment by seitbnao** [comment]
>Certo.
>Aguarda sua PR com as alterações.

Tranquilo mano, é um baita aprendizado também.

> Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?

Não fiz a parte da notificação, ainda to me adequando com a api, pretendo esta colocando isso, tive algumas dificuldades em lógica na ideia mesmo. Tipo, uma venda teria que ser faturada para q depois seja possível gerar a cobrança?, se a cobrança foi gerada e a venda não foi faturada como vai proceder? tive essas dúvidas

**Comment by willph** [comment]
> > Certo.
> > Aguarda sua PR com as alterações.
> 
> Tranquilo mano, é um baita aprendizado também.
> 
> > Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?
> 
> Não fiz a parte da notificação, ainda to me adequando com a api, pretendo esta colocando isso, tive algumas dificuldades em lógica na ideia mesmo. Tipo, uma venda teria que ser faturada para q depois seja possível gerar a cobrança?, se a cobrança foi gerada e a venda não foi faturada como vai proceder? tive essas dúvidas

Pensei que como ele usava o ID do boleto gerado, teria a possibilidade de vê de forma manual.
Ao clicar em atualiza, puxava os status mais recente.

**Comment by willph** [comment]
Com relação a sua pergunta, acredito que o @RamonSilva20 possa explicar melhor essas questões.

**Comment by seitbnao** [comment]
> > > Certo.
> > > Aguarda sua PR com as alterações.
> > 
> > 
> > Tranquilo mano, é um baita aprendizado também.
> > > Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?
> > 
> > 
> > Não fiz a parte da notificação, ainda to me adequando com a api, pretendo esta colocando isso, tive algumas dificuldades em lógica na ideia mesmo. Tipo, uma venda teria que ser faturada para q depois seja possível gerar a cobrança?, se a cobrança foi gerada e a venda não foi faturada como vai proceder? tive essas dúvidas
> 
> Pensei que como ele usava o ID do boleto gerado, teria a possibilidade de vê de forma manual.
> Ao clicar em atualiza, puxava os status mais recente.

Sim ao clicar em atualizar, o status atual é atualizado, só faltou implementar a baixa dos lançamentos caso o retorno seja de pagamento efetuado

**Comment by willph** [comment]
Falei com o @RamonSilva20 e ele vai tirar sua dúvida assim que possível.

Obrigado.

Em qua, 30 de dez de 2020 13:08, SeiTbNao - Djunio <notifications@github.com>
escreveu:

**Comment by RamonSilva20** [comment]
> > Certo.
> > Aguarda sua PR com as alterações.
> 
> Tranquilo mano, é um baita aprendizado também.
> 
> > Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?
> 
> Não fiz a parte da notificação, ainda to me adequando com a api, pretendo esta colocando isso, tive algumas dificuldades em lógica na ideia mesmo. Tipo, uma venda teria que ser faturada para q depois seja possível gerar a cobrança?, se a cobrança foi gerada e a venda não foi faturada como vai proceder? tive essas dúvidas

Acho que o ideal seria que essa cobrança fosse o próprio lançamento ou então relacionado a ele. O problema maior é que essa forma de faturar não está correta, não estamos realmente criando uma fatura com os itens cobrados, somente alteramos uma flag na venda informando que foi faturada e criamos os lançamentos.

**Comment by seitbnao** [comment]
> > > Certo.
> > > Aguarda sua PR com as alterações.
> > 
> > 
> > Tranquilo mano, é um baita aprendizado também.
> > > Aí se o pagamento for aprovado, quando clicar em atualiza vai aparecer status aprovado?
> > 
> > 
> > Não fiz a parte da notificação, ainda to me adequando com a api, pretendo esta colocando isso, tive algumas dificuldades em lógica na ideia mesmo. Tipo, uma venda teria que ser faturada para q depois seja possível gerar a cobrança?, se a cobrança foi gerada e a venda não foi faturada como vai proceder? tive essas dúvidas
> 
> Acho que o ideal seria que essa cobrança fosse o próprio lançamento ou então relacionado a ele. O problema maior é que essa forma de faturar não está correta, não estamos realmente criando uma fatura com os itens cobrados, somente alteramos uma flag na venda informando que foi faturada e criamos os lançamentos.

Agora consegui entender o por que buguei nas ideias kk, obg.


@willph  estava olhando as issues fechadas, havia muita gente pedindo pu espiculando como fazer o mapos funcionar como multi-usuário vou me aventurar nisso já comecei mecher no banco.

![Screenshot_7](https://user-images.githubusercontent.com/11374956/103369191-422ae280-4aa8-11eb-8c62-ba919244cd21.png)

**Comment by willph** [comment]
Como é gerado a cobrança?

Na venda?
Na OS?

Como é o fluxo?

**Comment by seitbnao** [comment]
> Como é gerado a cobrança?
> 
> Na venda?
> Na OS?
> 
> Como é o fluxo?

![Screenshot_8](https://user-images.githubusercontent.com/11374956/103376983-d2732280-4abc-11eb-81f6-18da5294b631.png)
acredito que a venda é amarrada ao lançamento, primeiro geramos a venda no momento que gera a venda já é para gerar o lançamento sem baixa, no momento que o pagamento é efetuado a baixa é realizada  e o lançamento entra como , caso fique com inadimplência receita é dada como negativa a parte de lançamentos do sistema não é errada, por que da para colocar receitas e despesas a parte. Bom vou deixar um fluxograma para trocarmos ideias.
@RamonSilva20
@willph

**Comment by willph** [comment]
> 
> 
> > Como é gerado a cobrança?
> > Na venda?
> > Na OS?
> > Como é o fluxo?
> 
> ![Screenshot_8](https://user-images.githubusercontent.com/11374956/103376983-d2732280-4abc-11eb-81f6-18da5294b631.png)
> acredito que a venda é amarrada ao lançamento, primeiro geramos a venda no momento que gera a venda já é para gerar o lançamento sem baixa, no momento que o pagamento é efetuado a baixa é realizada e o lançamento entra como , caso fique com inadimplência receita é dada como negativa a parte de lançamentos do sistema não é errada, por que da para colocar receitas e despesas a parte. Bom vou deixar um fluxograma para trocarmos ideias.
> @RamonSilva20
> @willph

Aqui o arquivo update_4.24.0_to_4.24.1.sql deu erro

` #1005 - Não pode criar a tabela `mapos-teste`.`cobrancas` (erro no. 150 "Foreign key constraint is incorrectly formed") (Informações…)`

**Comment by seitbnao** [comment]
> > > Como é gerado a cobrança?
> > > Na venda?
> > > Na OS?
> > > Como é o fluxo?
> > 
> > 
> > ![Screenshot_8](https://user-images.githubusercontent.com/11374956/103376983-d2732280-4abc-11eb-81f6-18da5294b631.png)
> > acredito que a venda é amarrada ao lançamento, primeiro geramos a venda no momento que gera a venda já é para gerar o lançamento sem baixa, no momento que o pagamento é efetuado a baixa é realizada e o lançamento entra como , caso fique com inadimplência receita é dada como negativa a parte de lançamentos do sistema não é errada, por que da para colocar receitas e despesas a parte. Bom vou deixar um fluxograma para trocarmos ideias.
> > @RamonSilva20
> > @willph
> 
> Aqui o arquivo update_4.24.0_to_4.24.1.sql deu erro
> 
> `#1005 - Não pode criar a tabela`mapos-teste`.`cobrancas` (erro no. 150 "Foreign key constraint is incorrectly formed") (Informações…)`

Vou da commit pra ajeitar, ta o anexo ai
[update_4.24.0_to_4.24.1.zip](https://github.com/RamonSilva20/mapos/files/5755514/update_4.24.0_to_4.24.1.zip)

**Comment by willph** [comment]
Com a correção agora funcionou ao gerar o boleto, a função cobrança. 

Você criou o arquivo migrations? Lá na pasta `application-》database-》migrations`

A versão não seria 4.25.0, porque criou uma função nova?
E no arquivo config.....

Eu também me atrapalho com essas coisas 😁

**Comment by willph** [comment]
Não sei se fiz algo errado, mas aqui não funcionou visualizar boleto. 

Gerei também um boleto em visualizarOS e não apareceu em cobrança. 

Lá só aparece se for de vendas?

**Comment by seitbnao** [comment]
> Não sei se fiz algo errado, mas aqui não funcionou visualizar boleto.
> 
> Gerei também um boleto em visualizarOS e não apareceu em cobrança.
> 
> Lá só aparece se for de vendas?

Caramba, passou batido não reparei que na OS gera boleto também, vou estar vendo isso e a parte do migration

**Comment by willph** [comment]
> > Não sei se fiz algo errado, mas aqui não funcionou visualizar boleto.
> > Gerei também um boleto em visualizarOS e não apareceu em cobrança.
> > Lá só aparece se for de vendas?
> 
> Caramba, passou batido não reparei que na OS gera boleto também, vou estar vendo isso e a parte do migration

Deixei alguns comentários de sugestões para alterações na sua Pull request. 

Relaxa, eu as vezes faço isso também 😁

**Comment by willph** [comment]
Como o bug dessa issue já foi corrigido, irei finalizar. 
Qualquer coisa é só abrir novamente ou criar uma nova, caso o assunto seja diferente.
