### ISSUE TITLE
Geração de Boleto acidental

### ISSUE THREAD

**Issue by seitbnao** [RamonSilva20/mapos#1097]
Fiz alguns testes, seria interessante salvar  ou linkar de alguma forma o boleto gerado na venda, para q o mesmo não seja gerado novamente de forma acidental, se tenho uma venda gero o boleto e entro novamente na venda e vou em gerar boleto, não tem nenhuma validação de que o boleto já foi gerado neste caso será gerado +1 boleto

Seria bom uma tabela para salvar os dados do pagamento gerado por exemplo o retorno da geração do boleto:
`barcode: "00000.00000 00000.000000 00000.000000 0 00000000000000"
charge_id: 1219166
expire_at: "2020-12-31"
link: "https://visualizacaosandbox.gerencianet.com.br/emissao/xxxxxxxxxxxxxxxxxxx"
payment: "banking_billet"
pdf: {charge: "https://download.gerencianet.com.br/xxxxxxxxxxxx.pdf?sandbox=true"}
status: "waiting"
total: 40000`

**Comment by willph** [comment]
> Fiz alguns testes, seria interessante salvar ou linkar de alguma forma o boleto gerado na venda, para q o mesmo não seja gerado novamente de forma acidental, se tenho uma venda gero o boleto e entro novamente na venda e vou em gerar boleto, não tem nenhuma validação de que o boleto já foi gerado neste caso será gerado +1 boleto
> 
> Seria bom uma tabela para salvar os dados do pagamento gerado por exemplo o retorno da geração do boleto:
> `barcode: "00000.00000 00000.000000 00000.000000 0 00000000000000" charge_id: 1219166 expire_at: "2020-12-31" link: "https://visualizacaosandbox.gerencianet.com.br/emissao/xxxxxxxxxxxxxxxxxxx" payment: "banking_billet" pdf: {charge: "https://download.gerencianet.com.br/xxxxxxxxxxxx.pdf?sandbox=true"} status: "waiting" total: 40000`

Estamos planejando reorganizar a parte de pagamento, em configurações e no bd também. 

Caso seja programado, e puder nos ajudar enviando uma PR, ficaríamos muito grato.

Se tiver tempo livre é lógico. 

Desde já obrigado por sua sugestão.

**Comment by willph** [comment]
Tem bugs ao tentar gerar  um mesmo boleto 2 vezes.

acredito que houve uma mudança na lógica ao gerar json
A verificação até funciona, mas a mensagem de erro não vem em JSON.

Fora isso alguns dados não esta sendo salvo no banco de dados.
Referente a sua PR #1102

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    success http://localhost/mapos/assets/js/script-payments.js:39
    jQuery 6
    <anonymous> http://localhost/mapos/assets/js/script-payments.js:32
    jQuery 9
    <anonymous> http://localhost/mapos/assets/js/script-payments.js:25
```

**Comment by willph** [comment]
Vou finalizar essa issue porque você já corrigiu esse bug.

Obrigado pela correção!
