### ISSUE TITLE
Ajuda no desenvolvimento 

### ISSUE THREAD

**Issue by jocieldo** [RamonSilva20/mapos#110]
Gostaria de ajudar no desenvolvimento do novo mapos. Poderiam me passar mais detalhes? Existe algum cronograma? Algum mapeamento do que fazer? Podem entrar em contato comigo.
jocieldo@live.com

 Vlw

**Comment by mariolucasdev** [comment]
Também gostaria de contribuir. 

mariolucasdev@gmail.com

**Comment by edgarmeireles** [comment]
Gostaria de contribuir, porém como não tenho muita habilidade no desenvolvimento, me proponho a criar os tutoriais de todas as funções e detalhamento dos processos que o sistema faz.
