### ISSUE TITLE
Nao consigo editar o CPF cliente 

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#1100]
Apos a ultima atualizacao nao consigo editar mais os CPFs dos clientes (no CNPJ esta normal). Quando entro vou na pagina de edcao, escolho o cliente pessoa fisica e altero o endereco e em seguida atualizar aparece a mensagem "The CPF/CNPJ field is required." e apaga o endereco cadastrado 

Gostaria muito que fizessem um modulo de busca de clientes para facilitar a edicao.

Obrigado

**Comment by willph** [comment]
Tem a imagem?

**Comment by willph** [comment]
Já identifiquei, a falha.

Em breve será corrigida. 

Com relação a edição do CPF, a maioria dos sistemas não é permitido a edição do CPF, pois o CPF uma vez cadastrado não tem porque alterar, até porque o número de CPF não muda.

**Comment by fwsund** [comment]
verdade, o cpf cadastrado nao muda. Mas o endeco apagar apos a atualizacao que atrapalha o cadastro do cliente

**Comment by willph** [comment]
> verdade, o cpf cadastrado nao muda. Mas o endeco apagar apos a atualizacao que atrapalha o cadastro do cliente

Será corrigido a falha que está impedido a atualização

**Comment by fwsund** [comment]
obrigado

**Comment by willph** [comment]
Correção enviada, você pode colocar o código do arquivo funcoes.js que esta na PR #1101 que já vai funcionar.

**Comment by fwsund** [comment]
subi a ultima atualizacao na funcoes.js da linha 10 a 24
mas ainda esta apresentado erro "The CPF/CNPJ field is required."

**Comment by fwsund** [comment]
![Sem título](https://user-images.githubusercontent.com/55247088/103304337-23b0e280-49e7-11eb-8394-23cf729ec1ad.jpg)

**Comment by willph** [comment]
Remova as linha 13, 20 e 21. Onde tem escrito desabled

**Comment by fwsund** [comment]
https://user-images.githubusercontent.com/55247088/103304443-6c689b80-49e7-11eb-8a9f-3a161280b184.mp4

**Comment by willph** [comment]
Você esqueceu de remover as linha que indicava na PR.

**Comment by willph** [comment]
Você deletou as linha que mencionei?

Em ter, 29 de dez de 2020 15:07, Franklin <notifications@github.com>
escreveu:

**Comment by fwsund** [comment]
agora deu certo!!

**Comment by fwsund** [comment]
obrigado e parabens pelo desenvolvimento!

**Comment by augustocoletti** [comment]
@willph, entendo e concordo com as colocações sobre alteração de cpf de cliente, mas há um problema, ao menos no meu caso. Nem todos os clientes fornecem o CPF no momento da abertura da OS e é complicado forçar, já tentei varios argumentos, mas nem sempre obtive sucesso. Sendo assim, acabo colocando números aleatórios pois seguindo uma orientação na issue #763 e depois, caso o cliente deseje NF, eu edito ele e deixo o cadastro certinho.
Minha pergunta é se posso continuar assim e quais alterações posso fazer ou existe a intenção de colocar uma função de bloqueio de CPF nas configurações do sistema?
Grato.

**Comment by willph** [comment]
> 
> 
> @willph, entendo e concordo com as colocações sobre alteração de cpf de cliente, mas há um problema, ao menos no meu caso. Nem todos os clientes fornecem o CPF no momento da abertura da OS e é complicado forçar, já tentei varios argumentos, mas nem sempre obtive sucesso. Sendo assim, acabo colocando números aleatórios pois seguindo uma orientação na issue #763 e depois, caso o cliente deseje NF, eu edito ele e deixo o cadastro certinho.
> Minha pergunta é se posso continuar assim e quais alterações posso fazer ou existe a intenção de colocar uma função de bloqueio de CPF nas configurações do sistema?
> Grato.

No seu caso infelizmente terá que remover a função que se encontra no arquivo `funcoes.js` que se encontra na pasta `assets/js`

``` $(function () {
    if ($('.cpfcnpj').val() != null) {
        var cpfcnpj = $('.cpfcnpj').val().length;
        if (cpfcnpj == "14") {
            $(".cpfcnpj").prop('readonly', true);
        }
    }
    if ($('.cpfUser').val() != null) {
        var cpfUser = $('.cpfUser').val().length;
        if (cpfUser == "14") {
            $(".cpfUser").prop('readonly', true);
        }
    }

}); ```

**Comment by augustocoletti** [comment]
show de bola, já resolve, agradeço!

**Comment by willph** [comment]
> show de bola, já resolve, agradeço!

Agora teste pra vê se aparecerá alguma falha. 

Apesar que o certo é cadastrar o cpf.

Qual seu ramo de atividade?

**Comment by augustocoletti** [comment]
tenho uma loja de manutenção de impressoras e Informática. Tenho dois CNPJs lá, um em meu nome e outro MEI pra emissão de NF de serviço. Portanto tudo que é serviço, lanço no MAPOS e o que é produtos, no sistema da loja.

**Comment by willph** [comment]
> tenho uma loja de manutenção de impressoras e Informática. Tenho dois CNPJs lá, um em meu nome e outro MEI pra emissão de NF de serviço. Portanto tudo que é serviço, lanço no MAPOS e o que é produtos, no sistema da loja.
> è um jeitinho pra pagar menos imposto.

Então, o pessoa sabe que é necessário CPF para esse tipo de serviços, e não quer colocar. 😁

**Comment by augustocoletti** [comment]
Sabe sim... 
mas trabalhar com pessoas é complicado, algumas  acham que tem razão em tudo, não respeitam regras e procedimentos de ninguém e ainda por cima falam mal de vc sem ao menos ter feito o serviço.
Aconteceu isso, chegou um rapaz com um equipamento e pedi seus dados e mesmo explicando o porquê de tudo, ele não quis nem mais deixar o equipamento e ainda disse que eu estava desconfiando dele, o que não fez sentido algum pois eu já o conhecia de outra data/serviço. Acabou levando em um amigo que me falou que ele contou uma historia absurda, então mostrei a filmagem da loja pra mostrar a mentira do cara. 
Desde então, peço o CPF, se o cara quer dar blz, senão, peço pro cliente assinar na RAT um campo onde diz que o cliente não quis informar dados pessoais.

**Comment by willph** [comment]
O povo aí é complicado einh 😁

**Comment by willph** [comment]
Caso necessite de mais alguma informação com relação a essa issue, é só reabrir. 
Se o assunto for diferente, só abrir uma nova issue.
