### ISSUE TITLE
Alterar notificações

### ISSUE THREAD

**Issue by seitbnao** [RamonSilva20/mapos#1103]
Se fosse possível alterar a forma atual das notificações para um modelo de notificações em toasts 
[https://getbootstrap.com/docs/4.2/components/toasts/](url)
Não manjo muito de HTML se não ia me aventurar ^^

+/- assim
`$this->session->set_flashdata('toast', 'Você não tem permissão para visualizar vendas.');`
Exemplo canto superior direito
![Screenshot_6](https://user-images.githubusercontent.com/11374956/103364833-7f3da780-4a9d-11eb-8eca-a92627d36b7b.png)

**Comment by willph** [comment]
Está sendo usado na migração do Mapos para Laravel. Bootstrap mais recente. 
Só não tenho 100% de certeza.

@Pr3d4dor poderá explicar melhor. 

https://github.com/map-os/mapos

**Comment by willph** [comment]
Parece que foi adicionado o sistema de notificação do sweetalert2.
Apesar que não foi migrado 100% do sistema ainda.
