### ISSUE TITLE
Não consigo FATURAR

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#1104]
** Descreva o bug **
Ao finalizar uma OS no momento de salvar como faturado ocorre tudo CERTO, mas ao tentar faturar (adicionar o recebimento do pagamento) simplismente surgi a mensagem de erro 
                
 "Atenção
Ocorreu um erro ao tentar faturar OS.

             OK"

Versão do sistema 4.24

**Comment by willph** [comment]
> 
> 
> ** Descreva o bug **
> Ao finalizar uma OS no momento de salvar como faturado ocorre tudo CERTO, mas ao tentar faturar (adicionar o recebimento do pagamento) simplismente surgi a mensagem de erro
> 
> "Atenção
> Ocorreu um erro ao tentar faturar OS.
> 
> ```
>          OK"
> ```
> 
> Versão do sistema 4.24

Você atualizou o banco de dados?
Pois tem campo novo, e precisa ser adicionado no banco de dados!

**Comment by CarlosCavalcante87** [comment]
Deu certo quando fiz a atualização, obrigado 👏👏👏👏

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by willph** [comment]
Certo.
Qualquer coisa, só reabrir essa issue ou criar uma nova se for algo diferente.

**Comment by dawis2021** [comment]
Eu estou com mesmo problema, e demais erros gostaria de tentar a atualização, o meu mapos esta instalado no hostinger alguem tem um link explicando como proceder a atualização.
Obs.: Quando atualizo pela plataforma do sistema apresenta erro.

**Comment by CarlosCavalcante87** [comment]
A resposta que tive foi para atualizar o banco de dados... Daí resolvel

Carlos Cavalcante Informática


________________________________

**Comment by dawis2021** [comment]
Você não consegui solucionar seu problema? o meu aqui é hospedado no hostinger

**Comment by CarlosCavalcante87** [comment]
Já consegui, fazendo o que eu comentei de atualizar o banco de dados. Algo tão simples mas não tinha essa informação daí já viu a dificuldade rsrs

Carlos Cavalcante Informática


________________________________

**Comment by evertonterra** [comment]
esta ocorrendo o mesmo problema com o meu sistema , ja atualizei o banco de dados. porém o problema continua, sera que tem como fazer um downgrade de versão
