### ISSUE TITLE
BUG menu cobrança

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1107]
Estou testando o menu cobrança e ao clicar nele, ele some da seleção. Quando clicamos em outros menus eles se mantem visivel e o cobrança ao clicar abre do lado direito mais sobe do menu. acredito ser coisa simples apenas um erro simples né?

**Comment by marllonferreira** [comment]
não intendi como funciona esse novo recuso

**Comment by willph** [comment]
> 
> 
> Estou testando o menu cobrança e ao clicar nele, ele some da seleção. Quando clicamos em outros menus eles se mantem visivel e o cobrança ao clicar abre do lado direito mais sobe do menu. acredito ser coisa simples apenas um erro simples né?

Isso ocorre porque ele foi criado como se fosse um Menu principal, e não como se fosse parte do menu financeiro.

basta editar o controller `cobrancas.php` na pasta `application/controller`

e colocar esse código abaixo da linha 20 `$this->data['menuFinanceiro'] = 'cobrancas';` que já resolve

**Comment by cabralwms** [comment]
Muito obrigado willph vou fazer aqui a modificação grato pela atenção

**Comment by cabralwms** [comment]
Fiz aqui deu certinho muito obrigado.

**Comment by seitbnao** [comment]
Boa tarde a correção já foi inserida na PR #1111

**Comment by seitbnao** [comment]
> não intendi como funciona esse novo recuso
Boa tarde, funciona da seguinte forma, todas as cobranças que forem emitidas em OS e vendas por meio de boleto ou link usando a gerencianet serão cadastrados no menu cobranças para que você possa visualizar os status puxar boleto , cancelar ou confirmar pagamento.
