### ISSUE TITLE
erro a pós a instalação

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1108]
fiz instalação depois que fiz o login ficou assim não aparece o menu
![mapos 01](https://user-images.githubusercontent.com/31580600/103568492-63267580-4ea4-11eb-8a79-1a0be09fc034.PNG)

me parece um problema de permissão

**Comment by marllonferreira** [comment]
fui fui usar meu banco de dados na hora de usa o arquivo 

update_4.24.0_to_4.25.0

da esse erro 

![mapos 02](https://user-images.githubusercontent.com/31580600/103570151-52c3ca00-4ea7-11eb-8c2b-058c8946f2b5.PNG)

depois disso o menu lateral voltou mais não abre o menu cobranças imagino q seja por não te criado as tabelas

**Comment by willph** [comment]
> 
> 
> fui fui usar meu banco de dados na hora de usa o arquivo
> 
> update_4.24.0_to_4.25.0
> 
> da esse erro
> 
> ![mapos 02](https://user-images.githubusercontent.com/31580600/103570151-52c3ca00-4ea7-11eb-8c2b-058c8946f2b5.PNG)
> 
> depois disso o menu lateral voltou mais não abre o menu cobranças imagino q seja por não te criado as tabelas

vá na tabela permissoes e confira se esta esse código no campo `permissoes`

`a:53:{s:8:"aCliente";s:1:"1";s:8:"eCliente";s:1:"1";s:8:"dCliente";s:1:"1";s:8:"vCliente";s:1:"1";s:8:"aProduto";s:1:"1";s:8:"eProduto";s:1:"1";s:8:"dProduto";s:1:"1";s:8:"vProduto";s:1:"1";s:8:"aServico";s:1:"1";s:8:"eServico";s:1:"1";s:8:"dServico";s:1:"1";s:8:"vServico";s:1:"1";s:3:"aOs";s:1:"1";s:3:"eOs";s:1:"1";s:3:"dOs";s:1:"1";s:3:"vOs";s:1:"1";s:6:"aVenda";s:1:"1";s:6:"eVenda";s:1:"1";s:6:"dVenda";s:1:"1";s:6:"vVenda";s:1:"1";s:9:"aGarantia";s:1:"1";s:9:"eGarantia";s:1:"1";s:9:"dGarantia";s:1:"1";s:9:"vGarantia";s:1:"1";s:8:"aArquivo";s:1:"1";s:8:"eArquivo";s:1:"1";s:8:"dArquivo";s:1:"1";s:8:"vArquivo";s:1:"1";s:10:"aPagamento";s:1:"1";s:10:"ePagamento";s:1:"1";s:10:"dPagamento";s:1:"1";s:10:"vPagamento";s:1:"1";s:11:"aLancamento";s:1:"1";s:11:"eLancamento";s:1:"1";s:11:"dLancamento";s:1:"1";s:11:"vLancamento";s:1:"1";s:8:"cUsuario";s:1:"1";s:9:"cEmitente";s:1:"1";s:10:"cPermissao";s:1:"1";s:7:"cBackup";s:1:"1";s:10:"cAuditoria";s:1:"1";s:6:"cEmail";s:1:"1";s:8:"cSistema";s:1:"1";s:8:"rCliente";s:1:"1";s:8:"rProduto";s:1:"1";s:8:"rServico";s:1:"1";s:3:"rOs";s:1:"1";s:6:"rVenda";s:1:"1";s:11:"rFinanceiro";s:1:"1";s:9:"aCobranca";s:1:"1";s:9:"eCobranca";s:1:"1";s:9:"dCobranca";s:1:"1";s:9:"vCobranca";s:1:"1";}`

**Comment by marllonferreira** [comment]
eu usei uma copia do meu bando ai funcionou tudo indica realmente q era as permissões

depois q entrei fui em sistema atualiza banco de dados ai o menu de cobrança também funcionou

só não entendi como ele funciona

me da uma dica por favor

**Comment by willph** [comment]
> 
> 
> fui fui usar meu banco de dados na hora de usa o arquivo
> 
> update_4.24.0_to_4.25.0
> 
> da esse erro
> 
> ![mapos 02](https://user-images.githubusercontent.com/31580600/103570151-52c3ca00-4ea7-11eb-8c2b-058c8946f2b5.PNG)
> 
> depois disso o menu lateral voltou mais não abre o menu cobranças imagino q seja por não te criado as tabelas

Com relação ao banco de dados aqui funcionou tranquilo, apague o campo cobrança no bd e tente esse.

```
CREATE TABLE `cobrancas` (
  `idCobranca` int(11) NOT NULL,
  `charge_id` int(11) DEFAULT NULL,
  `conditional_discount_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `custom_id` int(11) DEFAULT NULL,
  `expire_at` date NOT NULL,
  `message` varchar(255) NOT NULL,
  `payment_method` varchar(11) DEFAULT NULL,
  `payment_url` varchar(255) DEFAULT NULL,
  `request_delivery_address` varchar(64) DEFAULT NULL,
  `status` varchar(36) NOT NULL,
  `total` varchar(15) DEFAULT NULL,
  `barcode` varchar(255) NOT NULL,
  `link` varchar(255) NOT NULL,
  `payment` varchar(64) NOT NULL,
  `pdf` varchar(255) DEFAULT NULL,
  `vendas_id` int(11) DEFAULT NULL,
  `os_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`idCobranca`),
  INDEX `fk_cobrancas_os1` (`os_id` ASC),
  CONSTRAINT `fk_cobrancas_os1` FOREIGN KEY (`os_id`) REFERENCES `os` (`idOs`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  INDEX `fk_cobrancas_vendas1` (`vendas_id` ASC),
  CONSTRAINT `fk_cobrancas_vendas1` FOREIGN KEY (`vendas_id`) REFERENCES `vendas` (`idVendas`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```

**Comment by willph** [comment]
> 
> 
> eu usei uma copia do meu bando ai funcionou tudo indica realmente q era as permissões
> 
> depois q entrei fui em sistema atualiza banco de dados ai o menu de cobrança também funcionou
> 
> só não entendi como ele funciona
> 
> me da uma dica por favor

Ele aparece as cobranças geradas do botão GERAR PAGAMENTO em VENDA e em OS, mas para isso precisa ter o cadastro no gerencianet e cadastra no mapos o client id e o client secret.

**Comment by marllonferreira** [comment]
> > eu usei uma copia do meu bando ai funcionou tudo indica realmente q era as permissões
> > depois q entrei fui em sistema atualiza banco de dados ai o menu de cobrança também funcionou
> > só não entendi como ele funciona
> > me da uma dica por favor
> 
> Ele aparece as cobranças geradas do botão GERAR PAGAMENTO em VENDA e em OS, mas para isso precisa ter o cadastro no gerencianet e cadastra no mapos o client id e o client secret.

entendi
tambem vai funciona com o mercado pago

**Comment by marllonferreira** [comment]
> > fui fui usar meu banco de dados na hora de usa o arquivo
> > update_4.24.0_to_4.25.0
> > da esse erro
> > ![mapos 02](https://user-images.githubusercontent.com/31580600/103570151-52c3ca00-4ea7-11eb-8c2b-058c8946f2b5.PNG)
> > depois disso o menu lateral voltou mais não abre o menu cobranças imagino q seja por não te criado as tabelas
> 
> Com relação ao banco de dados aqui funcionou tranquilo, apague o campo cobrança no bd e tente esse.
> 
> ```
> CREATE TABLE `cobrancas` (
>   `idCobranca` int(11) NOT NULL,
>   `charge_id` int(11) DEFAULT NULL,
>   `conditional_discount_date` date DEFAULT NULL,
>   `created_at` datetime DEFAULT NULL,
>   `custom_id` int(11) DEFAULT NULL,
>   `expire_at` date NOT NULL,
>   `message` varchar(255) NOT NULL,
>   `payment_method` varchar(11) DEFAULT NULL,
>   `payment_url` varchar(255) DEFAULT NULL,
>   `request_delivery_address` varchar(64) DEFAULT NULL,
>   `status` varchar(36) NOT NULL,
>   `total` varchar(15) DEFAULT NULL,
>   `barcode` varchar(255) NOT NULL,
>   `link` varchar(255) NOT NULL,
>   `payment` varchar(64) NOT NULL,
>   `pdf` varchar(255) DEFAULT NULL,
>   `vendas_id` int(11) DEFAULT NULL,
>   `os_id` int(11) DEFAULT NULL,
>   PRIMARY KEY (`idCobranca`),
>   INDEX `fk_cobrancas_os1` (`os_id` ASC),
>   CONSTRAINT `fk_cobrancas_os1` FOREIGN KEY (`os_id`) REFERENCES `os` (`idOs`) ON DELETE NO ACTION ON UPDATE NO ACTION,
>   INDEX `fk_cobrancas_vendas1` (`vendas_id` ASC),
>   CONSTRAINT `fk_cobrancas_vendas1` FOREIGN KEY (`vendas_id`) REFERENCES `vendas` (`idVendas`) ON DELETE NO ACTION ON UPDATE NO ACTION
> ) ENGINE = InnoDB DEFAULT CHARSET = utf8;
> ```
agora usei no phpmyadmin e deu no mesmo
![mapos 03](https://user-images.githubusercontent.com/31580600/103578910-295e6a80-4eb6-11eb-8a44-e7b6a8b02eb9.PNG)

**Comment by willph** [comment]
> > > eu usei uma copia do meu bando ai funcionou tudo indica realmente q era as permissões
> > > depois q entrei fui em sistema atualiza banco de dados ai o menu de cobrança também funcionou
> > > só não entendi como ele funciona
> > > me da uma dica por favor
> > 
> > 
> > Ele aparece as cobranças geradas do botão GERAR PAGAMENTO em VENDA e em OS, mas para isso precisa ter o cadastro no gerencianet e cadastra no mapos o client id e o client secret.
> 
> entendi
> tambem vai funciona com o mercado pago

Não. Apenas do Gerencianet.

**Comment by willph** [comment]
Pera. Vou exportar é posto aqui. Tendo exportado não tem como da erro.
Só importar.

Agora precisa deletar a tabela cobrança

**Comment by willph** [comment]
Renomear a extensão para cobrancas.1**.SQL**

[cobrancas(1).txt](https://github.com/RamonSilva20/mapos/files/5766779/cobrancas.1.txt)

ou pode abrir o texto e copiar todo o codigo, colar e executar.

**Comment by willph** [comment]
Pode remover o campo `clientes_id`, pois isso foi um teste que fiz aqui

**Comment by willph** [comment]
Ou pode baixar esse. Já removi os campos hehehe

[cobrancas(2).txt](https://github.com/RamonSilva20/mapos/files/5766806/cobrancas.2.txt)

Renomear a extensão para cobrancas(2)**.SQL**
ou pode abrir o texto e copiar todo o código, colar e executar.

**Comment by marllonferreira** [comment]
esse foi o resultado para o cobrancas.1**.SQL**
![mapos 04](https://user-images.githubusercontent.com/31580600/103580450-fa95c380-4eb8-11eb-81a3-0790896f582e.PNG)

**Comment by marllonferreira** [comment]
> Baixar esse que já removi os campos hehehe
> 
> [cobrancas(2).txt](https://github.com/RamonSilva20/mapos/files/5766806/cobrancas.2.txt)
> 
> Renomear a extensão para cobrancas(2)**.SQL**
> ou pode abrir o texto e copiar todo o código, colar e executar.

deu resultado semelhante

se tiver tempo posso te da cesso remoto via AnyDesk

**Comment by willph** [comment]
> 
> 
> esse foi o resultado para o cobrancas.1**.SQL**
> ![mapos 04](https://user-images.githubusercontent.com/31580600/103580450-fa95c380-4eb8-11eb-81a3-0790896f582e.PNG)

Se esse não funcionar então não sei qual o erro  porque aqui esta funcionando tranquilo.

cobrancas(2).txt

deletou a tabela cobrança antes?

**Comment by marllonferreira** [comment]
> > esse foi o resultado para o cobrancas.1**.SQL**
> > ![mapos 04](https://user-images.githubusercontent.com/31580600/103580450-fa95c380-4eb8-11eb-81a3-0790896f582e.PNG)
> 
> Se esse não funcionar então não sei qual o erro porque aqui esta funcionando tranquilo.
> 
> cobrancas(2).txt
> 
> deletou a tabela cobrança antes?

sim

**Comment by willph** [comment]
![16097955163368414432708960430337](https://user-images.githubusercontent.com/17226802/103581184-4bf28280-4eba-11eb-81e4-7abcdad37327.jpg)

**Comment by marllonferreira** [comment]
nao ta igual 

![mapos 05](https://user-images.githubusercontent.com/31580600/103581602-17cb9180-4ebb-11eb-8b41-ac69f62597af.PNG)

**Comment by willph** [comment]
> nao ta igual
> 
> ![mapos 05](https://user-images.githubusercontent.com/31580600/103581602-17cb9180-4ebb-11eb-8b41-ac69f62597af.PNG)

Verifica as colunas venda_id e depois os_id para vê se está assim. Se não tiver coloque.

![16097960887503682966243282441485](https://user-images.githubusercontent.com/17226802/103581909-a2ac8c00-4ebb-11eb-8481-a98e3f543b3a.jpg)

![16097961567287044434128340889017](https://user-images.githubusercontent.com/17226802/103581966-ba841000-4ebb-11eb-8924-486d8e05c892.jpg)

**Comment by marllonferreira** [comment]
> Verifica as colunas venda_id e depois os_id para vê se está assim. Se não tiver coloque.
> 
> ![16097960887503682966243282441485](https://user-images.githubusercontent.com/17226802/103581909-a2ac8c00-4ebb-11eb-8481-a98e3f543b3a.jpg)
> 
> ![16097961567287044434128340889017](https://user-images.githubusercontent.com/17226802/103581966-ba841000-4ebb-11eb-8924-486d8e05c892.jpg)

ta igual

**Comment by marllonferreira** [comment]
eu subir o código em etapas descobrir que ta dando erro e na ultima parte do código
![mapos 06](https://user-images.githubusercontent.com/31580600/103582922-90cbe880-4ebd-11eb-9373-42299c761202.PNG)

**Comment by willph** [comment]
> eu subir o código em etapas descobrir que ta dando erro e na ultima parte do código
> ![mapos 06](https://user-images.githubusercontent.com/31580600/103582922-90cbe880-4ebd-11eb-9373-42299c761202.PNG)

Tenta adicionar manualmente as FKs pra vê qual dos dois da erro, se é em OS id ou venda Id

**Comment by marllonferreira** [comment]
nao sei se coloquei certo mais tentei assim deu erro
```
ALTER TABLE `cobrancas`
  ADD CONSTRAINT `fk_cobrancas_vendas1` FOREIGN KEY (`vendas_id`) REFERENCES `vendas` (`idVendas`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;
```


assim também deu erro
```
ALTER TABLE `cobrancas`
  ADD CONSTRAINT `fk_cobrancas_os1` FOREIGN KEY (`os_id`) REFERENCES `os` (`idOs`) ON DELETE NO ACTION ON UPDATE NO ACTION,
COMMIT;
```

**Comment by willph** [comment]
Tem uma nova PR para ser aprovada, vamos espera para vê se resolve seu problema.

**Comment by marllonferreira** [comment]
acabei de testa
e o seguinte a instalação ocorreu tudo bem o problema de permissão foi resolvido
na hora de coloca meu backup ta dando o mesmo erro

primeiro limpo o banco de dados depois 
depois coloco meu banco atual
**to usando a 4.20.1**
depois adiciono
update_4.23.0_to_4.24.0
ate aqui tudo certo

porem quando adiciono update_4.24.0_to_4.25.0

dessa vez não e marquina virtual usei meu servido real e deu o mesmo erro
![admin](https://user-images.githubusercontent.com/31580600/103684446-5409fb00-4f6a-11eb-8377-23b64b6e6303.PNG)

**Comment by willph** [comment]
> acabei de testa
> e o seguinte a instalação ocorreu tudo bem o problema de permissão foi resolvido
> na hora de coloca meu backup ta dando o mesmo erro
> 
> primeiro limpo o banco de dados depois
> depois coloco meu banco atual
> **to usando a 4.20.1**
> depois adiciono
> update_4.23.0_to_4.24.0
> ate aqui tudo certo
> 
> porem quando adiciono update_4.24.0_to_4.25.0
> 
> dessa vez não e marquina virtual usei meu servido real e deu o mesmo erro
> ![admin](https://user-images.githubusercontent.com/31580600/103684446-5409fb00-4f6a-11eb-8377-23b64b6e6303.PNG)

Vou fazer uma instalação do zero. E já dou retorno.

**Comment by willph** [comment]
Sim.

Foi bloqueado para administrador.
Uma vez cadastrado o CPF não tem pra que alterar.

A não ser que crie um check-box para quando o cliente não quiser dizer ele
fica desativado, aí você poderá informar depois

Em ter, 5 de jan de 2021 15:56, Marllon Ferreira <notifications@github.com>
escreveu:
