### ISSUE TITLE
Cadastrar metodo de pagamento gerencianet?

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1113]
Pessoal bom dia, A todos. Estou tentando criar o método de pagamento com gerencianet e nao consegui. Criei a aplicação no site ele me da Cliente_id e cliente_secret colouquei em cobracas, e deixei como padrao mas ele fala que vai gerar por exemplo o boleto e some. devo ter esquecido algo alguem que ja fez consegue orientar?

**Comment by willph** [comment]
Qual a versão do seu Mapos?

**Comment by cabralwms** [comment]
Estou utilizando essa ultima versão 25.1
com mercado pago deu certo

**Comment by willph** [comment]
> Estou utilizando essa ultima versão 25.1
> com mercado pago deu certo

Vou baixa é instalar aqui e te digo. Inclusive tenho que da a resposta lá no grupo whatsapp também

**Comment by cabralwms** [comment]
tem um grupo no Whatsapp que legal, seria possivel adicionar um link para incluir o grupo ou se quiser eu passo meu numero.
Grato pela atenção.

**Comment by willph** [comment]
Você atualizou as tabelas?
Pois tem campos novos.

**Comment by cabralwms** [comment]
Sim foi atualizado.

**Comment by willph** [comment]
> Sim foi atualizado.

Tem como manda o print 

> Sim foi atualizado.

Aqui funcionou tranquilo o boleto e o link de pagamento.

**Comment by cabralwms** [comment]
O gerencianet me forneceu apenas Client_ID e Client_secret é normal só preciso disso? o Mercado pago deu certo me manda preencher algusn dados e fazer o boleto, eu só não terminei para confirmar.

**Comment by willph** [comment]
> O gerencianet me forneceu apenas Client_ID e Client_secret é normal só preciso disso? o Mercado pago deu certo me manda preencher algusn dados e fazer o boleto, eu só não terminei para confirmar.

Sim, só precisa desses 2 o resto deixa em branco. 
Você pegou o código relativo a desenvolvimento ou pegou o de produção?

**Comment by cabralwms** [comment]
Peguei o Codigo produção.

**Comment by willph** [comment]
> Peguei o Codigo produção.

Então foi isso.

Por enquanto deixamos em modo sandbox, para poder identificar os erros, para só quando estiver 100% liberar modo produção. 

Coloque o código de desenvolvimento e teste novamente por favor. 


https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by cabralwms** [comment]
Muito obrigado vou fazer o teste aqui

**Comment by cabralwms** [comment]
Fiz o teste agora com tudo certinho obrigado pela ajuda deu certo, esta gerando o boleto e o link com o codigo de desemvolvimento.
