### ISSUE TITLE
informaçao de baixa financeira

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#1114]
Solicito que apareça a informação de quem deu a devida baixa

ex:  o titulo no financeiro esta como "pendente" ao usuario, colocar como "pago" apareça a informaçao de quem informou o pagamento, dessa forma, controlar quem recebeu valores...

![issui](https://user-images.githubusercontent.com/69607468/103927699-8d24a580-50f9-11eb-93ee-c3391c04dbed.png)

**Comment by seitbnao** [comment]
Acredito para que isso funcione da melhor forma possível teríamos de implementar PDV no mapos, alguma outra sugestão @willph ?

**Comment by willph** [comment]
> Acredito para que isso funcione da melhor forma possível teríamos de implementar PDV no mapos, alguma outra sugestão @willph ?

Se ele escreve de uma forma mais educada, até analiso, caso contrário vai ser ignorado.

**Comment by Pr3d4dor** [comment]
@willph Não me pareceu que ele escreveu de uma forma não educada, ele tinha pedido pra mim no whatsapp essa feature e eu falei para ele criar uma issue.

**Comment by willph** [comment]
> @willph Não me pareceu que ele escreveu de uma forma não educada, ele tinha pedido pra mim no whatsapp essa feature e eu falei para ele criar uma issue.

Então esqueceu de me avisar kkkkk.

**Comment by willph** [comment]
> @willph Não me pareceu que ele escreveu de uma forma não educada, ele tinha pedido pra mim no whatsapp essa feature e eu falei para ele criar uma issue.

Pra mim que não estava sabendo, pareceu.
Mas, jogo que segue 😁
