### ISSUE TITLE
Flag financeiro

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#1115]
solicito um flag na aba financeira "negociaçao"
para clientes em negociação, no caso inadimplentes...

se possivel claro !

**Comment by seitbnao** [comment]
Olá, caso a PR #1111  seja aprovada, essa feature entrará em vigor

**Comment by R4T0** [comment]
#1111 Porém já existe esse aba. Cobranças; só que não funciona ainda
