### ISSUE TITLE
Servidor local funciona somente no primeiro pc

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#1116]
Servidor local funciona somente no primeiro PC, onde esta instalador o Docker.
Ate abre no meu computador, mas tipo, fica sem as imagens, logos como anexado nas capturas de telas abaixo.
Poderia me ajudar? E tambem, teria como fixar um link sem utilizar o localhost? Pois seria somente para uso interno da rede
![image](https://user-images.githubusercontent.com/73778547/104030319-ff54c300-51a9-11eb-94a6-3fc280c6206f.png)
![image](https://user-images.githubusercontent.com/73778547/104030388-14c9ed00-51aa-11eb-9775-03b40e66bfc8.png)

**Comment by willph** [comment]
> Servidor local funciona somente no primeiro PC, onde esta instalador o Docker.
> Ate abre no meu computador, mas tipo, fica sem as imagens, logos como anexado nas capturas de telas abaixo.
> Poderia me ajudar? E tambem, teria como fixar um link sem utilizar o localhost? Pois seria somente para uso interno da rede
> ![image](https://user-images.githubusercontent.com/73778547/104030319-ff54c300-51a9-11eb-94a6-3fc280c6206f.png)
> ![image](https://user-images.githubusercontent.com/73778547/104030388-14c9ed00-51aa-11eb-9775-03b40e66bfc8.png)

A primeira foto está com HTTPS?

**Comment by CarlosRezini** [comment]
Não, esse é o link da primeira foto

http://192.168.0.111:8000/index.php/login

**Comment by willph** [comment]
> Não @willph, esse é o link da primeira foto
> 
> http://192.168.0.111:8000/index.php/login

Tem firewall?

**Comment by CarlosRezini** [comment]
@willph Esta habilitado nos 2 computadores o firewall

**Comment by willph** [comment]
> @willph Esta habilitado nos 2 computadores o firewall

O link adicionado no arquivo config.php é o mesmo que está tentando acessar?

**Comment by CarlosRezini** [comment]
Esta assim la

$config['base_url'] = 'http://localhost:8000/';

**Comment by willph** [comment]
> Esta assim la
> 
> $config['base_url'] = 'http://localhost:8000/';

Coloca no local de localhost o IP da máquina que está tentando. 

`$config['base_url'] = 'http://192.168.0.111:8000/';`

**Comment by CarlosRezini** [comment]
Eu não acredito que era só isso kkkk vlw, muito obrigado!

Eu abri uma vez uma pergunta, pois tipo, esta tudo configurado certo que é pra enviar email né, so que tipo, ele não manda nada de email pra nenhum que cadastrei la dos clintes. Poderia me ajudar tambem?

**Comment by CarlosRezini** [comment]
@willph Eu não acredito que era só isso kkkk vlw, muito obrigado!

Eu abri uma vez uma pergunta, pois tipo, esta tudo configurado certo o que é pra enviar e-mail, só que tipo, ele não manda nada de email pra nenhum que cadastrei lá dos clientes. Poderia me ajudar também? Só que não aparece nada em logs

**Comment by CarlosRezini** [comment]
![image](https://user-images.githubusercontent.com/73778547/104088901-d8010300-5248-11eb-8226-0dfd30e2766e.png)
![image](https://user-images.githubusercontent.com/73778547/104088908-f0711d80-5248-11eb-931a-12d3f6f03bab.png)
![image](https://user-images.githubusercontent.com/73778547/104088914-0088fd00-5249-11eb-8179-378710f4e103.png)

**Comment by CarlosRezini** [comment]
E esta ativado para apps menos seguros la na conta do google do dudu123contato....

**Comment by CarlosRezini** [comment]
Se tiver um email que possa passar para conversarmos melhor pra descobrir esse erro

**Comment by willph** [comment]
> Se tiver um email que possa passar para conversarmos melhor pra descobrir esse erro

Você pode encontrar no grupo do Whatsapp

**Comment by CarlosRezini** [comment]
@willph Pode me passar o link?

**Comment by willph** [comment]
https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by CarlosRezini** [comment]
Entrei la vlw
