### ISSUE TITLE
Trocar AUTOCOMPLETE por um SELECT que já vem carregado do BD

### ISSUE THREAD

**Issue by fabioemersonp** [RamonSilva20/mapos#112]
Olá á todos,
Sou da época do "antigo ASP" e nunca havia me interessado por PHP, hoje precisando de um sistema me deparei com o MAPOS do Ramon e fiquei deslumbrado,
mas confesso que apanho muito pois na minha época não haviam controllers, views, models... era tudo em uma coisa só! rsrsrs

Enfim...
Na página OS > Aba Produtos > Campo PRODUTO
Troquei o AUTOCOMPLETE por um SELECT que já vem carregado com as opções de produtos cadastrados no BD, porém não consigo ADICIONAR, pois preciso passar os devidos valores para os inputs "hidden"

Alguém pode me ajudar ?

Um abraço e mais uma vez obrigado !

**Comment by Pr3d4dor** [comment]
Você pode usar JavaScript por meio do método onChange do jQuery para cada vez que ocorrer uma mudança no select setar os valores nos devidos inputs hidden.

Por exemplo:

```
$('#idDoMeuSelect').on('change', function() { 
            $("#idProduto").val(ID DO PRODUTO AQUI);
            $("#estoque").val(ESTOQUE DO PRODUTO AQUI);
            $("#preco").val(PRECO DO PRODUTO AQUI);
            $("#quantidade").focus();
})
```
Quando você gerar o select no banco nas opçoes do select é possível usar atributos data-* e assim ficaria mais fácil a implementação:

Fonte: https://www.w3schools.com/tags/att_global_data.asp

```
 <select>
  // o FOR ou FOREACH do PHP aqui
  <option value="<?php echo $produto->preco; ?>" data-id="<?php echo $produto->id; ?>" data-estoque="<?php echo $produto->estoque; ?>"> <?php echo $produto->nome; ?> </option>
// FIM FOR ou FOREACH do PHP
</select> 
```

Assim a implementação do JavaScript ficaria:
```
$('#idDoMeuSelect').on('change', function() {
            var id = $('option:selected', this).data('id');
            var estoque = $('option:selected', this).data('estoque');
            var preco = $('option:selected', this).val()
 
            $("#idProduto").val(id);
            $("#estoque").val(estoque);
            $("#preco").val(preco);
            $("#quantidade").focus();
})
```

Exemplo no JSFiddle: https://jsfiddle.net/uw62nw69/1/
