### ISSUE TITLE
Bug na pagina de lançamento(financeiro) pos atualização 

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#1125]
Cliquei em financeiro lançamentos aparece a seguinte pagina, e outra atualizei a versão continua antiga em cima...
https://prnt.sc/wk6yus

**Comment by willph** [comment]
Você atualizou o banco de dados?

Em dom, 10 de jan de 2021 07:24, matheuscorteletti <notifications@github.com>
escreveu:

**Comment by matheuscorteletti** [comment]
@willph cliquei em atualizar e nada mudou...

**Comment by matheuscorteletti** [comment]
@willph Sistema > Configura > Atualizar banco...

**Comment by willph** [comment]
Depois de clicar em atualizar banco de dados a falha se mantém?

Em dom, 10 de jan de 2021 07:31, matheuscorteletti <notifications@github.com>
escreveu:

**Comment by matheuscorteletti** [comment]
×Banco de dados atualizado com sucesso!

**Comment by matheuscorteletti** [comment]
O sistema já tá com as funcões novas porém continua quando abre o financeiro e a versão em cima tá errada, tem algum comando para eu rodar no banco?

**Comment by willph** [comment]
Consegui atualiza usando o arquivo que tem em updates?

**Comment by matheuscorteletti** [comment]
Eu rodo um por um ou somente esse ? update_4.25.1_to_4.26.0
Minha versão era 4.10.0 
Outra dúvida queria mudar para https procurei no banco e  n achei..

**Comment by matheuscorteletti** [comment]
Resolvi dando esse update update_4.25.1_to_4.26.0

**Comment by willph** [comment]
É no arquivo config.php.

Como você clicou em atualizar banco.

Só update_4.25.1_to_4.26.0 esse mesmo

Em dom, 10 de jan de 2021 07:50, matheuscorteletti <notifications@github.com>
escreveu:

**Comment by matheuscorteletti** [comment]
Agora a versão continua antiga e queria ver o lance do https

**Comment by matheuscorteletti** [comment]
Vou olhar

**Comment by matheuscorteletti** [comment]
Versão corrigida na config.php

**Comment by willph** [comment]
> 
> 
> Agora a versão continua antiga e queria ver o lance do https



> 
> 
> Versão corrigida na config.php

nesse mesmo arquivo você corrige para https

$config['base_url'] = 'enter_baseurl';

**Comment by matheuscorteletti** [comment]
ERR_SSL_PROTOCOL_ERROR

**Comment by matheuscorteletti** [comment]
Sendo que tenho ssl
