### ISSUE TITLE
Ordem dos clientes, produtos, cobranças...

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1128]
Boa tarde pessoal. Após essa atualização 26.1 percebi que ao clicar em clientes por exemplo aparece 10 do primeiro para o último. Vendas a mesma coisa. Conflito com as configurações do sistema que no meu caso esta 50 linhas. Mas acredito que deveria aparecer da última venda para a primeira. Assim como os clientes. E também na parte de cobrança eu acho que se aparecer tbm o nome do cliente ficaria mais fácil para encontrar caso tenha muitas cobranças no dia. 
De resto parabéns pelas novas funções ficaram ótimas.

**Comment by R4T0** [comment]
Como você configurou para funcionar essas cobranças? Apenas duvidas porque pra mim não funciona.

**Comment by cabralwms** [comment]
Eu configurei com dados da Gerencianet, mas apenas para desenvolvimento seria apenas teste, sem valor comercial ainda entendeu. Precisa atualizar e rodar os UPDATES do banco de dados para dar certo.

**Comment by cabralwms** [comment]
Um dos integrantes do grupo me passou a solução que resolveu o problema.

segue o codigo. no arquivo /mapos/application/views/tema/rodape.php


<div class="row-fluid">
    <div id="footer" class="span12"> <a href="https://github.com/RamonSilva20/mapos" target="_blank">
        <?= date('Y'); ?> &copy; Map-OS - Ramon Silva </a></div>
  </div>
  
  <script src="<?= base_url(); ?>assets/js/bootstrap.min.js"></script>
  <script src="<?= base_url(); ?>assets/js/matrix.js"></script>
</body>
<script type="text/javascript">
    $(document).ready(function() {
        $('#tabela').dataTable( {
            "language": {
                "url": "<?= base_url(); ?>assets/js/dataTable_pt-br.json"
    },
    "ordering": false
        } );
} );
</script>
</html>
