### ISSUE TITLE
Bug na aba de cobranças 

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#1131]
NO painel do cliente ao clicar em cobrança da o seguinte erro https://prnt.sc/wl6g5c

**Comment by mikxingu** [comment]
Estou com o mesmo problema. Ocorre tanto quando clico em lançamentos financeiros quanto em cobrança.
Pelo que li, é alguma coisa relacionada ao banco de dados. Vou dar uma fuçada aqui pra ver se descubro o que é, mas esperar o pessoal mais experiente ver o que está acontecendo.

![erro mapos](https://user-images.githubusercontent.com/30123586/104225089-acd30b00-5424-11eb-842f-32ac31cd56f4.png)

**Comment by matheuscorteletti** [comment]
> Estou com o mesmo problema. Ocorre tanto quando clico em lançamentos financeiros quanto em cobrança.
> Pelo que li, é alguma coisa relacionada ao banco de dados. Vou dar uma fuçada aqui pra ver se descubro o que é, mas esperar o pessoal mais experiente ver o que está acontecendo.
> 
> ![erro mapos](https://user-images.githubusercontent.com/30123586/104225089-acd30b00-5424-11eb-842f-32ac31cd56f4.png)

sobre o de lançamento resolvi rodando o ultimo update direto no phpmyadmin...

**Comment by mikxingu** [comment]
Exatamente. Fiz a mesma coisa e deu certo. Tinha clicado em atualizar banco pela aba Sistema>Atualizar BD, ele dá sucesso na atualização mas provavelmente não está fazendo puxando o último arquivo de update.
Obrigado de qualquer forma.

**Comment by matheuscorteletti** [comment]
o seu resolveu o da cobrança?

**Comment by mikxingu** [comment]
Aparentemente sim. Consigo clicar na aba cobranças e ele abre sem erro nenhum. Só avisa que não existe cobrança cadastrada. Estou procurando como faz pra cadastrar uma cobrança. Mas meu financeiro agora está funcionando normalmente.

**Comment by matheuscorteletti** [comment]
Aqui não :X

**Comment by mikxingu** [comment]
Mas continua dando o mesmo erro da foto?

**Comment by matheuscorteletti** [comment]
Sim

**Comment by seitbnao** [comment]
> Aparentemente sim. Consigo clicar na aba cobranças e ele abre sem erro nenhum. Só avisa que não existe cobrança cadastrada. Estou procurando como faz pra cadastrar uma cobrança. Mas meu financeiro agora está funcionando normalmente.

Uma cobrança não é cadastrada, ela é gerada quando você utiliza a api GenrenciaNet, neste caso você pode gerar os boletos ou links de pagamentos em OS ou vendas então a cobrança será gerada

**Comment by mikxingu** [comment]
> > Aparentemente sim. Consigo clicar na aba cobranças e ele abre sem erro nenhum. Só avisa que não existe cobrança cadastrada. Estou procurando como faz pra cadastrar uma cobrança. Mas meu financeiro agora está funcionando normalmente.
> 
> Uma cobrança não é cadastrada, ela é gerada quando você utiliza a api GenrenciaNet, neste caso você pode gerar os boletos ou links de pagamentos em OS ou vendas então a cobrança será gerada

Ahh, entendi agora porque não consigo cadastrar nem criar boletos.
Obrigado!!
Entao @matheuscorteletti , o meu aqui ta funcionando 100%
