### ISSUE TITLE
Atualização pela aplicação

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1132]
Ao atualizar pelo sistema, ele está me retornando a seguinte mensagem.
![image](https://user-images.githubusercontent.com/73944522/104222676-02091f80-5419-11eb-892d-53d61fcbd480.png)

Estou atualizando da 4.26.1 para 4.26.2.
![image](https://user-images.githubusercontent.com/73944522/104222576-e4d45100-5418-11eb-939b-f0f6b21be12a.png)

**Comment by Pr3d4dor** [comment]
@R4T0 O atualizador do sistema tem alguns bugs que precisam ser corrigidos, por isso sempre atualize manualmente por enquanto.
