### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by vinnyparker** [RamonSilva20/mapos#1133]
Olá pessoal. Eu fiz download do codigo da ultima release. rodei o comando em minha maquina, "composer install --no-dev "
depois q instalou tudo, eu subi o codigo todo pra minha hospedagem na hostgator. 
Criei um banco vazio, e na hora q eu acesso a url: assistencia.xhost.net.br, da a seguinte mensagem: 
Arquivo de configuraÃ§Ã£o nÃ£o encontrado!
Alguem tem ideia do que pode ser?

**Comment by R4T0** [comment]
Para mim funcionou assim.
1> criar banco vazio
2> rodar composer
3> instalação no Browser e funciona

**Comment by vinnyparker** [comment]
> Para mim funcionou assim.
> 1> criar banco vazio
> 2> rodar composer
> 3> instalação no Browser e funciona

mas tu instalou no browser  local e depois subiu pro host, ou instalou no host? pq eu n tenho como rodar composer no host. (nao q eu saiba) entao eu instalei na minha maquina e depois eu subi tudo e fui instalar via browser

**Comment by R4T0** [comment]
Não entendi muito a pergunta. Mas criei um banco zerado.... Rodei o composer na máquina. Depois acessei a instalação pelo browser e funcionou.

**Comment by vinnyparker** [comment]
em minha maquina tbm funcionou, mas no host nao funcionou. quando eu vou instalar da o erro descrito acima
