### ISSUE TITLE
pagina de impressão a4

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#1136]
bom dia, 

solicito aos prezados senhores(se possível), uma customização da pagina a4 de vendas via que entregamos ao cliente, deixar ela mais chamativa/intuitiva 

desde ja agradeço !!!

abaixo um exemplo:

[TESTE DE PEDIDOS.pdf](https://github.com/RamonSilva20/mapos/files/5802369/TESTE.DE.PEDIDOS.pdf)

**Comment by willph** [comment]
Ideia é boa.

Em ter, 12 de jan de 2021 10:39, vksaghaz <notifications@github.com>
escreveu:

**Comment by vksaghaz** [comment]
vlw kkkkkk
