### ISSUE TITLE
erro de baixa em estoques ao faturar OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1137]
se a OS esta em Orçamento ao add um produto ele realmente não da baixa no estoque
se altero o status da os de orçamento para aprovado ele não da baixa no estoque
se add algum produto em alguma OS que esteja em qualker outro tipo de status que não seja Orçamnto ele da baixa no estoque

se pego uma OS em Orçamento, add um produto, cliente aprova, mudo o status para Aprovado, depois faturo essa OS, ela não da baixa no estoque

se ao faturar eu add um produto quando estava em orçamento e outro quando estava em aprovado a baixa do estoque e somente do que foi add qando a OS estava aprovada, o que foi add enquanto era orçamento ela não e dado baixa no estoque

**Comment by seitbnao** [comment]
Isso não é um bug, ainda não foi implementado a atualização do estoque ao mudar o status da Os

**Comment by R4T0** [comment]
@hoshikawakun Desculpe amigo, mas na minha indagação, o produto só deve realmente dar baixa no estoque quando o produto for faturado/lançado o pagamento como recebido no financeiro. Caso contrario você estaria dando baixa de um produto, que nem foi concretizada a venda. a Lógica é (Entra receita - Sai produto). Pelo menos nos testes que estou fazendo na versão 4.26.1 está tudo normal, dando baixa apenas quando o pagamento e realizado.
Neste exemplo faturei 2 un de correia dentada
![image](https://user-images.githubusercontent.com/73944522/104484661-ee3bf580-559f-11eb-9788-27ebf7fc2e02.png)

O sistema não precisa dar baixa, pois não houve pagamento algum para que ela não seja mais minha.
![image](https://user-images.githubusercontent.com/73944522/104484755-09a70080-55a0-11eb-97f7-0246dc182bde.png)

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Desculpe amigo, mas na minha indagação, o produto só deve realmente dar baixa no estoque quando o produto for faturado/lançado o pagamento como recebido no financeiro. Caso contrario você estaria dando baixa de um produto, que nem foi concretizada a venda. a Lógica é (Entra receita - Sai produto). Pelo menos nos testes que estou fazendo na versão 4.26.1 está tudo normal, dando baixa apenas quando o pagamento e realizado.
> Neste exemplo faturei 2 un de correia dentada
> ![image](https://user-images.githubusercontent.com/73944522/104484661-ee3bf580-559f-11eb-9788-27ebf7fc2e02.png)
> 
> O sistema não precisa dar baixa, pois não houve pagamento algum para que ela não seja mais minha.
> ![image](https://user-images.githubusercontent.com/73944522/104484755-09a70080-55a0-11eb-97f7-0246dc182bde.png)

a questao e que mesmo faturando a OS o item que foi add quando estava em orçamento nao e dado baixa

**Comment by hoshikawakun** [comment]
por fim retirei as linhas no codigo que faziam esse sistema e fiquei no modo antigo mesmo

**Comment by p-francelino** [comment]
Amigos estou com o mesmo problema, no meu caso ja com o produto fatura o estoque não dá baixa.

**Comment by R4T0** [comment]
da uma olhada na sua versão do sistema. Pois isso já foi corrigido nas versões mais atuais. 4.26~



Douglas Tecnologia em Redes
Em p-francelino <notifications@github.com>, 20 de jan de 2021 1:13 PM escreveu:

Amigos estou com o mesmo problema, no meu caso ja com o produto fatura o estoque não dá baixa.
