### ISSUE TITLE
Baixa dos Lançamentos no financeiro

### ISSUE THREAD

**Issue by octaralves** [RamonSilva20/mapos#1140]
Se possível seria muito útil ter uma restrição ao editar os lançamentos no financeiros para não permitir lançar um pagamento com data inferir e nem superior ao do dia da edição a fim de controlar melhor os pagamentos evitando manipulação de dados por parte do usuário.

Por exemplo:
Ao controlar o faturamento no fechamento do mês pode acontecer de um mal intencionado editar um pagamento do mês anterior e colocar para o mês vigente fraudado o total do mês.

![image](https://user-images.githubusercontent.com/33269913/104453444-2f71dc80-5583-11eb-8a32-37cceb29d53c.png)

**Comment by seitbnao** [comment]
O correto é você ter um usuário com apenas o controle financeiro, o restante desativado para você controlar isso melhor, o poderíamos ver a possibilidade de utilizar a senha do administrador ao editar um lançamento assim como ocorre em caixas de supermercados por exemplo.

**Comment by octaralves** [comment]
Sim, mas mesmo ao faturar a venda o sistema permite faturar e lançar pago com data retroativa e futura o que não e vantagem.

**Comment by seitbnao** [comment]
> Sim, mas mesmo ao faturar a venda o sistema permite faturar e lançar pago com data retroativa e futura o que não e vantagem.

Para resolver sua situação, o campo  Data de Pagamento deve ser desabilitado, digo impossível de ser editado, e deve manter o valor dele como a data atual, essa configuração poderia ser implementado vou ver oque posso fazer para ajudar

**Comment by seitbnao** [comment]
Sua request está na PR #1146
