### ISSUE TITLE
INTEGRAÇÃO COM BANCO INTER EMISSÃO DE BOLETOS

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1141]
Boa tarde pessoal. O banco Inter possui um recurso para quem é MEI ou ME. Esse recurso permite o usuário Emitir até 200 boletos sem pagar NADA!. O dinheiro que vc cobra pelo boleto vem limpo, sem desconto algum.
Observei que algumas Plataformas estão fazendo essa integração. 
Assim como o GerenciaNet. É possivel fazer essa integração com o Banco Inter?
Estava dando uma olhada nesse post eles conseguem via API.
https://suporte.beteltecnologia.com.br/hc/pt-br/articles/360053695013-Integra%C3%A7%C3%A3o-Banco-Inter

**Comment by willph** [comment]
Tem https://github.com/allgood/APInter-PHP é só baixar e integrar ao sistema. 

Pelo que li para ter acesso a api tem que ter conta no banco inter tipo PJ, e não tem modo sandbox para testar. O teste é feito com boletos já valendo. Tendo que colocar dados reais.

**Comment by willph** [comment]
Agora acessando o chat do banco inter, eles dizem que no momento não tem API para gerar boleto no momento.

**Comment by R4T0** [comment]
que massa mano... vou ler a respeito. Pra mim implementar essa API eu preciso mexer com algum código ?

**Comment by willph** [comment]
Falei com pessoal do suporte do Inter, realmente existe API, mas só tem para cliente de porte ME para cima.
Mei não tem

**Comment by R4T0** [comment]
seria possível por isso no Mapos? é pra ME mesmo.



Douglas Tecnologia em Redes
Em Wilmerson <notifications@github.com>, 13 de jan de 2021 6:03 PM escreveu:

Falei com pessoal do suporte do Inter, realmente existe API, mas só tem para cliente de porte ME para cima.
Mei não tem
