### ISSUE TITLE
ERRO AO FATURAR OS

### ISSUE THREAD

**Issue by Weltoncastro97** [RamonSilva20/mapos#1143]
AO FATURAR A OS ESTÁ APARACENDO ESSE ERRO, JÁ TENTEI ATUALIZAR O BANCO DE DADOS, RECRIEI A OS MAIS MESMO ASSIM FICA DANDO ESSE ERRO, VERSÃO 4.26.2
![Sem título](https://user-images.githubusercontent.com/77410845/104500125-60b6d080-55b4-11eb-9428-9e4f670fef5e.png)

**Comment by willph** [comment]
> 
> 
> AO FATURAR A OS ESTÁ APARACENDO ESSE ERRO, JÁ TENTEI ATUALIZAR O BANCO DE DADOS, RECRIEI A OS MAIS MESMO ASSIM FICA DANDO ESSE ERRO, VERSÃO 4.26.2
> ![Sem título](https://user-images.githubusercontent.com/77410845/104500125-60b6d080-55b4-11eb-9428-9e4f670fef5e.png)

Baixe a versão 4.27 e não se esqueça de atualizar o BD através do arquivo SQL que se encontra na pasta UPDATES
