### ISSUE TITLE
Erro ao Faturar OS

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#1144]
** Descreva o bug **
Com a OS aberta é inserido a data do faturamento e a forma de pagamento e é apresentado uma mensagem de erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'qualquer OS aberta'
2. Clique em 'faturar os'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Faturamento e baixa da OS

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [W10 x64]
 - Navegador [edge]
 - Versão [87.0.664.75]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
![erro-faturar-os](https://user-images.githubusercontent.com/25686016/104504278-f9ebe400-55c0-11eb-9af0-059577e13b68.png)

**Comment by SOROInfo** [comment]
O banco de dados está atualizado, feita atualização pelo próprio sistema.

**Comment by willph** [comment]
> O banco de dados está atualizado, feita atualização pelo próprio sistema.

Sabe fazer essa atualização do BD via arquivo .SQL que tem na pasta update?

É pra vê se tem algum erro no arquivo que é responsável pelo botão em configuração. Sistema.

**Comment by SOROInfo** [comment]
Sim, vou tentar.

Atenciosamente,



*André Fernandes **Telefone e WhatsApp 15 99619-6573*
*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br>*


Em qua., 13 de jan. de 2021 às 17:05, Wilmerson <notifications@github.com>
escreveu:

**Comment by seitbnao** [comment]
Amigo, esta é a versão estável? não me recordo da 4.26.2 ter este alert personalizado

**Comment by seitbnao** [comment]
Provavelmente seu banco está desatualizado, tabela lancamentos verifique se existe o campo usuarios_id nela

**Comment by SOROInfo** [comment]
Então a atualização automática do banco de dados não funciona?


Atenciosamente,

SOROInfo - Manutenção de Computadores
André Fernandes
Telefone 15 3222-0482 | WhatsApp 15 99619-6573

Website https://www.soroinfo.com.br



Em qua, 13 de jan de 2021 19:35, SeiTbNao - Djunio <notifications@github.com>
escreveu:

**Comment by SOROInfo** [comment]
Fiz a atualização manual do banco de dados e o problema foi resolvido.
Obrigado pela atenção de todos.


Atenciosamente,



*André Fernandes **Telefone e WhatsApp 15 99619-6573*
*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br>*


Em qua., 13 de jan. de 2021 às 21:55, SOROInfo Manutencao de Computadores <
contato@soroinfo.com.br> escreveu:

**Comment by willph** [comment]
Ok. Provavelmente deve ter algum erro na migrations, irei verificar depois, pra vê se realmente tem.

**Comment by evertonterra** [comment]
boa tarde , atualizei o sistema para ter a função de impressão em duas vias , porem esta ocorrendo este mesmo erro, alguém sabe como resolver ? é desfazer a atualização?

**Comment by willph** [comment]
> boa tarde , atualizei o sistema para ter a função de impressão em duas vias , porem esta ocorrendo este mesmo erro, alguém sabe como resolver ? é desfazer a atualização?

O banco de dados Está atualizado. 

Os comandos fica na pasta update.
Arquivos .sql

**Comment by evertonterra** [comment]
>
dentro da pasta updade tem os arquivos .sql , só que são vários , provavel que deve ser numeros de versão , eu não sei qual usar 
você consegue resolver isso pra mim , faço o pagamento ou uma doação , sei la rsrsrs , pra eu conseguir continuar a vender , estou usando em produção o sistema

**Comment by willph** [comment]
> > 
> 
> dentro da pasta updade tem os arquivos .sql , só que são vários , provavel que deve ser numeros de versão , eu não sei qual usar você consegue resolver isso pra mim , faço o pagamento ou uma doação , sei la rsrsrs , pra eu conseguir continuar a vender , estou usando em produção o sistema

Se estiver no grupo do MapOs no Whatsapp. 
Só manda um alô

**Comment by evertonterra** [comment]
> > boa tarde , atualizei o sistema para ter a função de impressão em duas vias , porem esta ocorrendo este mesmo erro, alguém sabe como resolver ? é desfazer a atualização?
> 
> O banco de dados Está atualizado.
> 
> Os comandos fica na pasta update. Arquivos .sql

aqui mostra que meu sistema esta na versão 4.39.0, porém o .sql que chega proximo é update_4.37.0_to_4.38.0.sql então seria esse que tenho que executar

**Comment by evertonterra** [comment]
> > > 
> > 
> > 
> > dentro da pasta updade tem os arquivos .sql , só que são vários , provavel que deve ser numeros de versão , eu não sei qual usar você consegue resolver isso pra mim , faço o pagamento ou uma doação , sei la rsrsrs , pra eu conseguir continuar a vender , estou usando em produção o sistema
> 
> Se estiver no grupo do MapOs no Whatsapp. Só manda um alô

não estou no grupo , como faço para entrar meu whatsapp é 35988274079

**Comment by evertonterra** [comment]
> > > 
> > 
> > 
> > dentro da pasta updade tem os arquivos .sql , só que são vários , provavel que deve ser numeros de versão , eu não sei qual usar você consegue resolver isso pra mim , faço o pagamento ou uma doação , sei la rsrsrs , pra eu conseguir continuar a vender , estou usando em produção o sistema
> 
> Se estiver no grupo do MapOs no Whatsapp. Só manda um alô

@willph sera que você pode me adicionar?

**Comment by willph** [comment]
https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

**Comment by evertonterra** [comment]
> https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

muito obrigado @willph
