### ISSUE TITLE
Erro atualização

### ISSUE THREAD

**Issue by eduardoleaoinformatica** [RamonSilva20/mapos#1147]
- Subi os novos arquivos pro servidor.
- Rodei o comando "composer install --no-dev" e atualizou todas as dependências. 
- substitui os arquivos "config.php", "database.php" e "email.php" com os anteriores.
- ao acessar o sistema ele fica redirecionando para a pasta de instalação e exibe a mensagem de o que o sistema já foi instalado.
- clico em "Ir para página de Login" e o sistema fica em loop sempre voltando para essa pagina.
- segue print
![tela-sistema](https://user-images.githubusercontent.com/73653372/104621664-2100ef00-566f-11eb-9b81-cc2f9a89e05c.png)

**Comment by willph** [comment]
> * Subi os novos arquivos pro servidor.
> * Rodei o comando "composer install --no-dev" e atualizou todas as dependências.
> * substitui os arquivos "config.php", "database.php" e "email.php" com os anteriores.
> * ao acessar o sistema ele fica redirecionando para a pasta de instalação e exibe a mensagem de o que o sistema já foi instalado.
> * clico em "Ir para página de Login" e o sistema fica em loop sempre voltando para essa pagina.
> * segue print
>   ![tela-sistema](https://user-images.githubusercontent.com/73653372/104621664-2100ef00-566f-11eb-9b81-cc2f9a89e05c.png)

Não precisava fazer essa etapa 

`substitui os arquivos "config.php", "database.php" e "email.php" com os anteriores.`

Era seguir com a instalação normalmente inserindo os mesmo dados da instalação anterior e finalizar que dava certo.

**Comment by willph** [comment]
Agora se o BD for de versão anterior precisa atualiza com o arquivo .SQL que está na pasta update.

Ou já que fez isso, basta editar o arquivo index.php e muda uma linha pra production

**Comment by willph** [comment]
Linha `define('ENVIRONMENT', 'pre_installation');` alterar para ` define('ENVIRONMENT', 'production'); `

**Comment by eduardoleaoinformatica** [comment]
> Linha `define('ENVIRONMENT', 'pre_installation');` alterar para `define('ENVIRONMENT', 'production');`

Fiz apenas a alteração dessa linha e voltou a funcionar normalmente. Obrigado pela ajuda.

**Comment by willph** [comment]
De nada.

**Comment by eduardoleaoinformatica** [comment]
Não queria reabrir o tópico, mas depois da atualização dos arquivos e do BD tudo esta funcionando normal, apenas a página de "Financeiro>lançamentos" esta com erro.
![tela-sistema](https://user-images.githubusercontent.com/73653372/104639446-32a1c100-5686-11eb-98bf-2217832565ca.png)

**Comment by willph** [comment]
> Não queria reabrir o tópico, mas depois da atualização dos arquivos e do BD tudo esta funcionando normal, apenas a página de "Financeiro>lançamentos" esta com erro.
> ![tela-sistema](https://user-images.githubusercontent.com/73653372/104639446-32a1c100-5686-11eb-98bf-2217832565ca.png)

Faltou atualiza o BD, parece que está faltando o campo usuario_id na tabela lançamento.

**Comment by willph** [comment]
Na pasta UPDATES tem o arquivo SQL para atualizar o BD via comando SQL.

**Comment by eduardoleaoinformatica** [comment]
- Já tinha executado o sql "update_4.26.2_to_4.27.0.sql", logo após a atualização dos arquivos e apresentou esse erro.
- Executei o arquivo "update_4.25.1_to_4.26.0.sql", que no caso seria um versão anterior e funcionou perfeitamente.
- Mais uma vez muito obrigado.
