### ISSUE TITLE
Data final na abertura da ordem serviço.

### ISSUE THREAD

**Issue by tonnybarros** [RamonSilva20/mapos#1148]
Alguém pode me explicar qual a função dessa data?

Eu já usei ao longo de 20 anos, vários software de assistência, e nunca vi essa função.

Seria a promessa de quando estaria pronto o orçamento?

E depois dessa data atingida, o que acontece?

**Comment by augustocoletti** [comment]
Creio que seja uma previsão de encerramento. Eu sempre usei considerando estimativa de termino, mas quando ultrapassa, não muda nada pra mim. Sei que nas versões com agenda, ele mostra no calendário a data final, como se fosse um controle de agendamento para "chamados técnicos" e para mostrar o fluxo de OS encerradas no dia. 
Creio que seja isso amigo.
