### ISSUE TITLE
não consigo abrir as ordens de serviço com instalação recente

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#1149]
galera acabei de instalar o mapos na hostinger, e bem... pra fazer a instalação eu tive de ir no ssh da minha hospedagem,e digitar
composer install
dentro da pasta do mapos, afim de instalar todos os componentes.
instalação feita, tudo ok. fiz aq instalação do sistema, e tudo está funcionando, exceto uma coisa:

ao abrir a tela de ordens de serviço no administrador, aparece o seguinte erro:

se preparem, é um log grande:

Error thrown with message "Call to a member function setTime() on bool"

Stacktrace:
#11 Error in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/helpers/date_helper.php:9
#10 dateInterval in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/views/os/os.php:114
#9 include in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/third_party/MX/Loader.php:588
#8 MX_Loader:_ci_load in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/third_party/MX/Loader.php:506
#7 MX_Loader:view in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/views/tema/conteudo.php:20
#6 include in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/third_party/MX/Loader.php:588
#5 MX_Loader:_ci_load in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/third_party/MX/Loader.php:506
#4 MX_Loader:view in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/core/MY_Controller.php:60
#3 MY_Controller:layout in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/controllers/Os.php:75
#2 Os:gerenciar in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/controllers/Os.php:23
#1 Os:index in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:532
#0 require_once in /home/u958679346/domains/brasilconserta.com.br/public_html/sistema/index.php:307

se precisarem de detalhes me avisem
mas, quero resolver isso

**Comment by willph** [comment]
> _No description provided._

Você precisa atualiza o banco de dados com o arquivo SQL que está dentro da pasta UPDATE.

Procure pela versão que está atualizando.

**Comment by thadeu220** [comment]
mas, a instalação é nova
ainda assim precisa disso?
e eu baixei foi o release, e preenchi todo o setup depois de fazer o composer
ou seja, em tese, deveria tá normal

**Comment by thadeu220** [comment]
e outra coisa, isso não vai apagar os dados de meus clientes não né?

**Comment by thadeu220** [comment]
aqui tem vários sql, e tipo a minha versão atual de instalação é a 4.27.0 mas, não tenho nenhuma instalação anterior
devo aplicar o sql update_4.26.2_to_4.27.0.sql mesmo assim no meu phpmyadmin ?
e isso mata algum de meus dados?

**Comment by thadeu220** [comment]
bem fiz o import do sql do v4.6 to v4.7 mas, mesmo assim
continua com erro
acho que, não vai funcionar
meeeeeu deeeeus vou ter que dar reinstall nisso mesmo!
auauauauauuauau
eu peguei o v4.6 to v4.7 sql, e, coloquei no phpmyadmin dentro da seção import...
e deu dois erros de consulta que são relacionados com o trecho de whatsapp notiicação em configurações do sistema
to mais perdido que cego no tiroteio, e eu sou mesmo cego, sou mesmo deficiente visual

**Comment by willph** [comment]
Pensei que era atualização. 
Você não tinha colocado descrição

**Comment by willph** [comment]
Eu preciso saber, afinal a instalação do banco de dados é nova mesmo ou o BD é de uma versão anterior?

**Comment by thadeu220** [comment]
é uma instalação nova... não tinha feito nada nela
aliás tem um outro detalhe, com a instalação na ultima versão o botão de atualizar mapos aparece, e ele na verdade, deveria sinalizar que não há updates.
eu baixei hoje o sistema

**Comment by thadeu220** [comment]
sobre a descrição erro foi meu mesmo... cego tapado

**Comment by willph** [comment]
> sobre a descrição erro foi meu mesmo... cego tapado

Vou fazer uma instalação do zero e vê se dá erro aqui.

Já dou retorno

**Comment by thadeu220** [comment]
belezaaaaaa!

**Comment by willph** [comment]
Aqui esta tranquilo.

Instalação do zero, criado novo banco de dados e tudo mais foi feito.

**Comment by willph** [comment]
Agora a PR ##1140 corrige alguns erros, inclusive a da mensagem de OS adicionada com sucesso, que não estava aparecendo.

**Comment by thadeu220** [comment]
Eu fiz uma nova instalação em funcionam tranquilamente
Eu acho que deve ser uma coisa
Estava experimentando o sistema e clique nos botões de atualizar sistema e atualizar banco de dados, pensando que apareceria um aviso de que não há novas versões disponíveis mas ele realmente tentou fazer atualização e não conseguiu então deve ter dado esse bug
Eu acho que quando você clica ali, deveria aparecer os avisos de que não há novas versões disponíveis ao invés de tentar baixar

**Comment by willph** [comment]
O atualiza sistema está com bug.

Agora o atualiza banco de dados estava funcionando. Mas possa ser que apareceu algum bug.
Depois eu testo.

**Comment by seitbnao** [comment]
> O atualiza sistema está com bug.
 acredito que tenha que adicionar o Index.php na lista de arquivos ignorados, para que não bugue, por que quando clica em atualizar ele faz o download de tudo menos esses itens     'application/config', 'application/database', 'application/email' mas quando a atualização é feita o index.php é substituido pelo pre_instalation e ai buga algumas coisas, outra coisa que notei também é que este método de atualização deveria estar e "tools"  tipo assim, php index.php tools forceupdate

Estive olhando o atualiza o sistema, acredito que ele deva ser por te

**Comment by thadeu220** [comment]
Acabei de confirmar aqui instalando novamente e não está dando bug mas se clicar em atualizar sistema ele vai dar o bug que eu relatei
Realmente o problema está na atualização de sistema
Pelo menos ao meu ver, o botão só deveria aparecer caso houvesse atualizações mas o projeto não tem um site oficial feito para buscar atualização
