### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by HigorHenrike** [RamonSilva20/mapos#1152]
erro ao rodar o comando: composer install --no-dev

Erro apresentado:

Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 2
    - mpdf/mpdf is locked to version v8.0.5 and an update of this package was not requested.
    - mpdf/mpdf v8.0.5 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 3
    - paragonie/random_compat is locked to version v9.99.99 and an update of this package was not requested.
    - paragonie/random_compat v9.99.99 requires php ^7 -> your php version (8.0.0) does not satisfy that requirement.

Ja pesquisei no google mas nao encontro como resolver

**Comment by willph** [comment]
Acredito que seja problema no php 8, já tentou rodando uma versão inferior do php? A 7.4  por exemplo

**Comment by HigorHenrike** [comment]
acabei usando o xampp mesmo
