### ISSUE TITLE
Erro no item Financeiro do menu em celulares

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1153]
Boa tarde, sou novo em PHP e adorei esse projeto. Estou estudando ele e já estou precisando de ajuda.

Quando abro o submenu do financeiro, os ítens lançamentos e cobrança aparecem normalmente. Porém quando abro em uma configuração de celular ou tablet ele some com o submenu lançamentos, ficando apenas o cobrança

Preciso de uma luz para em primeiro lugar entender o erro e depois resolver. Desde já meu muito obrigado..

**Comment by willph** [comment]
> Boa tarde, sou novo em PHP e adorei esse projeto. Estou estudando ele e já estou precisando de ajuda.
> 
> Quando abro o submenu do financeiro, os ítens lançamentos e cobrança aparecem normalmente. Porém quando abro em uma configuração de celular ou tablet ele some com o submenu lançamentos, ficando apenas o cobrança
> 
> Preciso de uma luz para em primeiro lugar entender o erro e depois resolver. Desde já meu muito obrigado..

Poderia enviar o print?

**Comment by Lucios1989** [comment]
![erromapOs1](https://user-images.githubusercontent.com/77629142/104942195-e068e480-5992-11eb-9b15-717900b8c936.png)

**Comment by Lucios1989** [comment]
![erromapOs2](https://user-images.githubusercontent.com/77629142/104942309-0db59280-5993-11eb-81ac-23ae8d593dec.png)

**Comment by willph** [comment]
Erro de HTML

Só remover linha 58 e 59 do arquivo `menu.php` que fica na pasta `application > view > tema`

**Comment by Lucios1989** [comment]
Funcionou, obrigado

**Comment by willph** [comment]
De nada
