### ISSUE TITLE
Bloquear para edição as OS que estejam com status  "FINALIZADO"

### ISSUE THREAD

**Issue by Loury-Silva** [RamonSilva20/mapos#1154]
Boa tarde!

Teria alguma forma, um comando, que eu possa inserir no código para bloquear a edição de OS finalizada?
Entendo muito pouco de PHP e vossa ajuda será de grande valia. Desde já agradeço.

**Comment by marcelinoac** [comment]
Boa tarde! Uma ideia seria fazer assim, mas seria aplicado para todos os usuários. Assim que o usuário salvar a OS como finalizada, o botão de atualizar será desativado, qualquer alteração que fizer não vai ter como ser salva.

<?php if ($result->status != "Finalizado") { ?>
<button class="btn btn-primary" id="btnContinuar"><i class="fas fa-sync-alt"></i> Atualizar</button>
<?php } ?>

**Comment by marcelinoac** [comment]
<?php if ($result->status != "Finalizado") { ?>
                                            <button class="btn btn-primary" id="btnContinuar"><i class="fas fa-sync-alt"></i> Atualizar</button>
                                            <?php
                                            } ?>

**Comment by marcelinoac** [comment]
Boa tarde! Uma ideia seria fazer assim, mas seria aplicado para todos os usuários. Assim que o usuário salvar a OS como finalizada, o botão de atualizar será desativado, qualquer alteração que fizer não vai ter como ser salva.

`<?php if ($result->status != "Finalizado") { ?>
                                            <button class="btn btn-primary" id="btnContinuar"><i class="fas fa-sync-alt"></i> Atualizar</button>
                                            <?php
                                            } ?>`

**Comment by Loury-Silva** [comment]
marcelinoac, muito obrigado pela dica, mas preciso que o admin tenha esse acesso de poder alterar as informações.

**Comment by marcelinoac** [comment]
Você pode colocar um código checando a string usuarios_id pra poder liberar ou não
