### ISSUE TITLE
Erro ao salvar Notificação personalizada do Whatsapp

### ISSUE THREAD

**Issue by Isaqjonatas** [RamonSilva20/mapos#1155]
Após preencher mensagem personalizada de notificação do whatsapp, ao clicar em salvar, está sendo salvo em branco. Quando clica em "Enviar Notificação por Whatsapp", não aparece mensagem definida.

**Comment by willph** [comment]
> 
> 
> Após preencher mensagem personalizada de notificação do whatsapp, ao clicar em salvar, está sendo salvo em branco. Quando clica em "Enviar Notificação por Whatsapp", não aparece mensagem definida.

Atualizou o banco de dados?

**Comment by Isaqjonatas** [comment]
Não, instalei sobre o BD anterior. Farei isso e retorno com o feedback.

**Comment by willph** [comment]
> Não, instalei sobre o BD anterior. Farei isso e retorno com o feedback.

Olhe na pasta UPDATES. 

E vai atualizando de acordo com sua versão, até chegar ao update mais recente.

**Comment by Isaqjonatas** [comment]
Desculpe, sou leigo nesses procedimentos, voce tem um passo a passo de como atualizar da versão 3.1.12 até a versão 4.7?

**Comment by Isaqjonatas** [comment]
Olá, fiz todas as atualizações, mas ocorre um erro ao editar dados do cliente.

**Comment by willph** [comment]
Qual versão?

**Comment by Isaqjonatas** [comment]
Fiz o teste com a V4.27 e a v4.28, apresentaram o mesmo erro

**Comment by willph** [comment]
> Fiz o teste com a V4.27 e a v4.28, apresentaram o mesmo erro

Usou o arquivo SQL da pasta Update?

Manda o screenshot do erro

**Comment by Isaqjonatas** [comment]
Sim, Importei os SQL um a um até chegar na v4.28, utilizei meu BD original que era na v3.15
![erro](https://user-images.githubusercontent.com/35502804/105529107-ac5c2f00-5cc4-11eb-8aa0-2e394f807125.jpg)

**Comment by willph** [comment]
> Sim, Importei os SQL um a um até chegar na v4.28, utilizei meu BD original que era na v3.15
> ![erro](https://user-images.githubusercontent.com/35502804/105529107-ac5c2f00-5cc4-11eb-8aa0-2e394f807125.jpg)

Tem um  botão em configuração > sistema que ser para atualizar o banco de dados também. 

Da um clique nele pra fazer um teste

**Comment by Isaqjonatas** [comment]
Resolvido, realmente faltava atualizar por esse botão.
Obrigado!

**Comment by willph** [comment]
> Resolvido, realmente faltava atualizar por esse botão.
> Obrigado!

De nada.

Esse botão faz a mesma função de atualização do banco de dados manualmente, só que de uma forma automática.

**Comment by willph** [comment]
> Resolvido, realmente faltava atualizar por esse botão.
> Obrigado!

Versão mais recente é 4.28, você pode baixar o código em realese.

**Comment by Isaqjonatas** [comment]
Sim, ja estou utilizando ele, obrigado.

**Comment by willph** [comment]
> Sim, ja estou utilizando ele, obrigado.

É que pela foto tinha 4.27 😁
