### ISSUE TITLE
Erro de atualização de estoque

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1157]
Boa tarde.
Amigos a versão atual está apresentando um erro na baixa do estoque mesmo com a os faturada.

**Comment by seitbnao** [comment]
Boa tarde pode informar o erro?

**Comment by p-francelino** [comment]
O produto cadastrado em estoque não da baixa.
Ex tenho 10 produtos abro a os icluo o produto e faço o faturamentos porem no estoque continuam os 10

**Comment by seitbnao** [comment]
Pode ficar tranquilo que será corrigido.
