### ISSUE TITLE
Erro ao Gerar boleto pelo Gerencianet

### ISSUE THREAD

**Issue by cgarrotti** [RamonSilva20/mapos#1158]
Boa tarde pessoal, configurei com o meu client_id e o secret, porem qdo vou criar o boleto ou link aparece:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by Pr3d4dor** [comment]
Você usa xamp ou wamp?

Isso pode ajudar: https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by cgarrotti** [comment]
Wampp,

Usei o link q da sua resposta, deu certo, valeu amigo.
