### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by nicopastorello** [RamonSilva20/mapos#116]
Ola seria muito útil ter um tutorial explicando como funciona o sistema, algo bem de pratico.

**Comment by edgarmeireles** [comment]
@RamonSilva20 Posso criar um tutorial detalhado quando o MAPOS 4 estiver mais funcional...
Baixei ele pra ver, mas acredito que ainda não está ao ponto de capturar telas e mostrar os detalhes...

Se possível, implemente um comando tipo F1 em todas as páginas para abrir um iframe com as funcionalidades da tela e uma tela geral para ter o link de todos os processos do sistema.
