### ISSUE TITLE
Erro na geração de Boleto no GerenciaNet

### ISSUE THREAD

**Issue by cgarrotti** [RamonSilva20/mapos#1160]
Boa tarde pessoal,
fiz uma conta la no GerenciaNet, peguei o client_id e o secret_id la do sandbox e configurei no meu mapos.
Cadastrei um cliente, com os dados tudo certo, cpf, nome, telefone, tudo certinho. Criei uma venda pra ele, e dai la no Gerar Pagamento qdo eu escolho Boleto aparece a mensagem:

Codigo:  3500034
validation_error
[object Object]

Meu Mapos é a versão 4.27.0

**Comment by willph** [comment]
> Boa tarde pessoal,
> fiz uma conta la no GerenciaNet, peguei o client_id e o secret_id la do sandbox e configurei no meu mapos.
> Cadastrei um cliente, com os dados tudo certo, cpf, nome, telefone, tudo certinho. Criei uma venda pra ele, e dai la no Gerar Pagamento qdo eu escolho Boleto aparece a mensagem:
> 
> Codigo: 3500034
> validation_error
> [object Object]
> 
> Meu Mapos é a versão 4.27.0

Você pegou qual código?

Sandbox(desenvolvimento) ou Produção?

**Comment by cgarrotti** [comment]
> > Boa tarde pessoal,
> > fiz uma conta la no GerenciaNet, peguei o client_id e o secret_id la do sandbox e configurei no meu mapos.
> > Cadastrei um cliente, com os dados tudo certo, cpf, nome, telefone, tudo certinho. Criei uma venda pra ele, e dai la no Gerar Pagamento qdo eu escolho Boleto aparece a mensagem:
> > Codigo: 3500034
> > validation_error
> > [object Object]
> > Meu Mapos é a versão 4.27.0
> 
> Você pegou qual código?
> 
> Sandbox(desenvolvimento) ou Produção?

Foi do Sandbox(desenvolvimento), acabei de atualizar pra versao 4.28.0, não achei o meu cobrança Pagamentos, foi retirado nessa versao ?

**Comment by Pr3d4dor** [comment]
@cgarrotti Foi removido para deixar mais flexível, toda configuração de chaves e gateways de pagamentos agora fica em: https://www.github.com/RamonSilva20/mapos/tree/master/application%2Fconfig%2Fpayment_gateways.php

Lá você seta as credenciais agora.
