### ISSUE TITLE
aparecer a descricao na pagina inicial das OS

### ISSUE THREAD

**Issue by leandroperussolo** [RamonSilva20/mapos#1163]
ola, eu utilizo o sistema para um laboratorio de impressao 3d e atendo um mesmo cliente repetidas vezes, portanto só aparecer o nome do cliente na pagina das OS me confunde para saber de qual trabalho se trata. Tem como deixar parte da descriçao aparente na pagina inicial de ordem de servico para evitar que eu tenha que entrar em cada OS para procurar o servico desejado?

na minha tela inicial aparecem os seguintes itens:
N da OS / cliente / responsavel / data inicial / data final / venc. garantia / valor total / valor faturado / status / t. garantia / açoes

teria como deixar somente?
n da os / cliente / descricao (pelo menos uns 30 caracteres) / responsavel / data inicial / status / açoes

como nao sou programador e nao tenho conhecimento, estou disposto a remunerar alguem que me ajude a personalizar o programa para adequar melhor ao meu negocio. se alguem se interessar, meu telefone é 41 98850-7446 (Leandro)

desde ja, obrigado

**Comment by Pr3d4dor** [comment]
@leandroperussolo Se você não se importar de perder a coluna T. Garantia só ussar esse código: https://pastebin.com/1GR9WRXL

Copiar por cima do código do arquivo `application/views/os/os.php`

**Comment by leandroperussolo** [comment]
@Pr3d4dor desculpe a ignorancia, mas de eu escrever "Descrição" em cima do Venc. Garantia tambem funciona?

**Comment by Pr3d4dor** [comment]
Você quer trocar a ordem das colunas Descrição e Venc. Garantia, isso?

**Comment by leandroperussolo** [comment]
isso mesmo!

**Comment by Pr3d4dor** [comment]
@leandroperussolo segue o link: https://pastebin.com/QR6w2DcN

**Comment by leandroperussolo** [comment]
valeu garoto! te devo um chopp!
