### ISSUE TITLE
Erro na pagina de lançamento/financeiro após atualizar para 4.26 

### ISSUE THREAD

**Issue by TK2KMG** [RamonSilva20/mapos#1165]
Olá! Primeiramente agradecer pelo excelente trabalho de vocês. 

Estou tendo problemas após atualizar da versão 4.25.1 para 4.26.
Ocorre um erro ao tentar entrar em Financeiro/Lançamentos. 

Ao clicar, aparece o seguinte erro na tela capturada logo abaixo.
![ERRO TELA FINANCEIRO](https://user-images.githubusercontent.com/65869753/105593226-99536880-5d71-11eb-9d46-8cb2f802fea6.jpg)

Já fiz o procedimento de ir em: Configurações/Sistema/Atualizar Banco de Dados. Aparece a mensagem de "Banco de Dados Atualizado com Sucesso!"  mas o erro persiste. 

Por favor, podem me orientar qual o procedimento  para corrigir este erro? 

Desde já agradeço pela atenção.

**Comment by Pr3d4dor** [comment]
@TK2KMG Está faltando atualizar seu banco de dados, olhe na pasta updates ou rode o Atualizar Banco de dados dentro do sistema.

**Comment by TK2KMG** [comment]
Olá Pr3d4dor. 
Dentro desta pasta updates tem vários arquivos, há inclusive esse que você citou "update_4.25.1_to_4.26.0". Como proceder ? 
O procedimento dentro do sistema já fiz, não surtiu efeito.

**Comment by TK2KMG** [comment]
> @TK2KMG Está faltando atualizar seu banco de dados, olhe na pasta updates ou rode o Atualizar Banco de dados dentro do sistema.

**Comment by TK2KMG** [comment]
Problema resolvido. Muito obrigado.
