### ISSUE TITLE
Tag para notificação Personalizada do whatsapp

### ISSUE THREAD

**Issue by Isaqjonatas** [RamonSilva20/mapos#1166]
Olá, alguem sabe informar qual a Tag correta para Valor total da OS, a {VALOR_OS} não funciona.
Gostaria de Saber se existe alguma para Valor de Produtos e valor de Serviços.

**Comment by willph** [comment]
Já foi enviado a PR com a correção disso.
Só aguardar aprovar para baixar a correção.

**Comment by Isaqjonatas** [comment]
Ok, Obrigado!
