### ISSUE TITLE
falha download anexos painel cliente

### ISSUE THREAD

**Issue by lemrage** [RamonSilva20/mapos#117]
alguem conseguiu resolver o erro de nao ser possivel realizar o download de anexos no painel do cliente ?

**Comment by lemrage** [comment]
acho que sei o que e deve ta faltando as funcoes do botao no arquivo dentro da pasta conecte arquivo detalhesOs

**Comment by alexts55** [comment]
Alguém conseguiu a correção? download de anexos no painel do cliente ?

**Comment by lemrage** [comment]
da hora vamos tentar

**Comment by lemrage** [comment]
outra coisa vc nao sabe chamar o nome do arquivo no anexo da os os nomes nao parecer caso alguem suba mais anexos tera que ir baixando para saber que anexo e sabe

**Comment by lemrage** [comment]
nao consegui inserir o codigo o final dele e esse no detalhesOs.php na pasta conecte 

  </div>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true" id="btn-cancelar-faturar">Cancelar</button>
  <button class="btn btn-primary">Faturar</button>
</div>
</form>
</div>

------>>> insere aqui o codigo pois se sim nao deu certo

**Comment by alexts55** [comment]
manda teu email para te repassar o arquivo certinho

**Comment by lemrage** [comment]
o meu e luiz_gruskamendes@hotmail.com

**Comment by RicardoPires20** [comment]
Resolveu mas alguém sabe porque ele vem 0 kb no download do anexo ?

**Comment by rafaerigson** [comment]
mesmo colocando o arquivo que passou ao clicar em donwload ele redireciona pra tela de login do admin, alguém com esse problema ?
