### ISSUE TITLE
Habilitar letras no campo "venc. garantia"

### ISSUE THREAD

**Issue by leandroperussolo** [RamonSilva20/mapos#1170]
olá. é possivel habilitar palavras no campo "venc. garantia"?

Como eu trabalho em outra area que nao é assistencia, eu nao uso esse campo e gostaria de aproveitar pra outra finalidade. O problema é que ele é habilitado só para escrever numeros. É possivel desbloquear para que possa receber palavras até uns 20 ou 30 caracteres e ficar visivel na tela inicial de OS?

obrigado!

**Comment by marllonferreira** [comment]
voce deve ir em 

application\views\os

voce deve edita o  **adicionarOs.php**

a linha 77 esta assim
`<input id="garantia" type="number" min="0" max="9999" class="span12" name="garantia" value="" />`

voce deve deix  assim

`<input id="garantia" type="text" class="span12" name="garantia" value="" />`



agora voce deve edita o  **editarOs.php**

a linha 102 esta assim
`<input id="garantia" type="number" min="0" max="9999" class="span12" name="garantia" value="<?php echo $result->garantia ?>" />`

voce deve deix  assim

`<input id="garantia" type="text" class="span12" name="garantia" value="<?php echo $result->garantia ?>" />`


pra finaliza vá em

\application\config

voce deve edita o  **form_validation.php**

a linha 192 esta assim
`'rules' => 'trim|numeric',`

voce deve deix  assim

`'rules' => 'trim',`


com isso e possível digita texto com ate 30 caracteres

lembrando q ainda tem q muda o titulo do campo em
application\views\os

nos arquivos

adicionarOs.php
editarOs.php
imprimirOs.php
visualizarOs.php
