### ISSUE TITLE
Edição de OS finalizadas e Faturadas. 

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#1171]
Percebi que foi feito uma alteração na edição das OS, onde agora não se edita mais as os finalizadas e faturadas. 

O problema que existem anexos e anotações que ficam presas. 
![image](https://user-images.githubusercontent.com/4989569/105629314-0eca4200-5e21-11eb-9e09-92d7cb8afe77.png)

Ou OS que são reabertas por garantia ou trocas e ou adição de materiais. 

Talvez seja interessante a opção de deixar o usuário definir ?

**Comment by Pr3d4dor** [comment]
@bulfaitelo Como diz na mensagem o correto é abrir outra OS com a troca.

**Comment by cabralwms** [comment]
Se clicar em visualizar e abrir a O.S. Consegue editar? Acho que seria legal uma permissão em vez de total bloqueio. Um administrador consegue editar, modificar, incluir, ou excluir itens,.

**Comment by Pr3d4dor** [comment]
@cabralwms Mesmo assim não é ideal o administrador ficar editando OS que já foram finalizadas/faturas para manter a integridade dos dados. Por isso o ideal é abrir outra OS.

**Comment by maycon1977** [comment]
> @cabralwms Mesmo assim não é ideal o administrador ficar editando OS que já foram finalizadas/faturas para manter a integridade dos dados. Por isso o ideal é abrir outra OS.

Respeitosamente eu discordo...

Acho que o administrador deveria ter poder para editar qualquer coisa. Eu mesmo como administrador do meu sistema, vez por outra edito O.S. finalizada caso ache necessário...

Se tivesse a opção do Administrador poder fazer essa edição eu agradeceria demais, pois esse bloqueio pode me atrapalhar no futuro!

**Comment by Pr3d4dor** [comment]
@maycon1977 Como eu disse, ficar tudo livre para editar gera um problema de integridade dos dados, mesmo sendo administrador. Pois na minha opinião é o correto não conseguir editar OS antigas que já foram faturas justamente para não acontecer divergências no financeiro.

Essa feature foi pedida por outros usuários no grupo e foi o @seitbnao que implementou.

**Comment by maycon1977** [comment]
> @maycon1977 Como eu disse, ficar tudo livre para editar gera um problema de integridade dos dados, mesmo sendo administrador. Pois na minha opinião é o correto não conseguir editar OS antigas que já foram faturas justamente para não acontecer divergências no financeiro.
> 
> Essa feature foi pedida por outros usuários no grupo e foi o @seitbnao que implementou.

Sim, eu até vi quando pediram e acho importante que nem todos tenham acesso à modificar uma O.S. finalizada por questão de segurança... Mas se o sistema permite níveis de acesso e/ou privilégio, não vejo o porquê tirar o acesso às edições do Administrador que ao meu ver "tudo pode", mesmo que não convenha...

Sou usuário antigo do sistema, utilizando a versão 3.14.2 toda personalizada... Venho tomando coragem para atualizar a minha versão há 2 anos já e tenho segurado porque a minha empresa roda toda em cima do MAPOS. Fico com receio de instalar uma versão nova e dar algum problema aqui. Sei que o certo é instalar em outro diretório fazendo backup do banco de dados e atualizando ele e tal, mas ainda assim tenho medo ainda mais depois que implementaram o lance aí do "composer install --no-dev". Nunca fiz isso e me dá um certo bloqueio...

Se puder deixar o administrador com "funções quase ilimitadas" eu preferiria, mas vocês que são os mestres da programação aqui, eu realmente só dou umas customizadas básicas na base da tentativa e erro (com mais erros do que acertos).

Muito obrigado pela atenção de todos os desenvolvedores no projeto.

**Comment by Pr3d4dor** [comment]
@maycon1977 Obrigado pelas considerações, o @seitbnao irá fazer uma configuração no sistema para ativar ou não esse bloqueio para poder editar OS que foi faturada/cancelada.

**Comment by maycon1977** [comment]
> @maycon1977 Obrigado pelas considerações, o @seitbnao irá fazer uma configuração no sistema para ativar ou não esse bloqueio para poder editar OS que foi faturada/cancelada.
> 
> Assim o administrador irá poder ativar/desativar para editar a OS mesmo depois de faturada/cancelada.

Muito obrigado mais uma vez! ;-)

**Comment by bulfaitelo** [comment]
> 
> 
> > @maycon1977 Obrigado pelas considerações, o @seitbnao irá fazer uma configuração no sistema para ativar ou não esse bloqueio para poder editar OS que foi faturada/cancelada.
> > Assim o administrador irá poder ativar/desativar para editar a OS mesmo depois de faturada/cancelada.
> 
> Muito obrigado mais uma vez! ;-)

Essa feature veio nessa versão .29? Eu acho que poderia ser uma flag lá dentro do campos de configurações, creio que seria mais interessante e ficaria a par de configuração, 

O que poderia ser interessante seria a edição unicamente de informações do tipo alteração de status pra finalizando (pois normalmente uso quando o cliente paga e finaliza o debito comigo) e dos campos de texto, (descrição, defeito, observações e laudo), com isso não alteraria o financeiro.

**Comment by Pr3d4dor** [comment]
@bulfaitelo Controlar por campos específicos é um pouco difícil, então creio que no seu caso você possa deixar habilitado mesmo a edição. Logo estara disponível quando o @seitbnao terminar a PR.
