### ISSUE TITLE
possíveis bugs na v4.28

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1172]
Pessoal
Vim passar o relatório de teste na v4.28 q baixei na noite de 23/01/21

Tem varias coisas novas q gostei muito mais vou citar as coisas acredito ser bugs
* a notificação do whatsApp continua mandado formatação html ( menos no campo descrição do produto )
* a notificação do whatsApp só mostra o valor total a pois se faturada.
* a opção de pagamento via mercado pago usando o api de teste funciona normal mais quando vc usa a api de produção da erro em (atualizar cobrança ,cancelar, excluir )
* Percebi que foi feito uma alteração na edição das OS, onde agora não se edita mais as os faturadas.
O problema que existem anexos e anotações que ficam presas. **( alguém comentou isso e achei interessante ressaltar)**

 **parabéns pela trabalho o mapos ta ficando cada dia mais incrível espero te ajudado de alguma forma**

**Comment by seitbnao** [comment]
As correções estão sendo enviadas para a PR #1169

**Comment by tonnybarros** [comment]
Quanto ao mercado pago acredito que esteja normal
Nesse demo
http://95.217.155.200/demo/index.php/login
Eu vi que gerou em minha conta mercado pago 3 boletos.

**Comment by marllonferreira** [comment]
cara ele gera normal mesmo de pois quando vc tenta (atualizar cobrança ,cancelar, excluir ) ai da erro

**Comment by Pr3d4dor** [comment]
@marllonferreira A api do mercado pago está sendo usado a SDK oficial, então creio que não é um problema na configuração, pelo pelo que lembro tem que ser homologado, ou tem que realizar alguma configuração no painel.

**Comment by marllonferreira** [comment]
> @marllonferreira A api do mercado pago está sendo usado a SDK oficial, então creio que não é um problema na configuração, pelo pelo que lembro tem que ser homologado, ou tem que realizar alguma configuração no painel.

pode ate ser porem to usando a mesma q usava antes e funcionava mais tranquilo vamos v se aparece mais alguém usando o mercado pago pra testa

**Comment by marllonferreira** [comment]
fora o probleminha com mercado pago (que quase nem uso mesmo aqui só avista ou cartão )

todas as questões já foram resolvido parabéns pelo trabalho de vocês

**Comment by robertonfaustino** [comment]
Aqui nao consegui usar o modulo do mercadopago
Retorna com erro:
bad_request: The customer can't be equal to the collector.


Coloquei as seguintes credenciais:
access_token
public_key
client_secret
client_id

Faltou alguma coisa? desculpe pela pergunta, to voltando a usar o map os, quando usava nao tinha essas opções hehe

**Comment by Pr3d4dor** [comment]
@robertonfaustino Você está gerando boleto para vocẽ mesmo (mesmo cpf) e ele não permite.
