### ISSUE TITLE
É possível adicionar um símbolo de moeda e fazer com que esse símbolo apareça em todas as consultas e relatórios?

### ISSUE THREAD

**Issue by guaycool** [RamonSilva20/mapos#1173]
Até agora, fiz o seguinte:
-Adicione ao banco de dados "app_currency" na tabela Configurações
-Adicionar no arquivo: \application\controllers\Mapos.php
   adicione a linha: $this->form_validation->set_rules('app_currency', 'Moneda de Sistema', 'required|trim');
   adicione a linha: 'app_currency' => $this->input->post('app_currency'),
-Adicione no arquivo: \application\database\seeds\Configuracoes.php
  adicione a linha: [
                'idConfig' => 2,
                'config' => 'app_currency',
                'valor' => '',
            ],
-Adicione no arquivo: \application\views\mapos\configurar.php
   adicione a linha: 
                        div class="control-group" > label for="app_currency" class="control-label" >Moeda   /label>
                        div class="controls">
                             inpu t type="text" required name="app_currency" value="<?= $configuration['app_currency']?>">
                            span class="help-inline">  Moeda   /span>
                        /d iv>
                    /d iv>

Com isso eu adiciono moeda ao sistema

**Comment by guaycool** [comment]
Preciso da tua ajuda.
Quero mostrar a moeda "app_currency" imediatamente antes do preço exibido.
-No arquivo: \application\views\produtos\produtos.php
             foreach ($results as $r){
                echo '<tr>';
                echo '<td>' . $r->idProdutos . '</td>';
                echo '<td>' . $r->codDeBarra . '</td>';
                echo '<td>' . $r->descricao . '</td>';
                echo '<td>' . $r->estoque . '</td>';
                echo '<td>' . $r->precoVenda . '</td>';
aqui eu quero mostrar antes do "precoVenda", a moeda (app_currency)

**Comment by Pr3d4dor** [comment]
@guaycool É possível, mas creio que seria melhor você customizar a sua versão e procurar todos os "R$" e trocar pela sua moeda;

**Comment by guaycool** [comment]
Obrigado por responder!
Eu não sou um especialista, você é um novato como n conhecimentos básicos.
você poderia ajudar com o que estou tentando fazer?

**Comment by Pr3d4dor** [comment]
Basicamente o que você tem que fazer é buscar em todos os arquivos PHP onde estiver "R$" e substituir pela moeda que você quer.

**Comment by guaycool** [comment]
Isso mesmo, coloque a moeda que estabeleci nas configurações através do campo "app_currency" da tabela de configurações

**Comment by Pr3d4dor** [comment]
@guaycool O mais fácil e rápido pra fazer ao invés de salvar no banco de dados é ir no arquivo `index.php` e colocar a linha:
```
define('CURRENCY_SIMBOL', 'R$');
```

Após isso, em todos os lugares que exibem "R$" você deverá fazer uma concatenação entre essa variável global e o valor. 

Por exemplo, no arquivo: `application/views/conecte/imprimirVenda.php` o trecho das linhas 92 à 100:
```
foreach ($produtos as $p) {
    $totalProdutos = $totalProdutos + $p->subTotal;
    echo '<tr>';
    echo '<td>' . $p->descricao . '</td>';
    echo '<td>' . $p->quantidade . '</td>';

    echo '<td>R$ ' . number_format($p->subTotal, 2, ',', '.') . '</td>';
    echo '</tr>';
} ?>
```

Ficaria:
```
foreach ($produtos as $p) {
    $totalProdutos = $totalProdutos + $p->subTotal;
    echo '<tr>';
    echo '<td>' . $p->descricao . '</td>';
    echo '<td>' . $p->quantidade . '</td>';

    echo '<td>' . CURRENCY_SIMBOL . number_format($p->subTotal, 2, ',', '.') . '</td>';
    echo '</tr>';
} ?>
```

**Comment by guaycool** [comment]
Obrigado, é uma opção muito boa. Gostaria de poder colocar antes do preço a moeda que salvo nas configurações do sistema.

--------------------------------------------------------------------------
no arquivo:  \application\views\mapos\configurar.php

aquele que cria a caixa "app_currency" no arquivo e no banco de dados.

-------------------------------------------------------------------------

_(linhea 28 até 42) editado em Notepad ++_
então no arquivo: \application\views\produtos\produtos.php
             foreach ($results as $r){
                echo '<td>' . $r->precoVenda . '</td>';
aqui eu quero mostrar antes do "precoVenda", a moeda (app_currency)

**Comment by Pr3d4dor** [comment]
@guaycool Se você quer pegar do banco mesmo, você primeiro precisará em todos os lugares que precisa exibir, buscar essa informação e com isso usar na view.

**Comment by guaycool** [comment]
Obrigado por responder, a verdade é que sou um novato e essa consulta é a única que não posso fazer.
Não sei como criar a consulta.

**Comment by Pr3d4dor** [comment]
@guaycool Você pode fazer assim (dentro de um controller)
```
$this->load->model('mapos_model');

$where = "app_config = 'app_currency'"
$result = $this->mapos_model->get('configuracoes', '*', $where);

dd($result); // Aqui vai estar sua config
```

**Comment by guaycool** [comment]
Muito obrigado pela ajuda, mas o código só gera erros.
Desculpe o incômodo, você poderia me indicar em que parte ou em qual arquivo devo copiá-lo para que funcione para mim, e como adicioná-lo para que apareça antes neste caso de "precoVenda"

 echo '<td>' . **aqui eu quero que apareça**  . $r->precoVenda . '</td>';

**Comment by Pr3d4dor** [comment]
@guaycool Qual foi o erro que apareceu?

**Comment by guaycool** [comment]
Boa tarde, obrigado.
Desculpe, talvez eu não esteja fazendo a coisa certa, você poderia me dizer em qual arquivo ou em qual parte do arquivo eu teria que copiar o texto.

**Comment by Pr3d4dor** [comment]
@guaycool Dentro de um controller, antes de renderizar alguma view que você queira colocar o símbolo da moeda.

**Comment by guaycool** [comment]
[
![A1](https://user-images.githubusercontent.com/77904857/105776329-b00fe000-5f68-11eb-9aa2-5e9295868a7a.png)
](url)

**Comment by guaycool** [comment]
![Sin título](https://user-images.githubusercontent.com/77904857/105776415-d46bbc80-5f68-11eb-8e3a-189946172b11.jpg)
obrigado.
Independentemente de onde seja colocado, o erro é o mesmo.
Eu ficaria muito grato se você pudesse me explicar o local exato para colocar o código e como fazer esse código aparecer antes da caixa "" precoVenda ".

**Comment by Pr3d4dor** [comment]
Faltou ponto e vírgula na linha 37

**Comment by guaycool** [comment]
![Sin título](https://user-images.githubusercontent.com/77904857/105777123-2103c780-5f6a-11eb-92f3-fcef356f7ae6.jpg)

Desta forma estou integrando o código que você me fornece, mas esse erro é o que me retorna

**Comment by Pr3d4dor** [comment]
@guaycool Você ainda não colocou o ";" que está faltando na linha 36.

**Comment by guaycool** [comment]
adicionar o erro muda e gera um novo

![Sin título](https://user-images.githubusercontent.com/77904857/105777967-ae93e700-5f6b-11eb-92a0-ae16ef6bc95e.jpg)

**Comment by Pr3d4dor** [comment]
Vá no Mapos_model e adicione a função:

```
/**
 * Busca configurações do sistema
 * @param array $data
 * @return boolean
 */
public function buscarConfiguracao($config, $one = true)
{
    $this->db->select('valor');
    $this->db->from('configuracoes');
    $this->db->where('config', $config);

    $query = $this->db->get();

    return $query->row()->valor;
}
```

Em qualquer controller para usar:
```
$this->load->model('mapos_model');

$result = $this->mapos_model->buscarConfiguracao('app_currency');

dd($result); // Aqui vai estar sua config
```

**Comment by guaycool** [comment]
_use como segue_

![Sin título2](https://user-images.githubusercontent.com/77904857/105780009-d8e7a380-5f6f-11eb-9ddb-f4732d24b243.jpg)

![Sin título3](https://user-images.githubusercontent.com/77904857/105780016-dedd8480-5f6f-11eb-9f8c-f8bdceafce43.jpg)

_Eu gero o seguinte erro_

![Sin título1](https://user-images.githubusercontent.com/77904857/105780075-ff0d4380-5f6f-11eb-8bb7-aa03b0262606.jpg)

**Comment by Pr3d4dor** [comment]
Você instalou as dependencias com o composer?

De qualque forma para ver o resultado você pode usar:
```
$this->load->model('mapos_model');

$result = $this->mapos_model->buscarConfiguracao('app_name');

var_dump($result);die(); // Aqui vai estar sua config
```

**Comment by guaycool** [comment]
usando desta forma este é o resultado removendo ";" na linha 42
`foreach ($results as $r){
            $this->load->model('mapos_model');
            $result = $this->mapos_model->buscarConfiguracao('app_currency');
                echo '<tr>';
                echo '<td>' . var_dump($result);die() . $r->precoVenda . '</td>';
                echo '<td>';`
                
![A1](https://user-images.githubusercontent.com/77904857/105781945-c66f6900-5f73-11eb-9908-adb1eb0356ca.png)

adicionando ";" para a linha 42 o resultado é este
![A2](https://user-images.githubusercontent.com/77904857/105782169-439ade00-5f74-11eb-942f-322f80f3f788.png)

---------------------------------------------------------------------------------------------------------------------------------

Para fazer o código funcionar para mim, fiz da seguinte maneira

`$this->load->model('mapos_model');
            $result = $this->mapos_model->buscarConfiguracao('app_currency');
                echo '<tr>';
                echo '<td>' . $result . $r->precoVenda . '</td>';
                echo '<td>';`

![A3](https://user-images.githubusercontent.com/77904857/105782630-2ca8bb80-5f75-11eb-956d-0efc70d47618.png)

--------------------------------------------------------------------------------------------------------------------------------

**### Muito obrigado por sua ajuda.
eu sou muito grato a você**

**Comment by guaycool** [comment]
Após as modificações, eu tenho esse erro nas ordens de serviço, você pode me ajudar por favor.
![Sin título](https://user-images.githubusercontent.com/77904857/105788328-8fec1b00-5f80-11eb-9981-07231db6e5bb.jpg)
