### ISSUE TITLE
ATUALIZAÇÃO DE MODO SEGURO

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1175]
Boa tarde DEvs.. Estou tendo muita dificuldade ao atualizar o sistema para as versões atuais.. Na maioria das vezes faço um dump do banco e reinstalo o sistema com a versão nova. E apartir daí ele só funciona se eu apagar meu banco e começar um novo.
Observei em uma issue fechada que é necessário copiar alguns arquivos.. Porém não deu mt certo.. Se houver possibilidade eu gravo um video e posto na comunidade de como realizar esse upgrade de forma correta;

**Comment by Pr3d4dor** [comment]
@R4T0 Não era pra ocorrer problemas, existem vários usuários que conseguiram atualizar, até mesmo teve recente um que atualizou da versãp 3.11 para a atual e consegui manter o mesmo banco.

**Comment by R4T0** [comment]
faço o mesmo processo da instalação. com o mesmo banco?



Douglas Tecnologia em Redes
Em Gianluca Bine <notifications@github.com>, 24 de jan de 2021 3:23 PM escreveu:

@R4T0<https://github.com/R4T0> Não era pra ocorrer problemas, existem vários usuários que conseguiram atualizar, até mesmo teve recente um que atualizou da versãp 3.11 para a atual e consegui manter o mesmo banco.

**Comment by cabralwms** [comment]
Hoje ao tentar atualizar minha versão mapos 4.28.0 para nova deu erro. Ao Baixar o pacote e instalar padrão enviando os arquivos e rodando o composer funciona. Mas se vou em sistema e clico em atualizar da erro de novo. Postei no whatsapp a foto do erro,.

**Comment by Pr3d4dor** [comment]
@cabralwms e @R4T0 Como eu sempre digo nas demais issues, o melhor mesmo é ainda atualizar manualmente e não usando o atualizador do sistema, ele ainda não está 100%.

Então o ideal para atualizar é baixar em outra pasta e copiar seus arquivos de configuração da pasta config para usar seu banco de dados anterior.

E atualizar seu banco de dados se tiver algum arquivo para ser executado dentro da pasta updates ou executar o atualizar banco de dados dentro do sistema.

**Comment by cabralwms** [comment]
opa meu amigo sim eu faço um teste em outra pasta sem ser a  de produção, então só passo para de produção quando deu certo na que faço o teste. Mas desculpe caso não tenha sido claro. muito obrigado pela atenção

**Comment by R4T0** [comment]
beleza meu amigo obrigado então vou baixar a nova versão e substituir para a pasta antiga. fazendo o backup da pasta config. vou testar aqui e posto em breve



Douglas Tecnologia em Redes
Em cabralwms <notifications@github.com>, 24 de jan de 2021 3:54 PM escreveu:

opa meu amigo sim eu faço um teste em outra pasta sem ser a de produção, então só passo para de produção quando deu certo na que faço o teste. Mas desculpe caso não tenha sido claro. muito obrigado pela atenção

**Comment by R4T0** [comment]
Só passando para dar o feedback. Fiz o backup da pasta antiga.. Baixei a nova versão do sistema. Rodei o composer e refiz a instalação via browser... Funcionou perfeitamente.
