### ISSUE TITLE
Melhoria para Modulo Financeiro / Clientes / Usuário

### ISSUE THREAD

**Issue by cleytonasa** [RamonSilva20/mapos#1176]
Boa noite, 

FINANCEIRO
Vocês poderiam em adicionar nova receita, na aba clientes vincular esse campo a os clientes já cadastrados.
Na forma de pagamento acrescentar o PIX.

CLIENTES
Poderia mudar o modulo para CLIENTES/FORNECEDORES
numa opção no cadastro num Checkbox selecionando ou poderia criar um modulo fornecedores.

USUARIOS
Dispensar a opção de CPF no cadastro de Usuário.

**Comment by willph** [comment]
> Boa noite,
> 
> FINANCEIRO
> Vocês poderiam em adicionar nova receita, na aba clientes vincular esse campo a os clientes já cadastrados.
> Na forma de pagamento acrescentar o PIX.
> 
> CLIENTES
> Poderia mudar o modulo para CLIENTES/FORNECEDORES
> numa opção no cadastro num Checkbox selecionando ou poderia criar um modulo fornecedores.
> 
> USUARIOS
> Dispensar a opção de CPF no cadastro de Usuário.

`Na forma de pagamento acrescentar o PIX.`

Isso é acrescenta uma nova forma de pagamento?

Feito boleto e o link de pagamento, só que sendo o PIX
