### ISSUE TITLE
erro ao criar conta na área do cliente

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#1178]
na hora de criar um novo cadastro na área do cliente está dando um bug

primeiro o campo cpf esta sem a mascara para deixar o cpf formatado
se você coloca um cpf invalido ao invés de avisar ele só bloqueia a edição
se colocar um cpf já existente ele faz a mesma coisa 

sou seja o cliente não consegue fazer o cadastro e nem sabe por que

![Capturar](https://user-images.githubusercontent.com/31580600/105721293-2da10500-5f03-11eb-8115-fbbc7265e4d6.PNG)

desde já obrigado pela atenção

**Comment by cabralwms** [comment]
Fiz alguns testes tambem, ao tentar cadastrar um cliente que já existe não aparece erro. Aquele botão pesquisar o que seria? ele sempre da que o CPF está invalido, mesmo sendo valido.

**Comment by marllonferreira** [comment]
> Fiz alguns testes tambem, ao tentar cadastrar um cliente que já existe não aparece erro. Aquele botão pesquisar o que seria? ele sempre da que o CPF está invalido, mesmo sendo valido.

no botão de pesquisa e para puxa os dados de um cnpj ele não funciona com cpf
