### ISSUE TITLE
Erro de logomarca no Cadastro de Dados do Emitente

### ISSUE THREAD

**Issue by yago-rocha** [RamonSilva20/mapos#118]
[Erro Mapos.pdf](https://github.com/RamonSilva20/mapos/files/1940233/Erro.Mapos.pdf)

Estou tendo este erro ao tentar colocar uma Logomarca no Cadastro  de Dados do Emitente. Se alguém puder me ajudar agradeço.

**Comment by Augustobf** [comment]
@yago-rocha Crie uma pasta uploads dentro de assents, dê permissões de escrita. EX: chmod 777 assets/uploads/

**Comment by mendaxcn** [comment]
Boa noite senhores,

Fiz o procedimento de criar um diretório chamado uploads dentro de assents, com a permissão:

chmod 777 assets/uploads/*

E sem sucesso, poderia me informar se é preciso fazer mais alguma coisa? Obrigado.

MendaxCN
