### ISSUE TITLE
Arquivo Update para a V4.29.0

### ISSUE THREAD

**Issue by Isaqjonatas** [RamonSilva20/mapos#1180]
Olá, baixei o arquivo da nova versão, notei que não tem o arquivo de atualização na pasta Update para a versão 4.29.0. Utilizo hospedagem online, preciso desse arquivo para atualizar a versão q utilizo.

**Comment by Pr3d4dor** [comment]
@Isaqjonatas Não teve alteração no banco de dados da versão v4.28.0 à v4.29.0

**Comment by Isaqjonatas** [comment]
Então, tem que reinstalar o arquivo completo dessa versão?

**Comment by Pr3d4dor** [comment]
Sim, basta somente reinstalar usando seu banco atual.
