### ISSUE TITLE
PRODUTO PRESO NA OS "FATURADA"

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1181]
Saudações... Primeiramente venho expressar minha admiração pelo projeto. E parabenizar cada um que adbicou seu tempo para compor esse sistema. "Está extremamente satisfatório ver a evolução das suas funções".

Pessoal não se foi proposital ou não.. mas. Notei que na v29.0 a OS depois de faturada, não é possível quaisquer alteração.
Até ai ok. Porém o se eu FATURAR e por acaso o cliente não me pagar por conta de algum motivo "esquecimento do cartão". O produto é retirado do meu sistema e fica preso naquela OS. Tendo em vista que se esse cliente nunca mais voltar. O produto "técnicamente não consta no estoque". 

![image](https://user-images.githubusercontent.com/73944522/105743037-a196d980-5f12-11eb-8f50-90a961ab8dde.png)

![image](https://user-images.githubusercontent.com/73944522/105743216-d440d200-5f12-11eb-849f-e1a3d0456ffb.png)
  
VEJO DUAS OPÇÕES QUE PODEM RESOLVER

A 1 é poder alterar as OS por meio de " Permissões ".  
![image](https://user-images.githubusercontent.com/73944522/105744747-e8d19a00-5f13-11eb-91ff-e15bfaba2392.png)

Ou 
A 2 é que o item "produto" dê baixa no estoque somente quando o financeiro daquela OS ter dado baixa.

**Comment by Pr3d4dor** [comment]
@R4T0 Como comentei em outra PR, o @seitbnao irá implementar uma permissão para permitir editar OS faturada/cancelada, só aguardar a PR.

**Comment by R4T0** [comment]
Ah sim obrigado @Pr3d4dor . Vou fechar essa. Pois cheguei a uma conclusão que isso não é um bug
