### ISSUE TITLE
Cadastro de produtos não exibe "Unidade"

### ISSUE THREAD

**Issue by mikxingu** [RamonSilva20/mapos#1182]
** Descreva o bug **
Vi que na atualização 4.29 alterava algo relacionado a unidades dos produtos.
Atualizei meu mapos e atualizei o banco, aparentemente sem problemas, mas na tela de cadastro de produtos, não mostra mais tipo "Unidade" de produtos. Seria um bug? Pois nas abas de configuração do sistema não encontrei lugar para cadastrar. Aguardo uma resposta. Obrigado!

![erro unidade mapos](https://user-images.githubusercontent.com/30123586/105756439-6359e400-5f2b-11eb-9b16-fb3898a47b20.png)

**Comment by R4T0** [comment]
Na versão 4.29.0 Está funcionando perfeitamente. 
![image](https://user-images.githubusercontent.com/73944522/105790592-00804100-5f5b-11eb-8edb-bb2cc58c2234.png)
Lembrando para funcionar precisei rodar um update na base de dados!
![image](https://user-images.githubusercontent.com/73944522/105790721-2efe1c00-5f5b-11eb-85e2-e7368c6b2015.png)

**Comment by seitbnao** [comment]
Mantenha sempre seu banco de dados atualizado, é sempre recomendado que mesmo depois de uma instalação limpa você deve ir em atualizar o banco de dados.

**Comment by R4T0** [comment]
@mikxingu  funcionou?

**Comment by mikxingu** [comment]
@R4T0  testei hoje, eu fiz a atualização do banco tanto pelo sistema quanto manualmente, mesmo assim, sem sucesso.
@Pr3d4dor  Vou verificar os logs

**Comment by willph** [comment]
> 
> 
> ** Descreva o bug **
> Vi que na atualização 4.29 alterava algo relacionado a unidades dos produtos.
> Atualizei meu mapos e atualizei o banco, aparentemente sem problemas, mas na tela de cadastro de produtos, não mostra mais tipo "Unidade" de produtos. Seria um bug? Pois nas abas de configuração do sistema não encontrei lugar para cadastrar. Aguardo uma resposta. Obrigado!
> 
> ![erro unidade mapos](https://user-images.githubusercontent.com/30123586/105756439-6359e400-5f2b-11eb-9b16-fb3898a47b20.png)

Você já verificou se na pasta `assets>json` tem um arquivo chamado `tabela_medidas`?

[tabela_medidas.json](https://github.com/RamonSilva20/mapos/blob/master/assets/json/tabela_medidas.json)

**Comment by mikxingu** [comment]
> 

> > ** Descreva o bug **
> > Vi que na atualização 4.29 alterava algo relacionado a unidades dos produtos.
> > Atualizei meu mapos e atualizei o banco, aparentemente sem problemas, mas na tela de cadastro de produtos, não mostra mais tipo "Unidade" de produtos. Seria um bug? Pois nas abas de configuração do sistema não encontrei lugar para cadastrar. Aguardo uma resposta. Obrigado!
> > ![erro unidade mapos](https://user-images.githubusercontent.com/30123586/105756439-6359e400-5f2b-11eb-9b16-fb3898a47b20.png)
> 
> Você já verificou se na pasta `assets>json` tem um arquivo chamado `tabela_medidas`?
> 
> [tabela_medidas.json](https://github.com/RamonSilva20/mapos/blob/master/assets/json/tabela_medidas.json)

@willph o problema está exatamente nesse arquivo. Segue imagem do console. Utilizo a imagem docker, mas naveguei até a pasta, e aparentemente o arquivo está no local correto.
Por via de duvidas, renomeei o arquivo original e salvei um novo com esse arquivo que vc mandou o link, restartei o docker, mas mesmo assim, sem sucesso.
![console](https://user-images.githubusercontent.com/30123586/106010124-db451d00-6097-11eb-811a-1adb311969bb.png)
![docker](https://user-images.githubusercontent.com/30123586/106010131-dc764a00-6097-11eb-92c1-ab258154aabb.png)

**Comment by willph** [comment]
> > 
> 
> > > ** Descreva o bug **
> > > Vi que na atualização 4.29 alterava algo relacionado a unidades dos produtos.
> > > Atualizei meu mapos e atualizei o banco, aparentemente sem problemas, mas na tela de cadastro de produtos, não mostra mais tipo "Unidade" de produtos. Seria um bug? Pois nas abas de configuração do sistema não encontrei lugar para cadastrar. Aguardo uma resposta. Obrigado!
> > > ![erro unidade mapos](https://user-images.githubusercontent.com/30123586/105756439-6359e400-5f2b-11eb-9b16-fb3898a47b20.png)
> > 
> > 
> > Você já verificou se na pasta `assets>json` tem um arquivo chamado `tabela_medidas`?
> > [tabela_medidas.json](https://github.com/RamonSilva20/mapos/blob/master/assets/json/tabela_medidas.json)
> 
> @willph o problema está exatamente nesse arquivo. Segue imagem do console. Utilizo a imagem docker, mas naveguei até a pasta, e aparentemente o arquivo está no local correto.
> Por via de duvidas, renomeei o arquivo original e salvei um novo com esse arquivo que vc mandou o link, restartei o docker, mas mesmo assim, sem sucesso.
> ![console](https://user-images.githubusercontent.com/30123586/106010124-db451d00-6097-11eb-811a-1adb311969bb.png)
> ![docker](https://user-images.githubusercontent.com/30123586/106010131-dc764a00-6097-11eb-92c1-ab258154aabb.png)

Já recompilou a imagem no docker?

**Comment by mikxingu** [comment]
> > > 
> > 
> > 
> > > > ** Descreva o bug **
> > > > Vi que na atualização 4.29 alterava algo relacionado a unidades dos produtos.
> > > > Atualizei meu mapos e atualizei o banco, aparentemente sem problemas, mas na tela de cadastro de produtos, não mostra mais tipo "Unidade" de produtos. Seria um bug? Pois nas abas de configuração do sistema não encontrei lugar para cadastrar. Aguardo uma resposta. Obrigado!
> > > > ![erro unidade mapos](https://user-images.githubusercontent.com/30123586/105756439-6359e400-5f2b-11eb-9b16-fb3898a47b20.png)
> > > 
> > > 
> > > Você já verificou se na pasta `assets>json` tem um arquivo chamado `tabela_medidas`?
> > > [tabela_medidas.json](https://github.com/RamonSilva20/mapos/blob/master/assets/json/tabela_medidas.json)
> > 
> > 
> > @willph o problema está exatamente nesse arquivo. Segue imagem do console. Utilizo a imagem docker, mas naveguei até a pasta, e aparentemente o arquivo está no local correto.
> > Por via de duvidas, renomeei o arquivo original e salvei um novo com esse arquivo que vc mandou o link, restartei o docker, mas mesmo assim, sem sucesso.
> > ![console](https://user-images.githubusercontent.com/30123586/106010124-db451d00-6097-11eb-811a-1adb311969bb.png)
> > ![docker](https://user-images.githubusercontent.com/30123586/106010131-dc764a00-6097-11eb-92c1-ab258154aabb.png)
> 
> Já recompilou a imagem no docker?

Sim, recompilada. Acabei de descobrir que aparentemente pode ser algum problema de permissao.
Entrei no cadastro de clientes, e ocorre o mesmo erro pro arquivo "estados.json".

**Comment by willph** [comment]
Ok Então.  Vou fica no aguardo do seu teste

**Comment by mikxingu** [comment]
Era um problema de permissão. Desculpa a confusão e obrigado pela ajuda.
Resolvi dando permissão total a pasta raiz do MapOS. Vou fechar a Issue, mas fica como documentação caso alguém tenha o mesmo problema.
Obrigado pela ajuda!
