### ISSUE TITLE
Sugestão de recurso

### ISSUE THREAD

**Issue by drwdos** [RamonSilva20/mapos#1183]
Gostaria de sugerir se possível aos desenvolvedores, recursos de abertura de chamados que os cliente possam utilizar. ou até mesmo o usuário do sistema. Seria muito interessante para quem gerencia parque tecnológico de empresas.

Até o momento o sistema está ótimo, só tenho à elogiar os colaboradores...

**Comment by R4T0** [comment]
@drwdos  Cara para esse tipo de propósito tem projetos prontos,  abrir chamado creio que sairia muito do foco.. Dá uma olhada nesse sistema.. " Eu uso "
https://glpi-project.org/pt-br/

**Comment by Pr3d4dor** [comment]
@drwdos Obrigado pela sugestão, mas como o @R4T0 disse eu acho que o GLPI lhe atenderia melhor, mas eu acho interessante a ideia de "chamados" no mapos, mas sendo separado da OS, ou seja, um chamado pode virar "OS".

**Comment by drwdos** [comment]
Obrigado pela sugestão do GLPI. Muito interessante e funcional para o que quero. Vai me ajudar.
Outra sugestão que gostaria de dar, é uma forma campo opção de desconto antes de faturar, como devem muitos devem passar por isso, são os clientes que choram demais. assim o pessoal consegue trabalhar um valor pra oferecer algum desconto. Desculpe se tiver esta opção em algum recurso eu ainda não notei. Obrigado, e mais uma vez parabéns aos desenvolvedores!
