### ISSUE TITLE
Pagamento Recorrente

### ISSUE THREAD

**Issue by danillodars** [RamonSilva20/mapos#1186]
Olá,

Gostaria de saber se é possível, além da forma de pagamento por boleto ou link de pagamento, adicionar também pagamento recorrente.

Acontece que as vezes é fechado contrato mensais com alguns clientes, pensando nisso, acredito ser interessante que o sistema possua essa funcionalidade.

O pagamento Recorrente iria facilitar o lado do cliente, ele poderia acompanhar no menu cobrança se existe ou não alguma mensalidade em aberto, facilitaria também para o operador do sistema já que ele iria evitar o retrabalho.

Como o sistema ele é voltado para ordem de serviços, acredito que seria útil para muitas pessoas.

**Comment by seitbnao** [comment]
Possibilidade há sim, no entanto vamos pausar a adição de novos recursos por algum tempo focando apenas nas correções de bugs encontrados, e dar continuidade em uma versão com novas tecnologias.

**Comment by Pr3d4dor** [comment]
@danillodars É possível, porém não é tão trivial e como o @seitbnao a partir de agora iremos focar mais em correção de bugs e não na adicão de novas funcionalidades.
