### ISSUE TITLE
ALGUEM ME AJUDA COMO RESOLVER ESSE ERRO NO FINAL DA INSTALAÇAO

### ISSUE THREAD

**Issue by tombeira5** [RamonSilva20/mapos#1187]
[](https://ibb.co/ChVnL7q)

**Comment by tombeira5** [comment]
https://ibb.co/ChVnL7q

**Comment by tombeira5** [comment]
TA DANDO ESSE ERRO

**Comment by tombeira5** [comment]
![erro](https://user-images.githubusercontent.com/78092643/106023475-988a4180-60a5-11eb-94a1-64c3b5035b02.png)

**Comment by pvagasm** [comment]
Estou com esse mesmo problema depois que desinstalei e tentei instalar uma atual
como posso proceder?
Obrigada

**Comment by willph** [comment]
Parece que tem relação a está logado no github, se não le errado.

Vê se com isso resolve.

https://git-scm.com/book/pt-br/v2/Come%C3%A7ando-Configura%C3%A7%C3%A3o-Inicial-do-Git

**Comment by pvagasm** [comment]
@willph Oi tudo bem? eu instalei o GIT configurei com o user e email seguindo os passos do link acima, e mesmo assim não estou conseguindo instalar o programa novamente, tens como me auxiliar em como proceder apos a instalação do git?

**Comment by willph** [comment]
> @willph Oi tudo bem? eu instalei o GIT configurei com o user e email seguindo os passos do link acima, e mesmo assim não estou conseguindo instalar o programa novamente, tens como me auxiliar em como proceder apos a instalação do git?

Só pra eu entende. 

Depois desse procedimento rodou novamente o composer install ?

Poderia postar o print do cmd pra vê o erro?

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107117868-f95f0a00-685b-11eb-8584-2bb3e3e24a80.png)

**Comment by willph** [comment]
Falta instalar o composer

https://getcomposer.org/

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107118459-ef3f0a80-685f-11eb-9e4a-9dcf3caff4a9.png)
Agora instalou?

**Comment by willph** [comment]
> ![image](https://user-images.githubusercontent.com/43431963/107118459-ef3f0a80-685f-11eb-9e4a-9dcf3caff4a9.png)
> Agora instalou?

Sim.
Tudo ok.

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107118537-67a5cb80-6860-11eb-9942-7beffa1e8508.png)
Mas continua aparecer essa msg :(

**Comment by willph** [comment]
> ![image](https://user-images.githubusercontent.com/43431963/107118537-67a5cb80-6860-11eb-9942-7beffa1e8508.png)
> Mas continua aparecer essa msg :(

Você atualizou o sistema foi?

**Comment by pvagasm** [comment]
Não eu removi da minha maquina a versão anterior e fiz o processo como se estivesse fazendo do zero novamente
exclui até o xampp e reinstalei e agora não consigo instalar novamente :/

**Comment by willph** [comment]
> Não eu removi da minha maquina a versão anterior e fiz o processo como se estivesse fazendo do zero novamente
> exclui até o xampp e reinstalei e agora não consigo instalar novamente :/

Verificar linha 59 do arquivo index.php na pasta raiz se está como `production`. Se não estiver substituir.

![Screenshot_20210206-095304_Chrome](https://user-images.githubusercontent.com/17226802/107118725-61641f00-6861-11eb-9312-b0634bfcdd8c.jpg)

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107118863-6d9cac00-6862-11eb-86e6-b2c43e9eaee1.png)
Está aparecendo assim

**Comment by willph** [comment]
> ![image](https://user-images.githubusercontent.com/43431963/107118863-6d9cac00-6862-11eb-86e6-b2c43e9eaee1.png)
> Está aparecendo assim

Alterar linha 59 para `production` no lugar da `pre_installation`

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107119119-3202e180-6864-11eb-95e9-3cd0ea826a0e.png)
Não consigo logar, acessei o bd e aparece essa msg

**Comment by pvagasm** [comment]
![image](https://user-images.githubusercontent.com/43431963/107119166-8312d580-6864-11eb-87f1-81353c4276b4.png)

**Comment by willph** [comment]
Como foi feita essa instalação?

Você seguiu esses passos https://github.com/RamonSilva20/mapos/blob/master/Instalacao_xampp_windows.md?

Sua instalação é em localhost ou na hospedagem?

**Comment by pvagasm** [comment]
Fiz o mesmo procedimento porem quando aparecei pra instalar ele pulou da imagem 9 pra 11. Não apareceu aquela img onde insiro os dados de login

**Comment by pvagasm** [comment]
@willph consegui arrumar, exclui tudo e refiz conforme você explicou e deu certo! Agradeço de coração, muito obrigada <3

**Comment by willph** [comment]
De nada. Qualquer coisa tem o grupo Mapos no Whatsapp onde o pessoal se
ajuda.

Em sáb, 6 de fev de 2021 12:54, pvagasm <notifications@github.com> escreveu:

**Comment by pvagasm** [comment]
@willph pode me colocar no grupo (55) 991585768 obrigada, bom findi!

**Comment by willph** [comment]
> @willph pode me colocar no grupo (55) xxxxxxxxxx obrigada, bom findi!

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by willph** [comment]
> @willph pode me colocar no grupo (55) xxxxx-xxxx obrigada, bom findi!

Por motivos de segurança editei e apaguei seu número.
