### ISSUE TITLE
Copiar e colar texto do office (word e outlook) nos campos de "adicionar OS" 

### ISSUE THREAD

**Issue by Loury-Silva** [RamonSilva20/mapos#1189]
Prezados, quando copia e colo texto  do word ou do outlook nos campos da tela de adicionar OS ou Editar OS, salva no banco uma infinidade de códigos de formatação. Um campo curto de no máximo 3 linhas fica com mais de 100 linhas.
Isso só se reflete no banco nas telas de visualização do sistema fica oculto, mas creio, isso acabará por inchar desnecessariamente o banco.
Alguém sabe como resolver esse problema?
![BD_OS](https://user-images.githubusercontent.com/73559534/106144000-a2cf3d00-6184-11eb-96fb-862408601cb1.jpg)

**Comment by seitbnao** [comment]
Isso é normal, o word tem sua própria formatação e não e 100% compatível com editores de texto simplificados igual ao do mapos

**Comment by marllonferreira** [comment]
faz um teste colando primeiro no bloco de nota depois para o mapos
