### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1190]
Boa noite pessoal, tudo bem.

Até a versão 4.28 estava instalando numa boa mais resolvi testar a versão 4.29, pois a 4.28 estava com problema de baixa no estoque.
Só que ao instalar começando a partir do composer ele apresenta o seguinte erro: Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-6K6Q1KD+2021-01-29+0024
to retrieve a token. It will be stored in "C:/Users/Service Info/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

????

**Comment by seitbnao** [comment]
Faça uma reinstalação do composer, o servidor web que você usa com php 7.4 ou superior

**Comment by robertonfaustino** [comment]
vc tem que acessar esse link (https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-6K6Q1KD+2021-01-29+0024) do github a logar com sua conta, após isso ele vai te dar um token  e vc coloca no cmd
onde diz:
Token (hidden):

depois que colocar isso, vai instalar normalmente. Fiz isso aqui e funcionou

**Comment by glbservicos** [comment]
> vc tem que acessar esse link ( https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-6K6Q1KD+2021-01-29+0024 ) do github a logar com sua conta, após isso ele vai te dar um token e vc coloca no cmd
> onde diz:
> Token (oculto):
> 
> depois que colocar isso, vai instalar normalmente. Fiz isso aqui e funcionou

Olá amigo, se puder simular um passo a passo ai....com relação a parte da adição do novo token gerado aqui no site pois nao consigo tambem.

**Comment by robertonfaustino** [comment]
> > vc tem que acessar esse link ( https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-6K6Q1KD+2021-01-29+0024 ) do github a logar com sua conta, após isso ele vai te dar um token e vc coloca no cmd
> > onde diz:
> > Token (oculto):
> > depois que colocar isso, vai instalar normalmente. Fiz isso aqui e funcionou
> 
> Olá amigo, se puder simular um passo a passo ai....com relação a parte da adição do novo token gerado aqui no site pois nao consigo tambem.

Ao instalar o composer, ele retorna com a mensagem que contém um link
https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-6K6Q1KD+2021-01-29+0024
(não vai ser igual, muda o nome do pc e data)

Vamos aos passos:
Copie o link, abra o navegador e cole o link
Vai abrir a pagina do github
Faça o login ou crie uma conta
Após feito o login, vai aparecer um token na tela
Copie esse token
Volte la na instalação, cole o token la, ele nao vai aparecer nada, vai ficar oculto, de um "enter"
depois disso vai continuar a instalação
