### ISSUE TITLE
Não gera e não fatura pagamentos

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#1191]
Erro ao tentar fatura

versão 4.29.0

![Screenshot_1](https://user-images.githubusercontent.com/76854766/106214613-ed18e400-61ad-11eb-9f84-47322316bc7e.jpg)

**Comment by Pr3d4dor** [comment]
@CarlosCavalcante87 Parece que seu banco não está atualizado.

**Comment by CarlosCavalcante87** [comment]
Obrigado, ajudou.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
