### ISSUE TITLE
Sugestões de melhorias para o projeto.

### ISSUE THREAD

**Issue by naodoubuff** [RamonSilva20/mapos#1192]
Estou utilizando a versão 4.29.0 e estou gostando bastante.
Porém tenho algumas sugestões.

1º Tirar obrigatoriedade do Cpf
2º Fazer um campo com a data de nascimento do cliente, para que o sistema alerte, e talvez até possa mandar mensagem via wpp, como nas o.s
3º Acho que poderiam fazer  um campo para cadastrar o tipo de equipamento. Ex: Celulares,Notebooks,Tablets e afins.
Incluindo na hora de fazer a abertura da O.S. Selecionando o Tipo de equipamento e sua Marca ja facilitaria.
Pra quem tem assistência grande, com muitas prateleiras, é meio complicado ficar procurando pela etiqueta do Nº da os.
Obrigado !_

**Comment by seitbnao** [comment]
A obrigatoriedade dos campos ao fazer um cadastro do cliente foi removida, sendo obrigatório apenas o NOME, sobre novos recursos iremos pausar por algum tempo, afim de corrigir os bugs encontrados nas versões atuais, e dar continuidade a versão do mapos  em laravel

**Comment by R4T0** [comment]
@seitbnao Fala man blza? Cara vcs tem algo planejado para as migrações do whats para o Telegram... Aqui no meu estado MS, as pessoas estão abandonando o whats e migrando para o Telegram.

**Comment by naodoubuff** [comment]
> A obrigatoriedade dos campos ao fazer um cadastro do cliente foi removida, sendo obrigatório apenas o NOME, sobre novos recursos iremos pausar por algum tempo, afim de corrigir os bugs encontrados nas versões atuais, e dar continuidade a versão do mapos em laravel

Aqui ainda, pede obrigatoriedade do campo CPF/CNPJ. To usando na versão mais atualizada.. 
![image](https://user-images.githubusercontent.com/78187809/106349217-fc318c00-62aa-11eb-89b3-4d6fde71afd8.png)

**Comment by robertonfaustino** [comment]
Aqui tbm nao aceita só o nome, na versão mais atual

![image](https://user-images.githubusercontent.com/38968509/106458414-1caa4380-646f-11eb-82de-3e2c4487825a.png)
