### ISSUE TITLE
API MercadoPago

### ISSUE THREAD

**Issue by robertonfaustino** [RamonSilva20/mapos#1193]
Instalei a ultima versão hoje (4.29.0) e nao encontro o local pra preencher as credenciais do mercadopago
Alguém poderia me auxiliar?

![image](https://user-images.githubusercontent.com/38968509/106339528-9971cd80-6275-11eb-849b-6200fa2f0af8.png)

**Comment by Pr3d4dor** [comment]
@robertonfaustino As credenciais são configuradas no arquivo `config/payment_gateways.php`

**Comment by robertonfaustino** [comment]
> @robertonfaustino As credenciais são configuradas no arquivo `config/payment_gateways.php`

vlw obrigado
só precisa colocar access_token, public_key, client_secret e 'client_id, certo?

**Comment by robertonfaustino** [comment]
![image](https://user-images.githubusercontent.com/38968509/106343897-756ab800-6286-11eb-8c6b-2f6b6596c1a8.png)

**Comment by Pr3d4dor** [comment]
@robertonfaustino Você não pode gerar um boleto para você mesmo (emitente e cliente iguais)
