### ISSUE TITLE
Faturamento da OS Parcelado

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1194]
Boa noite, 

Existe a possibilidade de faturar a OS parcelado? assim que clicamos em FATURAR abrir um campo para o parcelamento.
minha dificuldade é essa no momento, porque parcelo uma venda de um notebook por exemplo, mas na hora de faturar, no financeiro o valor esta cheio.

**Comment by augustocoletti** [comment]
Esta função é muito interessante, não apenas no faturamento de OS mas também em vendas e despesas.

**Comment by Pr3d4dor** [comment]
@jsfachini Obrigado pela sugestão, mas no momento estamos focados somente em correção de bugs e não na adicão de novas features.

**Comment by hodevcom** [comment]
Também precisei desse item e acabei criando de forma customizada. @Pr3d4dor estarei te encaminhando o código.

Estou atuando na correção / implantação de alguns novos itens interessantes. Me chama quando poder para falarmos.

![image](https://user-images.githubusercontent.com/66075384/108625249-9effa500-7428-11eb-87a9-a4a0df1fef36.png)

**Comment by Pr3d4dor** [comment]
@hodevcom Se você quiser contribuir, basta fazer uma PR com o código.
