### ISSUE TITLE
Bom dia a todos! Criei uma conta no Gerencianet, configurei o arquivo payment_gateways mas mesmo assim não consigo gerar a cobrança.

### ISSUE THREAD

**Issue by ivigneeporto** [RamonSilva20/mapos#1195]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by willph** [comment]
Qual código pegou, produção ou desenvolvimento?

Em sáb, 30 de jan de 2021 14:48, ivigneeporto <notifications@github.com>
escreveu:

**Comment by ivigneeporto** [comment]
Boa noite! 
Em primeiro lugar obrigado imensamente por me responder.
Vamos lá ...
Primeiro tentei com o código de Desenvolvimento
Quando mando gerar a COBRANÇA ele fica infinitamente com o popup PROCESSANDO: CRIANDO COBRANÇA, mas nunca cria.
Depois tentei com o código de PRODUÇÃO, mas o erro acima se repetiu.
![email](https://user-images.githubusercontent.com/49702376/106370240-e5387b80-6336-11eb-8edc-7355066657d6.png)

**Comment by ivigneeporto** [comment]
Fiz a configuração abaixo:

<?php if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

$config['payment_gateways'] = [
    'GerencianetSdk' => [
        'name' => 'GerenciaNet',
        'library_name' => 'GerencianetSdk',
        'production' => false,
        'credentials' => [
            'client_id' => 'Client_Id_196349c84423a3a91d06d93f95f41409a45475bf',
            'client_secret' => 'Client_Secret_751b38485cb1bd862d0a39d3509d0b8d26d38065'
        ],
        'timeout' => 30,
        'boleto_expiration' => 'P3D',
        'payment_methods' => [
            [
                'name' => 'Boleto',
                'value' => 'boleto',
            ],
            [
                'name' => 'Link',
                'value' => 'link'
            ]
        ],
        'transaction_status' => [
            'new' => 'Cobrança / Assinatura gerada',
            'waiting' => 'Aguardando a confirmação do pagamento',
            'paid' => 'Pagamento confirmado',
            'unpaid' => 'Não foi possível confirmar o pagamento da cobrança',
            'refunded' => 'Pagamento devolvido pelo lojista ou pelo intermediador Gerencianet',
            'contested' => 'Pagamento em processo de contestação',
            'canceled' => 'Cobrança/Assinatura cancelada pelo vendedor ou pelo pagador ',
            'settled' => 'Cobrança/Pagamento foi confirmada manualmente ',
            'link' => 'Link de pagamento',
            'expired' => 'Link/Assinatura de pagamento expirado',
            'active' => 'Assinatura ativa Todas as cobranças estão sendo geradas',
            'finished' => 'Carnê está finalizado',
            'up_to_date' => 'Carnê encontra-se em dia',
        ]
    ],
    'MercadoPago' => [
        'name' => 'MercadoPago',
        'library_name' => 'MercadoPago',
        'credentials' => [
            'access_token' => 'APP_USR-3246144180330963-013018-3c45dc3e5baf93522ba1c1accad2f0e4-679464473',
            'public_key' => 'APP_USR-047abd45-4d1d-4bc9-a03c-d947d7696b46',
            'client_secret' => 'h500GZ3nzSKbq0W9p1n4rLavxekXckKd',
            'client_id' => '3246144180330963',
            'integrator_id' => '',
            'platform_id' => '',
            'corporation_id' => ''
        ],
        'boleto_expiration' => 'P3D',
        'payment_methods' => [
            [
                'name' => 'Boleto',
                'value' => 'boleto',
            ]
        ],
        'transaction_status' => [
            'pending' => 'O usuário ainda não concluiu o processo de pagamento',
            'approved' => 'O pagamento foi aprovado e credenciado',
            'authorized' => 'O pagamento foi autorizado, mas ainda não foi capturado',
            'in_process' => 'O pagamento está sendo revisado',
            'in_mediation' => 'Os usuários iniciaram uma disputa',
            'rejected' => 'O pagamento foi rejeitado, o usuário pode tentar o pagamento novamente',
            'cancelled' => 'O pagamento foi cancelado por uma das partes ou porque o prazo para pagamento expirou',
            'refunded' => 'O pagamento foi reembolsado ao usuário',
            'charged_back' => 'Foi feito um estorno no cartão de crédito do comprador'
        ]
    ]
];

**Comment by ivigneeporto** [comment]
Fiz a configuração conforme a imagem abaixo, com o Mercado Pago funcionou tudo ok, exceto que quando tento excluir a cobrança da um erro muito louco.
![confi](https://user-images.githubusercontent.com/49702376/106370281-42ccc800-6337-11eb-9bfd-b99fceb77968.png)

**Comment by willph** [comment]
> Fiz a configuração conforme a imagem abaixo, com o Mercado Pago funcionou tudo ok, exceto que quando tento excluir a cobrança da um erro muito louco.
> ![confi](https://user-images.githubusercontent.com/49702376/106370281-42ccc800-6337-11eb-9bfd-b99fceb77968.png)

Em modo de produção tem que mudar linha 9

Production de `false` para `true`

**Comment by ivigneeporto** [comment]
Vou tentar agora meu amigo! 
E no que eu puder contribuir com o grupo me coloco a disposição! Eu trabalho produzindo sites, não sou programador, mas trabalho bem com o WordPress, se eu puder ser útil estarei a disposição!

**Comment by willph** [comment]
> 
> 
> Vou tentar agora meu amigo!
> E no que eu puder contribuir com o grupo me coloco a disposição! Eu trabalho produzindo sites, não sou programador, mas trabalho bem com o WordPress, se eu puder ser útil estarei a disposição!

qual sua versão de php?

Aqui esta funcionando, mas minha versão é a 7.4.11

**Comment by ivigneeporto** [comment]
Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?

**Comment by willph** [comment]
> 
> 
> Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?

com o código de produção?

**Comment by ivigneeporto** [comment]
> > Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?
> 
> com o código de produção?

Me corrija se eu estiver entendido errado, quando você diz código de produção é o código PHP da página, ou é client id e o client secret, fiquei com essa dúvida. 
De qualquer maneira estou editando o código PHP que já vem na página e coloquei os códigos cliente id e cliente secret de produção quando setei para true

**Comment by willph** [comment]
> 
> 
> Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?

ta no grupo do mapos whatsaap? qual nome lá

**Comment by ivigneeporto** [comment]
> > Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?
> 
> ta no grupo do mapos whatsaap? qual nome lá

Não estou, se puder me adicionar ficaria muito grato (33) 98845-6512 meu nome é Rodrigo Porto

**Comment by willph** [comment]
>  client id e o client secret

 `client id` e o `client secret` no gerencianet, se mudar pra `true` tem que pegar o codigo de produção e se mudar pra `false` pegara o codigo de desenvolvimento.

**Comment by ivigneeporto** [comment]
> > client id e o client secret
> 
> `client id` e o `client secret` no gerencianet, se mudar pra `true` tem que pegar o codigo de produção e se mudar pra `false` pegara o codigo de desenvolvimento.

Entendi, então to fazendo certinho sim!

**Comment by willph** [comment]
> 
> 
> > > Ficou com o mesmo erro, mesmo fazendo a alteração na linha 09 de false para true, acredita que tenha algo a mais que posso ter feito de errado?
> > 
> > 
> > ta no grupo do mapos whatsaap? qual nome lá
> 
> Não estou, se puder me adicionar ficaria muito grato (33) 98845-**** meu nome é Rodrigo Porto

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by ivigneeporto** [comment]
> > Vou tentar agora meu amigo!
> > E no que eu puder contribuir com o grupo me coloco a disposição! Eu trabalho produzindo sites, não sou programador, mas trabalho bem com o WordPress, se eu puder ser útil estarei a disposição!
> 
> qual sua versão de php?
> 
> Aqui esta funcionando, mas minha versão é a 7.4.11

A minha é a 7.4, mas ocorreu um erro estranho, eu pensei a principio que pudesse ser pelo fato de estar atualizando as versões a muito tempo, e precisar reinstalar. Quando fui reinstalar deram vários erros no composer inclusive falando que minha versão de php era 7.2 mesmo no sistema estando configurado como 7.4

**Comment by willph** [comment]
> 
> 
> > > Vou tentar agora meu amigo!
> > > E no que eu puder contribuir com o grupo me coloco a disposição! Eu trabalho produzindo sites, não sou programador, mas trabalho bem com o WordPress, se eu puder ser útil estarei a disposição!
> > 
> > 
> > qual sua versão de php?
> > Aqui esta funcionando, mas minha versão é a 7.4.11
> 
> A minha é a 7.4, mas ocorreu um erro estranho, eu pensei a principio que pudesse ser pelo fato de estar atualizando as versões a muito tempo, e precisar reinstalar. Quando fui reinstalar deram vários erros no composer inclusive falando que minha versão de php era 7.2 mesmo no sistema estando configurado como 7.4

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by willph** [comment]
> 
> 
> > > Vou tentar agora meu amigo!
> > > E no que eu puder contribuir com o grupo me coloco a disposição! Eu trabalho produzindo sites, não sou programador, mas trabalho bem com o WordPress, se eu puder ser útil estarei a disposição!
> > 
> > 
> > qual sua versão de php?
> > Aqui esta funcionando, mas minha versão é a 7.4.11
> 
> A minha é a 7.4, mas ocorreu um erro estranho, eu pensei a principio que pudesse ser pelo fato de estar atualizando as versões a muito tempo, e precisar reinstalar. Quando fui reinstalar deram vários erros no composer inclusive falando que minha versão de php era 7.2 mesmo no sistema estando configurado como 7.4

atualizou banco de dados? 
Instalação do zero?

**Comment by ivigneeporto** [comment]
Atualizei o banco de dados, tentei fazer a instalação do zero, mas não deu certo ai voltei a pasta antiga.

**Comment by willph** [comment]
RESOLVIDO VIA SUPORTE POR WHATSAPP
