### ISSUE TITLE
Não consigo instalar, erro ao dar o comando "composer install --no-dev"

### ISSUE THREAD

**Issue by marcianoknob** [RamonSilva20/mapos#1197]
Ola,
estou com um erro ao executar o comando "composer install --no-dev"

![image](https://user-images.githubusercontent.com/78303121/106384246-8e6b8a00-63a8-11eb-94ab-d72b19572b04.png)

Uso o windows 10

**Comment by Pr3d4dor** [comment]
@marcianoknob Você precisa utilizar o PHP 7.4 pois algumas dependências não permitem ainda o PHP 8

**Comment by marcianoknob** [comment]
Ok, Muito obrigado.
