### ISSUE TITLE
ALGUEM AÍ ME AJUDA SEM RESPOSTAS AINDA?

### ISSUE THREAD

**Issue by tombeira5** [RamonSilva20/mapos#1198]
![106023475-988a4180-60a5-11eb-94a1-64c3b5035b02](https://user-images.githubusercontent.com/78092643/106390449-50319300-63c7-11eb-8c38-178ea0c59c05.png)

**Comment by Pr3d4dor** [comment]
@tombeira5 https://github.com/RamonSilva20/mapos/issues/1190#issuecomment-770090181

**Comment by tombeira5** [comment]
@Pr3d4dor fiz esse processo mais gerou outro erro,estou usando laragon 
![tela](https://user-images.githubusercontent.com/78092643/106392021-f3d27180-63ce-11eb-8c93-77d1cf6aef88.png)

**Comment by Pr3d4dor** [comment]
Está faltando instalar GIT no seu computador

**Comment by tombeira5** [comment]
ufa valeu obrigado valeu @Pr3d4dor
