### ISSUE TITLE
Add + de 1 Usuário/Tecnico em OS

### ISSUE THREAD

**Issue by paulinhowoox** [RamonSilva20/mapos#12]
é possivel adicionar mais de 1 usuário/tecnico na ordem de serviço, eu vi que no model ele tem um limit(5) no autocompleteusuario(), porem não estou conseguindo adicionar mais de um tecnico! Alguém pode me ajudar?

**Comment by phiterf** [comment]
A tabela de OS só permite um usuário, pq o usuário é linkado na tabela em si. 

Pra ter mais de um, ia ter que adicionar uma tabela a mais e apontar a chave estrangeira pra chave primaria dessa tabela. 

Depois ia ter que mexer em algumas coisas no código também. Vai dar um pouco de trabalho

**Comment by paulinhowoox** [comment]
eu vou tentar fazer isso, caso eu consiga eu digo como fiz, e se for do agrado de todos eu faço o commit! Valeu pela explicação @phiterf

**Comment by edgarmeireles** [comment]
Tentei fazer essas alterações, ainda não consegui resultado satisfatório.
Levando em consideração uma Assistência onde uso o campo responsável para informar qual funcionário recebeu o equipamento, depois preciso alterar esse campo para saber com qual dos técnicos o equipamento está.
Por enquanto, estou usando o Status para saber, mas é meio que uma gambiarra...

Perfeito mesmo seria um campo para o responsável e outro para o técnico.

**Comment by P4R4G0N** [comment]
O ideal seria a transferência de um técnico para outro, registrando todas as transferências/técnicos, assim fica tudo documentado- a não ser que você tenha um cenário diferenciado onde permita dois técnicos de fato trabalhando ao mesmo tempo no mesmo chamado.
