### ISSUE TITLE
Erro ao consultar lançamentos após atualizar.

### ISSUE THREAD

**Issue by GLEISONtiago** [RamonSilva20/mapos#1202]
** Descreva o bug **
Eu utilizava a versão 4.24, atualizei para a 4.30, ela limpinha funciona tranquilo, mas quando coloco o meu banco de dados, dá erro ao consultar lançamentos, não queria perder esse BD, já tenho muita informação nele.

REPORTA O SEGUINTE:

        $ this -> db -> from ( $ table );
        $ this -> db -> join ( 'usuarios' , 'usuarios.idUsuarios = usuarios_id' , 'esquerda' );  
        $ this -> db -> order_by ( 'data_vencimento' , 'asc' ); 
        $ this -> db -> limit ( $ perpage , $ start );
        if ( $ where ) {  
            $ this -> db -> where ( $ where );
        }
 
        $ query = $ this -> db -> get ();
 
        $ resultado = ! $ um ? $ consulta -> resultado () : $ consulta -> linha ();  
 
        return $ result ;
    }
 
    public function getTotals ( $ where = '' )  
    {
        $ this -> db -> select ( "
            SUM (caso em que tipo = 'despesa', então valor final) como despesas,
            SUM (caso quando tipo = 'receita' então valor final) como receitas
        " );
        $ this -> db -> from ( 'lancamentos' );
 
        if ( $ where ) {  
            $ this -> db -> where ( $ where );
        }
 
        return ( array ) $ this -> db -> get () -> row (); 
    }

**Comment by willph** [comment]
> ** Descreva o bug **
> Eu utilizava a versão 4.24, atualizei para a 4.30, ela limpinha funciona tranquilo, mas quando coloco o meu banco de dados, dá erro ao consultar lançamentos, não queria perder esse BD, já tenho muita informação nele.
> 
> REPORTA O SEGUINTE:
> 
> ```
>     $ this -> db -> from ( $ table );
>     $ this -> db -> join ( 'usuarios' , 'usuarios.idUsuarios = usuarios_id' , 'esquerda' );  
>     $ this -> db -> order_by ( 'data_vencimento' , 'asc' ); 
>     $ this -> db -> limit ( $ perpage , $ start );
>     if ( $ where ) {  
>         $ this -> db -> where ( $ where );
>     }
> 
>     $ query = $ this -> db -> get ();
> 
>     $ resultado = ! $ um ? $ consulta -> resultado () : $ consulta -> linha ();  
> 
>     return $ result ;
> }
> 
> public function getTotals ( $ where = '' )  
> {
>     $ this -> db -> select ( "
>         SUM (caso em que tipo = 'despesa', então valor final) como despesas,
>         SUM (caso quando tipo = 'receita' então valor final) como receitas
>     " );
>     $ this -> db -> from ( 'lancamentos' );
> 
>     if ( $ where ) {  
>         $ this -> db -> where ( $ where );
>     }
> 
>     return ( array ) $ this -> db -> get () -> row (); 
> }
> ```

Já testou usando o botão atualizar banco de dados que tem em configurações?

**Comment by GLEISONtiago** [comment]
Atualizei o BD em configurações e deu certo!!! Depois de passar a manhã inteira e pedir ajuda eu achei -.-

Obrigado.

**Comment by willph** [comment]
> Atualizei o BD em configurações e deu certo!!! Depois de passar a manhã inteira e pedir ajuda eu achei -.-
> 
> Obrigado.

Verificar se tem a coluna fornecedores, na tabela cliente?
