### ISSUE TITLE
Inserir complemento na tela de cadastro do cliente.

### ISSUE THREAD

**Issue by GLEISONtiago** [RamonSilva20/mapos#1204]
Colocar a opção de inserir um complemento (opcional) para que mora em apartamento, bloco, anexo... na tela de cadastro do cliente.

**Comment by willph** [comment]
> Colocar a opção de inserir um complemento (opcional) para que mora em apartamento, bloco, anexo... na tela de cadastro do cliente.

Já tem, só olhar na aba endereço de adicionar cliente.

**Comment by GLEISONtiago** [comment]
Me refiro à área do cliente, especificamente.

**Comment by willph** [comment]
> Me refiro à área do cliente, especificamente.

Ahhh.

Realmente, no cadastro que fica na área do cliente (MINE) Não tem o campo complemento

**Comment by seitbnao** [comment]
Considerei isso como uma falha nossa, e fiz a alteração já está em uma PR
