### ISSUE TITLE
Travamento na dashboard, agenda desaparece, gráficos sumiram

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1205]
Boa tarde, não sei se está acontecendo só comigo, mas quando insiro qualquer tipo de lançamento, quando volto para a Dashboard, ela apresenta um comportamento atípico. Menu travado,  agenda desaparece, gráficos sumiram. Quando apago o lançamento ele volta ao normal. Estou utilizando a nova versão.
![bugmapos1](https://user-images.githubusercontent.com/77629142/106645665-6c6e3500-656b-11eb-90f3-d22afc999b8f.png)
![bugmapos2](https://user-images.githubusercontent.com/77629142/106645690-742dd980-656b-11eb-8a91-3d377b6b773e.png)

**Comment by willph** [comment]
Pois é. 
Bug já identificado.

Em breve assim que possível será enviada à correção. 

Obrigado.

**Comment by Lucios1989** [comment]
Obrigado você
