### ISSUE TITLE
Area do cliente em cobrança nao aparece Lançamentos dele.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1207]
Pessoal bom dia. 
Fiz uma venda e lancei no financeiro/lançamentos todos os pagamentos que o cliente ira fazer, mas na area de cobrança, nao aparece para ele acompanhar esses lançamentos. Eu nao sei se e bug ou se nao existe mesmo essa ferramenta.

**Comment by cabralwms** [comment]
Entendi, então se eu quiser que ele acompanhe os pagamentos teria que fazer em boleto ou mercado pago. obrigado meu amigo

**Comment by willph** [comment]
> Entendi, então se eu quiser que ele acompanhe os pagamentos teria que fazer em boleto ou mercado pago. obrigado meu amigo

Boleto, tem tanto o Gerencianet ou MercadoPago. 
Aí só escolher. 

Mas sua dúvida ficará como sugestão. 
Não posso lhe da uma data de quando sairá, porque agora demos uma pausa, para focar apenas nos bugs que está aparecendo. 

Atenciosamente, Equipe MAP-Os
