### ISSUE TITLE
Alterar o tamanho da Janela Modal

### ISSUE THREAD

**Issue by hdarantes** [RamonSilva20/mapos#1208]
Estou precisando de uma Janela modal maior que a padrão, utilizei códigos da internet  modal-dialog modal-lg, porém, não altera o tamanho da janela modal do Mapos. 

Como faço para ter uma janela modal maior?

**Comment by Pr3d4dor** [comment]
@hdarantes Já conseguiu resolver?

**Comment by hdarantes** [comment]
Boa tarde ainda não consegui resolver, como faço?
