### ISSUE TITLE
MAPOS

### ISSUE THREAD

**Issue by ruanfelipedacunha** [RamonSilva20/mapos#1209]
Instalei o mapos em localhost, mas cadas vez que faço uma alteração no sistema e aparece uma mensagem, por exemplo: cadastrei um cliente ai salvo e aparece a mensagem de cliente cadastrado, mas quando vou clicar em outro menu sempre aparece a mesma msg, não importa onde clico sempre aparece a msg, oq fazer?

**Comment by willph** [comment]
Poderia postar um print ou video, para entender melhor a falha?

**Comment by ruanfelipedacunha** [comment]
> Poderia postar um print or video, para entender melhor a falha?

quando salvei a alteração do sistema - ![image](https://user-images.githubusercontent.com/78494297/106780011-52ddf380-6626-11eb-973e-b2d76ba42c78.png)

quando entro no menu produtos - ![image](https://user-images.githubusercontent.com/78494297/106780104-6e48fe80-6626-11eb-9466-66ac7f8238b3.png)

cada menu que entro ou cada atualizada na pagina(f5) aparece a mensagem.

**Comment by willph** [comment]
> 
> 
> > Poderia postar um print or video, para entender melhor a falha?
> 
> quando salvei a alteração do sistema - ![image](https://user-images.githubusercontent.com/78494297/106780011-52ddf380-6626-11eb-973e-b2d76ba42c78.png)
> 
> quando entro no menu produtos - ![image](https://user-images.githubusercodontent.com/78494297/106780104-6e48fe80-6626-11eb-9466-66ac7f8238b3.png)
> 
> cada menu que entro ou cada atualizada na pagina(f5) aparece a mensagem.

instalação do zero ou atualização?

Porque aqui esta normal

**Comment by ruanfelipedacunha** [comment]
> > > Poderia postar um print or video, para entender melhor a falha?
> > 
> > 
> > quando salvei a alteração do sistema - ![imagem](https://user-images.githubusercontent.com/78494297/106780011-52ddf380-6626-11eb-973e-b2d76ba42c78.png)
> > quando entro no menu produtos - ![imagem](https://camo.githubusercontent.com/9045c7ae9c59f693685fb4d1e4834b4de2f5741aa8683f10b3974eb540a0a498/68747470733a2f2f757365722d696d616765732e67697468756275736572636f646f6e74656e742e636f6d2f37383439343239372f3130363738303130342d36653438666538302d363632362d313165622d393436362d3636616337663832333862332e706e67)
> > Cada menu que entra ou cada atualizado na página (f5) aparece uma mensagem.
> 
> instalação do zero ou atualização?
> 
> Porque aqui esta normal

do zero

**Comment by willph** [comment]
Versão do php, Windows ou Linux?

Navegador utilizado.

Peço por favor que se possível teste em outros navegadores

Em qua, 3 de fev de 2021 14:20, ruanfelipedacunha <notifications@github.com>
escreveu:

**Comment by ruanfelipedacunha** [comment]
xampp 8.0.1, windows10, no chrome

**Comment by ruanfelipedacunha** [comment]
Acho que no pc mesmo, pq online ele não da esse erro

**Comment by willph** [comment]
> 
> 
> xampp 8.0.1, windows10, no chrome

aconselho a instalar o xampp com php na versão 7.4.
por enquanto não temos 100% compatibilidade com php 8.

**Comment by ruanfelipedacunha** [comment]
> > xampp 8.0.1, windows10, sem cromo
> 
> conselho a instalar o xampp com php na versão 7.4.
> por enquanto não temos 100% de compatibilidade com php 8.

ah ok muito obrigado, na parte venda:
![image](https://user-images.githubusercontent.com/78494297/106787555-9d636e00-662e-11eb-996b-a31231b3b173.png)

quando coloca o cliente e vou em continuar da esse erro

**Comment by willph** [comment]
> 
> 
> > > xampp 8.0.1, windows10, sem cromo
> > 
> > 
> > conselho a instalar o xampp com php na versão 7.4.
> > por enquanto não temos 100% de compatibilidade com php 8.
> 
> ah ok muito obrigado, na parte venda:
> ![image](https://user-images.githubusercontent.com/78494297/106787555-9d636e00-662e-11eb-996b-a31231b3b173.png)
> 
> quando coloca o cliente e vou em continuar da esse erro

testa no firefox por favor, para vê se apresenta os mesmo erros.

**Comment by ruanfelipedacunha** [comment]
> > > > xampp 8.0.1, windows10, sem cromo
> > > 
> > > 
> > > conselho a instalar o xampp com php na versão 7.4.
> > > por enquanto não temos 100% de compatibilidade com php 8.
> > 
> > 
> > ah ok muito obrigado, na parte venda:
> > ![image](https://user-images.githubusercontent.com/78494297/106787555-9d636e00-662e-11eb-996b-a31231b3b173.png)
> > quando coloca o cliente e vou em continuar da esse erro
> 
> testa no firefox por favor, para vê se apresenta os mesmo erros.

no explorer foi sem erro, obg

**Comment by ruanfelipedacunha** [comment]
como faço para alterar esse nome aqui para igreja?

![image](https://user-images.githubusercontent.com/78494297/106795770-457e3480-6639-11eb-98ad-a7b7c3943ec4.png)
