### ISSUE TITLE
Minha tela de login nao sei desta barra azul....servidor local xampp

### ISSUE THREAD

**Issue by jonasbfranco** [RamonSilva20/mapos#121]
![mapos](https://user-images.githubusercontent.com/17801275/39409348-e5f27f48-4bbb-11e8-8e6c-91995ea0b637.PNG)

**Comment by PH7-Jack** [comment]
Eu fiz um implemento e funcionou, bem, é o seguinte, abre o arquivo de login views/mapos/login e procura o botão de enviar, e coloca esse comando dentro da tag do botão onclick="window.location='http://localhost/sua_url/'" e ai ele vai redirecionar apos o login pra o inicio do sistema, pois ele faz login, mas não sai dessa tela, e com esse comando ele redireciona.

**Comment by KokeroO** [comment]
Este problema e referente a extensão Mcrypt do PHP, onde está extensão foi descontinuada apartir do PHP 7. Você deve ter um ambiente conforme os requisitos da aplicação Mapos: PHP >= 5.4.0 < 7.0 e a Extensão Mcrypt ativada.

Uma solução e você fazer a troca da criptografia.

**Comment by PH7-Jack** [comment]
Tenho php 7, e ta habilitado o Mcrypt, mas não funciona do mesmo jeito. Como faz?
E como faço pra adicionar novos menus de cadastros e etc?

**Comment by darouca** [comment]
Olá. 

Veja a resposta que o KokeroO te mandou.
É por ter o 7 que não está cantando. O erro está na sua resposta.

Atenciosamente,


> On 3 May 2018, at 23:55, PH7-Jack <notifications@github.com> wrote:
> 
> Tenho php 7, e ta habilitado o Mcrypt, mas não funciona do mesmo jeito. Como faz?
> E como faço pra adicionar novos menus de cadastros e etc?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
CONFIDENCIAL. SUJEITO A PRIVILÉGIO LEGAL DE COMUNICAÇÃO, PROTEGIDO NOS 
TERMOS DA LEI. Esta mensagem e seus anexos são endereçados exclusivamente 
para seu destinatário e podem conter informações confidenciais ou 
privilegiadas e legalmente protegidas, sujeitas a sigilo profissional.  Se 
você não é o destinatário ou uma pessoa autorizada para recebê-la, você não 
deve usar, copiar, divulgar ou tomar qualquer ação com base nesta mensagem 
ou quaisquer informações nela contidas. Se você recebeu esta mensagem por 
engano, por favor, informe o remetente imediatamente, respondendo o e-mail 
e exclua esta mensagem do seu computador. O conteúdo desta mensagem e seus 
anexos não necessariamente exprimir o parecer ou a intenção da empresa e 
fazer não implica qualquer obrigação legal ou responsabilidades essa 
empresa.

**Comment by PH7-Jack** [comment]
No caso preciso mudar minha versão do PHP ou trocar a criptografia? Como mudo  a criptografia?

**Comment by PH7-Jack** [comment]
Tenho uma pergunta, vão ultilizar o bootstrap 4?

**Comment by daniezlt007** [comment]
Eu executei com a versão do PHP > 7. E funcionou bacana.

**Comment by KFBSolucoes** [comment]
Estou com a ultima configuração do Xamp + PHP, porém não posso alterar pois ja tenho alguns projetos em andamento, como removo a crptografia?
Mesmo mudando no banco de dados a senha não me deixa logar

**Comment by altairdantas** [comment]
estou com o mesmo problema!

![image](https://user-images.githubusercontent.com/50056972/56855123-cca46180-6917-11e9-9bea-a56b94e343c4.png)

**Comment by altairdantas** [comment]
coloquei no Xampp e nada também.

![image](https://user-images.githubusercontent.com/50056972/56855324-aed8fb80-691b-11e9-9bcf-b22c09477e8d.png)

**Comment by altairdantas** [comment]
coloquei no Xampp e nada também.

![Uploading image.png…]()
