### ISSUE TITLE
MAP-OS / LOGO

### ISSUE THREAD

**Issue by ruanfelipedacunha** [RamonSilva20/mapos#1211]
Bom dia pessoal!
Como faço para entrar nesse comando para alterar?
![image](https://user-images.githubusercontent.com/78494297/106904202-a8270d00-66d9-11eb-8122-a6fa476e4591.png)

Fico no aguardo

**Comment by R4T0** [comment]
você precisa mudar isso no php...  Me chama no telegram. @D0GL4S

**Comment by ruanfelipedacunha** [comment]
> você precisa mudar isso no php ... Me chama no telegram. @ D0GL4S

ok

**Comment by marcielgus** [comment]
Basta substituir a imagem no diretório com as mesma característica:
X:\xampp\htdocs\mapos\assets\img\logo.png (onde "X:" é o diretório raiz)

Em propriedade do arquivo tem as dimensões:
![image](https://user-images.githubusercontent.com/78231479/108548367-80839780-72ca-11eb-8f06-c8556fa88eaa.png)
