### ISSUE TITLE
Como mudar o código para não listar as OS faturadas?

### ISSUE THREAD

**Issue by tonnybarros** [RamonSilva20/mapos#1213]
Talvez até um controle no menu sistema para listar as OS com ou sem as OS faturadas.
Digo essa lista
http://95.217.155.200/demo/index.php/os

Alguém aí que já editou pode disponibilizar, talvez uma PR sobre isso.

**Comment by willph** [comment]
A versão mais recente as OS faturada já está oculta.

**Comment by tonnybarros** [comment]
Vdd, desculpa a galera, era um pedido antigo kkkkk
