### ISSUE TITLE
Erro ao mostrar as ordens de serviços do cliente

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#1214]
** Descreva o bug **
Quando faço a pesquisa pelo nome do cliente usando a pesquisa no canto superior direito é mostrado um histórico com todas os serviços feitos para este cliente. Quando vou no menu ORDEM DE SERVIÇO e faço a pesquisa pelo nome do cliente não são mostrados os registros de ordens daquele cliente, o seletor de STATUS DA ORDEM parece não estar funcionando.

Estou usando esta pesquisa para verificar a garantia de um determinado cliente, mais o sistema não está mostrando todos os registros.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'MENU ORDEM DE SERVIÇO'
2. Clique em 'NOME DO CLIENTE A PESQUISAR'
3. Role para baixo até 'NÃO SÃO MOSTRADOS OS REGISTROS, INDEPENDENTE DO STATUS DA ORDEM SELECIONADO'
4. Ver erro

**Comportamento esperado**
Exibir todos os registros de ordens de serviço do cliente com informação sobre a garantia.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [W10]
 - Navegador [EDGE]
 - Versão [88.0.705.56]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@SOROInfo Obrigado por reportar, iremos corrigir assim que possível.
