### ISSUE TITLE
Cobrança GerenciaNet. Alguém mais com esse problema?

### ISSUE THREAD

**Issue by drwdos** [RamonSilva20/mapos#1215]
Uma dúvida. Nós não usava-mos GerenciaNet para cobranças, mas criamos uma conta. 
Mas ao inserir os dados API fica apenas informando na janela (Processando criando cobrança...) e não apresenta nenhum erro e também não cria a cobrança. 
o API do MercadoPago funciona normalmente.

Alguém mais com este problema ou somente eu?

Para o API usei os dados Client_Id_ e Client_Secret_ da aba Desenvolvimento.

**Comment by willph** [comment]
Qual código pegou no Gerencianet?

Produção ou desenvolvimento?

**Comment by drwdos** [comment]
Da aba Desenvolvimento

**Comment by willph** [comment]
> Da aba Desenvolvimento

Todos os dados do cliente foram preenchidas?

**Comment by drwdos** [comment]
Detalhe que não informei, não sei se isso influencia. Uso o sistema em um subdomínio de revenda KingHost. Ultima versão do Mapos. PHP 7.4

**Comment by drwdos** [comment]
Segue print
![image](https://user-images.githubusercontent.com/33677172/107050555-218e3080-67aa-11eb-8771-89be9fcf5023.png)

**Comment by drwdos** [comment]
no caso no cadastro do cliente estão todos preenchidos com os dados corretos para a emissão da cobrança.

**Comment by drwdos** [comment]
Tentei com outros clientes mas fica na mesma. no MercadoPagos gera normalmente as cobranças.

**Comment by willph** [comment]
> Tentei com outros clientes mas fica na mesma. no MercadoPagos gera normalmente as cobranças.

Tem como testar em localhost pra vê se é a hospedagem?

Porque aqui está normal.

**Comment by drwdos** [comment]
Vou testar.

**Comment by willph** [comment]
> Vou testar.

Você testou? Ainda continua com problema?

**Comment by willph** [comment]
Contínuo no aguardo ok?
