### ISSUE TITLE
Atualização de uma versão para outra

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#1216]
Olá, tenho o MAPOS 4.11.2 instalado em servidor online com vários dados de clientes, os e tudo. 
Fiz uma instalação nova com a versão 4.30.1 .
Gostaria de saber se eu fizer o backup do banco de dados da versão 4.11.2 e carregar para a versão 4.30.1 , ela irá funcionar normal ou se preciso fazer alguma coisa antes de atualizar.
Obrigado pela ajuda galera!

**Comment by augustocoletti** [comment]
Boa noite amigo, o ideal é que após restaurar o backup do seu banco, rodar na sequência os updates que acompanham o sistema, na pasta updates.
