### ISSUE TITLE
Integração cobrança Mercado Pago (Como utilizar?)

### ISSUE THREAD

**Issue by hudson-santos** [RamonSilva20/mapos#1218]
Olá.

Estou usando o Mapos desde o começo do ano e atualmente na versão 4.30.2.

Consegui gerar as credenciais do Mercado Pago para geração dos boletos, porém não encontrei local para informar esses dados e nem qual o processo para geração dos boletos após conclusão de uma O.S.

**Comment by willph** [comment]
> 
> 
> Olá.
> 
> Estou usando o Mapos desde o começo do ano e atualmente na versão 4.30.2.
> 
> Consegui gerar as credenciais do Mercado Pago para geração dos boletos, porém não encontrei local para informar esses dados e nem qual o processo para geração dos boletos após conclusão de uma O.S.

fica no caminho` /application/config/payment_gateways.php ` so descer ate chega na api do mercado pago na linha 46 e 47 
```
'access_token' => '',
'public_key' => '',
```

**Comment by R4T0** [comment]
![image](https://user-images.githubusercontent.com/73944522/107574830-7fb17e00-6bc5-11eb-8f6e-185eda9367e0.png)
Não tem a função de Mercado pago ou Gerencia Net

**Comment by willph** [comment]
> ![image](https://user-images.githubusercontent.com/73944522/107574830-7fb17e00-6bc5-11eb-8f6e-185eda9367e0.png)
> Não tem a função de Mercado pago ou Gerencia Net

Fica em visualizarOs o botão.

**Comment by R4T0** [comment]
@willph obrigado, deu certo

**Comment by hudson-santos** [comment]
Consegui fazer todo o processo:
1 - Colocar as credenciais no arquivo **_`/application/config/payment_gateways.php`_**;
2 - Gerar O.S. e Gerar Pagamento para o Mercado Pago;
3 - Boleto foi gerado e enviado para o cliente;
4 - Cliente pagou o boleto e recebi a notificação por e-mail;
5 - Ao clicar em **_`Atualizar Cobrança`_** ocorre erro.

Vou acompanhar as issue #1221 e #1222 pois acredito que seja o mesmo problema.

Ambiente: **_`Produção`_**
Versão: **_`4.31.1`_**
