### ISSUE TITLE
Não exibe inadimplentes no gráfico

### ISSUE THREAD

**Issue by augustocoletti** [RamonSilva20/mapos#1220]
Pessoal,  fiz instalação nova para os vídeos do canal e ao tentar simular uma situação de inadimplência (status negociação) ele não mostra nada nos gráficos de barras do balanço mensal, apenas no gráfico pizza de estatísticas.
Fiz varias simulações, uma delas foi faturamento de OS sem marcar a checkbox de recebido (pois em teoria não foi) e colocando vencimento para dois dias anterior a data atual. Olhei os gráficos e nada, voltei para OS e alterei o Status para "Negociação" e ao olhar os gráficos de barras do balanço mensal, ainda não aparecia.
Usando versão 4.30.2 limpa e adicionando novos dados.
Abraços

**Comment by Pr3d4dor** [comment]
@augustocoletti Obrigado por reportar, iremos corrigir assim que possível.
