### ISSUE TITLE
Como configurar o mercado pago

### ISSUE THREAD

**Issue by ylivebr** [RamonSilva20/mapos#1221]
Olá gostaria de saber como configura o mercado pago, quando vou gerar boleto pelo mercado pago da esse erro:
easy handle already used in multi handle.

**Comment by Gilberto-Artigas** [comment]
Você deve pegar suas credenciais do mercado pago e inserir no código que fica no caminho/application/config/payment_gateways.php so descer ate chega na api do mercado pago na linha 46 e 47

'access_token' => '',
'public_key' => '',

aí é só gerar as cobranças diretamente pelo sistema!

**Comment by ylivebr** [comment]
Deu certo consigo agora gerar os boletos,
eu fiz um teste pra ver se tava ok, agora na hora de canselar a cobrança da um erro
![Sem título](https://user-images.githubusercontent.com/78357882/107362832-0aa45280-6ab8-11eb-8951-2c587709d5df.png)

**Comment by Gilberto-Artigas** [comment]
Pois é, agora você chegou no mesmo bug que eu estou, na [Issue#1222](https://github.com/RamonSilva20/mapos/issues/1222)!

**Comment by ylivebr** [comment]
como resolvo? ou tem que esperar por aluma atualização ?

**Comment by Pr3d4dor** [comment]
@Gilberto-Artigas  e @ylivebr é um bug, tentarei resolver, mas somente no final de semana terei tempo.

**Comment by wesley020291** [comment]
ja saiu alguma solução desse erro?

**Comment by Pr3d4dor** [comment]
@wesley020291 Ainda não saiu correção, ainda não consegui arrumar
