### ISSUE TITLE
Erro ao tentar excluir cobrança

### ISSUE THREAD

**Issue by Gilberto-Artigas** [RamonSilva20/mapos#1222]
Ao tentar excluir qualquer cobrança, o sistema retorna com essa imagem de erro:

![image](https://user-images.githubusercontent.com/78747878/107245503-fd328e00-6a0d-11eb-849a-5e48e57f1782.png)

**Comment by willph** [comment]
> Ao tentar excluir qualquer cobrança, o sistema retorna com essa imagem de erro:
> 
> ![image](https://user-images.githubusercontent.com/78747878/107245503-fd328e00-6a0d-11eb-849a-5e48e57f1782.png)

Feito em ambiente de produção ou desenvolvimento?

**Comment by Gilberto-Artigas** [comment]
produção

**Comment by willph** [comment]
Tem um bug.

No ambiente de teste funciona todos os botões. 

Em produção ele está gerando, mas como você mesmo percebeu não está funcionando o cancelar.

Estamos verificando onde está a falha, pois no ambiente de teste esta ok.
