### ISSUE TITLE
Erro ao atualizar OS dispositivos móveis

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1224]
Boa tarde, está ocorrendo um erro quando tento atualizar uma Os em dispositivos móveis. Fica totalmente desconfigurado.
![maposErro080201](https://user-images.githubusercontent.com/77629142/107272805-fe26e800-6a2c-11eb-893a-594566bbbe52.png)
![maposErro080202](https://user-images.githubusercontent.com/77629142/107272818-05e68c80-6a2d-11eb-82b2-0ff7aed2f44c.png)

**Comment by Pr3d4dor** [comment]
@Lucios1989 Obrigado por reportar, iremos corrigir assim que possível.
