### ISSUE TITLE
vencGarantia

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1225]
estou tentando colocar para que seja impressa na OS a data de vencimento da garantia, mas o máximo que consigo e apenas a quantidade de dias de garantia e quando coloco o codigo dateInterval ou não aparece a informação ou a pag fica toda branca

Esta saindo assim
![Screenshot_48](https://user-images.githubusercontent.com/1253576/107277805-b6578f00-6a33-11eb-95fe-a4e79748289b.png)

ou assim
![Screenshot_49](https://user-images.githubusercontent.com/1253576/107277830-bfe0f700-6a33-11eb-87ff-c0da3f2a2245.png)

mas a ideia e que ele saia assim
![Screenshot_50](https://user-images.githubusercontent.com/1253576/107277966-ee5ed200-6a33-11eb-9cd2-ca7921aef4a6.png)

Mas para sair desse modo oque tenho de fazer e no campo de vencimento da garantia colocar a data direto ao invés apenas da quantidade de dias de garantia

**Comment by Pr3d4dor** [comment]
@hoshikawakun Consegue compartilhar o código que vc fez e que deu errado?

Assim fica mais fácil para lhe ajudar.

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Consegue compartilhar o código que vc fez e que deu errado?
> 
> Assim fica mais fácil para lhe ajudar.

para funcionar e aparecer oque eu fiz foi simples

no PHP referente as OS apenas alterei o tipo de preenchimento do campo para ao invez de vc digitar o numero da quantidade de dias de garantia aparece o calendario e vc simplismente escolhe a data de quando a garantia vai vencer, não alterei nada na DB

alterei o arquivo la das permissoes tmb pra ficar igual os que vc escreve qualker coisa tipo o do Laudo Tecnico

**Comment by Pr3d4dor** [comment]
Certo, mas então você conseguiu então?

Não precisa mais de ajuda?

**Comment by hoshikawakun** [comment]
> 
> 
> Certo, mas então você conseguiu então?
> 
> Não precisa mais de ajuda?

eu consegui dar um jeito para apresentar a informação como eu queria, mas oque seria bom que ao invez de ter que colocar diretamente a data de quando a garantia vai vencer, colocar a quantidade de dias de garantia e a data aparecer

**Comment by willph** [comment]
> > Certo, mas então você conseguiu então?
> > Não precisa mais de ajuda?
> 
> eu consegui dar um jeito para apresentar a informação como eu queria, mas oque seria bom que ao invez de ter que colocar diretamente a data de quando a garantia vai vencer, colocar a quantidade de dias de garantia e a data aparecer

Já é assim
