### ISSUE TITLE
No migrations were found! após atualizar

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1228]
Boa noite, após atualizar está aparecendo esse erro em qualquer lugar que eu clico.
![image](https://user-images.githubusercontent.com/73944522/107454460-753ea800-6b23-11eb-892f-a0083dec1049.png)
Fiz o backup das pastas, verifiquei as permissões... só não consegui atualizar o banco por causa dessa mensagem, tem uma forma de atualizar manual?

**Comment by Pr3d4dor** [comment]
@R4T0 Você pode atualizar manualmente o seu banco olhando na pasta update e executando os .sql das versões após a última versão que você fez o backup.

**Comment by R4T0** [comment]
![image](https://user-images.githubusercontent.com/73944522/107508106-e9ef0200-6b76-11eb-9345-56db1afa558b.png)
@Pr3d4dor  executei esse comando...
![image](https://user-images.githubusercontent.com/73944522/107508167-fd01d200-6b76-11eb-8047-e2edeb8df193.png)
não deu certo ainda

**Comment by R4T0** [comment]
Criei um banco zerado em cima do arquivo /mapos/banco.sql
até aí deu certo, dá pra usar o sistema, porém...
Ao rodar o update database, ou atualizar manualmente como feito no shell, ele retorna o erro  "Migration_Controle_editar_os is missing an up method" .  Meu PHP é o 8.0, todas as extensões a princípio estão ok.

**Comment by Pr3d4dor** [comment]
Você já tem as alterações da versão 4.30.0 então precisa executar, por isso deu o erro de duplicado.

Não recomendo usar o PHP 8 ainda pois algumas dependências do projeto ainda não atualizaram para PHP 8.

**Comment by R4T0** [comment]
![image](https://user-images.githubusercontent.com/73944522/107543769-eae85980-6b9f-11eb-9152-354c04bfdf11.png)
Obrigado @Pr3d4dor o problema realmente era o PHP8.0. Refiz todos os procedimentos iguais, e agora funcionol liso kkkk
já fica a experiência, que com  essa versão do php8, não funciona... Abraços irmão
