### ISSUE TITLE
Hora errada no resgistro quando se add uma anotação na OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1229]
Quando add uma anotação a OS ela fica registrada a hora e dia que a mesma foi Add
o problema esta que a hora esta 3h adiantada

Veja so como esta acontecendo
![Screenshot_52](https://user-images.githubusercontent.com/1253576/107456648-48908d80-6b2f-11eb-9463-fe873fd4e3c9.png)

Como faço para alterar o Fuso Horário?

**Comment by Pr3d4dor** [comment]
Você alterou o fuso horário do seu PHP para America/Fortaleza?

**Comment by hoshikawakun** [comment]
> 
> onde que altero isso?
> Você alterou o fuso horário do seu PHP para America/Fortaleza?

**Comment by hoshikawakun** [comment]
> 
> 
> Você alterou o fuso horário do seu PHP para America/Fortaleza?

onde que altero isso?

**Comment by Pr3d4dor** [comment]
No index.php

**Comment by hoshikawakun** [comment]
> 
> 
> No index.php

Não estou axando

**Comment by Loury-Silva** [comment]
hoshikawakun , basta alterar o php.ini conforme segue:
Procure seu arquivo php.ini:
# find / -name php.ini
Geralmente, fica localizado em /etc/php.ini.
Edite e altere a configuração de timezone:
Encontre a linha date.timezone e deixe como abaixo:
De: ;date.timezone =
Para: date.timezone = America/Sao_Paulo

Se estiver usando o xampp basta editar pelo painel e alterar as linhas referidas acima.
