### ISSUE TITLE
Bug ao Atualizar sistema.

### ISSUE THREAD

**Issue by naodoubuff** [RamonSilva20/mapos#1231]
Ao tentar atualizar o sistema ele apresenta erro.
1º Atualizei o banco de dados, em seguida coloquei para atualizar o sistema.
Apresenta o seguinte erro:
![image](https://user-images.githubusercontent.com/78187809/107606219-31779b80-6c14-11eb-9638-4c3be7e03487.png)

**Comment by Pr3d4dor** [comment]
@naodoubuff O atualizador apresenta alguns problemas com arquivos novos, por isso que o recomendado é realizar a atualização manual.

**Comment by naodoubuff** [comment]
> @naodoubuff O atualizador apresenta alguns problemas com arquivos novos, por isso que o recomendado é realizar a atualização manual.

Poderia me falar o processo manual? Pois tenho muitas informações no banco de dados...

**Comment by Pr3d4dor** [comment]
@naodoubuff Você precisa baixar o novo mapos, realizar a instalação normalmente e depois importar um backup do seu banco de dados antigo ou conectar o novo nele.

Também deve realizar as atualizações dentro da pasta updates no seu banco.
