### ISSUE TITLE
Erro ao Gerar Etiquetas

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1232]
Toda vez que vou gerar etiqueta no formato UPCA tenho esse erro

![Screenshot_53](https://user-images.githubusercontent.com/1253576/107664551-4af80200-6c6b-11eb-95d8-58b3fd7a8a28.png)

**Comment by Pr3d4dor** [comment]
@hoshikawakun O seu código de barras está inválido, confrome a mensagem o dígito verificador não confere.

**Comment by hoshikawakun** [comment]
eu consegui resolver o problema de gerar as etiquetas mas quando tento gerar elas usando a função que gere somente etiqueta dos produtos que tem no estoque tenho esse erro
Isso tanto gerando UPCA como EAN13

![Screenshot_54](https://user-images.githubusercontent.com/1253576/107671666-d9bc4d00-6c72-11eb-9fea-ee7658544edf.png)

**Comment by hoshikawakun** [comment]
QUANDO EU USAVA UMA VERSÃO ANTIGA DO SISTEMA NÃO TINHA ESSE ERRO axo que era a 4.11

**Comment by hoshikawakun** [comment]
Encontrei o problema,
era a quantidade de itens no estoque
oque acabava gerando um numero muito grande de etiquetas
por fim descobri qual e o maximo de etiquetas que o sistema consegue gerar

o sistema consegue gerar no maximo 1744 etiquetas
se a quantidade de itens em estoque dos varios produtos for menor ou igual a 1744 vai gerar normal as etiquetas

se ja tiver 1745 o sistema ja vai reportar o erro

**Comment by hoshikawakun** [comment]
Ja se o Cod. Barra escolhido for UPCA o limite de etiquetas dele e de 1189

Se tiver 1190 ele ja vai dar erro
