### ISSUE TITLE
erro cadastro pix

### ISSUE THREAD

**Issue by microreis** [RamonSilva20/mapos#1235]
![image](https://user-images.githubusercontent.com/23633030/107734011-2cc9ea80-6cdb-11eb-9e95-dd05b8e91940.png)
![image](https://user-images.githubusercontent.com/23633030/107734036-3eab8d80-6cdb-11eb-84c4-80cf992585d5.png)

**Comment by willph** [comment]
Faltou roda o comando composer install.

**Comment by cabralwms** [comment]
Eu fiz a Atualização, rodei o composer, cadastrei a chave pix mas nao identifiquei como gerar o QR cod para pagamento. E a chave ao cadastrar nao aparece no menu configuração/sistema/financeiro.

**Comment by cabralwms** [comment]
Desculpem, vi a atualização no banco, mas através do botão atualizar banco não foi, fiz na mão e então no menu configuração/sistema/financeiro apareceu a chave pix cadastrada, mas ainda não entendi como usar.

**Comment by willph** [comment]
O Qr code aparece por enquanto em imprimir OS. Ao clicar em imprimir OS. O mesmo aparece na folha que será impressa.

**Comment by cabralwms** [comment]
Muito obrigado Willph deu certo aqui

**Comment by robertonfaustino** [comment]
O meu parece que nao salva a chave pix. ja coloquei com o cnpj e com o email e nao fica salvo..

**Comment by cabralwms** [comment]
Robertonfaustino roda o Update do banco de dados mapos4.30.3 para mapos4.31.0

**Comment by robertonfaustino** [comment]
> Robertonfaustino roda o Update do banco de dados mapos4.30.3 para mapos4.31.0

deu certo. obrigado
