### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1238]
Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
Como faço para poder contribuir com o desenvolvimento do Sistema
Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?

Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki

Estou fazendo as alterações sobre a versão 4.31.1

**Comment by willph** [comment]
> 
> 
> Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> Como faço para poder contribuir com o desenvolvimento do Sistema
> Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> 
> Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> 
> Estou fazendo as alterações sobre a versão 4.31.1

poderia postar o print das melhorias, por favor?

**Comment by hoshikawakun** [comment]
> 
> 
> > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > Como faço para poder contribuir com o desenvolvimento do Sistema
> > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > Estou fazendo as alterações sobre a versão 4.31.1
> 
> poderia postar o print das melhorias, por favor?

oque eu fiz foi centralizar algumas infos das tabelas em geral das pag inicial 
![Screenshot_57](https://user-images.githubusercontent.com/1253576/107866839-cddbb100-6e53-11eb-82de-d410b215c8f7.png)


Add mais 2 botões de gerar etiquetas em Produtos
![Screenshot_58](https://user-images.githubusercontent.com/1253576/107866849-fd8ab900-6e53-11eb-92de-61e48e0c06a7.png)

Etiqueta QR Code 
![Screenshot_59](https://user-images.githubusercontent.com/1253576/107866907-3d51a080-6e54-11eb-8941-490b303c276c.png)

ao escanear o código QR sera apresentada informações como Cod do produto "No meu sistema e o numero automático da DB para cada item tipo o numero do Protocolo de OS" Nome do Produto e o Preço do mesmo
VC pode escanear o mesmo para verificar

 Add alguns campos a mais nas OS, e o campo de garantia Até ao clicar abre o calendário
 Add tmb mais alguns botoes de funções no cabeçalho da area Editar OS
![Screenshot_62](https://user-images.githubusercontent.com/1253576/107866981-74748180-6e55-11eb-9df8-cfdfa263b4c9.png)

Ainda em Editar OS o Botão WhatsApp e em forma MODAL (Janela)
que ira apresentar na tela exatamente oque sera enviado na mensagem
alem de mais algumas infos do cliente como link da area do cliente e os dados para o mesmo fazer o LogIn
![Screenshot_63](https://user-images.githubusercontent.com/1253576/107867045-ebaa1580-6e55-11eb-96a5-d12203796f19.png)

A personalização dessa Msg do WhatsApp e feita em uma Aba na parte de Config do Sistema
![Screenshot_64](https://user-images.githubusercontent.com/1253576/107867068-1f853b00-6e56-11eb-9349-5f8b6c227d88.png)


Organizei melhor como e apresentado os Anexos da OS e deixei sem limitação de formato de arquivo que pode ser Anexado
![Screenshot_61](https://user-images.githubusercontent.com/1253576/107866965-22cbf700-6e55-11eb-970e-9fe3cd43e7fa.png)

na parte do Cliente em Cadastro de Novo Cliente Add o campo Senha que o qual gera uma senha automatica de 10 digitos entre Maiusculo, Minusculo e Numeros de forma aleatoria.
E em Email utilizei da mesma função de gerar aleatorio para o email que gera uma sequencia aleatoria de 15 letras minusculas, e o restante do endereço do email vc configura ele na Aba Gerais Das Config do Sistema
![Screenshot_66](https://user-images.githubusercontent.com/1253576/107867228-d635eb00-6e57-11eb-8e8d-f91e4223b39a.png)

em Config do Sistema na Aba Gerais Coloquei um campo de Msg Rápida do WhatsApp
Que consiste em um campo Em branco Editavel o qual vc coloca o numero desejado
O botão Enviar WhatsApp
e um outro campo Somente de Leitura que mostra o numero que esta atrelado a botão do Enviar
Como funciona
Vc Coloca o numero Desejado e clica em Atualizar
após atualizar o numero que vc digitou vai para o campo so de leitura e o campo editavel fica em branco
Se vc clicar em Atualizar Novamente sem escrever nada o primeiro campo ele apaga o numero do segundo campo

![Screenshot_67](https://user-images.githubusercontent.com/1253576/107867373-3a0ce380-6e59-11eb-9c13-87b261ee4147.png)


E varias outras Coisas

**Comment by gabrielcoder01** [comment]
Boa tarde poderia me mandar essas suas modificações se poder...

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde poderia me mandar essas suas modificações se poder...

Estou finalizando mais algumas Mod aki pra finalizar e umpar no meu Github

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde poderia me mandar essas suas modificações se poder...

Algumas delas ja estão listadas no post acima

**Comment by BESystemInfo** [comment]
Excelentes melhorias. Muito bom trabalho. Também estou no aguardo.

**Comment by hoshikawakun** [comment]
Outra Alteração que fiz foi colcar Varios tipos de Status para OS
Sendo cada um de uma cor
Como na foto Abaixo

![Screenshot_71](https://user-images.githubusercontent.com/1253576/107886406-5bfc7980-6ede-11eb-99c0-d85ca761c082.png)
![Screenshot_72](https://user-images.githubusercontent.com/1253576/107886411-5f900080-6ede-11eb-8e75-dfc1dcf89bbc.png)


Na Area do Cliente e apresentada da mesma forma com as mesmas cores

**Comment by hoshikawakun** [comment]
Mais uma Modificação que fiz foi de no Emitente colocar 2 Logo diferentes
Uma Colorida para uso geral
E uma Monocromática para uso nas Impressão Térmica

![Screenshot_76](https://user-images.githubusercontent.com/1253576/108002685-1ff51180-6fcf-11eb-972c-edcce99f33f0.png)

Re-posicionei o QR Code do PIX na impressão das OS
Agora ele fica centrado na impressão e Logo abaixo do valor total dos itens e por mero detalhe acima do QR Code do PIX tem a Logo do PIX
![Screenshot_77](https://user-images.githubusercontent.com/1253576/108002901-c2ad9000-6fcf-11eb-8cb7-f5e092328bdc.png)

**Comment by hoshikawakun** [comment]
E para facilitar a Troca da Logo das telas de LogIn e da Logo que fica dentro do sistema
se pode alterar elas atravez do Gerenciador de arquivos alternativo que ja falei
Logo Tela de LogIn
![Screenshot_78](https://user-images.githubusercontent.com/1253576/108003743-64ce7780-6fd2-11eb-9514-10752e95ccde.png)

Onde as Logos ficam dentro do gerenciador de Arquivos
![Screenshot_79](https://user-images.githubusercontent.com/1253576/108003765-7748b100-6fd2-11eb-86a9-ea07371d5ebb.png)

Deve-se Respeitar Nome, Tamanho e Formato de Arquivo
Logo Pag de LogIn Nome sendo Logo.png Largura Máxima de 400px
Logo que aparece dentro do Sistema Logo2.png Tamanho Maximo 200x55px
![Screenshot_80](https://user-images.githubusercontent.com/1253576/108003863-ce4e8600-6fd2-11eb-8ec1-11a1e19a1129.png)

**Comment by gabrielcoder01** [comment]
Me passa essas atualização por favor!

**Comment by hoshikawakun** [comment]
> 
> 
> Me passa essas atualização por favor!

Falta alterar as pag de impressão de vendas pra finalizar
Obs Alem de Modificações no Sistema tive de fazer algumas alterações na DB

**Comment by gabrielcoder01** [comment]
Não tem problema se poder me mandar desse jeito mesmo já ajuda 😁

**Comment by naodoubuff** [comment]
Opa, amigo me fornece essas atualizações por favor?

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde poderia me mandar essas suas modificações se poder...
https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1

**Comment by hoshikawakun** [comment]
> 
> 
> > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > Como faço para poder contribuir com o desenvolvimento do Sistema
> > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > Estou fazendo as alterações sobre a versão 4.31.1
> 
> poderia postar o print das melhorias, por favor?

Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
se quiser conferir
https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1

**Comment by willph** [comment]
Estamos esperando finalizar 100% a PR para análise.

Obrigado pela contribuições

Em qua, 17 de fev de 2021 06:04, hoshikawakun <notifications@github.com>
escreveu:

**Comment by BESystemInfo** [comment]
> > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > Estou fazendo as alterações sobre a versão 4.31.1
> > 
> > 
> > poderia postar o print das melhorias, por favor?
> 
> Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> se quiser conferir
> https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1

Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?

Mais uma vez parabéns pelas modificações.

**Comment by hoshikawakun** [comment]
> 
> 
> > > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > > Estou fazendo as alterações sobre a versão 4.31.1
> > > 
> > > 
> > > poderia postar o print das melhorias, por favor?
> > 
> > 
> > Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> > se quiser conferir
> > https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1
> 
> Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?
> 
> Mais uma vez parabéns pelas modificações.

CONFERI aki e realmente esta dando erro
devo ter esquecido alguma coisa referente as permissões para cadastrar
pois se ja tiver algo cadastrado ela mostra normal e vc consegue excluir sem problemas
Vou Corrigir isso
Origado por informar

**Comment by hoshikawakun** [comment]
> 
> 
> > > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > > Estou fazendo as alterações sobre a versão 4.31.1
> > > 
> > > 
> > > poderia postar o print das melhorias, por favor?
> > 
> > 
> > Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> > se quiser conferir
> > https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1
> 
> Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?
> 
> Mais uma vez parabéns pelas modificações.

Ja fiz a correção

**Comment by BESystemInfo** [comment]
> > > > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > > > Estou fazendo as alterações sobre a versão 4.31.1
> > > > 
> > > > 
> > > > poderia postar o print das melhorias, por favor?
> > > 
> > > 
> > > Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> > > se quiser conferir
> > > https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1
> > 
> > 
> > Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?
> > Mais uma vez parabéns pelas modificações.
> 
> Ja fiz a correção

Legal. Poderia disponibilizar a correção feita? Ou o caminho para corrigir, se possível? Parabéns novamente, ficaram show as alterações.

**Comment by hoshikawakun** [comment]
> 
> 
> > > > > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > > > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > > > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > > > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > > > > Estou fazendo as alterações sobre a versão 4.31.1
> > > > > 
> > > > > 
> > > > > poderia postar o print das melhorias, por favor?
> > > > 
> > > > 
> > > > Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> > > > se quiser conferir
> > > > https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1
> > > 
> > > 
> > > Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?
> > > Mais uma vez parabéns pelas modificações.
> > 
> > 
> > Ja fiz a correção
> 
> Legal. Poderia disponibilizar a correção feita? Ou o caminho para corrigir, se possível? Parabéns novamente, ficaram show as alterações.

Caminho application/config/
https://github.com/hoshikawakun/MasterOS/blob/master/application/config/form_validation.php

**Comment by naodoubuff** [comment]
> > > > > > > Estou fazendo varias "Melhorias" e algumas correções que axo necessárias no sistema
> > > > > > > Como faço para poder contribuir com o desenvolvimento do Sistema
> > > > > > > Fornecendo essas alterações que estou fazendo e meu nome aparecer ali em Contribuidores?
> > > > > > > Falta fazer apenas algumas alterações na area do Cliente para finalizar tudo aki
> > > > > > > Estou fazendo as alterações sobre a versão 4.31.1
> > > > > > 
> > > > > > 
> > > > > > poderia postar o print das melhorias, por favor?
> > > > > 
> > > > > 
> > > > > Ja finalizei as MOD quase 100% Ficou faltando apenas detalhes na area do cliente
> > > > > se quiser conferir
> > > > > https://github.com/hoshikawakun/MasterOS/releases/tag/10.0.1
> > > > 
> > > > 
> > > > Boa tarde. Adorei as alterações feitas. Meus parabéns pelo excelente trabalho. Um detalhe que notei, após baixar seu projeto para verificar, é que na abertura de OS existe a aba para cadastro de equipamentos, mas quando tentei cadastrar um equipamento para ver, ele dá erro. Essa parte foi finalizada?
> > > > Mais uma vez parabéns pelas modificações.
> > > 
> > > 
> > > Ja fiz a correção
> > 
> > 
> > Legal. Poderia disponibilizar a correção feita? Ou o caminho para corrigir, se possível? Parabéns novamente, ficaram show as alterações.
> 
> Caminho application/config/
> https://github.com/hoshikawakun/MasterOS/blob/master/application/config/form_validation.php
> ou simplismente pode baixar o release https://github.com/hoshikawakun/MasterOS

Amigo, nao to conseguindo instalar, é necessario alguns arquivos do sistema original MapOS, ou a forma de instalação seria somente com esse release que vc forneceu?

**Comment by naodoubuff** [comment]
Se eu instalar usando a pasta updates, e install do mapos original, dá o seguinte erro apos finalizar a  configuração da instalação.
![image](https://user-images.githubusercontent.com/78187809/108663604-b7ff6900-74af-11eb-8e65-2804096fd6b0.png)

**Comment by BESystemInfo** [comment]
> Se eu instalar usando a pasta updates, e install do mapos original, dá o seguinte erro apos finalizar a configuração da instalação.
> ![image](https://user-images.githubusercontent.com/78187809/108663604-b7ff6900-74af-11eb-8e65-2804096fd6b0.png)

Amigo, aqui eu copiei um mapos já configurado e só substitui com os arquivos do projeto Master do colega Hoshikawakun.

**Comment by naodoubuff** [comment]
> > Se eu instalar usando a pasta updates, e install do mapos original, dá o seguinte erro apos finalizar a configuração da instalação.
> > ![image](https://user-images.githubusercontent.com/78187809/108663604-b7ff6900-74af-11eb-8e65-2804096fd6b0.png)
> 
> Amigo, aqui eu copiei um mapos já configurado e só substitui com os arquivos do projeto Master do colega Hoshikawakun.

Fiz a mesma coisa aqui, pediu para reconfigurar, até que prosseguiu para tela de loguin, só que ao logar aparece o seguinte erro
![image](https://user-images.githubusercontent.com/78187809/108665599-0b73b600-74b4-11eb-8ab1-88a62c1c047b.png)

**Comment by hoshikawakun** [comment]
Acabei de subir um .rar da pasta instal que eu uso
ele esta dando erro pois fiz algumas alteração no DB e adequei o instal pra elas

**Comment by hoshikawakun** [comment]
https://github.com/hoshikawakun/MasterOS/blob/master/install.rar

**Comment by naodoubuff** [comment]
> https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
Instalo um MapOS antes? Ou so baixo o seu pack, e adiciono o install?

**Comment by naodoubuff** [comment]
> https://github.com/hoshikawakun/MasterOS/blob/master/install.rar

Tem como tirar obrigatoriedade dos campos no preenchimento do cliente, deixando obrigado somente nome e telefone?. Tem tambem, a opção de bkp? não encontrei por aqui.

**Comment by hoshikawakun** [comment]
> 
> 
> > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > Consegui instalar com o install !!.

To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)

Escureci as bordas dos quadrados dos dias
borda amarela com numero preto e o dia atual
borda vermelha com numero vermelho e o dia que esta selecionado
borda preta com numero vermelho e o dia que esta com o mouse encima

**Comment by naodoubuff** [comment]
> > > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > > Consegui instalar com o install !!.
> 
> To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
> ![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)
> 
> Escureci as bordas dos quadrados dos dias
> borda amarela com numero preto e o dia atual
> borda vermelha com numero vermelho e o dia que esta selecionado
> borda preta com numero vermelho e o dia que esta com o mouse encima

To no aguardo pela nova release !!!!

**Comment by naodoubuff** [comment]
> > > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > > Consegui instalar com o install !!.
> 
> To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
> ![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)
> 
> Escureci as bordas dos quadrados dos dias
> borda amarela com numero preto e o dia atual
> borda vermelha com numero vermelho e o dia que esta selecionado
> borda preta com numero vermelho e o dia que esta com o mouse encima

Fui abrir uma O.S aqui de teste, já veio com a data de abertura e fechamento com o ano de 1969.!

**Comment by hoshikawakun** [comment]
> 
> 
> > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> 
> Tem como tirar obrigatoriedade dos campos no preenchimento do cliente, deixando obrigado somente nome e telefone?. Tem tambem, a opção de bkp? não encontrei por aqui.

tirei ela pois na versão 4.30.3 do MapOS que e a que eu uso de base não estava funcionando
isso vc contorna usando um programa no PC para fazer o beckup da DB
eu uso o Navicat for MySQL

**Comment by hoshikawakun** [comment]
> 
> 
> > > > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > > > Consegui instalar com o install !!.
> > 
> > 
> > To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
> > ![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)
> > Escureci as bordas dos quadrados dos dias
> > borda amarela com numero preto e o dia atual
> > borda vermelha com numero vermelho e o dia que esta selecionado
> > borda preta com numero vermelho e o dia que esta com o mouse encima
> 
> Fui abrir uma O.S aqui de teste, já veio com a data de abertura e fechamento com o ano de 1969.!

aki abre com 1970
mas e so vc digitar a data que ela aparece

**Comment by naodoubuff** [comment]
> > > > > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > > > > Consegui instalar com o install !!.
> > > 
> > > 
> > > To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
> > > ![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)
> > > Escureci as bordas dos quadrados dos dias
> > > borda amarela com numero preto e o dia atual
> > > borda vermelha com numero vermelho e o dia que esta selecionado
> > > borda preta com numero vermelho e o dia que esta com o mouse encima
> > 
> > 
> > Fui abrir uma O.S aqui de teste, já veio com a data de abertura e fechamento com o ano de 1969.!
> 
> aki abre com 1970
> mas e so vc digitar a data que ela aparece

Sistema quebrou, logo após restaurar Banco de Dados do MapOS.

**Comment by hoshikawakun** [comment]
> 
> 
> > > > > > https://github.com/hoshikawakun/MasterOS/blob/master/install.rar
> > > > > > Consegui instalar com o install !!.
> > > > 
> > > > 
> > > > To enrrolando pra lançar uma nova Release do das modificação pois estou criando uns temas com cores diferentes para o sistema e corrigindo alguns bugs que aparecem durante o processo, estou alterando as cores do calendario que aparece ao clicar onde vc vai colocar as datas
> > > > ![Screenshot_85](https://user-images.githubusercontent.com/1253576/108672477-045f9e80-74da-11eb-9e13-ce5e89c17540.png)
> > > > Escureci as bordas dos quadrados dos dias
> > > > borda amarela com numero preto e o dia atual
> > > > borda vermelha com numero vermelho e o dia que esta selecionado
> > > > borda preta com numero vermelho e o dia que esta com o mouse encima
> > > 
> > > 
> > > Fui abrir uma O.S aqui de teste, já veio com a data de abertura e fechamento com o ano de 1969.!
> > 
> > 
> > aki abre com 1970
> > mas e so vc digitar a data que ela aparece
> 
> Sistema quebrou, logo após restaurar Banco de Dados do MapOS.

vc nao consegue restaurar outro banco pois no meu tem colunas e tabelas a mais em relação ao mapos

**Comment by naodoubuff** [comment]
Posso começar a utilizar o seu? As proximas releases nao tem perigo de eu perder o BD?

**Comment by hoshikawakun** [comment]
> 
> 
> Posso começar a utilizar o seu? As proximas releases nao tem perigo de eu perder o BD?

nao

**Comment by naodoubuff** [comment]
No aguardo das releases ! Corrija o install publicamente no seu github para outras pessoas baixarem e utilizarem

**Comment by hoshikawakun** [comment]
essas mod no DB e devido a algumas implementação que fiz tipo equipamento nas OS 
logo normal e logo termica e mais algumas coisas

**Comment by hoshikawakun** [comment]
> 
> 
> Posso começar a utilizar o seu? As proximas releases nao tem perigo de eu perder o BD?

os updates são sempre manuais na minha versão
inclusive não tem opçao de atualisar o sistema nem o DB nas config do sistema

oque quecomendo fazer e sempre antes fazer um beckup da DB
Recomendo utilizar o "Navicat for MySQL" para isso pois e mais garantido

feito isso vc Trunca o DB apagando todas as tabelas

então vc subistitui todos os arquivos e faz uma nova instalação
Se vc renomear o seu Beckup para banco.sql e colocar na raiz da hospedagem ele sera restaurado

**Comment by hoshikawakun** [comment]
isso quando sair uma nova release
se for algum arquivo corrigido so vc baixar individualmente e subistituir na hospedagem

**Comment by naodoubuff** [comment]
> essas mod no DB e devido a algumas implementação que fiz tipo equipamento nas OS
> logo normal e logo termica e mais algumas coisas



> > Posso começar a utilizar o seu? As proximas releases nao tem perigo de eu perder o BD?
> 
> os updates são sempre manuais na minha versão
> inclusive não tem opçao de atualisar o sistema nem o DB nas config do sistema
> 
> oque quecomendo fazer e sempre antes fazer um beckup da DB
> Recomendo utilizar o "Navicat for MySQL" para isso pois e mais garantido
> 
> feito isso vc Trunca o DB apagando todas as tabelas
> 
> então vc subistitui todos os arquivos e faz uma nova instalação
> Se vc renomear o seu Beckup para banco.sql e colocar na raiz da hospedagem ele sera restaurado

Depois que o sistema quebrou nao consigo reinstalar mesmo com a sua pasta install.
Instalo o MapOS, depois extraio seus arquivos, incluindo o install.
Apresenta seguinte erro
![image](https://user-images.githubusercontent.com/78187809/108674514-277f5380-74c4-11eb-9657-90589b3813c0.png)

**Comment by hoshikawakun** [comment]
> 
> 
> > essas mod no DB e devido a algumas implementação que fiz tipo equipamento nas OS
> > logo normal e logo termica e mais algumas coisas
> 
> > > Posso começar a utilizar o seu? As proximas releases nao tem perigo de eu perder o BD?
> > 
> > 
> > os updates são sempre manuais na minha versão
> > inclusive não tem opçao de atualisar o sistema nem o DB nas config do sistema
> > oque quecomendo fazer e sempre antes fazer um beckup da DB
> > Recomendo utilizar o "Navicat for MySQL" para isso pois e mais garantido
> > feito isso vc Trunca o DB apagando todas as tabelas
> > então vc subistitui todos os arquivos e faz uma nova instalação
> > Se vc renomear o seu Beckup para banco.sql e colocar na raiz da hospedagem ele sera restaurado
> 
> Depois que o sistema quebrou nao consigo reinstalar mesmo com a sua pasta install.
> Instalo o MapOS, depois extraio seus arquivos, incluindo o install.
> Apresenta seguinte erro
> ![image](https://user-images.githubusercontent.com/78187809/108674514-277f5380-74c4-11eb-9657-90589b3813c0.png)

subistitua todos os arquivos da hospedagem e apague todas as tabelas da DB, ai vc consegue reinstalar

**Comment by naodoubuff** [comment]
Deu certo, vou te dar algumas sugestões para a proxima release, quer que eu crie uma issue no seu github? Ou pode ser aqui?

**Comment by hoshikawakun** [comment]
> 
> 
> Deu certo, vou te dar algumas sugestões para a proxima release, quer que eu crie uma issue no seu github? Ou pode ser aqui?

por la e mais interessante
cara e olha que não entendo nada de programação nem de desenvolvimento de site
mecho na raça
se não entendo uma sintaxe usada por exemplo "padding" nao sei oque significa os valores na frente, pesquiso na hora pra ver oque cada valor faz e por ai vai

**Comment by hoshikawakun** [comment]
> 
> 
> Deu certo, vou te dar algumas sugestões para a proxima release, quer que eu crie uma issue no seu github? Ou pode ser aqui?

por la e mais interessante
