### ISSUE TITLE
Erro a solicitar impressão de Venda

### ISSUE THREAD

**Issue by DanielAraujo98** [RamonSilva20/mapos#1239]
Após atualizar da versão 4.31.0 para 4.31.1, me deparei com o seguinte erro ao tentar solicitar a impressão de uma venda.
Ressalto que isso acontece apenas com a opção "**Imprimir A4**" em **Vendas**.

![ERRO MAPOS 13-12-21](https://user-images.githubusercontent.com/53981325/107866379-06c55700-6e4f-11eb-8e75-6077ad27551e.PNG)

**Comment by willph** [comment]
> 
> 
> Após atualizar da versão 4.31.0 para 4.31.1, me deparei com o seguinte erro ao tentar solicitar a impressão de uma venda.
> Ressalto que isso acontece apenas com a opção "**Imprimir A4**" em **Vendas**.
> 
> ![ERRO MAPOS 13-12-21](https://user-images.githubusercontent.com/53981325/107866379-06c55700-6e4f-11eb-8e75-6077ad27551e.PNG)

Ja executou o composer update e já atualizou o banco de dados?

**Comment by hoshikawakun** [comment]
> 
> 
> Após atualizar da versão 4.31.0 para 4.31.1, me deparei com o seguinte erro ao tentar solicitar a impressão de uma venda.
> Ressalto que isso acontece apenas com a opção "**Imprimir A4**" em **Vendas**.
> 
> ![ERRO MAPOS 13-12-21](https://user-images.githubusercontent.com/53981325/107866379-06c55700-6e4f-11eb-8e75-6077ad27551e.PNG)

tive esse mesmo erro que foi corrigiudo ao rodar o composer

**Comment by DanielAraujo98** [comment]
![ERRO MAPOS 14-12-21](https://user-images.githubusercontent.com/53981325/107883532-4da66180-6ece-11eb-8cd4-463733feda0b.PNG)
Me deparei com este erro após rodar o comando **composer install --no-dev** pelo SSH

**Comment by Pr3d4dor** [comment]
@DanielAraujo98 Necessário no mínimo PHP 7.3, você está usando PHP 7.2

**Comment by DanielAraujo98** [comment]
Ok! Já tinha mudado a versão do PHP, porém não estava conseguindo executar o comando, pois precisava atualizar o ssh também para a versão do PHP.
Obrigado!
