### ISSUE TITLE
Ajuda com atualização ou instalação do mapos....

### ISSUE THREAD

**Issue by JetLi-Almeida** [RamonSilva20/mapos#1241]
Estava na versão v4.21 ai fui tentar atualizar pelas configurações e deu erro, resolvi fazer manual, fiz como esta na descrição para atualizar manualmente mais agarrou na tela que diz que já tem uma instalação do mapos e não saia dela, então desinstalei o xampp e comecei do inicio, agora não consigo usar o comando do composer e na pré instalação aparece que falta "gd" não sei o que é exatamente..

[https://imgur.com/zqrQoss](url)

[https://imgur.com/H18dATC](url)

**Comment by hoshikawakun** [comment]
VC esta usando Host Online ou Servidor Local?

**Comment by JetLi-Almeida** [comment]
Servidor Local, xampp....

**Comment by robertonfaustino** [comment]
Aproveitando o tópico: 
É possível atualizar da versão 3.14.2 para essa última versão? (4.31.1)

**Comment by robertonfaustino** [comment]
> Estava na versão v4.21 ai fui tentar atualizar pelas configurações e deu erro, resolvi fazer manual, fiz como esta na descrição para atualizar manualmente mais agarrou na tela que diz que já tem uma instalação do mapos e não saia dela, então desinstalei o xampp e comecei do inicio, agora não consigo usar o comando do composer e na pré instalação aparece que falta "gd" não sei o que é exatamente..
> 
> [https://imgur.com/zqrQoss](url)
> 
> [https://imgur.com/H18dATC](url)

Creio que tem que habilitar a extenção no php.ini (extension=gd2)

![image](https://user-images.githubusercontent.com/38968509/108209846-8c742b80-7109-11eb-9b97-ba884364b437.png)

**Comment by Pr3d4dor** [comment]
@robertonfaustino É possível atualizar para a última versão sim.

O mais fácil a se fazer é instalar em outra pasta, fazer backup do banco de dados da versão 3 e importar ele na última versão.

Após isso rodar todas as updates dentro da pasta updates em ordem no banco.

**Comment by JetLi-Almeida** [comment]
> > Estava na versão v4.21 ai fui tentar atualizar pelas configurações e deu erro, resolvi fazer manual, fiz como esta na descrição para atualizar manualmente mais agarrou na tela que diz que já tem uma instalação do mapos e não saia dela, então desinstalei o xampp e comecei do inicio, agora não consigo usar o comando do composer e na pré instalação aparece que falta "gd" não sei o que é exatamente..
> > [https://imgur.com/zqrQoss](url)
> > [https://imgur.com/H18dATC](url)
> 
> Creio que tem que habilitar a extenção no php.ini (extension=gd2)
> 
> ![image](https://user-images.githubusercontent.com/38968509/108209846-8c742b80-7109-11eb-9b97-ba884364b437.png)

![image](https://user-images.githubusercontent.com/79049787/108270551-5d33dd80-714e-11eb-8a68-b5b72af0cba0.png)

**Comment by JetLi-Almeida** [comment]
![image](https://user-images.githubusercontent.com/79049787/108271121-1a263a00-714f-11eb-80bc-99a14d37bc8d.png)

**Comment by Pr3d4dor** [comment]
@JetLi-Almeida Você está usando o PHP 8 que não é compatível ainda com alguns pacotes.

**Comment by JetLi-Almeida** [comment]
> @JetLi-Almeida Você está usando o PHP 8 que não é compatível ainda com alguns pacotes.

PHP seria o Python ? se for já testei outras versões, inclusive a que eu usava antes e o problema continua.

**Comment by Pr3d4dor** [comment]
@JetLi-Almeida Não, PHP é uma linguagem de programação.
