### ISSUE TITLE
QR Code PIX em Impressão Termica

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1242]
Não consigo colocar o QRcode do PIX em impressão termica
na impressão normal ele aparece, se eu alterar o nome do arquivo pro nome do termica ele abre normal so que sem o QRcode

**Comment by hoshikawakun** [comment]
Foi Resolvido add

`$this->data['qrCode'] = $this->os_model->getQrCode(
            $this->uri->segment(3),
            $this->data['configuration']['pix_key'],
            $this->data['emitente'][0]
        );

nas funções `public function imprimirTermica`

**Comment by tibjunior** [comment]
Em que arquivo coloco este código?
