### ISSUE TITLE
onde está o driver do remetente?

### ISSUE THREAD

**Issue by RicRey1988** [RamonSilva20/mapos#1243]
Modifiquei o desenho do mapos com "AdminLTE" ajora mais bonito, mas não consigo encontrar em nenhum lugar o controlador do emitente.php para poder adicionar informações e as notificações que fiz funcionam bem ...

então eu tenho isso em todas as páginas:
https://prnt.sc/zlu2xf

assim é apenas no emissor:
https://prnt.sc/zlu8az

as variáveis ​​que criei já estão no mapos_model e no controlador de cada página em tudo parece bem e funciona, mas só no emissor não achei nada na pasta do controlador ...

**Comment by hoshikawakun** [comment]
> 
> 
> Modifiquei o desenho do mapos com "AdminLTE" ajora mais bonito, mas não consigo encontrar em nenhum lugar o controlador do emitente.php para poder adicionar informações e as notificações que fiz funcionam bem ...
> 
> então eu tenho isso em todas as páginas:
> https://prnt.sc/zlu2xf
> 
> assim é apenas no emissor:
> https://prnt.sc/zlu8az
> 
> as variáveis ​​que criei já estão no mapos_model e no controlador de cada página em tudo parece bem e funciona, mas só no emissor não achei nada na pasta do controlador ...

Posta umas fotos de pag toda dessa sua modificação

**Comment by RicRey1988** [comment]
Aqui coloco uma imagem ...

mas preciso de ajuda com os controladores de emissor, pois tenho que adicionar algumas funções, em todos os demais controladores adicionei as funções e fica bem em todas as páginas exceto o emissor porque não sei onde adiciono as funções para o controlador do emissor.

![Screenshot_140](https://user-images.githubusercontent.com/44790517/108526141-caef1f00-729e-11eb-9019-afe887e45e6f.png)

este é o erro que me mostra no emitente.

![Screenshot_141](https://user-images.githubusercontent.com/44790517/108528796-cd9f4380-72a1-11eb-9906-79a1eef5b6ce.png)

Preciso definir essas variáveis ​​para que o erro não apareça mais .. mas não sei onde: S

**Comment by Pr3d4dor** [comment]
@RicRey1988 Você vai ter que sempre carregar os dados da tabela emitente para exibir eles nessa parte.

**Comment by RicRey1988** [comment]
você pode explicar com mais detalhes ?? Eu realmente não entendo o que você está me dizendo para fazer.
