### ISSUE TITLE
Logo Telas de LogIn

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1244]
Gostaria de configurar para nas telas de LogIn do sistema e do Usuario aparecer a Logo que foi configurada no Emitente,
Como devo proseguir com o codigo para que ele me de essa informação?

Tentei das seguintes formas e nenhuma funcionou

`<img src="<?php echo $emitente[0]->url_logo; ?>" alt="Logo" />`
`<img src="<?php echo $emitente[0]->url_logo; ?> />`
`<?php echo $emitente[0]->url_logo; ?>`

no arquivo login.php

**Comment by robertonfaustino** [comment]
vai dentro da pasta assets, depois na pasta img e la dentro tem o arquivo "logo.png"
só substituir pela imagem que vc quer

**Comment by hoshikawakun** [comment]
> 
> 
> vai dentro da pasta assets, depois na pasta img e la dentro tem o arquivo "logo.png"
> só substituir pela imagem que vc quer

eu sei onde estão os arquivos, eu queria poder alterar os mesmos de dentro do sistema sem tem que ficar indo ate a pasta
