### ISSUE TITLE
Erro no arquivo do Beckup

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1246]
Ao clicar no botão Beckup e gerado um arquivo zip o qual pode ser baixado, mas ao abrir o arquivo sql ao invez de ter o conteudo eu encontro apenas essas infos

SET foreign_key_checks = 0;
SET foreign_key_checks = 1;

**Comment by Pr3d4dor** [comment]
@hoshikawakun Se puder colocar mais logs de erro seria melhor para ajudar.

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Se puder colocar mais logs de erro seria melhor para ajudar.

ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anexos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anexos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anotacoes_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anotacoes_os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`categorias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`categorias`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`ci_sessions`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`ci_sessions`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`clientes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`clientes`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`cobrancas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`cobrancas`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`configuracoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`configuracoes`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`contas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`contas`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`documentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`documentos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`email_queue`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`email_queue`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`emitente`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`emitente`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamento_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamento_os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos_os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`garantias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`garantias`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`itens_de_vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`itens_de_vendas`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`lancamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`lancamentos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`logs`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`logs`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`marcas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`marcas`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`migrations`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`migrations`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`pagamento`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`pagamento`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`permissoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`permissoes`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos_os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos_os`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`usuarios`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`usuarios`
ERROR - 2021-02-17 07:01:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`vendas`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anexos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anexos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anotacoes_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anotacoes_os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`categorias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`categorias`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`ci_sessions`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`ci_sessions`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`clientes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`clientes`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`cobrancas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`cobrancas`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`configuracoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`configuracoes`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`contas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`contas`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`documentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`documentos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`email_queue`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`email_queue`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`emitente`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`emitente`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamento_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamento_os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos_os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`garantias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`garantias`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`itens_de_vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`itens_de_vendas`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`lancamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`lancamentos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`logs`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`logs`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`marcas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`marcas`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`migrations`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`migrations`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`pagamento`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`pagamento`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`permissoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`permissoes`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos_os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos_os`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`usuarios`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`usuarios`
ERROR - 2021-02-17 07:03:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`vendas`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anexos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anexos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anotacoes_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anotacoes_os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`categorias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`categorias`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`ci_sessions`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`ci_sessions`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`clientes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`clientes`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`cobrancas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`cobrancas`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`configuracoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`configuracoes`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`contas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`contas`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`documentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`documentos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`email_queue`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`email_queue`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`emitente`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`emitente`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamento_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamento_os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos_os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`garantias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`garantias`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`itens_de_vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`itens_de_vendas`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`lancamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`lancamentos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`logs`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`logs`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`marcas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`marcas`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`migrations`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`migrations`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`pagamento`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`pagamento`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`permissoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`permissoes`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos_os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos_os`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`usuarios`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`usuarios`
ERROR - 2021-02-17 07:03:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`vendas`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anexos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anexos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`anotacoes_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`anotacoes_os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`categorias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`categorias`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`ci_sessions`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`ci_sessions`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`clientes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`clientes`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`cobrancas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`cobrancas`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`configuracoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`configuracoes`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`contas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`contas`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`documentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`documentos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`email_queue`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`email_queue`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`emitente`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`emitente`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamento_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamento_os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`equipamentos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`equipamentos_os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`garantias`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`garantias`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`itens_de_vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`itens_de_vendas`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`lancamentos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`lancamentos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`logs`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`logs`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`marcas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`marcas`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`migrations`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`migrations`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`pagamento`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`pagamento`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`permissoes`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`permissoes`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`produtos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`produtos_os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`servicos_os`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`servicos_os`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`usuarios`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`usuarios`
ERROR - 2021-02-17 07:04:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`3`.`vendas`' at line 1 - Invalid query: SHOW CREATE TABLE `mapos-4`.`30`.`3`.`vendas`
