### ISSUE TITLE
Erro ao cadastrar pix.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#1247]
Boa tarde,
Fiz o update para a versão 4.31.1 e fiz os updates dentro do BD, porém recebo erro ao cadastrar o pix.

Obs: tentei anexar imagens aqui, mas aparece um erro dizendo que alguma coisa saiu errado e não pode processar o arquivo, então subi no Lightshot.

Atualização BD: https://prnt.sc/zvbksr

Erro do sistema: https://prnt.sc/zvbnwp

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde,
> Fiz o update para a versão 4.31.1 e fiz os updates dentro do BD, porém recebo erro ao cadastrar o pix.
> 
> Obs: tentei anexar imagens aqui, mas aparece um erro dizendo que alguma coisa saiu errado e não pode processar o arquivo, então subi no Lightshot.
> 
> Atualização BD: https://prnt.sc/zvbksr
> 
> Erro do sistema: https://prnt.sc/zvbnwp

vc vai ter de atualizar o composer

**Comment by hoshikawakun** [comment]
composer install --no-dev

**Comment by Triaca** [comment]
> 
> 
> composer install --no-dev

rodei o comando na raiz, porém não tenho as permissões, nem mesmo rodando com SUDO.
Aparentemente a locaweb não libera essas permissões e eu vou ter que pedir a pasta para alguém novamente

**Comment by microreis** [comment]
@Triaca tive o mesmo problema.
1º =  Instale o git

**Comment by hoshikawakun** [comment]
Algo que vc pode fazer e extrair os arquivos em alguma pasta do PC e rodar o composer nela e depois so subir no servidor a pasta vendor

**Comment by Triaca** [comment]
@hoshikawakun @microreis eu instalei o get e rodei o comando por lá, copiei a pasta vendor para o FTP, porém agora acusa o erro de estar faltando arquivos
Erro mapos: https://prnt.sc/zxijyb

Após isso instalei o Xammp e instalei o Composer, baixei o composer.jhar e rolei ele para pegar os packages.
Fiz todo o processo desses tutoriais:

Tutorial 1: [Site do Hostinger](https://www.hostinger.com.br/tutoriais/como-instalar-e-usar-o-composer)
Tutorial 2: [Site do Getcomposer](https://getcomposer.org/download/)

**Comment by hoshikawakun** [comment]
eu na minha maquina uso Win7 com servidor local via WampServer64 3.2.0 instalei o composer e rodei o comando na pasta onde estava o sistema e baixou tudo certinho

**Comment by hoshikawakun** [comment]
e tenho o sistema hospedado na HostGator e nunca tive problema de faltar arquivos
a não ser que tenha dado erro na transferencia do FTP

**Comment by Triaca** [comment]
É... tentei de tudo aqui já.
Essa não é a primeira vez que tenho esse tipo de problema com composer, vou ver se consigo alguém que faça upload da pasta vendor para que eu possa usar

**Comment by naodoubuff** [comment]
Tambem to precisando da pasta vendor atualizada.

**Comment by naodoubuff** [comment]
To com o mesmo erro para cadastrar o pix.

**Comment by JCMF85** [comment]
Boa noite galera!
Encontrei esse video no youtube, eu creio que podem ajudar vocês com a pasta vendor e hostgator,

https://youtu.be/mo7vn4ws03g

**Comment by naodoubuff** [comment]
> Boa noite galera!
> Encontrei esse video no youtube, eu creio que podem ajudar vocês com a pasta vendor e hostgator,
> 
> https://youtu.be/mo7vn4ws03g

Estou usando exatamente essa pasta vendor, sem sucesso..

**Comment by microreis** [comment]
> To com o mesmo erro para cadastrar o pix.

você atualizou o banco de dados?

**Comment by Triaca** [comment]
@microreis utilizei o vídeo e não deu certo, falta arquivos.
o meu BD esta atualizado, sempre fiz o meu composer install --no-dev local e depois subia para o FTP e funcionava perfeitamente, mas nessa ultima atualização não funcionou mais.

**Comment by Pr3d4dor** [comment]
@Triaca no seu local delete o arquivo composer.lock e a pasta application/vendor e rode novamente o comando composer install --no-dev e faça o upload novamente para o FTP.

**Comment by rogowski193** [comment]
Parece ser um erro na biblioteca piggly/php-pix.
Consegui resolver usando o comando "composer require piggly/php-pix" por ssh,
