### ISSUE TITLE
Erro na exibição de ordens de serviço

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#1249]
** Descreva o bug **
Ao acessar o sistema e fazer uma busca por um determinado cliente usando o campo de pesquisa no lado superior direito ao localizar o cliente e clicar em MAIS DETALHES e depois em ORDENS DE SERVIÇO são apresentadas todas as ordens já executadas para aquele cliente, formando assim um histórico dos serviços feitos.

Quando se usa o menu lateral esquerdo ORDENS DE SERVIÇO e é feita uma pesquisa por este mesmo cliente usando o campo NOME DO CLIENTE A PESQUISAR são exibidos apenas alguns registros, sendo que o correto seria exibir todos os registros de Ordem de Serviço feitas para aquele cliente.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'PESQUISA MENU SUPERIOR'
2. Clique em 'PESQUISE POR UM CLIENTE E DEPOIS VEJA AS ORDENS DESSE CLIENTE, SÃO EXIBIDOS TODOS OS REGISTROS'
3. Role para baixo até 'USANDO A PESQUISA DO MENU ORDEM DE SERVIÇO ISSO NÃO ACONTECE'
4. Ver erro

**Comportamento esperado**
Exibir todos os registros referente ao cliente pesquisado.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
![1](https://user-images.githubusercontent.com/25686016/108518354-376e1c00-72a7-11eb-960c-9c70393f84fe.png)
![2](https://user-images.githubusercontent.com/25686016/108518356-389f4900-72a7-11eb-8a4b-33179e9f4aac.png)
![3](https://user-images.githubusercontent.com/25686016/108518358-389f4900-72a7-11eb-9b75-6e07c5d9c078.png)
![4](https://user-images.githubusercontent.com/25686016/108518359-3937df80-72a7-11eb-981d-32103c5f2bfb.png)

** Desktop (preencha as seguintes informações): **
 - SO: [W10]
 - Navegador [EDGE CHROMIUM]
 - Versão [88.0.705.74 (Compilação oficial) (64 bits)]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@SOROInfo Na pesquisa pelo campo pesquisar no canto superior direito, as listagens são sem paginação, por isso aparece todas.

A listagem pelo menu "Ordens de Servço" é paginada, na sua imagem podemos ver que existe mais de página. Já conferiu se nas outras paginas estão o resto das OS daquele cliente?

**Comment by SOROInfo** [comment]
Sim, este é outro problema que acabei me esquecendo de mencionar. Ao usar a
paginação os registros ficam todos embaralhados se misturando com os de
outros clientes.

Em sex, 19 de fev de 2021 13:35, Gianluca Bine <notifications@github.com>
escreveu:
