### ISSUE TITLE
Erro Relatório de OS

### ISSUE THREAD

**Issue by marcielgus** [RamonSilva20/mapos#1251]
Erro Relatório de OS 

Não consigo imprimir o relatório de OS.

Ao tentar gerar qualquer relatório de OS aparece o erro da imagem abaixo:
![image](https://user-images.githubusercontent.com/78231479/108549995-b164cc00-72cc-11eb-9696-9a9542de39e7.png)

**Comment by R4T0** [comment]
chmod -R 777 /var/www/html/mapos
> Está faltando permissão nos seus diretórios. Se usa Windows aplica as permissões necessárias, se usa Linux ta aí em cima.

**Comment by marcielgus** [comment]
> chmod -R 777 / var / www / html / mapos
> 
> > Está faltando permissão nos seus diretórios. Se usa o Windows aplica como requisito, se usa o Linux ta aí em cima.

Dei permissão total nas pastas e no arquivo PHP, mas o erro persiste:
![image](https://user-images.githubusercontent.com/78231479/108559193-cac04500-72d9-11eb-93ae-5137e5eadf80.png)

**Comment by Pr3d4dor** [comment]
@marcielgus Está com o banco de dados atualizado?

**Comment by hoshikawakun** [comment]
em servidor local esta dasndo esse erro
mas se estiver hospedado funciona normal

**Comment by marcielgus** [comment]
> @marcielgus Está com o banco de dados atualizado?

Sim!

**Comment by marcielgus** [comment]
> em servidor local esta dasndo esse erro
> mas se estiver hospedado funciona normal

O meu está hospedado na infinityfree e está dando o erro!
