### ISSUE TITLE
Olá poderiam me ajudar a iniciar o número da OS em outro que não seja 1, por exemplo começar em 1001! qual linha de código devo altera?!

### ISSUE THREAD

**Issue by vitaljr-prog** [RamonSilva20/mapos#1252]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
```
ALTER TABLE os AUTO_INCREMENT = 10000;
```

**Comment by hoshikawakun** [comment]
seria legal na hora da instalação do sistema vc puder escolher em que numero a OS vai Iniciar

**Comment by cleytonasa** [comment]
> ```
> ALTER TABLE os AUTO_INCREMENT = 10000;
> ```

Gostei!

**Comment by vitaljr-prog** [comment]
> 
> 
> ```
> ALTER TABLE os AUTO_INCREMENT = 10000;
> ```

Desculpa  Pr3d4dor , mas qual o nome do arquivo que devo alterar essa instrução?

**Comment by Pr3d4dor** [comment]
Esse comando deve ser executado no seu banco de dados.

**Comment by gabrielcoder01** [comment]
Após rodar esse comando quando você apaga a ordem de serviço ele continua como se ela não estivesse sido apagada exemplo apago a ordem com ID 10 e em vez de a próxima continuar no 10 ela continua no 11 pode ajudar ?

**Comment by Pr3d4dor** [comment]
@gabrielcoder01 Um id num banco de dados nunca é repetido, é assim mesmo que o AUTO_INCREMENT funciona nos bancos de dados. 

Um id primário em uma tabela nunca se repete, mesmo que seja excluído, aquele id nunca mais será usado.
