### ISSUE TITLE
Listagem de OS

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#1254]
Após alguns updates eu percebi que algumas Os não estão aparecendo quando se abre a listagem de OS, no caso as Os com o status Faturado, porem todas as outras ainda aparecem, sendo necessário buscar para encontrar as mesmas. 

Por exemplo eu gero uma fatura, e quando o cliente paga eu normalmente troco o status par finalizado. 

Poderia ser interessante criamos uma função para pré configurar  o que será exibido na lista de OS.

Eu dei uma olhada no código porem não consegui encontrar dentro do controller ou model onde está sendo definido isso.  

**Abrindo as OS diretamente:**
![image](https://user-images.githubusercontent.com/4989569/108624507-1d0d7d00-7424-11eb-9d37-88d6f86138e8.png)

**Após fazer uma busca:**
![image](https://user-images.githubusercontent.com/4989569/108624542-4dedb200-7424-11eb-8a5a-1c859bfd508f.png)

**Comment by hoshikawakun** [comment]
Qual Vers do sistema vc esta usando?

**Comment by bulfaitelo** [comment]
> 
> 
> Qual Vers do sistema vc esta usando?

Olá, eu estou usando a 4.31.1, mas tinha percebido isso a algumas versões passadas.
