### ISSUE TITLE
Tag Notificação Whatsapp Nao funcionando

### ISSUE THREAD

**Issue by mattos123** [RamonSilva20/mapos#1255]
a tag "{DESCRI_PRODUTOS}"
nao está gerando o esperado, 
se espera que ela gere a descrição de produtos usados na ordem de serviço, na notificação pro whatsapp do cliente,
porem a mesma retorna valor em branco.

**Comment by Pr3d4dor** [comment]
@mattos123 Obrigado por reportar, iremos corrigir assim que possível.
