### ISSUE TITLE
Ajuda com restauração de bkp.

### ISSUE THREAD

**Issue by naodoubuff** [RamonSilva20/mapos#1256]
Fiz a atualização do sistema, e antes efetuei o bkp que veio zipado com um SQL. Minha duvida é, não achei no sistema um lugar para selecionar o arquivo, alguem pode me ajudar como inserir esse bkp na versão nova que estou utilizando?

**Comment by hoshikawakun** [comment]
vc esta usando host local no PC ou Servidor Online?

**Comment by naodoubuff** [comment]
> vc esta usando host local no PC ou Servidor Online?

HostGator. Aliás, me ajuda a instalar aquele pack que você gerou com algumas atualizações ficaria grato.

**Comment by hoshikawakun** [comment]
Eu aki uso servidor local para fazer os testes e uso o online pra trabalho mesmo
em ambos uso um programa chamado "Navicat for MySQL"
![Screenshot_82](https://user-images.githubusercontent.com/1253576/108669122-272e8a80-74bb-11eb-8420-826549d15d74.png)
![Screenshot_83](https://user-images.githubusercontent.com/1253576/108669193-4b8a6700-74bb-11eb-96b1-dea86a462109.png)

**Comment by naodoubuff** [comment]
Vou baixar para tentar executar essa sql.
Mudando de assunto.
Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.

**Comment by hoshikawakun** [comment]
> 
> 
> > vc esta usando host local no PC ou Servidor Online?
> 
> HostGator. Aliás, me ajuda a instalar aquele pack que você gerou com algumas atualizações ficaria grato.

eu tmb uso ele

**Comment by hoshikawakun** [comment]
> 
> 
> Vou baixar para tentar executar essa sql.
> Mudando de assunto.
> Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.

vou subir ele aki e jaja ti passo

**Comment by naodoubuff** [comment]
> > Vou baixar para tentar executar essa sql.
> > Mudando de assunto.
> > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> 
> vou subir ele aki e jaja ti passo

Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.

**Comment by hoshikawakun** [comment]
> 
> 
> > > Vou baixar para tentar executar essa sql.
> > > Mudando de assunto.
> > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > 
> > 
> > vou subir ele aki e jaja ti passo
> 
> Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.

ajudo sim

**Comment by hoshikawakun** [comment]
> 
> 
> > Vou baixar para tentar executar essa sql.
> > Mudando de assunto.
> > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> 
> vou subir ele aki e jaja ti passo

https://github.com/hoshikawakun/MasterOS/blob/master/Navicat.on

So trocar o .on por .rar
senha 123

**Comment by hoshikawakun** [comment]
> 
> 
> > > Vou baixar para tentar executar essa sql.
> > > Mudando de assunto.
> > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > 
> > 
> > vou subir ele aki e jaja ti passo
> 
> Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.

que erro esta acontecendo?

**Comment by naodoubuff** [comment]
Abri uma 

> > > > Vou baixar para tentar executar essa sql.
> > > > Mudando de assunto.
> > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > 
> > > 
> > > vou subir ele aki e jaja ti passo
> > 
> > 
> > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> 
> que erro esta acontecendo?

Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.

**Comment by hoshikawakun** [comment]
> 
> 
> > vc esta usando host local no PC ou Servidor Online?
> 
> HostGator. Aliás, me ajuda a instalar aquele pack que você gerou com algumas atualizações ficaria grato.

como vc instalou o composer neles?

**Comment by hoshikawakun** [comment]
> 
> 
> Abri uma
> 
> > > > > Vou baixar para tentar executar essa sql.
> > > > > Mudando de assunto.
> > > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > > 
> > > > 
> > > > vou subir ele aki e jaja ti passo
> > > 
> > > 
> > > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> > 
> > 
> > que erro esta acontecendo?
> 
> Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.

ok

**Comment by naodoubuff** [comment]
> > Abri uma
> > > > > > Vou baixar para tentar executar essa sql.
> > > > > > Mudando de assunto.
> > > > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > > > 
> > > > > 
> > > > > vou subir ele aki e jaja ti passo
> > > > 
> > > > 
> > > > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> > > 
> > > 
> > > que erro esta acontecendo?
> > 
> > 
> > Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.
> 
> ok

Como eu conecto no navicat? Pode me ajudar, sou meio leigo com BD,HOSTS,ETC

**Comment by hoshikawakun** [comment]
> 
> 
> > > Abri uma
> > > > > > > Vou baixar para tentar executar essa sql.
> > > > > > > Mudando de assunto.
> > > > > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > > > > 
> > > > > > 
> > > > > > vou subir ele aki e jaja ti passo
> > > > > 
> > > > > 
> > > > > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> > > > 
> > > > 
> > > > que erro esta acontecendo?
> > > 
> > > 
> > > Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.
> > 
> > 
> > ok
> 
> Como eu conecto no navicat? Pode me ajudar, sou meio leigo com BD,HOSTS,ETC

![Screenshot_84](https://user-images.githubusercontent.com/1253576/108670341-7970ab00-74bd-11eb-91ed-5414b9d0c835.png)

Após instalar e crakear ele vc abre
ao abrir vc clica em Conection
ali dentro vc vai colocar as credenciais

Connection Name um nome qualker pra coneção
Host name vc abre o cPainel e la dentro vc vera o IP da hospedagem esse IP vc coloca ali
Username e Password e os que vc usa na instalação do MapOS

**Comment by naodoubuff** [comment]
> > > > Abri uma
> > > > > > > > Vou baixar para tentar executar essa sql.
> > > > > > > > Mudando de assunto.
> > > > > > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > > > > > 
> > > > > > > 
> > > > > > > vou subir ele aki e jaja ti passo
> > > > > > 
> > > > > > 
> > > > > > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> > > > > 
> > > > > 
> > > > > que erro esta acontecendo?
> > > > 
> > > > 
> > > > Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.
> > > 
> > > 
> > > ok
> > 
> > 
> > Como eu conecto no navicat? Pode me ajudar, sou meio leigo com BD,HOSTS,ETC
> 
> ![Screenshot_84](https://user-images.githubusercontent.com/1253576/108670341-7970ab00-74bd-11eb-91ed-5414b9d0c835.png)
> 
> Após instalar e crakear ele vc abre
> ao abrir vc clica em Conection
> ali dentro vc vai colocar as credenciais
> 
> Connection Name um nome qualker pra coneção
> Host name vc abre o cPainel e la dentro vc vera o IP da hospedagem esse IP vc coloca ali
> Username e Password e os que vc usa na instalação do MapOS

![image](https://user-images.githubusercontent.com/78187809/108671908-f43ac580-74bf-11eb-9334-77722bcb9b5d.png)
Só da esse erro, e o usuario e senha estão corretos. ip tbm

**Comment by hoshikawakun** [comment]
> 
> 
> > > > > Abri uma
> > > > > > > > > Vou baixar para tentar executar essa sql.
> > > > > > > > > Mudando de assunto.
> > > > > > > > > Agora que vi no seu perfil, vc mora em ceres? Morei ai até o começo de janeiro kk.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > vou subir ele aki e jaja ti passo
> > > > > > > 
> > > > > > > 
> > > > > > > Me ajuda a instalar o MasterOS mano, sempre dps que configuro a page da erro.
> > > > > > 
> > > > > > 
> > > > > > que erro esta acontecendo?
> > > > > 
> > > > > 
> > > > > Eu respondi la no seu topico, onde você postou as melhorias. vamos falar por lá.
> > > > 
> > > > 
> > > > ok
> > > 
> > > 
> > > Como eu conecto no navicat? Pode me ajudar, sou meio leigo com BD,HOSTS,ETC
> > 
> > 
> > ![Screenshot_84](https://user-images.githubusercontent.com/1253576/108670341-7970ab00-74bd-11eb-91ed-5414b9d0c835.png)
> > Após instalar e crakear ele vc abre
> > ao abrir vc clica em Conection
> > ali dentro vc vai colocar as credenciais
> > Connection Name um nome qualker pra coneção
> > Host name vc abre o cPainel e la dentro vc vera o IP da hospedagem esse IP vc coloca ali
> > Username e Password e os que vc usa na instalação do MapOS
> 
> ![image](https://user-images.githubusercontent.com/78187809/108671908-f43ac580-74bf-11eb-9334-77722bcb9b5d.png)
> Só da esse erro, e o usuario e senha estão corretos. ip tbm

podemostrar como esta colocando os dados?

**Comment by hoshikawakun** [comment]
tenta usar o username e senha que vc usa para acessar o cpainel

**Comment by naodoubuff** [comment]
> tenta usar o username e senha que vc usa para acessar o cpainel

nao funcionou tambem

**Comment by hoshikawakun** [comment]
os updates são sempre manuais na minha versão
inclusive não tem opçao de atualisar o sistema nem o DB nas config do sistema

**Comment by hoshikawakun** [comment]
oque quecomendo fazer e sempre antes fazer um beckup da DB
Recomendo utilizar o "Navicat for MySQL" para isso pois e mais garantido

feito isso vc Trunca o DB apagando todas as tabelas

então vc subistitui todos os arquivos e faz uma nova instalação
Se vc renomear o seu Beckup para banco.sql e colocar na raiz da hospedagem ele sera restaurado
