### ISSUE TITLE
BUG RELATORIOS

### ISSUE THREAD

**Issue by SaghaZ** [RamonSilva20/mapos#1257]
boa tarde, entrei um bug entre relatórios onde queria compartilhar

vamos la, seguindo p processo:

efetuo uma venda para o cliente x
produto "hd seagate" preço 10 reais, quantidade 1

faturo o pedido.

vou editar essa venda, pois errei o valor, excluo o produto da venda, adiciono novamente,
produto "hd seagate" preço 100 reais, quantidade 1
clico em "atualizar"

no relatorio "sku" a venda do produto esta, 100 reais como e o correto, (em excel)
no relatorio "vendas" a venda ainda esta 10 reais...

minha solicitar seria para que encarecidamente, fosse corrigido isso, agradeço imensamente,

Atenciosamente,

RELATORIO DE SKU (CERTINHO)

![SKU](https://user-images.githubusercontent.com/66077575/108731132-03933080-750b-11eb-9efb-7abd41a60a3b.png)

RELATORIO DE VENDAS (NAO ATUALIZA)

![VENDAS](https://user-images.githubusercontent.com/66077575/108731206-186fc400-750b-11eb-953b-476e0630e7c2.png)

**Comment by hoshikawakun** [comment]
axo que isso e devido a vc ter faturado errado a venda com valor errado
se vc faturar uma venda de 10,00
depois colocar 500,00 em produtos nessa venda no relatorio vai continuar constando 10,00, o que se deve fazer nesse caso em vez de alterar o produto dentro de uma venda, vc exclui a venda (axo que ai os valores e estoque referentes são resetados)
e faz outra venda com os valores corretos
