### ISSUE TITLE
BUG VENDAS

### ISSUE THREAD

**Issue by SaghaZ** [RamonSilva20/mapos#1258]
Boa tarde,

encarecidamente, queria pedir uma ajuda referente a algo que tem acontecido comigo,
faço bastante vendas via mapos, e algumas vendas minhas estao duplicando por algum motivo....

apenas consigo diferenciar, pelo codigo de lançamento, abaixo o print...

solicito ajuda, pois isso tem me atrapalhando bastante, desde ja, muito obrigado !

![vendas2](https://user-images.githubusercontent.com/66077575/108731820-b499cb00-750b-11eb-97bd-28dafcd4e557.png)

**Comment by Pr3d4dor** [comment]
@SaghaZ Obrigado por reportar, iremos corrigir assim que possível.
