### ISSUE TITLE
Erro de data

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1259]
não sei o motivo mas qualker coisa referente a data QUE VC VA DAR UMA ENTRADA NO sistema seja uma anotação em uma OS ou os relatorios da auditoria do sistema esta caindo como +3 em relação ao relogio do PC onde esta o host

Horario baseado em 24h

Se são por exemplo 13:30 do dia 22/02/2021
ao dar uma entrada no sistema esta caindo como 16:30 do dia 22/02/2021

**Comment by Pr3d4dor** [comment]
@hoshikawakun Se seu banco estiver com as datas no formato UTC que é +00:00, está certo, porque a timezone do Brasil é -03:00.

Então 16:00 em UTC são 13:00 no Brasil.
