### ISSUE TITLE
Configuração de envio de e-mail automático para o cliente.

### ISSUE THREAD

**Issue by gilbertoalmeida16** [RamonSilva20/mapos#1261]
https://www.youtube.com/watch?v=2NH3nLFMfz8

Esse vídeo é de nossa autoria em nossa canal para ajudar o pessoal aqui no mapos4, a configurar o e-mail automático assim que abre um novo orçamento, ou os entre outros.

**Comment by maycon1977** [comment]
Show de bola...

Seria possível fazer um vídeo com uma instalação limpa do MAPOS com os passos todos corretos? Iria ajudar muita gente!

Valeu!

**Comment by maycon1977** [comment]
> Show de bola...
> 
> Seria possível fazer um vídeo com uma instalação limpa do MAPOS com os passos todos corretos? Iria ajudar muita gente!
> 
> Valeu!

Opa...

Achei aqui no seu canal..

https://www.youtube.com/watch?v=mo7vn4ws03g

Os procedimentos continuam iguais a esses?

**Comment by wesley020291** [comment]
> https://www.youtube.com/watch?v=2NH3nLFMfz8
> 
> Esse vídeo é de nossa autoria em nossa canal para ajudar o pessoal aqui no mapos4, a configurar o e-mail automático assim que abre um novo orçamento, ou os entre outros.

se poder faz um de como configura o mercado pago e o gerencianet :)

**Comment by andrehoffmann1** [comment]
Bom dia pessoal!
Gilberto, estou com dificuldades no envio automático para o cliente.
Já visualizei seu tuto no youtube, porem nada de solução.
Minha hospedagem é na hostinger.

Segue uma parte do log:
ERROR - 2021-02-26 14:11:03 --> 220 ESMTP smtp.hostinger.com
<br /><pre>hello: 250-nl-srv-smtpout1.hostinger.io
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-nl-srv-smtpout1.hostinger.io
</pre><pre>from: 250 2.1.0 Ok
</pre><pre>to: 553 5.7.1 <andre_guilherme@msn.com>: Sender address rejected: not owned by user teste@andrehoffmann.website
</pre>The following SMTP error was encountered: 553 5.7.1 <andre_guilherme@msn.com>: Sender address rejected: not owned by user teste@andrehoffmann.website
<br /><pre>quit: 221 2.0.0 Bye
</pre>Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br /><pre>From: andre_guilherme@msn.com
Subject: Ordem de Serviço - Criada
To: andguihofros@gmail.com

Acontece que o serviço de SMTP está ativo.

Poderia me ajudar?
