### ISSUE TITLE
Onde esta o diretorio da area do cliente 

### ISSUE THREAD

**Issue by gabrielcoder01** [RamonSilva20/mapos#1262]
onde esta o diretorio da area do cliente mine

**Comment by hoshikawakun** [comment]
> 
> 
> onde esta o diretorio da area do cliente mine

application>>views>>conecte

**Comment by marcielgus** [comment]
> onde esta o diretorio da area do cliente mina

http://seudominio/index.php/mine
ou
http://localhost/mapos/index.php/mine

**Comment by gabrielcoder01** [comment]
Onde está o arquivo de notificação do WhatsApp???
