### ISSUE TITLE
Data de Nascimento do Cliente

### ISSUE THREAD

**Issue by wslucasleite** [RamonSilva20/mapos#1263]
Estou precisando incluir o campo de Data de Nascimento do cliente.

Já fiz essas mudanças:
- Criei 1 tabela no banco de clientes, `dataNasc`;
- Na tela de cadastro, editar e visualizar o cliente já contém o campo;
- Editar e Visualizar os dados do cliente já consegui colocar a máscara;

O problema seria encontrar onde o botão pega as informações preenchidas e salvar no banco, e também colocar essa máscara na hora de cadastrar um novo cliente.

Se alguém puder dar uma moral pra conseguir incluir isso, agradeço demais!

**Comment by hoshikawakun** [comment]
> 
> 
> Estou precisando incluir o campo de Data de Nascimento do cliente.
> 
> Já fiz essas mudanças:
> 
>     * Criei 1 tabela no banco de clientes, `dataNasc`;
> 
>     * Na tela de cadastro, editar e visualizar o cliente já contém o campo;
> 
>     * Editar e Visualizar os dados do cliente já consegui colocar a máscara;
> 
> 
> O problema seria encontrar onde o botão pega as informações preenchidas e salvar no banco, e também colocar essa máscara na hora de cadastrar um novo cliente.
> 
> Se alguém puder dar uma moral pra conseguir incluir isso, agradeço demais!

Fazer isso e bem simples olhe um dado que e escrito na tabela na hora de cadastrar
peque esse aki que sera mais facil "nomeCliente"
se ja Add a coluna referente a data de nascimento na DB e tranquilo agora

Procure em todos os PHP por essa informação que no caso esta sendo "nomeCliente"
Toda ela que vc encontrar vc duplica e muda para o nome que deseja usar
depois e so acrescentar os campos para vc editar e cadastrar e visualizar

E assim que costumo fazer
E utilizo o Adobe Dreamweaver para fazer as edição

**Comment by microreis** [comment]
![image](https://user-images.githubusercontent.com/23633030/108789883-0b2df600-755a-11eb-81f4-bc0f7b722f0e.png)

**Comment by wslucasleite** [comment]
Vlw man, vou tentar fazer isso aqui, acabei fechando o ticket sem querer, ainda não to acostumado com GitHub hehe'

Mas tipo, peguei o adicionarCliente.php

<div class="control-group">
                            <label for="nomeCliente" class="control-label">Nome/Razão Social<span class="required">*</span></label>
                            <div class="controls">
                                <input id="nomeCliente" type="text" name="nomeCliente"
                                       value="<?php echo set_value('nomeCliente'); ?>"/>
                            </div>
                        </div>
						
						<div class="control-group">
                            <label for="dataNasc" class="control-label">Data de Nascimento<span class="required">*</span></label>
                            <div class="controls">
                                <input id="dataNasc" type="text" name="dataNasc"
                                       value="<?php echo date('d/m/Y'); ?>"/>
                            </div>
                        </div>

Deixei dessa maneira e não salvou no banco

**Comment by wslucasleite** [comment]
https://github.com/RamonSilva20/mapos/issues/1263#issuecomment-783792738
Fiz isso e não deu certo

**Comment by hoshikawakun** [comment]
Simplismente duplique tudo referente a "nomeCliente" e altere para "dataNasc"
na DB vc usa para a coluna o tipo Varchar 45
somente nos PHP que esta os campos onde vc faz o preenchimento vc coloca a seguinte info
em class que deve estar como 
class="span12"
Coloque
class="span12 datepicker"
que ele ja vai chamar o calendario quando vc clicar no casmpo

**Comment by wslucasleite** [comment]
Cara, fazendo teste pra poder cadastrar no cliente novo, fiz a alteração no: 
application\views\clientes\adicionarClientes.php

//CODIGO ORIGINAL PRA INSERIR NOME
<div class="control-group">
	<label for="nomeCliente" class="control-label">Nome/Razão Social<span class="required">*</span></label>
	<div class="controls">
		<input id="nomeCliente" type="text" name="nomeCliente"
		value="<?php echo set_value('nomeCliente'); ?>"/>
	</div>
</div>


//COPIANDO CODIGO PARA INSERIR DATA DE NASCIMENTO
<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>

Não deu certo, o campo não teve a formatação pra data...

Coloquei a class = "span12 datepicker" também não deu certo, como no código abaixo...
<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento" class = "span12 datepicker"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>


Em application\controllers\Clientes.php copiei a linha da dataCadastro, e inseri o dataNascimento

Também não deu certo...

E pra desencargo, fui no application\views\os\adicionarOs.php onde contém o campo de data das OS, copiei o código fui testando e também não vai...

Já dentro do banco fica gravando a data atual, copiando a data de cadastro.

**Comment by wslucasleite** [comment]
Cara, fazendo teste pra poder cadastrar no cliente novo, fiz a alteração no: 
application\views\clientes\adicionarClientes.php

//CODIGO ORIGINAL PRA INSERIR NOME
`<div class="control-group">
	<label for="nomeCliente" class="control-label">Nome/Razão Social<span class="required">*</span></label>
	<div class="controls">
		<input id="nomeCliente" type="text" name="nomeCliente"
		value="<?php echo set_value('nomeCliente'); ?>"/>
	</div>
</div>`


//COPIANDO CODIGO PARA INSERIR DATA DE NASCIMENTO
`<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>`

Não deu certo, o campo não teve a formatação pra data...

Coloquei a class = "span12 datepicker" também não deu certo, como no código abaixo...
```
`<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento" class = "span12 datepicker"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>`
```


Em application\controllers\Clientes.php copiei a linha da dataCadastro, e inseri o dataNascimento

Também não deu certo...

E pra desencargo, fui no application\views\os\adicionarOs.php onde contém o campo de data das OS, copiei o código fui testando e também não vai...

Já dentro do banco fica gravando a data atual, copiando a data de cadastro.

**Comment by wslucasleite** [comment]
Cara, fazendo teste pra poder cadastrar no cliente novo, fiz a alteração no: 
application\views\clientes\adicionarClientes.php

//CODIGO ORIGINAL PRA INSERIR NOME
```
<div class="control-group">
	<label for="nomeCliente" class="control-label">Nome/Razão Social<span class="required">*</span></label>
	<div class="controls">
		<input id="nomeCliente" type="text" name="nomeCliente"
		value="<?php echo set_value('nomeCliente'); ?>"/>
	</div>
</div>
```


//COPIANDO CODIGO PARA INSERIR DATA DE NASCIMENTO
```
<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>
```

Não deu certo, o campo não teve a formatação pra data...

Coloquei a class = "span12 datepicker" também não deu certo, como no código abaixo...
```
<div class="control-group">
	<label for="dataNascimento" class="control-label">Data de Nascimento<span class="required">*</span></label>
	<div class="controls">
		<input id="dataNascimento" type="text" name="dataNascimento" class = "span12 datepicker"
		value="<?php echo set_value('dataNascimento') ?>"/>
	</div>
</div>
```


Em application\controllers\Clientes.php copiei a linha da dataCadastro, e inseri o dataNascimento

Também não deu certo...

E pra desencargo, fui no application\views\os\adicionarOs.php onde contém o campo de data das OS, copiei o código fui testando e também não vai...

Já dentro do banco fica gravando a data atual, copiando a data de cadastro.

**Comment by microreis** [comment]
@wslucasleite segue o seguinte passo a passo
Para o painel administrador você vai colocar assim
1ª Banco de dados (tabela clientes)
Adicione o campo `dataNasc date DEFAULT NULL,`
![image](https://user-images.githubusercontent.com/23633030/108837099-891cec00-75b0-11eb-91bc-c8e27b8826c7.png)

**Alterações no script no adminstrador**
- 1 **_Todas as views_**
- 2 **_Colocando mascara nos campos_**
- 3 **_Editando o Controllers_**

1. **_views_** 

 Adicione em:  _views/clientes/adicionarClientes.php_
```
<div class="control-group" class="control-label">
     <label for="dataNasc" class="control-label">Data Nascimeto</label>
            <div class="controls datepicker">
                  <input id="dataNasc" type="text" name="dataNasc" value="<?php echo set_value('dataNasc'); ?>"/>
            </div>
</div>
```
Adicione em:  _views/clientes/editarClientes.php_
```
<div class="control-group" class="control-label">
        <label for="dataNasc" class="control-label">Data Nascimeto</label>
               <div class="controls datepicker">
                       <input id="dataNasc" type="text" name="dataNasc" value="<?php echo date('d/m/Y', strtotime($result->dataNasc)); ?>"/>
              </div>
</div>
```
Adicione em:  _views/clientes/visualizar.php_
```
 <tr>
         <td style="text-align: right"><strong>Data de Nascimento</strong></td>
           <td>
                   <?php echo date('d/m/Y', strtotime($result->dataNasc)) ?>
           </td>
</tr>
```
2. **_Mask_** 

Adicionar em: _assets/js/funcoes.js_ na linha 3
`$("#dataNasc").mask("00/00/0000")`

3. **_Controllers_** 

Adicionar em: _controllers/clientes.php_

> public function adicionar()
`'dataNasc' => date('Y-m-d', strtotime(set_value('dataNasc'))),`

![image](https://user-images.githubusercontent.com/23633030/108839518-eebea780-75b3-11eb-8e1d-f46570b28ccd.png)

>  public function editar()
`'dataNasc' => date('Y-m-d', strtotime($this->input->post('dataNasc'))),`

![image](https://user-images.githubusercontent.com/23633030/108839326-b4eda100-75b3-11eb-9aac-75ec4d62818a.png)

**Comment by wslucasleite** [comment]
Fiz e não deu certo, configurei da maneira que mandou, quando vou no campo pra preencher a data, não abre o calendário e também não coloca máscara... E ao tentar salvar ocorre um erro.

![image](https://user-images.githubusercontent.com/31487116/108872139-a2399300-75d8-11eb-923b-a8aea61a30ce.png)

**Comment by wslucasleite** [comment]
@microreis, fiz essa alteração aqui mudando o type = "text" para type = "date"

```
<div class="control-group" class="control-label">
     <label for="dataNasc" class="control-label">Data Nascimeto</label>
            <div class="controls datepicker">
                  <input id="dataNasc" type="date" name="dataNasc" value="<?php echo set_value('dataNasc'); ?>"/>
            </div>
</div>
```

**Comment by microreis** [comment]
@wslucasleite qualquer duvida entra no meu perfil e mim chama.

**Comment by microreis** [comment]
> @microreis no caso eu não terei tela pra cliente.
> 
> Como falei ai em cima, colocando o type do campo como "date" está gravando, tudo certo.
> Mas quando eu vou editar as informações do cliente, se eu deixo o type do campo também como "date" a página carrega com a data de nascimento vazio, se eu atualizar sem preencher ele muda pra 31/12/1969, ou se eu troco de data ele salva a nova data.
> Agora se eu deixo o type do campo como "text", ele me retorna o que tá salvo no banco com a data de nascimento correto, mas quando atualizo os dados do cliente ele muda pra 31/1/1969 também.

isso acontece porque ele pega a data padrão inicial, na minha opinião não gosto do `type=date` por este motivo.
é estranho não ter funcionado o passo a passo, pois fiz e te mandei e esta tudo funcionando.

**Comment by wslucasleite** [comment]
@microreis também não entendi porque não funciona, pra não ter problema ainda, peguei o projeto do zero, fiz a intatalação toda nova pra não ter problema de ter mexido em algum arquivo que influenciasse pra não funcionar, e mesmo assim não deu certo.

**Comment by microreis** [comment]
@wslucasleite mim chama que vemos o que pode ter ocorrido.

**Comment by wslucasleite** [comment]
@microreis por onde? hehe, tô perdido com esse github

**Comment by microreis** [comment]
clique @microreis vai aparecer meu

**Comment by wslucasleite** [comment]
@microreis entrei na usa página, mas não encontrei nada pra poder mandar msg pra vc ou alguma coisa do tipo

**Comment by microreis** [comment]
> @microreis entrei na sua página, mas não encontrei nada pra poder mandar msg pra vc ou alguma coisa do tipo

![image](https://user-images.githubusercontent.com/23633030/108888111-d1a4cb80-75e9-11eb-9080-5804579fcfb8.png)

**Comment by wslucasleite** [comment]
Achei que existia alguma ferramenta aqui dentro do github pra conversar com os usuários.
