### ISSUE TITLE
Envio de Email ao ser cadastrado cliente novo via web sistema.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1266]
Boa Tarde pessoal tudo bem.?
Gostaria de verificar se o sistema MAPOS, quando o cliente entra no link que tenho no meu site, direciono para o cadastro no sistema. O Cliente faz o cadastro e então seria legal um email avisando o email do administrador que foi cadastrado cliente novo. Isso já existe? ou só quando é gerado uma ordem de serviço? Pelo Campo cliente

**Comment by Pr3d4dor** [comment]
@cabralwms No momento não existe essa funcionalidade no mapos. Os únicos emails que são enviados são os de OS.
