### ISSUE TITLE
Criar tipo de equipamentos, e termo de ordem de serviço.

### ISSUE THREAD

**Issue by naodoubuff** [RamonSilva20/mapos#1269]
Estou utilizando o sistema e por enquanto tem me atendido, porém estou com um problema. As vezes pego celulares, notebooks etc.
Gostaria de saber se é possivel criar um campo especificando o tipo de equipamento e marca.
Tambem gostaria de incluir um termo para o cliente assinar na abertura da ordem de serviço.
Alguem pode me ajudar com isso?

**Comment by Pr3d4dor** [comment]
@naodoubuff Obrigado pela sugestão.
