### ISSUE TITLE
Onde está o arquivo de notificação do WhatsApp???

### ISSUE THREAD

**Issue by gabrielcoder01** [RamonSilva20/mapos#1270]
Onde está o arquivo de notificação do WhatsApp???

**Comment by TK2KMG** [comment]
Bom dia Gabriel !
Me desculpe a sinceridade, mas acho que você poderia ser um pouco mais cortês. Creio que cortesia não machuca ninguém em dizer " Bom dia!" , "Boa Tarde!" ou "Boa Noite!", e também usar aquelas palavrinhas mágicas "Por favor!". 
Verás que tudo em sua vida irá melhorar.

**Comment by augustocoletti** [comment]
> Bom dia Gabriel !
> Me desculpe a sinceridade, mas acho que você poderia ser um pouco mais cortês. Creio que cortesia não machuca ninguém em dizer " Bom dia!" , "Boa Tarde!" ou "Boa Noite!", e também usar aquelas palavrinhas mágicas "Por favor!".
> Verás que tudo em sua vida irá melhorar.

Perfeitamente colocado!

**Comment by R4T0** [comment]
@TK2KMG Perfeito! só agradeça por esses feras que desenvolve o projeto.
