### ISSUE TITLE
Erro  quando executo composer install --no-dev

### ISSUE THREAD

**Issue by decodegear** [RamonSilva20/mapos#1271]
Bom dia e olá a todos.
Não tenho experiência com algumas ferramentas, e queria experimentar o mapos. Consegui rodar em localhost (+-) mas no webserver da um erro quando no terminal envio o comando `composer install --no-dev`, Exibe a seguinte msg:

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

Não sei como proceder. Coloquei na hostgator. 

![composer](https://user-images.githubusercontent.com/79609201/109166095-14d27c00-775b-11eb-9d69-2bb86af11d9a.jpg)
Desculpe por minha falta de experiência. 
Agradeço desde já e peço desculpas se for ignorância da minha parte.
Obrigado e boa semana.

**Comment by Pr3d4dor** [comment]
@decodegear Você está usando PHP 7.2, que não tem mais suporte no mapos.

É necessário usar PHP 7.3 ou PHP 7.4 na sua hospedagem.

**Comment by hoshikawakun** [comment]
Eu tmb utilizo a HostGator, e não tenho problemas com o MapOS, so que o composer eu rodo localmente e faço o UP tudo via FTP

**Comment by gilbertoalmeida16** [comment]
Olá Amigo vou te indicar lá pro meu canal onde explico passo a passo sobre isso que você precisa, precisa se ter uma noção de programação e lá acredito que vai concluir com sucesso , apos isso disponibilizo um vídeo também para configurar os e-mails automáticos assim que abre ou modifica uma OS

https://www.youtube.com/watch?v=mo7vn4ws03g
