### ISSUE TITLE
DROP INDEVIDO DE PRODUTO

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1272]
Ao deletar uma venda, notei que todos os produtos vinculados a ela, é dado baixa na quantidade do meu estoque. Em Ordem de Serviço esse problema esse problema foi corrigido.
![image](https://user-images.githubusercontent.com/73944522/109200393-ee223e80-7776-11eb-85c9-50c0df4fd786.png)

**Comment by Pr3d4dor** [comment]
@R4T0 O que eu entendi é que quando deleta a venda os produtos não voltam ao estoque?

É esse o problema?

**Comment by R4T0** [comment]
@Pr3d4dor isso meu amigo, eles não retornam...

**Comment by cabralwms** [comment]
Eu fiz um teste aqui no meu Sistema mapos 4.31.1 e criei a venda e depois exclui e o produto voltou ao estoque.

**Comment by R4T0** [comment]
instalei em um server totalmente zerado, e persiste o problema. "rodei update na base"
![image](https://user-images.githubusercontent.com/73944522/109319032-d0abae00-7824-11eb-839b-9e8576adf305.png)

Aqui gerei a venda com 4 Cadernos
![image](https://user-images.githubusercontent.com/73944522/109319133-e9b45f00-7824-11eb-89c4-0e374288b344.png)

![image](https://user-images.githubusercontent.com/73944522/109319249-0a7cb480-7825-11eb-90bc-78ec5fbdef36.png)

Após excluir a venda,  vou no meu estoque.
![image](https://user-images.githubusercontent.com/73944522/109319336-21230b80-7825-11eb-8fa9-e9f26cd4eb41.png)

**Comment by willph** [comment]
> instalei em um server totalmente zerado, e persiste o problema. "rodei update na base"
> ![image](https://user-images.githubusercontent.com/73944522/109319032-d0abae00-7824-11eb-839b-9e8576adf305.png)
> 
> Aqui gerei a venda com 4 Cadernos
> ![image](https://user-images.githubusercontent.com/73944522/109319133-e9b45f00-7824-11eb-89c4-0e374288b344.png)
> 
> ![image](https://user-images.githubusercontent.com/73944522/109319249-0a7cb480-7825-11eb-90bc-78ec5fbdef36.png)
> 
> Após excluir a venda, vou no meu estoque.
> ![image](https://user-images.githubusercontent.com/73944522/109319336-21230b80-7825-11eb-8fa9-e9f26cd4eb41.png)

Venda foi faturada?

Depois vou testar novamente do zero, mas aqui também estava voltando pro estoque quando excluía.

**Comment by hoshikawakun** [comment]
> 
> 
> instalei em um server totalmente zerado, e persiste o problema. "rodei update na base"
> ![image](https://user-images.githubusercontent.com/73944522/109319032-d0abae00-7824-11eb-839b-9e8576adf305.png)
> 
> Aqui gerei a venda com 4 Cadernos
> ![image](https://user-images.githubusercontent.com/73944522/109319133-e9b45f00-7824-11eb-89c4-0e374288b344.png)
> 
> ![image](https://user-images.githubusercontent.com/73944522/109319249-0a7cb480-7825-11eb-90bc-78ec5fbdef36.png)
> 
> Após excluir a venda, vou no meu estoque.
> ![image](https://user-images.githubusercontent.com/73944522/109319336-21230b80-7825-11eb-8fa9-e9f26cd4eb41.png)

Axo que depois de fatuara o produto realmente não volta ao estoque

**Comment by R4T0** [comment]
Não não ela nem foi faturada...
