### ISSUE TITLE
Pix

### ISSUE THREAD

**Issue by tombeira** [RamonSilva20/mapos#1273]
Preciso de uma informação como faço a cobrança via pix pois ao gerar pagamanetos é via mercado pago e via gerencia net
só uma duvida, ja inclui a opção no bancode dados

**Comment by Pr3d4dor** [comment]
@tombeira Ao configurar sua chave PIX nas configurações, quando você imprime a OS/Venda (A4) e vai ter lá o QR code que o cliente pode usar para ser feito o pagamento.

Porém não existe integração para saber se foi pagou ou não, então a OS/Venda ainda deverá ser faturada manualmente após o cliente pagar pelo QR code.
