### ISSUE TITLE
Imagens nos produtos.

### ISSUE THREAD

**Issue by jowclides** [RamonSilva20/mapos#1274]
** Sua solicitação de feature está relacionada a um problema? Não. Apenas uma sugestão de melhoria neste sistema fantástico**
Pessoal,  percebi que neste sistema, não temos a opção de **imagens no cadastro de um produto**.
Seria muito complicado inserirmos esta feature nas próximas versões ?

** Sua solicitação de feature está relacionada a um problema? Não. Apenas uma sugestão de melhoria neste sistema fantástico**
Pessoal,  percebi que neste sistema, não temos a opção **comissão dos vendedores** .
Seria muito complicado inserirmos esta feature nas próximas versões ?

**Comment by Pr3d4dor** [comment]
@jowclides Obrigado pela sugestão, mas muito dos usuários do mapos não necessitam de imagem nos produtos. Se quiser fazer uma PR fazendo essa adição, será bem vindo.

Porém a proridade atual é correção de bugs e não adição de novas features.

**Comment by hoshikawakun** [comment]
Tentei fazer isso uma vez e desisti na epoca pois não conseguia, hoje talvez consiga
a mesma coisa e valida para add foto a clientes

Na epoca consegui add todos os botoes e campos para vc add foto, editar, visualizar, editar e excluir, o grande problema era que ao editar a foto (Colocar outra no lugar) la na pasta onde fica as fotos a anterior não era apagada e o sistema apenas ia acrescentando novas.

Não desisti dessa ideia ainda, creio que hoje eu deva conseguir pois ja adquiri o conhecimento que axo ser nescesario.

No momento estou trabalhando em descobrir todos os codigos CSS do sistema que altera a cor das linhas e que fique tudo fininha as linhas

Creio ja ter localizado todos

Agora e so aplicar aos PHP para que fique tudo apresentado corretamente

O arquivo do tema estou cometando cada linha dele

**Comment by jowclides** [comment]
**Olá pessoal,**

eu consegui fazer a implementação do campo de imagem do produto neste sistema.

como eu posso contribuir disponibilizando as melhorias?


![tela01](https://user-images.githubusercontent.com/19734762/109964431-6e432980-7ccc-11eb-94c6-10ce5bf00e00.jpg)
![tela02](https://user-images.githubusercontent.com/19734762/109964661-b82c0f80-7ccc-11eb-949c-6fb310c7bac2.jpg)
![tela03](https://user-images.githubusercontent.com/19734762/109964663-b95d3c80-7ccc-11eb-8637-2e239301a3cb.jpg)
![tela04](https://user-images.githubusercontent.com/19734762/109964666-b95d3c80-7ccc-11eb-895a-a89a22460b87.jpg)
