### ISSUE TITLE
Erro ao tentar cadastrar chave PIX

### ISSUE THREAD

**Issue by jowclides** [RamonSilva20/mapos#1275]
** Descreva o bug **
Estou com erro ao tentar cadastrar uma chave PIX.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Configurações > Sistema > Financeiro'
2. Clique em 'Chave Pix para Recebimento de Pagamentos
3. Insira a chave '(Aqui eu tentei e-mail, cpf, rg e não foi)...'
4.  Após a inclusão da chave, o campo volta ZERADO e não dá erro.

**Comportamento esperado**
Espera que apos este procedimento, o sistema pudesse cadastrar o item (chave PIX) no Banco e os metodos de cobrança PIX pudesse funcionar.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

![image](https://user-images.githubusercontent.com/19734762/109230956-7d921680-77a4-11eb-9ce4-c562a510797a.png)

![image](https://user-images.githubusercontent.com/19734762/109230989-8b479c00-77a4-11eb-984e-7874ceadd449.png)

Após o fim do processo o campo aparece em branco.

![image](https://user-images.githubusercontent.com/19734762/109231068-a87c6a80-77a4-11eb-97d1-0088144b5d9f.png)

**VERSAO 4.31.1**

Alguém pode me ajudar ?

**Comment by Pr3d4dor** [comment]
@jowclides Provavelmente o seu banco de dados não está atualizado, verifique se ele está.

Caso não esteja você pode atualizar ele lá em Configurações, ou executar o .sql da pasta updates que estiver faltante.

**Comment by jowclides** [comment]
Boa ... Resolvido com a execução do UPDATE SQL "update_4.30.3_to_4.31.0.sql".

**Pr3d4dor**,  

muito obrigado !!!
