### ISSUE TITLE
Onde fica o arquivo de notificação do WhatsApp

### ISSUE THREAD

**Issue by igoatier** [RamonSilva20/mapos#1276]
Bom dia.

Gostaria de saber onde fica o arquivo de configuração do WhatsApp, pois nas versões anteriores  eu modificava o nome do emitente para um nome fantasia quer criei no banco de dados, logo na configuração do botão fazia a modificação.

gostaria de uma ajuda para localizar esses arquivo se possível. 

desde já agradeço a toda equipe pelo ótimo trabalho.

**Comment by willph** [comment]
> Bom dia.
> 
> Gostaria de saber onde fica o arquivo de configuração do WhatsApp, pois nas versões anteriores eu modificava o nome do emitente para um nome fantasia quer criei no banco de dados, logo na configuração do botão fazia a modificação.
> 
> gostaria de uma ajuda para localizar esses arquivo se possível.
> 
> desde já agradeço a toda equipe pelo ótimo trabalho.

A mensagem é formada nas configurações, sistema, notificação, mas vou olhar como muda a variáveis e de onde vem

**Comment by willph** [comment]
A variáveis fica na view `VisualizarOs.php`  é daqui que vem o emitente `$emitente ? $emitente[0]->nome `

```
$zapnumber = preg_replace("/[^0-9]/", "", $result->celular_cliente);
    $troca = [$result->nomeCliente, $result->idOs, $result->status, 'R$ ' . number_format($totalProdutos + $totalServico, 2, ',', '.'), strip_tags($result->descricaoProduto), ($emitente ? $emitente[0]->nome : ''), ($emitente ? $emitente[0]->telefone : ''), strip_tags($result->observacoes), strip_tags($result->defeito), strip_tags($result->laudoTecnico), date('d/m/Y', strtotime($result->dataFinal)), date('d/m/Y', strtotime($result->dataInicial)), $result->garantia . ' dias'];
    $texto_de_notificacao = $this->os_model->criarTextoWhats($texto_de_notificacao, $troca);
    if (!empty($zapnumber)) {
        echo '<a title="Enviar Por WhatsApp" class="btn btn-mini btn-success" id="enviarWhatsApp" target="_blank" href="https://web.whatsapp.com/send?phone=55' . $zapnumber . '&text=' . $texto_de_notificacao . '"><i class="fab fa-whatsapp"></i> WhatsApp</a>';
    }
} ?>
```

**Comment by igoatier** [comment]
Bom dia.
Obrigado pelo retorno.
agora consigo colocar o nome fantasia no lugar da razão do cliente

**Comment by willph** [comment]
De nada, qualquer dúvida só entra em contato.

Atenciosamente, Equipe MAPOS.
________________________________________________
Doações

Gosta do MapOS e gostaria de contribuir financeiramente para o projeto?
Doações podem ser realizadas nos links:

Doação via PIX(QR-CODE).

(Resp. Wilmerson)
https://nubank.com.br/pagar/2eeye/IuBRsX1FTf

(Resp. Gianluca)
https://nubank.com.br/pagar/1ipq5/CMuUVpPLQY
________________________________

Grupos Oficiais

Grupo Whatsapp: https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

Grupo Telegram:  https://t.me/joinchat/mbFGDElRFNszNTRh
