### ISSUE TITLE
Login cliente por CPF e Celular

### ISSUE THREAD

**Issue by vitorpiedras** [RamonSilva20/mapos#1277]
Bom dia, gostaria de substituir o campo email pelo campo Celular no Login do cliente.
Assim o cliente logará usando apenas CPF e Celular, uma vez que muitos não querem informar email durante abertura de OS.
Ja alterei o arquivo Mine.php dentro de controllers, o arquivo Login.php dentro da pasta conecte.

A validação de campos ficou correta pois ocorre erro ao entrar com Celular e CPF incorretos e não ocorre o erro ao entrar com CPF e Celular corretos, porém a pagina do Cliente não carrega mesmo com os dados corretos, fica na pagina de Login.

Obrigado pela ajuda.

**Comment by hoshikawakun** [comment]
Eu no meu coloquei para o cliente entrar na area do cliente por eMail e Senha
Caso o cliente não informe o eMail o sistema gera um eMail Aleatorio e uma senha aleatoria
as mesmas são informadas ao cliente quando se envia WhatsApp referente a OS
![Screenshot_86](https://user-images.githubusercontent.com/1253576/109375194-929ca180-7899-11eb-9317-aac4eb14a252.png)

**Comment by hoshikawakun** [comment]
Eu no meu coloquei para o cliente entrar na area do cliente por eMail e Senha
Caso o cliente não informe o eMail o sistema gera um eMail Aleatorio e uma senha aleatoria
as mesmas são informadas ao cliente quando se envia WhatsApp referente a OS
![Screenshot_86](https://user-images.githubusercontent.com/1253576/109375215-cd063e80-7899-11eb-9cb6-b80d40da9423.png)

**Comment by willph** [comment]
> Eu no meu coloquei para o cliente entrar na area do cliente por eMail e Senha
> Caso o cliente não informe o eMail o sistema gera um eMail Aleatorio e uma senha aleatoria
> as mesmas são informadas ao cliente quando se envia WhatsApp referente a OS
> ![Screenshot_86](https://user-images.githubusercontent.com/1253576/109375215-cd063e80-7899-11eb-9cb6-b80d40da9423.png)

Você tinha feito uma PR num foi?

**Comment by hoshikawakun** [comment]
> 
> 
> > Eu no meu coloquei para o cliente entrar na area do cliente por eMail e Senha
> > Caso o cliente não informe o eMail o sistema gera um eMail Aleatorio e uma senha aleatoria
> > as mesmas são informadas ao cliente quando se envia WhatsApp referente a OS
> > ![Screenshot_86](https://user-images.githubusercontent.com/1253576/109375215-cd063e80-7899-11eb-9cb6-b80d40da9423.png)
> 
> Você tinha feito uma PR num foi?
tem uma insue sobre modificações que eu fiz

**Comment by willph** [comment]
> Bom dia, gostaria de substituir o campo email pelo campo Celular no Login do cliente.
> Assim o cliente logará usando apenas CPF e Celular, uma vez que muitos não querem informar email durante abertura de OS.
> Ja alterei o arquivo Mine.php dentro de controllers, o arquivo Login.php dentro da pasta conecte.
> 
> A validação de campos ficou correta pois ocorre erro ao entrar com Celular e CPF incorretos e não ocorre o erro ao entrar com CPF e Celular corretos, porém a pagina do Cliente não carrega mesmo com os dados corretos, fica na pagina de Login.
> 
> Obrigado pela ajuda.

Já conseguiu?

Precisa de ajuda ainda?
Fico no aguardo.
