### ISSUE TITLE
Selecionar cliente e mandar pra página de vendas

### ISSUE THREAD

**Issue by JCMF85** [RamonSilva20/mapos#1278]
Olá pessoal, como estão? =)

Queria implementar um recurso que seria muito útil aqui pra mim, se puderem me ajudar, ficaria muito grato.

O que eu gostaria de tentar fazer é colocar um botão ou um select junto ao nome do cliente para puxar as informações dele.

Por exemplo:

Quando eu fizer a pesquisa do cliente, na área de clientes onde aparece toda a lista, queria ter um botão ou um select onde já mando esse determinado cliente para a área de vendas, já selecionando os dados desse cliente. Em seguida, na área de vendas, eu finalizava a venda.

Espero que tenham entendido e que possam me ajudar.

Desde já agradeço demais.

**Comment by hoshikawakun** [comment]
mas creio que para isso que serve o Auto Complete do cliente nas vendas
se vc começa a escreve o nome dele ali e não aparece e prq não tem ele cadastrado

**Comment by JCMF85** [comment]
> mas creio que para isso que serve o Auto Complete do cliente nas vendas
> se vc começa a escreve o nome dele ali e não aparece e prq não tem ele cadastrado

Não seria bem isso amigo.

Olha o vídeo abaixo por gentileza.

https://user-images.githubusercontent.com/66706763/109439197-20989980-7a0c-11eb-94f6-f5207a4ee9f6.mp4


https://user-images.githubusercontent.com/66706763/109439205-25f5e400-7a0c-11eb-9199-9e31a53f48e5.mp4

**Comment by willph** [comment]
> 
> 
> Olá pessoal, como estão? =)
> 
> Queria implementar um recurso que seria muito útil aqui pra mim, se puderem me ajudar, ficaria muito grato.
> 
> O que eu gostaria de tentar fazer é colocar um botão ou um select junto ao nome do cliente para puxar as informações dele.
> 
> Por exemplo:
> 
> Quando eu fizer a pesquisa do cliente, na área de clientes onde aparece toda a lista, queria ter um botão ou um select onde já mando esse determinado cliente para a área de vendas, já selecionando os dados desse cliente. Em seguida, na área de vendas, eu finalizava a venda.
> 
> Espero que tenham entendido e que possam me ajudar.
> 
> Desde já agradeço demais.

Você é o rapaz do grupo do Mapos né?

**Comment by JCMF85** [comment]
> Você é o rapaz do grupo do Mapos né?

Isso meu brother.
Você consegue me ajudar? o/
