### ISSUE TITLE
Cobrança GerenciaNet

### ISSUE THREAD

**Issue by juniorweskley** [RamonSilva20/mapos#1279]
Alguém possa me ajudar pois não estou conseguindo fazer integração da api do gerencianet com o mapos. Fiz o teste com api de desenvolvimento rodou perfeito mas ao colocar em produção ela não faz a integração. Quando altero as IDs para o modo produção e tento gerar uma ordem de pagameno da o erro Por favor configurar os dados da API em Config/payment_gatways.php.

**Comment by microreis** [comment]
@juniorweskley qual o erro esta apresentando na tela?

**Comment by juniorweskley** [comment]
![image](https://user-images.githubusercontent.com/51975290/109492047-22447a80-7a69-11eb-8898-5edd343b0d1b.png)

**Comment by juniorweskley** [comment]
Com as IDs do modo desemvolvimento gera os boletos normais, mas ao colocar as IDs do modo produção pede para configurar conforme imagem acima.

**Comment by willph** [comment]
> 
> 
> Com as IDs do modo desemvolvimento gera os boletos normais, mas ao colocar as IDs do modo produção pede para configurar conforme imagem acima.

pegou o código client id e client secret do modo produção?

Eu testei aqui e estava ok

**Comment by juniorweskley** [comment]
Boa noite @willph consegui resolver aqui alterando no codigo para 'production' => true

**Comment by willph** [comment]
> Boa noite @willph consegui resolver aqui alterando no codigo para 'production' => true

Esquece de perguntar se tinha alterado o código para produção hehehe
