### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1280]
Eu fiz varias "Melhorias" e algumas correções que axo necessárias no sistema
Gostaria de poder contribuir com o desenvolvimento do Sistema
Fornecendo essas alterações que fiz e meu nome aparecer ali em Contribuidores

Todas as alterações foram feitas sob a versão 4.31.1

As Alterações são

Centralizada algumas infos das tabelas em geral das pag inicial
![Screenshot_57](https://user-images.githubusercontent.com/1253576/109581031-6c197900-7ada-11eb-97d1-6ae88926b476.png)

Add mais 2 botões de gerar etiquetas em Produtos
![Screenshot_58](https://user-images.githubusercontent.com/1253576/109581066-7c315880-7ada-11eb-9fe1-77b83e9f2eec.png)

Etiqueta QR Code
![Screenshot_59](https://user-images.githubusercontent.com/1253576/109581134-a125cb80-7ada-11eb-9f55-32421b1ce87b.png)

ao escanear o código QR sera apresentada informações como Cod do produto "No meu sistema e o numero automático da DB para cada item tipo o numero do Protocolo de OS" Nome do Produto e o Preço do mesmo
VC pode escanear o mesmo para verificar

Add alguns campos a mais nas OS, e o campo de garantia Até ao clicar abre o calendário
Add tmb mais alguns botoes de funções no cabeçalho da area Editar OS
![Screenshot_62](https://user-images.githubusercontent.com/1253576/109581402-037ecc00-7adb-11eb-90c1-aa65ce5160ec.png)

Modificado o Calendario que aparece ao clicar em um campo para preencher data
Escureci a cor de fundo dos dias em geral
Dia Atual fica com a borda amarela com numero preto
Dia com o mouse encima fica com borda preta e numero Vermelho
E dia Selecionando fica com a borda e o numero Vermelho
![Screenshot_89](https://user-images.githubusercontent.com/1253576/109581702-89027c00-7adb-11eb-83c5-9bd84929253d.png)

Ainda em Editar OS o Botão WhatsApp e em forma MODAL (Janela)
que ira apresentar na tela exatamente oque sera enviado na mensagem
alem de mais algumas infos do cliente como link da area do cliente e os dados para o mesmo fazer o LogIn
![Screenshot_92](https://user-images.githubusercontent.com/1253576/109582877-b05a4880-7add-11eb-8e53-a571dbe66a37.png)

A personalização dessa Msg do WhatsApp e feita em uma Aba na parte de Config do Sistema
![Screenshot_64](https://user-images.githubusercontent.com/1253576/107867068-1f853b00-6e56-11eb-9349-5f8b6c227d88.png)

Organizei melhor como e apresentado os Anexos da OS e deixei sem limitação de formato de arquivo que pode ser Anexado
![Screenshot_61](https://user-images.githubusercontent.com/1253576/107866965-22cbf700-6e55-11eb-970e-9fe3cd43e7fa.png)

na parte do Cliente em Cadastro de Novo Cliente Add o campo Senha que o qual gera uma senha automatica de 10 digitos entre Maiusculo, Minusculo e Numeros de forma aleatoria.
E em Email utilizei da mesma função de gerar aleatorio para o email que gera uma sequencia aleatoria de 15 letras minusculas, e o restante do endereço do email vc configura ele na Aba Gerais Das Config do Sistema
![Screenshot_66](https://user-images.githubusercontent.com/1253576/107867228-d635eb00-6e57-11eb-8e8d-f91e4223b39a.png)

em Config do Sistema na Aba Gerais Coloquei um campo de Msg Rápida do WhatsApp
Que consiste em um campo Em branco Editavel o qual vc coloca o numero desejado
O botão Enviar WhatsApp
e um outro campo Somente de Leitura que mostra o numero que esta atrelado a botão do Enviar
Como funciona
Vc Coloca o numero Desejado e clica em Atualizar
após atualizar o numero que vc digitou vai para o campo so de leitura e o campo editavel fica em branco
Se vc clicar em Atualizar Novamente sem escrever nada o primeiro campo ele apaga o numero do segundo campo

![Screenshot_68](https://user-images.githubusercontent.com/1253576/107867473-e77ff700-6e59-11eb-896a-0e0e825457be.png)

Fiz correções na pag Visualizar OS para melhor apresentar as infos
e na mesma apresenta basicamete igual sera impresso
corrigi A exibição dos Anexos em Visualizar OS

![Screenshot_69](https://user-images.githubusercontent.com/1253576/107867515-58bfaa00-6e5a-11eb-8434-9285482fa537.png)
![Screenshot_70](https://user-images.githubusercontent.com/1253576/107867518-5e1cf480-6e5a-11eb-9cb8-5d7363c18cfc.png)

Outra Alteração que fiz foi colcar Varios tipos de Status para OS
Sendo cada um de uma cor
Como na foto Abaixo

![Screenshot_71](https://user-images.githubusercontent.com/1253576/107886406-5bfc7980-6ede-11eb-99c0-d85ca761c082.png)
![Screenshot_72](https://user-images.githubusercontent.com/1253576/107886411-5f900080-6ede-11eb-8e75-dfc1dcf89bbc.png)

Na Area do Cliente e apresentada da mesma forma com as mesmas cores

Coloquei TMB 2 gerenciadores de arquivos no sistema

O Gerenciador Classico 
![Screenshot_73](https://user-images.githubusercontent.com/1253576/107886643-dc6faa00-6edf-11eb-9462-b63cc772584c.png)

e um outro Gerenciador mais Moderno
![Screenshot_74](https://user-images.githubusercontent.com/1253576/107886702-63248700-6ee0-11eb-80f7-44cf6b4d1624.png)

o qual vc pode escolher qual ira utilizar em Config do Sistema na Aba Gerais
![Screenshot_90](https://user-images.githubusercontent.com/1253576/109581922-f6161180-7adb-11eb-8892-f16062b4c77c.png)

Mais uma Modificação que fiz foi de no Emitente colocar 2 Logo diferentes
Uma Colorida para uso geral
E uma Monocromática para uso nas Impressão Térmica

![Screenshot_76](https://user-images.githubusercontent.com/1253576/108002685-1ff51180-6fcf-11eb-972c-edcce99f33f0.png)

Re-posicionei o QR Code do PIX na impressão das OS
Agora ele fica centrado na impressão e Logo abaixo do valor total dos itens e por mero detalhe acima do QR Code do PIX tem a Logo do PIX
![Screenshot_77](https://user-images.githubusercontent.com/1253576/108002901-c2ad9000-6fcf-11eb-8cb7-f5e092328bdc.png)

Nessa minha modificação devido a quantidade de alterações que foram feitas retirei o tema Neve e deixei apenas o tema modificado que eu fiz
Mas se quiser criar um novo tema ou editar o atual basta mecher o arquivo Tema2.css
Editando ele para modificar o tema e duplicando para fazer outros temas
O arquivo esta todo comentado

Outra alteração que fiz que axei bem pertinente e no menu lateral em Cliente, Produtos, Serviços e OS na frente apresenta a quantidade de itens que tem 
![Screenshot_91](https://user-images.githubusercontent.com/1253576/109582382-cf0c0f80-7adc-11eb-97e6-a8966026fe38.png)

E varias outras alterações

**Comment by Pr3d4dor** [comment]
Boa noite @hoshikawakun, não teria como você fazer uma Pull Request com essas melhorias?

**Comment by hoshikawakun** [comment]
> 
> 
> Boa noite @hoshikawakun, não teria como você fazer uma Pull Request com essas melhorias?

Como se faz isso?

**Comment by hoshikawakun** [comment]
> 
> 
> Boa noite @hoshikawakun, não teria como você fazer uma Pull Request com essas melhorias?

então aki e so alterar os arquivos da pasta no PC, mandar subir e fazer a pull rquest?
![Screenshot_94](https://user-images.githubusercontent.com/1253576/109589057-82c6cc80-7ae8-11eb-97cc-737a1870dc91.png)

**Comment by hoshikawakun** [comment]
Axo que consegui criar a Pull Request

**Comment by willph** [comment]
> Axo que consegui criar a Pull Request

Obrigado pela contribuição. 
Cada um ajudando com um pouquinho o sistema ficará TOP. 

Vou olhar pra vê se conseguiu fazer a PR.

**Comment by R4T0** [comment]
@hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?

**Comment by mikxingu** [comment]
Nossa que melhorias excelentes! Espero que esteja disponível em uma futura atualização logo!

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?

o cliente não tem como Upar nenhum tipo de arquivo

**Comment by willph** [comment]
> > @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?
> 
> o cliente não tem como Upar nenhum tipo de arquivo

Não conseguiu resolver os conflitos da sua PR num foi?

**Comment by R4wd0g** [comment]
> 
> 
> > > @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?
> > 
> > 
> > o cliente não tem como Upar nenhum tipo de arquivo
> 
> Não conseguiu resolver os conflitos da sua PR num foi?

O que vc acha de usarmos este gráfico ao invés do de barras? Gostaria de uma opinião do seu ponto de vista:
![image](https://user-images.githubusercontent.com/29448208/110257533-1e3ebe00-7f7d-11eb-94a3-b50cc3b8c05a.png)

**Comment by willph** [comment]
> > > > @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?
> > > 
> > > 
> > > o cliente não tem como Upar nenhum tipo de arquivo
> > 
> > 
> > Não conseguiu resolver os conflitos da sua PR num foi?
> 
> O que vc acha de usarmos este gráfico ao invés do de barras? Gostaria de uma opinião do seu ponto de vista:
> ![image](https://user-images.githubusercontent.com/29448208/110257533-1e3ebe00-7f7d-11eb-94a3-b50cc3b8c05a.png)

Pode ser.
Fica bom também.

**Comment by xdnl0506** [comment]
Como consigo ter acesso á essas melhorias?

**Comment by hoshikawakun** [comment]
> 
> 
> > > > @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?
> > > 
> > > 
> > > o cliente não tem como Upar nenhum tipo de arquivo
> > 
> > 
> > Não conseguiu resolver os conflitos da sua PR num foi?
> 
> O que vc acha de usarmos este gráfico ao invés do de barras? Gostaria de uma opinião do seu ponto de vista:
> ![image](https://user-images.githubusercontent.com/29448208/110257533-1e3ebe00-7f7d-11eb-94a3-b50cc3b8c05a.png)

seria axo melhor ainda se nas config do sistema pudesse escolher o tipo do grafico

**Comment by hoshikawakun** [comment]
> 
> 
> > > @hoshikawakun Parabéns mano ficou show suas melhorias... só uma que acho melhor do jeito que está, é a do WhatsApp.. fora essa ficou legal... Mas já pensou na possibilidade de o cliente upar um arquivo malicioso, capaz de comprometer o servidor?
> > 
> > 
> > o cliente não tem como Upar nenhum tipo de arquivo
> 
> Não conseguiu resolver os conflitos da sua PR num foi?

eram conflitos que não entendo

não saberia nem por onde começar pra resolver e nem oque estava cusando eles, ate como falei, mudei muitos arquivos, quase todos os PHP e mechi neles

Na PR me foi dado umas sugestões que irei aplicar e depois tento outra PR
