### ISSUE TITLE
Erro ao inserir chave PIX

### ISSUE THREAD

**Issue by naodoubuff** [RamonSilva20/mapos#1282]
Ao tentar inserir a chave PIX, apresenta seguinte erro. 
Estou utilizando a ultima versão, instalação limpa do sistema, banco de dados atualizado. 
Alguem pode me ajudar?
![image](https://user-images.githubusercontent.com/78187809/109595850-020dcd80-7af4-11eb-969c-3edf0cb480de.png)

**Comment by hoshikawakun** [comment]
Axo que a chave pix que o sistema aceita e so o numero de telefone

**Comment by naodoubuff** [comment]
> Axo que a chave pix que o sistema aceita e so o numero de telefone

Tentei, deu o mesmo problema.

**Comment by tibjunior** [comment]
No meu tive que atualizar o composer localmente e enviei a pasta vendor pro servidor (apaguei a que tinha lá).. após isso saiu esse bug.

**Comment by hoshikawakun** [comment]
> 
> 
> No meu tive que atualizar o composer localmente e enviei a pasta vendor pro servidor (apaguei a que tinha lá).. após isso saiu esse bug.

no meu tmb tive esse problema quando saiu o pix
so atualizei o composer e resouveu

**Comment by cabralwms** [comment]
Tem uma atualização no Banco de Dados e o composer, precisa fazer os dois para funcionar.

**Comment by R4T0** [comment]
com e-mail e telefone já testei e funciona... como o amigo @cabralwms disse, tem essa atualização que precisa ser feita no banco

**Comment by Pr3d4dor** [comment]
@naodoubuff rode o comando composer install

**Comment by willph** [comment]
> 
> 
> Ao tentar inserir a chave PIX, apresenta seguinte erro.
> Estou utilizando a ultima versão, instalação limpa do sistema, banco de dados atualizado.
> Alguem pode me ajudar?
> ![image](https://user-images.githubusercontent.com/78187809/109595850-020dcd80-7af4-11eb-969c-3edf0cb480de.png)

conseguiu resolver o problema?

**Comment by naodoubuff** [comment]
> > Ao tentar inserir a chave PIX, apresenta seguinte erro.
> > Estou utilizando a ultima versão, instalação limpa do sistema, banco de dados atualizado.
> > Alguem pode me ajudar?
> > ![image](https://user-images.githubusercontent.com/78187809/109595850-020dcd80-7af4-11eb-969c-3edf0cb480de.png)
> 
> conseguiu resolver o problema?

Ainda nao...

**Comment by willph** [comment]
> @naodoubuff rode o comando composer install

Tá parecendo que ele não tem a dependência relacionada ao PIX.

**Comment by willph** [comment]
> > > Ao tentar inserir a chave PIX, apresenta seguinte erro.
> > > Estou utilizando a ultima versão, instalação limpa do sistema, banco de dados atualizado.
> > > Alguem pode me ajudar?
> > > ![image](https://user-images.githubusercontent.com/78187809/109595850-020dcd80-7af4-11eb-969c-3edf0cb480de.png)
> > 
> > 
> > conseguiu resolver o problema?
> 
> Ainda nao...

Rodou o comando COMPOSER UPDATE?

**Comment by rogowski193** [comment]
Parece ser um erro na biblioteca piggly/php-pix.
Consegui resolver usando o comando "composer require piggly/php-pix" por ssh,

**Comment by Pr3d4dor** [comment]
Não é um problema na lib, o que ocorre é que quando atualizam é necessário rodar o composer install para instar as dependencias pois ela foi adicionada posteriormente.
