### ISSUE TITLE
Envio de e-mail automático

### ISSUE THREAD

**Issue by andrehoffmann1** [RamonSilva20/mapos#1283]
Bom dia pessoal! Que projetão esse MapOS! Parabéns a todos os envolvidos!

Bom, estou com dificuldades no envio automático para o cliente.
Minha hospedagem é na hostinger.

Segue uma parte do log:
ERROR - 2021-02-26 14:11:03 --> 220 ESMTP smtp.hostinger.com
hello: 250-nl-srv-smtpout1.hostinger.io
starttls: 220 2.0.0 Ready to start TLS
hello: 250-nl-srv-smtpout1.hostinger.io
from: 250 2.1.0 Ok
to: 553 5.7.1 andre_guilherme@msn.com: Sender address rejected: not owned by user teste@andrehoffmann.website
The following SMTP error was encountered: 553 5.7.1 andre_guilherme@msn.com: Sender address rejected: not owned by user teste@andrehoffmann.website
quit: 221 2.0.0 Bye
Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method. From: andre_guilherme@msn.com
Subject: Ordem de Serviço - Criada
To: andguihofros@gmail.com

Acontece que o serviço de SMTP está ativo.

Poderia me ajudar?

**Comment by cabralwms** [comment]
Parece ser erro no PHP e nao no SMTP. Verifica os modulos do PHP deve ser a resposta para esse erro.

**Comment by R4T0** [comment]
Testa com o servidor do Gmail primeiro... hostinger nunca usei

**Comment by Pr3d4dor** [comment]
@andrehoffmann1 O e-mail do emitente precisa ser o mesmo das credenciais ed autenticação que vc está usando.

Nesse seu caso precisa ser o teste@andrehoffmann.website que precisa ser setado no email em configurações >> emitente.

**Comment by andrehoffmann1** [comment]
> @andrehoffmann1 O e-mail do emitente precisa ser o mesmo das credenciais ed autenticação que vc está usando.
> 
> Nesse seu caso precisa ser o [teste@andrehoffmann.website](mailto:teste@andrehoffmann.website) que precisa ser setado no email em configurações >> emitente.

Acertou em cheio, muito obrigado a vc e a todos que se preocuparam em resolver este problema!

**Comment by heraf250** [comment]
> andrehoffmann.website

Boa noite, André minha hospedagem tbm é hostinger, como vc configurou o email.php? e as cron?

**Comment by andrehoffmann1** [comment]
> > andrehoffmann.website
> 
> Boa noite, André minha hospedagem tbm é hostinger, como vc configurou o email.php? e as cron?

Olá, 

No email.php foi assim:
$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.hostinger.com.br';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;

No cron:
*/5 * * * * | /usr/bin/php /home/u318605424/public_html/index.php email/process

Lembrando que o e-mail do emitente deve ser igual ao configurado no email.php como relatou nosso amigo Predador.
