### ISSUE TITLE
Bug ao excluir ou atualizar cobranças.

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#1284]
Está retornando um erro quando tento excluir ou atualizar uma cobrança, (no meu caso) pelo mercadopago (boleto).

![image](https://user-images.githubusercontent.com/11595213/109717083-611b2300-7b84-11eb-9c5c-e76b07ff516a.png)

Grato pela atenção!

**Comment by willph** [comment]
> 
> 
> Está retornando um erro quando tento excluir ou atualizar uma cobrança, (no meu caso) pelo mercadopago (boleto).
> 
> ![image](https://user-images.githubusercontent.com/11595213/109717083-611b2300-7b84-11eb-9c5c-e76b07ff516a.png)
> 
> Grato pela atenção!

Infelizmente tem um bug na api do MercadoPago, em modo de teste funciona tudo ok, mas em produção so funciona o gerar boleto.

Agora a API da gerencianet esta funcionando 100% em modo produção.

**Comment by tibjunior** [comment]
Mas pra gerar boleto gerou ok.. não consigo é apagar, nem atualizar o status.. :( vou tentar resetar e fazer só com o gerencianet.

**Comment by brunomontteiro** [comment]
Estou com o mesmo problema, não consigo excluir, cancelar ou qualquer outra opção da o mesmo erro.

**Comment by Pr3d4dor** [comment]
@brunomontteiro Está ocorrendo esse problema no modo produção ou sandbox?

**Comment by tibjunior** [comment]
Produção..
