### ISSUE TITLE
Ordens com status FATURADO não esta aparecendo 

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1285]
Boa noite jovens, recentemente atualizei o sistema que estava na v4.13 para a 4.31.1,
no caso após atualizar, as ordens com status FATURADO não estão mais aparecendo nas pesquisas,
se pesquisar por um determinado cliente, só aparece as OS Finalizadas e canceladas.

**Comment by hoshikawakun** [comment]
em config do sistema esperimente colocar "Controle de edição de OS" como desativado

**Comment by jsfachini** [comment]
Testei, sem sucesso, ao pesquisar um cliente, as OS Faturadas não aparecem.

**Comment by jsfachini** [comment]
Existe a possibilidade de voltar a mostrar as OS faturadas ? tanto no menu "ordens de serviço" quanto ao pesquisar por cliente ?

**Comment by willph** [comment]
> 
> 
> Existe a possibilidade de voltar a mostrar as OS faturadas ? tanto no menu "ordens de serviço" quanto ao pesquisar por cliente ?

As ordens faturadas continua lá, mas oculta.

Instalação do zero?
Atualização?

**Comment by jsfachini** [comment]
> > Existe a possibilidade de voltar a mostrar as OS faturadas ? tanto no menu "ordens de serviço" quanto ao pesquisar por cliente ?
> 
> As ordens faturadas continua lá, mas oculta.
> 
> Instalação do zero?
> Atualização?


quanto elas estarem ocultas no menu ordem de serviço, blz ficou melhor mesmo
mas na pesquisa por cliente não aparece,

fiz uma instalação limpa pra testar, banco zerado, apresenta o mesmo problema

fiz a instalação limpeza e importei a base, mesmo problema.

**Comment by willph** [comment]
> > > Existe a possibilidade de voltar a mostrar as OS faturadas ? tanto no menu "ordens de serviço" quanto ao pesquisar por cliente ?
> > 
> > 
> > As ordens faturadas continua lá, mas oculta.
> > Instalação do zero?
> > Atualização?
> 
> quanto elas estarem ocultas no menu ordem de serviço, blz ficou melhor mesmo
> mas na pesquisa por cliente não aparece,
> 
> fiz uma instalação limpa pra testar, banco zerado, apresenta o mesmo problema
> 
> fiz a instalação limpeza e importei a base, mesmo problema.

Já testou selecionar o filtro FATURADO e clicar em pesquisa?

Aqui está OK

![16149901587893527065294121738845](https://user-images.githubusercontent.com/17226802/110187988-faeb0600-7df8-11eb-9bfd-0d1416867a9d.jpg)

**Comment by jsfachini** [comment]
> > > > Existe a possibilidade de voltar a mostrar as OS faturadas ? tanto no menu "ordens de serviço" quanto ao pesquisar por cliente ?
> > > 
> > > 
> > > As ordens faturadas continua lá, mas oculta.
> > > Instalação do zero?
> > > Atualização?
> > 
> > 
> > quanto elas estarem ocultas no menu ordem de serviço, blz ficou melhor mesmo
> > mas na pesquisa por cliente não aparece,
> > fiz uma instalação limpa pra testar, banco zerado, apresenta o mesmo problema
> > fiz a instalação limpeza e importei a base, mesmo problema.
> 
> Já testou selecionar o filtro FATURADO e clicar em pesquisa?
> 
> Aqui está OK
> 
> ![16149901587893527065294121738845](https://user-images.githubusercontent.com/17226802/110187988-faeb0600-7df8-11eb-9bfd-0d1416867a9d.jpg)


sim no caso escolhendo o filtro faturado elas aparecem mas de todos os clientes juntos,
se você selecionar um cliente, ai elas não aparecem.

**Comment by jsfachini** [comment]
na versão 4.13 funcionava perfeitamente pesquisando por um cliente em especifico,
aparecem todas as OS do mesmo, faturada, cancelada, aberta... todas.

me parece que o filtro faturado não esta funcionando quando se determina um cliente.

**Comment by jsfachini** [comment]
Pesquisa por faturada desse cliente ( tem mais de 30 OS ) já faturadas, porem não aparecem
![nop](https://user-images.githubusercontent.com/72340074/110188543-d728bf80-7dfa-11eb-9758-cecdb609ee6e.JPG)

Pesquisando pelo cliente sem selecionar um filtro, aparece só as não faturadas.
![nop 2](https://user-images.githubusercontent.com/72340074/110188547-dabc4680-7dfa-11eb-96a4-b036754db008.JPG)

**Comment by willph** [comment]
> na versão 4.13 funcionava perfeitamente pesquisando por um cliente em especifico,
> aparecem todas as OS do mesmo, faturada, cancelada, aberta... todas.
> 
> me parece que o filtro faturado não esta funcionando quando se determina um cliente.

Entende.

No caso é colocando nome do cliente + filtro FATURADO.

Realmente não funcionou. 
Vou analisar.

**Comment by jsfachini** [comment]
> > na versão 4.13 funcionava perfeitamente pesquisando por um cliente em especifico,
> > aparecem todas as OS do mesmo, faturada, cancelada, aberta... todas.
> > me parece que o filtro faturado não esta funcionando quando se determina um cliente.
> 
> Entende.
> 
> No caso é colocando nome do cliente + filtro FATURADO.
> 
> Realmente não funcionou.
> Vou analisar.


Show, valeu obrigado pela atenção.

**Comment by willph** [comment]
> > > na versão 4.13 funcionava perfeitamente pesquisando por um cliente em especifico,
> > > aparecem todas as OS do mesmo, faturada, cancelada, aberta... todas.
> > > me parece que o filtro faturado não esta funcionando quando se determina um cliente.
> > 
> > 
> > Entende.
> > No caso é colocando nome do cliente + filtro FATURADO.
> > Realmente não funcionou.
> > Vou analisar.
> 
> Show, valeu obrigado pela atenção.

Bug já localizado.

Em breve será enviado PR com a correção

**Comment by willph** [comment]
Correção feita, só aguarda aprovação #1291.

**Comment by willph** [comment]
Irei fechar Issue após aprovação da PR, qualquer coisa só abri novamente ok?

-----------------------------------------------------------------------------------
Gosta do Mapos e gostaria de contribuir com seu desenvolvimento?
Doações podem ser realizadas nos links:

Vakinha
http://vaka.me/1625349

Catarse
https://www.catarse.me/mapos

Compartilhe nas suas redes sociais, toda ajuda será bem-vinda.

Atenciosamente, Wilmerson (Equipe Mapos)

**Comment by jsfachini** [comment]
> Irei fechar Issue após aprovação da PR, qualquer coisa só abri novamente ok?
> 
> Gosta do Mapos e gostaria de contribuir com seu desenvolvimento?
> Doações podem ser realizadas nos links:
> 
> Vakinha
> http://vaka.me/1625349
> 
> Catarse
> https://www.catarse.me/mapos
> 
> Compartilhe nas suas redes sociais, toda ajuda será bem-vinda.
> 
> Atenciosamente, Wilmerson (Equipe Mapos)


Muito Obrigado

**Comment by willph** [comment]
> > Irei fechar Issue após aprovação da PR, qualquer coisa só abri novamente ok?
> > Gosta do Mapos e gostaria de contribuir com seu desenvolvimento?
> > Doações podem ser realizadas nos links:
> > Vakinha
> > http://vaka.me/1625349
> > Catarse
> > https://www.catarse.me/mapos
> > Compartilhe nas suas redes sociais, toda ajuda será bem-vinda.
> > Atenciosamente, Wilmerson (Equipe Mapos)
> 
> Muito Obrigado

Eu é que agradeço. 
Sua ajuda nos ajuda e muito. 


Atenciosamente, Wilmerson (Equipe Mapos)

**Comment by willph** [comment]
> > Irei fechar Issue após aprovação da PR, qualquer coisa só abri novamente ok?
> > Gosta do Mapos e gostaria de contribuir com seu desenvolvimento?
> > Doações podem ser realizadas nos links:
> > Vakinha
> > http://vaka.me/1625349
> > Catarse
> > https://www.catarse.me/mapos
> > Compartilhe nas suas redes sociais, toda ajuda será bem-vinda.
> > Atenciosamente, Wilmerson (Equipe Mapos)
> 
> Muito Obrigado

Aprovado já.
Só baixa e testar

Qualquer dúvida só falar

**Comment by jsfachini** [comment]
> > > Irei fechar Issue após aprovação da PR, qualquer coisa só abri novamente ok?
> > > Gosta do Mapos e gostaria de contribuir com seu desenvolvimento?
> > > Doações podem ser realizadas nos links:
> > > Vakinha
> > > http://vaka.me/1625349
> > > Catarse
> > > https://www.catarse.me/mapos
> > > Compartilhe nas suas redes sociais, toda ajuda será bem-vinda.
> > > Atenciosamente, Wilmerson (Equipe Mapos)
> > 
> > 
> > Muito Obrigado
> 
> Aprovado já.
> Só baixa e testar
> 
> Qualquer dúvida só falar


Testado e funcionando, mais uma vez obrigado pela força.
