### ISSUE TITLE
Base de fallas

### ISSUE THREAD

**Issue by dragonascendent** [RamonSilva20/mapos#1286]
Nose si le podrían poner una opción donde se le agregue la falla y solución y llevar un registro de fallas por. Modelo de equipo según sea conveniente

**Comment by willph** [comment]
¿Le gustaría tener una base de datos con las fallas ya arregladas, para ayudar con futuras reparaciones?

**Comment by hoshikawakun** [comment]
> 
> 
> ¿Le gustaría tener una base de datos con las fallas ya arregladas, para ayudar con futuras reparaciones?

si
