### ISSUE TITLE
Trocar cor das categorias do highcharts

### ISSUE THREAD

**Issue by mikxingu** [RamonSilva20/mapos#1288]
** Descreva o bug **
Bom dia pessoal. Já procurei editar um milhão de arquivos, e não consigo achar onde mudar a cor das categorias do highcharts, pra mudar as cores dessas categorias das imagens. É algo besta, mas me incomoda as receitas em azul e preto, e despesas em verde. Queria mudar a cor pra ter uma melhor leitura visual, mas não encontro onde está o arquivo que cria essas cores.
No arquivo "painel.php", onde é criada essa chart, só têm o atributo "negativecolor", mas nenhuma alteração que eu faça muda a cor da barra.
Também ja rodei todos os arquivos do css na pasta assets e o arquivo highcharts.js, tem uma parte onde é criada um array com as cores. Já editei esse arquivo também, mas não altera a cor da chart. Alguém pode me ajudar?
Só preciso saber onde é definida a cor. Assim que eu alterar eu faço um PR pois acredito que mais pessoas vão gostar de ver por exemplo as despesas na cor vermelha.

![Mapos](https://user-images.githubusercontent.com/30123586/109972984-9cc60200-7cd6-11eb-8e15-7596642e3643.png)

Desde já agradeço. Obrigado!

**Comment by hoshikawakun** [comment]
> 
> 
> ** Descreva o bug **
> Bom dia pessoal. Já procurei editar um milhão de arquivos, e não consigo achar onde mudar a cor das categorias do highcharts, pra mudar as cores dessas categorias das imagens. É algo besta, mas me incomoda as receitas em azul e preto, e despesas em verde. Queria mudar a cor pra ter uma melhor leitura visual, mas não encontro onde está o arquivo que cria essas cores.
> No arquivo "painel.php", onde é criada essa chart, só têm o atributo "negativecolor", mas nenhuma alteração que eu faça muda a cor da barra.
> Também ja rodei todos os arquivos do css na pasta assets e o arquivo highcharts.js, tem uma parte onde é criada um array com as cores. Já editei esse arquivo também, mas não altera a cor da chart. Alguém pode me ajudar?
> Só preciso saber onde é definida a cor. Assim que eu alterar eu faço um PR pois acredito que mais pessoas vão gostar de ver por exemplo as despesas na cor vermelha.
> 
> ![Mapos](https://user-images.githubusercontent.com/30123586/109972984-9cc60200-7cd6-11eb-8e15-7596642e3643.png)
> 
> Desde já agradeço. Obrigado!

SO ME LEBRO QUE EDITEI UM ARQUIVO JS
![Screenshot_101](https://user-images.githubusercontent.com/1253576/110036829-5f846300-7d1c-11eb-9c6e-311f65ac0198.png)

**Comment by hoshikawakun** [comment]
![Screenshot_102](https://user-images.githubusercontent.com/1253576/110037092-affbc080-7d1c-11eb-883c-3372fcd85f80.png)

**Comment by hoshikawakun** [comment]
Tente colocar esses mesmos codigos que coloquei nesse ponto do meu e veja se resolve seu problema

**Comment by mikxingu** [comment]
Cara, alterei, deixei igual o seu arquivo, mesmo assim, sem sucesso.

**Comment by mikxingu** [comment]
https://gist.github.com/mikxingu/2df189ddf8585e93106156b4359dc195
Aqui é como meu arquivo está. Ja restartei a imagem docker, ja fiz um force recreate depois de alterar, mas nada muda as cores padrão da chart

**Comment by hoshikawakun** [comment]
no proprio php da pag inicial onde fica os graficos, eclua toda confir que tenha la sobre as cores, talvez isso resolva, pode ser que tenha algum conflito ja que em 2 lugares esta falando q7ual deve ser a cor

**Comment by hoshikawakun** [comment]
Tente deixar o painel.php nessa ´parte do balanço igual o meu aki

` <<?php if ($estatisticas_financeiro != null) {
    if ($estatisticas_financeiro->total_receita != null || $estatisticas_financeiro->total_despesa != null || $estatisticas_financeiro->total_receita_pendente != null || $estatisticas_financeiro->total_despesa_pendente != null) {  ?>

        <?php if ($this->permission->checkPermission($this->session->userdata('permissao'), 'rFinanceiro')) : ?>
            <div class="row-fluid" style="margin-top: 0">
                    <div class="span12">
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon"><i class="fas fa-diagnoses"></i></span>
                                <h5>
                                    Balanço Mensal do Ano:
                                </h5>
                                <form method="get">
                                    <input type="number" name="year" style="height: 1.1rem; margin-bottom: 0; margin-top: 0.2rem" value="<?php echo intval(preg_replace('/[^0-9]/', '', $this->input->get('year'))) ?: date('Y') ?>">
                                    <button type="submit" class="btn-xs" style="height: 1.8rem; margin-bottom: 0; margin-top: 0.2rem">Pesquisar</button>
                                </form>
                            </div>
                            <div class="widget_box_master_os">
                                <div class="row-fluid">
                                    <div class="span12">
                                        <div id="chart-vendas-mes1" style=""></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <script src="<?= base_url('assets/js/highchart/highcharts.js') ?>"></script>

            <script type="text/javascript">
                $(function() {
                    var myChart = Highcharts.chart('chart-vendas-mes1', {
                        chart: {
                            type: 'column'
                        },
                        title: {
                            text: 'Financeiro'
                        },
                        xAxis: {
                            categories: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
                        },
                        yAxis: {
                            title: {
                                text: 'Reais',
                                format: 'R$: {value}'
                            }
                        },
                        tooltip: {
                            valueDecimals: 2,
                            valuePrefix: 'R$: '
                        },
                        plotOptions: {
                            series: {
                                dataLabels: {
                                    enabled: true,
                                    format: 'R$: {y}',
                                }
                            }
                        },
                        credits: {
                            enabled: false
                        },
                        series: [{
                                name: 'Receita Líquida',
                                data: [
                                    [<?php echo ($financeiro_mes->VALOR_JAN_REC - $financeiro_mes->VALOR_JAN_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_FEV_REC - $financeiro_mes->VALOR_FEV_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAR_REC - $financeiro_mes->VALOR_MAR_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_ABR_REC - $financeiro_mes->VALOR_ABR_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAI_REC - $financeiro_mes->VALOR_MAI_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUN_REC - $financeiro_mes->VALOR_JUN_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUL_REC - $financeiro_mes->VALOR_JUL_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_AGO_REC - $financeiro_mes->VALOR_AGO_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_SET_REC - $financeiro_mes->VALOR_SET_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_OUT_REC - $financeiro_mes->VALOR_OUT_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_NOV_REC - $financeiro_mes->VALOR_NOV_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_DEZ_REC - $financeiro_mes->VALOR_DEZ_DES); ?>]
                                ]
                            },
                            {
                                name: 'Receita Bruta',
                                data: [
                                    [<?php echo ($financeiro_mes->VALOR_JAN_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_FEV_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAR_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_ABR_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAI_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUN_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUL_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_AGO_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_SET_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_OUT_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_NOV_REC); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_DEZ_REC); ?>]
                                ]
                            },
                            {
                                name: 'Despesas',
                                data: [
                                    [<?php echo ($financeiro_mes->VALOR_JAN_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_FEV_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAR_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_ABR_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_MAI_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUN_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_JUL_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_AGO_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_SET_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_OUT_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_NOV_DES); ?>],
                                    [<?php echo ($financeiro_mes->VALOR_DEZ_DES); ?>]
                                ]
                            }
                        ]
                    });
                });
            </script>
        <?php endif ?>
<?php  }
} ?>

**Comment by mikxingu** [comment]
Cara. Mesmo assim, ainda sem sucesso.
Percebi que o meu hicharts.js ta diferente do seu, o meu não vem esse trecho "defaultOptions=" igual ao seu, antes das cores. Pode me mandar esse arquivo?
De resto, tudo certo. Consigo mudar a cor dos gráficos de pizza, mas do financeiro, nada que eu faço altera as cores dessa chart. Tá muito estranho.

**Comment by mikxingu** [comment]
Descobri que era o cache do meu navegador que não estava atualizando a página. Resolvi o problema fazendo a limpeza do cache.
