### ISSUE TITLE
Ajuda por favor! Erro no envio de e-mail do Cron

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1289]
Bom dia!

Por favor, não sei se alguém já passou por isso. Coloquei o sistema para testar em uma VPS, tudo está  funcionando, porém quando envia os e-mail automaticamente pelo Cron, eu recebo essa mensagem e o email fica preso no gerenciador.

Menssagem de erro que recebo no email:

Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 7.2.0". You are running 5.4.16.

A versão do PHP no server Linux:
![versao_php](https://user-images.githubusercontent.com/77629142/109978340-8cb12100-7cdc-11eb-92c1-0bd1a6f09307.png)

**Comment by Pr3d4dor** [comment]
@Lucios1989 Na VPS você está usando ainda o PHP 5.4 que está depreciado.

Você terá que atualizar o PHP para a versão 7.3

**Comment by Lucios1989** [comment]
@Pr3d4dor , tudo setado direitinho, mas o erro persiste.
Versão Nova PHP VPS
![erroCron](https://user-images.githubusercontent.com/77629142/110094158-48745e00-7d7a-11eb-9081-dc343c695deb.png)
Erro persistente
![erroCron2](https://user-images.githubusercontent.com/77629142/110094255-617d0f00-7d7a-11eb-9061-c4e356dd1808.png)

**Comment by Pr3d4dor** [comment]
@Lucios1989 Para o composer você está usando o PHP 5.4 conforme você pode ver na mensagem de erro. Tente entrar em contato com o suporte da hospedagem

**Comment by R4T0** [comment]
@Lucios1989 cola isso no terminal Para que o php 7.3 seja  o default. 
sudo update-alternatives --set php /usr/bin/php7.3
 Caso não resolva. Deleta as versões anteriores.
apt-get purge --remove php7.x

**Comment by Lucios1989** [comment]
Obrigado @Pr3d4dor e @R4T0 . A versão default do PHP é mesmo a 7.3. Vou tentar resolver com a hospedagem
