### ISSUE TITLE
Email automático não envia mesmo estando configurado

### ISSUE THREAD

**Issue by pepehend** [RamonSilva20/mapos#1290]
configurei o email exatamente como informado, porém ele informa no sistema que envia, mas não chega o email.

alguém poderia me ajudar?

**Comment by Pr3d4dor** [comment]
@pepehend Verificou se não está caindo no lixo eletrônico? Qual email está usando?

**Comment by pepehend** [comment]
> @pepehend Verificou se não está caindo no lixo eletrônico? Qual email está usando?

verifiquei sim. no caso estou usando em uma hospedagem da hostgator, quando eu envio para um email do mesmo domínio, funciona normalmente, mas para qualquer email que não seja do domínio ele não envia.

**Comment by Welder01** [comment]
@Pr3d4dor @pepehend 

Boa noite a todos, estou com um problema semelhante, entretanto, o meu e-mail só fica **pendente**, já tendei configurar por MX Hostinger e Google "aplicativos menos seguros".

Informei o Cron e nada.

Podem me ajudar?

**Comment by Pr3d4dor** [comment]
@Welder01 O email que está configurado no Configurações >> Emitente é o mesmo que está configurado nas configurações de e-mail?

Caso estejam corretos as configurações o problema certamente é o cron que não está executando.

**Comment by Welder01** [comment]
> @Welder01 O email que está configurado no Configurações >> Emitente é o mesmo que está configurado nas configurações de e-mail?
> 
> Caso estejam corretos as configurações o problema certamente é o cron que não está executando.

Prezado amigo, obrigado pela pronta reposta de sempre, parabéns pelo decoro!

Sobre o problema, percebi que deve o mesmo email nas configurações do email.php, devem ser o mesmo do emitente, assim foi feito.

Usei os caminhos para a cron:
diretório raiz/index.php email/process
Diretório raiz/index.php email/retry

Usei as configurações predefinidas pelo próprio hpainel da hostinger.

Viu colar aqui o log de erros !
