### ISSUE TITLE
Ausência de QRCODE PIX na impressão Cliente "CONECTE"

### ISSUE THREAD

**Issue by Welder01** [RamonSilva20/mapos#1292]
** Descreva o bug **
Prezados, boa tarde, percebi que nesta nova versão existe a possibilidade de impressão de QRCODE PIX no momento em que gera impressão de OS | VENDA.
Na oprortunidade esclareço que mesmo preenchendo a chave pix o respectivo código não é apresentado na OS, o que devo fazer para corrigir ?

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Cadastro da chave pix nas configurações;
2. Gerar os para impressão;
3. Ausência do QRCODE.
4. " Não é gerado nenhum log de erro".

Obrigado pela atenção !

**Comment by Pr3d4dor** [comment]
@Welder01 O QR Code aparece na impressão a4 e na não fiscal

**Comment by Pr3d4dor** [comment]
@Welder01 Veja também se seu banco de dados está atualizado e salvando a sua chave pix lá.

**Comment by hoshikawakun** [comment]
> 
> 
> ** Descreva o bug **
> Prezados, boa tarde, percebi que nesta nova versão existe a possibilidade de impressão de QRCODE PIX no momento em que gera impressão de OS | VENDA.
> Na oprortunidade esclareço que mesmo preenchendo a chave pix o respectivo código não é apresentado na OS, o que devo fazer para corrigir ?
> 
> **Reproduzir**
> Etapas para reproduzir o comportamento:
> 
>     1. Cadastro da chave pix nas configurações;
> 
>     2. Gerar os para impressão;
> 
>     3. Ausência do QRCODE.
> 
>     4. " Não é gerado nenhum log de erro".
> 
> 
> Obrigado pela atenção !

para aparecer o QR CODE e preciso ter algum valor na OS, seja Peoduto ou Serviço

**Comment by Welder01** [comment]
@Pr3d4doro, obrigado pela cortesia e agilidade de resposta de sempre !

Fiz a inserção através das configurações do backend, mas vou analisar se elas foram para o DB.

**Comment by Welder01** [comment]
> > ** Descreva o bug **
> > Prezados, boa tarde, percebi que nesta nova versão existe a possibilidade de impressão de QRCODE PIX no momento em que gera impressão de OS | VENDA.
> > Na oprortunidade esclareço que mesmo preenchendo a chave pix o respectivo código não é apresentado na OS, o que devo fazer para corrigir ?
> > **Reproduzir**
> > Etapas para reproduzir o comportamento:
> > ```
> > 1. Cadastro da chave pix nas configurações;
> > 
> > 2. Gerar os para impressão;
> > 
> > 3. Ausência do QRCODE.
> > 
> > 4. " Não é gerado nenhum log de erro".
> > ```
> > 
> > 
> > Obrigado pela atenção !
> 
> para aparecer o QR CODE e preciso ter algum valor na OS, seja Produto ou Serviço

Prezado amigo, obrigado pela prontidão, a os teste foi gerada com custas.

**Comment by Welder01** [comment]
> @Welder01 Veja também se seu banco de dados está atualizado e salvando a sua chave pix lá.

Meu amigo, a chave esta no DB !

**Comment by Welder01** [comment]
Prezados amigos, agradeço muito pela atenção de sempre, consegui resolver o problema da seguinte forma:
**Exclui a informação, salvei, limpei cache e histórico, abri o sistema e reinseri, apareceu normalmente.**

Obrigado pela atenção de sempre !!

**Comment by Welder01** [comment]
Uma dúvida, o QRCODE é visível em que status da OS?

**Comment by Pr3d4dor** [comment]
@Welder01 É visível em todos os status de OS.

**Comment by Welder01** [comment]
> @Welder01 É visível em todos os status de OS.

Obrigado meu amigo pela atenção de sempre !

Mas, aqui para mim, só é visível no status **FATURADO**, nos demais não aparece !
Outra coisa que reparei, foi; quando o cliente imprime a OS, não apresenta o QRCODE PIX também, é normal isso ?

**Comment by Welder01** [comment]
Prezados, boa tarde, como consegui resolver a questão, encerro a OS por aqui agradecendo muito a atenção de todos.

Abrirei uma outra para a ultima solicitação acima, assim outras pessoas que passam pelo mesmo problema possam encontrar facilmente a  ISSUE.

Att:
Welder

**Comment by Pr3d4dor** [comment]
@Welder01 Conseguiu identificar o problema?

**Comment by Welder01** [comment]
@Pr3d4dor , prezado amigo, havia fechado a ISSUE para abrir uma específica, assim servindo de ajuda para os demais além de esta facilmente visível à todos !

Mas, não me reservo a isso, esteja a vontade para me ajudar nesta mesmo, caso seja oportuno e conveniente !!!

Diante do exposto, digo que o problema do QRCODE PIX na impressão A4 resolvi sim mas não estou conseguindo fazer com que o próprio cliente no momento da impressão através do log-in dele imprima o código junto da OS.

Saberia me ajudar com isso ?

Novamente obrigado !!

**Comment by Pr3d4dor** [comment]
@Welder01 Na impressão de OS/Venda no painel do cliente não foi adicionado o QRCODE PIX, teria que ser adicionado e lançado nova versão do mapos.

**Comment by Welder01** [comment]
> @Welder01 Na impressão de OS/Venda no painel do cliente não foi adicionado o QRCODE PIX, teria que ser adicionado e lançado nova versão do mapos.

Meu amigo, boa tarde !!

eu inseri na funcion os parâmetros e depois informei o arquivo de impressão térmica. consegui resolver dessa forma !
AGORA IMPRIME NA TERMICA.

o mesmo processo eu fiz em:
VENDA
COMPRAS
IMPRIMI OS "CONECTE"
VISUALIZAR OS "CONECTE"

Se me permite, esperando eu não ultrapassar os limites, fomentar contigo requisições na atualizações futuras:
1 - visualizar e imprimir QRCODE PIX pelo Usuário ""CONECTE"".
2 - Ativar e desativar anexo de clientes "checkbox" true or false.

seriam considerações, espero que veja com bons olhos, conte comigo!!

**Comment by willph** [comment]
Doações

Gosta do MapOS e gostaria de contribuir financeiramente para o projeto?
Doações podem ser realizadas nos links:

Vakinha
http://vaka.me/1625349

Mensal
https://www.catarse.me/mapos

Única/Mensal/Anual
https://donorbox.org/mapos


Atenciosamente, Equipe MAPOS.

**Comment by Welder01** [comment]
Meus amigos, por hora, informo que consegui inserir o QRCODE na Impressão Térmica.

Agradeço a atenção verdadeira e dedicada !

Na oportunidade , pergunto, qual o diretório de edição de e-mails ?
