### ISSUE TITLE
Os faturada não aparece na relação e não permite exclusão

### ISSUE THREAD

**Issue by Welder01** [RamonSilva20/mapos#1293]
** Descreva o bug **
Ao fatorar uma OS, ela não aparece na relação de os, apenas na busca singular. Também não é possível excluir a respectiva OS faturada. 

Ex: Caso alguém fature uma OS equivocadamente seria impossível corrigir o erro.

Acredito que deve ser algo relacionado ao filtro.

Como posso resolver, obrigado pela atenção !

**Comment by Pr3d4dor** [comment]
@Welder01 Sobre não aparecer já foi corrigido, porém sobre excluir OS faturada eu não concordo, mesmo que esteja errado o correto é fazer a adequação nos lançamentos financeiros, pois o correto é manter o histórico.
