### ISSUE TITLE
https://br.000webhost.com/

### ISSUE THREAD

**Issue by LucassCM** [RamonSilva20/mapos#1295]
Nas versões antigas conseguia hospedar gratuitamente no https://br.000webhost.com/ nesta ultima versão anda tem algum jeito de fazer ou somente m pagos mesmo ?

**Comment by willph** [comment]
> Nas versões antigas conseguia hospedar gratuitamente no https://br.000webhost.com/ nesta ultima versão anda tem algum jeito de fazer ou somente m pagos mesmo ?

Tem sim.

Mas precisa baixar as dependências localmente e depois subir a pasta vendor para a o mesmo local na hospedagem.

**Comment by jsfachini** [comment]
Já tentei hospedar 2x no https://br.000webhost.com/ e em poucas horas bloqueiam o login e o sistema fica off.

**Comment by LucassCM** [comment]
> Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.

O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/, me bloquearam

**Comment by LucassCM** [comment]
> > Nas versões antigas herdadas gratuitamente no https://br.000webhost.com/ nesta última versão e tem algum jeito de fazer somente m pagos mesmo?
> 
> Tem sim.
> 
> Mas precisa baixar as dependências localmente e depois subir um vendedor de macarrão para ao mesmo local na hospedagem.

Obrigado acho melhor hospedar localmente e para acessar remotamente utilizar o DynDNS já que o meu IP não é fixo, já que o https://br.000webhost.com/ esta bloqueando a conta quando hospedo o sistema nele

**Comment by jsfachini** [comment]
> > Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.
> 
> O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/, me bloquearam

Uso localmente também, mas fiz pra um cliente no host, lá não dá, Block direto.

**Comment by willph** [comment]
> 
> 
> > > Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.
> > 
> > 
> > O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/, me bloquearam
> 
> Uso localmente também, mas fiz pra um cliente no host, lá não dá, Block direto.

Testa nessa pra vê se é melhor https://infinityfree.net/

**Comment by jsfachini** [comment]
> > > > Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.
> > > 
> > > 
> > > O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/, me bloquearam
> > 
> > 
> > Uso localmente também, mas fiz pra um cliente no host, lá não dá, Block direto.
> 
> Testa nessa pra vê se é melhor https://infinityfree.net/

Testarei, obrigado.

**Comment by ylivebr** [comment]
> > Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.
> 
> O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/, me bloquearam

Olá, acho que te bloquearam por atingir o limite de banda, tenta nesse https://www.heliohost.org/ ele não tem limite

**Comment by LucassCM** [comment]
> > > Já tentei hospedar 2x no https://br.000webhost.com/ e em horas bloqueiam o login e o sistema fica off.
> > 
> > 
> > O meu fiquei fuçando Ontem e do nada perdi o acesso quando estava quase conseguindo, agora não consigo logar no https://br.000webhost.com/ , me bloquearam
> 
> Olá, acho que te bloquearam por atingir o limite de banda, tente nesse https://www.heliohost.org/ ele não tem limite

Eles bloqueiam por alegarem que para Phishing

**Comment by neofln** [comment]
Essas hospedagens gratuitas de hoje em dia são uma piada, muito antigamente funcionavam maravilhosamente bem, atualmente não dá pra fazer nada com elas, a incomodação é tão grande que não compensa.
Além de não funcionar, depois de cadastrar numa gratuita dessas aí recebi mensagem do chrome que minha senha tinha vazado pra trocar imediatamente, e nunca mais parei de receber e-mails de tentativa de golpe.
Acabei assinando a hostinger pra hospedar meu mapos, e achei o custo benefício bem interessante, recomendo.

**Comment by fapernas** [comment]
> Nas versões antigas conseguia hospedar gratuitamente no https://br.000webhost.com/ nesta ultima versão anda tem algum jeito de fazer ou somente m pagos mesmo ?

Consegui hospedar no InfinityFree, veja lá. Tem um vídeo online no YT com a explicação exata.
Tive a conta bloqueada por conta de um PDF, pedi pra remover e deu certo.
Espero que tenha êxito.
Fabio.
