### ISSUE TITLE
NAO CONSEGUE IMPRIMIR A4 COM PRODUTO ADICIONADO

### ISSUE THREAD

**Issue by dawis2021** [RamonSilva20/mapos#1297]
AO ADICIONAR ALGUM PRODUTO OU SERVIÇO NA OS NAO CONSEGUE IMPRIMIR APRESENTA A PAGINA A SEGUIR, SE EU REMOVER OS ITEMS REDIRECIONA NORMALMENTE PARA IMPRESSÃO.

![ERRO090321](https://user-images.githubusercontent.com/79979756/110539271-ca121600-8103-11eb-97b2-a0ff5665bb6a.png)

GRATO.

**Comment by Pr3d4dor** [comment]
@dawis2021 É necessário preencher todas as informações em Configurações >> Emitente, no seu caso faltou a cidade.

**Comment by dawis2021** [comment]
Bravo!
Problema solucionado.

**Comment by willph** [comment]
Doações

Gosta do MapOS e gostaria de contribuir financeiramente para o projeto?
Compartilhe com os amigos nas redes sociais. 

Doações podem ser realizadas nos links:

Vakinha
http://vaka.me/1625349

Mensal
https://www.catarse.me/mapos

Única/Mensal/Anual
https://donorbox.org/mapos

Atenciosamente, Equipe MAPOS.
