### ISSUE TITLE
adicionar no cadastro do cliente uma aba para cadastrar equipamentos e numero de serie 

### ISSUE THREAD

**Issue by jonyslash** [RamonSilva20/mapos#1299]
** Descreva a solução que você deseja **
Gostaria da inclusão de um campo no cadastro do cliente onde permitisse cadastrar os equipamentos que este cliente tem e tmb o numero de serie do equipamento, sem restrições de quantidade de equipamentos.
sendo assim na hora de abrir uma O.S vc consegue escolher no cadastro do cliente para qual equipamento será prestado o serviço.

**Comment by Pr3d4dor** [comment]
@jonyslash Esse feature já foi pedida, obrigado pela sugestão.
