### ISSUE TITLE
Adicionar campos os

### ISSUE THREAD

**Issue by gugatxr** [RamonSilva20/mapos#13]
Sugestão do @hardbrasil.
Trabalho com Assistência ha anos, usei diversos sistemas. Acredito Muito no Map os mas as buscas para encontrar na Oficina os aparelhos ficam meio fracas as vezes por falta de campos e filtros, exemplos:

Cadastro:

Tipo de Aparelho:  (Onde se coloca, computador, Notebook, DVD Player, Impressora, Air Frier, Liquidificador etc...)

Marca: ( CCE, Phillips, AOC, LG, Samsung, Cadence, Canon etc..)

Modelo: ( Modelo de acordo com o fabricante numerico, alfanumerico ou outro)

* Isso é indispensável em uma oficina, o sujeito liga mas não sabe a os mas sabe marca e modelo, você pesquisar direto pelo nome do cliente número de série tipo do aparelho data de entrada estas coisas.

* Muitos dos sistemas também utilizam de campos de multipla escolha onde já se marca o que deseja exemplo marca do aparelho, tipo, defeito.

Cadastra-se no BD estes dados e depois é só escolher e acho que vcs dizem vincular me perdoem se estiver errado.

Quando da os já impressa não saem os dados de contato do cliente.

Seria bom inserir também um campo Box ou Prateleira onde saberia em qual prateleira o aparelho se encontra.

**Comment by hardbrasil** [comment]
Seria interessante se o usuário pudesse cadastrar marcas, modelos, tipos, defeitos diretamente pelo sistema salvando no BD mysql.





Att;






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Seg, 06 Fev 2017 10:22:36 -0200 Gus &lt;notifications@github.com&gt; wrote ----




Sugestão do @hardbrasil.

 Trabalho com Assistência ha anos, usei diversos sistemas. Acredito Muito no Map os mas as buscas para encontrar na Oficina os aparelhos ficam meio fracas as vezes por falta de campos e filtros, exemplos:


Cadastro:

Tipo de Aparelho: (Onde se coloca, computador, Notebook, DVD Player, Impressora, Air Frier, Liquidificador etc...)

Marca: ( CCE, Phillips, AOC, LG, Samsung, Cadence, Canon etc..)

Modelo: ( Modelo de acordo com o fabricante numerico, alfanumerico ou outro)

Isso é indispensável em uma oficina, o sujeito liga mas não sabe a os mas sabe marca e modelo, você pesquisar direto pelo nome do cliente número de série tipo do aparelho data de entrada estas coisas.


Muitos dos sistemas também utilizam de campos de multipla escolha onde já se marca o que deseja exemplo marca do aparelho, tipo, defeito.


Cadastra-se no BD estes dados e depois é só escolher e acho que vcs dizem vincular me perdoem se estiver errado.

Quando da os já impressa não saem os dados de contato do cliente.

Seria bom inserir também um campo Box ou Prateleira onde saberia em qual prateleira o aparelho se encontra.

**Comment by TecSecret** [comment]
Conforme consta no site: http://sistemamapos.esy.es/ o projeto foi descontinuado.

Mas nós da TecSecret vamos manter o projeto ativo com uma equipe focada em sempre proporcionar atualizações constantes e correção de bugs, inclusive no suporte a instalações existentes.

Acesse o novo Git do Projeto: https://github.com/TecSecret/TS-Assistencia

**Comment by P4R4G0N** [comment]
Primeiramente, parabéns!
Gostaria de acrescentar a seguinte sugestão:
Cadastro de equipamento, de preferencia com campos customizáveis e upload de imagens, para ser usado em ordens de serviço. Assim um equipamento cadastrado já poderia ser relacionado a um cliente e utilizado várias vezes em ordens de serviço. 
Obrigado.
