### ISSUE TITLE
Configuração para rodar com PHP atual + XAMPP V3.2.2

### ISSUE THREAD

**Issue by KFBSolucoes** [RamonSilva20/mapos#130]
Estou com a ultima versão do Xamp + PHP, porém não posso alterar pois ja tenho alguns projetos em andamento, o problema é que não loga, sempre dá erro de usuario e senha.
Nem alterando a senha no bd deu certo, como faço?
//Tem como adicionar outra criptografia ou remover a mcrypt e deixar sem?

**Comment by PH7-Jack** [comment]
Já tentei vários modos, mas não deu também, porém sou brasileiro kkkkkkkkkkkkk usa a malandragem, no botão de login você coloca um onclick redirecionando pro index, ai no primeiro login não vai dar certo entre aspas, por que dá certo, mas não redireciona, depois é só clicar em login de novo.

**Comment by KFBSolucoes** [comment]
Precisa remover a criptografia ou apenas isso?

**Comment by Pr3d4dor** [comment]
Eu tive um problema parecido e aparentemente é causado pela criptografia que é feita por meio da extensão mcrypt.

O que deve ser feito é instalar e verificar se essa extensão está ativada no PHP de vocês.

Essa extensão já é deprecated e foi removida PHP 7.2. 

O ideal em relação ao repositório seria trocar a criptografia para uma mais atual (por exemplo bcrypt).

Mesmo com essa extensão sendo removida no PHP 7.2 é possível usá-la segundo o tutorial:
https://stackoverflow.com/questions/48275494/issue-in-installing-php7-2-mcrypt

**Comment by KokeroO** [comment]
Altere você mesmo o a criptografia de login em Application/controllers/mapos.php. Vai estar na função verificarLogin. E melhor do que ter mais uma configuração para instalar a aplicação.
Use password_hash.
