### ISSUE TITLE
Documento fiscal emitido

### ISSUE THREAD

**Issue by imc78** [RamonSilva20/mapos#1300]
Boa noite. Onde insiro o valor de documento fiscal emitido para impressão em Relatórios de receitas brutas MEI

**Comment by Pr3d4dor** [comment]
@imc78 Você se refere à esse campo?

https://github.com/RamonSilva20/mapos/issues/1310

**Comment by Marke2018** [comment]
Boa tarde, isso mesmo Pr3d4dor. Obrigado!
