### ISSUE TITLE
Bug dos botões

### ISSUE THREAD

**Issue by xdnl0506** [RamonSilva20/mapos#1301]
Estou com um bug nos botões, não está aparecendo imagens e eles ficam como uma barra, não consigo identificar o que é o que 
Estou na versão 4.31.1
![image](https://user-images.githubusercontent.com/80452032/110826918-4fb4d380-8274-11eb-88dd-4c19182a6f9e.png)

**Comment by willph** [comment]
Isso é os ícones que não está aparecendo. Terá que editar e colocar. 

Versão modificada?

**Comment by xdnl0506** [comment]
Não, baixei a versão aqui mesmo e fiz a instalação normal, mas não manjo nada pra fazer a edição kk

**Comment by willph** [comment]
> Não, baixei a versão aqui mesmo e fiz a instalação normal, mas não manjo nada pra fazer a edição kk

Qual é esse menu?

**Comment by willph** [comment]
Ordens de Serviço?

**Comment by willph** [comment]
Qual versão está usando?

**Comment by xdnl0506** [comment]
A versão 4.31.1 e sim é o menu de O.S, mas no de vendas também tem o mesmo bug, todos os ícones dos botões de ações não tem, os outros em sua maioria está normal 
![image](https://user-images.githubusercontent.com/80452032/110832104-b2f53480-8279-11eb-9b6b-019b382694ff.png)

![image](https://user-images.githubusercontent.com/80452032/110831990-9658fc80-8279-11eb-8c94-56854533d235.png)
![image](https://user-images.githubusercontent.com/80452032/110832010-9bb64700-8279-11eb-83a3-571637cd166b.png)

**Comment by willph** [comment]
> A versão 4.31.1 e sim é o menu de O.S, mas no de vendas também tem o mesmo bug, todos os ícones dos botões de ações não tem, os outros em sua maioria está normal
> ![image](https://user-images.githubusercontent.com/80452032/110832104-b2f53480-8279-11eb-9b6b-019b382694ff.png)
> 
> ![image](https://user-images.githubusercontent.com/80452032/110831990-9658fc80-8279-11eb-8c94-56854533d235.png)
> ![image](https://user-images.githubusercontent.com/80452032/110832010-9bb64700-8279-11eb-83a3-571637cd166b.png)

Aqui está normal. 

Localhost ou hospedagem?

**Comment by xdnl0506** [comment]
> > A versão 4.31.1 e sim é o menu de O.S, mas no de vendas também tem o mesmo bug, todos os ícones dos botões de ações não tem, os outros em sua maioria está normal
> > ![image](https://user-images.githubusercontent.com/80452032/110832104-b2f53480-8279-11eb-9b6b-019b382694ff.png)
> > ![image](https://user-images.githubusercontent.com/80452032/110831990-9658fc80-8279-11eb-8c94-56854533d235.png)
> > ![image](https://user-images.githubusercontent.com/80452032/110832010-9bb64700-8279-11eb-83a3-571637cd166b.png)
> 
> Aqui está normal.
> 
> Localhost ou hospedagem?


localhost 
![image](https://user-images.githubusercontent.com/80452032/110832614-4464a680-827a-11eb-92da-2594296644c9.png)

**Comment by xdnl0506** [comment]
> > > A versão 4.31.1 e sim é o menu de O.S, mas no de vendas também tem o mesmo bug, todos os ícones dos botões de ações não tem, os outros em sua maioria está normal
> > > ![image](https://user-images.githubusercontent.com/80452032/110832104-b2f53480-8279-11eb-9b6b-019b382694ff.png)
> > > ![image](https://user-images.githubusercontent.com/80452032/110831990-9658fc80-8279-11eb-8c94-56854533d235.png)
> > > ![image](https://user-images.githubusercontent.com/80452032/110832010-9bb64700-8279-11eb-83a3-571637cd166b.png)
> > 
> > 
> > Aqui está normal.
> > Localhost ou hospedagem?
> 
> localhost
> ![image](https://user-images.githubusercontent.com/80452032/110832614-4464a680-827a-11eb-92da-2594296644c9.png)

Já reinstalei umas 3x, excluindo o xampp, git, composer, tudo, mas continua

**Comment by willph** [comment]
Veja se essa linha esta no arquivo `topo.php` fica em `\application\views\tema`

`<link href="<?= base_url(); ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet" />`

**Comment by willph** [comment]
E se tem essa pasta ai no seu `assets\font-awesome\`

**font-awesome** é responsável pelo ícones.

**Comment by xdnl0506** [comment]
![image](https://user-images.githubusercontent.com/80452032/110833505-45e29e80-827b-11eb-9cb7-08ca30736041.png)
![image](https://user-images.githubusercontent.com/80452032/110833598-601c7c80-827b-11eb-90df-643598c91324.png)

**Comment by willph** [comment]
Limpou Cache do navegador?

Poderia testar em outro navegador?

**Comment by xdnl0506** [comment]
Limpeza do cache resolveu, valeu!! Desculpa a noobice haha
![image](https://user-images.githubusercontent.com/80452032/110834198-05cfeb80-827c-11eb-9845-2b48f9e12c87.png)

**Comment by willph** [comment]
Tranquilo, acontece. 

Se possível peço que compartilhe nas suas redes sociais os links, isso ajudará a manter o projeto e da um UP.

Doações podem ser realizadas nos links:

Única 
http://vaka.me/1625349

Mensal
https://www.catarse.me/mapos

Única/Mensal/Anual
https://donorbox.org/mapos

**Comment by willph** [comment]
Uma ótima tarde.
Qualquer coisa só manda uma nova mensagem. 

Atenciosamente, Equipe MapOs
