### ISSUE TITLE
Acesso Remoto

### ISSUE THREAD

**Issue by LucassCM** [RamonSilva20/mapos#1302]
Estou com problemas para acessar remotamente o MAPS alguém poderia dar uma luz

IP que fixei no meu computador: 10.0.0.18
Meu DDNS: mti.serveirc.com

Redirecionamento:
![2021-03-12](https://user-images.githubusercontent.com/80243143/110901093-875a6480-82e2-11eb-9280-769d57de10af.png)

XAMPP Control Panel
![Porta](https://user-images.githubusercontent.com/80243143/110901238-c688b580-82e2-11eb-8bfb-57a5e5888f64.png)

Httpd.Conf
![3000](https://user-images.githubusercontent.com/80243143/110901359-fe8ff880-82e2-11eb-8585-b6d6e8849067.png)
![Captura de tela 2021-03-12 032203](https://user-images.githubusercontent.com/80243143/110901363-ff288f00-82e2-11eb-854c-7f0a0e1f762e.png)

Config.PHP
![Config](https://user-images.githubusercontent.com/80243143/110901408-0c457e00-82e3-11eb-8cc9-4d87863938dc.png)

**Comment by Pr3d4dor** [comment]
O $URL_ATUAL precisa ser:
```
$URL_ATUAL = sprintf("http://%s", $_SERVER['HTTP_HOST']);
```

E parece que o http://mti.serveir.com/mti está com uma barra "|" a mais no final.

**Comment by LucassCM** [comment]
Concertei mais ainda não vai, não abre nem o xampp com o DDNS, não sei se esta faltando alguma configuração ou se tenho que utilizar outra porta


$URL_ATUAL = sprintf("http://%s", $_SERVER['HTTP_HOST']);

if($URL_ATUAL == 'http://mti.serveirc.com')
{
$config['base_url'] = 'http://mti.serveirc.com:3000/mti';
}
else
{
$config['base_url'] = 'http://10.0.0.18:3000/mti';
}

**Comment by LucassCM** [comment]
> O $ URL_ATUAL precisa ser:
> 
> ```
> $URL_ATUAL = sprintf("http://%s", $_SERVER['HTTP_HOST']);
> ```
> 
> E parece que o http://mti.serveir.com/mti está com uma barra "|" a mais no final.

Concertei mais ainda não vai, não abre nem o xampp com o DDNS, não sei se esta faltando alguma configuração ou se tenho que utilizar outra porta

$ URL_ATUAL = sprintf ("http: //% s", $ _SERVER ['HTTP_HOST']);

if ($ URL_ATUAL == ' http://mti.serveirc.com ')
{
$ config ['base_url'] = ' http://mti.serveirc.com:3000/mti ';
}
else
{
$ config ['base_url'] = ' http://10.0.0.18:3000/mti ';
}

**Comment by LucassCM** [comment]
> O $ URL_ATUAL precisa ser:
> 
> ```
> $URL_ATUAL = sprintf("http://%s", $_SERVER['HTTP_HOST']);
> ```
> 
> E parece que o http://mti.serveir.com/mti está com uma barra "|" a mais no final.

Concertei mais ainda não vai, não abre nem o xampp com o DDNS, não sei se esta faltando alguma configuração ou se tenho que utilizar outra porta

$ URL_ATUAL = sprintf ("http: //% s", $ _SERVER ['HTTP_HOST']);

if ($ URL_ATUAL == ' http://mti.serveirc.com ')
{
$ config ['base_url'] = ' http://mti.serveirc.com:3000/mti ';
}
else
{
$ config ['base_url'] = ' http://10.0.0.18:3000/mti ';
}

**Comment by willph** [comment]
> > O $ URL_ATUAL precisa ser:
> > ```
> > $URL_ATUAL = sprintf("http://%s", $_SERVER['HTTP_HOST']);
> > ```
> > 
> > 
> > E parece que o http://mti.serveir.com/mti está com uma barra "|" a mais no final.
> 
> Concertei mais ainda não vai, não abre nem o xampp com o DDNS, não sei se esta faltando alguma configuração ou se tenho que utilizar outra porta
> 
> $ URL_ATUAL = sprintf ("http: //% s", $ _SERVER ['HTTP_HOST']);
> 
> if ($ URL_ATUAL == ' http://mti.serveirc.com ')
> {
> $ config ['base_url'] = ' http://mti.serveirc.com:3000/mti ';
> }
> else
> {
> $ config ['base_url'] = ' http://10.0.0.18:3000/mti ';
> }

Verificar o IP da sua máquina. 

https://www.myip.com/

Aí em `Your IP address is:` vai está o IP que deve usar.

Fora isso você precisa configura o roteador, para liberar acesso e o firewall da máquina também.
