### ISSUE TITLE
Arquivo de BKP zerado

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1303]
Bom dia, estou com problema ao gerar o backup pelo sistema, o arquivo exporta zerado.
banco atualizado, mapos atualizado, xamp atualizadov4.31.1

Abrindo o sql com editor exibe esse conteúdo: 
SET foreign_key_checks = 0;
SET foreign_key_checks = 1;

**Comment by jsfachini** [comment]
Resolvido

**Comment by willph** [comment]
Que bom que resolveu.



> Resolvido
