### ISSUE TITLE
Pesquisa

### ISSUE THREAD

**Issue by Rennancbr** [RamonSilva20/mapos#1304]
** Descreva o bug **
Quando se realiza uma pesquisa de produtos/serviços identicos, só apresenta apenas 05 informações. Sendo que existem muitos outros com o mesmo nome. Tipo: Tenho 10 cores de Cabo, quando jogo na pesquisa só lista 5.

Se alguém puder me dizer em qual arquivo tenho que alterar pra que quando for realizado pesquisa, o sistema liste todos.
Overflow

**Comment by Pr3d4dor** [comment]
@Rennancbr Isso não é um bug, ele retorna somente 5 serviços mesmo.

Procure pelas funções de "autocomplete"
