### ISSUE TITLE
Enviar venda por email

### ISSUE THREAD

**Issue by luizejessica** [RamonSilva20/mapos#1305]
Ao gerar uma venda é muito importante ter a opção de enviar email.

**Comment by Pr3d4dor** [comment]
@luizejessica As funções de email atuomático que já existe no mapos não lhe atendem?

**Comment by luizejessica** [comment]
Preciso enviar a venda por email, o sistema só envia ordem de serviço

Em seg, 15 de mar de 2021 18:27, Gianluca Bine ***@***.***>
escreveu:
