### ISSUE TITLE
Gerar Orcamento

### ISSUE THREAD

**Issue by luizejessica** [RamonSilva20/mapos#1307]
Na tela de venda deveria ter uma opção de selecionar um tipo - VENDA OU ORÇAMENTO
Onde venda baixaria o estoque e gerar financeiro.
e se for do tipo ORÇAMENTO apenas gravar e não baixar o estoque e não permitir gerar financeiro.

**Comment by Pr3d4dor** [comment]
@luizejessica Obrigado pela sugestão.
