### ISSUE TITLE
RECEBIMENTO COM MAIS DE UMA FORMA DE PAGAMENTO

### ISSUE THREAD

**Issue by luizejessica** [RamonSilva20/mapos#1308]
NA VENDA E ORDEM DE SERVIÇO É DE EXTREMA IMPORTANCIA TER DUAS FORMAS DE RECEBIMENTO.

EX. O CLIENTE FAZ UM SERVIÇO OU UMA COMPRA E PAGA UMA PARTE EM DINHEIRO E RESTANTE QUER EM BOLETO OU OUTRA FORMA E NO SISTEMA TEM ESSA DEPENDENCIA.

**Comment by hoshikawakun** [comment]
Eu aki pego muito desse jeito, Parte no debito e outra em outro card no credito, Cartão e $$, Pix e cartão e por ai vai, eu acabo selecionando ou $$ ou cartão quando recebo de 2 formas diferentes

**Comment by skadbr** [comment]
Daria para faturar mais de 1x cada um com forma de pgto diferente, e controlar criando status faturado parcial ou faturado total.
