### ISSUE TITLE
Problema ao cadastrar usuário 'Ocorreu um erro'

### ISSUE THREAD

**Issue by Peffmb** [RamonSilva20/mapos#1309]
Aonde tentar cadastrar um usuário novo, seja qualquer um, ou alterar outro, me da este erro na tela:
![image](https://user-images.githubusercontent.com/80719576/111219597-fe2f8000-85b6-11eb-93a7-dffdd22edcd6.png)

Tentei mexer para ver mas não obtive êxito. 

Aguardo uma ajuda, obrigado 👍

**Comment by Pr3d4dor** [comment]
@Peffmb Consegue verificar se seu banco de dados está atualizado?
