### ISSUE TITLE
Falta informação em receitas Brutas-MEI do valor da nota emitida

### ISSUE THREAD

**Issue by Marke2018** [RamonSilva20/mapos#1310]
Ao clicar no menu Relatórios e rolar até Receitas Brutas - MEI, extraindo relatório não encontro a informação de adicionar, um valor de nota fiscal.

![image](https://user-images.githubusercontent.com/80719064/111220318-ca088f00-85b7-11eb-9e86-bc5a3b9e67b3.png)

**Comment by Pr3d4dor** [comment]
@Marke2018 Como não existe controle de notas no sistema, ele considera que todos são sem nota fiscal. Vou pensar em algo para deixar isso editável.
