### ISSUE TITLE
Melhorias (Sugestões)

### ISSUE THREAD

**Issue by RafaelMG2019** [RamonSilva20/mapos#1311]
Boa tarde, primeiramente parabéns pelo sistema, muito bom e pratico, passando aqui para dar algumas sugestões!
Separar Fornecedor de Cliente
Adicionar fornecedor e observações em produtos 
Adicionar Leitura do Código de Barra na venda, através de leitores 
Adicionar emissão de promissória 
Adicionar forma de pagamento, cartão, dinheiro, promissória, etc. (Em vendas e OS)
Adicionar alerta de aniversário de clientes, e opção para enviar mensagem de saudação para eles 
Adicionar opção de entrar com um saldo inicial ou de iniciar caixa .
Adicionar atalho de cadastro de clientes em os, vendas e outros que necessitam de cadastro.
Adicionar opção de orçamento para vendas 
Opção de Troca e ou devolução 
Seria muito complicado inserirmos esta feature nas próximas versões?

**Comment by Pr3d4dor** [comment]
@RafaelMG2019 São várias features, e algumas delas podem parecer simples mas não são.

Eu agradeço a sugestão, podemos no futuro implementar algumas delas ou até todas, mas levaria um tempo considerável.

**Comment by RafaelMG2019** [comment]
> @RafaelMG2019 São várias features, e algumas delas podem parecer simples mas não são.
> 
> Eu agradeço a sugestão, podemos no futuro implementar algumas delas ou até todas, mas levaria um tempo considerável.

Entendo, nesse caso e aos poucos para ir implementando, espero ter ajudado com a sugestão!
