### ISSUE TITLE
Problema ao acessar os lançamentos na aba financeiro

### ISSUE THREAD

**Issue by jonyslash** [RamonSilva20/mapos#1312]
** Descreva o bug **
Ao tentar acessar os lançamentos na aba financeiro ele entra na tela de erro

![image](https://user-images.githubusercontent.com/80428320/111400429-1631fd00-86a6-11eb-9f7c-f90278704664.png)

**Comment by willph** [comment]
> ** Descreva o bug **
> Ao tentar acessar os lançamentos na aba financeiro ele entra na tela de erro
> 
> ![image](https://user-images.githubusercontent.com/80428320/111400429-1631fd00-86a6-11eb-9f7c-f90278704664.png)

Instalação feita do zero ou atualização?

**Comment by Pr3d4dor** [comment]
@jonyslash Verifique se seu banco de dados está atualizado.

**Comment by jonyslash** [comment]
Verdade @Pr3d4dor, apos a atualização do Mapos ficou faltanto atualizar o banco de dados! mas ja esta resolvido! muito obrigado amigos por compartilhar todo esse conhecimento conosco!
