### ISSUE TITLE
Erro em atualizações de cobrança usando sandbox mercado pago

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1313]
Bom dia amigos,

Estou encontrando problemas em qualquer atualização em cobranças. Não atualiza, não exclui e não cancela.

O gateway é o mercado pago e método sandbox. Ainda não coloquei em produção.

Alguém pode me dar uma luz por favor?

**Comment by Pr3d4dor** [comment]
@Lucios1989 Configurou certo as chaves?
