### ISSUE TITLE
Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

### ISSUE THREAD

**Issue by evertompb** [RamonSilva20/mapos#1314]
Instalei o mapOS via Docker no Debian 10
a instalação ocorreu bem,
Fiz a instalação do mapOS pelo navegador,
quando pediu para ir para a Tela de Login, aparece isso
"Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada."
usei o comando sugerido: docker-compose up --force-recreate

alguém pode me ajudar?

**Comment by Pr3d4dor** [comment]
@evertompb Consegue verificar se ele instalou as dependencias do composer?

**Comment by evertompb** [comment]
que eu tenha prestado atenção, não deu nenhum erro ao gerar no docker-compose.

**Comment by evertompb** [comment]
composer      | Your lock file does not contain a compatible set of packages. Please run composer update.
composer      | 
composer      |   Problem 1
composer      |     - chillerlan/php-qrcode is locked to version 3.4.0 and an update of this package was not requested.
composer      |     - chillerlan/php-qrcode 3.4.0 requires php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
composer      |   Problem 2
composer      |     - chillerlan/php-settings-container is locked to version 1.2.1 and an update of this package was not requested.
composer      |     - chillerlan/php-settings-container 1.2.1 requires php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
composer      |   Problem 3
composer      |     - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
composer      |     - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
composer      |   Problem 4
composer      |     - piggly/php-pix is locked to version 1.1.2 and an update of this package was not requested.
composer      |     - piggly/php-pix 1.1.2 requires php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
composer      | 
composer exited with code 2

**Comment by Pr3d4dor** [comment]
@evertompb Vai ser necessário fixar a versão do PHP para a versão 7.4, quando foi implementado o dockerfile, a última versão era a 7.4, mas agora também temos a última que é a 8.0 que não é compatível.

Vá nesse arquivo e troque a linha:
```
FROM nanoninja/php-fpm:latest
```

Por:
```
FROM nanoninja/php-fpm:7.4
```

**Comment by ZanzouShio** [comment]
> @evertompb Vai ser necessário fixar a versão do PHP para a versão 7.4, quando foi implementado o dockerfile, a última versão era a 7.4, mas agora também temos a última que é a 8.0 que não é compatível.
> 
> Vá nesse arquivo e troque a linha:
> 
> ```
> FROM nanoninja/php-fpm:latest
> ```
> 
> Por:
> 
> ```
> FROM nanoninja/php-fpm:7.4
> ```

no meu caso, mesmo trocando, ainda obtive o mesmo erro, sou novo no docker, e aparece justamente a mesma descrição de erro.

**Comment by ZanzouShio** [comment]
> @evertompb Vai ser necessário fixar a versão do PHP para a versão 7.4, quando foi implementado o dockerfile, a última versão era a 7.4, mas agora também temos a última que é a 8.0 que não é compatível.
> 
> Vá nesse arquivo e troque a linha:
> 
> ```
> FROM nanoninja/php-fpm:latest
> ```
> 
> Por:
> 
> ```
> FROM nanoninja/php-fpm:7.4
> ```

Na verdade pelo que entendi, o Composer do docker já vem com uma versão do PHP embarcada, essa por sua vez é a versão 8.0.3, eles deixam claro que não tem a intenção de disponibilizar uma imagem com várias versões de PHP, o que fez rodar pra mim foi alterar o command install para command install --ignore-platform-reqs --no-scripts no composer.
