### ISSUE TITLE
Processar O.S faturada

### ISSUE THREAD

**Issue by dawis2021** [RamonSilva20/mapos#1315]
Boa noite, 
Como fazer pra processar a O.S faturada só tenho a opção de visualizar e embaixo gerar pagamento, como fazer para processa-la ou existir uma opção de receber em mãos com lançamento no financeiro automático, ou até mesmo exclui-la.

**Comment by Pr3d4dor** [comment]
@dawis2021 O modo correto de ser usado seria:
- Mudar a OS para o status finalizado.
- Receber o pagamento do cliente;
- Após isso ir na OS e clicar na opção fatura, irá aparecer a modal para indicar como foi pago e também será inserido o valor nos lançamentos financeiros.

Portanto  "Faturado" seria o status final de uma OS.
