### ISSUE TITLE
your php version (8.0.2) does not satisfy that requirement.

### ISSUE THREAD

**Issue by oaksoft12** [RamonSilva20/mapos#1316]
![Screenshot_20210322-190721_Termux](https://user-images.githubusercontent.com/35842155/112069447-34827780-8b42-11eb-8b1c-9ce3569553f3.jpg)

**Comment by willph** [comment]
Usa a versão do php 7.4 pode ser 7.4.11 vai funcionar tranquilo.

**Comment by willph** [comment]
Php na versão 8 ainda não tem suporte.

**Comment by SpartanT269** [comment]
Tá bom irmão, agradeço, agora surgiu outra coisa, talvez seja meu serviço de hospedagem, mas ao acessar o instaldor aparece o erro 403 sobre redirecionamento excesivo
