### ISSUE TITLE
Celular erro visualizar os

### ISSUE THREAD

**Issue by rodolfocarlosbji** [RamonSilva20/mapos#1317]
Olá amigos primeiramente da os parabéns ao Ramon pelo script... Amigos estou com erro no celular quando vou visualizar a os da erro na página alguém com mesmo problema ou sabe como resolver ?

**Comment by Pr3d4dor** [comment]
@rodolfocarlosbji Consegue postar imagem do erro ou dar mais detalhes sobre o mesmo?

**Comment by rodolfocarlosbji** [comment]
Sim amigo, estou enviando a tela antes de clicar e logo apos clicar...
o erro quando clica para gerar a OS padrao de imprimir o celular da erro.. 
http://wrsecurity.com.br/erro1.jpeg
http://wrsecurity.com.br/erro2.jpeg

**Comment by rodolfocarlosbji** [comment]
Alguem pode me ajudar?
