### ISSUE TITLE
Email - Corpo do email com caracteres e escritas de forma incorreta

### ISSUE THREAD

**Issue by smilesbh** [RamonSilva20/mapos#1318]
Prezados na versão que estou utilizando Mapos 4.31.1 ao enviar o e-mail para o cliente o e-mail chega com caracteres diferentes e com palavras escritas de forma incorreta.

Isso acontece ao:
1º - Ordens de Serviços
2º - Ver mais detalhes de uma OS
3º - Enviar por E-mail - Entra em fila...e depois envia conforme meu cron.

Ao checar a caixa de correio do destinatário o e-mail apresenta caracteres como "3C/li>" ou palavras como "t�=A9cnico." ou "<=trong>Obs2: " ou em uma frase como "Outros testes só poderão ser=ealizados"

Pensei em verificar a formatação do e-mail para ISO-8859-1 mas aí aumentou erros quanto aos acentos e retornei para UTF-8.

Segue abaixo alguns prints de tela
![image](https://user-images.githubusercontent.com/81257936/112217957-e339bd00-8c01-11eb-91cf-3fa9e790564e.png)
![image](https://user-images.githubusercontent.com/81257936/112218126-23993b00-8c02-11eb-8ffc-ba46dfc84a0f.png)

Estou utilizando Outlook 2016
Sistema Windows 10
Navegado Chrome - ultima versão

Acontece também de não enviar a logo da empresa no topo da mensagem ficando com aquele icone de como a imagem na pode carregar. 
Na tela do sistema o logo aparece perfeitamente. Esta hospedado na locaweb em um dominio compartilhado.
![image](https://user-images.githubusercontent.com/81257936/112218560-9f938300-8c02-11eb-816e-b2ef9192de85.png)

Se voces tiverem a solução para isso, gostaria muito que pudessem me ajudar. O sistema tem sido ótimo e comecei a implementar agora para o envio de mensagens para o cliente, mas ainda estou em fase de testes para pode homologar.
Desde já agradeço à atenção.

**Comment by Pr3d4dor** [comment]
@smilesbh Creio que isso tem a ver com o charset, está sendo usado UTF-8 ou ISO?

**Comment by tecnofreitas** [comment]
Bom dia, pessoal! Estou com esse mesmo problema, alguém descobriu como resolver?
