### ISSUE TITLE
Migração de Banco de Dados

### ISSUE THREAD

**Issue by smigou31** [RamonSilva20/mapos#1320]
Eu atualmente utilizo um sistema, que utiliza Firebird como banco de dados. Seria possível eu migrar esse sistema ?. Assim eu não perderia meus dados de clientes e precisaria cadastrar novamente.

**Comment by Pr3d4dor** [comment]
@smigou31 Você terá que fazer um script para pegar os dados desse banco FireBird e inserir nas tabelas no mapos. As tabelas desse seu outro sistema serão outras. Será necessário fazer um mapeando para pegar das tabelas do Firebird e inserir nas do mapos.

**Comment by smigou31** [comment]
> @smigou31 Você terá que fazer um script para pegar os dados desse banco FireBird e inserir nas tabelas no mapos. As tabelas desse seu outro sistema serão outras. Será necessário fazer um mapeando para pegar das tabelas do Firebird e inserir nas do mapos.

Você teria, um tutorial de como fazer isso ?

**Comment by Pr3d4dor** [comment]
Não tem como fazer um tutorial porque depende do sistema antigo que você usa e quer migrar.
