### ISSUE TITLE
Adicionando hora de emissão de O.S.

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#1322]
Ola, boa noite amigos.
Fiz uma alteracao na linha 55 do imprimirOs.php. Adicionei uma codigo para imprimir tambem a hora de emicao, pois em alguns casos o cliente diz que deixou o equipamento em uma determinada hora do dia quando na verdade foi em outro.  
segue o codigo: 
Antes:  `<?php  echo date('d/m/Y') ?>`

Depois:  `<?php date_default_timezone_set('America/Sao_Paulo'); echo date('d/m/Y \à\s H:i:s'); ?>` 

Inseri uma timezone pois por algum motivo o horario que saia impresso era diferente do Brasil-MG

Acho que vale a pena promover esta alteracao neste sistema. [Obrigado]

![Sem título11](https://user-images.githubusercontent.com/55247088/112545734-54f73f80-8d97-11eb-87a1-e56b76e6f6dc.jpg)

**Comment by Pr3d4dor** [comment]
@fwsund Obrigado pela sugestão.

Se você quiser, pode fazer uma pull request com essa alteração. Se você não conseguir fazer eu posso fazer e depois colocar-lo na lista de contribuidores.

**Comment by fwsund** [comment]
@Pr3d4dor   abri a  pull request  conforme voce me pediu.

**Comment by fwsund** [comment]
emissao com Ç foi foda...kkkk
