### ISSUE TITLE
TypeError: $(...).autocomplete is not a function

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#1324]
Estou fazendo uma alteração de layout no sistema, aplicando o tema [SB-ADMIN](https://startbootstrap.com/theme/sb-admin-2), quando cheguei na tela de vendas, o autoComplete não estava mais funcionando. 
Me apresenta a mensagem de erro `TypeError: $(...).autocomplete is not a function`

Achei que havia outro script em conflito mas, após vários testes, o problema persiste.
Alguém sabe ajudar?

**Comment by RamonSilva20** [comment]
Olá @monutb91, provavelmente está faltando a dependência do autocomplete.

https://jqueryui.com/autocomplete/
