### ISSUE TITLE
Erro na aba meu perfil

### ISSUE THREAD

**Issue by Ironaldo-Silva** [RamonSilva20/mapos#1326]
Tem um bug na aba meu perfil não retorna o perfil e sim uma falha

**Comment by vagnerlaiber** [comment]
Coloca a Foto e os detalhes do Erro, tipo caminho que vc fez

**Comment by Pr3d4dor** [comment]
@Ironaldo-Silva como o @vagnerlaiber precisamos de mais detalhes sobre o erro para poder lhe ajudar
