### ISSUE TITLE
Termo de entrega

### ISSUE THREAD

**Issue by upjet** [RamonSilva20/mapos#1327]
Olá boa tarde, tem como acrescentar a opção de impressão de termo de entrega (tipo quando vc devolve o equipamento o cliente assina para ficar comigo) como um comprovante de que entreguei.

**Comment by Pr3d4dor** [comment]
@upjet É possível, porém não existe esse termo ainda no sistema e teria que ser implementado.

**Comment by upjet** [comment]
entendi, obrigado
