### ISSUE TITLE
novo 4.32.0 mudar status?

### ISSUE THREAD

**Issue by jonathasnp** [RamonSilva20/mapos#1328]
Olá alguem ja conseguiu mudar os status da os na nova versão?  Aberto  
![image](https://user-images.githubusercontent.com/81585844/112882824-d73b7880-90a3-11eb-9226-6fe2f5999d6d.png)

quando eu mudo  buga ,
e fica assim não aparece a cor do status
![image](https://user-images.githubusercontent.com/81585844/112883081-2da8b700-90a4-11eb-9c38-380a00736f1a.png)

nas versões antigas eu mudava e colocava o que eu queria   chamado , manuteção etc , nessa nao consegui e se eu altero alguma ja da erro ,

**Comment by bietez** [comment]
Usa o Sublime Text e usa a função "Find in files" e substitui algum Status que você não usaria normalmente. O sistema `switch case` para definir as cores para cada Status então no momento que você acrescenta um Status que não existe no `case`, é aplicado um `default`

**Comment by jonathasnp** [comment]
Desculpe não entedi muito bem , existe a possibilidade de eu personaliza isso?

**Comment by bietez** [comment]
Existe sim. Por exemplo, quero acrescentar o status "Entregue sem reparo"

1- Parte
No caminho `\application\controllers\Mapos.php` tem uma variavel chamada `$events`. Há nela a função `switch ($os->status) { case ...`.No final, depois de 
`case 'Aguardando peças': 
$cor = #FF7F00;
break;`

voce vai acrescentar depois do break (nesse exemplo):

`case 'Entregue sem reparo':
$cor = #ff6600;
break;`

**Comment by jonathasnp** [comment]
ok vou testa , e Obrigado pela atenção

**Comment by bietez** [comment]
Na real é um serviço bem grande e bateu uma preguiça de detalhar tudinho kkkk mas é basicamente isso. Procure todos os locais onde aparecem os Status da OS e vai acrescentando a informação faltante. De cara posso te adiantar os caminhos para ficar mais facil e a linha onde voce pode começar a ter um rumo

application\controllers\Mapos.php: linha 465
application\views\mapos\configurar.php: linha 204
application\views\mapos\painel.php: linha 89
application\views\os\adicionarOs.php: 64
application\views\os\editarOs.php: 130
application\views\os\os.php: 28 e 112
application\views\relatorios\rel_os.php: 63

**Comment by jonathasnp** [comment]
eu tenho um funcionando na versao 3.14.12  e tudo perconalizado  e outros locais eu fazia isso
![image](https://user-images.githubusercontent.com/81585844/113070590-4e9f0400-9199-11eb-8c72-4f1476059b1d.png)
agora consegui , vlw msm
