### ISSUE TITLE
Instalação e Utilização no WIX

### ISSUE THREAD

**Issue by fomezero** [RamonSilva20/mapos#1329]
Boa noite, 

Procurei no forum e não encontrei, por isso abri esta feature.

Estava utilizando o sistema normalmente, abrindo OS e fazendo todo o controle que eu preciso.
Porem precisei e migrei meu site para o WIX, o site esta hospedado no UOLHOST. Porem o apontamento do domínio esta no WIX, isso é algo que o WIX precisa para poder ser feito o site e colocado em funcionamento.
Quando fiz o site apontando para o WIX, perdi o acesso ao meu sistema, tentei fazer um modificação no apontador do arquivo confg.php linha 42 coloquei 'www44.wixdns.net'.
Minha dúvida é? Para fazer o sistema funcionar on-line, eu preciso colocar qual informação do WIX, já que esta sobre o controle deles.

Desde já peço desculpas ser abri de forma errada esta feature. E se já existe algo no fórum interno.

TMJ

**Comment by Pr3d4dor** [comment]
@fomezero Infelizmente não sei como o WIX funciona porque nunca utilizei.

Como que o WIX funciona?

Ele dá um subdomínio e você utiliza?

**Comment by fomezero** [comment]
Tenho que entrar nas configurações de ZONE DE DNS, de onde esta hospedado o site. O que ele faz é apontar o WIX para onde hospedo o site, ai todas as modificações são feitas no WIX e vai para o site, e  funciona normalmente, o problema que depois que eu apontei para lá não funciona mais meu sistema.
