### ISSUE TITLE
Mudar local dos downloads dos relatórios.

### ISSUE THREAD

**Issue by Loury-Silva** [RamonSilva20/mapos#1330]
Prezados, preciso alterar o caminho da pasta onde atualmente são baixados os relatórios.
Alguém pode me informar qual scripyt PHP devo alterar.

**Comment by Pr3d4dor** [comment]
@Loury-Silva Qual relatório especificamente?

**Comment by Loury-Silva** [comment]
> @Loury-Silva Qual relatório especificamente?

Desculpe a demora para dar retorno. 
Os relatórios, todos, são baixados na pasta downloads, gostaria de determinar um caminho diferente. O relatório que mais emito   é de OS, me ajudando com este será de grande valia. Forte abraço
