### ISSUE TITLE
Caminho para alterações!

### ISSUE THREAD

**Issue by smigou31** [RamonSilva20/mapos#1331]
Boa noite amigos. Esse sistema é muito bom.
Gostaria de saber, aonde que eu altero os nomes dos STATUS das os. 

https://github.com/RamonSilva20/mapos/issues/1280 

Nosso colega, fez uma modificação, que eu achei muito boa, porém queria modificar os nomes ali.

Obrigado, a todos!

**Comment by jonathasnp** [comment]
application\controllers\Mapos.php: linha 465           
application\views\mapos\configurar.php: linha 204      
application\views\mapos\painel.php: linha 89           
application\views\os\adicionarOs.php: 64               
application\views\os\editarOs.php: 130                 
application\views\os\os.php: 28 e 112                                
application\views\relatorios\rel_os.php: 6
