### ISSUE TITLE
Alterar a geração de relatório

### ISSUE THREAD

**Issue by Marke2018** [RamonSilva20/mapos#1334]
Srs, muito boa tarde. Parabéns pelo sistema!
Gostaria de saber como eu faço para alterar a geração de receitas brutas mei subtraindo **receitas** (menos) **despesas**, para obter o meu faturamento bruto do serviço prestado.

` public function receitasBrutasRapid()
    {
        $emitente = $this->db->query("SELECT * FROM emitente LIMIT 1")->row_array();

        $inicio = (new DateTime())->modify('first day of this month');
        $fim = (new DateTime())->modify('last day of this month');

        $query = "
            SELECT
                SUM(valor) total,
                SUM(case when descricao NOT LIKE '%Fatura de OS%' AND descricao NOT LIKE '%Fatura de Venda%' then valor else 0 end) as totalOutros,
                SUM(case when descricao LIKE '%Fatura de OS%' then valor else 0 end) as totalServicos,
                SUM(case when descricao LIKE '%Fatura de Venda%' then valor else 0 end) as totalVendas
            FROM lancamentos
                WHERE baixado = 1
                AND tipo = 'receita'
                AND data_vencimento >= ?
                AND data_vencimento <= ?
        ";

        $relatorio = $this->db->query($query, [$inicio->format('c'), $fim->format('c')])->row_array();
        
        $mercadoriasTotalSemNf = floatval($relatorio['totalVendas']);
        $mercadoriasTotalComNf = 0;
        $mercadoriasTotal = $mercadoriasTotalSemNf + $mercadoriasTotalComNf;

        $industriaTotalSemNf = 0;
        $industriaTotalComNf = 0;
        $industriaTotal = $industriaTotalSemNf + $industriaTotalComNf;

        $servicosTotalSemNf = floatval($relatorio['totalServicos']);
        $servicosTotalComNf = 0;
        $servicosTotal = $servicosTotalSemNf + $servicosTotalComNf;

        $totalMes = $mercadoriasTotal + $industriaTotal = $servicosTotal;

        $periodo = sprintf("%s à %s", $inicio->format('d/m/Y'), $fim->format('d/m/Y'));

        return [
            'cnpj' => $emitente['cnpj'],
            'emitente' => $emitente['nome'],
            'periodo' => $periodo,
            'mercadoriasTotalSemNf' => number_format($mercadoriasTotalSemNf, 2, ',', '.'),
            'mercadoriasTotalComNf' => number_format($mercadoriasTotalComNf, 2, ',', '.'),
            'mercadoriasTotal' => number_format($mercadoriasTotal, 2, ',', '.'),
            'industriaTotalSemNf' => number_format($industriaTotalSemNf, 2, ',', '.'),
            'industriaTotalComNf' => number_format($industriaTotalComNf, 2, ',', '.'),
            'industriaTotal' => number_format($industriaTotal, 2, ',', '.'),
            'servicosTotalSemNf' => number_format($servicosTotalSemNf, 2, ',', '.'),
            'servicosTotalComNf' => number_format($servicosTotalComNf, 2, ',', '.'),
            'servicosTotal' => number_format($servicosTotal, 2, ',', '.'),
            'totalMes' => number_format($totalMes, 2, ',', '.'),
            'localEdata' => sprintf("%s, %s", $emitente['cidade'], (new DateTime())->format('d/m/Y')),
        ];
    }
`

**Comment by Pr3d4dor** [comment]
@Marke2018 Pelo que eu sei no relatório de MEI não deve ser descontado as despesas da receitas. Pois devem ser informados os valores brutos mesmo.

Porém não tenho certeza disso.

**Comment by imc78** [comment]
Boa noite @Pr3d4dor, no meu caso eu lanço o valor de peças gastas em lançamentos. Preciso somar todas as receitas e despesas depois subtrair uma pela outra.
Alterei o código em Relatorios_model.php, mas só está somando as receitas... poderia verificar por favor o que está de errado no código?

` public function receitasBrutasCustom($dataInicial = null, $dataFinal = null)
    {
        $emitente = $this->db->query("SELECT * FROM emitente LIMIT 1")->row_array();

        $query = "
            SELECT
                SUM(valor) total,                
                SUM(case when tipo LIKE '%receita%' then valor else 0 end) - (case when tipo LIKE '%despesa%' then valor else 0 end) as totalServicos
                FROM lancamentos
                WHERE baixado = 1                
                AND data_vencimento >= ?
                AND data_vencimento <= ?
        ";`

**Comment by Pr3d4dor** [comment]
@imc78 Sim, mas como disse anteriormente, o correto não é o valor bruto?

Consultei aqui: https://www.sebrae.com.br/sites/PortalSebrae/ufs/ms/artigos/serie-mei-passo-a-passo-para-elaboracao-do-relatorio-mensal,a0a12bb750c04510VgnVCM1000004c00210aRCRD

Ali consta:
```
Importante: receita bruta é o valor das vendas de mercadoria e prestação de serviço sem deduzir nenhuma despesa.
```

Então pelo que entendi, deve ser colocado os valores brutos mesmo.
