### ISSUE TITLE
Relatorios

### ISSUE THREAD

**Issue by winnerinformatica** [RamonSilva20/mapos#1335]
Relatório das OSs:
Hospedei o Mapos no Infityfree e estou tendo dificuldades, para imprimir relatórios detalhados das OSs
A Mensagem de erro é: **Chamada para uma função de membro result () em boo**l 
 …/modelos/Relatorios_model.php289
…/controladores/Relatorios.php485
…/fornecedor/codeigniter/estrutura/sistema/essencial/CodeIgniter.php532
/casa/vol9_7/epizy.com/epiz_28265361/htdocs/index.php306

**Comment by Pr3d4dor** [comment]
@winnerinformatica Aparentemente seu banco de dados está desatualizado, tente atualizar para ver se corrige o erro.

**Comment by vagnerlaiber** [comment]
Basta você colocar a logomarca da empresa em Configurações => Emitente

**Comment by winnerinformatica** [comment]
Já cadastrei a logomarca e atualizei o banco de dados, mas não cria relatórios de OS detalhada.

**Comment by vagnerlaiber** [comment]
Manda a foto do Erro e Passo a Passo como esta fazendo

**Comment by winnerinformatica** [comment]
[cid:8a378676-a46a-4f46-a3d7-cd0a56e0ea13][cid:a378455e-5a2b-4da3-bf40-af7f0fced87f][cid:e974ac70-d008-4948-9943-93d88c485136]
->Dashboard>Relatórios>Os (Relatórios Rápidos)
________________________________
De: Digital Tech ***@***.***>
Enviado: terça-feira, 13 de abril de 2021 21:34
Para: RamonSilva20/mapos ***@***.***>
Cc: winnerinformatica ***@***.***>; Mention ***@***.***>
Assunto: Re: [RamonSilva20/mapos] Relatorios (#1335)


Manda a foto do Erro e Passo a Passo como esta fazendo
