### ISSUE TITLE
Espião???

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#1336]
Boa tarde td bem? Passei o antivirus kaspersky e detectou que tinha um codigo malicioso, falando em ser um espião. isso me deixou um pouco preocupado, esse alerta aparecem na sua maquina? é normal?

No demais, o programa esta maravilhoso.

Obrigado a todos

**Comment by willph** [comment]
> Boa tarde td bem? Passei o antivirus kaspersky e detectou que tinha um codigo malicioso, falando em ser um espião. isso me deixou um pouco preocupado, esse alerta aparecem na sua maquina? é normal?
> 
> No demais, o programa esta maravilhoso.
> 
> Obrigado a todos

Qual foi o arquivo que ele acusou?
