### ISSUE TITLE
Não é bug - Banco de Dados como recuperar.

### ISSUE THREAD

**Issue by TK2KMG** [RamonSilva20/mapos#1337]
Bom dia ! 
Meu computador deu um bug no Windows. só consegui resolver reinstalando (não formatei). Porém não tinha feito backup do sistema ontem,
Tem como reaver o banco de dados sem perder nada  ?
Terei que reinstalar o sistema, porém não queria perde nenhuma informação, pois já tenho centenas de lançamentos. 
Por favor, podem me ajudar ?

Obs.: A pasta XAMPP está intacta na raiz do disco.

**Comment by willph** [comment]
> Bom dia !
> Meu computador deu um bug no Windows. só consegui resolver reinstalando (não formatei). Porém não tinha feito backup do sistema ontem,
> Tem como reaver o banco de dados sem perder nada ?
> Terei que reinstalar o sistema, porém não queria perde nenhuma informação, pois já tenho centenas de lançamentos.
> Por favor, podem me ajudar ?
> 
> Obs.: A pasta XAMPP está intacta na raiz do disco.

Vou tentar simular isso aqui, pra vê se o MySQL mantém os dados.
Já executou o arquivo do xampp referente ao Painel do Xampp?
É um .EXE 
Pra vê se funciona

**Comment by TK2KMG** [comment]
Sim, mas nada funciona.

**Comment by willph** [comment]
> Sim, mas nada funciona.
> Ok, agradeço pela ajuda.

Mantém os arquivos aí como backup. 

Você pode instalar a mesma versão do xampp mudando a pasta de instalação. 
`C:/xampp2` 
por exemplo. Depois que instalar você cópia os arquivos do backup e sobreescreve a instalação nova. Pra vê se vai funcionar. 

Cuidado pra não fazer o contrário. Porque essa instalação antiga é sua possível salvação.

**Comment by TK2KMG** [comment]
Ok. Irei fazer esse procedimento e lhe informo o resultado.
Até cheguei a pensar nisso , mas melhor perguntar para quem sabe. rsrs

**Comment by fwsund** [comment]
> Bom dia !
> Meu computador deu um bug no Windows. só consegui resolver reinstalando (não formatei). Porém não tinha feito backup do sistema ontem,
> Tem como reaver o banco de dados sem perder nada ?
> Terei que reinstalar o sistema, porém não queria perde nenhuma informação, pois já tenho centenas de lançamentos.
> Por favor, podem me ajudar ?
> 
> Obs.: A pasta XAMPP está intacta na raiz do disco.

normalmente a reistalacao do windows por padrao remove todas as chaves de registro do sistema, portanto todas os programas devem ser reinstalados. Faca o recorte da pasta  XAMPP para outro que nao seja o mesmo lugar da nova instalacao. Reinstale o programa e substitua a pasta nova pela antiga. conserve a pasta antiga do Xampp como copia em outro lugar ate que tenha certeza de que tudo ira funcionar.

**Comment by TK2KMG** [comment]
> 
> 
> > Sim, mas nada funciona.
> > Ok, agradeço pela ajuda.
> 
> Mantém os arquivos aí como backup.
> 
> Você pode instalar a mesma versão do xampp mudando a pasta de instalação.
> `C:/xampp2`
> por exemplo. Depois que instalar você cópia os arquivos do backup e sobreescreve a instalação nova. Pra vê se vai funcionar.
> 
> Cuidado pra não fazer o contrário. Porque essa instalação antiga é sua possível salvação.


Deu certo da maneira que você explicou , muito obrigado !
