### ISSUE TITLE
Erro ao fazer uma nova instalação local.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#1338]
Boa tarde.
Iniciei uma nova instalação local em meu notebook após formata-lo.
Anteriormente fiz a instalação direta da seguinte forma:
-Xampp
-Copiar o mapos para htdocs
-Instalar o Composer
-Entrar no localhost e criar o BD
-Entrar no localhost e instalar o mapos.

Porém nessa ultima parte aparece o seguinte erro, cujo qual não aparecia antes da formatação seguindo esses passos a cima.

![erro GD](https://user-images.githubusercontent.com/21310068/113924417-cd0e2e00-97b7-11eb-967a-6988f212e3dc.png)

**Comment by Pr3d4dor** [comment]
@Triaca Está faltando a extensão gd no seu PHP e além disso o PHP 8 não é compatível com o mapos ainda. Por favor tente usar o PHP 7.4 ou PHP 7.3.
