### ISSUE TITLE
Erro ao buscar OS's antigas

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#1339]
![erro na aba os](https://user-images.githubusercontent.com/21310068/113949626-b2e74680-97dd-11eb-8b74-17d6d0a56bca.png)
Olá,
o banco de dados foi atualizado para a versão 4.32.1, composer foi rodado em uma instalação local da mesma versão e a pasta copiada para a hospedagem.
Após isso, ocorreu o problema na hora de mudar as abas das O.S.
Isso só ocorre nessa aba, no financeiro, clientes, produtos e serviços esta ok.

**Comment by Pr3d4dor** [comment]
@Triaca Você atualizou o seu banco de dados usando os .sql dentro da pasta updates ou por dentro do sistema?

**Comment by Triaca** [comment]
utilizando os .sql.
copiei um por um até a versão atual

**Comment by Pr3d4dor** [comment]
@Triaca Tente olhar na pasta `application/logs` para ver se não tem algum log de erro.

**Comment by Triaca** [comment]
> 
> 
> @Triaca Tente olhar na pasta `application/logs` para ver se não tem algum log de erro.
Não possui logs de erros.

Uma coisa que percebi ontem logo após postar aqui, mas não tive tempo de comentar foi que:
1. Se eu clico na lupa da direita igual na imagem, todas as OS's aparecem.
![erro aba os 1](https://user-images.githubusercontent.com/21310068/114087509-f85d4f80-9881-11eb-824b-92849b977c18.png)

2. se eu clico para mudar de aba, todas as OS's somem e preciso clicar na lupa novamente, porém volta para a primeira página e não na que estava.
![erro aba os 2](https://user-images.githubusercontent.com/21310068/114087722-38bccd80-9882-11eb-81c2-dacd2996f7a3.png)

**Comment by Triaca** [comment]
Continuo com o problema.
Quando vou pesquisar OS's antigas elas não aparecem, se clico para avançar ou no número da página, simplesmente as OS's não aparecem.
Porém se clico em pesquisar com o status da OS's. Elas aparecem mas não me deixa mudar a página e checar as antigas.
![erro aba os 1](https://user-images.githubusercontent.com/21310068/114789802-aae55480-9d51-11eb-9979-0b1427afd9da.png)

![erro na aba os](https://user-images.githubusercontent.com/21310068/114789814-b0db3580-9d51-11eb-8729-58055078de53.png)

**Comment by Pr3d4dor** [comment]
@Triaca Vou investigar esse problema no final de semana
