### ISSUE TITLE
Finalização de OS

### ISSUE THREAD

**Issue by upjet** [RamonSilva20/mapos#1340]
Boa tarde, estou usando o sistema e é excelente. Parabéns aos desenvolvedores.
Queria sugerir a opção de finalizar a OS.
quando faturo ela fica finalizada, apenas podendo ser visualizada.
mais quando faço a devolução do equipamento seja por que o cliente não quiz o reparo ou porque não teve reparo não tenho a opção de finalizar a OS com esse status

**Comment by mikxingu** [comment]
Bom dia!! 
Queria entender seu fluxo de trabalho, pois ao faturar uma OS, ao meu entender você finalizou uma OS "com sucesso", gerando inclusive cobrança, pois ao faturar ele já abre a tela pra fazer o lançamento no financeiro.
No seu caso, acredito que voce pode deixar a OS em determinado status (Orçamento, Negociação, Garantia), e ao devolver o equipamento que não foi consertado, você pode alterar o status para "Finalizado" ou "Cancelado".
Caso essa opção ainda não seja suficiente, o que você pode fazer é acessar o menu de Configurações -> Sistema -> Financeiro e marcar como "não" a opção "Controle de edição de OS", onde nesse caso será possivel alterar o status de uma OS faturada.
Espero que resolva seu problema e fico à disposição caso consiga ajudar com mais alguma coisa. Lembre-se de por favor finalizar a Issue caso o problema tenha sido resolvido.

**Comment by upjet** [comment]
Bom dia mikxingu, obrigado pelo retorno.
essa parte da finalização eu entendi como funciona, e esta de boa. o que queria ver é se teria a opção de caso haja a devolução por desistência do cliente ou equipamento condenado e não tem reparo, eu finalizar e não poder mais fazer edição na OS assim como ocorre quando faço o faturamento.

**Comment by upjet** [comment]
outro detalhe, tem como gerar um termo de devolução(ou termo de entrega), assim como tem termo de garantia.

**Comment by hoshikawakun** [comment]
> 
> 
> Bom dia mikxingu, obrigado pelo retorno.
> essa parte da finalização eu entendi como funciona, e esta de boa. o que queria ver é se teria a opção de caso haja a devolução por desistência do cliente ou equipamento condenado e não tem reparo, eu finalizar e não poder mais fazer edição na OS assim como ocorre quando faço o faturamento.

Faça assim como eu, quando tenho de devolver o item por algum motivo, seja não autorizado, sem reparo ou outras coisas eu so altero o status da OS, e quando o cliente retira o aparelho eu faço o faturamento da OS com valor 0,00

**Comment by upjet** [comment]
hoshikawakun obrigado, vou fazer assim tbm
