### ISSUE TITLE
Adicionar campo observacoes em cadastro cliente 

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#1341]
Boa tarde, 
Estou tentando implementar um campo Observacoes no cadastro do cliente, acho de bastante ajuda, pois ali posso adicionar varias anotacoes importantes como; outro email, data para boletos, outros contatos, em fim... muitas ultilidades.

a principio um adicionaei uma linha na tabela clientes, apos fornecedor com o nome **observacoescliente** tipo text, colacao latin1_swedish_ci
![3](https://user-images.githubusercontent.com/55247088/114070247-2e94d200-9876-11eb-830d-af2afe024ab4.jpg)

depois fiz algumas alteracoes no arquivo Adicionarcliente.php para que ficasse desta forma
![1](https://user-images.githubusercontent.com/55247088/114070507-73206d80-9876-11eb-8223-699c7c4b1e55.jpg)
![2](https://user-images.githubusercontent.com/55247088/114070518-7582c780-9876-11eb-8f4c-a92dfde74d47.jpg)

ainda preciso modificar os arquivos visualizar.php e editarCliente.php para que seja possivel editar e vizualizar essas informacoes . 

Gostaria de saber se a ideia seria apoiada por voces, pois tenho algumas duvidas referente a comunicacao do banco de dados e de nada adianta eu modificar o mapos desta forma e em uma futura atualizacao eu ter que modificar por minha conta tudo novamente.

**Comment by bietez** [comment]
Eu acho interessante, provavelmente vou implementar aqui. Acredito que isso seja mais interessante ainda no caso de PJ pois abre um bom espaço para anotar algo tipo "Responsavel por tal area", "E-mail financeiro" e etc...

**Comment by fwsund** [comment]
@bietez  sem duvidas, essa e a ideia, e se fosse criar varios campos para isso ficaria muito confuso e muito extenso a programacao, creio que um campo para adicionar anotacoes no cliente seria o mais interessante

**Comment by neozinh** [comment]
Por favor pode me passar como ficou nos arquivos adcionarcliente.php,  visualizar.php e editarCliente.php? Não estou conseguindo, a observação esta aparecendo embaixo do endereço e não na nova aba.

**Comment by fwsund** [comment]
segue o adcionarclientes.php, preciso de ajuda para configura a comunicacao do banco de dados, vc conseguiu?


`						
                    <div id="menu3" class="tab-pane fade">
						<div class="span6" style="padding: 1%; margin-left: 0">
                                        <label for="observacoes">
                                            <h4>Observações</h4>
                                        </label>
                                        <textarea class="span12 editor" name="observacoescliente" id="observacoescliente" cols="30"
                                                  rows="5"><?php echo $result->observacoescliente ?></textarea>
                        </div>
                        <div class="form-actions">
                            <div class="span12">
                                <div class="span6 offset3">
                                    <button type="submit" class="btn btn-success">Salvar</button>
                                </div>
                            </div>
                        </div>
					</div>

**Comment by fwsund** [comment]
Segue o codigo, adcionarclientes.php. Vc ja configurou a comunicacao com banco de dados?

![10](https://user-images.githubusercontent.com/55247088/115295773-82ce6a80-a130-11eb-9e98-8f3663c9b46b.jpg)

**Comment by neozinh** [comment]
Havia configurado sim.

**Comment by fwsund** [comment]
tem sim, um pouco mais pra cima.

![11](https://user-images.githubusercontent.com/55247088/115299731-90d2ba00-a135-11eb-9962-8698d9edda6c.jpg)
