### ISSUE TITLE
Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

### ISSUE THREAD

**Issue by LouanJuliels** [RamonSilva20/mapos#1342]
Segui os passos de instalação porem não esta instalando o repositório

aparece a seguinte mensagem
 
![image](https://user-images.githubusercontent.com/82371113/114417045-a53c1300-9b87-11eb-99f4-6ba230a8bf93.png)

**Comment by willph** [comment]
Qual versão do Mapos?

**Comment by LouanJuliels** [comment]
> Qual versão do Mapos?
usando Xampp 7.4.16
Mapos versão 4.32.1

**Comment by Pr3d4dor** [comment]
@LouanJuliels Verifique se existe a pasta application/vendor, se existir já estão instalados as dependencias.

**Comment by LouanJuliels** [comment]
> @LouanJuliels Verifique se existe a pasta application/vendor, se existir já estão instalados as dependências.

acabei de chegar e não possui essa pasta dentro do application

**Comment by LouanJuliels** [comment]
Alguém pode me ajudar por favor? tem algum jeito de zerar o composer, desinstalar ou algo assim??

**Comment by Pr3d4dor** [comment]
@LouanJuliels Tente deletar o arquivo composer.lock e rodar o comando composer install

**Comment by LouanJuliels** [comment]
Deu na mesma, aparentemente todos os arquivos principais estão no lugar certo, só as dependências que não vai mesmo
![image](https://user-images.githubusercontent.com/82371113/114497161-e10ec100-9bf7-11eb-9499-56d35885ce3b.png)

**Comment by vagnerlaiber** [comment]
Tenta executar comando composer update

**Comment by LouanJuliels** [comment]
> Tenta executar comando composer update

mesma coisa 
![image](https://user-images.githubusercontent.com/82371113/114591680-878eac80-9c60-11eb-9db0-58b0c2b48476.png)

**Comment by willph** [comment]
> > Tenta executar comando composer update
> 
> mesma coisa
> ![image](https://user-images.githubusercontent.com/82371113/114591680-878eac80-9c60-11eb-9db0-58b0c2b48476.png)

Poderia postar o conteúdo do seu arquivo composer.json? 
Fica no raiz do Mapos

**Comment by willph** [comment]
Vou te enviar o link com o zip da pasta vendor.
Só baixar, extrair e colocar na pasta application

Já já posto

**Comment by willph** [comment]
Pasta vendor, so extrair e colocar na pasta application.

https://drive.google.com/file/d/1I5uE6awTreY_perjRRPktPm_dI0WXOKx/view?usp=sharing

**Comment by LouanJuliels** [comment]
> > > Tenta executar comando composer update
> > 
> > 
> > mesma coisa
> > ![image](https://user-images.githubusercontent.com/82371113/114591680-878eac80-9c60-11eb-9db0-58b0c2b48476.png)
> 
> Poderia postar o conteúdo do seu arquivo composer.json?
> Fica no raiz do Mapos

desculpe a demora conteudo do composer.json


    "require": {
        "fzaninotto/faker": "^1.9",
        "mercadopago/dx-php": "^2.2.1",
        "gerencianet/gerencianet-sdk-php": "^2.4.1",
        "codeigniter/framework": "3.1.11",
        "mpdf/mpdf" : "^8.0.10",
        "filp/whoops": "^2.7",
        "mk-j/php_xlsxwriter": "^0.38.0",
        "mpdf/qrcode": "^1.1",
        "phpoffice/phpword": "^0.18.0",
        "piggly/php-pix": "^1.2.5"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.16",
        "symfony/var-dumper": "^5.0"
    },
    "scripts": {
        "format": [
            "application/vendor/bin/php-cs-fixer fix"
        ]
    },
    "config": {
        "vendor-dir": "application/vendor"
    },
    "autoload": {
        "psr-4": {
            "Libraries\\": "application/libraries"
        }
    }
}

**Comment by willph** [comment]
Quando baixar e extrair o arquivo na pasta application o Mapos funcionará tranquilamente.

**Comment by LouanJuliels** [comment]
> Quando baixar e extrair o arquivo na pasta application o Mapos funcionará tranquilamente.

Funcionou muito obrigado

**Comment by lucassilvarp** [comment]
Pessoal alguém consegue upar a pasta Vendor novamente ? Meu provedor de hospedagem não cria a pasta system
