### ISSUE TITLE
BUG VENDAS

### ISSUE THREAD

**Issue by SaghaZ** [RamonSilva20/mapos#1343]
Bom dia, ja abri uma solicitação referente a isso mais expirou...
entao estamos nós aqui novamente, ao lançar uma venda, por algum motivo ela e lançada 2,3,4 vezes igual nos "lançamentos"
e isso vem causando bastante transtornos...
Agradeço muito se alguém puder me ajudar, desde ja agradeço a equipe do mapos !

![Sem título](https://user-images.githubusercontent.com/66077575/114542486-60b78280-9c2e-11eb-92f7-070d21304a94.png)

**Comment by willph** [comment]
Isso ocorre só clicar em FATURAR uma venda?

**Comment by vagnerlaiber** [comment]
Bom Dia, já tentou fazer uptade no banco, talvez vc atualizou o sistema mas não o banco de Dados.

**Comment by marcelinoac** [comment]
Boa tarde! Uma vez aconteceu comigo e descobri que o problema era o mouse. Sempre que ia adicionar uma OS, aparecia duas ou três iguais no BD.

**Comment by suzannaMoura** [comment]
tbm tenho esse problema, no meu caso descobri que e o seguinte, o vendedor clica em "faturar" e ai a internet cai na hora ou da uma oscilada, entao, ele fica clicando "faturar,faturar" vai genrando "lancamentos" no banco de dados, seria otimo ter algo pra resolver isso...

**Comment by SaghaZ** [comment]
ja dei update no banco sim....
bem suzanna, acredito que oq voce falou tem logica... pode ser isso heim !!
e possivel criar alguma trava pra isso ?
