### ISSUE TITLE
Estatísticas de OS

### ISSUE THREAD

**Issue by jonathasnp** [RamonSilva20/mapos#1344]
Boa noite alguém sabe  onde posso personalizar a cor das  Estatísticas de OS?
![image](https://user-images.githubusercontent.com/81585844/114647662-d9aced80-9cb3-11eb-9688-7ab130043078.png)
 ja mudei em tudo só aqui que não consegui

**Comment by bietez** [comment]
@jonathasnp Linha 586 no caminho `application\views\mapos\painel.php` acrescenta um 
`seriesColors: ["#cor100", "#cor200"... ],`
![image](https://user-images.githubusercontent.com/81322742/114749246-1e26a080-9d29-11eb-9b35-f3b3f7de33a9.png)

**Comment by bietez** [comment]
@jonathasnp Exemplo que fiz mudando as duas primeiras cores:
![image](https://user-images.githubusercontent.com/81322742/114749515-66de5980-9d29-11eb-990f-42c20f3ab249.png)

**Comment by jonathasnp** [comment]
Tanky

**Comment by augustocoletti** [comment]
> @jonathasnp Linha 586 no caminho `application\views\mapos\painel.php` acrescenta um
> `seriesColors: ["#cor100", "#cor200"... ],`
> ![image](https://user-images.githubusercontent.com/81322742/114749246-1e26a080-9d29-11eb-9b35-f3b3f7de33a9.png)

Bom dia amigo, se me permitir abusar da ajuda, gostaria de saber 2 coisas, como faço  pra alterar as cores do gráfico anual (balanço mensal) e se há alguma forma de trazer por padrão a opção de receita bruta ou inadimplentes (por ex) desmarcadas. Não quero remover, apenas que o padrão seja dois dados.
Agradeço desde já

**Comment by bietez** [comment]
@augustocoletti Bom dia meu Sr. Então... Eu particularmente utilizo a versão 4.11.2 e não sei exatamente como funciona a questão de inadimplência e tal. Toda versão nova que chega do MAPOS vou la garimpar o que é interessante pra mim, e a inadimplência é algo que não foi/é interessante para usar aqui na minha loja, mas eu te ajudo nessa, só preciso de tempo e, sinceramente, entender realmente o que você precisa porque não entendi kkkkk Faz um desenho no Paint mesmo do resultado final do que você precisa que eu subo o código pra você. Talvez demore um pouco, pois no momento estou preparando um Pull Request, mas uma hora sai! Precisando, estamos ai!

**Comment by mikxingu** [comment]
Bom dia! @augustocoletti  voce pode alterar as cores colocando a propriedade "color" na série em que é montada a chart do balanço mensal conforme código abaixo: 

![Screenshot from 2021-04-16 09-38-31](https://user-images.githubusercontent.com/30123586/115025296-94491580-9e97-11eb-8b88-017fa7c71cbc.png)


Esse é o resultado final:

![Screenshot from 2021-04-16 09-19-12](https://user-images.githubusercontent.com/30123586/115023263-ed637a00-9e94-11eb-9a0f-de42232b020d.png)

Conforme comentei na issue #1288, eu estava com problemas para alterar a cor, mexendo no arquivo "highcharts.js" e não estava dando certo, mas acabei descobrindo que o problema era no meu navegador que tinha gerado cache da página e por isso eu não conseguia atualizar. Depois que eu limpei o cache, as cores foram atualizadas.

Conforme o @bietez  comentou, acho que vou abrir uma PR pra atualizar essas cores e pelo menos adicionar esses comentários no código, para que mais pessoas consigam alterar facilmente esse código.
Eu até faria uma opção lá nas configurações pra alterar, mas ai acredito que teria que ser gerada uma atualização no banco pra salvar as cores selecionadas pelo usuário, sei lá. Estou aprendendo programação, se alguém puder me ajudar, tenho interesse em fazer isso. No mais, espero que te ajude, e qualquer coisa estou a disposição.

**Comment by augustocoletti** [comment]
Agradeço a atenção de @bietez e @mikxingu !!! vou fazer algumas alterações e aviso o resultado.  Novamente, muito obrigado pelas dicas e por terem se disponibilizado a ajudar!!!

**Comment by mikxingu** [comment]
@augustocoletti  Disponha.
@jonathasnp Peço para que finalize essa issue caso o problema tenha sido resolvido. Agradeço e mais uma vez me coloco à disposição caso consiga ajudar com mais alguma coisa.
