### ISSUE TITLE
API - Gerencianet

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1345]
Boa Noite pessoal 
Gostaria de tirar uma duvida, sobre o sistema de cobrança. Gerencianet será cobrado por utilizar o API no sistema? 
Vi algo assim no site deles ai resolvi tirar a duvida com vocês.

**Comment by willph** [comment]
Sim.
Tem a tarifa deles.

https://gerencianet.com.br/tarifas/

**Comment by cabralwms** [comment]
Muito obrigado meu amigo, acredito que vale pela facilidade, grato pela agilidade.
