### ISSUE TITLE
Erro ao clicar em adicionar ou atualizar

### ISSUE THREAD

**Issue by gfBarreto** [RamonSilva20/mapos#1346]
![Captura de Tela 2021-04-15 às 16 13 24](https://user-images.githubusercontent.com/50118176/114925505-94003a00-9e05-11eb-9c16-c5ce2fb42631.png)
![Captura de Tela 2021-04-15 às 16 13 33](https://user-images.githubusercontent.com/50118176/114925522-9b274800-9e05-11eb-9bfd-500efd581080.png)

Ao clicar em qualquer dos itens para adicionar ou alterar, o caminho da url repete duas vezes o index.php, como no exemplo abaixo e apresenta erro 404, página não encontrada.

index.php/index.php/clientes/editar/1

Se eu retirar um dos "index.php" volta o conteúdo do botão clicado, funciona blz.
Em que arquivo consigo configurar o caminho correto?
Na instalação, utilizei localhost e caminho da URL utilizei "/"

OBS: estou utilizando Debian numa instalação limpa, somente o sistema rodando. Os serviços rodando, instalei por linha de comando.

**Comment by bietez** [comment]
@gfBarreto Cria um `.htaccess` na raiz da instalação com o seguinte:
`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule (.*) /index.php/$1 [L]`

Depois vai em `application\config\config.php` linha 54 `$config['index_page'] = 'index.php';` e apaga o `index.php`
Vai ficar:
`$config['index_page'] = '';`

**Comment by bietez** [comment]
@gfBarreto O Github tirou a quebra de linha do codigo que passei ai em cima pro htaccess, tem que ficar assim:

![image](https://user-images.githubusercontent.com/81322742/114932142-877fdf80-9e0d-11eb-9bc1-e31f80bdf40b.png)

**Comment by gfBarreto** [comment]
Feito meu amigo!

Muito obrigado, resolvido e funcionando.
Tentei instalar no MacOs e tive alguns problemas... Como vou testar o
sistema por enquanto estou utilizando numa máquina virtual, depois vou
migrar para meu servidor linux.

Geovane Feijó Barreto
Hard & Soft - Serviços em T.I.
Soluções em Windows e Linux
*(53) 9.9977-4466 (WhatsApp)


Em qui., 15 de abr. de 2021 às 17:11, bietez ***@***.***>
escreveu:

**Comment by gfBarreto** [comment]
![Captura de Tela 2021-04-15 às 19 07 08](https://user-images.githubusercontent.com/50118176/114944359-d2a1ee80-9e1d-11eb-9dcd-92074ab31c33.png)

**Comment by gfBarreto** [comment]
Resolvido ...
