### ISSUE TITLE
ERRO CRON

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#1347]
Boa Noite, Estou Tentando fazer tarefa no Cron no Provedor pelo painel Direct Admin, Primeiro deu Mensagem falando da versão do PHP (a Mesma ja estava em 7,3 porem dizia que era 5,6) e depois tentei puxar direto o 7,3 deu outro erro segue os Prints abaixo.
![cron2](https://user-images.githubusercontent.com/58378184/114946237-2a8e2480-9e21-11eb-9e70-a086faf90af9.PNG)
![cron3](https://user-images.githubusercontent.com/58378184/114946242-2c57e800-9e21-11eb-9db5-1ceafbc8689b.PNG)
![Cron](https://user-images.githubusercontent.com/58378184/114946243-2cf07e80-9e21-11eb-9c96-0657b30ef6d0.PNG)

**Comment by Pr3d4dor** [comment]
@vagnerlaiber Qual versão do mapos você está utilizando?
