### ISSUE TITLE
Notificação WhatsApp

### ISSUE THREAD

**Issue by gfBarreto** [RamonSilva20/mapos#1350]
O Envio de notificação está funcionando corretamente, porém tenho duas dúvidas...
Eu utilizo o WhatsApp Aplicativo e quando envio a notificação ele tenta abrir o Whats Web. Tranquilo.. posso voltar a usar o WEB, porém ao utilizar o WEB, a cada envio de notificação ele abre uma nova aba.
Existe possibilidade de utilizar o Whats Aplicativo? 
Se não, como faço para não abrir uma nova aba a cada envio de notificação, o sistema utilizar a mesma que já está em uso?

Grato,

Geovane Barreto

**Comment by RamonSilva20** [comment]
Olá @gfBarreto, nesse caso basta trocar o target do link para algum nome específico ao invés de _blank.

target="_blank" ----> target="_whats"

Para detectar se é mobile e qual deveria abrir, precisaria rodar um script de detecção e alterar o link de acordo.

Um exemplo de como poderia ser feito:

```
var link_whats = 'https://web.whatsapp.com/send?phone=55' + zapnumber + '&text=' + texto_de_notificacao;

var isMobileDevice = /Mobi/i.test(window.navigator.userAgent);

var isMobile = window.orientation > -1;
if (isMobile) {
         window.open('whatsapp://send?phone=' + zapnumber + '&text=' + texto_de_notificacao);
}
else{
        window.open(link_whats, "_whats");
}

```

**Comment by gfBarreto** [comment]
Blz!!!

Vou tentar...
No meu caso, utilizo por enquanto o MAPOS numa maquina virtual com Debian.

Meu note é Mac, portanto não sei como seria para fazer o MAPOS detectar o
aplicativo do whats no mac...

grato!!


Geovane Feijó Barreto
Hard & Soft - Serviços em T.I.
Soluções em Windows e Linux
*(53) 9.9977-4466 (WhatsApp)


Em sex., 16 de abr. de 2021 às 17:19, Ramon Silva ***@***.***>
escreveu:

**Comment by gfBarreto** [comment]
Consegui fazer abrir o App do whats... 

Alterei a entrada de  href="https://web.whatsapp.com/send?phone=55

para  href="whatsapp://send?phone=55

**Comment by MarceloGrass** [comment]
Boa tarde, gostaria de fazer essa mudança também, aonde fica essa linha?

Alterei a entrada de href="https://web.whatsapp.com/send?phone=55
para href="whatsapp://send?phone=55

Muito obrigado!!! Ótimo aplicativo!!! estou rodando ele com subdomínio no meu site e implementando ele pra usar no lugar do OS Plus.

**Comment by MarceloGrass** [comment]
Achei no visualizarOs.php modifiquei e deu certo no PC abre o app!!! e o melhor de tudo é que no smartphone abre a opção de abrir Whastapp ou Whatsapp Business, isso é ótimo!!! parabéns!!!

**Comment by gfBarreto** [comment]
Bom dia!!!

Blz que achou meu amigo!!

Geovane Feijó Barreto
Hard & Soft - Serviços em T.I.
Soluções em Windows e Linux
*(53) 9.9977-4466 (WhatsApp)


Em ter., 6 de jul. de 2021 às 18:00, MarceloGrass ***@***.***>
escreveu:
