### ISSUE TITLE
Data de vencimento do boleto emitido

### ISSUE THREAD

**Issue by Marke2018** [RamonSilva20/mapos#1351]
Boa tarde!
Quando eu emito boletos pelo API do GerenciaNet, no mapos não tenha a opção de colocar uma data de vencimento, e ele emite com 3 dias. É possível colocar essa data no mapos?

**Comment by Pr3d4dor** [comment]
É configurável:
https://github.com/RamonSilva20/mapos/blob/master/application/config/payment_gateways.php#L15
