### ISSUE TITLE
Pontuação ortográfica

### ISSUE THREAD

**Issue by Marke2018** [RamonSilva20/mapos#1352]
Boa noite!
Ao abrir uma O.S e clicar no botão do Whastapp, a observação que possui pontos ortográficos na frase sai com os caracteres assim: **&lt;/p&gt;&;p&lt;p&gt;p&;p&gt;p&gt;p&gtv...** enviando o texto para o cliente. O que pode ser?

**Comment by Pr3d4dor** [comment]
@Marke2018 Pode postar uma imagem pra entendermos melhor?

**Comment by Marke2018** [comment]
Boa tarde @Pr3d4dor,  segue o Print do Whatsapp que ocorreu o problema, vou observar melhor porque só foi esse caso, estou testando agora o sistema e não ocorreu.

![image](https://user-images.githubusercontent.com/80719064/115154623-43c9e780-a052-11eb-9ea3-1d6525fbb802.png)

**Comment by Pr3d4dor** [comment]
@Marke2018 Estranho, realmente não sei o motivo de ter ocorrido isso

**Comment by TK2KMG** [comment]
Olá , tudo bem ? 
No meu também está ocorrendo a o mesmo problema, ao  enviar por WhatsApp, está aparecendo caracteres entre a descrição do equipamento. 
O que pode ser ?
