### ISSUE TITLE
Produtos

### ISSUE THREAD

**Issue by neozinh** [RamonSilva20/mapos#1353]
Como habilitar para registrar a quantidade e data das entradas e saídas dos produtos?

**Comment by Pr3d4dor** [comment]
@neozinh Para implementar isso seria necessário implementar um controle de estoque diferenciado.

**Comment by hoshikawakun** [comment]
Não daria para implementar para aparecer na auditoria não?
Sendo Assim
Usuario "xxx" add "y" itens ao item "Z"
