### ISSUE TITLE
Como alterar a cor de fundo da tela de login

### ISSUE THREAD

**Issue by fapernas** [RamonSilva20/mapos#1357]
Olá, boa tarde a todos.

Por favor, como alterar a cor de fundo da tela de login??

Obrigado.

**Comment by fwsund** [comment]
ola, @fapernas  o arquivo que precisa ser alterado e  o matrix-login.css.
caminho do arquivo  mapos/assets/css 
A cor atual e #2E363F linha 42,46 e 58. 
vc pode trocar a cor altrando o codigo das linhas, lembrando que cada uma delas representa uma parte da pagina. 
exemplo: eu usei #008000 e ficou assim... 
![45](https://user-images.githubusercontent.com/55247088/115916985-ed8ee700-a44b-11eb-9eb5-60437c01aaee.jpg)

**Comment by fapernas** [comment]
> ola, @fapernas o arquivo que precisa ser alterado e o matrix-login.css.
> caminho do arquivo mapos/assets/css
> A cor atual e #2E363F linha 42,46 e 58.
> vc pode trocar a cor alterando o codigo das linhas, lembrando que cada uma delas representa uma parte da pagina.
> exemplo: eu usei #8000 e ficou assim...
> ![45](https://user-images.githubusercontent.com/55247088/115916985-ed8ee700-a44b-11eb-9eb5-60437c01aaee.jpg)

@fwsund, funcionou perfeitamente. Agradeço pela ajuda e atenção.
Abraço.
