### ISSUE TITLE
Não envia email de OS para o cliente.

### ISSUE THREAD

**Issue by adielramos** [RamonSilva20/mapos#1361]
Olá pessoal!
Comecei a usar o Map-OS essa semana, estou achando excelente. 
Porém estou com dificuldade na parte de envio de emails para os clientes mesmo seguindo todos os issues já abertos aqui.

Fiz a configuração do email.php, do emitente no sistema e o comando cron conforme os prints abaixo.

![image](https://user-images.githubusercontent.com/83191544/116014390-66886d00-a60b-11eb-9e08-dd9a5961822a.png)
![image](https://user-images.githubusercontent.com/83191544/116014435-a8191800-a60b-11eb-9585-62606c74626e.png)
![image](https://user-images.githubusercontent.com/83191544/116014746-3641ce00-a60d-11eb-969f-0fc499a703dc.png)

todavia os emails não são enviados quando clico em enviar email na ordem de serviço.

recebo o sequinte erro de resposta do cron:

session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/cpanel/php/sessions/ea-php73)
![image](https://user-images.githubusercontent.com/83191544/116014630-92582280-a60c-11eb-8b23-01eb5964921f.png)

Alguém já passou por isso? Alguém consegue me ajudar?

Desde já agradeço e parabenizo por esse excelente sistema.

**Comment by brtechst** [comment]
Rapaz acho que a maior mazela desse lindo projeto é a desgraça desse envio de emails que quase ninguém consegue kkkk.

Fora isso sistema é topp, obrigado a todos os desenvolvedores pela iniciativa.

**Comment by cabralwms** [comment]
me chama que tento te ajudar

**Comment by brtechst** [comment]
to na mesma situação..

comigo não da esse erro, no entanto la no cron jobs tudo ok mas não funciona.

![image](https://user-images.githubusercontent.com/53625745/119411955-9b96e680-bcc1-11eb-80d4-b3f5fbe6cdaf.png)

**Comment by roviglio** [comment]
Estou com o mesmo problema mas estou usando o XAMMP no windows 10, os e-mails ficam com status de enviando....

**Comment by willph** [comment]
> Estou com o mesmo problema mas estou usando o XAMMP no windows 10, os e-mails ficam com status de enviando....

No Windows você terá que enviar digitando o comando no CMD de dentro da pasta do Mapos

```php index.php email/process```

**Comment by willph** [comment]
Lembrando que tem que está tudo bem configurado para evitar falha.

Poderá criar também um script e colocar no agendamento de tarefas do Windows para automatizar.

**Comment by roviglio** [comment]
Obrigado por responder.
Acho que esta configurado sim, mas ...
O arquivo email.php do diretório mapos\application configurado com a caixa postal e senha.
A caixa postal é a mesma do arquivo e do emitente
O comando  php index.php email/process é executado dentro da pasta mapos
Mas fica sempre com status enviando.
Desliguei a firewall desliguei o antivirus a mesma coisa.
Então fiz um teste exemplo-PHPMailer e o e-mail foi.
Então ser tiver algo que possa me ajudar

Atenciosamente.
Oliveira.

RWO-Roviglio Wanderley Oliveira
Tel.: (15) 96299068
***@***.******@***.***>


________________________________
De: Wilmerson ***@***.***>
Enviado: quarta-feira, 26 de maio de 2021 20:21
Para: RamonSilva20/mapos ***@***.***>
Cc: roviglio ***@***.***>; Comment ***@***.***>
Assunto: Re: [RamonSilva20/mapos] Não envia email de OS para o cliente. (#1361)


Lembrando que tem que está tudo bem configurado para evitar falha.

Poderá criar também um script e colocar no agendamento de tarefas do Windows para automatizar.

**Comment by roviglio** [comment]
Gostaria de saber como é executado o envio de e-mail.
No windows vou em cmd dentro do diretório do MAPOS e digito php index.php email/process.
o comando php executa o php o index.php é o arquivo index.php mas o que é o mail/process?
Dentro do arquivo index.php tambem não encontrei uma referencia para o envio de email.
O arquivo de configuração é o que alteramos o e-mail e senha mas onde esta o arquivo php que envia os e-mails ?
Da para ver que os e-mails para serem enviados ficam no banco de dados mas como funciona esse comando??
Desde já obridado

**Comment by LucasPolli** [comment]
estava quebrando a cabeça com isso tb, porem percebi após muito tempo que o problema só ocorre com e-mails do gmail, para outros domínios funciona normalmente, ainda não achei uma solução, uso hospedado no hostgator

**Comment by roviglio** [comment]
fiquei curioso e no inicio achei que era os e-mails da gmail, troquei por um que tenho hospedagem mas também não funcionou, acho que é um problema de compatibilidade de protocolos logo depois do helo enviado para o servidor, este mesmo tenha fazer uma conexao com algo como outro helo, 
Como não entendi direito os arquivos php index.php email/process resolvi tentar desenvolver algo em php para acessar a tabela email_queue e caso o status fosse "sent" ele pulava o registro e são fosse enviado então enviava o email e trocava o status para enviado.
Tudo num so arquivo usando a biblioteca PHPMailer dentro do windows 10 com xammp
Ta rodando mas vou ver ser melhoro um pouquinho

**Comment by roviglio** [comment]
Há por curiosidade hostgator o MAPOS esta sendo executado sem certificado SSL
Tanto no servido que uso a Webhost e localmente no windows estão rodando com SSL
Achei que podia ser isto dai fiz a minha rotina  que usa PHPMailer

**Comment by roviglio** [comment]
Boa noite, tentando resolver este meu problema, fiz uma rotina para enviar os e-mails do MAPOS e actualizar o status para enviado no XAMPP com windows 10 e ssl, quem quizer ver a rotina esta em https://github.com/roviglio/mail_mapos.

**Comment by dvdbsilva** [comment]
Olá pessoal, 

Configurei hoje o mapos e funcionou o envio de e-mail, utilizei o gmail para envio e antes tive que desativar o FMA
e aceitar acesso menos seguros e desbloquear para não pedi Captcha segue os links abaixo. 

    https://myaccount.google.com/lesssecureapps
    http://www.google.com/accounts/DisplayUnlockCaptcha

**Comment by tutibueno** [comment]
No meu caso, resolvi alterando 'smtp' para 'mail' conforme o print

![image](https://user-images.githubusercontent.com/10643032/125845525-0719de95-bab4-4816-ad3b-cb69c70478f1.png)
