### ISSUE TITLE
Adicionar campo 'Margem' para calculo automático do valor de venda

### ISSUE THREAD

**Issue by fapernas** [RamonSilva20/mapos#1362]
Olá, bom dia.

Acredito que essa melhoria seja 'simples', me arrisco com programação...até tentei fazer algumas buscas online mas não consegui evoluir.
Preciso criar um campo 'Margem' na tela de cadastro de produtos e na de serviços que receberá a % ref. a margem de lucro e que automaticamente o preço de venda seja calculado.

Consegui adicionar o campo em adicionarProduto.php, passar um valor padrão no item value mas estou com dificuldade em apresentar o valor de venda -> valor de compra + margem(%)

Obrigado.

**Comment by mikxingu** [comment]
Achei interessante essa issue. Gostaria de lhe ajudar a fazer isso. Estou comentando aqui pra entrar no meu feed do github

**Comment by fapernas** [comment]
> Achei interessante essa issue. Gostaria de lhe ajudar a fazer isso. Estou comentando aqui pra entrar no meu feed do github

Agradeço @mikxingu!! Caso queira trocar uma ideia a respeito estou a disposição. Abraço.

**Comment by martins2019** [comment]
Olá!

Eu implementei dessa forma...
Talvez não seja a melhor opção mas facilita fazer o cálculo durante o cadastro do produto.
![Tela](https://user-images.githubusercontent.com/50087178/116604518-9d5ccc80-a904-11eb-87d1-4ecd796463f1.png)
![tela1](https://user-images.githubusercontent.com/50087178/116604557-ab125200-a904-11eb-9fab-2cbcaecc2adb.png)

**Comment by mikxingu** [comment]
Pow! Bem legal! Já dá uma idéia pra desenvolver, mas acredito que seja legal fazer isso e disponibilizar pra todo mundo. Acho que a maioria dos usuários vao se beneficiar

**Comment by mikxingu** [comment]
@martins2019 poderia disponibilizar o código fonte? Só pra eu ter uma base, pois confesso que meu php nao é dos melhores

**Comment by martins2019** [comment]
Segue o arquivo.
Só alterar a extensao para php...
[adicionarProduto.txt](https://github.com/RamonSilva20/mapos/files/6401860/adicionarProduto.txt)

**Comment by hoshikawakun** [comment]
> 
> 
> Segue o arquivo.
> Só alterar a extensao para php...
> [adicionarProduto.txt](https://github.com/RamonSilva20/mapos/files/6401860/adicionarProduto.txt)

Vou implementar no meu essa % na hora de faturar uma OS ou venda, vai ajudar bastante

**Comment by martins2019** [comment]
Estou implantando esse projeto para um cliente...
Segue uma dica para implantar em faturar vendas e OS.
![Tela OS](https://user-images.githubusercontent.com/50087178/116640990-2d6d3700-a942-11eb-8a33-716fe7183ede.png)

**Comment by hoshikawakun** [comment]
> 
> 
> Estou implantando esse projeto para um cliente...
> Segue uma dica para implantar em faturar vendas e OS.
> ![Tela OS](https://user-images.githubusercontent.com/50087178/116640990-2d6d3700-a942-11eb-8a33-716fe7183ede.png)

passa o arquivo editarOS.php quando concluir as alterações ai

**Comment by fapernas** [comment]
> Segue o arquivo.
> Só alterar a extensao para php...
> [adicionarProduto.txt](https://github.com/RamonSilva20/mapos/files/6401860/adicionarProduto.txt)

@martins2019 massa demais. Perfeito. Obrigado por compartilhar.
Vou fazer o deploy aqui e aviso do resultado.
Abraço.
