### ISSUE TITLE
é confiavel?

### ISSUE THREAD

**Issue by Marcosrocha5858** [RamonSilva20/mapos#1363]
olá este script é confiável? alguém usa ?

**Comment by hoshikawakun** [comment]
> 
> 
> olá este script é confiável? alguém usa ?

eu uso na minha loja/assistencia e conheço varios amigops que usam
eu mesmo uso praticamente desde o começo do projeto

**Comment by Marcosrocha5858** [comment]
hoshikawakun, vc me indica qual plano de hospedagem aceita este projeto? vou implementar NFC e cima das vendas , para usar na loja da minha esposa.

**Comment by Marcosrocha5858** [comment]
> > olá este script é confiável? alguém usa ?
> 
> eu uso na minha loja/assistencia e conheço varios amigops que usam
> eu mesmo uso praticamente desde o começo do projeto

vc me indica qual plano de hospedagem aceita este projeto? vou implementar NFC e cima das vendas , para usar na loja da minha esposa.

**Comment by hoshikawakun** [comment]
> 
> 
> > > olá este script é confiável? alguém usa ?
> > 
> > 
> > eu uso na minha loja/assistencia e conheço varios amigops que usam
> > eu mesmo uso praticamente desde o começo do projeto
> 
> vc me indica qual plano de hospedagem aceita este projeto? vou implementar NFC e cima das vendas , para usar na loja da minha esposa.

Nota Fiscal e emitida aki atravez de um App somente para ela, e eu aki uso a hostgator

**Comment by mikxingu** [comment]
Boa noite @Marcosrocha5858 ! Você precisará de um plano de hospedagem que rode PHP versão 7.3 ou mais atual, banco de dados MySQL e preferivelmente que tenha acesso ao terminal, pra rodar o comando composer do PHP. Eu utilizava ele na hostinger e nunca tive problema, e os planos lá são bem baratos. Espero ter ajudado.

**Comment by mikxingu** [comment]
Caso sua hospedagem nao libere acesso ao terminal, voce pode rodar o comando em uma máquina local e subir os arquivos já prontos pra sua hospedagem.

**Comment by Marcosrocha5858** [comment]
> Boa noite @Marcosrocha5858 ! Você precisará de um plano de hospedagem que rode PHP versão 7.3 ou mais atual, banco de dados MySQL e preferivelmente que tenha acesso ao terminal, pra rodar o comando composer do PHP. Eu utilizava ele na hostinger e nunca tive problema, e os planos lá são bem baratos. Espero ter ajudado.

obrigado @mikxingu
