### ISSUE TITLE
Contabilizando Valor por quantidade de horas trabalhadas

### ISSUE THREAD

**Issue by viniciusjales** [RamonSilva20/mapos#1366]
A nova versão do mapos esta perfeita, gostaria de re adequar para minha realidade uma função para contabilizar um certo valor pela quantidade de horas trabalhadas quando eu for abrir e finalizar uma O.S por exemplo.

**Comment by fwsund** [comment]
Ola, @viniciusjales uma sugetao por exemplo, sua hora tecnica e R$100,00 entao vc vai na guia de servicos e adicionar por exemplo: MANUTENÇÃO/ SERVIÇO POR HORA TECNICA/VALOR MIN. valor de Exempo: R$1,66 entao basta colocar quantos minutos gastou e o sistema calcula o valor final.
![serv](https://user-images.githubusercontent.com/55247088/116619139-79a28200-a916-11eb-94ca-c0ea1fc5765e.png)

**Comment by TK2KMG** [comment]
Fwsund, iria informar ele a mesma coisa , fiz isso aqui também. 
Mas a turma aqui é rápida em ajudar. Ainda bem. rsrs

**Comment by fwsund** [comment]
> Fwsund, iria informar ele a mesma coisa , fiz isso aqui também.
> Mas a turma aqui é rápida em ajudar. Ainda bem. rsrs

a turma aqui realmente ajuda muito... rsrs por isso retribuo da melhor forma possivel. Forte Abraço!

**Comment by viniciusjales** [comment]
Perfeito @fwsund ajudou bastante com minha dúvida, agradecido demais pela dica!! Abraços para a turma!
