### ISSUE TITLE
NÃO É BUG - Importar apenas meus clientes do BD (antigo MAPOS 3.8)

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#1367]
Estou importando minha tabela de clientes do antigo Mapos em formato CSV mas sempre que vou importar da esse erro.

Contador de colunas inválido no input CSV na linha 1.

OBS: Ja tentei com SQL, TXT e nada.

Alguém me diz uma outra forma de importar isso.

Obrigado desde já

**Comment by Pr3d4dor** [comment]
@brtechst Consegue colocar um print exato do erro e uma descrição mais detalhada?

Assim fica mais fácil em lhe ajudar.

**Comment by hoshikawakun** [comment]
utilize um programa chamado "Navicat for MySQL" para gerenciar o banco,
![Screenshot_122](https://user-images.githubusercontent.com/1253576/116631410-6f3eb300-a92b-11eb-9524-08d9041ed333.png)

Recomendo essa vers.

o DB antigo se ainda tiver ele, se não tiver cria uma DB e restaura ela, ai vc abre a DB ANTIGA e clica com botão direito na Tabela Clientes e seleciona Design Table, faça o mesmo na DB Nova
Organiza ali as colunas da TABELA original add as colunas que tem na TABELA NOVA e reorganizando a ordem dessas colunas
Feito isso vc so clica em Save, feito isso vc clica com botão direito novamente na TABELA ORIGINAL (Ja atualizada) e seleciona Dump SQL File, seleciona um lugar pra salvar e aguarde concluir a exportação
![Screenshot_117](https://user-images.githubusercontent.com/1253576/116630851-6bf6f780-a92a-11eb-995f-49d5321a744e.png)

Agora na Nova DB vc clica 
![Screenshot_116](https://user-images.githubusercontent.com/1253576/116630734-2e926a00-a92a-11eb-9ebc-3095136cd203.png)

Agora só arraste o arquivo SQL exportado para dentro da janela
Quando soltar selecione Copy Here
Quando tiver carregado vc clica 2x rapido no arquivo e ele vai aparecer
Delete tudo que estiver acima de

-- ----------------------------
-- Records 
-- ----------------------------
![Screenshot_118](https://user-images.githubusercontent.com/1253576/116631131-df990480-a92a-11eb-80ad-5b080bd19291.png)

oque vai deixar o arquivo somente com as entradas da Tabela
![Screenshot_119](https://user-images.githubusercontent.com/1253576/116631227-fc353c80-a92a-11eb-9929-4b5222b2f645.png)

Agora vc clica em 
![Screenshot_120](https://user-images.githubusercontent.com/1253576/116631256-0eaf7600-a92b-11eb-9c5b-3c29c7a1e045.png)

dependendo da quantidade de entradas vai demorar um tempo

quando vc ver essa janela
![Screenshot_121](https://user-images.githubusercontent.com/1253576/116631318-330b5280-a92b-11eb-8703-b6c892751b9e.png)

ja estara tudo pronto

Obs, faça isso apos somente uma instalação limpa pois pra funcionar a tabela clientes não pode ter nenhuma entrada

**Comment by brtechst** [comment]
> @brtechst Consegue colocar um print exato do erro e uma descrição mais detalhada?
> 
> Assim fica mais fácil em lhe ajudar.

Vou mandar aqui abaixo o erro sempre mas vou tentar a opção que o amigo ai @hoshikawakun sugeriu.



> utilize um programa chamado "Navicat for MySQL" para gerenciar o banco,
> ![Screenshot_122](https://user-images.githubusercontent.com/1253576/116631410-6f3eb300-a92b-11eb-9524-08d9041ed333.png)
> 
> Recomendo essa vers.
> 
> o DB antigo se ainda tiver ele, se não tiver cria uma DB e restaura ela, ai vc abre a DB ANTIGA e clica com botão direito na Tabela Clientes e seleciona Design Table, faça o mesmo na DB Nova
> Organiza ali as colunas da TABELA original add as colunas que tem na TABELA NOVA e reorganizando a ordem dessas colunas
> Feito isso vc so clica em Save, feito isso vc clica com botão direito novamente na TABELA ORIGINAL (Ja atualizada) e seleciona Dump SQL File, seleciona um lugar pra salvar e aguarde concluir a exportação
> ![Screenshot_117](https://user-images.githubusercontent.com/1253576/116630851-6bf6f780-a92a-11eb-995f-49d5321a744e.png)
> 
> Agora na Nova DB vc clica
> ![Screenshot_116](https://user-images.githubusercontent.com/1253576/116630734-2e926a00-a92a-11eb-9ebc-3095136cd203.png)
> 
> Agora só arraste o arquivo SQL exportado para dentro da janela
> Quando soltar selecione Copy Here
> Quando tiver carregado vc clica 2x rapido no arquivo e ele vai aparecer
> Delete tudo que estiver acima de
> 
> -- Records
> 
> ![Screenshot_118](https://user-images.githubusercontent.com/1253576/116631131-df990480-a92a-11eb-80ad-5b080bd19291.png)
> 
> oque vai deixar o arquivo somente com as entradas da Tabela
> ![Screenshot_119](https://user-images.githubusercontent.com/1253576/116631227-fc353c80-a92a-11eb-9929-4b5222b2f645.png)
> 
> Agora vc clica em
> ![Screenshot_120](https://user-images.githubusercontent.com/1253576/116631256-0eaf7600-a92b-11eb-9c5b-3c29c7a1e045.png)
> 
> dependendo da quantidade de entradas vai demorar um tempo
> 
> quando vc ver essa janela
> ![Screenshot_121](https://user-images.githubusercontent.com/1253576/116631318-330b5280-a92b-11eb-8703-b6c892751b9e.png)
> 
> ja estara tudo pronto
> 
> Obs, faça isso apos somente uma instalação limpa pois pra funcionar a tabela clientes não pode ter nenhuma entrada

Vou tentar meu querido, não manjo muito disso mas como você deixou bem explicado vou tentar, por sinal amei suas modificações e ja implementei elas do MasterOS, será para ele.

**Comment by brtechst** [comment]
Segue a situação só para os amigos terem ciência do que está acontecendo.

Segue banco novinho...

![image](https://user-images.githubusercontent.com/53625745/116693893-e78d8e80-a994-11eb-94bd-14788a8f3998.png)

Arquivo CSV extraido do antigo BD.

![image](https://user-images.githubusercontent.com/53625745/116694794-19532500-a996-11eb-8235-c7757ccddd33.png)

erro que acontece 

![image](https://user-images.githubusercontent.com/53625745/116694868-2f60e580-a996-11eb-951e-543b7d205759.png)

**Comment by hoshikawakun** [comment]
> Segue a situação só para os amigos terem ciência do que está acontecendo.
> 
> Segue banco novinho...
> 
> ![image](https://user-images.githubusercontent.com/53625745/116693893-e78d8e80-a994-11eb-94bd-14788a8f3998.png)
> 
> Arquivo CSV extraido do antigo BD.
> 
> ![image](https://user-images.githubusercontent.com/53625745/116694794-19532500-a996-11eb-8235-c7757ccddd33.png)
> 
> erro que acontece
> 
> ![image](https://user-images.githubusercontent.com/53625745/116694868-2f60e580-a996-11eb-951e-543b7d205759.png)
Mesmo com o programa que falei não funcionou?

**Comment by hoshikawakun** [comment]
Vc tem o DB antigo ainda?

**Comment by brtechst** [comment]
> Vc tem o DB antigo ainda?

Tenho sim, mas como disse não manjo bem de BD (sou curiosos e aprendo rápido) mas as vezes não tão rápido devido a necessidade.

baixei seu app que mandou mas estou meio perdido aqui kk

pelo CVS é uma linguagem mais fácil para mim.

**Comment by hoshikawakun** [comment]
> > Vc tem o DB antigo ainda?
> 
> Tenho sim, mas como disse não manjo bem de BD (sou curiosos e aprendo rápido) mas as vezes não tão rápido devido a necessidade.
> 
> baixei seu app que mandou mas estou meio perdido aqui kk
> 
> pelo CVS é uma linguagem mais fácil para mim.

CVS seria oque?

**Comment by hoshikawakun** [comment]
> > Vc tem o DB antigo ainda?
> 
> Tenho sim, mas como disse não manjo bem de BD (sou curiosos e aprendo rápido) mas as vezes não tão rápido devido a necessidade.
> 
> baixei seu app que mandou mas estou meio perdido aqui kk
> 
> pelo CVS é uma linguagem mais fácil para mim.

Se nao tiver problemas, vc me manda um zap que ti ajudo com o problema (62) 98405-4022

**Comment by brtechst** [comment]
> > > Vc tem o DB antigo ainda?
> > 
> > 
> > Tenho sim, mas como disse não manjo bem de BD (sou curiosos e aprendo rápido) mas as vezes não tão rápido devido a necessidade.
> > baixei seu app que mandou mas estou meio perdido aqui kk
> > pelo CVS é uma linguagem mais fácil para mim.
> 
> CVS seria oque?

CSV*

> > > Vc tem o DB antigo ainda?
> > 
> > 
> > Tenho sim, mas como disse não manjo bem de BD (sou curiosos e aprendo rápido) mas as vezes não tão rápido devido a necessidade.
> > baixei seu app que mandou mas estou meio perdido aqui kk
> > pelo CVS é uma linguagem mais fácil para mim.
> 
> Se nao tiver problemas, vc me manda um zap que ti ajudo com o problema (62) 98405-4022

Agora homi de Deus

**Comment by brtechst** [comment]
Problema resolvido.

Meu amigo @hoshikawakun me deu suporte via WhatsApp e me ajudou no problema.

Muito grato.
