### ISSUE TITLE
Cadastro de equipamentos vinculado aos clientes.

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#1369]
Seria muito interessante que pudéssemos cadastrar os equipamentos nas ordens de serviços e eles ficassem vinculados a cada cliente para que ao abrir uma próxima OS possamos escolher para qual equipamento será dado a nova entrada.

Ou seja, chegou equipamento ao selecionar cliente ja teria os equipamentos dele cadastrados evitando ter que digitar tudo de novo.

**Comment by wgiacomelli** [comment]
Vou deixar uma dica que pode ser útil, para contornar esse tipo de situação fiz um ajuste mais simples que já me ajuda muito, criei um campo Observação no cadastro de Clientes. 
![11](https://user-images.githubusercontent.com/37094545/116836397-b5e71400-ab9c-11eb-9b4c-ea2cde34cead.png)

**Comment by brtechst** [comment]
Boa @wgiacomelli ..

Vamos aguardar a implementação definitiva.

**Comment by brtechst** [comment]
@Pr3d4dor isso é possível?

**Comment by brtechst** [comment]
Alguém além do @Pr3d4dor ta ativo no projeto?

só vejo ele aqui direto respondendo o pessoal.

**Comment by Pr3d4dor** [comment]
O @willph também é ativo no projeto, tem uma PR que o @hoshikawakun fez, mas precisa de ajustes.

Estamos aguardando.
