### ISSUE TITLE
cadastro de produtos

### ISSUE THREAD

**Issue by SaghaZ** [RamonSilva20/mapos#1370]
boa tarde,, esses dias eu estava effetuando uma vende de teclado,
e ao digitar teclado vem varios que nao tenho mais em estoque ai veio a ideia de colocar no cadastro do produto a função "inativar"

e so uma ideia claro... pra a melhoria deste projeto que ja e incrivel.

**Comment by Pr3d4dor** [comment]
@SaghaZ Obrigado pela sugestão. 

Eu não me lembro, mas acho que se você colocar a quantidade em estoque como 0, ele não irá retornar na busca.

**Comment by SaghaZ** [comment]
aparece sim... testei rsrs
