### ISSUE TITLE
Erro na inicialização do comando do Docker

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#1371]
![image](https://user-images.githubusercontent.com/73778547/116799493-2c6a1000-aad0-11eb-94e8-45458e7cd296.png)
Depois que formatei meu notebook, não consigo mais rodar o sistema nele, não sei mais o que fazer, fucei a internet toda pra tentar resolver, mas sem sucesso

**Comment by Pr3d4dor** [comment]
Tentou mudar no dockerfile de php-fpm:7.4 para php-fpm?

**Comment by CarlosRezini** [comment]
Cara, eu não acredito que era somente isso, fiquei ontem das 15h ate as 23h tentando entender, nem consegui dormir direito kkk, mas cara vlw mesmo
![image](https://user-images.githubusercontent.com/73778547/116810127-416a9180-ab18-11eb-9005-e6bde138245a.png)

**Comment by CarlosRezini** [comment]
![Sem título](https://user-images.githubusercontent.com/73778547/116816487-7be42680-ab38-11eb-8878-3caea404da6d.png)
Só mudando de assunto, o servidor esta no notebook, mesma rede cabeada que meu pc, porque não recebo a logo da empresa quando vou imprimir a OS e também quando envia por email

**Comment by Pr3d4dor** [comment]
@CarlosRezini Para aparecer no email precisa ter um domínio e um site que tenha acesso público mesmo

**Comment by CarlosRezini** [comment]
@Pr3d4dor E em rede local?

**Comment by Pr3d4dor** [comment]
@CarlosRezini Em rede local também não aparece, pois o endereço da imagem deveria ser o ip do seu computador na rede local, mas no e-mail ficará 'localhost', por isso não aparece.
