### ISSUE TITLE
Como faço pra fazer varias Pull Requests

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1372]
Queria saber como faço pra poder fazer varias PR diferentes
Cada uma com alterações especificas sem afetar a que ja esta em andamento

Ex, faço uma PR com algumas Mods
ai vejo nas insues alguem pedindo um recurso bem interessante que seja facil fazer
Como faço para abrir outra PR somente com as alteraçoes da insue e sem as alteraçoes da PR que ja esta em andamento e sem que as novas Mod entrem na PR que ja esta em andamento

**Comment by Pr3d4dor** [comment]
@hoshikawakun Você tem que voltar para o branch original, no caso a master e criar outro branch e fazer a PR a partir dele.

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Você tem que voltar para o branch original, no caso a master e criar outro branch e fazer a PR a partir dele.

Muito Obrigado, Axo que consegui, vou fazer as mod aki e laçõ a PR

**Comment by augustocoletti** [comment]
@hoshikawakun , cara, como vc é bem prestativo quanto às solicitações do pessoal, gostaria de pedir algo que ja foi solicitado em varias issues mas até agora não foi implementado. Não tenho conhecimento para avaliar o grau de dificuldade, então, por favor não me julgue kkkk.
O caso é que o parcelamento de receitas e despesas é bem interessante de se ter na versão oficial e se posse possível implementar, ajudaria bastante.
Agradeço as contribuições!
