### ISSUE TITLE
Lançamentos - Filtrar serviços com emissão de NF 

### ISSUE THREAD

**Issue by wgiacomelli** [RamonSilva20/mapos#1374]
Criar um campo de controle para Vendas e Ordem de serviços em que foi emitido NF, pois em caso de MEi nem todos os trabalhos são emitidos NF, isso ajudaria bastante na gestão.

O campo já consegui criar e posso compartilhar se alguém mais tiver interesse, mas o problema que apenas consigo filtrar dentro das OS e não nos lançamentos, como posso fazer com que os dados adicionais sejam salvos também na tabela de lançamentos no momento que faturar?

![12](https://user-images.githubusercontent.com/37094545/116836704-f4c99980-ab9d-11eb-9e38-062400b5d628.png)

**Comment by hoshikawakun** [comment]
> 
> 
> Criar um campo de controle para Vendas e Ordem de serviços em que foi emitido NF, pois em caso de MEi nem todos os trabalhos são emitidos NF, isso ajudaria bastante na gestão.
> 
> O campo já consegui criar e posso compartilhar se alguém mais tiver interesse, mas o problema que apenas consigo filtrar dentro das OS e não nos lançamentos, como posso fazer com que os dados adicionais sejam salvos também na tabela de lançamentos no momento que faturar?
> 
> ![12](https://user-images.githubusercontent.com/37094545/116836704-f4c99980-ab9d-11eb-9e38-062400b5d628.png)

deixe-me ver se entendi, ao faturar a OS ele esta gerando nota fiscal ou e somente uma caixa de seleção que vc marca quando gera uma NF por fora referente akela OS?

**Comment by wgiacomelli** [comment]
Seria Isso mesmo,
é apenas uma caixa de seleção que serve para saber se foi gerado NF, a NF gero por fora e salvo em anexos, mas se eu precisar saber quanto foi faturado com NF seria facil, bastaria criar um filtro na consulta conforme segue  Ex: ' select * from lancamentos where emitir_nf = 1'

Minha dificuldade esta em gravar esse dado da OS na tabela lançamentos.

**Comment by hoshikawakun** [comment]
> 
> 
> Seria Isso mesmo,
> é apenas uma caixa de seleção que serve para saber se foi gerado NF, a NF gero por fora e salvo em anexos, mas se eu precisar saber quanto foi faturado com NF seria facil, bastaria criar um filtro na consulta conforme segue Ex: ' select * from lancamentos where emitir_nf = 1'
> 
> Minha dificuldade esta em gravar esse dado da OS na tabela lançamentos.

axo que pra funcionar envez do botão fica dentro da OS ele ficar na janela do faturamento, ai dentro da OS apareceria apenas informando que foi gerada nota

axo que esse e o unico jeito da info estar nos lancamentos, ou seja vc emite a nota e so depois vc fatura a OS selecionando o botão NF

**Comment by wgiacomelli** [comment]
Ao faturar os dados de data e valor são inseridos na tabela lançamentos, sabe como funciona esse processo?
