### ISSUE TITLE
erro na instalação

### ISSUE THREAD

**Issue by LucasPolli** [RamonSilva20/mapos#1375]
Senhores estou tendo problemas na instalação no hostgator, fiz os procedimentos, porem ao abrir a url aparece a seguinte mensagem:

Fatal error: Uncaught Error: Call to undefined function json_decode() in "path do meu site"/install/index.php:9 Stack trace: #0 {main} thrown in "path do meu site"/install/index.php on line 9

como resolver?

**Comment by hoshikawakun** [comment]
o composer eu faço o processo todo no PC antes pra fazer todo o download da pasta vendor, depois subo tudo na hospedagem e faço a instalação normalmente.
Obs: onde pede a URL sempre coloque **https://**

**Comment by LucasPolli** [comment]
nao creio ser problema com o composer, pois se eu mudo a versao do PHP para uma mais baixa, alterando o index.php na pasta install, ele instala normalmente, porem não executa depois, ai sim por causa do composer que requer php 7.2, depois de instalado, se eu altero a versao do php novamente para 7.3, ai buga tudo..
