### ISSUE TITLE
Criar campo em OS para pesquisar/editar uma Ordem pelo numero

### ISSUE THREAD

**Issue by juliobenassi** [RamonSilva20/mapos#1377]
Boa tarde,
Primeiramente parabéns pela dedicação de todos, esse software esta muito top!
Estou querendo fazer duas inclusões, uma acredito ser simples, outra nem tanto.

A primeira, simples, seria colocar um campo na pagina de OS onde pudesse filtrar/editar uma OS pelo seu numero. Onde eu preencheria o campo com o numero da OS e ele já abrisse a pagina de EDIÇÃO. Se alguém puder me dar uma luz agradeço muito.

A outra, é possível eu gerar um QRCode Pix no final de um relatório? Somando os valores que tenho em aberto de determinado cliente? Acontece que atendo alguns clientes e mando a cobrança no final do mês com a relação de todos atendimentos, facilitaria muito minha vida se ele gerasse esse QR para pagamento.

De antemão peço desculpas se falei besteira aqui, sou novato e estou aprendendo ainda.

Obrigado a todos.

**Comment by Pr3d4dor** [comment]
@juliobenassi Sobre o filtro da OS iremos colocar na lista de features junto com as demais que foram pedidas.

Sobre o QR code do pix, enquanto não tem essa feature no sistema você pode gerar o relatório e depois com o valor final usar esse site para gerar o QR code: https://www.gerarpix.com.br/

**Comment by hoshikawakun** [comment]
> A outra, é possível eu gerar um QRCode Pix no final de um relatório? Somando os valores que tenho em aberto de determinado cliente? Acontece que atendo alguns clientes e mando a cobrança no final do mês com a relação de todos atendimentos, facilitaria muito minha vida se ele gerasse esse QR para pagamento.
> 
> De antemão peço desculpas se falei besteira aqui, sou novato e estou aprendendo ainda.
> 
> Obrigado a todos.

Sobre essa parte de gerar um QRcode do PIX com o valor de todas as OS do cliente X não teria como colocar na pag de relatorio de OS?

Ao gerar um relatorio das OS de determinado cliente ja e mostrado o valor que da juntando todas akelas OS
![Screenshot_6](https://user-images.githubusercontent.com/1253576/117236088-64d65a80-adfe-11eb-897d-b4b04498e957.png)

Não seria mais pratico e talvez até facil de implementar para que ao final desse relatorio fosse gerado um QRcode do PIX cadastrado la no sistema?

**Comment by juliobenassi** [comment]
Amanhã vou tentar pegar o mesmo código existente na impressão da OS para usar no relatório. Seria isso mesmo, ele já dá a soma de todas pendências, só gerariam o qrcode no final de tudo.
Caso consiga, volto a postar.

**Comment by hoshikawakun** [comment]
> 
> 
> Amanhã vou tentar pegar o mesmo código existente na impressão da OS para usar no relatório. Seria isso mesmo, ele já dá a soma de todas pendências, só gerariam o qrcode no final de tudo.
> Caso consiga, volto a postar.

eu stou tentando a mesma coisa aki tmb

**Comment by hoshikawakun** [comment]
Estou tentando Add o QRcode do pix no relatorio de osCustom 
tem de se fazer entradas em **controllers>Relatorios.php** em **public function osCustom**
e em **models>Relatorios_model.php** add a função **public function getQrCode**

Ja fiz as Add mas não esta aparecendo o QRcode ainda
