### ISSUE TITLE
Estatistica de OS e Pagina Inicial

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#1378]
creio que seria melhor se em estatisticas de OS ao invez de aparecer dessa maneira
![Screenshot_5](https://user-images.githubusercontent.com/1253576/117235228-b4b42200-adfc-11eb-88ed-00ae7d6cf228.png)

um grafico que mostra apenas as porcentagens de cada tipo de OS ele mostrasse os tipos de status de OS e a quantidade de OS em cada um, dessa maneira
![Screenshot_4](https://user-images.githubusercontent.com/1253576/117235295-d90ffe80-adfc-11eb-85cc-25e2fdaa41f3.png)

Outra Alteração que seria interessante seria na pag inicial do sistema ao invez dakelas tabelas grandes que ocupam bastante espaço elas fossem organizadas dessa maneira
![Screenshot_2](https://user-images.githubusercontent.com/1253576/117235411-09f03380-adfd-11eb-8fab-4245a8b159e1.png)

e as OS que ainda estão dentro do praso estejam verdes e as que ja passaram do praso ficassem vermelhas?

Seria de grande ajuda tmb se tivesse algum lugar para cadastrar os tipos de equipamentos, Placa de Video, Notebook, PS3, PS4, Controle e por ai vai e na hora de abrir uma OS tiver um campo que possamos selecionar qual o tipo do equipamento

**Comment by brtechst** [comment]
Gostei da ideia, mais alguém ai que manja que possa ajudar nessas mudanças??

Seria muito mais válido dessa forma.

**Comment by edgarmeireles** [comment]
Acredito que nas estatísticas, o "Finalizado" não deveria aparecer (A não ser que isso seja contabilizado por período).

Instalei o MapOS para um amigo, o BD dele tem mais de 15k registros de OS, onde cerca de 95% está finalizada. Isso torna as demais OS Irrelevantes, uma vez que mal se enxerga os demais status.
