### ISSUE TITLE
Criação de boletos

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1379]
Bom dia a Todos,
Venho utilizando o sistema desde 2016 gerenciando minha assistencia, com esse sistema de boletos em cobrança seria possivel ao clicar em gerar boleto preencher a data de vencimento? Eu consegui alterando o arquivo payment_gateways mais não fica produtivo por exemplo criar boleto para 20 empresas com datas diferentes.
Agradeço a atenção de todos e parabenizo pelo trabalho.

**Comment by Pr3d4dor** [comment]
@cabralwms É possível mas iria requerer modificação no código.

**Comment by leofranklim** [comment]
Olá.
Tenho o sitema, amei, estou controlando minhas OS e financeiro.
Porem, eu configurei a integração com o mercado pago, mas quando tento excluir a cobrança e retorna uma tela com alguns codigos e sem retorno.

**Comment by Pr3d4dor** [comment]
@leofranklim Isso ocorre, porque dependendo do status o mercado pago não permite excluir
