### ISSUE TITLE
Campos a mais no cadastro de OS

### ISSUE THREAD

**Issue by Janio21** [RamonSilva20/mapos#138]
Olá,  Sou leigo no assunto , consegui adicionar busca de CEP , máscara nos campos CPF/Cnpj e outros . Mais tô tendo uma grande dificuldade para colocar mais campos no cadastro de os , quero usar o sistema na minha assistência de eletrônicos , aí preciso dos campos, APARELHO / MARCA / MODELO / NS .
Alguém já fez isso ?

**Comment by allanalcantara** [comment]
voce pode adicionar mais campos, indo em ::
Viewer/Cliente/addcliente

> 
> <div class="control-group">
>                         <label for="modelo" class="control-label">Modelo<span class="required">*</span></label>
>                         <div class="controls">
>                             <input id="modelo" type="text" name="modelo" value="<?php echo set_value('modelo'); ?>"  />
>                         </div>
>                     </div>
> <div class="control-group">
>                         <label for="aparelho" class="control-label">Aparelho<span class="required">*</span></label>
>                         <div class="controls">
>                             <input id="aparelho" type="text" name="aparelho" value="<?php echo set_value('aparelho'); ?>"  />
>                         </div>
>                     </div>
> 

nas funcções.
voce add também pra requerer verdadeiro (não deixar em branco)

Controller/Clientes
> você procura por : function adicionar()

adiciona a parte que deseja
exemplo:
> 'estado' => set_value('estado'),
>                 'cep' => set_value('cep'),
>                 'dataCadastro' => date('Y-m-d')
a parte do arquivo
ao add:

> 'estado' => set_value('estado'),
>                 'cep' => set_value('cep'),
>                 'aparelho' => set_value('aparelho'),
>                 'marca' => set_value('marca'),
>                 'modelo' => set_value('modelo'),
>                 'dataCadastro' => date('Y-m-d')


Ai voce add as colunas no banco de dados. 


e assim por diante.

**Comment by jeffsys** [comment]
Utilizo aqui na empresa um sistema em acess. Neste a impressão está padronizada para um formulário continuo. É possível usar o mapos para imprimir no mesmo formulário? Como faço para padronizar de forma que os campos fiquem iguais ao que já uso?
