### ISSUE TITLE
Função para desativar produtos descontinuados

### ISSUE THREAD

**Issue by DiegoKerr** [RamonSilva20/mapos#1387]
Sempre quando vou procurar produtos para adicionar a uma venda ou os aparece varios produtos antigos que não tem estoque e isso atrapalha para identificar o produto e tambem ter uma noção do que realmente tenho em estoque.

Acredito que se houvesse uma opção no ato do cadastro do produto, de desativar a visualização do produto ao zerar o estoque seria otimo.
![isue](https://user-images.githubusercontent.com/50930266/118051884-2a1d7680-b358-11eb-9d07-cbfedd98f391.png)

**Comment by cabralwms** [comment]
Antigamento o que estivesse sem estoque nao aparecia agora esta aparecendo mesmo sem estoque.
