### ISSUE TITLE
Erro ao realizar busca de produtos, clientes e serviços 

### ISSUE THREAD

**Issue by DiegoKerr** [RamonSilva20/mapos#1388]
Ao realizar uma busca de produtos, clientes e serviços observei que aparecem alguns produtos cadastrados que não consigo encontrar na aba reservada para produtos

Eu esperava que aparecesse na aba reservada para produtos pois eu desejava excluir alguns que foram lançados com erro e buscando fora de produtos não aparece a função excluir

realizando uma busca pela pesquisa geral
![Seqqq](https://user-images.githubusercontent.com/50930266/118053177-67830380-b35a-11eb-8755-2f9db4bb43e8.png)

realizando uma busca em produtos
![Seqqq](https://user-images.githubusercontent.com/50930266/118052804-c3995800-b359-11eb-9b13-5794d59026db.png)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10 64x
 - Navegador Google Chrome 
 - Versão Versão 90.0.4430.212 (Versão oficial) 64 bits

**Comment by jsfachini** [comment]
Tentou pesquisar pelo código do produto ?

**Comment by cabralwms** [comment]
Verifica ao cadastrar o produto se o senhor colocou entrada e saida as vezes não selecionou essas opções.

**Comment by DiegoKerr** [comment]
sim, mas não aparece.

Em qui, 13 de mai de 2021 10:51 AM, Jhonathan ***@***.***>
escreveu:

**Comment by DiegoKerr** [comment]
Bom dia, vim no produto confirmar e vi que selecionei sim. acredito que
esse produto seja de versões anteriores do mapos. não sei se pode ter
relação com isso..

Em sex, 14 de mai de 2021 9:34 AM, cabralwms ***@***.***>
escreveu:
