### ISSUE TITLE
Bug na agenda

### ISSUE THREAD

**Issue by Gilbertogc39** [RamonSilva20/mapos#1389]
** Descreva o bug **
A Agenda não apresenta outros resultados de chamados Abertos e ou outros resultados. Somente apresenta o primeiro chamado criado.

**Reproduzir**
Quando se colocar na busca também não traz o resultado.
![Erro na agenda - os](https://user-images.githubusercontent.com/20045421/118129404-802f0000-b3d2-11eb-981b-141d7a23acf5.png)
![Erro na agenda](https://user-images.githubusercontent.com/20045421/118129406-80c79680-b3d2-11eb-9702-a0a615ad906e.png)

** Capturas de tela **
Duas Telas em anexo.

** Desktop (preencha as seguintes informações): **
 - SO: Qualquer um
 - Navegador Chrome
 - Versão 90

**Comment by hoshikawakun** [comment]
quando tem mais de uma OS no mesmo dia ele aparece da seguinte forma
![Screenshot_7](https://user-images.githubusercontent.com/1253576/119264144-4ae79680-bbb8-11eb-9d29-fad404c12b75.png)

e ao clicar em **"mais"** ele abre essa nova parte mostrando as OS daquele dia
![Screenshot_8](https://user-images.githubusercontent.com/1253576/119264196-84b89d00-bbb8-11eb-9458-90fc457cc963.png)

**Comment by Gilbertogc39** [comment]
No Meu somente aparece uma única a primeira e mais nenhuma.

**Comment by Gilbertogc39** [comment]
![Captura de tela 2021-05-24 111205](https://user-images.githubusercontent.com/20045421/119360530-17bd0a00-bc81-11eb-8d9e-349b83479d9a.jpg)

**Comment by Pr3d4dor** [comment]
@Gilbertogc39 Você está com o mapos atualizado?

**Comment by Gilbertogc39** [comment]
Sim ... 
![2021-05-25 135408](https://user-images.githubusercontent.com/20045421/119537749-c08e6680-bd60-11eb-83a9-8961983e62fd.jpg)

**Comment by willph** [comment]
> Sim ...
> ![2021-05-25 135408](https://user-images.githubusercontent.com/20045421/119537749-c08e6680-bd60-11eb-83a9-8961983e62fd.jpg)

A mais recente é a 4.33.1
