### ISSUE TITLE
Problema nas permissões do usuario

### ISSUE THREAD

**Issue by adriano2290** [RamonSilva20/mapos#1391]
Gostaria de uma ajuda, peço desculpas se estou no lugar errado. Criei dois usuários no MapOS, quando atualizei a páginas o meu usuário que é o master ficou como o usuário com menos permissões. Não consigo mais editar as permissões a partir disso e não consigo resolver. Se alguém poder me dar uma luz?

**Comment by microreis** [comment]
basta atualizar a tabela de usuário em permissoes_id 1.
![image](https://user-images.githubusercontent.com/23633030/119162122-67f15d80-ba30-11eb-9b55-aa440f8308b4.png)
e na tabela permissoes
![image](https://user-images.githubusercontent.com/23633030/119162303-94a57500-ba30-11eb-916d-5a0993dd566d.png)
cole  a:38:{s:8:"aCliente";s:1:"1";s:8:"eCliente";s:1:"1";s:8:"dCliente";s:1:"1";s:8:"vCliente";s:1:"1";s:8:"aProduto";s:1:"1";s:8:"eProduto";s:1:"1";s:8:"dProduto";s:1:"1";s:8:"vProduto";s:1:"1";s:8:"aServico";s:1:"1";s:8:"eServico";s:1:"1";s:8:"dServico";s:1:"1";s:8:"vServico";s:1:"1";s:3:"aOs";s:1:"1";s:3:"eOs";s:1:"1";s:3:"dOs";s:1:"1";s:3:"vOs";s:1:"1";s:6:"aVenda";s:1:"1";s:6:"eVenda";s:1:"1";s:6:"dVenda";s:1:"1";s:6:"vVenda";s:1:"1";s:8:"aArquivo";s:1:"1";s:8:"eArquivo";s:1:"1";s:8:"dArquivo";s:1:"1";s:8:"vArquivo";s:1:"1";s:11:"aLancamento";s:1:"1";s:11:"eLancamento";s:1:"1";s:11:"dLancamento";s:1:"1";s:11:"vLancamento";s:1:"1";s:8:"cUsuario";s:1:"1";s:9:"cEmitente";s:1:"1";s:10:"cPermissao";s:1:"1";s:7:"cBackup";s:1:"1";s:8:"rCliente";s:1:"1";s:8:"rProduto";s:1:"1";s:8:"rServico";s:1:"1";s:3:"rOs";s:1:"1";s:6:"rVenda";s:1:"1";s:11:"rFinanceiro";s:1:"1";}

**Comment by adriano2290** [comment]
Desculpa ainda estou iniciando na vida de programador, não sei quase nada. Onde encontro estas tabelas, não estou conseguindo

**Comment by microreis** [comment]
se estiver servidor local 
http://localhost/phpmyadmin/nome do seu banco de dados/ tabela usuário 
http://localhost/phpmyadmin/  nome do seu banco de dados/ tabela permissoes

se estiver servidor web
http://seusite.com.br:2083/ nome do seu banco de dados/ tabela usuário 
http://seusite.com.br:2083/ nome do seu banco de dados/ tabela permissoes

**Comment by adriano2290** [comment]
Muito obrigado mesmo! vocês são F****

**Comment by hoshikawakun** [comment]
eu utilizo um programa no PC pra gerenciar a DB remotamente, Navicat for MySQL
