### ISSUE TITLE
OS -Serviços - Ocorreu um erro ao tentar adicionar serviço

### ISSUE THREAD

**Issue by roviglio** [RamonSilva20/mapos#1392]
** Não busca e não salva o valor do serviço na Os**
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para ordem de serviço 'Adcione uma ordem de teste'
2. Clique em continuar''
3. Na ordem de serviço clique na aba serviços' adcione um serviço e valor'
4. Vera o  erro "Atenção , Ocorreu um erro ao tentar adicionar serviço

**Comportamento esperado**
Que salva-se o valor do serviço para aquela OS

** Capturas de tela **
![ERRO](https://user-images.githubusercontent.com/84595434/119194584-b0714100-ba59-11eb-8b0c-77ea0a61dc85.jpg)
![ERRO2](https://user-images.githubusercontent.com/84595434/119194595-b36c3180-ba59-11eb-8d80-0c2168e1afc8.jpg)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Crome
 - Versão  90.0.4430.212 (Compilação oficial) (64 bits)

** Contexto adicional **
O mesmo erro ocorre na versão 4.31.0

**Comment by microreis** [comment]
Você colocou a quantidade?

**Comment by roviglio** [comment]
Desculpe o mesmo erro ocorre na versão 4.32.1 e na versão 4.32.0 
A versão 4.31.1 esta funcionando bem.

**Comment by roviglio** [comment]
Muito obrigado por responder.
Sim eu coloquei o valor, mas não salva.
Fui instalando versões anteriores quando chegou na versão 4.31.1
Desta vez sem querer usei o nome "teste" para o serviço e tentei salvar o serviço na aba "serviço da OS" e salvou.
Sai da versão 4.31.1 voltei na versão corrente e toquei o nome longo do serviço pelo curto e funcionou normalmente.

Atenciosamente.
Oliveira.

RWO-Roviglio Wanderley Oliveira
Tel.: (15) 96299068
***@***.******@***.***>

[http://www.oliveira.clientewebhost.com.br/portal/timbrado/LOGO247x104-PNG.png]<http://www.oliveira.clientewebhost.com.br/>

________________________________
De: MRIE ***@***.***>
Enviado: sexta-feira, 21 de maio de 2021 17:52
Para: RamonSilva20/mapos ***@***.***>
Cc: roviglio ***@***.***>; Author ***@***.***>
Assunto: Re: [RamonSilva20/mapos] OS -Serviços - Ocorreu um erro ao tentar adicionar serviço (#1392)


Você colocou a quantidade?
