### ISSUE TITLE
Sistema fiscal?

### ISSUE THREAD

**Issue by GuilhermeDischer** [RamonSilva20/mapos#1393]
O sistema seria fiscal, ou seria apenas para controle não fiscal?

**Comment by Pr3d4dor** [comment]
@GuilhermeDischer Apenas para controler interno de vendas, ordens de produtos, produtos, serviços e clientes. Como a parte fiscal varia muito de cidade à cidade, o sistema não emite NF.

**Comment by GuilhermeDischer** [comment]
> @GuilhermeDischer Apenas para controler interno de vendas, ordens de produtos, produtos, serviços e clientes. Como a parte fiscal varia muito de cidade à cidade, o sistema não emite NF.

Então o que seria o relatório de MEI, comecei a dar uma testada com aqui e vi isto é fiquei com medo kkk. Então, tudo o que é feito não precisa mandar pra contabilidade nade né?

**Comment by Pr3d4dor** [comment]
o Relatório MEI apenas gera aquele relatório que auxilia o MEI ao realizar a declaração de imposto, mas não é obrigatório usar. Tanto que o relatório é gerado como se todas as entradas e saídas fossem feitas sem emissão de NF.
