### ISSUE TITLE
Acessa no Windows mas nao acessa no Linux

### ISSUE THREAD

**Issue by vessc** [RamonSilva20/mapos#1395]
** Descreva o bug **
Quando acesso o mapos pelo windows, tanto 7 como 10 em qualquer navegador, o acesso e utilização ocorre normalmente.
Quando acesso de um pc com Linux, utilizando os mesmos navegadores, nao consigo acesso ao sistema ( erro dns )

**Reproduzir**
Etapas para reproduzir o comportamento:
O erro ja logo quando acessa o link server:8000

**Comportamento esperado**
gostaria que acessasse igual no linux assim como acesso no windows

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 
** Contexto adicional **
Todos os pcs estao ligados a mesma rede e nao possui firewall, nem proxy, nem restrição alguma
Não temos AD nem qualquer tipo de controle que seja.

**Comment by Pr3d4dor** [comment]
@vessc Isso não é um bug do mapos e talvez seja problema de alguma configuração interna na sua rede. O PC com Linux realmente está conectado na rede local?

**Comment by vessc** [comment]
Eu fiz todos os testes possíveis dentro do meu conhecimento.
Inclusive, instalei dentro do Linux Mint um VIrtualbox e dentro dele instalei o Windows 7, e na VM abre o sistema e no linux nao. [https://scontent.fcgh37-1.fna.fbcdn.net/v/t1.6435-9/188419054_1662855910567135_3138724952127129237_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=dbeb18&_nc_ohc=u4uM3kESGmoAX-Qp2A8&_nc_ht=scontent.fcgh37-1.fna&oh=d0f593bc9b87e873a332576119eb5fc9&oe=60D1914A](url)

**Comment by vessc** [comment]
teste 1 efetuado em Linux Mint 20.1 Cinamon
teste 2 efetuado em Linux Mint 20.1 Xfce
teste 3 efetuado em Linux Manjaro

- efetuei novos testes, deixando IP, Mascara e dns Manual.
- navegadores testados: Firefox, CHrome, Chromium, Tor, Web, todos deram a mesma mensgem.
- também instalei wine e playonlinux rodando Internet Explorer ( sem sucesso )
- Liberei portas do firewall ( do servidor mapos )
- mudei o mapos de diretorio, 
## Obs: se eu acessar http://192.168.20.150:8080/ - ele carrega  phpmyadmin mas o MAPOS nao abre por nada

Todos os pcs com windows testados OK, mas Linux e Android nao acessa por nada desse mundo.

nao manjo nada do sistema e nem de linux, apenas fui pesquisando e tentando tudo, mas infelizmente nao deu certo.

**Comment by Pr3d4dor** [comment]
@vessc Vou tentar simular esse problema e te retorno.

**Comment by willph** [comment]
> teste 1 efetuado em Linux Mint 20.1 Cinamon
> teste 2 efetuado em Linux Mint 20.1 Xfce
> teste 3 efetuado em Linux Manjaro
> 
> * efetuei novos testes, deixando IP, Mascara e dns Manual.
> * navegadores testados: Firefox, CHrome, Chromium, Tor, Web, todos deram a mesma mensgem.
> * também instalei wine e playonlinux rodando Internet Explorer ( sem sucesso )
> * Liberei portas do firewall ( do servidor mapos )
> * mudei o mapos de diretorio,
> 
> ## Obs: se eu acessar http://192.168.20.150:8080/ - ele carrega phpmyadmin mas o MAPOS nao abre por nada
> Todos os pcs com windows testados OK, mas Linux e Android nao acessa por nada desse mundo.
> 
> nao manjo nada do sistema e nem de linux, apenas fui pesquisando e tentando tudo, mas infelizmente nao deu certo.

Qual link está configurado em config.php na linha 42 config['base_url'] =

**Comment by vessc** [comment]
> > teste 1 efetuado em Linux Mint 20.1 Cinamon
> > teste 2 efetuado em Linux Mint 20.1 Xfce
> > teste 3 efetuado em Linux Manjaro
> > 
> > * efetuei novos testes, deixando IP, Mascara e dns Manual.
> > * navegadores testados: Firefox, CHrome, Chromium, Tor, Web, todos deram a mesma mensgem.
> > * também instalei wine e playonlinux rodando Internet Explorer ( sem sucesso )
> > * Liberei portas do firewall ( do servidor mapos )
> > * mudei o mapos de diretorio,
> > 
> > ## Obs: se eu acessar http://192.168.20.150:8080/ - ele carrega phpmyadmin mas o MAPOS nao abre por nada
> > Todos os pcs com windows testados OK, mas Linux e Android nao acessa por nada desse mundo.
> > nao manjo nada do sistema e nem de linux, apenas fui pesquisando e tentando tudo, mas infelizmente nao deu certo.
> 
> Qual link está configurado em config.php na linha 42 config['base_url'] =

bom dia, eu tive que procurar em todos os diretorios esse arquivo, pois nao sabia onde estava, e encontrei em: 
  - mapos-master/application/config 
  - Na linha 42 --> : $config['base_url'] = 'http://server:8000/';

**Comment by vessc** [comment]
Uma OBS: quando acesso do pc com linux 192.168.20.150:8000 
  dentro do servidor, na tela fica monitrando ( depois do comando ...recreate) , ele da mensagem de que o pc 192.168.20.105 esta acessando " ---->> 

   nginx         | 192.168.20.105 - - [28/May/2021:14:10:28 +0000] "GET / HTTP/1.1" 307 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
<< ----

**Comment by willph** [comment]
> Uma OBS: quando acesso do pc com linux 192.168.20.150:8000
> dentro do servidor, na tela fica monitrando ( depois do comando ...recreate) , ele da mensagem de que o pc 192.168.20.105 esta acessando " ---->>
> 
> nginx | 192.168.20.105 - - [28/May/2021:14:10:28 +0000] "GET / HTTP/1.1" 307 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
> << ----

Faz um teste. Coloca um IP fixo na linha 42. Da máquina onde está o Mapos rodando.

Depois diz o que deu

**Comment by willph** [comment]
Usando Docker?

**Comment by vessc** [comment]
> > Uma OBS: quando acesso do pc com linux 192.168.20.150:8000
> > dentro do servidor, na tela fica monitrando ( depois do comando ...recreate) , ele da mensagem de que o pc 192.168.20.105 esta acessando " ---->>
> > nginx | 192.168.20.105 - - [28/May/2021:14:10:28 +0000] "GET / HTTP/1.1" 307 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
> > << ----
> 
> Faz um teste. Coloca um IP fixo na linha 42. Da máquina onde está o Mapos rodando.
> 
> Depois diz o que deu

kkkkkkkkkkk....funcionou...kkkkkkkkkk q da hora, só q agora nao loga no windows, somente colocando IPe porta.
eu poderia criar uma outra linnha igual colocando o host também? ou vai dar chabu, senao deixo assim mesmo...
Fico show de bola.

**Comment by vessc** [comment]
> > > Uma OBS: quando acesso do pc com linux 192.168.20.150:8000
> > > dentro do servidor, na tela fica monitrando ( depois do comando ...recreate) , ele da mensagem de que o pc 192.168.20.105 esta acessando " ---->>
> > > nginx | 192.168.20.105 - - [28/May/2021:14:10:28 +0000] "GET / HTTP/1.1" 307 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
> > > << ----
> > 
> > 
> > Faz um teste. Coloca um IP fixo na linha 42. Da máquina onde está o Mapos rodando.
> > Depois diz o que deu
> 
> kkkkkkkkkkk....funcionou...kkkkkkkkkk q da hora, só q agora nao loga no windows, somente colocando IPe porta.
> eu poderia criar uma outra linnha igual colocando o host também? ou vai dar chabu, senao deixo assim mesmo...
> Fico show de bola.

ai...eu fui no meu /etc/ e editei o arquivo "hosts" com: vim /etc/hosts e adicionei uma linha no arquivo com IP e NOME do server
  ->    192.168.20.150       server
  Agora ele esta indo pelo digitando server:8000 sem digitar o IP.
  
  Enfim, eu poderia ter evitado todo esse transtorno simplesmente adicionando essa linha no MEU arquivo "/etc/hosts"
  
  Ficou assim o arquivo "hosts"
  
127.0.0.1       localhost
127.0.1.1       orlandopc
192.168.20.150  server

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
~                   

ESPERO QUE ISSO AJUDE FUTUROS PROBLEMAS COM PESSOAS SEM CONHECIMENTO COMO EU.

Agora esta tudo tranquilo pessoal..... muito obrigado dimais ai pela atenção que vcs me deram...
e eu to aprendendo usar o sistema e estou gostando bastante.

MAIS UMA VEZ, MUITO OBRIGADO

podemos encerrar esta solicitação....

**Comment by vessc** [comment]
Bem vamos lah....

ai...eu fui no meu /etc/ e editei o arquivo "hosts" com: vim /etc/hosts e adicionei uma linha no arquivo com IP e NOME do server
-> 192.168.20.150 server
Agora ele esta indo pelo digitando server:8000 sem digitar o IP.

Enfim, eu poderia ter evitado todo esse transtorno simplesmente adicionando essa linha no MEU arquivo "/etc/hosts"

Ficou assim o arquivo "hosts"

127.0.0.1 localhost
127.0.1.1 orlandopc
192.168.20.150 server
The following lines are desirable for IPv6 capable hosts

::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
~

ESPERO QUE ISSO AJUDE FUTUROS PROBLEMAS COM PESSOAS SEM CONHECIMENTO COMO EU.

Agora esta tudo tranquilo pessoal..... muito obrigado dimais ai pela atenção que vcs me deram...
e eu to aprendendo usar o sistema e estou gostando bastante.

MAIS UMA VEZ, MUITO OBRIGADO

podemos encerrar esta solicitação....

**Comment by willph** [comment]
De nada.

Qualquer coisa tem o grupo do Mapos 

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

E na descrição do grupo tem o Telegram caso queira.

**Comment by vessc** [comment]
> De nada.
> 
> Qualquer coisa tem o grupo do Mapos
> 
> https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
> 
> E na descrição do grupo tem o Telegram caso queira.

Opa, esta adicionado, muito obrigado!
