### ISSUE TITLE
Uma tela de login para vários bancos de dados

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#1396]
Não sei se me expressei bem no título, mas minha dúvida é a seguinte:

Possuo 3 empresas com nomes diferentes em segmentos parecidos, como seria possível apenas uma tela de LOGIN mas quando a loja entrar com seu cadastro (e-mail/senha) automaticamente ela só tem acesso ao banco de dados referente a ela (cadastros, clientes, etc).

Como isso seria possível?

**Comment by hoshikawakun** [comment]
gostei da ideia, e gostaria de dar uma dica,
dentro do sistema apresentar estatísticas das outras DB
Loja 1 5000 produtos, 300 OS, 15000 clientes
Loja 2 2000 produtos, 1200 OS, 11000 clientes
Loja 3 4000 produtos, 80 OS, 14000 clientes

e apresentar nas estatisticas de OS de cada banco quantas OS de cada tipo possue

**Comment by brtechst** [comment]
@hoshikawakun 

exatamente nessa perspectiva.

Acredito que teria que ser uma mudança com relação em hierarquias para que isso fosse possível.

**Comment by Pr3d4dor** [comment]
@brtechst Não acho interessante colocar isso no mapos, pois a premissa do mapos é de ser simples e de fácil uso. Por isso acho que o ideal é você customizar o seu mapos mesmo.

**Comment by hoshikawakun** [comment]
> 
> 
> @brtechst Não acho interessante colocar isso no mapos, pois a premissa do mapos é de ser simples e de fácil uso. Por isso acho que o ideal é você customizar o seu mapos mesmo.

mas isso seria possivel de ser feito correto

para facilitar vou exemplificar melhor a ideia

penso da seguinte forma

na tela de login tem uma opção para escolher qual DB vc vai utilizar
so que essa opção só vai aparecer caso no **"database.php"** esteja configurado as outras DB

E em Estatisticas do Sistema ele mostrar alem da estatistica da DB em uso mostrar a das outras DB caso esteja configurado no **"database.php"**

e por fim em **"Estatísticas de OS"** ele apresentar os graficos das outras DB so que ao invez de mostrar em % mostrar ja o numero real de quantas OS tem de cada tipo, isso claro caso esteja configurado no **"database.php"**

**Comment by brtechst** [comment]
> @brtechst Não acho interessante colocar isso no mapos, pois a premissa do mapos é de ser simples e de fácil uso. Por isso acho que o ideal é você customizar o seu mapos mesmo.

Olá @Pr3d4dor, acho que na programação talvez seja mais complicado fazer isso, no entanto, acredito que isso não deixará sistema mais complexo, pelo contrário, deixará mais funcional para a necessidade de empresas um pouquinho maiores.

Acredito que a verdadeira complexidade é dentro do sistema em si, nesse aspecto o Mapos se sai muito bem por ser simples de manuseio.

**Comment by microreis** [comment]
@Pr3d4dor Concordo que tem que manter a simplicidade do sistema, mas a função para que estão querendo não meche muito na base.
@hoshikawakun não necessita ter vários banco de dados e sim somente um com um cambo em cada tabela referenciando a "loja".
Minha opinião que pode ser feito as mudança não são tão complicadas, mas da trabalho, para a realidade atual do sistema @Pr3d4dor tem razão seria bom realizar as próprias modificações independentes, mas a ideia é muito boa para agregar algo mais a frente com este tipo de lógica.

Para você ter um norte em fazer estas mudanças @brtechst crie uma tb_lojas, e em todas as tabelas a referencie puxando assim de acordo com a loja cadastrada "login_da_loja" e suas permissões.  como falei simples, mais é muito trabalho.

**Comment by brtechst** [comment]
@microreis rapaz eu to começando a entender isso de banco de dados.

Para ser sincero ainda não sei bem como fazer essas coisinhas kkkk.

**Comment by brtechst** [comment]
Acredito que se a ideia for levada a frente vai ajudar muita gente que também precisa de algo assim.

Literalmente vai unir uma função muito bacana + a simplicidade do Mapos = Sistema perfeito para necessidades básicas.

**Comment by cabralwms** [comment]
Eu vi alguem no grupo do whatsapp falando sobre um projetos para ter filiais acho que esse é o caso que foi falado aqui. procura no grupo eu tenho quase certeza que alguem já fez algo assim.

**Comment by brtechst** [comment]
tem link do grupo?

**Comment by Pr3d4dor** [comment]
@brtechst https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
