### ISSUE TITLE
Administrador não é criado na versão 4.33.0

### ISSUE THREAD

**Issue by GuilhermeDischer** [RamonSilva20/mapos#1398]
Fui testar a nova versão, e na instalação meu usuário não foi criado no banco

**Reproduzir**
Etapas para reproduzir o comportamento:
Instalação do MapOS, na seção do administrador

**Comportamento esperado**
Criação do Administrador

** Capturas de tela **
Não Possui

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Google Chrome
 - Versão MapOS v4.33

**Comment by GuilhermeDischer** [comment]
@Pr3d4dor testei novamente e o adm não foi criado

**Comment by brtechst** [comment]
Amigo instalei aqui no meu servidor a versão nova e foi de boa o administrador.

refaz o processo do zero, pode ter sido um bug no caminho.

**Comment by GuilhermeDischer** [comment]
@brtechst Testei 2 vezes já e nada

**Comment by brtechst** [comment]
Rapaz tem que deletar o antigo BD e recriar um do zero.

Refazer a importação do BD e reupar os arquivos do zero na pasta.

aqui foi de primeira fazendo assim.

**Comment by GuilhermeDischer** [comment]
Foi exatamente isto que eu fiz

**Comment by willph** [comment]
bug banco.sql #1401 
 
 PR ja feita com a correção

**Comment by GuilhermeDischer** [comment]
Valeu
