### ISSUE TITLE
Instalação no debian, sei que não deve ser bug, só preciso de ajuda.

### ISSUE THREAD

**Issue by PU2JNP** [RamonSilva20/mapos#1399]
Estou tentando instalar no debian, mas sempre da erro na hora de adicionar URL. Segue erro:
php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by Pr3d4dor** [comment]
@PU2JNP Usando docker ou instalando manualmente?

**Comment by cabralwms** [comment]
Eu tenho um servidor debian no que puder ajudar so me chamar.

**Comment by PU2JNP** [comment]
> @PU2JNP Usando docker ou instalando manualmente?

Manualmente, tentando rodar em um raspberry, quero ver se ele suporta, pois é uma maquina que estava parada e vai gastar pouca energia.

**Comment by PU2JNP** [comment]
@cabralwms, não sei o que faltou, mas deu esse erro, algo errado com o localhost

**Comment by cabralwms** [comment]
Acredito ser erro em alguma configuração de rede. ou ate mesmo no PHP do apache

**Comment by PU2JNP** [comment]
@cabralwms você ideia de algo que eu possa fazer para testar?

**Comment by PU2JNP** [comment]
esse é meu hosts, ip da maquina é o 192.168.15.19
127.0.0.1   localhost
127.0.1.1   orangepipc
::1         localhost orangepipc ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters

**Comment by PU2JNP** [comment]
@cabralwms php e apache2 ok.

**Comment by cabralwms** [comment]
Qual Debian está em uso?

**Comment by cabralwms** [comment]
Permissões ok tambem, conseguiu testar o apache2 com o phpinfo.php?

**Comment by cabralwms** [comment]
Desabilita o IPV6 só para teste

**Comment by PU2JNP** [comment]
5.10.21-sunxi
desabilitei ipv6 e não deu tbm.
permissão ok

**Comment by PU2JNP** [comment]
![2021-05-25](https://user-images.githubusercontent.com/64419790/119548014-28967a00-bd6c-11eb-8ba3-9aa01bf9ca05.png)

**Comment by cabralwms** [comment]
resolvido

**Comment by vessc** [comment]
> resolvido

resolveu como?
