### ISSUE TITLE
CRON não funciona na HOSTINGER

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#1400]
ATENÇÃO, NÃO É BUG DO MAPOS.

Não consigo fazer esse CRON funcionar na hostinger, to fazendo certinho mas só retorna vázio la no HPanel

![image](https://user-images.githubusercontent.com/53625745/119410969-05ae8c00-bcc0-11eb-8360-6c548561d21c.png)

Emitente ta com email certo (não é google) e ta tudo configurado de acordo com o provedor.
ja tentei TLS e SSL e nada.

la no email.php ta o mesmo email do emitente.

Alguém ai conseguiu na HOSTINGER???

**Comment by Pr3d4dor** [comment]
@brtechst Infelizmente não tenho nada hospedado na hostinger para testar, já tentou entrar em contato com o suporte deles?

Na pasta application/logs existe algum log?

**Comment by marllonferreira** [comment]
> ATENÇÃO, NÃO É BUG DO MAPOS.
> 
> Não consigo fazer esse CRON funcionar na hostinger, to fazendo certinho mas só retorna vázio la no HPanel
> 
> ![image](https://user-images.githubusercontent.com/53625745/119410969-05ae8c00-bcc0-11eb-8360-6c548561d21c.png)
> 
> Emitente ta com email certo (não é google) e ta tudo configurado de acordo com o provedor.
> ja tentei TLS e SSL e nada.
> 
> la no email.php ta o mesmo email do emitente.
> 
> Alguém ai conseguiu na HOSTINGER???

conseguiu resolver ?

**Comment by brtechst** [comment]
Ainda não @marllonferreira 

@Pr3d4dor  ja vi com eles mas eles só dizem que o CRON ta OK mas ele está obtendo uma resposta vazia da aplicação PHP.

**Comment by brtechst** [comment]
@Pr3d4dor verifiquei aqui no log.php e não tem nada relacionado a e-mail.

**Comment by brtechst** [comment]
@Pr3d4dor onde eu encontro esse arquivo "email/process" e "email/retry"?

![image](https://user-images.githubusercontent.com/53625745/120482635-ae777e00-c387-11eb-9924-1bbc506581ec.png)

O carinha da hostinger falou que poderia ser a permissão do arquivo index.php (e eu fiz a alteração que ele mandou para ativar o executar) só que continua na mesma.

tem algum outro arquivo que eu posso da permissão de executar?

**Comment by brtechst** [comment]
GALERAAAAAA RESOLVIIIIIIIIIIII

Seguinte, segundo o atendente lá o caminho estava correto mas com uma AMBIGUIDADE então ele me disse o caminho certo que seria esse da IMAGEM ABAIXO

![image](https://user-images.githubusercontent.com/53625745/120521230-18ede580-c3ab-11eb-85aa-d87576b0d26b.png)

é só fazer igualzinho o meu alterando as informações de acordo com o de vocês ai.

![image](https://user-images.githubusercontent.com/53625745/120521326-36bb4a80-c3ab-11eb-8ad1-835385b8a237.png)

o ÚNICO ERRO PELO QUE PERCEBI AGORA é só a LOGO que não aparece

![image](https://user-images.githubusercontent.com/53625745/120521868-69654300-c3ab-11eb-852c-90d53daa1dd0.png)

@Pr3d4dor alguma coisa que eu possa fazer??

OBS: Sistema ja tem LOGO.

**Comment by Pr3d4dor** [comment]
@brtechst A imagem não aparece porque provavelmente a URL dela não é pública.

**Comment by brtechst** [comment]
APENAS PARA EXPLICAR CASO ALGUÉM NÃO ENTENDA

![image](https://user-images.githubusercontent.com/53625745/120523491-530bb700-c3ac-11eb-82eb-f98546790a6c.png)

AS 3 SETINHAS NA ORDEM SÃO

USUÁRIO: Esse usuário é automático e fornecido pela hostinger
DOMAIN: No meu caso é que eu tenho 2 domínios nessa hospedagem (por isso tem essa pasta)
DOMINIO: Domínio onde o seu sistema vai está.

OBRIGADO A TODOS!!!!



> @brtechst A imagem não aparece porque provavelmente a URL dela não é pública.

Como faço para deixar ela pública? A única coisa que fiz foi deixar ela la dentro da pasta padrão.

**Comment by brtechst** [comment]
@Pr3d4dor agradeço se puder ajudar como faço para deixar ela pública.

**Comment by Pr3d4dor** [comment]
@brtechst No momento eu não consigo ajudar pois estou no trabalho, somente de noite poderei ajudar.

**Comment by brtechst** [comment]
Ta certo @Pr3d4dor eu te agradeço demais.

Um excelente trabalho.

**Comment by brtechst** [comment]
Uma outra coisa antes que eu esqueça é que tive que alterar as permissões do arquivo INDEX.PHP na raiz.

![image](https://user-images.githubusercontent.com/53625745/120530387-d5e44000-c3b3-11eb-82d2-d46ed6d17925.png)

**Comment by brtechst** [comment]
Problema foi resolvido da imagem.

Simplesmente era o e-mail que estava bloqueando a imagem.
