### ISSUE TITLE
Alteracao do arquivo adicionarOS.php

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#1402]
@Pr3d4dor  o que acha de usar um script para calcular a data final automaticamente? Eu uso aqui para calcular 7 dias e acrecentar 2 dias quando a data final da no sabado e 1 dia quando  a data da  no domingo. Se quiser posso fazer uma PR com o codigo. O usuario ainda vai poder deterninar a data sozinho.

**Comment by Pr3d4dor** [comment]
Eu acho que se for fazer algo do gênero seria bom lá em Sistema >> Configurações para que seja configurado, por exemplo:
Prazo Padrão para Finalizar Ordens de Servico: 7

**Comment by hoshikawakun** [comment]
> 
> 
> Eu acho que se for fazer algo do gênero seria bom lá em Sistema >> Configurações para que seja configurado, por exemplo:
> Prazo Padrão para Finalizar Ordens de Servico: 7

isso de escolher qual o praso eu dou conta de fazer

@fwsund manda aki mesmo se puder o arquivo editarOS.php que ja faço a PR junto com uma que ja esta pra sair

**Comment by fwsund** [comment]
@hoshikawakun o arquivo e adicionarOs.php 
A linha editada e da 74 a 95
[adicionarOs.TXT](https://github.com/RamonSilva20/mapos/files/6549642/adicionarOs.TXT)

**Comment by fwsund** [comment]
> Eu acho que se for fazer algo do gênero seria bom lá em Sistema >> Configurações para que seja configurado, por exemplo:
> Prazo Padrão para Finalizar Ordens de Servico: 7

@Pr3d4dor  seguindo o CDC, o que falta para impressao de OS e a "previsao de orcamento" hj no meu sistema trato a "data final" como tal. Mas creio que seria melhor o seguinte...

Arquivo adicionarOS.php ter um campo de "previsao de orcamento"  => remover "Data final" (sera preenchida no aquivo editarOS)

Arquivo ImprimirOS.php  campo de previsao de orcamento

Arquivo editarOS.php ter o campo de "data final" que sera quando o equipamento de fato tiver pronto. 

Arquivo OS.php Ordenar as OS de acordo com a que tiver mais proxima do final da "Previcao orcamento" assimo usuario ira ver com mais claresa qual equipamento esta proximo de vencimento da data de previsao de orcamento acordado no momento do cadastro. 

So que acompanho esse trabalho ja algum tempo e desdo primordios essa data final e tratada de quando a OS e finalizada, o que de fato continuara sendo, entao sujiro criarmos a "previsao de orcamento". O que acha?

**Comment by Pr3d4dor** [comment]
@fwsund Eu acho que se trocar o Data Final para "Previsão" talvez vai deixar usuários antigos do mapos confusos. 

Acho que se você conseguir primeiro fazer esse ajuste para ter uma configuração para preencehr automaticamente o "Data Final" seria o primeiro passo.

Depois podemos pensar nesses demais ajustes.
