### ISSUE TITLE
Cobranças - Opção de Gestão Interna

### ISSUE THREAD

**Issue by zecamara21** [RamonSilva20/mapos#1403]
É possível criar uma cobrança sem está necessariamente conectada a um gateway?

Se sim, qual melhor forma ?

**Comment by Pr3d4dor** [comment]
Não é melhor criar uma lançamento e deixar como não pago?

**Comment by zecamara21** [comment]
O cliente não consegue visualizar os Lançamentos, somente as cobranças

**Comment by Pr3d4dor** [comment]
@zecamara21 Se for somente para lembrar para cobrar o cliente, só criar no lançamentos iria resolver. Porém realmente não aparece para o cliente na área dele. O intuito do cobranças era ser gerado somente via um gateway de pagamento mesmo. Para criar cobrança manual sem gateway de pagamento vai ter que ser adaptado.
