### ISSUE TITLE
Sujestao

### ISSUE THREAD

**Issue by Ivancarmo** [RamonSilva20/mapos#1411]
Ola, parabens pelo projeto mapos, gostaria de saber como alterar a cor de fundo da pagina de login do mapos ou ate mesmo adicionar uma imagem no formulario tipo  <img src="link_da_imagem"/> tambem como almentar o numero de linhas da pagina de produtos que por padrao é 10, mas a busca pelo produto especifico ocorre apenas na aba visivel

**Comment by Pr3d4dor** [comment]
@Ivancarmo Sim, é possível, vocẽ pode editar o HTML das páginas que quer mudar e para mostrar mais de 10 registros deve alterar a quantidade da paginação.

**Comment by Ivancarmo** [comment]
Sim mas qual arquivo editar e qual linha, pois dei uma analizada no login vi q tem varios css mas la encontrei a referencia

**Comment by Ivancarmo** [comment]
Pois se apenas seleciona no front end o numero d linhas ele assume o padrao d 10 do codugo fonte

**Comment by Pr3d4dor** [comment]
Para alterar a quantidade de registros:
![image](https://user-images.githubusercontent.com/13210429/120079917-90aad000-c08c-11eb-8a83-28a11b6b756b.png)
