### ISSUE TITLE
OS em pdf para whats

### ISSUE THREAD

**Issue by LucasPolli** [RamonSilva20/mapos#1413]
Se possível gostaria que fosse implementado, a possibilidade de gerar o pdf da OS e enviar diretamente por whats ao invés de enviar o texto padrão

**Comment by Pr3d4dor** [comment]
@LucasPolli Isso requer com que seja comprado o WhatsApp Business, para fazer a integração diretamente com a API do WhatsApp.

O WhatsApp Business não é tão barato.
