### ISSUE TITLE
Restaurar backup de localhost para hospedagem

### ISSUE THREAD

**Issue by adriano2290** [RamonSilva20/mapos#1415]
Boa noite! 
Gostaria de saber se alguém pode me dar uma ajuda, uso o sistema em localhost, mas acabei instalando ele em uma hospedagem. O sistema que esta na hospedagem esta sem nada. Gostaria de saber se consigo realizar o backup do sistema que esta em localhost e restaurar o backup na hospedagem?

**Comment by Pr3d4dor** [comment]
@adriano2290 Sim, basta você pegar o seu banco local e restaurar para um banco na hospedagem usando phpmyadmin por exemplo se a hospedagem disponibilizar.

**Comment by adriano2290** [comment]
Muito obrigado! Fiz isso, mas apareceu um erro, não estou conseguindo resolver. Ao gerar fatura ele da um erro "O correu um erro ao tentar faturar esta venda". Tentei passar novamente o banco local, mas o erro continua. Como seria possível resolver ele?
![Captura de tela_2021-06-01_17-11-53](https://user-images.githubusercontent.com/72393813/120384783-fef5c980-c2fc-11eb-8b38-09550395a869.png)

**Comment by Pr3d4dor** [comment]
Consegue verificar os logs de erro dentro da pasta "application/logs"?

**Comment by willph** [comment]
> Muito obrigado! Fiz isso, mas apareceu um erro, não estou conseguindo resolver. Ao gerar fatura ele da um erro "O correu um erro ao tentar faturar esta venda". Tentei passar novamente o banco local, mas o erro continua. Como seria possível resolver ele?
> ![Captura de tela_2021-06-01_17-11-53](https://user-images.githubusercontent.com/72393813/120384783-fef5c980-c2fc-11eb-8b38-09550395a869.png)

Vá em `configurações>sistema.` Aba de `atualizações` e clicar na opção `ATUALIZA BANCOS DE DADOS.`

Fazer novo teste e depois me diz se deu ok.

**Comment by adriano2290** [comment]
Fiz a atualização mas persiste o erro. Percebi que a tela de vendas não esta exibindo as observações, esta abrindo assim:
![teladevendas](https://user-images.githubusercontent.com/72393813/120390224-d32a1200-c303-11eb-9685-2d9cdea442d4.png)
Em localhost ela abre deste jeito, funcionando normalmente:
![teladevendaslocalhost](https://user-images.githubusercontent.com/72393813/120390463-1c7a6180-c304-11eb-98df-a94522ad34a3.png)

**Comment by willph** [comment]
> Fiz a atualização mas persiste o erro. Percebi que a tela de vendas não esta exibindo as observações, esta abrindo assim:
> ![teladevendas](https://user-images.githubusercontent.com/72393813/120390224-d32a1200-c303-11eb-9685-2d9cdea442d4.png)
> Em localhost ela abre deste jeito, funcionando normalmente:
> ![teladevendaslocalhost](https://user-images.githubusercontent.com/72393813/120390463-1c7a6180-c304-11eb-98df-a94522ad34a3.png)

Consegui conferir se todos os campos de vendas está presente no banco de dados?

**Comment by adriano2290** [comment]
Olhei os itens da tabela estão todos iguais, sera que tendo colocar os do localhost nela?
![hospedagem](https://user-images.githubusercontent.com/72393813/120395621-ad087000-c30b-11eb-878c-2884e05b3a3a.png)
![localhost](https://user-images.githubusercontent.com/72393813/120395624-ada10680-c30b-11eb-8b2e-5d16dae5e13c.png)

**Comment by willph** [comment]
Isso acontece ao faturar né?

Olha agora por favor a tabela lançamentos no banco de dados 
E posta aqui, por favor

**Comment by adriano2290** [comment]
Em localhost ele faz inclusão na tabela lançamentos, na hospedagem não faz. Primeira foto é local. A segunda foto na hospedagem, não faz o lançamento ali.
![HOSPEDAGEM](https://user-images.githubusercontent.com/72393813/120398942-7d5c6680-c311-11eb-8748-7eaa1a309044.png)


![TESTELOCALHOST](https://user-images.githubusercontent.com/72393813/120398748-2bb3dc00-c311-11eb-8eb9-fa4487a2087e.png)

**Comment by willph** [comment]
> Em localhost ele faz inclusão na tabela lançamentos, na hospedagem não faz. Primeira foto é hospedagem.
> ![HOSPEDAGEM](https://user-images.githubusercontent.com/72393813/120398942-7d5c6680-c311-11eb-8748-7eaa1a309044.png)
> 
> ![TESTELOCALHOST](https://user-images.githubusercontent.com/72393813/120398748-2bb3dc00-c311-11eb-8eb9-fa4487a2087e.png)

Faz um teste por favor. 

Tenta faturar uma OS  pra vê se dá o mesmo erro por favor?

**Comment by adriano2290** [comment]
Tentei faturar e acontece o mesmo erro.

**Comment by willph** [comment]
> Tentei faturar e acontece o mesmo erro.

Agora pra finalizar, me manda a lista da tabela lançamentos no banco de dados. 

Do mesmo jeito dessa imagem 
https://user-images.githubusercontent.com/72393813/120395624-ada10680-c30b-11eb-8b2e-5d16dae5e13c.png

**Comment by willph** [comment]
Acredito que está faltando algum campo na tabela lançamentos.

**Comment by adriano2290** [comment]
Fiz o print das duas, local e hospedagem
![lancamentoshospedagem](https://user-images.githubusercontent.com/72393813/120400261-e8a73800-c313-11eb-9e6d-3f32c09624b3.png)
![local](https://user-images.githubusercontent.com/72393813/120400262-e9d86500-c313-11eb-8b9a-f876f8b0c3b0.png)

**Comment by willph** [comment]
> Fiz o print das duas, local e hospedagem
> ![lancamentoshospedagem](https://user-images.githubusercontent.com/72393813/120400261-e8a73800-c313-11eb-9e6d-3f32c09624b3.png)
> ![local](https://user-images.githubusercontent.com/72393813/120400262-e9d86500-c313-11eb-8b9a-f876f8b0c3b0.png)

Aparentemente parece está tudo ok.


Qual versão mesmo roda na hospedagem e qual versão roda em localhost?

**Comment by adriano2290** [comment]
![versaohospedagem](https://user-images.githubusercontent.com/72393813/120401716-ec888980-c316-11eb-851d-ab9ca06c8648.png)
![VERSAOLOCAL](https://user-images.githubusercontent.com/72393813/120401718-edb9b680-c316-11eb-9c12-4b9cbb241b53.png)


estes são os prints, pensei em reinstalar ele na hospedagem, mas após isso se eu restaurar o backup pode ser que o erro volto né?

**Comment by willph** [comment]
> ![versaohospedagem](https://user-images.githubusercontent.com/72393813/120401716-ec888980-c316-11eb-851d-ab9ca06c8648.png)
> ![VERSAOLOCAL](https://user-images.githubusercontent.com/72393813/120401718-edb9b680-c316-11eb-9c12-4b9cbb241b53.png)
> 
> estes são os prints, pensei em reinstalar ele na hospedagem, mas após isso se eu restaurar o backup pode ser que o erro volto né?

Esquece de avisar que era a versão do Mapos 😅

**Comment by adriano2290** [comment]
A versão da hospedagem 4.11.2 e local 4.32.1 sera que é isso?

**Comment by willph** [comment]
> A versão da hospedagem 4.11.2 e local 4.32.1 sera que é isso?

Tente deixar os dois na mesma versão. Por favor. 

A atual é 4.33.1.

Lembrando que as versões mais recentes precisa das dependências instalada através do composer.

**Comment by adriano2290** [comment]
Eu atualizo o localhost e faço um backup e atualizo a hospedagem e depois subo o backup? Pode me dar uma dica de como atualizar ele, o backup do localhost é o que tem todos os dados que preciso colocar no sistema da hospedagem.

**Comment by willph** [comment]
> Eu atualizo o localhost e faço um backup e atualizo a hospedagem e depois subo o backup? Pode me dar uma dica de como atualizar ele, o backup do localhost é o que tem todos os dados que preciso colocar no sistema da hospedagem.

Mas fácil fazer backup da sua instalação antiga e do banco de dados da hospedagem. 

Faz uma instalação do zero na hospedagem em outra pasta e depois vai executando só os insert do backup do Sql. 
Deu pra entender, da forma como expliquei?

**Comment by adriano2290** [comment]
Olá! Realizei a atualização e restaurei o backup, ficou funcionando perfeitamente.
