### ISSUE TITLE
Não gera pagamento após atualização para 4.33.1

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1416]
Bom dia pessoal, por favor será que alguém pode me ajudar?

Após eu atualizar de versão o Mapos, não estou conseguindo gerar pagamentos. Eu clico no botão, escolho o gateway, escolho boleto e quando mando gerar nada acontece. Nenhuma mensagem é exibida e quando vou em cobranças, nada foi inserido lá.

**Comment by Pr3d4dor** [comment]
@Lucios1989 Você configurou as credenciais em payment_gateways.php?

**Comment by Lucios1989** [comment]
Configurei sim @Pr3d4dor

**Comment by Lucios1989** [comment]
O que estou achando estranho é que não gera nenhum erro. Simplesmente não executa.

**Comment by Lucios1989** [comment]
No log só tem esse erro:
ERROR - 2021-06-01 15:40:01 --> Severity: User Error --> Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 5.4.16. /mapos/public_html/sistema/application/vendor/composer/platform_check.php 25

Só que o meu php é o 7.3

**Comment by Pr3d4dor** [comment]
@Lucios1989 Eu acho que o composer não está enganado não, parece que de alguma forma você está executando o PHP 5.4 ainda.

**Comment by Lucios1989** [comment]
Acredito que não. Esse erro sempre dá quando o sistema tenta enviar os emails via cron. Já tinha postado isso a um tempo atrás, mas não obtive nenhuma resposta. Não está relacionado com o erro do post.

**Comment by Pr3d4dor** [comment]
@Lucios1989 Você atualizou o banco de dados?

**Comment by Lucios1989** [comment]
Esse erro do post só ocorreu depois que atualizei o mapos via sistema. Geralmente eu atualizo sempre do zero e depois migro a base de dados. Nas versões anteriores estava tudo funcionando, tirando o erro no envio de emails

**Comment by willph** [comment]
> Esse erro do post só ocorreu depois que atualizei o mapos via sistema. Geralmente eu atualizo sempre do zero e depois migro a base de dados. Nas versões anteriores estava tudo funcionando, tirando o erro no envio de emails

Qual versão usava antes de atualiza?

**Comment by willph** [comment]
Usando em localhost ou hospedagem?

Qual versão está usando?

**Comment by Lucios1989** [comment]
@willph estava utilizando a versão 4.32.0. Funciona em Localhost, mas na rede de onde trabalho. O server é um CentOs 7

**Comment by willph** [comment]
> @willph estava utilizando a versão 4.32.0. Funciona em Localhost, mas na rede de onde trabalho. O server é um CentOs 7

Como foi feito a atualização do banco de dados? 

Arquivo da pasta UPDATES?
Eu pelo botão atualizar banco de dados que fica em configurações > sistema ?

**Comment by Lucios1989** [comment]
Foi pelo botão de configuração do sistema

**Comment by willph** [comment]
Qual API está usando Gerencianet?

**Comment by Lucios1989** [comment]
Mercado Pago

**Comment by Pr3d4dor** [comment]
@Lucios1989 Eu acho que você pode instalar do zero a importar o banco para ficar mais fácil.

**Comment by Lucios1989** [comment]
Obrigado @Lucios1989 , vou fazer isso mais tarde e depois posto o resultado.

**Comment by Lucios1989** [comment]
Já fiz o procedimento. Hehehe, agora está gerando um erro:

bad_request: The customer can't be equal to the collector.

**Comment by Pr3d4dor** [comment]
@Lucios1989 Parece que você está usando um cliente que seria você mesmo certo? Então parece que a API deles barra se o recebedor for o mesmo do pagador, recomendo criar outro cliente para testar.

**Comment by Lucios1989** [comment]
@Pr3d4dor , fiz com um cliente. Estava gerando o erro: invalid user identification number. Fui verificar as credenciais, tudo batendo com o Mercado Pago. Agora voltou a não processar o pagamento e não gerar erro algum.

**Comment by Lucios1989** [comment]
Amigos, tentei de tudo e não funciona. Vou fazer um downgrade para a versão anterior para ver se roda.

**Comment by Lucios1989** [comment]
Instalei a versão 4.32.1 do zero e a cobrança está ocorrendo normalmente. Esse problema está relacionado com a atualização 4.33.1
