### ISSUE TITLE
Update 4.32.0 to 4.33.1

### ISSUE THREAD

**Issue by dcassios** [RamonSilva20/mapos#1417]
** Descreva o bug **
Ao tentar atualizar a versão direto pelo sistema, aparece o erro fwrite() expects parameter 1 to be resource, bool given.

Acredito que seja alguma permissão de pasta, más não conheço muito, por isso peço ajuda de vocês, por favor.

![erro-01](https://user-images.githubusercontent.com/29898540/120350910-c7bff200-c2d5-11eb-86ff-702f41ce656e.PNG)
![erro-02](https://user-images.githubusercontent.com/29898540/120350916-c8f11f00-c2d5-11eb-8a2f-fe97fd2f8ba1.PNG)
![erro-03](https://user-images.githubusercontent.com/29898540/120350918-c8f11f00-c2d5-11eb-9978-b8f778ed61c4.PNG)

**Comment by Pr3d4dor** [comment]
@dcassios Isso é um problema antigo do atualizador dentro do sistema. O recomendado é atualizar o mapos manualmente mesmo.

**Comment by dcassios** [comment]
Pode me ajudar a fazer esse update sem ter que fazer uma nova instalação?

**Comment by Pr3d4dor** [comment]
Infelizmente é necessário fazer uma nova instalação mesmo e apontar para o banco de dados antigo.

**Comment by dcassios** [comment]
Obrigado pelo apoio pessoal
