### ISSUE TITLE
Imagem da versão do sistema desaparece

### ISSUE THREAD

**Issue by dcassios** [RamonSilva20/mapos#1418]
Pessoal bom dia.

Pode ser um erro bobo ou pode acontecer somente comigo, quando eu clico na parte superior do sistema MAPOS, onde mostra a versão do sistema e encaminha para o site GIT, a imagem da versão simplesmente desaparece e fica em branco, conforme os prints em anexo.

![erro-01](https://user-images.githubusercontent.com/29898540/120351809-8f6ce380-c2d6-11eb-9f62-378d094e4db5.PNG)
![erro-02](https://user-images.githubusercontent.com/29898540/120352101-d22ebb80-c2d6-11eb-8346-4f2a71499b9d.PNG)

**Comment by brtechst** [comment]
Troca o fundo para preto la nas configurações.

**Comment by dcassios** [comment]
Sim, no fundo preto funciona normalmente e no Neve, quando atualiza a página, volta ao normal. Só enviei a informação para pontuar o time de desenvolvimento para ver se é interessante corrigir, más não me causa nenhum problema isso. É só para ver esse ótimo sistema, funcionar melhor ainda 👍
