### ISSUE TITLE
Possibilidade de incluir quantidades fracionadas em produtos 

### ISSUE THREAD

**Issue by Loury-Silva** [RamonSilva20/mapos#1419]
Prezados;
Em Editar OS na guia produtos só é possível informar a quantidade em números inteiros, preciso que o sistema aceite números fracionados.

Não sei onde alterar, nem como fazer.

Se alguém puder me ajudar, agradeço muito.

**Comment by Pr3d4dor** [comment]
@Loury-Silva Se você fracionar o produto não resolve no momento? Por exemplo criar um produto chamado "Produto X (100 gramas)" e usar. Pois seria necessário um ajuste para usar quantidades fracionadas.

**Comment by willph** [comment]
> @Loury-Silva Se você fracionar o produto não resolve no momento? Por exemplo criar um produto chamado "Produto X (100 gramas)" e usar. Pois seria necessário um ajuste para usar quantidades fracionadas.

E se for 20.5kg 

Vai complica não acha. 😁

**Comment by Pr3d4dor** [comment]
Se for 20.5 kg a quantidade vai ser 205, é o que da pra fazer no momento sem fazer alteração no código.

**Comment by Loury-Silva** [comment]
@Pr3d4dor e @willph, pois é meus caros o problema é que estou trabalhando com várias unidades, kg é uma delas, mas também tenho m³ (metro cúbico), tipo: areia e brita, dentre outras que vão saindo do estoque em frações.
