### ISSUE TITLE
Desconto não aparece no QR code

### ISSUE THREAD

**Issue by imc7897** [RamonSilva20/mapos#1420]
Boa noite! Atualizei o mapos para 4.33.1 e ao aplicar um desconto e ler o QR CODE sempre aparece o valor Total e não o desconto.
Tentei mudar na função valorTotalOS, mas não consegui. Será que poderiam ajudar
OBS: o valor que carrega o Qr CODE é de R$223,00, conforme figura abaixo, e não o valor de R$187,32

![image](https://user-images.githubusercontent.com/85318272/120717005-3bf8c200-c49d-11eb-8873-b8acaf23d743.png)

**Comment by Pr3d4dor** [comment]
@imc7897 A implementação do desconto ainda não está finalizada pelo @willph, apenas está com a PR aberta, não foi lançado versão oficial do mapos com a funcionalidade de desconto ainda. Peço que aguarde quando a PR for aceita/finalizada e lançamento da versão oficial com essa funcionalidade.

**Comment by imc7897** [comment]
Muito obrigado por responder @Pr3d4dor .
