### ISSUE TITLE
Erro ao gerar boleto mercado pago

### ISSUE THREAD

**Issue by adriano2290** [RamonSilva20/mapos#1422]
Boa noite!
Ao tentar gerar um boleto pelo mercado pago dentro do sistema volta um erro, mas não consegui resolver ele. Alguém pode me dar uma ajuda?![Screenshots_2021-06-04-22-29-25.png](https://user-images.githubusercontent.com/72393813/120876048-016a5480-c585-11eb-9a36-4bb1c1d1ad99.png)

**Comment by leofranklim** [comment]
COBRANÇA PELO MERCADO PAGO NÃO RECOMENDO.
ESTOU USANDO A GERENCIA NET, SÓ ALEGRIA

**Comment by adriano2290** [comment]
Legal! Bom saber, sera que consigo integrar outra api? 
É que hoje uso a paghiper, o é mais baixo que a Gerencianet.

**Comment by Pr3d4dor** [comment]
@adriano2290 Você não está tentando gerar uma cobrança para si mesmo né?

Eu acho que não permite.

**Comment by adriano2290** [comment]
Pior que não, usei 2 cadastros diferentes. Mas onde precisa colocar os dados do mercado pago, api, cliente secret , token , faltou o Integrador IP, plataform id e corporation id. Os outros 4 estão preenchidos.

**Comment by Pr3d4dor** [comment]
@adriano2290 Estranho, recomendo tentar usar o GerenciaNET mesmo como o @leofranklim citou.
