### ISSUE TITLE
Valor do lucro no relatório

### ISSUE THREAD

**Issue by marcosrossato** [RamonSilva20/mapos#1425]
Seria muito interessante que no relatório do financeiro tbm aparecesse o valor do lucro da venda podendo assim ter um controle mais exato do lucro diário nas vendas e serviços prestados

**Comment by visaotec** [comment]
Olá, eu fiz isso tanto Lucros dos produtos e lucros nas ordens de serviços, saem nos relatórios.
Dê uma olha se é assim que vc quer.
https://negocios.topnacional.com/
User: empresa@gmail.com
Senha: empresa
Abraços

**Comment by Pr3d4dor** [comment]
@visaotec Se você quiser contribuir essa funcionalidade para o mapos basta abrir uma pull request.

**Comment by cabralwms** [comment]
Achei muito interessante fornecedores em cadastro e campos separados, e o relatorio no final ficou bem legal.

**Comment by marcosrossato** [comment]
muito bom, bem completo
