### ISSUE TITLE
Não inserindo Serviços e Produtos na OS

### ISSUE THREAD

**Issue by Milokoz** [RamonSilva20/mapos#1426]
** Descreva o bug **
Ao tentar inserir produtos ou pedidos na OS me deparo com um erro de Bad Request (400) ao consultar o console do navegador.

![image](https://user-images.githubusercontent.com/21976522/121427433-1828f680-c94b-11eb-9344-aa6816662719.png)

![image](https://user-images.githubusercontent.com/21976522/121427412-0fd0bb80-c94b-11eb-8e85-2d584c70446d.png)

**Comment by visaotec** [comment]
Olá tudo bem,
olha a versão do php que seu sistema  está rodando..
aqui no meu está tranquilo no php 7.3
