### ISSUE TITLE
Não salva as configurações

### ISSUE THREAD

**Issue by tecnofreitas** [RamonSilva20/mapos#1427]
Ao clicar em Configurações -> Sistema, independentemente dos parâmetros que alterar, aparece uma mensagem de erro informando que devo selecionar ao menos uma opção, mas isso já foi feto anteriormente. Segue print em anexo explicando o erro. Alguém poderia ajudar?
[https://prnt.sc/15hu7rl](url)

**Comment by visaotec** [comment]
O  print não está aparecendo amigo ....
se puder enviar por e-mail, quem sabe posso te ajudar
visaotec.com@gmail.com

**Comment by tecnofreitas** [comment]
Olá @visaotec, basta copiar e colar em seu navegador: https://prnt.sc/15hu7rl

**Comment by imc7897** [comment]
Boa noite, @tecnofreitas, verifica se as informações do banco "configuracoes" subiram corretamente no mysql. Aconteceu comigo e inseri novamente.

**Comment by tecnofreitas** [comment]
> Boa noite, @tecnofreitas, verifica se as informações do banco "configuracoes" subiram corretamente no mysql. Aconteceu comigo e inseri novamente.

**Comment by tecnofreitas** [comment]
Olá, @visaotec
Não entendi direito como você resolveu, poderia explicar melhor?
