### ISSUE TITLE
Ola boa tarde amigos, gostaria de saber se dentro do Mapos na parte de Emitente, se consigo colocar 2 numeros de telefone?

### ISSUE THREAD

**Issue by leolfgomes** [RamonSilva20/mapos#1428]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by visaotec** [comment]
Consegue sim, só adicionar mais um campo e depois puxar no cabeçalhos nos relatórios e vendas.

**Comment by leolfgomes** [comment]
![image](https://user-images.githubusercontent.com/81575159/122644475-bf482380-d0eb-11eb-8b75-a63283e5c0bb.png)
desculpa borrar a imagem, nesse caso eu entrei no codigo fonte do arquivo emitente e dupliquei o campo telefone e nomeie como telefone 2 mais mesmo assim não aparece aqui

**Comment by leolfgomes** [comment]
desde ja agradeço pelo retorno das mensagens

**Comment by visaotec** [comment]
Tem mais arquivos pra você mexer, inclusive no banco de dados...

Em sáb., 19 de jun. de 2021 10:49, leolfgomes ***@***.***>
escreveu:

**Comment by leolfgomes** [comment]
ha entendi, então deixa quieto, meu conhecimento em codigo é iniciante, rsrssr

**Comment by visaotec** [comment]
Eu fiz diversas modificações para atender Assistência Técnica, mas mantendo
sempre a originalidade da estrutura do sistema.
Depois dê uma olhada.
 negocios.topnacional.com
User: ***@***.***
Senha: empresa

Em sáb., 19 de jun. de 2021 10:57, leolfgomes ***@***.***>
escreveu:

**Comment by leolfgomes** [comment]
blz
tentei aqui mais deu usuario incorreto

**Comment by leolfgomes** [comment]
mais pelo visual inicial ja esta top

**Comment by visaotec** [comment]
Tenta novamente, deve ter colocado usuário e senha incorreto
Usuário : ***@***.***
Senha : empresa
Aqui está funcionando normalmente

Em sáb., 19 de jun. de 2021 11:29, leolfgomes ***@***.***>
escreveu:
