### ISSUE TITLE
Erro no date_helper.php

### ISSUE THREAD

**Issue by samuelfoco** [RamonSilva20/mapos#1429]
** Descreva o bug **
Com a nova versão do Mapos, quando clicamos em Ordem de serviço apresenta o erro que vem do arquivo date_helper.php

![erro-mapos](https://user-images.githubusercontent.com/86168776/122654222-57f89680-d120-11eb-9483-2dd3c79009f1.jpg)

**Comment by Pr3d4dor** [comment]
@samuelfoco Provavelmente seu banco de dados está desatualizado
