### ISSUE TITLE
Erro ao exibir tipo de condição de pagamento VER 4.33.1

### ISSUE THREAD

**Issue by allanredante** [RamonSilva20/mapos#1432]
Boa tarde.

Não é exibido a configuração de FORMA DE PAGAMENTO na ultima versão que baixei do MAPOS 

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Configurações'
2. Em "Configurações, não é exibido o menu "Forma de pagamento"

**Comportamento esperado**
Exibir o menu "Condição de pagamento

** Capturas de tela **
![image](https://user-images.githubusercontent.com/86257217/122808620-7d61dd80-d2a3-11eb-8174-132577dec74d.png)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 8.1 Pro 
 - Navegador Google Chrome
 - Versão 91.0.4472.114

** Contexto adicional **
Versão atual MAPOS 4.33.1

**Comment by Pr3d4dor** [comment]
@allanredante Seu banco de dados está atualizado?

**Comment by allanredante** [comment]
> @allanredante Seu banco de dados está atualizado?

Sim, fiz a instalação no mesmo dia.

**Comment by Pr3d4dor** [comment]
@allanredante Esqueci de mencionar que essa opção foi removida do menu, agora as configurações ficam em payment_gateways.php

**Comment by allanredante** [comment]
Ok, realmente pelo não havia visto.
Farei as configurações por la!

Obrigado!
