### ISSUE TITLE
Erro de "Mysql" ao iniciar o Xampp

### ISSUE THREAD

**Issue by Accuvix** [RamonSilva20/mapos#1434]
Boa noite pessoas, gostaria de pedir a ajuda de vocês, pois não consigo resolver isso sozinho. Quando inicio o 'Xampp Control' o MySQL não inicia e apresenta a seguinte mensagem:
Error: MySQL shutdown unexpectedly.
This may be due to a blocked port, missing dependencies,
improper privileges, a crash, or a shutdown by another method.
Press the Logs button to view error logs and check
the Windows Event Viewer for more clues
If you need more help, copy and post this
entire log window on the forums.
Agradeço a quem puder ajudar!

**Comment by allanredante** [comment]
Podem ter inúmeras situações para apresentar esse erro, minha sugestão é que faça o seguinte:

1. Desinstale por completo o xampp e todas suas features integradas.
2. Limpe as sujeiras de registro do windows com CCleaner por exemplo (ou use um desinstalador como o Revo)
3. Verifique se não existe nenhum outro serviço utilizando as mesmas portas que seu MySQL (por padrão 3306)

Após isso instale novamente para verificar se continuará com o mesmo erro.
