### ISSUE TITLE
IE - Inscrição Estadual

### ISSUE THREAD

**Issue by Robizidoro** [RamonSilva20/mapos#1435]
Olá amigos, bom dia.
Vocês poderiam deixar a IE no cadastro do emitente como não obrigatório, pois sou mei mas não tenho Inscrição Estadual, e ai não consigo me cadastrar no mapos.

Seria uma boa idéia.

Tenham todos um ótimo dias

**Comment by willph** [comment]
Você pode colocar inscrição municipal ou apenas um -

**Comment by Robizidoro** [comment]
Will, muito obrigado.
Resolveu..
