### ISSUE TITLE
Tutorial para exibir e ocultar  filtro na OS

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#1437]
Tutorial - para exibir e ocultar filtro em OS
---------------------------------------------------------------
1ª Acesse a pasta do Sistema Mapos
Exemplo: C:\xampp\htdocs\pastadoseumapos\application\views\os\os.php
---------------------------------------------------------------
2ª Abre o arquivo os.php com seu editor preferido
na linha 14 cole o codigo abaixo
```
</br><div id="minhaDiv"  style="display:none">
```
esse código vai ficar acima da  div class="span3" 
---------------------------------------------------------------
3ª Na linha 50 cole o código abaixo
```
<span class="badge" style="background-color:#32CD32"><button type="button"  class="btn" onclick="Mudarestado('minhaDiv')"><b>Filtro</b></span></button>
```

esse código vai ficar abaixo da escrita Ordens de Serviço
---------------------------------------------------------------
4ª Na linha 183 cole o código abaixo
```
function Mudarestado(el) {
        var display = document.getElementById(el).style.display;
        if(display == "block")
            document.getElementById(el).style.display = 'none';
        else
            document.getElementById(el).style.display = 'block';
    }
```
pode colocar esse código logo após o script type="text/javascript"

------------------------------------------------------------------
Quem quiser ver funcionando
[Acesse](https://negocios.topnacional.com/)
User: empresa@gmail.com
Senha: empresa
[Video passo a passo](https://youtu.be/Zd-6lHXq3RU)
-----------------------------------------------------------------
Atenciosamente,
visaotec eletrônicos
visaotec.com@gmail.com

![Exibir](https://user-images.githubusercontent.com/35280835/123425904-0f663080-d599-11eb-8497-c98fd89d48e3.JPG)
![ocultar](https://user-images.githubusercontent.com/35280835/123425906-10975d80-d599-11eb-869c-e2adcf6eb8e1.JPG)

**Comment by cabralwms** [comment]
Oi bom dia a todos. 
Já existe um filtro desse na versão mais nova.

**Comment by visaotec** [comment]
Bom dia, isso é pra tantos outros usuários que usa as versões mais antigas.

Em sex., 25 de jun. de 2021 08:21, cabralwms ***@***.***>
escreveu:
