### ISSUE TITLE
Usuário expirado - Erro após atualização

### ISSUE THREAD

**Issue by thiagos717** [RamonSilva20/mapos#1439]
Bom dia senhores. Estou com um problema em que após atualizado o Mapos estou recebendo erro de usuário expirado. Mesmo ja fazendo um procedimento visto pelo Ramon de remover a pasta system e outro adicionando dataExpiracao no banco.sql

**Comment by thiagos717** [comment]
@RamonSilva20  alguma ajuda brother? ja tentei oque citei acima e o esquema que resolveu para outro amigo nas linhas que alteram o usuário dentro do banco.sql

**Comment by RamonSilva20** [comment]
Olá @thiagos717, altere diretamente no banco de dados, usando o PHPMyAdmin ou outra ferramenta. Tabela de usuários, coluna dataExpiracao.

![image](https://user-images.githubusercontent.com/12385697/123690936-608d5300-d82b-11eb-9167-a9579152d622.png)

**Comment by RamonSilva20** [comment]
Agora o problema é outro então, provavelmente o hash que você está usando está incorreto, o sistema não usa md5. Tente um dos hashs abaixo:

123456
$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO

admin
$2y$10$j9KyqKUsCIW./R1lKpvw7.Yfrnlx2IX5c2WEUUdJ.q0Ht1ZJWP9tq

**Comment by thiagos717** [comment]
Entrou mas
 Error Call to a member function result() on bool
