### ISSUE TITLE
Implementação de troco na venda com recibo.

### ISSUE THREAD

**Issue by mike-inacio** [RamonSilva20/mapos#1442]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Nao, é apenas uma sugestao na guia de vendas e faturamento.

** Descreva a solução que você deseja **
Gostaria que na aba de faturamento, houvesse a opção de troco, pois nem sempre o cliente paga no valor exato.

** Descreva as alternativas que você considerou **
ao clicar em faturar tem a opção do valor e esse é editavel, ao menos pode escrever nesse campo, mesmo colocando um valor diferente o que vai pro BD eh o valor total da venda, se houvesse uma forma de pegar esse valor inserido, e colocar numa variavel, essa poderia subtrair do valor total gerando o troco. se alguem puder de dar uma dica de como fazer isso.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by cabralwms** [comment]
Seria uma coisa legal em fluxo e controle de caixa, talvez algo ao abrir e fechar e com esse sistema de troco seria um otimo controle.

**Comment by R4T0** [comment]
Alguma previsão ou possibilidade de acontecer isso?
