### ISSUE TITLE
Não consigo alterar a cor mesmo mudando no Css da pasta C:\xampp\htdocs\mapos\assets\css

### ISSUE THREAD

**Issue by chinayder15** [RamonSilva20/mapos#1446]
** bug **
Não consigo alterar a cor da tela de login  nesse projeto queria modificar a cor a principio e também a tela de carregamento.

*No Navegador**

[Segue a imagem do projeto aberto no meu navegador] Localhost

(https://drive.google.com/file/d/1cqwqHuK0skZYa07AmmbykA1ofHLoDVoP/view?usp=sharing)

/*Metro Background color class*/
.bg_lb{ background:#27a9e3;}
.bg_db{ background:#2295c9;}
.bg_lg{ background:#28b779;}
.bg_dg{ background:#28b779;}
.bg_ly{ background:#ffb848;}
.bg_dy{ background:#da9628;}
.bg_ls{ background:#2255a4;}
.bg_lo{ background:#da542e;}
.bg_lr{ background:#f74d4d;}
.bg_lv{ background:#603bbc;}
.bg_lh{ background:#b6b3b3;}

body { background-color:#2E363F;    padding: 0;    margin-top:10%;}
#logo, #loginbox {    width: 32%;    margin-left: auto;    margin-right: auto;    position: relative;}
#logo img {  margin: 0 auto;    display: block;}
#loginbox { overflow: hidden !important;    text-align: left;    position: relative; }
#loginbox form{ width:100%; background:#2E363F; position:relative; top:0; left:0; }
#loginbox .form-actions { padding: 14px 20px 15px;}
#loginbox .form-actions .pull-left { margin-top:0px;}
#loginbox form#loginform { z-index: 200; display:block;}
#loginbox form#recoverform { z-index: 100;     display:none;}
#loginbox form#recoverform .form-actions {    margin-top: 10px;}
#loginbox .main_input_box { margin:0 auto; text-align:center; font-size:13px;}
#loginbox .main_input_box .add-on{  padding:9px 9px; *line-height:31px; color:#fff;  width:30px; display:inline-block;}
#loginbox .main_input_box input{ height:30px; border:0px; display:inline-block; width:75%; line-height:28px;  margin-bottom:3px;}
#loginbox .controls{ padding:0 20px;}
#loginbox .control-group{ padding:20px 0; margin-bottom:0px;}
.form-vertical, .form-actions {  margin-bottom: 0; background:none; border-top:1px solid #3f4954; }
#loginbox .normal_text{ padding:15px 10px; text-align:center; font-size:14px; line-height:20px; background:#2E363F; color:#fff; }
@media (max-width:800px){
#logo { width: 60%; }
#loginbox{ width:80%}
}

**No código fonte***

[Segue Imagem do Código fonte dentro da pasta Xamp] Localhost

(https://drive.google.com/file/d/1RK23rrOoO5mEOCJDgP2JWTn2O56352Yt/view?usp=sharing)

**Comment by chinayder15** [comment]
?

**Comment by visaotec** [comment]
Eu fiz atenção por aí mesmo
https://negocios.topnacional.com/index.php/login

**Comment by chinayder15** [comment]
Opa gratidão resolvido sempre verificamos o cache do navegador agora estou para alterar a opção de cadastro faturado no sistema ! para que seja possivel excluir caso seja necessário.
