### ISSUE TITLE
Meu mapos parou de imprimir A4

### ISSUE THREAD

**Issue by LucasPolli** [RamonSilva20/mapos#1447]
Estava usando normalmente, ao cadastrar uma OS, logo apos o cadastro imprime normal, depois do cadastro efetuado, se quero imprimir novamente, não consigo mais imprimir A4, aparece a mensagem:

Esta página não está funcionandoos.tecfloripa.com.br não consegue atender a esta solicitação no momento.
HTTP ERROR 500

**Comment by LucasPolli** [comment]
vi q so acontece quando tem produto ou serviço adicionado

**Comment by Pr3d4dor** [comment]
@LucasPolli Se puder colocar os logs que ficam na pasta application/logs ajudaria

**Comment by LucasPolli** [comment]
segue logs:

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-08 09:31:58 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to Symfony\Component\VarDumper\Caster\Caster::castObject() must be an instance of Symfony\Component\VarDumper\Caster\object, instance of stdClass given, called in /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 342 and defined in /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Caster/Caster.php:47
Stack trace:
#0 /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(342): Symfony\Component\VarDumper\Caster\Caster::castObject(Object(stdClass), 'stdClass', false, 'stdClass')
#1 /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Cloner/VarCloner.php(176): Symfony\Component\VarDumper\Cloner\AbstractCloner->castObject(Object(Symfony\Component\VarDumper\Cloner\Stub), false)
#2 /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Cloner/Abstr /home2/criat935/public_html/os.tecfloripa.com.br/application/vendor/symfony/var-dumper/Caster/Caster.php 47

**Comment by dvdbsilva** [comment]
Olá, acredito que esse problema seja pelo parâmetro de memória no php.ini
verifiquei o log de erro vai ter algo assim 

PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes

basta aumenta a memória no php.ini a lista que tem memory_limit que por padrão vem 128MB para 512 ou para o valor que você verificar no log de erro e restartar o serviço

**Comment by LucasPolli** [comment]
obrigado, fiz as alterações porem nao tenho acesso para retart do aoache, o
hostgator nao permite,vou aguardar e ver o que acontece

Em dom., 11 de jul. de 2021 às 01:16, dvdbsilva ***@***.***>
escreveu:

**Comment by dvdbsilva** [comment]
Você pode reiniciar o servidor que irá pegar as novas configurações. Se não
reiniciar não vai pegar

Em dom., 11 de jul. de 2021 às 10:51, LucasPolli ***@***.***>
escreveu:

**Comment by LucasPolli** [comment]
bom fiz as alterações e permanece na mesma.. ainda sem solução..

**Comment by LucasPolli** [comment]
problema resolvido, meu domínio principal estava com uma configuração que forçava utilizar o php 7.1, o que estava causando o problema.. feito a correção nisso, voltou a funcionar normalmente.
