### ISSUE TITLE
Acesso interno e externo

### ISSUE THREAD

**Issue by vilelamatheus** [RamonSilva20/mapos#145]
Boa Noite,

E possivel deixar dentro do config.php um IP que acesse simultaneamente intranet e internet... pq se eu coloco ip interno no arquivo, a galera acessa normalmente por outros computadores da rede, porem qndo alguem fora da rede digita o ip externo + a porta, ele redireciona pro ip interno nao abrindo nda pq n ta na mesma rede… e se eu configurar o arquivo com ip externo ai funciona, porem pessoal da rede local nao acessa.

**Comment by RamonSilva20** [comment]
Olá, na documentação tem uma sugestão de como colocar mais de um domínio. 

https://www.codeigniter.com/user_guide/installation/upgrade_303.html?highlight=base_url

**Comment by marcelinoac** [comment]
Bom dia, pra poder resolver isso fiz uma alteração no arquivo hosts do Windows. Configurei o domínio para acesso externo e para acessar na rede interna eu direcionei o dominio para o IP do servidor.
