### ISSUE TITLE
Ao configurar visualização de OS, lista de OS não mostra tudo na mesma tela

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#1450]
** Descreva o bug **
Quando você configura para visualizar apenas alguns tipos de OS, a lista de ordens de serviços apresentada segue um padrão confuso, pulando páginas dependendo do número da OS.

**Reproduzir**
Etapas para reproduzir o comportamento:
Tenha 51 Ordens de serviços cadastradas, os serviços 51, 38 e 28 estão em Andamento, o restante está como faturado.
Configure o sistema para apresentar apenas 10 registros por página. Assim, a lista de OS será da 51 a 41 na pagina 1, 40 a 30 na página 2, 29 a 19 na pagina 3, 18 a 8 na página 4 e o 7 a 1 na página 5.
Configure para visualizar apenas as OS em Andamento.
Será a página 1 com apenas uma OS, a 51, depois na segunda página com a OS 38 e a terceira página com a OS 28, ou seja, um registro por página.

**Comportamento esperado**
Deveria apresentar apenas uma página, com os serviços 51, 38 e 28.

** Desktop (preencha as seguintes informações): **
 - SO: [Windows 10]
 - Navegador [Chrome]
 - Versão [91.0.4472.124]

**Comment by dvdbsilva** [comment]
Estou com um problema parecido, pelo que pesquisei esta relacionado com o método get e post que no momento da pesquisa utiliza get e na paginação utiliza post tem como realizar o ajuste utilizando appends, estou estudando com resolver conseguindo compartilho
