### ISSUE TITLE
Colocar mais dados na notificação do cliente

### ISSUE THREAD

**Issue by vagner3101** [RamonSilva20/mapos#1452]
Pessoal, boa noite alguém pode me dar uma forcinha para conseguir incluir mais dados na notificação para o cliente por whatsapp.

queria colocar mais dados tipo, e-mail do cliente, endereço e tal

Desde já agradeço a atenção e coolaboração.

**Comment by tutibueno** [comment]
Seria necessário criar uma solicitação de melhoria do sistema. Estas informações não estão disponíveis no momento.
