### ISSUE TITLE
Erro ao tentar excluir uma venda nao faturada

### ISSUE THREAD

**Issue by Perzivall** [RamonSilva20/mapos#1458]
segue erro

Whoops \ Exception \ ErrorException (E_WARNING)
Undefined property: stdClass::$idCobranca

tela preta com branca, segui o tutorial do MAPOS OFICIAL no youtube e funcionou tudo certo ate então, porem ao excluir uma venda aparece uma tela de erro

tambem, depois que aparece aquele POPUP de SUCESSO, em cada lugar que clico no site fica reaparecendo aquele POPUP e se torna bem desconfortavel a utilização. Se puderem me ajudar fico muito grato. 

E alias, parabens a toda equipe o aplicativo está ficando extremamente pratico e eficaz.

**Comment by chinayder15** [comment]
Olá também enfrentando o mesmo erro porém vou ver se consigo alterar pois estaria que stá vinculada a permisão dos usuarios não podendo assim qualquer usuario alterar a OS Faturada
