### ISSUE TITLE
Ao tentar instalar já diz ser instalado antes 

### ISSUE THREAD

**Issue by Ironaldo-Silva** [RamonSilva20/mapos#1459]
Faço o procedimento de instalação mas ao finalizar diz já ter instalado antes e não passa pra liberar o sistema 

images.githubusercontent.com/26805772/126852370-52545d4e-af78-4b2f-bc97-b0adeb0af3c4.jpg)

**Comment by wgiacomelli** [comment]
Tive o mesmo problema ao tentar atualizar o meu sistema, acabei retornando ao antigo, caso alguém tenha alguma sugestão para contribuir.

**Comment by henriquemenin** [comment]
Mesmo alterando o ambiente para "production" aparece a página que já está instalado. Porém, acessando a URL do sistema com /index.php abriu normalmente.
