### ISSUE TITLE
Problema ao cadastrar emitente

### ISSUE THREAD

**Issue by alexcerlini** [RamonSilva20/mapos#146]
Alguém já lidou com esse erro?

Ao clicar em cadastrar ao preencher todas as informações e selecionar a imagem para logomarca, dá esse erro e não consigo cadastrar o emitente...
![erro sistemico](https://user-images.githubusercontent.com/26857487/41884969-38b95110-78cc-11e8-969e-edce03f7bd0c.png)

**Comment by Pr3d4dor** [comment]
Verifique se o diretório de uploads existe e está com as permissões corretas (o Codeigniter sugere permissão 777).

**Comment by paulinhowoox** [comment]
Eu uso esse codigo em toda e qualquer função que faz upload no sistema:
```
if (!file_exists($config['upload_path'])) {
    mkdir($config['upload_path'], 777, TRUE);
}
```

**Comment by alexcerlini** [comment]
Deu certo... Estava faltando a pasta "uploads" dentro de assets... Criei e adicionei as permissões 777 e agora está cadastrando normalmente. Grato.

**Comment by mendaxcn** [comment]
Helppp!!!

Mesmo criando o diretório uploads neste caminho: assets/uploads/ e aplicando a permissão 777, ocorre o mesmo erro em anexo, as configurações do php.ini (upload_tmp_dir) estão OK, poderiam me auxiliar por favor na resolução do problema? Obrigado.

[
![Captura de tela de 2019-06-24 22-46-36](https://user-images.githubusercontent.com/52184318/60063176-6b5bfd00-96d2-11e9-8a66-0e1a91c620ff.png)
](url)
