### ISSUE TITLE
Todas O.S estão aparecendo.

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1466]
Boa tarde jovens, seguinte, atualizei da versão 4.31.1 para a 4.34 até ai tudo ok, banco de dados importado tudo certo.
mas estou com o seguinte problema, as ordens de serviço estão aparecendo TODAS ( faturada, cancelada, aberta, tudo,
mesmo selecionando lá nas configurações somente o que quero que aparece, NADA muda.

fiz um teste com o banco limpo, após instalação ai funciona a opção de ocultar as OS, porem com o banco importado 
ai fica aparecendo todas.

alguma sugestão do que aconteceu ?

**Comment by Pr3d4dor** [comment]
@jsfachini Tente ver a diferença ao salvar as OS em relação às antigas no campo status
