### ISSUE TITLE
anexar arquivos em os

### ISSUE THREAD

**Issue by jonathasnp** [RamonSilva20/mapos#1467]
olá existe a possibilidade de anexar um arquivo um pouco mais pesado que uma foto , para uma os?

estou tentando implementa  o sistema em minha gráfica , e os trabalhos realizado gostaria de deixar salvo junto com as os dos clientes.

**Comment by Pr3d4dor** [comment]
@jonathasnp Não seria mais fácil salvar no Google Drive por exemplo e adicionar uma anotação?

De qualquer forma você pode alterar quais são os formatos permitidos nessa linha: https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Arquivos.php#L226

Além disso se vc estiver usando WAMP, LAMP ou XAMP terá que aumentar o limite de upload de arquivos do próprio PHP.

**Comment by jonathasnp** [comment]
ele não adiciona arquivo .cdr  arquivo do CorelDRAW  msm quando eu adiciono a extensão

**Comment by Pr3d4dor** [comment]
@jonathasnp Você aumentou o limite de upload do PHP também? Que tamanho são os arquivos?

**Comment by jonathasnp** [comment]
![image](https://user-images.githubusercontent.com/81585844/129031873-7da4f3ad-277e-4300-b1bf-6634a2c0df4d.png)

2 arquivos que eu achei relacionado a upload  Os.php  , Arquivo .php  , os arquivo são pequenos nos teste um dos arquivos tem 990kb

**Comment by jonathasnp** [comment]
![image](https://user-images.githubusercontent.com/81585844/129032767-24f6ab7a-ef4f-4707-9647-0bfa71b35684.png)

sempre da esse erro

**Comment by Pr3d4dor** [comment]
@jonathasnp Eu me confundi, pensei que estava falando arquivos e não no anexar na OS. O anexar na OS é aqui: https://github.com/RamonSilva20/mapos/blob/7ff603319cd0bc0dcd795026e7966f465782c559/application/controllers/Os.php#L712

**Comment by jonathasnp** [comment]
é infelizmente não deu certo

**Comment by jonathasnp** [comment]
Boa Noite,  consegui resolver meu problema  seguindo esse post https://github.com/RamonSilva20/mapos/issues/724
