### ISSUE TITLE
Possibilidade de Edição do Status da OS

### ISSUE THREAD

**Issue by alexandreangelis** [RamonSilva20/mapos#1468]
Olá, ótimo sistema! Comecei a espalhar ele em alguns grupos do segmento de gráfica rápida, que é meio que fora do propósito inicial do seu projeto. Mas é bem útil, pois o processo de serviço é parecido.

Gostaria de ver a possibilidade de implementação de edição dos status de OS, pois seria melhor se pudéssemos personalizar as etapas.

Obrigado!!!

**Comment by chinayder15** [comment]
No caso deve modificar as variaveis padrões  ( MAPOS /  Views /os  ) Consegue realizar alterações

                       // BLOCO DE CONDICIONAL DE BOTOES DAS OS: EXCLUIR VISUALIZAR E EDITAR. 
                        $editavel = $this->os_model->isEditable($r->idOs);

                        if ($this->permission->checkPermission($this->session->userdata('permissao'), 'vOs')) {
                            echo '<a style="margin-right: 1%" href="' . base_url() . 'index.php/os/visualizar/' . $r->idOs . '" class="btn tip-top" title="Ver mais detalhes"><i class="fas fa-eye"></i></a>';
                        }
                        if ($editavel) {
                            echo '<a style="margin-right: 1%" href="' . base_url() . 'index.php/os/editar/' . $r->idOs . '" class="btn btn-info tip-top" title="Editar OS"><i class="fas fa-edit"></i></a>';
                        }
                        if ($this->permission->checkPermission($this->session->userdata('permissao'), 'dOs') || $editavel) {
                            echo '<a href="#modal-excluir" role="button" data-toggle="modal" os="' . $r->idOs . '" class="btn btn-danger tip-top" title="Excluir OS"><i class="fas fa-trash-alt"></i></a>  ';
                        }
                        echo '</td>';
                        echo '</tr>';
