### ISSUE TITLE
Contribuir

### ISSUE THREAD

**Issue by allanbarcelos** [RamonSilva20/mapos#147]
Como posso me tornar um contribuidor oficial?

**Comment by RamonSilva20** [comment]
Adicionei seu usuário aos colaboradores do projeto. No momento o projeto está sendo refatorado para depois ser adicionadas novas funcionalidades. As tasks estão listadas no projeto **[mapos 4](https://github.com/RamonSilva20/mapos/projects/3)**. :+1:

**Comment by allanbarcelos** [comment]
ok, agradeço a confiança. Vou seguir as tasks.

**Comment by allanalcantara** [comment]
como faço tbm pra poder contribuir, ou me passar o contato para ajudar no projeto.

**Comment by RamonSilva20** [comment]
Adicionado aos colaboradores @allanalcantara. Para facilitar a comunicação criei um canal no #slack , quem tiver interesse em participar do desenvolvimento segue o [link do convite](https://join.slack.com/t/maposworkspace/shared_invite/enQtMzk0MTQ3OTg2Njg5LTk5MjEzYWJiZGRhYWM2MGJmZDBjMjAyNjc5MGM3M2M2ZTczZDE4ZWY1OTQ1ZTA4N2FkMzY2MjI5Mzk4ZTBjYmY).

**Comment by AndersonSilca** [comment]
Olá tudo bem Ramon?
Gostaria de parabenizar por sua iniciativa e projeto. Vejo um mercado necessitante nesse segmento. Como faço para conhecer melhor o projeto?

**Comment by allanalcantara** [comment]
fui acessar link do convite já tinha expirado. dai acabando que me mudei e fiquei sem net.

**Comment by RamonSilva20** [comment]
@allanalcantara e @AndersonSilca, gerei um novo [convite](https://join.slack.com/t/maposworkspace/shared_invite/enQtNDAyNzE2NDI5MDI5LTdkNGFiNGRjYTQ1MWNlNTlhMmQ5NDE4NGQyMTJlOTk1N2IxNTgzNTRmOGVmMmQ4MDViMDk3ZDdiMTRkYmRlMzQ) para o grupo no #slack sem data de expiração.

**Comment by jonaellemos** [comment]
Fala Ramon, tudo bem? Como faço pra ser contribuidor?

**Comment by allanalcantara** [comment]
Blz, Consegui!
