### ISSUE TITLE
Erro em Ordem de Serviço e Financeiro após importar banco de dados 3.1.11 -> 4.34.0

### ISSUE THREAD

**Issue by pwrslv3** [RamonSilva20/mapos#1470]
Fiz a instalação local da versão 4.34.0 (Xampp + Composer), consegui logar e acessar todas as funções normalmente, incluindo ordem de serviço e financeiro.

Exportei o banco de dados da versão que uso atualmente, 3.1.11 e importei no banco de dados da versão nova. Após isso, rodei todos os updates disponíveis. Todos updates foram importados com sucesso, porem apresentando a mensagem de erro:
_"Mensagens do MySQL : Documentação
#1064 - Você tem um erro de sintaxe no seu SQL próximo a '<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="ligh...' na linha 1"_

Após a importação, tanto antes quando depois de todos os updates, não consigo acessar mais os menus "ordem de serviço" e "financeiro", conforme as imagens de erro abaixo:
https://imgur.com/QrgkNVH
https://imgur.com/K7iWQdu

Todos os outros itens como clientes, produtos, serviços está 100%, somente esses dois estão com erro.
Não entendo nada de programação e fiz a instalação seguindo os tópicos daqui, mas esse erro especifico não encontrei ninguém relatando.
Alguém pode me ajudar ?

**Comment by Pr3d4dor** [comment]
@pwrslv3 Os updates no banco não foram executados com sucesso, não pode aparecer essa mensagem

Tente atualizar o banco em Configurações >> Sistema

**Comment by pwrslv3** [comment]
Fiz o procedimento, ele dá a mensagem de "Banco de dados atualizado com sucesso", porem o erro nas telas de OS e financeiro permanecem iguais.

**Comment by pwrslv3** [comment]
Não entendi muito bem o que aconteceu, mas no fim funcionou.
Depois que fiz o processo de atualizar o banco por dentro da interface, o erro continuou, mas na sequencia ao importar os arquivos de update pelo phpmyadmin o processo deu certo.
Obrigado :)
