### ISSUE TITLE
E-mail da O.S na versão 4.34.0 com Hostgator "enviado" e não chega no destino

### ISSUE THREAD

**Issue by Sergiosantanati** [RamonSilva20/mapos#1471]
Boa tarde!

Ao configurar o hostgator com uma conta de email, criar as tarefas cron e executar no Mapos na rotina de cadastrar uma O.S ou enviar e-mail depois de cadastrada, após isso fui acompanhar o e-mail do que aparece com status de pendente logo em seguida enviando e por fim enviado, o problema é que não chega nas caixas de e-mail, já testei tanto com Gmail quanto com Icloud.

**Comment by chinayder15** [comment]
Opa verifique no span do seu E-mail e niveis de permisão mais também explique pouco melhor sobre como configurou seu e-mail e qual operação está realizando para envio do e-mail favor.

**Comment by Sergiosantanati** [comment]
Boa tarde Ramon,


Bom, fiz as configurações conforme orientações do Git (
https://github.com/RamonSilva20/mapos), depois dei uma olhada no Youtube
que tem um vasto conteúdo sobre o MAPOS (
https://www.youtube.com/watch?v=2NH3nLFMfz8&lc=Ugyen4J7P9i258cM1Px4AaABAg.9Qx48WyA2CR9QxG2BtsNSo),
pronto dai pra frente gerei uma ordem de serviço e fiz o envio do e-mail na
opção disponível em: ordem de serviço>>ver mais detalhes>>enviar por e-mail.

Segue alguns prints, outra coisa, enviei para dois emails diferentes e com
toda certeza verifiquei TODAS as pastas e não chegou nada.


[image: image.png]

[image: image.png]


[image: image.png]


[image: image.png]

HOSTGATOR
MAPOS 4.34.0
PHP 7.3
CPANEL

Atenciosamente,


*Sergio Santana*

Quem quiser ser líder deve ser primeiro servo. Se você quiser liderar, deve
servir. #Jesus



Em sex., 13 de ago. de 2021 às 12:17, chinayder15 ***@***.***>
escreveu:

**Comment by dgcursino** [comment]
Bom dia.

NO arquivo de configuração do e-mail 
/application/config/email.php
No inicio do codgo deve se usar smtps no local de smtp.

<?php
$config['protocol']         = 'smtps';
$config['smtp_host']        = 'dominio.com.br';
$config['smtp_crypto']      = 'ssl'; // tls or ssl
$config['smtp_port']        = '465';
$config['smtp_user']        = 'user@dominio.com.br';
$config['smtp_pass']        = 'senhaaqui';
$config['validate']         = TRUE; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = FALSE;
$config['wordwrap']         = FALSE;
$config['priority']         = '1'; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.
