### ISSUE TITLE
Gateway de Pagamento na versão 4.34.0 não aparece em Configurações

### ISSUE THREAD

**Issue by Sergiosantanati** [RamonSilva20/mapos#1473]
Boa tarde!

Não está disponível a opção de configurar e incluir as chaves do mercado pago e nem de nenhum Gateway de Pagamento nessa nova versão apenas na ordem de serviço aparece para Escolher Forma de Pagamento e escolher o Gateway de Pagamento, porém como escolher sem fazer a inclusão das devidas configurações.

**Comment by microreis** [comment]
Boa tarde @Sergiosantanati a configuração esta sendo feita internamente application/libraries/gateways

**Comment by Sergiosantanati** [comment]
Muito obrigado pela atenção Ramon.

E sobre o envio de e-mail que não está funcionando, tem alguma orientação?


Atenciosamente,


*Sergio Santana*

Quem quiser ser líder deve ser primeiro servo. Se você quiser liderar, deve
servir. #Jesus



Em qui., 12 de ago. de 2021 às 17:08, MRIE ***@***.***>
escreveu:
