### ISSUE TITLE
No cadastro de Produtos quando for Entrada solicitar Fornecedor

### ISSUE THREAD

**Issue by Sergiosantanati** [RamonSilva20/mapos#1477]
Boa tarde!

No menu Produtos, quando tiver marcado o tipo de movimento Entrada, abrir a opção para selecionar o fornecedor que tiver cadastrado em Cliente/Fornecedor.

**Comment by cabralwms** [comment]
Eu acho que seria legal ter esse campo fornecedor/entrada fora do cadastro de clientes, seria mais organizado eu acredito, fora que pode fazer um controle muito melhor futuro e implementações.
