### ISSUE TITLE
Janela modal não está funcionando, gerar pagamentos também não funciona

### ISSUE THREAD

**Issue by Lucios1989** [RamonSilva20/mapos#1478]
Boa noite,
Hoje fui fazer uns testes no sistema e percebi que ao fazer qualquer update, o sistema até executa, mas não informa na janela modal essa atualização.
Não sei se é por conta desse problema, mas também não está gerando pagamento.

Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [CentOS7]
 - Navegador [Opera]
 - Versão [4.30.0]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@Lucios1989 Suas credenciais dos gateways de pagamento estão configuradas. Recomendo atualizar manualmente mesmo pois infelizlmente o atualizador por dentro do sistema apresenta alguns bugs.

**Comment by Lucios1989** [comment]
Oi @Pr3d4dor , sim eu já tinha configurado manualmente e estava funcionando. Tive um problema no meu apache no sábado, tive que parar o serviço e depois iniciá-lo novamente. Após esse procedimento, as modais não funcionam mais e o Mercado Pago não processa mais. Não gera erro, simplesmente nada acontece. Por isso minha dúvida se o problema com as janelas modais de atualização não teriam relação com esse problema.

**Comment by Pr3d4dor** [comment]
@Lucios1989 Estranho, veja se tem algum log de erro na pasta application/logs

**Comment by Lucios1989** [comment]
Boa tarde @Pr3d4dor , eu acabe fazendo o mesmo procedimento que fiz anteriormente. Fiz uma instalação limpa novamente, restaurei a base de dados e tudo voltou ao normal. O único erro que tem nos logs é o mesmo que já me acompanha por um bom tempo, mesmo com o sistema funcionando perfeitamente:
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 5.4.16. /application/vendor/composer/platform_check.php 25
Tanto no Xampp quanto no Linux.
