### ISSUE TITLE
Erro ao cadastrar OS

### ISSUE THREAD

**Issue by jailtonurbano** [RamonSilva20/mapos#148]
Ao abrir uma os como admin o sistema gera erro:
Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente e responsável.

https://drive.google.com/file/d/19IHDD8T8cCaXf69RSVAFhGJZIXxoCXdL/view?usp=sharing

**Comment by Pr3d4dor** [comment]
A OS é realmente aberta ou o erro é exibido somente na tentativa de criar uma?

Verifique se os campos foram preenchidos corretamente.

**Comment by jailtonurbano** [comment]
A os como admin não abre.
A os como mine abre.

**Comment by allanalcantara** [comment]
As Abas somente são mostradas quando voce cadastra a O.S.
Obrigatoriamente somente diz que é obrigado 4 informações.
Cliente / Tecnico
Data inicial / Data final. preencha apenas isso e tente salvar;.

**Comment by jailtonurbano** [comment]
Faltou somente um asterisco na data final.
Funcionou perfeitamente.
