### ISSUE TITLE
ERRO AO GERAR RELATORIO EM PDF

### ISSUE THREAD

**Issue by zedopicadin** [RamonSilva20/mapos#1480]
não consigo gerar nem um tipo de relatório em pdf
![Captura de tela 2021-08-16 140207](https://user-images.githubusercontent.com/89035321/129606281-07a54ea2-5d6b-48da-bc72-ed36000746fd.png)

porem em xls funciona normal só a ordem q bem meio bagunçada.

testei tento no XAMPP quanto online da o mesmo resultado.

já fiz o processo de ir em: Configurações >> Emitente e atualize a Logo.
mas o erro continua

**Comment by Pr3d4dor** [comment]
Parece que sua imagem é PNG?

Tente converter a imagem do seu logo para JPG e usar. Ou terá que habilitar no seu PHP na biblioteca GD o suporte à PNG.

**Comment by zedopicadin** [comment]
Sim, ela está em PNG.
Acabei de ver que minha extensão GD está desativada... como faço para ativar rs ?

**Comment by Pr3d4dor** [comment]
@zedopicadin Você está usando no wamp ou na hospedagem?

**Comment by Sergiosantanati** [comment]
Boa tarde estou com o mesmo problema e utilizo hospedagem da Hostgator, como faço para resolver?
