### ISSUE TITLE
Exibir desconto na OS do cliente

### ISSUE THREAD

**Issue by allanredante** [RamonSilva20/mapos#1483]
Boa tarde pessoal.

Existe alguma forma de aplicarmos desconto diretamente na OS?

Para mostrar para o cliente a OS já com desconto?
![Capturar](https://user-images.githubusercontent.com/86257217/130674468-702251ba-c524-41d1-852b-daddb981dfdf.PNG)

**Comment by imc7897** [comment]
Existe, deu um trabalhão. Porque tive que mudar o QR code, gráficos, relatórios

![image](https://user-images.githubusercontent.com/85318272/130691646-5510b407-ea45-41f3-a0b6-a2741a049fcd.png)

**Comment by cabralwms** [comment]
Passa o código para nós, muito importante esse campo desconto. Tanto em vendas como Ordens de Serviços.

**Comment by wgiacomelli** [comment]
Importante essa alteração, acredito que muitos serão beneficiados.
