### ISSUE TITLE
Resultados por página

### ISSUE THREAD

**Issue by juniormb** [RamonSilva20/mapos#1484]
Como faço pra alterar os resultados por página do id="tabela", ele da a opção de 10, 25, 50 e 100, mas queria alterar esses valores para 1000 e não encontrei o arquivo onde precisa modificar.
![Capturar](https://user-images.githubusercontent.com/89545517/130849313-03740486-026a-4d7a-ac4a-478637bf2d47.PNG)

**Comment by Pr3d4dor** [comment]
Esses valores são configurados pelo dataTables automaticamente.
