### ISSUE TITLE
Problema na parte do boleto mercado pago, atualizar, confirmar, e excluir e tbm em cancelar pagamento

### ISSUE THREAD

**Issue by Naldotec** [RamonSilva20/mapos#1485]
Problema na parte do boleto mercado pago, atualizar, confirmar, e excluir e tbm em cancelar pagamento
Usando qualquer navegador tanto em smartphone quanto Pc

**Comment by Pr3d4dor** [comment]
@Naldotec As credenciais foram configuradas corretamente?

**Comment by Naldotec** [comment]
Eu coloquei os dados que estava disponível no mercado pago,

Em qua, 8 de set de 2021 22:27, Gianluca Bine ***@***.***>
escreveu:

**Comment by dgcursino** [comment]
eu vi que tem mais dados mais a plataforma so forneceu 3 dados:
'access_token' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'public_key' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'client_secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'client_id' => 'xxxxxxxxxxxxxxxxxxxx',

Aguem resolveu?

            'integrator_id' => '',
            'platform_id' => '',
            'corporation_id' => ''

**Comment by Naldotec** [comment]
Exatamente, o restante dos dados não sei como conseguir a configuração,
pois não é  fornecido pelo mercado pago

Em ter, 21 de set de 2021 23:52, dgcursino ***@***.***>
escreveu:

**Comment by dgcursino** [comment]
Eu acho que o motivo do erro do cancelamento é esse. Pois ele gera o boleto
mas não consegue apagar da plataforma do mercado pago. Ele só gera os
boletos.

E não consegue gerar uma nova fatura pois tem uma em aberto.

Em qua, 22 de set de 2021 08:25, Naldotec ***@***.***>
escreveu:

**Comment by Naldotec** [comment]
Será que tem um meio de resolver ?

Em qua, 22 de set de 2021 08:49, dgcursino ***@***.***>
escreveu:

**Comment by Pr3d4dor** [comment]
Eu vou tentar investigar o problema no final de semana

**Comment by Naldotec** [comment]
Obrigado!

Em qui, 23 de set de 2021 18:59, Gianluca Bine ***@***.***>
escreveu:
