### ISSUE TITLE
Big em editar os, usando smartfone em pe, na posição deitada funciona normal

### ISSUE THREAD

**Issue by Naldotec** [RamonSilva20/mapos#1486]
Big em editar os, usando smartfone em pe, na posição deitada funciona normal

**Comment by Pr3d4dor** [comment]
@Naldotec O mapos não tem foco para ser utilizado em celulares, mas se puder especificar onde que o layout apresenta problemas ficaria melhor para corrigirmos futuramente.

**Comment by Naldotec** [comment]
O problema apresenta na parte de edição da os com a tela em pé na posição
normal do aparelho, já com a tela deitada está normal

Em qua, 8 de set de 2021 22:27, Gianluca Bine ***@***.***>
escreveu:
