### ISSUE TITLE
Emails só chega se for do mesmo Host da Hospedagem

### ISSUE THREAD

**Issue by luc1anocruz** [RamonSilva20/mapos#1488]
Estou com ultima versao do MAPOS, todo configurado certinho,  banco, crons, versao de PHP,  mas notei que os emails não chegam para dominios externos,  se for dominio interno ele chega normal,    hospedagem da Hostgator,  ja testei com SSL e sem SSL,  e o problema persiste.

Exemplo de como funciona:  Meu dominio    teste.com.br   se o cliente for joao@teste.com.br entao ele recebe o email,  se caso ele for joao@hotmail.com  ou joao@gmail.com  ou qualquer outro email,  entao ele nao recebe.

Lembrando que isso nao tem haver com crons, ou configuracao de email,  ja que tudo se encontra perfeitamente configurado, e
os emails ficam marcados como Enviados sem erros algum.  

Hospedagem:  Hostgator compartilhada.

Ja entrei em contato com suporte da Hostgator, e apos analise do mesmo me responderam que isso é um Bug do sistema, que falta um parametro de configuração para envio externo. (mas nao me falaram qual)

Os emails funcionavam tao bem com PHPMailer nas primeiras versoes do MAPOS,  não sei porque mudaram, já que a maioria que usa é MEI pequenas empresas que nao tem fluxos e filas grandes de emails, tipo clicou ja enviou, mudou status ja enviou, e bastava configurar o phpmailer

**Comment by Sergiosantanati** [comment]
Bom dia, reforçando a sua solicitação eu também utilizo Hostgator e estou com o mesmo problema e já reportei aqui, acredito que na nova versão seja corrigido e implementado melhorias sugeridas pala comunidade.

**Comment by luc1anocruz** [comment]
Teriam quem implementar o PHPMailer igual lá no inicio nas primeiras versoes, esse nunca teve problemas e funcionava bem para mim

**Comment by luc1anocruz** [comment]
Complementando meu problema, eu resolvi usanco a o protocolo mail no lugar do SMTP, e entao os emails chegaram nos dominios externos, claro que isso precisa ser resolvido de uma outra forma, pois protocolo mail os email podem cair muito no spam

**Comment by LeoNMeireles** [comment]
desculpe a minha pergunta mas vc poderia me auxiliar a configurar o protocolo mail e quais as portas que devo utilizar?

**Comment by LeoNMeireles** [comment]
> Complementando meu problema, eu resolvi usanco a o protocolo mail no lugar do SMTP, e entao os emails chegaram nos dominios externos, claro que isso precisa ser resolvido de uma outra forma, pois protocolo mail os email podem cair muito no spam

desculpe a minha pergunta mas vc poderia me auxiliar a configurar o protocolo mail e quais as portas que devo utilizar?
