### ISSUE TITLE
Erro Instalação

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#1489]
Opa, tudo blz?
Formatei a minha maquina e, baixei novamente o mapos ... ao instalar apresenta erro no "composer install"

`Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - chillerlan/php-qrcode is locked to version 4.2.0 and an update of this package was not requested.
    - chillerlan/php-qrcode 4.2.0 requires php ^7.2 -> your php version (8.0.9) does not satisfy that requirement.
  Problem 2
    - chillerlan/php-settings-container is locked to version 2.1.0 and an update of this package was not requested.
    - chillerlan/php-settings-container 2.1.0 requires php ^7.2 -> your php version (8.0.9) does not satisfy that requirement.
  Problem 3
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.9) does not satisfy that requirement.
  Problem 4
    - piggly/php-pix is locked to version 1.2.6 and an update of this package was not requested.
    - piggly/php-pix 1.2.6 requires chillerlan/php-qrcode ^3.4 -> found chillerlan/php-qrcode[4.2.0] but it does not match the constraint.`

como posso resolver?

**Comment by codemasher** [comment]
Hi, i just stumbled across this issue - i have fixed the requirement for the v3.4 branch of `chillerlan/php-qrcode` (as of 3.4.1) so that it also will install on PHP8. However, v4.3.x is recommended but this would require PHP7.4+ and therefore a change in `piggly/php-pix` (pinging @caiquearaujo).
