### ISSUE TITLE
Abas não aparecem ao abrir os como cliente

### ISSUE THREAD

**Issue by jailtonurbano** [RamonSilva20/mapos#149]
Ao adicionar os acessando o Mine as abas não ficam disponiveis. Exemplo aba anexos.

https://drive.google.com/file/d/19IHDD8T8cCaXf69RSVAFhGJZIXxoCXdL/view?usp=sharing

**Comment by allanalcantara** [comment]
Somente cria as abas quando voce salva a OS

**Comment by jailtonurbano** [comment]
Fechou. Isso mesmo,
