### ISSUE TITLE
Dashboards - ajustar casas decimais

### ISSUE THREAD

**Issue by wgiacomelli** [RamonSilva20/mapos#1490]
Dashboards com valores inconsistentes

Valor exibido contém números ZEROS além do esperado.
![image](https://user-images.githubusercontent.com/37094545/132096554-ea35fd0b-c493-4625-a77d-33694dad1f4d.png)

Após posicionar  o mouse acima do gráfico o valor exibido é o correto.
![image](https://user-images.githubusercontent.com/37094545/132096581-5c91aea9-4421-4321-bb42-d14e788cd684.png)

**Comment by wgiacomelli** [comment]
Alguém mais com esse problema?

**Comment by wgiacomelli** [comment]
Up!

**Comment by horanerd** [comment]
Olhei aqui esta normal, chegou a ver se quando foi cadastrado esta receita ela não esta com 0 a mais ?
