### ISSUE TITLE
Dificuldade para alterar status.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#1491]
Fala meus amigos, blz?
A cada atualização do sistema, eu altero o nome dos status das O.S, assim facilitando para os meus clientes.
Porém nessa ultima atualização, acabou que ao alterar o nome do STATUS, ele não puxou no sistema.

![image](https://user-images.githubusercontent.com/21310068/132131612-4fc1fd30-655a-407a-b13c-db3f00106593.png)

Como podem ver, o "pago" não esta buscando.
Porém fiz a alteração dentro da pasta correta: 
![image](https://user-images.githubusercontent.com/21310068/132133719-3788d3a8-837f-4add-a604-0a6bcae41a2e.png)

**Comment by jsfachini** [comment]
@Triaca  Modificou o arquivo **Configurar** também?  (views\mapos\configurar)

OBS: as alterações para tornar valido os termos **Ex: PAGO** todos os arquivos relacionados com OS tem que constar essa alteração/modificação.
