### ISSUE TITLE
bug de mensagem após uma ação

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#1493]
** Bug na mensagem após executar uma ação**
EX: Ao adcionar um cliente ou uma OS ou qualquer outra ação que apareça aquela mensagem escrita, "Cliente ou OS ou venda etc, adicionado com sucesso". 
Quando clica em cima de qualquer item do menu, dentro do mapos, a mesma mensagem da ultima ação executada aparece na tela. A cada clique nos links dos menus, a mensagem volta a aparecer.
Se criar uma OS por ultimo, a mensagem fica aparecendo sempre no click em qualquer item do menu.

**Comportamento esperado**
A mensagem não ficasse aparecendo a cada click.

** Desktop (preencha as seguintes informações): **
 - SO: [LUBUNTU - linux 5.11.0-16-generic]
 - Navegador [midori, chrome e firefox]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@guskid Isso parece ser um problema de JavaScript. Onde você está hospedando o seu mapos?

**Comment by guskid** [comment]
> @guskid Isso parece ser um problema de JavaScript. Onde você está hospedando o seu mapos?

Estou no xampp do linux.
Tenho uma instalação na versão 4.1.0 também que apresenta o mesmo erro.

**Comment by guskid** [comment]
Unica solução que encontrei no momento foi removendo o arquivo " sweetalert.min.js ".
Tentei fazer atualização de js no pc e não deu boa. 
Só removendo o arquivo mesmo.
