### ISSUE TITLE
erro asaas

### ISSUE THREAD

**Issue by rogowski193** [RamonSilva20/mapos#1494]
ola!
estou tentando configurar o pagamento pelo asaas mas estou tendo o erro "Erro ao criar cliente na Asaas!" ao  tentar gerar a cobrança,  
já configurei o api no php,

teria algum manual para podermos revisar se foi feito a configuração certo?

**Comment by Pr3d4dor** [comment]
@rogowski193 Como você configurou as credenciais? Qual versão de PHP você está utilizando?

**Comment by rogowski193** [comment]
hoje tenho hospedado o sistema na hostgator PHP 7.3, tudo funcionando certinho somente este erro 

![erro](https://user-images.githubusercontent.com/80807543/132609677-fa743e49-5dca-4974-8a87-5986fc78fe03.png)




porem ele cria o cliente la na plataforma do asaas mas nao gera a fatura



![cod](https://user-images.githubusercontent.com/80807543/132609702-b1f6caaa-9812-46dd-9517-b5f408e8e06b.jpg)

**Comment by rogowski193** [comment]
Alguém já passou por este erro e conseguiu resolver?
Ainda estou na mesma!
Não gera a cobrança mas cria o usuário no sistema asaas!
