### ISSUE TITLE
Nao consigo instalar o MAPOS

### ISSUE THREAD

**Issue by vessc** [RamonSilva20/mapos#1495]
** Descreva o bug **
/var/www/html/mapos-4.34.0$ composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mk-j/php_xlsxwriter 0.38 -> satisfiable by mk-j/php_xlsxwriter[0.38].
    - mk-j/php_xlsxwriter 0.38 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  Problem 2
    - Installation request for mpdf/mpdf v8.0.11 -> satisfiable by mpdf/mpdf[v8.0.11].
    - mpdf/mpdf v8.0.11 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 3
    - Installation request for phpoffice/phpword 0.18.1 -> satisfiable by phpoffice/phpword[0.18.1].
    - phpoffice/phpword 0.18.1 requires ext-xml * -> the requested PHP extension xml is missing from your system.
  Problem 4
    - Installation request for piggly/php-pix 1.2.6 -> satisfiable by piggly/php-pix[1.2.6].
    - piggly/php-pix 1.2.6 requires ext-gd * -> the requested PHP extension gd is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comportamento esperado**
Instalar o MAPOS

** Capturas de tela **
Efetuei a copia de todo processo e colei acima

** Desktop (preencha as seguintes informações): **
 - Linux Mint 20.2 Cinnamon
 - Navegador [Firefox}
 - 92.0 (64-bits

** Contexto adicional **
Estou tentando instalar o MAPOS mas nao consigo, poderia me ajudar?

**Comment by vessc** [comment]
movi o diretorio do MAPOS para um diretorio anterior, executei o comando novamente...

servidor@fileserver:/var/www/mapos-4.34.0$ docker-compose up --force-recreate
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by Pr3d4dor** [comment]
@vessc Conforme essas mensagens:
```
Problem 1
- Installation request for mk-j/php_xlsxwriter 0.38 -> satisfiable by mk-j/php_xlsxwriter[0.38].
- mk-j/php_xlsxwriter 0.38 requires ext-zip * -> the requested PHP extension zip is missing from your system.
Problem 2
- Installation request for mpdf/mpdf v8.0.11 -> satisfiable by mpdf/mpdf[v8.0.11].
- mpdf/mpdf v8.0.11 requires ext-gd * -> the requested PHP extension gd is missing from your system.
Problem 3
- Installation request for phpoffice/phpword 0.18.1 -> satisfiable by phpoffice/phpword[0.18.1].
- phpoffice/phpword 0.18.1 requires ext-xml * -> the requested PHP extension xml is missing from your system.
Problem 4
- Installation request for piggly/php-pix 1.2.6 -> satisfiable by piggly/php-pix[1.2.6].
- piggly/php-pix 1.2.6 requires ext-gd * -> the requested PHP extension gd is missing from your system.
```

Estão faltando as extensões gd, zip e xml no seu PHP.

**Comment by vessc** [comment]
eu nao faço ideia do que seja isso...mas blz....obrigado

**Comment by vessc** [comment]
consegui instalar

**Comment by Edivandro** [comment]
#Meu BUG é semelhante ao que parece o composer não consegue instalar os pack:

#Maquina:
    Operating System: Arch Linux                                   
    Kernel: Linux 5.14.15-arch1-1
    Architecture: x86-64
    Hardware Vendor: SAMSUNG ELECTRONICS CO., LTD.
    Hardware Model: 300E5EV/300E4EV/270E5EV/270E4EV/2470EV/2470EE

#Procedimento:
/srv/httpd/mapos-master$ composer install --no-dev
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 2
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 3
    - piggly/php-pix is locked to version 1.2.8 and an update of this package was not requested.
    - piggly/php-pix 1.2.8 requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 4
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Edivandro** [comment]
#Meu BUG é semelhante, parece que o composer não consegue instalar os pack:

#Maquina: obs. APACHE, PHP, MARIADB instalados individuais-(SEM XAMPP)
    Operating System: Arch Linux                                   
    Kernel: Linux 5.14.15-arch1-1
    Architecture: x86-64
    Hardware Vendor: SAMSUNG ELECTRONICS CO., LTD.
    Hardware Model: 300E5EV/300E4EV/270E5EV/270E4EV/2470EV/2470EE

#Procedimento:
/srv/httpd/mapos-master$ composer install --no-dev
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 2
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 3
    - piggly/php-pix is locked to version 1.2.8 and an update of this package was not requested.
    - piggly/php-pix 1.2.8 requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 4
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Edivandro** [comment]
#Meu BUG é semelhante, parece que o composer não consegue instalar os pack:

#Maquina: obs. APACHE, PHP, MARIADB instalados individuais-(SEM XAMPP).
    Operating System: Arch Linux                                   
    Kernel: Linux 5.14.15-arch1-1
    Architecture: x86-64
    Hardware Vendor: SAMSUNG ELECTRONICS CO., LTD.
    Hardware Model: 300E5EV/300E4EV/270E5EV/270E4EV/2470EV/2470EE

#Procedimento:
`/srv/http/mapos-master$ composer install --no-dev`
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 2
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 3
    - piggly/php-pix is locked to version 1.2.8 and an update of this package was not requested.
    - piggly/php-pix 1.2.8 requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 4
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
    - codephix/asaas-sdk is locked to version dev-master and an update of this package was not requested.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by RamonSilva20** [comment]
Olá @Edivandro, faça o downgrade para a versão 7.4 do PHP.

**Comment by Edivandro** [comment]
Após downgrade o erro persistia, mas a instalação foi possível usando o comando:
composer install --ignore-platform-reqs

Conforme este post: https://github.com/composer/composer/issues/9529

**Comment by evertonrj** [comment]
Aconteceu comigo no ambiente do Laragon com o PHP 8.2, fiz o downgrade para 8.1 e resolveu


Agluem sabe dizer como corrige esse bug?
