### ISSUE TITLE
Relátorios

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1496]
Boa tarde alguém pode me ajudar com esse problema?

Ao tentar abrir os relatórios recebo este erro.
![erro](https://user-images.githubusercontent.com/71839236/132915184-a2f40d3d-5383-45be-b2f6-5041ef714568.jpg)

**Comment by Pr3d4dor** [comment]
@p-francelino Tenta ir em Configurações >> Emitente e refazer o upload do logo da sua empresa.

**Comment by p-francelino** [comment]
Valeu, depois de refazer o upload da logo normalizou.
