### ISSUE TITLE
Troca dos dados do usuário não aceita troca do CPF 600.021.520-87

### ISSUE THREAD

**Issue by BrenoHeydy** [RamonSilva20/mapos#1504]
Ao acessar o mapos e ir em configurações/usuário ao editar os dados do usuário não aceita a troca do CPF so fica com o CPF 600.021.520-87
Poderiam me ajuda

**Comment by Pr3d4dor** [comment]
@BrenoHeydy Não entendi muito bem o problema, pode explicar melhor?
