### ISSUE TITLE
Modificação da View de Ordem de Serviço

### ISSUE THREAD

**Issue by R4T0** [RamonSilva20/mapos#1505]
Bom dia, no MapOS a emissão de uma Ordem de Serviço tem muitas caixas de texto, e ocupam toda a tela e quase não usamos. Observando a Modficação de um usuário achei a ideia dele interessante. Ao invés de 4 campos para escrever ele colocou apenas 2 campos, seria interessante essa atualização no MapOS.... 
![image](https://user-images.githubusercontent.com/73944522/134672774-39eef905-54e9-4473-8fea-35b8c098de7b.png)

**Comment by MarceloGrass** [comment]
Também achei muito boa essa modificação, me sumo a essa sugestão.

**Comment by Pr3d4dor** [comment]
@R4T0 Agradecemos a sugestão, mas não podemos remover as outras caixas de texto porque outro usuário do mapos pode ter utilizado elas.

**Comment by Ramaniks** [comment]
Seria possível um parâmetro para ocultar duas e essas demais ficariam fixas? Permitndo ocultar "Laudo Técnico" e/ou "Descrição Produto/Serviço" por exemplo!!

**Comment by R4T0** [comment]
@Pr3d4dor sendo assim poderia uma opção para ocultar elas não é?

**Comment by tonnybarros** [comment]
O ideal seria trabalhar com módulo, eu sou posto autorizado de várias marcas, e algumas tem seu próprio sistema, e em geral é bem simples, próprio a modificação que criei.

Pensando em criar um módulo, ou uma pasta view apenas para assistência técnica em TV e SOM, onde a instalação seria só substituir a pasta view, alguns controles, e add algumas tabelas no banco.

Ou ainda se puder criar vários módulo, e a pessoa escolhesse na instalação o seguimento do seu negocio, como assistência, mecanica, refrigeração, celulares, etc...
