### ISSUE TITLE
Error ao anexar imagem  Atenção! mkdir(): Disk quota exceeded

### ISSUE THREAD

**Issue by heraf250** [RamonSilva20/mapos#1507]
Olá estou com problema relacionado a anexao a imagem na os Atenção! mkdir(): Disk quota exceeded
Gostaria de saber como solucionar 
Desde já agradeço a atenção da comunidade

**Comment by heraf250** [comment]
Identifiquei que o mapos está gerando logs muito grande

**Comment by RamonSilva20** [comment]
Pode ser o nível de log utilizado. Se você usar por exemplo o nível 4, vai realmente gerar arquivos grandes.

    0 = Disables logging, Error logging TURNED OFF
    1 = Error Messages (including PHP errors)
    2 = Debug Messages
    3 = Informational Messages
    4 = All Messages

**Comment by heraf250** [comment]
Desculpa pela minha ignorancia mas onde eu modifico o nivel de log utilizado ?

**Comment by RamonSilva20** [comment]
Linha 242 do arquivo `application/config/config.php`. 

https://github.com/RamonSilva20/mapos/blob/master/application/config/config.php#L242
