### ISSUE TITLE
Bloqueio de edição de OS em usuários diferentes simultâneos. 

### ISSUE THREAD

**Issue by GSNasciment0** [RamonSilva20/mapos#1508]
Olá,

Meus caros, estou usando o MAP-Os desde Agosto de 2020.
A adaptação ao sistema é rápida e simples.

Gostaria de solicitar uma configuração em que o sistema não permita que dois usuários não possam estar na tela de Edição da OS ao mesmo tempo.

Acontece que, se 2 usuários estiverem editando a mesa OS, os dados que ficam salvos no banco é a ultima alteração, deixando perdido quaisquer outros dados que possam ter sido inseridos anteriormente.

**Comment by Pr3d4dor** [comment]
@GSNasciment0 Vou adicionar na lista de sugestões.
