### ISSUE TITLE
Recebimento !

### ISSUE THREAD

**Issue by PauloAgape** [RamonSilva20/mapos#1509]
Boa tarde.
Gostaria de saber se tem previsao de colocar
multiplos recebimentos.
Porque muita vezes o cliente pagar em cheque ou cartao
2 ou 3 parcelas.
Obrigado.

**Comment by TK2KMG** [comment]
Olá PauloAgape.
Eu resolvi minha demanda, fazendo lançamentos de receitas, com datas futuras. 
Não sei se essa dica irá lhe atender.
