### ISSUE TITLE
refatorar area cliente

### ISSUE THREAD

**Issue by allanbarcelos** [RamonSilva20/mapos#151]
vou pegar a task "refatorar area de cliente" vou coloca-la em "in progress".

**Comment by skadbr** [comment]
Allan, estou com uma questão:
1. O cliente entra na área do cliente e faz o cadastro.
2. Apos o cadastro, o cliente entra na tela do login, informa email e documento(cpf), e depois clica em "Acessar".
![image](https://user-images.githubusercontent.com/47054994/51916658-ebe92c80-23c4-11e9-98dc-2351c5cf7b30.png)
3. O sistema ao inves de chamar "/index.php/mine/painel", não faz nada. E se entra com dado invalido, tambem não dá mensagem alguma.  Ou seja, o cliente não consegue entrar na sua área, a não ser que mude a url manualmente para "index.php/mine/painel", ai sim entra.
*Aparente ser algo a ver com ajax.
Tem alguma dica?
Obrigado.
