### ISSUE TITLE
Problema ao faturar OS com valor superior a 1000,00

### ISSUE THREAD

**Issue by CaramujoRei** [RamonSilva20/mapos#1510]
Estou com problemas ao faturar uma OS com valor superior a 1000,00 .
Quando fatura e olho no financeiro a OS consta apenas o primeiro numero, se for 1543,00 fica computado apenas 1,00. Caso seja 3500,00 fica 3,00.
Notei que ao faturar a OS se eu apenas clicar no valor antes de faturar não ocorre o problema.

**Comment by Andrefiel** [comment]
Isso também está acontecendo comigo, mais como paliativo depois de faturar vc altera o valor da fatura para o mesmo valor

**Comment by Pr3d4dor** [comment]
Obrigado pelo report do bug.

@CaramujoRei e @Andrefiel, criei uma PR que corrige esse problema: #1511.

Assim que for lançado uma nova versão do mapos, esse bug estará corrigido.
