### ISSUE TITLE
Não consigo mais acesso

### ISSUE THREAD

**Issue by Carlos87Cavalcante** [RamonSilva20/mapos#1518]
Não acessa mais a conta...

/home/vol6_5/epizy.com/epiz_28782370/htdocs/application/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php
                elseif (defined('MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT'))
                {
                    $client_flags |= MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT;
                }
            }
 
            if ( ! empty($ssl))
            {
                $client_flags |= MYSQLI_CLIENT_SSL;
                $this->_mysqli->ssl_set(
                    isset($ssl['key'])    ? $ssl['key']    : NULL,
                    isset($ssl['cert'])   ? $ssl['cert']   : NULL,
                    isset($ssl['ca'])     ? $ssl['ca']     : NULL,
                    isset($ssl['capath']) ? $ssl['capath'] : NULL,
                    isset($ssl['cipher']) ? $ssl['cipher'] : NULL
                );
            }
        }
 
        if ($this->_mysqli->real_connect($hostname, $this->username, $this->password, $this->database, $port, $socket, $client_flags))
        {
            // Prior to version 5.7.3, MySQL silently downgrades to an unencrypted connection if SSL setup fails
            if (
                ($client_flags & MYSQLI_CLIENT_SSL)
                && version_compare($this->_mysqli->client_info, '5.7.3', '<=')
                && empty($this->_mysqli->query("SHOW STATUS LIKE 'ssl_cipher'")->fetch_object()->Value)
            )
            {
                $this->_mysqli->close();
                $message = 'MySQLi was configured for an SSL connection, but got an unencrypted connection instead!';
                log_message('error', $message);
                return ($this->db_debug) ? $this->display_error($message, '', TRUE) : FALSE;
            }
 
            return $this->_mysqli;
        }
 
        return FALSE;
    }
 
Arguments
"mysqli::real_connect(): (HY000/2002): Connection refused"

**Comment by Pr3d4dor** [comment]
@Carlos87Cavalcante As configurações de conexão com o seu banco de dados estão corretas?
