### ISSUE TITLE
Mapos 4.35.2

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1522]
Ao instalar a versão atual recebo a seguinte resposta.
A pagina não existe
![mapos](https://user-images.githubusercontent.com/71839236/136825171-b8f1bec1-fb87-44e4-9c00-d6985cef2552.jpg)
.

**Comment by Pr3d4dor** [comment]
@p-francelino Conseguiu resolver?

Não consegui simular o problema.
