### ISSUE TITLE
Pesquisa de Cliente BUG

### ISSUE THREAD

**Issue by BrunoCastroRS** [RamonSilva20/mapos#1523]
Ao pesquisar cliente se não estiver na mesma aba ele não encontra .

![Desktop Screenshot 2021 10 12 - 00 23 55 97 (2)](https://user-images.githubusercontent.com/92350091/136975096-2b55f457-47e5-4ff8-9259-1ef2589a856c.png)
![Desktop Screenshot 2021 10 12 - 00 24 00 10](https://user-images.githubusercontent.com/92350091/136975100-3a1e49bd-1dd4-44a1-a6d9-8dbd1bc04fe2.png)
![Desktop Screenshot 2021 10 12 - 00 24 06 83](https://user-images.githubusercontent.com/92350091/136975104-b49d0145-3aad-4edd-b860-65365e8a191b.png)

**Comment by Pr3d4dor** [comment]
@BrunoCastroRS Não é um bug pois o datatables funciona dessa maneira mesmo e só realiza a busca no registros que estão aparecendo na tela.

**Comment by BrunoCastroRS** [comment]
Sim , agora imagina eu ter 50 telas tenho q procurar um por um , fica dificil achar
