### ISSUE TITLE
Alteração.

### ISSUE THREAD

**Issue by VoidUFC** [RamonSilva20/mapos#1524]
Olá, estou utilizando o sistema em minha loja, gostei muito. 
Fizemos algumas alterações na parte visual pra ficar com a cara da nossa loja. 
Eu gostaria de saber em quais arquivos tenho alterar para que quando eu mude o nome da pasta "mapos" ele não me retorne erro 404.

**Comment by dgcursino** [comment]
\application\config

$config['base_url'] = 'http://localhost/mapos/'
