### ISSUE TITLE
Vencimento das cobranças

### ISSUE THREAD

**Issue by metalfox** [RamonSilva20/mapos#1532]
Gostaria de saber se existe a possibilidade das cobranças geradas (Gerencianet) capturassem a data final das O.S como vencimento, ou dinamicamente no ato do lançamento da mesma, tentei criar algo para preencher a variável 'boleto_expiration' => 'P3D', mais sem sucesso.
![image](https://user-images.githubusercontent.com/814764/139439770-84b9d467-d5f4-4b44-a4e0-f432a68cc79d.png)

**Comment by Pr3d4dor** [comment]
@metalfox É possível, mas teria que adequar o código.

**Comment by metalfox** [comment]
> @metalfox É possível, mas teria que adequar o código.

Creio que ajudaria bastante, obrigado por responder.
