### ISSUE TITLE
sistema de os modificação

### ISSUE THREAD

**Issue by HDTur** [RamonSilva20/mapos#1537]
Gostaria se possivel deixar um texto fixo nas observações em todas as OS e que nas novas apareça também.

**Comment by Pr3d4dor** [comment]
@HDTur Você pode editar o HTML pra já vir preenchido com o texto no input. As OS que já existem você terá que editar no banco de dados para colocar o texto.

**Comment by HerbertRuan** [comment]
@HDTur fiz isso que vc quer no meu , mais nada proficional . se quiser te passo como fiz.

**Comment by HDTur** [comment]
@HerbertRuan cara se não for te incomodar eu gostaria
