### ISSUE TITLE
COMPOSER

### ISSUE THREAD

**Issue by allanpmelo** [RamonSilva20/mapos#1538]
Não seria um erro, mas estou com a seguinte mensagem após a instalação:
Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

O que devo fazer ?

**Comment by allanpmelo** [comment]
Deu certo, porém agora está com um erro de SSL, mas tenho SSL em minha hospedagem

**Comment by Pr3d4dor** [comment]
@allanpmelo Qual é o erro exato?
