### ISSUE TITLE
Página pagamentos..

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#1539]
![image](https://user-images.githubusercontent.com/61605704/140631261-cc57abea-e270-41a1-bba7-4fe9097bdd21.png)
Ao clicar configurações > pagamentos da o seguinte erro The page you requested was not found.

**Comment by matheuscorteletti** [comment]
além disso quando entro em configurações > sistema e salvo da o seguinte erro..


The Notificação Whatsapp field is required.

The Controle de Baixa field is required.

The Controle de Edição de OS field is required.

The Controle de Visualização em DataTables field is required.

Selecione ao menos uma das opções

**Comment by Pr3d4dor** [comment]
@matheuscorteletti Parece ser um problema com a configuração da hospedagem ou do .htaccess, você mexeu neles?

**Comment by matheuscorteletti** [comment]
# BEGIN LSCACHE
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
<IfModule LiteSpeed>
RewriteEngine on
CacheLookup on
RewriteRule .* - [E=Cache-Control:no-autoflush]
RewriteRule \.litespeed_conf\.dat - [F,L]

### marker CACHE RESOURCE start ###
RewriteRule wp-content/.*/[^/]*(responsive|css|js|dynamic|loader|fonts)\.php - [E=cache-control:max-age=3600]
### marker CACHE RESOURCE end ###

### marker FAVICON start ###
RewriteRule favicon\.ico$ - [E=cache-control:max-age=86400]
### marker FAVICON end ###

### marker DROPQS start ###
CacheKeyModify -qs:fbclid
CacheKeyModify -qs:gclid
CacheKeyModify -qs:utm*
CacheKeyModify -qs:_ga
### marker DROPQS end ###

</IfModule>
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
# END LSCACHE
# BEGIN NON_LSCACHE
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
# END NON_LSCACHE
# BEGIN WordPress
# As diretrizes (linhas) entre "BEGIN WordPress" e "END WordPress" são
# geradas dinamicamente e só devem ser modificadas através de filtros do WordPress.
# Quaisquer alterações nas diretivas entre esses marcadores serão sobrescritas.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

**Comment by matheuscorteletti** [comment]
![image](https://user-images.githubusercontent.com/61605704/140984782-95add5a8-910b-4058-99a8-3ce14d4a3c80.png)

**Comment by matheuscorteletti** [comment]
reenviei os arquivos e resolveu o problema...
