### ISSUE TITLE
Quero colocar todas as informações da foto no visualizar vendas 

### ISSUE THREAD

**Issue by FabianaBras** [RamonSilva20/mapos#1542]
![image](https://user-images.githubusercontent.com/93921367/140961832-3fc8f793-ec39-44a7-a3c9-9ef8920f256f.png)

**Comment by FabianaBras** [comment]
Quero colocar todas essas informações ai da venda, no visualizar venda, alguém pode me ajudar ?

**Comment by Pr3d4dor** [comment]
@FabianaBras Você vai precisar criar esses 3 novos campos no seu banco de dados e fazer a adequação no vendas controller para salvar-los.
