### ISSUE TITLE
Lista de clientes com apenas 10 registros por página, mesmo configurando para mostrar 100.

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#1544]
** Descreva o bug **
Quando configurado no sistema para mostrar 100 registros por página, ao acessar a lista de clientes, apenas 10 registros são mostrados na página.
Logo no canto inferior direito existe uma singela lista de 10 páginas para rolar, como se fosse gerado automaticamente e no canto inferior esquerdo a paginação gerada pelo sistema.

Caso tenha uma lista de 150 clientes, dentro dessas condições, ao exibir a lista acontecerá:

No canto inferior esquerdo, a listagem adequada do sistema apresentará duas páginas.
A primeira página com 10 registros e no canto inferior direito 10 abas para navegar.
Na segunda página terá também 10 registros e no canto inferior direito, 5 abas para navegar.

**Comment by Pr3d4dor** [comment]
@Doonine Iremos verificar o problema
