### ISSUE TITLE
Na página de cadastro de clientes, o campo de pesquisa não está pesquisando corretamente.

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#1545]
Com uma lista de muitos clientes, caso precise acessar diretamente o cadastro de algum deles para qualquer alteração, será necessário buscar na lista.
Na página de registro dos clientes, ao acessar, é apresentando uma lista de todos os clientes e também um campo para pesquisar o cliente.
Nesse campo de pesquisa, o resultado dessa pesquisa não é confiável.
Parece que ele não busca nos registros mais antigos, apenas nos mais novos.
Exemplo:

Caso tenha 3 registros com o nome de Fernando.
Registro 15 = Fernando Ferreira
Registro 79 = Fernando Lucas
Registro 129 = Fernando Silva

Na ferramenta de busca, ao pesquisar por Fernando, o registro 15 é mais provável dele encontrar, o 129 ele não encontra.

**Comment by Pr3d4dor** [comment]
@Doonine Iremos verificar.
