### ISSUE TITLE
Erro ao Excluir Ordem de Serviço

### ISSUE THREAD

**Issue by Deniizynhu** [RamonSilva20/mapos#1546]
Gostaria de parabenizar os criadores e colaboradores do projeto, é muito bom o sistema.
Mas estou tendo algumas dificuldades, ainda está em fase de implantação.

1. Consigo cadastrar a O.S e realizar qualquer alteração, porém quando eu mando excluir, ele dá o erro na imagem abaixo.
Sistema Hospedado na Locaweb

2. Gostaria de tirar o botão "CADASTRAR" na área do cliente, mas não estou conseguindo achar o local exato desse código.

3. Após qualquer ação executada, fica aparecendo toda hora o pop up de confirmação do procedimento realizado.

Alguém consegue me ajudar?

![image](https://user-images.githubusercontent.com/94185161/141489952-a72a6e09-86ab-4369-9516-e1c5c2fef2a4.png)

**Comment by Pr3d4dor** [comment]
@Deniizynhu qual a versão do PHP que está sendo utilizado?

**Comment by Deniizynhu** [comment]
Versão 8.0
![image](https://user-images.githubusercontent.com/94185161/141524804-921cdea2-b027-42e1-8e9a-d9d40509842b.png)

**Comment by Pr3d4dor** [comment]
@Deniizynhu O mapos não é compatível com o PHP 8.0 ainda, recomendo usar o PHP 7.4 se puder.

**Comment by Deniizynhu** [comment]
Me desculpe pela demora na resposta. Fim de semana foi complicado.
Só uma pergunta, se eu mudar a versão do PHP eu vou perder os dados já inseridos?

**Comment by Deniizynhu** [comment]
A questão de Exclusão de O.S foi resolvido. muito obrigado @Pr3d4dor pelo auxilio. Resolveu numa boa e não perdi os dados.
Agora, consegue me auxiliar no 2° ponto?
Gostaria de retirar o botão de cadastrar da área do cliente, pois o cadastro terá que ser feito exclusivamente por nosso departamento responsável.
