### ISSUE TITLE
@Deniizynhu O mapos não é compatível com o PHP 8.0 ainda, recomendo usar o PHP 7.4 se puder.

### ISSUE THREAD

**Issue by Deniizynhu** [RamonSilva20/mapos#1547]
@Deniizynhu O mapos não é compatível com o PHP 8.0 ainda, recomendo usar o PHP 7.4 se puder.

_Originally posted by @Pr3d4dor in https://github.com/RamonSilva20/mapos/issues/1546#issuecomment-967761548_

Me desculpe pela demora na resposta. Fim de semana foi complicado.
Só uma pergunta, se eu mudar a versão do PHP eu vou perder os dados já inseridos?

**Comment by Deniizynhu** [comment]
Errei na resposta.

**Comment by Pr3d4dor** [comment]
@Deniizynhu Não irá perder os dados já inseridos não. Os dados ficam guardados no banco de dados (MySQL).
