### ISSUE TITLE
Erro nos redirecionamentos das páginas

### ISSUE THREAD

**Issue by vbrito17** [RamonSilva20/mapos#1548]
Estou com um probleminha e espero que essa comunidade possa me auxiliar na possível correção.

Eu instalei o MAPOS em minha hospedagem a versão mais recente, instalei e composer, configurei o banco de dados etc, tudo certinho. O sistema está funcionando até que bem, com exceção das páginas de redirecionamento/retorno aos comandos aplicados no sistema.

Por exemplo: Se eu for em qualquer uma das sessões (Clientes, Serviços, Fornecedores etc) todas as vezes que eu adiciono um novo item e clico em salvar, no retorno das páginas até a página anterior ao qual eu estava apresenta um erro de inserção duplicada na URL do site e só retorna depois que eu excluo a parte duplicada da URL (conforme está na foto em anexo)

![Capturar](https://user-images.githubusercontent.com/54509166/142017516-a2c82c76-d7fa-4c89-9758-228214dfe2aa.PNG)

Já mexi no arquivo Config.php porém não conseguir solucionar esse erro.

Alguém ai já teve algo parecido ou uma ajuda no que posso fazer para solucionar esse problema?

Fico grato.

**Comment by Pr3d4dor** [comment]
@vbrito17 Parece que o .htaccess pode estar configurado incorretamente.  Qual a sua hospedagem?

**Comment by vbrito17** [comment]
Minha hospedagem uma hospedagem simples para web, não é um servidor dedicado ou uma VPS. Atualmente estou utilizando da empresa Hostmídia. Já verifiquei esse arquivo (.htaccess) porém não encontrei erros aparentes. Não sei o que faço

**Comment by vbrito17** [comment]
> @vbrito17 Parece que o .htaccess pode estar configurado incorretamente. Qual a sua hospedagem?

Minha hospedagem uma hospedagem simples para web, não é um servidor dedicado ou uma VPS. Atualmente estou utilizando da empresa Hostmídia. Já verifiquei esse arquivo (.htaccess) porém não encontrei erros aparentes. Não sei o que faço

**Comment by Pr3d4dor** [comment]
@vbrito17 Como está configurado a URL em config.php?

**Comment by Pr3d4dor** [comment]
@vbrito17 O problema está na linha 42, você deve colocar:
```
$config['base_url'] = 'http://meusite.com.br';
```

**Comment by LucasPolli** [comment]
tive um problema parecido, no meu caso havia 3 versoes diferentes do php rodando, uso hostgatro entao da pra configurar manualmente qual versao vc quer, havia 3 configuracoes  em locais diferentes, inclusive uma no .htaccess, corrigi isso e nao tive mais problemas.
