### ISSUE TITLE
Pesquisar um serviço na lista só apresenta resultados que estão listados no momento

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#1556]
Supondo que tenha uma lista com 50 serviços diferentes e tenha configurado o sistema para mostrar apenas 10 por página.
Você terá uma lista com 10 resultados e 5 páginas.
Supondo que cada item da lista tenha o nome como um número, indo de 0 até 50, nesse cenário você terá na primeira página os serviços de 0 a 9, na segunda página de 10 a 19 e assim por diante.

Com a página 1 sendo exibida, e os resultados de 0 a 9 sendo listados nessa página, se você pesquisar qualquer resultado de 0 a 9, ele fará a pesquisa adequadamente e apresentará o resultado dentro dessa lista de 0 a 9. Mas se você pesquisar o número 42, nenhum resultado será apresentado.

**Comment by jonathasnp** [comment]
estou com o msm problema ..

**Comment by seitbnao** [comment]
Olá, foi respondido no issue  #1560
