### ISSUE TITLE
Produtos cadastrados não aparece quando add uma venda

### ISSUE THREAD

**Issue by evertonlsds** [RamonSilva20/mapos#1557]
** Descreva o bug **
Eu instalei a ultima versão e hospedei e ta funcionando . Cadastrei 4 produtos e cadastrei 2 clientes. Quando add a venda aparece o cliente p escolher, quando vou na aba produtos e tento colocar o produto cadastrado ele nao aparece, tento colocar o produto manualmente mas apresenta o seguinte erro
![20211124_131357](https://user-images.githubusercontent.com/69548570/143274848-0382e0ad-eefa-412d-85e9-4de5967dabff.jpg)

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@evertonlsds Marcou os produtos como "Saída"?

**Comment by evertonlsds** [comment]
@Pr3d4dor  Realmente foi isso.mesmo. so tava marcado entrada! Muito obrigado!!!
