### ISSUE TITLE
Impressão em formulário continuo 

### ISSUE THREAD

**Issue by jeffsys** [RamonSilva20/mapos#156]
Utilizo aqui na empresa um sistema em acess. Ele é muito antigo, e está dando falhas constantes. Gostaria de poder usar um sistema novo, mas, temos formulário continuo e impressão em matricial. É possível usar o mapos para imprimir no mesmo formulário? Como faço para padronizar de forma que os campos fiquem iguais ao que já uso?

**Comment by allanalcantara** [comment]
ai você teria que saber um pouco de modelagem, pois os campos ficarem iguais a impressão fica dificil, sem teste, manda um modelo teste de alguma impressão ...
