### ISSUE TITLE
erro na procura do produto 

### ISSUE THREAD

**Issue by jonathasnp** [RamonSilva20/mapos#1560]
Supondo que tenha uma lista com 50 serviços diferentes e tenha configurado o sistema para mostrar apenas 10 por página.
Você terá uma lista com 10 resultados e 5 páginas.
Supondo que cada item da lista tenha o nome como um número, indo de 0 até 50, nesse cenário você terá na primeira página os serviços de 0 a 9, na segunda página de 10 a 19 e assim por diante.

Com a página 1 sendo exibida, e os resultados de 0 a 9 sendo listados nessa página, se você pesquisar qualquer resultado de 0 a 9, ele fará a pesquisa adequadamente e apresentará o resultado dentro dessa lista de 0 a 9. Mas se você pesquisar o número 42, nenhum resultado será apresentado.

**Comment by seitbnao** [comment]
Olá, no arquivo mapos\application\models\Mapos_model.php

 Altere os limites das consultas para o desejado, não se trata de um bug expressamente dito

`    public function pesquisar($termo)
    {
        $data = [];
        // buscando clientes
        $this->db->like('nomeCliente', $termo);
        $this->db->or_like('telefone', $termo);
        $this->db->or_like('celular', $termo);
        $this->db->limit(15);
        $data['clientes'] = $this->db->get('clientes')->result();

        // buscando os
        $this->db->like('idOs', $termo);
        $this->db->or_like('descricaoProduto', $termo);
        $this->db->limit(15);// alterar o limite
        $data['os'] = $this->db->get('os')->result();

        // buscando produtos
        $this->db->like('codDeBarra', $termo);
        $this->db->or_like('descricao', $termo);
        $this->db->limit(50);// alterar o limite
        $data['produtos'] = $this->db->get('produtos')->result();

        //buscando serviços
        $this->db->like('nome', $termo);
        $this->db->limit(15);// alterar o limite
        $data['servicos'] = $this->db->get('servicos')->result();

        return $data;
    }`

**Comment by Doonine** [comment]
Eu não entendi o que você quis dizer...

Pareceu que você tentou dizer que, sempre que adicionar um produto, serviço ou registrar um novo cliente é necessário entrar no servidor para alterar o código do sistema, se não ele não pesquisa direito, e que isso é intencional.

**Comment by seitbnao** [comment]
No código está configurado desta forma, basta estabelecer um novo limite ou apenas remover ou comentar a linha, isso basta fazer apenas uma única vez.  Acredito que não foi intencional poderia ter passado despercebido, visando performance/velocidade

**Comment by Doonine** [comment]
Entendi.
É ruim alterar o código por conta pois perdemos a possibilidade de atualizações automáticas.
Também corre o risco de ter uma razão por trás dessas linhas.

Acho que o ideal seria a correção oficial.

Mas obrigado pela dica de solução temporária até a chegada da atualização.

**Comment by lrochawl** [comment]
Tenho um problema parecido com a pesquisa de produtos onde são localizados apenas os itens da pagina atual e ajuste de resultados por pagina não funciona

**Comment by jonathasnp** [comment]
Exemplo  tenho 3 páginas de produtos, e o item que eu quero  pesquisar
estar na página  3 , quando  eu vou procurar o  produto  tenho que fazer 3
pesquisa na página 1 na página 2 na página  3 , uma única  pesquisa  não
abrange as 3 páginas  existente

Em seg, 29 de nov de 2021 19:42, Doonine ***@***.***>
escreveu:

**Comment by lrochawl** [comment]
Correto, apenas para deixar claro na pesquisa global marcada em *amarelo* é possível pesquisar um item que consta em qualquer pagina porém na pesquisa marcada em *laranja* apenas na pagina atual 
![Captura de tela 2021-12-14 144518](https://user-images.githubusercontent.com/49371821/146053669-e20ac98f-7723-4ec1-95b8-0c34e4d07ec0.png)

**Comment by jonathasnp** [comment]
Cara desculpe minha ignorância , eu nunca tinha testado assim ,
![image](https://user-images.githubusercontent.com/81585844/146086857-558eae01-b824-42dd-bf36-2a1e85565e3f.png)
 agora deu certo
![image](https://user-images.githubusercontent.com/81585844/146087025-c9cfb337-4330-4cc1-9363-0997e4e4d4bc.png)

**Comment by jonathasnp** [comment]
obrigado pela atenção
