### ISSUE TITLE
Proble installing composer libraries

### ISSUE THREAD

**Issue by KaiserSKL** [RamonSilva20/mapos#1563]
![Captura de pantalla de 2021-11-29 17-12-23](https://user-images.githubusercontent.com/47432760/143957712-45ce3da7-af95-49fd-adf3-2103fb9f3542.png)
I need some help i cant pass instaling from here

I'm on ubuntu server 21.4

php 7.4

**Comment by Pr3d4dor** [comment]
@KaiserSKL Hello, I think you are running composer install in the wrong way.

You need to run "composer install" in the terminal.

After that, you need to check if the "vendor" folder is inside the application folder. This means that the composer successfully installed all the dependencies of the project.

**Comment by KaiserSKL** [comment]
thnx a lot i had some issuel so I reconfig the lock dependencies and all went smoothly
