### ISSUE TITLE
Relatorio OS

### ISSUE THREAD

**Issue by gouveia1979** [RamonSilva20/mapos#1565]
Boa noite, não consigo gerar relatorio de OS, apareceo seguinte erro:

Mpdf \ MpdfImageException (E_ERROR)
Could not find image file (C:/wamp64/www/mapos/assets/uploads/c970af4831b03c2796f57fbc6ef1c14b.jpg)

Alguem poderia ajudar?

**Comment by Pr3d4dor** [comment]
@gouveia1979 Vá em configurações >> emitente e envie o logo de sua empresa novamente. Após isso creio que voltará a funcionar.
