### ISSUE TITLE
Erro ao Salvar Cobrança

### ISSUE THREAD

**Issue by dgcursino** [RamonSilva20/mapos#1567]
Cobrança é gerada no mercado pago. Mas não salva cobrança na plataforma.
![image](https://user-images.githubusercontent.com/54563738/144755053-1ab9b412-dc03-4b8a-be90-abc784a3dced.png)

**Comment by Pr3d4dor** [comment]
@dgcursino Se conseguir pegar os logs de erro em application/logs acho que fica mais fácil para podermos lhe ajudar.

**Comment by dgcursino** [comment]
Eu vi aqui. Resolvi. Obrigado


Em seg., 6 de dez. de 2021 14:16, Gianluca Bine ***@***.***>
escreveu:

**Comment by dgcursino** [comment]
Toda vez que efetuo atualização do bd ocorre isso.

Em seg., 6 de dez. de 2021 14:19, Douglas Cursino Infocentric <
***@***.***> escreveu:

**Comment by dgcursino** [comment]
O erro que desencadeia a formatação da página editar os
Tem que retirar o botão faturar os editar os.
Pois não tem como estar um os que já está sendo editada.

Isso faz com que a página funcione no celular.

Em seg., 6 de dez. de 2021 23:41, Gianluca Bine ***@***.***>
escreveu:
