### ISSUE TITLE
Layout de impressão

### ISSUE THREAD

**Issue by leosass** [RamonSilva20/mapos#1576]
Olá pessoal. Muito bom o sistema!

Como conseguimos alterar o layout de impressão da OS? Deixar mais bonito?

Ex já viram do Operand?

**Comment by Pr3d4dor** [comment]
@leosass Vocẽ pode editar o arquivo imprimir_os.php e deixar à seu gosto.

**Comment by AcessoHAG** [comment]
Estou tentando colocar a imagem de anexo dentro do imprimir_os.php, mas não retorna a imagem.
Alguém pode me ajudar?

**Comment by Pr3d4dor** [comment]
@AcessoHAG Como você está tentando colocar essa imagem?
