### ISSUE TITLE
Impossivel Usar fora do Brasil

### ISSUE THREAD

**Issue by kalukramer** [RamonSilva20/mapos#158]
Boas.
Nestas novas versões é impossivel usar fora do Brasil, o CEP e o Código Postal tem formatos diferentes, por isso ele dá sempre erro no registo, alem do mais o formato do telefone e do "documento" também é deferente do NIF...
ainda uso a primeira versão devido as prametrizações restritivas.
**Existe algum modo de mudar isto no PHP?**

**Comment by allanalcantara** [comment]
manda o erro que da no registro. voce não consegue cadastrar, estranho pois é apenas um text

`<input id="cep" type="text" name="cep" value="<?php echo set_value('cep'); ?>"  />` 

voce pode corrigir os formatos pelo bd, caso seja menor, ou maior. ja com (/) voce pode colocar uma mascara para resolver nas visualizações.

**Comment by kalukramer** [comment]
É devido ao formato e numero de carateres, depois tem os parênteses que em
pt nao se usa. Mesmo no codigo fiscal, ca tem 9 algarismos sem hifen.

A sexta, 20/07/2018, 18:09, allanalcantara <notifications@github.com>
escreveu:

**Comment by allanalcantara** [comment]
entendi, o cep no bd esta em varchar, então parcialmente ele deve aceitar hifen, ou qualquer caractere, se não me engano o caractere no sistema tbm.

me manda o que aparece no seu pra podermos corrigir, eu lhe ajudo.
