### ISSUE TITLE
Financeiro: Filtro Por Forma de Pagamento

### ISSUE THREAD

**Issue by Acaruma** [RamonSilva20/mapos#1580]
Seria possível adicionar um filtro para método de pagamento?
Será super útil para conferir o tanto que entrou no caixa em espécie e demais meios, poderia dia, semana, ou mês.

Senti a falta somente desse item, mas o sistema é incrível.

Gerar um relatorio somente com esse filtro também seria interessante.

**Comment by Acaruma** [comment]
Apenas para deixar claro pois acho ficou vago.

Em financeiro>Lançamentos
Ao pesquisar onde há os filtros, poderia haver um com a forma de pagamento utilizada nas vendas de produtos.

Da mesmo forma ao gerar o relatorio de vendas.

**Comment by Pr3d4dor** [comment]
@Acaruma Iremos adicionar na lista de sugestões.
