### ISSUE TITLE
Atualizar contatos e ordens de serviço

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#1587]
Boa tarde meus amigos. 
Estava utilizando o mapos bem antigo, uma versão que ainda não estava disponível a atualização automática.
Meu sócio deve ter apertado no botão de atualizar o mapos e deu alguma nhaca. 
Resolvi instalar a versão mais nova no meu servidor de hospedagem. 
O que estou precisando de ajuda é em trazer apenas os clientes e as OS que estão no sistema antigo. 
Já tentei o seguinte: 
Baixei o arquivo do banco de dados antigo e do novo, diretamente pelo myadmin.
Com os dois arquivos (bancoantigo.sql e banconovo.sql), coloquei um ao lado do outro e tentei copiar de dentro da tabela clientes e os. 
Por exemplo. 
Peguei o início do código do antigo.sql: INSERT INTO `clientes` (`idClientes`, `nomeCliente`, `sexo`, `pessoa_fisica`, `documento`, `telefone`, `celular`, `email`, `dataCadastro`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `cep`, `contato`, `complemento`, `fornecedor`) VALUES

E acrescentei no novo.sql.
Mas deu erro. 
Vocês me dariam uma luz de como eu poderia trazer apenas os clientes e as OS's?
Agradeço a ajuda de quem puder responder! 
Oxalá abençoe!

**Comment by jsfachini** [comment]
você já utilizou o sistema novo tem dados no banco? porque importar só as OS e Clientes? não é mais fácil criar um banco limpo e depois só importar o teu bkp do sistema antigo para esse banco novo ?

**Comment by guskid** [comment]
> 

Pensei em fazer isso, não cheguei a tentar importar o bkp do antigo para o novo pq acredito que existam campos novos e que pode dar algum erro. 
Vou tentar fazer este teste e retorno

**Comment by Pr3d4dor** [comment]
@guskid O mais fácil é vc fazer um bkp do banco antigo e executar todos os sql em ordem que ficam na pasta de updates.

**Comment by guskid** [comment]
> @guskid O mais fácil é vc fazer um bkp do banco antigo e executar todos os sql em ordem que ficam na pasta de updates.

Tentarei fazer aqui, mas sou meio burro pra lidar no sql

**Comment by guskid** [comment]
> @guskid O mais fácil é vc fazer um bkp do banco antigo e executar todos os sql em ordem que ficam na pasta de updates.

Rapaz, não consegui fiz cagada... 
Meu sistema antigo não consigo acessar, sem querer apertei em atualizar o mapos no sistema e agora aparece uma mensagem dizendo "Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente."
Caracas consegue me ajudar?

**Comment by Pr3d4dor** [comment]
@guskid O seu sistema antigo usava qual versão?

Você pode baixar o mapos da versão que usava e apontar ele para o banco que você já usava.

**Comment by guskid** [comment]
> @guskid O seu sistema antigo usava qual versão?
> 
> Você pode baixar o mapos da versão que usava e apontar ele para o banco que você já usava.

Pior que apertei pra atualizar o mapos e não sei qual era a versão que eu estava usando. 
Tentei verificar nos arquivos mas não encontrei. Pelo banco tem como saber qual é a versão que era?
