### ISSUE TITLE
Listar apenas o lucro das vendas

### ISSUE THREAD

**Issue by Acaruma** [RamonSilva20/mapos#1588]
Bom dia pessoal, e de já feliz natal e ano novo :)
Se alguem puder meda um help serei eternamente grato s2
Em relação ao produtos.
Tem algum jeito fácil de implementar agora no relatório de "financeiro" ou no "vendas", ao inves de mostrar a soma de todo o faturamento, mostrar a soma do lucro da venda dos produtos?
Por exemplo atualmente se vendemos 280R$ de produto, la mostra os 280R$, mas não mostra o lucro de cada.
Se um produto custo para a empresa 150R$ e eu vendi por 280R$, gostaria que mostrasse somente os 130R$ no relatório que é o lucro bruto.
Sendo assim fizesse essa soma do lucro de todos os produtos vendidos.

Muito Obrigado por ao menos ler isso :)

**Comment by jsfachini** [comment]
pelo que sei essa parte é do financeiro e não dos relatórios, no menu **financeiro>lançamentos** tu coloca os custos de produtos e quando faz a venda ou fatura a OS é lançado nesse menu, assim você tem a noção de quanto lucrou no dia, mês, ano...

**Comment by Acaruma** [comment]
> pelo que sei essa parte é do financeiro e não dos relatórios, no menu **financeiro>lançamentos** tu coloca os custos de produtos e quando faz a venda ou fatura a OS é lançado nesse menu, assim você tem a noção de quanto lucrou no dia, mês, ano...

Claramente você não entendeu.

**Comment by visaotec** [comment]
Fiz essa alteração que aparece no relatório o lucro das vendas, no meu caso eu tenho funcionários daí aparece a comissão também separados

**Comment by Acaruma** [comment]
> Fiz essa alteração que aparece no relatório o lucro das vendas, no meu caso eu tenho funcionários daí aparece a comissão também separados

Você pode me ajudar ou upar seus arquivos para que eu utilize ?
Isso seria perfeito pois tenho funcionários também e listar a comissão seria top de mais
