### ISSUE TITLE
Alteração na unidade de medida m²

### ISSUE THREAD

**Issue by ameize** [RamonSilva20/mapos#1591]
Quando cadastramos um produto ele pede o valor da compra, se compramos o m² nós sabemos o valor do m² porem alguns produtos são vendidos fracionados, e isso acaba alterando o resultado financeiro.

Sugiro que continuem pedindo o valor de custo do m² e o valor de venda, mas na hora de vender o produto por m² tenha o campo "ALTURA" E "LARGURA" assim quando for preenchido o sistema deve fazer a multiplicação simples Altura x Largura x Valor de venda do m², assim no relatório financeiro você tem exato quantos m² foi vendido, quanto te custou e quando ganhou.

**O Código no Excel seria...**

```
LINHA A1 - ALTURA / LINHA A2 - LARGURA / LINHA A3 - VALOR DO M² / LINHA A4 - ESTOQUE ATUAL
Para calcular estoque utiliza =SOMA(A1-A3)
Para venda utiliza =SOMA(A1*A2*A3)
```
**O Código para o sistema mapos seria algo em torno disso...**
```

                                    <div class="span2">
                                        <label for="">Altura</label>
                                        <input type="text" placeholder="Altura" id="$numero1" name="numero1" class="span12 money" />
                                    </div>
                                    <div class="span2">
                                        <label for="">Largura</label>
                                        <input type="text" placeholder="Largura" id="$numero2" name="numero2" class="span12 money" />
                                    </div>
                                    <div class="span2">
                                        <label for="">Valor do m²</label>
                                        <input type="text" placeholder="Valor do m²" id="$numero3" name="numero3" class="span12 money" />
                                    </div>
                                    <div class="span2">
                                        <label for="">Quantidade</label>
                                        <input type="text" placeholder="Quantidade" id="$quantidade" name="quantidade" class="span12" />
                                    </div>
                                    <div class="span2">
                                        <label for="">Valor total</label>
                                        <?php echo $total = $numero1 * $numero2 * $numero3 * $quantidade; echo $total; ?>
                                    </div>
```
Ao adicionar o código que passei acima o visual torna-se idêntico ao print abaixo.
https://imgur.com/a/gr7kxCv

Porém, não consigo tornar usual a ponto do sistema calcular pra mim.

Sou entusiasta, não fiz cursos ou algo do tipo! o código EXCEL com certeza está correto, oq sugeri para o MAPOS pode contar um erro ou outro, mas acredito estar correto.

**Comment by Pr3d4dor** [comment]
@ameize Obrigado pela sugestão, mas essa alteração é bem específica para uso na sua empresa. Para outros tipos de empregas talvez não faria sentido.

**Comment by AcessoHAG** [comment]
@ameize fui no phpmyadim e mudei o tipo de valor de INT 11 para DECIMAL 11,3 assim o valor fica com 3 casas decimais e você pode calcular a area antes de inserir na quantidade.

https://imgur.com/rRDLtFy
https://imgur.com/4jRZgQ6
https://imgur.com/B4anDNo

**Comment by guskid** [comment]
> @ameize fui no phpmyadim e mudei o tipo de valor de INT 11 para DECIMAL 11,3 assim o valor fica com 3 casas decimais e você pode calcular a area antes de inserir na quantidade.
> 
> https://imgur.com/rRDLtFy https://imgur.com/4jRZgQ6 https://imgur.com/B4anDNo

Legal cara... Por mais que a issue não tenha sido minha curti demais, tb tenho uma gráfica! 
Deus abençoe!

**Comment by guskid** [comment]
> @ameize fui no phpmyadim e mudei o tipo de valor de INT 11 para DECIMAL 11,3 assim o valor fica com 3 casas decimais e você pode calcular a area antes de inserir na quantidade.
> 
> https://imgur.com/rRDLtFy https://imgur.com/4jRZgQ6 https://imgur.com/B4anDNo

Acabei de ver, única coisa ruim que na quantidade de outros pedidos agora aparece por exemplo, para 20 unidades, 20.000.

**Comment by ameize** [comment]
@guskid bacana! vou testar e te aviso, vou procurar solução para o erro da quantidade nos outros pedidos.
