### ISSUE TITLE
Colocar imagem de anexo dentro do imprimir_os.php?

### ISSUE THREAD

**Issue by AcessoHAG** [RamonSilva20/mapos#1593]
Estou tentando colocar a imagem de anexo dentro do imprimir_os.php, mas não retorna a imagem.
Alguém pode me ajudar?

**Comment by Pr3d4dor** [comment]
@AcessoHAG Como você está tentando colocar essa imagem?

**Comment by AcessoHAG** [comment]
> @AcessoHAG Como você está tentando colocar essa imagem?

Tentei copiar o codigo do anexo que aparece no visualizar_os e colocar no imprimir_os, mas a imagem nao aparece.

**Comment by roviglio** [comment]
Uma única imagem?
Eu costumo clicar na imagem que aparece em visualizar anexo com o botão do lado direito do mouse  e  copiar o link.
Com o link na área de transferência do windows eu clico em um das caixas  da os e clico em imagem e colo o link pronto.
Seria legal ter um botão com a opção de copiar link.

**Comment by AcessoHAG** [comment]
@roviglio Estou tentando fazer  aparecer a mesma imagem da miniatura do anexo que fica em visualizar_os aparecer no imprimir_os, mas ela não aparece, pois tem que imprimir com a imagem do anexo no A4

**Comment by roviglio** [comment]
Entendo.
Seria ligal, eu também gostaria disto no MAPOS.
No momento eu faço isso manualmente, faço um print de tela das minuaturas que quero que apareça na OS impressa e salvo e edito arquivo, depois anexo e colo o link da foto do anexo .
E chato de fazer , é um quebra galho. fica assim

![teste](https://user-images.githubusercontent.com/84595434/148080885-c4e3d45f-7cf4-456c-baf4-e7ed8507bb31.jpg)
