### ISSUE TITLE
Informações exclusivas na área Ordens de Serviço

### ISSUE THREAD

**Issue by almron** [RamonSilva20/mapos#1598]
Olá,

Dentro de Ordens de Serviços, temos "Descrição Produto/Serviço", "Defeito", "Observações" e "Laudo Técnico"
É possível ter uma área exclusiva para a Assistência Técnica onde as informações não são mostradas na área do cliente?

Até mais

**Comment by AcessoHAG** [comment]
@almron , é só alterar o application/views/conecte/visualizar_os.php dentro dele vai ter as informações da os que aparecem pro cliente ai você altera da forma que quiser.

**Comment by guskid** [comment]
> @almron , é só alterar o application/views/conecte/visualizar_os.php dentro dele vai ter as informações da os que aparecem pro cliente ai você altera da forma que quiser.

Amigo, estas alterações manuais se perdem ao atualizar o MAPOS em uma atualização futura?

**Comment by roviglio** [comment]
Sim, as atualizações do MAPOS não tem nossas personalizações.
Eu tenho o controle do que que mudei, conde fica os arquivos alterados etc..
Acho que vale a pena refazer as minhas  alterações depois de  atualizar o MAPOS para as versões novas.
Assim fico com o meu MAPOS atualizado e com minhas personalizações.
Mas isso é minha opnião, para mim até o momento isto foi facil.

**Comment by AcessoHAG** [comment]
Antes de fazer atualização faço backup da pasta views completa, pois ai o que mudar eu vejo só as modificações que já fiz e coloco de volta no codigo.
