### ISSUE TITLE
problema ao adicionar servico mapos

### ISSUE THREAD

**Issue by turbonetlink** [RamonSilva20/mapos#16]
Boa noite desculpe o incomodo mais o sitema esta dando problema ao tentar adicionar servicos na ordem de servico 

segue o anexo
![erro ao adicionar servico](https://cloud.githubusercontent.com/assets/12984495/24181557/67a2e66e-0e9a-11e7-9808-814acb95ba15.jpg)
![1tela](https://cloud.githubusercontent.com/assets/12984495/24181792/2529da5c-0e9c-11e7-93f4-2a5691ea089d.jpg)
![Uploading 1TELA.jpg…]()
![Uploading 2 TELA.jpg…]()
![Uploading erro ao adicionar servico.jpg…]()

**Comment by turbonetlink** [comment]
![1tela](https://cloud.githubusercontent.com/assets/12984495/24181819/5536b684-0e9c-11e7-809b-bdbcd843cfd4.jpg)
![2 tela](https://cloud.githubusercontent.com/assets/12984495/24181821/5538712c-0e9c-11e7-9cc9-b33679cac84a.jpg)
![erro ao adicionar servico](https://cloud.githubusercontent.com/assets/12984495/24181820/55383d7e-0e9c-11e7-9d4e-660c06f91774.jpg)

**Comment by RamonSilva20** [comment]
Bom dia. Você tem que utilizar o autocomplete do sistema (digitar para pesquisar um serviço ou produto cadastrado). Vou colocar uma validação para o sistema não inserir se não tiver sido feita a pesquisa.

**Comment by michelfritsch** [comment]
Tive o mesmo problema, os produtos cadastrados não aparecem no autocomplete, este problema não ocorre em uma versão anterior. Já tentei com versões de php diferentes (5.4 e 5.6) mas não resolveu.

**Comment by willsantos07** [comment]
Única solução que encontrei até o momento foi copiar a pasta js dentro das asstes  para a raiz junto ao Index.php

**Comment by RamonSilva20** [comment]
Problema solucionado, dois links estavam apontando para um local incorreto.
