### ISSUE TITLE
Sugestão - Inserir forma de pagamento parcelado para faturar OS

### ISSUE THREAD

**Issue by AcessoHAG** [RamonSilva20/mapos#1606]
Exemplo: Faturar OS em R$800,00 Cliente pagar R$200,00 e já gerar nova receita em pendentes do valor restante da OS.

**Comment by visaotec** [comment]
Eu fiz essa alteração em faturar  na versão que uso, ficou bem legal

**Comment by jucenir20** [comment]
você poderia compartilha seu código com nós?
