### ISSUE TITLE
Erro Modulo de pagamento Mercado Pago, falha no codigo!

### ISSUE THREAD

**Issue by AcessoHAG** [RamonSilva20/mapos#1610]
Erro para CANCELAR,ATUALIZAR, ou qualquer outra modificação no boleto.

https://imgur.com/KUQwYAj

**Comment by willph** [comment]
Olá, esse bug é antigo. 

O problema é que em modo sandbox funciona tranquilo, mas quando passa para o modo produção não funciona essa parte que citou.

Irei falar com o pessoal, para se não conseguir resolver esse bug.(caso o bug venha da API)
Remover ele de forma temporária ou definitiva.

**Comment by microreis** [comment]
Esse erro é da api, o modo produção estão a todo momento passando por atualização e esta causando conflitos, tive problema e outras aplicações que usa o mercado pago. O problema que o mercado pago não comunica nada.
