### ISSUE TITLE
Erro System Composer

### ISSUE THREAD

**Issue by lucassilvarp** [RamonSilva20/mapos#1611]
Pessoal fiz a instalação do mapos 2021 do repositório em um provedor de hospedagem que utilizo e que pelo qual a grande parte de hoje não entrega o SSH  no CPANEL para instalar o Composer , sendo assim o meu provedor me migrou para o DirectAdmin , por ele via SSH  consegui instalar o Composer e validar o seu funcionamento  como existe um problema dele não montar a pasta SYSTEM  , e pela dica do pessoal peguei a pasta VENDOR ( de 2020) de um membro  e instalei na Application , após isso ao tentar carregar o MAPOS o mesmo fica em uma tela em branco sem ação nenhuma e sem chegar no login , alguém já passou por isso ou sabe o que pode ser feito ?

**Comment by Pr3d4dor** [comment]
@lucassilvarp O melhor a se fazer é vocẽ instalar o composer localmente, realizar a instação das dependencias localmente e apóis isso fazer o upload da pasta vendor via FTP.

**Comment by lucassilvarp** [comment]
Obrigado @Pr3d4dor  fiz exatamente isso e tudo certo , instalei o xampp e o Composer , depois que ele criou a Vendor subi para o provedor 
Só estranhei uma coisa em Configurações , ele não criou o menu de configuração de pagamento para configurar os Gateways de pagamento ( Mercado Pago , Gerencianet e Asaas) o último item lá é o Backup apenas
