### ISSUE TITLE
GAYTEWAY ASAAS

### ISSUE THREAD

**Issue by lucassilvarp** [RamonSilva20/mapos#1612]
Pessoal fiz a configuracao conforme, abaixo no payment_gateways.php conforme evidencia abaixo , porem ao tentar fazer qualquer transacional utilizando o ASAAS estou tendo o erro abaixo

![image](https://user-images.githubusercontent.com/97764862/149973767-6c8dcf5f-9a98-458d-8f70-226370e72a98.png)

Se eu vou em LINK o erro gerado é esse

![image](https://user-images.githubusercontent.com/97764862/149974173-f195f0f4-abf8-465d-b887-4ecf6080666c.png)

Alguem consegue me ajudar?

**Comment by Pr3d4dor** [comment]
@lucassilvarp Consegue olhar em "application/logs" e colar aqui os logs de erro?

Fica mais fácil para tentar te ajudar.

**Comment by lucassilvarp** [comment]
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-01-20 00:38:52 --> Query error: Unknown column 'asaas_id' in 'field list' - Invalid query: UPDATE `clientes` SET `asaas_id` = 'cus_000027916780'
WHERE `idClientes` = '1'

**Comment by Pr3d4dor** [comment]
@lucassilvarp está faltanto colunas no seu banco de dados, vai precisar atualizar.

**Comment by lucassilvarp** [comment]
@Pr3d4dor  eu atualizei o BD pela propria atualizador da pagina, e deu como atualizacao OK  tem algum outro metodo para atualizar ou verificar se os campos foram criados?

**Comment by Pr3d4dor** [comment]
na pasta updates tem os SQL de todas as atualizações.

**Comment by lucassilvarp** [comment]
Pela logica foi aplicado 

![image](https://user-images.githubusercontent.com/97764862/150411803-d63fbd95-67a9-4648-aceb-b97f6e6ea85e.png)

A instalacao é nova, nao foi feita atraves de atualizações pegamos a ultima versao do repositório (4.35.2) e o banco é zerado

**Comment by Pr3d4dor** [comment]
@lucassilvarp Tente encontrar o SQL que faz a adição dessa coluna e executar ele, talvez a atualização automática falhou

**Comment by lucassilvarp** [comment]
@Pr3d4dor  muito obrigado atualizei manualmente o php foi certo
