### ISSUE TITLE
Problema no composer

### ISSUE THREAD

**Issue by DevinderFTW** [RamonSilva20/mapos#1613]
Para novatos gostaria que fize-se um tutorial se possivel do composer, estou tendo dificuldades

**Comment by DevinderFTW** [comment]
C:\Users\HP>composer install --no-dev
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fzaninotto/faker ^1.9 -> satisfiable by fzaninotto/faker[v1.9.0, v1.9.1, v1.9.2].
    - fzaninotto/faker[v1.9.0, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires piggly/php-pix ^1.2.5 -> satisfiable by piggly/php-pix[1.2.5, 1.2.6, 1.2.7, 1.2.8].
    - piggly/php-pix[1.2.5, ..., 1.2.8] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires codephix/asaas-sdk dev-master -> satisfiable by codephix/asaas-sdk[dev-master].
    - codephix/asaas-sdk dev-master requires php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by DevinderFTW** [comment]
Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

**Comment by Pr3d4dor** [comment]
@DevinderFTW Esse vídeo pode te ajudar: https://www.youtube.com/watch?v=8joUGLpzUtE

**Comment by DevinderFTW** [comment]
![image](https://user-images.githubusercontent.com/16402587/151025555-8e5f8e82-27f7-4a2c-a6b7-bc90e6e733cc.png)

**Comment by DevinderFTW** [comment]
como resolver este erro de layout?

**Comment by Pr3d4dor** [comment]
@DevinderFTW Nunca vi esse acontecer, testou com outros navegadores? ou reinstalar o mapos?

**Comment by DevinderFTW** [comment]
@Pr3d4dor já fiz este procedimento de reinstalação e funcionou muito grato pela ajuda <3
