### ISSUE TITLE
Bug ao atualizar pix

### ISSUE THREAD

**Issue by juniorgtxx** [RamonSilva20/mapos#1618]
Olá,ao tentar atualizar a chave pix la em financeiro ele me retorna com uma mensagem, "selecione uma das opções" ja rodei composer update e não resolveu ele sempre retorna o mesmo,estou usando xampp no windows server 2019.

**Comment by willph** [comment]
> Olá,ao tentar atualizar a chave pix la em financeiro ele me retorna com uma mensagem, "selecione uma das opções" ja rodei composer update e não resolveu ele sempre retorna o mesmo,estou usando xampp no windows server 2019.

Qual versão do seu Mapos?
Ja tinha chave cadastrada?

**Comment by juniorgtxx** [comment]
Bom dia está no ultimo release,sim ja tinha eu tentei remover e não vai.

**Comment by willph** [comment]
> Bom dia está no ultimo release,sim ja tinha eu tentei remover e não vai.

Então não está conseguindo excluir para poder cadastrar outra?

**Comment by juniorgtxx** [comment]
correto,quando eu mando salvar ele não salva.

**Comment by willph** [comment]
Assim que dê vou fazer uma instalação do zero e testar aqui ok?

**Comment by juniorgtxx** [comment]
ja fiz isso pois tive que reinstalar ele pois deu problema na ao atualizar.

**Comment by willph** [comment]
> ja fiz isso pois tive que reinstalar ele pois deu problema na ao atualizar.

Eu disse que irei testar na minha máquina 😁

**Comment by willph** [comment]
Testei aqui, e está funcionando tranquilo. 

Usando o Xampp, Windows 10. 
Php na versão 7.4.25

**Comment by juniorgtxx** [comment]
estranho,pois aqui não vai ele dá essa mensagem que colei em cima.

**Comment by willph** [comment]
> estranho,pois aqui não vai ele dá essa mensagem que colei em cima.

Atualizou o banco de dados?
Usou o composer update?

**Comment by juniorgtxx** [comment]
resolvido atualizei o banco de dados e alterou obrigado Will.

**Comment by willph** [comment]
> resolvido atualizei o banco de dados e alterou obrigado Will.

Tranquilo. 
De nada
