### ISSUE TITLE
Imprimir anexo junto da A4

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#1626]
Boa tarde. 
Gostaria de uma ajuda. 
Estava precisando acrescentar o Anexo no final da página quando faz a impressão da OS em A4. 
Tentei pegar os mesmos códigos do editar e visualizar os, mas não traz a imagem. 
Alguém poderia me dar uma ajuda ou indicar como daria para imprimir a imagem do anexo junto?
Valeu, grande abraço!

**Comment by LucasPolli** [comment]
faz um tempo que to tentando a mesma coisa.. sem sucesso ainda..

**Comment by guskid** [comment]
Fui no visualizar OS e retirei todos os códigos da página até restar somente a imagem do anexo.
Ficando:
`<div class="widget-content" id="printOs">
    

        <div style="margin-top: 0; padding-top: 0">
            <?php if ($anexos != null) { ?>
                <table class="table table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th>Anexo</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($anexos as $a) {
                        if ($a->thumb == null) {
                            $thumb = base_url() . 'assets/img/icon-file.png';
                            $link = base_url() . 'assets/img/icon-file.png';
                        } else {
                            $thumb = $a->url . '/thumbs/' . $a->thumb;
                            $link = $a->url . '/' . $a->anexo;
                        }
                        echo '<tr>';
                        echo '<td><a style="min-height: 150px;" href="#modal-anexo" imagem="' . $a->idAnexos . '" link="' . $link . '" role="button" class="btn anexo span12" data-toggle="modal"><img src="' . $thumb . '" alt=""></a></td>';
                        echo '</tr>';
                    } ?>
                    </tbody>
                </table>
            <?php } ?>

            
        </div>
    </div>
</div>
       



<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '.anexo', function (event) {
            event.preventDefault();
            var link = $(this).attr('link');
            var id = $(this).attr('imagem');
            var url = '<?php echo base_url(); ?>index.php/os/excluirAnexo/';
            $("#div-visualizar-anexo").html('<img src="' + link + '" alt="">');
            $("#excluir-anexo").attr('link', url + id);

            $("#download").attr('href', "<?php echo base_url(); ?>index.php/os/downloadanexo/" + id);

        });

        $(document).on('click', '#excluir-anexo', function (event) {
            event.preventDefault();

            var link = $(this).attr('link');
            var idOS = "<?php echo $result->idOs; ?>"

            $('#modal-anexo').modal('hide');
            $("#divAnexos").html("<div class='progress progress-info progress-striped active'><div class='bar' style='width: 100%'></div></div>");

            $.ajax({
                type: "POST",
                url: link,
                dataType: 'json',
                data: "idOs=" + idOS,
                success: function (data) {
                    if (data.result == true) {
                        $("#divAnexos").load("<?php echo current_url(); ?> #divAnexos");
                    } else {
                        Swal.fire({
                            type: "error",
                            title: "Atenção",
                            text: data.mensagem
                        });
                    }
                }
            });
        });
    });
</script>`
Mas o engraçado que esse código aí deve puxar algo da URL visualizar. 
Deve ser algo bem bestinha kkk 
Mas não consegui entender.

**Comment by guskid** [comment]
Foi no visualizar OS e editei todo o código restando somente isso:


<div class="widget-content" id="printOs">
    

        <div style="margin-top: 0; padding-top: 0">
            <?php if ($anexos != null) { ?>
                <table class="table table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th>Anexo</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($anexos as $a) {
                        if ($a->thumb == null) {
                            $thumb = base_url() . 'assets/img/icon-file.png';
                            $link = base_url() . 'assets/img/icon-file.png';
                        } else {
                            $thumb = $a->url . '/thumbs/' . $a->thumb;
                            $link = $a->url . '/' . $a->anexo;
                        }
                        echo '<tr>';
                        echo '<td><a style="min-height: 150px;" href="#modal-anexo" imagem="' . $a->idAnexos . '" link="' . $link . '" role="button" class="btn anexo span12" data-toggle="modal"><img src="' . $thumb . '" alt=""></a></td>';
                        echo '</tr>';
                    } ?>
                    </tbody>
                </table>
            <?php } ?>

            
        </div>
    </div>
</div>
       



<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '.anexo', function (event) {
            event.preventDefault();
            var link = $(this).attr('link');
            var id = $(this).attr('imagem');
            var url = '<?php echo base_url(); ?>index.php/os/excluirAnexo/';
            $("#div-visualizar-anexo").html('<img src="' + link + '" alt="">');
            $("#excluir-anexo").attr('link', url + id);

            $("#download").attr('href', "<?php echo base_url(); ?>index.php/os/downloadanexo/" + id);

        });

        $(document).on('click', '#excluir-anexo', function (event) {
            event.preventDefault();

            var link = $(this).attr('link');
            var idOS = "<?php echo $result->idOs; ?>"

            $('#modal-anexo').modal('hide');
            $("#divAnexos").html("<div class='progress progress-info progress-striped active'><div class='bar' style='width: 100%'></div></div>");

            $.ajax({
                type: "POST",
                url: link,
                dataType: 'json',
                data: "idOs=" + idOS,
                success: function (data) {
                    if (data.result == true) {
                        $("#divAnexos").load("<?php echo current_url(); ?> #divAnexos");
                    } else {
                        Swal.fire({
                            type: "error",
                            title: "Atenção",
                            text: data.mensagem
                        });
                    }
                }
            });
        });
    });
</script>

Engraçado que o mesmo código não funciona no "imprimirOs.php". Deve puxar algo da URL.

**Comment by guskid** [comment]
Fui no Visualizar OS e retirei todos os códigos até restar somente a imagem do anexo. 
O engraçado é que com o código que restou, não funcionou inserir no imprimirOs.
Deve puxar algo da URL, mas o que? kkk

**Comment by roviglio** [comment]
Tenho usado (anexando) as fotos do anexo (só serve para fotos) a url que tem a imagem , ai em uma das abas da OS coloco a imagem , pois lá você pode usar html e tem até o campo para colocar imagem.
Pelo que vi é assim, todos os anexos tem um link na tabela anexo que é achada pelo numero da Os acho que é idOS o campo da tabela.
Para colocar no relatório automaticamente tem que separar os anexo de uma os, pegar um por um e acrescentar  a url e o nome do arquivo , é necessário fazer um tratamento para exibir um icone quando o anexo não for foto.
Acho que por ser relatório o ideal seria usar os thumbs,.
Se alguém descobrir como criar algo como tabelas com os thumbs  no codegnitor por favor me explica que isso eu não sei.
