### ISSUE TITLE
Remover os logs ou desativar..

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#1627]
![image](https://user-images.githubusercontent.com/61605704/152461920-e09b491e-6df6-49b8-ad9b-ed58e6483974.png)

como faço para desativar os logs?

**Comment by willph** [comment]
> ![image](https://user-images.githubusercontent.com/61605704/152461920-e09b491e-6df6-49b8-ad9b-ed58e6483974.png)
> 
> como faço para desativar os logs?

Acredito que o que gostaria de fazer, teria que editar arquivo por arquivo, e remover do controller a geração do arquivo log
