### ISSUE TITLE
Paginação de Produtos 

### ISSUE THREAD

**Issue by Sergiosouza18** [RamonSilva20/mapos#1628]
Ao cadastrar vários produtos, quando clicamos pesquisar seja por Descrição, código de barra ou código do produto, se o produto estiver na ultima página a informação não é trazida. 

Outro bug percebido, quando modificamos na paginação de 10 para 100 também não é mostrado.

Caso alguém consiga agradeço muito

**Comment by Sergiosouza18** [comment]
Algum Contato do Ramon ?

**Comment by willph** [comment]
> Algum Contato do Ramon ?

Saiu a versão nova Mapos, baixa e testa para vê se resolveu
