### ISSUE TITLE
Nenhuma ligação pôde ser feita porque o computador de destino as recusou ativamente.

### ISSUE THREAD

**Issue by luisgouveia3112** [RamonSilva20/mapos#1629]
** Descreva o bug **
Após seguir todos os passos acontece que me aparece o seguinte erro: Nenhuma ligação pôde ser feita porque o computador de destino as recusou ativamente.
Ainda no painel de criação.

![image](https://user-images.githubusercontent.com/99078274/152641850-052b2237-f821-41e1-910d-2948223f9708.png)

**Reproduzir**
Etapas para reproduzir o comportamento:
No painel de finalização de criação de "conta":
![image](https://user-images.githubusercontent.com/99078274/152641864-a7263efb-bcfd-48b1-896d-bf69fed6c965.png)

**Comportamento esperado**
Que funcionasse

** Capturas de tela **
![image](https://user-images.githubusercontent.com/99078274/152641868-afb04f36-ca53-4e71-b194-368ac6c3a965.png)
![image](https://user-images.githubusercontent.com/99078274/152641873-3b175204-a916-4128-b63b-8d0a39bc776a.png)
![image](https://user-images.githubusercontent.com/99078274/152641879-a7703b59-961e-4d18-ae68-9b5e6302fe45.png)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10 PRO 64Bits
 - Navegador: Google Chrome

** Contexto adicional **
Conseguimos alterar os reais brasileiros para outras moedas? tipo euro!

**Comment by willph** [comment]
Já tentou fazer o login com o BD usando apenas root sem @localhost?

**Comment by luisgouveia3112** [comment]
Já, o erro persiste 

Cumprimentos 
Luís Gouveia

**Comment by willph** [comment]
> Já, o erro persiste Cumprimentos Luís Gouveia
> […](#)
> No dia 05/02/2022, às 12:33, Wilmerson ***@***.***> escreveu: ﻿ Já tentou fazer o login com o BD usando apenas root sem @localhost? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

Qual versão do Mapos?

**Comment by willph** [comment]
Tem senha no seu banco de dados?
