### ISSUE TITLE
como adicionar forma de pagamrento na última versão do mapos

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#1631]
gente, estou tentando configurar o mpapos para aceitar mercadopago ou gerencianet, mas, não encontrei nenhum botão para adicionar a integração
onde é o botão para adicionar a minha conta e as chaves de api?
e falta uma documentação mais clara.,
obrigado

**Comment by willph** [comment]
> gente, estou tentando configurar o mpapos para aceitar mercadopago ou gerencianet, mas, não encontrei nenhum botão para adicionar a integração onde é o botão para adicionar a minha conta e as chaves de api? e falta uma documentação mais clara., obrigado

Entre esse dois use o Gerencianet, porque no MercadoPago está com um bug

Já colocou os dados da API no Mapos?

Você configura no arquivo `payment_gateways.php` que fica na pasta `application>config`

Gerencianet fica na linha 11 e 12.

**Comment by vinicioaraujo** [comment]
Oi, por favor, me esclareça: Ao colocar os dados da API em payment_gateways.php essa a função de pagamento já fica disponível? Pos, no sistema não temos a opção "Pagamento" dentro do menu "Configurações."

**Comment by willph** [comment]
> Oi, por favor, me esclareça: Ao colocar os dados da API em payment_gateways.php essa a função de pagamento já fica disponível? Pos, no sistema não temos a opção "Pagamento" dentro do menu "Configurações."

Opa, gostaria de saber se ainda precisa de ajuda?

**Comment by vinicioaraujo** [comment]
@willph, obrigado pelo retorno, mas ainda preciso de ajuda sim. Pra mim, não aparece abaixo do menu "Configurações" a opção "Pagamento", como faço para ativar este recurso?

**Comment by willph** [comment]
> @willph, obrigado pelo retorno, mas ainda preciso de ajuda sim. Pra mim, não aparece abaixo do menu "Configurações" a opção "Pagamento", como faço para ativar este recurso?

Tem cadastro no Gerencianet?

**Comment by vinicioaraujo** [comment]
Ainda não, vou precisar de ter um cadastro primeiro?

**Comment by willph** [comment]
> Ainda não, vou precisar de ter um cadastro primeiro?

Sim.
Ou na Gerencianet ou na Asaas
