### ISSUE TITLE
Resultado por página 

### ISSUE THREAD

**Issue by Sergiosouza18** [RamonSilva20/mapos#1632]
** Descreva o bug **
quando alteramos o valor do resultado por página não ocorre nada
**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by mmonzato** [comment]
Para funcionar vc precisa ir na tela de configurações, na aba geral e mudar o campo como pode ser visto na imagem abaixo.

![image](https://user-images.githubusercontent.com/55327526/153258720-50cbec0d-99f9-412e-8409-3cbb39c1e574.png)
