### ISSUE TITLE
Parcelamento de  pagamento

### ISSUE THREAD

**Issue by HSchneiderS** [RamonSilva20/mapos#1638]
Ola a todos!
teria como ter no sistema parcelamento de servicços ? ex: cliente solicitou serviço e o valor do mesmo seria dividido em 12x.
facilitaria bastante e ajudaria no bom desenvolvimento na qual segue o sistema
vlw. 👍 🥇

**Comment by Pr3d4dor** [comment]
@HSchneiderS Obrigado pela sugestão, essa funcionalidade já está na lista das que foram pedidas.
