### ISSUE TITLE
ERRO - Call to a member function result() on bool

### ISSUE THREAD

**Issue by Wallidantas** [RamonSilva20/mapos#1641]
não consigo visualizar a OS, assim que entro em serviços, vou visualizar qualquer OS da esse erro:
![Captura de tela 2022-02-11 233557](https://user-images.githubusercontent.com/48001221/153695204-bf1a83dd-8352-48c8-b848-523772879b81.png)

alguém poderia me ajudar?

**Comment by Pr3d4dor** [comment]
@Wallidantas Verifique se seu banco de dados está atualizado.
