### ISSUE TITLE
apresenta erro ao abrir uma nova ordem de serviço

### ISSUE THREAD

**Issue by Dtecheletronica** [RamonSilva20/mapos#1642]
![erro map-os](https://user-images.githubusercontent.com/98718961/153724298-f328b6ac-10e0-434a-bb41-d36ddfbd98b5.png)

**Comment by Pr3d4dor** [comment]
@Dtecheletronica Ao abrir qual tela esse erro ocorre?

**Comment by Dtecheletronica** [comment]
Pr3d4dor, só 
![mapos erro](https://user-images.githubusercontent.com/98718961/154094133-90e43d27-2691-4eb1-8df2-fda577b97b82.png)
na tela de "Ordens de Serviço",

**Comment by Dtecheletronica** [comment]
clicamos em Ordens de Serviço, apresenta o erro na imagem acima.
 nas outras abas, ele abre normalmente.
 somente nessa de Ordens de Serviços que dá o erro.

**Comment by willph** [comment]
O erro foi após atualiza o sistema?

**Comment by Dtecheletronica** [comment]
Willph, não chegamos atualizar o banco de dados, salvo engano só atualizamos o mapos.

**Comment by willph** [comment]
Infelizmente precisa atualizar banco de dados.

**Comment by willph** [comment]
Faz um teste por favor.
Baixa o código, faz uma instalação do zero. 
Só pra testar
Pra vê se acontece o erro. 

Porque aqui está normal.

**Comment by Dtecheletronica** [comment]
> Faz um teste por favor. Baixa o código, faz uma instalação do zero. Só pra testar Pra vê se acontece o erro.
> 
> Porque aqui está normal.

conseguimos identificar o erro, tivemos que apagar uma ordem de serviço pelo xampp, na raiz da OS, e voltou a funcionar, nao perdemos nada.

**Comment by willph** [comment]
> > Faz um teste por favor. Baixa o código, faz uma instalação do zero. Só pra testar Pra vê se acontece o erro.
> > Porque aqui está normal.
> 
> conseguimos identificar o erro, tivemos que apagar uma ordem de serviço pelo xampp, na raiz da OS, e voltou a funcionar, nao perdemos nada.

Estranho.
E qual foi o erro identificado?

**Comment by Dtecheletronica** [comment]
> > > Faz um teste por favor. Baixa o código, faz uma instalação do zero. Só pra testar Pra vê se acontece o erro. 
> > > Porque aqui está normal.
> > 
> > 
> > identificar o erro, que funcionou na ordem de serviço pelo xampp, e voltou a funcionar, não perdemos nada.
> 
> Estranho. E qual foi o erro identificado?

nao sabemos o certo. começamos a mudar a gestao e transpondo as OS de papel para o mapos, do ano de 2020 ate o presente momento, acreditamos que tenha um limitador.
