### ISSUE TITLE
Cron job - fila de envio de emails

### ISSUE THREAD

**Issue by luizrn** [RamonSilva20/mapos#1643]
Ola, tenho uma duvida, de formal alguma consigo fazer funcionar o cron job pra executar a fila de email, nao conheço bem o codeingter mas teria uma url para acessar e acionar a fila? tipo site.com.br/cron_emails.php

**Comment by luizrn** [comment]
Mudei de hospedagem, fui para a Hostgator e funcionou o cron de primeira, também eles tem por padrão já ativado o shell_exec(), que da de criar um arquivo .php com o comando shell para executar a fila (essa função ativa deixa muito vulnerável seu host porque pode executar comandos shell direto em arquivo .php). 

Outra possibilidade tbm para quem não ta conseguindo e a hospedagem não ativa o shell_exec(), é criar um arquivo .sh na raiz do projeto e nele por o código `php /[path]/mapos/index.php email/proccess` ai executa no cron esse arquivo, no cron precisa verifica com a hospedagem como faz com arquivos .sh 

Na hostgator meu cronjob ficou assim:
`/usr/local/bin/php /home2/[SEU USER CPANEL]/public_html/mapos/index.php email/process`

**Comment by tomnasc** [comment]
Cara, como que faz o envio de email funcionar, fiz todas as configurações, aparece na lista que oi enviado, mas o email não chega ao destinatário e não gera log de erro. O email só chega se o destinatário for uma conta de email criada na própria hospedagem, com o mesmo domínio ou outro.
