### ISSUE TITLE
Agendamento de horários

### ISSUE THREAD

**Issue by petersonbreno** [RamonSilva20/mapos#1644]
Bom dai, espero que estejam todos bem.

É possível adicionar que mostre o horário no calendário do dashboard?
Exemplo, quero agendar um atendimento de uma OS para o dia 15 Às 09:00, aparecer essa informação dentro do calendário no dia 15.

**Comment by Pr3d4dor** [comment]
@petersonbreno Atualmente não, porque no banco de dados só salva a data, só se for modificado para salvar o horário também na OS.

**Comment by Pr3d4dor** [comment]
@petersonbreno Sim porém temos várias outras funcionalidades na fila. O mapos antigo (atual) vai ser mantido, porém estamos refazendo o mapos usando outro framework (Laravel). Então o foco agora será apenas manter as coisas existentes e não adicionar novas coisas.
