### ISSUE TITLE
Gostaria que em Vendas Conseguisse adicionar o produto pelo Codigo de Barras

### ISSUE THREAD

**Issue by Igor-Montuani** [RamonSilva20/mapos#1647]
Implementei o sistema na minha empresa porém todos os produtos que adiciono no estoque possuem código de Barra, quando vou executar uma venda o sistema apenas me permite buscar pela descrição seria possível alterar a busca para buscar pelo código de barras pois tenho um leitor de código de barras  e geralmente minhas vendas possuem muito produtos

**Comment by willph** [comment]
Em vendas funciona a busca por código de barra. Mas digitando, não pelo leitor de código de barra.

**Comment by Igor-Montuani** [comment]
Assim muito obrigado pelo retorno e teria alguma maneira de eu estar implementando para funcionar com o codigo de barras ?

**Comment by Igor-Montuani** [comment]
Uma outra duvida teria a possibilidade de incluir o qrcode do PIX no na impressão do comprovante não fiscal

**Comment by willph** [comment]
> Uma outra duvida teria a possibilidade de incluir o qrcode do PIX no na impressão do comprovante não fiscal

Tem, poderia pegar o código que já existe em A4 e colocar no não fiscal
