### ISSUE TITLE
Gerador de etiqueta parou de funcionar

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1648]
Boa noite, estou com um problema no gerador de etiquetas, coloco o intervalo e ao clicar em gerar a tela some e não gera etiqueta, simplesmente parou do nada.

![gerador](https://user-images.githubusercontent.com/72340074/154588857-c22e2485-2fd9-4574-980e-92016cf6ca2d.png)

**Comment by willph** [comment]
Eu fiz o teste no demo online, e está pegando.

Qual erro que está apresentando, teria imagens desse erro?

**Comment by jsfachini** [comment]
> Eu fiz o teste no demo online, e está pegando.
> 
> Qual erro que está apresentando, teria imagens desse erro?

Ai que esta, não apresenta erro nenhum, quando clica em **Gerar** essa tela da etiqueta some, sem erros...

**Comment by willph** [comment]
> > Eu fiz o teste no demo online, e está pegando.
> > Qual erro que está apresentando, teria imagens desse erro?
> 
> Consegui resolver, voltei um bkp da pasta do mapos, resolveu, agora o que aconteceu nao tenho ideia... obrigado

Estamos por aqui na correria de atualização do layout. 
Aí pode ser que demore pra responder. 

Que bom que conseguiu resolver
