### ISSUE TITLE
Mapos 4.6 - 404 Page Not Found

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1651]
Bom dia a todos, de inicio quero parabenizar pelo novo visual do Mapos fichou show!!!
Bem fiz a instalação do novo mapos 4.36 porém depois de atualizar não é encontrada a pagina, sou leigo nesse quesito e gostaria da ajuda dos amigos.
![mapos erro](https://user-images.githubusercontent.com/71839236/155150999-c6e5cec4-2c62-418f-939c-69e65c748638.jpg)

**Comment by willph** [comment]
> Bom dia a todos, de inicio quero parabenizar pelo novo visual do Mapos fichou show!!! Bem fiz a instalação do novo mapos 4.6 porém depois de atualizar não é encontrada a pagina, sou leigo nesse quesito e gostaria da ajuda dos amigos. ![mapos erro](https://user-images.githubusercontent.com/71839236/155150999-c6e5cec4-2c62-418f-939c-69e65c748638.jpg)

4.6?

O Mapos vai na versão 4.36.

Como foi feito esse atualização?

**Comment by p-francelino** [comment]
Eu faço sempre como descreve na pagina, baixo o arquivo extraio coloco na pasta, depois executo o instalador.

**Comment by p-francelino** [comment]
Reinstalei agora e obtive a seguinte pagina.
![mapos erro_2](https://user-images.githubusercontent.com/71839236/155157291-c74663bd-4327-4c7d-aa51-394ec1ca5fa8.jpg)

**Comment by willph** [comment]
> Reinstalei agora e obtive a seguinte pagina. ![mapos erro_2](https://user-images.githubusercontent.com/71839236/155157291-c74663bd-4327-4c7d-aa51-394ec1ca5fa8.jpg)

Verifica a url que está no arquivo `config.php`. linha 42 `$config['base_url'] = 'enter_baseurl';`
Colocar url base do sistema ex: `http://localhost/mapos`

**Comment by p-francelino** [comment]
Pronto acabei de ve.
Comparei com o arquivo anterior:
$config['base_url'] = 'http://localhost/loja';

Atual estava:
$config['base_url'] = 'localhost/loja';

Depois de alterado ele encontrou.
deixa eu ve se vai logar numa boa.

**Comment by p-francelino** [comment]
Funcionou porém o layout está assim:
![layout_1](https://user-images.githubusercontent.com/71839236/155161459-d3121a51-a67c-4460-a41b-d2f3160551f9.jpg)
![layout_2](https://user-images.githubusercontent.com/71839236/155161482-d41a0c31-dd36-4da4-9535-9837b72d266c.jpg)

**Comment by willph** [comment]
Limpou o cache do navegador?

**Comment by willph** [comment]
Obrigado!

Atenciosamente, Equipe Mapos!
