### ISSUE TITLE
Erro ao gerar relatório de OS

### ISSUE THREAD

**Issue by itiossi** [RamonSilva20/mapos#1652]
**Descreva o bug**
Ao emitir relatório de OS apresenta o seguinte erro:

**Reproduzir**
Etapas para reproduzir o comportamento:
Na guia relatórios, selecionado o relatório de OS, indicado o cliente e data. Ao imprimir apresenta o erro seguinte.

**Comportamento esperado**
Que emitisse o relatório das os normalmente.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
![image](https://user-images.githubusercontent.com/98911819/155193086-10ab1645-8330-4a0a-8914-c38449d0d63a.png)

**Desktop (preencha as seguintes informações):**

 - Dispositivo: [Desktop]
 - SO: Windows 10 64 bits
 - Navegador [Chrome]
 - Versão [4.36.0]

**Comment by willph** [comment]
Mude a imagem que está usando no emitente. 
Bug com imagens do tipo PNG gerada por alguns software.

**Comment by willph** [comment]
Teste novamente e me avise

**Comment by itiossi** [comment]
@willph , agradeço o retorno rápido. Excelene! Era esse o problema mesmo! 
Parabéns pelas contribuições e pela nova versão!
