### ISSUE TITLE
Não exclui serviços em OS

### ISSUE THREAD

**Issue by TatianeVila** [RamonSilva20/mapos#1655]
Bom dia, primeiro, gostaria de parabenizar a todos os envolvidos no projeto e  na melhoria do visual, ficou fantástico!
Gostaria de reportar um problema que eu percebi na versão 4.36 onde os serviços lançados na OS não podem ser excluídos. O botão da correspondente simplesmente não gera ação nenhuma. 
Apenas um registro caso ninguém tenha reportado ainda.
Obs.: Tanto em instalação limpa como migrada isso ocorre (localhost) mesmo após Ctrl+F5.
Obrigada!

**Comment by willph** [comment]
Ok. Irei analisar

**Comment by SOROInfo** [comment]
O mesmo problema por aqui. Reforçando o elogio, ficou muito bom o novo layout, inclusive no celular.

**Comment by willph** [comment]
Já identificado o problema. 

Na atualização foi removido sem querer a tag `<a>`

**Comment by willph** [comment]
Correção enviada `bug fix delete service #1657 `

Aguarda aprovação

**Comment by TatianeVila** [comment]
Nossa, que rapidez!  Grata pelo empenho!!!

**Comment by willph** [comment]
> Nossa, que rapidez! Grata pelo empenho!!!

É que estava com um tempo livre.
Caso contrário demoraria um pouquinho.

Deu sorte. 😁

Mas a comunidade sempre ajuda.
https://chat.whatsapp.com/L8iJYyfHbHbIkh13XMGtjV

Atenciosamente, Equipe Mapos
