### ISSUE TITLE
configuração / emitente

### ISSUE THREAD

**Issue by jader-cz** [RamonSilva20/mapos#1656]
Falha!
Você não tem permissão para configurar emitente.

Como resolver este problema?

![erro - emitente](https://user-images.githubusercontent.com/82244572/155343458-fa1a32fa-e4d3-4a83-8c6d-5a59b145016d.png)

**Comment by willph** [comment]
> Falha! Você não tem permissão para configurar emitente.
> 
> Como resolver este problema?
> 
> ![erro - emitente](https://user-images.githubusercontent.com/82244572/155343458-fa1a32fa-e4d3-4a83-8c6d-5a59b145016d.png)

para liberar acesso precisa ser administrador do sistema.

Você criou 2 usuários com permissões diferentes?

**Comment by jader-cz** [comment]
Opa boa tarde, só tenho um usuário instalei o programa e quando clico em configurar o emitente abre este erro sendo que sou usuário único.

**Comment by willph** [comment]
> Opa boa tarde, só tenho um usuário instalei o programa e quando clico em configurar o emitente abre este erro sendo que sou usuário único.

Instalou do zero a versão daqui do repositório Mapos?

**Comment by jader-cz** [comment]
Sim notei agora que (usuário - permissões  e emitente não tenho permissões para configurar) vou salvar meu banco e instalar do zero novamente.

**Comment by willph** [comment]
> Sim notei agora que (usuário - permissões e emitente não tenho permissões para configurar) vou salvar meu banco e instalar do zero novamente.

Se conseguiu alterar, não precisa instalar o sistema novamente. 

Agora caso queira, aconselho a cria uma nova base de dados e aí sim instalar nessa nova base de dados

**Comment by jader-cz** [comment]
criar um novo banco?

**Comment by willph** [comment]
> criar um novo banco?

Se for reinstalar e não tiver nenhum dados, melhor fazer uma nova base de dados, para testar.
Vê se as permissões vem correta.

Mas só se quiser.
Não é necessário realmente fazer isso

**Comment by jader-cz** [comment]
entendi, não sei se você notou na imagem que mandei, mas nas guias laterais( inicio, produtos, ordens de serviço após instalar esta versão não me aparece a opção de vendas.

**Comment by jader-cz** [comment]
corrigindo = Entendi, não sei se você notou na imagem que mandei, mas nas guias laterais( inicio, produtos, serviços,  após a instalação desta versão não me aparece a opção de vendas.

**Comment by willph** [comment]
> entendi, não sei se você notou na imagem que mandei, mas nas guias laterais( inicio, produtos, ordens de serviço após instalar esta versão não me aparece a opção de vendas.

Permissão também. 
Se não tiver permissão. Não aparece

**Comment by jader-cz** [comment]
Obrigado vou tentar novamente, não conseguindo entro em contato.

**Comment by jader-cz** [comment]
Obrigado, vou tentar novamente, se eu não conseguir entro em contato novamente.

**Comment by willph** [comment]
De nada.
Só reabrir essa issue.

Atenciosamente, Equipe Mapos.

**Comment by jader-cz** [comment]
olá reinstalei tudo novamente o programa veio tudo certinho.  após instalar tudo novamente e restaurar o banco ele restaura faltando as guias ( Vendas, lançamentos, cobranças.) .

**Comment by willph** [comment]
> olá reinstalei tudo novamente o programa veio tudo certinho. após instalar tudo novamente e restaurar o banco ele restaura faltando as guias ( Vendas, lançamentos, cobranças.) .

Tem muitos dados?

Foi atualização?
Se sim, de qual versão?

**Comment by jader-cz** [comment]
Não tem muitos dados não começando agora a fazer alguns cadastros de clientes e produtos tipo uns 10 só para testar. foi onde notei isto na volta do backup. estou usando a versão mais recente mapos-master.

**Comment by willph** [comment]
> Não tem muitos dados não começando agora a fazer alguns cadastros de clientes e produtos tipo uns 10 só para testar. foi onde notei isto na volta do backup. estou usando a versão mais recente mapos-master.

Ok.
Irei testar também.

Cadastrar, salvar backup, fazer instalação do zero e tentar restaurar pra vê.

**Comment by jader-cz** [comment]
se eu restaurar um backup de ontem da instalação do sistema anterior vem desconfigurado as guias. creio que se eu fizer um backup hoje e amanha restaurar vai da certo.

**Comment by jader-cz** [comment]
explicando melhor, se eu restaurar o banco de dados exportado do dia que te mandei esta primeira foto no começo da conversa o sistema vai vir só com : ( inicio / cliente/fornecedor produto / ordem de serviço / termos de serviço e garantia. ) e não virar completo como na versão atual.

**Comment by jsfachini** [comment]
> explicando melhor, se eu restaurar o banco de dados exportado do dia que te mandei esta primeira foto no começo da conversa o sistema vai vir só com : ( inicio / cliente/fornecedor produto / ordem de serviço / termos de serviço e garantia. ) e não virar completo como na versão atual.

veja se isso te ajuda.
vai no seu (http://localhost/phpmyadmin/) e abra o seu banco de dados, ao abrir vai na seção USUARIOS clica em editar no seu user e procura por **permissoes_id** veja se esta marcado como **1-administrador**
