### ISSUE TITLE
Não esta adicionando nem editando as Os's

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#1659]
Após a atualização a pagina de adicionarOS aparece a seguinte mensagem "Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente, responsável e garantia. Ou se tem um cliente e um termo de garantia cadastrado." 

Ao realizar a edição de alguma OS ja cadastrada, não aparece mais a mensagem de confirmação de alteração e por isso também não salva os dados editados, voltando para edição anterior à atualização.

**Comment by willph** [comment]
> Após a atualização a pagina de adicionarOS aparece a seguinte mensagem "Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente, responsável e garantia. Ou se tem um cliente e um termo de garantia cadastrado."
> 
> Ao realizar a edição de alguma OS ja cadastrada, não aparece mais a mensagem de confirmação de alteração e por isso também não salva os dados editados, voltando para edição anterior à atualização.

Qual versão era anteriormente e qual a versão atualizada?

Atualizou o banco de dados?

Como foi feita essa atualização?

**Comment by vagnerlaiber** [comment]
Qual era versão que vc usava antes?

**Comment by fwsund** [comment]
4.32.0 e a atualização foi feita pelo próprio sistema
também realizai a atualização do banco de dados.
Usei outros navegadores.
a versão atual 4.35.2

**Comment by fwsund** [comment]
> 4.32.0 e a atualização foi feita pelo próprio sistema também realizai a atualização do banco de dados. Usei outros navegadores. a versão atual 4.35.2

atualizai para a versao 8.0 do  php e nao o seguinte erro aparece ja na tela de login "Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $configuration" entao voltei para versao anterior 7.4

**Comment by willph** [comment]
> > 4.32.0 e a atualização foi feita pelo próprio sistema também realizai a atualização do banco de dados. Usei outros navegadores. a versão atual 4.35.2
> 
> atualizai para a versao 8.0 do php e nao o seguinte erro aparece ja na tela de login "Whoops \ Exception \ ErrorException (E_WARNING) Undefined variable $configuration" entao voltei para versao anterior 7.4

botão atualizar sistema esta com bug. apenas o atualizar banco de dados funciona.

por favor substituir os arquivos manualmente e configura novamente.

**Comment by willph** [comment]
> > 4.32.0 e a atualização foi feita pelo próprio sistema também realizai a atualização do banco de dados. Usei outros navegadores. a versão atual 4.35.2
> 
> atualizai para a versao 8.0 do php e nao o seguinte erro aparece ja na tela de login "Whoops \ Exception \ ErrorException (E_WARNING) Undefined variable $configuration" entao voltei para versao anterior 7.4

Mapos ainda não tem suporte para versão php 8

**Comment by fwsund** [comment]
> > > 4.32.0 e a atualização foi feita pelo próprio sistema também realizai a atualização do banco de dados. Usei outros navegadores. a versão atual 4.35.2
> > 
> > 
> > atualizai para a versao 8.0 do php e nao o seguinte erro aparece ja na tela de login "Whoops \ Exception \ ErrorException (E_WARNING) Undefined variable $configuration" entao voltei para versao anterior 7.4
> 
> botão atualizar sistema esta com bug. apenas o atualizar banco de dados funciona.
> 
> por favor substituir os arquivos manualmente e configura novamente.

blz, vou executar a instalação

**Comment by willph** [comment]
Conseguiu?

**Comment by fwsund** [comment]
> Conseguiu?

Perdi um tempo aqui atualizando o composer e o xampp que deram problema. Os arquivos já estão no servidor. Vou instalar daqui uns 30min.

**Comment by willph** [comment]
> > Conseguiu?
> 
> Perdi um tempo aqui atualizando o composer e o xampp que deram problema. Os arquivos já estão no servidor. Vou instalar daqui uns 30min.

Certo. 
Ficarei no aguardo

**Comment by fwsund** [comment]
> Certo

Realmente o update através do sistema gera algum bug na atualização. Fiz o procedimento de instalação, subindo os novos arquivos e até agora não encontrei nenhum erro.  Agradeço muito a ajuda!
