### ISSUE TITLE
Parcelamento de pagamento

### ISSUE THREAD

**Issue by tutujaru** [RamonSilva20/mapos#1663]
Boa noite

Usou a um bom tempo e ainda não tem a função de venda parcelada 

E nem vencimento das ordem de serviço

Exemplo ele tem prazo de 6 meses

Pois uso em empresa de manutenção de ar condicionado e período e de 6 em 6 meses

**Comment by willph** [comment]
> E nem vencimento das ordem de serviço

Parcelamento realmente ainda não  tem, mas "`vencimento das ordem de serviço`" já tem, onde mostra se a ordem de serviço ainda esta na garantia, vencida ou serviço sem garantia
![vencia](https://user-images.githubusercontent.com/17226802/155511835-d4fe6675-32ec-407b-9fd6-946627946a86.PNG)

Você tem a versão mais recente do Map-Os?

**Comment by TatianeVila** [comment]
@willph, bom dia! :blush: e aqueles arquivos disponibilizados no grupo do whats, não poderiam ser utilizados?  :pray: :pray: :pray:
[parcelamento.zip](https://github.com/RamonSilva20/mapos/files/8132046/parcelamento.zip)
No caso estes 3 arquivos. Eu até tentei mas não sei se fiz errado  mas só apareceu em adicionar novas receitas, no resto não mudou nada!  :sweat_smile:
Por favorzinho? :kissing_cat:

**Comment by tutujaru** [comment]
> > E nem vencimento das ordem de serviço
> 
> Parcelamento realmente ainda não tem, mas "`vencimento das ordem de serviço`" já tem, onde mostra se a ordem de serviço ainda esta na garantia, vencida ou serviço sem garantia ![vencia](https://user-images.githubusercontent.com/17226802/155511835-d4fe6675-32ec-407b-9fd6-946627946a86.PNG)
> 
> Você tem a versão mais recente do Map-Os?

SIM ESTOU USANDO A 4.36

DIGO PARTE DE VENCIMENTOS SERIA UMA PAGINA ESPECIFICA 

PARCELAMENTO SERIA AJUDA E TANTO
![image](https://user-images.githubusercontent.com/100329749/155532164-061c38cd-66d4-40d4-a09a-dd35a6ee82d9.png)

**Comment by luizrn** [comment]
> @willph, bom dia! 😊 e aqueles arquivos disponibilizados no grupo do whats, não poderiam ser utilizados? 🙏 🙏 🙏 [parcelamento.zip](https://github.com/RamonSilva20/mapos/files/8132046/parcelamento.zip) No caso estes 3 arquivos. Eu até tentei mas não sei se fiz errado mas só apareceu em adicionar novas receitas, no resto não mudou nada! 😅 Por favorzinho? 😽

tem um grupo do whats? kkk sera que eu poderia entrar? é do mapos?

**Comment by willph** [comment]
> > @willph, bom dia! 😊 e aqueles arquivos disponibilizados no grupo do whats, não poderiam ser utilizados? 🙏 🙏 🙏 [parcelamento.zip](https://github.com/RamonSilva20/mapos/files/8132046/parcelamento.zip) No caso estes 3 arquivos. Eu até tentei mas não sei se fiz errado mas só apareceu em adicionar novas receitas, no resto não mudou nada! 😅 Por favorzinho? 😽
> 
> tem um grupo do whats? kkk sera que eu poderia entrar? é do mapos?

Tem sim.
Onde nos ajudamos, contribuímos, conversarmos....

https://chat.whatsapp.com/L8iJYyfHbHbIkh13XMGtjV
