### ISSUE TITLE
Desconto faturamento não aparece para o cliente na os

### ISSUE THREAD

**Issue by alexpicsilva** [RamonSilva20/mapos#1666]
Boa tarde, primeiro gostaria de agradecer pela aplicação, é muito eficiente.

Se puderem verificar o faturamento.
Talvez eu não entendi direito como funciona, mas quando eu faço uma ordem de serviço e aplico algum desconto, esse valor é faturado pra mim com o desconto, mas na ordem de serviço aparece o original. 
Isso gera um problema. Por exemplo: Se a conta do meu cliente deu R$ 300 e eu dei um desconto de 10% ficando então R$ 270, caso haja algum retorno desse problema e eu tenha que restituir o valor pro cliente, no comprovante vai constar que ele pagou R$ 300, e não R$270 então a loja perde R$ 30. Quanto às questões legais seria interessante sair discriminado na ordem de serviço o valor original e o valor com desconto qual o cliente pagou, para resguardar a loja.

Obrigado.

**Comment by willph** [comment]
> 

Esta se referindo a isso?
![desconto](https://user-images.githubusercontent.com/17226802/155623443-abd749b0-5392-4b9f-9444-bcdca76e5766.PNG)

Se for isso, o valor que aparece em vermelho é apenas para facilitar o preenchimento do campo VALOR, tendo que apagar e preencher com o valor sugerido em vermelho.

A função desconto ainda esta em desenvolvimento, isso foi uma sugestão da comunidade enquanto a função desconto não fica pronto.

Atenciosamente, Equipe Mapos.

**Comment by alexpicsilva** [comment]
Olá amigo, não seria exatamente isso, no entanto está vinculado à esta função. Vou tentar fazer um desenho sobre o problema.

![github-1](https://user-images.githubusercontent.com/36484118/155711757-d968514f-5b7c-4bbd-81f4-b3da61f99de3.png)
![github-2](https://user-images.githubusercontent.com/36484118/155711760-c5663cdd-399b-4c4c-ba80-4bad49ce5c20.png)
![github-desconto](https://user-images.githubusercontent.com/36484118/155711762-bac3a0a7-5140-4cda-9edc-2f7dd08279d2.png)

**Comment by willph** [comment]
Agora sim, eu entendi.

Nada como desenhado, como o ditado diz Kkkkkkk 
Irei analisar.

**Comment by jsfachini** [comment]
A opção de aparecer o desconto na OS impressa seria muito bem vinda!

**Comment by willph** [comment]
Tava fazendo uma Atualização do Mapos. 
Mas não esquece isso não.

**Comment by willph** [comment]
> Boa tarde, primeiro gostaria de agradecer pela aplicação, é muito eficiente.
> 
> Se puderem verificar o faturamento. Talvez eu não entendi direito como funciona, mas quando eu faço uma ordem de serviço e aplico algum desconto, esse valor é faturado pra mim com o desconto, mas na ordem de serviço aparece o original. Isso gera um problema. Por exemplo: Se a conta do meu cliente deu R$ 300 e eu dei um desconto de 10% ficando então R$ 270, caso haja algum retorno desse problema e eu tenha que restituir o valor pro cliente, no comprovante vai constar que ele pagou R$ 300, e não R$270 então a loja perde R$ 30. Quanto às questões legais seria interessante sair discriminado na ordem de serviço o valor original e o valor com desconto qual o cliente pagou, para resguardar a loja.
> 
> Obrigado.

Olá tudo bem?

Sobre sua questão fiz uma PR de numero #1734 que corrige esse problema.
Aguarde a aprovação e integração ao sistema.
