### ISSUE TITLE
Mapos 4 - Erro login

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#167]
Boa noite @RamonSilva20 

Instalei a versao 4 do mapos para ver como está, porém estou usando o banco de dados da versao antiga. Porem ao tentar efetuar login diz que os dados não conferem. O que será que pode estar ocorrendo? Da o erro que os dados de acesso estão errados, para tentar novamente.

Obrigado

**Comment by Pr3d4dor** [comment]
Eu não sei se no mapos4 ele está fazendo a verificação de login com a função password_verifiry nativa do PHP.

Se estiver precisa pegar o banco.sql no mapos3

Caso o mapos4 esteja utilizando o mcrypt para verificar o login precisa utilizar a outra versão do banco.sql.

**Comment by acinformatica2004** [comment]
Eu tenho o banco do mapos3 que utilizo e esta com os dados que preciso. Gostaria de reutiliza-lo.

**Comment by Pr3d4dor** [comment]
A criptografia foi alterada do mcrypt para bcrypt com a função nativa do PHP password_verify().

Você precisa fazer novamente o hash das senhas do seu banco de dados usando a função bcrypt() ou password_hash().

Ou você pode utilizar o banco.sql que está no repositório que está com hash da senha 123456 padrão do admin correta.

**Comment by acinformatica2004** [comment]
Boa tarde, teria como me dizer como fazer?
Obrigado

**Comment by acinformatica2004** [comment]
Posso mudar o banco que ja existe, o que vc acha melhor e mais fácil?

**Comment by Pr3d4dor** [comment]
Faz o seguinte:

Conecte no teu banco de dados com o phpMyAdmin ou pelo terminal e mude a hash da senha do banco da conta admin para:
```
$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO
```

Assim vc poderá logar com a sua conta de admin com a senha 123456.

Após isso você pode alterar a senha dos outros usuários.

**Comment by Pr3d4dor** [comment]
Pode postar uma print do erro ou uma descrição mais detalhada?

Eu não trabalhei muito com o mapos 4 mas posso tentar lhe ajudar.

**Comment by acinformatica2004** [comment]
Entao,eu clico no menu em ordem de serviço, ai da esse erro. Ele muda a tela e só aparece esse erro na parte superior.

**Comment by Pr3d4dor** [comment]
Parece que esse arquivo está faltando no branch mapos4.

Você pode pegar ele aqui: https://github.com/RamonSilva20/mapos/blob/master/application/helpers/codegen_helper.php

Cole ele dentro da pasta application/helpers/ com o nome codegen_helper.php

**Comment by acinformatica2004** [comment]
ixii, agora deu outro erro.

Fatal error: Cannot redeclare p() (previously declared in /home/advanced/public_html/mapos/application/helpers/util_helper.php:3) in /home/advanced/public_html/mapos/application/helpers/codegen_helper.php on line 8
A PHP Error was encountered

Severity: Error

Message: Cannot redeclare p() (previously declared in /home/advanced/public_html/mapos/application/helpers/util_helper.php:3)

Filename: helpers/codegen_helper.php

Line Number: 8

**Comment by Pr3d4dor** [comment]
Parece que as funções desse arquivo agora estão no arquivo util_helper.php

Então você tem que retirar a chamada de include/require helpers/codegen_helper.php onde está dando erro.

**Comment by acinformatica2004** [comment]
Blz, vou tentar.

**Comment by Pr3d4dor** [comment]
Recomendo esperar a resposta do @RamonSilva20, pois eu não mexi muito com o mapos 4 e ele lhe responderá melhor.

**Comment by RamonSilva20** [comment]
@acinformatica2004 os cadastros que não foram refatorados ainda este erro irá ocorrer, o helper codegen não será mais utilizado.

**Comment by acinformatica2004** [comment]
Obrigado a todos. Valeu.
