### ISSUE TITLE
Boleto não é gerado

### ISSUE THREAD

**Issue by petersonbreno** [RamonSilva20/mapos#1671]
Bom dia, espero que estejam bem!

Estou tentando gerar uma cobrança de venda, via boleto gerencianet porém o sistema não sai dessa tela:
![image](https://user-images.githubusercontent.com/99659564/155701841-c7362803-e709-42d3-85a0-6579aba1d504.png)

Na plataforma gerencianet, eu utilizei a informação de cliente_id e client_secret da aba produção.
![image](https://user-images.githubusercontent.com/99659564/155701948-35705864-2714-4b30-9aad-eb65a202175a.png)

**Comment by willph** [comment]
> Bom dia, espero que estejam bem!
> 
> Estou tentando gerar uma cobrança de venda, via boleto gerencianet porém o sistema não sai dessa tela: ![image](https://user-images.githubusercontent.com/99659564/155701841-c7362803-e709-42d3-85a0-6579aba1d504.png)
> 
> Na plataforma gerencianet, eu utilizei a informação de cliente_id e client_secret da aba produção. ![image](https://user-images.githubusercontent.com/99659564/155701948-35705864-2714-4b30-9aad-eb65a202175a.png)

Bom dia.
Tudo bom?

No arquivo `application/config/payment_gateways.php`
Na linha 11 e 12 foi inserido as credenciais de produção?

Mudou a linha 9 de `false` pra `true` 
`'production' => true,`

Atenciosamente, Equipe Mapos.

**Comment by petersonbreno** [comment]
Já está alterado para true.
Está informado as credencias de produção nas linhas 11 e 12.

**Comment by petersonbreno** [comment]
Nas linhas 11 e 12 eu preciso repetir a identificação client_id e client_secret dentro da chave?
![image](https://user-images.githubusercontent.com/99659564/155705582-dc710948-3940-4b5d-af1c-ea3abee61793.png)

**Comment by willph** [comment]
> Já está alterado para true. Está informado as credencias de produção nas linhas 11 e 12.

Perguntei porque fiz o teste ontem.

Tava lento, mas estava gerando.

**Comment by petersonbreno** [comment]
> > Já está alterado para true. Está informado as credencias de produção nas linhas 11 e 12.
> 
> Perguntei porque fiz o teste ontem.
> 
> Tava lento, mas estava gerando.

Tranquilo, aguardei até agora e a tela continua parada ainda naquela imagem que postei ;(

**Comment by willph** [comment]
> > > Já está alterado para true. Está informado as credencias de produção nas linhas 11 e 12.
> > 
> > 
> > Perguntei porque fiz o teste ontem.
> > Tava lento, mas estava gerando.
> 
> Tranquilo, aguardei até agora e a tela continua parada ainda naquela imagem que postei ;(

Terei que analisar pra saber se é lá na Gerencianet ou cá no nosso App

**Comment by petersonbreno** [comment]
Beleza muito obrigado.

**Comment by willph** [comment]
> Beleza muito obrigado.

testei agora no modo sandbox e funcionou!

**Comment by petersonbreno** [comment]
> > Beleza muito obrigado.
> 
> testei agora no modo sandbox e funcionou!

Meu arquivo php está desse jeito:

![image](https://user-images.githubusercontent.com/99659564/155717269-57005bb9-719b-4561-8ce1-562ba80c38fe.png)

Está correto, certo?
Estranho, aqui não gera nem com reza, rsrsrs

**Comment by willph** [comment]
> Bom dia, espero que estejam bem!
> 
> Estou tentando gerar uma cobrança de venda, via boleto gerencianet porém o sistema não sai dessa tela: ![image](https://user-images.githubusercontent.com/99659564/155701841-c7362803-e709-42d3-85a0-6579aba1d504.png)
> 
> Na plataforma gerencianet, eu utilizei a informação de cliente_id e client_secret da aba produção. ![image](https://user-images.githubusercontent.com/99659564/155701948-35705864-2714-4b30-9aad-eb65a202175a.png)

su

> > > Beleza muito obrigado.
> > 
> > 
> > testei agora no modo sandbox e funcionou!
> 
> Meu arquivo php está desse jeito:
> 
> ![image](https://user-images.githubusercontent.com/99659564/155717269-57005bb9-719b-4561-8ce1-562ba80c38fe.png)
> 
> Está correto, certo? Estranho, aqui não gera nem com reza, rsrsrs

Sua conta é nova ou antiga?

**Comment by willph** [comment]
porque tem umas coisas que precisa ser preenchida para poder liberar.

Testei modo produção e funcionou também.

Seu site esta hospedado?
localhost?

**Comment by petersonbreno** [comment]
> > Bom dia, espero que estejam bem!
> > Estou tentando gerar uma cobrança de venda, via boleto gerencianet porém o sistema não sai dessa tela: ![image](https://user-images.githubusercontent.com/99659564/155701841-c7362803-e709-42d3-85a0-6579aba1d504.png)
> > Na plataforma gerencianet, eu utilizei a informação de cliente_id e client_secret da aba produção. ![image](https://user-images.githubusercontent.com/99659564/155701948-35705864-2714-4b30-9aad-eb65a202175a.png)
> 
> su
> 
> > > > Beleza muito obrigado.
> > > 
> > > 
> > > testei agora no modo sandbox e funcionou!
> > 
> > 
> > Meu arquivo php está desse jeito:
> > ![image](https://user-images.githubusercontent.com/99659564/155717269-57005bb9-719b-4561-8ce1-562ba80c38fe.png)
> > Está correto, certo? Estranho, aqui não gera nem com reza, rsrsrs
> 
> Sua conta é nova ou antiga?

conta nova, criei ontem.

meu site está hospedado na umbler.com

saberia me dizer quais coisas precisa preencher? eu já criei a aplicação na plataforma do gerencianet para poder pegar esses códigos client_id e secret

**Comment by petersonbreno** [comment]
sem sucesso ainda, não consigo encontrar o erro, alguma sugestão?

já troquei inclusive os client_id e secret para os informados na aba homologação e playground.

**Comment by willph** [comment]
> 

Playground tem que mudar pra false. 

Testa instalando em localhost pra vê. 

Já configurou toda a conta.
Tem que preencher atividade e outras coisas pra liberar.

**Comment by petersonbreno** [comment]
Na conta do gerencianet não falta nada, acabei de gerar um boleto direto da plataforma deles e deu certo.

**Comment by willph** [comment]
> Na conta do gerencianet não falta nada, acabei de gerar um boleto direto da plataforma deles e deu certo.

Aí fica difícil. 

Baixa o código e testa localmente. 
Pra vê.
Modo playground

**Comment by petersonbreno** [comment]
Consegui resolver, rodei o comando composer install --no-dev no gitbash e após isso deu certo.

Gostaria de deixar registrado meus parabéns para a equipe toda que está colaborando para esse sistema ficar cada vez melhor, uso o MAPOS faz muito tempo já, acompanhei a evolução dele, esse novo layout está sensacional, meus parabéns mesmo e meus agradecimentos também, isso me ajuda muito.

**Comment by willph** [comment]
> Consegui resolver, rodei o comando composer install --no-dev no gitbash e após isso deu certo.
> 
> Gostaria de deixar registrado meus parabéns para a equipe toda que está colaborando para esse sistema ficar cada vez melhor, uso o MAPOS faz muito tempo já, acompanhei a evolução dele, esse novo layout está sensacional, meus parabéns mesmo e meus agradecimentos também, isso me ajuda muito.

Oxe. Não pensei nisso porque como o sistema já estava funcionando, pensei que fosse outra coisa.

Que bom que funcionou.

**Comment by petersonbreno** [comment]
> > Consegui resolver, rodei o comando composer install --no-dev no gitbash e após isso deu certo.
> > Gostaria de deixar registrado meus parabéns para a equipe toda que está colaborando para esse sistema ficar cada vez melhor, uso o MAPOS faz muito tempo já, acompanhei a evolução dele, esse novo layout está sensacional, meus parabéns mesmo e meus agradecimentos também, isso me ajuda muito.
> 
> Oxe. Não pensei nisso porque como o sistema já estava funcionando, pensei que fosse outra coisa.
> 
> Que bom que funcionou.

Pois é, eu tbm nem tinha imaginado isso antes, estava tudo bonitinho no sistema, mas pensei "já testei tudo, vou tentar no composer novamente" e foi :)
