### ISSUE TITLE
Busca não esta operando Corretamente 

### ISSUE THREAD

**Issue by Igor-Montuani** [RamonSilva20/mapos#1672]
Quando estou na parte de produtos, ou de serviço quando vou efetuar uma pesquisa usando o campo de pesquisa ele apenas me retorna os resultados listado na pagina atual que esta sendo exibida e não filtra do total

**Comment by luizrn** [comment]
realmente ele so filtra os resultado listados na página, da de aumentar o limite que ele busca alterando o resultado por página para 100 la em configurações, mas mesmo assim eu desativei esse campo em configurações para nao confundir, ai se usa o buscador geral,
