### ISSUE TITLE
Faturar

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1673]
Boa noite.
Geralmente usa o termo finalizado para concluir a OS. Porém quando faturamos fica por padrão o status "FATURADO" em qual o arquivo eu faço essa mudança, ou seja ao faturar a OS ele ja deixar o Status "FINALIZADO".

**Comment by luizrn** [comment]
boa noite, nao sei posso ajudar, porem creio que a ideia é essa mesmo, uma OS finalizada é faturada, mas se deseja mudar o status que ele salva após faturar, vc pode depois de faturado mudar o status para finalizada, ou do modo mais dificil, vá em /application/controllers editarOs.php linha 601 é onde processa e envia o POST para faturar, ai ele envia para index.php/os/faturar, é nessa funnção ai que vai ta onde ele grava o status provavelmente e nao consegui achar

**Comment by jsfachini** [comment]
Ao meu ver o FINALIZADO é quando o técnico terminou o serviço e FATURADO é quando além de terminado o serviço já foi enviado ao setor financeiro e evidentemente faturado para cobrança, mas como o @luizrn falou da para alterar caso queira personalizar.

**Comment by p-francelino** [comment]
Valeu!!!
