### ISSUE TITLE
Gerar Receita com Parcelamento

### ISSUE THREAD

**Issue by Igor-Montuani** [RamonSilva20/mapos#1674]
Olá estou utilizando o sistema e gostaria que quando fosse adicionar uma venda tivesse a opção de lançar uma receita parcelada

**Comment by luizrn** [comment]
seria muito bom em,mas uma dica se precisa fazer isso, atualmente, pra parcelar algo nele, precisa criar uma OS ou VENDA para cada parcela com as respectivas datas futuras

**Comment by luizrn** [comment]
Em breve estará disponível, ja mandei a PR para análise
