### ISSUE TITLE
Bug com a atualização.

### ISSUE THREAD

**Issue by JetLi-Almeida** [RamonSilva20/mapos#1676]
Bom, fui atualizar meu mapos para a nova versão e ele ficou bugado, como nos prints ali em baixo.. então removi ele e instalei novamente mas ainda sim ficou bugado.. alguma sugestão do que fazer ?

![image](https://user-images.githubusercontent.com/79049787/156366153-fe20ddee-9fc1-4b9f-be8b-8f06fd963756.png)
![image](https://user-images.githubusercontent.com/79049787/156366493-d938bbc3-6ce0-4af3-9bcb-2bc888ec73c3.png)

**Comment by willph** [comment]
Bom dia.

Aperte CTRL + R ou limpa cache do navegador e tente acessar novamente. 

Atenciosamente, Equipe Mapos

**Comment by JetLi-Almeida** [comment]
> Bom dia.
> 
> Aperte CTRL + R ou limpa cache do navegador e tente acessar novamente.
> 
> Atenciosamente, Equipe Mapos

Olá Bom dia..

Era exatamente isso, Obrigado.
