### ISSUE TITLE
Pode atualizar da versão 4.35.2 diretamente pelo atualizar mapos?

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#1677]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by pachekosss** [comment]
Tentei fazer o processo e me encheu de dor de cabeça, terei que reinstalar. Fiz o processo pelo atualizador do próprio sistema.

**Comment by Pr3d4dor** [comment]
@pachekosss @MarceloGrass O recomendado sempre antes de atualizar é fazer um backup do banco e do código mesmo. Infelizmente o atualizador por dentro do sistema tem alguns bugs. Então o recomendado é atualizar manualmente.

**Comment by pachekosss** [comment]
Então, estou tentando instalar a nova versão e só da erro, se eu instalo a
antiga ele roda perfeito. Tentei instalar a antiga e atualizar fazendo
backup do banco de dados e dos arquivos database.php e config.php da pasta
application/config e colando os arquivos novos, dessa maneira o sistema
ficou preso na tela que diz estar instalado e nao redireciona para nenhuma
outra.

Em sex., 4 de mar. de 2022 às 01:17, Gianluca Bine ***@***.***>
escreveu:

**Comment by pachekosss** [comment]
[image: erro_mapos.png]

Em sex., 4 de mar. de 2022 às 10:56, Leandro da Silva Pacheco <
***@***.***> escreveu:

**Comment by pachekosss** [comment]
![erro_mapos](https://user-images.githubusercontent.com/100850832/156802918-c5a4bc6d-ae0a-454d-9a06-f3dd52df4efe.png)

**Comment by MarceloGrass** [comment]
Então como uso o sistema diariamente não me animei a atualizar diretamente por medo a travar, vou descarregar a pasta completa do site e depois tentar atualizar qualquer coisa apago tudo e volto a subir, pretendo fazer isso no final de semana, porem criei um outro subdomínio e instalei de zero e depois copiei os dados da base de dados que uso pra base de dados do novo e deu certo os dados estão todos lá, agora uma coisa que notei escolhi o tema escuro porem não funciona nem em clientes nem em OSs no estante sim, também escolhi 20 registros por pagina mas só aparecem 10, já nos produtos tenho a opção de visualizar 10, 20, 50, etc isso sim funciona, os relatórios também funcionam só tive que copiar a logo do subdomínio em uso para o novo na mesma pasta pois sem logo da erro.

**Comment by MarceloGrass** [comment]
Achei excelente a gráfica nova,parabéns!

**Comment by MarceloGrass** [comment]
Limpei a cache do site e agora mostra 20 registros por pagina e a cor focou escura em todas as paginas.

**Comment by luizrn** [comment]
uma coisa tbm que queria saber, onde no codigo que fica para mudar oo numero de resultados por página? oque tem tem nas configurações parece ser só o limite, ai vai em alguma listagem como as OS e ai sim pode mudar, mas nao fica salvo, fica sempre 10

**Comment by MarceloGrass** [comment]
Uma coisa que eu tinha esquecido cuando instalei o sistema anterior pela primeira vez é que tem que desabilitar a cachê no subdomínio ou dominio aonde se instale o sistema, pois se não fizer isso as mudanças são feitas mas não aparecem até limpar a cachê, isso pode ser feito no cPanel ou similar do hosting. Se não fizer fica parecendo bug do sistema e não é não.

**Comment by luizrn** [comment]
mas quando vc apagou o cache e ficou mostrando 20 registros por página direto? sem precisar toda vez mudar na tabela de registros de 10 para 20? oque quero dizer é que se cada vez que atualiza a pagina de OS fica 20 registros?

**Comment by MarceloGrass** [comment]
Fica sim os 20 registros, mas só para reforçar o cachê deve ser desabilitado no hosting aonde estiver hospedado o sistema seja num subdomínio ou dominio. Deve entrar nas configurações do hosting na parte do cachê e desabilitar no endereço que estiver o sistema mapos rodando.

**Comment by luizrn** [comment]
assim entendi obg

**Comment by MarceloGrass** [comment]
Respondendo a pergunta inicial do post sim foi possível atualizar sem problemas desde o próprio sistema em Configurações - Atualizar - Fiz o teste hoje e assim que fiz a primeira pagina a aparecer foi um erro como o usuário [pachekosss] mostrou no print: [https://github.com/RamonSilva20/mapos/issues/1677#issuecomment-1059323135]  porem voltando atras no navegador o sistema apareceu sem erros, e os dados sem alterações tudo como estava, somente tive que substituir a logo e o arquivo OS view e OS edit modificados para o WhatsApp abrir no App em lugar do navegador. Mas uma vez parabéns pela nova versão que é responsiva no celular ficando show.
