### ISSUE TITLE
Não funciona relatórios, atualização e e-mail 

### ISSUE THREAD

**Issue by Aldrith72** [RamonSilva20/mapos#1678]
** Descreva o bug **
Estou cadastrando clientes e realizando normalmente a abertura de OS, porém não consigo mais realizar nenhum relatório, logo que foi instalado o sistema chegou a funcionar 1 dia , porém parou de funcionar e nenhum relatório funciona clientes, OS, produtos, nada   

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'clientes '
2. Clique em  Relatórios Rápidos' Todos os clientes ' ou em Relatórios Customizáveis
3. abre a página com erro 
4. Mpdf \ MpdfImageException (E_ERROR)
Error parsing image file - image type not recognised, and not supported by GD imagecreate

Após a instalação do sistema no domínio a página de entrada da empresa parou de funcionar e fica enviando um arquivo para Download

application/x-httpd-ea-php74 (405 bytes)

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [windows 10, Android e IOs]
 - Navegador [ Chrome, Mozilla, Edge]
 - Versão [ última versão ]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [iPhone12 e Samsung S21]
 - SO: [ última versão ]
 - Navegador [Chrome, Safari, ]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@Aldrith72 Aparentemente precisa habilitar a extensão GD no seu PHP.

**Comment by willph** [comment]
> ** Descreva o bug ** Estou cadastrando clientes e realizando normalmente a abertura de OS, porém não consigo mais realizar nenhum relatório, logo que foi instalado o sistema chegou a funcionar 1 dia , porém parou de funcionar e nenhum relatório funciona clientes, OS, produtos, nada
> 
> **Reproduzir** Etapas para reproduzir o comportamento:
> 
>     1. Vá para 'clientes '
> 
>     2. Clique em  Relatórios Rápidos' Todos os clientes ' ou em Relatórios Customizáveis
> 
>     3. abre a página com erro
> 
>     4. Mpdf \ MpdfImageException (E_ERROR)
>        Error parsing image file - image type not recognised, and not supported by GD imagecreate
> 
> 
> Após a instalação do sistema no domínio a página de entrada da empresa parou de funcionar e fica enviando um arquivo para Download
> 
> application/x-httpd-ea-php74 (405 bytes)
> 
> **Comportamento esperado** Uma descrição clara e concisa do que você esperava que acontecesse.
> 
> ** Capturas de tela ** Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
> 
> ** Desktop (preencha as seguintes informações): **
> 
>     * SO: [windows 10, Android e IOs]
> 
>     * Navegador [ Chrome, Mozilla, Edge]
> 
>     * Versão [ última versão ]
> 
> 
> ** Smartphone (preencha as seguintes informações): **
> 
>     * Dispositivo: [iPhone12 e Samsung S21]
> 
>     * SO: [ última versão ]
> 
>     * Navegador [Chrome, Safari, ]
> 
>     * Versão [por exemplo 22]
> 
> 
> ** Contexto adicional ** Adicione qualquer outro contexto sobre o problema aqui.

Você cadastrou imagem do Emitente?
