### ISSUE TITLE
Venda de Produtos

### ISSUE THREAD

**Issue by ChrisFrs** [RamonSilva20/mapos#1681]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.
Ao cria a venda ele funciona normal, mas ele não encontra os produtos para adicionar.

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.
Adicionar o produto para a finalização da venda.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

![image](https://user-images.githubusercontent.com/79609733/156484253-6825a044-e598-4154-bce1-3bb607c4b74f.png)

**Comment by willph** [comment]
Boa noite.
Tudo bom?

O produto precisa está cadastrado no menu produto, para poder adicionar. 
Não é possível fazer adição direta.

Atenciosamente, Equipe Mapos

**Comment by ChrisFrs** [comment]
Bom dia Willph, fiz um teste em Os, o mesmo consegue achar o produto que foi cadastrado, por algum motivo ele não acha em vendas.

**Comment by willph** [comment]
> Bom dia Willph, fiz um teste em Os, o mesmo consegue achar o produto que foi cadastrado, por algum motivo ele não acha o produto em vendas, para adicionar.
> 
> ![image](https://user-images.githubusercontent.com/79609733/156538148-94ac9073-f7b2-484b-9cde-ad0d2cd8d720.png)
> 
> ![image](https://user-images.githubusercontent.com/79609733/156538275-a5d90c10-1c1b-45c0-a94f-ac8bcf811835.png)

Irei analisar

**Comment by willph** [comment]
Analisei aqui, e está funcionando.
Para teste cadastrei o mesmo produto.

**Comment by ChrisFrs** [comment]
Provavelmente já consertaram, mesmo assim obrigado. Irei baixar dnovo e testar novamente.

**Comment by willph** [comment]
> 

O produto está em estoque?
Está marcado entrada e saída do produto?

**Comment by ChrisFrs** [comment]
Pode fechar,  já descobri meu erro, na hora de adicionar o produto eu marquei somente entrada, mas estranho que ele adicionava em OS porém em venda ele não deixava adicionar.
