### ISSUE TITLE
chamar nome do arquivo no anexo ou colocar um nome no anexo

### ISSUE THREAD

**Issue by lemrage** [RamonSilva20/mapos#169]
Quando sobre os anexos deveria puxar um nome para o arquivo

**Comment by lemrage** [comment]
alguem sabe onde editar para chamar o nome do anexo da os?

**Comment by lemrage** [comment]
beleza mas tipo quando coloco vamos dizer uns 5 anexos como vou saber qual e qual quando precisar baixar referente a os so chama o nome do anexo embaixo do quadradinho da foto la na lista de anexos

**Comment by lemrage** [comment]
na os em anexos na listagem aparecer o nome em baixo eu acho que ficaria joia

**Comment by Pr3d4dor** [comment]
Você quer saber quais anexos estão relacionados à uma OS? É isso mesmo?

**Comment by lemrage** [comment]
sim na tela de anexos do cliente e do administrador aparecer em baixo na foto o nome do arquivo tipo na imagem ai do link abaixo

https://ibb.co/eqv0Ae

**Comment by Pr3d4dor** [comment]
@lemrage Vou verificar e tentar fazer essa implementação.

**Comment by Pr3d4dor** [comment]
Fiz a implementação disponível na PR #173
