### ISSUE TITLE
Sugestão: PDV no sistema.

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#1696]
Sou novo aqui... Me perdoe qualquer equivocu meu... 

Sugestão 

1- PDV no sistema. 

2 - O campo/gráfico Estatísticas Financeira deveria ter opção de visualização por ano... no meu caso eu estou vendo tudo desde o inicio dados geral financeiro...

**Comment by willph** [comment]
Boa noite.

Editei para fica um pouco mais fácil a compreensão.
Era isso que estava tentando dizer?

**Comment by CarlosCavalcante87** [comment]
> Boa noite.
> 
> Editei para fica um pouco mais fácil de compreensão. Era isso que estava tentando dizer?

Sim. Obrigado pela ajuda!
