### ISSUE TITLE
Derrubando o Site

### ISSUE THREAD

**Issue by Aldrith72** [RamonSilva20/mapos#1699]
** Descreva o bug **
O sistema MAPos  não coexiste no mesmo domínio

**Comportamento esperado**
Quando realizo a configuração no  htaccess para o Site da empresa funcionar o MAPos  não funciona.
Quando o sistema MAPos funciona perfeitamente, a página principal fica enviando um arquivo para Download toda vez que acessa a página do Domínio e a página fica em branco, e não informa erro. 

** Capturas de tela **
![image](https://user-images.githubusercontent.com/99360284/157536976-9c9cd1d5-3e91-4c50-bcbc-9c197cec40f7.png)

** Desktop (preencha as seguintes informações): **
 - SO: [todos os sistemas]
 - Navegador [todos navegadoresi]
 - Versão [atualizado ]

** Contexto adicional **
conteúdo do arquivo 

<?php
/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which does and tells WordPress to load the theme.
 *
 * @package WordPress
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define( 'WP_USE_THEMES', true );

/** Loads the WordPress Environment and Template */
require __DIR__ . '/wp-blog-header.php';

**Comment by luizrn** [comment]
cara, se envia um arquivo pra download e esse arquivo for php, quer dizer que nessa hospedagem sua ai, não ta rodando um servidor php, verifica com a hospedagem se esta rodando php e tbm precisa estar na versão 7.4. espero ter ajudado.

**Comment by Aldrith72** [comment]
Preciso de alguém que de suporte no sistema MAPOS  estou com ele instalado em um subdomínio do CentOS7 e quando funciona a página principal , não funciona o sistema e vice versa.

**Comment by willph** [comment]
> Preciso de alguém que de suporte no sistema MAPOS estou com ele instalado em um subdomínio do CentOS7 e quando funciona a página principal , não funciona o sistema e vice versa.

É uma VPS ou é como?
