### ISSUE TITLE
Cadastro de Fornecedor

### ISSUE THREAD

**Issue by jeanhoracio** [RamonSilva20/mapos#17]
Tem ideia para adicionar um cadastro de fornecedor igual o de cliente?

**Comment by hardbrasil** [comment]
É Muito útil e este recurso e sendo possível também juntamente seria interessante um cadastro de Pedidos de compras.
Dentro deste tópico também seria interessante a possibilidade de inserir fotos e detalhes do produto no cadastro de produto além de preço de compra, preço de venda atacado, preço de venda varejo, campo para inserção de desconto em porcentagem no ítem no ato da venda.

**Comment by rafaelmarques** [comment]
Tenho algo neste sentido mas ainda muito beta. Apenas um cadastro de compras atrelado com a os para facilitar a identificação do material utilizado no serviço.

![captura de tela 2017-04-28 as 00 24 18](https://cloud.githubusercontent.com/assets/1713986/25513187/afef8022-2ba9-11e7-9afa-e14ff8b01f6c.png)
![captura de tela 2017-04-28 as 00 25 02](https://cloud.githubusercontent.com/assets/1713986/25513188/aff02c8e-2ba9-11e7-8232-e3d5b65ada27.png)

**Comment by hardbrasil** [comment]
Show muito bom






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 28 abr 2017 00:29:32 -0300 Rafael Marques &lt;notifications@github.com&gt; wrote ----




Tenho algo neste sentido mas ainda muito beta. Apenas um cadastro de compras atrelado com a os para facilitar a identificação do material utilizado no serviço.

**Comment by edgarmeireles** [comment]
@rafaelmarques ficou show!!! 
Consegue compartilhar o fonte? Seria muito útil pra mim também... até mesmo para corrigir possíveis erros...

Dependendo do caso, o @RamonSilva poderia até incluir isso em versões futuras.
