### ISSUE TITLE
Campo responsável/ tecnico da OS automático com o login do usuário.

### ISSUE THREAD

**Issue by mauriliolopesjunior** [RamonSilva20/mapos#170]
Galera blz, poderiam me ajudar, como faço para mudar e deixar
Campo responsável/ tecnico da OS automático com o login do usuário.

nao precisar colocar o resposavel, ele ficara a pessoa que estiver logada

segue imagem
![os responsavel](https://user-images.githubusercontent.com/41583140/43476803-7f60b182-94c7-11e8-8959-44e45c028c69.PNG)

O codigo do campo
![responsavel](https://user-images.githubusercontent.com/41583140/43476808-83b5eb94-94c7-11e8-95a6-5c1b97d2b391.PNG)
tentei colocar desta forma <?php echo $usuario->nome?>

mas deu erro.

poderiam me dar uma ajuda.

obrigado

**Comment by RamonSilva20** [comment]
@mauriliolopesjunior tente puxar esses dados da sessão. 

Exemplo (Código não testado):

` <input id="tecnico" class="span12" type="text" name="tecnico" readonly value="<?= $this->session->userdata('nome'); ?>"  />`

`<input id="usuarios_id" class="span12" type="hidden" name="usuarios_id" value="<?= $this->session->userdata('id'); ?>"  />`
