### ISSUE TITLE
Ajuda com sistema

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#1700]
** Descreva o bug **
Boa noite, utilizo uma versão antiga do sistema, porem modifiquei algumas coisas para meu uso, mais nunca quis atualizar pra versão nova, pois a versão que uso me supre. Porém hoje pela manha o sistema estava funcionando perfeitamente, logo após o almoço fui acessar e está dando esse erro na imagem em anexo.
Utilizo o sistema hospedado na hospedagem hostimidia, entrei em contato e me mandaram que meu código está com erro, sendo que mais cedo estava tudo ok.
Se puderem meu ajudar.
Agradeço desde já

** Desktop (preencha as seguintes informações): **
 - SO: windows 10
 - Navegador Firefox 98

[http://ordemservico.advancedcomputer.com.br/erro/erro1.png](url)
[http://ordemservico.advancedcomputer.com.br/erro/erro2.jpg](url)

**Comment by willph** [comment]
não tem imagem.

Not Found

**Comment by willph** [comment]
> não tem imagem.
> 
> Not Found

http://ordemservico.advancedcomputer.com.br/erro/erro1.png
http://ordemservico.advancedcomputer.com.br/erro/erro2.jpg

Essas imagens não estão disponíveis. 

Como você fechou subjugo que já resolveu.
