### ISSUE TITLE
AJUDA COM HOSTINGER

### ISSUE THREAD

**Issue by MiqueiasMarinho** [RamonSilva20/mapos#1701]
Já configurei tudo. Inclusive fiz um Passo a passo igual ao de um amigo aqui postou a solução do problema. Mas nada adianta. 

Eu não consigo fazer o Cron funcionar na Hostinger. Logo, os E-mails não disparam. 

Já editei os campos na pasta do servidor conforme é solicitado no passo a passo de instalação, configurei um E-mail profissional, e para este mesmo E-mail fiz diversas configurações e tentativas no Cron, mas nada funciona. Aparece a mensagem: NÃO FOI POSSÍVEL LOCALIZAR OU PUXAR OS DADOS DO SERVIDOR. 

Podem me ajudar?

**Comment by willph** [comment]
> Já configurei tudo. Inclusive fiz um Passo a passo igual ao de um amigo aqui postou a solução do problema. Mas nada adianta.
> 
> Eu não consigo fazer o Cron funcionar na Hostinger. Logo, os E-mails não disparam.
> 
> Já editei os campos na pasta do servidor conforme é solicitado no passo a passo de instalação, configurei um E-mail profissional, e para este mesmo E-mail fiz diversas configurações e tentativas no Cron, mas nada funciona. Aparece a mensagem: NÃO FOI POSSÍVEL LOCALIZAR OU PUXAR OS DADOS DO SERVIDOR.
> 
> Podem me ajudar?

Conseguiu resolver?

**Comment by MiqueiasMarinho** [comment]
Opa.. ainda não... Usando somente o Whats por enquanto
________________________________
De: Wilmerson ***@***.***>
Enviado: quinta-feira, 14 de abril de 2022 23:03
Para: RamonSilva20/mapos ***@***.***>
Cc: MiqueiasMarinho ***@***.***>; Author ***@***.***>
Assunto: Re: [RamonSilva20/mapos] AJUDA COM HOSTINGER (Issue #1701)


Já configurei tudo. Inclusive fiz um Passo a passo igual ao de um amigo aqui postou a solução do problema. Mas nada adianta.

Eu não consigo fazer o Cron funcionar na Hostinger. Logo, os E-mails não disparam.

Já editei os campos na pasta do servidor conforme é solicitado no passo a passo de instalação, configurei um E-mail profissional, e para este mesmo E-mail fiz diversas configurações e tentativas no Cron, mas nada funciona. Aparece a mensagem: NÃO FOI POSSÍVEL LOCALIZAR OU PUXAR OS DADOS DO SERVIDOR.

Podem me ajudar?

Conseguiu resolver?
