### ISSUE TITLE
ARQUIVOS LOGOTIPO MAPOS 4.36.2

### ISSUE THREAD

**Issue by lucassilvarp** [RamonSilva20/mapos#1702]
Na antiga versao no arquivo matrix-style  la na pasta CSS , conseguimos alterar a logo editando o arquivo, na nova versão devido a mudança no codigo fonte, nao estou localizando aonde estao referenciais para os logos que ficam na pasta IMG , alguem consegue apoiar?

**Comment by tibjunior** [comment]
Entrando pelo google chrome, pressiona f12 pra abrir a parte de inspeção, daí vc vai abrindo as divs e ele vai marcando na pagina onde vc ta..

A imagem da esquerda (SVG) /assets/img/dashboard-animate.svg
As 2 do login:
/assets/img/logo-two.png e /assets/img/logo-mapos-branco.png

só colocar imagens compatíveis e com o mesmo nome nessas pastas e substituir.. :)
