### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by roviglio** [RamonSilva20/mapos#1704]
Estou usando a versão 4.35.2
1 erro - Ao Actualizar directamente pelo 'MAPOS' apareceu aquela tela de erro que todo mundo esta escrevendo.
2 erro - Mesmo voltando o navegado o programa não mostra todos os icones, falta algumas imagens e as letras ficaram bem pequenas.
3 erro - Instação limpa, o composer por linha de comando agora pede token. 
4 erro - Mesmo usando o token criado no github o composer não termina a instalação falta algo parece que é referente pagamento assa
5 erro - Se tentar substituir a pasta aplication e assets exibe erro 500
Alguma possibilidade de alguem enviar um zip do ultimo mapos.??? 
Não estou conseguindo intalar a ultima versão.

**Comment by willph** [comment]
> Estou usando a versão 4.35.2 1 erro - Ao Actualizar directamente pelo 'MAPOS' apareceu aquela tela de erro que todo mundo esta escrevendo. 2 erro - Mesmo voltando o navegado o programa não mostra todos os icones, falta algumas imagens e as letras ficaram bem pequenas. 3 erro - Instação limpa, o composer por linha de comando agora pede token. 4 erro - Mesmo usando o token criado no github o composer não termina a instalação falta algo parece que é referente pagamento assa 5 erro - Se tentar substituir a pasta aplication e assets exibe erro 500 Alguma possibilidade de alguem enviar um zip do ultimo mapos.??? Não estou conseguindo intalar a ultima versão.

Aqui funcionou normalmente o comando `composer install --no-dev` na pasta raiz do mapos.

Botão atualizar mapos tem bug, o unico que funciona é o atualizar banco de dados.

**Comment by roviglio** [comment]
Willph obrigado por responder.
Voltei os backup e refiz para pegar as telas de erro:
![01-erro](https://user-images.githubusercontent.com/84595434/158172615-c086170b-2a47-4fb9-a4d2-03a16a639cb3.jpg)
![02-erro](https://user-images.githubusercontent.com/84595434/158172628-5315283a-c318-43e0-aea8-d589f5c78121.jpg)
![03-erro](https://user-images.githubusercontent.com/84595434/158172647-e281ff5a-3e15-4800-aa75-6d437696d114.jpg)
Isto é o que acontece quando uso o botão atualizar do mapos.
Mas se depois de atulizar pelo botão do mapos fechar o navegador.
Abrir uma tela nova do navegador e limpar o cache, tudo senha imagens etc.. e fechar o navegador .
Abrir o navegador e o mapos.
Pronto ta rodando
![04-depois de limpar o cache](https://user-images.githubusercontent.com/84595434/158173213-629990a2-ac15-4a8c-b107-4597b2f488be.jpg)
.
Não sei se ajuda os demais, para mim funcionou.
Ha!
O programa que mostra erro é o Github_updater.php na linha 95.
copy ( $dir."/". $file->filename, $file -> filename);

**Comment by roviglio** [comment]
Willph quando ao composer.
Será que muda alguma coisa quando usa-se ssl
Mesmo sendo local estou usando certificado 
Criei uma pasta e tentei rodar o composer
![erro do composer](https://user-images.githubusercontent.com/84595434/158176574-4fc9364e-182f-4bd4-b5ef-5062e69f2f7b.jpg)
Aparentemente ele reclamou da senha ou token  mas antes não pedia isso.
Desde já obridado.

**Comment by roviglio** [comment]
Parabéns pela actualização ficou muito bonita!!!

**Comment by willph** [comment]
> Parabéns pela actualização ficou muito bonita!!!

Obrigado. 

Foi feito por @MilsonElias da comunidade Mapos.

**Comment by willph** [comment]
> Willph quando ao composer. Será que muda alguma coisa quando usa-se ssl Mesmo sendo local estou usando certificado Criei uma pasta e tentei rodar o composer ![erro do composer](https://user-images.githubusercontent.com/84595434/158176574-4fc9364e-182f-4bd4-b5ef-5062e69f2f7b.jpg) Aparentemente ele reclamou da senha ou token mas antes não pedia isso. Desde já obridado.

Está na pasta raiz do Mapos?

**Comment by roviglio** [comment]
Estou trabalhando com vários domínios:
Dentro deste domínio criei a pasta m para teste porque estou usando a mapos
Vou mudar e já te envio

**Comment by roviglio** [comment]
mesmo dentro da pasta com nome de mapos ,

![erro_composer](https://user-images.githubusercontent.com/84595434/158179167-426291f0-3aa9-4457-af89-1058efb7474f.jpg)

**Comment by roviglio** [comment]
Mesmo colocando a pasta na raiz do htdocs
![mapos](https://user-images.githubusercontent.com/84595434/158179862-57d42e18-8952-40b8-b258-255d847cf5fb.jpg)
d
