### ISSUE TITLE
Sugestão simples - cronjobs no Windows para enviar os e-emails

### ISSUE THREAD

**Issue by luizrn** [RamonSilva20/mapos#1707]
no .md https://github.com/RamonSilva20/mapos/blob/create-function-reset-password/Instalacao_xampp_windows.md, colocar tbm para como fazer cron no windows assim enviar emails. 

Esse cron rodará a cada minuto o comando `email/process` (FAZER O MESMO TUTORIAL PARA CRIAR PARA O COMANDO email/retry)

No Windows é possível usar o Agendador de Tarefas do sistema para fazer isso.

- Abra o agendador de tarefas (ou task scheduler):
![LSEsX](https://user-images.githubusercontent.com/10822915/158272712-83ee8867-47ec-463c-93f3-6cb9ad93670f.png)

- Vá em criar uma nova tarefa:
![UdVf1](https://user-images.githubusercontent.com/10822915/158272755-079c3511-fd21-44d3-9219-e1b79b843eb9.png)

- Na aba geral defina um nome para a tarefa e para ela executar mesmo que o usuário não esteja logado (isso faz rodar em background)
Na aba seguinte, crie um trigger para ser executado a cada minuto indefinidamente.:
![Fm9hw](https://user-images.githubusercontent.com/10822915/158272792-886f11b1-0873-4287-8f77-d03614074644.png)

![jndGc](https://user-images.githubusercontent.com/10822915/158272822-35a4a265-8f1b-446a-a93b-53fecba295f1.png)

- E na aba de ações, crie uma nova ação especificando o executável do php, o comando email/process e o diretório do seu projeto. Depois disso basta dar um ok e informar uma credencial do seu usuário e o schedule será executado como um cron:
![45dWz](https://user-images.githubusercontent.com/10822915/158272844-4a3697c9-6ea3-4ff7-93db-48a3d6080574.png)

**Comment by willph** [comment]
obrigado pela sugestão

**Comment by willph** [comment]
Como enviou uma PR #1715 com essa sugestão, estou fechando essa issue.

**Comment by luizrn** [comment]
atualizado
