### ISSUE TITLE
Listar apenas OS aberto no sistema V2.6

### ISSUE THREAD

**Issue by mauriliolopesjunior** [RamonSilva20/mapos#171]
Preciso de ajuda, quero que apareça apenas as OS em aberto no menu Ordem de Serviço.

![os](https://user-images.githubusercontent.com/41583140/43482090-b6e9c1d0-94d5-11e8-8fdc-e9c04fcf0390.PNG)

pois esta aparecendo todas as OS. versao 2.6

**Comment by RamonSilva20** [comment]
@mauriliolopesjunior atualize a versão do sistema para uma mais recente onde existe o filtro, ou adicione uma cláusula abaixo no model para filtrar somente pelo status aberto. O arquivo é o os_model e o método não me lembro se é o **get()** ou **getOs()**.

**$this->db->where('status','Aberto');**
