### ISSUE TITLE
Erro ao cadastrar Cliente

### ISSUE THREAD

**Issue by Hik94** [RamonSilva20/mapos#1712]
Estou com problemas em cadastrar cliente. Sempre aparece 'Ocorreu um erro'. Estou na última bersão do Map-Os

**Comment by Hik94** [comment]
![PSX_20220316_131610](https://user-images.githubusercontent.com/77890344/158637754-88cac031-9041-40ab-b0ad-f9ef1cd7da8b.jpg)

**Comment by willph** [comment]
Foi atualização ou instalação do zero?

**Comment by Hik94** [comment]
Instalação do zero. Mas como apresentou o mesmo problema. Atualizei do zero pra última versão. Usei o xamp versão 7.4.27

**Comment by Hik94** [comment]
Preenchi todos os campos e mesmo assim o problema persistiu (lacunas das informações dos clientes).

**Comment by willph** [comment]
Versão Mapos-master?

**Comment by willph** [comment]
Preencha a senha e coloque salvar, pra vê se vai

**Comment by Hik94** [comment]
Achei apenas a aba de atualização do banco de dados.

**Comment by willph** [comment]
> Achei apenas a aba de atualização do banco de dados.

Pode clicar nele para atualizar banco de dados.

Não clique no atualiza Mapos pois esse botão tem bug.

**Comment by Hik94** [comment]
Eu cliquei em atualizar Map-Os e atualizou.

**Comment by Hik94** [comment]
Agora foi.

**Comment by Hik94** [comment]
Obrigado.
