### ISSUE TITLE
Valor da ordem de serviço não carrega

### ISSUE THREAD

**Issue by Hik94** [RamonSilva20/mapos#1713]
![Uploading 20220316_181411.jpg…]()

**Comment by willph** [comment]
Esse produto está cadastrado?

Não é possível inserir manualmente direto sem ter ele cadastrado.

**Comment by Hik94** [comment]
Não.

**Comment by Hik94** [comment]
Obrigado.

**Comment by willph** [comment]
> Obrigado.

Isso se aplica para produto e serviços.
