### ISSUE TITLE
auditoria

### ISSUE THREAD

**Issue by Santtzin** [RamonSilva20/mapos#1714]
alguem sabe me dizer se é possivel adicionar o numero da os que foi adicionada na auditoria
![image](https://user-images.githubusercontent.com/101824375/158858977-b4cc9e54-00d2-440f-b345-39a33782a1ba.png)

**Comment by willph** [comment]
Sim tem como. Só pega o id do retorno do registro.

**Comment by Santtzin** [comment]
Pode me dar um exemplo de como fazer isso

**Comment by luizrn** [comment]
O problema é que é um insert de OS, o id só é obtido depois, porem, na function OS.php que fica em controllers, chamada alguma coisa como Adicionar, antes de inserir no banco de dados, ele tem um código la que obtém o próximo id de um insert no banco, esse é o id q será dado a OS, ele salva esse ID em em uma variável, basta pegar essa variável e colocar lá onde tem o código log, pouco antes do insert no banco ou depois não me lembro bem. Espero ter ajudado.

**Comment by Santtzin** [comment]
Vou tentar, se der certo dou um retorno aqui, obrigado!
