### ISSUE TITLE
Acesso recusado ao localhost/mapos

### ISSUE THREAD

**Issue by Hik94** [RamonSilva20/mapos#1716]
Não carrega mais a página de log in do Mapos. Como resolver ?

**Comment by luizrn** [comment]
Você fez alguma alteração nos arquivos do maps ou apache/Wamp/Xampp? pode descrever melhor o problema ou oque fez por último antes de ocorrer isso?

**Comment by Hik94** [comment]
Não fiz modificações em nenhuma pasta do Mapos.

**Comment by Hik94** [comment]
Só tentei acessar pelo celular.

**Comment by Hik94** [comment]
Desliguei o notebook

**Comment by luizrn** [comment]
assim, vc fez o procedimento no seu apache para acesso externo? esse erro ocorre pq seu servidor local não está configurado corretamente para acesso na rede local, o melhor seria mesmo se vc configurasse para acesso ip local e nao localhost, vai no seu arquivo apache (httpd-conf) procura pela linha Listen, ou 80, ai vc coloca nesta linha "Listen localhost:80"

**Comment by Hik94** [comment]
Vou fazer isso.

**Comment by luizrn** [comment]
Siga esse tutorial ou procure por "Liberar acesso externo Apache" , ou muda o aapache para o programa que vc ta usando como servidor local, talves o wamp server ou xampp, http://www.linhadecodigo.com.br/artigo/3512/liberando-acesso-global-no-apache.aspx

**Comment by Hik94** [comment]
Certo.

**Comment by ChrisFrs** [comment]
Pelo que deu a entender, o xampp esta no notebook e você esta usando ele via localhost, no caso ai funciona assim, o seu notebook precisa estar ligado e o xampp estar rodando, para que você acesse o mapos via celular, lembrando também que o celular tem que estar na mesma rede.
Se por acaso você desliga o notebook você esta desligando o mapos também, para que funcione ele via internet terá que contratar uma hospedagem.

**Comment by Hik94** [comment]
Entendi.

**Comment by Hik94** [comment]
Eu fiz o procedimento. Mas, o MySQL não inicia.

**Comment by Hik94** [comment]
![16475616051524141370950957318013](https://user-images.githubusercontent.com/77890344/158912722-eced5917-f9b4-4075-ad23-5e72168de7ec.jpg)

**Comment by ChrisFrs** [comment]
Tenta rodar ele sempre como administrador, normalmente isso se resolve.

**Comment by Hik94** [comment]
Voltou ao normal.
