### ISSUE TITLE
Área do Cliente

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#1719]
Alguém tendo problemas com a área do cliente?

acabei de atualizar e notei que não conseguia acessar pela área do cliente.. 
ao tentar cadastrar ele não cadastra.. nem apresenta erros..

**Comment by willph** [comment]
Porque a área do cliente agora é dado por senha e não pelo cpf/CNPJ.

Você pode adicionar a senha pela área do administrador.
Também precisa atualizar banco de dados. 

Solicitação da comunidade

**Comment by tibjunior** [comment]
A ok, vou fazer.. vlw.. :)
