### ISSUE TITLE
Quando fatura uma OS a ela nao muda o status para Faturado.

### ISSUE THREAD

**Issue by mauriliolopesjunior** [RamonSilva20/mapos#172]
Boa tarde galera.

Quando fatura uma OS a ela nao muda o status para faturado. é normal isso ou a versao esta com bug.

caso nao tenha alguem teria ideia de como fazer para que mude o status para faturado.

obrigado

**Comment by acinformatica2004** [comment]
Boa noite, nas vendas acontece isso, ja nas OS não, seria uma boa essa implantação.
