### ISSUE TITLE
Não consigo adcionar novo cliente

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#1720]
Após a ultima atualização Não consigo adcionar clientes. Simplismente da uma mensagem que "ocorreu um erro" no momento de salvar o novo cliente.
Dai quando vou atualizar o sistema aparece essa mensagem:

Arguments
"copy(application/views/conecte/emails/clientenovasenha.php): failed to open stream: No such file or directory"

obs. uso o sistema on line.

![Screenshot_4](https://user-images.githubusercontent.com/76854766/159122764-601eb58e-cfcf-4909-aed7-475ca37d093e.png)
.

**Comment by willph** [comment]
Você usou o atualizado do MapOs. 

Botão atualiza Mapos?

**Comment by Mouzinho08** [comment]
Estou com o mesmo poblema, mesmo atualizando o banco de dados, gera esse erro ao atualizar, não consigo adicionar clientes ou apagar um serviço ou venda.
Estou na versão 4.35.2

**Comment by Pr3d4dor** [comment]
@CarlosCavalcante87 @Mouzinho08 Provavelment vocês realizaram a atualização do mapos usando o botão atualizar dentro do próprio mapos. Essa atualização do próprio mapos tem alguns bugs que precisam ser corrigidos. Recomendo realizar a atualização/instalação manual.

**Comment by Mouzinho08** [comment]
@Pr3d4dor Obrigado vou fazer isso

**Comment by alexpicsilva** [comment]
Eu baixei a instalação do zero e refiz nessa nova versão e também estou com erro ao criar novo cliente. Voltei pra versão anterior à esta e nela consegui criar.

**Comment by willph** [comment]
> Eu baixei a instalação do zero e refiz nessa nova versão e também estou com erro ao criar novo cliente. Voltei pra versão anterior à esta e nela consegui criar.

Tem que inserir senha do cliente. 
Por favor Insira uma senha pro cliente e teste.

Caso não funcione por favor retornar

**Comment by CarlosCavalcante87** [comment]
> Você é o atualizado do MapOs.
> 
> Botão atualização Mapas?

Fiz a atualização manual, resolver o problema! Obrigado a todos pela atenção!

**Comment by TatianeVila** [comment]
A ideia de acesso á cliente via senha é ótima. Mas creio que a maioria de quem usa o MAP-OS não usa essa função e honestamente é chato ter que cadastrar uma senha para cada usuário, sabendo que nunca ira acessar pois o sistema esta local.
Seria ótimo, ter a opção então de não precisar cadastrar (não ser campo obrigatório)  ou desativar os campos.

**Comment by willph** [comment]
> A ideia de acesso á cliente via senha é ótima. Mas creio que a maioria de quem usa o MAP-OS não usa essa função e honestamente é chato ter que cadastrar uma senha para cada usuário, sabendo que nunca ira acessar pois o sistema esta local. Seria ótimo, ter a opção então de não precisar cadastrar (não ser campo obrigatório) ou desativar os campos.

Já discuti isso no grupo do Whatsapp com a comunidade. 

Vou enviar uma PR onde na área do administrador, caso não preencha vira o CPF/CNPJ do cliente.
Apenas números.

**Comment by willph** [comment]
> Após a ultima atualização Não consigo adcionar clientes. Simplismente da uma mensagem que "ocorreu um erro" no momento de salvar o novo cliente. Dai quando vou atualizar o sistema aparece essa mensagem:
> 
> Arguments "copy(application/views/conecte/emails/clientenovasenha.php): failed to open stream: No such file or directory"
> 
> obs. uso o sistema on line.
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/76854766/159122764-601eb58e-cfcf-4909-aed7-475ca37d093e.png) .

Fiz uma PR para caso não preencha o campo senha na hora do cadastro do cliente ele assume o cpf/cnpj como sendo a senha do cliente.
Isso na area do administrador.
Lembrando que tem que preencher o pelo menos um dos dois campos ou senha ou cpf. 😄 

PR #1725
