### ISSUE TITLE
Este erro iniciou após atualização

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#1727]
![MAPOS](https://user-images.githubusercontent.com/76854766/159790742-2c750b4f-c942-45bd-bf22-cf1d8cb7c2f6.png)

Isso occore tanto na versao on line quanto na local

**Comment by willph** [comment]
Como foi feita a atualização?

**Comment by CarlosCavalcante87** [comment]
Quando eu subir os arquivos


![MAPOS2](https://user-images.githubusercontent.com/76854766/159802450-e2ad44f6-ac8b-4bf4-ad1b-94b68d5b4ba3.png)
!

**Comment by luizrn** [comment]
via mapos da muito erro, é aconselhável fazer manualmente, baixar do repositório e atualizar os arquivos, outra coisa tabem, se sua versao é muito antiga, nao é recomendado apos instalados o novo mapos, nao restaurar o backup todo, caso tiver, somente seus dados como clientes, OS, etc, e exportar o backup somente dos dados e não estrutura

**Comment by CarlosCavalcante87** [comment]
Realmente a versão do PHP tinha direta ligação com o erro citado.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
