### ISSUE TITLE
Enviar cobrança pelo whatsapp

### ISSUE THREAD

**Issue by Santtzin** [RamonSilva20/mapos#1731]
Teria como adicionar uma forma de enviar a cobrança pelo whatsapp, tipo um botão como na parte de "OS".

**Comment by luizrn** [comment]
teria que ter um botao igual que tem em OS mas colocar no visualizar cobrança la em Cobranças, ai nas infos vc coloca tudo referente a cobrança, precisa fazer tbm uma function no controller igual de Os para envio no whats
