### ISSUE TITLE
Link da o.s.

### ISSUE THREAD

**Issue by N01062561978** [RamonSilva20/mapos#1736]
Boa tarde Pessoal. Gostaria de adicionar uma idéia, um link para o cliente abrir pelo whatsapp. Não tenho o código mas vale uma dica.

![image](https://user-images.githubusercontent.com/67173632/160491493-b9ae1eb1-53ed-4d6f-a668-b73be002c0df.png)

**Comment by N01062561978** [comment]
Enviar o link para o cliente abrir a o.s
Mas se eu enviar dessa forma: https://meudominio.com?id=1200. O cliente
terá acesso a o.s1199, 1201 ou 1202 etc. Gostaria que fosse criptografado
ex:
https://meudominio.com?id=Fgha43h@?CdA


Em qui, 31 de mar de 2022 16:16, Wilmerson ***@***.***>
escreveu:

**Comment by luizrn** [comment]
envia para ele os dados da area do cliente, la ele tem acesso a OS, manda o link https://meudominio.com/mine

no link tbm pode ser enviado o email junto assim /mine?e=email_cliente@hotmail.com

**Comment by demasnet** [comment]
muita boa a dica, porem teria como add a tag la onde configura os dados na menssagem zap? la tem varias, porem nao tem uma para selecionar o email do cliente auto
