### ISSUE TITLE
Desconto adicionado na venda não é contabilizado 

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#1737]
![image](https://user-images.githubusercontent.com/49371821/160492782-a3718f1a-8c5b-45ca-88df-5125d94807bc.png)

**Comment by willph** [comment]
O desconto ainda não foi lançado.

Está na PR ainda.

**Comment by iagocotta** [comment]
> O desconto ainda não foi lançado.
> 
> Está na PR ainda.

Boa noite Will qual o melhor local para esclarecer dúvidas sobre o código com vocês? Comecei a mexer com esse desconto, já fiz a interface que captura o valor total da os, já consigo inserir no banco algumas informações, mas surgiu uma dúvida na hora de passar da tela de EditarOS na função faturar() alguns valores para jogar no banco que não estou conseguindo capturar, tem algum canal que consigo falar sobre dúvidas

![image](https://user-images.githubusercontent.com/9218459/160727469-7b1eb219-3118-4581-9582-12098ded3a54.png)

![image](https://user-images.githubusercontent.com/9218459/160727618-567069c0-b543-459f-bc36-1d07b0b8c956.png)

![image](https://user-images.githubusercontent.com/9218459/160727753-20ddd4af-05e9-4e38-8f08-d01423b965bd.png)

![image](https://user-images.githubusercontent.com/9218459/160727804-626ad35b-b278-4d3d-acbd-8e73f60e85dc.png)

![image](https://user-images.githubusercontent.com/9218459/160727864-3804a1f6-c772-4779-9a89-b1c6e4665c32.png)

![image](https://user-images.githubusercontent.com/9218459/160727896-d56f31ad-4aee-4bf0-ba62-61d6b86f5f61.png)

Minha dúvida é como pegar os valores abaixo: para que em Os.php eu possa fazer os calculos dos valores a incrementar em valorFaturado e atualizar na tabela OS

![image](https://user-images.githubusercontent.com/9218459/160728274-1260f209-1bdf-4d47-8e42-cff6580c79fb.png)


![image](https://user-images.githubusercontent.com/9218459/160728838-4493aa23-23e1-4e4b-9412-bfebbb897e53.png)


Resumindo, queria além de inserir na tabela lançamento( que ja funciona) atualizar apenas o valorFaturado que criei  na tabela OS que seria o somatorio do que já existe nesse campo no banco de dados + o valor que usuario acabou de faturar na OS vindo do editarOS na função faturar, só preciso dessa orientação de como passar da view (editarOS ) para a OS.php (model faturar()) e fazer o update na tabela OS no campo valorFaturado

![image](https://user-images.githubusercontent.com/9218459/160729564-b1616806-c82e-4693-b807-8ad058704e99.png)

Pretendo depois que concluir essa etapa, pois realmente fiquei muitos anos sem mexer com programação e estou retomando agora, então de antemao já peço desculpas pela dúvida grotesca heheh , começar a enviar novas funcionalidades para o projeto e fazer crescer ainda mais, pq realmente ta TOPPPP!!!!

**Comment by willph** [comment]
Tem a PR #1734 onde já tem desconto em OS e Venda, cuidado com conflitos.

De uma olhada e teste as PRs.
Qualquer duvida estaremos aqui.

Agradecemos a força.

Obrigado!

**Comment by iagocotta** [comment]
> Tem a PR #1734 onde já tem desconto em OS e Venda, cuidado com conflitos.
> 
> De uma olhada e teste as PRs. Qualquer duvida estaremos aqui.
> 
> Agradecemos a força.
> 
> Obrigado!

VI realmente que já estava trabalhando nela quando fui vir aqui pedir suporte, mas minha duvida nem é tanto com relação ao desconto em si, mas qual a forma correta de passar da view para o controller e como fazer o update em uma tabela em especifica com esse dado capturado, você teria um exemplo pratico para me explica? Pq estou travado nesta situação de capturar da view tratar esses dados na controller e como enviar para o banco. Trazer do banco de dados ta tranquilo ja entendi
