### ISSUE TITLE
Erro ao cadastrar cliente

### ISSUE THREAD

**Issue by minuanorefrigera** [RamonSilva20/mapos#1739]
Estou tendo erro ao cadastrar um cliente
Atualmente tenho somente um cliente cadastrado.
Achei interessante a ideia do seu projeto, penso emmigrar alguns cliente porem, consegui cadastrar somente um cliente
Não sei se foi depois da ultima atualização, ou o que aconteceu

**Comment by willph** [comment]
Olá, tudo bom?

Qual versão está usando?


Atenciosamente, Wilmerson (Equipe Map-Os)

**Comment by Rosean-dev** [comment]
O MEU TAMBEM DA ERRO AO CADASTRAR CLIENTE, MOSTRA QUE OCORREU UM ERRO

**Comment by minuanorefrigera** [comment]
Bom dia
Onde vejo a versão?
Eu instalei o sistema a uns 15 dias baixado aqui do github mesmo

**Comment by minuanorefrigera** [comment]
[2022 © Ramon Silva - Map-OS - Versão: 4.36.2](https://github.com/RamonSilva20/mapos)

**Comment by jsfachini** [comment]
> Estou tendo erro ao cadastrar um cliente Atualmente tenho somente um cliente cadastrado. Achei interessante a ideia do seu projeto, penso emmigrar alguns cliente porem, consegui cadastrar somente um cliente Não sei se foi depois da ultima atualização, ou o que aconteceu
__________________________________________

Tive problema parecido, após atualizar pra uma versão mais nova.
foi resolvido atualizando o banco de dados
configurações>sistema>atualizações>BANCO DE DADOS

**Comment by leolfgomes** [comment]
Boa tarde, tbm esta tendo problemas para cadastrar clientes, minha versão é a 4.37
também esta apresentando erro ao faturar OS,

**Comment by Pr3d4dor** [comment]
@leolfgomes Atualize o seu banco de dados.

**Comment by leolfgomes** [comment]
> @leolfgomesAtualize o seu banco de dados.

@Pr3d4dor banco de dados atualizado, e problema resolvido. Obrigado.
