### ISSUE TITLE
iniciar ordem de serviços a partir de um número

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#1740]
na nossa assistência técnica usavamos papel para nota manual.
aggora queremos usar o mapos, mas, a dúvida é:
queremos que ao cadastrar uma OS ela seja iniciada a partir de 5000 por exemplo, e a partir daí, sequencialmente vai 5001, 5002, 5003, 5004, 5006, e assim vai 5050 e assim vai.
ou seja, iniciar a ordem a partir de um número.
ao invés de criar OS 1, OS2 e etc.
obrigado desde já pela ajuda

**Comment by N01062561978** [comment]
É só você dar comando no seu phpmyadmin: ALTER TABLE os AUTO_INCREMENT = 5000;
onde o "5000" pode ser a numeração inicial apartir do momento que fazer
