### ISSUE TITLE
Adicionar nota de serviço anônima

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#1741]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.
aqui em pouso alegre, alguns clientes e assistências técnicas porcas acabam não solicitando cpf, endereço e outros dados na entrada da ordem de serviço.
o problema é reeducar estes individuos,
deveria haver uma função chamada OS anônima, onde ao adicionar a opção, apenas informamos dados dos equipamentos. e o no máximo nome do cliente e telefone.
tem muita gente que não passa cpf
ou como posso tornar alguns campos opcionais?

**Comment by N01062561978** [comment]
Sim, você pode alterar tudo isso no código.  No form_validation que está na pasta config e no próprio javascript da página onde queira alterar
