### ISSUE TITLE
Permitir ao cliente inserir anexos ao abrir uma OS.

### ISSUE THREAD

**Issue by wabassis** [RamonSilva20/mapos#1748]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
**Quando meu cliente abre uma OS ele precisa anexar arquivos para a elaboração do orçamento.
Fazemos orçamento para instalação de câmeras, instalação de controle de acesso e montagem de quadros de comando, além de outros serviços técnicos de elétrica/automação.
Para entender a necessidade do cliente eles precisam nos enviar plantas e outros documentos.** 

** Descreva a solução que você deseja **
**Permitir que esteja disponível o envio de anexos na abertura da OS.**

** Descreva as alternativas que você considerou **
**Como ainda estamos implementando e testando o MAP-OS (15 dias apenas), a solução até o momento é o cliente abrir a OS e requisitarmos os arquivos via email.**

** Contexto adicional **
**Achei muito legal o sistema, instalei em uma máquina virtual linux (Debian) e depois num Openwrt.
Deu bastante trabalho no Openwrt (Por conta dos pacotes no PHP e eu não instalar o Composer como root), mas acabou rodando legal... um dos problemas foi o timezone que é fixo no código, tive que alterar na mão.**

_**Não vou subir outro request, mas a opção de habilitar/desabilitar o botão de cadastramento de usuário na tela de login do cliente também seria interessante (Vou acabar removendo o botão no código mesmo)**_

**Comment by luizrn** [comment]
Ola, so para deixar claro aqui e resumir, na área do cliente, implementar a opção do cliente anexar arquivos em sua OS, vamos lá,. é uma boa ideia, no entendo, é muito perigoso isso, deixar o cliente fazer upload de arquivos em seu sistema/host,.

Ja o segundo ponto que falou, de criar uma opção de ativar ou desativar a criação ou login na área de clientes, por esta opção la em Configurações > Sistema, criar uma aba chamada Área Cliente e nela por a opção de ativar e desativar, muito boa essa sugestão.
