### ISSUE TITLE
imagem no cadastro de produtos

### ISSUE THREAD

**Issue by luispasten** [RamonSilva20/mapos#175]
Bom dia galera!
Gostaria adicionar um **input file**  no cadastro dos Produtos para adicionar uma imagem ao momento de adicionar, deletar ou alterar!

Alguém pode dar uma dica ou ajudar na implementação dessa função...

**Comment by khigashi** [comment]
Estou pensando em fazer um catálogo de peças consumindo o banco do sistema e categorias e imagens nos produtos ajudaria d+ além de ter um insumo maior para os relatórios.

**Comment by HigorHenrike** [comment]
> Estou pensando em fazer um catálogo de peças consumindo o banco do sistema e categorias e imagens nos produtos ajudaria d+ além de ter um insumo maior para os relatórios.

Você já começou a fazer? estou trabalhando no mesmo, poderíamos nos unir para melhorar o desenvolvimento.

**Comment by khigashi** [comment]
Boa tarde Higor! Tudo bem? Desisti do projeto na fase de processo do formato que eu iria aplicar então nem dei andamento! =\
