### ISSUE TITLE
Instalação do LocalWeb

### ISSUE THREAD

**Issue by systech-brz** [RamonSilva20/mapos#1751]
Pela experiência de vocês 

Tem como me dizer se dá para instalar no LocalWeb....?

![IMG-20220407-WA0014](https://user-images.githubusercontent.com/100020785/162237688-b506b4ef-2c84-40ea-a8fb-1d056026bc6f.jpeg)

![IMG-20220407-WA0010](https://user-images.githubusercontent.com/100020785/162237800-aad66561-1831-4e5b-8918-dbe6c521c707.jpeg)

![IMG-20220407-WA0012](https://user-images.githubusercontent.com/100020785/162237929-fb0c66a4-50e6-46cc-9c4d-a4dc078aaad8.jpeg)

**

**Comment by tecinfotecnologia** [comment]
Boa tarde @systech-brz , instalei em uma VPS e esta rodando 100%.

**Comment by Pr3d4dor** [comment]
@systech-brz Tem algumas pessoas que usam na locaweb sim.

**Comment by alanpereiracoelho** [comment]
@systech-brz Basta apenas ajustar o arquivo php.ini dentro da pasta da locaweb.

allow_url_fopen = Off
Para 
allow_url_fopen = On
