### ISSUE TITLE
E-mail aparece como enviado mas não chega

### ISSUE THREAD

**Issue by pepehend** [RamonSilva20/mapos#1754]
Instalei o sistema e estou testando, e um problema que encontrei foi o seguinte:

ao enviar uma OS por e-mail para um cliente, não chega o e-mail, usando o e-mail da Hostgator, chegando somente para e-mails do mesmo domínio.

Abaixo estão as configurações do e-mail.

![Captura de Tela 2022-04-07 às 22 21 08](https://user-images.githubusercontent.com/67608911/162344692-911ab867-e12c-4b37-8976-28a2c844ba9d.png)
![Captura de Tela 2022-04-07 às 22 21 26](https://user-images.githubusercontent.com/67608911/162344696-f5ba4274-db85-42fa-a2cc-cf5cbb9ebaac.png)

**Comment by IRAKE** [comment]
Estou com o mesmo problema, queria saber o que modificar no MY_mail para corrigir

**Comment by IRAKE** [comment]
![image](https://user-images.githubusercontent.com/5889544/162562752-03c21d18-7183-41e4-a9bc-d60c911647f5.png)
enviado mas só chega no email do mesmo servidor

![image](https://user-images.githubusercontent.com/5889544/162562770-0ef92255-e53e-4cf3-97ff-5aac81be0f4b.png)
não chega envia para servidores Gmail & hotmail

**Comment by IRAKE** [comment]
já tentei com e sem SSL, mesma situação em ambos

**Comment by pedrotrm** [comment]
Seria uma boa você acessar via ssh e checar o logs do sistema para ver o que esta acontecendo

**Comment by pepehend** [comment]
> Seria uma boa você acessar via ssh e checar o logs do sistema para ver o que esta acontecendo

onde fica o log?

**Comment by pedrotrm** [comment]
Cara depende do provedor , pesquisa como habilitar/verificar log php provedor que voce ta usando por exemplo eu uso hostinger seria isso https://www.hostinger.com.br/tutoriais/como-verificar-os-logs-de-erro-php-do-seu-site ... apos isso voce vai acompanhar o arquivo log e ver o que erro vai dar no envio do email .

**Comment by willph** [comment]
> Instalei o sistema e estou testando, e um problema que encontrei foi o seguinte:
> 
> ao enviar uma OS por e-mail para um cliente, não chega o e-mail, usando o e-mail da Hostgator, chegando somente para e-mails do mesmo domínio.
> 
> Abaixo estão as configurações do e-mail.
> 
> ![Captura de Tela 2022-04-07 às 22 21 08](https://user-images.githubusercontent.com/67608911/162344692-911ab867-e12c-4b37-8976-28a2c844ba9d.png) ![Captura de Tela 2022-04-07 às 22 21 26](https://user-images.githubusercontent.com/67608911/162344696-f5ba4274-db85-42fa-a2cc-cf5cbb9ebaac.png)

Olá, tudo bom?

Verificou em configuração, notificações, se está marcado para enviar email para o cliente?

**Comment by pepehend** [comment]
> > Instalei o sistema e estou testando, e um problema que encontrei foi o seguinte:
> > ao enviar uma OS por e-mail para um cliente, não chega o e-mail, usando o e-mail da Hostgator, chegando somente para e-mails do mesmo domínio.
> > Abaixo estão as configurações do e-mail.
> > ![Captura de Tela 2022-04-07 às 22 21 08](https://user-images.githubusercontent.com/67608911/162344692-911ab867-e12c-4b37-8976-28a2c844ba9d.png) ![Captura de Tela 2022-04-07 às 22 21 26](https://user-images.githubusercontent.com/67608911/162344696-f5ba4274-db85-42fa-a2cc-cf5cbb9ebaac.png)
> 
> Olá, tudo bom?
> 
> Verificou em configuração, notificações, se está marcado para enviar email para o cliente?

Sim, está marcado para enviar para o cliente, porém ele só envia se for do mesmo domínio cadastrado na configuração do email.

![prtsc1](https://user-images.githubusercontent.com/67608911/162579590-63bc8416-d738-4e6f-8aae-e4f9cbde4db1.png)

**Comment by IRAKE** [comment]
> > > Instalei o sistema e estou testando, e um problema que encontrei foi o seguinte:
> > > ao enviar uma OS por e-mail para um cliente, não chega o e-mail, usando o e-mail da Hostgator, chegando somente para e-mails do mesmo domínio.
> > > Abaixo estão as configurações do e-mail.
> > > ![Captura de Tela 2022-04-07 às 22 21 08](https://user-images.githubusercontent.com/67608911/162344692-911ab867-e12c-4b37-8976-28a2c844ba9d.png) ![Captura de Tela 2022-04-07 às 22 21 26](https://user-images.githubusercontent.com/67608911/162344696-f5ba4274-db85-42fa-a2cc-cf5cbb9ebaac.png)
> > 
> > 
> > Olá, tudo bom?
> > Verificou em configuração, notificações, se está marcado para enviar email para o cliente?
> 
> Sim, está marcado para enviar para o cliente, porém ele só envia se for do mesmo domínio cadastrado na configuração do email.
> 
> ![prtsc1](https://user-images.githubusercontent.com/67608911/162579590-63bc8416-d738-4e6f-8aae-e4f9cbde4db1.png)

esse é o meu mesmo problema, tambem uso hostgator

**Comment by willph** [comment]
Verificou se não está chegando como span?

**Comment by pepehend** [comment]
> Verificou se não está chegando como span?

Verifiquei sim, não chega, mas quando eu envio para um e-mail do mesmo domínio, chega normalmente, só não chega para outros domínios.

**Comment by pedrotrm** [comment]
O cron esta configurado corretamente ? Caso sim o sistema pelo menos tenta enviar email ?

**Comment by pepehend** [comment]
> O cron esta configurado corretamente ? Caso sim o sistema pelo menos tenta enviar email ?

O problema em si não são as crons. Como eu estava testando, eu rodo o comando pelo terminal só para enviar, e ele envia, mas não chega, a não ser que seja do mesmo domínio.

**Comment by IRAKE** [comment]
> Verificou se não está chegando como span?

Não envia não, só vai para email que é do mesmo servidor, meu cron esta funcionando, porque o status no email muda de enviando para enviado, quando coloco um email do mesmo servidor o email chega no destinatario, mas quando é enviado para hotmail ou gmail não chega no destinatario, se eu enviar direto do servidor chega em ambos, mas pelo script MY_MAIL não vai, nunca consegui enviar email desde quando instalei, dar vontade de alugar outro servidor só pra testar, uso o hostgator.

**Comment by willph** [comment]
> > Verificou se não está chegando como span?
> 
> Não envia não, só vai para email que é do mesmo servidor, meu cron esta funcionando, porque o status no email muda de enviando para enviado, quando coloco um email do mesmo servidor o email chega no destinatario, mas quando é enviado para hotmail ou gmail não chega no destinatario, se eu enviar direto do servidor chega em ambos, mas pelo script MY_MAIL não vai, nunca consegui enviar email desde quando instalei, dar vontade de alugar outro servidor só pra testar, uso o hostgator.

Eu tive um problema parecido. 
Mas foi VPS 

A porta SMTP era bloqueado. 
Não sei se é o seu caso.

Mas aparentemente parece ser bloqueo do servidor. 

Está usando o SMTP do próprio servidor?

**Comment by IRAKE** [comment]
> > > Verificou se não está chegando como span?
> > 
> > 
> > Não envia não, só vai para email que é do mesmo servidor, meu cron esta funcionando, porque o status no email muda de enviando para enviado, quando coloco um email do mesmo servidor o email chega no destinatario, mas quando é enviado para hotmail ou gmail não chega no destinatario, se eu enviar direto do servidor chega em ambos, mas pelo script MY_MAIL não vai, nunca consegui enviar email desde quando instalei, dar vontade de alugar outro servidor só pra testar, uso o hostgator.
> 
> Eu tive um problema parecido. Mas foi VPS
> 
> A porta SMTP era bloqueado. Não sei se é o seu caso.
> 
> Mas aparentemente parece ser bloqueo do servidor.
> 
> Está usando o SMTP do próprio servidor?

isso, imaginei ser algo do tipo, vou tentar ver se o suporte do servidor pode corrigir isso, porque é estranho mandar email só para email do mesmo servidor quando usado protocolo SMTP

**Comment by pepehend** [comment]
Acho que não deve ser isso, por que ao usar outras plataformas de e-mail como o Outlook por exemplo, funciona perfeitamente.

**Comment by willph** [comment]
> Acho que não deve ser isso, por que ao usar outras plataformas de e-mail como o Outlook por exemplo, funciona perfeitamente.

Justamente por ser um SMTP externo.
Não está usando o SMTP do próprio servidor.

Eu usava do Google por não ter SMTP da VPS.

**Comment by luizrn** [comment]
Olá, 

- primeiro, você verificou se este email "contato@phdevtech.com" é o mesmo que está nas configurações do mapos, em Emitente > se está o mesmo email?

- Segundo, a hostgator tem um serviço muito bom para smtp, chamada titan que é vinculado ao seu email, no caso, para usar esse serviço as configurações seriam:


![image](https://user-images.githubusercontent.com/10822915/163059914-7c86d6c0-447a-4e34-9c8a-9952f9b18b44.png)

**Comment by luizrn** [comment]
> Olá,
> 
> * primeiro, você verificou se este email "[contato@phdevtech.com](mailto:contato@phdevtech.com)" é o mesmo que está nas configurações do mapos, em Emitente > se está o mesmo email?
> * Segundo, a hostgator tem um serviço muito bom para smtp, chamada titan que é vinculado ao seu email, no caso, para usar esse serviço as configurações seriam:
> 
> ![image](https://user-images.githubusercontent.com/10822915/163059914-7c86d6c0-447a-4e34-9c8a-9952f9b18b44.png)

Para mais informações do Titan https://support.titan.email/hc/en-us/articles/900000215446

**Comment by IRAKE** [comment]
Realmente, só consegui resolver o problema do envio do email quando contratei o servidor de email titan
