### ISSUE TITLE
Integração Mercado Pago não Funciona

### ISSUE THREAD

**Issue by rodrigobg** [RamonSilva20/mapos#1755]
Olá tudo bem?
Percebi que vocês removeram a integração via painel do MercadoPago porém colocaram a integração 
via arquivo. Cadastrei meu access token, meu client_ID, client_secret, public_key corretamente. 

Porém na hora de gerar o boleto está dando este erro: 
![image](https://user-images.githubusercontent.com/16972000/162368876-cd221164-ffcc-4d41-a6df-aa3dc355ccc9.png)

Alguém sabe como resolver?

**Comment by Pr3d4dor** [comment]
@rodrigobg Você pegou o token de prod ou sandbox?

**Comment by luizrn** [comment]
@rodrigobg  caso ajude, dê uma olhada neste vídeo do próprio mercado pago https://youtu.be/OprvmiFXmWM

**Comment by rodrigobg** [comment]
Vlw pessoal, eu usei o token do aplicativo, mas não roda. Tem que ser o token direto da conta. Uma coisa que percebi ele só gera o boleto quando você adiciona um produto na OS, quando adiciona serviços ele não funciona. pode ser algum bug. não sei.

**Comment by rodrigobg** [comment]
Vlw pessoal, eu usei o token do aplicativo, mas não roda. Tem que ser o token direto da conta. Uma coisa que percebi ele só gera o boleto quando você adiciona um produto na OS, quando adiciona serviços ele não funciona. pode ser algum bug. não sei.
