### ISSUE TITLE
Erro ao imprimir

### ISSUE THREAD

**Issue by clickvirtual** [RamonSilva20/mapos#176]
Como realizar a impressão dos relatórios em um ambiente com PHP 5.6 ou 7? Ocorre o erro abaixo:
`An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected 'else' (T_ELSE)

Filename: D:\xampp\htdocs\mapos\application\helpers\mpdf\mpdf.php

Line Number: 33096`

Obrigado.

**Comment by dokti** [comment]
Olá pessoal, mesmo erro comigo. Alguém sabe como solucionar?

**Comment by Pr3d4dor** [comment]
Excluam a pasta application/helpers/mpdf/ e baixem novamente o mpdf versão 6.0 ou 6.1 em: https://github.com/mpdf/mpdf/releases?after=v6.1.1(source code zip)

Façam a extração do zip, renomeiem a pasta extraída para mpdf e coloquem no mesmo lugar da pasta excluída: application/helpers/
