### ISSUE TITLE
Erro ao importar BASE

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1762]
Fiz a atualização para a ultima versão, que tem o desconto na OS, porem ao importar a base apresenta esse erro.
estou usando a versão nova mas sem a opção de desconto atualmente 4.37.0, 
fiz uma instalação limpa com essa versão que tem o desconto mas sem chance de funcionar.
 já tentei de tudo ao meu alcance. 
parece incompatibilidade das bases.

![erro](https://user-images.githubusercontent.com/72340074/162861892-b0d9036e-9ca5-4d49-89dc-9a05559a8ef8.png)

**Comment by luizrn** [comment]
me parece ser problema com o banco de dados por estar faltando alguma tabela ou coluna, ao importar dnv seus antigos dados, talvez possa ter alterado algum nome do banco ou removido, para testar se é esse o problema, faça uma instalação limpa novamente, mas antes de importar seus dados, teste o sistema e ve se apresenta o mesmo erro, se não der nenhum erro, o problema foi a importação do antigo banco de dados, ai eu sugiro que você faça novamente a exportação dos dados mas exporte somente os dados e nao a estrutura do banco de dados. Por favor caso tenha resolvido seu problema, não esqueça de voltar aqui e nos dizer para que seja fechado o issue. Obg

**Comment by jsfachini** [comment]
Bom dia @luizrn então fiz esse teste, com o sistema limpo funciona normal, mas importando a base não vai, e me parece que é algo com as novas funções de desconto, se importo a base com a pagina do sistema aberta ele ate funciona mas ao entrar no menu home ou financeiro, apresenta esse erro da imagem.

Com a versão sem a opção de desconto esta funcionando 100% nunca tive problemas na importação dos dados.

**Comment by Pr3d4dor** [comment]
@jsfachini Mesmo depois de importar a base você precisa atualizar as tabelas por conta dos novos campos. Usando os .sql da pasta updates ou por dentro do sistema.
