### ISSUE TITLE
A pagina de relatórios da erro.

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1765]
** Descreva o bug **
Relatórios não exibem a pagina, apenas apresentam a pagina de erro.

![tela de erro](https://user-images.githubusercontent.com/71839236/163419988-eb6642ee-a692-40cc-a7ed-ccb15509f474.png)

**Comment by jsfachini** [comment]
@p-francelino faz o update da logo novamente lá em EMITENTE

**Comment by p-francelino** [comment]
Fiz o update da logo, mais o erro continuou.

**Comment by luizrn** [comment]
> ** Descreva o bug ** Relatórios não exibem a pagina, apenas apresentam a pagina de erro.
> 
> ![tela de erro](https://user-images.githubusercontent.com/71839236/163419988-eb6642ee-a692-40cc-a7ed-ccb15509f474.png)

tentou com outra imagem?

**Comment by p-francelino** [comment]
Resolvido, o problema estava na na imagem, ou mais precisamente no perfil de cores sRGB. Salvei a imagem sem o perfil e os relatórios abriram normalmente.
