### ISSUE TITLE
Adicionar campo NCM (código de Produtos)

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#1766]
Olá
Sinto falta do campo NCM na parte de produtos, ja vi esse campo em outros programas de Orçamentos.
![image](https://user-images.githubusercontent.com/60369684/163449765-b5167806-b207-4cea-bd80-94f7309adcf4.png)

Seria interessante esse campo no MAPOS também, e caso fosse possivel buscar o código no site do link abaixo:
https://portalunico.siscomex.gov.br/classif/#/sumario?perfil=publico

e na hora da impressão da OS sairia impresso tambem esse código do produto
![image](https://user-images.githubusercontent.com/60369684/163450675-8a8a9082-6cca-4ba7-87c9-0473b9cdd0c9.png)

**Comment by luizrn** [comment]
@cftvseginfo para fazer isso precisa de uma API que fornece isso, esse site que vc falou nao encontrei, é bem limitado, mas ao procurar no google encontrei este, https://figurafiscalws.com.br/v2.0/, e tem ja para outras coisas fiscais, parece ser de fácil integração.

**Comment by cftvseginfo** [comment]
> @cftvseginfo para fazer isso precisa de uma API que fornece isso, esse site que vc falou nao encontrei, é bem limitado, mas ao procurar no google encontrei este, https://figurafiscalws.com.br/v2.0/, e tem ja para outras coisas fiscais, parece ser de fácil integração.

Olhe a informação do site sobre integração nesse link
http://siscomex.gov.br/conheca-o-programa/como-se-integrar-ao-portal-unico-de-comercio-exterior/

**Comment by hoshikawakun** [comment]
oque seria esse NCM?

**Comment by cftvseginfo** [comment]
> oque seria esse NCM?

 é um código de oito dígitos, criado para facilitar a identificação mercadorias comercializadas.
o código correspondente precisa constar na nota fiscal referente à transação.

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/167634800-504c47cb-b04d-4867-a5a1-e84a69192d52.png)

por exemplo
