### ISSUE TITLE
Relatório de OS não contabilizando

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1767]
O relatório de OS não esta contabilizando os valores das OS que não tem desconto na coluna **TOTAL COM DESCONTO**

![relatorio mapos](https://user-images.githubusercontent.com/72340074/163512949-409b55de-6105-49e6-96f9-04d3d3597b12.png)

**Comment by luizrn** [comment]
@willph ai vai ter que fazer com aquele metodo de calculo, em vez de pegar do campo 'valor_total' que é onde ta o valor total com desconto (porque vai vim gente com dados antigos que nao vao ter este campo), vai ter que fazer o calculo na hora na listagem tipo valor (campo do banco) - desconto (campo do banco) = Valor total com desconto, ai por esse calculo ali no valor total em vez de pegar o valor total la do banco de dados, elimina o problema de gente com dados antigos que nao tem este campo como é o caso dessa issue.
