### ISSUE TITLE
Relatório financeiro não descontou o valor de compra do valor final.

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1770]
Boa noite pessoal, primeiro quero dizer que depois que conheci o MAPOS, não usei mais outro programa para gerencia meus serviços.
Então entendo que tudo que e reportado aqui, acaba sendo uma forma dos desenvolvedores irem aperfeiçoando o programa.
Eu percebi isso agora, não lembro se havia visto isso nas versões anteriores, bem eu coloquei a imagem como exemplo daquilo que quero mostrar.
A receita não deveria ser 660,00, porque o produto tem o valor de compra de 250,00.
Então a receita deveria ser de R$ 410,00, descontando do valor final o 250,00 do valor de compra do produto?
![erro](https://user-images.githubusercontent.com/71839236/163693333-984ce086-918e-4c56-a254-f65e0f628585.png)

**Comment by luizrn** [comment]
Olá, entendi oque quis dizer, este relatório é para te mostrar os valores dos produtos que foram vendidos com o valor de venda deles, se oque vc quer saber é o seu lucro por produto, o relatorio de Produtos mostra isso, oque poderia ser feito, é neste relatório de produtos adicionar uma nova coluna com nome "Lucro" que faz o cálculo do valor de vendas - valor de compra, q seria o seu lucro naquele produto, pode estar adicionando a tag Request feature, isso nao é bug.

**Comment by p-francelino** [comment]
Entendo, mais não entendo porque na pagina principal onde mostra o balança anual e o valor correspondente a cada mês aparece a valor referente ao ao preço final sem o desconto do valor inicial?
Eu sou estou tentando entender, penso que seria interessante, que a cada mês mostrasse o valor real de lucro, entendeu.

**Comment by luizrn** [comment]
mas vale ressaltar que esse relatorio que falei é so dos seus produtos em estoque e não dos produtos vendidos, talves seria mais util fazer oque falei no relatório de OS.
Ignora: (Mas so para deixar registrado aqui, se tratando da parte de programação, teria ao adicionar os produtos na OS incluir em hidden o valor de compra de cada produto,ai em hidden tbm soma o valor total dos produtos - o valor de compra = lucro, ai salva este valor no banco chamado "valor_produtos_lucro_bruto" ai ao faturar pega este campo e subtrai com o valor de desconto , salvar tbm no banco esse calculo com o nome "valor_produtos_lucro_liquido", ai no financeiro da pra por uma coluna pra exibir isso e tbm em relatórios, essa é a lógica que pensei, pode talves ser melhorada ou feita de outro jeito.)

**Comment by p-francelino** [comment]
Não sei se consegui ser claro quanto ao que estou tentando mostrar, talvez na imagem consigo explicar melhor
![ERRO 2](https://user-images.githubusercontent.com/71839236/163719396-27d1e5a1-538f-462e-ba86-192a8c75a9c8.png)
.

**Comment by luizrn** [comment]
sim deu de entender perfeitamente, mas como eu disse, não é bug, mas provavelmente uma atualização futura, a logica é meia complicada, já que esses gráficos são do financeiro, e como vc pode perceber quando vc fatura uma venda ou OS, só é levado para o financeiros os valores finais e nome, nada de detalhes dos produtos como preço de compra, ai na parte que mencionei acima, em "ignorar" seria uma logica de programação pra implementar isso, só não é feito agora esses cálculos mesmo, por isso poderia adicionar a tag Request feature nesta issue.
