### ISSUE TITLE
Erro depois de atualizar para a versão 4.37.0

### ISSUE THREAD

**Issue by MarlonJPA** [RamonSilva20/mapos#1775]
Após atualizar da versão 4.36.x para a versão 4.37.0 manualmente, recebi este erro. Não consigo mais acessar a dashboard.

![image](https://user-images.githubusercontent.com/104098355/164305713-c36cd239-1de5-49bc-8f93-bfe5f9e13b7d.png)

**Comment by MarlonJPA** [comment]
Fiz o procedimento para regredir com meu backup de pasta na versão 4.36.x, que apresentou o mesmo erro. Então busquei um backup mais antigo de pasta que estava na 4.35.2 e consegui reabrir o sistema, graças a Deus Pai kkk.
Estou me inteirando mais acerca do Mapos pois quero começar a contribuir.

Ficarei no aguardo do que fazer, não quero fazer melada aqui.

**Comment by willph** [comment]
https://youtu.be/7DBZsY3WGmc

Lá para os 10:50
Mais ou menos isso
Acho que vai te ajudar resolver isso

**Comment by marllonferreira** [comment]
da uma olhada nesse video

https://youtu.be/7DBZsY3WGmc

**Comment by alanpereiracoelho** [comment]
@MarlonJPA Versão do php aqui com versão 8.0 deu o mesmo erro.

**Comment by willph** [comment]
> @MarlonJPA Versão do php aqui com versão 8.0 deu o mesmo erro.

Tem que ser php 7.4.xx 

Php 8 o mapos ainda não tem suporte por enquanto.
