### ISSUE TITLE
Data de pagamento para emissão de cobranças

### ISSUE THREAD

**Issue by metalfox** [RamonSilva20/mapos#1784]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.
--- Gostaria se possível, de um campo para lançamento dos  vencimentos para os boletos, pensei em algo que pegasse direto da elaboração da O.S,  ou até mesmo durante a emisão do boleto (Pop Up) , um campo do tipo caledário para que pudessemos escolher a data de vencimento dos mesmos.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

-
Tentei algo aqui, mais não deu certo.
![image](https://user-images.githubusercontent.com/814764/165965192-b80d732d-b62a-400b-9f7f-eada043827c4.png)

Poderia pegar deste campo durante a emissão da O.S
![image](https://user-images.githubusercontent.com/814764/165965391-e1b6d6e6-071e-473e-bbba-c6c585b724ae.png)

Ou um campo com calendário para validar o vencimento do mesmo no pop up
![image](https://user-images.githubusercontent.com/814764/165965581-d7e9a3db-80ce-4a80-9c9e-a22814279b15.png)

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by lukasabino** [comment]
Opa! Estou atuando nisso, já tá passando para boleto no Asaas, que é o Gateway que eu uso até então.

Qual métodos de pagamento que usa ou que gostaria que tivesse essa opção?!

**Comment by metalfox** [comment]
Primeiramente obrigado pelo feedback, estou usando o gerencianet, gostaria muito que tivesse essa opção neste método de pagamento, obrigado.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lukasabino** [comment]
Show! 

Vou tentar aplicar tal alteração para ele também, como não tenho mais acesso a uma conta Gerencianet, não seria possível eu realizar esta homologação.

**Comment by metalfox** [comment]
Obrigado de vdd.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jhsolucoes** [comment]
Boa tarde pessoal. Alguma noticia de como colocar a data de vencimento do boleto, tanto no Asaas quanto no Mercado Pago?
