### ISSUE TITLE
TESTE BRANCH feature/suporte-php-8.0-e-8.1.

### ISSUE THREAD

**Issue by eliabeclayton** [RamonSilva20/mapos#1790]
** Ao acessar o mapos pelo navegador entra direto sem aparecer a tela login [RESOLVIDO]https://github.com/RamonSilva20/mapos/commit/758416eeb55c7c3bf599356617371264f1ed265c**
![login entra direto](https://user-images.githubusercontent.com/53370621/166176207-fc3ff872-379f-4a9c-a353-34db36421ae0.jpg)

** Ao clicar na 'área do cliente' para aparecer a tela login dá esse erro**
![login area cliente](https://user-images.githubusercontent.com/53370621/166176090-f0dc4a7d-4d56-4300-95ea-c1e1c3cd2879.jpg)

** erro ao adicionar OS, aparece o erro mas a OS é gravada no banco de dados e também aparece no sistema com as informações em formatação de código html [RESOLVIDO]https://github.com/RamonSilva20/mapos/commit/758416eeb55c7c3bf599356617371264f1ed265c**
![adicionar os](https://user-images.githubusercontent.com/53370621/166174941-d3e4cd3b-ba5c-4018-b5cc-99327e6cbb44.jpg)
![bd os](https://user-images.githubusercontent.com/53370621/166176379-421f827a-daf9-4421-887b-376d02f8b322.jpg)
![agenda click os](https://user-images.githubusercontent.com/53370621/166175406-0729a21a-7d04-4fb3-8596-3c76dbf0afe5.jpg)
![status click os](https://user-images.githubusercontent.com/53370621/166175413-323f9305-fabe-4b75-b8f8-f77c2fe4f37c.jpg)

** erro ao tentar excluir a OS direto no sistema, somente pelo bando de dados **
![erro excluir os](https://user-images.githubusercontent.com/53370621/166175560-cadb734c-98a2-47a4-916d-912b84065c16.jpg)
![erro 2 excluir os](https://user-images.githubusercontent.com/53370621/166390941-255dbdfe-fb22-43d4-8442-29cf4f466caf.jpg)

 **OBS.: AO TENTAR EDITAR E ATUALIZAR A Ordem de Serviço DIRETO NO SISTEMA DÁ O MESMO ERRO DE ADICIONAR OS, SOMENTE PELO BANDO DE DADOS [RESOLVIDO]https://github.com/RamonSilva20/mapos/commit/758416eeb55c7c3bf599356617371264f1ed265c**

 **QUASE TODOS OS PROBLEMAS MENSIONAOS ACIMA JA RESOLVIDO PELO https://github.com/RamonSilva20/mapos/commit/758416eeb55c7c3bf599356617371264f1ed265c**

**Comment by marllonferreira** [comment]
Nos teste tava usando uma instalação limpa ou ta usando backup do banco?

**Comment by eliabeclayton** [comment]
Instalação limpa....

**Comment by marllonferreira** [comment]
Eu tive resultado bem diferente

Amanhã vou fazer os teste

**Comment by willph** [comment]
Cadastrou o emitente?

Acredito que o erro da foto 3 seja a falta do emitente

**Comment by eliabeclayton** [comment]
> Cadastrou o emitente?
> 
> Acredito que o erro da foto 3 seja a falta do emitente

Vou cadastrar o emitente, pra ver se resolve..

**Comment by eliabeclayton** [comment]
> Cadastrou o emitente?
> 
> Acredito que o erro da foto 3 seja a falta do emitente

acabei de cadastrar o emitente, e realmente não apareceu mais o erro ao cadastrar OS.

**Comment by eliabeclayton** [comment]
Depois de faturar a OS, ao clickar em 'ordens de serviço':
![IMG_20220502_193103.jpg](https://user-images.githubusercontent.com/53370621/166337797-c2c3c2fc-a3ca-4d71-b7b5-7046f8fd6343.jpg)

 aparece esse erro:
![IMG_20220502_193211.jpg](https://user-images.githubusercontent.com/53370621/166337824-5c35abbd-50fa-462e-bdac-37f99dda2084.jpg)

Para continuar a testar o menu seção de OS, tive que mudar o valor 1 para 0 da coluna 'faturados' na tabla 'OS' no banco de dados do mapos.
![IMG_20220502_193812.jpg](https://user-images.githubusercontent.com/53370621/166338271-07352be0-2e35-4047-bf91-60602a00ad22.jpg)

**Comment by eliabeclayton** [comment]
Depois de faturar a OS, ao clickar em 'ordens de serviço':
![IMG_20220502_193103.jpg](https://user-images.githubusercontent.com/53370621/166337797-c2c3c2fc-a3ca-4d71-b7b5-7046f8fd6343.jpg)

 aparece esse erro:
![IMG_20220502_193211.jpg](https://user-images.githubusercontent.com/53370621/166337824-5c35abbd-50fa-462e-bdac-37f99dda2084.jpg)

Para continuar a testar o menu seção de OS, tive que mudar o valor 1 para 0 da coluna 'faturados' na tabla 'OS' no banco de dados do mapos.
![IMG_20220502_193812.jpg](https://user-images.githubusercontent.com/53370621/166338271-07352be0-2e35-4047-bf91-60602a00ad22.jpg)

E apagar a informações da tabla 'lancamentos', referente a OS.

**Comment by eliabeclayton** [comment]
**Também aparece essa mensagem de falha ao buscar OS no calendário, ( se não tiver nenhuma OS cadastrada).**  
![falha ao buscar os agenda](https://user-images.githubusercontent.com/53370621/166341047-056b57a0-0d88-4496-8649-91c6bf83bc0e.jpeg)

**Comment by willph** [comment]
> **Também aparece essa mensagem de falha ao buscar OS no calendário, ( se não tiver nenhuma OS cadastrada).** ![falha ao buscar os agenda](https://user-images.githubusercontent.com/53370621/166341047-056b57a0-0d88-4496-8649-91c6bf83bc0e.jpeg)
> 
> obs.: antes que me cobram direitos autorais da foto, confesso que fiquei com preeeguiiçaaa de tirar a foto e peguei a foto da insue do nosso amigo [marllonferreira](https://github.com/marllonferreira), kkkkkkk

Esse erro já foi corrigido. 

Baixar o branch atual

**Comment by eliabeclayton** [comment]
> **bém aparece essa mensagem de falha ao buscar OS no calendário, ( se não tiver nenhuma OS cadastrada).**

**Comment by eliabeclayton** [comment]
fechei a inssue sem querer...

**Comment by eliabeclayton** [comment]
**Ao dar o desconto em 'VENDAS' no campo total com desconto aparece NaN, e nao aparece o desconto mesmo clicando em 'aplicar' e  aparecendo a mensagem, Desconto adicionado com sucesso!**

![Captura da Web_2-5-2022_21651_mapos me](https://user-images.githubusercontent.com/53370621/166345292-f1bd70cf-405d-4b73-853b-ffd18c81e7e3.jpeg)

**Comment by Pr3d4dor** [comment]
@eliabeclayton Não consegui reproduzir nenhum desses problemas, parece que você está usando a versão errada, tanto que está aparecendo 4.38.0 ali em baixo.

**Comment by eliabeclayton** [comment]
> @eliabeclayton Não consegui reproduzir nenhum desses problemas, parece que você está usando a versão errada, tanto que está aparecendo 4.38.0 ali em baixo.

Estou usando a versão que o @willph me passou pelo whats no grupo --> Branche
- https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (Testar no PHP 8.0 e PHP 8.1, incluido a correção dos bugs do branch fix/bugs). mas eu consegui resolver quase todos os erros copiando as modificações que você fez em --> https://github.com/RamonSilva20/mapos/commit/758416eeb55c7c3bf599356617371264f1ed265c

**Comment by marllonferreira** [comment]
Já testei os bugs de referem a calendário Os e Os foram corrigidos

Ficando a penas as antigas 
Calendário em vendas e inadimplência
No balanço mensal do ano

**Comment by eliabeclayton** [comment]
> 

@marllonferreira eu acabei de testar a nova branch [php-8.0-e-8.1] com os erros corrigidos]  tudo ok, com exceção  a tela de login cliente que agora até entra na tela, mas não entra e aparece um erro, e excluir uma OS também ainda esta dando erro e Você também testou esses 2 fatores?

**Comment by marllonferreira** [comment]
![20220502_233236.jpg](https://user-images.githubusercontent.com/31580600/166396555-5a9b122b-a0f6-4e6a-8d86-f80aaef56197.jpg)

Realmente área do cliente ta dando erro

**Comment by marllonferreira** [comment]
![20220502_233436.jpg](https://user-images.githubusercontent.com/31580600/166396713-0f3e9b60-4612-4738-bb10-ee3391078b0c.jpg)


Excluir os  assim como excluir vendas estão dando erro

**Comment by eliabeclayton** [comment]
> 

> ![20220502_233236.jpg](https://user-images.githubusercontent.com/31580600/166396555-5a9b122b-a0f6-4e6a-8d86-f80aaef56197.jpg)
> 
> Realmente área do cliente ta dando erro

esse erro resolve substituindo a linha 57 por essa  `<img src="<?php echo base_url() ?>assets/img/logo-mapos-branco.png">` só entra a tela de login e logo o mesmo erro acima mencionado...

**Comment by willph** [comment]
> > 
> 
> > ![20220502_233236.jpg](https://user-images.githubusercontent.com/31580600/166396555-5a9b122b-a0f6-4e6a-8d86-f80aaef56197.jpg)
> > Realmente área do cliente ta dando erro
> 
> esse erro resolve substituindo a linha 57 por essa `<img src="<?php echo base_url() ?>assets/img/logo-mapos-branco.png">` só entra a tela de login e logo o mesmo erro acima mencionado... ---> [#1790 (comment)](https://github.com/RamonSilva20/mapos/issues/1790#issuecomment-1115553492)

Enviei na área administrativa e esquece da área do cliente.

**Comment by willph** [comment]
Vou baixar o branch do php8/8.1 porque estava testando o 7.4 ai esta ok

**Comment by willph** [comment]
Por favor baixar novamente pra vê se corrigiu alguns dos bugs mencionados. 

Tô corrigindo.

**Comment by eliabeclayton** [comment]
> Por favor baixar novamente pra vê se corrigiu alguns dos bugs mencionados.
> 
> Tô corrigindo.

### **acabei de testar a area de login cliente funcionou está Ok, mas excluir OS ainda esta dando erro**

**Comment by eliabeclayton** [comment]
> ![20220502_233436.jpg](https://user-images.githubusercontent.com/31580600/166396713-0f3e9b60-4612-4738-bb10-ee3391078b0c.jpg)
> 
> **Excluir os**
> 
> assim como
> 
> **excluir vendas**
> 
> estão dando erro

 [ERRO CORRIGIDO]. por @willph em ---> **OS**https://github.com/RamonSilva20/mapos/commit/82f180cec5c18d1c0f6b0fda5c175d1b98155ac3 **VENDAS**https://github.com/RamonSilva20/mapos/commit/df0c1a53449722073e4e80556bd23d6c31f33b5c

**Comment by willph** [comment]
> > ![20220502_233436.jpg](https://user-images.githubusercontent.com/31580600/166396713-0f3e9b60-4612-4738-bb10-ee3391078b0c.jpg)
> > **Excluir os**
> > assim como
> > **excluir vendas**
> > estão dando erro
> > @marllonferreira  [ERRO CORRIGIDO]. por @willph em ---> **OS**[82f180c](https://github.com/RamonSilva20/mapos/commit/82f180cec5c18d1c0f6b0fda5c175d1b98155ac3) **VENDAS**[df0c1a5](https://github.com/RamonSilva20/mapos/commit/df0c1a53449722073e4e80556bd23d6c31f33b5c)

O seu está dando erro, mesmo após ter atualizado o código?

**Comment by eliabeclayton** [comment]
> após as correções não esta mais dando erro no código, somente alguns conflitos em Permissões: 
em Configurações > Permissões: 
ao adicionar configurar a permissão em 'Configurações e Sistema'  e marcar somente a opção de Configurar Usuário, e 
e clicka no botão Confirmar. Até ai tudo bem o problema é que o usuário que estiver com essa configuração de permissão quando ele for em > mapos/minhaConta, para alterar a sua foto de usuário aparece a  mensagem > 'Falha!
Você não tem permissão para configurar emitente', e não atualiza a foto de perfil do usuário. que ao meu ver, esta mensagem não tem nada que ver com a configuração de 'emitente'. a foto só atualiza se em 'Configurações e Sistema' também marcado  a opção de 'Configurar Emitente' também.

**FOTO DA SEQUENCIA 01**
![01](https://user-images.githubusercontent.com/53370621/166746186-171cd1a0-b3f3-4728-b098-0dff0c1618eb.jpg)

**FOTO DA SEQUENCIA 02**
![02](https://user-images.githubusercontent.com/53370621/166746199-5218cc7f-1dd2-4917-8ee5-a1fcfe30742e.jpg)

**FOTO DA SEQUENCIA 03**
![03](https://user-images.githubusercontent.com/53370621/166746226-46e822bf-5667-43cc-926f-a24df44b7d43.jpg)

**FOTO DA SEQUENCIA 04**
![04](https://user-images.githubusercontent.com/53370621/166746265-35abbb16-15c5-4d49-854d-d22e63c5465c.jpg)

**FOTO DA SEQUENCIA 05**
![05](https://user-images.githubusercontent.com/53370621/166746287-aae00ac0-f80a-40a5-b018-0d25f40b4012.jpg)

**FOTO DA SEQUENCIA 06**
![06](https://user-images.githubusercontent.com/53370621/166746313-a764fbc5-e34a-448e-9fd6-ae5b35a0eed6.jpg)

**Comment by willph** [comment]
irei analisar esse da foto

**Comment by willph** [comment]
Por favor refazer o teste, para analisar se esta ok agora.
Upload de imagem do usuario.

Lembrando que precisa atualizar o codigo

**Comment by eliabeclayton** [comment]
@willph, Refiz o teste e o problema de upload de imagem do usuário foi solucionado...

**Comment by eliabeclayton** [comment]
@willph , fecho a inssue ou aguardo até a o lançamento da nova versão?

**Comment by willph** [comment]
Aguarda, vai que apareça mais bugs.

Quando sair a versão oficial, aí só fechar

**Comment by eliabeclayton** [comment]
> 

OK.
