### ISSUE TITLE
Desconto em % tanto na Ordem de Serviço quanto na Venda é contabilizado como R$ em Lançamentos

### ISSUE THREAD

**Issue by nakoniev** [RamonSilva20/mapos#1791]
O sistema é muito bom, os desenvolvedores estão de parabéns! 
Estou relatando esse bug, creio que mais pessoas estejam passando pelo mesmo problema. A versão do Map-OS é a última lançada.

**Segue descrição do bug:**

Aqui eu adiciono o desconto em %, nesse exemplo 20% _(Teste realizado tanto na Ordem de Serviço quanto na venda)_:
![Tela01](https://user-images.githubusercontent.com/67238082/166178220-7a0b659b-edb6-4264-b6fe-fa78e3faa272.PNG)

Vou em faturar e até aí tudo ok, o desconto aparece com o valor correto:
![Tela02](https://user-images.githubusercontent.com/67238082/166178223-2226c780-a721-488c-8a09-2082ce76238f.PNG)

Porém na tela de lançamentos o desconto é contabilizado como sendo -R$ 20,00 e não -20%, tornando o valor total completamente diferente do faturado com desconto:
![Tela03](https://user-images.githubusercontent.com/67238082/166178597-838f50c3-00b9-41d9-9c14-e27662c8b6f8.PNG)

_Gostaria de saber como posso solucionar. Grato!_

**Comment by willph** [comment]
Baixou o branch por completo?

O seu financeiro não está igual ao meu.

**Comment by marllonferreira** [comment]
A versão dele  ainda está com PR do Luiz

Preciso baixá novamente

**Comment by jsfachini** [comment]
aqui aconteceu o mesmo @willph versão 4.38 limpa instalada

**Comment by willph** [comment]
Branches
- https://github.com/RamonSilva20/mapos/tree/fix/bugs (Testar no PHP 7.4)
- https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (Testar no PHP 8.0 e PHP 8.1, inclui a correção dos bugs do branch fix/bugs)

Esses são os Branch para testar.

**Comment by nakoniev** [comment]
Fiz os procedimentos em nova instalação, testei e funcionou. Porém quando vou em sistema e atualizar Map-OS ele volta na versão que estava com falha.

**Comment by nakoniev** [comment]
Refiz todos os procedimentos novamente, instalei o Map-OS do Branche [https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1](https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1) na versão 8.0 ou 8.1 do PHP, e ocorre o seguinte erro ao acessar a área do cliente:

![Erro Area do Cliente](https://user-images.githubusercontent.com/67238082/166335627-2dab5dfe-5a75-4661-a639-693d880968f2.PNG)

Só volta a funcionar se colocar na versão 7.4

**Comment by Pr3d4dor** [comment]
@nakoniev Algo me diz que vc ainda está usando a versão incorreta, pois esse erro já foi corrigido.

**Comment by nakoniev** [comment]
@Pr3d4dor em qual branch essas falhas foram corrigidas? tanto a do primeiro bug do desconto quanto o da área de cliente no php >=8.0? se eu atualizar através do próprio Map-OS vai pegar a versão certa agora?

**Comment by marllonferreira** [comment]
![20220502_231156.jpg](https://user-images.githubusercontent.com/31580600/166395699-01ee1fcf-f4d9-4604-bd07-a4ead42f7223.jpg)

**Comment by marllonferreira** [comment]
> @Pr3d4dor em qual branch essas falhas foram corrigidas? tanto a do primeiro bug do desconto quanto o da área de cliente no php >=8.0? se eu atualizar através do próprio Map-OS vai pegar a versão certa agora?
> 
> 

Deve baixar do principal 

https://github.com/RamonSilva20/mapos

master

**Comment by marllonferreira** [comment]
> @Pr3d4dor em qual branch essas falhas foram corrigidas? tanto a do primeiro bug do desconto quanto o da área de cliente no php >=8.0? se eu atualizar através do próprio Map-OS vai pegar a versão certa agora?

o que aconteceu foi que a PR onde estava o desconto em real nao foi aprovada e a PR do lamcamento q vc ta usando foi revertida.

**Comment by marllonferreira** [comment]
> Fiz os procedimentos em nova instalação, testei e funcionou. Porém quando vou em sistema e atualizar Map-OS ele volta na versão que estava com falha.

a atualização pelo sistema nao funciona muito bem, recomendado quando necessario atualizar de forma manual para evitar erros

**Comment by nakoniev** [comment]
@marllonferreira fiz uma instalação limpa do ramo master sem atualizar nada via sistema e mesmo assim o problema do desconto em % virar R$ retorna.

**Comment by nakoniev** [comment]
@willph qual é o branch correto para baixar com todos esses bugs corrigidos? no ramo master como o @marllonferreira mencionou não resolveu e eu também gostaria de sempre poder atualizar o Map-OS pelo próprio sistema já que ele tem essa funcionalidade. Grato!

**Comment by jsfachini** [comment]
@marllonferreira @willph https://github.com/RamonSilva20/mapos (master) esta na PR do Luiz, baixei e fiz uma nova instalação limpa para testar, os descontos em % são subtraídos em Real

![desc](https://user-images.githubusercontent.com/72340074/166556466-26c6c404-5da8-4ec8-b1e0-7374120d6346.png)

**Comment by willph** [comment]
> @willph qual é o branch correto para baixar com todos esses bugs corrigidos? no ramo master como o @marllonferreira mencionou não resolveu e eu também gostaria de sempre poder atualizar o Map-OS pelo próprio sistema já que ele tem essa funcionalidade. Grato!

Branches

- https://github.com/RamonSilva20/mapos/tree/fix/bugs (Testar no PHP 7.4)
 
- https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (Testar no PHP 8.0 e PHP 8.1, inclui a correção dos bugs do branch fix/bugs)

**Comment by marllonferreira** [comment]
> @marllonferreira @willph https://github.com/RamonSilva20/mapos (master) esta na PR do Luiz, baixei e fiz uma nova instalação limpa para testar, os descontos em % são subtraídos em Real
> 
> ![desc](https://user-images.githubusercontent.com/72340074/166556466-26c6c404-5da8-4ec8-b1e0-7374120d6346.png)
> 
> 
> 
>  
> 
> 

ja fez a limpeza o cache do seu navegador ?

**Comment by jsfachini** [comment]
@marllonferreira sim limpo, se baixarem a compilação do link acima, esta na PR do luiz, não é a mesma que o @willph forneceu no outro link e se atualizar pelo mapos vai baixar a do luiz novamente

**Comment by willph** [comment]
> @marllonferreira sim limpo, se baixarem a compilação do link acima, esta na PR do luiz, não é a mesma que o @willph forneceu no outro link e se atualizar pelo mapos vai baixar a do luiz novamente

quais os links que ainda consta as modificações mencionadas?

**Comment by jsfachini** [comment]
@willph do code principal do mapos, sempre baixei por lá https://github.com/RamonSilva20/mapos

![cod](https://user-images.githubusercontent.com/72340074/166559638-79c6ab3c-ac1b-4da1-a087-95aabf5a9c2d.png)

**Comment by willph** [comment]
> @willph do code principal do mapos, sempre baixei por lá https://github.com/RamonSilva20/mapos
> 
> ![cod](https://user-images.githubusercontent.com/72340074/166559638-79c6ab3c-ac1b-4da1-a087-95aabf5a9c2d.png)

Entendi agora.

O master parece que está ainda com a PR do Luiz. 

Você tem que alterar para os branchs que mencionei. 
Se usar o Master, realmente vai está assim do jeito que mencionou.

**Comment by willph** [comment]
Se usar o Github desktop é mais simples de ir alternando entre os Branch.

Via comando também da.

**Comment by jsfachini** [comment]
@willph Entendi, mas se voltar para essa Branch do seu link, não consta mais a forma de pagamento lá no lançamentos financeiros, as versões mais antigas tinham.

![sim](https://user-images.githubusercontent.com/72340074/166608175-7b27fef9-2ef5-45c9-9237-1383ed056d45.png)
