### ISSUE TITLE
( Faturamento ) não aparece forma de pagamento

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1792]
Antes tinha a opção de escolher a forma de pagamento ao faturar a OS
exemplo, nesse caso do print foi faturado com boleto para 15 dias
mas não tem mais a opção de escolher boleto...
lá no financeiro apare todos como dinheiro.
versão utilizada 4.38

para contornar essa falta, marco a caixa recebido, escolho boleto e desmarco a caixa, ai sim aparece no lançamento como boleto ou outra forma escolhida.

![FATURAMENTO](https://user-images.githubusercontent.com/72340074/166259525-f2550896-6ecf-4626-bfb5-7798c683a66f.png)

**Comment by jsfachini** [comment]
sim, mas não recebi o valor foi faturado e enviado a cobrança hj dia 2 mas o valor só vai ser recebido dia 16, lá no lançamento aparece como pago se eu marcar a caixa e faturar marcado, antes era só escolher a data da entrada e a forma de pagamento ai sim faturar, ficava pendente, cliente pagava e eu ia manual e colocava como pago. meu sistema de boleto não tem integração, por isso faço manual o pagamento no financeiro.

**Comment by willph** [comment]
> sim, mas não recebi o valor foi faturado e enviado a cobrança hj dia 2 mas o valor só vai ser recebido dia 16, lá no lançamento aparece como pago se eu marcar a caixa e faturar marcado, antes era só escolher a data da entrada e a forma de pagamento ai sim faturar, ficava pendente, cliente pagava e eu ia manual e colocava como pago. meu sistema de boleto não tem integração, por isso faço manual o pagamento no financeiro.

Entendi. 
Vou verificar.

**Comment by jsfachini** [comment]
@willph La em add. Receita/Despesa esta acontecendo o mesmo, não tem mais a opção de escolher a forma do pagamento, só se marcar a caixa escolher a forma e depois desmarcar.
faço a inclusão manual no financeiro quando a empresa tem muitas ordens e eles parcelam, 
ai lá no Status da O.S escolho faturado MANUAL nessas ordens e depois crio um faturamento de boleto parcelado.

![FINAN](https://user-images.githubusercontent.com/72340074/166340480-672b67d2-21b3-40db-9044-d7e488a15e97.png)

**Comment by willph** [comment]
> @willph La em add. Receita/Despesa esta acontecendo o mesmo, não tem mais a opção de escolher a forma do pagamento, só se marcar a caixa escolher a forma e depois desmarcar. faço a inclusão manual no financeiro quando a empresa tem muitas ordens e eles parcelam, ai lá no Status da O.S escolho faturado MANUAL nessas ordens e depois crio um faturamento de boleto parcelado.
> 
> detalhe, nesse caso foram parcelados em 2x dentro do mesmo mês, ai não posso escolher parcelado em **QTD Parcelas.**
> 
> ![FINAN](https://user-images.githubusercontent.com/72340074/166340480-672b67d2-21b3-40db-9044-d7e488a15e97.png)

Esse modal não é do Branch que eu mencionei.
Não me lembro de ter esse modal. 

Irei analisar pra vê

**Comment by jsfachini** [comment]
@willph não não esse é do sistema principal, nesse nem mexi.
no Branch que você mencionou testei a parte do % 

fiz uma instalação a parte para testar os novos recursos antes de aplicar no principal.
mas irei testar lá.

**Comment by jsfachini** [comment]
@willph Testei no Branch e realmente nesse funciona em partes, não precisa escolher a forma de pagamento ate porque ele não tem lá em **Lançamentos Financeiros** não aparece a forma de pagamento, que a meu ver é muito interessante ter, pra justamente saber a origem do pagamento, boleto, pix, cartão... 

**Com forma de pagamento:** 
![com form](https://user-images.githubusercontent.com/72340074/166344405-6b03c085-36a4-4a24-9dd9-79abf9819e81.png)


**Sem forma de pagamento:**
![sem form](https://user-images.githubusercontent.com/72340074/166344420-fad0f6da-07f5-4ddf-9ae8-5d259b67f2da.png)

**Comment by marllonferreira** [comment]
> > @willph La em add. Receita/Despesa esta acontecendo o mesmo, não tem mais a opção de escolher a forma do pagamento, só se marcar a caixa escolher a forma e depois desmarcar. faço a inclusão manual no financeiro quando a empresa tem muitas ordens e eles parcelam, ai lá no Status da O.S escolho faturado MANUAL nessas ordens e depois crio um faturamento de boleto parcelado.
> > 
> > detalhe, nesse caso foram parcelados em 2x dentro do mesmo mês, ai não posso escolher parcelado em **QTD Parcelas.**
> > 
> > ![FINAN](https://user-images.githubusercontent.com/72340074/166340480-672b67d2-21b3-40db-9044-d7e488a15e97.png)
> 
> Esse modal não é do Branch que eu mencionei.
> Não me lembro de ter esse modal. 
> 
> Irei analisar pra vê 

Esse é o da PR do Luiz

**Comment by jsfachini** [comment]
@marllonferreira É o último code oficial, o que atualiza por dentro do mapos, apesar de eu nunca atualiza lá por dentro, sem baixo a compilação oficial.
