### ISSUE TITLE
Botão "ver mais detalhes" dos Termos de Garantia retornando erro

### ISSUE THREAD

**Issue by nakoniev** [RamonSilva20/mapos#1798]
Ao clicar no botão "ver mais detalhes" em Termos de Garantia retorna o seguinte erro:

![Erro Garantia](https://user-images.githubusercontent.com/67238082/166830453-9480d653-e58e-4198-8aa7-716ea2e300e2.PNG)

**Etapas para reproduzir o comportamento:**
1. Vá para 'Termos de Garantia'
2. Clique em 'ver mais detalhes'
3. Ver erro

**Comportamento esperado:**
Ver detalhes do Termo de Garantia.

**Branch utilizado:**
https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (versão mais recente)

**PHP:** 8.1

**Comment by willph** [comment]
Irei analisar

**Comment by eliabeclayton** [comment]
Eu também reproduzi o comportamento aqui e também retorna o mesmo erro...

**Comment by willph** [comment]
Corrigido, favor retestar, atualizando o código primeiro, 
Teste feito em php8/8.1

**Comment by nakoniev** [comment]
@willph problema resolvido. Deixarei a issue aberta por 1 dia caso alguém reporte algum outro bug relacionado.

**Comment by eliabeclayton** [comment]
Acabo de testar e o problema resolvido.
