### ISSUE TITLE
Dica: Centralizar Logo em seus campos.

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#18]

**Comment by michelfritsch** [comment]
Dica: Cabeçalho OS
Empresa
CNPJ
Rua Teste, nº:40, Bairro - Cidade - UF
 > Para >
Empresa
CNPJ
Rua Teste, 40 - Bairro - Cidade - UF

**Comment by RamonSilva20** [comment]
Olá. Segui sua sugestão e a atualização já está disponível. Grato.
