### ISSUE TITLE
Resultados exibidos por página não atualizam

### ISSUE THREAD

**Issue by nakoniev** [RamonSilva20/mapos#1802]
**Descrição do Bug:**
Ao selecionar a quantia de resultados exibidos por página, por exemplo, na área de Serviços que estão cadastrados. Só aparece 10 (padrão) de cada vez e a paginação, e se eu selecionar qualquer valor para ser exibido, como 50 por exemplo, não ocorre nada.

**Etapas para reproduzir o comportamento:**
1. Vá para 'Serviços'
2. Clique em 'Campo que seleciona quantia de dados exibidos (10, 25, 50 ou 100)'
3. Nada ocorre
Obs: Testei apenas na parte dos serviços, ainda não sei se em outras partes tem o mesmo comportamento pois não alimentei tantos dados nas outras.

**Comportamento esperado:**
Aumentar o número de dados exibidos.

**Branch utilizado:**
https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (versão mais recente)

**PHP:** 8.1

**Comment by willph** [comment]
> **Descrição do Bug:** Ao selecionar a quantia de resultados exibidos por página, por exemplo, na área de Serviços que estão cadastrados. Só aparece 10 (padrão) de cada vez e a paginação, e se eu selecionar qualquer valor para ser exibido, como 50 por exemplo, não ocorre nada.
> 
> **Etapas para reproduzir o comportamento:**
> 
>     1. Vá para 'Serviços'
> 
>     2. Clique em 'Campo que seleciona quantia de dados exibidos (10, 25, 50 ou 100)'
> 
>     3. Nada ocorre
>        Obs: Testei apenas na parte dos serviços, ainda não sei se em outras partes tem o mesmo comportamento pois não alimentei tantos dados nas outras.
> 
> 
> **Comportamento esperado:** Aumentar o número de dados exibidos.
> 
> **Branch utilizado:** https://github.com/RamonSilva20/mapos/tree/feature/suporte-php-8.0-e-8.1 (versão mais recente)
> 
> **PHP:** 8.1

Isso ocorre porque foi modificado e agora pode ser configurado em configurações>sistema

![image](https://user-images.githubusercontent.com/17226802/166842985-6daa87cf-fb63-40b0-b8b5-390780661125.png)


Ai com isso o sistema obedece o que esta configurado lá.

Agora se na configurações estiver para 100 e ai no select escolher 10, 50 ele reduz, mais se estiver configurado para 10 e selecionar 50, não ira funcionar

**Comment by nakoniev** [comment]
@willph funcionou. Obrigado!
