### ISSUE TITLE
Vendas a Vulso 

### ISSUE THREAD

**Issue by leolfgomes** [RamonSilva20/mapos#1804]
Boa noite pessoal, primeiramente início novamente parabenizando todos os envolvidos nesse projeto fantástico.
Minha dúvida/solicitação seria: é possível fazer vendas avulso, sem a necessidade de cadastrar o cliente, até se possível colocar o nome mais que essas não fosse obrigatório estar cadastrado?

**Comment by nakoniev** [comment]
Boa noite, uma sugestão é criar um cliente com o nome de Consumidor Final, sem dados adicionais. Assim você não precisa cadastrar clientes para cada venda avulsa. Estou usando dessa forma.

**Comment by leolfgomes** [comment]
@nakoniev Valeu pela dica.
