### ISSUE TITLE
Trabalhos Cron

### ISSUE THREAD

**Issue by JhonnMarvin** [RamonSilva20/mapos#1806]
Estou tendo dificuldade nos trabalhos Cron dentro do DirectAdmin
Alguém conseguiu trabalhar o Cron dentro do DirectAdmin?

**Comment by Pr3d4dor** [comment]
@JhonnMarvin Qual é o problema exatamente?

**Comment by JhonnMarvin** [comment]
@Pr3d4dor o e-mails não chegam ao seu destinatário... não consigo dizer precisamente se o erro é no DirectAdmin

**Comment by Pr3d4dor** [comment]
@JhonnMarvin É uma hospedagem específica ou local?
