### ISSUE TITLE
Erro em Atualização Error Call to a member function row() on bool

### ISSUE THREAD

**Issue by LuisFelipe97** [RamonSilva20/mapos#1808]
Call to a member function row() on bool

Após atualização via sistema o mesmo não entra, apresenta o erro, descrito.
Caso haja forma de pegar o banco de dados, eu tenho backup da pasta xampp, meu ultimo backup em SQL foi a um mês, ai eu faço a reinstalação.

![image](https://user-images.githubusercontent.com/105297418/167649517-b5e31281-80db-4d7a-a919-758c8da6bd7a.png)

Agradeço desde já.

**Comment by wesley020291** [comment]
Entra em seu phpmyadmin e salba seu banco de dados. depois apague tudo na rais dos arquivos e coloque tudo novo. faz todo procedimento de instalação e no banco de dados depois importe o salvo. vai fica zero

**Comment by MauricioEstudier** [comment]
Bom dia. Estou com o mesmo problema.
Fiz o backup do sql antes de atualizar, mas agora fica stuck, igual tela inicial do @LuisFelipe97 .
Consigo entrar no ' localhost/mapos/index.php/mapos/configurar ', mas permanece a versão anterior (4.35.2).

Senhas do banco e de login OK, arquivos config e database configurados.
Abre o login, mas ao validar, mesmo erro.

**Comment by LuisFelipe97** [comment]
Se alguém tiver a solução, como eu tinha o banco de dados desinstalei o Xampp apaguei a pasta e reinstalei tudo, na ultima versão continua dando erro tiver que instalar a 4.35.2 e importar o banco de dados para dar certo.

**Comment by MauricioEstudier** [comment]
Baixei novamente q a versão 4.35.2, sobrescrevi todos os arquivos, exceto config, e voltou ao normal


Maurício Estudier
(51)99374-5000
