### ISSUE TITLE
exibir valor da O.S e possibilitar a aceitação ou recusa do orçamento pela área cliente

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#181]
gente, gostaria de saber, como faço para que, nos detalhes da O.S exiba o valor do serviço inserido no sistema, e permitir aos clientes a aceitação ou recusa desta ordem de serviço
e como inserir o valor da O.S para que o cliente a consulte ?
e tenha uma noção.
se existe, como fazer essas duas coisas.
e se não existe, peço que implementem na próxima versão do mapOS as opções para que o cliente aceite ou recuse uma ordem de serviço, atualizando o painel do técnico com a aceitação ou recusa por parte do cliente.
e como exibir o valor do serviço da O.S para que o cliente aceite ou recuse, para que ele já saiba o preço?
agradeço
por favor, implementem isso na próxima release do mapOS.

**Comment by edgarmeireles** [comment]
Gostei da ideia...
