### ISSUE TITLE
Adicionar dados nas vendas

### ISSUE THREAD

**Issue by eletroboy97** [RamonSilva20/mapos#1811]
Boa noite, 

em mapos\application\controllers\Vendas.php na linha 312 +

Tenho esse código:

        if ($this->form_validation->run() == false) {
            echo json_encode(['result' => false]);
        } else {
            $preco = $this->input->post('preco');
            $quantidade = $this->input->post('quantidade');
            $subtotal = $preco * $quantidade;
            $produto = $this->input->post('idProduto');
            
Queria adicionar uma nova entrada no banco de dados mas não sei de onde ele pega os dados input

Alguém pode me dizer de onde ele puxa esses dados para eu poder puxar o dado que eu quero?

**Comment by Pr3d4dor** [comment]
@eletroboy97 O que vc quer adicionar exatamente?
