### ISSUE TITLE
DUVIDAS SOBRE COBRANÇAS

### ISSUE THREAD

**Issue by wnjulio** [RamonSilva20/mapos#1821]
Ola pessoal, boa noite.

Como faço para emitir boleto nessa uiltima versao,  não estou encontrando a opcao e nem a parte de configuração.
fc apenas assim.
![image](https://user-images.githubusercontent.com/42722761/168728104-dbce5f82-26f1-48ad-b2e2-193412468ad5.png)

**Comment by lukasabino** [comment]
Olá! 

Para emitir cobranças, tem de se alterar o arquivo (https://github.com/RamonSilva20/mapos/tree/master/application/config)/payment_gateways.php

E inserir as credenciais de conexão com seu gateway preferencial (GerenciaNet, Asaas, Mercado Pago).

Após inserir as credenciais, será possível inserir as cobranças nas vendas/Ordens de serviços.

**Comment by wnjulio** [comment]
ah sim, muito obrigado parceiro.
