### ISSUE TITLE
Erro ao gerar Relatório -  imagecreatefromstring()

### ISSUE THREAD

**Issue by GabrielNubeli** [RamonSilva20/mapos#1825]
Sempre ao gerar relatório da o seguinte erro:
imagecreatefromstring(): gd-png: libpng warning: iCCP: known incorrect sRGB profile
![Capturar](https://user-images.githubusercontent.com/106108115/169883793-4656f14f-01ab-4e42-a4f5-005e08f1ec56.PNG)

**Comment by GabrielNubeli** [comment]
Sempre ao gerar relatório da o seguinte erro: imagecreatefromstring(): gd-png: libpng warning: iCCP: known incorrect sRGB profile ![Capturar](https://user-images.githubusercontent.com/106108115/169883793-4656f14f-01ab-4e42-a4f5-005e08f1ec56.PNG)

**Comment by cabralwms** [comment]
Parece ser o erro da imagem do emitente tenta atualizar a imagem do emitente e veja se corrige.
