### ISSUE TITLE
preciso de ajuda para configurar o boleto do mercado pago essas informaçoes não encontro:'integrator_id' => '',             'platform_id' => '',             'corporation_id' => ''

### ISSUE THREAD

**Issue by Naldotec** [RamonSilva20/mapos#1830]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by lukasabino** [comment]
Tem de fazer o cadastro na plataforma de desenvolvedor do Mercado Pago ([Clique aqui](https://www.mercadopago.com.br/developers/pt/reference).

Após realizar o cadastro, poderá criar um aplicativo na plataforma e coloca-lo em produção, assim vai ter a disposição as informações para colocar no Mapos!

**Comment by Naldotec** [comment]
Eu já criei só esses dados não consigo

Em dom, 29 de mai de 2022 19:06, Luka Sabino Carvalho <
***@***.***> escreveu:

**Comment by lukasabino** [comment]
Não consegue oq?!

Qualquer coisa me dá um toque no telegram que eu lhe ajudo, https://t.me/Lukasabino
