### ISSUE TITLE
Mpdf \ MpdfException (E_ERROR)

### ISSUE THREAD

**Issue by EltonAlexandre** [RamonSilva20/mapos#1832]
** Descreva o bug **
Erro ao gerar relatórios 
**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Relatórios'
2. Clique em 'ordem de serviço'
3. Role para baixo até '....'
4. Ver erro
Mpdf \ MpdfException (E_ERROR)
Temporary files directory "C:\xampp\htdocs\os\assets/uploads/temp//mpdf" is not writable
**Comportamento esperado**
Deveria ser gerado o relatório normalmente

** Capturas de tela **
![image](https://user-images.githubusercontent.com/90334991/171193539-32870e4f-427d-4e75-8cd2-c8ed7efd4bca.png)

** Desktop (preencha as seguintes informações): **
 - SO: w11 64 bits
 - Navegador Edge
 - Versão 4.37

**Comment by EltonAlexandre** [comment]
qual pasta??

**Comment by EltonAlexandre** [comment]
só prá deixar claro...eu faço um backup do mysqldmin...apago a pasta mapos e refaço a instalação e dá certo(já fiz isso 4 vezez)...do nada o windows mexe na nas permissões de pastas?!

**Comment by Pr3d4dor** [comment]
@EltonAlexandre Sim

**Comment by pcmsjr** [comment]
Eu apaguei o comando if que tá marcado no MpdfException e salvei o arquivo, após isso deu certo.
