### ISSUE TITLE
solicitação de idioma

### ISSUE THREAD

**Issue by ze3r0o** [RamonSilva20/mapos#1833]
Poderiam adicionar a função de mudar de idioma, inglês, espanhol, seria muito útil.

**Comment by Pr3d4dor** [comment]
@ze3r0o As "strings" estão fixas nas páginas HTML, não seria tão fácil implementar isso.

**Comment by ze3r0o** [comment]
> @ze3r0o As "strings" estão fixas nas páginas HTML, não seria tão fácil implementar isso.

Se eu puder fazer isso, haveria algum problema se eu fizer isso?

**Comment by Pr3d4dor** [comment]
@ze3r0o Pior que sem conhecimento de programação, não é tão fácil.
