### ISSUE TITLE
Bug ao salvar ou atualizar qualquer cadastro (Alguem Consegui Resolver?)

### ISSUE THREAD

**Issue by lmainformatica** [RamonSilva20/mapos#1835]
### Discussed in https://github.com/RamonSilva20/mapos/discussions/1747

<div type='discussions-op-text'>

<sup>Originally posted by **llucasrn** April  4, 2022</sup>
Fiz a instalação em um ubuntu server, ele rodo bem, porém na hora de salvar ou atualizar qualquer cadastro, sou redirecionado para a página atualizada, nesse momento ele duplica a url.

Ex. O caminho é meudominio.com/mapos/index.php/cliente

Quando clico em salvar ou atualizar fica:
Meudominio.com/mapos/meu domínio.com/mapos/index.php/cliente

E vai para um tela de erro de página não encontrada 404.

![Screenshot_20220404-202647.png](https://user-images.githubusercontent.com/35467331/161648708-773985ff-9800-48a6-90ee-f180f31496d9.png)

</div>

**Comment by lmainformatica** [comment]
consegui resolver o BUG de salvar vou mandar as telas.

**Comment by lmainformatica** [comment]
[](url
![Redirect estava no lugar errado do código tem que ficar nessa posição](https://user-images.githubusercontent.com/92346998/172085350-b0270508-aa8c-47ee-b028-dd61fd2743e3.png)
)

**Comment by lmainformatica** [comment]
como no exemplo alterei apenas "serviços" entao tem que ser alterado em todos os arquivos onde tem a opção de adicionar!!

**Comment by alanmartins096** [comment]
Edite seu arquivo config.php nas seguintes linhas, deixando assim:

$config['base_url'] = 'http://pcellnatal.ddns.net/system/mapos';

$config['index_page'] = 'index.php';

**Comment by edsonkozak** [comment]
Bom dia 

Estou passando pela mesma situação, qual foi a solução deste caso?

**Comment by alanmartins096** [comment]
> Bom dia
> 
> Estou passando pela mesma situação, qual foi a solução deste caso?

Testou o que eu escrevi acima ?
