### ISSUE TITLE
Gateway PIX em cobranças

### ISSUE THREAD

**Issue by paulohcgs1997** [RamonSilva20/mapos#1836]
gostaria de saber se e possível colocar um gateway PIX nas vendas aonde tem o botão criar cobrança pois assim a aba cobranças teria uma utilidade melhor.

agradeço o trabalho incrível que todo o time esta fazendo.

**Comment by RicharViera** [comment]
Olá, estou ultilizando a ultima versão e esta apresentando esse erro quando vai fazer o cadastro do pix pelo painel.
Alguém poderia auxiliar?
![image](https://user-images.githubusercontent.com/107273201/173127250-e1ef2672-898d-4d10-9a3a-b5afbc1ccc42.png)

**Comment by lukasabino** [comment]
@RicharViera esse erro é referente a chave pix não for valida, está tentando adicionar qual?!

Eu indico criar uma chave aleatória somente para isto.

**Comment by RicharViera** [comment]
Estava utilizando chave CNPJ, criei uma aleatória para ver se resolvia e o erro aparece.

![image](https://user-images.githubusercontent.com/107273201/174172247-66d14f87-5705-491a-9377-bce05ccc295c.png)

**Comment by Pr3d4dor** [comment]
@GGINFORSP @RicharViera @lukasabino Vcs precisam instalar as dependencias do composer.
