### ISSUE TITLE
Não consigo acessar após importação do banco.

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#1838]
** Descreva o bug **
Bom dia migrei hoje para a versão atual do mapos, realizei a instalação numa boa, entrei no sistema até ai tudo bem. No momento que importei o banco de dados ja não consegui mais acesso.

Recebo essa tela de erro
![erro](https://user-images.githubusercontent.com/71839236/172646887-9540361b-387b-455f-a3e1-36ccd3b3fecb.png)
.

**Comment by jsfachini** [comment]
Tenta isso, assim que importar abre a pagina localhost/NOMEDOMAPOS/index.php/mapos/configurar/  vai em atualizações e depois clica em atualizar banco.  faz o teste, entra em ordens de serviço e seja se da erro. 

obs: localhost caso esteja usando localmente, caso contrario usa o endereço do server
