### ISSUE TITLE
Problema com instalação falta extensão GD

### ISSUE THREAD

**Issue by LouanJuliels** [RamonSilva20/mapos#1839]
Descrição do bug
Fiz toda instalação seguindo tutorial depois de um problema no windows porem não consigo reinstalar o mapos diz que falta a extensão GD

![image](https://user-images.githubusercontent.com/82371113/172753406-e7392c4e-ff35-4aca-9b3f-da653ca12ada.png)

Desktop
 - SO: [WINDOWS 10 Pro X64]
 - Navegador OPERA GX

Contexto adicional
tentei fazer a instalação mais de uma vez para ter certeza que não fiz nada de errado porem o erro persiste não sei oque fazer se alguém poder ajudar eu agradeço.

**Comment by LouanJuliels** [comment]
Resolvi gente era um erro com documento de configuração PHP

**Comment by Paul0Silva** [comment]
@LouanJuliels como resolveu? Estou com o mesmo problema.
