### ISSUE TITLE
Problema ao enviar email

### ISSUE THREAD

**Issue by juniorgtxx** [RamonSilva20/mapos#1842]
Boa tarde,

Após a politica nova do google em questão de menos segurança dos aplicativos não pode ser mais ativo,e para azar total um abençoado da minha equipe botou no email que eu usava,no maldito google ads ai ativo nessa conta com dois fatores,então criando uma conta nova no google o mapos não consegue enviar mais os emails para os clientes.
Como faço para resolver esse BO?

Obs: estou tentando o yahoo mas sem sucesso.

**Comment by lukasabino** [comment]
Dependendo do tanto de email que envia e se tem um domínio, indico fortemente o uso do AWS SES, evita tais políticas, tem uma boa quantidade de envio diário/minuto e o custo é infimo pelo que entrega.

**Comment by juniorgtxx** [comment]
> Dependendo do tanto de email que envia e se tem um domínio, indico fortemente o uso do AWS SES, evita tais políticas, tem uma boa quantidade de envio diário/minuto e o custo é infimo pelo que entrega.

AWS SES? Qual provedor de email gratuito você recomenda,pois o yahoo/gmail esses ja não dão certo mais.

**Comment by lukasabino** [comment]
Isso [AWS SES](https://aws.amazon.com/pt/ses/).
Gratuito não conheço nenhum.

**Comment by jsfachini** [comment]
@juniorgtxx Teoricamente da se resolver esse "problema" do google.
**você tem que ir em >gerenciar conta do google>segurança>como fazer login no google>senha de app.**
nessa parte da senha de app, você escolhe selecionar app >E-mail  > selecionar dispositivo> Windows e clica em **GERAR**
vai criar uma senha especifica para uma aplicação como um MS Outlook ou Mapos, essa senha não da para acessar a conta do google, ela é exclusiva para uso de algum APP.

![EMAILGOOGLE](https://user-images.githubusercontent.com/72340074/175027111-b11f32e2-d18f-4a11-9d36-c110277c354a.png)

**Comment by juniorgtxx** [comment]
Deu certo viu valeu.
