### ISSUE TITLE
Paginas enganosas pelo Google Search Console

### ISSUE THREAD

**Issue by almron** [RamonSilva20/mapos#1843]
Eu instalei o Map-OS como vários daqui em um provedor VPS e sempre funcionou normalmente. No meu caso estava instalado na Hostgator. Porém agora o site ganhou um banner vermelho mencionando que temos um Site com páginas enganosas. Acredito que isso irá acontecer com vários que utilizam o mesmo processo.
Qual seria a melhor opção para resolver esse problema? Criar uma instância na AWS, Google Cloud ou Azure, ou instalar o Map-OS em um domínio separado? Instalando por exemplo na AWS, qual a melhor forma de criar a instância? 
Ainda não consegui pensar em uma solução mais simples do que essas? Alguém tem uma ideia melhor?

**Comment by Maloqueiru** [comment]
Estou passando pelo mesmo problema. O Google já liberou o meu domínio, mas ao abrir o local onde esta o map-os ele ainda dá a mensagem de phishing

**Comment by almron** [comment]
Talvez o problema estaria que todo o código roda em http. Para isso a aplicação deveria estar em https. Abaixo temos um link de uma matéria antiga do Tecnoblog que aviso sobre o problema.

https://tecnoblog.net/noticias/2019/10/04/google-chrome-bloquear-conteudo-misto-https/

Realmente eu não sou programador e a única linha de código que eu alterei na minha vida, foi mostrar a descrição do produto, e retirar o campo valores no campo "Ordens de Serviço". Isso faz mais sentido para a empresa.
O próximo passo agora é aprender sobre Laravel, rodar em Docker Desktop, e verificar se todo o código agora roda em https. A partir disso, migrar toda a aplicação para Laravel. 

Fazendo uma pesquisa rápida no Google de todos que estão utilizando a aplicação, eu vejo que todos os sites foram afetados.
