### ISSUE TITLE
aplicativo já está instalado

### ISSUE THREAD

**Issue by diegorcampos** [RamonSilva20/mapos#1850]
"Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente."
Mas nao instalei.
Desde o envio do sistema à Infinityfree até o presente momento, aparece esse aviso, não consigo acessar a tela login nem manualmente e não me mosttra erros.
![mapos 4-4](https://user-images.githubusercontent.com/95454120/175356616-ee2d3544-7789-4ee8-964a-fe89d3937f6c.png)
Mas curiosamente qdo clico em ir para a pagina de login, a tela de instalação "pisca" e volta pra esse aviso.

**Comment by N01062561978** [comment]
Aconselho fazer um backup dos arquivos, instalar localmente e depois enviar os dados para seu provedor.

**Comment by diegorcampos** [comment]
> Aconselho fazer um backup dos arquivos, instalar localmente e depois enviar os dados para seu provedor.

eu consegui instalar.
mas o app apresenta erro no cadastro de produtos, independente da localização, seja no meu localhost ou online.
apresenta erros pra gerar relatórios, como não consigo cadastrar produtos tb nao consigo vender e testar as demais funções do sistema.

**Comment by Pr3d4dor** [comment]
@diegorcampos Que banco de dados vc está usando?
