### ISSUE TITLE
Pagamento parcial

### ISSUE THREAD

**Issue by carlospjr** [RamonSilva20/mapos#1854]
Opa pessoal, tudo bem? 

Existe alguma forma de incluir um pagamento parcial, por exemplo: 

Serviço/Produto custa R$200,00

Cliente pagou R$150,00 e ficou pendente de pagamento mais R$50,00.

É possivel faturar quebrado?

**Comment by Pr3d4dor** [comment]
@carlospjr Sim, é possível no financeiro.
