### ISSUE TITLE
Pagamento parcial de OS.

### ISSUE THREAD

**Issue by carlospjr** [RamonSilva20/mapos#1855]
Pessoal, tudo bem? 

Gostaria de saber se é possível cadastrar um pagamento parcial, segue exemplo: 

Produto/Serviço custou R$300,00

Cliente pagou agora R$250 e depois vai pagar mais R$50,00.

É possível fazer tal lançamento parcial?

**Comment by Pr3d4dor** [comment]
@carlospjr Sim, no financeiro é possível.
