### ISSUE TITLE
cor da fonte

### ISSUE THREAD

**Issue by jonathasnp** [RamonSilva20/mapos#1857]
ola alguem sabe onde muda a cor da fonte , gostaria de mudar onde esta em negrito , e colocar algo mais claro igual as versões passada

![image](https://user-images.githubusercontent.com/81585844/176906094-62af674b-bd21-4af2-99e7-c43c3ee63df0.png)

**Comment by jonathasnp** [comment]
![image](https://user-images.githubusercontent.com/81585844/177075338-7020c17d-6fa9-4070-828e-7e016b9805c6.png)
 queria deixar assim

**Comment by jsfachini** [comment]
@jonathasnp Se não me engano fica em assets>css matrix style

**Comment by jonathasnp** [comment]
![image](https://user-images.githubusercontent.com/81585844/177891971-e9dfe813-a7c8-4382-8e51-9e6b94c70c7f.png)

**Comment by jonathasnp** [comment]
![2022-07-07 (3)](https://user-images.githubusercontent.com/81585844/177892045-3c37371e-5c5a-48ed-acf7-ed6a5675895b.png)

**Comment by jonathasnp** [comment]
![2022-07-20](https://user-images.githubusercontent.com/81585844/180014889-bf81fcf0-b136-4922-b087-0d016a937b36.png)
