### ISSUE TITLE
overflow-x hidden?

### ISSUE THREAD

**Issue by DyegoPimentel** [RamonSilva20/mapos#186]
acessando o site pelo celular, ao deslizar o dedo na horizontal o site da scroll aparecendo umas bordas.

"consegui" corrigir isso e deixar o scroll apenas na vertical inserindo o css

html {
overflow-x: hidden;
}

Mas ai bugou o header e as vezes o scroll vertical nao vai ate o final, alguem sabe dizer como posso corrigir isso? (no caso remover o scroll horizontal na versão mobile)

**Comment by DyegoPimentel** [comment]
Alguém sabe como posso resolver isso?

**Comment by rogeriodomino** [comment]
apagar  o css     position: relative     caminho matrix-style.css  #user-nav
