### ISSUE TITLE
Dúvida na parte de cobranças

### ISSUE THREAD

**Issue by pcmsjr** [RamonSilva20/mapos#1861]
Olá pessoal, estou com uma dúvida, na parte de cobranças, como faço para adicionar uma cobrança, ou o sistema já gera automaticamente, pois não estou conseguindo.

**Comment by pcmsjr** [comment]
Estou usando a Versão: 4.38.0
XAMPP v3.3.0

**Comment by lukasabino** [comment]
Na parte de visualizar a OS, tem a opção para gerar pagamento.
![image](https://user-images.githubusercontent.com/70410692/181788208-f1f13c45-f27d-4ad1-b29e-514d3c9120df.png)


Antes disso, tem de se ter configurado o gateway a usar nos arquivos da aplicação.
