### ISSUE TITLE
Lançamentos financeiros sem valor do desconto

### ISSUE THREAD

**Issue by alexpicsilva** [RamonSilva20/mapos#1872]
Parabéns pelo projeto, maravilhoso como sempre. Só gostaria de relatar um bug.

Quando eu aplico um desconto (que é feito em porcentagem), seja faturando na OS ou mesmo na venda de um produto, o valor consta corretamente na home page, no entanto quando eu entro na página de lançamentos financeiros o desconto aparece errado, porque essa parte do sistema não entende o desconto como porcentagem, e sim como valor.

Por exemplo: Se eu vendo um produto que custa R$ 200 aplicando um desconto de 50%, na home page aparece meu saldo como R$ 100,00.
No entanto, quando eu entro na página de lançamentos financeiros, esse valor aparece como um saldo de R$ 150,00 porque o sistema entende que eu dei R$ 50,00 de desconto.

Venda do produto aplicando 50% de desconto:
![image](https://user-images.githubusercontent.com/36484118/180661721-68fc602d-3dba-45b5-94f5-902f6866f181.png)

Home page recebendo a informação correta:
![image](https://user-images.githubusercontent.com/36484118/180661771-3769eb91-3eb5-4c78-8aea-707eed426f4e.png)

Página de lançamento interpretando como se fosse 50 reais de desconto
![image](https://user-images.githubusercontent.com/36484118/180661823-e24ad93a-3a19-4860-9209-bb38cc9c7a39.png)

**Comment by jsfachini** [comment]
@alexpicsilva É problema nessa versão, baixa esta versão ( a master esta com alguns bugs )  
https://github.com/RamonSilva20/mapos/tree/fix/bugs

**Comment by alexpicsilva** [comment]
Show de bola,  vou testar. Muito obrigado.
