### ISSUE TITLE
Emissor de notas fiscais

### ISSUE THREAD

**Issue by Thiago18081** [RamonSilva20/mapos#1879]
Ola amigos 
Seria possível a instalação de um modulo de emissão de nota fiscais ?

**Comment by lukasabino** [comment]
Como respondido pelo Gianluca na issue #600, a parametrização de NF de produtos já se consome muito tempo e de mais pessoas apoiando no projeto, a de serviço se torna ainda mais complexa por se alterar de cidade para cidade, tendo que se usar algum gateway que para varias empresas que usa o MAPOS acaba se tornando um custo alto.

Como eu disse no grupo do [Telegram](https://t.me/maposbr), tem muito o que ser feito para o Mapos poder emitir NF, usando API ou não, e o que EU acho mais sensato é talvez o colaborador que for fazer isto, foque no mapos laravel que apesar de ainda estar bem no berço, possa vim se tornar uma melhor aplicação ao decorrer do tempo.
