### ISSUE TITLE
Alterar página de login da Área de Cliente

### ISSUE THREAD

**Issue by caiosantoy** [RamonSilva20/mapos#1883]
Pessoal eu queria fazer algumas alterações na tela de login da Área de Clientes, por exemplo adicionar algum texto, mas estou meio perdido pois não encontro a página mine.

Podem me dar uma luz? 

Obrigado!

**Comment by almron** [comment]
A página de login fica em "application/views/conecte/login.php"

https://github.com/RamonSilva20/mapos/blob/master/application/views/conecte/login.php
