### ISSUE TITLE
Aumenta a quantidade de registro da tela inicial

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#1884]
Gostaria de saber como faço pra aumentar a quantidade de registro que aparece na tela inicial. exemplo do produto em estoque baixo, porque so aparece 10 registro.

**Comment by N01062561978** [comment]
Bom, não tem configuração no sistema, mas você pode alterar diretamente no código no arquivo  Mapos_model na função getProdutosMinimo está com limite em 10
