### ISSUE TITLE
Programa não abre sem eu ter modificado nada no computador

### ISSUE THREAD

**Issue by marcelodepaola** [RamonSilva20/mapos#1885]
Programa estava funcionando normalmente e ao fechar o navegador e abris novamente apareceu esse erro.

Whoops \ Exception \ ErrorException (E_WARNING)
mysqli::real_connect(): (HY000/2002): No connection could be made because the target machine actively refused it.

Uso o chrome como navegador do MAPOS

O que devo fazer?
Segue a tela com o erro.

![Captura de tela 2022-08-04 114102 mapos](https://user-images.githubusercontent.com/110616959/182875579-1a0128e8-bab4-4ef6-81b8-b4143e2bd40d.png)

**Comment by N01062561978** [comment]
Banco de dados não encontrado, sem conexão

**Comment by Jhenriquek1** [comment]
estou com o mesmo problema
