### ISSUE TITLE
resultados por página não funciona

### ISSUE THREAD

**Issue by eletroboy97** [RamonSilva20/mapos#1897]
Ao selecionar 25 resultados por página em clientes, simplesmente não muda nada
![Screenshot_3](https://user-images.githubusercontent.com/8783876/184944637-16d419d3-9887-42e9-8b3f-c36846d90265.png)

**Comment by nmsolutions-org** [comment]
Bom dia, tive o mesmo problema, mas da pra voce contornar da seguinte forma:

Na pagina de configurações do sistema, selecione o registro por pagina para 100 como mostrado abaixo:
![image](https://user-images.githubusercontent.com/65481209/185925303-bf170f8a-6e97-4101-9ee4-b843c6bcba90.png)
Depois e so salvar que voce conseguira filtrar normalmente por mais resultados nas outras paginas, como vendas, produtos e etc... basta voce selecionar o filtro na pagina que voce quer.

**Comment by eletroboy97** [comment]
Tem como eu tirar esta parte?
![image](https://user-images.githubusercontent.com/8783876/186780109-9b5f4e24-e4d2-4b7e-9283-163960555a81.png)
meio sem sentido ter 2 filtros de dados

**Comment by nmsolutions-org** [comment]
Sem sentido não é… pois o filtro nas configurações ele só limita a quantidade de resultado por páginas, o filtro de vdd são nas páginas do sistema.

mas se você quiser pode remover no html
