### ISSUE TITLE
Pesquisa por produtos não funciona como esperado

### ISSUE THREAD

**Issue by nmsolutions-org** [RamonSilva20/mapos#1899]
** Descreva o bug **
Ao no campo de pesquisa na area de produtos, quando digito o nome do produto ou o codigo de barras o mesmo não retorna as informações, somente funciona se eu selecionar a pagina onde esta o produto e ai sim pesquisar.

Por exemplo, se eu sei q o produto está na pagina 3 ta tabela, eu so vou conseguir achar ele na pesquisa se eu ir para pagina 3 antes

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Produtos'
2. Clique em 'Pesquisar'
3. Pesquise por algo que estaja na ultima pagina
4. Se voce estiver em alguma pagina que não seja a que se encontra a informação o sistema nao encontrara o que foi pesquisado

** Capturas de tela **
BUG:
![image](https://user-images.githubusercontent.com/65481209/185617525-0be65c87-b311-47b9-8700-07bbe22a9fea.png)
![image](https://user-images.githubusercontent.com/65481209/185617817-d3bf0470-225d-4a79-81ed-5cc566701411.png)

**Comment by N01062561978** [comment]
Tentou usar essa busca?
![image](https://user-images.githubusercontent.com/67173632/185765911-9f9d87bb-533c-40d2-bdca-42e7823d4720.png)
Essa busca é somente por caracter na página mesmo.

**Comment by nmsolutions-org** [comment]
Bom dia.

Usando a busca que voce informou acima consegui localizar o produto normalmente, somente na busca que tem dentro da pagina de produtos que nao consigo localizar, mas como voce disse que ela e somente por produtos da pagina mesmo então esta explicado.

Muito obrigado pela informação
