### ISSUE TITLE
Adicionar opção para calcular taxas da maquina de cartão de credito

### ISSUE THREAD

**Issue by nmsolutions-org** [RamonSilva20/mapos#1900]
Gostaria de solicitar que fosse possivel configurar no sistema as taxas das maquinas de cartão de credito, para que fosse lançado no sistema o valor liquido que vou receber ja descontando as taxas da maquina de cartão.

**Comment by diamantes-eletronicos** [comment]
Seria excelente ter essa funcionalidade
