### ISSUE TITLE
Ordens de Serviço Em Aberto

### ISSUE THREAD

**Issue by melezinf** [RamonSilva20/mapos#191]
Na pagina inicial mudar Ordens de Serviço Em Aberto para ( Em andamento ) alguém sabe o nome da função "Em Andamento"?

        $this->data['ordens'] = $this->mapos_model->getOsAbertas();    
        $this->data['produtos'] = $this->mapos_model->getProdutosMinimo();
        $this->data['os'] = $this->mapos_model->getOsEstatisticas();
        $this->data['estatisticas_financeiro'] = $this->mapos_model->getEstatisticasFinanceiro();
        $this->data['menuPainel'] = 'Painel';
        $this->data['view'] = 'mapos/painel';
        $this->load->view('tema/topo',  $this->data);

**Comment by RamonSilva20** [comment]
Crie um novo método dentro do Mapos_model exatamente como o getOsAbertas, basta alterar o filtro para "Em Andamento".

![20190113205442](https://user-images.githubusercontent.com/12385697/51091725-86b2fb80-1775-11e9-993c-471551cb195f.png)
