### ISSUE TITLE
amigos após a ultima atualização o google ficou notificando o seite como perigoso "O site seguinte é fraudulento" so eu tive esse problema?

### ISSUE THREAD

**Issue by MarceloDSPires** [RamonSilva20/mapos#1915]
[**]( **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by almron** [comment]
Acho que várias pessoas tiveram o mesmo problema. Eu alterei algumas coisas para fazer funcionar.

Se você está utilizando uma hospedagem, você terá que alterar uma linha de código no index.php na raís do projeto.


62 if (ENVIRONMENT === 'pre_installation') {
    $domain = $_SERVER['HTTP_HOST'] . $_SERVER['SCRIPT_NAME'];

    $domain = preg_replace('/index.php.*/', '', $domain); //remove everything after index.php
    if (!empty($_SERVER['HTTPS'])) {
        $domain = 'https://' . $domain;
    } else {
        $domain = 'http://' . $domain;
    }

    header("Location: $domain./install/index.php");
    exit;

Altere a linha 69 para:

69 $domain = 'https://' . $domain;

Assim você não dá chance para utilização de um aplicativo em http. Logo o Google verá que o seu aplicativo funciona apenas em https.

Talvez na versão mais nova do CodeIgniter, o problema já tem sido corrigido e não exista mais o problema.

Eu também alterei a aplicação para um subdomínio:

Antes era: https://meusite.com.br/mapos
Alterado para https://mapos.meusite.com.br

Solicitei uma nova revisão para o Google. O link abaixo pode te ajudar no processo de revisão.

https://suporte.hostgator.com.br/hc/pt-br/articles/115000510394-Como-remover-a-p%C3%A1gina-vermelha-de-alerta-do-Google-

Não sei se o que eu fiz é o correto. Infelizmente não sou programador, mas foi o que dei certo, já que também eu não achei nenhum tutorial ou vídeo propondo uma solução melhor.
