### ISSUE TITLE
BUG Faturar e Lançamentos, BUG tambem nos graficos Pagina inicial.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#1917]
Bom dia Pessoal. Apos essas ultima atualizações esta ocorrendo varios bugs voltados a FATURAR, LANÇAMENTO, Relatórios. Isso está dando uma diferença muito grande. Ao faturar o desconto em porcentagem vai para valor em real no desconto, precisa fazer duas vezes o faturamento, e depois em lançamento para corrigir. em Relatórios só aparece o valor ao utilizar o modal de lançamento corrigindo o erro do model faturamento que coloca a porcentagem no valor de desconto. e então ai aparece nos relatórios. Agora o gráfico da pagina inicial está com valores errados não sei o pq.

**Comment by jsfachini** [comment]
@cabralwms se estiver usando a versão MASTER está cheia de bugs.
Agora essa esta ok 
https://github.com/RamonSilva20/mapos/tree/fix/bugs 
Mantida pelo @willph

**Comment by joaobsd** [comment]
Otimo dia! Pessoal
fica bem bacana se colocar os graficos nos relatorio, ajudaria em uma visão com mais velocidade
