### ISSUE TITLE
Mapos online e offline

### ISSUE THREAD

**Issue by DyegoPimentel** [RamonSilva20/mapos#192]
É possivel instalar o mapos online e local, e sincronizar o banco de dados?

vi algo semelhante a isso mas no firebase, por exemplo:

Queria poder usar online como se fosse um site, e no computador da empresa local(caso acabe a internet os dados seriam salvos no banco de dados local e assim que tivesse acesso a internet sincronizasse os dados), e quem sabe criar um app pra celular com um banco de dados que sincronize tmb, alguem sabe alguma forma de fazer isso?

Ou alguma forma de poder ter acesso ou criar alguma api que sincronize todas as fontes em um banco de dados só?

**Comment by paulinhowoox** [comment]
Daria pra criar um script que faça o deploy dos dados, mas pra isso acontecer na base teria que usar as migrations do CI, pra poder ter o banco versionado. Aí com o banco versionado é só executar as migrations e junto uma tarefa pra att os dadis.

**Comment by DyegoPimentel** [comment]
Como pesquiso sobre esse script? alem dele no caso preciso pesquisar só o migrations class do codeigniter é isso?
