### ISSUE TITLE
Erro ao atualizar da versao 4.31 para a 4.37

### ISSUE THREAD

**Issue by heraf250** [RamonSilva20/mapos#1920]
Olá estou com um problema, uso a versao 4.31 e ao fazer o update para a versao 4.37 está apresentando esse erro 
Desde já obrigado pela atenção!

![Untitled](https://user-images.githubusercontent.com/61998439/191058817-a6636462-84df-42f0-9999-fc7429f68079.png)

**Comment by Maloqueiru** [comment]
Fez o backup antes ? Aqui quando eu atualizo sempre da algum problema ( falta de conhecimento meu) então eu faço o Backup do banco de dados e instalo o novo mapos, e depois subo o backup. Se não der certo, só volto a pasta antiga.

**Comment by heraf250** [comment]
> Fez o backup antes ? Aqui quando eu atualizo sempre da algum problema ( falta de conhecimento meu) então eu faço o Backup do banco de dados e instalo o novo mapos, e depois subo o backup. Se não der certo, só volto a pasta antiga.

Opa fiz sim, na verdade o meu sistema antigo esta funcionando, ai eu crio o backup e jogo pra uma nova instalaçao, o problema está dando justamente apos a transferencia do backup

**Comment by jsfachini** [comment]
@heraf250 faz o seguinte
- 1 - Nesse novo mapos instalado, deixa ele com a base limpa sem passar o seu bkp, entra no sistema vai em **configurações>sistema>atualizações** ( deixa essa pagina aberta ) "só deixa aberta"
- 2 - Agora você vai no phpmyadmin e sobe o seu bkp.
- 3 - Assim que subir o bkp completo no phpmyadmin, volta nessa na pagina que deixou aberta "atualizações" 
- e clica em **banco de dados>atualizar**

--- aqui funcionou assim, quando atualizei o mapos que não tinha o desconto para a nova versão já com o desconto 

![2022-09-19_19h35_24](https://user-images.githubusercontent.com/72340074/191132287-4a73e267-ea87-4b93-b433-01e16fae407b.png)

**Comment by heraf250** [comment]
> @heraf250 faz o seguinte
> 
> * 1 - Nesse novo mapos instalado, deixa ele com a base limpa sem passar o seu bkp, entra no sistema vai em **configurações>sistema>atualizações** ( deixa essa pagina aberta ) "só deixa aberta"
> * 2 - Agora você vai no phpmyadmin e sobe o seu bkp.
> * 3 - Assim que subir o bkp completo no phpmyadmin, volta nessa na pagina que deixou aberta "atualizações"
> * e clica em **banco de dados>atualizar**
> 
> --- aqui funcionou assim, quando atualizei o mapos que não tinha o desconto para a nova versão já com o desconto
> 
> ![2022-09-19_19h35_24](https://user-images.githubusercontent.com/72340074/191132287-4a73e267-ea87-4b93-b433-01e16fae407b.png)

Meu colega, o procedimento que vc explicou deu certo !
muito Obrigado 
quebrou um galho gigantesco na verdade quebrou a arvore toda kkkkk

**Comment by jsfachini** [comment]
@heraf250 Agradeço pelo feedback, no que puder ajudar estamos aí. bons negócios
