### ISSUE TITLE
E-mail Automatico

### ISSUE THREAD

**Issue by phaelcoura** [RamonSilva20/mapos#1923]
Galera estou tendo problema para enviar os orçamentos por email, ja tentei alterar algumas coisas como tem em alguns videos na net mas nenhum funcionou, alguem conseguiu alguma solução ja ?
E mais uma duvida, alguem saberia dizer como consigo usar o mapos no celular tambem ? se teria alguma forma?
Desde ja muito obrigado

**Comment by jsfachini** [comment]
@phaelcoura qual tipo de problema no envio? e qual provedor de e-mail esta usando ?

Mapos nativamente no celular ate onde sei não da, o que você pode fazer pra ter acesso a ele é configurar pra rodar na sua rede local, ou em algum host ai terá acesso via internet.

**Comment by almron** [comment]
Estou tendo o mesmo problema. No meu caso, o e-mail é enviado com sucesso, porém não chega na caixa de correio. O mesmo endereço de e-mail e senha é utilizado em outra aplicação PHP e funciona perfeitamente. Ambas as aplicações, estão hospedadas em uma VPS na HostGator.

**Comment by DimmyBandeira** [comment]
Estou o mesmo problema com emails.

**Comment by jprpessoa** [comment]
Estou com um problema com e-mails também. Uso a versão 4.37.0 fiz todas as configurações email.php quando executo o index.php/process ou retry os e-mails continua pendente. Me parece que o comando não está funcionando, olho o log e não gera nenhum erro para rastrear o problema.

**Comment by naodoubuff** [comment]
Tambem estou com mesmo problema, o email não sai de pendente. Estou com o sistema hospedado na Hostgator.

**Comment by phaelcoura** [comment]
@jsfachini eu uso e-mail da gmail, antigamente ele enviava normal mas agora nao consigo enviar nenhum email mas, vi que foi algo que a google mudou, alguma sugestão do que posso fazer ?

**Comment by jsfachini** [comment]
@phaelcoura da uma olhada nesse tópico, veja se ajuda. >>>> #1848
se for gmail, tem que ativar a verificação em duas etapas.

**Comment by willph** [comment]
Alguém ainda esta com problema de enviar emails?

Provavelmente pode ser nas configurações de SMTP ou a configuração da CRON.

**Comment by jprpessoa** [comment]
@willph O problema persisti aqui. SMTP é a mesma configuração que uso em um gerenciador de e-mail e quando rodo o CRON a saída não gera qualquer resultado. Ao verificar o LOG não tem qualquer registro sobre envio de e-mails. Então estou perdido sem saber onde pode está o problema. E os e-mails fica como **pendente**.

**Comment by visaotec** [comment]
Eu tenho uma vídeo aula onde ensino como fazer as configurações de SMTP ou a configuração da CRON.
[https://www.youtube.com/watch?v=5mpVNRbcz_k](url)

**Comment by willph** [comment]
> @willph O problema persisti aqui. SMTP é a mesma configuração que uso em um gerenciador de e-mail e quando rodo o CRON a saída não gera qualquer resultado. Ao verificar o LOG não tem qualquer registro sobre envio de e-mails. Então estou perdido sem saber onde pode está o problema. E os e-mails fica como **pendente**.

tentou roda o comando via terminal para vê se vai?

porque se for a falha esta na cron

**Comment by jprpessoa** [comment]
> > @willph O problema persisti aqui. SMTP é a mesma configuração que uso em um gerenciador de e-mail e quando rodo o CRON a saída não gera qualquer resultado. Ao verificar o LOG não tem qualquer registro sobre envio de e-mails. Então estou perdido sem saber onde pode está o problema. E os e-mails fica como **pendente**.
> 
> tentou roda o comando via terminal para vê se vai?
> 
> porque se for a falha esta na cron

Sim! Inclusive a saída não tem retorno e se coloco o comando errado fala algo que não encontrou a função, e os e-mails continua pendentes e no log não mostra nenhuma informação a respeito dos e-mails.

**Comment by phaelcoura** [comment]
> @phaelcoura da uma olhada nesse tópico, veja se ajuda. >>>> #1848
> se for gmail, tem que ativar a verificação em duas etapas.

Valeuu vou dar  uma olhada e volto a avisar se deu certo
Uma duvida, tenho um domínio no hostgator, consigo subir o mapos neste servidor. ? Vi que no hostinger funciona mas no hostagator não vi nada sobre !
