### ISSUE TITLE
EDITAR CAMPOS OS

### ISSUE THREAD

**Issue by seileremerson** [RamonSilva20/mapos#193]
Ola, gostaria de usar o programa para minha produção.
Para isso eu precisaria renomear alguns campos das OS, como o campo DEFEITO que será NOME e LAUDO TECNICO que será COR. Preciso mudar dentro do Status o FATURADO para AG RETIRADA.

Ainda preciso que o dashboard mostre além das OS em aberto, também as em andamento e ag retirada. Preciso alterar os campos que que aparecem nos itens mencionados. Ou dentro da própria tela inicial da OS, alterar o nome dos campo que aparecem já me resolve.

Quais arquivos eu preciso alterar para fazer isso?
Sou um pouco leigo, mas com ajuda consigo fazer isso.
Obrigado por hora.

**Comment by RamonSilva20** [comment]
Os dados que você deseja alterar estão fixos no HTML, portando devem ser alterados nos arquivos de views da OS (application/views/os). Na próxima versão será feito via cadastro.

**Comment by pvagasm** [comment]
tenho como alterar as cores? qual o caminho?

**Comment by ruanfelipedacunha** [comment]
gostaria de alterar o nome dos campos e a logo

**Comment by pvagasm** [comment]
Digo alterar as cores do menu do "dashboard" onde diz "cliente", "Produtos".... cada um tem uma cor gostaria de deixar padrão uma só, isso é possível? qual seria o caminho?

**Comment by RamonSilva20** [comment]
> gostaria de alterar o nome dos campos e a logo

Para alterar a logo basta substituir a imagem logo.png dentro da pasta **assets/img/logo.png**, mantendo um tamanho similar e logo após efetuar a limpeza do cache Ctrl + F5.
Os nomes dos campos ficam em arquivos dentro da pasta **application/views**, basta procurar na pasta cujo cadastro você quer alterar.

**Comment by RamonSilva20** [comment]
> Digo alterar as cores do menu do "dashboard" onde diz "cliente", "Produtos".... cada um tem uma cor gostaria de deixar padrão uma só, isso é possível? qual seria o caminho?
> E tirar o cpf como campo obrigatório?

Para alterar a cor basta colocar a mesma classe nos elementos li. 
Para a cor verde por exemplo, basta replicar a classe **bg_ly**    ` <li class="bg_ly">`.
Arquivo -> https://github.com/RamonSilva20/mapos/blob/master/application/views/mapos/painel.php#L25


Para remover a obrigatoriedade no campo de CPF será preciso remover a validação no javascript, no form_validation e no banco de dados.

**Comment by willph** [comment]
Versão mais recente, só é obrigatório nome. CPF não mais

**Comment by pvagasm** [comment]
@willph Estou com a versão 4.23.0 e quando vou cadastrar o cliente o campo CPF é obrigatório qual seria a versão mais recente?

**Comment by pvagasm** [comment]
Aonde baixo a versão v4.4.0?

**Comment by Pr3d4dor** [comment]
@pvagasm https://github.com/RamonSilva20/mapos/releases

**Comment by pvagasm** [comment]
exclui minha versão anterior e estou reinstalando porem está ocorrendo esta mensagem
Quando rodo o comando "composer install --no-dev"
"
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-QM1C99C+2021-02-06+0134
to retrieve a token. It will be stored in "C:/Users/User/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):
" 
o que pode ser?

**Comment by willph** [comment]
> exclui minha versão anterior e estou reinstalando porem está ocorrendo esta mensagem
> Quando rodo o comando "composer install --no-dev"
> "
> Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-QM1C99C+2021-02-06+0134
> to retrieve a token. It will be stored in "C:/Users/User/AppData/Roaming/Composer/auth.json" for future use by Composer.
> Token (hidden):
> "
> o que pode ser?

Tem o aplicativo GIT instalado?

**Comment by WelingtonSimao** [comment]
Olá Renan primeiramente obrigado pelo ótimo sistema, agora o que eu gostaria de saber e seguinte eu alterei o nome de alguns "status" das "os" exemplo: de "Orçamento" para "Agendado" pois vou usar o sistema numa pequena clinica, mas, ao fazer isso quando clico no menu em "Ordens de Serviço" ele não lista as os as quais estão com status com nomes diferente, mas, as sem alteração lista normal, onde mais eu devo alterar o status para listar as os.

**Comment by WelingtonSimao** [comment]
![Captura de tela de 2023-09-09 08-44-44](https://github.com/RamonSilva20/mapos/assets/144533618/394bfcf5-1bce-4f79-a9f4-4a53c28caacb)
