### ISSUE TITLE
Campo de Emitente com CPF e CNPJ

### ISSUE THREAD

**Issue by zavanella** [RamonSilva20/mapos#1934]
É possível deixar o campo de emitente com a opção de CPF além de CNPJ? Não possuo CNPJ, mas gostaria de deixar o cpf.

**Comment by jsfachini** [comment]
@zavanella tem, coloca qualquer cnpj no campo dentro do mapos, depois vai no **phpmyadmin** e procura por emitente, remove o cnpj e coloca o seu cpf, igual no imagem abaixo, depois clica em **EXECUTAR.**

![phpm](https://user-images.githubusercontent.com/72340074/195226822-793b4d56-cec2-43ec-9796-3962935421d5.png)

**Comment by willph** [comment]
> Perfeito @jsfachini deu super certo. Muito obrigado pelo apoio.

o mais simples é inserindo o seu CPF normalmente, ele aceita salvar, só não fica com a mascara de CPF.

Mas que bom que já conseguiu resolver do seu jeito.
