### ISSUE TITLE
Logotipo não aparece no email ao cliente

### ISSUE THREAD

**Issue by zavanella** [RamonSilva20/mapos#1937]
Ola, boa noite a todos, 

O logotipo da OS não esta aparecendo quando enviado via e-mail, fica como se a imagem estivesse quebrada. Localmente, funciona normal. Utilizo rodando em um server local, não em hospedagem.

![erro_email](https://user-images.githubusercontent.com/30843160/196315832-c814c338-c5a1-4d1c-8b02-6994a8e45665.png)

Alguém enfrentou esse cenário e sabe como resolver?

Obrigado.

**Comment by Pr3d4dor** [comment]
@zavanella Isso acontece porque a imagem do logotipo não é pública. Para funcionar tem que usar uma imagem pública.

**Comment by willph** [comment]
> Ola, boa noite a todos,
> 
> O logotipo da OS não esta aparecendo quando enviado via e-mail, fica como se a imagem estivesse quebrada. Localmente, funciona normal. Utilizo rodando em um server local, não em hospedagem.
> 
> ![erro_email](https://user-images.githubusercontent.com/30843160/196315832-c814c338-c5a1-4d1c-8b02-6994a8e45665.png)
> 
> Alguém enfrentou esse cenário e sabe como resolver?
> 
> Obrigado.

O seu MapOS esta em localhost ou em alguma hospedagem?


Se for em locahost:
Em resumo o site precisaria esta hospedado em algum local, pois ai a imagem estaria atrelada ao endereço do seu site e não a maquina local.

Ex:  `seusite.com.br/assets/uploads/imagemDoEmitente.png` 

                      ao inves de

 `localhost/assets/uploads/imagemDoEmitente.png`


Infelizmente localhost num é um endereço reconhecido e acessível por outros computadores.
