### ISSUE TITLE
Erro ao tentar faturar ordem de serviço 

### ISSUE THREAD

**Issue by 21bruno** [RamonSilva20/mapos#1938]
Quando vou faturar uma ordem de serviço aparece a seguinte mensagem (Atenção
Ocorreu um erro ao tentar faturar OS.
OK)

**Comment by Pr3d4dor** [comment]
@21bruno Qual versão do mapos e PHP?

**Comment by willph** [comment]
> Quando vou faturar uma ordem de serviço aparece a seguinte mensagem (Atenção Ocorreu um erro ao tentar faturar OS. OK)

Conseguiu resolver já?

**Comment by diamantes-eletronicos** [comment]
Estou usando o PHP 7.4 e também estou com o mesmo erro. Já mudei a versão do PHP porém não resolveu o problema.

**Comment by diamantes-eletronicos** [comment]
![erro-faturar-mapos](https://user-images.githubusercontent.com/113117890/207902090-4a87d1fe-cd97-45e5-9658-b4a92172b529.png)

**Comment by 21bruno** [comment]
> @21brunoQual versão do mapas e PHP?

7.4

**Comment by 21bruno** [comment]
> > Quando vou faturar uma ordem de serviço aparece a seguinte mensagem (Atenção Ocorreu um erro ao tentar faturar OS. OK)
> 
> Conseguiu resolver já?

Ainda não!
Preciso bastante de ajuda com isto

**Comment by diamantes-eletronicos** [comment]
Acabei de resolver o problema, apaguei tudo e instalei do zero. Esse erro começou depois que atualizei pra última versão, havia feito a atualização por dentro do próprio MapOS.

**Comment by 21bruno** [comment]
> Qual versão está usando?
> 
> Foi instalação do zero ou atualização?

Eu instalei do zero a versão 4.37 aí coloquei na hospedagem e deu este erro, atualizei para versão agora 4.39 e continua

**Comment by 21bruno** [comment]
> Qual versão está usando?
> 
> Foi instalação do zero ou atualização?

Eu creio que seja no meu banco de dados, a versão 4.39 em localhost funcionou tudo normal, coloquei na hospedagem e usei o meu banco de dados para não perder as minhas coisas e começou o erro mas só dentro da hospedagem

**Comment by willph** [comment]
> Acabei de resolver o problema, apaguei tudo e instalei do zero. Esse erro começou depois que atualizei pra última versão, havia feito a atualização por dentro do próprio MapOS.

Tem um botão no sistema. 
Sobre atualiza banco de dados.

**Comment by 21bruno** [comment]
> > Acabei de resolver o problema, apaguei tudo e instalei do zero. Esse erro começou depois que atualizei pra última versão, havia feito a atualização por dentro do próprio MapOS.
> 
> Tem um botão no sistema. Sobre atualiza banco de dados.

Eu cheguei a fazer este procedimento e não resolveu vou criar outro banco de dados e ver

**Comment by ruanitto** [comment]
Eu percebi que no meu, após atualizar nas tabelas lancamentos e os, o sistema tenta buscar valores da coluna tipo_desconto. Criei um varchar(100) e resolveu. Mas vou alterar para enum depois.

**Comment by willph** [comment]
> Eu percebi que no meu, após atualizar nas tabelas lancamentos e os, o sistema tenta buscar valores da coluna tipo_desconto. Criei um varchar(100) e resolveu. Mas vou alterar para enum depois.

Tem atualizações na pasta updates.
Serve para atualiza o banco de dados. 

Ou pode atualiza o banco de dados no próprio sistema.
Tem o botão para atualizar o banco de dados.

**Comment by ruanitto** [comment]
> > Eu percebi que no meu, após atualizar nas tabelas lancamentos e os, o sistema tenta buscar valores da coluna tipo_desconto. Criei um varchar(100) e resolveu. Mas vou alterar para enum depois.
> 
> Tem atualizações na pasta updates. Serve para atualiza o banco de dados.
> 
> Ou pode atualiza o banco de dados no próprio sistema. Tem o botão para atualizar o banco de dados.

Sim, mas nela pela última release não tem ainda essas colunas
