### ISSUE TITLE
Erro ao tentar rodar o compose

### ISSUE THREAD

**Issue by GuiTeche** [RamonSilva20/mapos#1939]
Ao rodar o comando de subir os containeres, no step do composer fica rodando o sync e da falha de timeout, um deles é o composer/pcre e vários outros.

**Comment by visaotec** [comment]
Olá tudo bem!
ja postei a solução aqui nesse link
[https://github.com/RamonSilva20/mapos/issues/1925](url)

**Comment by willph** [comment]
Caso não tenha conseguido resolver com a sugestão do @visaotec só reabrir essa Issue.
