### ISSUE TITLE
VERSÃO 4.39 ERRO %

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1953]
@Pr3d4dor 

Testes realizados na versão, foi detectado o erro da % 
que permanece na sessão **Lançamentos>Lançamento Financeiro** 
esta como R$ e não %

![Sem título](https://user-images.githubusercontent.com/72340074/198885291-89f12e8c-f051-4bd6-b2c4-ce2ffd4d046c.png)

**Comment by willph** [comment]
Precisa atualizar o Banco de dados.

Essa atualização infelizmente não afeta se já tiver dados no lançamento. 

Pois se for atualização os dados de lançamento vai vim com tipo_desconto como null.
E ele precisa está preenchido para o sistema reconhece qual foi o tipo de desconto dado

**Comment by jsfachini** [comment]
@willph Base limpa, instalado agora para fins de teste

**Comment by willph** [comment]
> @willph Base limpa, instalado agora para fins de teste

Como foi feito esse lançamento?

**Comment by jsfachini** [comment]
Criado uma ordem de serviço e faturado

**Comment by willph** [comment]
> Criado uma ordem de serviço e faturado

Campo desconto foi utilizado?

**Comment by jsfachini** [comment]
sim

**Comment by willph** [comment]
> sim

Selecionou % no campo de seleção de tipo de desconto?

**Comment by jsfachini** [comment]
a forma utilizada foi essa

![sss](https://user-images.githubusercontent.com/72340074/198886573-0788fd10-8ac7-4b76-be12-c88d327eead3.png)

**Comment by willph** [comment]
> a forma utilizada foi essa
> 
> ![sss](https://user-images.githubusercontent.com/72340074/198886573-0788fd10-8ac7-4b76-be12-c88d327eead3.png)

Está faltando o seletor onde tem $ ou %.

Seto o código no branch de desconto 4.39?

Caso contrário não testou o código corretamente. 

Obrigado por disponibilizar tempo para nós ajudar

**Comment by jsfachini** [comment]
@willph sim faltou a branch de desconto, utilizei somente o master.

obrigado.
