### ISSUE TITLE
Problema com a integração com Gatway de cobrança Asaas

### ISSUE THREAD

**Issue by basgelly** [RamonSilva20/mapos#1954]
** Descreva o bug **
Fiz a tentativa de integração com o Gateway de pagamento ASAAS, gerei a chave com sucesso, coloquei entre as aspas e salvei, quando clico para gerar o boleto ele dá o seguinte erro "Erro ao criar cliente na Asaas!"

**Reproduzir**

Para reproduzir o problema crie uma ordem de Venda e fature a mesma e ordene que o sistema gere um boleto, quando selecionar o ASAAS ele dá um erro

**Comportamento esperado**

Acredito que seja criar o Cliente e Emitir o boleto

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Edge, Chrome e Firefox
 - Versão a mais atual

**Comment by Pr3d4dor** [comment]
@basgelly Está usando o ambiente de testes ou produção?

**Comment by willph** [comment]
> @basgelly Está usando o ambiente de testes ou produção?

eu fiz os testes em ambiente de teste e da esse erro **"Erro ao criar cliente na Asaas!"**
so não conseguir identificar a origem, mas creio que esta vindo da API.

**Comment by willph** [comment]
bug fix: asaas generate billet #1968 

so aguarda.

**Comment by willph** [comment]
Lembrando que são 2 cadastro, cada um tem sua Key especifica.

Modo Teste
[sandbox](https://sandbox.asaas.com)

Modo Real
[produção](https://www.asaas.com)
