### ISSUE TITLE
[Resolvido] Instalei, mas não consigo logar.

### ISSUE THREAD

**Issue by gustavopareschi** [RamonSilva20/mapos#1956]
Olá, pessoal, instalei tudo como o tutorial, mas o usuario e senha que coloquei no install não foi para a DB. Então não consigo logar. Ai criei manualmente pela DB e mesmo assim não consigo logar.

**Comment by Pr3d4dor** [comment]
Qual versão?

**Comment by willph** [comment]
> Olá, pessoal, instalei tudo como o tutorial, mas o usuario e senha que coloquei no install não foi para a DB. Então não consigo logar. Ai criei manualmente pela DB e mesmo assim não consigo logar.

Atualização ou instalação feita do zero?

**Comment by gustavopareschi** [comment]
Bom dia,
Então, eu consegui instalar agora, provavelmente foi algum erro de extensão do PHP. Obrigado pela atenção!

**Comment by willph** [comment]
Tranquilo!

Qualquer outra duvida só entra em contato.

Atenciosamente, Equipe MapOS.
