### ISSUE TITLE
Não loga

### ISSUE THREAD

**Issue by yasron** [RamonSilva20/mapos#1959]
** Não loga **
Fiz a instalação da ultima versão mais não loga .

Instalei a versão  4.39.0 e não consigo logar com os dados cadastrados na instalação.

**Comment by Pr3d4dor** [comment]
@yasron Você configurou corretamente o banco de dados?

**Comment by willph** [comment]
> ** Não loga ** Fiz a instalação da ultima versão mais não loga .
> 
> Instalei a versão 4.39.0 e não consigo logar com os dados cadastrados na instalação.

É atualização ou instalação feita do zero?

**Comment by willph** [comment]
Se o erro era pela quebra do código devido a estatísticas foi enviada uma PR.

Caso ainda tenha alguma duvida so reabrir novamente esta issue

 bug fix: statistic had a null value #1968

**Comment by yasron** [comment]
> @yasronVocê configurou corretamente o banco de dados?

Acredito sim, vou refazer a instalação para ver se consigo resolver

**Comment by willph** [comment]
> > @yasronVocê configurou corretamente o banco de dados?
> 
> Acredito sim, vou refazer a instalação para ver se consigo resolver

certo.
aguardo o retorno.

**Comment by jackanilto** [comment]
Caso precise de ajuda na instalação no período da noite posso te ajudar tbm a esclarecer alguma duvida
