### ISSUE TITLE
COMO VISUALIZAR MAIS DE 10 ORDENS DE SERVIÇOS POR VEZ ?

### ISSUE THREAD

**Issue by diegoker** [RamonSilva20/mapos#196]
Ola, utilizo o sistema em minha loja, agradeço muito pela iniciativa nobre de criar um sistema tão funcional. 

Em um certo dia tentei visualizar mais de 10 ordens de serviços por vez no meu monitor sem precisar emitir algum relatório mas não consegui, vocês poderia me ajudar com isso ?  

Map OS 3.1.12

**Comment by bykarlos** [comment]
Hola alguien pudo encontrar solución a este punto? Gracias, Saludos

**Comment by RamonSilva20** [comment]
Altere o valor da configuração de quantidade por página no arquivo application/controllers/Os.php.

![20190113234630](https://user-images.githubusercontent.com/12385697/51093705-83c40500-178d-11e9-9f92-f66762e3d720.png)
