### ISSUE TITLE
Error Call to a member function setTime() on bool   

### ISSUE THREAD

**Issue by rafatk9** [RamonSilva20/mapos#1963]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...' Ordens de Serviço 
2. Clique em '....'
3. Ver erro já acontece o erro
Error
Call to a member function setTime() on bool
  

**Comportamento esperado**
Que seja aberto a tela de OS normalmente

** Capturas de tela **

![image](https://user-images.githubusercontent.com/117676674/200387481-a5e4cb4f-ee5e-42de-b153-e58f412c93d0.png)

** Desktop (preencha as seguintes informações): **
 - SO: Windows
 - Navegador Mozila
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@rafatk9 Qual é a versão do PHP que está sendo usado?

**Comment by rafatk9** [comment]
Boa tarde consegui resolver era uma OS que estava com data 00.00.0000

Agora só estou com problema no relatório de os hospedado no infinity


Em qui., 10 de nov. de 2022 15:54, Gianluca Bine ***@***.***>
escreveu:

**Comment by Pr3d4dor** [comment]
@rafatk9 Qual erro que ocorre?

**Comment by rafatk9** [comment]
Em qui., 10 de nov. de 2022 16:16, Gianluca Bine ***@***.***>
escreveu:

**Comment by Pr3d4dor** [comment]
@rafatk9 Não sei se você anexou alguma imagem. A mesma não apareceu aqui.
