### ISSUE TITLE
impressão não fiscal

### ISSUE THREAD

**Issue by magaoallex** [RamonSilva20/mapos#1964]
** Descreva o bug **
QUANDO ALTERA O STATUS PARA FINALIZADO  AS INFORMAÇÕES DO CAMPOS DESCRIÇÃO NÃO APARECER NA IMPRESSÃO

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá em visualizar **OS** e abra uma **OS** com status ABERTO NELA VAI ESTÁ NORMAL CONFORME , coloque para imprimir, nela aparecerá o você escreveu no campo **descrição**.
2. Mude o status da Os para finalizado, coloque para imprimir novamente, note que as informações contida no campo **descrição** não aparece na impressão.

**Comment by acinformatica2004** [comment]
Boa noite, sei que não tem nada haver com esse problema, mais me tira uma dúvida, quando vc imprime no cupom, ele para no final do texto ou imprime do tamanho da folha A4? Pq aqui no meu ele termina o texto e continua em branco até o tamanho da A4.

**Comment by willph** [comment]
bug fix in PR "CP Non-Fiscal". #1966
