### ISSUE TITLE
Melhorias  no MapOs para uso 

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#1967]
**Olá tudo bem!**
Quero agradecer o pessoal do desenvolvimento no qual tem empenhado para tornar o MapOs mais produtivo ...
Venho apresentar melhorias que fizemos ao longo desses dias para usar o Sistemas mais estável, **vou fazer uma branch e solicitar um Pull Request a fim de melhorar o projeto nas correções!**
 
**A PARTE DE IMPLEMENTAÇÕES DE VEÍCULOS, EQUIPAMENTOS É DE USO PESSOAL, CADA USUÁRIO FAZ A IMPLEMENTAÇÃO QUE ACHAR CONVENIENTE!**

Segue a baixa a descrição de tudo que fiz para melhorar...
* Novo Menu: Veiculos (add, editar, excluir)

* Novo Menu: Categorias (add, editar, excluir)

* Assinatura Digital para Clientes na OS

* Novo Menu: Subcategorias (add, editar, excluir)

* Novo Menu: Marcas (add, editar, excluir)

* Vínculo de veiculos cadastrados por cliente em menu OS

* Correção de bug (Map-Os) ao cadastrar cliente/fornecedor

* Correção de erro no menu financeiro: Lançamento do valor desconto em porcentagem (menus OS e Vendas) alterando para salvar o valor de desconto em reais no menu Financeiro.

* Alteração nos submenus de OS: imprimir A4, imprimir Cupom não fiscal e Visualizar OS

* Alteração nos submenus de VENDAS: imprimir A4, imprimir Cupom não fiscal e Visualizar VENDAS

* Inclusão de campos: Categorias, SubCategorias e Marcas em menu PRODUTOS

*Organização de menu dropdown com lista de submenus.

*Inclusão do Favicon em todas páginas dos relatórios

*Em vendas se faturado o status fica verde, caso contrário vermelho

*Correção e implementação para exibir Termo de garantia na OS e em Vendas

*Inserção Qrcode no cupom não fiscal

*Correção no financeiro, os desconto vinha errado nos calculos 

* Relatórios Novos:

-- Veículos
-- Categorias
-- Subcategorias
-- Marcas

** Acrescimo de campos em relatórios existentes:
      *** Relatório OS: Veiculos vinculados, total de comissão do vendedor, somatória de todas as comissões lançadas nas ordens de serviço e total líquido de OS.
	 - Somente a permissão de administrador visualiza todas as OS em relatórios.
	 - Inclusão da cláusula para visualizar em relatorios somente as OS que foram faturadas.
	 - Obrigatoriedade em filtrar relatório por data.
	
      *** Relatório Vendas:
	- Somente a permissão de administrador visualiza todas as Vendas em relatórios.
	- Inclusão da cláusula para visualizar em relatorios somente as vendas que foram faturadas. 
	- Obrigatoriedade em filtrar relatório por data.	
	- Filtro tipo para pesquisa:
		 *total de vendas: inclusão do valor de comissão total do vendedor, somatória de todas as comissões lançadas nas vendas e total líquido de vendas.
		 * Detalhes de produtos, com valor de compra, valor de venda, porcentagem da comissão do vendedor, nome de todos os produtos lançado nas vendas,somatória do total de compras e total de vendas sem o desconto.

      *** Relatório Produtos: Inclusão de campos categorias, subcategorias e marcas dos produtos.	
![001](https://user-images.githubusercontent.com/35280835/201932458-4660a0b2-20d8-4541-89ef-65d57ea9f220.JPG)
![007](https://user-images.githubusercontent.com/35280835/201932604-bb5e5de8-621a-47ef-80eb-2ff6aebfb8a6.JPG)
![002](https://user-images.githubusercontent.com/35280835/201932689-b3665e45-1cb4-46cb-b138-3e64aee6030d.JPG)
![003](https://user-images.githubusercontent.com/35280835/201932718-4287d83f-c40e-4e8a-9cd6-4b3a1a4fc9dc.JPG)
![004](https://user-images.githubusercontent.com/35280835/201932745-0175a767-02e7-4216-9239-ce1b431bf886.JPG)
![005](https://user-images.githubusercontent.com/35280835/201932773-60c38578-adb6-45a1-9c31-3b1f818799ec.JPG)
![006](https://user-images.githubusercontent.com/35280835/201932800-c75a89e4-e029-45b3-9de4-78113e0e32d3.JPG)
![0010](https://user-images.githubusercontent.com/35280835/202020310-60efdf9e-d22f-49c3-9acd-3e51371c241c.JPG)
![0011](https://user-images.githubusercontent.com/35280835/202020649-abb1e11c-751a-4ed6-ae13-9bb4ec66b784.JPG)
![ass](https://user-images.githubusercontent.com/35280835/202198952-754f6a55-4d41-4921-8aaa-d277fd905664.JPG)
![ass02](https://user-images.githubusercontent.com/35280835/202198983-7c34ff56-6603-48a0-a8a9-993fe005efb4.JPG)

**Agradeço a todos**
E-mail: visaotec.com@gmail.com

**Comment by acinformatica2004** [comment]
Boa tarde, gostei dessas melhorias, se puder enviar, gostaria de modificar a opção veículos pra equipamento de informática.

Top!!

**Comment by visaotec** [comment]
> Boa tarde, gostei dessas melhorias, se puder enviar, gostaria de modificar a opção veículos pra equipamento de informática.
> 
> Top!!

Já tenho também com opção de equipamentos!

**Comment by visaotec** [comment]
> Nessa mesma versão de hj do mapos?

Sim!

**Comment by acinformatica2004** [comment]
Vai disponibilizar aqui?

**Comment by visaotec** [comment]
> Vai disponibilizar aqui?

Não tem data previsto, vou fazer um Pull Request !

**Comment by acinformatica2004** [comment]
Legal, vou aguardar pra implementar no meu.

**Comment by almron** [comment]
O Map-OS é um sistema mais genérico para ser utilizado por todos. Acho que cadastro de equipamentos ou produtos iria atender mais empresas. Depois cada uma pode adaptar para o produto que utiliza como Veículos ou Equipamentos de Informática por exemplo. Talvez uma opção mais fácil para cada um alterar da maneira que desejar.

**Comment by cabralwms** [comment]
Acredito que cliente e fornecedores deveriam ser separados, pensando em organizar por exemplo financeiro/fornecedores. Caso seja implementado futuramente como gasto ou investimentos, compras, reposição. não sei se tem intenção de fazer isso mais acho que seria muito legal e forncedores separados para conseguir distinguir mais facil e separar opções que seriam apenas para fornecedores.

**Comment by visaotec** [comment]
> Acredito que cliente e fornecedores deveriam ser separados, pensando em organizar por exemplo financeiro/fornecedores. Caso seja implementado futuramente como gasto ou investimentos, compras, reposição. não sei se tem intenção de fazer isso mais acho que seria muito legal e fornecedores separados para conseguir distinguir mais fácil e separar opções que seriam apenas para fornecedores.

Vou fazer essas alterações daqui uns dias, inclusive inserir  Equipamentos e muitas outras modificações!

**Comment by xiuris** [comment]
Aguardando ansioso, se puder disponibilizar para mim, essa versão, ficaria muito grato, gabrielfariasfelipeh@gmail.com
