### ISSUE TITLE
Erro ao restaurar backup

### ISSUE THREAD

**Issue by Soldadodelcaro** [RamonSilva20/mapos#1978]
Olá, desinstalei meu mapos para atualizar, quando reinstalei fui devolver meu backup e aparece um erro, antes de atualizar eu tinha personalizado ele apenas com minhas logos e mais nada, alguém pode me ajudar.. segue a imagem do erro. 
![16690861703531091341271020845014](https://user-images.githubusercontent.com/118787155/203210971-16969fb8-0c50-4b4a-9b88-66048e2aab4c.jpg)

**Comment by visaotec** [comment]
Muitas vezes as atualizações causa esse erro, já peguei muitos Mapos de clientes pra corrigir depois das atualizações
te recomendo não ficar atualizando com frequência, até porque não tem nada significativo nessas atualizações, tem que testar o sistema antes de fazer atualizações, e outra coisa caso tenha feito alguma alteração no código do sistema, será perdido.

**Comment by Soldadodelcaro** [comment]
Muito obrigado meu amigo. Serve de experiência né.... Valeu

Em ter, 22 de nov de 2022 14:07, Visaotec Eletrônicos <
***@***.***> escreveu:

**Comment by jsfachini** [comment]
@Soldadodelcaro  ( esse comentário copiei de uma postagem mais antiga e resolve seu problema )

Não lembro o nome do autor, caso ver deixa seu comentário ai.
acredito que isso ajudou bastante gente. **( poderia ate fixar em discussão )**

________________________________________________________________
**Segue post:**

Pessoal, bom dia!

Esse erro é que a nova versão passou por updates de campos no banco de dados e a solução é primeiro baixar o arquivo completo do sistema, aqui do git e abrir a pasta Update na sua maquina local mesmo - > e abra o phpmyadmin do banco de dados lá na hospedagem....
em seguida, selecione o banco de dados que o sistema vai usar e click em importar, e importe um a um cada update que esta disponível nessa pasta

na sequencia importe o seu backup e acesse a pagina de login
