### ISSUE TITLE
Cadastro de Compras 

### ISSUE THREAD

**Issue by Saviodellano** [RamonSilva20/mapos#1979]
Olá bom dia, no programa não tem opção de compra. Só venda.
No cadastro do produto eu vi que posso por o produto como entrada (que seria compra) e saída (que seria venda), mas nao achei a opção/modo de compra. Porque se tiver a gente cadastraria a compra de acordo com o fornecedor, incluindo os produtos e ai ja citava o estoque e as despesas.
Teria como verificar se seria possivel essa opção?

**Comment by visaotec** [comment]
Olá, no sistema que usamos implementamos essa opção de compra, no qual pode fazer cotação com vários fornecedores!

**Comment by willph** [comment]
> Olá, no sistema que usamos implementamos essa opção de compra, no qual pode fazer cotação com vários fornecedores!

Então porque você num envia  toda alterações feitas pra fica aqui como uma variante do MapOs ao invés de está usando as issues como propaganda do seu sistema? 

Nada contra você querer vende sua variante ou serviços, mas não acho legal está usando as issues como propaganda ou marketing do seu sistema.

**Comment by visaotec** [comment]
> > Olá, no sistema que usamos implementamos essa opção de compra, no qual pode fazer cotação com vários fornecedores!
> 
> Então porque você num envia toda alterações feitas pra fica aqui como uma variante do MapOs ao invés de está usando as issues como propaganda do seu sistema?
> 
> Nada contra você querer vende sua variante ou serviços, mas não acho legal está usando as issues como propaganda ou marketing do seu sistema.

Em momento nenhum eu falei de propaganda, eu só falei que no que uso eu fiz a alteração pra compras, até porque não é a necessidade de todos! Se fosse a necessidade de todos eu colocaria sem problemas nenhum!

**Comment by willph** [comment]
### Comunicado Oficial 

_Infelizmente, venho por meio desta mensagem avisar que se permanecer com a atitude de usar as issues como meio de marketing disfarçado de ajuda ou qualquer outro tipo de intenção que seja meramente promoção própria ou do seu sistema, iremos bloquea-lo do repositório._

_Issues foram feitas para ajudar as pessoas, tirar dúvidas, fazer sugestões, informar bugs e não pra fica fazendo marketing pessoal._

Assinado, Equipe MapOs.

**Comment by visaotec** [comment]
> ### Comunicado Oficial
> _Infelizmente, venho por meio desta mensagem avisar que se permanecer com a atitude de usar as issues como meio de marketing disfarçado de ajuda ou qualquer outro tipo de intenção que seja meramente promoção própria ou do seu sistema, iremos bloquea-lo do repositório._
> 
> _Issues foram feitas para ajudar as pessoas, tirar dúvidas, fazer sugestões, informar bugs e não pra fica fazendo marketing pessoal._
> 
> Assinado, Equipe MapOs.

**Por mim pode bloquear a hora que quiser, mas a verdade eu sempre irei dizer..... Permaneço com o texto que mencionei acima.
é só respeitar o meu espaço que respeitarei o seu! Quando é algo que não tem no Sistema eu faço alterações sim e aproveitando que já vai bloquear , vou deixar uma dica! Pare de mudar versão do sistema e design e preocupa em corrigir o sistema ok. Abraços**

**Comment by willph** [comment]
> Olá bom dia, no programa não tem opção de compra. Só venda. No cadastro do produto eu vi que posso por o produto como entrada (que seria compra) e saída (que seria venda), mas nao achei a opção/modo de compra. Porque se tiver a gente cadastraria a compra de acordo com o fornecedor, incluindo os produtos e ai ja citava o estoque e as despesas. Teria como verificar se seria possivel essa opção?

Acredito que o fluxo correto seria redesenhar essa parte.
Iremos analisar sua sugestão. 

Obrigado.

**Comment by Saviodellano** [comment]
agradeço a atenção .

**Comment by Saviodellano** [comment]
Alguma possibilidade de incluir essas informações ?
