### ISSUE TITLE
Adicionar horas a ordem de serviço

### ISSUE THREAD

**Issue by danillosouzaa** [RamonSilva20/mapos#1984]
Olá, se tiver alguém que entenda mais de programação pra me dar uma força, eu preciso que a ordem de serviço contenha as horas que o serviço iniciará. Funçando aqui eu consegui fazer pra ficar no lugar da Data inicial, porém quando eu altero a hora ela não fica salva.
![Captura de tela 2022-12-03 022059](https://user-images.githubusercontent.com/51977419/205425691-f4062541-8039-4297-aee3-bd97784e1f27.png)
![Captura de tela 2022-12-03 022151](https://user-images.githubusercontent.com/51977419/205425692-d67b4ff7-c934-4966-8730-706b5df9cfbe.png)
![Captura de tela 2022-12-03 021916](https://user-images.githubusercontent.com/51977419/205425693-464a6387-e7f4-491d-a502-a7b9bb613e9a.png)
![Captura de tela 2022-12-03 022006](https://user-images.githubusercontent.com/51977419/205425695-6dfad278-8b55-4281-9042-cedbc84d10b8.png)
![Captura de tela 2022-12-03 023058](https://user-images.githubusercontent.com/51977419/205425716-7a0e6946-7c80-48bf-9ce7-addf475f8a2d.png)

**Comment by visaotec** [comment]
Olá, 
isso aí tem que criar um campo no banco e depois mexer em controller pra salvar.

**Comment by danillosouzaa** [comment]
> Olá, isso aí tem que criar um campo no banco e depois mexer em controller pra salvar.

Eu ja editei o código de "dataFinal" no banco de dados, de "date" para "time" e em controllers alterei de "date('Y/m/d')" para "date('H:i')".  Se eu alterar o horário pelo próprio BD no phpMyAdmin ele fica salvo de boa, mas se eu fizer pelo mapos ele não salva, isso que não entendo.
![Captura de tela 2022-12-04 122054](https://user-images.githubusercontent.com/51977419/205499578-68738e66-ed7f-4df7-8710-1302e0fa69f7.png)
![Captura de tela 2022-12-04 122256](https://user-images.githubusercontent.com/51977419/205499584-a59fd8a1-adde-49cb-af0a-354d29e0e18e.png)
![Captura de tela 2022-12-04 122421](https://user-images.githubusercontent.com/51977419/205499589-d9d3fd4c-39cc-4005-b27b-1832c2b6a7a0.png)

**Comment by danillosouzaa** [comment]
Se alguém puder me ajudar
