### ISSUE TITLE
Erros ao solicitar relatorios

### ISSUE THREAD

**Issue by Saviodellano** [RamonSilva20/mapos#1990]
Estou tentando solicitar os relatórios, e está aparecendo o seguinte erro!
Vocês podem me ajudar ?
![erro relatorios](https://user-images.githubusercontent.com/65836998/206020894-4d862de2-aa0b-4db4-90a9-a2a71411d0cf.png)

**Comment by willph** [comment]
Qual relatório?

**Comment by Saviodellano** [comment]
Ola, todos eles!

**Comment by willph** [comment]
> Ola, todos eles!

Você colocou a imagem do emitente?

**Comment by Saviodellano** [comment]
Sim, porque todos estão dendo erros, voce quer que eu coloque todos aqui ?

**Comment by Saviodellano** [comment]
Sim coloquei

**Comment by willph** [comment]
> Sim coloquei

Eu fiz o teste Aqui.

Tem um erro que ocorre por falta da imagem ou quando ela está corrompida.
Por isso perguntei

**Comment by Saviodellano** [comment]
Entendi posso tentar por outra para testar o que acha ?

**Comment by willph** [comment]
> Entendi posso tentar por outra para testar o que acha ?

Faz o teste.
Faz o upload de uma nova imagem pra testar.

**Comment by Saviodellano** [comment]
Infelizmente o erro continua, creio que seja a atualização do composer

**Comment by Saviodellano** [comment]
Resolvi, removento toda a instalação e reinstalando o app.
