### ISSUE TITLE
Bug Impressão 2 Folhas

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#1992]
Testando essa versão na hora de imprimir sai a **via cliente** e a **via empresa**, mas na via da empresa sai um valor somado com a via do cliente. segue print. e também fiz o teste com desconto, ele soma um valor de desconto que no final fica o valor correto, 
bug bem louco.

![2022-12-08_18h58_06](https://user-images.githubusercontent.com/72340074/206577162-2d712252-8d8e-48ea-b5b9-20fad679968c.png)

![2022-12-08_18h58_13](https://user-images.githubusercontent.com/72340074/206577201-9fbc7573-9549-4573-9a9a-37af592446bc.png)

**Comment by willph** [comment]
Já corrigi. Está na PR #1991

**Comment by willph** [comment]
Só aguardar aprovar.

**Comment by willph** [comment]
Baixar o código MASTER e testar Novamente. 

Já foi corrigido.

Qualquer coisa só volta e comunicar
