### ISSUE TITLE
Map_OS Ocupando espaço em excesso no servidor

### ISSUE THREAD

**Issue by diamantes-eletronicos** [RamonSilva20/mapos#1993]
Pessoal, minha instalação do Map_OS está ocupando 100% de espaço em disco do meu servidor. Da ultima vez que isso aconteceu eu excluí a pasta e instalei novamente, agora aconteceu novamente. O que pode estar causando esse problema?

**Comment by N01062561978** [comment]
É só apagar os logs na pasta logs

**Comment by diamantes-eletronicos** [comment]
Obrigado pela resposta!
