### ISSUE TITLE
Mensagem de cadastro em todas as telas

### ISSUE THREAD

**Issue by Felipeb96** [RamonSilva20/mapos#1996]
Boa tarde. Toda vez que faço um lançamento de despesa, ou algo do tipo. A mensagem aparece que foi lançada com sucesso, porem, se eu for para outra pagina, a mesma mensagem fica aparecendo, ela não some depois que cadastrada/editado, etc... A versão do mapos é a recente..

**Comment by willph** [comment]
tentei reproduzir o erro aqui, porem não aconteceu.

teria um vídeo mostrando?

eu adicionei um lançamento e fui para outro menu, e nada ocorreu.

Por favor baixar versão mais recente, o MASTER e testar.
Obrigado!
