### ISSUE TITLE
Vendas (paginação)

### ISSUE THREAD

**Issue by davidpvilaca** [RamonSilva20/mapos#2]
Estava testando e quando cadastrei bastante vendas vi que não estava paginando e com isso escondendo muitas vendas, que por consequência não dava mais pra visualizá-las, editá-las e/ou excluí-las. Ocasionado por não ter cadastrado nenhuma ordem de serviço.

Problema:
-mapos/application/controllers/vendas.php (linha 39)
   $config['total_rows'] = $this->vendas_model->count('os');

O controller é da página de vendas, então o count deveria ser de 'vendas'.

**Comment by RamonSilva20** [comment]
Valeu amigo. Corrigido.
