### ISSUE TITLE
OS - Serviços

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#20]
Cobro por hora técnica (simples, avançada, complexa, etc), hoje não tenho como gerar uma OS realmente de serviços e sim por produto, no serviço precisaria de quantidade para o cálculo do valor total assim como é feito com os produtos.
Obrigado.

**Comment by hardbrasil** [comment]
Para Uso Atual Crie no cadastro de serviços as horas exemplo hora técnica com deslocamento para equipamento x e coloque o valor da hora. quando lançar as horas ele dará o Total da OS exemplo a hora a 100 lança 5 horas ele vai colocar 500,00 no valor de serviços.
