### ISSUE TITLE
Hostgator

### ISSUE THREAD

**Issue by phaelcoura** [RamonSilva20/mapos#2001]
Ola galera estou subindo o Mapos para o hostgator, porem ele nao le a pasta Sistema mesmo com o composer instalado, achei um link que fala que voce tem que adicionar uma pasta Vendor ao sistema para ele le, porem o video e do mapos 4 , quando fiz isso ele bugou, alguem sabe se existe esses arquivos para nova atualização ou tem alguma outra forma de fazer isso ?

**Comment by willph** [comment]
No site do MapOs.com.br você pode fazer o download já com a pasta vendor.
Aí você pode pegar apenas a pasta vendor e juntar ao seu projeto.

**Comment by phaelcoura** [comment]
obrigado

**Comment by phaelcoura** [comment]
> Conseguiu?
> 
> Caso qualquer outra dúvida só falar que retorno e reabro a issues

nao consegui, fazendo sem o arquivo do seite ele instala tudo, mais ai da a mensagem que nao reconhece a pasta sistem, quando baixei o arquivo do site que ele ja contem a pasta vendor, ele esta dando erro 
![image](https://user-images.githubusercontent.com/114200092/209481721-98cc1bb6-8449-4d66-95b5-504adb680b19.png)

**Comment by willph** [comment]
> > Conseguiu?
> > Caso qualquer outra dúvida só falar que retorno e reabro a issues
> 
> nao consegui, fazendo sem o arquivo do seite ele instala tudo, mais ai da a mensagem que nao reconhece a pasta sistem, quando baixei o arquivo do site que ele ja contem a pasta vendor, ele esta dando erro ![image](https://user-images.githubusercontent.com/114200092/209481721-98cc1bb6-8449-4d66-95b5-504adb680b19.png)

Foi atualização? 
Instalação feita do zero?

**Comment by phaelcoura** [comment]
> > > Conseguiu?
> > > Caso qualquer outra dúvida só falar que retorno e reabro a issues
> > 
> > 
> > nao consegui, fazendo sem o arquivo do seite ele instala tudo, mais ai da a mensagem que nao reconhece a pasta sistem, quando baixei o arquivo do site que ele ja contem a pasta vendor, ele esta dando erro ![image](https://user-images.githubusercontent.com/114200092/209481721-98cc1bb6-8449-4d66-95b5-504adb680b19.png)
> 
> Foi atualização? Instalação feita do zero?

Instalação feita do zero, baixei o arquivo no site do mapos, e instalei , instalei o composer via putty, e ja estou com liberação do ssh

**Comment by willph** [comment]
> > > > Conseguiu?
> > > > Caso qualquer outra dúvida só falar que retorno e reabro a issues
> > > 
> > > 
> > > nao consegui, fazendo sem o arquivo do seite ele instala tudo, mais ai da a mensagem que nao reconhece a pasta sistem, quando baixei o arquivo do site que ele ja contem a pasta vendor, ele esta dando erro ![image](https://user-images.githubusercontent.com/114200092/209481721-98cc1bb6-8449-4d66-95b5-504adb680b19.png)
> > 
> > 
> > Foi atualização? Instalação feita do zero?
> 
> Instalação feita do zero, baixei o arquivo no site do ma


Do site github ou MapOs.com.br?

**Comment by phaelcoura** [comment]
Tentei pelas duas formas, do site do mapos deu este erro que enviei o print
Pelo Github ele não acha a pasta sistem aí vi que teria que colocar a pasta vendor , mas quando fiz isso ele também deu um erro , então não consegui de nenhuma forma

**Comment by willph** [comment]
> Tentei pelas duas formas, do site do mapos deu este erro que enviei o print Pelo Github ele não acha a pasta sistem aí vi que teria que colocar a pasta vendor , mas quando fiz isso ele também deu um erro , então não consegui de nenhuma forma

Você subiu os arquivos via terminal ou via gerenciador de arquivos? 
Para subir os arquivos? 
Deu as permissões aos arquivos?

**Comment by phaelcoura** [comment]
> > Tentei pelas duas formas, do site do mapos deu este erro que enviei o print Pelo Github ele não acha a pasta sistem aí vi que teria que colocar a pasta vendor , mas quando fiz isso ele também deu um erro , então não consegui de nenhuma forma
> 
> Você subiu os arquivos via terminal ou via gerenciador de arquivos? Para subir os arquivos? Deu as permissões aos arquivos?

Fiz tudo pelo Cpainel, entrei no gerenciador de ariquivos criei uma pasta dentro do public_html , joguei o zip, extrai, dai entrei no link, abriu a instalação do mapos
La coloquei o banco de dados o loguin e a senha para acessar
loguin e senha do progama , e link
Ai depois instalei o composer via putty pelo ip do hostgator, ate ai foi tudo certinho, ai depois de finalizado ele ainda da esse erro

**Comment by willph** [comment]
Colocou o endereço completo na hora da instalação?

**Comment by phaelcoura** [comment]
> Colocou o endereço completo na hora da instalação?

Sim copiei direto da barra, desde o http://  ate o final
O usuario do banco de dados tambem
ip tb

**Comment by willph** [comment]
https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

Nosso grupo no Whatsapp, tem uma galera que se ajuda entre si.
Também estou lá.

**Comment by phaelcoura** [comment]
> https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl
> 
> Nosso grupo no Whatsapp, tem uma galera que se ajuda entre si. Também estou lá.

boa ia pergntar se tinha algum lugar pra falar com voces, vou entrar la

**Comment by willph** [comment]
Resolvido com ajuda de @rodrigo3d Rodrigo, na comunidade MapOs Whatsapp.

**Comment by willph** [comment]
Resolvido com ajuda de @Rodrigo-Paz, na comunidade MapOs Whatsapp.
