### ISSUE TITLE
Etiqueta não funciona

### ISSUE THREAD

**Issue by Gabriellhantol** [RamonSilva20/mapos#2002]
Olá, infelizmente testei todos modelos de código de barras e o leitor não ler nenhum.
Testei 3 modelos de leitores e vários tipos de papel.

Podem verificar esse bug ? seria muito bom ler as etiquetas.

**Comment by willph** [comment]
Testou qual tipo de código de barra.

EAN13?

**Comment by willph** [comment]
Testei via celular e está ok.

Não tenho leitor de código de barra daquele que tem em supermercados.

Cuidado com reflexos de luz de led perto do leitor.

**Comment by Gabriellhantol** [comment]
Olá bom dia, fiz alguns testes com o app também. usei 2 APP.

EAN-13 - LER PELO APP MAS OS NÚMEROS NÃO BATEM E NÃO LER PELO SCARNER DE MÃO
UPCA - LER PELO APP MAS OS NÚMEROS NÃO BATEM E NÃO LER PELO SCARNER DE MÃO
CODEBAR - LER TUDO ERRADO PELO APP E NÃO LER PELO SCARNER DE MÃO

CODE128 - LER CERTINHO PELO APP E PELO SCARNER DE MÃO
CODE 93 - LER CERTINHO PELO APP  NÃO LER PELO SCARNER DE MÃO
QRCODE - LER CERTINHO PELO APP
