### ISSUE TITLE
A pagina de lançamentos da erro depois de atualizar a ultima versão.

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#2003]
** Descreva o bug **
A pagina de lançamentos da erro depois de atualizar a ultima versão.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

![Captura de tela 2022-12-15 110405](https://user-images.githubusercontent.com/68141004/207881279-5b060bcf-0683-458e-a3dd-eb5c185febd2.png)

**Comment by willph** [comment]
> ** Descreva o bug ** A pagina de lançamentos da erro depois de atualizar a ultima versão.
> 
> ** Capturas de tela ** Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
> 
> ![Captura de tela 2022-12-15 110405](https://user-images.githubusercontent.com/68141004/207881279-5b060bcf-0683-458e-a3dd-eb5c185febd2.png)

Atualizou o banco de dados?

Tem um botão na configuração que atualiza o banco de dados

**Comment by MarceloGrass** [comment]
Atualizei sim. Sempre faço isso depois de uma atualização do sistema.

**Comment by willph** [comment]
Qual versão estava usando?

**Comment by MarceloGrass** [comment]
4.38.0 a anterior.

**Comment by willph** [comment]
Irei testar, já já retorno.
Baixou a versão master ou invés da 4.39?

**Comment by MarceloGrass** [comment]
Atualizei pelo próprio sistema em atualizar Mapos.

**Comment by MarceloGrass** [comment]
Somente resolveu instalar do zero no hosting a versão master e importar a base de dados. A atualização pelo próprio sistema não deu certo ficou com vários erros. Felizmente esta resolvido, o sistema está muito bom. Parabéns e obrigado pelas respostas.

**Comment by willph** [comment]
> Somente resolveu instalar do zero no hosting a versão master e importar a base de dados. A atualização pelo próprio sistema não deu certo ficou com vários erros. Felizmente esta resolvido, o sistema está muito bom. Parabéns e obrigado pelas respostas.

Obrigado.

O único botão que funciona sem bug é o atualiza banco de dados.
O botão de atualizar o sistema está instável. "Quebrando os arquivos"
