### ISSUE TITLE
Gerência Net com problema chave de produção 

### ISSUE THREAD

**Issue by Naldotec** [RamonSilva20/mapos#2004]
Bom dia! Verifiquei erro no pagamento com gencia Net usando a chave de produção, na chave homologação funciona normal, e gostaria de usar pois o pagamento via link seria muito ultil para os clientes usar a forma de pagamento que ele desejar

**Comment by willph** [comment]
> Bom dia! Verifiquei erro no pagamento com gencia Net usando a chave de produção, na chave homologação funciona normal, e gostaria de usar pois o pagamento via link seria muito ultil para os clientes usar a forma de pagamento que ele desejar

Alterou o tipo. De teste para produção?

**Comment by willph** [comment]
Na linha 9 do arquivo `payment_gateways.php`  de `false`, alterar para `true`
