### ISSUE TITLE
Alterar Status da OS em Massa

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#2005]
Olá pessoal blz!
vou deixar um código abaixo, quem tem muitas OS e deseja alterar o status sem ter que editar a OS
é só seguir o passo a passo abaixo ok!

![os_massa](https://user-images.githubusercontent.com/35280835/208133041-5ac3fd09-19d2-4649-a5dd-7858d8c9f766.JPG)

`/*  Em Model  Os_model.php   */

/* linha: 152 a 159 */

public function editMassIn($table, $data, $fieldWhere, $conds)
{
    $this->db->where_in($fieldWhere, $conds);
    $this->db->update($table, $data);

    if ($this->db->affected() >= 0) {
        return true;
    }

    return $this->db->last_query();
}

------------------------------------------------------------------------------------------------------------------------------------
/*Controllers  Os.php   */

/* linha: 281 a 310 */

public function alterarCheckbox(){

 if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'eOs')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para editar Status.');
            redirect('os/gerenciar');
        }

     $ids =  $this->input->post('os[]');
    $numRegs = count($ids);

    if($numRegs > 0){

        $data['status'] = $this->input->post('status');

        $atualiza = $this->os_model->editMassIn('os', $data, 'idOs',$ids);

        if($atualiza === true){
            $this->session->set_flashdata('success', 'Status Atualizado(s)!');
        }else{
           $this->session->set_flashdata('error', 'Erro ao atualizar chamados!<br>'.$atualiza);
        }

    } else {
        $this->session->flashdata('error', 'Nenhum item foi marcado!');
    }

    redirect('os/gerenciar');

}

---------------------------------------------------------------------------------------------------------------------------------------------
/*Views  os.php  */

/*linha: 41 a 64 */

<div class="span12" style="margin-left: 0">
<form name="form1" id="form1" method="post" action="<?php echo base_url(); ?>index.php/os/alterarCheckbox" onSubmit="return valida_campos();">
  <?php echo form_hidden('idOs',$result->idOs) ?>

  <label for="status" class="control-label"></label>
  <div class="controls">
    <select required class="span3" name="status" id="status">
      <option value="" disabled selected>Alterar Status em Massa</option>
      <option <?php if ($result->status == 'Aberto') { echo 'selected'; } ?> value="Aberto">Aberto</option>
      <option <?php if ($result->status == 'Faturado') { echo 'selected'; } ?> value="Faturado">Faturado</option>
      <option <?php if ($result->status == 'Negociação') { echo 'selected'; } ?> value="Negociação">Negociação</option>
      <option <?php if ($result->status == 'Em Andamento') { echo 'selected'; } ?> value="Em Andamento">Em Andamento</option>
      <option <?php if ($result->status == 'Orçamento') { echo 'selected'; } ?> value="Orçamento">Orçamento</option>
      <option <?php if ($result->status == 'Finalizado') { echo 'selected'; } ?> value="Finalizado">Finalizado</option>
      <option <?php if ($result->status == 'Cancelado') { echo 'selected'; } ?> value="Cancelado">Cancelado</option>
      <option <?php if ($result->status == 'Aguardando Peças') { echo 'selected'; } ?> value="Aguardando Peças">Aguardando Peças</option>
      <option <?php if ($result->status == 'Aprovado') { echo 'selected'; } ?> value="Aprovado">Aprovado</option>
    </select>
     <span>
    <button type="submit" class="btn" style="padding-top: px;border-top-width: px;margin-bottom: 9px;"><i class="fas fa-sync-alt"></i></button>
    </span>

 <input class="span6" type="hidden" name="grupo_os" id="grupo_os" />
  </div>
  </div>
  

  -----------------------------------------------------------------------------------------------------------------------------------------------

/*linha: 77 */
<th><input name="todos" id="todos" type="checkbox" value="todos" onchange="if(this.checked == true){marcacao_generico('form1',1,'os[]','grupo_os');}else{marcacao_generico('form1',0,'os[]','grupo_os');}" /> </th>

  /* Nao esquecer de fechar o form depois que inserir o input checkbox ( </form>)*/
----------------------------------------------------------------------------------------------------------------------------------------------------
/*linha: 139 */
 echo '<td><input type="checkbox" name="os" value="'. $r->idOs. '" onclick="acao_coleta_generico(\''. $r->idOs. '\', \'grupo_os\' );"></td>';

 ---------------------------------------------------------------------------------------------------------------------------------------------------
/*linha: 174 a 191 */

 <?PHP
if(isset($_POST['grupo_os']))
  {
    $os = '';
    $os = explode(",",str_replace(':','',$_POST['grupo_os']));
    ?>
  <br>
  <?PHP
    for($i = 0;$P < count($os) - 1; $i++)
      {
        echo($os[$i]);
        echo "<br>";
      }
    ?>
    <hr>
    <?PHP
  }
?>

<script>
    select: required: invalid {
        color: gray;
    }
    option[value = ""][disabled] {
        display: none;
    }
    option {
        color: black;
    }
</script>

--------------------------------------------------------------------------------------------------------------------------------------------------
 /*linha: 212 a 239 */
 <script type="text/javascript">
     function acao_coleta_generico(valor, campo_alvo) {
          if (document.getElementById(campo_alvo).value.indexOf(':' + valor + ':,') == -1) {
            document.getElementById(campo_alvo).value += ':' + valor + ':,';
          } else {
            var grupo = document.getElementById(campo_alvo).value;
            grupo = grupo.replace(':' + valor + ':,', '');
            document.getElementById(campo_alvo).value = grupo;
          }
        }

        function marcacao_generico(formulario, opcao, campo, campo_alvo) {
          for (i = 0; i < document.getElementById(formulario).elements.length; i++) {
            if (document.getElementById(formulario).elements[i].name == campo) {
              if (document.getElementById(formulario).elements[i].checked != opcao) {
                document.getElementById(formulario).elements[i].checked = opcao;
                acao_coleta_generico(document.getElementById(formulario).elements[i].value, campo_alvo);
              }
            }
          }
        }

		 function valida_campos() {
          if (document.getElementById('grupo_os').value == '') {
            alert('Por favor, selecione ao menos um item.');
            return false;
          }

        }
		 </script>
`

**Comment by ramostriker** [comment]
o código do view os.php está correto?
