### ISSUE TITLE
Venda do Sistema

### ISSUE THREAD

**Issue by ruanitto** [RamonSilva20/mapos#2026]
Boa tarde, um tempo atrás um cliente me pediu ajuda com a instalação de um sistema de Ordem de serviço que ele comprou em um site, e recentemente ele me pediu pra verificar alguns erros que estavam acontecendo no momento do login.

Estava analisando o código, e descobri que é o MapOS.

Não sei se são vocês que comercializam ele, mas caso não seja e não estejam tendo nenhum retorno financeiro sobre a venda, aqui está o link:

https://temdetudoprogramas.com.br/item/sistema-web-para-ordem-de-servico-script-php

**Comment by eraiely** [comment]
Realmente tem várias pessoas editando o mapOS e vendendo, afinal qual a licença do mapOS?
Por que se não for OpenSource deve ser crime vender sem autorização do dono, uma pesquisa rápida no YouTube e acha várias pessoas vendendo como se fossem delas

**Comment by Gabrielhantoll** [comment]
https://github.com/RamonSilva20/mapos/blob/master/LICENSE.txt
