### ISSUE TITLE
Bug nas mensagens de cadastro, e edição

### ISSUE THREAD

**Issue by Felipeb96** [RamonSilva20/mapos#2027]
Boa tarde, sempre que executado alguma função de cadastro ou alteramento, aparece a mensagem de sucesso, porem quando vai para outra aba do sistema , a mensagem permanece 

![Captura de tela 2023-01-06 152301](https://user-images.githubusercontent.com/86575492/211074770-766e3579-24b0-46e6-9fbe-0ca68f1d8756.png)

**Comment by N01062561978** [comment]
Verifique se a versão do seu PHP configurado no servidor, está acima da 8, se for, pode ser esse o problema

**Comment by Felipeb96** [comment]
Bom dia, muito obrigado. Deu certo

**Comment by GeniIson** [comment]
eu resolvei adicionando 

 $_SESSION["success"]=0;
 $_SESSION["error"]=0;

No arquivo chamado: conteudo.php





<div id="content">

  <div id="content-header">
   <div></div>
      <div id="breadcrumb">
        <a href="<?= base_url() ?>" title="Dashboard" class="tip-bottom"> Início</a>
        <?php if ($this->uri->segment(1) != null) { ?>
            <a href="<?= base_url() . 'index.php/' . $this->uri->segment(1) ?>" class="tip-bottom" title="<?= ucfirst($this->uri->segment(1)); ?>">
              <?= ucfirst($this->uri->segment(1)); ?>
            </a>
          <?php if ($this->uri->segment(2) != null) { ?>
            <a href="<?= base_url() . 'index.php/' . $this->uri->segment(1) . '/' . $this->uri->segment(2) . '/' . $this->uri->segment(3) ?>" class="current tip-bottom" title="<?= ucfirst($this->uri->segment(2)); ?>">
              <?= ucfirst($this->uri->segment(2));
          } ?>
            </a>
          <?php } ?>
      </div>
    </div>
    <div class="container-flu">
      <div class="row-fluid">
        <div class="span12">
          <?php if ($var = $this->session->flashdata('success')): ?><script>swal("Sucesso!", "<?php echo str_replace('"', '', $var); ?>", "success");</script><?php endif; ?>
          <?php if ($var = $this->session->flashdata('error')): ?><script>swal("Falha!", "<?php echo str_replace('"', '', $var); ?>", "error");</script><?php endif; ?>
          <?php if (isset($view)) {
              echo $this->load->view($view, null, true);
          } 
          $_SESSION["success"]=0;
          $_SESSION["error"]=0;
        
          ?>
        </div>
      </div>
    </div>
  </div>

**Comment by GeniIson** [comment]
<?php      <div id="content">

  <div id="content-header">
   <div></div>
      <div id="breadcrumb">
        <a href="<?= base_url() ?>" title="Dashboard" class="tip-bottom"> Início</a>
        <?php if ($this->uri->segment(1) != null) { ?>
            <a href="<?= base_url() . 'index.php/' . $this->uri->segment(1) ?>" class="tip-bottom" title="<?= ucfirst($this->uri->segment(1)); ?>">
              <?= ucfirst($this->uri->segment(1)); ?>
            </a>
          <?php if ($this->uri->segment(2) != null) { ?>
            <a href="<?= base_url() . 'index.php/' . $this->uri->segment(1) . '/' . $this->uri->segment(2) . '/' . $this->uri->segment(3) ?>" class="current tip-bottom" title="<?= ucfirst($this->uri->segment(2)); ?>">
              <?= ucfirst($this->uri->segment(2));
          } ?>
            </a>
          <?php } ?>
      </div>
    </div>
    <div class="container-flu">
      <div class="row-fluid">
        <div class="span12">
          <?php if ($var = $this->session->flashdata('success')): ?><script>swal("Sucesso!", "<?php echo str_replace('"', '', $var); ?>", "success");</script><?php endif; ?>
          <?php if ($var = $this->session->flashdata('error')): ?><script>swal("Falha!", "<?php echo str_replace('"', '', $var); ?>", "error");</script><?php endif; ?>
          <?php if (isset($view)) {
              echo $this->load->view($view, null, true);
          } 
          $_SESSION["success"]=0;
          $_SESSION["error"]=0;
         // echo 'Atualizado--'.$_SESSION["success"];
          ?>
        </div>
      </div>
    </div>
  </div>

?>
