### ISSUE TITLE
Desconto na venda

### ISSUE THREAD

**Issue by leonardoleao** [RamonSilva20/mapos#203]
Olá,

Estou usando o sistema na versão 3.1.12, achei excelente, alias parabéns pelo Trabalho. Só senti falta de 1 coisa, na loja em que trabalho utilizamos muito desconto, principalmente para clientes mais "fieis" ou mesmo para cobrir uma oferta do concorrente. Seria possível adicionar um botão ou campo "Desconto" na tela de fechamento da venda?

Muito Obrigado!.

**Comment by RamonSilva20** [comment]
Olá. Esta funcionalidade será adicionada na próxima versão. Grato.
