### ISSUE TITLE
Etiquetas sem código de barras

### ISSUE THREAD

**Issue by N01062561978** [RamonSilva20/mapos#2030]
Boa noite, não estou conseguindo imprimir o cód de barras dos produtos. O que pode ser?

![Sem título](https://user-images.githubusercontent.com/67173632/211225473-9a4a7001-4af9-48d4-9164-e07f5bf1d9b0.jpg)

**Comment by willph** [comment]
O código de barra está salvo no banco de dados?

**Comment by willph** [comment]
Qual formato que está tentando? 

Aqui está normal.

**Comment by N01062561978** [comment]
Tem alguns códigos salvos no banco, isso porque em uma versão mais antiga eu gerei etiquetas para 5 produtos e salvou normal . Conseguia ler o código, o nome e o preço. mas agora só lê o código de barras pelo app do smart fone. E não gera mais nenhum código de barras no intervalo, aparece somente dessa forma aí que mandei o print

**Comment by willph** [comment]
Mas qual padrão está tentando gerar? EAN13....

**Comment by willph** [comment]
Qual o número que está dando erro, pra colocar aqui no meu e simular

**Comment by N01062561978** [comment]
Obrigado por responder, tentei todos os formatos, verifiquei se existia algum erro no banco, instalei do zero e nada, tanto código quanto banco

**Comment by willph** [comment]
Mande o código de barras salvo no seu BD para eu simular aqui. Os que deram falha.

**Comment by N01062561978** [comment]
INSERT INTO `produtos` (`idProdutos`, `codDeBarra`, `descricao`, `unidade`, `precoCompra`, `precoVenda`, `estoque`, `estoqueMinimo`, `saida`, `entrada`) VALUES
(214, '262373464', 'Filtro com regulador de ar', 'UNID', '67.00', '90.00', '8872.3', 1, 1, 1),
(215, '978073562153', 'Instalação de cadeira odontológica TOP nova', 'UNID', '250.00', '250.00', '19', 1, 1, 1),
(216, '12345678', 'Válvula de retenção modelo Shulz', 'UNID', '74.00', '74.00', '19', 1, 1, 1);

**Comment by willph** [comment]
Aqui no meu todos 3 funcionaram. 

Testei os 3 primeiros tipo de padrão nos 3 código de barras que você mencionou.

**Comment by Marcio2820** [comment]
No meu também não gera o código de barras na etiqueta, clico em "gerar etiqueta", coloco o intervalo entre elas e só gera o nome, o cód. e preço sem o código de barras. Estou fazendo algo errado, tem um tutorial para gerar? A versão que estou usando é a última

Fica igual ao do colega:
![image](https://user-images.githubusercontent.com/123276470/213893903-554fbb1b-cb46-4597-b653-768aae967aa2.png)

**Comment by willph** [comment]
Qual a versão que estão usando?

**Comment by Marcio2820** [comment]
Bom dia, a minha versão é a 4.38.0

**Comment by Marcio2820** [comment]
Bom dia, a minha versão do Mapos é a 4.38.0. e estou tentando gerar etiqueta EAN-13, mas testei com todas, e nenhuma da certo.

**Comment by willph** [comment]
A versão que eu testei é a mais recente. 
Código Master aqui do github.
