### ISSUE TITLE
Impressão térmica em duas folhas

### ISSUE THREAD

**Issue by N01062561978** [RamonSilva20/mapos#2034]
Srs na impressão térmica em duas folhas o resultado da soma total e por item, da folha 02 está multiplicando por 2, tentei alterar o nome das variáveis mas não adiantou!

![image](https://user-images.githubusercontent.com/67173632/212558646-479a0867-dcbd-4b0b-8289-f79f98b41a44.png)

**Comment by willph** [comment]
Já sei o que é.
O código é o mais recente? 

Porque tenho a impressão de que já tinha corrigido isso.
Irei analisar.

**Comment by willph** [comment]
Já já envio a correção

**Comment by willph** [comment]
Pronto corrigido o arquivo. 

Para atualiza basta pegar o arquivo https://github.com/RamonSilva20/mapos/blob/master/application/views/os/imprimirOsTermica.php

E sobreescreve o arquivo da sua pasta.

Pode ser copiando e colando também. 

Testa aí e depois me diz se está ok Aí no seu também.

**Comment by andremp15** [comment]
Oi primeiramente agradeço a todos envolvidos nesse excelência sistema. Tem um problema na parte de vender produtos, quando adicionar a data da venda a tabela fica por trás de uma aba conforme mostra a imagem, alguém pode me ajudar a resolver esse problema fazendo favor.

![Screenshot_20230115_231828_Chrome.jpg](https://user-images.githubusercontent.com/117945999/212585267-a10c69a5-d875-4d00-bf8e-6fa17d160b3c.jpg)
