### ISSUE TITLE
Versão estavel

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#2035]
Boa noite! Gostaria de saber qual versão que eu possa fazer download que está mais completa? Pois tem varia versões aqui para download, tem master dentre outras.

Obrigado

**Comment by willph** [comment]
Boa noite.

Acredito que a versão Master.

**Comment by acinformatica2004** [comment]
Instalei, em lançamento da erro e não cadastra o lançamento financeiro.

**Comment by willph** [comment]
Cadastrou o emitente? 

Poderia enviar por favor o print ou vídeo?

**Comment by acinformatica2004** [comment]
Tem sim. 
![IMG_20230115_204312](https://user-images.githubusercontent.com/29789157/212573978-3e53f338-c870-4cea-a601-82034b8abe98.jpg)
![IMG_20230115_204318](https://user-images.githubusercontent.com/29789157/212573984-974a9db6-1e00-494e-bfd6-15248a4c715a.jpg)

**Comment by willph** [comment]
Instalação feita do zero ou atualização?

**Comment by acinformatica2004** [comment]
Feita do zero

**Comment by willph** [comment]
> Feita do zero

Testei a versão Master e não vi esse erro.

https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip

**Comment by acinformatica2004** [comment]
Substitui os arquivos, mesmo assim dando erro

**Comment by willph** [comment]
> Substitui os arquivos, mesmo assim dando erro

Vai em configurações sistema e atualizações e clica apenas em atualiza banco de dados só pra testar

**Comment by willph** [comment]
Php 7.4?
Só pra saber se está igual o meu.

**Comment by acinformatica2004** [comment]
Atualizei o banco e deu certo, muito obrigado

**Comment by acinformatica2004** [comment]
Abri uma nova questão, será que pode me ajudar. Vou tentar explicar, eu tenho uma versão muito antiga do mapos, usa php 5.6, porém tô migrando pra nova, e tem modificoes que fui fazendo só longo do tempo, uma delas seria a aba equipamentos na o s. Porém está dando erro.
