### ISSUE TITLE
Equipamentos

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#2037]
Boa noite, estou tentando colocar a aba equipamentos na ordem de serviço e está dando o seguinte erro, será que podem me ajudar 

![IMG_20230115_215325](https://user-images.githubusercontent.com/29789157/212577056-d0a56705-2dfb-4250-9d6c-f0f90c225fc8.jpg)

Obrigado

**Comment by willph** [comment]
Se os dedos requisitados não estiver vindo do banco de dados para o controller e do controller para a View, infelizmente não irá funcionar.

**Comment by acinformatica2004** [comment]
Modifiquei os arquivos na pasta Controller, modelo e views conforme meu sistema antigo, e também adicionei a tabela no banco de dados

**Comment by acinformatica2004** [comment]
A issue e a 1410 que inseri no meu código antigo e estou tentando colocar no novo.

**Comment by willph** [comment]
Da pra levar, porém precisará alterar todos os arquivos que alterou naquela epoca.

Isso incluí banco de dados, da um trabalhinho. Mas funciona tranquilamente.
