### ISSUE TITLE
erro em desconto e faturar

### ISSUE THREAD

**Issue by SSCARDUA** [RamonSilva20/mapos#2045]
esta versao apresenta erro qnd quero aplicar desconto de algum produti, venda, os, e no fechamento de vendas e os pra faturar apresenta erro.
![image](https://user-images.githubusercontent.com/123421917/214164121-67233691-78e2-4048-aece-ba6f8f4cbcea.png)

**Comment by fatarellibtos** [comment]
Galera uma dica que deu certo aqui comigo foi fazer a atualização do BD - banco de dados pelo sistema MAPOS pelo microsoft edge, pelo google chrome o sistema da ok más não atualiza o BD corretamente, abri o sistema pelo Edge atualizei o BD e funcionou normalmente, deve ter um bug no chrome que não atualiza corretamente
