### ISSUE TITLE
OAuth2.0 Autenticação em 02 fatores Microsoft

### ISSUE THREAD

**Issue by gilbertoalmeida16** [RamonSilva20/mapos#2046]
Fizemos uma instalação do MapOS em um servidor hostinger, o qual o mesmo está apontando o serviço de emails para a microsoft, sendo assim passa a microsoft a gerenciar qualquer aplicação que queira enviar emails a partir dele. 

Sendo assim é necessario configurar o oAuth 2.0 (autenticador microsoft)

Gostaria de saber se já tem essa ferramenta para o sistema MapOS, para assim gerar as chaver e keys que dentro do ambiente azure configuramos para disparar o emails do sistema, pois somente se configurar ele normalmente no email.php com as informações da microsoft ele é barrado por não ter o Oauth 2.0 com sua chaves apontando para a aplicação.

Gostaria de saber se já há essa aplicação tanto para local como online.

**Comment by almron** [comment]
Se uma integração com oAuth 2.0 é muito complicado, talvez uma integração com LDAP seja mais fácil. Existem alguns serviços em que você pode integrar o Google Workspace, Microsoft Autenticator e LDAP no mesmo lugar. Talmbém estou precisando de algo assim.
