### ISSUE TITLE
E-mails Automáticos Não Chegam a Outros Provedores de E-mail

### ISSUE THREAD

**Issue by barretowiisk** [RamonSilva20/mapos#2047]
** Descreva o bug **
Quando disparado e-mails pelo MapOS chegam apenas em endereços que são do mesmo provedor de e-mail (dominio.com.br) porém em outros domínios ou provedores conhecidos (Gmail e Outlook) não chegam na caixa de entrada.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Configurei o arquivo email.php conforme abaixo:
$config['protocol']         = 'smtp';
$config['smtp_host']        = 'mail.dominio.com.br';
$config['smtp_crypto']      = 'ssl'; // tls or ssl
$config['smtp_port']        = 465;
$config['smtp_user']        = 'noreply@dominio.com.br';
$config['smtp_pass']        = 'SenhaSegura';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

Quando status fica como enviado, apenas o endereço do Emitente noreply@dominio.com.br recebe o e-mail, e-mail do cliente usuario@gmail.com não recebe o e-mail.

** Capturas de tela **
![image](https://user-images.githubusercontent.com/45976190/214622984-ccd6e6cd-bb9d-4b53-8401-68f74699fafd.png)
![image](https://user-images.githubusercontent.com/45976190/214623089-f992d84d-f320-47a7-bc84-770d815ca6df.png)
![image](https://user-images.githubusercontent.com/45976190/214623146-f0963b25-9607-4ec0-bef5-299e0d47461c.png)

** Desktop (preencha as seguintes informações): **
1. Servidor Linux Ubuntu Server 22.04
2. Apache/2.4.52 (Ubuntu)
3. PHP 7.4.33

** Contexto adicional **
Realizei testes com o protocolo SMTPS e com portas sem SSL/TLS (587), porém o resultado é sempre o mesmo.

**Comment by willph** [comment]
a sua porta de envio SMTP esta liberada?
usa VPS ou hospedagem?

Em qua., 25 de jan. de 2023 às 13:41, Barreto ***@***.***>
escreveu:

**Comment by barretowiisk** [comment]
Boa noite,
Sim, não existe problema de firewall, por que como mencionei o e-mail é enviado para a mesma hospedagem, só não envia para outros.
Estou usando uma maquina com Ubuntu Server instalado, conforme as especificações abaixo. Essa maquina pode ser acessada por um IP Publico e o e-mail é da hospedagem HostGator.

** Desktop (preencha as seguintes informações): **
Servidor Linux Ubuntu Server 22.04
Apache/2.4.52 (Ubuntu)
PHP 7.4.33

**Comment by gilbertoalmeida16** [comment]
olá amigo coloque um s no final so smtp assim:
$config['protocol'] = 'smtps';

**Comment by almron** [comment]
Meu amigo @gilbertoalmeida16. Essa sua dica resolveu esse problema que eu tinha por anos. Não sei se para o @barretowiisk funcionou, mas aqui funcionou perfeitamente.

**Comment by barretowiisk** [comment]
Então, como comentei eu já havia testado com smtp e smtps e não surtiu efeito, conforme falei, estou usando o PHP e MySQL rodando em um servidor Linux Ubuntu fora do IP da hospedagem do e-mail.

**Comment by willph** [comment]
> Então, como comentei eu já havia testado com smtp e smtps e não surtiu efeito, conforme falei, estou usando o PHP e MySQL rodando em um servidor Linux Ubuntu fora do IP da hospedagem do e-mail. Numa instalação na Hospedagem HostGator (mesma do email) funciona com smtps, porém estou tendo problemas para rodar a extensão PHP-GD, mas isso estou vendo com o suporte, por isso queria usar no meu servidor próprio.

Então só inserir os dados do seu servidor SMTP.

A cron estando ok ele irá enviar. 
Se fica pendente provavelmente a cron não pegou

E se de falha no envio, provavelmente será na configuração do smtp

**Comment by barretowiisk** [comment]
Conforme evidências na abertura da thread, os dados estão corretos no arquivo email.php e a cron também uma vez que o e-mail é enviado para outros e-mails do mesmo domínio, só não envia para e-mail de terceiros. É disparado e fica com status de enviado.

**Comment by willph** [comment]
Se está tudo ok e não está indo, só se a porta SMTP 25 estiver bloqueada.

Essa VPS está hospedada aonde

**Comment by barretowiisk** [comment]
Trata-se de um servidor PVE físico que está disponível a um IP Público, como a hospedagem é na HostGator, não existem bloqueios de saída, e o firewall está aberto para as portas que estou utilizando até como entrada (input) e o IP da hospedagem tem acesso livre a minha Infraestrutura por que usamos a hospedagem HostGator para monitorar os links, hoje trouxe o servidor pra casa, vou fazer um teste na minha rede doméstica pra ver se algo muda... Qualquer coisa posso te mandar no zap @willph ?

**Comment by willph** [comment]
https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

Qualquer coisa estamos na comunidade MapOs no Whatsapp.

Esse teu problema tá meio complicado.

Porque você diz que está tudo ok e não está indo.

**Comment by barretowiisk** [comment]
Exatamente, estou a semanas procurando uma solução por isso abri a thread.
