### ISSUE TITLE
google bloqueando o site 

### ISSUE THREAD

**Issue by Janio1215** [RamonSilva20/mapos#2050]
Uso o sistema com ssl, mas hoje o google diz que é um site fraudulento, que tem um malware em: assents/js/validate.js
o que devo fazer ?

**Comment by willph** [comment]
> Uso o sistema com ssl, mas hoje o google diz que é um site fraudulento, que tem um malware em: assents/js/validate.js o que devo fazer ?

Tem um formulário no Google para dizer que é um falso positivo. 

Mas para isso tem que ter certeza que o código não sofreu alterações.

**Comment by almron** [comment]
Altere todas as linhas http:// para https://. Depois responda o questionário do Google para que eles façam uma nova análise do seu site.
