### ISSUE TITLE
Php 8.1

### ISSUE THREAD

**Issue by weulerandrade** [RamonSilva20/mapos#2054]
oa noite, atualizei  minha hospedagem para php 8.1 e agora nao bare o mapos, da erro, poderia me ajudar como corrigir.
![image](https://user-images.githubusercontent.com/38442400/216725617-a8d11405-b799-4e8b-9d62-cac417339aa0.png)

**Comment by willph** [comment]
Voltando o php para versão 7.4 no domínio que o MapOs está.

**Comment by weulerandrade** [comment]
na 8.1 ele nao vai funcionar?

**Comment by willph** [comment]
Por enquanto ainda não está 100% funcionando em php8

**Comment by weulerandrade** [comment]
ok obrigado

**Comment by k4k4rot0** [comment]
Olá, boa tarde e bom domingo a todos... Vocês tem previsão de quando vai estar disponível o MapOS no PHP 8.1? Porque eu tenho duas aplicações rodando em meu servidor, a primeira seria o Nextcloud, já está disponível para o PHP 8.1. E o segundo seria o MapOS... Se eu mudar a versão do PHP no meu servidor, o Nextcloud não funciona. =D
