### ISSUE TITLE
Boa noite

### ISSUE THREAD

**Issue by Felipeb96** [RamonSilva20/mapos#2057]
Estou tentando implementar uma nova função de Notas ficais para o sistema, pois estou com dificuldades, alguem teria uma API? Ou esta função no sistema?

**Comment by RamonSilva20** [comment]
Olá @Felipeb96. 

Algumas opções de APIs:

https://enotas.com.br/
https://focusnfe.com.br/

Boa sorte.

**Comment by Felipeb96** [comment]
Boa noite. Obrigado
