### ISSUE TITLE
Como adicionar uma nova tabela

### ISSUE THREAD

**Issue by GeniIson** [RamonSilva20/mapos#2066]
Pessoal como faço para adicionar nova tabela? 
Eu criei a tabela mas no sistema não intendi como ele faz para inserir os dados , desculpa a ignorância é que estou aprendendo progamar em php e não entedie esta parte.

**Comment by Felipeb96** [comment]
Boa noite, qual tabela voce criou?

**Comment by GeniIson** [comment]
Criei uma tabela chamada " fretes" com as colunas: valor,  tipo de transporte, distancia, custos.
