### ISSUE TITLE
ERRO AO ADICIONAR CHAVE PIX NO FINANCEIRO

### ISSUE THREAD

**Issue by gilbertoalmeida16** [RamonSilva20/mapos#2067]
** Descreva o bug **
Ao adicionar a chave PIX no menu sistema -. financeiro
Gera um erro
Error
Class 'Piggly\Pix\Parser' not found

Alguem já passou por isso e sabe como resolver esse erro.?

Após isso ao abrir para impressao A4 não abre tambem com o mesmo erro, ao remover a cahve no banco de dados o sistema volta ao normal porem sem aparecer o QR code ou a chave.

![image](https://user-images.githubusercontent.com/60909123/221389265-f445f017-014e-4d9f-b6b6-de0db09f099d.png)

**Comment by gilbertoalmeida16** [comment]
Pessoal eu mesmo resolvi subindo uma pasta atualizada vendor.

**Comment by leolfgomes** [comment]
gilbertoalmeida16, Boa tarde.

como vc resolveu? subi uma pasta atualizada fornecedor? onde tem essa pasta atualizada? eu não tenho fornecedor cadastrado

**Comment by gilbertoalmeida16** [comment]
Opa subi uma pasta do vendor com aas correções
