### ISSUE TITLE
Unable to load the requested file: helpers/codegen_helper.php

### ISSUE THREAD

**Issue by vinnyparker** [RamonSilva20/mapos#207]
Alguem sabe onde encontro esse arquivo? eu coloquei o arquivo da versao 3.1.9 mas nao funcionou...

**Comment by acinformatica2004** [comment]
Você pode pegar ele aqui: https://github.com/RamonSilva20/mapos/blob/master/application/helpers/codegen_helper.php

Cole ele dentro da pasta application/helpers/ com o nome codegen_helper.php

**Comment by MrKadu** [comment]
Estou tendo o mesmo erro segue a print http://prntscr.com/m6n555
