### ISSUE TITLE
Remover administradores, criação de APP e um campo de preenchimento automático

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#2072]
Queria saber como faço pra remover um usuário do sistema que acabei criando

Também se há uma possibilidade de criação de um app para android e iOS

E como faco pra toda vez que abrir uma OS, pra ela preencher o cambo de observação com uma mensagem automatica

**Comment by WillianCamargo01** [comment]
Bom dia! A remoção do usuário só é possível através do banco de dados, porém, é bom ter uma atenção para que não entre em conflito com dados já processados com nesse usuário. 
O mais recomendado seria inativar esse usuário caso esteja em modo produção.

**Comment by CarlosRezini** [comment]
@WillianCamargo01 e a parte de preenchimento automático??

**Comment by microreis** [comment]
Você teria que colocar no próprio código exemplo <textarea >Tenha um bom dia</textarea>.
Ou criar no banco de dados na configuração ao e puxar par o <textarea >
