### ISSUE TITLE
Variável indefinida $configuration

### ISSUE THREAD

**Issue by EvertonParisi** [RamonSilva20/mapos#2073]
Olá a todos, me deparei com o seguinte erro ilustrado a baixo ao tentar  instalar  o sistema em meu servidor apachce "xampp", o erro estava descrito como *Variável indefinida $configuration*. Para a correção apenas localizei onde essa váriavel estava seguindo os diretórios dos arquivos,  e a exclui. Feito isso consegui acessar e utilizar os serviços do sistema normalmente.
Gostaria de entender porque esse erro aconteceu, e se teria outra maneira de soluciona-lo.

Desde já agradeço, abraço!

![image](https://user-images.githubusercontent.com/124217396/222938317-ef2630f6-65ba-497b-907f-36c2d7ec2492.png)

**Comment by thiagosalesmd** [comment]
Eita.. esse erro acontece pq a variável não foi definida. na linha em que está a variavel, subistitua pela seguinte que vai funcionar.....
 <?= isset($configuration['app_theme']) ? (
                    $configuration['app_theme'] == 'white' 
                    ? '<img src="'. base_url() .'assets/img/logo-mapos.png">' 
                    : '<img src="'. base_url() .'assets/img/logo-mapos-branco.png">'
                  ): '<img src="'. base_url() .'assets/img/logo-mapos-branco.png">'; ?>
                </div>
