### ISSUE TITLE
Não consigo colocar a loga da minha loja no site.

### ISSUE THREAD

**Issue by JeizonSilva** [RamonSilva20/mapos#208]
Gostaria de saber como alterar a logo do site pro logo da minha loja, fiz do modo que esta explicado, de trocar a logo por uma do mesmo tamanho mais não deu certo, alguém pode me ajudar nisso?
![logo](https://user-images.githubusercontent.com/43971963/46634412-3c433280-cb27-11e8-9d1d-4b7aead4c10d.png)

**Comment by RamonSilva20** [comment]
Olá. O procedimento é este mesmo. Tente limpar o cache da página pressionando Ctrl + F5.

**Comment by RamonSilva20** [comment]
Sim, o arquivo é o assets/css/**matrix-style.css**.
