### ISSUE TITLE
Não consigo logar

### ISSUE THREAD

**Issue by ranyerschouds** [RamonSilva20/mapos#2084]
Prezados, instalei o MAPOS no Ubuntu Server 18.04, PHP 7.4.33, porém não consigo logar. Abre a tela de login e tudo, mas ao inserir o email, senha, e clicar em Acessar simplesmente não acontece nada.

**Comment by willph** [comment]
Qual a versão do seu MapOs?

Em qui, 16 de mar de 2023 18:51, ranyerschouds ***@***.***>
escreveu:

**Comment by dokti** [comment]
Mesma coisa com a instalação que eu realizei. É como se não estivesse comunicando com o banco de dados. Alguém sabe como devo proceder?

**Comment by barretowiisk** [comment]
@dokti @ranyerschouds 
por gentileza informar versão Map-OS e PHP, onde está hospedado  e quais configurações foram aplicadas.

Observação: Versão 7.4 não é mais utilizada, atualmente é instalada com PHP 8.1 ou superior, para melhor instalação (caso queriam a instalação automatizada), fiz uma instalação automatizada para Windows e Ubuntu.

https://github.com/RamonSilva20/mapos/blob/master/README.md
