### ISSUE TITLE
Pesquisa de nome "DataTable"

### ISSUE THREAD

**Issue by WillianCamargo01** [RamonSilva20/mapos#2087]
** Descreva o bug **
Nomes de clientes, servicos, produtos cadastrados que estejam em outra tabela no qual esteja selecionado "10 registros" por página o sistema não consgue encontar.

**Comment by almron** [comment]
Vá em application/models/Mapos_model.php

A partir da linha 52, procure por "$this->db->limit(200)". Coloque o valor que você acha que seja o suficiente no espaço entre parênteses, que no meu caso como exemplo, defini como 200.

A ideia é a mesma para Clientes, OS, Produtos, Serviços. Acho que isso não seria um bug, talvez seja uma feature onde possa ser definida pelo administrador em configurações. Talvez algum Dev possa implementar em uma próxima release. Pense que quanto maior o valor, maior também é o tempo de resposta. Como não utilizamos o projeto em uma aplicação de alta escalabilidade, esse tempo maior é bem imperceptível. O que vai mudar, é somente a estética na tela mesmo.

Até mais,

**Comment by WillianCamargo01** [comment]
Olá, boa noite! Apliquei os valores siugeridos e o problema continua!
