### ISSUE TITLE
Visualizacao de impressao em branco

### ISSUE THREAD

**Issue by OxAnexios** [RamonSilva20/mapos#2088]
**Descreva o bug**
Na visualização de impressão da ORDEM DE SERVIÇO e TERMO DE GARANTIA após o cabeçalho fica em branco até o fim da pagina. Logo na segunda pagina as informações aparecem.

**Reproduzir**
A OS foi preenchida nos campos "descriçao produto/serviço e observaçoes" e os campos "defeito e laudo tecnico" foram mantidos em branco.
Foi inserido "produtos, serviços e anotaçoes".
Ao visualizar a OS os dados aparecem seguidos sem o espaçamento em branco.
Quando é clicado em impressão A4 ou acima, após o campo DATA FINAL só vai aparecer informaçoes na pagina 02 com a "descriçao" e demais dados na sequencia normalmente.
Se mudar o formato para papel A3 ou abaixo os dados sao apresentados corretamente.

**Comportamento esperado**
Em impressao A4 ou acima, após o campo DATA FINAL aparecer informações na pagina 01 com a "descriçao" seguido das demais informaçoes. Ao inves de usar apenas 01 folha acaba usando 02 sendo uma apenas para o cabeçalho.

**Capturas de tela**
![Screenshot_1](https://user-images.githubusercontent.com/81033558/226129060-f41b7a47-2e8b-4765-bc5c-5ec51bd5908a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/81033558/226129056-95055b46-ccb0-4f1b-9f2f-edfe4f3ae510.jpg)
![ef67309d-754b-476e-adfb-179d3ef24639](https://user-images.githubusercontent.com/81033558/226129653-5703a854-6865-432f-8594-ee0b89671fc7.jpg)

**Desktop (preencha as seguintes informações):**
 - SO: Windows 10
 - Navegador : Edge
 - Versão: 111.0.1661.41

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: Xiaomi Mi 6
 - SO: Android 9
 - Navegador: Edge
 - Versão 111.0.1661.43

**Observações complementares**
Foi observado na OS que isso ocorre quando um dos 4 campos iniciais contém informações que ocupam uma página.
Dos 4 campos inseri apenas um "." em 3 e no "laudo" com informações que ocupam uma folha. Com isso o laudo é jogado pra página 02, como se tivesse ocorrido uma quebra de página.

Já no termo de garantia possui 2 paginas de texto onde isso ocorre.

Se na visualização eu redimensionar conteúdo pra 72% normaliza em ambos os casos.

**Comment by OxAnexios** [comment]
![75e739f8-f0dd-42ff-addc-d2f69c9a1429](https://user-images.githubusercontent.com/81033558/226130041-26f96eb8-156d-4331-b232-e8dd7fb76326.jpg)

**Comment by willph** [comment]
Qual versão está usando?



Em sáb, 18 de mar de 2023 15:50, OxAnexios ***@***.***>
escreveu:

**Comment by OxAnexios** [comment]
@willph 4.39.0

**Comment by cc4** [comment]
Estava tendo este mesmo problema, reparei que após a digitação havia espaço em branco, removi todos, no meu caso resolveu.
