### ISSUE TITLE
@TVANDRA Você tem que alterar o AUTO_INCREMENT da tabela OS.

### ISSUE THREAD

**Issue by mateuslms8482** [RamonSilva20/mapos#2089]
@TVANDRA Você tem que alterar o AUTO_INCREMENT da tabela OS.
```
ALTER TABLE os AUTO_INCREMENT =10000;
```

_Originally posted by @Pr3d4dor in https://github.com/RamonSilva20/mapos/issues/336#issuecomment-705188165_

**Comment by willph** [comment]
> qual o nome do arquvio pra eu fazer essa alteração?

precisa acessar o banco de dados da sua aplicação.
geralmente o pessoal usa o phpmyadmin para fazer isso.
