### ISSUE TITLE
Migração de banco de dados

### ISSUE THREAD

**Issue by leolfgomes** [RamonSilva20/mapos#2091]
** Descreva o bug **
Ola, estou tendo problemas em importar o banco de dados. minha hospedagem antiga a Hostgator (fiz a exportação do banco de dados em formato .sql) n nova hospedagem Hostinger o mapos ja esta instalado, porem ao tentar importar o banco de dados antigo apresenta erro e não sobe os dados.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/81575159/228294874-b833058f-cee1-4e72-907f-a7ee4a56c596.png">
alguem pode me ajudar? estou com o sistema parado devido a esse erro.
de antemão obrigado pela ajuda e pelo sistema que é fantastico

**Comment by cabralwms** [comment]
Você está importando em um Banco de dados novo, cria apenas o nome do banco de dados e importa nele seu backup.

**Comment by leolfgomes** [comment]
valeu, vou fazer isso
