### ISSUE TITLE
Como Instalar o Mapos na Locaweb?

### ISSUE THREAD

**Issue by dbrdemetrius** [RamonSilva20/mapos#2093]
Estou subindo o Mapos na Locaweb, mas como faço para ele dar o comando do composer no ftp da locaweb e depois executar o instalador?

Obrigado pela Ajuda

Abcs

**Comment by marcozbr** [comment]
mano é a pior hospedagem que existe e CARA mas procura no YOUTUBE " como instalar mapos que existe um arquivo que já esta com todas as dependência do composer

**Comment by willph** [comment]
Fora isso tem uma turma no grupo MapOs no Whatsapp que se ajudam entre si.

https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

Em sáb, 1 de abr de 2023 12:04, Marcozbr ***@***.***>
escreveu:

**Comment by dbrdemetrius** [comment]
Obrigado, mas já pedi o cancelamento da conta pois não tem o cron para
email, vou migrar para a hostgator

Em sáb, 1 de abr de 2023 12:21, Wilmerson ***@***.***>
escreveu:
