### ISSUE TITLE
Financeiro > Nova receita

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#21]
Ao tentar adicionar nova receita, não aparece e lista de clientes no campo e ao adicionar manualmente ele cria a receita mas com erro.

A PHP Error was encountered
Severity: Notice
Message: A non well formed numeric value encountered
Filename: financeiro/lancamentos.php
Line Number: 141

**Comment by RamonSilva20** [comment]
Olá. A questão de não estar aparecendo a lista de clientes é porque não está vinculado. A respeito do erro, vou tratar melhor, provavelmente você está utilizando um navegador que não carrega a máscara (IE ou Edge), aí o valor fica mal formatado, vou tratar melhor isso no lado do servidor. Grato.

**Comment by michelfritsch** [comment]
Firefox 52.0.2 (64-bit) Linux
Google Chrome 57.0.2987.133 (64-bit) Linux
Ambos com o mesmo erro.
Obs.: Não é possíver remover o lançamento que gerou o erro.

**Comment by michelfritsch** [comment]
Só consegui remover o lançamento que estava gerando o erro diretamente no banco de dados.

**Comment by willsantos07** [comment]
aqui aconteceu o mesmo erro porem so acontece quando adiciono um valor acima de 999,99 por ex 1,000.01

**Comment by RamonSilva20** [comment]
Está aparecendo a máscara de formatação dos valores?

**Comment by michelfritsch** [comment]
Sim, a máscara dos valores aparece, só a lista de clientes não.
![captura de tela_2017-04-14_00-01-22](https://cloud.githubusercontent.com/assets/26671487/25031800/c8350dbe-20a5-11e7-8e17-13fe44b5c600.png)

**Comment by RamonSilva20** [comment]
Problema solucionado e validação adicionada no controller para formatar os valores caso estejam fora do padrão. As correções estão nos dois últimos commits. Grato.
