### ISSUE TITLE
URLs do seu site detectados com malware

### ISSUE THREAD

**Issue by leolfgomes** [RamonSilva20/mapos#2105]
Problemas detectados

Páginas enganosas
Descrição
Estas páginas têm o objetivo de convencer os usuários a fazer algo perigoso, como instalar softwares indesejados ou revelar informações pessoais. [Saiba mais](https://support.google.com/webmasters/answer/9044101#phising)
URLs de amostra
https://upjetcell.com.br/sistema
https://upjetcell.com.br/sistema/
https://upjetcell.com.br/sistema/index.php
https://upjetcell.com.br/sistema/index.php/
https://upjetcell.com.br/sistema/index.php/login

Pessoal Bom dia, ja solicitei a revisão das paginas para a plataforma do google. porem essa ja é a segunda vez que isso acontece, tem alguma forma de resolver isso e o google não apresentar essa mensagem?

**Comment by douglasr0x** [comment]
pode ser certificado

**Comment by almron** [comment]
Siga o link abaixo. Eu tive esse problema e foi dessa forma que eu resolvi.

https://github.com/RamonSilva20/mapos/issues/1915

**Comment by leolfgomes** [comment]
> pode ser certificado
nesse caso o certificado SSl?

na hospedagem o certificado SSL esta ativo e não apresentou problemas de malware ou phishing no site ao fazer a varredura,

**Comment by almron** [comment]
Abra ou crie o arquivo .htaccess na raiz do Map-OS em sua hospedagem e coloque o código abaixo.

RewriteEngine On 
RewriteCond %{HTTPS} off 
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Esse código faz com que o tráfego em http:// seja redirecionado para https://. Hospedagens como Hostgator não possui um um serviço ativo de redicionamento. Faça um teste antes e depois da alteração forçando o tráfego em http.
