### ISSUE TITLE
Dimensão logo

### ISSUE THREAD

**Issue by JeizonSilva** [RamonSilva20/mapos#211]
Alguém sabe me dizer qual a linha code pra mudar as dimensões da logo no matrix-style?

**Comment by RamonSilva20** [comment]
Olá. Linha 55 até a 64.

#header h1 {
	background: url("../img/logo.png") no-repeat scroll 0 0 transparent;
	height: 31px;
	left: 20px;
	line-height: 600px;
	overflow: hidden;
	position: relative;
	top: 26px;
	width: 191px;
}
