### ISSUE TITLE
Intalação com Docker em Sistemas de Arquitetura ARM64

### ISSUE THREAD

**Issue by FelipeFTN** [RamonSilva20/mapos#2111]
# Descrição :scroll: 
Aparentemente não é possível utilizar o Docker-compose para construir o projeto **mapos** a partir de um sistema com arquitetura _linux/arm64_.
Isto acontece durante a execução do Docker-compose, assim como é descrito na instalação via Docker do README:
```bash
➜  docker $ sudo docker-compose up --force-recreate
Building php-fpm
Step 1/10 : FROM nanoninja/php-fpm:7.4.0
 ---> 2720b63a0904
Step 2/10 : RUN usermod -u 1000 www-data
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
 ---> Running in 02e0029a4cc3
standard_init_linux.go:219: exec user process caused: exec format error
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c usermod -u 1000 www-data' returned a non-zero code: 1
```

## O que eu desejo :thinking: 
Por favor, podem informar neste post, como eu poderia fazer isto, talvez alterando algum arquivo, eu mesmo, no meu projeto?
Já tentei adicionar `platform: linux/arm` ou apenas `platform: linux/arm64` nos serviços do **docker-compose.yml**.
Aparentemente nada funcionou. :pensive: 

# O que eu considerei :bulb: 
Sei que é possível fazer a instalação "pura", instalando manualmente o apache2, mysql e phpmyadmin, mas creio que, por configurar todo o ambiente, e principalmente o banco de dados, sistemas do NGINX e PHP, creio que a instalação via Docker seria a mais viável e menos dolorosa para mim. :smiley: :+1: 

# Contexto adicional :nerd_face: 
Estou criando um servidor com o Sistema MapOS em um Raspberry Pi 3, creio que o MapOS atende perfeitamente minhas necessidades, porém sempre acabo esbarrando neste problema da instalação via Docker.

Agradeço qualquer ajuda;

Obrigado. :rocket:

**Comment by willph** [comment]
É algo relacionado a isso?

https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

**Comment by willph** [comment]
> # Descrição 📜
> 
> Aparentemente não é possível utilizar o Docker-compose para construir o projeto **mapos** a partir de um sistema com arquitetura _linux/arm64_. Isto acontece durante a execução do Docker-compose, assim como é descrito na instalação via Docker do README:
> 
> ```shell
> ➜  docker $ sudo docker-compose up --force-recreate
> Building php-fpm
> Step 1/10 : FROM nanoninja/php-fpm:7.4.0
>  ---> 2720b63a0904
> Step 2/10 : RUN usermod -u 1000 www-data
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
>  ---> Running in 02e0029a4cc3
> standard_init_linux.go:219: exec user process caused: exec format error
> ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c usermod -u 1000 www-data' returned a non-zero code: 1
> ```
> 
> ## O que eu desejo 🤔
> 
> Por favor, podem informar neste post, como eu poderia fazer isto, talvez alterando algum arquivo, eu mesmo, no meu projeto? Já tentei adicionar `platform: linux/arm` ou apenas `platform: linux/arm64` nos serviços do **docker-compose.yml**. Aparentemente nada funcionou. 😔
> # O que eu considerei 💡
> 
> Sei que é possível fazer a instalação "pura", instalando manualmente o apache2, mysql e phpmyadmin, mas creio que, por configurar todo o ambiente, e principalmente o banco de dados, sistemas do NGINX e PHP, creio que a instalação via Docker seria a mais viável e menos dolorosa para mim. 😃 👍
> # Contexto adicional 🤓
> 
> Estou criando um servidor com o Sistema MapOS em um Raspberry Pi 3, creio que o MapOS atende perfeitamente minhas necessidades, porém sempre acabo esbarrando neste problema da instalação via Docker.
> 
> Agradeço qualquer ajuda;
> 
> Obrigado. 🚀

Achei esse link, testa e depois nos diz se funcionou

https://greenoperations.com.br/greenblog/index.php/2021/08/05/map-os-2021-instalar-no-linux-ou-raspberry-pi-sistema-de-controle-de-ordens-de-servico-gratuito/

Infelizmente eu não tenho uma placa dessa para fazer os testes.

**Comment by FelipeFTN** [comment]
Olá, primeiramente obrigado pela resposta, analisei ambas as respostas, e nenhuma parece se encaixar adequadamente ao meu caso.<br>

### Resumo do problema
Deixe-me ser mais direto: tenho um Raspberry pi 3 rodando **Raspberry Pi OS lite** (sem Desktop-Environment), sempre que eu tento instalar o Map-os através do Docker - localizado nos diretórios em `docker/` - rodando o comando `$ sudo docker-compose up --force-recreate` eu recebo uma mensagem de erro dizendo que as imagens que seriam baixadas através dos arquivos `Dockerfile` não são compatíveis com sistemas de arquitetura _**ARM**_.
Fiz algumas pesquisas e acredito que seja possível [emular um ambiente _**ARM**_ em sistemas **Windows**](https://superuser.com/questions/469525/how-can-i-virtualize-an-arm-machine-in-windows); link [sourceforge](http://sourceforge.net/projects/rpiqemuwindows/files/latest/download); link [tutorial](https://www.youtube.com/watch?v=xiQX0YXYuqU).
Acredito que seguindo os passos acima, você consiga simular de forma mais exata o problema ao qual estou passando.

### O que deve ser feito?

- Emular um Raspberry pi no seu sistema operacional;
- Instalar atualizações `sudo apt update && apt upgrade -y`;
- Instalar requisitos do Mapos `sudo apt install composer docker-compose, docker ... -y`;
- rodar o comando de instalação do Mapos `sudo docker-compose up --force-recreate`;
- Wait for it - aqui deveria ocorrer o erro.

Não hesite em mandar aqui caso tenha algum problema com a instalação no ambiente linux, estou à disposição!

desde já, agradeço pela ajuda!

**Comment by willph** [comment]
Testou a versão mais recente do código?

Houve uma atualização lá

Em seg, 22 de mai de 2023 18:27, FelipeFTN ***@***.***>
escreveu:

**Comment by FelipeFTN** [comment]
Testei a nova versão, sim! Mas como eu disse, é um problema com a instalação via docker em sistemas com arquitetura `linux/arm`.
Fazendo uma pequena análise aqui, acredito que você possa testar esse problema acontecendo direto pelo seu celular android.
Veja bem, ele executa a partir de um Kernel Linux, e o chip do processador é baseado na arquitetura arm64, logo, creio que ele possa ser o alvo perfeito para alguns testes.
Baixe um aplicativo que executa um terminal linux no android (existem vários aplicativos que fazem isso na play store); e tente fazer a instalação via docker do MapOs lá; creio que você terá o mesmo problema que eu tive.
O problema ocorre porque o Docker tenta fazer um pull em algumas **Images** que foram construidas para rodar em sistemas de arquitetura amd64 ou x86_64 (as que precisam necessariamente de um sistema de refrigeração, pois seu chip de processamento esquenta muito, geralmente são processadores que tem cooler); e o docker informa que a imagem não pode ser usada em sistemas com processador mais simples, como o de celular, ou raspberry pi, por exemplo.
` ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested`.

**Comment by hiagocosta** [comment]
boa tarde pessoal, tentei procurar algo assim, e localizei esse issue.

Infelizmente o bot está fechando todos os requests mesmo os ainda em aberto...

posso dar uma dica: testarem usando a Oracle free tier, que é gratuito para uso e permite uma VPS com arquitetura ARM pra testar esta questão. 

espero que possa tê-los ajudado, o projeto é muito bom, porém esta questão do fechamento dos issues pelo bot passa uma impressão incorreta de atividade
