### ISSUE TITLE
Tags HTML sendo inseridas no banco!

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#2113]
** Descreva o bug **
Boa Tarde Instalei o mapos 4.39 e percebi que ao adicionar uma nova OS  o script de inserção esta salvando tags HTML no banco!

Segue a imagem das tags adicionadas ao banco!
![mapos](https://user-images.githubusercontent.com/71839236/235487202-0ecf5697-8d16-42b0-9071-061e466cb55e.png)

Pode ser percebido que a cada nova Os cadastrada o script coloca a tag <p></>, o que fazer para corrigir?

**Comment by willph** [comment]
Infelizmente não tem como lhe ajuda, pois sua versão é modificada, não sei como esta seu código.

mas tem código php para remover tags html

**Comment by p-francelino** [comment]
Willph boa noite.

Sem modificações ele também tá mandando código html, eu fiz o teste para ter a certeza.

**Comment by almron** [comment]
Talvez não seja um problema.

![image](https://user-images.githubusercontent.com/49542923/235803438-fb189d5b-b4f8-4830-bfa5-56076d180e7d.png)

**Comment by p-francelino** [comment]
Também ja realizei o teste mais continua inserido html no banco

**Comment by p-francelino** [comment]
Willph entendo muito pouco de PHP, mais posso tentar resolver. Só não sei qual o arquivo devo modificar, porque ainda não tenho muita familiaridade com o codeigniter.

**Comment by WillianCamargo01** [comment]
Deixa a class="span12" apenas (remove o editor para que o sistema grave no banco em formato de texto simples) linha 82 do arquivo adicionarOS.php em views

**Comment by p-francelino** [comment]
A questão é porque o editor está enviando caracteres html? se nas versões anteriores não fazia isto?
