### ISSUE TITLE
My Model

### ISSUE THREAD

**Issue by thiago122** [RamonSilva20/mapos#212]
Estava olhando os models do projeto, e acho que poderia poupar muito tempo se usasse um MY_Model, eu criei um o qual eu estou utilizando em meus projetos e tem sido muito mais rápido o desenvolvimento, quase não faço mais queries no meus model, acho que vale a pena dar uma olhada, eu acho que está desatualizado, no mais recente tem softdelete, quando puder eu subo o mais recente.
https://github.com/thiago122/codeigniter-my-model

**Comment by RamonSilva20** [comment]
Olá. Verdade, na versão 4 está sendo utilizado.
