### ISSUE TITLE
Agendamento de serviço

### ISSUE THREAD

**Issue by luissobrinho** [RamonSilva20/mapos#213]
Olá galera, 
Amei o trabalha de vocês, queria sugerir uma agenda de horários de serviço para quem faz os serviços externos, para facilitar esse trabalho poderia ter isso para que possa marcar um horário de visita no cliente sem se preocupar se esse horário já está marcado.

Aproveitando esse Issues, queria saber se vão migrar para [Laravel](https://laravel.com/)?

**Comment by edgarmeireles** [comment]
Essa agenda poderia ser incluida na area do cliente, onde o mesmo pode solicitar uma visita técnica por exemplo.
