### ISSUE TITLE
Erro ao atualizar via sistema 

### ISSUE THREAD

**Issue by willybrandtleao** [RamonSilva20/mapos#2131]
![image](https://github.com/RamonSilva20/mapos/assets/46223150/29f839ef-ee3b-467d-a759-ec0f0fa33c8d)
![image](https://github.com/RamonSilva20/mapos/assets/46223150/0be36bc4-4ba9-4b7e-bd44-4e4a849dc95e)
![image](https://github.com/RamonSilva20/mapos/assets/46223150/ca1adcc8-0d17-4e3f-a548-9ed10d3ddb3c)
![image](https://github.com/RamonSilva20/mapos/assets/46223150/f91c70c7-9754-4aa0-9dda-0f7dbf7b6de0)

<html>
<body>
<h2 class="details-heading" style="color: rgb(66, 136, 206); font-weight: 300; padding-bottom: 10px; margin-bottom: 10px; border-bottom: 1px solid rgba(0, 0, 0, 0.1); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment &amp; details:</h2><div class="data-table-container" id="data-tables" style="color: rgb(19, 19, 19); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="data-table" id="sg-get-data" style="width: 1290.23px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">GET Data</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-post-data" style="width: 1290.23px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">POST Data</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-files" style="width: 1290.23px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">Files</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-cookies" style="width: 1290.23px; margin-bottom: 10px;"><label style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: block; padding-bottom: 5px;">Cookies</label>

app_session | a5b55bfb2d46121190729c124c56692fe9b16667
-- | --

</div><div class="data-table" id="sg-environment-variables" style="width: 1290.23px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">Environment Variables</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div></div><div class="data-table-container" id="handlers" style="color: rgb(19, 19, 19); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: block; padding-bottom: 5px;">Registered Handlers</label><div class="handler active" style="padding: 4px 0px; font: 14px Inconsolata, &quot;Fira Mono&quot;, &quot;Source Code Pro&quot;, Monaco, Consolas, &quot;Lucida Console&quot;, monospace;">0. Whoops\Handler\PrettyPageHandler</div></div>
</body>
</html>

**Comment by willybrandtleao** [comment]
Quando atualizo a versão doPHP 7.3 (ea-php73) para qualuqer uma outra versão, não resolve e para de funcionar total.

**Comment by willybrandtleao** [comment]
Rodei esse comando INSERT INTO configuracoes (idConfig, config, valor) VALUES (15, 'control_2vias', 0); e não deu bom ainda, infelizmente.

**Comment by willph** [comment]
Você atualizou pelo botão dentro do sistema?

Ou foi sobreescrevendo os arquivos?

Em qua, 24 de mai de 2023 07:12, Willy Brandt ***@***.***>
escreveu:

**Comment by willph** [comment]
> Bom dia @willph , tudo bem ? Tentei atualizar dentro do sistema. ![image](https://user-images.githubusercontent.com/46223150/240587393-b407c0f1-7b3a-4ea3-8757-5e3be4113f24.png)

Em algumas hospedagem ele não esta funcionado corretamente.

O sistema roda em php8.1 e aconselho atualizar sobrescrevendo os arquivos.

Ai precisa editar os arquivos config.php, database.php e index.php

**config.php** na linha **46** `$config['base_url'] = 'COLOCA AQUI SUA URL';`

**database.php** nas linhas **7 a 10** com os dados do antigo **databese.php**

```
    'hostname' => 'enter_hostname',
    'username' => 'enter_db_username',
    'password' => 'enter_db_password',
    'database' => 'enter_database_name',
```
index.php na linha **59** `define('ENVIRONMENT', 'production');`

e o banco de dados pode ser atualizado pelo sistema, ele funciona tranquilamente. botão `Banco de Dados` ou no raiz pela pasta **UPDATES**  arquivo [update_4.39.0_to_4.40.0.sql](https://github.com/RamonSilva20/mapos/blob/master/updates/update_4.39.0_to_4.40.0.sql)
