### ISSUE TITLE
ERRO AO CADASTRAR O.S COM USUARIO NA INTERFACE DO CLIENTE

### ISSUE THREAD

**Issue by DanielReisl** [RamonSilva20/mapos#2132]
** Descreva o bug **
Ao tentar cadastrar O.S através da interface do usuário, apresenta-se o seguinte erro.
Whoops \ Exception \ ErrorException (E_WARNING)
Attempt to read property "usuarios_id" on null

**Reproduzir**
Etapas para reproduzir o comportamento:
1 cadastre um novo cliente
2 Vá para 'Área do Cliente.' Faça o Login com usuário cliente
3. Clique em 'Ordens de Serviço', 
4. Clique em 'Adicionar',
5. Preencha todos os campos
6. clique em cadastrar
7. Ver erro

**Comportamento esperado**
O registro da O.S, mostrar OS na interface.

** Capturas de tela **

![Captura de Tela (1)](https://github.com/RamonSilva20/mapos/assets/9903363/0cb8b0a3-69e8-4459-b56b-3ac026da4f18)

** Desktop (preencha as seguintes informações): **
 - SO: [Windows 10 64 bit)]
 - Navegador [Opera]
 - Versão [99.0]

**Comment by willph** [comment]
enviado a correção.

aguardar aprovar pr

obrigado por compartilhar.
