### ISSUE TITLE
Esqueceu sua senha? - área do cliente - após instalação nova do mapos na versão 4.40.0 e importação do banco 4.32.1

### ISSUE THREAD

**Issue by neofln** [RamonSilva20/mapos#2138]
Nova rodada de testes na versão 4.40.0 
Na área do cliente, clicando em "Esqueceu sua senha?" surge um dialogo pedindo o e-mail, ao inserir o e-mail e clicar em enviar surge a seguinte mensagem de erro:

Error
Cannot use object of type stdClass as array

e no frame do lado direito aparece isto:

```
mapos/application/views/conecte/emails/clientenovasenha.php
 
        .rtl table tr td:nth-child(2) {
            text-align: left;
        }
 
        .justify {
            text-align: justify;
        }
    </style>
</head>
 
<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="4">
                    <table>
                        <tr>
                            <td class="title">
###                                 <img src="<?= $emitente[0]->url_logo; ?>" style="width:100%; max-width:120px;">
                            </td>
                            <td style="text-align: right">
                                <br>
                                <br>
 
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

```
A linha com highlight é a acusada. ;D

Alguém tem alguma ideia de como resolver?

**Comment by almron** [comment]
Acredito que esse erro foi corrigido na última revisão na semana passada. Vá até o código e veja as três alterações realizadas.

https://github.com/RamonSilva20/mapos/blame/master/application/views/conecte/emails/clientenovasenha.php
https://github.com/RamonSilva20/mapos/blame/master/application/views/conecte/visualizar_os.php

**Comment by neofln** [comment]
Muito obrigado pela ajuda, copiei os novos arquivos mencionados e aparentemente o problema foi solucionado.
Só estou agora tentando entender porque o e-mail ficou pendente sendo que já está configurado como na versão anterior.

**Comment by matheusneves2023** [comment]
Boa tarde, fiz as 3 alterações das linhas, o erro parou, chega a msg de confirmação porem o email de recuperação não chega.
alguém pode me ajudar?

**Comment by neofln** [comment]
No meu caso tive que reconfigurar o cronjob, pedi ajuda pro pessoal da hostinger e eles forneceram a solução.

**Comment by matheusneves2023** [comment]
> No meu caso tive que reconfigurar o cronjob, pedi ajuda pro pessoal da hostinger e eles forneceram a solução.


Poderia mandar uma foto de como ficou seu cron?
