### ISSUE TITLE
Correção do HTML na hora de cadastrar o emitente.

### ISSUE THREAD

**Issue by evertonrj** [RamonSilva20/mapos#214]
Bom dia.

Percebi um erro na hora de cadastrar o emitente, o navegador "EDGE" reproduz desta forma a página.
![tela emitente](https://user-images.githubusercontent.com/37884646/47555283-ce965500-d8e1-11e8-8cde-b1e653b69049.png)
E também o botão cancelar não esta funcionando.

**Comment by RamonSilva20** [comment]
Olá @evertonrj. A versão 4 está em desenvolvimento, esta parte de emitente não está finalizada.
