### ISSUE TITLE
Erro no campo valores quando estou editando

### ISSUE THREAD

**Issue by Blayver** [RamonSilva20/mapos#2140]
** Descreva o bug **
Quando eu tento editar um lancamento qualquer ou qualquer valor acima de 1.000,00 acontece que quando eu clico para salvar ou atualizar os valores de 1000 reais passam a ser de apenas 1,00 real.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para ' lancamentos'
2. Clique em 'editar um lancamento que tenha valores de 1.000,00'
3. Clique em editar lancamento 'MANDA SALVAR SEM FAZER QUALQUER ALTERAÇÃO'
4. VAI VER QUE O VALOR MUDARÁ PARA APENAS "1,00"

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
![image](https://github.com/RamonSilva20/mapos/assets/89590286/86715413-26bc-46ac-8ce6-14622e0aea98)

![image](https://github.com/RamonSilva20/mapos/assets/89590286/1e404fd3-986a-45b6-bdfa-b5fd57f7a623)

![image](https://github.com/RamonSilva20/mapos/assets/89590286/54701d96-b343-472b-8365-c1a5a226e58b)

** Desktop (preencha as seguintes informações): **
 - SO: [WINDOWS 10]
 - Navegador [CHROME]
 - Versão [![image](https://github.com/RamonSilva20/mapos/assets/89590286/59685bb8-8559-4eec-aba5-202b38d9dc47)]

**Comment by cabralwms** [comment]
Você está colocando a virgula nos 1.000,00 tenta deixar sem virgula e testa. Mas acredito que foi corrigido esse bug. está na versão master 4.40.0??

**Comment by Blayver** [comment]
Sim estou na versão 4.40.0. 
O que acontece somente na parte de lancamentos. creio que deve ser a formatação do campo valor, se eu edito o lancamento e não clico dentro deste campo pra essa virgula sair ele muda o valor toda vez. Ex se eu editar ele e alterar qualquer coisa e não clicar dentro do campo valor ele pega o valor que esta na formatação e vai com a virgula. Esse e o problema. Se eu soubesse ao menos tirar esta formatação ja ajudaria...

**Comment by rafaelbrasileiro** [comment]
Boa tarde.

Realmente acontece. Qualquer valor, que se edita nos lançamentos, que seja a cima de R$ 1.000,00 ele faz isso. Ele diminui a quantidade de casas decimais.

**Comment by rafaelbrasileiro** [comment]
Boa tarde.

Ninguém conseguiu resolver esse problema não? Já busquei em todos os locais, mas não consigo resolver. É somente na hora de editar uma venda ou OS já faturada. Alguém saberia o local no arquivo para ajudar?

**Comment by rafaelbrasileiro** [comment]
Amigo, funcionou muito bem. Mas tem outro Bug que percebi agora. Depois de editar um valor com desconto aplicado, ele vai adicionando o valor do desconto no valor total, sempre que é editado e salvo o lançamento. Ele vai incrementando o valor do desconto no valor total.

Se remover o desconto e salvar, ele salva normal. Agora se fizer o mesmo processo, ele volta a fazer a mesma coisa de incrementar o valor do desconto no valor e no valor total.

**Comment by rafaelbrasileiro** [comment]
Conseguiu simular esse bug ai amigo?
