### ISSUE TITLE
Tentei instalar, fiz todos os passos corretamente, porém fica instalando eternamente

### ISSUE THREAD

**Issue by devcael** [RamonSilva20/mapos#2144]
Não sai dessa tela por nada, preenchi todos os campos corretamente, só removi algumas coisas pra não ficar aqui

![image](https://github.com/RamonSilva20/mapos/assets/51369599/3dbb0646-fb8c-4d3a-861e-0c54e76b7c19)

**Comment by Blayver** [comment]
Tenta não subir backup no banco de dados. Apenas criar o banco com o nome mapos e deixar ele vazio, depois vc abre essa pagina de cadastro.

**Comment by devcael** [comment]
O nome do banco precisa necessariamente ser MAPOS em maiusculo?

**Comment by cabralwms** [comment]
Não precisa ser mapos, vc pode colocar o nome que quiser, mas indica esse nome no campo aonde pede o banco tem que ser o mesmo nome que criou, mas sem importar as informações.

**Comment by devcael** [comment]
@cabralwms  e @Blayver  obrigado manos, funcionou aqui
