### ISSUE TITLE
Problema com Geração de Etiquetas

### ISSUE THREAD

**Issue by rafaelbrasileiro** [RamonSilva20/mapos#2146]
** Descreva o bug **
Mesmo que escolha qualquer formato de etiqueta, o Mapos gera todas do mesmo jeito da foto anexada.

 Mapos Versão: 4.40.0

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Produtos'
2. Clique em 'Gerar Etiquetas'
3. Role para baixo até 'Digite o ID do primeiro produto, e o ID final do produto.'
4. Escolha qualquer formato da etiqueta, e clique para 'Gerar'.

**Comportamento esperado**
Mostrar as etiquetas geradas no formato escolhido.

** Capturas de tela **

![Screenshot_3](https://github.com/RamonSilva20/mapos/assets/55510222/a1f06963-788d-41a1-a3cb-d6fa1d7fc21c)

** Desktop (preencha as seguintes informações): **
 - SO: [WIN 10]
 - Navegador [Google Chrome]
 - Versão [114.0.5735.133]

**Comment by cabralwms** [comment]
Gerei aqui e não ficou apenas 1 produto colocou todos com estoque.
