### ISSUE TITLE
Adicionar Quantidade de Serviços na OS

### ISSUE THREAD

**Issue by fsconsultti** [RamonSilva20/mapos#215]
Amigos,

Gostaria de pedir a ajuda de vocês no que diz respeito a inserção da quantidade de serviços assim como há na aba produtos.

Desde já agradeço a atenção de todos.

**Comment by evertonrj** [comment]
Boa tarde Ramon. Antes de mais nada gostaria de agradecer por esta ferramenta fantástica que é o MAPOS! Parabéns pela ideia e a todos que de certa forma contribuíram e contribuem para o desenvolvimento dessa ferramenta.

Quanto a inserção de serviços acredito é interessante ter a opção de adicionar a quantidade de serviço para o mesmo serviço.

Eu por exemplo, trabalho com mesmo serviço sendo executado mais de uma vez (Instalação de fechaduras) esse serviço o meu técnico pode instalar de 01 a 300 em uma mesma implantação, e o preço varia de acordo com a quantidade de fechaduras instaladas. A gente teria que ter além da opção de adicionar a quantidade de serviços ter a opção de ou ajustar valor ou dar desconto.


Obter o Outlook para Android<https://aka.ms/ghei36>



De: fsconsultti
Enviado: segunda-feira, 29 de outubro 21:36
Assunto: [RamonSilva20/mapos] Adicionar Quantidade de Serviços na OS (#215)
Para: RamonSilva20/mapos
Cc: Subscribed


Amigos,
Gostaria de pedir a ajuda de vocês no que diz respeito a inserção da quantidade de serviços assim como há na aba produtos.
Desde já agradeço a atenção de todos.

**Comment by edgarmeireles** [comment]
> Boa tarde Ramon. Antes de mais nada gostaria de agradecer por esta ferramenta fantástica que é o MAPOS! Parabéns pela ideia e a todos que de certa forma contribuíram e contribuem para o desenvolvimento dessa ferramenta. Quanto a inserção de serviços acredito é interessante ter a opção de adicionar a quantidade de serviço para o mesmo serviço. Eu por exemplo, trabalho com mesmo serviço sendo executado mais de uma vez (Instalação de fechaduras) esse serviço o meu técnico pode instalar de 01 a 300 em uma mesma implantação, e o preço varia de acordo com a quantidade de fechaduras instaladas. A gente teria que ter além da opção de adicionar a quantidade de serviços ter a opção de ou ajustar valor ou dar desconto. Obter o Outlook para Android<https://aka.ms/ghei36> De: fsconsultti Enviado: segunda-feira, 29 de outubro 21:36 Assunto: [RamonSilva20/mapos] Adicionar Quantidade de Serviços na OS (#215) Para: RamonSilva20/mapos Cc: Subscribed Amigos, Gostaria de pedir a ajuda de vocês no que diz respeito a inserção da quantidade de serviços assim como há na aba produtos. Desde já agradeço a atenção de todos. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRamonSilva20%2Fmapos%2Fissues%2F215&data=02%7C01%7C%7Cd5d9bcd95b8e4846705408d63dffae32%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636764565672635426&sdata=TG4S4XxIi1jw8SrEbgi1jFXNM2LzrcHq0K%2F%2FUukRAyo%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAkIS5huJ9ALvQMGWmodlxaZwL09ChGGpks5up572gaJpZM4YA9J5&data=02%7C01%7C%7Cd5d9bcd95b8e4846705408d63dffae32%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636764565672635426&sdata=rDG%2B9qRCXpcR1M1tx%2BnKtPPL3Dmx8Arc8DW3udlj7uY%3D&reserved=0>.

A idéia é muito boa... Não só para o caso de se repetirem, mas sim em poder manipular o valor diretamente ao incluir o serviço...

Para um dos meus clientes que usa o Mapos, tivemos que incluir diversos serviços iguais, os quais são combinados diretamente com o cliente na hora da venda, ou seja, o serviço é o mesmo, o que muda é o valor negociado com o cliente.

**Comment by evertonrj** [comment]
Isso daria uma flexibilidade muito grande na ordem de serviço.

**Comment by heliocristaldo** [comment]
Alguem conseguiu ?

**Comment by evertonrj** [comment]
Ainda não... Estou precisando muito disso, assim como editar o valor do produto/serviço dentro da O.S
E implantar uma agenda (com sincronismo com o google ou Microsoft)
