### ISSUE TITLE
Problema com geração de cobrança no Asaas

### ISSUE THREAD

**Issue by rafaelbrasileiro** [RamonSilva20/mapos#2156]
** Descreva o bug **
Sempre que vai ser gerado uma cobrança no Assas, tanto para Vendas quanto OS, a cobrança não é gerada, e é apresentado um erro na tela.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Vendas -> Escolha uma venda e clique para ver mais detalhes-> Clique no botão "Gerar Pagamento -> Escolha o Assas boleto ou link -> e clique em Gerar Pagamento"'

**Comportamento esperado**
Gerar a cobrança via boleto ou link.

** Capturas de tela **
![Mapos](https://github.com/RamonSilva20/mapos/assets/55510222/be56e6b5-1762-4e2d-9b3a-bee8126348ab)

** Desktop (preencha as seguintes informações): **
 - SO: [10]
 - Navegador [Google Chrome]
 - Versão [114.0.5735.199]

** Contexto adicional **
Se eu gerar a cobrança tanto pelo Gerencianet, quanto MercadoPago, a cobrança é gerada normalmente sem nenhum problema. Apenas a forma de cobrança Asaas está assim.

**Comment by rafaelbrasileiro** [comment]
Bom dia. Saberiam dizer se esse projeto do Mapos foi abandonado? percebo que é bem dificil alguém ajudar com algum bug agora.

**Comment by lukasabino** [comment]
Opa! 

Está ativo sim, tente entrar no grupo do WhatsApp, pois de fato a ajuda por lá é mais rápida. 

Sobre o problema em questão, basta remover um código no arquivo: liberies/gateway/Asaas:

![image](https://github.com/RamonSilva20/mapos/assets/70410692/0dbb2f21-3a92-4fd7-8ac6-494404b0a2ed)

**Comment by rafaelbrasileiro** [comment]
Olá, bom dia. Fiz como mostrou no print, e deu certo para boletos. Deu o mesmo erro para pagamentos por link, mas apliquei a mesma modificação e deu certo também. Agora uma dúvida. Não é possível cancelar e apagar cobranças por link não? Tentei e deu essa mensagem. Outra dúvida, percebi que no Asaas, apenas as cobranças feitas via boleto aparecem normalmente. As cobranças via link de pagamento não aparece dentro do Asaas. Nem mesmo o cliente é criado dentro do Asaas, se a forma de pagamento é link.

![link-Asaas](https://github.com/RamonSilva20/mapos/assets/55510222/b1ffe119-d95f-46d4-b3e3-d6bd95312c7c)

**Comment by rafaelbrasileiro** [comment]
> Opa!
> 
> Está ativo sim, tente entrar no grupo do WhatsApp, pois de fato a ajuda por lá é mais rápido.
> 
> Sobre o problema em questão, basta remover um código no arquivo: liberies/gateway/Asaas:
> 
> ![imagem](https://user-images.githubusercontent.com/70410692/252980063-0dbb2f21-3a92-4fd7-8ac6-494404b0a2ed.png)

Amigo, poderia mandar o link do Grupo do mapos no WhatsApp?

**Comment by willph** [comment]
https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

Em qua, 12 de jul de 2023 13:07, José Rafael ***@***.***>
escreveu:

**Comment by rafaelbrasileiro** [comment]
> Collaborator

Mandei a solicitação para entrar no grupo.
