### ISSUE TITLE
Virtualização

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#2158]
Boa noite, queria tirar uma duvida, tem como eu comprar aqueles mini pc e rodar sem o Windows (docker, essas virtualizações que tem pra fazer dentro do Windows) o sistema mapos, queria saber como poderia fazer isso??

**Comment by rafaelbrasileiro** [comment]
Boa noite. Instale um sistema linux, e instale o Docker, e então instale o Mapos docker. Na tela de início do mapos mostra como fazer.

**Comment by MichelDiz** [comment]
OBS. Docker não é virtualização. Em alguns sistemas virtualizam(Como Windows e macOS) o Linux para poder rodar o Docker. Mas nativamente no Linux o Docker roda junto com o Kernel("coração" do sistema), ele não virtualiza ou simula nada. O Docker literalmente roda como se fosse um programa isolado.

Se você comprar uma máquina barata sem virtualização e instalar Docker vai funcionar normalmente.

Vlw!

**Comment by barretowiisk** [comment]
@CarlosRezini 
Seu caso se aplica mais a uma análise de infraestrutura, não ao Map-OS em si.
Vai depender muito da sua finalidade, necessidade e recurso. Entra em contato comigo no WhatsApp e posso tentar te ajudar com esse assunto, observando e entendendo seu ambiente.

Barreto +55 81 98950-5723
