### ISSUE TITLE
codegen_helper.php

### ISSUE THREAD

**Issue by XeniaRP** [RamonSilva20/mapos#216]
No mapos4 não tem codegen_helper.php, e ao clicar no link ORDEM DE SERVIÇO, não é localizado no BD. tem como importar do master o arquivo ?

**Comment by XeniaRP** [comment]
An Error Was Encountered
Unable to load the requested file: helpers/codegen_helper.php

**Comment by RamonSilva20** [comment]
Olá. Este arquivo será removido na versão 4, o erro está ocorrendo onde não foi refatorado o código.
