### ISSUE TITLE
PROBLEMA IMPLEMENTAÇÃO AGENDA

### ISSUE THREAD

**Issue by heliocristaldo** [RamonSilva20/mapos#217]
Boa tarde, tentei implementar a agenda na ultima versão aparentemente deu certo, porem coloquei em um servidor vps e mostra todas as OS mas no servidor local já não mostra todas, algumas fica oculta na agenda.

Já aconteceu isso com alguém e que possa me ajudar.

**Comment by evertonrj** [comment]
Opa, boa noite amigo!!

Po cara legal. essa questão da agenda faz muita falta! poderia compartilhar?

**Comment by edgarmeireles** [comment]
Curti a ideia também... da para priorizar melhor os reparos...

**Comment by heliocristaldo** [comment]
Segue abaixo.

https://github.com/hardbrasil/mapos-hafael

**Comment by heliocristaldo** [comment]
Estou tendo problemas com minha agenda, percebi quando faço o backup.

Apos fazer o backup algumas OS some da tela, mas só na agenda que some.

**Comment by ronaldnnr** [comment]
eu visualizei o seu MAPOS... poderia me passar algumas informações  ?

**Comment by heliocristaldo** [comment]
Sim

**Comment by maycon1977** [comment]
> Segue abaixo.
> 
> https://github.com/hardbrasil/mapos-hafael

Oi, HelioCristaldo.

Teria como dar o passo-apasso pra implementar essa agenda? Fui nesse link aí, mas não entendi muito bem, como "roubatilhar" a idéia...
