### ISSUE TITLE
somente quando eu tento entrar no financeiro do meu mapos da esse erro erro de sintaxe, inesperado ')', esperando '|' ou variável (T_VARIABLE)    CÓPIA DE ESCONDER Estruturas de pilha (2) 1 Erro de análise  …\controladores\Financeiro.php249 0  requer uma vez C:\xampp\htdocs\mapos\index.php298

### ISSUE THREAD

**Issue by 93vinnie93** [RamonSilva20/mapos#2170]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by barretowiisk** [comment]
Encontrei esse mesmo erro com um usuário, o que fiz foi a reinstalação do MAP-OS v4.40.0 e substituí o banco de dados, parou de apresentar o erro, acredito que seja alguma arquivo corrompido, até identifiquei algumas coisa olhando o log, e fui arrumando, no final percebi que atualizar todos os arquivos era mais viável.

OBS: Para produção sempre baixe no releases do projeto, não do MASTER para sempre usar a versão estável.
