### ISSUE TITLE
Inclusão de mais uma opção para impressão em vendas

### ISSUE THREAD

**Issue by NeiMoraes10** [RamonSilva20/mapos#2178]
Criar mais um botão na página visualizarVenda.php com opção para imprimir um orçamento, alterando somente as variáveis na página imprimirVenda.php para personalizar o que deseja que apareça, por exemplo:

Alterar o título de Venda: 1 para Orçamento:1
Incluir uma data de validade padrão fixa
Não mostrar o Qr Code
Etc.

**Comment by barretowiisk** [comment]
A forma de resolver isso exige alguns passos.

- Clonei o arquivo `application/views/vendas/imprimirVenda.php` nomeando como `imprimirVendaOrcamento.php`
- Alterei as seguintes linhas do arquivo `application/views/vendas/imprimirVendaOrcamento.php`:
-- Linha 54: Alterei "Venda" para "Orçamento",
-- Linha 56: Inseri antes de `</span>` um paragrafo `<br>` e em seguida acrescentei a frase `Válido por até 10 dias.`
-- Linhas 88-93: Excluí toda a referência para QRCODE PIX, afim de que não imprima o QRCODE,
- Acrescentei os dados abaixo abaixo da linha 224:
```
public function imprimirVendaOrcamento()
    {
        if (!$this->uri->segment(3) || !is_numeric($this->uri->segment(3))) {
            $this->session->set_flashdata('error', 'Item não pode ser encontrado, parâmetro não foi passado corretamente.');
            redirect('mapos');
        }

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vVenda')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para visualizar vendas.');
            redirect(base_url());
        }

        $this->data['custom_error'] = '';
        $this->load->model('mapos_model');
        $this->data['result'] = $this->vendas_model->getById($this->uri->segment(3));
        $this->data['produtos'] = $this->vendas_model->getProdutos($this->uri->segment(3));
        $this->data['emitente'] = $this->mapos_model->getEmitente();
        $this->data['qrCode'] = $this->vendas_model->getQrCode(
            $this->uri->segment(3),
            $this->data['configuration']['pix_key'],
            $this->data['emitente']
        );

        $this->load->view('vendas/imprimirVendaOrcamento', $this->data);
    }
```
