### ISSUE TITLE
Anexos fora da pasta assets/anexo

### ISSUE THREAD

**Issue by joubertdias** [RamonSilva20/mapos#2179]
Estou com problemas com a hospedagem pois os arquivos ANEXOS ficam na estrutura das pastas que integram o FTP de maneira que a empresa entende que este método cria um "mau uso" da hospedagem, ou seja tratam como armazenamento, portanto, querem que eu extraia qualquer pasta que armazene conteúdo "anexo", então pergunto, teríamos como anexar estes arquivos no "drive com um link compartilhado" por exemplo? afinal o endereço fica no DB, é chamado pelo link compartilhado do drive.

**Comment by barretowiisk** [comment]
Sim é possível, mas ai se trata de um ajuste pontual. recomendo procurar um DEV para realizar os ajustes desejados.

**Comment by almron** [comment]
Copie o arquivo que quiser no Google Drive, OneDrive ou qualquer outro serviço, configure os acessos de compartilhamento conforme a sua necessidade, crie um link e copie o link no campo necessário utilizando a função "add link" no editor de texto. Assim fica muito mais seguro.
