### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#2182]
Após atualizar meu servidor pra versão 4.40.0 ele bugou e não consigo fazer login, coloco o email e senha so que não sai da tela de login, não faz nada mais

**Comment by CarlosRezini** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/73778547/e82e1780-b403-464c-808c-7bb0488d3f8a)

Instalei do zero via docker, ai não vai por causa do php, como atualizo, ja fiz de tudo e não vai

**Comment by CarlosRezini** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/73778547/857785ba-ff77-43dd-bec7-f49568a1193b)

**Comment by CarlosRezini** [comment]
Mas eu não sei atualizar, consegue me explicar?
@almron

**Comment by CarlosRezini** [comment]
> almron


#!/usr/bin/env bash

# See https://docs.docker.com/compose/environment-variables/#the-env-file

# Nginx
NGINX_HOST=localhost
NGINX_PORT=8000

# PHP

# See https://hub.docker.com/r/nanoninja/php-fpm/tags/
PHP_VERSION=latest

# PhpMyAdmin
PHP_MY_ADMIN_PORT=8080

**Comment by almron** [comment]
Basicamente a versão 4.40.0 já está com a versão do PHP corrigida. Talvez seria melhor vc baixar novamente o código em [Download Zip](https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip) e seguir o [Readme](https://github.com/RamonSilva20/mapos#instala%C3%A7%C3%A3o-docker) onde há a explicação para a instalação via Docker.
/

**Comment by CarlosRezini** [comment]
@almron ele não atualiza o php, fica sempre em 7.4.0 
![Capturar1](https://github.com/RamonSilva20/mapos/assets/73778547/7651fc65-1ae5-43d9-89fd-5ae0cfc73859)

**Comment by barretowiisk** [comment]
Olá @CarlosRezini,
Não sou especializado em docker, mas claramente o erro está na versão do PHP, da versão v4.40 em diante, o PHP precisa ser 8.1 ou superior (Se disponível recomendo usar 8.2).

@lukasabino @willph 
Consegue ajudar nesse caso com update de backup no docker?

**Comment by almron** [comment]
Se você baixar a última versão disponível do [Map-OS](https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip) no Github, todas as dependências estarão atualizadas e o PhP 8.2 será instalado.

**Comment by CarlosRezini** [comment]
@almron @barretowiisk Baixei a ultima versão Hoje 23/09, mas mesmo assim não atualiza a versão do php

**Comment by CarlosRezini** [comment]
Ela continua na 7.4.0

**Comment by barretowiisk** [comment]
@CarlosRezini via Docker ou via pacote zip?
A versão do PHP precisa ser alterada na sua hospedagem ou Servidor, não é no projeto, no projeto já está aguardando a versão 8.1 ou superior.

**Comment by CarlosRezini** [comment]
Via docker @barretowiisk

**Comment by Rodrigo-Paz** [comment]
Bom se ja atualizou a versao do php e ao rodar o comando no terminal php -v ele informar a versao 8.1, e bom testar em outro navegador pode ser o cache.

**Comment by CarlosRezini** [comment]
@Rodrigo-Paz @barretowiisk @almron Agora consegui, formatei a maquina e foi, so que não consigo voltar a voltar o banco de dados ou mesmo acessar o sistema antigo que da erro

**Comment by CarlosRezini** [comment]
Consegui resolver tudo, muito obrigado pela ajuda
