### ISSUE TITLE
Adicionar Ordem de serviço de Entrada e Nota de entrega de Saída

### ISSUE THREAD

**Issue by Rsetbrasiltecnologia** [RamonSilva20/mapos#2186]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by barretowiisk** [comment]
@willph @Pr3d4dor 
Se possível encerrar essa ISSUE o mesmo aparentemente foi aberta por engano.

**Comment by willph** [comment]
> @willph @Pr3d4dor Se possível encerrar essa ISSUE o mesmo aparentemente foi aberta por engano.

é que ele colocou tudo o que queria no titulo da issue

 _**Adicionar Ordem de serviço de Entrada e Nota de entrega de Saída**_
