### ISSUE TITLE
erro na instalação do mapos na hospedagem 

### ISSUE THREAD

**Issue by robsonroot** [RamonSilva20/mapos#219]
Boa tarde para todos.
Tentei instalar o mapos na minha hospedagem, porem esta dando o seguinte erro.
( Parse error: syntax error, unexpected T_CONST in /home/formulasdeganhos/public_html/mapos/system/core/CodeIgniter.php on line 58)

**Comment by edgarmeireles** [comment]
Essa linha identifica a versão do script (acredito que do framework CodeIgniter).

Há duas possibilidades, 1a o seu pacote está corrompido (faltando algum arquivo, ou arquivos do framework com erros), 2a o seu servidor não está executando todas os recursos necessários do PHP para que o script execute corretamente.

Baixe novamente o pacote e tente reinstalar... se não der certo, manda um reply com algum contato seu que te ajudo na instalação.

**Comment by RamonSilva20** [comment]
Por favor verifique se a versão do PHP é adequada aos requerimentos do sistema.

**Comment by softcia** [comment]
Bom dia. A minha versao do PHP é 5.3 pode ser isso do erro?

**Comment by Pr3d4dor** [comment]
Sim, precisa de PHP 7.1 no mínimo.
