### ISSUE TITLE
Bug ao restaurar backup

### ISSUE THREAD

**Issue by JetLi-Almeida** [RamonSilva20/mapos#2191]
** Descreva o bug **
Recentemente troquei de computador e instalei o MapOS / XAMPP e ao restaurar o backup na hora de imprimir a O.S ou acessar as configurações ocorre os erros dos prinsts. Se não restaurar o backup fica tudo normal, se puderem me ajudar como possa resolver sem perder o backup anterior.. agradeço muito.

** Capturas de tela **
![IMG_20230906_035909_320](https://github.com/RamonSilva20/mapos/assets/79049787/c8082882-ea2c-4b33-98ca-8692e3b9c1ca)
![IMG_20230906_035826_518](https://github.com/RamonSilva20/mapos/assets/79049787/b0618745-4460-4aab-b6e3-daeef49bb8a0)

**Comment by barretowiisk** [comment]
Olá @JetLi-Almeida  , segue um passo a passo de como realizado o update correto.

Solução:
1- Na versão anterior do Map-OS faça uma backup via sistema (Configurações -> Backup), será baixado um arquivo zipado com um backup do seu banco de dados atual.
2- Agora instale a ultima versão estável do Map-OS (Sempre baixe da release, não da Master) e após completar toda a instalação zerada e ter acesso ao sistema, acesse seu banco de dados (a maioria usa phpMyAdmin) e importe para o banco de dados da nova versão esse backup, e pronto, todos os seus dados estarão de volta a seu banco de dados.

Vários ajustes de configuração precisaram ser refeitos, como usuário, logomarca e etc, porém os dados importantes como Cliente, OS, Vendas, Produtos e Serviços já estarão nessa nova versão.

Caso funcione, retorne aqui o feedback.
Até breve.

**Comment by JetLi-Almeida** [comment]
Olá, foi exatamente assim que fiz tanto o backup quanto a restauração, mais de uma vez mas ainda persiste esse erro na hora de tentar imprimir uma o.s

**Comment by barretowiisk** [comment]
Entre no seu banco de dados e aplique o seguinte comando no banco dados do MapOS:

`INSERT INTO configuracoes (idConfig, config, valor) VALUES (15, 'control_2vias', 0);`

Irá resolver o problema

**Comment by JetLi-Almeida** [comment]
Muito obrigado, problema resolvido.

**Comment by barretowiisk** [comment]
@JetLi-Almeida 
Por favor, encerrar a ISSUE como resolvido.
