### ISSUE TITLE
não recupera a senha

### ISSUE THREAD

**Issue by Rardotz** [RamonSilva20/mapos#2193]
quando eu abro o mapos e tento fazer uma nova senha do adm eu não consigo. Eu vou em mudar a senha preencho tudo oque tem para preencher e até da o alerta de senha mudada com sucesso, porém a senha nova não funciona, eu faço as tentativas, mas não da certo e só consigo logar com a senha antiga, mesmo tendo tentado mudar ela varias vezes, eu já tentei desinstalar e instalar de novo e nada, já subi no xamp(localmente), laragon(localmente) e até na 000webhost(servidor-web) mas todas estão com o mesmo problema. detalhe que não da erro em nenhum momento.  até tentei excluir e apagar manualmente o usuario adm para criar outro em seguida na intenção de que a nova senha funcionasse nesse usuario adm mas nada tambrm

**Comment by barretowiisk** [comment]
@Rardotz 
Siga as instruções abaixo:

Acesse seu phpMyAdmin, acesse seu banco de dados, clique na tabela "usuarios" e altere a informação contida dentro da coluna senha referente ao usuário que deseja alterar a senha, copiando e colando a chave a baixo, isso vai alterar a senha do usuário para 123456

$2y$10$ILURo1IyCMrpoQgzB1wvk.cRMUGDtZ7RdvRkWBgH3UtROponn6EWu

**Comment by barretowiisk** [comment]
@Rardotz 
Por gentileza retornar o feedback sobre o caso, e se foi resolvido, encerrar a ISSUE.

**Comment by willph** [comment]
> quando eu abro o mapos e tento fazer uma nova senha do adm eu não consigo. Eu vou em mudar a senha preencho tudo oque tem para preencher e até da o alerta de senha mudada com sucesso, porém a senha nova não funciona, eu faço as tentativas, mas não da certo e só consigo logar com a senha antiga, mesmo tendo tentado mudar ela varias vezes, eu já tentei desinstalar e instalar de novo e nada, já subi no xamp(localmente), laragon(localmente) e até na 000webhost(servidor-web) mas todas estão com o mesmo problema. detalhe que não da erro em nenhum momento. até tentei excluir e apagar manualmente o usuario adm para criar outro em seguida na intenção de que a nova senha funcionasse nesse usuario adm mas nada tambrm



Erro corrigido com a PR #2268, aguarda analise e possível merge da correção.
