### ISSUE TITLE
Não consigo logar após a instalação e restauração do backup

### ISSUE THREAD

**Issue by lewisHeart** [RamonSilva20/mapos#2196]
**Descreva o bug**
Não consigo entrar no MapOS após a instalação e restauração do backup antigo.

**Reproduzir**
- Instalei o mapos manualmente (sem docker), assim como está escrito no Reame.md.
- Fiz a configuração inicial (Fiz a instalação duas vezes, na segunda não tentei logar após a configuração inicial).
- Limpei dentro do phpMyAdmin; a base de dados.
- Importei meu backup antigo.
- Tentei logar normalmente, porém; não acontece nada (Quando tento colocar a senha errada aparece que errei a senha).

**Comportamento esperado**
Entrar normalmente no sistema.

**Capturas de tela**
Não quis colocar porque não acontece realmente nada.

**Desktop**
 - SO: ArchLinux, kernel 6.5.2-arch1-1.
 - Navegador: Firefox, Brave, Edge (tentei nos três, acontece o mesmo).

**Informações Adicionais**
Não consegui achar a informação antiga da versão do MapOS, porém vi que a ultima modificação que fiz foi em fevereiro de 2022, então provavelmente a versão era a [v4.36.0](https://github.com/RamonSilva20/mapos/releases/tag/v4.36.0) ou [v4.35.2](https://github.com/RamonSilva20/mapos/releases/tag/v4.35.2)

**Comment by barretowiisk** [comment]
Olá @lewisHeart , isso acontece porque muita coisa mudou da versão v.4.35.2 até a atual, então segue um passo a passo de como realizado o update correto.

Solução:
1- Na versão anterior do Map-OS faça uma backup via sistema (Configurações -> Backup), será baixado um arquivo zipado com um backup do seu banco de dados atual.
2- Agora instale a ultima versão estável do Map-OS (Sempre baixe da release, não da Master) e após completar toda a instalação zerada e ter acesso ao sistema, acesse seu banco de dados (a maioria usa phpMyAdmin) e importe para o banco de dados da nova versão esse backup, e pronto, todos os seus dados estarão de volta a seu banco de dados.

Vários ajustes de configuração precisaram ser refeitos, como usuário, logomarca e etc, porém os dados importantes como Cliente, OS, Vendas, Produtos e Serviços já estarão nessa nova versão.

Caso funcione, retorne aqui o feedback.

**Comment by lewisHeart** [comment]
Então, eu não cheguei a fazer o procedimento que você disse, apenas pesquisando vi sobre os arquivos da pasta update, fiz o procedimento, funcionou, porém, estava dando um erro na hora de imprimir as ordens de serviços e abrir as configurações, aí pesquisando achei [essa discussão](https://github.com/RamonSilva20/mapos/discussions/2119) e executei esse seguinte código ` INSERT INTO configuracoes (idConfig, config, valor) VALUES (15, 'control_2vias', 0);` e funcionou tudo tranquilo.

**Comment by lewisHeart** [comment]
Então, eu não cheguei a fazer o procedimento que você disse, apenas pesquisando vi sobre os arquivos da pasta update, fiz o procedimento, funcionou, porém, estava dando um erro na hora de imprimir as ordens de serviços e abrir as configurações, aí pesquisando achei [essa discussão](https://github.com/RamonSilva20/mapos/discussions/2119) e executei esse seguinte código no banco de dados pelo phpmyadmin: ` INSERT INTO configuracoes (idConfig, config, valor) VALUES (15, 'control_2vias', 0);` e funcionou tudo tranquilo, não que eu entenda muito sobre php e mysql XD
