### ISSUE TITLE
Problema com relatório financeiro

### ISSUE THREAD

**Issue by rodrigoodebrito** [RamonSilva20/mapos#2198]
Primeiramente parabéns pelo projeto!

Gostaria de reportar o bug que o relatório do financeiro esta saindo sem a soma das receitas, esta somando apenas as despesas.

![Captura de tela 2023-09-14 190746](https://github.com/RamonSilva20/mapos/assets/145071440/42c7fb0d-2ac1-4fae-958a-fff01a514e2b)

**Comment by rodrigoodebrito** [comment]
Receitas de serviço ele soma, mas de venda de produtos não

**Comment by rodrigoodebrito** [comment]
Estranho...
Aqui, se tirar o relatório de vendar ele soma normal, mas o relatório do financeiro não.

**Comment by barretowiisk** [comment]
Olá @rodrigoodebrito,
Já corrigimos (Eu, @lukasabino e @Fesantt) esse e alguns outros relatórios que realmente estão realizando os cálculos incorretos, em breve estaremos disponibilizando em PRs.

Até breve.

**Comment by rodrigoodebrito** [comment]
Legal, obrigado!
