### ISSUE TITLE
Erro ao clicar no menu "Lançamentos".

### ISSUE THREAD

**Issue by cezargf** [RamonSilva20/mapos#2203]
Após instalar e entrar no sistema, ao clicar no menu "Lançamentos", é exibida a seguinte tela de erro:

![Captura da Web_18-9-2023_113930_localhost](https://github.com/RamonSilva20/mapos/assets/25113573/b93dd147-ac6e-4315-9fb5-0517e2b947b0)

**Comment by barretowiisk** [comment]
Olá, temos outro usuário com o mesmo problema, porém em QA não conseguimos reproduzir o mesmo problema, isso aconteceu por que você tentou fazer a atualização via sistema ou algum erro durante a restauração do seu backup em uma atualização manual, é importante trazer mais informações nesse tipo de report para que possamos ajudar com a solução.

Possível solução:
1- Na versão anterior do Map-OS faça uma backup via sistema (Configurações -> Backup), será baixado um arquivo zipado com um backup do seu banco de dados atual.
2- Agora instale a ultima versão estável do Map-OS (Sempre baixe da release, não da Master) e após completar toda a instalação zerada e ter acesso ao sistema, acesse seu banco de dados (a maioria usa phpMyAdmin) e importe para o banco de dados da nova versão esse backup, e pronto, todos os seus dados estarão de volta a seu banco de dados.

Caso funcione, retorne aqui o feedback.

**Comment by Fesantt** [comment]
O erro ja foi corrigido a 6 horas

**Comment by Fesantt** [comment]
Isso mesmo @cezargf ja fiz a PR com a correção
