### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by fehveiga** [RamonSilva20/mapos#2207]
Estava com um erro ao entrar em lançamentos, então voltei o controlador financeiro da 4.41.0 e então voltou a funcionar.
Agora estou com um erro ao clicar em visualizar no cliente. Alguém passando por isso?
![Captura de ecrã 2023-09-18 231253](https://github.com/RamonSilva20/mapos/assets/127157240/16ccd107-31b9-4f58-bd5a-1a49c55bdfce)

**Comment by barretowiisk** [comment]
@fehveiga 
Estamos trabalhando para corrigir, o erro é proveniente da PR #2207, em breve iremos corrigir o erro.
Como medida paliativa, baixe a versão v4.40.0 e copie o arquivo `application/views/clientes/visualizar.php` ou delete as linhas 216 a 278.
