### ISSUE TITLE
ao instalar o sql no BD o mesmo apresenta erro na parte de usuario

### ISSUE THREAD

**Issue by silvanoxavier** [RamonSilva20/mapos#221]
ao instalar o sql no BD o mesmo apresenta erro na parte de usuário e quando se faz a finalização da instalação e vi tentar logar da erro de dados incorretos do usuario

**Comment by RamonSilva20** [comment]
Olá. Crie somente o banco de dados, o instalador irá criar as tabelas e inserir o usuário de acesso.
