### ISSUE TITLE
Erro ao lançar receita parcelada com 'cliente/fornecedor' preenchidos, porém não cadastrados.

### ISSUE THREAD

**Issue by cezargf** [RamonSilva20/mapos#2210]
**Descrição**
Ao tentar adicionar um novo lançamento com o campo "cliente/fornecedor" preenchido com dados não cadastrados previamente.
![image](https://github.com/RamonSilva20/mapos/assets/25113573/9031fc5c-bef4-4c05-b51f-2d6b9af8a098)

Etapas para reproduzir o comportamento:
1. Vá para 'Lançamentos';
2. Clique em 'Adicionar Receita/Despesa';
3. Altere a quantidade de parcelas para 2x ou mais;
4. Preencha o campo "Cliente/Fornecedor" com dados que não estejam cadastrados em "Clientes";
![image](https://github.com/RamonSilva20/mapos/assets/25113573/4f318e0e-c010-49cf-92f0-167184530f87)

**Comportamento esperado**
1. Cadastramento do lançamento mesmo quando o cliente/fornecedor  não estiver cadastrado;
2. Exibir alerta para incluir um cliente/fornecedor previamente cadastrado;
3. Exibir atalho para cadastrar novo cliente/fornecedor.

**Comment by barretowiisk** [comment]
@cezargf 
Precisaremos entender o que ocorreu antes de apresentar esse erro? Foi atualização de versão? Se sim, de qual para qual?
As informações como as que pedi são pertinentes para entendermos o cenário e tentar reproduzir em ambiente de DEV.

**Comment by barretowiisk** [comment]
Acho que pegou a PR errada, a minha PR trata apenas do Mini Calendário, e nem estava dentre os arquivos alterados, contudo, houve uma PR do @lukasabino que visa preparar o Map-OS para futuras melhorias. Estamos investigando o que pode estar causando o erro, pelo que vimos é intermitente.

**Comment by cezargf** [comment]
@barretowiisk, desculpe, mas me referia a ter feito uma nova instalação utilizando a branch master atualizada com o commit da PR #2208.

**Comment by cezargf** [comment]
Quanto ao erro, é causado apenas quando o campo cliente/fornecedor estão preenchidos com dados que não estão previamente cadastrados em clientes.

**Comment by lukasabino** [comment]
@cezargf

Realizei a correção do caso relatado e foi feito o merge da PR agora a pouco.

Caso consiga realizar a atualização e nos informar se está tudo certo, fico a disposição.

**Comment by barretowiisk** [comment]
@cezargf 
Conseguiu realizar os teste? Se sim, não esquece de retornar o feedback e encerrar a ISSUE.

**Comment by cezargf** [comment]
Olá @barretowiisk e @lukasabino,
Realizei os teste de cadastramento de lançamentos com clientes/fornecedores não cadastrados e funcionou corretamente.

![image](https://github.com/RamonSilva20/mapos/assets/25113573/905e73d5-f876-4bab-9b0f-ff3502bd05e7)

Obrigado!

**Comment by barretowiisk** [comment]
Ainda estamos vendo uma maneira de forçar o cadastramento, pois não é gerado do idclient e isso impacta em projetos futuros. Agradecemos o report e estaremos sempre ajudando para fazer esse projeto crescer ainda mais.
