### ISSUE TITLE
MAPOS não abre mais

### ISSUE THREAD

**Issue by Shokaiii** [RamonSilva20/mapos#2211]
** Descreva o bug **
Usei o sistema normalmente na quinta-feira e quando fui abrir na sexta-feira ele já não estava mais abrindo.
Eu havia feito diversas modificações de código para adequar o sistema ao meu uso, mas não entendo de PHP, então era basicamente excluir a visualização do que eu não queria. 
Não queria ter que fazer manualmente tudo isso novamente reinstalando o sistema.
Eu uso o sistema tem quase um ano e nunca havia dado nenhum problema. Não fiz nenhuma alteração de código depois de ter instalado o sistema.

**Reproduzir**
Abrir o site que eu uso para hospedar o sistema já causa o erro (https://microgames.com.br/oscliente)

** Capturas de tela **
![00](https://github.com/RamonSilva20/mapos/assets/22568216/fbaab1b4-0914-4539-8dac-496385737d37)
![01](https://github.com/RamonSilva20/mapos/assets/22568216/92af3bd9-58f0-4b73-9632-c0109ae57905)
![02](https://github.com/RamonSilva20/mapos/assets/22568216/774b52ff-43c3-4bc3-a3da-7a0b52883dd1)
![03](https://github.com/RamonSilva20/mapos/assets/22568216/e4a598fd-ac0d-4d75-aad7-ab87477ebc4e)
![04](https://github.com/RamonSilva20/mapos/assets/22568216/f5d18567-20cd-4ad0-a688-824f72b080c4)
![05](https://github.com/RamonSilva20/mapos/assets/22568216/fe8c6ff6-b10a-46e3-8b39-5a6a97e04170)
![06](https://github.com/RamonSilva20/mapos/assets/22568216/411339e6-8dde-4ded-9243-9c8daff4756c)

**Comment by Shokaiii** [comment]
Atualização: Pensei em comparar onde estava dando erro com o arquivo da versão mais nova disponível aqui no GitHub e vi uma diferença na linha em questão (Linha 61 do arquivo login.php).

DIRETORIO DO ARQUIVO: application/views/mapos/login.php
MEU ARQUIVO: **<?= $configuration['app_theme'] == 'white' ? '<img src="'. base_url() .'assets/img/logo-mapos.png">' : '<img src="'. base_url() .'assets/img/logo-mapos-branco.png">'; ?>**
AQUIVO NOVO DO GITHUB: **<?= '<img src="' . base_url() . 'assets/img/logo-mapos-branco.png">'; ?>**

Fiz apenas a alteração dessa linha e o sistema voltou a abrir. Mas testando para ver se estava tudo certo com o resto do sistema eu pude ver que a Área do Cliente estava apresentando o mesmo problema. E ele foi resolvido da mesma maneira, com uma alteração idêntica, mas dessa vez na linha 57 do arquivo application/views/conecte/login.php.
O problema é que agora a Área do Cliente não está mais fazendo login. Criei um cliente de teste, mas não loga na conta dele e alterei a senha de um cliente antigo e também não faz o login.

**Comment by barretowiisk** [comment]
@Shokaiii 
Geralmente esse erro na configuracao indefinida ocorre em atualizações de versões anteriores a v3.38 para a atual, isso ocorria principalmente por causa da implementação da nova configuração, então em tese, é só importar o banco de dados update da sua versão até a versão atual que todos os ajustes serão feitos.
Contudo, me casou estranheza o erro apresentado relacionado a logo, poderia detalhar mais precisamente suas ações, informações importantes detalhando versão, passo a passo da sua atualização? Fiz diversas atualizações de versões mais antigas para atual  e não me deparei com esse erro.

Não acredito que seja um bug, apenas um caso muito pontual.

**Comment by Shokaiii** [comment]
@barretowiisk 
O pior é que eu não atualizei. Usei o sistema normalmente durante a quinta-feira e quando encerrei o expediente só fiz fechar o navegador. Na sexta-feira cheguei para trabalhar e ao abrir o site, ele estava apresentando esse erro.
A não ser que o sistema realize atualizações automáticas, está na mesma versão que eu instalei (Versão 4.38.0). 
Desde que eu instalei o MAPOS, não fiz nenhuma edição no código nem na hospedagem. Tanto que a única vez que eu abri a hospedagem foi no dia da instalação, em meados de novembro de 2022. Voltei a abrir ontem apenas para tentar resolver o problema.

Pelo pouco que eu entendo, vi em qual arquivo e linha estava tendo problema e fui tentar resolver.

O arquivo que estava causando o problema era o `application/views/mapos/login.php` e a linha era a 61.
O conteúdo da linha 61 era o seguinte:
`<?= $configuration['app_theme'] == 'white' ? '<img src="'. base_url() .'assets/img/logo-mapos.png">' : '<img src="'. base_url() .'assets/img/logo-mapos-branco.png">'; ?>`
Pelo que eu pude entender dessa linha de código, ela apenas verificava se o sistema estava com o tema claro ou tema escuro e colocava a logo correspondente ao tema. Não sabia se eu estava correto ou não quanto a isso, mas usei isso de base para tentar resolver.

Com o suposto problema em mente, vim aqui no github e abri o mesmo arquivo para comparar as linhas. E comparando pude ver que elas eram diferentes.
A linha do arquivo aqui no GitHub tinha o seguinte código:
`<?= '<img src="' . base_url() . 'assets/img/logo-mapos-branco.png">'; ?>`
Realizei um teste alterando a linha de código do arquivo que eu possuía pela linha de código do arquivo do GitHub e funcionou.

O mesmo erro ocorria na Área do Cliente e eu resolvi ele da exata mesma forma. Era em outro arquivo e em outro diretório, mas a linha de código era mesma. Alterei a linha de código e a Área do Cliente passou a carregar, mas percebi que é impossível realizar login nela.

Eu só não entendi como o sistema que estava funcionando normalmente passou a dar problema de um dia para o outro sem que fosse feita nenhuma alteração.

**Comment by Rodrigo-Paz** [comment]
Sugiro observar se não ouvi mudança na versão do php, mas estou vendo aqui que você usa hospedagem na hostigator, essa semana tive uma demanda de alguem que relatou virus no servidor deles, é bom olhar com suporte da sua hospedagem.
da uma conferida nos arquivos mencionado nos erros acima, em um que avaliei o arquivo estava totalmente corrompido pelo virus.

**Comment by barretowiisk** [comment]
@Shokaiii 
Por gentileza encerrar a ISSUE como resolvido.
