### ISSUE TITLE
Erro após instalação do sistema

### ISSUE THREAD

**Issue by bccinfo** [RamonSilva20/mapos#222]
Boa noite,

Eu faço todo o procedimento de instalação na minha hospedagem e o ultimo item a ser escolhido é a URL para login, qual o caminho colocar ali? Tentei diversas opções e todas elas não me levam para a pagina de login. 
Poderiam por favor me dar uma orientada?

**Comment by RamonSilva20** [comment]
Olá, você deve colocar a URL base (caminho até a pasta do sistema). Se você colocar na raiz basta colocar o domínio (http:sistema.com.br/), se você colocar dentro de uma pasta, adicione-a na URL (http://meusistema.com.br/sistema/).

**Comment by bccinfo** [comment]
Eu fiz todo o procedimento, porém, a URL apos instalação fica assim: meudominio.com.br/mapos-master/meudominio.com.br/mapos/login.
Depois removi tudo e fiz novamente o procedimento e ficou assim: meudominio.com.br/mapos-master/meudominio.com.br/mapos-master/mapos/login.

Na minha hospedagem eu estou colocando o sistema no home/public_html, la eu descompacto zip, fica a pasta mapos-master ( posteriormente posso alterar esse nome para outro? tipo "os"? Qual o caminho? lembro que uma vez peguei um tutorial que mostrava como.)

Para instalar eu digito apos descompactar: meudominio.com.br/mapos-master e ele encontra normal e tals, mas na hora da URL acho que estou me perdendo...

**Comment by RamonSilva20** [comment]
Pode sim renomear a pasta, mas aí tem que trocar na URL. Coloque a configuração diretamente no arquivo. Fica dentro de application/config/config.php, linha 31. Coloque como no exemplo abaixo, informe o protocolo, http ou https e termine com '/'.

**$config['base_url'] = 'http://meudominio.com.br/mapos/';**

**Comment by bccinfo** [comment]
Funcionou! Muito Obrigado!
