### ISSUE TITLE
Estou com erro na aba de Ordem de serviço

### ISSUE THREAD

**Issue by Weltoncastro97** [RamonSilva20/mapos#2222]
Ao clica na aba de ordem de serviço , me aparece esse erro, so nessa aba que isso acontece, versão nova, ultima 
![iScreen Shoter - Google Chrome - 230922163456](https://github.com/RamonSilva20/mapos/assets/77410845/e3168fd2-ed16-4447-80dc-f6c9b9613020)

**Comment by Fesantt** [comment]
da uma olhada na PR #2200 - ja foi resolvido esse problema

**Comment by barretowiisk** [comment]
@Weltoncastro97 
Por gentileza, retornar o feedback do problema e caso tenha sido resolvido, encerrar o ISSUE.

**Comment by Weltoncastro97** [comment]
Vou encerrar, tudo certo! valeu pela ajuda pessoal.
