### ISSUE TITLE
problemas com novo banco

### ISSUE THREAD

**Issue by CaramujoRei** [RamonSilva20/mapos#2224]
Olá.. tive um problema e precisei trocar a hospedagem.
Peguei todo o backup de DB e Files.
Tentei subir com a nova versão, mas nao deu muito certo, pois percebi que houveram mudanças no novo banco de dados , sendo assim quando eu faço a importação acaba sem eu conseguir fazer login e nem verificar se demais dados estão funcionando corretamente. 
Os usuários nao entendi porque nao consigo fazer a importação dos usuarios antigos. 
Quanto aos clientes verifiquei que existem duas novas colunas então nao consigo fazer a importação a não ser que edite todo o banco nessas partes.
As OS's também ainda não encontrei onde está o problema pra fazer a importação.
Teria alguma forma mais simples pra eu conseguir fazer a importação do banco?
Tentei subir o backup inteiro na versão antiga e atualizar o banco e arquivos, mas verifiquei que o banco nao altera nada então continuo sem conseguir fazer rodar.
Obrigadoo

**Comment by Fesantt** [comment]
certo qual versão do mapos vc estava usando na sua antiga hospagem?

**Comment by CaramujoRei** [comment]
Preciso subir novamente pra verificar. Mas já era mais recente. A última vez que instalei ela foi em 04/2023
Se não me engano era 4.33.

**Comment by Fesantt** [comment]
eu ja fiz algumas vezes da seguinte forma:
Faz a instalação da versão desejada
depois vai no seu phpmyadmin exclui todas as tabelas e sobe seu banco de dados antigo
assim que logar no sistema vai la nas configurações e coloca pra atualizar o banco de dados

No meu caso funcionou

**Comment by barretowiisk** [comment]
@CaramujoRei 
Por gentileza, retornar o feedback do problema e caso tenha sido resolvido, encerrar o ISSUE.

**Comment by willph** [comment]
Por falta de atualização estarei fechando a ISSUE, porem assim que responder eu reabro
