### ISSUE TITLE
Bugs Versão 4.41

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#2225]
Boa tarde, 

Realizando alguns testes na v4.41, detectei alguns problemas

1) Ao faturar uma OS o calendário esta aparecendo abaixo da janela de faturamento.
e o cabeçalho esta com falha no tema (Pure Dark) não assumindo o layout. 

![2023-09-25_17h09_59](https://github.com/RamonSilva20/mapos/assets/72340074/9018732b-f198-4ddf-a2a2-f2a5d4e3c1b0)

2) Ao incluir uma OS e adicionar produtos e já em seguida FATURAR, o valor fica zerado,
Para sanar o problema tem que ir em Detalhes da OS>Atualizar e após, FATURAR, nesse caso o valor volta a aparecer.

![2023-09-25_17h00_41](https://github.com/RamonSilva20/mapos/assets/72340074/07fdabb9-2429-4347-af41-51a184f5c89f)

3) Ao faturar uma OS com valores que contenham CENTAVOS e depois ir em LANÇAMENTOS>Alterar>Foi Pago>SALVAR
os centavos somente, ficando somente o valor cheio. ( Aparentemente ele muda de virgula para ponto )

![2023-09-25_17h12_20](https://github.com/RamonSilva20/mapos/assets/72340074/96427d8b-0b94-4928-8a44-29a1758ccb83)
![2023-09-25_17h12_29](https://github.com/RamonSilva20/mapos/assets/72340074/dde7b765-b3bc-4ac4-bff2-48ecc42292f5)

Testes executados em 3 equipamentos e navegadores diferentes.

OBS. Banco de dados zerado, instalação nova zerada <<

**Comment by barretowiisk** [comment]
Boa noite @jsfachini,
Obrigado pelo report.
1- O erro do Calendário já foi corrigido para a próxima versão.
![image](https://github.com/RamonSilva20/mapos/assets/45976190/39ec0054-5b94-47aa-8ff5-c7e355c1fa96)

2- Sobre o erro, está correto, se não houve inserção no banco de dados, não terá o que calcular, então você adiciona e atualiza e depois fatura.

3- O sistema utiliza o padrão americano de decimais, onde o mesmo é representado por ponto e não por virgula, replicando seu cenário identificamos que é o PHP que está retornando com virgula, mas o banco só considera com ponto, vamos investigar e abrir uma PR de correção.

**Comment by j7info** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/15069082/8ab2ab59-845a-4f55-8935-ee705aa701c9)
Estou tendo dois problemas com essa versão, um deles é dessa imagem acima, quando clico em "Ordem de Servoço" retorna esse erro aí. 
e abaixo o erro quando eu vou preencher com os dados emitente, retorna o erro que parece que não tem permissão pra subir  a logo.
![image](https://github.com/RamonSilva20/mapos/assets/15069082/404639df-7908-480f-9b80-da52bd2616a4)

**Comment by j7info** [comment]
Pessoal, acabei de instalar via docker, e ocntinua o memso erro, ainda não conferi quanto ao arquivo de logo, mas ao clicar no botão "Ordens de Serviço", dá o memso erro...

**Comment by barretowiisk** [comment]
@j7info 
Inicialmente recomendo que nesses casos específicos (no caso do Docker) crie uma ISSUE nova, para não gerar confusão sobre as soluções.
Em seguida, recomendo que acompanhe as PRs, fizemos uma serie de correções na v4.41 visando corrigir os problemas da versão, inclusive a que mencionou na função "Ordens" foi ajustada na PR #2200 e o mesmo já está funcionado na MASTER.
Sobre o script fico feliz que tenha sido funcional e útil, grato pelo feedback.

**Comment by barretowiisk** [comment]
Observei que erro abaixo não é necessariamente um erro na versão do Map-OS, e sim de um problema de permissões da pasta, a qual a pasta Upload não havia sido criada até o momento que atualizou os dados do emitente, recomendo que reveja as permissões das pastas, bem como para ajudar nesse quesito eu precisaria saber mais sobre sua estrutura, recomendo a abertura de uma ISSUE dedicada a esse problema, caso ocorra.

Obs: O script de autoinstalação já aplica as permissões necessárias para que tudo corra corretamente.


![image](https://github.com/RamonSilva20/mapos/assets/45976190/eed1e2f7-edb9-4914-aa15-df16fb8b664f)

**Comment by barretowiisk** [comment]
@jsfachini 
Sobre o cabeçalho do Faturar OS segue correção.. PR #2242

**Comment by willph** [comment]
Por falta de atualização estarei fechando a ISSUE, porem assim que responder eu reabro.

Já foram corrigidos, baixar a versão mais recente do Map-Os
