### ISSUE TITLE
Lembrete na hora de acessar o mapos

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#2226]
Seria legal, se ao abrir o mapos abrisse automaticamente um janela, pode ser modal ou outro tipo de notificacao, onde poderiamos colocar algum texto ou buscar no banco de dados alguns campos desejados, fiz um teste, logico q nao sou programador, mas apenas a ideia.
![lembrete mapos1](https://github.com/RamonSilva20/mapos/assets/69985797/41d99864-f7a5-460d-97c2-2c9baca6c5f3)

**Comment by Fesantt** [comment]
como você ja fez poderia abrir uma PR
se tiver duvida manda mensagem la no grupo do whatsapp que ajudo

**Comment by barretowiisk** [comment]
@marquinhomaquinas 
Não pense dessa forma, abre uma PR e precisando pode falar conosco e vamos colocar isso pra frente, o @Fesantt, @lukasabino e eu estamos focados em dar um gás no MapOS, eu vou passar seu Telegram para o @Fesantt e vamos colocar isso pra andar. A ideia é boa e pode se tornar uma funcionalidade muito boa no futuro do MapOS
