### ISSUE TITLE
Melhorias  arquivos para visualizar

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#2227]
Gosto muito do sistema, mas uma coisa q faz muita falta e a visuallização do arquivo, pois te obriga a fazer download, as vezes quer apenas consulta um manual ou até uma anotação tem q fazer o download, nao tem como adicionar um função para fazer a visualização e tb poder colocar uma capa no arquivo na hora do upload
mas deixando aqui meu sincero e muito agradecimento aos desenvolvedores, Deus abençoe ricamente
![ARQUIVO2](https://github.com/RamonSilva20/mapos/assets/69985797/e4faa5c8-810f-49c4-b5e5-d171b6904ac6)

**Comment by Fesantt** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/33626716/533c60cf-1b31-4342-a0d0-d33ab9f22877)
algo assim:?

**Comment by marquinhomaquinas** [comment]
realmente a ideia eh essa, arquivo de imagem ele ja faz isso,agora pdf não, o intessante seria poder selecionar uma capa principalemtne para os arquivos pdf ou ate mesmo capturando a primeira pagina do arquivo pdf, e na acao colocar a opção visualização seria interessante
