### ISSUE TITLE
Configuração Email

### ISSUE THREAD

**Issue by lucianoabis** [RamonSilva20/mapos#2229]
Fiz a configuração no arquivo email.php e ao executar o comado c:\xampp/php/php c:/xampp/htdocs/mapos/index.php email/process ele apresenta o seguinte erro. Como posso resolver ?

![erro](https://github.com/RamonSilva20/mapos/assets/146354376/014687e3-a3f6-4e4c-b520-0220cb88e9f3)

**Comment by barretowiisk** [comment]
Boa tarde,
Recomendo que chame o arquivo PHP com a extensão, conforme abaixo. Realizei testes em meu ambiente e funcionou corretamente.

C:\xampp\php\php.exe C:\xampp\htdocs\mapos\index.php email/process

![image](https://github.com/RamonSilva20/mapos/assets/45976190/6a65d8a7-2432-4e66-baa6-16fb7cdd954e)

**Comment by lucianoabis** [comment]
Obrigado, acabei resolvendo antes, percebi que meu arquivo email.php por algum motivo estava totalmente diferente do que o pessoal mostra, fiz outra instalação separada ai copiei o arquivo email.php e substitui no lugar do meu, ai deu certo, obrigado!

**Comment by lucianoabis** [comment]
[email.txt](https://github.com/RamonSilva20/mapos/files/12775155/email.txt)
este é o arquivo que apresentava o erro
