### ISSUE TITLE
Produto

### ISSUE THREAD

**Issue by lucianoabis** [RamonSilva20/mapos#2234]
Ao utilizar um produto controlado por unidade de metro, quando adicionado este produto para venda ou na ordem de serviço usando o quantidade picada, por exemplo 1.5 metros, o valor fica correto, porem a quantidade de produtos sempre mostra numero inteiro, colocando 1,2,3..... Não mostra no caso os 1.5

**Comment by Fesantt** [comment]
O sistema funciona com UN

**Comment by Fesantt** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/33626716/3c77ef63-7ffa-4dc3-9adb-87ddf50cf974)
a coluna estoque na tabela produtos esta marcada como INT, se colocar a mesma como VARCHAR vai resolver

**Comment by barretowiisk** [comment]
@Fesantt 
Podemos considerar isso para uma PR futura? acho que pode ser uma boa correção, depois vamos ver uma resolução sobre isso, mas ai precisa ser tratado com . e não ,
