### ISSUE TITLE
Layout imprimirOs

### ISSUE THREAD

**Issue by Weltoncastro97** [RamonSilva20/mapos#2236]
Gostaria de algum desenvovedor para criar layout de imprimir os como esse da foto:

![image](https://github.com/RamonSilva20/mapos/assets/77410845/76851b68-1d18-4c87-bd40-e1d30dce0d11)

**Comment by Fesantt** [comment]
Chama no WhatsApp 
https://api.whatsapp.com/send/?phone=5567996758663&text&type=phone_number&app_absent=0

**Comment by barretowiisk** [comment]
@Weltoncastro97 
Caso a solução tenha sido satisfatória ou conseguiu resolver a sua Feature, por gentileza, comente o feedback e encerre a ISSUE.
