### ISSUE TITLE
Sugestão para cadastro na OS

### ISSUE THREAD

**Issue by bccinfo** [RamonSilva20/mapos#224]
Boa noite. 
Comecei o uso do sistema hoje e reparei que ao abrir uma OS, o campo descrição produto/serviço ele não é impresso na OS, acredito ser um campo primordial de sair impresso pois ali poderia ser descrito o produto, a serie do mesmo e ate mesmo um mini checklist do produto ( arranhão, amassado e etc).

O campo defeito poderiam existir dois campos dessa modalidade: um para o relatado (pelo cliente) e outro para o encontrado (pelo técnico)

O campo para solução adotada e observação. Como sugestão, poderia mudar o posicionamento na impressão e deixar observação abaixo de solução adotada.

Na listagem das OS não aparece a descrição do produto, isso pode vir a ser um problema se o mesmo cliente tiver 5 produtos na AT e não souber o numero da OS?

Ao finalizar uma OS percebi que consigo altera-la livremente, uma sugestão seria não permitir alterar os campos ja escritos para não haver problemas futuros.

Ao finalizar a OS e tendo o pagamento confirmado, poderia ter a opção de imprimir um recibo de pagamento e apresentar ja a garantia legal do consumidor de 90 dias.

**Comment by heliocristaldo** [comment]
Todas essas observações você pode está implementando em seu sistema, acaba que é uma customização especifica, o meu se assemelha muito ao seu, porem coloquei mais coisas.
Não sou programador nem desenvolvedor, sou estudante de engenharia e estou usando ele para me dar suporte onde trabalho.

Segue abaixo minha base de testes
http://51.38.233.84/os/
teste@teste.com
123456

**Comment by bccinfo** [comment]
Boa tarde Helio!

Eu não faço a minima idéia de como fazer essas implementações...

Como utilizo uma ordem de serviço manual constantemente, observei esses pontos do post como mais uma ajuda ao sistema. O sistema em si é ótimo! E com certeza esta caminhando pra ficar melhor ainda.

**Comment by evertonrj** [comment]
> 
> 
> Todas essas observações você pode está implementando em seu sistema, acaba que é uma customização especifica, o meu se assemelha muito ao seu, porem coloquei mais coisas.
> Não sou programador nem desenvolvedor, sou estudante de engenharia e estou usando ele para me dar suporte onde trabalho.
> 
> Segue abaixo minha base de testes
> http://51.38.233.84/os/
> [teste@teste.com](mailto:teste@teste.com)
> 123456

Helio, bom dia.

Rapaz, ficou muito top esse seu upgrade. Estou começando meus primeiros passos no PHP, gostaria muito de realizar algumas implementações no meu sistema, mas fico perdido sem saber por onde começar. se pudesse dar uma dica, seria de grande valia...

Vlw.

**Comment by heliocristaldo** [comment]
Bom dia Erverton, estou na mesma situação que você, as pessoas vão me dando dicas e vou implementando aos poucos. Mas vai pontuando as duvidas e que no que eu puder ajudar vamos nos ajudando, não sou programador, estou usando essa ferramenta para me auxiliar na empresa que trabalho.

**Comment by evertonrj** [comment]
Opa @heliocristaldo , boa noite.

Então cara, eu achei esse sistema TOP, necessitando de alguns refinos para ficar melhor ainda como:

- Poder adicionar a quantidade de serviços na OS.
(no meu caso, o técnico vai instalar 150 fechaduras, cada instalação custa aproximadamente R$25,00, logo eu tenho como adicionar essa quantidade ao serviço e ele soma automaticamente).


- Poder ajustar o preço do produto ou serviço na OS.
(habilitar o campo de preço 'ele já pré carrega o preço cadastrado', mas me dá a opção de ajustar na hora.


- Todos os meu técnicos tem acesso ao sistema, mas eles conseguem visualizar todas as O.S cadastrada mesmo não sendo a deles, seria interessante que eles só vissem as O.S cadastradas para eles.


- Ter o Campo "observações", tanto para o cliente quanto o usuário, pois nesse campo eu teria como no caso do cliente (hotel) cadastrar o nome da pessoa de contato. E no caso do usuário (técnico) ter anotado os dados bancários.



Basicamente é isso que necessito por hora...


Não sou programador, mas tenho noção, pois estudei HTML e CSS, eu preciso me entender dentro da estrutura dos códigos, aonde fica o que e como alterar, vi que ele utiliza o codeigniter, mas não faço ideia de como usar....

Qualquer ajuda é bem vinda, grato!
