### ISSUE TITLE
Undefined array key "control_2vias"

### ISSUE THREAD

**Issue by diamantes-eletronicos** [RamonSilva20/mapos#2243]
Bom dia, pessoal. Estou um com erro no MapOS, ao tentar ir nas configurações, aparece a seguinte mensagem de erro:

Undefined array key "control_2vias"

Alguém poderia me ajudar a resolver?

**Comment by Fesantt** [comment]
Ta usando qual versão do MAP-OS?

**Comment by barretowiisk** [comment]
Boa tarde @diamantes-eletronicos 
Selecione o banco de dados e execute o seguinte comando:

`INSERT INTO `configuracoes` (`idConfig`, `config`, `valor`) VALUES (15, 'control_2vias', 0);`

**Comment by diamantes-eletronicos** [comment]
> Boa tarde @diamantes-eletronicos Selecione o banco de dados e execute o seguinte comando:
> 
> `INSERT INTO `configuracoes` (`idConfig`, `config`, `valor`) VALUES (15, 'control_2vias', 0);`

Boa tarde, amigo. Muito grato pela ajuda, deu certo aqui!
