### ISSUE TITLE
Erro ao abrir a OS

### ISSUE THREAD

**Issue by juniorgtxx** [RamonSilva20/mapos#2244]
Boa tarde pessoal estou com este erro ao abrir a ordem de serviço eu conferi o fix do PR#2000 deu certo porém quando eu escolho qualquer uma das ordem de serviço me retorna com esse erro abaixo.
Whoops\Exception\ErrorException thrown with message "Undefined variable $result_vendas"

Stacktrace:
#10 Whoops\Exception\ErrorException in /var/www/html/sistema/application/views/clientes/visualizar.php:218
#9 Whoops\Run:handleError in /var/www/html/sistema/application/views/clientes/visualizar.php:218
#8 include in /var/www/html/sistema/application/vendor/codeigniter/framework/system/core/Loader.php:969
#7 CI_Loader:_ci_load in /var/www/html/sistema/application/vendor/codeigniter/framework/system/core/Loader.php:496
#6 CI_Loader:view in /var/www/html/sistema/application/views/tema/conteudo.php:25
#5 include in /var/www/html/sistema/application/vendor/codeigniter/framework/system/core/Loader.php:969
#4 CI_Loader:_ci_load in /var/www/html/sistema/application/vendor/codeigniter/framework/system/core/Loader.php:496
#3 CI_Loader:view in /var/www/html/sistema/application/core/MY_Controller.php:64
#2 MY_Controller:layout in /var/www/html/sistema/application/controllers/Clientes.php:189
#1 Clientes:visualizar in /var/www/html/sistema/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:533
#0 require_once in /var/www/html/sistema/index.php:306
![erro](https://github.com/RamonSilva20/mapos/assets/98664237/cbdcfc77-b6a2-487a-bf87-8d68ddd48f5e)

**Comment by barretowiisk** [comment]
Boa tarde @juniorgtxx 
Já foi ajustado, para receber as ultimas correções, siga o passo a passo abaixo.

_Obs: Sempre faça backup._

![Screenshot_3](https://github.com/RamonSilva20/mapos/assets/45976190/fc76b55b-6230-43c8-838b-25b296d682de)
![Screenshot_4](https://github.com/RamonSilva20/mapos/assets/45976190/a37585d4-3a60-479f-a5cd-d56c64f41be6)
![Screenshot_5](https://github.com/RamonSilva20/mapos/assets/45976190/ecfff4b1-68b1-4d26-958c-93bba114d3e7)

**Comment by juniorgtxx** [comment]
boa tarde então eu peguei aqui pelo que eu vi a ultima versão é 4.41.0

**Comment by barretowiisk** [comment]
Estranho, está com a estrutura de Laravel, acesse o projeto mapos e não mapos4, verifique se realmente está baixando a versão correta.

**Comment by juniorgtxx** [comment]
eu vou reinstalar ele então novamente mas eu baixei aqui o arquivo não foi de terceiros.

**Comment by juniorgtxx** [comment]
Atualizando o topico
Peguei o arquivo pelo https://github.com/RamonSilva20/mapos instalei novamente mas desta vez eu não peguei coloquei o banco de dados antigo,fui acessar a parte de Ordem de serviço deu erro ai deletei as linhas do 846-856 ele abriu eu consegui acessar a parte e criar uma OS porém ao clicar ele da esse erro.
![erro](https://github.com/RamonSilva20/mapos/assets/98664237/a6614059-cd93-449c-a587-ae77f8446595)

**Comment by willph** [comment]
> Atualizando o topico Peguei o arquivo pelo https://github.com/RamonSilva20/mapos instalei novamente mas desta vez eu não peguei coloquei o banco de dados antigo,fui acessar a parte de Ordem de serviço deu erro ai deletei as linhas do 846-856 ele abriu eu consegui acessar a parte e criar uma OS porém ao clicar ele da esse erro. ![erro](https://user-images.githubusercontent.com/98664237/274445662-a6614059-cd93-449c-a587-ae77f8446595.png)

Após importar o banco de dados antigo tentou atualizar ele?

Ex:
http://localhost/mapos/index.php/mapos/configurar

em `atualizações` depois `Banco de Dados`.

_**Obs.: Seu endereço pode ser diferente do meu, pois estou executando em ambiente local e nome da pasta é mapos**_

![image](https://github.com/RamonSilva20/mapos/assets/17226802/bdb3ca98-566e-4de2-95a1-649afcdd758f)

**Comment by juniorgtxx** [comment]
bom dia, eu fiz isso mas vou tentar de uma outra forma

**Comment by willph** [comment]
Por falta de atualização estarei fechando a ISSUE, porem assim que responder eu reabro.

Por favor testar a versão mais recente do Map-Os para vê se esse erro ainda persiste.
