### ISSUE TITLE
Erro ao abrir Ordens de Serviço

### ISSUE THREAD

**Issue by wallaprog** [RamonSilva20/mapos#2248]
Olá a todos, sou novo aqui, se este post não estiver nos padrões de envio, peço perdão pois estou aprendendo a usar o Github ainda.

Problema:
Ao abrir "Ordens de Serviço" está aparecendo este erro

ParseError thrown with message "syntax error, unexpected token "if", expecting "function" or "const""

Stacktrace:
#1 ParseError in /var/www/html/mapos-4.41.0/application/controllers/Os.php:847
#0 require_once in /var/www/html/mapos-4.41.0/index.php:306

SO:
Ubuntu Server 22.04.3 LTS - (GNU/Linux 5.15.0-86-generic x86_64)

Navegador
Google Chrome - Versão 117.0.5938.152 (Versão oficial) 64 bits

Link que aparece na barra de endereço:
http://172.16.1.20/mapos-4.41.0/index.php/os

Imagens do problema:

![Captura de tela 17-10-2023 11 13 10](https://github.com/RamonSilva20/mapos/assets/68176708/5a8f59c3-b819-486c-b94f-96eb8cdd7e86)
![Captura de tela 17-10-2023 11 22 15](https://github.com/RamonSilva20/mapos/assets/68176708/d863945d-10a6-445d-8954-9df9b2dde001)
![Captura de tela 17-10-2023 11 22 41](https://github.com/RamonSilva20/mapos/assets/68176708/97d1e9c6-4f9f-4b05-a112-ab1861ab5c49)

Parabéns pelo projeto. Sucesso!

**Comment by Pr3d4dor** [comment]
@wallaprog Usa o mapos-master, a versão 4.41.0 está com problema.

**Comment by wallaprog** [comment]
@Pr3d4dor, boa noite, seria esta instalação automatizada?

Instalação Automatizada (Ubuntu/Debian)](https://github.com/RamonSilva20/mapos#instala%C3%A7%C3%A3o-automatizada-ubuntudebian)
Abra o Terminal ou acesse seu servidor via SSH;
Eleve o privilégio aplicando sudo su (Recomendado);
Execute o comando: curl -o MapOS_Install.sh -L https://raw.githubusercontent.com/RamonSilva20/mapos/master/install.sh && chmod +x MapOS_Install.sh && ./MapOS_Install.sh

**Comment by barretowiisk** [comment]
Boa noite @wallaprog 
Você está executando em localhost ou hospedagem?
O que o Gian quis orientar é que você deve baixar da Master projeto, já houveram correções dos bugs.

O método mais simples é seguir o passo a passo seguindo as etapas de atualização, não se preocupe com a versão.
 abaixo![IMG-20231006-WA0020.jpg](https://github.com/RamonSilva20/mapos/assets/45976190/433e0095-7ad6-4556-89c5-75ee47e92f35)

.

**Comment by wallaprog** [comment]
@barretowiisk Bom dia, nao estou usando VPS apenas instalei numa maquina fisica mesmo. Essa versao mapos master é aquela do site mapos.com.br (mapos-master)?

**Comment by barretowiisk** [comment]
Bom dia @wallaprog 
Acaba sendo o mesmo que uma VPS rsrsrs...
Segue a orientação e resolverá o problema, pois as correções já foram feitas como falamos anteriormente.

**Comment by wallaprog** [comment]
> Bom dia @wallaprog 
> Acaba sendo o mesmo que uma VPS rsrsrs...
> Segue a orientação e resolverá o problema, pois as correções já foram feitas como falamos anteriormente.

So pra confirmar, é a versao do site mapos.com.br?

**Comment by barretowiisk** [comment]
@wallaprog 
Por gentileza informe o feedback da ação orientada e se resolveu o problema, encerre a ISSUE.

**Comment by willph** [comment]
> > Bom dia @wallaprog
> > Acaba sendo o mesmo que uma VPS rsrsrs...
> > Segue a orientação e resolverá o problema, pois as correções já foram feitas como falamos anteriormente.
> 
> So pra confirmar, é a versao do site mapos.com.br?

Por falta de atualização estarei fechando a ISSUE, porem assim que responder eu reabro.
