### ISSUE TITLE
Gostaria de ajuda

### ISSUE THREAD

**Issue by vitolike** [RamonSilva20/mapos#225]
Boa tarde, 

Gostaria de ajudar no desenvolvimento, gosto muito de mexer com CodeIgniter.

Desenvolvi um modulo de vendedores..

Att

**Comment by RamonSilva20** [comment]
Olá @vitolike. Adicionei seu usuário como colaborador do projeto. Dê preferência aos issues sugerido pelos usuários, ou pode auxiliar na nova versão do sistema, por enquanto na fase de refatoração.
