### ISSUE TITLE
Função a nexos

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#2254]
preciso colocar uma função para tirar foto.
clicar na opção e abri a câmera e tirar foto para anexa a imagem, no atual momento uso a câmera do celular mas não consigo envia a foto porque a resolução é alta ai da erro de tamanho não permitido

**Comment by barretowiisk** [comment]
Boa tarde @wesley020291 
Para melhor entendimento, informe o passo a passo de como é ocorrido o erro, pelo que imagino você está tentando fazer isso em Anexo da OS. Ponto de observação, estamos no momento em freeze para migração do projeto para Laravel, então somente FIX/CORREÇÕES serão publicados.

Como contorno análise o código e altere o tamanho máximo para upload no sistema, dependendo pode ser necessário alterar no seu servidor de hospedagem.
