### ISSUE TITLE
Erros ao gerar Relatórios MapOs4.42

### ISSUE THREAD

**Issue by SuperPorte** [RamonSilva20/mapos#2259]
Não sei se estou fazendo isso no lugar certo. Por favor me desculpem se não o for.

** Descreva o bug **
MapOs instalado pelo script install.sh contido na Readme.md
Instalação Local, Linux MX, Xampp8.2
Instalação limpa, SEM restauração de backup
Ao clicar para gerar relatórios PDF, apresenta tela de erro
Testei todos os relatórios e dá o mesmo erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'relatórios'
2. Clique em 'relatorio desejado'
3. Clique para gerar qualquer relatório em PDF
4. Ver erro

**Comportamento esperado**
Que o relatório fosse gerado normalmente

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
![image](https://github.com/RamonSilva20/mapos/assets/68247011/cd9c59c8-0c7a-466e-84be-fd263460f492)
![image](https://github.com/RamonSilva20/mapos/assets/68247011/1351760a-50e8-4a76-9e03-dcb794a0f6a0)

** Desktop (preencha as seguintes informações): **
 - SO: [MXlinux 23.1 (debian)]
 - Navegador [Firefox ]
 - Versão [por exemplo 119.0 (64-bits)]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
Observei que o caminho "/opt/lampp/htdocs/mapos/assets/uploads/temp/mpdf não foi criado. Só vai até assets
Pelo terminal criei todo o caminho /opt/lampp/htdocs/mapos/assets/uploads/temp/mpdf
Testei e ainda deu erro
sudo chmod -R 777 /opt/lampp/htdocs/mapos/assets/uploads/temp/mpdf
Testei de novo e todos os relatórios PDFs funcionáram.
![image](https://github.com/RamonSilva20/mapos/assets/68247011/4940960b-dfe3-47dd-a27d-897a1efaa710)

**Comment by willph** [comment]
Enviei uma correção na PR #2267, aguarda analise e depois um possível merge

**Comment by SuperPorte** [comment]
Bom dia Pessoal.
O erro do relatório (https://github.com/RamonSilva20/mapos/issues/2259) é sobre a falta do caminho e não da falta de imagem.
Houve algum ruido entre o erro relatado e a solução proposta.
Ou eu não entendi a solução proposta.
Se possível, alguém me explica? Obrigado.
