### ISSUE TITLE
Erro HTTP 500

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#226]
Erro http 500 ao acessar cadastro de venda.

![erro venda](https://user-images.githubusercontent.com/25686016/48844325-99fea780-ed80-11e8-99c8-91a0234f0900.JPG)

**Comment by RamonSilva20** [comment]
Olá @SOROInfo. Por favor verifique o arquivo de log do Apache para ver qual exatamente o erro.

**Comment by SOROInfo** [comment]
O sistema está hospedado na hostgator... estou procurando pela informação.

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qua, 21 de nov de 2018 às 18:37, Ramon Silva <notifications@github.com>
escreveu:

**Comment by SOROInfo** [comment]
Oi Ramon, encontrei esse log na pasta do sistema. Está retornando erro na
linha 47 do modelo de vendas.

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qua, 21 de nov de 2018 às 18:37, Ramon Silva <notifications@github.com>
escreveu:

**Comment by RamonSilva20** [comment]
Ok, tem como colocar a mensagem de erro para analisarmos?

**Comment by SOROInfo** [comment]
Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qui, 22 de nov de 2018 às 13:10, Ramon Silva <notifications@github.com>
escreveu:

**Comment by SOROInfo** [comment]
![erro](https://user-images.githubusercontent.com/25686016/48920014-73726680-ee7d-11e8-91d0-f805540484c6.jpg)

**Comment by SOROInfo** [comment]
![erro](https://user-images.githubusercontent.com/25686016/48920108-11663100-ee7e-11e8-94ea-ecfb8b7c4be8.jpg)

**Comment by SOROInfo** [comment]
Conseguiu ver o erro Ramon?

**Comment by RamonSilva20** [comment]
Você excluiu algum usuário? Existe este registro no banco de dados? A query está retornando false, talvez o ideal seria usar um LEFT JOIN com a tabela de usuários e verificar o retorno para evitar esse erro.

**Comment by SOROInfo** [comment]
Sim, tive problemas com o usuário. Usava a versão 3.1.9 e depois que
atualizei para versão 3.1.14 não consegui logar mais. Acabei criando um
novo usuário manualmente pelo phpmyadmin e consegui logar no sistema. Tive
alguns problemas pois meus registros tinham um id de usuario diferente do
id do novo usuario que criei, então fiz uma alteração manual para fazer
bater o id. Deu certo, mais estou tendo problemas com a venda.

Como devo proceder para fazer o LEFT JOIN?

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website http://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em sex, 23 de nov de 2018 às 13:03, Ramon Silva <notifications@github.com>
escreveu:

**Comment by SOROInfo** [comment]
O que acho estranho é que existe o usuário e o id do usuário bate com o id de usuário da tabela de venda.

![tb-usuario](https://user-images.githubusercontent.com/25686016/49083331-6960b700-f233-11e8-9f6d-bc964444f5d6.JPG)
![tb-vendas](https://user-images.githubusercontent.com/25686016/49083333-6bc31100-f233-11e8-8cbc-1b7bad6063a8.JPG)

**Comment by RamonSilva20** [comment]
Realmente, parece correto. A venda de ID 115 está com o mesmo valor? Outra coisa que você pode verificar é se o ID do cliente também está correto.
