### ISSUE TITLE
Nfe

### ISSUE THREAD

**Issue by Felipeb96** [RamonSilva20/mapos#2264]
Boa noite, preciso de algum desenvolvedor ,para fazer a parte da nota fiscal do sistema. Valores a combinar...

**Comment by devcael** [comment]
Boa tarde, já encontrou alguém pra fazer o serviço? estou disponivél

**Comment by Felipeb96** [comment]
boa noite, ainda nao, entrar em contato no email. felipebarbosa1996@hotmail.com.br

**Comment by erpzeos** [comment]
Boa Tarde, Caso precisem de ajuda gostaria de participar do desenvolvimento.
