### ISSUE TITLE
Adicionar novos clientes

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#2265]
Não estou conseguindo adicionar novos clientes, ao salvar o novo cliente o campo do Nome/Razão Social fica vermelho e aparece uma mensagem "Ocorreu um erro."

 - SO: Windows 10 Pro 64 bits
 - Navegador Brave
 - Versão 4.41.0

**Comment by willph** [comment]
Baixei o Brave 1.62.21 e funcionou tranquilamente.

baixe a versão mais recente do Mapos, o codigo Master
