### ISSUE TITLE
Erro ao editar lançamento de receita

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#2266]
Erro ao alterar lançamento de receita para pago "Falha!
Ocorreu um erro ao tentar editar lançamento."

SO: Windows 10 Pro 64 bits
Navegador Brave
Versão 4.41.0

**Comment by willph** [comment]
Qual versão esta usando?

Baixou a versão MASTER do código para testar se esse erro ocorre?
Fiz uma simulação aqui e não apresentou esse erro mencionado.

Atenciosamente, Equipe MapOS

**Comment by denis-ulterior** [comment]
Resolvi colocando:

is_array($pagamento)?$pagamento="":$pagamento;

Na função editar logo antes da $data
Acontece que no php8.1 apresenta array to string conversion pois ao vir vazia volta um array vazio.

Espero ter ajudado,
