### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#2272]
** Descreva o bug **
Na tela de pré-instalação esta tudo ok.
Porem ao continuar, não finaliza a instalação, fica em "Por favor espere"...
utilizo o xampp como servidor 

** Desktop **
 - SO: windows 10
 -  PHP 8.2.4
  - Navegador chrome
--

alguém saberia auxiliar?

**Comment by willph** [comment]
Qual versão esta tentando instalar?

**Comment by monutb91** [comment]
do mapos, a ultima versão acredito, 4,42,0 e xampp 8.2

**Comment by willph** [comment]
Eu testei aqui e foi tranquilo, usei o codigo master.

`git clone https://github.com/RamonSilva20/mapos`

**Comment by barretowiisk** [comment]
Por recomendação,
Utilize o auto instalador para Windows ([clique aqui](https://github.com/RamonSilva20/mapos#instala%C3%A7%C3%A3o-automatizada-windows-1011)), dessa forma todas as dependências necessárias serão instaladas e o MAP-OS ficará funcional.

Vídeo tutorial:
https://youtu.be/NgXzzBB_2bM?si=UMNaoHQ07ywAr4Na

_Observação: Antes de executar o script desinstale o XAMPP e Composer que instalou anteriormente para evitar incompatibilidade. Caso o script apresente erro ao executar no PowerShell remova os caracteres "&&" e no lugar coloque um paragrafo (ENTER) e cole no terminal._

Em caso de dúvidas sobre o script pode me procurar no WhatsApp.
https://wa.me/5581989505723

**Comment by maycon1977** [comment]
Tutorial batuta demais. Valeu pelas dicas!
