### ISSUE TITLE
Impressoras A4 e Térmica

### ISSUE THREAD

**Issue by Claudiomfa** [RamonSilva20/mapos#2275]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

Boa tarde,

Alguém sabe se há alguma maneira de incluir direto no código uma forma de selecionar uma impressora para imprimir a4 e outra para impressão térmica, ambas as impressoras estando instaladas no computador local?

É chato estar sempre a selecionar no browser em que impressora queremos que se imprima em a4 ou térmica. Em alguns casos se não dermos conta vamos imprimir uma a4 na impressora fiscal ou vice-versa.

**Comment by SuperPorte** [comment]
Se estiver no Windows, tem a opção de "[x] Deixar o Windows decidir a impressora padrão".
Experimenta se faz o Sistema enviar para a impressora correta

**Comment by Claudiomfa** [comment]
Com essa opção fica exatamente igual. Isso só vai deixar o Windows selecionar a impressora padrão. O que eu preciso é que no código interno ao imprimir uma folha normal o mapos utilize a impressora a4 instalada, ao imprimir um talão o mapos utilize a impressora de talões. Mas sem que haja escolha da impressora pelo utilizador.
