### ISSUE TITLE
Faturamento Parcelado na venda e na OS

### ISSUE THREAD

**Issue by gusttavoh** [RamonSilva20/mapos#2276]
Ao clicar em faturar na ordem de serviço e na venda, ter a mesma opção de parcelamento, de maneira que ao finalizar o faturamento fique parcelado no financeiro, ou seja com a mesma opção de parcelamento do modal de lançamento financeiro.

**Comment by barretowiisk** [comment]
Olá @gusttavoh 
No momento o projeto está em Freezing para migrção de CI3 para Laravel, Features serão rejeitadas até a nova versão ser publicada, apenas FIX BUG serão atendidos.

Já temos essa necessidade em vista, mas com a migração teremos que aguardar a finalização.
