### ISSUE TITLE
Preço de COMPRA em RELATÓRIOS.

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#2277]
Boa noite, 

Segue sugestão para os relatórios de produtos, incluir **"Valor de Compra"**
hoje os valores que estão em estoque são contabilizados mas somente o valor de venda e não o de custo,
seria interessante esta opção para saber o quanto de investimento tem em estoque,
contabilizando também a quantidade, exatamente como "Valor Estoque"

![2023-11-08_22h45_00](https://github.com/RamonSilva20/mapos/assets/72340074/74ac96e8-77a0-45cc-ad11-6d8a44954fc7)

**Comment by Fesantt** [comment]
![image](https://github.com/RamonSilva20/mapos/assets/33626716/887e29ca-792d-4fe6-ab77-804a068f50dd)
algo assim?
só um exemplo, ignore a formatação

**Comment by jsfachini** [comment]
Boa tarde @Fesantt 

Perfeito, testei e a funcionalidade esta ok
Se me permite fiz algumas alterações em relação ao layout
inverter as duas ultimas colunas, no mais esta ótimo.
Deixarei aqui o arquivo com as modificações. 

Obrigado.

[imprimirProdutos.zip](https://github.com/RamonSilva20/mapos/files/13418997/imprimirProdutos.zip)

![2023-11-20_17h14_08](https://github.com/RamonSilva20/mapos/assets/72340074/532dbf0c-13d6-4f51-adea-3bd17cae5d5a)

![2023-11-20_17h14_55](https://github.com/RamonSilva20/mapos/assets/72340074/8045a676-cb78-4dd3-8431-61b09c703ebf)

**Comment by Fesantt** [comment]
Sem problemas, pode fazer as alterações que achar necessario 👯
