### ISSUE TITLE
Lançamentos - Bug (Valor)

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#2281]
Em LANÇAMENTOS > Ao clicar no campo (valor) da OS faturada é alterado 
Segue ex:

Valor correto - R$150,00 ( não esta aparecendo (,) - mas o valor soma ao total normal como R$150,00
![2023-11-17_10h26_50](https://github.com/RamonSilva20/mapos/assets/72340074/78e96ca1-9758-4955-af34-981558ffa1c3)

Se clicar no campo valor 150 ele altera sozinho para 1,50
![2023-11-17_10h26_59](https://github.com/RamonSilva20/mapos/assets/72340074/4aec2825-eed0-4b81-98b8-b97b0917a621)

**Versão te deste: 4.42 ( base limpa e base em produção ) ambas acontecem o mesmo bug.**

OBS: Isso só acontece em LANÇAMENTOS, se faturar uma OS e clicar no campo valor, não se altera.

**Comment by barretowiisk** [comment]
Bom dia @jsfachini 
Esse BUG já foi resolvido, para que tenha acesso a correção realize a atualização do seu sistema MAP-OS.
Ex:
![image](https://github.com/RamonSilva20/mapos/assets/45976190/8d8f06b7-14dd-4716-8e51-8306ae99d4af)

Para atualizar, siga as instruções abaixo:
![Update-MapOS - Copia](https://github.com/RamonSilva20/mapos/assets/45976190/5fa97701-0013-4b13-9820-8af9c1da4e88)

**Comment by jsfachini** [comment]
Boa noite @barretowiisk 

Então, a versão esta a mais atual, mesmo assim fiz a atualização pelo sistema mas o erro persiste,
o que percebi é que, só após a importação do banco que esta em produção é onde acontece a divergência.

**Comment by barretowiisk** [comment]
Entra em contato pelo suporte da SysGO.com.br e no chat seleciona falar com um atendente, eu quero entender melhor esse caso.

Estais usando em localhost ou hospedado?

**Comment by jsfachini** [comment]
Boa tarde @barretowiisk 

Quando puder me avisa que entre em contato.

Estou usando localhost, em um servidor físico fora da rede local.

**Comment by barretowiisk** [comment]
https://wa.me/+5581989505723

**Comment by barretowiisk** [comment]
Boa noite @jsfachini,
Após analise do banco de dados identifiquei que o tipo de coluna está incorreto, possivelmente causado por atualização do seu sistema em que houve alteração do banco de dados e você não atualizou.

O tipo atual da coluna 'valor' da tabela 'lancamento' está VARCHAR(15), porém o tipo correto é DECIMAL(10,2) respeitando assim o valor como dado monetário, para correção é necessário aplicar o comando SQL abaixo e o mesmo irá ajustar não só a coluna como refletir nos valores contidos nela.

ALTER TABLE `lancamentos` CHANGE `valor` `valor` DECIMAL(10,2) NULL DEFAULT '0.00';

**Comment by jsfachini** [comment]
Boa noite @barretowiisk 

**( ALTER TABLE lancamentos CHANGE valor valor DECIMAL(10,2) NULL DEFAULT '0.00'; )**

Applied n resolved, thanks
