### ISSUE TITLE
Cadastro de Equipamentos

### ISSUE THREAD

**Issue by adrianoazevedo** [RamonSilva20/mapos#2283]
Uma das falhas do MAP-OS é não ter um cadastro de equipamentos, para controle de garantia e onde foi aplicado os serviços e produtos. Equipamentos devem ser ligados a um cliente. Assim saberíamos, em qual equipamento foi dado manutenção, quais serviços fizemos e quais produtos/insumos utilizamos. Poderemos então ter controle de garantia, qualidade do serviço, dos técnicos, dos produtos/insumos, clientes problemáticos e até oferecer contratos de manutenção.

**Comment by Fesantt** [comment]
Futuramente vai ser implementado, muito provavel no que seja no projeto em Laravel que esta em desenvolvimento.
Esse projeto em C.I. 3  está aceitando somente correções de bugs, mas sim seria bem possivel implementar essa Feature que você citou
