### ISSUE TITLE
Após restaurar backup, nao faz mais login

### ISSUE THREAD

**Issue by DersoTech** [RamonSilva20/mapos#2285]
Olá a todos, sou um usuario a pouco tempo do MAPOS.
Estava tudo funcionando perfeitamente até que tive que trocar de pc.
Realizei um backup do sistema antes, e agora no novo pc fiz a instalação da nova versão, ele em branco novo, abriu normalmente
Mais após eu importar o backup do sistema antigo, fico travado na tela de login.
Realizei algumas buscas aqui e fiz o procedimento de criar um novo usuario admin@admin.com mais tambem não entra.
Poderiam me auxiliar em oque posso fazer para resolver?

![image](https://github.com/RamonSilva20/mapos/assets/151527254/93f6aae1-18f1-41e7-b43c-5bc17e31f57a)

**Comment by jsfachini** [comment]
Boa tarde @DersoTech 

Quando você criou o banco de dados novo usou o mesmo nome do qual estava em seu sistema antigo ?
o e-mail e senha criado no novo mapos é o mesmo do antigo ? 

Se cadastrar tudo igual ao antigo, não tem erro!

**Comment by barretowiisk** [comment]
Boa noite @DersoTech 
Quando o banco de dados é importado os usuário são substituídos, ou seja, o usuário atual é o mesmo do banco de dados a qual você importou para o novo banco de dados.

**Solução**
Acesse seu phpMyAdmin, acesse seu banco de dados, clique na tabela "usuarios" e altere a informação contida dentro da coluna senha referente ao usuário que deseja alterar a senha, copiando e colando a chave a baixo, isso vai alterar a senha do usuário para 123456.

`$2y$10$ILURo1IyCMrpoQgzB1wvk.cRMUGDtZ7RdvRkWBgH3UtROponn6EWu`

![image](https://github.com/RamonSilva20/mapos/assets/45976190/a9074e8e-9552-45b2-a394-85d817562716)

Caso ainda necessite de suporte, adquira uma instância MAP-OS com a parceria oficial do Projeto [SysGO Soluções](https://sysgo.com.br/mapos-github) e tenha suporte exclusivo ao sistema.

**Comment by juliolobo** [comment]
Resolvi isso no MapOS de um amigo ontem.
Quando atualiza de uma versão mais antiga pra atual algumas colunas no DB ainda não existem.
Na tabela "usuarios" falta a coluna "url_image_user" (varchar 255) que é consultada na hora do login.
Inclua essa coluna em "usuarios"

Se der erro quando for acessar "Configurações > Sistema" pra atualizar o BD, vá ao banco na tabela de "configuracoes" insira as linhas 
- "os_status_list" com valor "["Aberto","Faturado","Negocia\u00e7\u00e3o","Em Andamento","Or\u00e7amento","Finalizado","Cancelado","Aguardando Pe\u00e7as","Aprovado"]"
- "control_edit_vendas" com valor "1"
- "email_automatico" com valor "1"
- "control_2vias" com valor "0"

Foi assim que resolvi esse mesmo problema ontem!
