### ISSUE TITLE
Adicionar campo no Menu.

### ISSUE THREAD

**Issue by alexhith** [RamonSilva20/mapos#2288]
Saudações a todos.

Eu gostaria de saber como eu poderia adicionar mais um campo ao menu principal que seria para Ordem de Compra.

Poderia ser exatamente como o campo de OS, mas que gerasse informações diferentes no banco de dados. 
Eu tentei duplicar a tabela mas eu não consigo valida-la.

Outra coisa que eu gostaria de saber como colocar, isso tanto na OS quando na OC, seria mais um campo de técnico/responsável, pra ter um controle de quem solicitou a ordem e pra quem vai executar o trabalho.

Novamente, eu até consegui adicionar esse campo, mas quando eu adiciono uma OS e salvo, o campo passa a ficar vazio e não gera nenhuma informação.

Eu adianto, que gosto muito do sistema e o pouco que já consegui fazer foi fuçando mesmo. Mas qualquer ajuda eu já ficaria muito grato.

**Comment by alexhith** [comment]
Só pra facilitar a compreensão, eu preciso que o campo "Setor Destino" tenha a mesma funcionalidade do campo "Solicitante", de buscar os usuários cadastrados mas que gere informações diferentes, ou seja, que cada um consiga selecionar um usuário diferente.

![Screenshot_3](https://github.com/RamonSilva20/mapos/assets/77502774/c32e5e94-e2a2-4f44-afa4-9c67f03d832b)

Mas do jeito que está, está puxando a mesma informação nos dois na parte de Visualizar Os, e na parte de Adicionar/Editar OS fica em branco.

**Comment by Fesantt** [comment]
Não seria mais facil criar a "Ordem de compra" do zero?

**Comment by alexhith** [comment]
Na verdade, nos campos da OS eu consegui resolver. Ao invés de usar um campo com autocomplete para os usuários, eu simplesmente criei um campo de seleção igual ao do status, mas com os setores pra onde essa OS poderia ir.

Quanto a Ordem de Compra eu ainda não consegui ajustar totalmente. E pra não ter que criar tudo de novo, eu gostaria de saber se eu poderia fazer isso usando a opção de Termo de Garantia, que no meu caso não tem utilidade aqui.

A propósito, eu não consegui encontrar nos arquivos como eu mudo os nomes no menu lateral do dashboard.

![image](https://github.com/RamonSilva20/mapos/assets/77502774/9d5d6b22-bd34-419f-bdcc-04d7de92bd4c)

Sabe me dizer em qual arquivo está essa opção? Achei que estaria em application/views/mapos/painel mas não está.

**Comment by barretowiisk** [comment]
Olá @alexhith 
Faz sentido você criar uma nova função no sistema e tabela no banco de dados para atender a sua demanda que é muito especifica, ainda sim, sobre ordem de compra que é um antecessor da venda (na minha opinião) poderia simplesmente criar alguns processos dentro da função Vendas que poderia te atender, sendo assim recomendo entrar em contato com um programador para desenvolver conforme as suas necessidades, tendo em vista que essa não atende as necessidades do objetivo do projeto.

Se desejar, podemos ajudar com o isso, ver uma forma legal de desenvolver o seu projeto. Cadastre-se e abra um chamado detalhando como podemos te ajudar.

https://sysgo.com.br/saobarreto

Caso ainda necessite de suporte, adquira uma instância MAP-OS com a parceria oficial do Projeto [SysGO Soluções](https://sysgo.com.br/mapos-github) e tenha suporte exclusivo ao sistema.
