### ISSUE TITLE
Retirar obrigatoriedade de alguns campos do Emitente

### ISSUE THREAD

**Issue by KioGyn** [RamonSilva20/mapos#2290]
Olá a todos, deixe me primeiramente agradecer a todos os envolvidos nesse projeto maravilhoso que é o MAPOS. O descobri a 3 dias e não tenho palavras para dizer como me alegra ver pessoas se empenhando em para manter um projeto que beneficia a toda comunidade. Espero entender ele completamente para futuramente poder somar.

Estou tentando retirar a obrigatoriedade do campo IE (Inscrição Estadual) porem sem sucesso.

Já tentei:

1º No arquivo "C:\xampp\htdocs\mapos\application\views\mapos\emitente.php" 

Comentar as 3 primeiras linhas referentes a validação das mascaras:
![image](https://github.com/RamonSilva20/mapos/assets/74689907/55cc91d6-5812-4efc-b505-adb0ccd5a6f0)

Comentar todas as linhas do codigo PHP onde o IE apareça: 92 a 97, 222 a 227
![image](https://github.com/RamonSilva20/mapos/assets/74689907/abe2e090-b0fd-46e8-8722-58101a3da083)

Comentar todas as linhas 350 a 352, 385 a 387, 435 a 437, 470 a 472
![image](https://github.com/RamonSilva20/mapos/assets/74689907/10e7ea27-7a1d-403a-aee2-518c86d06778)

Mesmo assim quando tento Atualizar os dados do emitente recebo o erro:
![image](https://github.com/RamonSilva20/mapos/assets/74689907/548b8176-9f3b-4c31-bd75-edab8ddf23a3)

Poderiam me ajudar por favor?

**Comment by KioGyn** [comment]
Obs.: Apesar de ter comentado mais linhas conforme descrevi, mandei o print apenas das primeiras linhas citadas para que possam ver como comentei os códigos em cada caso.

**Comment by Pr3d4dor** [comment]
@KioGyn precisa mexer nesse arquivo também: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php

**Comment by KioGyn** [comment]
@Pr3d4dor Obrigado pela orientação. Estive olhando o arquivo que vc indicou, mas não consegui encontrar nada referente ao campo IE (inscrição estadual)

**Comment by barretowiisk** [comment]
@KioGyn 
Na ultima PR que fiz ocultei o campo CNPJ quando o emitente possui 00.000.000/0000-00 como valor para o CNPJ e o campo IE não tem nenhuma utilidade em outras abas do sistema, então pode simplesmente colocar N/A e pronto.

Os outros dados são o mínimo para qualquer sistema negócio, então é de se entender a obrigatoriedade.

Caso ainda necessite de suporte, adquira uma instância MAP-OS com a parceria oficial do Projeto [SysGO Soluções](https://sysgo.com.br/mapos-github) e tenha suporte exclusivo ao sistema.

**Comment by wesley020291** [comment]
quero retirar na parte de cadastro do cliente a obrigatoriedade de CNPJ e por o cpf. ja mudei varias partes mas não consegui tirar.

**Comment by wesley020291** [comment]
> @KioGyn Na ultima PR que fiz ocultei o campo CNPJ quando o emitente possui 00.000.000/0000-00 como valor para o CNPJ e o campo IE não tem nenhuma utilidade em outras abas do sistema, então pode simplesmente colocar N/A e pronto.
> 
> Os outros dados são o mínimo para qualquer sistema negócio, então é de se entender a obrigatoriedade.
> 
> Caso ainda necessite de suporte, adquira uma instância MAP-OS com a parceria oficial do Projeto [SysGO Soluções](https://sysgo.com.br/mapos-github) e tenha suporte exclusivo ao sistema.

teria foto?

**Comment by wesley020291** [comment]
> @KioGyn precisa mexer nesse arquivo também: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php

consegue me ajudar a retirar a obrigatoriedade do cnpj no campo de cadastro? para cliente por cpf no lugar?
![obrigatorio cpf](https://github.com/RamonSilva20/mapos/assets/56301435/e796d731-895a-4a0b-81aa-adc3d89f2b88)

**Comment by barretowiisk** [comment]
@wesley020291 
No campo o cliente pode inserir CPF ou RG tranquilamente, não existe problema na inserção do CPF/CNPJ.
![image](https://github.com/RamonSilva20/mapos/assets/45976190/f4c3beea-e969-4394-ae81-fa2e9edecc65)
![image](https://github.com/RamonSilva20/mapos/assets/45976190/5907ef97-e12e-49f1-b914-312162ff6c81)
![image](https://github.com/RamonSilva20/mapos/assets/45976190/16b2dca0-0d03-4ecd-9f33-290983ef7868)


Caso queira verificar um orçamento para desenvolvimento, acesse o parceiro https://sysgo.com.br/ ou entre em contato comigo no wa.me/+5581989505723

**Comment by wesley020291** [comment]
> @wesley020291 No campo o cliente pode inserir CPF ou RG tranquilamente, não existe problema na inserção do CPF/CNPJ. ![image](https://private-user-images.githubusercontent.com/45976190/296630145-f4c3beea-e969-4394-ae81-fa2e9edecc65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTQxMTUsIm5iZiI6MTcwNTQ5MzgxNSwicGF0aCI6Ii80NTk3NjE5MC8yOTY2MzAxNDUtZjRjM2JlZWEtZTk2OS00Mzk0LWFlODEtZmEyZTllZGVjYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NWIzYWY1ZjJkMTE0YTA5YTA0ZGJkZmQ2MzVkOGRjYWM2NTRiMmVlMzkzYzIyNjIyZTdlYTg4ODAyNDE2ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yosx73VWSTXgPm2EfKOXpcvsvChVjFYgcaUJHrg_Lys) ![image](https://private-user-images.githubusercontent.com/45976190/296630158-5907ef97-e12e-49f1-b914-312162ff6c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTQxMTUsIm5iZiI6MTcwNTQ5MzgxNSwicGF0aCI6Ii80NTk3NjE5MC8yOTY2MzAxNTgtNTkwN2VmOTctZTEyZS00OWYxLWI5MTQtMzEyMTYyZmY2YzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzhiYmZjNThlMDgxMjk5NTMzYTc5NjYzZTI1M2U4ZjUzZmJkNGEzMzY2Yzg1NDgzM2NmYmU1OTI1YTdlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-RdjxV2wr1XCrTjO1n3EZhOD6Yut18sepKXlYBembc) ![image](https://private-user-images.githubusercontent.com/45976190/296630209-16b2dca0-0d03-4ecd-9f33-290983ef7868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTQxMTUsIm5iZiI6MTcwNTQ5MzgxNSwicGF0aCI6Ii80NTk3NjE5MC8yOTY2MzAyMDktMTZiMmRjYTAtMGQwMy00ZWNkLTlmMzMtMjkwOTgzZWY3ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhODJhODI0Yzk0ODNlNTY1NDg5YTNmYzNkYWVjOGJhYmE1MDJjOTZlMDQ3OTgxYzFjZGEzOGI0NDYxYmY0YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n6Z0QMNnlLZdT3okh3j6HL0q-rld6WbqbNX2xTjfNV8)
> 
> Caso queira verificar um orçamento para desenvolvimento, acesse o parceiro https://sysgo.com.br/ ou entre em contato comigo no wa.me/+5581989505723

qual a versão esta usando?

**Comment by wesley020291** [comment]
quando cliente vai cadastrar pelo portal dele da esse erro. mesmo com todos os dados preenchidos.

![ee9da1c5-4bf2-4df5-9df4-beb4bc8c35fc](https://github.com/RamonSilva20/mapos/assets/56301435/e71ae12a-ac5b-497e-ba64-8ac8b76d8db7)

**Comment by barretowiisk** [comment]
@wesley020291 
Então, o problema é que você está digitando o CPF e clicando na busca (LUPA), essa API funciona para retornar dados de um CNPJ não funciona para CPF (são dados não públicos), oriente seu cliente a preencher com um CPF válido e não clicar em buscar, finalizando de preencher os dados no final do formulário tem a opção cadastrar.
