### ISSUE TITLE
mysqli_sql_exception (1054) Unknown column 'tipo_desconto' in 'field list'

### ISSUE THREAD

**Issue by willybrandtleao** [RamonSilva20/mapos#2293]
Ao tentar logar no sistema, me foi reportado esse erro. Não atualizei sistema, nem nada. Alguem poderia me dar um help.
![Captura de tela de 2023-12-06 09-47-01](https://github.com/RamonSilva20/mapos/assets/46223150/11b865d3-4d45-4b77-99ba-81cffb4cc346)
![Captura de tela de 2023-12-06 09-48-30](https://github.com/RamonSilva20/mapos/assets/46223150/1389cce1-9c6d-4574-90cb-e459c2c31407)
![Captura de tela de 2023-12-06 09-48-37](https://github.com/RamonSilva20/mapos/assets/46223150/de7c751d-7724-465b-a3c0-4975e093580a)

**Comment by barretowiisk** [comment]
Boa noite @willybrandtleao 
Acredito que para entender melhor seu problema, precisaria de mais informações, mas acredito que o comando abaixo pode ajudar na resolução.

Selecione o seu banco de dados e execute o comando abaixo no SQL:

```
CREATE TABLE IF NOT EXISTS `os` (
  `idOs` int NOT NULL AUTO_INCREMENT,
  `dataInicial` date DEFAULT NULL,
  `dataFinal` date DEFAULT NULL,
  `garantia` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `descricaoProduto` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `defeito` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `status` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `prioridade` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
  `observacoes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `laudoTecnico` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `valorTotal` decimal(10,2) DEFAULT '0.00',
  `desconto` decimal(10,2) DEFAULT '0.00',
  `valor_desconto` decimal(10,2) DEFAULT '0.00',
  `tipo_desconto` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clientes_id` int NOT NULL,
  `usuarios_id` int NOT NULL,
  `lancamento` int DEFAULT NULL,
  `faturado` tinyint(1) NOT NULL,
  `garantias_id` int DEFAULT NULL,
  PRIMARY KEY (`idOs`),
  KEY `fk_os_clientes1` (`clientes_id`),
  KEY `fk_os_usuarios1` (`usuarios_id`),
  KEY `fk_os_lancamentos1` (`lancamento`),
  KEY `fk_os_garantias1` (`garantias_id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

Caso ainda necessite de suporte, adquira uma instância MAP-OS com a parceria oficial do Projeto [SysGO Soluções](https://sysgo.com.br/mapos-github) e tenha suporte exclusivo ao sistema.

**Comment by willybrandtleao** [comment]
@barretowiisk , não rolou

**Comment by barretowiisk** [comment]
Chama ai e me envia seu banco
https://wa.me/+5581989505723
