### ISSUE TITLE
Erro ao editar as permissões

### ISSUE THREAD

**Issue by juniorjmenezes** [RamonSilva20/mapos#23]
Quando tento editar uma permissão, nunca consigo sucesso, sempre tenho como retorno a seguinte mensagem: `Item não pode ser encontrado, parâmetro não foi passado corretamente. `

**Comment by RamonSilva20** [comment]
Fiz diversos testes, está funcionando normalmente, talvez esteja com uma versão anterior que ainda estava com este problema. Atualize os arquivos que deve funcionar corretamente. Grato.

**Comment by juniorjmenezes** [comment]
Boa Noite Ramon,

Baixei a nova versão e os problemas de permissão não se repetiram, mas
agora não consigo adicionar produtos às Ordens de Serviço.

Jr

Em 14 de abril de 2017 00:54, Ramon Silva <notifications@github.com>
escreveu:

**Comment by RamonSilva20** [comment]
Alguma mensagem de erro ou algo que possa sugerir o problema?

**Comment by juniorjmenezes** [comment]
Já consegui resolver o problema! Mas estou necessitando de uma pequena
ajuda sua se for possível! Como utilizamos o MAPOS em um ambiente público,
não fazemos uso das funções de preços e somatórios de preços, nesse caso
gostaria de nas OS e nas "Vendas" que aqui utilizamos como "Saídas de
Produtos", fosse mostrada a quantidade de produtos que foram retirados e
não o valor total.

Segue em anexo, uma imagem explicativa. Já tentei alterar as variáveis pra
realizar essa operação, mas estou tendo certa dificuldade. Se puder ajudar,
ficaremos gratos.

Atenciosamente,

Júnior Menezes
NTI - Prefeitura de Cruz/CE

2017-04-20 23:53 GMT-03:00 Ramon Silva <notifications@github.com>:

**Comment by RamonSilva20** [comment]
Bom dia. Consegui entender, é uma alteração bem simples de se fazer. Me envie um e-mail (silva018-mg@yahoo.com.br) que lhe respondo com um arquivo exemplo.
