### ISSUE TITLE
MAPOS com SSL.

### ISSUE THREAD

**Issue by ClaudioRSB13** [RamonSilva20/mapos#2300]
Olá pessoal, uso o mapos já faz uns 3 anos, usava ele só local mas no ano passado coloquei na minha revenda da kinghost e estava funcionando tudo corretamente.
Mas no mês de novembro de 2023 resolvi atualizar para aversão atual e tudo ok porém apareceu alguns erros que não consegui resolver *Solução era atualizar o banco de dados* mas até descobrir causei outros problemas.
Então resolvi instalar localmente e descobrir e corrigir os erros.
Depois de tudo pronto em Localhost resolvi subir novamente  então aproveitei para ativar o ssl no meu domínio então tudo pronto mas agora não funciona não abre nem a tela de login kkk estou perdido pois não estou encontrando nada que fale como resolver e por onde começar.
Alguém teria alguma dica?

**Comment by cabralwms** [comment]
Você ativou o SSL com o sistema já instalado? quando mudou colocou no arquivos application/config/config.php no local base_url o endereço com SSL? https://www.siteemuso.com.br/mapos/ assim irá funcionar.

**Comment by ClaudioRSB13** [comment]
Não, ativei antes.
Agora colocando ou não na base_url  o https  não funciona

**Comment by ClaudioRSB13** [comment]
Obrigado Pessoal,
Refiz a instalação no servidor e deu tudo certo.
