### ISSUE TITLE
cadastrar emitente

### ISSUE THREAD

**Issue by leosantos1371** [RamonSilva20/mapos#2307]
estou tentando cadastar o emitente e aparece seguinte mensagem "A pasta temporária está faltando." como posso resolver? obrigado

**Comment by cabralwms** [comment]
Boa Noite LeoSantos1371, você está com mapos instalado localmente ou hospedagem? qual versão está usando? Consegue cadastrar cliente , produtos ou serviços?

**Comment by leosantos1371** [comment]
boa noite, está instalado na 000wehost, consigo cadastrar clientes, produtos e serviços, estou usando a versão 4.42, além com problema no cadastro emitente, tambem estou tendo problema na emissão dos relatórios receita bruta-MEI, quando tento emitir esse relatório da erro no banco na linha 106 do TemplateProcessor.php. agradeço desde já

**Comment by cabralwms** [comment]
Confere a versão do PHP na sua hospedagem, precisa ser 8.0 ou superior. Se quiser chama no WhatsApp e tento ajudar 011 99369-8430

**Comment by leosantos1371** [comment]
versão 8.2

**Comment by leosantos1371** [comment]
se puder mande por aqui mesmo, por que caso outra pessoa tenha o mesmo problema ja vai ajudar tambem
obrigado

**Comment by cabralwms** [comment]
Você precisa cadastrar o Emitente para testar sobre os relatórios, testei na versão 4.42.0 que é a mais atual e está tudo funcionando perfeitamente, o cadastro do emitente, os relatórios e tambem Receita bruta para MEI.

**Comment by leosantos1371** [comment]
que estranho, e é essa versão que estou usando, mas obrigado

**Comment by cabralwms** [comment]
faz um teste local em sua maquina, instala e testa, vera que funciona normal, sem saber o erro exato fica dificil ajudar.

**Comment by leosantos1371** [comment]
já entendi a situação aqui, estou usando 000webost para teste, mas não tenho a conta premiu, e acho q isso esta bloqueando. mensagem do segundo erro tempnam(): open_basedir restriction in effect. File(/storage/ssd1/300/21672300/tmp) is not within the allowed path(s): (/opt/awex-pages:/storage/ssd5/566/20336566)

**Comment by wesley020291** [comment]
000webost da inumeros problemas, sai de la por isso

**Comment by barretowiisk** [comment]
@leosantos1371 
Reavaliando seu caso, faça o seguinte:
1- Verifique se o diretório \assets\uploads existe, se não, crie-a;
2- Esse erro `open_basedir` é uma restrição do servidor, me deparei com esse problema quando utilizei o aaPanel, recomendo que reveja a hospedagem que está usando, tendo em vista que a 000webost é uma hospedagem gratuita e que acumula diversos históricos de problemas de compatibilidade, indisponibilidade de perda de dados.

Recomendação:
Se deseja testar o sistema, utilize-o em uma instalação LOCALHOST, criei dois scripts de auto instalação do MAP-OS que está disponível no readme.md do projeto.

Para uma hospedagem dedicada com suporte ao Map-OS, recomendo que verifique os planos da SYSGO (https://sysgo.com.br) que é a parceira Oficial do Projeto MAP-OS.
