### ISSUE TITLE
Ao mudar a data de vencimento de um Faturamento ocorre erro.

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#2308]
Bom dia, 

Ao fazer a alteração na data de vencimento de um faturamento 
esta apresentando o seguinte erro.

![2023-12-19_08h38_40](https://github.com/RamonSilva20/mapos/assets/72340074/f6a2f81a-4421-4c5f-88b3-aaea17b7fd58)

Exemplo: Cliente pediu para alterar a data de vencimento de um pagamento 
ou pagou com atraso e ao mudar a data em LANÇAMENTOS o erro ocorre
Nesse exemplo mudei a data do dia 18/12 para dia 19/12 e o erro ocorre.

![2023-12-19_09h03_52](https://github.com/RamonSilva20/mapos/assets/72340074/786051bf-0d7e-4dff-947b-ad9cedf3c907)

Obs:
Versão: 4.42.0
Testes realizados em dois equipamentos diferentes.

**Comment by lukasabino** [comment]
Bom dia! 

Se o cliente pagar com atraso a data de vencimento não pode ser alterada e a data de recebimento tem que de fato ser a data que o cliente pagou, se não você perde o histórico de que o cliente pagou em atraso e quantos dias de fato foi o atraso que ocorreu.

Fazendo o teste aqui na  minha base de teste, de fato não é permitido alteração, tanto que o calendário fica bloqueado e caso tente alterar a força, aponta o erro.

![image](https://github.com/RamonSilva20/mapos/assets/70410692/c876389f-6b57-4ad4-8ee8-6e7b9aea0309)


Irei verificar o código fonte, mas creio que de fato não possa ser alterado a data de vencimento de um faturamento.

**Comment by jsfachini** [comment]
Boa noite @lukasabino 

O problema é quando o vencimento passar o mês ex: era pra ter pago em novembro e o cliente pagou em 
dezembro, nesse caso quando você vai faturar pra data de dezembro a entrada continua em novembro

Por isso nesses casos preciso sempre alterar a data do vencimento se não a entrada não contabiliza no mês que foi pago realmente e sim no mês que foi dado a entrada de faturamento, 

Abaixo deixo um exemplo, essa entrada para pagamento era pra dia 11/12, a titulo de teste
fiz o pagamento para 01/01/2024 mas a entrada continua em dezembro
ao meu ver o sistema teria que contabilizar a data do pagamento e não a data do vencimento,
não sei como resolver essa questão sem alterar a data de vencimento.
Usava essa alternativa ate antes das ultimas versões
Não sei exatamente em que momento isso mudou 
porque não é algo que eu precise fazer direto só quando acontece de algum pagamento atrasar e justamente virar o mês.

![2023-12-25_20h53_11](https://github.com/RamonSilva20/mapos/assets/72340074/b3e0cda9-3372-42cb-81e3-ebd0c470673e)

![2023-12-25_20h53_32](https://github.com/RamonSilva20/mapos/assets/72340074/f85c4074-3a4a-4c10-949f-68935027b0d1)
