### ISSUE TITLE
Não consigo fazer login após instalação

### ISSUE THREAD

**Issue by vitoralcantara** [RamonSilva20/mapos#231]
Faço a instalação, porém na tela de login o usuário e senha não são reconhecidos.
Acessando o banco de dados, noto que não houve alteração na tabela 'usuarios.
-- PHP versão 7.2

**Comment by vitolike** [comment]
Boa tarde, qual versão do mapos ?

**Comment by vitoralcantara** [comment]
3.1.15

**Comment by vitolike** [comment]
Infelizmente essa versão 3.1.15 não é compatível com php 7.2, a próxima versão a 4 será compatível..

**Comment by vitoralcantara** [comment]
Há previsão de lançamento?

**Comment by Pr3d4dor** [comment]
@vitoralcantara você atualizou uma versão antiga para a versão 3.1.15 mantendo o mesmo banco de dados ou instalou do zero a versão 3.1.15?

**Comment by vitoralcantara** [comment]
Instalação do zero.

**Comment by Pr3d4dor** [comment]
Eu acabei de fazer uma instalação do zero aqui da versão 3.1.15 no PHP 7.2 e o mesmo funcionou perfeitamente.

**Comment by vitoralcantara** [comment]
Servidor Linux?

**Comment by Pr3d4dor** [comment]
@vitoralcantara sim no Linux Ubuntu 16.04 LTS.

**Comment by vitoralcantara** [comment]
Entendi. Vou tentar novamente e postar o resultado.

**Comment by Pr3d4dor** [comment]
@vitoralcantara talvez o problema seja no seu banco de dados, precisaria de mais detalhes e logs de debug para poder lhe ajudar.

**Comment by rafso** [comment]
eu também tive problemas com o login inicial, o arquivo banco.sql está desatualizado e não consegue inserir o usuário admin padrão, acabei de tentar fazer um pull-request mas não sei se foi.

**Comment by vitoralcantara** [comment]
Consegui com instalação manual de acordo com o arquivo de instruções.
