### ISSUE TITLE
Novos Campos - Produtos

### ISSUE THREAD

**Issue by Boveto** [RamonSilva20/mapos#2315]
Ola, 
é possível adicionar campos adicionais nas telas?

Por exemplo, na tela de produtos, é possível adicionar o campo "Tipo" e "Local", assim conseguimos diferenciar e saber onde esta cada item.

Na tela cliente, colocar o campo "Site"
Na Tela de Serviços, colocar o campo Tipo

Na tela de venda e serviço, colocar o campo comissão (onde ele fique correspondente ao financeiro tambem)

Na tela lançamento, ter a opção de colocar contas recorrentes, como aluguel, internet e etc.

Estou iniciando o uso do sistema para uma assistência especializada serviços para notebook e desktop.

**Comment by Fesantt** [comment]
É possivel sim, pode fazer qualquer alteração que desejar no codigo fonte!

**Comment by barretowiisk** [comment]
@Boveto 
O projeto é Open Source com licença MIT, você pode fazer qualquer alteração que desejar desde que mantenha os créditos do desenvolvedor do projeto.

Caso precise de um desenvolvedor, acesse a parceira oficial do projeto https://sysgo.com.br/ e solicite um orçamento.
