### ISSUE TITLE
Versão Laravel

### ISSUE THREAD

**Issue by tiagofrancafernandes** [RamonSilva20/mapos#2320]
Tenho interesse em dar evolução na versão Laravel do MapOS.

Mais alguém topa o desafio de entrar junto?

Se mais alguém me apoiar, eu pego pra evoluir. 

Sou expert em Laravel e quero ajudar a comunidade.

**Comment by barretowiisk** [comment]
@juliolobo @Fesantt 

PSC
@willph @Pr3d4dor

**Comment by willph** [comment]
> Tenho interesse em dar evolução na versão Laravel do MapOS.
> 
> Mais alguém topa o desafio de entrar junto?
> 
> Se mais alguém me apoiar, eu pego pra evoluir.
> 
> Sou expert em Laravel e quero ajudar a comunidade.

O @Pr3d4dor esta desenvolvendo, ele pode da mais informações sobre o andamento do projeto.
Obrigado pelo seu interesse em ajudar o projeto.
