### ISSUE TITLE
Novo Status EFI: identified

### ISSUE THREAD

**Issue by wgiacomelli** [RamonSilva20/mapos#2323]
Aparentemente na Integração de cobranças com o EFI está salvando em banco um status 'identified' invés de 'paid', parece ser um Status intermediário ao pagamento, porem quando ocorre trava o acesso da aba cobranças, assim sendo necessário ajustar em Banco a linha afetada, bastando trocar para PAID, se necessário me coloco a disposição para auxiliar nos testes.

Obs: Em cobranças mais antigas em que o pagamento já tem vários dias o erro não ocorre.

![image](https://github.com/RamonSilva20/mapos/assets/37094545/467b985e-1f78-405a-980b-ad8ad2d3bf5a)
![image](https://github.com/RamonSilva20/mapos/assets/37094545/e646e2c6-c24e-4178-8ef6-e50840a073da)

**Comment by cabralwms** [comment]
Criei uma atualização para resolver esse problema, caso queira fazer até ser aprovada a PR, adiciona no arquivo application/config/payment_gateways.php linha 29 adiciona uma linha nova e digita isso 'identified' => 'Pagamento confirmado',. Salve o arquivo e apartir de então não dará mais esse erro.

**Comment by wgiacomelli** [comment]
Olá, na última versão o problema persiste, parece haver um erro de digitação, o seguinte  status precisa ser criado:
'identified' => 'Pagamento confirmado',


![image](https://github.com/user-attachments/assets/b8482c3a-d912-47cf-b241-047aed4cd8ec)
