### ISSUE TITLE
ERRO NO LOGIN

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#2330]
Instalei o MAPOS conforme as instruções, porém quando fui logar com o usuario admin ao clicar em acessar nao acontece nada. Verifiquei no navegador e obtive:

XHRPOST
http://localhost/index.php/login/verificarLogin?ajax=true
[HTTP/1.1 404 Not Found 4ms]

	
POST
	http://localhost/index.php/login/verificarLogin?ajax=true
Estado
404
Not Found
VersãoHTTP/1.1
Transferido488 B (tamanho 271 B)
Política de referênciasstrict-origin-when-cross-origin
Prioridade do PedidoHighest
Resolução de DNSSistema

    	
    Connection
    	Keep-Alive
    Content-Length
    	271
    Content-Type
    	text/html; charset=iso-8859-1
    Date
    	Tue, 13 Feb 2024 00:12:05 GMT
    Keep-Alive
    	timeout=5, max=100
    Server
    	Apache/2.4.57 (Ubuntu)
    	
    Accept
    	application/json, text/javascript, */*; q=0.01
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	pt-PT,pt;q=0.8,en;q=0.5,en-US;q=0.3
    Connection
    	keep-alive
    Content-Length
    	49
    Content-Type
    	application/x-www-form-urlencoded; charset=UTF-8
    Cookie
    	MAPOS_COOKIE=3d907d316e9df70a929ce9649a8436e7; app_session=2ct4vmd4dn8qnbjoa3u6ntk0idnh6qhe
    Host
    	localhost
    Origin
    	http://localhost
    Referer
    	http://localhost/topbox/index.php/login
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
    X-Requested-With
    	

Pelo que percebi o post não ta pegando o local correto pois ele me mostra:

http://localhost/index.php/login/verificarLogin?ajax=true

e deveria ser:

http://localhost/topbox/index.php/login/verificarLogin?ajax=true

Alguma ideia de como corrigir?

**Comment by willph** [comment]
Ola, tudo bom?

Sua instalação é local ou numa hospedagem?

Qual versão está usando?

**Comment by crimat06** [comment]
É local, versão 4.43.0

**Comment by willph** [comment]
> 187.7.134.117/topbox/

teve umas correções recente.

**Comment by crimat06** [comment]
nao era esse mas ja vou rodar com esse e ja faço uma devolutiva aqui... ooobrigado por enquanto.

**Comment by crimat06** [comment]
funcionou amigo! obrigado, o link que eu havia pego era o que estava como mais recente na pagina do projeto...

**Comment by willph** [comment]
De nada!
