### ISSUE TITLE
Bug no auto cadastro do cliente 

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#2331]
Ao acessar o auto cadastro do cliente está dando um erro. Peço a gentileza de acessar e me ajudar a diagnosticar o erro:

http://187.7.134.117/topbox/index.php/mine <== aqui abre normalmente

http://187.7.134.117/topbox/index.php/mine/cadastrar <== esse é depois que clico em cadastrar

Obrigado!

**Comment by crimat06** [comment]
Estava dando uma fuçada e parece ser algo no mine.php mas nao tenho certeza

**Comment by crimat06** [comment]
pera... o noob aqui nao entendeu hahaha

**Comment by willph** [comment]
https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip

precisa atualizar o codigo fonte do projeto, reinserindo os mesmo dados da primeira instalação.

**Comment by juliolobo** [comment]
Boa tarde. Veja se vc está com as pastas "captcha-images" e "font" dentro de "assets", e se dentro da pasta "font" tem as 4 fontes

**Comment by crimat06** [comment]
sim está tudo conforme vc descreveu...

**Comment by juliolobo** [comment]
Pelo erro parece que o script não está conseguindo criar a imagem do Captcha, veja se a pasta captcha-images está com a permissão 0755 (755)

**Comment by crimat06** [comment]
deu boa mas com permissão 777 somente, com 755 continuou com o mesmo erro. Obrigado!

Agora resta somente o erro do cadastro que vai para a pagina em branco...

**Comment by juliolobo** [comment]
Esse erro é relacionado ao CSRF, @Fesantt dá um pulinho aqui.

**Comment by crimat06** [comment]
pois é... mas essa que eu tô rodando já essa nova...

**Comment by crimat06** [comment]
Cadastro abre agora porém ainda tem o problema de ir para uma página de erro após o preenchimento do formulário mas grava normalmente no banco de dados.

**Comment by juliolobo** [comment]
Pelo print que postou, tem algo errado no seu código.
Tentamos replicar seu erro e não foi possível.
Verifique algo que você tenha alterado.
![image](https://github.com/RamonSilva20/mapos/assets/13459803/6b079066-a5db-4bde-b28e-78772581e6b9)

Baixe somente o arquivo [aplication/controllers/Clientes.php](https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Clientes.php) do repositório e substitua o do seu projeto.

**Comment by crimat06** [comment]
sim peguei a versão 4.44 segui os procedimentos de instalação do site e nao fiz qualquer alteração nos codigos... mas o erro persiste:

http://187.7.134.117/topbox/index.php/topbox/index.php/produtos/adicionar/


Então me ocorreu... na parte da instalação que pede URL eu cooloquei somente /topbox, não seria ali o problema?

**Comment by crimat06** [comment]
era isso.. quando coloquei o endereço completo do sistema ele funcionou... Obrigado!

**Comment by crimat06** [comment]
daria pra colocar a dica na pagina de instalação (Sugestão)

**Comment by crimat06** [comment]
era isso.. quando coloquei o endereço completo do sistema ele funcionou... Obrigado!

**Comment by crimat06** [comment]
daria pra colocar a dica na pagina de instalação (Sugestão)

**Comment by juliolobo** [comment]
Que bom que resolveu.
Um abraço.
Analisaremos a sugestão.
