### ISSUE TITLE
Bug em todos os formulários 

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#2335]
Mesmo usando a versão lançada ontem os formulários continuam indo para uma página de erro depois de gravar. Os dados ficam salvos corretamente e é necessário clicar em voltar no navegador pra receber a mensagem de que foi salvo com sucesso.

**Comment by Fesantt** [comment]
saiu a release 4.44, caso só faça a atualização pelo sistema lembrese de fazer as alterações no arquivo config.php Application/config/config.php

**Comment by crimat06** [comment]
sim peguei a versão 4.44 segui os procedimentos de instalação do site e nao fiz qualquer alteração nos codigos... mas o erro persiste:

http://187.7.134.117/topbox/index.php/topbox/index.php/produtos/adicionar/


Então me ocorreu... na parte da instalação que pede URL eu cooloquei somente /topbox, não seria ali o problema?

**Comment by willph** [comment]
> ![Screenshot_2024-02-14_16-09-14](https://private-user-images.githubusercontent.com/52707975/304799891-9999bf57-9ad0-400a-9271-a99bc07f114e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Mjc4NjgsIm5iZiI6MTcwNzkyNzU2OCwicGF0aCI6Ii81MjcwNzk3NS8zMDQ3OTk4OTEtOTk5OWJmNTctOWFkMC00MDBhLTkyNzEtYTk5YmMwN2YxMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE2MTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTU1OWIxOWQ3ZGYxZTBlYzgxNjE4YjM1ZDhiNWIwZGQ4YjMzZDc2Y2YyNjAyNjIyYTg2YzEyNjNjZTY5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UVdQw-uqM1tn5gRkrkSBM8si8kyDW-ZcYK5wYxSFCHU) sim peguei a versão 4.44 segui os procedimentos de instalação do site e nao fiz qualquer alteração nos codigos... mas o erro persiste:
> 
> http://187.7.134.117/topbox/index.php/topbox/index.php/produtos/adicionar/
> 
> Então me ocorreu... na parte da instalação que pede URL eu cooloquei somente /topbox, não seria ali o problema?

A url tem que ser a mesma que esta na bara de endereço, na hora da instalação.

No seu caso parece ser http://187.7.134.117/topbox onde a pasta topbox é o raiz do seu mapos.
