### ISSUE TITLE
Erro ao tentar instalar atualização 

### ISSUE THREAD

**Issue by Iron2025** [RamonSilva20/mapos#2336]
Erro ao tentar instalar a atualização, não muda a versão do sistema e o erro ao cadastrar cliente permanece , apenas na área do cliente ao tentar cadastrar

**Comment by Fesantt** [comment]
sempre que  mandar print de um erro envie o print completo

**Comment by juliolobo** [comment]
O print como está não dá pra identificar o erro.
Favor mandar o print completo

**Comment by Iron2025** [comment]
![Screenshot_20240215-214430](https://github.com/RamonSilva20/mapos/assets/160193672/1c99efa1-5ab9-4a0d-b89f-295b256ed107)

**Comment by Fesantt** [comment]
pra facilitar, no celular a visualização é limitada, coloque o navegador em modo Descktop

**Comment by Iron2025** [comment]
![Screenshot_20240215-230643](https://github.com/RamonSilva20/mapos/assets/160193672/48d9a3d3-6f56-4ce5-9186-6d1a012ede21)

**Comment by Iron2025** [comment]
![Screenshot_20240215-230920](https://github.com/RamonSilva20/mapos/assets/160193672/43337cfd-00bb-42ce-8f8c-353d4a6c8f95)

**Comment by juliolobo** [comment]
Em /assets/ crie as pasta "captcha-images" e "font" e tente novamente.

**Comment by Iron2025** [comment]
Onde encontro essa linha?

Em qui., 15 de fev. de 2024 23:15, Julio Lobo ***@***.***>
escreveu:

**Comment by juliolobo** [comment]
Que linha?
Entre na pasta "assets" crie as pasta "captcha-images" e "font" e tente novamente.

**Comment by Iron2025** [comment]
Cris as pastas no local indicado porém tentei atualizar e da o mesmo erro,
segue anexo do erro

Em qui., 15 de fev. de 2024 23:23, Julio Lobo ***@***.***>
escreveu:

**Comment by Iron2025** [comment]
E aí tentar cadastrar o cliente da esse erro que segue no print

Em qui., 15 de fev. de 2024 23:31, Ironaldo Silva <
***@***.***> escreveu:

**Comment by juliolobo** [comment]
Os prints não carregaram

**Comment by juliolobo** [comment]
Manda print da sua pasta assets

**Comment by Iron2025** [comment]
Em qui., 15 de fev. de 2024 23:34, Julio Lobo ***@***.***>
escreveu:

**Comment by juliolobo** [comment]
Quando for mandar print, espera o mesmo terminar o upload, vc não está enviando os prints, olhe suas mensagens anteriores

**Comment by juliolobo** [comment]
Se tá respondendo pelo email, utilize o github

**Comment by Iron2025** [comment]
Estou enviando, para mim aqui abre normalmente, mas vou tentar enviar agora
mais uma vez, segue os anexos, veja se consegue agora visualizar

Em qui., 15 de fev. de 2024 23:39, Julio Lobo ***@***.***>
escreveu:

**Comment by Iron2025** [comment]
![Screenshot_20240215-233208](https://github.com/RamonSilva20/mapos/assets/160193672/dd50ff63-dc9b-410a-a760-b5873d20a02b)
![Screenshot_20240215-233052](https://github.com/RamonSilva20/mapos/assets/160193672/8963f810-43b2-4477-bba7-d00d23d611ad)
![Screenshot_20240215-232948](https://github.com/RamonSilva20/mapos/assets/160193672/215852c5-58a1-44bf-a290-e8ba0bbf00eb)

**Comment by Fesantt** [comment]
na sua pasta Application/config substitua o arquivo Autoload.php

por esse.
https://github.com/RamonSilva20/mapos/blob/master/application/config/autoload.php

**Comment by Fesantt** [comment]
@Iron2025 encerrar a inssue caso tenha resolvido o problema :)

**Comment by Iron2025** [comment]
A parte de cadastro do cliente já resolveu, do falta resolver a questão de atualizar o app, que sempre dá erro e não muda a versão da atualização
![Screenshot_20240216-001409](https://github.com/RamonSilva20/mapos/assets/160193672/ac6e5320-7d1f-41bd-a586-619c794bcccc)
![Screenshot_20240216-001620](https://github.com/RamonSilva20/mapos/assets/160193672/019d1024-e0e7-443a-9712-166dbb845a66)

**Comment by Fesantt** [comment]
vai em Application/libraries/github_updater.php
linha 97 susbstitui  $diretorio = '';
por  $diretorio = '/assets/';
testei aqui e funcionou assim.

**Comment by Iron2025** [comment]
Fiz o procedimento porém ainda continua com erro para atualizar 
![Screenshot_20240216-004154](https://github.com/RamonSilva20/mapos/assets/160193672/9fde80ce-1601-4513-b266-efdf72a54a43)

**Comment by Fesantt** [comment]
deu permissão 0755 no diretorio assets?
esse erro é referente a permissões

**Comment by Iron2025** [comment]
Sim está com a permissão 
![Screenshot_20240216-004911](https://github.com/RamonSilva20/mapos/assets/160193672/158218c2-9053-4d8c-9dab-d7d325b14d3a)

**Comment by Iron2025** [comment]
Boa tarde, alguém conseguiria me ajudar a resolver a questão de não conseguir atualizar o sistema automaticamente?
