### ISSUE TITLE
Não consigo instalar com administrador

### ISSUE THREAD

**Issue by morrice22** [RamonSilva20/mapos#234]
eu faço todo procedimento correto, entretanto ele não cria um administrador e não consigo logar. estou usando o xampp

**Comment by willph** [comment]
Como VitoLike disse, qual versão?

Porque eu uso a que tem "PHP Version 7.2.12", Apache/2.4.37, DB 10.1.37-MariaDB.
O sistema tem alguns bugs, mas na parte da instalação, tanto a forma automática e a manual funciona tranquilamente. 
Agora no Ubuntu 18.04 sem o Xampp eu testei e só conseguir instalar de forma manual.
