### ISSUE TITLE
Lançamento

### ISSUE THREAD

**Issue by Marcus-313** [RamonSilva20/mapos#2342]
Ao acessar página de lançamento apresenta um erro, isso vou depois que atualizei a versão.

 Versão: 4.44.0 Atual

 Versão: 4.42.0 Anterior ( Não tinha esse Bug)

![Capturar](https://github.com/RamonSilva20/mapos/assets/45233786/2452cf17-6fd4-40ae-89a5-9339702e9629)

**Comment by juliolobo** [comment]
Foi feito merge de um PR que realmente estava com erro. Irei corrigir

**Comment by juliolobo** [comment]
A PR https://github.com/RamonSilva20/mapos/pull/2343 Corrige o problema

**Comment by CarlosCavalcante87** [comment]
Depois que eu atualizei não consigo editar os "lançamentos"

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by juliolobo** [comment]
A PR com a correção já foi mergeada.
Atualizem o Mapos de vcs

**Comment by barretowiisk** [comment]
Boa noite @CarlosCavalcante87 
Considerando que seja o Administrador do sistema, a depender de quando você realizou a atualização/instalação da v4.44.0 será necessário alguns ajustes manuais conforme informado pelo @juliolobo, pois mesmo atualizando via sistema não serão adicionadas. Caso tenha conhecimento, recomendo que verifique a PR informada ou que realize a instalação (em UAT inicialmente) da MASTER do projeto para verificar se o caso ainda persiste.

Caso tenha sido resolvido, não esqueça de nós dar um feedback e encerrar a ISSUE.

#Publicidade
Para suporte especializado no MAP-OS, conte com a SYSGO, que é a Parceira Oficial do Projeto, temos a solução conforme a sua necessidade sem dores de cabeça.
https://sysgo.com.br/

**Comment by CarlosCavalcante87** [comment]
Eu não corrigi! Eu resolvi retorna a versão 4.42 onde já roda tranquilo. Estou aguardando novas atualização para novamente tentar atualizar!
Obrigado pela atenção!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by juliolobo** [comment]
@CarlosCavalcante87 O bug foi resolvido, não precisa aguardar.

**Comment by CarlosCavalcante87** [comment]
Show meu amigo!!!!! 🚀


Pois muito obrigado pela informação e atenção 🤜🤛

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by willph** [comment]
Precisa baixa o código master
Ainda não foi criada uma nova Release.

Em dom., 17 de mar. de 2024 19:21, CarlosCavalcante87 <
***@***.***> escreveu:

**Comment by fapernas** [comment]
Obrigado @juliolobo. Estava com esse mesmo problema e agora deu certo.
