### ISSUE TITLE
Erro ao adicinar permissões

### ISSUE THREAD

**Issue by everaldovds** [RamonSilva20/mapos#2345]
Ao tentar adicinar uma permissão ele apresenta o erro (An Error Was Encountered - The action you have requested is not allowed)

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Configurações/Permissões
2. Adicionar
3. Nome da permissão (Funcionário)
4. Marcando todas as opçoes ou selecionado algumas dá o mesmo erro.
5. Confirmar

**Comportamento esperado**
Permissão criada com sucesso.

** Capturas de tela **
![Screenshot 2024-02-23 201405](https://github.com/RamonSilva20/mapos/assets/56073947/5d205145-725a-4881-9459-d032cff40958)
![Screenshot 2024-02-23 201445](https://github.com/RamonSilva20/mapos/assets/56073947/c15f73b8-db8a-4c5d-b1ad-9b0a90208e9f)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 11
 - Navegador Microsoft Edge 
 - Versão 121.0.2277.128 (Compilação oficial) (64 bits)

**Comment by Fesantt** [comment]
Amanha ja subo a correção :)

**Comment by juliolobo** [comment]
@Fesantt Eu subi a correção mais cedo, só esperando ser aprovada!

**Comment by willph** [comment]
Correção aprovada.

Atualizar o código e testar novamente,  caso não tenha resolvido, só abrir uma nova PR.

PR merged  #2346


Atenciosamente, Equipe MapOs.
