### ISSUE TITLE
instalação infinita

### ISSUE THREAD

**Issue by srmiduby** [RamonSilva20/mapos#2349]
Quando entra na tela pra colocar os dados para instalar, fica preso nela pedindo para esperar

** Desktop (preencha as seguintes informações): **
 - SO: WINDOWS 10
 - Navegador GOOGLE E OPERA 
![Screenshot_3](https://github.com/RamonSilva20/mapos/assets/118935047/3a6d53b9-01e4-48dc-9d72-111f4a28ccb0)
GX

**Comment by Fesantt** [comment]
isso acontece quando os dados de conexão com o banco estão incorretos, abra o Inspecionar elemento do navegador e observe as requisições que estão sendo feitas. Talvez isso ajude!

**Comment by barretowiisk** [comment]
Olá @srmiduby 
Geralmente esse erro ocorre quando o banco de dados apontado (no seu caso ``mapos``) já está populado ou dados de conexão incorretos, recomendo que acesse o phpMyAdmin e verifique se o mesmo possui tabelas já inseridas ou se os dados de conexão com o bando de dados estão corretos.

Caso tenha usado o script de auto instalação disponível no README.md, sou o desenvolvedor do script, pode entrar em contato comigo pelo WhatsApp e será um prazer ajudar.

https://wa.me/5581989505723

Caso já tenha resolvido, não esqueça de retornar aqui seu feedback e encerrar a ISSUE.

#Publicidade
Para suporte especializado no MAP-OS, conte com a SYSGO, que é a Parceira Oficial do Projeto, temos a solução conforme a sua necessidade sem dores de cabeça.
https://sysgo.com.br/

**Comment by k4k4rot0** [comment]
@srmiduby , boa tarde! apague o Banco de Dados existente e crie um novo. Isso vai resolver o seu problema.

Listar usuários MySQL
SELECT user FROM mysql.user;

Deletar Usuário MySQL
DROP USER 'nome_do_usuário'@'localhost';

Deletar DB
SHOW DATABASES;
DROP DATABASE nome_do_banco;

**Comment by srmiduby** [comment]
A atualização do Windows 10 de alguma forma estava impedindo de continuar a instalação, após eu formatar novamente o pc e impedir as atualizações deu certo
