### ISSUE TITLE
Erro ao adicionar novo usuario ou grupo de permissóes no sistema

### ISSUE THREAD

**Issue by maxdantas** [RamonSilva20/mapos#2350]
Ao tentar adicionar um novo usuario para o sistema da erro de permissão, tanto em localhost como hospedado!

![image](https://github.com/RamonSilva20/mapos/assets/57685339/8b0fc771-4ba4-47ce-8ea2-a62610e59f9a)

**Comment by Fesantt** [comment]
Esse problema foi resolvido na PR #2346 se possivel baixe a Master ou siga os passos descritos na PR!

**Comment by barretowiisk** [comment]
@maxdantas 
Caso tenha sido resolvido, não esqueça de nós dar um feedback e encerrar a ISSUE.

**Comment by fapernas** [comment]
@Fesantt Felipe, tudo bem?
Estou enfrentando o mesmo problema que o colega @maxdantas Maxwel.
Minha hospedagem é InfinityFree e a versão do MAPOS é 4.44
A instalação foi realizada por mim mesmo do zero.
Estou começando a utilizar o MAPOS, até agora tomei essa mesma mensagem em dois momentos: ao tentar adicionar um novo usuário e adicionar lançamento de receita manualmente na tela de lançamentos.

Conforme sua mensagem ao Maxwel existe uma correção porém estou com dificuldade em entender o que é 'PR' e como localizo a orientação para aplicar a correção em meu ambiente.

Desde já agradeço pela atenção.

Fabio Pereira
17 99704-0857

**Comment by Pr3d4dor** [comment]
@fapernas precisa configurar o arquivo .env corretamente e também precisa limpar o cache do navegador por conta do arquivo funcoesGlobal.js (ctrl + shift + r).
