### ISSUE TITLE
Responsividade - Área do Cliente

### ISSUE THREAD

**Issue by k4k4rot0** [RamonSilva20/mapos#2353]
Segue Screenshot 

![resp](https://github.com/RamonSilva20/mapos/assets/65426919/4478e791-a8b7-420d-9f30-f6635f8015d3)

**Comment by juliolobo** [comment]
Não temos previsão de fazer esse ajuste.

**Comment by k4k4rot0** [comment]
@juliolobo , boa tarde! ok, sem problemas... abraço!!
