### ISSUE TITLE
Ação não solicitada

### ISSUE THREAD

**Issue by newitersorocaba** [RamonSilva20/mapos#2355]
** Descreva o bug **
Estou tentando incluir uma despesa e mostra o erro "A ação que você solicitou não é permitida".

**Comment by Pr3d4dor** [comment]
@newitersorocaba Precisa dar permissão para o usuário que você está logado fazer essa ação.

**Comment by barretowiisk** [comment]
Boa noite @newitersorocaba,
Qual versão está usando? 

Cenário possível: Considerando que seja o Administrador do sistema, a depender de quando você realizou a atualização/instalação da v4.44.0 será necessário alguns ajustes manuais, pois mesmo atualizando via sistema não serão adicionadas. Caso tenha conhecimento, recomendo que verifique as ultimas PRs publicadas ou que realize a instalação (em UAT inicialmente) da MASTER do projeto para verificar se o caso ainda persiste.

Se preferir por falar direto comigo https://wa.me/5581989505723

#Publicidade
Para suporte especializado no MAP-OS, conte com a SYSGO, que é a Parceira Oficial do Projeto, temos a solução conforme a sua necessidade.
https://sysgo.com.br/

**Comment by juliolobo** [comment]
Vá no arquivo config.php aqui no projeto e copie toda a variável **$config['csrf_exclude_uris']** e cole no seu arquivo config, substituindo a mesma variável.
https://github.com/RamonSilva20/mapos/blob/8cc3ca500186900b31db8c01c26e75bd8430eeb8/application/config/config.php#L449

**Comment by fapernas** [comment]
Olá @juliolobo Julio
Estou com o mesmo problema do @newitersorocaba.

A variável no projeto aqui no Git está assim:
$config['csrf_exclude_uris'] = []

Já na minha instalação está assim:
$config['csrf_exclude_uris'] = [
  "os.*+",
  "servicos.*+",
  "produtos.*+",
  "clientes.*+",
  "vendas.*+",
  "garantias.*+",
  "arquivos.*+",
  "lancamentos.*+",
  "cobrancas.*+",
  "configurar.*+",
  "relatorios.*+",
  "mapos.*+",
  "configurar.*+",
  "email.*+"
];

Alterei mas sigo com problemas. Não consigo fazer um lançamento manual de receita e tenho o mesmo erro para incluir um novo usuário.

Minha aplicação está hospedada na InfinityFree e a versão é 4.44 recém instalada do zero.

Desde já agradeço pela atenção.

Fabio Pereira
17 99704-0857

**Comment by juliolobo** [comment]
> Olá @juliolobo Julio
> Estou com o mesmo problema do @newitersorocaba.
> 
> A variável no projeto aqui no Git está assim:
> $config['csrf_exclude_uris'] = [];
> 
> Já na minha instalação está assim:
> $config['csrf_exclude_uris'] = [
>   "os.*+",
>   "servicos.*+",
>   "produtos.*+",
>   "clientes.*+",
>   "vendas.*+",
>   "garantias.*+",
>   "arquivos.*+",
>   "lancamentos.*+",
>   "cobrancas.*+",
>   "configurar.*+",
>   "relatorios.*+",
>   "mapos.*+",
>   "configurar.*+",
>   "email.*+"
> ];
> 
> Alterei mas sigo com problemas. Não consigo fazer um lançamento manual de receita e tenho o mesmo erro para incluir um novo usuário.
> 
> Minha aplicação está hospedada na InfinityFree e a versão é 4.44 recém instalada do zero.
> 
> Desde já agradeço pela atenção.
> 
> Fabio Pereira
> 17 99704-0857

Vc deve estar olhando a versão errada.
Clica no link que coloquei acima e verá que a variável não está de nenhuma das 2 formas como vc mencionou.
Coloquei o link pra deixar tudo bem mais fácil, mas parece que vc ignorou.
