### ISSUE TITLE
emissor de nota fiscal de serviço integrado

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#2356]
durante o gerenciamento de nossa loja em algumas situações será importante emitir nota fiscal de serviços relacionados.
seria ideal permitir, dentro do próprio MapOS um emissor de notas fiscais de serviço no estilo NFSE, que permite a emissão gratuita de nota fiscal para dentro do sistema do simples nacional.

o intuito é por um único sistema, ser possível emitir nota fiscal facilitando a gestão de fechamento de caixa e borderô.

**Comment by Pr3d4dor** [comment]
Emissão de NF requer muita manutenção de código, não teremos isso no mapos base.
