### ISSUE TITLE
Como inserir novo campo a ser visualidado no Dashboard de Clientes

### ISSUE THREAD

**Issue by EdBatista** [RamonSilva20/mapos#236]
Sou um entusiasta e gostei muito do MAPOS, e estou tentando adequar ele a minha realidade.
Já fiz algumas mudanças inserindo um novo campo de preenchimento com dados obrigatórios, porém eu queira que esse mesmo campo seja visualizado na lista de clientes, la contém o código do cliente, Nome, documento, telefone. Eu queria que o campo que eu adicionei também fosse visualizado mas não sei como fazer. Esse campo já está inserido no cadastro ,entretanto no visualizar.php não busca a informação.O que devo fazer?

**Comment by KokeroO** [comment]
Qualquer coisa posso te fazer a adequação. 
Whatsapp: 44 99970-1349
