### ISSUE TITLE
Bug ao adicionar OS - DATA FINAL 31/12/1969

### ISSUE THREAD

**Issue by willph** [RamonSilva20/mapos#237]
Olá, tudo bom?

Com mais alguém acontece isso também, ao adicionar uma O.S. ele já preenche automaticamente com a data final 31/12/1969, ao invés de ir para o banco de dados como NULL e o campo fica em branco.

Desde já obrigado

**Comment by heliocristaldo** [comment]
Coloque o código da VIEW referente a "datafinal " para que possamos ajudar.

**Comment by willph** [comment]
heliocristaldo O codigo é do arquivo "adicionarOS.php".

Eu dei uma analisada e ele vai para o DB assim "0000-00-00" o que acaba fazendo com que as views que trabalha com essa data fique assim "31/12/1969".

Isso acontece apenas quando deixa o campo em branco, tanto no arquivo  "adicionarOS.php" e o "editarOS.php"

Os locais onde tem o campo "Data Final" trás aquele resultado. Eu poderia resolver com um if, mas acredito que assim ficaria uma gambiarra eu acho. To vendo se consigo uma forma melhor de fazer isso.

Desde já muito obrigado.

 ```
<div class="span3">
                                            <label for="dataFinal">Data Final</label>
                                            <input id="dataFinal" class="span12 datepicker" type="text" name="dataFinal" value=""  />
                                        </div>
```

**Comment by KokeroO** [comment]
Os.php está com uma inconsistência nas linhas (122, 126 e 127) que caso os campos dataFinal e dataInicial estiverem em branco ele preenche com a data corrente, mas o problema mesmo e que acaba preenchendo a data de forma incorreta, já que a coluna no banco está definida para o tipo DATE que usa a ISO 8601 para data, que no caso do formato e YYYY-MM-DD e não YYYY/MM/DD.

**Comment by willph** [comment]
KokeroO Será que vai ser corrigido na próxima versão?

**Comment by willph** [comment]
Eu corrigir, mas acredito que não é a forma mais correta de se fazer isso.

 ```
if ($dataFinal = "1969-12-31") {
                    $dataFinal = null;
                }
```
Adicionei abaixo da linha 116 do **adicionar()**, e abaixo da linha 227 do **editar()**

Assim que encontra uma forma melhor de resolver isso, envio como sugestão

**Comment by willph** [comment]
Bug resolvido entre aspa, porque resolvi o problema de ir para o banco de dados com a data "0000-00-00" e na view de **visualizar** e **imprimir** assim "31/12/1969".
Nesse dois ficou ok, agora só tem um problema de bug ainda na view **editar**, pois aparece a data "31/12/1969", mesmo sem ter nada no BD(NULL).

Segue o código colocado abaixo da linha 220 do arquivo Os.php.

```
 if($dataFinal == null  || $dataFinal == ""){
                    $dataFinal = null;
                }else{
                $dataFinal = explode('/', $dataFinal);
                $dataFinal = $dataFinal[2].'-'.$dataFinal[1].'-'.$dataFinal[0];
                }
```

O **adicionar** do arquivo Os.php segue a mesma linha de raciocínio, apesar que eu ainda não testei, por isso não coloquei aqui ainda.

Após analise, percebe que o campo ia assim ` -- ` para o BD e por algum motivo o mesmo preenchia 0000-00-00

Não sei se esta da forma correta o código.

Vou vê se consigo resolver o restante.

Obrigado a todos desde já pelo apoio.

**Comment by willph** [comment]
Bug resolvido no arquivo da View editarOs.php e os.php 


no arquivo da View editarOs.php basta substituir linha 65 por esta:

`<input id="dataFinal" class="span12 datepicker" type="text" name="dataFinal" value="<?php if($result->dataFinal != null){ echo date('d/m/Y', strtotime($result->dataFinal));}else{echo "";} ?>"  />`

e pra resolver no arquivo  da View que se chama os.php basta substituir o código da linha 102
por este:

```
            if($r->dataFinal != null){ 
                $dataFinal = date(('d/m/Y'), strtotime($r->dataFinal));
            }else{
                $dataFinal = "";
            }
```

Não sei se é a melhor forma pra se corrigir, porem funcionou comigo.

Qualquer duvida só perguntar. :)

Obrigado a todos desde já pelo apoio.

**Comment by KokeroO** [comment]
Willph. E simples, altere onde tá y/m/d para Y-M-d nas linhas que citei. Mais só serve para OS Novas, não para as já criadas. 
Obs. Em outros controller acontece a mesma coisa.

**Comment by willph** [comment]
> 
> 
> Willph. E simples, altere onde tá y/m/d para Y-M-d nas linhas que citei. Mais só serve para OS Novas, não para as já criadas.
> Obs. Em outros controller acontece a mesma coisa.

E eu fazendo o mais difícil kkkkkkk
Sei não einh

Vou deixar ai as mensagens anteriores, pra quem quiser fazer assim feito eu.

Obrigado KokeroO pela ajuda.

**Comment by KokeroO** [comment]
Me chame no Zap ai discutimos mais sobre a situação. (44) 9 9970-1349

**Comment by willph** [comment]
Quem quiser esta ai um grupo Mapos criado pra tentar ajudar o povo de alguma forma.

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
