### ISSUE TITLE
Erro lançamento de financeiro

### ISSUE THREAD

**Issue by tecinfopi** [RamonSilva20/mapos#2372]
Bom dia

Está me retornando esse erro na tela de lançamento de contas no sistema

um erro foi encontrado
A ação que você solicitou não é permitida.
print em anexo

!
Att, valdecy

**Comment by tecinfopi** [comment]
/
![Erro_Mapos](https://github.com/RamonSilva20/mapos/assets/47781050/173186c9-6d4b-4b05-a21f-2ff1feafa254)

**Comment by tecinfopi** [comment]
> Bom dia meu amigo, precisaria de maiores detalhes para conseguir te ajudar. Como está sua estrutura, é hospedagem ou local, windows ou linux. Ai qualquer coisa chama no Whatsapp que ajudamos 11 99369-8430

Boa tarde

Obrigado pelo retorna esse aparece tanto na instalação localhost em nuvens

Agradeço pelo retorno

**Comment by fapernas** [comment]
@cabralwms , tudo bem?
Estou enfrentando o mesmo problema que o colega @tecinfopi .
Minha hospedagem é InfinityFree e a versão do MAPOS é 4.44
A instalação foi realizada por mim mesmo do zero.
Estou começando a utilizar o MAPOS, até agora tomei essa mesma mensagem em dois momentos: ao tentar adicionar um novo usuário e adicionar lançamento de receita manualmente na tela de lançamentos.

Desde já agradeço pela atenção.

Fabio Pereira
17 99704-0857

**Comment by Pr3d4dor** [comment]
@cabralwms por favor não repassar mais essa configuração antiga. Nessa config antiga está desativado o csrf em tudo. Favor usar a nova config e precisa configurar o arquivo .env corretamente e também precisa limpar o cache do navegador por conta do arquivo funcoesGlobal.js (ctrl + shift + r).

**Comment by ABSDornelas** [comment]
Estou com o mesmo problema qual seria a forma certa de corrigir ?
