### ISSUE TITLE
Existe versão em inglês para o Mapos? 

### ISSUE THREAD

**Issue by leandroperussolo** [RamonSilva20/mapos#2376]
Gostaria de ter uma versão em inglês para o programa. Caso alguém tenha ou saiba como desenvolver, me envie um zap (41) 98850-7446 - Leandro

**Comment by barretowiisk** [comment]
Olá @leandroperussolo 
Nativamente o sistema não possui multi-idiomas, porém é possível implantar sim.
Para desenvolvimento e hospedagem recomentamos a SYSGO (Parceira Oficial do Projeto).

Acesse sysgo.com.br e terá acesso ao contato do Comercial para solicitar o desenvolvimento conforme as suas necessidades de forma simples.
