### ISSUE TITLE
Erro na guia PRODUTOS

### ISSUE THREAD

**Issue by mittwz** [RamonSilva20/mapos#2377]
**_EM PRODUTOS_**

A função de pesquisa e filtro e a quantidade de resultados por página não funciona corretamente. O filtro aparentemente ignora produtos que estão em outras abas e os resultados por página simplesmente não mudam, mesmo dando F5

**Comment by jardellnk** [comment]
respondido essa duvida nessa issu

https://github.com/RamonSilva20/mapos/issues/2408
