### ISSUE TITLE
ERRO HTTP 5000

### ISSUE THREAD

**Issue by hdarantes** [RamonSilva20/mapos#238]
Bom dia, estou colocando o sistema online e está dando erro http error 500, fui olhar no log de erro da o seguinte:

PHP Fatal error:  Uncaught Error: Call to undefined function mysql_pconnect() in /home/detectpa/public_html/sistema/system/database/drivers/mysql/mysql_driver.php:91
Stack trace:
#0 /home/detectpa/public_html/sistema/system/database/DB_driver.php(115): CI_DB_mysql_driver->db_pconnect()
#1 /home/detectpa/public_html/sistema/system/database/DB.php(148): CI_DB_driver->initialize()
#2 /home/detectpa/public_html/sistema/system/core/Loader.php(346): DB(Array, NULL)
#3 /home/detectpa/public_html/sistema/system/core/Loader.php(1171): CI_Loader->database()
#4 /home/detectpa/public_html/sistema/system/core/Loader.php(152): CI_Loader->_ci_autoloader()
#5 /home/detectpa/public_html/sistema/system/core/Controller.php(51): CI_Loader->initialize()
#6 /home/detectpa/public_html/sistema/application/controllers/mapos.php(13): CI_Controller->__construct()
#7 /home/detectpa/public_html/sistema/system/core/CodeIgniter.php(308): Mapos->__construct()
#8 /home/detectpa/public_html/sistema/index.php(202): require_once('/home/detectpa/...')
#9 {main}

MINHA VERSÃO DE PHP DA HOSPEDAGEM É 5.6.39

Alguém já teve este problema:?

**Comment by RamonSilva20** [comment]
Problema é a versão do PHP. Utilizando as versões indicadas este problema não ocorre.
