### ISSUE TITLE
Implementar autenticação de dois fatores para acesso ao sistema

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#2380]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Primeiramente gostaria de parabenizar a todos os envolvidos no projeto, MUITO BOM! Gosto muito do sistema mais o fato de qualquer um de posse de usuário e senha poder acessar, especialmente se o sistema estiver instalado em uma hospedagem é meio preocupante. Acredito que a implementação de autenticação de 2 fatores seja uma boa opção para aumentar a segurança das informações contidas no sistema.

** Descreva a solução que você deseja **
Talvez usar a biblioteca do Google Authenticator seja viável

** Descreva as alternativas que você considerou **
Praticidade e segurança

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by gleissonneves** [comment]
@SOROInfo será que autenticação implementação de dois fatores é viável visando que o sistema é para o farejo e geralmente nesse nicho o pessoal precisa de praticidade?

**Comment by SOROInfo** [comment]
Bom dia Gleisson, tudo bem com você?

Sim, concordo com você, o sistema deve ser prático de usar e isso ele já é, no entanto, implementar uma nova camada de segurança, visando evitar acesso indevido não vai deixar o sistema menos prático e sim, na minha humilde opinião, mais seguro. 

Permitindo o acesso apenas de pessoas realmente autorizadas, acredito que esse seja o ponto, além de que, isso pode ser implementado como uma opção de segurança configurável e não obrigatória.

**Comment by exosinfor** [comment]
Creio que esse recurso seria opcional  e segmentado, na hora de criar os usuários, ou melhor, os grupos de permissões e colocar a necessidade de 2fa no grupo de permissão, assim podemos configurar para que usuários Admin ou Fiscal usem necessariamente o 2FA enquanto os demais continuam só usando a senha

**Comment by k4k4rot0** [comment]
Olá, boa noite! Achei a ideia interessante. Esperando ansiosamente por esse recurso. :)

**Comment by exosinfor** [comment]
.
