### ISSUE TITLE
Nao consigo acessar a pagina de login

### ISSUE THREAD

**Issue by MaiconDMInfo** [RamonSilva20/mapos#2385]
session_write_close(): Falha ao gravar dados da sessão usando o manipulador de salvamento definido pelo usuário. (sessão.save_path: C:\xampp\tmp)  Recebo este erro ao tentar acessar a pagina de login, nao achei informaçoes para solucionar

**Comment by jardellnk** [comment]
Informe a versao do mapos utilizado. 
e versao php 

Porem acredito que esse erro seja falta de permissão gravação na pasta do Mapos 

acesse a pasta c:\xampp\htdocs botao direito pasta mapos e desmarque a opçao somente leitura 

ou cmd 

icacls "C:\xampp\htdocs\mapos" /grant "nome_do_usuário:(R,W)"

no linux 

va ate a pasta 

/opt/lampp/htdocs

chmod 777 mapos
