### ISSUE TITLE
Agrupamento de Empresas/Lojas como mesmo DONO.

### ISSUE THREAD

**Issue by Deniizynhu** [RamonSilva20/mapos#2391]
Caso não exista essa função (NUNCA ACHEI), seria muito interessanteadicionar a opção de criar uma espécie de grupo de acesso (**na parte do cliente**) com um único propósito:
O cliente tendo mais de uma loja, ele conseguiria acessar TODAS AS LOJAS VINCULADAS à um único usuário, tendo a mesma visão que ele tem hoje, porém, com todas as suas lojas...
Na forma que funcionar o sistema hoje, o cliente  que tem 3 lojas tem que acessar as 3 SEPARADAMENTE.
Tenho clientes que possuem mais de 1 loja e sei o quanto isso não é legal (Possuir mais de um acesso por ter mais de uma loja).
Acho que seria muito válido esse tipo de atualização, pois tenho certeza que seria muito útil para todos os usuário que prestam serviços e utilizam esse excelente sistema.
Aguardo um parecer da equipe.

**Comment by juliolobo** [comment]
Não acredito que isso será implementado nem tão cedo.
Quem sabe quando sair a versão Laravel.

**Comment by Deniizynhu** [comment]
Para quem já usa o sistema, isso seria muito importante.
Eu passo por essa situação, e sei o quanto isso ajudaria até na valorização do sistema que já é muito bom.
