### ISSUE TITLE
Tela de Anexo da ordem de serviços não exibe o nome do arquivo

### ISSUE THREAD

**Issue by mateushdasilva** [RamonSilva20/mapos#2397]
Versão do MAPOS - 4.45

Boa noite. A tela de anexos da ordem de serviço, não exibe o nome.formato do arquivo, impedindo de conseguir baixar o arquivo necessário.
![Sem título](https://github.com/RamonSilva20/mapos/assets/26901540/d26d5f5f-5504-4008-b0bb-a795dc944562)

Gostaria de saber se também é possível não compactar/alterar o nome dos arquivos em que é feito o upload.

Obrigado.

**Comment by juliolobo** [comment]
O Mapos não salva o nome do Arquivo então não tem como exibir.
