### ISSUE TITLE
Erro ao importar base sql

### ISSUE THREAD

**Issue by rodrigotheodoro** [RamonSilva20/mapos#24]
Está acontecendo o seguinte erro:

Erro

consulta SQL:

-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
`session_id` VARCHAR( 40 ) NOT NULL DEFAULT '0',
`ip_address` VARCHAR( 45 ) NOT NULL DEFAULT '0',
`user_agent` VARCHAR( 120 ) NOT NULL ,
`last_activity` INT( 10 ) UNSIGNED NOT NULL DEFAULT '0',
`user_data` TEXT NOT NULL ,
PRIMARY KEY ( `session_id` ) ,
INDEX `last_activity_idx` ( `last_activity` ASC )
) ENGINE = InnoDB DEFAULT CHARACTER SET = latin1;

Mensagens do MySQL : Documentação
#1286 - Unknown storage engine 'InnoDB'

**Comment by RamonSilva20** [comment]
Olá, o seu banco de dados não está com a engine InnoDB habilitada, ative-a ou remova as ocorrências de  "ENGINE = InnoDB" do script de criação das tabelas "banco.sql".
