### ISSUE TITLE
NAO CONSIGO INSTALAR PELO MODO AUTOINSTALACAO

### ISSUE THREAD

**Issue by cleytonasa** [RamonSilva20/mapos#240]
faço todo procedimento, mas não passa da segunda epata quando colocamos o banco, senha , login administrador, quando criamos a base de dados precisamos colocar senha mesmo?

**Comment by RamonSilva20** [comment]
Utilizando o instalador, é preciso somente criar o banco de dados, o instalador vai criar as tabelas e cadastrar o usuário informado no instalador.
