### ISSUE TITLE
Erro MySQL

### ISSUE THREAD

**Issue by DiegoCrepaldi** [RamonSilva20/mapos#2402]
Prezados boa noite, não estou conseguindo acessar o MAPOS, apresenta o erro abaixo:
Poderia me ajudar, por gentileza.
Obrigado

Error: MySQL shutdown unexpectedly.
This may be due to a blocked port, missing dependencies, 
improper privileges, a crash, or a shutdown by another method.
Press the Logs button to view error logs and check
the Windows Event Viewer for more clues
If you need more help, copy and post this
entire log window on the forums

**Comment by jardellnk** [comment]
Antes de mais nada é bom reforçar que seja feito o Backup do banco de dados ! 

alternativa 1 

- menu iniciar do windows -> botao direito executar como administrador e tentar iniciar o apache e mysql 

alternativa 2 

- tente alterar a porta 3306 por outra porta como a 3307 ou 3308 ->  xampp painel control ->configuracao->my.ini
reinicie o xamppcontrol e tente novamente 

alternativa 3

*/xampp/mysql/  renomei a pasta data como data.old  crie uma nova pasta e copie os arquivos da pasta data.old ´para a nova pasta reinicie o xampp e tente novamente

**Comment by DiegoCrepaldi** [comment]
Ola meu amigo, obrigado pelo apoio.

Agora aparece esse erro ao acessar o MAPOS:

session_write_close(): Failed to write session data using user defined save handler. (session.save_path: C:\xampp\tmp, handler: CI_SessionWrapper::write)
