### ISSUE TITLE
Sistema só funciona no Firefox

### ISSUE THREAD

**Issue by lvidau** [RamonSilva20/mapos#2406]
Estou fazendo a instalação do sistema na Hostgator. Os passos para instalação ocorrem sem problemas, sem erros. Ao tentar acessar via Google Chrome, a tela de login fica toda desconfigurada e não faz login, o erro também ocorre em outros navegadores, Opera e Edge por exemplo. Mas se acesso o site via Firefox, o acesso ocorre normalmente, sem problemas.

Já testei tanto a versão 4.44 com php 8.1, quanto a versão 4.45 com php 8.2, ambos apresentam o mesmo erro.

Página desconfigurada.
![loginchrome](https://github.com/RamonSilva20/mapos/assets/42617604/8a28f40e-854a-421c-8c7d-2bac8867794a)

Ao digitar usuário e senha aparece a seguinte mensagem:
![errocho](https://github.com/RamonSilva20/mapos/assets/42617604/2b8616f8-2f23-4a9b-a686-6fced3d39d60)

Observei os seguintes erro ao inspecionar a página no chrome:
![https](https://github.com/RamonSilva20/mapos/assets/42617604/fe62e132-9847-48dd-836b-12a354457606)

**Comment by cabralwms** [comment]
Verifica no arquivo application/.env se a base_url = esta correta, http://seu-domonio.com.br/mapos/ com a barra no final. se usa HTTPS ou HTTP.

**Comment by juliolobo** [comment]
Seu problema está no uso ou não de https
O chrome força o uso de https
Configure corretamente um certificado digital no subdomínio do mapos e altere no arquivo .env para https

![image](https://github.com/RamonSilva20/mapos/assets/13459803/e42acbc4-822d-4e7e-967e-93d047828a41)

**Comment by andremp15** [comment]
Boa noite a todos, estou com o mesmo erro no Android, acessando pelo Android fica dessa forma

**Comment by lvidau** [comment]
Boa tarde. Problema resolvido! Era relacionado ao HTTPS da hospedagem mesmo. Após isso funcionou ok em todas as plataformas.

**Comment by juliolobo** [comment]
Obrigado pelo retorno

> Boa tarde. Problema resolvido! Era relacionado ao HTTPS da hospedagem mesmo. Após isso funcionou ok em todas as plataformas.
