### ISSUE TITLE
erro na pesquiça de cliente e de OS. 

### ISSUE THREAD

**Issue by lizar007** [RamonSilva20/mapos#2408]
Olá, tudo bem?

Quando quero fazer uma pesquisa de algum cliente ou ordem de serviço o sistema consegui fazer somente dos 100 registro que estão abertos na página. eu tenho 400 clientes cadastrado. para eu encontrar um cliente preciso ir às 4 paginas para encontrar o cliente ou a ordem de serviço.

**Comportamento esperado**

gostaria que na opção de pesquisa conseguisse resultado em todos os meu registro sem precisar trocar de página.

**Comment by juliolobo** [comment]
Já foi resolvido, atualize seu mapos

**Comment by cabralwms** [comment]
Faz a busca pelo campo pesquisar do lado esquerda proximo ao menu para testar.

**Comment by lizar007** [comment]
obrigado pelo retorno....

Na pesquisar próximo ao menu. faz a busca de cliente esta ok, as da Ordem de serviço não encontra nada.
na aba de ordem de serviço se pesquisar por nome, a página não muda. já na parte de status e pelas data, esta filtrando normalmente.

**Comment by lizar007** [comment]
A  4.45.

**Comment by jardellnk** [comment]
Sobre aquele campo acima da tabela que exibe as OS, é apenas um filtro das "paginaçoes " aonde são carregados alguns item por pagina e não um campo de pesquisa em si. 

nesse caso na parte inferior tera outras abas numeradas conforme a quantidade de OS que você tenha! e pode usar o filtro alternando as paginas. 

Outra alternativa é incluir um numero maior de  itens exibido por paginas (lembrando que isso pode deixar o carregamento da pagina um pouco mais lento) 

Porem um exemplo de como voce pode fazer isso :  


abra com um editor de texto o arquivo ..\mapos\application\views\mapos\configurar.php e busque por 

<label for="per_page" class="control-label">Registros por Página</label>

algumas linhas abaixo você ira ver algo como 
<option value="100" <?= $configuration['per_page'] == '100' ? 'selected' : ''; ?>>100</option>

e podera incluir um novo valor 

<option value="500" <?= $configuration['per_page'] == '500' ? 'selected' : ''; ?>>500</option>

com isso voce ira carregar 500 os inves de 100 o que acredito que seja um numero bem satisfatório

**Comment by lizar007** [comment]
Obrigado jardellnk, pelas instruções. 

resolveu parte do problema. agora eu estou conseguindo filtrar cliente. 
mais na ordem de serviço ainda não dar para filtrar por nome. quando eu tento pesquisar não retornada nada.

fiz um video com a versão 4.45, que está com problema na pesquisa na orgem de serviço e na versão 4.44, que esta com a pesquisa ok.
link versão 4.45
https://drive.google.com/file/d/1ett64XGfZ-rY6CZEh6yQtEQlaxNF58SG/view?usp=drivesdk
link versão 4.44
https://drive.google.com/file/d/1exrBxprQsMiEIMNVOVhnMiDYsyeKiYRB/view?usp=drivesdk

**Comment by juliolobo** [comment]
> Obrigado jardellnk, pelas instruções.
> 
> resolveu parte do problema. agora eu estou conseguindo filtrar cliente. mais na ordem de serviço ainda não dar para filtrar por nome. quando eu tento pesquisar não retornada nada.
> 
> fiz um video com a versão 4.45, que está com problema na pesquisa na orgem de serviço e na versão 4.44, que esta com a pesquisa ok. link versão 4.45 https://drive.google.com/file/d/1ett64XGfZ-rY6CZEh6yQtEQlaxNF58SG/view?usp=drivesdk link versão 4.44 https://drive.google.com/file/d/1exrBxprQsMiEIMNVOVhnMiDYsyeKiYRB/view?usp=drivesdk

Existia um problema nessa pesquisa que já foi identificada e corrigida, atualiza esse seu arquivo [application\controllers\Os.php](https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php)

**Comment by lizar007** [comment]
juliolobo, 

fiz a substituição do OS.php, application/controllers/Os.php, mas ficou do mesmo jeito quantinua o problema.

**Comment by juliolobo** [comment]
@lizar007 Acabei de subir uma PR pra resolver isso.
https://github.com/RamonSilva20/mapos/pull/2410

**Comment by juliolobo** [comment]
@lizar007 
Já foi feito merge da correção, atualize seu mapos de preferência baixando o projeto novamente para ter certeza que está tudo ok
https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip

**Comment by lizar007** [comment]
@juliolobo 
beleza. fiz a instalação do projeto e deu tudo certo. 
obrigado pelo empenho.

**Comment by gdk-dev** [comment]
@lizar007, Fico feliz que tenha resolvido seu problema.
Como seu problema foi resolvido, poderia fechar a issue "close issue"  (acho que é algo assim).


Abraço!
