### ISSUE TITLE
Hospedar MapOs no Locaweb

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#241]
Poderiam me ajudar a hospedar o MapOs em meu servidor Locaweb?

1. criei um subdomínio dentro do meu domínio para hospedar o MapOs.
2. fiz upload de todos os arquivos do MapOs para meu servidor FTP
3. criei um banco de dados com o nome sistena_mapos
4. deixei meu subdominio para ler a pasta de FTP onde salvei os arquivos do MapOs
5. tentei instalar o MapOs pela web como o passo-a-passo mas só diz que o arquivo de configuração não foi encontrado.
6. tentei instalar manualmente mas o problema continua. alterei o config.ini e database direcionando para meu banco manualmente, executei a tabela.sql, alterei no indice etc...

Alguém tem alguma ideia?

FTP:
![arquivo ftp](https://user-images.githubusercontent.com/21310068/50426678-f4ed5800-0872-11e9-915c-fcd2cad48aff.jpg)

Dominio / SubDominio:
![dominio e sub](https://user-images.githubusercontent.com/21310068/50426679-fcacfc80-0872-11e9-8945-681b6f1beb98.jpg)

Erro do site:
![site](https://user-images.githubusercontent.com/21310068/50426695-88268d80-0873-11e9-801e-992ca1e85526.jpg)

Banco de dados: 
![banco de dados 1](https://user-images.githubusercontent.com/21310068/50426723-5f52c800-0874-11e9-9844-411c1cacf7cb.jpg)

PHPMyAdmin
![phpmyadmin](https://user-images.githubusercontent.com/21310068/50426725-6a0d5d00-0874-11e9-933a-ab9b6099214a.jpg)

**Comment by KokeroO** [comment]
Whattsapp  (44) 99970-1349

**Comment by vitolike** [comment]
Poderia postar um print do erro?

**Comment by Triaca** [comment]
o erro é de parâmetros do banco, excluir e estou refazendo meu banco de dados na locaweb para tentar novamente.
mas o que preciso de ajuda é para adicionar os dados de minha hospedagem dentro do arquivo do banco.
não estou sabendo fazer isso

**Comment by Triaca** [comment]
Exemplo: 
subi todos os arquivos do mapo offline para meu servidor FTP.
Subi o arquivo .sql do BD do mapos para o meu servidor BD.
no arquivo phpmyadmin do mapos eu preciso por o diretório do mapos onde estarei acessando ele, no caso eu coloquei os dados do meu BD, estaria certo isso?

![mapos php](https://user-images.githubusercontent.com/21310068/50403474-8c707f00-077d-11e9-8baf-772ab3f6a33f.jpg)

**Comment by vitolike** [comment]
Vamos por partes.. 
1. Subiu os arquivos via FTP? Feito
2. Criou o banco de dados?
3. Executou o install?

**Comment by KokeroO** [comment]
Whattsap (44) 99970-1349

**Comment by Triaca** [comment]
@KokeroO / @vitolike 

Fiz todo o processo, alterei os dados de conexão do servidor dentro do bin etc do MapOs e mesmo assim deu erro!
o que descobri é que como eu utilizo um site pelo criador de sites da locaweb ai da incompatibilidade pois o direcionamento de meu dominio fica para o site, eu teria que ter um site fora desse criador ou até mesmo por wordpress para conseguir utilizar o MapOs lá.

isso segundo o suporte da locaweb

**Comment by Triaca** [comment]
para tentar melhorar a ajuda, vou postar o passa a passo que utilizei.

**Comment by Triaca** [comment]
> Vamos por partes..
> 
> 1. Subiu os arquivos via FTP? Feito
> 2. Criou o banco de dados?
> 3. Executou o install?

Na hora de executar o install da erro.
reformulei o post para ficar um pouco mais claro.

**Comment by RamonSilva20** [comment]
@Triaca qual a mensagem de erro está dando ao executar o install? Conseguiu resolver?

**Comment by Triaca** [comment]
> @Triaca qual a mensagem de erro está dando ao executar o install? Conseguiu resolver?

Ramon obrigado pela preocupação!
Acredito que o problema era alguma configuração servidor / mapos.
Eu refiz o subdomínio e todo o servidor (hospedagem FTP) e o @KokeroO revisou e instalou para mim o MapOs.
acredito que era alguma informação ou permissão em alguma pasta.

**Comment by vinnyparker** [comment]
alguem pode me informar como resolveu? eu to com o mesmo problema com uma instalação em subdominio.  Vi que a mensagem que da é quando nao encontra o arquivo settings.json. Mas ele ta la. alguem tem uma luz sobre como resolver?
