### ISSUE TITLE
[DUVIDA] No mapos existe duas seções - Login e mine, a quem se refere a área do cliente?

### ISSUE THREAD

**Issue by gdk-dev** [RamonSilva20/mapos#2411]
A área do cliente, é do meu cliente onde ele irá opera?

**Comment by cabralwms** [comment]
Então a area do cliente é representado pela Mine. Você administrador no link www.seudominio.com.br/mapos/index.php e então você passa para seu cliente www.seudominio.com.br/mapos/index.php/mine.

**Comment by gdk-dev** [comment]
aaaaaaaah, ficou claro!!!! bacana
