### ISSUE TITLE
Erro ao tentar realizar login no Mapos

### ISSUE THREAD

**Issue by EduardoRDias** [RamonSilva20/mapos#2412]
Estou tentando realizar o login no Mapos, porém não carrega a tela de login..
Segue imagem.

![image](https://github.com/RamonSilva20/mapos/assets/169870262/d63e1c7a-db29-47d9-af03-41e73c012cbe)

**Comment by juliolobo** [comment]
A configuração da URL está errada, pode ser que vc tenha colocado com http:// e na verdade seja https:// ou vice e versa.
Se está instalando um mapos Novo, recomendo pegar a versão mais recente aqui no repositório.
