### ISSUE TITLE
Envio OS para aprovação sem necessidade de login e senha na area do cliente

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#2414]
Preciso enviar a os especifica para o cliente aprovar, so que gostaria q fosse para ele visualizar e aprovar mas sem necessidade do cliente fazer login e senha, alguem ja fez isso???
Imaginei em fazer um formulario a parte aonde carregar os dados das os e depois salvar no banco se foi aprovado

**Comment by juliolobo** [comment]
Já fiz para alguns clientes. Me procure nos grupos de Whatsapp ou Telegram do Mapos e te passo um orçamento.

**Comment by juliolobo** [comment]
@marquinhomaquinas Como isso vai de encontro com a LGPD (Lei geral de proteção de dados), Isso não será implantado de forma oficial no Mapos.
