### ISSUE TITLE
inserir as configs do .env dentro de "Configurações > Sistema"

### ISSUE THREAD

**Issue by exosinfor** [RamonSilva20/mapos#2415]
Gostaria de solicitar que configurações manuais tipo email e gateway de pagamentos sejam colocadas em configurações > sistema, minimizando ao máximo o contato do usuário com o código nos arquivos locais.

**Comment by willph** [comment]
Se não me falhe a memória a versão master do código já está assim.

Qual versão está usando?

Em seg., 20 de mai. de 2024, 22:18, Exos informática <
***@***.***> escreveu:

**Comment by juliolobo** [comment]
@willph Está assim sim.
@exosinfor Utilize a versão master do repositório e verá que já tem isso no menu configurações

**Comment by juliolobo** [comment]
@exosinfor Assim que confirmar favor fechar a issue

**Comment by exosinfor** [comment]
estou fechando a issue, eu tinha instalado com o instalador automático que não puxa a ultima versão. na nova já está desse jeito.
