### ISSUE TITLE
ADICIONAR NOVA TELA

### ISSUE THREAD

**Issue by Higor188** [RamonSilva20/mapos#2420]
Bom dia, preciso de ajudar para adicionar uma tela de Equipamentos no map os 3.10.0. Eu já configurei o controller, model e views, mas mesmo assim não consigo. Quando termino de configurar, vou no dashboard ver se apareceu a opção equipamento, porém a opção não aparece.

observação: Eu preciso da versão 3.10.0
[mapos.zip](https://github.com/RamonSilva20/mapos/files/15443589/mapos.zip)

**Comment by juliolobo** [comment]
Bom dia @Higor188 
Essa versão é muito antiga.
Remova a Tag **Bug** pois isso não é **Bug**.
Peça ajuda para personalizações nos grupos de Whatsapp ou Telegram.
Aqui não damos suporte a personalizações.
