### ISSUE TITLE
Erro ou entrar no site 

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#2423]
** Descreva o bug **
Do nada hoje apresentou erro ou entrar no site (esta online num subdomínio e o site esta funcionando normalmente). Não fiz nenhuma atualização nem nenhuma mudança.
![Captura de tela 2024-05-29 132604](https://github.com/RamonSilva20/mapos/assets/68141004/c9997513-9fed-4934-bbdc-29e5a06a69ec)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 11
 - Chrome ou Firefox
 - Versão Ultimas

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: Poco X5 Pro
 - SO: Android
 - Chrome ou Firefox
 - Versão Ultimas

**Comment by MarceloGrass** [comment]
Foi uma atualização do PHP no servidor que ocasionou o problema. Voltei a versão anterior e voltou ao normal. Vou ter que atualizar o Mapos primeiro e depois atualizar o PHP na versão 8.1. Me responderam rapidamente no canal de WhatsApp e resolvi rapidamente o problema. Muito obrigado a esta comunidade incrível.

**Comment by juliolobo** [comment]
@MarceloGrass Recomendo vc fazer backup do banco de dados e dos arquivos do mapos.
Muda a versão do PHP pra 8.3 que é a mais recente.
Baixa o mapos mais atual que é a Master (https://github.com/RamonSilva20/mapos/archive/refs/heads/master.zip)
Instala e depois vc importa o Backup do Banco de dados antigo.

Assim vc terá a versão mais atualizada do PHP e do Mapos e não vai se preocupar nem tão cedo.
OBS. Fui eu que lhe dei a dica da versão do PHP lá no Grupo. Qualquer dúvida só mandar lá que a gente ajuda.
E se precisa de algum serviço de personalização (novos campos, novos itens no menu...) só chamar no privado.
