### ISSUE TITLE
AJUDA INSTALAÇÃO

### ISSUE THREAD

**Issue by DiegoCrepaldi** [RamonSilva20/mapos#2424]
Prezados, bom dia!
Por gentileza, algum poderia me ajudar instalar o mapos na hostinger. Sou leigo no tema.
Obrigado

**Comment by cabralwms** [comment]
qual a dificuldade?

**Comment by DiegoCrepaldi** [comment]
Olá amigo!
Eu fiz todo procedimento com base em um vídeo no YouTube, mas o sistema não carrega!
Como não conheço alguns termos técnico, não sei se fiz correto.
Vc tem como me ajudar ou indicar um passo a passo.
Obrigado

**Comment by juliolobo** [comment]
@cabralwms Manda aquele mapos com a vendor pra ele.

**Comment by cabralwms** [comment]
Com esse link vc consegue instalar diretamente na sua hospedagem sem precisar comandos pelo composer, envia essa pasta para a hospedagem e então abre o link e segue com a instalação padrão após comando do composer.

https://www.firewarrior.com.br/nextcloud/index.php/s/73Wnc4MANW3qJBb

**Comment by DiegoCrepaldi** [comment]
Amigo consegui, atraves de uma pessoa que intende de TI. por gentieza, como eu acesso agora a tela de casdastramento do login e senha do sistema. pq agora ele cai na tela de login e senha direto

**Comment by cabralwms** [comment]
Na hora que configurou o sistema pede o cadastro do administrador. Usa esse cadastro para logar e então criar mais usuários permissões e tudo que precisa no sistema



Enviado do meu Galaxy



-------- Mensagem original --------
De : DiegoCrepaldi ***@***.***>
Data: 06/06/2024 17:38 (GMT-03:00)
Para: RamonSilva20/mapos ***@***.***>
Cc: cabralwms ***@***.***>, Mention ***@***.***>
Assunto: Re: [RamonSilva20/mapos] AJUDA INSTALAÇÃO (Issue #2424)


Amigo consegui, atraves de uma pessoa que intende de TI. por gentieza, como eu acesso agora a tela de casdastramento do login e senha do sistema. pq agora ele cai na tela de login e senha direto
