### ISSUE TITLE
Poder Adicionar/Mudar o Nome da Ordem de Serviço pelo Arquivo de Configuração

### ISSUE THREAD

**Issue by k4k4rot0** [RamonSilva20/mapos#2428]
Olá, Boa tarde! Tudo bem com V6? Espero que sim!

AVISO, não sou programador, sou apenas um curioso. Mas estou tentando contribuir com um pouco de conhecimento que tenho.
EU fiz essas alterações, não sei se fiz certo.

Também não sei se é de muita importância para V6.

Att;
Paulo

## No Arquivo de configuração
![config](https://github.com/RamonSilva20/mapos/assets/65426919/f1dcb1ae-4430-4563-9827-2d5861717c96)

## No arquivo da OS
![os](https://github.com/RamonSilva20/mapos/assets/65426919/5b522a0e-7d10-4967-9514-32cb03d0d932)

## Resultado
![resultado](https://github.com/RamonSilva20/mapos/assets/65426919/1521cfbc-5e75-48eb-ab0f-61c0eedd3db3)

**Comment by juliolobo** [comment]
Não entendi o que tentou fazer.
Poderia explicar melhor com prints de tela inteira?
E diga que arquivos são esses, especificando o caminho e o nome do arquivo.

**Comment by k4k4rot0** [comment]
@juliolobo , bom dia! Sim, claro! 

## Segue caminho dos arquivos;

mapos/application/config/config.php

![config](https://github.com/RamonSilva20/mapos/assets/65426919/aeea1bad-2281-449e-b6c2-3a982d215abb)


mapos/application/views/os/imprimirOs.php

![os](https://github.com/RamonSilva20/mapos/assets/65426919/9276a8ab-7355-4c30-96c9-196d90462228)

**AVISO**, o que está sublinhado foram as alterações que fiz no meu arquivo.

A minha ideia é na hora de gerar para imprimir a OS não sair com o nome: **Map-OS**, e sim, com o nome da Loja/Empresa.

## Resultado
![resultado](https://github.com/RamonSilva20/mapos/assets/65426919/f78a2092-0aef-4b27-828f-535d4e46e39a)

**Comment by juliolobo** [comment]
@k4k4rot0 Entendi o que você quis fazer.
Sua versão do mapos deve ser anterior a 4.44, não usamos mais o arquivo config.php para guardar as configurações.
Mas achei a ideia interessante.

**Comment by k4k4rot0** [comment]
Obrigado por me compreender, @juliolobo . Então, eu atualizei a minha versão, porém, deu conflito no setor de vendas. Não sei por qual motivo. Mas vou reportar para vocês darem uma olhada depois.

**Comment by cabralwms** [comment]
Opa bom dia meu amigo, teve algumas mudanças no setor de vendas, você baixou os arquivos novos do github do mapos? Verifica fazer as atualizações no banco de dados nos arquivos update/update_4.45.0_to_4.46.0.sql

**Comment by juliolobo** [comment]
@cabralwms Não tem nada a ver com setor de vendas.
Acho que vc fez confusão.

**Comment by k4k4rot0** [comment]
@cabralwms , bom dia! Tudo bem? Espero que sim! Eu entendi o que você quis falar. Vou testar mais tarde e dou o feedback, Bllz?

**Comment by cabralwms** [comment]
Perfeito



Enviado do meu Galaxy



-------- Mensagem original --------
De : Paulo Soares ***@***.***>
Data: 05/06/2024 08:37 (GMT-03:00)
Para: RamonSilva20/mapos ***@***.***>
Cc: cabralwms ***@***.***>, Mention ***@***.***>
Assunto: Re: [RamonSilva20/mapos] Poder Adicionar/Mudar o Nome da Ordem de Serviço pelo Arquivo de Configuração (Issue #2428)


@cabralwms<https://github.com/cabralwms> , bom dia! Tudo bem? Espero que sim! Eu entendi o que você quis falar. Vou testar mais tarde e dou o feedback, Bllz?

**Comment by cabralwms** [comment]
Verifica ao editar venda como está a garantia



Enviado do meu Galaxy



-------- Mensagem original --------
De : Paulo Soares ***@***.***>
Data: 05/06/2024 11:22 (GMT-03:00)
Para: RamonSilva20/mapos ***@***.***>
Cc: cabralwms ***@***.***>, Mention ***@***.***>
Assunto: Re: [RamonSilva20/mapos] Poder Adicionar/Mudar o Nome da Ordem de Serviço pelo Arquivo de Configuração (Issue #2428)


Bom dia, @cabralwms<https://github.com/cabralwms> . Após executar: update/update_4.45.0_to_4.46.0.sql realmente deu tudo certo. Voltei o backup do Banco de Dados e abriu tudo certo. Mas pelo que estou vendo, ainda está dando um erro no setor de vendas. Segue prints;

Dentro do MapOS - (Setor de Vendas)

vendass.png (view on web)<https://github.com/RamonSilva20/mapos/assets/65426919/dc6596b5-4013-4e74-96ae-81bc914b6a19>

Erro após clicar em: Visualizar

vendas_db_erro.png (view on web)<https://github.com/RamonSilva20/mapos/assets/65426919/c23c8d91-1a83-4962-9e61-9aa389065251>

**Comment by k4k4rot0** [comment]
@cabralwms , eu fiz esses teste: coloquei sem nada, coloquei 0 e coloquei 7 dias. Mesmo assim o erro persiste.

**Comment by cabralwms** [comment]
Verifica então seu arquivo apllication/controller/Vendas.php se está atualizado visualizar Vendas.php tbm e imprimir vendas.php

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by k4k4rot0** [comment]
@cabralwms , está bem. vou verificar. Só uma **OBS**. Eu fiz uma instalação limpa para fazer esses testes. Eu não estou com o **MapOS** que uso em produção. mesmo assim preciso conferir??
