### ISSUE TITLE
Como remanejar o sistema

### ISSUE THREAD

**Issue by edsclickcell** [RamonSilva20/mapos#2429]
como eu faço para alterar a url, caso eu queira passar do local para web, pois config php não é mais usavel

**Comment by Pr3d4dor** [comment]
@edsclickcell Toda a configuração fica agora no arquivo .env na raiz. Basta alterar o APP_URL nesse arquivo.

**Comment by edsclickcell** [comment]
valeu muito obrigado

**Comment by exosinfor** [comment]
funcionou? por favor lembre de fechar a issue como "resolvida"
