### ISSUE TITLE
Remover envio automático quando cliente abre uma nova OS

### ISSUE THREAD

**Issue by exosinfor** [RamonSilva20/mapos#2436]
Prezados, 

pela área de logada é possível abrir uma ordem de serviço, nesse momento em que é aberta a OS é enviado um email para o técnico responsável. 

gostaria de solicitar que este email seja opcional pois muitas vezes o técnico não quer esse tipo de email em sua caixa de mensagem ao mesmo tempo que no caso de um técnico que não esteja presente ou que não acesse o sistema todo dia  pode continuar recebendo as notificações.

**Comment by cabralwms** [comment]
Você pode ir em configurações do sistema e colocar para quem quer que vá o email, ou se não quer envio algum. tem varias opções lá.

**Comment by exosinfor** [comment]
esta opção só existe na ordem de serviço aberta que vem por padrão como "notificar apenas o cliente". Esta opção não existe na hora que o cliente abre uma OS pela área do cliente (e nem deve existir) portanto a notificação não está atrelada a nenhuma configuração. 

![abrir OS cliente](https://github.com/RamonSilva20/mapos/assets/169174226/bcb7e66d-22ef-4fae-802c-e2428bda0776)
