### ISSUE TITLE
COMO HOSPEDAR OS ARQUIVOS ASSIM QUE BAIXADO

### ISSUE THREAD

**Issue by Fylipi** [RamonSilva20/mapos#244]
então baixei os arquivos da ultima versão, peguei o banco já coloquei na hospedagem, mas quando passo  os arquivos e entro no endereço da erro de índex ou minha tela fica toda branca, tem algum link ou tutorial que possa me indicar de como hospedar corretamente, pois ja procurei nesse forum e no google mas nada deu certo.

desde já grato.

**Comment by RamonSilva20** [comment]
Olá. O que você precisará fazer é o upload dos arquivos do sistema, criar o banco de dados e o usuário, depois acesse pela URL e coloque as informações no instalador, que irá criar as tabelas e o usuário administrador. Após a instalação, remova a pasta install.

**Comment by Fylipi** [comment]
então fiz ai quando terminei de instalar deu,  Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente. (http://fplsystem.tk/install/index.php)
e quando eu excluo a pasta instal da erro na pagina.

**Comment by RamonSilva20** [comment]
@Fylipi Conseguiu? Eu acessei e está funcionando normalmente.

**Comment by Fylipi** [comment]
@RamonSilva20  consegui sim, você pode me falar como altero, para iniciar na area do cliente, e como tiro o link onde esta a versão do sistema ?
