### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Teofilo382** [RamonSilva20/mapos#2440]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

Quando inserido as informaçoes na OS , a mesma fica carregando nao avançando para outra pagina, a nao ser que aperte voltar, faz-se necessario sair novamente e ir uma a uma para inserção de produtos e mais infrmaçoes.

**Comment by RamonSilva20** [comment]
Olá @Teofilo382. Esse tipo de comportamento acontece quando está com a versão diferente da indicada. Está usando a versão 8.1?

**Comment by cabralwms** [comment]
Bom dia meu amigo, Você consegue esclarecer como está seu ambiente? Hospedagem ou Local? Windows ou Linux? versão do PHP e versão do mapos baixada? Geralmente esses erros podem ser devido PHP e versão instalada do mapos.

**Comment by willph** [comment]
> ** Descreva o bug ** Uma descrição clara e concisa do que é o erro.
> 
> Quando inserido as informaçoes na OS , a mesma fica carregando nao avançando para outra pagina, a nao ser que aperte voltar, faz-se necessario sair novamente e ir uma a uma para inserção de produtos e mais infrmaçoes.

Para cadastra na OS ou Venda, precisa previamente ter cadastrado o Cliente, para add produto ou serviço também precisa ter cadastrado antes nos seus respectivos menus.

Fico no aguardo, qualquer coisa reabro a issue
