### ISSUE TITLE
Erro ao subir o MAPOS online cpanel

### ISSUE THREAD

**Issue by jhonescah** [RamonSilva20/mapos#2441]
![erro mapos](https://github.com/RamonSilva20/mapos/assets/172982636/107f293f-06e2-4477-a5fb-6dd118d4b55c)
no cpanel no seletor php está tudo ativado! e na hora de configurar aparece esse erro.

**Comment by jhonescah** [comment]
![extensoes](https://github.com/RamonSilva20/mapos/assets/172982636/dff3e373-918e-4dcb-8d81-46ec761f9341)
Está tudo ativado, só que não ativa na página de install do mapos.

**Comment by barretowiisk** [comment]
Boa noite @jhonescah,
Precisará verificar isso com seu provedor de Hospedagem, pois o código apenas retorna o status do serviço/função do server a qual está hospedado.
Importante outras informações complementares, tais como: versão do PHP, versão do Map-OS, quem é o provedor de hospedagem, print do PHPINFO (Demonstrando que as extensões necessárias estão realmente ativas) e etc.

#Publicidade
Recomendamos hospedar na SYSGO, a parceira Oficial do projeto e que oferece instâncias dedicadas a hospedar o MAP-OS, além de suporte especializado para o Projeto.

**Comment by jhonescah** [comment]
Eu tenho a hospedagem da https://webdesenvolvimento.com.br funciona muito bem.

**Comment by erickmoreno1** [comment]
O suporte do servidor resolveu o problema, está tudo funcionando perfeitamente obrigado a todos.

**Comment by erickmoreno1** [comment]
![funcionando](https://github.com/RamonSilva20/mapos/assets/172982636/c303fa91-15b4-4c5c-8dec-d7dfe5b8a21e)

O suporte do servidor resolveu o problema, está tudo funcionando perfeitamente obrigado a todos.
