### ISSUE TITLE
Não realiza a busca de produtos por todo BD.

### ISSUE THREAD

**Issue by ppeuti** [RamonSilva20/mapos#2446]
Quando vou em produtos e faço uma pesquisa, não consigo pesquisar além dos 100 itens já listado na página.
Ou seja, se eu estou pesquisando por SSD SATA no meu BD e ele não estiver na página com os 100 primeiros itens, eu tenho que mudar a página e realizar uma nova busca.

![image](https://github.com/RamonSilva20/mapos/assets/20739481/dc32e6a0-6073-49ee-85bc-d3af7db0176b)

Fiz essa pesquisa na primeira página e não apareceu.

![image](https://github.com/RamonSilva20/mapos/assets/20739481/6e47fb04-3997-4245-8217-73ed23e47b0e)

Somente quando eu fui para página 4 e refiz a busca que o item foi listado.

**Comment by ppeuti** [comment]
Estou usando a versão 4.45.0 e estou hospensando no hostgator.
PHP atualizado tb.

**Comment by ideniltonfreitas** [comment]
Também percebi esse problema aqui...

**Comment by ideniltonfreitas** [comment]
Resolvi aqui com Chat GPT. Ficou com eu queria, não sei se é a melhor forma de fazer mas, para hoje é o que temos.
No arquivo:
/application/controllers/Produtos.php

Modifiquei a função gerenciar() e, ficou assim:

public function gerenciar()
{
    if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vProduto')) {
        $this->session->set_flashdata('error', 'Você não tem permissão para visualizar produtos.');
        redirect(base_url());
    }

    $this->load->library('pagination');

    // Configuração da paginação
    $config['base_url'] = site_url('produtos/gerenciar/');
    $config['total_rows'] = $this->produtos_model->count('produtos'); // Total de registros na tabela

    // Ajuste para buscar todos os registros da tabela
    $config['per_page'] = 0; // Define para 0 para que não haja limitação na busca

    // Inicializa a configuração da paginação
    $this->pagination->initialize($config);

    // Obtém a página atual a partir da URI segment
    $page = $this->uri->segment(3, 0);

    // Obtém todos os produtos da base de dados
    $this->data['results'] = $this->produtos_model->get('produtos', '*', '');

    // Carrega a view
    $this->data['view'] = 'produtos/produtos';
    return $this->layout();
}

E, no arquivo:

/application/models/Produtos_model.php

Alterei a função get(), ficou que ficou dessa forma.

public function get($table, $fields, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array')
    {
        $this->db->select($fields);
        $this->db->from($table);
        $this->db->order_by('idProdutos', 'desc');
    
        // Verifica se deve aplicar um limite
        if ($perpage > 0) {
            $this->db->limit($perpage, $start);
        }

        if ($where) {
            $this->db->where($where);
        }
    
        $query = $this->db->get();
    
        if ($one) {
            $result = $query->row();
        } else {
            $result = $query->result();
        }
    
        return $result;
    }

Dessa forma, eu consigo pesquisar todos os registros da tabela produtos e, posso escolar quantos quero exibir na página apenas selecionando a quantidade no resultado por página do formulário. Espero que ajude. Esse é meu primeiro contato por aqui. Muito obrigado à todos pelo ótimo trabalho...

**Comment by ppeuti** [comment]
> i

Rapaz, no meu até lista mais de 10, só que a busca só vai nos 100 primeiros.

**Comment by ppeuti** [comment]
> Resolvi aqui. Ficou como eu queria, não sei se é a melhor forma de fazer mas, para hoje é o que temos. No arquivo: /application/controllers/Produtos.php
> 
> Modifiquei a função gerenciar() e, ficou assim:
> 
> public function gerenciar() { if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vProduto')) { $this->session->set_flashdata('error', 'Você não tem permissão para visualizar produtos.'); redirect(base_url()); }
> 
> ```
> $this->load->library('pagination');
> 
> // Configuração da paginação
> $config['base_url'] = site_url('produtos/gerenciar/');
> $config['total_rows'] = $this->produtos_model->count('produtos'); // Total de registros na tabela
> 
> // Ajuste para buscar todos os registros da tabela
> $config['per_page'] = 0; // Define para 0 para que não haja limitação na busca
> 
> // Inicializa a configuração da paginação
> $this->pagination->initialize($config);
> 
> // Obtém a página atual a partir da URI segment
> $page = $this->uri->segment(3, 0);
> 
> // Obtém todos os produtos da base de dados
> $this->data['results'] = $this->produtos_model->get('produtos', '*', '');
> 
> // Carrega a view
> $this->data['view'] = 'produtos/produtos';
> return $this->layout();
> ```
> 
> }
> 
> E, no arquivo:
> 
> /application/models/Produtos_model.php
> 
> Alterei a função get(), que ficou dessa forma.
> 
> public function get($table, $fields, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array') { $this->db->select($fields); $this->db->from($table); $this->db->order_by('idProdutos', 'desc');
> 
> ```
>     // Verifica se deve aplicar um limite
>     if ($perpage > 0) {
>         $this->db->limit($perpage, $start);
>     }
> 
>     if ($where) {
>         $this->db->where($where);
>     }
> 
>     $query = $this->db->get();
> 
>     if ($one) {
>         $result = $query->row();
>     } else {
>         $result = $query->result();
>     }
> 
>     return $result;
> }
> ```
> 
> Dessa forma, eu consigo pesquisar todos os registros da tabela produtos e, posso selecionar quantos quero exibir na página apenas selecionando a quantidade no resultado por página, direto no formulário. Dessa forma eu pesquiso em todo o banco de dados e, os registros que coincidem com a busca, já ficam filtrados no formulário. Espero que ajude. Esse é meu primeiro contato por aqui. Muito obrigado à todos pelo ótimo trabalho...

Aqui, tu fez essa atualização direto no sistema rodando, e foi de boas?

**Comment by ideniltonfreitas** [comment]
> > Resolva aqui. Ficou como eu queria, não sei se é a melhor forma de fazer mas, para hoje é o que temos. No arquivo: /application/controllers/Produtos.php
> > Modifiquei a função de gerenciamento() e ficou assim:
> > public function gerenciar() { if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vProduto')) { $this->session->set_flashdata('error' , 'Você não tem permissão para visualizar produtos.'); redirecionamento(base_url()); }
> > ```
> > $this->load->library('pagination');
> > 
> > // Configuração da paginação
> > $config['base_url'] = site_url('produtos/gerenciar/');
> > $config['total_rows'] = $this->produtos_model->count('produtos'); // Total de registros na tabela
> > 
> > // Ajuste para buscar todos os registros da tabela
> > $config['per_page'] = 0; // Define para 0 para que não haja limitação na busca
> > 
> > // Inicializa a configuração da paginação
> > $this->pagination->initialize($config);
> > 
> > // Obtém a página atual a partir da URI segment
> > $page = $this->uri->segment(3, 0);
> > 
> > // Obtém todos os produtos da base de dados
> > $this->data['results'] = $this->produtos_model->get('produtos', '*', '');
> > 
> > // Carrega a view
> > $this->data['view'] = 'produtos/produtos';
> > return $this->layout();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > E, sem arquivo:
> > /application/models/Produtos_model.php
> > Alterei a função get(), que ficou dessa forma.
> > função pública get($tabela, $campos, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array') { $this->db->select($fields ); $this->db->from($table); $this->db->order_by('idProdutos', 'desc');
> > ```
> >     // Verifica se deve aplicar um limite
> >     if ($perpage > 0) {
> >         $this->db->limit($perpage, $start);
> >     }
> > 
> >     if ($where) {
> >         $this->db->where($where);
> >     }
> > 
> >     $query = $this->db->get();
> > 
> >     if ($one) {
> >         $result = $query->row();
> >     } else {
> >         $result = $query->result();
> >     }
> > 
> >     return $result;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Dessa forma, eu consigo pesquisar todos os registros da tabela de produtos e, posso selecionar quantos quero exibir na página apenas selecionando a quantidade no resultado por página, direto no formulário. Dessa forma eu pesquiso em todo o banco de dados e, os registros que coincidem com a busca, já ficam filtrados no formulário. Espero que ajude. Esse é meu primeiro contato por aqui. Muito obrigado a todos pelo ótimo trabalho...
> 
> Aqui, você fez essa atualização direta no sistema rodando, e foi de boas?

Sim, funcionou normalmente, sistema em produção.

**Comment by ideniltonfreitas** [comment]
> > Resolva aqui. Ficou como eu queria, não sei se é a melhor forma de fazer mas, para hoje é o que temos. No arquivo: /application/controllers/Produtos.php
> > Modifiquei a função de gerenciamento() e ficou assim:
> > public function gerenciar() { if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vProduto')) { $this->session->set_flashdata('error' , 'Você não tem permissão para visualizar produtos.'); redirecionamento(base_url()); }
> > ```
> > $this->load->library('pagination');
> > 
> > // Configuração da paginação
> > $config['base_url'] = site_url('produtos/gerenciar/');
> > $config['total_rows'] = $this->produtos_model->count('produtos'); // Total de registros na tabela
> > 
> > // Ajuste para buscar todos os registros da tabela
> > $config['per_page'] = 0; // Define para 0 para que não haja limitação na busca
> > 
> > // Inicializa a configuração da paginação
> > $this->pagination->initialize($config);
> > 
> > // Obtém a página atual a partir da URI segment
> > $page = $this->uri->segment(3, 0);
> > 
> > // Obtém todos os produtos da base de dados
> > $this->data['results'] = $this->produtos_model->get('produtos', '*', '');
> > 
> > // Carrega a view
> > $this->data['view'] = 'produtos/produtos';
> > return $this->layout();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > E, sem arquivo:
> > /application/models/Produtos_model.php
> > Alterei a função get(), que ficou dessa forma.
> > função pública get($tabela, $campos, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array') { $this->db->select($fields ); $this->db->from($table); $this->db->order_by('idProdutos', 'desc');
> > ```
> >     // Verifica se deve aplicar um limite
> >     if ($perpage > 0) {
> >         $this->db->limit($perpage, $start);
> >     }
> > 
> >     if ($where) {
> >         $this->db->where($where);
> >     }
> > 
> >     $query = $this->db->get();
> > 
> >     if ($one) {
> >         $result = $query->row();
> >     } else {
> >         $result = $query->result();
> >     }
> > 
> >     return $result;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Dessa forma, eu consigo pesquisar todos os registros da tabela de produtos e, posso selecionar quantos quero exibir na página apenas selecionando a quantidade no resultado por página, direto no formulário. Dessa forma eu pesquiso em todo o banco de dados e, os registros que coincidem com a busca, já ficam filtrados no formulário. Espero que ajude. Esse é meu primeiro contato por aqui. Muito obrigado a todos pelo ótimo trabalho...
> 
> Aqui, você fez essa atualização direta no sistema rodando, e foi de boas?

Olhando agora, acho que o código acima foi traduzido pelo meu navegador para português na hora da postagem... vou corrigir aqui e mando novamente.

**Comment by CrisHoff** [comment]
como posso fazer isso para área de vendas?
