### ISSUE TITLE
Alterar data do produto ao incluir produto na O.S.

### ISSUE THREAD

**Issue by juniormb** [RamonSilva20/mapos#2447]
Quando faço a inlcusão de um produto na O.S. ele altera a quantidade no estoque, até ai tudo certo, porem, gostaria de alterar tambem a data de cadastro desse produto pra data do dia atual (que foi incluido o produto na O.S.) na tabela de produtos.
Eu uso dessa forma pra que eu saiba que essa foi a data da ultima venda desse produto (a data de cadastro do produto pra mim é irrelevante).

Percebi que ele faz isso em dois arquivos (alterar a quantidade), conforme trecho do codigo postado abaixo:
MODELS\PRODUTOS_MODEL.PHP
CONTROLLERS\OS.PHP

A minha duvida é o que eu preciso incluir no codigo para que ele altere junto com a quantidade no estoque (que ele ja faz normalmente), que ele altere a data de cadastro do produto pra data atual na tabela de produtos.

MODELS\PRODUTOS_MODEL.PHP
public function updateEstoque($produto, $quantidade, $operacao = '-')
{
$sql = "UPDATE produtos set estoque = estoque $operacao ? WHERE idProdutos = ?";
return $this->db->query($sql, [$quantidade, $produto]);
}

CONTROLLERS\OS.PHP
if ($this->os_model->add('produtos_os', $data) == true) {
$this->load->model('produtos_model');
if ($this->data['configuration']['control_estoque']) {
$this->produtos_model->updateEstoque($produto, $quantidade, '-');
}
log_info('Adicionou produto a uma OS. ID (OS): ' . $this->input->post('idOsProduto'));

return $this->output
->set_content_type('application/json')
->set_status_header(200)
->set_output(json_encode(['result' => true]));
}

**Comment by barretowiisk** [comment]
Opa @juniormb 
Não sei se entendi a sua dúvida ou sugestão, no entanto acredito que não seja viável a implementação no projeto, pois adicionar um Produto a uma OS não altera sua entrada no estoque, pois em tese (caso tenha estoque) ele já existe no estoque para ser vendido (atribuído).

#Publicidade
Caso seja uma necessidade somente sua, recomendo a SysGO Soluções para apoiar no desenvolvimento conforme as suas necessidade.

www.sysgo.com.br

**Comment by juliolobo** [comment]
Recomendo adicionar uma nova coluna no banco de dados como updated_at e colocar pra essa data se alterada quando houver um update na linha do produto, como a alteração do estoque.
algo como um:
`updated_at ` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

**Comment by cleciobarbosa** [comment]
> Recomendo adicionar uma nova coluna no na tabela de produtos como updated_at e colocar pra essa data se alterada quando houver um update na linha do produto, como a alteração do estoque. algo como um: `` `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ``

Sua sugestão faz total sentido, porém, o nome updated_at faz se entender data de ultima alteração do produto, sugiro 'ultima _venda', 'ultima_utilizacao' algo nesse sentido.

**Comment by barretowiisk** [comment]
@juniormb 
Precisa de suporte especializado para o MAP-OS?
Entre em contato com nosso time de suporte e obtenha a solução desejada.

SYSGO - Parceria Oficial do Projeto MAP-OS
https://sysgo.com.br/mapos-github
