### ISSUE TITLE
Problema com cadastro de Emitente

### ISSUE THREAD

**Issue by whm15** [RamonSilva20/mapos#245]
Boa tarde,
Estou tendo problemas ao cadastrar o emitente, aparece a seguinte mensagem quando coloco pra salvar as informações: "The temporary folder is missing.".
Lembrando que eu já coloquei a permissão de todas as pastas do sistema e principalmente da pasta "uploads" como 777, para que não haja interferência quanto a permissões. Mesmo assim, não consegui resultado.
Aguardo uma ajuda de vocês.
![emitente_mapos](https://user-images.githubusercontent.com/37050012/50843551-0bee7880-1350-11e9-8937-960ee2b6c168.jpg)

**Comment by whm15** [comment]
Amigo, desculpe a ignorância (estou aprendendo), mas onde fica este arquivo "php.ini"?

**Comment by KokeroO** [comment]
Você deve tratar com a hospedagem, e algumas não dão acesso a editar.
Qualquer coisa me add no zap: 44 9 9970-1349

**Comment by whm15** [comment]
A hospedagem é a 000webhost, gratuita. É muito boa e fácil de usar e tem um fórum com várias dúvidas resolvidas.
--- Resolvido ---
Pesquisei sobre a opção que você falou "upload_tmp_dir" e achei a solução: Criar a pasta "tmp" no diretório raiz do servidor de arquivos. Coloquei também a permissão 777, para evitar mais erros.
Grato pela ajuda!

**Comment by KokeroO** [comment]
Que bom que deu certo.

**Comment by mendaxcn** [comment]
Helppp!!!

Mesmo criando o diretório uploads neste caminho: assets/uploads/ e aplicando a permissão 777, ocorre o mesmo erro em anexo, as configurações do php.ini (upload_tmp_dir) estão OK, poderiam me auxiliar por favor na resolução do problema? Obrigado.


![Captura de tela de 2019-06-24 22-46-36](https://user-images.githubusercontent.com/52184318/60063640-ff7a9400-96d3-11e9-9a5e-1cebce0d3fe5.png)
