### ISSUE TITLE
Problemas na instalação do Composer.

### ISSUE THREAD

**Issue by cezargf** [RamonSilva20/mapos#2457]
Ao executar o comando "composer install --no-dev", são informados problemas com dois pacotes.

![image](https://github.com/RamonSilva20/mapos/assets/25113573/5f985308-f94f-475d-87fd-c5065e58e1e5)

**Comment by lukasabino** [comment]
Boa noite! Favor revomer tag de bug, não é.

A versão que está usando no seu PHP é 8.1.29, o MAPOS exige no mínimo a 8.2,  reinstale o XAMPP na versão correta.

**Comment by barretowiisk** [comment]
@cezargf 
O seu problema foi sanado? Se sim, por favor informe o feedback e encerre essa ISSUE.

**Comment by cezargf** [comment]
Obrigado, eu percebi, resolvi e estou fechando a issue.

Enviado do meu Samsung Mobile da Claro
Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
