### ISSUE TITLE
Este aplicativo não pode ser executado em seu PC

### ISSUE THREAD

**Issue by DavidsonPrata** [RamonSilva20/mapos#2459]
** Descreva o bug **
Estava seguindo o passo a passo para fazer a instalação do MapOS deste video:
https://www.youtube.com/watch?v=jIK8wjgcONo

Depois de instalar o Laragon segui para a instalação até que apareceu a mensagem "Este aplicativo não pode ser executado em seu PC" após rodar o arquivo .bat . 

Alguém já passou por isso ou sabe como resolver?

** Capturas de tela **
![image](https://github.com/RamonSilva20/mapos/assets/54452856/cdd37ac4-499d-4567-95fd-242b14dffbac)

**Desktop**
 - SO: Windows 10 Home
 - Navegador Microsoft Edge Version 126.0.2592.81 (Official build) (64-bit)

**Comment by barretowiisk** [comment]
Boa tarde @DavidsonPrata 
O script está desatualizado no momento, recomendo que não utilize no momento, a PR #2462 vai atualiza-la, está apenas aguardando aprovação.
Sobre a mensagem na tela, se dá ao nível de segurança em que está configurado seu sistema operacional, antes de executar o script:
- Vá até seu diretório padrão do terminal (Geralmente: C:\Users\"seu usuário"
- Localize o arquivo MapOS_Install.bat
- Clique com botão direito do mouse e selecione Propriedades
- Marque a opção desbloquear e aplique
- Execute o arquivos como Administrador e siga as Instruções.

Outra causa pra isso é que seu antivírus esteja barrando o download completo do XAMPP ou até mesmo impedindo sua execução, então vai mais uma recomendação:
- Desative o Antivírus temporariamente
- Abra o executar e digite `%temp%\InstaladorMAPOS` e Enter
- Delete todos os arquivos e execute o script novamente.

Se resolveu, não esqueça de retornar o feedback e também encerrar essa ISSUE.

**Comment by DavidsonPrata** [comment]
Olá @barretowiisk barretowiisk, muito obrigado pela atenção, mas o problema persiste. Eu cheguei a formatar a máquina e instalar o Win 10 Pro (foi me recomendado, já que o Home poderia haver alguma limitação). Repeti o passo a passo e nada.

Se vc ou alguém tiver alguma outra sugestão, fico grato!

**Comment by barretowiisk** [comment]
@DavidsonPrata 
Me chama no zap https://wa.me/5581989505723

**Comment by DavidsonPrata** [comment]
Muito obrigado @barretowiisk mas eu já consegui realizando a instalação manual seguindo o passo passo do video do edson olcheski. Valeu mesmo!

https://www.youtube.com/watch?v=wMKiKQXjffs&t=311s
