### ISSUE TITLE
ONDE ALTERO PARA INICIAR  NA TELA DO CLIENTE INDEX.PHP/MINE ?

### ISSUE THREAD

**Issue by Fylipi** [RamonSilva20/mapos#246]

**Comment by KokeroO** [comment]
Se quer executar direto a area do cliente pelo link principal pode entrar em application/config/routes.php e na linha 43 troque `$route['default_controller'] = "mapos";` por `$route['default_controller'] = "mine";`

**Comment by Fylipi** [comment]
mano muito obrigado.

**Comment by KokeroO** [comment]
Zap: 44 9 9970-1349

**Comment by Fylipi** [comment]
pode me informar onde altero o campo de cpf da tela de login
para aparecer digitos de senha  ******** .. ?

**Comment by KokeroO** [comment]
O login acontece somente por email.

**Comment by Fylipi** [comment]
eu sei mas quando o cliente digita o cpf, aparece os numeros, queria deixar com ***

**Comment by KokeroO** [comment]
Você fala entao na tela do cliente. Deve alterar o tipo de campo de text para password.

**Comment by Fylipi** [comment]
qual caminho que nao estou achando nem a pau.

**Comment by KokeroO** [comment]
application/views/conecte/login.php

**Comment by Fylipi** [comment]
> q

se executar esse comando, na tela principal quando se clica no dashboard volta para a tela de login/mine
não teria que mostra o painel ?
