### ISSUE TITLE
CPF não editável

### ISSUE THREAD

**Issue by itaymbere** [RamonSilva20/mapos#2460]
** Descreva o bug **
O usuário padrão criado pelo instalador não permite a edição do campo CPF ao editar o usuário

**Comportamento esperado**
Deveria permitir

** Capturas de tela **
![image](https://github.com/RamonSilva20/mapos/assets/6540332/f4cfe33b-0b4e-476d-bd58-c69cf3bb6326)

**Comment by barretowiisk** [comment]
Boa tarde @itaymbere 
Não se trata do instalador em si, isso é um padrão estabelecido no projeto, uma vez criado o usuário não pode alterar o CPF por se tratar de um documento não mutável, nesse caso recomendo que altere via banco de dados ou inative o usuário e crie um novo, tendo em vista que é sempre bom ter um super usuário e os demais com permissões mais restritas.

Geralmente oriento:
1- Administrador (Super usuário) - Permissão a tudo
2- Fulano (Administrador) - Sem permissão de Exclusão

Isso é um entendimento de negócio, pois nada deve ser excluído (somente em ultimo caso), uma vez cadastrado deve-se ser inativado ou cancelado.
