### ISSUE TITLE
Erro HTTP 500 ao tentar abrir sistema pela primeira vez 

### ISSUE THREAD

**Issue by RafaelMG2019** [RamonSilva20/mapos#247]
Erro HTTP 500 ao tentar abrir o sistema pela primeira vez 

localhost não consegue atender a esta solicitação no momento.
HTTP ERROR 500

**Comment by KokeroO** [comment]
Está acontecendo algum erro no script e o php não está configurado para mostrar os erros. 
No arquivo index.php apartir da linha 62 dentro da condição coloque o seguinte código:
`error_reporting(-1);
ini_set('display_errors', 1);`
Tente executar a aplicação novamente e veja qual erro apresenta.

**Comment by RafaelMG2019** [comment]
Tem como mandar fotos detalhando , porque não esta dando certo

**Comment by KokeroO** [comment]
Zap: 44 9 9970-1349
