### ISSUE TITLE
@viniciusvams Não posso realizar o merge da PR assim. Favor rever toda a indentação do código e remover os comentários. Vi que foi feito uma função para converter número pra texto, se não me engano já tem uma função que faz isso e não precisaria fazer uma nova.

### ISSUE THREAD

**Issue by viniciusvams** [RamonSilva20/mapos#2477]
Corrigida a indentação para melhorar a legibilidade do código, removido os comentários;

 @viniciusvams Não posso realizar o merge da PR assim. Favor rever toda a indentação do código e remover os comentários. Vi que foi feito uma função para converter número pra texto, se não me engano já tem uma função que faz isso e não precisaria fazer uma nova.

_Originally posted by @Pr3d4dor in https://github.com/RamonSilva20/mapos/issues/2476#issuecomment-2226938816_

**Comment by Fesantt** [comment]
Ops.... Lugar errado 🗡️

**Comment by barretowiisk** [comment]
@viniciusvams 
Favor, encerre a ISSUE
