### ISSUE TITLE
Inclusão de Área para Locação de materiais 

### ISSUE THREAD

**Issue by CrisHoff** [RamonSilva20/mapos#2479]
Olá, me chamo Cristian Hoffmeister, tenho uma empresa de locação de materiais para construção, eu gostei muito do sistema de vocês, eu gostaria de dar a ideia de adicionarem uma área para locação, pois minha loja trabalha com vendas, oque já tem presente no sistema, mas também temos muito foco em locação, se possível eu também gostaria de ajudar a desenvolver um pouco mais essa ideia da área de locação juntamente ao sistema de vendas. desde já agradeço a atenção. E-mail para contato: cdshjshjm@gmail.com

Eu ainda estou no começo da faculdade de desenvolvimento de sistemas, então não tenho muita experiência, eu estou usando o mapos, se possível alguém conseguir me ajudar criando essa área de locação eu vou ajudar com um valor simbólico no pix. Obrigado pela atenção 🙏

**Comment by barretowiisk** [comment]
@CrisHoff 
Precisa de suporte especializado para o MAP-OS?
Entre em contato com nosso time de suporte e obtenha a solução desejada.

SYSGO - Parceria Oficial do Projeto MAP-OS
https://sysgo.com.br/mapos-github
