### ISSUE TITLE
ERRO AO CLICA BOTÃO EXCLUIR

### ISSUE THREAD

**Issue by ronaldnnr** [RamonSilva20/mapos#248]
Olá, Ramon e pessoal, estou com um problema na tela de "PRODUTOS" ao colocar o mouse por cima do botão de excluir, o mouse fica como se estivesse clicando varias vezes, e nao consigo acionar para realizar a exclusão. alguem ja passou por essa situação ?

**Comment by KokeroO** [comment]
Provavelmente o problema é com o seu navegador. Já testou em outro PC? Tente recarregar essa página com Ctrl+F5, se não der teste em outro navegador.

**Comment by ronaldnnr** [comment]
então ja havia testado.  ja limpei a base, ja fiz toda instalação novamente... quando passo em cima do botão excluir na tela de "PRODUTOS" o mouse fica como se estivesse processando algo, fica piscando bem rapido.     caso alguem queira dar uma olhada eu passo o teamviwer so pra me dar um NORTE mesmo

**Comment by KokeroO** [comment]
Zap 44 9 9970-1349
