### ISSUE TITLE
Realizar uma venda

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#2488]
Sistema esta em hospedagem. Quando clico na opção VENDAS apresenta essa tela.
![Sem título](https://github.com/user-attachments/assets/4667090e-83a5-4c68-a053-20cbb4835e0a)

**Comment by barretowiisk** [comment]
Boa tarde,
Precisa atualizar o banco de dados, vá em Sistema -> Atualizações -> Atualizar Banco de Dados...
Sua coluna garantia e status não foram criadas.

**Comment by CarlosCavalcante87** [comment]
Muito obrigado!!!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by barretowiisk** [comment]
@CarlosCavalcante87 
Se foi resolvido, por favor encerre a ISSUE.
Fico feliz em ajudar.

**Comment by CarlosCavalcante87** [comment]
Resolvido com a importação do novo banco de dados!
Obrigado devs 👏🙌
