### ISSUE TITLE
Exibição na tela inicial

### ISSUE THREAD

**Issue by CarlosCavalcante87** [RamonSilva20/mapos#2489]
Seria mais interessante a exibição de dados de produtos / serviços mais vendidos no mês / semana.

Nesse caso retirava o campo de ESTATISTICAS FINANCEIRAS e adicionava no lugar esta exibição nova.

![Sem título](https://github.com/user-attachments/assets/5aba62d6-2cc8-4f04-aa9f-d16419f8b298)

**Comment by barretowiisk** [comment]
@CarlosCavalcante87 
Precisa de suporte especializado para o MAP-OS?
Entre em contato com nosso time de suporte e obtenha a solução desejada.

SYSGO - Parceria Oficial do Projeto MAP-OS
https://sysgo.com.br/mapos-github
