### ISSUE TITLE
PAGINA NAO ENCONTRADA - ADICIONAR ARQUIVO

### ISSUE THREAD

**Issue by ronaldnnr** [RamonSilva20/mapos#249]
na tela de   http://localhost/mapos/index.php/arquivos/adicionar
quando voce adiciona o arquivo, apresente o erro que a pagina nao pode ser encontrada

404 Page Not Found
The page you requested was not found

alguem passou por essa situação ?

**Comment by RamonSilva20** [comment]
Problema solucionado na versão 3.1.16.

**Comment by papaiisac** [comment]
bom dia estou com mesmo problema, minha versão 3.3 
Valeu

**Comment by lagethomas** [comment]
Bom dia, qual problema enfrenta nessa versão?

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em sex, 8 de mar de 2019 08:36, papaiisac <notifications@github.com>
escreveu:
