### ISSUE TITLE
Integração api whaticket

### ISSUE THREAD

**Issue by rogowski193** [RamonSilva20/mapos#2493]
Seria interessante a integração com a api do whaticket, junto com o envio automático de email, poder enviar as mensagens para o WhatsApp do cliente, all

**Comment by Fesantt** [comment]
@lukasabino

**Comment by barretowiisk** [comment]
@rogowski193 
Precisa de suporte especializado para o MAP-OS?
Entre em contato com nosso time de suporte e obtenha a solução desejada.

SYSGO - Parceria Oficial do Projeto MAP-OS
https://sysgo.com.br/mapos-github
