### ISSUE TITLE
Erro ao Instalar e tentar Carregar o BD pela Primeira Vez

### ISSUE THREAD

**Issue by hardbrasil** [RamonSilva20/mapos#25]
Ao instalar e configurar ao tentar acessar o domínio dá este erro:  

A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 346

**Comment by RamonSilva20** [comment]
Olá, os dados de conexão com o banco de dados estão incorretos, verifique novamente o arquivo database.php.

**Comment by hardbrasil** [comment]
Aparentemente está certo:



$active_group = 'default';

$active_record = TRUE;



$db['default']['hostname'] = 'mysql.hardbrasil.com.br';

$db['default']['username'] = 'hardbras_os';

$db['default']['password'] = '131326Coro';

$db['default']['database'] = 'hardbras_os';

$db['default']['dbdriver'] = 'mysql';

$db['default']['dbprefix'] = '';

$db['default']['pconnect'] = TRUE;

$db['default']['db_debug'] = TRUE;

$db['default']['cache_on'] = FALSE;

$db['default']['cachedir'] = '';

$db['default']['char_set'] = 'utf8';

$db['default']['dbcollat'] = 'utf8_general_ci';

$db['default']['swap_pre'] = '';

$db['default']['autoinit'] = TRUE;

$db['default']['stricton'] = FALSE;







Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Ter, 25 abr 2017 18:55:59 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Olá, os dados de conexão com o banco de dados estão incorretos, verifique novamente o arquivo database.php.

**Comment by hardbrasil** [comment]
Conferi alterei novamente e agora apresenta este outro erro:



A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 346



Poderia me dar uma ajudinha?​







Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Ter, 25 abr 2017 18:55:59 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Olá, os dados de conexão com o banco de dados estão incorretos, verifique novamente o arquivo database.php.

**Comment by RamonSilva20** [comment]
Infelizmente eu não tenho como validar se estão corretos os dados. Você vinculou o usuário ao banco de dados?

**Comment by hardbrasil** [comment]
Sim esta Vinculado:



A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/hardbrasil/public_html/os/application/config/database.php:1)

Filename: core/Common.php

Line Number: 439


A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 346








Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Ter, 25 abr 2017 19:09:16 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Infelizmente eu não tenho como validar se estão corretos os dados. Você vinculou o usuário ao banco de dados?

**Comment by RamonSilva20** [comment]
O mais provável que esteja incorreto é o hostname ou a senha. Tem certeza que o host do banco de dados é o que você inseriu, já tentou com localhost?

**Comment by hardbrasil** [comment]
Já revi tudo não é local é remoto meu servidor



O erro que dá agora é esse:





Parse error: syntax error, unexpected '*' in /home/u236882062/public_html/system/core/CodeIgniter.php on line 58





Obrigado​





Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Ter, 25 abr 2017 19:09:16 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Infelizmente eu não tenho como validar se estão corretos os dados. Você vinculou o usuário ao banco de dados?

**Comment by RamonSilva20** [comment]
Faça o upload novamente do arquivo que está dando problemas.

**Comment by michelfritsch** [comment]
Tenta alterar o hostname de:
$db['default']['hostname'] = 'mysql.hardbrasil.com.br';
Por:
$db['default']['hostname'] = 'localhost';
No Hostgator funciona.

**Comment by hardbrasil** [comment]
Já foi resolvido reconfigurei tudo e upei novamente para o server.





* Uma pergunta para atualizar por versões mais recentes é só copiar a pasta system por cima da atual ou como faço tem de baixar e upar o sistema todo?

E no caso de haver novas tabelas terei de rodar novamente o BD?





Obrigado pela atenção.



Att;



Sérgio C Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qua, 26 abr 2017 12:45:50 -0300 michelfritsch &lt;notifications@github.com&gt; wrote ----




Tenta alterar o hostname de:

 $db['default']['hostname'] = 'mysql.hardbrasil.com.br';

 Por:

 $db['default']['hostname'] = 'localhost';

 No Hostgator funciona.

**Comment by RamonSilva20** [comment]
A pasta system é do Codeigniter, não é feita alterações nela, somente em caso de atualização do framework, como será feito em breve ao atualizarmos para o versão 3. O banco de dados também não teve alterações, mas terá em breve, nesse caso terá um script de atualização para que não tenha perda dos dados do banco.

**Comment by hardbrasil** [comment]
Ok, obrigado.

Atualmente não é possível pesquisar por tipo de equipamento ou marca ou serial

Também não sai os dados de contato do Cliente na OS



Na 3.0 isso será corrigido?



Obrigado.



Att;






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qua, 26 abr 2017 13:34:19 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




A pasta system é do Codeigniter, não é feita alterações nela, somente em caso de atualização do framework, como será feito em breve ao atualizarmos para o versão 3. O banco de dados também não teve alterações, mas terá em breve, nesse caso terá um script de atualização para que não tenha perda dos dados do banco.

**Comment by RamonSilva20** [comment]
Sim, na versão 3 terá o cadastro de equipamentos e serão vinculados à OS.

**Comment by hardbrasil** [comment]
Ok, obrigado.






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qua, 26 abr 2017 14:24:06 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Sim, na versão 3 terá o cadastro de equipamentos e serão vinculados à OS.

**Comment by hardbrasil** [comment]
Como atualizar somente o sistema sem ter que upar todos os arquivos novamente?



Att;



Sérgio Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qui, 29 jun 2017 22:38:10 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Closed #25.

**Comment by rjmvaz** [comment]
estou tendo o seguinte erro ao acessar o meu MAPOS, pela primeira vez localmente
Um erro do PHP foi encontrado
Gravidade: aviso

Mensagem: Somente referências de variáveis ​​devem ser retornadas por referência

Nome do arquivo: core / Common.php

Número da linha: 257

Um erro do PHP foi encontrado
Gravidade: aviso

Mensagem: Não é possível modificar as informações do cabeçalho - cabeçalhos já enviados por (saída iniciada em /home/rjmvazi1/public_html/mapos/system/core/Exceptions.php:185)

Nome do arquivo: core / Common.php

Número da linha: 438

Ocorreu um erro de banco de dados
Não é possível conectar-se ao seu servidor de banco de dados usando as configurações fornecidas.

Nome do arquivo: core / Loader.php

Número da linha: 346

**Comment by altairdantas** [comment]
O meu é no login, já mudei tanta coisa e nada!.

![image](https://user-images.githubusercontent.com/50056972/56856794-c8d50700-6938-11e9-99ae-59c882e6ae3f.png)
