### ISSUE TITLE
Pesquisa por numero de telefone ou documento

### ISSUE THREAD

**Issue by Claudiomfa** [RamonSilva20/mapos#250]
qual o ficheiro a alterar o campo da pesquisa para que seja possível a pesquisa pelo numero de telefone, celular e pelo documento.

**Comment by Claudiomfa** [comment]
Na tela principal. No Canto superior direito

**Comment by RamonSilva20** [comment]
Altere no arquivo Mapos_model o método pesquisar (linha 55) como no exemplo abaixo, mude de acordo com o critério que você precisa, se quer buscar exatamente pelo termo pesquisado use where, se quer parcialmente use like. 

![0190115143553](https://user-images.githubusercontent.com/12385697/51194931-3651b000-18d3-11e9-8ac9-d6e839d3b6d1.png)

**Comment by Maria-18fra** [comment]
Preciso cancelar minha conta e não consigo, oque faço?
