### ISSUE TITLE
Erro ao ao tentar abrir a pagina vendas!

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#2502]
Boa tarde, atualizei o mapos para a versão 4.46, fiz o backup do banco e ao importar já não consigo mais abrir a pagina vendas.

Sempre exbe um erro, algum dos amigos desenvolvedores poderia me da uma ajuda?
![erro mapos](https://github.com/user-attachments/assets/4e33b7d8-f73f-43ca-8322-d7353b55ad1f)

**Comment by viniciusvams** [comment]
Veja se não é o mesmo problema que essa pessoa relatou:
https://github.com/RamonSilva20/mapos/issues/2488

Esse foi o procedimento, que um dos Devs passou para ele:

Boa tarde ,
Precisa atualizar o banco de dados, vá em Sistema -> Atualizações -> Atualizar Banco de Dados...
Sua coluna garantia e status não foram criadas.

Verifique no repositório
https://github.com/RamonSilva20/mapos/blob/master/updates/update_4.45.0_to_4.46.0.sql


SE FUNCIONAR, MARCAR COMO RESOLVIDO, boa sorte :)

**Comment by CarlosCavalcante87** [comment]
Comigo só resolveu importando o banco de dados que vem na pasta mapos master.
