### ISSUE TITLE
Problema ao instalar a nova versão

### ISSUE THREAD

**Issue by MrKadu** [RamonSilva20/mapos#251]
Estou fazendo a instalação do sistema mapos via easy php tive um problema que ele não reconhece o banco de dados e quando tento instalar ele manualmente fica sempre entrando direto na parte de instalar e dando a mensagem que  o programa ja foi instalado

**Comment by RamonSilva20** [comment]
Olá @MrKadu. Altere no arquivo index.php o environment para uma das opções abaixo.

Opções:
- development
- testing
- production

index.php - linha 59 -> define('ENVIRONMENT', 'pre_installation');
