### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by rodolfocarlosbji** [RamonSilva20/mapos#2517]
Olá bom dia a todos, uso a versão antiga em uma hospedagem antiga tambem não tenho problema, porem fui reinstalar em uma hospedagem nova não consigo iniciar o sistema, já fiz a instalação porem a pagina principal aparece um erro:

Esta página não está funcionando
xxxxxxxxxxxxxxxx não consegue atender a esta solicitação no momento.
HTTP ERROR 500

alguem sabe como arrumar ? desde já obrigado pela atenção de todos.

**Comment by cabralwms** [comment]
Qual hospedagem? Você instalou a verão 4.47.0 baixada do github? Precisaria de mais detalhes para tentar te ajudar.

**Comment by rodolfocarlosbji** [comment]
> Qual hospedagem? Você instalou no verão 4.47.0 baixada do github? Precisaria de mais detalhes para tentar te ajudar.

Amigo, isso mesmo instalei essa versão 4.47.0 
minha hospedagem é linux da locaweb
php 8.1

**Comment by cabralwms** [comment]
Requisitos para o funcionamento do Mapos é PHP8.2 ou superior.

**Comment by rodolfocarlosbji** [comment]
> Os requisitos para o funcionamento do Mapos são PHP8.2 ou superior.

já tentei mudar para 8.2 e 8.3 tambem não abre.. fica a tela branca com esse erro ai

**Comment by cabralwms** [comment]
Faz mais uma tentativa dessa forma que vou te passar.
Baixa esse pacote completo para hospedagem. https://www.firewarrior.com.br/nextcloud/index.php/s/37gz5eo6GiPcQHq

Depois copie e cole o arquivo application/.env-examplo então renomeie ele para .env dentro da pasta application

Ai vai até a pagina web e faça a instalação padrão. sem usar o comando composer install --no-dev que nesse pacote para hospedagem já tem tudo que precisa. 

E avisa se deu certo aqui depois ok. Qualquer coisa chama no zap 011 99369-8430

**Comment by cabralwms** [comment]
qualquer coisa tambem entra nesse grupo o pessoal te ajuda https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

**Comment by rodolfocarlosbji** [comment]
ta joia, vou entrar no grupo, se nao conseguir vou te incomodar no zap ai rsrsrsr, baixei esse do link que você me passou pelo menos mudou a tela agora... 
![image](https://github.com/user-attachments/assets/4b63f52c-3987-451a-9a10-31c785d2f7fa)


só que nao caiu na tela de login deu esse erro..

**Comment by barretowiisk** [comment]
@rodolfocarlosbji 
O erro está ocorrendo pois dentre as versões v3.35 e v3.40 houve mudanças na criptografia das senhas dos usuários e clientes. Então, recomendo a atualização da versão de forma adequada.

Precisa de suporte especializado para o MAP-OS?
Entre em contato com nosso time de suporte e obtenha a solução desejada.

SYSGO - Parceria Oficial do Projeto MAP-OS
https://sysgo.com.br/mapos-github
