### ISSUE TITLE
Erro ao gerar relatórios

### ISSUE THREAD

**Issue by fabianocruzdf** [RamonSilva20/mapos#252]
Qualquer relatório está devolvendo o seguinte erro:

"An uncaught Exception was encountered
Type: MpdfException

Message: Word is too long to fit in table -

Filename: /application/helpers/mpdf/mpdf.php

Line Number: 21887"

Estou utilizando a versão 3.1.15.

**Comment by RamonSilva20** [comment]
Qualquer relatório, ou somente os de ordem de serviço que geralmente tem texto longo?

**Comment by fabianocruzdf** [comment]
> Qualquer relatório, ou somente os de ordem de serviço que geralmente tem texto longo?

Qualquer relatório @RamonSilva20 !

**Comment by omeggawebsolucoes** [comment]
Tenho o mesmo problema , nao aparece nenhum tipo de relatorio!
o q pode ser @RamonSilva20 ????
