### ISSUE TITLE
mudar o ip/localhost da aplicação (solved)

### ISSUE THREAD

**Issue by kaoprado** [RamonSilva20/mapos#2520]
** Descreva o bug **
não posso utilizar localhost na rede, pois tenho outros apps rodando via localhost, por default coloquei o ip (http://192.168.1.20/mapos), porém preciso trocar esse IP, qual arquivo de configuração considigo alterar o base_path?

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
redirecionamento inapropriado

** Desktop (preencha as seguintes informações): **
 - SO: ubuntu 
 - Navegador todos
 - Versão 22.04

** Contexto adicional **
preciso saber qual arquivo troco o base_path.

**Comment by cabralwms** [comment]
Opa meu amigo blz? Então se vc estiver utilizando o mapos mais atual, 4.47.0 o arquivo que precisa alterar é o application/.env. Se estiver usando abaixo da versão 4.45.0 então o arquivo fica em application/config/config.php

**Comment by kaoprado** [comment]
Obrigado @cabralwms , encontrei e funcionou perfeitamente! Grande abraço.

**Comment by cabralwms** [comment]
De nada meu amigo. Finaliza o Issue como resolvida se puder
