### ISSUE TITLE
Imagem para os produtos

### ISSUE THREAD

**Issue by edmarcos1972** [RamonSilva20/mapos#2529]
Boa tarde.
Já foi considerado a possibilidade da adição de imagem ao cadastro de produtos. Creio que seja um recurso interessante.

**Comment by barretowiisk** [comment]
Boa tarde @edmarcos1972 
Já sim, mas não teria utilidade em outras telas, pois o sistema não possui um PDV por exemplo.

Caso deseja uma personalização em seu projeto, pode contar com a SYSGO, assim poderá customizar conforma sua necessidade.
https://sysgo.com.br/mapos
