### ISSUE TITLE
Sugestão de Termos de Garantia

### ISSUE THREAD

**Issue by MrKadu** [RamonSilva20/mapos#253]
Boa tarde queria sugerir  uma função de termo de garantia onde você pode já deixa um texto explicando a garantia e quando for imprimir já sair junto, eu uso o sistema minha assistência técnica de informatica e  recebi essa sugestão de um cliente agora atarde. Obrigado pela atenção parabéns ao desenvolvedor do projeto muito bom mesmo.

**Comment by willph** [comment]
O termo de garantia ficaria melhor em **configurações** ou um Menu próprio?

**Comment by MrKadu** [comment]
bom no meu caso seria apenas uma opção mais seria bacana ter varias opções

**Comment by edgarmeireles** [comment]
Para mim isso é essencial... Tenho alguns clientes que usam o MAPOS, toda vez que implanto um novo cliente ou algum deles me pede alguma alteração, preciso editar o código fonte da impressão e depois upar o arquivo para o FTP. Isso diretamente no sistema, irá facilitar muiiiiiiito... pois o próprio cliente pode fazer as alterações que ele quer.

**Comment by willph** [comment]
Em desenvolvimento.

Espero em breve fazer um pull request do que fiz.

**Comment by bernardoari** [comment]
Boa tarde,
alguém conseguiu adicionar o termo de garantia ?

**Comment by willph** [comment]
Pull Request enviado, aguardar aprovação para finalização (#request_feature)

**Comment by marcosaquino34** [comment]
acho seria é necessário conter o dados do cliente e do aparelho na parte de imprimir para o termo  de garantia ser valido!
