### ISSUE TITLE
🐛 Bug: Cálculo da margem de lucro do produto gerando valores incorretos

### ISSUE THREAD

**Issue by sidneyferracinjr** [RamonSilva20/mapos#2532]
**Descrição do bug**

Se o valor da porcentagem da margem do lucro no campo "Margem" for maior que 99, o campo "Preço de Venda" gera valores incorretos.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Navegue até Produto > Adicionar Produto
2. Preencha os campos, incluindo o campo "Margem"
3. Observe o valor apresentado pelo campo "Preço de Venda"

**Comportamento esperado**
O preço de venda deve ser calculado corretamente em um valor apresentável e coerente.

**Capturas de tela**

![Imagem do WhatsApp de 2024-08-12 à(s) 11 45 38_f06b0aff](https://github.com/user-attachments/assets/7e7f3420-8e4f-42c2-9013-2c284531e385)

![Imagem do WhatsApp de 2024-08-12 à(s) 11 45 22_66981b20](https://github.com/user-attachments/assets/5ab3ab0c-f195-4eea-8ac0-3d26660122b1)

![Imagem do WhatsApp de 2024-08-12 à(s) 11 46 34_e6fa09e7](https://github.com/user-attachments/assets/caf5f813-86b2-4bee-b2fd-6ee23bc58eb2)

![image](https://github.com/user-attachments/assets/3ec36433-781b-4c0e-8b3a-9bea761a4b9c)

**Contexto adicional**
Em 12/08/2024 o erro foi reportado por diversos usuários no grupo Map-OS(Geral).

**Comment by Marc3lo-sa** [comment]
Lancei a proposta de modificação, só aguardar.

**Comment by rodrigomilitao** [comment]
Já foi resolvido esse né? Apliquei as alterações e aqui deram certo 😁👍
