### ISSUE TITLE
Erro ao criar cliente na Asaas

### ISSUE THREAD

**Issue by AcessoHAG** [RamonSilva20/mapos#2536]
Erro ao gerar cobrança boleto
![Captura de tela 2024-08-19 195446](https://github.com/user-attachments/assets/40b3f6bd-7d64-4605-ab6e-3aa7a20f2910)

**Comment by Marc3lo-sa** [comment]
Certamente é por conta no novo endereço da API, conforme comunicações da ASAAS: Exemplo prático:

Como era: https://asaas.com/api/v3/payments 

Como será:  https://api.asaas.com/v3/payments/

**Comment by willph** [comment]
Atualizado a dependência do Asaas.

Precisa atualizar seu codigo **composer.json** e **compose.lock** 
Caso não queira atualizar as outras alterações feita.

Roda o comando `composer install --no-dev` novamente
