### ISSUE TITLE
aplicativo celular

### ISSUE THREAD

**Issue by tombeira** [RamonSilva20/mapos#2538]
ola onde encontro o app para celular para baixar?

**Comment by AcessoHAG** [comment]
Não precisa de app, o sistema é responsivo ou seja, pode abrir direto no navegador do celular que funciona direitinho, aí dá pra criar um atalho direto pro link do sistema na opção adicionar a tela inicial

**Comment by Pr3d4dor** [comment]
O sistema é responsivo como @AcessoHAG comentou, mas temos o aplicativo oficial também: https://play.google.com/store/apps/details?id=br.com.mapos.os.mapos_app

**Comment by lucaspaulino** [comment]
@Pr3d4dor a fonte do app é liberado? Onde posso baixar?

**Comment by SamuelPietro** [comment]
> @Pr3d4dora fonte do app está liberada? Onde posso baixar?

https://github.com/map-os/map-os-app-flutter
