### ISSUE TITLE
erro ao editar informação do usuario

### ISSUE THREAD

**Issue by PROJETO158** [RamonSilva20/mapos#2539]
Erro ao editar o usuario para adicionar os campos CPF e RG.
os que mostram na imagem a baixo são os que o site gerou automaticamente.
![image](https://github.com/user-attachments/assets/5213e2cb-5866-4ff9-940a-80bfdbab6bef)

**Comment by soarespaullo** [comment]
Olá, bom dia!

Se essas informações forem do usuários Administrador, você não consegue mudar se for assim;
```
UPDATE `usuarios` SET `cpf` = "000.000.000.00" WHERE idUsuarios = 2;
```
Espero que tenha ajudado.

Att;
Paulo

**Comment by PROJETO158** [comment]
no caso, onde que seria digitado isso ??

**Comment by soarespaullo** [comment]
Você usa em Windows ou Linux?

**Comment by PROJETO158** [comment]
> Você usa em Windows ou Linux?

o site fica e um pc com linux

**Comment by soarespaullo** [comment]
Então você pode abrir o terminal do Linux e entrar no seu banco de dados.

sudo mysql -uroot -pSenha_do_Banco

Se não souber os comandos eu te passo.

**Comment by PROJETO158** [comment]
> Então você pode abrir o terminal do Linux e entrar no seu banco de dados.
> 
> sudo mysql -uroot -pSenha_do_Banco
> 
> Se não souber os comandos eu te passo.

agradeço se puder passar, linux eu não entendo por completo não

**Comment by soarespaullo** [comment]
Claro!
Segue...

1º sudo mysql -uroot -p sua_senha
2º SHOW databases;
3º USE seuBanco
4º SHOW tables;
5º SELECT * FROM usuarios;
6º UPDATE `usuarios` SET `cpf` = "000.000.000.00" WHERE idUsuarios = 1;

OBS, faça um backup antes de mexer/fazer alguma alteração.

**Comment by cabralwms** [comment]
Acessa via phpmyadmin que fica mais facil e então vc conseguirá alterar os dados.

**Comment by barretowiisk** [comment]
@PROJETO158 
Se as respostas aqui já te ajudaram, retorna o Feedback e encerra a ISSUE por gentileza, não é um bug é uma regra do sistema.
