### ISSUE TITLE
Erro ao excluir anexos

### ISSUE THREAD

**Issue by Claudiomfa** [RamonSilva20/mapos#254]
não é possível excluir anexos das ordens de serviço.

fica sempre com a barra azul e não apaga o ficheiro

**Comment by Claudiomfa** [comment]
Já resolvi o problema

**Comment by brtechst** [comment]
Como resolveu? Estou precisando tbm!

**Comment by brtechst** [comment]
Desde lá ainda não resolvi kk, se puder ajudar como foi tbm estou precisando.
