### ISSUE TITLE
Erro ao excluir cobrança

### ISSUE THREAD

**Issue by Ghuvieira** [RamonSilva20/mapos#2545]
A cobrança foi cancelada normalmente mas dá erro ao tentar excluir.
no status da cobrança diz o seguinte: "O pagamento foi cancelado por uma das partes ou porque o prazo para pagamento expirou"

a mensagem de erro é: "bad_request: status attribute can't be null"

o gateway de pagamento que usei foi o MercadoPago, lá na conta aparece que foi cancelado certinho.
![image](https://github.com/user-attachments/assets/e857d992-12b9-4f69-8707-e4738267006d)

**Comment by barretowiisk** [comment]
Boa tarde,
Consegue verificar no banco de dados como está relacionado esse boleto?
O boleto foi cancelado via MAP-OS ou via MP?
Interessante ver no lado do Mercado Pago o Status do Boleto.

Cuidado com dados sensíveis ao enviar print ou a tabela do banco de dados.

**Comment by Ghuvieira** [comment]
Opa, boa noite, o boleto foi cancelado pelo MAP-OS, assim que deu o erro quando fui excluir a cobrança, já estava aparecendo como cancelada no MAP-OS, eu fui lá na conta do MP e estava cancelado sem nenhum problema, eu exportei a linha do banco de dados, as informações são as seguintes:
o estranho é que no status está "cancelled" e no erro diz que o status não pode ser null
![image](https://github.com/user-attachments/assets/50631de0-3909-46c7-91a5-e23e1164e8fe)

**Comment by barretowiisk** [comment]
O que podes fazer é deletar esse boleto diretamente no banco de dados, mas é uma causa interessante de se avaliar, assim que eu tiver um tempo dou uma olhada nas regras pra ver se identifico a causa.
Olha no MP se está cancelado pra não ter problemas e mata no banco de dados por hora.

**Comment by Ghuvieira** [comment]
beleza, vou apagar a linha no banco de dados então, agradeço pela atenção, abraço.

**Comment by soarespaullo** [comment]
> O que podes fazer é deletar esse boleto diretamente no banco de dados, mas é uma causa interessante de se avaliar, assim que eu tiver um tempo dou uma olhada nas regras pra ver se identifico a causa. Olha no MP se está cancelado pra não ter problemas e mata no banco de dados por hora.
> 
> Fala que o Status atribuído não pode ser nulo, acho que o problema pode ser na controller.

Olá, bom dia! 
O meu fez isso uma vez, aí tive que fazer a exclusão pelo banco de dados.

**Comment by cabralwms** [comment]
Quando vc quiser excluir o boleto, não cancele ele. Vá direto em Excluir que ele será excluido e cancelado. Se vc cancelar a api da esse erro mesmo, pq não pode excluir um boleto que não existe, no caso cancelado.

**Comment by barretowiisk** [comment]
@Ghuvieira 
Recomendo que encerre essa thread, pois sua solicitação já foi atendida e resolvida, lidar com transações externas tem desses bugs kkkks
