### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by markozandrade** [RamonSilva20/mapos#2546]
Error thrown with message "Call to a member function result() on bool"

Stacktrace:
#3 Error in /home3/mdhost/gm.mdhosting.com.br/application/models/Mapos_model.php:207
#2 Mapos_model:getVendasStatus in /home3/mdhost/gm.mdhosting.com.br/application/controllers/Mapos.php:14
#1 Mapos:index in /home3/mdhost/gm.mdhosting.com.br/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:533
#0 require_once in /home3/mdhost/gm.mdhosting.com.br/index.php:316
![Captura de tela 2024-09-06 155004](https://github.com/user-attachments/assets/fd81a5b5-d5bb-4758-9059-3448e311382a)

**Comment by markozandrade** [comment]
Caros se vocês poder me ajudar com esse erro, fico muito grato a todos.

**Comment by cabralwms** [comment]
Você precisa atualizar o banco de dados, para não dar esse erro, você está atualizando o mapos antigo para mais novo correto? vai no final do seu link mesmo com erro não sai da pagina, apóis index coloque isso index.php/mapos/configurar
então vá em atualização, clica em atualizar banco de dados,

**Comment by markozandrade** [comment]
Deu certo, muito obrigado.

**Comment by markozandrade** [comment]
Caros boa noite a todos, estou com novo erro: Whoops\Exception\ErrorException thrown with message "Undefined array key 2"

Stacktrace:
#4 Whoops\Exception\ErrorException in /home3/mdhost/gm.mdhosting.com.br/application/controllers/Arquivos.php:45
#3 Whoops\Run:handleError in /home3/mdhost/gm.mdhosting.com.br/application/controllers/Arquivos.php:45
#2 Arquivos:gerenciar in /home3/mdhost/gm.mdhosting.com.br/application/controllers/Arquivos.php:19
#1 Arquivos:index in /home3/mdhost/gm.mdhosting.com.br/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:533
#0 require_once in /home3/mdhost/gm.mdhosting.com.br/index.php:316
![Captura de tela 2024-09-11 222137](https://github.com/user-attachments/assets/73eebe5a-3935-48fc-ab25-17f7ee2c019b)
