### ISSUE TITLE
Pagamento parcelado, escolher intervalo de datas

### ISSUE THREAD

**Issue by AcessoHAG** [RamonSilva20/mapos#2547]
Onde modifico para escolher o intervalo paga data base do parcelamento, tipo colocar a cada 15 dias em vez de 30.
Já consigo faturar direntamente o pacelamento na tela de vendas em vez de ter que ir para lançamentos.
![Captura de tela 2024-09-09 223219](https://github.com/user-attachments/assets/a413bd5d-a88c-4882-be54-1b1e8440067c)

**Comment by barretowiisk** [comment]
Infelizmente, é algo ainda em correção... (que possível não ocorrerá no CI3 -  papo que se tornará publico em breve).
Nesse cenário, não existe o faturamento é avista, para parcelar, você pode colocar os STATUS em FATURADO e depois em lançamentos você pode lançar a venda manualmente parcelando.
Obs: O mesmo ocorre para OS.

Se precisa de ajuda com desenvolvimento e melhorias, recomendamos a SYSGO parceira oficial do projeto.
