### ISSUE TITLE
Adicionar itens, tanto na parte de material, quanto na de serviço sem ter cadastrado

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#2550]
Seria possível deixar aberto sem escolha de itens cadastrado nos campos de serviço e produtos dentro da ordem de serviço?

**Comment by barretowiisk** [comment]
Não sei se entendi Carlos, mas acredito que deseja inserir produtos sem a necessidade de registrar em Produtos, é possível criar uma tabela e tratar essa relação entre as duas tabelas.
Sinceramente, vejo como útil, mas não seria muito legal na forma em que o MAP-OS foi construído, talvez uma inserção simplificada seria o ideal, exemplo, caso não exista o produto ser inserido como um novo produto, porém vejo alguns problemas de gestão nesse cenário, por exemplo, você não faria inserção de valor de compra, margem ou estoque, o que poderia causar falsos alertas de estoque baixo ou conflitos em relatórios.

Acredito que possamos pensar em algo mais funcional, nesse segundo cenário de cadastro rápido, dado valores pre-determinados, mas vejo que uma digitação errada já iria criar um novo produto por engano kkkkkks

**Comment by CarlosRezini** [comment]
@barretowiisk Vou dar exemplo do meu caso, trabalho com prestação de serviços, uso o sistema para gerir datas das prestações dos serviços e fluxo de caixa, dificilmente uso estoque de produtos. Eu faço o seguinte, mando a relação de material para meu fornecedor e coloco como "Material" e coloco o valor que deu. Eu pensei nesse campo como por exemplo, se eu tiver isso que sobrou de uma obra e ja colocar no orçamento entende sem a necessidade de colocar algo la cadastrado

**Comment by CarlosRezini** [comment]
Outra questão, teria como trocar na base do sistema o nome do arquivo que envio via PDF para os clientes, hoje vai salvo assim "MAP-OS - XX - CLIENTE

**Comment by barretowiisk** [comment]
Entendi completamente, mas como falei, a estrutura do projeto não comportaria muito bem isso, de toda forma. Recomendo que procure um desenvolver para atender a sua necessidade, e recomendamos  fortemente a SYSGO que é a parceira do MAP-OS.

É possível fazer essa alteração na controller do projeto, recomendo que chame o APP_NAME, é o campo contido em Configurações -> Sistema -> Gerais -> Nome do Sistema, dessa forma fixando sem problemas.

SYSGO
https://sysgo.com.br/mapos
