### ISSUE TITLE
Erro ao incluir despesa no sistema

### ISSUE THREAD

**Issue by Nettinho12** [RamonSilva20/mapos#2551]
Estou utilizando a versão 4.44.0, e até o presente momento, todas as funcionalidades estão ok, exceto a inclusão de despesas. O que acontece? Faço o cadastro da despesa manual, assim como o de receita normalmente, ele mostra a mensagem que foi feito o lançamento, mas a despesa não aparece no relatório. Alguém poderia me ajudar com isso?

**Comment by barretowiisk** [comment]
Recomendo que atualize para a versão 4.47.0, muitos ajustes foram realizados, não sei se no seu caso resolverá, mas esse bug não diz respeito a ultima versão do sistema, então não podemos considerar como um relato de BUG válido.
