### ISSUE TITLE
Dois URL do servidor

### ISSUE THREAD

**Issue by CarlosRezini** [RamonSilva20/mapos#2553]
Gostaria de saber se seria possivel ter dois links para acesso do sistema, um que eu tenho acesso local e outro eu tenho acesso remoto via VPN
![LINKS](https://github.com/user-attachments/assets/95028880-187d-4a81-b229-971b02e42562)

**Comment by gleissonneves** [comment]
@CarlosRezini tenta usar environments no teu projeto, creio que vai ajudar.


Eu não entendi o cenário mas você tbm pode usar a função de captura de ip do php para setar dinamicamente.
