### ISSUE TITLE
Ajuda para alterar o Caminho dos LOGOS no arquivos gerado para imprimir em A4 - nao puxa o logo

### ISSUE THREAD

**Issue by Michelrochag** [RamonSilva20/mapos#2554]
Boa tarde, comecei a utilizar o sistema Mapos recentemente, e resolvi fazer um teste hospedando ele para que eu possa utilizar ele externamente, e após isso, na hora de gerar a impressão A4, ele não traz a imagem do logo, eu gostaria de saber onde fica o .php que gera a impressão para alterar o caminho até a imagem que esta agora dentro da assets/img, segue uma imagem do que eu preciso alterar.

![image](https://github.com/user-attachments/assets/1baebf53-5806-4139-baea-1784aeae6284)

no caso acima, eu mandei inspecionar, e alterei manualmente para ele puxar o logo da pasta e poder imprimir para o cliente., mas estou fazendo isso manualmente sempre, gostaria de deixar ja fixado o caminho onde ele puxa.

Grato.

**Comment by Michelrochag** [comment]
CONSEGUI DESCOBRIR O QUE ERA, DESCULPE O TRABALHO! GRATO!

**Comment by Jonathaf94** [comment]
E o que era amigo? Estou com um problema semelhante.
