### ISSUE TITLE
Erro ao cadastrar cliente

### ISSUE THREAD

**Issue by DisneyMjr** [RamonSilva20/mapos#2557]
Whoops \ Exception \ ErrorException (E_WARNING)
Attempt to read property "nome" on null

**Comment by DisneyMjr** [comment]
Whoops \ Exception \ ErrorException (E_WARNING)
Attempt to read property "url_logo" on null

**Comment by barretowiisk** [comment]
Possivelmente você não cadastrou o Emitente, pois quando o cliente se cadastra é disparado um e-mail (mesmo se a função não esteja configurada ou ativa), por causa disso ele retorna que a url_logo é igual a null (nulo).

**Comment by DisneyMjr** [comment]
foi isso mesmo.
Outra coisa, configurei o email direto no php, mas não está enviando

**Comment by barretowiisk** [comment]
Precisa configurar uma CRON (Linux) ou Agendador de Tarefas (Windows) para executar o comando PHP process e retry para que o e-mail seja disparado, apenas o clique não ativa o disparo.

Lembrando que instalação local só recomendamos para uso de teste, o ideal é hospedar e pra isso indico a SysGO, parceira oficial do projeto, onde poderá acessar de qualquer dispositivo e ainda atem suporte dedicado ao projeto, e também você ajuda o projeto.
