### ISSUE TITLE
"Saldo" cliente

### ISSUE THREAD

**Issue by Vitalexus** [RamonSilva20/mapos#256]
Tenho um pequeno negócio de engomadoria e seria muito útil que este script pudesse ajudar-me com a questão que passo a descrever.
Um cliente compra e paga um serviço por um determinado valor que é um pack de engomadoria por exemplo, um pacote de 100 peças que ele vai gastando quando quiser.
Seria bom se as ordens de serviço do mapos pudessem ser utilizadas para o consumo das peças ou seja, um cliente tem um saldo de 30 peças, hoje vai á engomadoria levar 10 peças, regista-se a entrega com a emissão da ordem de serviço e o sistema reduziria o saldo de peças deste cliente para 20.
Espero ter sido claro com esta questão.

Desde já muito obrigado.

**Comment by MrKadu** [comment]
Muito bom essa sua ideia para aprimorar ainda poderia ter um campo proprio para colocar a função com outros nomes tipo creditos etc
