### ISSUE TITLE
finalizei a instalação automatica  e apareceu o erro 

### ISSUE THREAD

**Issue by gauchoriosul** [RamonSilva20/mapos#2563]
Fatal error: Uncaught Error: Class "Dotenv\Dotenv" not found in C:\xampp\htdocs\mapos\index.php:68 Stack trace: #0 {main} thrown in C:\xampp\htdocs\mapos\index.php on line 68

![Uploading Screenshot_1.png…]()

**Comment by cabralwms** [comment]
Não da para ver o print do erro. Como está seu ambiente, parece ser windows com xampp correto? manda o print para ver melhor e tentar te ajudar.

**Comment by gauchoriosul** [comment]
Fatal error: Uncaught Error: Class "Dotenv\Dotenv" not found in C:\xampp\htdocs\mapos\index.php:68 Stack trace: #0 {main} thrown in C:\xampp\htdocs\mapos\index.php on line 68 quando termino de configurar ele aparece essa linha

**Comment by Pr3d4dor** [comment]
Faltou rodar composer install

**Comment by barretowiisk** [comment]
Feche o script e execute novamente, com isso ele vai executar o que faltar para sanar o erro.
