### ISSUE TITLE
Problema ao configurar o Map-OS na rede

### ISSUE THREAD

**Issue by Edielson2013** [RamonSilva20/mapos#2565]
Boa tarde.. tudo bem?
Fiz a instalação manual, numa maquina virtual com o Windows server 2019
segui o passo a passo de instalação e configurei os endereços e editei os txt's porem apenas consigo acesso ao dashboard do xampp
e quando mudo o final do endereço para o nome da pasta do mapos 
ela da erro e o endereço muda exemplo eu digito:
http://192.168.4.142:8888/mapos
da erro e retorna 
localhost/master/index.php/login

Alguem poderia me ajudar por favor

![Captura de tela 2024-10-16 141523](https://github.com/user-attachments/assets/cdcb16bf-4c6e-4645-bf1f-0eb81b77ddd9)
![Captura de tela 2024-10-16 141617](https://github.com/user-attachments/assets/d70812c1-2762-41dd-b714-f6a45a623ef1)

**Comment by mvstec** [comment]
desariva o firewall do Windows

**Comment by Edielson2013** [comment]
eu reinstalei em uma maquina física fiz o procedimento e agora não funciona nem na mesma :)
e continua mudando o endereço: digito http://192.168.4.140:83/dashboard/  dou enter e ele vira localhost/mapos/index.php/login

![Captura de tela 2024-10-16 141528](https://github.com/user-attachments/assets/ffc7db21-bb0e-49bb-a773-1dccf2fd9c85)
![Captura de tela 2024-10-16 155808](https://github.com/user-attachments/assets/1252ea22-01d8-4e68-b311-ff0ca0622d3f)
![Captura de tela 2024-10-16 155837](https://github.com/user-attachments/assets/c0489f1f-0a87-4d9e-9b55-c903314c3002)
![Captura de tela 2024-10-16 155942](https://github.com/user-attachments/assets/531a9b8f-e4dd-4386-8cc9-1bb7d8a1a307)
![Captura de tela 2024-10-16 160025](https://github.com/user-attachments/assets/7aa2b6c2-40a3-4ac6-a3c2-3ea559acdc9f)

**Comment by mvstec** [comment]
tira a porta da configuração , deixa só x.x.x.x./mapos

**Comment by Marc3lo-sa** [comment]
obs. não mexa no arquivo config.php 
retorne os valores padrão: $config['base_url'] = $_ENV['APP_BASEURL'] ?? 'http://localhost:8000/';

a configuração deve ser feita no arquivo .env

**Comment by Edielson2013** [comment]
Gostaria de Agradecer a todos pela força...Em especial o @Marc3lo-sa  realmente o erro estava em editar o arquivo config.php ao invés do .env, os tutoriais que vi mandavam editar o arquivo errado.
Deus abençoe a todos.

**Comment by Marc3lo-sa** [comment]
A grande recomensa em trabalhar com projetos de codigo aberto, é a satisfação em ajudar e ser ajudado ...vlw @Edielson2013
