### ISSUE TITLE
Previsão de Lançamento da Versão 4.0

### ISSUE THREAD

**Issue by gueeme** [RamonSilva20/mapos#257]
Bom dia Ramon,

Você tem alguma previsão de quando será finalizada a versão 4.0?
Fiz a instalação dele porém os módulos "Vendas e Financeiro / Lançamentos" não estão funcionando. Retorna o erro em anexo.
Esses módulos já foram finalizados ou é alguma falha no sistema mesmo?

![2019-01-17 11_08_32-error](https://user-images.githubusercontent.com/19538568/51320857-4b9c1b00-1a48-11e9-8b02-ca4e9dea0009.png)

**Comment by RamonSilva20** [comment]
Olá @gueeme. Sem previsão, não estou tendo tempo disponível para finalizar a versão 4. 
Esse erro está ocorrendo nos cadastros que não foram alterados ainda.

**Comment by Aksz** [comment]
> Olá @gueeme. Sem previsão, não estou tendo tempo disponível para finalizar a versão 4.
> Esse erro está ocorrendo nos cadastros que não foram alterados ainda.

Vou baixar e dar uma olhada ve se atualizo algumas coisas com base no que você ja atualizou

**Comment by bernardoari** [comment]
alguem tem a versão 4 funcionando pelo menos cadastros de os, clientes, produtos ?
obrigado

**Comment by Marcosaquino32** [comment]
Preciso acrescentar alguns campo no cadastro da ordem de serviço, alguém poderia mim ajudar??
