### ISSUE TITLE
Ajuda, Negar edição após venda faturada Map-os

### ISSUE THREAD

**Issue by Edielson2013** [RamonSilva20/mapos#2573]
Olá boa tarde pessoal, sou eu de novo :)
Teria uma forma do vendedor não editar a venda após faturada?
Eu desativei a função, porem mesmo assim o vendedor consegue editar após faturado...
o vendedor tem a permissão de editar a venda, pois se ela estiver desativada ele não consegue adicionar produtos
creio que após faturada não se deve mexer na venda. estou certo ?
Desde já muito obrigado a todos pelo apoio.
![1](https://github.com/user-attachments/assets/6a191aa0-0ffa-4bf3-a521-1ee9603ce707)
![2](https://github.com/user-attachments/assets/4139b745-29da-497c-9f67-094648affd02)

**Comment by Edielson2013** [comment]
Na verdade em O.S também, porem eu removi a função faturar da barra de status pois usamos as O.S's para controle interno

**Comment by Edielson2013** [comment]
> Verifiquei aqui e é apenas em Vendas que está ocorrendo isso né?

Na verdade em OS também, porem eu removi a função faturar da barra de status pois usamos as OS's para controle interno

**Comment by barretowiisk** [comment]
Você precisa desativar a função nas configurações do sistema.
Configurações -> Sistema -> Financeiro -> Controle de edição de Vendas

**Comment by Edielson2013** [comment]
> Você precisa desativar a função nas configurações do sistema. Configurações -> Sistema -> Financeiro -> Controle de edição de Vendas

Quando faço isso o vendedor não consegue adicionar os produtos na hora da venda, ele clica em adicionar produtos e uma mensagem aparece dizendo que ele não tem permissão para editar a venda.

**Comment by Edielson2013** [comment]
> Você precisa desativar a função nas configurações do sistema. Configurações -> Sistema -> Financeiro -> Controle de edição de Vendas

Olá boa tarde. como eu disse mesmo fazendo isso ele consegue editar a venda faturada.

**Comment by barretowiisk** [comment]
@Edielson2013 
Será corrigido em breve, o @cabralwms está ajustando isso e vai subir essa correção para o projeto.

@cabralwms Quando subir atrela essa ISSUE por favor.

**Comment by barretowiisk** [comment]
@Edielson2013 
Essa opção de foto não está dentro do planos do projeto, se quiser podemos desenvolver para você, entra em contato com a SYSGO para verificar essa possibilidade.

https://SysGO.com.br/

**Comment by cabralwms** [comment]
Feitas as correções e melhorias nesse sentido, se puder testar e dar um retorno. 
https://github.com/RamonSilva20/mapos/pull/2581

**Comment by Edielson2013** [comment]
> Feitas as correções e melhorias nesse sentido agora quando a venda estiver faturada so será permitido editar ou atualizar se permitir nas configurações. se puder testar e dar um retorno. #2581

@cabralwms 
Bom dia amigo, irei adicionar hoje e darei o feedback aqui. 
@cabralwms preciso muito entrar em contato com você para saber se é possível uma alteração no meu map-os e se o vc tem disponibilidade para fazer esses serviços 
obrigado,o sistema é bom e vocês são d+

**Comment by cabralwms** [comment]
Se quiser pode chamar no zap 11 99369-8430

**Comment by Edielson2013** [comment]
@cabralwms 
Bom dia fiz as alterações que me mandou deu tudo certo, obrigado a você e a todos da comunidade que são muito solícitos e gentis.
