### ISSUE TITLE
Inclusão de Status

### ISSUE THREAD

**Issue by DisneyMjr** [RamonSilva20/mapos#2575]
Tentei de todo jeito mas nem alterando o BD funciona.
Podia ter uma opção de inserir ou alterar os status de os.

**Comment by barretowiisk** [comment]
Status é adicionado mas páginas de View em que é utilizado, não no banco de dados, e a categoria é bug e não feature.

**Comment by DisneyMjr** [comment]
Entendo, mas queria mesmo uma request de colocar campo de inserção de status sem ter que precisar alterar nas views

**Comment by barretowiisk** [comment]
@DisneyMjr 
Podemos desenvolver conforme a sua necessidade, é só entrar em contato com a SYSGO para viabilizar o desenvolvimento.

https://sysgo.com.br/mapos
