### ISSUE TITLE
Dificuldades em instalar o Mapos. Erro composer 

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#2579]
![image](https://github.com/user-attachments/assets/0063c34e-f902-4647-b38f-8cd5ff280351)

Boa tarde;
Estou tendo problemas ao instalar o comporser. 
baixei o xampp https://sourceforge.net/projects/xampp/files/XAMPP Windows/8.2.12/xampp-windows-x64-8.2.12-0-VS16-installer.exe
baixei o composer https://getcomposer.org/Composer-Setup.exe

clinco na pasta e executo na raiz  e nao passa dai. Achei que poderia ser algo com alguma atualizacao do composer, pois a ultima  2.8.2 dia 29/10.
Alguem tem alguma ideia se e eu que estou errando ou um bug mesmo?
obrigado

**Comment by fwsund** [comment]
Uso Hospedagem, preciso dos arquivos.
A instalação automatica pensei comigo... vou instalar com ela e pegar os arquivos dentro do xampp... mas la tambem nao esta os arquivos baixados, somente a pasta do git.

**Comment by Edielson2013** [comment]
@fwsund 
Bom dia, abra Xampp em Apache click em config depois click em php.ini
localize as extensões GD e ZIP  remova o símbolo   ;  (dois pontos)
 estou mandando um link ao final caso não consiga fazer seguindo os prints.
 espero que consiga resolver o problema. 
![image](https://github.com/user-attachments/assets/b4103548-a4db-4797-aee8-cc616a3cd79e)
![image](https://github.com/user-attachments/assets/623b6d70-2fcf-4db4-b4df-8c09e7a99afb)


https://www.youtube.com/watch?v=2Q-zdlu_biw

**Comment by fwsund** [comment]
> você deve ativar as extenções "GD" e "ZIP" no seu php.ini apos isso restart o apache ou o serviço do php dependendo do seu caso. Dessa forma conseguirá executar o composer install

Obrigado, deu certinho... muita coisa mudou no mapos desdo meu update [sarkozin](https://github.com/sarkozin)

**Comment by fwsund** [comment]
> Edielson2013

Obrigado, fui no chatgpt pra descobrir onde mudava kkkkk, mais deu certinho. obrigado
