### ISSUE TITLE
Addicionar codigo para nova coluna na database

### ISSUE THREAD

**Issue by Claudiomfa** [RamonSilva20/mapos#258]
Alguém me consegue explicar como posso adicionar o código para ir buscar uma nova coluna na base de dados?

Queria duplicar o campo de técnico para dois técnicos. usuarios_id e tecnico_id

já adicionei a coluna na database mas não sei onde colocar nos ficheiros para poder alterar, gravar e ler

**Comment by Claudiomfa** [comment]
Obrigado @KokeroO mas eu já consegui fazer o que queria. Agora só ando às voltas com uma cena na área de cliente. Não consigo que o cliente consiga gravar alguns campos que adicionei na conecte/detalhes_Os.php.

Coloco a seguir uma imagem do que alterei: 
A vermelho - os campos que preciso para que os clientes possam alterar
A verde - o botão para poderem gravar as alterações.
![sem titulo](https://user-images.githubusercontent.com/27887277/51447565-766fc300-1d17-11e9-913d-757cb5f2b29c.png)


O ficheiro detalhes_Os.php
[detalhes_os.zip](https://github.com/RamonSilva20/mapos/files/2777233/detalhes_os.zip)

**Comment by KokeroO** [comment]
Você deve receber os valores destes campo no controller correspondente e passar os valores para o método correspondente a atualização. Também certificar que também criou as colunas correspondentes aos valores que serão enviados. Não e somente criar o campo do lado do cliente.

**Comment by Claudiomfa** [comment]
@KokeroO Eu ja criei as colunas na base de dados. Estão todas a funcionar na area do tecnico. Só não consigo por o botão gravar a funcionar. 

Como posso adicionar os valores no ficheiro controllers/mine.php. É que não sei como adicionar esses valores

**Comment by heliocristaldo** [comment]
Claudio bom ainda não tentei mexer na parte do cliente, mas uma coisa que já tentei e não deu certo é o cliente conseguir pesquisar itens na tabela produtos, da mesma forma que o administrador consegue pesquisar na tela os. vou fazer uns testes e deixar, tentou verificar na pasta config, o arquivo form_validation.php, algumas tabelas costuma só funcionar só se estiver citada nesse arquivo.
