### ISSUE TITLE
Suporte ao Novo Padrão de CNPJ Alfanumérico

### ISSUE THREAD

**Issue by SamuelPietro** [RamonSilva20/mapos#2587]
Com as recentes mudanças no padrão de CNPJ brasileiro para um formato alfanumérico, proponho a implementação do suporte a esse novo formato de CNPJ no projeto. Para facilitar essa implementação, sugiro o uso da biblioteca **[CNPJUtils](https://github.com/SamuelPietro/CNPJUtils)**, que desenvolvi em PHP para realizar operações como cálculo dos dígitos verificadores, validação e geração de CNPJ no novo padrão. Abaixo, destaco as principais funcionalidades da biblioteca, que pode ser diretamente integrada ao **[mapos](https://github.com/RamonSilva20/mapos)**.

**Funcionalidades do CNPJUtils**:

- **Geração de CNPJ**: Cria CNPJs aleatórios para testes e preenchimentos automáticos.
- **Cálculo de Dígito Verificador (DV)**: Gera os dois dígitos verificadores para um CNPJ, assegurando conformidade com o novo padrão.
- **Validação de CNPJ**: Verifica se um CNPJ segue o novo padrão e possui os dígitos verificadores corretos.
- **Interface Web e Suporte AJAX**: Facilita a interação para usuários não técnicos.
- **Execução via Terminal**: Permite operações de geração e validação por linha de comando, útil para automações.

**Estrutura do Projeto**:

O projeto segue uma estrutura modular para fácil integração com navegadores, AJAX e terminal, incluindo:

- Interface web (HTML/CSS/JavaScript) para geração e validação.
- Classe `CNPJ.php` para lógica de validação e geração.
- Script `terminal.php` para operações via linha de comando.

**Direitos e Licença de Uso**:

Estou cedendo integralmente os direitos de uso e licença para o projeto **mapos** reutilizar o código e expandir suas funcionalidades para o novo padrão de CNPJ.

Agradeço a atenção e fico à disposição para qualquer dúvida sobre a integração!

**Link do Repositório**: [CNPJUtils no GitHub](https://github.com/SamuelPietro/CNPJUtils)

**Comment by Pr3d4dor** [comment]
@SamuelPietro Se quiser mandar uma PR no repositório do mapos.

**Comment by willph** [comment]
@SamuelPietro se quiser entra no grupo map-os 

https://chat.whatsapp.com/D571nPLqNq6JgIsmL6Gucl

**Comment by SamuelPietro** [comment]
Olá senhores, estive bastante atarefado nestes ultimos dias e não consegui responder antes, será uma honra aplicar essa funcionalidade ao MapOs, em breve subirei o PR.

Infelizmente não consigo, neste momento, dar uma previsão de data devido há algumas situações em meu atual trabalho, mas em breve retornarei com isto também!
