### ISSUE TITLE
Erro ao importar base da V4.42.0 para V4.47.0

### ISSUE THREAD

**Issue by jsfachini** [RamonSilva20/mapos#2589]
Instalação limpa, somente importado a base da v4.42 para a atual.
Testes também atualizando por dentro do mapos, mesmo error.
![2024-11-07_18h43_39](https://github.com/user-attachments/assets/e8b1c193-e7b8-4023-9737-f50f6b087880)

**Comment by cabralwms** [comment]
Bom dia, para vc conseguir atualizar precisa rodar o atualizar banco de dados, apos esse erro, nao sai do link, vai na barra de endereço. final dela deve estar https://www.seudominio.com.br/mapos/ ai vc coloca no final https://www.seudominio.com.br/mapos/mapos/configurar. então vai até atualizar e atualiza o banco de dados.
