### ISSUE TITLE
Tradução e validação

### ISSUE THREAD

**Issue by rafaeldefazio** [RamonSilva20/mapos#259]
Olá!

Faltam traduções, ou pelo menos configurações, nos models, para pt-br. Seguem imagens:

---

## Antes...
![errado](https://user-images.githubusercontent.com/4692521/51551089-e59f0180-1e54-11e9-8118-dd74c021ec55.png)

## Possível solução...
![codigo](https://user-images.githubusercontent.com/4692521/51551101-e8015b80-1e54-11e9-8a31-c6d059d58649.png)

`$this->config->set_item('language', $lang);`

## Depois...
![edicao](https://user-images.githubusercontent.com/4692521/51551104-e9328880-1e54-11e9-84d4-767c49dceac9.png)

---

Não tenho experiência em Codeigniter. Seria caso de um pull request?

Além disso, as validações de CPF/CNPJ e telefone deixam passar caracteres.

Valeu!

**Comment by KokeroO** [comment]
A linha 84 do arquivo Application/config/config.php deve ser configurado da seguinte forma: 

> $config['language']     = 'pr-br';
