### ISSUE TITLE
Bug do arquivo .env Vulnerabilidade de Divulgação de Senha do Servidor

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#2590]
Boa tarde
Fiz a isntalacao do mapos na sua ultima versao, ocorreu tudo bem, nao notei nenum problemadurante a instalacao do mesmo na Hostiger. Ja usava uma versao mais antiga e resolvi testar esta nova. Entao criei um novo banco de dados zerado, em fim , tudo ficou bem e funcionava bem. Porem ao entrar no arquivo config.php para mudar o local de instalacao, no meu caso fiz em maposnew e depois de testar tudo ficou ok, entao troquei para mapos e renomei no filezila a pasta, simplismente caia e nada que fazia dava certo. Porem pra minha surpresa encontrei com arquivo no  application/config chamado **.env** e **.env.example**, e este e o problema, se vou no navegar digito meu endereco /mapos/application/.env, olha ai as senhas todas expostas, creio que algo deu errado durante a instalacao, porque dei uma olhada em outras instalacoes e nao havia este arquivo, porem quando renomeio ele o sistema para de funcionar. 
![Sem títulgho](https://github.com/user-attachments/assets/bf5d0988-1b8f-491f-9133-1abbff51e5e7)
 Alguem podereia me dar uma ajuda para corrigir isso?

**Comment by willph** [comment]
Olá se tiver acesso ao .htaccess teste coloca o seguinte codigo

```
<FilesMatch "^\.env$">
    Order allow,deny
    Deny from all
</FilesMatch>
```
e nos diga se conseguiu resolver ok

**Comment by fwsund** [comment]
Boa tarde,
eu avia coloquei o codigo na raiz do /application, mais ai fiz como no projeto e coloquei na raiz /mapos. Obrigado
O que faço a respeito do arquivo config.php? Pois por algum motivo que ainda nao descobri, os emails nao estao saindo do mapos, ficam com o status enviando, e foi por isso que achei este erro la no .env

**Comment by willph** [comment]
O arquivo config.php tem que ser mantido da forma original do projeto.

Todos os dados são inseridos no arquivo env, não sendo mais necessário editar o config.php

**Comment by fwsund** [comment]
Poderia so me dar um norte a respeito dos emails, eles ficam com status "enviando"  já configurei no mapos e no cron, mais nao estao saindo do mapos.

**Comment by willph** [comment]
Você precisa colocar o caminho completo para o script.


Exemplo Fictício: /home/ubuntu/htdocs/public/index.php

Análise sua cron e veja se está o caminho completo.
