### ISSUE TITLE
Adicionar campo ao cadastro de produto

### ISSUE THREAD

**Issue by vp15353** [RamonSilva20/mapos#26]
Tentei adicionar um campo ao cadastro de produto e estou com problemas, eis o que eu fiz:

1- Criei a coluna no banco de dados

2- Editei o arquivo na pasta views/adicionarProduto (não editei o editar nem visualizar ainda, apenas após o adicionar funcionar, creio que isso seja ok?) - Verifiquei que na pagina de adicionar produto o campo já apareceu porém ainda sem adicionar nada ao banco de dados , a entrada fica como Null porém tudo funcionando.

3-Editei o arquivo em controllers/produtos.php e adicionei o field que eu criei nos arrays data. Todo o site fica funcional exceto ao tentar adicionar o produto onde ao clicar no botão retorna o seguinte erro:

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/gasil915/public_html/estoque/application/controllers/produtos.php:1)

Filename: libraries/Session.php

Line Number: 675

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/gasil915/public_html/estoque/application/controllers/produtos.php:1)

Filename: helpers/url_helper.php

Line Number: 542

Porém o registro foi adicionado ao campo de dados, porém o meu campo ainda não recebe o valor, antes recebia NULL, agora recebe o valor 0.

4 - Fui editar então o arquivo models porém não achei nada que fosse necessário alterar, continuo com o erro acima e sem conseugir adicionar os dados do novo campo, poderiam me ajudar?

**Comment by EngMarcioBispo** [comment]
Boa noite, alguém já conseguiu adicionar um novo campo no formulário de abertura da ordem de serviço. Já consegui fazer o front end porém o back end não recebe as informações adicionando no campo criado, adicionei todos os campo na tabela do banco e adicionei as tags no código, porém, a tabela não recebe as informações dos novos campos. Alguém poderia me dá uma dica ficarei muito grato!

**Comment by Pr3d4dor** [comment]
@EngMarcioBispo Qual seria o problema exatamente?

**Comment by EngMarcioBispo** [comment]
![Screenshot_20210928-224110](https://user-images.githubusercontent.com/91513221/135188794-543f1ee3-8063-4d90-8896-e4af1d133ac0.png)
Boa noite, como havia informado, consegui adicionar alguns campos na página, porém, os campos extras não consegue enviar para o banco as informações.

**Comment by celorp-jpg** [comment]
@Pr3d4dor precisa adicionar 2 campos novos na aba ordem de serviço para adicionar texto que saísse na impressão térmica, consegue me ajudar com isso?

**Comment by Pr3d4dor** [comment]
@celorp-jpg Pede ajuda no grupo do whats: https://chat.whatsapp.com/GVSg8tPQzXy0grfYpRfQps
