### ISSUE TITLE
Erro ao atualizar o sistema pelas configurações do sistema menu atualizações

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#2600]
** Descreva o bug **
Sistema recém instalado na versão 4.48, verifiquei que foram feitas novas pequenas correções e fui tentar atualizar pelo menu de atualização dentro do proprio mapos, mais está dando erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...' Menu de configurações do Sistema
2. Clique em '....' Atualizações
3. Role para baixo até '....' Clique em atualizar mapos
4. Ver erro

**Comportamento esperado**
Das outras vezes que utilizei a função o sistema se atulializa e é mostrada uma mensagem de sucesso.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Chrome
 - Versão 131.0.6778.86
![erro_mapos_4 48](https://github.com/user-attachments/assets/c1b04f42-1d89-4f0c-90ee-ad9cf2fc4d0e)

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by SOROInfo** [comment]
Problema foi resolvido com a ajuda do Cabralwms

**Comment by xCoronelMakerx** [comment]
Estou com o mesmo problema, exatamente o mesmo problema, alguem poderia me orientar?
