### ISSUE TITLE
Relatórios Customizáveis

### ISSUE THREAD

**Issue by Hidrobr** [RamonSilva20/mapos#262]
(Relatórios  - Ordem de Serviços - Relatórios Customizáveis- STATUS : esta faltando o campo do faturado.
Exemplo: tenho que tirar um relatório de um determinado cliente, mas quero saber dos serviços já faturados que foram emitidos Nota fiscal por outro sistema.
Só falta o campo de Buscar por ordem Faturadas. 👍

**Comment by KokeroO** [comment]
Olá você ta pedindo uma implementação ou ajuda para adicionar esse filtro?

**Comment by Hidrobr** [comment]
> Olá você ta pedindo uma implementação ou ajuda para adicionar esse filtro?

Caso possa ajudar a adicionar sou novo com programação.
agradeço

**Comment by KokeroO** [comment]
Algumas tabelas não fazem parte do mapos 3, somente existe a estrutura, provavelmente estaram no mapos 4.

**Comment by Hidrobr** [comment]
> Algumas tabelas não fazem parte do mapos 3, somente existe a estrutura, provavelmente estaram no mapos 4.

Como faço para fazer o filtro?

**Comment by Hidrobr** [comment]
Achei o local para criar o filtro. /application/views/relatorios/rel_os.php.
<option value="Faturado">Faturado</option>
Agora esta faltando buscar esse filtro dentro de ordem de serviço, não achei o local para a impressão.

**Comment by Hidrobr** [comment]
Resolvido ; Obrigado.
