### ISSUE TITLE
Limitação de caracteres

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#263]
Primeiramente, quero deixar o meu "Muito obrigado" a todos os desenvolvedores.

Tenho usado e personalizado o sistema MAPOS, porém tenho tido alguma dificuldade devido á limitação de caracteres, principalmente nos campos de "telefone" e "celular". Muitas vezes preciso colocar mais de 02 números de telefones, além dos nomes dos responsáveis para contato. acaba que não cabe tudo e tenho usado o campo de Observações na O.S. para isso, mas no meu caso ainda não é o ideal.

Ficaria perfeito (para a minha necessidade), se o campo dos telefones fosse ilimitada a quantidade de caracteres, pois é muito limitado. Alguém poderia me dar uma ajuda nisso? Onde posso alterar essa limitação de caracteres?

**Comment by KokeroO** [comment]
No banco de dados o campo telefone e do tipo varchar e tem limitação de 20 caracteres. Somente alterar a quantidade de caracteres da coluna no banco para o tanto que achar necessário.

**Comment by maycon1977** [comment]
> No banco de dados o campo telefone e do tipo varchar e tem limitação de 20 caracteres. Somente alterar a quantidade de caracteres da coluna no banco para o tanto que achar necessário.

Cara... Muito obrigado. Vai me ajudar muito isso aí. Ficou perfeito (por enquanto). HEHE.
