### ISSUE TITLE
Tentando trocar de branch e dá erro

### ISSUE THREAD

**Issue by mvnp** [RamonSilva20/mapos#265]
Ao finalizar o clone do projeto e instalá-lo, eu tento acessar a branch mapos4 com "git checkout mapos4" e ocorre erro.

λ git checkout mapos4
Error: Your local changes to the following files would be overwritten by checkout:
        CHANGELOG.md
Please commit your changes or stash them before you switch branches.
Aborting

Alguém me ajuda a resolver?

Obrigado.

**Comment by Pr3d4dor** [comment]
Você fez alguma alteração no arquivo CHANGELOG.md.

Rode o comando git checkout CHANGELOG.md.

Após isso você poderá mudar de branch.
