### ISSUE TITLE
campo valor no corpo onde adiciona os

### ISSUE THREAD

**Issue by aportetecnologia** [RamonSilva20/mapos#266]
prezados como adicionar o campo valortotal na grade onde fica as os. do lado do campo status.

**Comment by BESystemInfo** [comment]
Estou com a mesma dúvida. Aqui só aparece o valor total na página de OS quando a mesma está Faturada. Se alguém tiver sugestões, ficaria grato.

**Comment by aportetecnologia** [comment]
Ola pessoal eu implementei realmente aparecer somente quando ela esta faturada. sera implementado no futuro para todo o tipo de OS.
