### ISSUE TITLE
Venda do sistema no Mercado Livre???

### ISSUE THREAD

**Issue by willph** [RamonSilva20/mapos#268]
Gostaria de saber se estão se aproveitando e vendendo o Sistema MapOS no Mercado Livre?

Ramon da uma verificada, lá no site, por que se realmente for verdade é uma baita sacanagem?

Usando termo de pesquisa.

https://lista.mercadolivre.com.br/ordem-de-servi%C3%A7o-em-php-e-mysql#D[A:ordem%20de%20servi%C3%A7o%20em%20php%20e%20mysql]

ou

https://lista.mercadolivre.com.br/ordem-de-servi%C3%A7o-responsivo-android-script-em-php-e-mysql#D[A:%20Ordem%20De%20Servi%C3%A7o%20Responsivo%20Android%20Script%20Em%20Php%20E%20Mysql]

**Comment by vitolike** [comment]
Sempre quando vejo eu denunció

**Comment by willph** [comment]
> 
> 
> Sempre quando vejo eu denunció

Pelo que pude ver tem vários vendendo, se eu não estiver enganado, a maioria é o MapOS, apenas modificado, retirando o Logo.

**Comment by KokeroO** [comment]
Com certeza vendem. E com certeza e ele. Já até já tem nomeado como versão 4. Não sei se o Ramon liga muito não. Já cheguei até comentar com ele sobre comercialização, e ele foi bem tranquilo a quanto isso.

**Comment by Pr3d4dor** [comment]
Como o sistema usa a licença MIT ele pode ser comercializado livremente.

Do ponto moral realmente não é certo, pois estão estão se aproveitando do trabalho de outras pessoas.

**Comment by willph** [comment]
> 
> 
> Como o sistema usa a licença MIT ele pode ser comercializado livremente.
> 
> Do ponto moral realmente não é certo, pois estão estão se aproveitando do trabalho de outras pessoas.

Então se esta permitido na licença, não tem muito o que dizer então.
Mas bem que poderiam repassar parte do dinheiro para apoiar o projeto (*caso não repassem), já ajudava.

**Comment by vinnyparker** [comment]
Ola todo mundo! Pelo q vejo, esta sob licença MIT. Logo, pode ser comercializado a migué (como se diz aqui em salvador) e do ponto de vista legal, nem deveria ser denunciado pq a pessoa esta coberta legalmente.

**Comment by vinnyparker** [comment]
a licença permissao de usar, copiar, modificar, publicar, distribuir, sublicenciar e/ou vender copias do softeare...............

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

**Comment by willph** [comment]
Resumindo, isso é questão superada. Quem quiser deixar mais alguma consideração, pode deixar, porem irei fechar esse issues de 16h.
Se esta sob licença MIT, não muito o que dizer.

**Comment by KokeroO** [comment]
Ressalvando que precisa constar o nome do desenvolvedor. Mais como disse acima, conversando com o Ramon, ele é bem tranquilo a quanto a isso, e poderia até remover se atrapalhar a comercialização.

**Comment by vinnyparker** [comment]
Mas eu acredito q tem. Eu comprei o mapos la. E no codigo vi q tinha aqui no github. Hoje eu nao utilizo. Mas  respeitei a licenca.
