### ISSUE TITLE
Mudar Descrição de Status das O.S.

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#269]
Olá...
Conto mais uma vez com as dicas dos Gurus para personalizar o MAPOS.

Gostaria de alterar os Status das O.S. para nomes que combinassem mais com os que adotamos aqui na empresa, mas já tentei achar onde modificar isso e até agora não consegui.

![status-os](https://user-images.githubusercontent.com/47214174/52922063-9d142000-32fc-11e9-99e2-2c5c7b2ffd69.jpg)

Exemplo:
Onde lê-se "ORÇAMENTO" gostaria de substituir por "A ORÇAR"
Onde lê-se "ABERTO" gostaria de substituir por "A AUTORIZAR"
Onde lê-se "CANCELADO" gostaria de substituir por "NÃO AUTORIZADO"
Onde lê-se "EM ANDAMENTO" gostaria de substituir por "AUTORIZADO"
Onde lê-se "FATURADO" gostaria de substituir por "A ENTREGAR/RECEBER"
Onde lê-se "FINALIZADO" gostaria de substituir por "CONCLUÍDO"

É somente uma facilidade para entendimento melhor mesmo aqui na empresa.

Alguma luz?

**Comment by Aksz** [comment]
> Olá...
> Conto mais uma vez com as dicas dos Gurus para personalizar o MAPOS.
> 
> Gostaria de alterar os Status das O.S. para nomes que combinassem mais com os que adotamos aqui na empresa, mas já tentei achar onde modificar isso e até agora não consegui.
> 
> ![status-os](https://user-images.githubusercontent.com/47214174/52922063-9d142000-32fc-11e9-99e2-2c5c7b2ffd69.jpg)
> 
> Exemplo:
> Onde lê-se "ORÇAMENTO" gostaria de substituir por "A ORÇAR"
> Onde lê-se "ABERTO" gostaria de substituir por "A AUTORIZAR"
> Onde lê-se "CANCELADO" gostaria de substituir por "NÃO AUTORIZADO"
> Onde lê-se "EM ANDAMENTO" gostaria de substituir por "AUTORIZADO"
> Onde lê-se "FATURADO" gostaria de substituir por "A ENTREGAR/RECEBER"
> Onde lê-se "FINALIZADO" gostaria de substituir por "CONCLUÍDO"
> 
> É somente uma facilidade para entendimento melhor mesmo aqui na empresa.
> 
> Alguma luz?

Em adicionarOS.php da pasta views tem os valores dentro do option.

```
  <select class="span12" name="status" id="status" value="">
                                                <option value="Orçamento">Orçamento</option>
                                                <option value="Aberto">Aberto</option>
                                                <option value="Em Andamento">Em Andamento</option>
                                                <option value="Finalizado">Finalizado</option>
                                                <option value="Cancelado">Cancelado</option>
                                            </select>
```

Terá de alterar, e os outros arquivos dentro da pasta views OS também tera de alterar, se não me engano deve haver outros para se trocarem..

**Comment by maycon1977** [comment]
> 
> Em adicionarOS.php da pasta views tem os valores dentro do option.
> 
> ```
>   <select class="span12" name="status" id="status" value="">
>                                                 <option value="Orçamento">Orçamento</option>
>                                                 <option value="Aberto">Aberto</option>
>                                                 <option value="Em Andamento">Em Andamento</option>
>                                                 <option value="Finalizado">Finalizado</option>
>                                                 <option value="Cancelado">Cancelado</option>
>                                             </select>
> ```
> Terá de alterar, e os outros arquivos dentro da pasta views OS também tera de alterar, se não me engano deve haver outros para se trocarem..

Opa. Já tentei fazer isso e não rolou...
Acredito que existem outros arquivos a serem modificados mesmo.
Obrigado mesmo assim!

**Comment by Aksz** [comment]
> > Em adicionarOS.php da pasta views tem os valores dentro do option.
> > ```
> >   <select class="span12" name="status" id="status" value="">
> >                                                 <option value="Orçamento">Orçamento</option>
> >                                                 <option value="Aberto">Aberto</option>
> >                                                 <option value="Em Andamento">Em Andamento</option>
> >                                                 <option value="Finalizado">Finalizado</option>
> >                                                 <option value="Cancelado">Cancelado</option>
> >                                             </select>
> > ```
> > Terá de alterar, e os outros arquivos dentro da pasta views OS também tera de alterar, se não me engano deve haver outros para se trocarem..
> 
> Opa. Já tentei fazer isso e não rolou...
> Acredito que existem outros arquivos a serem modificados mesmo.
> Obrigado mesmo assim!

Pois então, em adicionaros.php, os value são adicionados no banco de dados, mude e verifique se ao adicionar ele será adicionado no banco de dados conforme você mudou, na pasta views da OS tem as descrições e as cores que aparecem também os status da OS.

**Comment by vaidamerda** [comment]
Olá, eu consegui alterar e incluir também outros status, os arquivos que editei são;
adicionarOs.php, editarOs.php, os.php esses 3 estão na pasta application/views/os
e o arquivo rel_os.php na pasta application/views/relatorios

vc altera ou copia uma linha e muda o nome do status para criar outra ok 
abs.

**Comment by maycon1977** [comment]
> Olá, eu consegui alterar e incluir também outros status, os arquivos que editei são;
> adicionarOs.php, editarOs.php, os.php esses 3 estão na pasta application/views/os
> e o arquivo rel_os.php na pasta application/views/relatorios
> 
> vc altera ou copia uma linha e muda o nome do status para criar outra ok
> abs.

Vou tentar aqui e volto pra avisar se deu certo.
Muito obrigado!

**Comment by maycon1977** [comment]
> Olá, eu consegui alterar e incluir também outros status, os arquivos que editei são;
> adicionarOs.php, editarOs.php, os.php esses 3 estão na pasta application/views/os
> e o arquivo rel_os.php na pasta application/views/relatorios
> 
> vc altera ou copia uma linha e muda o nome do status para criar outra ok
> abs.

Então.. Isso eu já fiz, porém ainda assim nessa planilha não consigo mudar a descrição. Continua igual!

![image](https://user-images.githubusercontent.com/47214174/53523358-5c19c980-3abb-11e9-862d-1cd9d29b186d.png)

**Comment by vaidamerda** [comment]
em qual link vc abre essa planilha?

**Comment by aportetecnologia** [comment]
AMIGO tem que criar uma funcion para isso estou lancando uma versao nova com algumas modificacoes

**Comment by aportetecnologia** [comment]
dentro do arquivo mapos/models/Mapos_model.php
criar a funcao abaixo da funcao function getOsAbertas
function getOsAguardandoPecas()
    {
        $this->db->select('os.*, clientes.nomeCliente');
        $this->db->from('os');
        $this->db->join('clientes', 'clientes.idClientes = os.clientes_id');
        $this->db->where('os.status', 'Aguardando Peças');
        $this->db->limit(10);
        return $this->db->get()->result();
ai sim vc conseguirar fazer o que vc quer.

**Comment by Aksz** [comment]
> > Olá, eu consegui alterar e incluir também outros status, os arquivos que editei são;
> > adicionarOs.php, editarOs.php, os.php esses 3 estão na pasta application/views/os
> > e o arquivo rel_os.php na pasta application/views/relatorios
> > vc altera ou copia uma linha e muda o nome do status para criar outra ok
> > abs.
> 
> Então.. Isso eu já fiz...
> 
> ![image](https://user-images.githubusercontent.com/47214174/53523470-a307bf00-3abb-11e9-9bd9-38d42cd1ecda.png)
> 
> Porém ainda assim nessa planilha não consigo mudar a descrição. Continua igual!
> 
> ![image](https://user-images.githubusercontent.com/47214174/53523358-5c19c980-3abb-11e9-862d-1cd9d29b186d.png)

Então meu amigo, você só vai conseguir mudar das que já tinham no banco direto no banco de dados, nas demais tem que fazer as devidas modificações nos values que insere na db
