### ISSUE TITLE
[ Bug ] Visualização de Produtos

### ISSUE THREAD

**Issue by admkakaroto** [RamonSilva20/mapos#27]
Primeiro de tudo, parabéns pelo excelente software.

Existe um bug no sistema de visualização de produtos após uma busca.
Para reproduzir ele é bem simples.

1. Cadastre seus produtor normalmente.
2. Faça a busca por algum produto de forma genérica, ou seja, digitando apenas parte do nome dele.
3. Veja que na lista de produtos que será exibida, não é possível visualizar nem editar os mesmos, mesmo tendo o botão você não consegue clicar neles corretamente.

**Comment by michelfritsch** [comment]
Aqui na Versão 2.6.3 funciona normalmente.
Persquisar... "parte do produto"
Editar Ok
Visualizar Ok
Tentou em outro navegador?

**Comment by admkakaroto** [comment]
Testei no Chrome, vou testar no Mozila.

**Comment by drelldeveloper** [comment]
Olá @admkakaroto Eu realizei os procedimentos que você disse no Firefox. Está tudo okay.
