### ISSUE TITLE
Bug ao abrir a tela da OS

### ISSUE THREAD

**Issue by Warley12** [RamonSilva20/mapos#272]
Quando abro a tela de adicionar a os, aparece um erro 

A PHP Error was encountered
Severity: Compile Error

Message: Cannot redeclare p() (previously declared in C:\wamp64\www\mapos-master\application\helpers\util_helper.php:3)

Filename: helpers/codegen_helper.php

Line Number: 14

**Comment by maycon1977** [comment]
Você fez alguma alteração no sistema antes de acontecer o erro?

**Comment by Warley12** [comment]
Havia atualizado para a versão 4
