### ISSUE TITLE
Para remover campo obrigatório

### ISSUE THREAD

**Issue by rikardferreira** [RamonSilva20/mapos#273]
Para remover ou adicionar um campo obrigatório basta ir mapos/application/config/form_validation.php

Não esquecer que também é preciso editar mapos/application/views/"pagina que quer remover, exempo: editarOs.php"
Dentro de cada pagina é preciso também remover a linha do campo
Exemplo:
Antes

      $("#formOs").validate({
          rules:{
             cliente: {required:true},
             tecnico: {required:true},
             marcaEqui: {required:true},
             modeloEqui: {required:true},
             defeito: {required:true},
             observacoes: {required:true},
             dataInicial: {required:true}
            
             
             
          },
          messages:{
             cliente: {required: 'Campo Obrigatório.'},
             tecnico: {required: 'Campo Obrigatório.'},
             marcaEqui: {required: 'Campo Obrigatório.'},
             modeloEqui: {required: 'Campo Obrigatório.'},
             defeito: {required: 'Campo Obrigatório.'},
             observacoes: {required: 'Campo Obrigatório.'},
             dataInicial: {required: 'Campo Obrigatório.'}
             
          },
Depois

      $("#formOs").validate({
          rules:{
             cliente: {required:true},
             tecnico: {required:true},
             marcaEqui: {required:true},
             modeloEqui: {required:true},
             defeito: {required:true},
             
             dataInicial: {required:true}
            
             
             
          },
          messages:{
             cliente: {required: 'Campo Obrigatório.'},
             tecnico: {required: 'Campo Obrigatório.'},
             marcaEqui: {required: 'Campo Obrigatório.'},
             modeloEqui: {required: 'Campo Obrigatório.'},
             defeito: {required: 'Campo Obrigatório.'},
             
             dataInicial: {required: 'Campo Obrigatório.'}
             
          },

**Comment by maycon1977** [comment]
Vou tentar aqui. Valeu!

**Comment by edgarmunin** [comment]
Meu problema está no campo Expira em* no cadastro de usuários. 
Mesmo colocando a data correta, quando tento salvar as informações ele dá um erro. 
![mapos-Expira em*](https://user-images.githubusercontent.com/37554262/54390523-6f16c700-4681-11e9-9123-4e352c7f26c7.png)

Consigo resolver da mesma forma que está acima?

**Comment by lagethomas** [comment]
Tem como mandar um print dos campos preenchidos para ver como estão?

ENTRA Qui no grupo, mais fácil de falarmos.

https://t.me/joinchat/EfJSyUXAYkyxLzZHKgGJ3w

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qui, 14 de mar de 2019 17:49, 3dg4r <notifications@github.com> escreveu:
