### ISSUE TITLE
Ajuda para implementação de idéia de links

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#274]
Olá. Conto mais uma vez com a ajuda de vocês.
Ao entrar nos Lançamentos nos é mostrada uma lista dos serviços faturados.
Pensei que seria bem interessante podermos clicar no campo do cliente e dali já sermos direcionados diretamente para o cadastro dele, dessa forma podemos verificar as O.S. que geraram o lançamento no financeiro.

![link-01](https://user-images.githubusercontent.com/47214174/53488553-69a86280-3a6d-11e9-99a9-a3ac2262a864.jpg)
![link-02](https://user-images.githubusercontent.com/47214174/53488554-69a86280-3a6d-11e9-9948-39ee13d28070.jpg)

Dessa forma, ficaria mais fácil para cobrarmos o cliente que está devendo.
Alguém consegue dar uma luz?

**Comment by maycon1977** [comment]
Acredito que dentro do "lancamentos.php", eu deva modificar a linha:

`echo '<td>'.$r->cliente_fornecedor.'</td>';` para algo como:

`echo '<td><A HREF="CADASTRO CLIENTE">'.$r->cliente_fornecedor.'</A></td>';`

porém não sei como fazer buscar o cliente...

**Comment by lagethomas** [comment]
Bom dia, eu acredito que tenha que puxar o id do cliente quando clicar no
nome

echo '<td><A HREF="cliente">'.$r-idCliente.'</A></td>';

Para ele sempre abrir o cadastro do cliente que está na os

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------




Em qua, 27 de fev de 2019 09:04, maycon1977 <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Realmente é uma boa idéia.

Vou fazer essa implementação e disponibilizar para todos quando eu tiver um tempo.

**Comment by maycon1977** [comment]
> '.$r-idCliente.'

Tentei:

`echo '<td><A HREF="'.$r-idCliente.'">'.$r->cliente_fornecedor.'</A></td>';`

e deu:

![link-03](https://user-images.githubusercontent.com/47214174/53495395-a892e400-3a7e-11e9-955a-df85e145451a.jpg)

Tá faltando alguma coisa, pois além de aparecer parte do código lá em cima, a linha debaixo da tabela "pulou uma coluna"

**Comment by lagethomas** [comment]
Depois vou tentar, e que tô vendo ko cel kk aí saiu errado.
Estamos com um grupo no whats, algumas pessoas e estamos implementando
coisas nele, já colocamos algumas funcionalidades. Se quiser entrar lá e
ajudar a galera a customizar. Add aí.
12991264149

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qua, 27 de fev de 2019 10:59, maycon1977 <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
As customizações que não forem muito específicas e forem úteis a várias pessoas vocês poderiam fazer PR's para serem feitas o merge na master e ficarem disponíveis a todos.

**Comment by lagethomas** [comment]
Vamos fazer isso, tudo o que fizemos, hoje vamos lançar para a galera usar
também, estamos terminando de documentar e testar.

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qua, 27 de fev de 2019 11:31, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by maycon1977** [comment]
> As customizações que não forem muito específicas e forem úteis a várias pessoas vocês poderiam fazer PR's para serem feitas o merge na master e ficarem disponíveis a todos.

Não sou programador, somente fuçador mesmo... Vou trabalhando no esquema tentativa e erro...
Mas se alguém me ensinar como fazer "PR's" eu posso fazer sim...

**Comment by aportetecnologia** [comment]
Pr3d4dor

> As customizações que não forem muito específicas e forem úteis a várias pessoas vocês poderiam fazer PR's para serem feitas o merge na master e ficarem disponíveis a todos.

Adicionei la o pull request e alterei varias coisas conforme suas sugestoes. agora aguardando revisao e o merge.
