### ISSUE TITLE
Problemas em acessar o Mapos

### ISSUE THREAD

**Issue by felipecesarl** [RamonSilva20/mapos#276]
Boa tarde!

Ao tentar acessar o sistema Mapos o mesmo abre uma tela e informa: "Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente." Já tentei de tudo pessoal, e não sai dessa tela. Nunca acessei a tela de loguin dele. Estou usando em uma máquina virtual VMWARE Windows 7 32x. Webservice XAMPP (Localhost). Alguém pode me ajudar urgentemente? Já seguir os passos de configuração diversas vezes e nada de dá certo. Sempre cai nessa tela.

**Comment by aportetecnologia** [comment]
vc tentou instalar novamente ou vc copiou de algum lugar para outro

**Comment by felipecesarl** [comment]
Sim amigo! Tentei instalar diversas vezes. Até mudei de webService e nada! Só pra você ter ideia, até formatei outro Windows na máquina virtual mas mesmo assim não deu certo. Ao abrir o navegador e tentar acessar "localhost/mapos" o mesmo abre uma página informando que não posso reinstalar. O que eu faço?

**Comment by felipecesarl** [comment]
Se puderem me passar o passo a passo aqui me ajuda muito! Sou novo nessa área de WebService, PHP, não entendo muito. Podem me mandar pelo meu e-mail se quiserem: felipecesarl@hotmail.com

**Comment by aportetecnologia** [comment]
seguinte se vc tiver instalando veja no seu arquivo index.php o parametro esta assim
define('ENVIRONMENT', 'pre_installation'); senao mude e tente instalar

**Comment by lagethomas** [comment]
seguinte se vc tiver instalando veja no seu arquivo index.php o parametro
esta assim
define('ENVIRONMENT', 'pre_installation'); senao mude e tente instala.
Compelentando.
Mude de

define('ENVIRONMENT', 'pre_installation');
define('ENVIRONMENT', 'production');

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qui, 28 de fev de 2019 19:00, FABIO ALVES BARBOSA <
notifications@github.com> escreveu:

**Comment by felipecesarl** [comment]
Pessoal, conseguir entrar na tela de login, conforme orientação do nosso amigo Thomas. Porém está com outro problema. Não consigo logar! Tento o login padrão: admin@admin.com , senha: 123456 e não loga! Fica apenas na barra azul processando. Li sobre na internet e a galera fala que é a versão do PHP; To usando o Xampp 7.3, ja tentei voltar a versão 5 conforme o povo fala mas a 5 não abre o sistema. Como resolver isso?? Sugestões?

**Comment by felipecesarl** [comment]
![image](https://user-images.githubusercontent.com/48102338/53608575-14ba3880-3ba2-11e9-9d6c-c07d48632505.png)

**Comment by edgarmeireles** [comment]
Neste caso, ou você faz a instalação manual, ou apara tudo, extrai o arquivo do zip, cria um banco novo e faz tudo do zero com o instalador automático.

Se for fazer manualmente, roda o script abaixo no banco (confirma se as tabelas foram criadas...)
```
 INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
            (1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);
```

**Comment by diego0100** [comment]
Boa Noite, tentei instalar com assistente e manual aparece que já esta instalado fica só nessa imagem
![mapos](https://user-images.githubusercontent.com/48662728/54510121-e1f69b00-492a-11e9-9d71-bb6dfe1a38d1.PNG)

**Comment by lagethomas** [comment]
seguinte se vc tiver instalando veja no seu arquivo index.php o parametro
esta assim
define('ENVIRONMENT', 'pre_installation'); senao mude e tente instala.
Compelentando.
Mude de

define('ENVIRONMENT', 'pre_installation');
define('ENVIRONMENT', 'production');

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em seg, 18 de mar de 2019 03:07, diego0100 <notifications@github.com>
escreveu:

**Comment by williamzzz1** [comment]
o erro de carregar infinitamente não é por causa da versao php é pq você não seguiu a instrução de editar as linhas 527 e 528 do arquivo banco.sql

**Comment by borgesjsb** [comment]
Negativo colega. 
![image](https://user-images.githubusercontent.com/55168713/64661283-6cbbdc80-d41a-11e9-9164-39a48a490ecb.png)

**Comment by borgesjsb** [comment]
Negativo colega, no meu é a mesma coisa. Algo nao puxa o login e senha do banco

![image](https://user-images.githubusercontent.com/55168713/64661309-7e9d7f80-d41a-11e9-8b43-9e0dedf42186.png)

**Comment by borgesjsb** [comment]
Já editei até a senha que deve ser criptografada. [http://www.skyler.net.br/os](url)

**Comment by danidias78** [comment]
Bom dia.
Estou tentando instalar o map os em um servidor da infinityfree. Porém o map os não sai da pagina de instalação. Preencho todos os campos para o banco de dados mysql, preencho o nome do administrador, endereço de e-mail e crio a senha klico em prosseguir mas não sai da pagina de configuração.
Consegue me ajudar?
Já instalei e reinstalei o mapos e nada adiantou.
