### ISSUE TITLE
Ajuda: Status do Serviço

### ISSUE THREAD

**Issue by edgarmeireles** [RamonSilva20/mapos#278]
Galera, estou com um novo cliente que vou precisar alterar a descrição do STATUS DA OS para ajustar as necessidades dele. 
Basicamente já alterei elas no ComboBox, porém na tela "../index.php/os" não consigo alterar o status que aparece escrito no grid.

Alguém tem uma sugestão de como corrigir?

**Comment by maycon1977** [comment]
É exatamente o meu problema que ainda não consegui resolver...

Abaixo tem algumas sugestões dos amigos:

https://github.com/RamonSilva20/mapos/issues/269

**Comment by aportetecnologia** [comment]
vc quer que mude onde? aqui?
![captura de tela_20190301173559](https://user-images.githubusercontent.com/26696115/53664850-877def00-3c48-11e9-8155-8517386fe6b7.png)
![captura de tela_20190301173503](https://user-images.githubusercontent.com/26696115/53664851-877def00-3c48-11e9-8db5-5e6ccb9efbaa.png)

**Comment by maycon1977** [comment]
As outras 2 telas eu já me virei...

O que eu preciso é mudar na tela abaixo:

![image](https://user-images.githubusercontent.com/47214174/53665056-1c80e800-3c49-11e9-9d43-3fb55ae97b95.png)

**Comment by Pr3d4dor** [comment]
Pessoal o que acham de uma implementação onde os Status das ordens de serviço possam ser gerenciados?

Assim os status das OS ficariam salvos em uma tabela no banco de dados e seria possível configurar eles do jeito que fosse necessário.

**Comment by aportetecnologia** [comment]
> As outras 2 telas eu já me virei...
> 
> O que eu preciso é mudar na tela abaixo:
> 
> ![image](https://user-images.githubusercontent.com/47214174/53665056-1c80e800-3c49-11e9-9d43-3fb55ae97b95.png)
> 
> Inclusive essa opção de AGUARDANDO PEÇAS gostaria de inserir também, além da opção GARANTIA.
> 
> No meu eu não consegui dar jeito nisso. Seguem minhas telas:
> 
> ![image](https://user-images.githubusercontent.com/47214174/53665267-b2b50e00-3c49-11e9-801b-8ab403221ae9.png)
> 
> ![image](https://user-images.githubusercontent.com/47214174/53665435-30791980-3c4a-11e9-9b47-08d36409890f.png)

na versao nova que disponibilizamos hoje que é a 3.3 foi adicionado essa funcionalidade
se precisar de outras me passa que adiciono no projeto oficial 
e no painel quando tiver a opcao aguardando pecas ficara aparecendo tambem na pagina principal

**Comment by aportetecnologia** [comment]
> É exatamente o meu problema que ainda não consegui resolver...
> 
> Abaixo tem algumas sugestões dos amigos:
> 
> #269

maycon1977 baixou a versao nova? conseguiu o que queria?

**Comment by maycon1977** [comment]
> > É exatamente o meu problema que ainda não consegui resolver...
> > Abaixo tem algumas sugestões dos amigos:
> > #269
> 
> maycon1977 baixou a versao nova? conseguiu o que queria?

Opa...
Rapaz, meu pai estava internado e eu acabei não mexendo em nada na ultima semana...
Vou tentar ver aqui o que consigo fazer com as dicas de vocês.

O problema é que eu não posso baixar a versão nova porque vai sobrescrever as mudanças que já fiz na minha versão... O que tenho feito é analisar o código das mudanças que vocês fazem e implementar na minha...

No caso da dúvida desse tópico, quais arquivos eu teria que modificar?

Mais uma vez obrigado!

**Comment by vaidamerda** [comment]
> > É exatamente o meu problema que ainda não consegui resolver...
> > Abaixo tem algumas sugestões dos amigos:
> > #269
> 
> maycon1977 baixou a versao nova? conseguiu o que queria?

olá amigo eu baixei a versão 3.3 e não encontrei essa função para gerenciar os status, é essa versão mesmo que está na página principal para download?
grato

**Comment by aportetecnologia** [comment]
> > > É exatamente o meu problema que ainda não consegui resolver...
> > > Abaixo tem algumas sugestões dos amigos:
> > > #269
> > 
> > 
> > maycon1977 baixou a versao nova? conseguiu o que queria?
> 
> olá amigo eu baixei a versão 3.3 e não encontrei essa função para gerenciar os status, é essa versão mesmo que está na página principal para download?
> grato

ainda nao esta implementado na versao 3.3.
informquei que foi adicionado uma opcao a mais de Aguardando Pecas".
e que no dashboard tambem aparece ela como aguardando peas as os que estao com essa opcao.
o gerenciamento do status sera implementado fuguramente.

**Comment by maycon1977** [comment]
> o gerenciamento do status sera implementado fuguramente.

O que vc chama de gerenciamento é a tela abaixo, certo?

![image](https://user-images.githubusercontent.com/47214174/54156145-66758500-4424-11e9-9c65-58f283ca1f60.png)

Pq eu já "peguei" o esquema pra acrescentar novos Status graças a você... O que está faltando aqui pra mim é somente eles aparecerem na grade... Os meus só aparecem os nomes originais do MAPOS.

**Comment by aportetecnologia** [comment]
vc diz em qual grade? me adiciona no zap 33991077359 que te ajudo no que puder.
