### ISSUE TITLE
Botão Add Cliente ao inserir OS

### ISSUE THREAD

**Issue by edgarmeireles** [RamonSilva20/mapos#279]
Galera, basicamente todos os meus clientes usam o Mapos para assistência técnica de celular, então basicamente a cada OS criada, um novo cliente é incluído também.

Então eles ficam com 2 abas abertas, uma para incluir o cliente e outra para fazer a OS.

Estou tentando criar um botão ao lado do campo de clientes, no qual abre uma div com um iFrame para cadastrar o cliente. O problema é que estou falhando absurdamente no processo. Não tenho muita experiência com PHP, então vem daí a dificuldade... Mas vamos lá...

1 - Quando a DIV abre, não consigo carregar somente a parte de incluir o cliente, mas sim a tela do Mapos completa. **Como fazer para aparecer somente o formulário de cadastro do cliente?**
2 - Mesmo que eu inclua o cliente, precisei criar um botão para ocultar a div. **Como Fazer para ocultar a div automaticamente após finalizar o cadastro?**

Bom, estou fazendo com DIV e iFrame, se alguém souber uma solução mais fácil, me ajudaria muito.

**Comment by Pr3d4dor** [comment]
Olá, esse cadastro rápido de cliente é bem útil e creio que eu poderia fazer uma implementação genérica.

Porém creio que seria melhor utilizar uma modal para cadastrar o cliente rapidamente e não utilizar uma div com iframe. Assim no cadastro da OS pode ter um botão que ao ser clicado abre uma modal para cadastrar o cliente.

O que acha da idéia?

**Comment by aportetecnologia** [comment]
Top muito bom

**Comment by lagethomas** [comment]
Galera, vcs poderiam se juntar a nós ao grupo do WPP, estamos conversando e
fazendo essas alterações lá para depois ir lançando aqui. O que acham?

segue para quem quiser:  https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i



Atenciosamente.

Thomas Henrique Lage Marcelino
--------------------------------------------------------------------------------------------------------------
Formação acadêmica | Redes de Computadores

Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades

Instituição: Fatec Cruzeiro, Prof. Waldomiro May.

Cidade: Cachoeira Paulista - SP

Contato: (12) 99142-2467

E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com
--------------------------------------------------------------------------------------------------------------


Em sáb, 2 de mar de 2019 às 15:05, FABIO ALVES BARBOSA <
notifications@github.com> escreveu:

**Comment by felipepips** [comment]
Eu fiz isso... Nao sou programador, faço tudo na base do exemplo kkk... Peguei o exemplo de botao do "editar" que tem dentro do visualizar OS (que fica no cabeçalho, fica bonito kkk), coloquei ele na tela de inclusao de nova OS, referenciando a um novo modal (peguei o exemplo do modal do FATURAR, dentro da ediçao de OS, que abre em popup), todo o conteudo do modal vai ser o de cadastro de novo cliente... Em geral é isso, nao é dificil de fazer.
