### ISSUE TITLE
Area do cliente.

### ISSUE THREAD

**Issue by alexandresgbh** [RamonSilva20/mapos#28]
Como consigo disponibilizar para o meu cliente acessar sua informações como OS abertas e o status de cada uma?

**Comment by rafaelmarques** [comment]
Estou trabalhando nisso. Tem várias paradas para se levar em conta por questões de segurança. Estou pensando em exportar um json e consumir em um front separado. Sugestões são bem vindas.

**Comment by pedro-nunes** [comment]
poderia ser uma area simples onde o cliente usaria seu nome ou seu cpf para buscar a informação.
Aproveitando aqui, eu estou introduzindo um auto preenchimento no endereço com o cep, fica uma ajuda a mais na hora de preencher o cadastro do cliente.

**Comment by rafaelmarques** [comment]
A busca por CEP eu já implementei. https://github.com/rafaelmarques/mapos-hafael/issues/2

**Comment by alexandresgbh** [comment]
Muito legal @rafaelmarques
