### ISSUE TITLE
Unable to load the requested file: helpers/codegen_helper.php

### ISSUE THREAD

**Issue by legionariodassombras** [RamonSilva20/mapos#280]
Prezados, boa noite.
Estou tentando instalar a versão 4, mas inicialmente apareceu esse erro: Unable to load the requested file: helpers/codegen_helper.php
Segui a orientação dita aqui mas apereceu esse erro logo em seguida:

Fatal error: Cannot redeclare p() (previously declared in 
/application/helpers/util_helper.php:3) in 
/application/helpers/codegen_helper.php on line 10
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /application/helpers/codegen_helper.php:10)

Filename: core/Common.php

Line Number: 564

A PHP Error was encountered
Severity: Compile Error

Message: Cannot redeclare p() (previously declared in 
/application/helpers/util_helper.php:3)

Filename: helpers/codegen_helper.php

Line Number: 10

Alguém pode me ajudar? Por favor.

**Comment by KokeroO** [comment]
Qual versão do php?

**Comment by legionariodassombras** [comment]
7.1.13

**Comment by RamonSilva20** [comment]
O arquivo foi removido, por isso onde ainda não foi feito o refactory ocorre esse erro.

**Comment by jhantenas** [comment]
Olá, será que esse arquivo ja está disponivel, instalei aqui e esta dando o mesmo erro que o 'legionariodassom'
