### ISSUE TITLE
Acessar OS a partir de um número.

### ISSUE THREAD

**Issue by vaidamerda** [RamonSilva20/mapos#282]
Olá pessoal, gostaria de saber se é possível o cliente acessar a OS a partir de um número que poderia ser o número da fatura se possível sem precisar por o email, similar ao rastreamento de encomenda em sites como correios ou transportadora. Caso seja algo muito trabalhoso e algum colega programador possa fazer essa modificação me passe um orçamento, grato.

**Comment by Pr3d4dor** [comment]
Olá, creio que eu consigo fazer essa implementação no meu tempo livre.

Já existem inúmeras outras features para serem implementadas que foram pedidas.

**Comment by vaidamerda** [comment]
> Olá, creio que eu consigo fazer essa implementação no meu tempo livre.
> 
> Já existem inúmeras outras features para serem implementadas que foram pedidas.

opa, seria realmente show pois o sistema poderia ser adaptado para outras áreas como no meu caso que estou modificando para servir em uma transportadora onde a OS será uma (ordem de remessa) e esse número seria o código de rastreio passado direto ao cliente final. vlw
