### ISSUE TITLE
Problema Apos a Reinstalação do MOS

### ISSUE THREAD

**Issue by Hidrobr** [RamonSilva20/mapos#283]
Boa tarde. 
Pessoal, fui atualizar minha versão do Mapos, até ai tudo bem, fiz conforme tuto.:
Faça backup do banco de dados.
Remova a pasta system da instalação atual.
Copie os novos arquivos e substitua.
Execute o script update_v2_to_v3 para atualizar o banco de dados (Nenhuma informação será perdida).
Acesse o sistema com o usuário administrador utilizando a senha 123456.

Quando fui por a senha depois de radar o script não logava mais, entrei no banco alterei minha senha, mesmo assim não logou.. Fiz backup dos meu dados e dei um DEL no banco e arquivos, refiz a instalação do sistema, e quando terminei vi que mudou a background ficando branco, até ai tudo bem, quando loguei admin e senha 123456 apareceu a seguinte informação: 
{"result":true} e tudo branco.... 

e fiquei literalmente sem sistema alguém sabe como resolver ou vou ter que fazer a reinstalação do sistema antigo. "deveria ter testado em uma plataforma de test nao de produção kkkkk só chorar agora..

verifiquei que na linha de endereço esta assim: /index.php/mapos/verificarLogin , 
apaquei o verificar login ai foi para o sistema. alguém poderia dar uma luz.

**Comment by Pr3d4dor** [comment]
Boa tarde, qual a sua hospedagem, versão do PHP e versão do MySQL?

**Comment by Hidrobr** [comment]
Pacote de hospedagem | basico
-- | --
Nome do servidor | vmi179538
Versão do cPanel | 78.0 (build 16)
Versão do Apache | 2.4.38
Versão do PHP | 7.0.33
Versão do MySQL | 5.7.25
Arquitetura | x86_64
Sistema operacional | linux
Endereço IP compartilhado | 173.249.63.234
Caminho para envio de email | /usr/sbin/sendmail
Caminho para Perl | /usr/bin/perl
Versão do Perl | 5.16.3
Versão do kernel | 3.10.0-862.14.4.el7.x86_64

**Comment by Hidrobr** [comment]
> Boa tarde, qual a sua hospedagem, versão do PHP e versão do MySQL?

>

**Comment by Pr3d4dor** [comment]
Talvez o problema seja a versão do PHP, recomendo você atualizar para a versão 7.2 se for possível pelo menos.

**Comment by Hidrobr** [comment]
vou verificar... vlw pela ajuda

**Comment by Hidrobr** [comment]
Bom dia.
atualizado para 7.2 e continua do mesmo jeito.
quando abro o sistema fica index.php/mapos/verificarLogin = {"result":true} 
Apago o caminho verificarlogon retorna no sistema.

teria que reinstalar o Mos?

**Comment by dezao** [comment]
@Hidrobr , aqui também estou com o mesmo problema, mesmo fazendo uma nova instalação limpa do sistema.

**Comment by lagethomas** [comment]
A nova versão tem outro esquema de criptografia, tenta pegar a senha do
usuário que está no arquivo SQL e colocar no seu usuário direto no banco
ela é 123456

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em ter, 12 de mar de 2019 17:28, Hidrobr <notifications@github.com>
escreveu:

**Comment by Hidrobr** [comment]
@lagethomas, obrigado pela ajuda, mas o problema não é senha, como eu informei a cima, quando loga fica a pagina em branco, "result":true , o php não esta retornando para pasta do mos, automatiamente, tem que apagar o caminho /verificarLogin ai entra normalmente no sistema.
O problema que php para mim é tentativa e erro conheço banco de dados não php

**Comment by edgarmunin** [comment]
Alguém já tem a solução?

**Comment by lagethomas** [comment]
Faz o seguinte então, na kup da sua base, baixa os arquivos novamente, sobe
eles no servidor e aponta para seu banco.

Pode ser algum erro em algum arquivo.

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qua, 13 de mar de 2019 15:49, 3dg4r <notifications@github.com> escreveu:

**Comment by Kajueiro** [comment]
Tive o mesmo problema, ainda bem que estava em plataforma de teste.... voltei pra versão antiga até ser resolvido o problema.

Abraço!

**Comment by Hidrobr** [comment]
estou vendo agora algumas config na base.

**Comment by Hidrobr** [comment]
Não achei o problema se alguem poder verificar.... Obrigado por enquanto.

**Comment by Pr3d4dor** [comment]
@Hidrobr baixe o código novamente, o @RamonSilva20 fez a correção desse erro ontem.

Baixe novamente o código mais atualizado da master.

**Comment by Hidrobr** [comment]
blz Valew

**Comment by Pr3d4dor** [comment]
@Hidrobr baixe o código novamente, o @RamonSilva20 fez a correção desse erro ontem.

Baixe novamente o código mais atualizado da master.
