### ISSUE TITLE
{"result":true}

### ISSUE THREAD

**Issue by legionariodassombras** [RamonSilva20/mapos#284]
Prezados, boa noite,

Preciso de ajuda quanto ao erro abaixo:
/index.php/mapos/verificarLogin
{"result":true}

Obrigado

**Comment by Pr3d4dor** [comment]
Boa noite, qual a sua hospedagem, versão do PHP e versão do MySQL?

**Comment by edgarmunin** [comment]
Mesmo problema aqui! {"result":true} 
Versão do PHP ea-php70
Cpanel

**Comment by Kajueiro** [comment]
Tenho o mesmo problema aqui também. PHP 7.0

Grato!

**Comment by lagethomas** [comment]
Tenta fazer o que eu citei acima, o meu está funcionando normal
Emedicsystem.com.br/app/mapos

Atenciosamente.


Thomas Henrique Lage Marcelino

--------------------------------------------------------------------------------------------------------------

Formação acadêmica | Redes de Computadores


Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades


Instituição: Fatec Cruzeiro, Prof. Waldomiro May.


Cidade: Cachoeira Paulista - SP


Contato: (12) 99142-2467


E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com

--------------------------------------------------------------------------------------------------------------



Em qua, 13 de mar de 2019 16:51, Kajueiro <notifications@github.com>
escreveu:

**Comment by RamonSilva20** [comment]
Problema solucionado.
