### ISSUE TITLE
como posso colocar na OS a possibilidade de Desconto?

### ISSUE THREAD

**Issue by coronaes** [RamonSilva20/mapos#285]
Estou modificando algumas coisas devido ao ramo onde estou usando MAPOS... estou amando, mas gostaria de colocar na OS a opção de desconto (tanto porcentual ou em valor mesmo) alguém poderia me ajudar por favor??

**Comment by K36Pro** [comment]
ainda não foi implementado, mas deveria ter a opção xD

**Comment by marceloccarmo** [comment]
Também estou precisando dessa opção.

**Comment by felipepips** [comment]
Criei um produto "desconto" alterei o valor via SQL para -1... quando precisar dar desconto, coloque tantas unidades deste produto conforme o valor do desconto.

**Comment by coronaes** [comment]
Eu achei uma melhor opção que você pode usar na hora mesmo de dar o desconto

Em um editor de texto digite o valor do desconto negativo 
Ex: -250
Copiar o valor negativo e colar no campo preço do Map OS 
![3ACB6421-D2F2-40E8-9C6C-A98306429AB6](https://user-images.githubusercontent.com/48535682/68529563-50cb9e80-02d6-11ea-8a30-79681d2a8009.jpeg)
