### ISSUE TITLE
Como posso colocar um valor negativo em serviços??

### ISSUE THREAD

**Issue by coronaes** [RamonSilva20/mapos#288]
Estou tentando colocar um preço negativo (valor negativo, ex: -30,00) na aba serviços...
dessa forma poderia oferecer um desconto pro cliente (Quem não gosta de Desconto??)
echo '<td>'.number_format($r->preco, 2, ',', '.').'</td>'; tentei modificar aqui mas nao deu certo

alguém pode me ajudar??

**Comment by brunolafm** [comment]
Eu criei com um preço qualquer e editei no banco de dados.

**Comment by Pr3d4dor** [comment]
Creio que isso é um "hack" para colocar desconto nas OS.

O ideal mesmo é implementar uma opção de desconto percentual (%) ou desconto por valor ($).

Assim que eu tiver tempo eu posso tentar fazer uma implementação.

**Comment by coronaes** [comment]
Você foi mais esperto..!! @brunolafm Vou fazer isso também, obrigado.!!!

**Comment by maycon1977** [comment]
> Eu criei com um preço qualquer e editei no banco de dados.

Criei aqui da mesma forma. Valeu pela dica...

No caso de Produto criei um item com o nome de "Desconto" e valor de "R$1,00". depois alterei o "R$1,00" por "-R$1,00" no Banco de Dados... Se quero dar um desconto de R$70,00, basta acrescentar o produto "Desconto" com a quantidade "70".

**Comment by sjpinfo** [comment]
uso MAPOS faz tempo e nunca precisei dar desconto, mas hoje mesmo pensei nisso, e olhando o fórum agora me deparei com a solução do @brunolafm parabéns, solução criativa...acabei de copiar...

**Comment by coronaes** [comment]
Descubrí uma forma acho que mais rápida de fazer, simplesmente escreve em outro lugar o valor negativo e um simples copiar e colar resolve já.!!!

**Comment by augustocoletti** [comment]
Também utilizo a bastante tempo e a solução que encontrei foi a mesma do amigo, criar produto e via banco modificar valor como negativo. Já vi o pessoal falando sobre a inclusão da possibilidade de valor editável tanto em produtos como nos serviços, creio que seja questão de tempo para ser implantado. Espero que logo hehehe... Sinto por não contribuir com o projeto, ele é fabuloso mas me falta conhecimento....
