### ISSUE TITLE
Paginação em Financeiro>Lançamento

### ISSUE THREAD

**Issue by joaosouz4** [RamonSilva20/mapos#293]
Quando pesquiso os lançamentos financeiros e o resultado é maior que uma página, os totais de receita, despesa e saldo são diferentes para cada página.

**Comment by maycon1977** [comment]
Complementando a dúvida do cloega, gostaria de modificar a quantidade de itens que aparecem nas pesquisas, aumentando por exemplo de 10 para 30 a listagem de Ordens de Serviço...
Onde posso alterar essas limitações? Alguém saberia ajudar?
