### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by papaiisac** [RamonSilva20/mapos#295]
boa noite, trabalho muito bom este mapos parabens
quando faço qualquer tipo de cadastro e clico em adicionar vai para uma pagina
404 Page Not Found mas o cadastro e efetuado, estou na versão 3.3.1. muito obrigado
endereço do navegador
/index.php/index.php/clientes/adicionar/

**Comment by alanddos** [comment]
Pode ser que que precise sobreescrever redirecionamento pelo erro
apresentado da uma olhada em .htaccess no google

Em sáb, 23 de mar de 2019 18:29, papaiisac <notifications@github.com>
escreveu:

**Comment by papaiisac** [comment]
Muito obrigado vou pesquisar valeu

Em sáb, 23 de mar de 2019 20:31, alanddos <notifications@github.com>
escreveu:

**Comment by brunolafm** [comment]
Boa noite, verifica se no seu config.php o endereço está 'http://SEU-IP-AQUI/mapos'.
Se tiver com o config.php na frente, remova, provavelmente isso está ocasionando o erro.

**Comment by papaiisac** [comment]
muito obrigado Bruno, era isso mesmo valeu
