### ISSUE TITLE
Acesso Via Rede Local

### ISSUE THREAD

**Issue by ddaragone01** [RamonSilva20/mapos#297]
Boa noite, instalei o sistema em servidor wamp, e na maquina local roda normal. Redirecionei para as portas que eu queria, abri as portas no firewall, mas quando tento acessar por outro computador, da o erro - ERR_CONNECTION_REFUSED. testei em varios computadores e navegadores.

Se eu tentar acessar outros serviços do servidor wamp pelos outros computadores vai, mas quando tento o sistema não.

Podem me dar alguma dica?

No aguardo.

**Comment by mariolucasdev** [comment]
Vamos imaginar o seguinte ambiente:

Server:
 - COLOQUE UM IP ESTÁTICO
 - NO CONFIG ALTERE DE LOCALHOST PARA O IP QUE VOCÊ SETOU NO SERVIDOR
    examplo imaginando que o ip so servidor foi seta com 10.0.0.100
    `$config['base_url'] = 'http://10.0.0.100/pastadosistema/';`
    `$config['base_url'] = 'http://';`

acredito que com essas configurações já funcione.
