### ISSUE TITLE
Procuro algum programador/orçamento para 2 mudanças.

### ISSUE THREAD

**Issue by vaidamerda** [RamonSilva20/mapos#299]
olá pessoal preciso de 2 mudanças para adaptar melhor o sistema a minha necessidade, se algum programador puder me orçar essas mudanças eu agradeço.

1 - personalizar o número da OS.
2 - na tela de login do cliente deixar somente um campo para acessar OS a partir do número sem ter que por email ou cpf.

rrr5234@gmail.com

**Comment by mariolucasdev** [comment]
Olá bom dia, sou contribuidor do projeto, estarei entendo em contato.
