### ISSUE TITLE
[Informação] Uso do PHP 7.0

### ISSUE THREAD

**Issue by McGuyverBR** [RamonSilva20/mapos#30]
Pelos testes que executei com um amigo, o mapOS opera normalmente no PHP 7.0, bastando para isso alterar a linha abaixo no arquivo applicatons/config/database.php. 
Trocar de:
`$db['default']['dbdriver'] = 'mysql';`
para:
`$db['default']['dbdriver'] = 'mysqli';`

Fica a dica para quem desejar efetuar os testes.

**Comment by RamonSilva20** [comment]
Bom saber. Obrigado.

**Comment by cleytonasa** [comment]
Massa! :+1:

**Comment by KokeroO** [comment]
Testei desta maneira no PHP 7.1.4. E também está normal.

**Comment by KokeroO** [comment]
Os relatórios não funcionaram no PHP 7. Verei qual e o problema e passarei aqui.

**Comment by 19972019** [comment]
Estou com o mesmo problema do @KokeroO os relatório não estão funcionando na versão 7.0 do PHP, alguém ai sabe me dizer se já uma solução?

**Comment by KokeroO** [comment]
O problema está na versão do mpdf. E só atualizar a nova versão do mpdf.
