### ISSUE TITLE
Alterar o editor para um melhor como o TinyMCE

### ISSUE THREAD

**Issue by guibarbas** [RamonSilva20/mapos#300]
Olá, boa tarde
Seria possível modificar o editor de texto para um melhor como o TinyMCE
para disponibilizar a edição de tamanho de foto e etc ?

**Comment by lagethomas** [comment]
Mas isso já tem?



Atenciosamente.

Thomas Henrique Lage Marcelino
--------------------------------------------------------------------------------------------------------------
Formação acadêmica | Redes de Computadores

Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades

Instituição: Fatec Cruzeiro, Prof. Waldomiro May.

Cidade: Cachoeira Paulista - SP

Contato: (12) 99126-4149

E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com
--------------------------------------------------------------------------------------------------------------


Em ter, 2 de abr de 2019 às 17:59, guibarbas <notifications@github.com>
escreveu:

**Comment by guibarbas** [comment]
Opa Como vai @lagethomas 
Estou usando a versão 3.3.1
E veja como aparece a inserção de mídias 
http://prntscr.com/n6mo5m

Não da a opção de tamanho 
Como posso ativar ?

**Comment by lagethomas** [comment]
nesse caso vc terá que já editar a imagem e colocar o link dela editado ai.



Atenciosamente.

Thomas Henrique Lage Marcelino
--------------------------------------------------------------------------------------------------------------
Formação acadêmica | Redes de Computadores

Analista de Suporte | AME Lorena - Ambulatório Médico de Especialidades

Instituição: Fatec Cruzeiro, Prof. Waldomiro May.

Cidade: Cachoeira Paulista - SP

Contato: (12) 99126-4149

E-mail: lage.thomas@gmail.com | llage.thomas@gmail.com
--------------------------------------------------------------------------------------------------------------


Em ter, 2 de abr de 2019 às 18:41, guibarbas <notifications@github.com>
escreveu:

**Comment by guibarbas** [comment]
Humm entendo.
Seria ótimo se tivesse a opção de modificar o tamanho da foto
