### ISSUE TITLE
alterar theme

### ISSUE THREAD

**Issue by bernardoari** [RamonSilva20/mapos#301]
Boa tarde,

andei testando a versão 4 do mapos
e a versão 3.3.1
eu percebi que a mais estável é a versão 3
mas gostei do theme da versão 4
alguém de bom coração conseguiu colocar as cores do 4 na versão 3?
teria como orientar que arquivos modificar ou passar os arquivos css para copiar e colar na pasta do mapos  por gentileza?
obrigado

**Comment by guibarbas** [comment]
@bernardoari  Brother, onde você encontrou a v4 do mapos  ?
Você tem o download ?

**Comment by bernardoari** [comment]
aqui no forum mesmo la em "projects". se não me engano,
só que está com muitos bugs

**Comment by augustocoletti** [comment]
Realmente esse tema é espetacular... no mapos 3 ficaria show..
