### ISSUE TITLE
Pesquisa de Vários tipos de O.S.

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#302]
Olá, pessoal.

Consegui personalizar vários STATUS de acordo com o que mais utilizamos aqui na empresa.
Exemplo abaixo:

![image](https://user-images.githubusercontent.com/47214174/55557183-a6e0bf80-56bf-11e9-82d8-fdf247ca2e4e.png)

O link abaixo me leva pra página das O.S.
`http://www.pressaorio.com.br/sistema/index.php/os`
Até aí nada demais...

O próximo link me leva pras O.S. de "CLIENTES A VISITAR"
`http://www.pressaorio.com.br/sistema/index.php/os/gerenciar?pesquisa=&status=Cliente+a+Visitar&data=&data2=`
Tudo Ok até aqui...

O que preciso? Listar de uma vez só, todas as O.S. "não finalizadas", de forma que precisaria "construir" um atalho que englobasse "CLIENTES A VISITAR + ORÇAMENTOS A FAZER + AGUARDANDO APROVAÇÃO + FATURADO PARA ENTREGA + ETC".

Como posso fazer isso? Alguém sabe como colocar isso num link?
Tentei
`www.pressaorio.com.br/sistema/index.php/os/gerenciar?pesquisa=&status=Cliente+a+Visitar&FaturadoparaEntrega&data=&data2=`

Não Funcionou. Tem algum erro aí que eu travei...

**Comment by Pr3d4dor** [comment]
O que pode ser feito é no filtro de status ser passado um array com todos os status a serem filtrados (separados por vírgula), por exemplo:
```
www.pressaorio.com.br/sistema/index.php/os/gerenciar?pesquisa=&status=status1,status2,status3&data=&data2=
```
No controller a lista de status a serem exibidos pode ser recebida assim:
```php
$status = explode($stringDeStatusNaUrl, ",");
```

E assim a lógica no controller também devem ser alterados.

**Comment by maycon1977** [comment]
> O que pode ser feito é no filtro de status ser passado um array com todos os status a serem filtrados (separados por vírgula), por exemplo:
> 
> ```
> www.pressaorio.com.br/sistema/index.php/os/gerenciar?pesquisa=&status=status1,status2,status3&data=&data2=
> ```

**

OPA... Tentei aqui e não foi!
Eu já havia feito isso usando o "+" ao invés da "," e tb não funcionou!

**


> No controller a lista de status a serem exibidos pode ser recebida assim:
> 
> ```
> $status = explode($stringDeStatusNaUrl, ",");
> ```

**

Desculpa, mas não achei onde inserir essa linha de código. Pode ser mais específico?

**

> 
> E assim a lógica no controller também devem ser alterados.

Muito obrigado pela ajuda!

**Comment by Pr3d4dor** [comment]
Usan a a estratégia de vírgulas:

No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php`

Onde temos
```php
if ($status) {
    $where_array['status'] = $status;
}
```

Deve ser trocado por:
```php
if ($status) {
    $where_array['status'] = explode($status, ",");
}
```

No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php`
```php
// condicional de status
if (array_key_exists('status', $where)) {
    $this->db->where('status', $where['status']);
}
```

Deve ser trocado por:
```php
// condicional de status
if (array_key_exists('status', $where)) {
   $this->db->where_in('status', $where['status']);
}
```

**Comment by maycon1977** [comment]
> Usando a estratégia de vírgulas:
> 
> No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php`
> 
> Onde temos
> 
> ```
> if ($status) {
>     $where_array['status'] = $status;
> }
> ```
> 
> Deve ser trocado por:
> 
> ```
> if ($status) {
>     $where_array['status'] = explode($status, ",");
> }
> ```
> 
> No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php`
> 
> ```
> // condicional de status
> if (array_key_exists('status', $where)) {
>     $this->db->where('status', $where['status']);
> }
> ```
> 
> Deve ser trocado por:
> 
> ```
> // condicional de status
> if (array_key_exists('status', $where)) {
>    $this->db->where_in('status', $where['status']);
> }
> ```
> 
> Seria algo mais ou menos assim.
> 
> A lógica de montar a URL corretamente (com as vírgulas quando múltiplos forem selecionados) também deve ser verificada.

Cara... Fiz exatamente como você descreveu e editando os 2 arquivos dessa forma, a pesquisa das O.S. pára de funcionar. Nem funciona para "+ de 1 status" e nem a pesquisa original.. A listagem sempre me retorna sem dados...

![image](https://user-images.githubusercontent.com/47214174/57564983-875a4800-738b-11e9-90be-ff3b2f48efd4.png)

**Comment by Pr3d4dor** [comment]
Você vai precisar ir debugando o código usando var_dump() e die; para verificar onde exatamente está o problema.

**Comment by phlopes1406** [comment]
Amigo eu também preciso renomear alguns campos dos status e adicionar mais uns... Poderia me dar uma ajuda?

**Comment by phlopes1406** [comment]
amigo conseguiu fazer a alteracao para buscar mais de um tipo de ordem?

**Comment by phlopes1406** [comment]
> 
> 
> > Usando a estratégia de vírgulas:
> > No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php`
> > Onde temos
> > ```
> > if ($status) {
> >     $where_array['status'] = $status;
> > }
> > ```
> > 
> > 
> > Deve ser trocado por:
> > ```
> > if ($status) {
> >     $where_array['status'] = explode($status, ",");
> > }
> > ```
> > 
> > 
> > No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php`
> > ```
> > // condicional de status
> > if (array_key_exists('status', $where)) {
> >     $this->db->where('status', $where['status']);
> > }
> > ```
> > 
> > 
> > Deve ser trocado por:
> > ```
> > // condicional de status
> > if (array_key_exists('status', $where)) {
> >    $this->db->where_in('status', $where['status']);
> > }
> > ```
> > 
> > 
> > Seria algo mais ou menos assim.
> > A lógica de montar a URL corretamente (com as vírgulas quando múltiplos forem selecionados) também deve ser verificada.
> 
> Cara... Fiz exatamente como você descreveu e editando os 2 arquivos dessa forma, a pesquisa das O.S. pára de funcionar. Nem funciona para "+ de 1 status" e nem a pesquisa original.. A listagem sempre me retorna sem dados...
> 
> ![image](https://user-images.githubusercontent.com/47214174/57564983-875a4800-738b-11e9-90be-ff3b2f48efd4.png)


amigo o problema está no código que ele passou, ele apenas se confundiu na ordem dos parametros...

segue parametro que eu testei e funcionou!!

if ($status) {
    		$where_array['status'] = explode(",", $status);
		}

**Comment by maycon1977** [comment]
> > > Usando a estratégia de vírgulas:
> > > No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php`
> > > Onde temos
> > > ```
> > > if ($status) {
> > >     $where_array['status'] = $status;
> > > }
> > > ```
> > > 
> > > 
> > > Deve ser trocado por:
> > > ```
> > > if ($status) {
> > >     $where_array['status'] = explode($status, ",");
> > > }
> > > ```
> > > 
> > > 
> > > No arquivo: `https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php`
> > > ```
> > > // condicional de status
> > > if (array_key_exists('status', $where)) {
> > >     $this->db->where('status', $where['status']);
> > > }
> > > ```
> > > 
> > > 
> > > Deve ser trocado por:
> > > ```
> > > // condicional de status
> > > if (array_key_exists('status', $where)) {
> > >    $this->db->where_in('status', $where['status']);
> > > }
> > > ```
> > > 
> > > 
> > > Seria algo mais ou menos assim.
> > > A lógica de montar a URL corretamente (com as vírgulas quando múltiplos forem selecionados) também deve ser verificada.
> > 
> > 
> > Cara... Fiz exatamente como você descreveu e editando os 2 arquivos dessa forma, a pesquisa das O.S. pára de funcionar. Nem funciona para "+ de 1 status" e nem a pesquisa original.. A listagem sempre me retorna sem dados...
> > ![image](https://user-images.githubusercontent.com/47214174/57564983-875a4800-738b-11e9-90be-ff3b2f48efd4.png)
> 
> amigo o problema está no código que ele passou, ele apenas se confundiu na ordem dos parametros...
> 
> segue parametro que eu testei e funcionou!!
> 
> if ($status) {
> $where_array['status'] = explode(",", $status);
> }

Vou testar por esses dias e aviso se deu certo.
Obrigado pela ajuda!

**Comment by phlopes1406** [comment]
beleza

**Comment by phlopes1406** [comment]
> montar a URL correta

amigo voce poderia me explicar este caso de montar a URL corretamente? tipo se eu monto manualmente a url com a , ele filtra normal os status.. mais quando eu seleciono no form_multiselect, ele repete o parametro $string, ele filtra só um... olha só como está o codigo:

$options = array ('SELECIONE 1 OU + STATUS' => $situacao);
            echo form_multiselect($name = 'status', $options,'',$js); ?>

aí ele gera assim quando eu seleciono 2 status: http://localhost/mapos-infotech/index.php/os/gerenciar?pesquisa=&status=ENTREGAR&status=VISITAR&data=&data2=

no lugar desse segundo $status depois do ENTREGAR, como faço pra fazer virar uma virgula? vc sabe?
