### ISSUE TITLE
1º Valor da OS não aparece na pagina OS (2º Campo CPF/CNPJ Erro)

### ISSUE THREAD

**Issue by guibarbas** [RamonSilva20/mapos#304]
1º Como podem ver, no sistema o valor da OS aparece como Zerado,
Como corrigir ?
http://prntscr.com/n7ldsp

2º O segundo ponto é o campo CPF/CNPJ que esta com erro Mesmo inserindo o cnpj ao editar exibe errado
Ao visualizar
http://prntscr.com/n7ler6
Ao editar
http://prntscr.com/n7lf4i

**Comment by marcotuliomtb** [comment]
quanto a primeira pergunta, sou novato no sistema, mas pelo que conheço do sistema o preço final aparece apenas quando vc fatura a O.S

**Comment by guibarbas** [comment]
olá @marcotuliomtb  Como vai ?
Mesmo faturando o valor aparece 0

**Comment by juliorcarvalho** [comment]
1º - Olá @guibarbas  Testei aqui, e realmente o valor não está aparecendo sem que fature a OS. MAs então te auxiliando sobre como proceder: após abrir a OS, vá nas abas: PRODUTOS e/ou SERVIÇOS que estão logo acima da tela que abre OS(não é o menu da esquerda não) e adicionar os respectivos produtos e serviços que desejar, slavar as alterações então clique no fim da página em FATURAR, marque o campo: RECEBIDO, escolha uma data e fature então o Sistema vai apresentar os valores na tela de visualização de OS. 
OBS: Vc já precisa ter cadastrado antes os Produtos e Serviços que deseja nas opções do painel lateral esquerdo.

2º - Realmente o Sistema está fazendo isso, ele está consumindo SEMPRE QUE É UM CNPJ os ultimos 3 digitos. No momento a solução que uso é guardar quais são os 4 ultimos digitos, então na tela de erro, vc apaga o ultimo numero e digita os 4 ultimos numeros do CNPJ.
