### ISSUE TITLE
Duvidas/Auxilio para modificações próprias e possível contribuição no projeto

### ISSUE THREAD

**Issue by juliorcarvalho** [RamonSilva20/mapos#305]
**Olá Pessoal, Antes de Tudo Gostaria de Agradecer imensamente ao @RamonSilva20 pelo projeto e por tê-lo disponibilizado. E pedir desculpas se não for adequado abrir uma Issue para o que estou fazendo, mas essá é minha primeira postagem kkkk.** 
Não sou programador, e conheço quase nada sobre GitHub, até o momento, inclusive a primeira vez que entrei aqui, foi procurando na Internet sobre Sistemas de OS pois comecei a trabalhar como Técnico em Informática Autônomo e precisava de um Sistema para controle pessoal. Estou lendo o livro Git e pesquisando tudo o que posso para aprender a usar corretamente esta ferramenta. 
Já estou o utilizando há 1 ano e meio na versão Master do @RamonSilva20. Tenho estado muito satisfeito com ela mas gostaria de mudanças, sendo que li TODAS as Issues antes de fazer esta postagem e vi que algumas já até foram implementadas, ou solicitadas. 
Acabei de Baixar a versão Custom do Rafael Marques e gostei muito dela, devido ao recursos diferentes implementados(que pena que ele não conseguiu contribui em tempo real com o projeto caso contrário já teríamos novas funcionalidades no branch Master e o Ramon não teria de rever tudo de uma vez não é? rsrs)
Mas por fim... estou postando isso, pois gostaria do auxilio de vocês sobre materiais bons (que vocês diriam que vale mesmo a pena) para me ajudar a aprofundar e aprender mais sobre Git, Github, PHP, MVC(acho que é isso mesmo né :) ) ou cursos etc.. Aqui em minha cidade me procuraram para desenvolver projetos semelhantes (Quanto as funcionalidades e facilidade de uso) e se for permitido comercializar o programa, exclusivamente com a permissão do @RamonSilva20 (por mais que esteja sob a licença MIT eu prefiro dessa forma rsrs) Eu me sentiria super satisfeito em vender/ajudar no(o) sistema, e contribuir com os valores ganhos para ajudar no projeto, até porque vi os anuncios no ML dos idio...as que pegaram o código se aponderaram como softwares próprios e comercializaram sem creditar adequadamente o Ramon, o que é uma grande injustiça. Por isso gostaria de ajudar a corrigir isso, pq fui muito ajudado pelo projeto.
**Mais uma vez Muitíssimo Obrigado e Parabéns a todos os Colaboradores!!!**

**Comment by Pr3d4dor** [comment]
Olá, recomendo os seguintes materiais:
- GIT: https://rogerdudler.github.io/git-guide/index.pt_BR.html
- PHP: http://br.phptherightway.com/
- MVC: https://code.tutsplus.com/pt/tutorials/mvc-for-noobs--net-10488
