### ISSUE TITLE
Status da Ordem de Serviço

### ISSUE THREAD

**Issue by ongb4k** [RamonSilva20/mapos#306]
Olá, 

No login como cliente, 

A ordem de serviço com status já "faturada" no painel do cliente, ao entrar no menu "Ordens de Serviço" se encontra com status "Em Andamento". 

![Screen Shot 04-11-19 at 02 03 PM](https://user-images.githubusercontent.com/49531456/55976470-acf81280-5c62-11e9-871c-44dbc83cd8a5.PNG)
![Screen Shot 04-11-19 at 02 03 PM 001](https://user-images.githubusercontent.com/49531456/55976480-b2555d00-5c62-11e9-8cdf-c634184f275e.PNG)

**Comment by ongb4k** [comment]
Consegui corrigir

Problema: os clientes no painel após ser atendida e faturada a OS, aparecia em andamento no menu ordem de serviço. 
Solução: mapos-master\application\views\conecte\os.php 
adicionado o status na linha 89
} elseif ($r->status == "Faturado") {
                            $status = '<span class="label label-important">Faturado</span>';

**Comment by Pr3d4dor** [comment]
Obrigado pela correção, fiz uma PR com os ajustes disponível em #307
