### ISSUE TITLE
Ajuda para modificar templates

### ISSUE THREAD

**Issue by Franklin0180** [RamonSilva20/mapos#308]
Olá, tudo bem? 
Estava atrás de uma base para fazer meu sistema emissor de nota fiscal e encontrei essa que achei super bacana.

Preciso de ajuda para criar novas abas, por exemplo no financeiro queria adicionar a aba Emitir NFe, porém estou com um pouco de dificuldades para fazer isso... Alguém saberia me ajudar ou teria algum tutorial por ai?

**Comment by Pr3d4dor** [comment]
Qual seria o problema exatamente?

Você precisa crias as suas telas personalizadas usando HTML e PHP e editar as telas já existentes para mostrar os links para as suas novas telas.
