### ISSUE TITLE
Relatorio sem Cabeçalho

### ISSUE THREAD

**Issue by totivinicius** [RamonSilva20/mapos#309]
Bom dia amigos, tudo bem?

Preciso de uma ajuda, o cabeçalhos do relatório de cliente aparece normal mas os outros relatórios não aparecem, alguém sabe o que poderia ser?

Obrigado 
versao MAPOS 3.3.1

**Comment by mariolucasdev** [comment]
Bom dia, eu fiz alguns cabeçalhos dos relatórios, porém ainda não fiz todos, poderia me manar por gentileza os que estão com problemas ainda?

Aguardo...

**Comment by totivinicius** [comment]
Bom dia!

Obrigado por responder!

Só o de clientes que sai cabeçalho os outros nenhum sai, será que estou fazendo algo de errado?

Atenciosamente 

Enviado do meu iPhone

Em 2 de mai de 2019, à(s) 08:29, Mário Lucas <notifications@github.com> escreveu:

**Comment by mariolucasdev** [comment]
Não, realmente é que não foram feitos ainda, vou montar em breve esses cabeçalhos e subir. Estive um tempo ocupado em outros trabalhos mas vou retomar as contribuições vou incluir esses cabeçalhos em minha task list.

**Comment by totivinicius** [comment]
Legal, fico muito grato...e obrigado por compartilhar conosco seu sistema.

A versão 4 vi que esta em andamento?



Enviado do Email para Windows 10

De: Mário Lucas
Enviado:quinta-feira, 2 de maio de 2019 08:41
Para: RamonSilva20/mapos
Cc:totivinicius; Author
Assunto: Re: [RamonSilva20/mapos] Relatorio sem Cabeçalho (#309)

Não, realmente é que não foram feitos ainda, vou montar em breve esses cabeçalhos e subir. Estive um tempo ocupado em outros trabalhos mas vou retomar as contribuições vou incluir esses cabeçalhos em minha task list.

**Comment by mariolucasdev** [comment]
Na verdade esse sistema é do @RamonSilva20 sou apenas contribuidor. E sim o 4 está em andamento.

**Comment by totivinicius** [comment]
Desculpe achei que era o Ramon..kkk

Muito obrigado por responder.

Enviado do Email para Windows 10

De: Mário Lucas
Enviado:quinta-feira, 2 de maio de 2019 08:51
Para: RamonSilva20/mapos
Cc:totivinicius; Author
Assunto: Re: [RamonSilva20/mapos] Relatorio sem Cabeçalho (#309)

Na verdade esse sistema é do @RamonSilva20 sou apenas contribuidor. E sim o 4 está em andamento.

**Comment by luizdeltasouza** [comment]
ramon toda vez que tento imprimir relatorio de vendas do produto os dados do vendedor e do cliente saem com asteristicos

**Comment by RamonSilva20** [comment]
@luizdeltasouza farei a verificação e na próxima versão farei a correção.

**Comment by mariolucasdev** [comment]
@RamonSilva20 Eu estava vendo essa parte dos relatórios, mas mano, estou em uma correria medonha, por isso não consegui mais mexer. @luizdeltasouza  se poder enviar prints da tela facilita o processo.
