### ISSUE TITLE
Duas formas de pagamento

### ISSUE THREAD

**Issue by coronaes** [RamonSilva20/mapos#310]
Como posso adicionar 2 formas de pagamento numa OS?
Exemplo: Cliente paga à vista 300R$ e o restante paga no cartão 
Como posso adicionar os 2 pagamentos?

**Comment by mariolucasdev** [comment]
Essa função ainda não está disponível acredito que uma maneira de contornar, seria incluir 2 lançamento cada um com suas respectivas formas de pagamento e nas observações colocar o numero da OS para identificar.

**Comment by maycon1977** [comment]
> Essa função ainda não está disponível acredito que uma maneira de contornar, seria incluir 2 lançamento cada um com suas respectivas formas de pagamento e nas observações colocar o numero da OS para identificar.

Eu normalmente faturo e edito lá no lançamento. Descrevo no campo que tem lá de "Descrição", mas essa sua solução é bem melhor... 

A primeira parcela, fatura através da O.S. e as outras faz como lançamento. Passarei a fazer isso. Boa idéia!
