### ISSUE TITLE
TELAS NO SISTEMA

### ISSUE THREAD

**Issue by rochajoao881** [RamonSilva20/mapos#311]
COMO EU ADICIONO NOVAS TELAS NO SISTEMA ??????????

**Comment by mariolucasdev** [comment]
Seria necessário criar um método no controller do módulo que você deseja adicionar uma nova função, depois disso criar as views responsáveis, e posteriormente um método no model responsável assim você poderia criar novas telas e funções no sistema.

Atenciosamente,
Mário Lucas

**Comment by fixeva2019** [comment]
oque eu adiciono em controllers
