### ISSUE TITLE
Erro ao instalar em localhost

### ISSUE THREAD

**Issue by Kaoozie** [RamonSilva20/mapos#313]
Olá,
Estou com problemas ao instalar a última versão em localhost, com uma versão antiga funciona normalmente. Já tentei fazer a instalação tanto manualmente quanto automaticamente.

Imagem do erro: https://prnt.sc/nj4it9

**Comment by angelolpa** [comment]
application\config\config.php 
Linha 82 > $config['base_url'] = 'http://127.0.0.1/';

application\config\database.php 
        'hostname' => 'localhost',
	'username' => 'nome do usuário',
	'password' => 'senha dobd',
	'database' => 'nome no bd',
