### ISSUE TITLE
O.S. só aparece valor total se tiver VENDA

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#314]
Olá a todos.
Peço ajuda mais uma vez.

Aqui na empresa eu uso o MAPOS somente como Ordem de Serviço, mesmo quando é venda, uso o módulo de serviço para isso e tem sido muito útil. Desde o início, notei que quando eu insiro somente SERVIÇO na O.S. , O SISTEMA IGNORA E SÓ SOMA QUANDO TEM PRODUTO + SERVIÇO. Ele não TOTALIZA o Valor na visualização e/ou impressão do documento.

![image](https://user-images.githubusercontent.com/47214174/57080322-afc9ae80-6cc8-11e9-8eea-c6d836409d72.png)

![image](https://user-images.githubusercontent.com/47214174/57080488-033bfc80-6cc9-11e9-9a67-b0c80869d0df.png)

Não sei se em alguma das personalizações que eu fiz, alterei algo que tá fazendo acontecer esse erro. O que eu tenho feito quando não existe VENDA, é sempre lançar um item no PRODUTO como "Materiais e Insumos Diversos" que atribuí o valor de R$0,00, Dessa forma, o resultado final aparece ok, somando PRODUTO R$0,00 + SERVIÇO R$X,XX = TOTAL R$X,XX.

![image](https://user-images.githubusercontent.com/47214174/57080776-a2f98a80-6cc9-11e9-9a44-7712bcf60022.png)

Tenho trabalhado dessa forma e está tudo funcionando desse jeito, porém, seria interessante não ter que usar desse "artifício gambiarrístico".

Se algum dos mestres puderem me ajudar, agradeço muito!

**Comment by maycon1977** [comment]
Pessoal. Resolvi!

Seguinte... 

Em algum momento eu devo ter trocado de posição, colocando a listagem de PRODUTOS E DEPOIS A DE SERVIÇOS. Bastou inverter e (re)colocar? os SERVIÇOS NA FRENTE DOS PRODUTOS e tanto na visualização quanto na impressão voltou ao normal!

Muito obrigado!

**Comment by Louryval** [comment]
Buenos Maycon!
Preciso fazer uns ajustes nos relatórios mas não tenho conhecimento para tanto, terias disponibilidade para me ajudar? Tipo: em relatório de OS não tem a opção de aparecer o número da OS e isso é importante pra mim. Também os técnicos selecionados não aparecem no cabeçalho do relatório. 

Desde já agradeço.

louryval@gmail.com
