### ISSUE TITLE
mapos-custom Ajuda

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#315]
Estou a usar o Mapos-Custom mas estou com 3 problemas.
Quando faço login ele não me entra (http://localhost/registo/index.php/mapos/login)
depois de fazer o login sem entrar para a pagina principal eu altero o endereço (http://localhost/registo/index.php) e ja entra.

Podem ajudar como resolver?

Outro problema é nos Relatórios não consigo obter nenhum relatorio aparece. (Fatal error: Switch statements may only contain one default clause in C:\xampp\htdocs\registo\application\helpers\mpdf\mpdf.php on line 1419)

O 3 problema é para fazer backup. dá um erro:
A Database Error Occurred
Unsupported feature of the database platform you are using.
Filename: C:\xampp\htdocs\registo\system\database\drivers\mysqli\mysqli_utility.php
Line Number: 82 

Podem ajudar a resolver estes problemas?
Obrigado pelo excelente trabalho de equipa.

Grande abraço

**Comment by Pr3d4dor** [comment]
Qual versão exatamente do mapos você está utilizando?

Tente atualizar para a versão mais recente pois esse problema do login foi corrigido. (Isso deve resolver os problemas 1 e 2).

Sobre o problema 3, parece que o banco de dados que você está utilizando está conflitando com a versão do driver utilizado no sistema. Tente usar o MySQL 5.6 ou 8.0.

**Comment by LipzyLipzy** [comment]
Boas, eu mudei para a última versão e deixei a anterior. Estava com vários problemas, obrigado
