### ISSUE TITLE
Alerta ao entrar no sistema

### ISSUE THREAD

**Issue by ddevitte** [RamonSilva20/mapos#316]
Olá!
Acabo de realizar a instalação do sistema em meu servidor, mas não consigo ter acesso à ele.
Quando tento logar, sou direcionado para a página de Alerta, indicando que devo falar com o administrador.
Segui as instruções de instalação... alguma dica?

**Comment by willsantos07** [comment]
verifique que executou o arquivo update_v3.1.9_to_3.2.x.sql na pasta update caso sim verifique o valor na tabela dataExpiracao por um valor no futuro.

**Comment by ddevitte** [comment]
Perfeito! Era a data de expiração mesmo... valeu pelo toque!
