### ISSUE TITLE
Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.

### ISSUE THREAD

**Issue by guibarbas** [RamonSilva20/mapos#318]
Olá boa tarde.

Apos atualizar o sistema da versão 3.3.1 para 3.3.2 sempre aparece este erro 

Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.
Se eu clico em Ir para a pagina de login ele apenas pisca a tela e se eu apago a pasta Install ele da erro 404.

Como posso corrigir ?

**Comment by guibarbas** [comment]
Corrigido removendo e instalando novamente

**Comment by higorvergara** [comment]
Como vc corrigiu o problema?

**Comment by guibarbas** [comment]
> Como vc corrigiu o problema?

Removendo o sistema por completo e instalando novamente

**Comment by higorvergara** [comment]
Já fiz isso 3x e sempre da o mesmo erro. o banco de dados seu é o que vem na pasta ou vc fez Update ?

**Comment by guibarbas** [comment]
> Já fiz isso 3x e sempre da o mesmo erro. o banco de dados seu é o que vem na pasta ou vc fez Update ?

É o da pasta mesmo.
Estranho em.

**Comment by higorvergara** [comment]
Então parceiro consegui, vi onde é o erro
Assim que instala e coloca o banco tem que ir no index e alterar para
define('ENVIRONMENT', 'production');
sem isso ele cai para a pasta Install
agora funcionando perfeito...
