### ISSUE TITLE
Erro página OS Ver. 3.5.0

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#321]
Página Ordens de Serviços não carrega (/mapos/index.php/os) na Versão 3.5.0.
Testado no Firefox 66.0.5 e Chrome 74.0.3729.131

**Comment by RamonSilva20** [comment]
Olá. Teria como enviar a mensagem de erro. Se nenhum estiver aparecendo, altere no arquivo index.php linha 59 para development, para exibir o erro.

define('ENVIRONMENT', 'development');

**Comment by michelfritsch** [comment]
Boa tarde, não aparece nenhum erro no modo production e no modo development
não está logando nem como admin.



Em seg, 13 de mai de 2019 13:52, Ramon Silva <notifications@github.com>
escreveu:

**Comment by michelfritsch** [comment]
Resolvido, rodei o Update 3.3 to 3.5 e funcionou. Nãoprestei atenção nesse
Update.

Obrigado,


Em seg, 13 de mai de 2019 13:52, Ramon Silva <notifications@github.com>
escreveu:

**Comment by michelfritsch** [comment]
Resolvido com update_v3.3.x_to_3.4.x.sql
