### ISSUE TITLE
Modificar relatório de vendas

### ISSUE THREAD

**Issue by andrebertini** [RamonSilva20/mapos#322]
Olá, estou usando sistema dentro da minha empresa só para controle de estoque. Entrada e saída de produto.
Quando vou dar saída de um produto, eu efetuo como se fosse venda normal, com o cliente, produto, quantidade...
No relatório de venda me traz as informações de Cliente / Total / Data / Vendedor
Eu precisaria que tivesse qual o produto vendido e a quantidade. Total e Vendedor não são relevantes pra mim.
Ou então que tivesse um relatório que tratasse da saída dos produtos.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
