### ISSUE TITLE
Preciso de programador para 2 mudanças.

### ISSUE THREAD

**Issue by viotoneto** [RamonSilva20/mapos#325]
Ola gostaria de um orçamento para fazer duas modificações no mapos.
1º colocar desconto
2º colocar na aba produtos na tabela de quantidade valores de números não inteiros.

Outra coisa como faço para contribuir com o projeto?

**Comment by mvnp** [comment]
@viotoneto 48 99189 3313 me chama.

**Comment by willph** [comment]
> 
> 
> Ola gostaria de um orçamento para fazer duas modificações no mapos.
> 1º colocar desconto
> 2º colocar na aba produtos na tabela de quantidade valores de números não inteiros.
> 
> Outra coisa como faço para contribuir com o projeto?

Como seria esse desconto e onde?

Poderia explicar melhor para talvez adicionamos na próxima versão.

Com relação a contribuir ao projeto, seria como?
Porque você pode fazer alterações e envia um pull request

**Comment by viotoneto** [comment]
Como seria esse desconto e onde?
O desconto seria bom na hora de faturar, poderia colocar uma parte de desconto com valor ou porcentagem ou os dois. Poderia TB colocar uma parte de recebimento de dinheiro não sendo o total e coloca uma parte mostrando o quanto falta. Espero que esteja claro... Kkkk


Com relação a contribuir ao projeto, seria como?
Não sei muito de PHP... Gostaria de ajudar como puder... Quero aprender TB PHP se alguém me indicar como iniciar eu agradeço...

**Comment by Marcosaquino32** [comment]
Também acho interessante ter a opção de desconto, tipo o serviço ou o produto tem o valor de 100,00 já cadastrado no sistema, quanto eu for finalizar a venda posso dar um desconto de 10% 20%... e o valor já descontado já entraria na receita.

**Comment by Marcosaquino32** [comment]
Também seria bom ter o cadastro de produto com código de barra.

**Comment by marcotuliomtb** [comment]
sobre o desconto não está muito complicado fazer, quando vc lança o produto e vai faturar a venda vc pode alterar o valor a receber do cliente, então o sistema salva no bd o valor recebido no campo, daí é só usar a lógica para fazer os cálculos de desconto.

**Comment by melezinf** [comment]
Alguém sabe como fazer, quando altero o valor de algum serviço, não altere o mesmo valor do serviço dentro de uma OS já lançada. Tem como fazer??

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
