### ISSUE TITLE
mapos 4 disponível

### ISSUE THREAD

**Issue by Marcosaquino32** [RamonSilva20/mapos#326]
Olá, o mapos 4 já esta disponível para download?

**Comment by edgarmeireles** [comment]
Está em desenvolvimento ainda, mas se quiser baixar a versão teste, tem aqui no git. 

https://github.com/RamonSilva20/mapos/tree/mapos4

**Comment by Marcosaquino32** [comment]
Gostaria de acrescentar código barra na opção cadastro de produtos, e na
opção de venda o autocompleto pelo código de barra, estou disposto a pagar
pelo o serviço, aguardo um resposta!

Em ter, 9 de jul de 2019 19:50, Edgar Meireles <notifications@github.com>
escreveu:

**Comment by shimpato** [comment]
qual a previsão de lançamento da V4?

**Comment by shimpato** [comment]
instalei tudo certinho, mas nao sai da tela de login
Email: admin@admin.com
Senha: 123456

**Comment by psydown** [comment]
estou com o mesmo problema do shimpato  
creio que seja algum erro no script banco.sql  . Estou recebendo o seguinte erro 

./banco.sql: line 1: SET: command not found
./banco.sql: line 2: SET: command not found
./banco.sql: line 3: SET: command not found
./banco.sql: line 7: --: command not found
./banco.sql: line 8: ci_sessions: command not found
./banco.sql: line 8: --: command not found
./banco.sql: line 9: --: command not found
./banco.sql: line 10: syntax error near unexpected token `('
./banco.sql: line 10: `CREATE TABLE IF NOT EXISTS `ci_sessions` ('

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
