### ISSUE TITLE
Faturamento

### ISSUE THREAD

**Issue by renansmec** [RamonSilva20/mapos#328]
Bom dia, gostaria de saber como faço para finalizar uma venda e imprimir o recibo com o valor especificado na hora do faturamento.
Ex: Vendi um produto de R$ 10,00, e na hora de faturar a venda coloquei o valor de R$ 5,00. Porem quando vou imprimir o recibo o valor continua sendo R$ 10,00.

**Comment by fixeva2019** [comment]
whatsapp 77991924863

**Comment by renansmec** [comment]
> whatsapp 77991924863

seu contato não tem whatsapp

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
