### ISSUE TITLE
Migrando Versão

### ISSUE THREAD

**Issue by melezinf** [RamonSilva20/mapos#329]
Boa noite galera estou com dificuldade de migrar para a versão 3.5.3 a ultima.
Eu tenho a versão a versão 3.1.11

Alguém pode me explica como que faz?

Eu tentei migrar, deu erro nas OS e tbm problemas com acentuação!

Alguém pode me ajudar?

**Comment by melezinf** [comment]
Depois de varias tentativas consegui fazer a migração, mas estou tendo o seguinte problema, mas parte Ordens de Serviço se é alterado algo dentro da OS, algum valor.
/sistema-os/index.php/os - aqui o VALOR TOTAL não altera o valor , alguem sabe o pq?

**Comment by RamonSilva20** [comment]
Boa tarde. Se for o campo valorTotal no banco de dados, o mesmo não é usado. Grato.



At.te.

Ramon Silva.
 

    Em quarta-feira, 22 de maio de 2019 22:51:32 BRT, melezinf <notifications@github.com> escreveu:  
 
 
Depois de varias tentativas consegui fazer a migração, mas estou tendo o seguinte problema, mas parte Ordens de Serviço se é alterado algo dentro da OS, algum valor.
/sistema-os/index.php/os - aqui o VALOR TOTAL não altera o valor , alguem sabe o pq?

**Comment by melezinf** [comment]
Ramon Silva sabe me dizer pq Termo de Garantia some depois que importa o BD da versão 3.11, poderia me ajudar??

**Comment by willph** [comment]
> 
> 
> Ramon Silva sabe me dizer pq Termo de Garantia some depois que importa o BD da versão 3.1.11, poderia me ajudar??

O BD terá que ser atualizado

```
CREATE TABLE IF NOT EXISTS `garantias` (
  `idGarantias` INT NOT NULL AUTO_INCREMENT,
  `dataGarantia` DATE NULL,
  `refGarantia` VARCHAR(15) NULL,
  `textoGarantia` TEXT NULL,
  `usuarios_id` INT(11) NULL,
  PRIMARY KEY (`idGarantias`),
  INDEX `fk_garantias_usuarios1` (`usuarios_id` ASC),
  CONSTRAINT `fk_garantias_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
```
Caso ainda não tenha criado esta tabela.

Agora para ativar a opção do "**Termo Garantia**" no menu lateral, terá que ir em **CONFIGURAÇÕES>PERMISSÕES>** e depois clicar em "**Editar Permissão**" no usuário onde queira ativar.

só marcar as caixas 

Visualizar Garantia | Adicionar Garantia | Editar Garantia | Excluir Garantia
 
e clicar em **ALTERAR**.

**Comment by melezinf** [comment]
Muito obrigado!

**Comment by willph** [comment]
> 
> 
> Muito obrigado!

Resolveu?

**Comment by melezinf** [comment]
Sim resolvido, muito obrigado!
