### ISSUE TITLE
Lançamentos em branco.

### ISSUE THREAD

**Issue by heaccioly** [RamonSilva20/mapos#33]
Prezados,
Bom dia!

Está ocorrendo algum erro no sistema, que ao faturar uma OS, esta não aparece nada aba "lançamentos" em "financeiro".
O sistema insere o lançamento no banco, mas não a exibe.

Só aparece inserindo o lançamento manualmente pelo botão + Nova Receita, ou + Nova Despesa.
E também não aparece adicionando manualmente pelo banco.

Porém, ao gerar relatórios, todas os lançamentos são exibidos normalmente.

Estou tentando encontrar o problema.

**Comment by pedro-nunes** [comment]
Boa noite, ja tentou usar "Filtrar" e em "Período" e "Situação" usar "Todos" ?
No meu esta igual ao seu, porem quando filtro a busca aparece tudo
Quando vc clica em Lançamentos ele busca os lançamentos do dia atual a pesquisa e acho que tem algo errado com a data por que parece que o sistema esta um dia a frente.

**Comment by heaccioly** [comment]
Olá Pedro! Boa noite!
Primeiramente, obrigado pela ajuda!

Estava criando novos módulos no sistema esses dias, e parei para olhar os códigos do financeiro, como você comentou acho que tem algo de errado nas condições de exibição. Na verdade, achei o funcionamento do módulo um pouco confuso. Mas como estava focado em outra tarefa, acabei deixando passar.
Essa semana, vou tentar identificar a falha lá.

Vou ver se o Ramon, me adiciona como colaborador do projeto também.

Abs!
