### ISSUE TITLE
Existe algum tutorial de como fazer atualização do mapos ?

### ISSUE THREAD

**Issue by DiegoKerr** [RamonSilva20/mapos#331]
Quero atualizar mas tenho medo de perder minhas informações ja lançadas

**Comment by edgarmeireles** [comment]
Você tem alguma customização no seu Mapos ou usa a versão aqui do Git?
Se não tem nenhuma customização, faça um backup (Banco de dados e arquivos). Feito o backup, baixe a versão atualizada aqui do Git, execute o conteúdo dos arquivos da pasta UPDATES no phpMyAdmin para atualizar o banco (Veja qual é a sua versão atual e siga os arquivos um a um). 
Atualize os arquivos da pasta application/config/

Se tem customizações, primeiro vc precisa passar tudo para versão nova... se precisar chama aqui...

Confirma aí se tudo deu certo.

**Comment by DiegoKerr** [comment]
Voce poderia me ajudar na instalação pois penso que não vou conseguir

Em seg, 3 de jun de 2019 às 13:39, Edgar Meireles <notifications@github.com>
escreveu:

**Comment by DiegoKerr** [comment]
e eu tenho muitos dados no sistemanão posso perder


Em sex, 28 de jun de 2019 às 14:38, Kerr technology <
kerrinformatica@gmail.com> escreveu:

**Comment by DiegoKerr** [comment]
eu utilizo o sistema com o xamp qual seria o procedimento

Em sex, 28 de jun de 2019 às 14:39, Kerr technology <
kerrinformatica@gmail.com> escreveu:
