### ISSUE TITLE
Garantia - Dados incompletos, verifique os campos com asterisco.

### ISSUE THREAD

**Issue by Delta7pgm** [RamonSilva20/mapos#335]
Mesmo preenchendo os campos no momento de adicionar a garantia recebo o mesmo erro.

![01](https://user-images.githubusercontent.com/31080255/58490921-655f1480-8144-11e9-86d9-38582205e09f.png)

**Comment by willph** [comment]
Instalação do zero, ou atualizou?

**Comment by Delta7pgm** [comment]
Fiz a atualização

**Comment by willph** [comment]
Atualizou o Banco de dados também?

Criando a tabela necessária para o funcionamento da função "Termo Garantia"

**Comment by Delta7pgm** [comment]
O BD foi atualizado e criei as tabelas para confirmar se estava tudo ok mais não deu certo.

CREATE TABLE IF NOT EXISTS `garantias` (
  `idGarantias` INT NOT NULL AUTO_INCREMENT,
  `dataGarantia` DATE NULL,
  `refGarantia` VARCHAR(15) NULL,
  `textoGarantia` TEXT NULL,
  `usuarios_id` INT(11) NULL,
  PRIMARY KEY (`idGarantias`),
  INDEX `fk_garantias_usuarios1` (`usuarios_id` ASC),
  CONSTRAINT `fk_garantias_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

**Comment by Delta7pgm** [comment]
[backup29-05-2019 13-05-54.zip](https://github.com/RamonSilva20/mapos/files/3232748/backup29-05-2019.13-05-54.zip)

**Comment by willph** [comment]
> 
> 
> O BD foi atualizado e criei as tabelas para confirmar se estava tudo ok mais não deu certo.
> 
> CREATE TABLE IF NOT EXISTS `garantias` (
> `idGarantias` INT NOT NULL AUTO_INCREMENT,
> `dataGarantia` DATE NULL,
> `refGarantia` VARCHAR(15) NULL,
> `textoGarantia` TEXT NULL,
> `usuarios_id` INT(11) NULL,
> PRIMARY KEY (`idGarantias`),
> INDEX `fk_garantias_usuarios1` (`usuarios_id` ASC),
> CONSTRAINT `fk_garantias_usuarios1`
> FOREIGN KEY (`usuarios_id`)
> REFERENCES `usuarios` (`idUsuarios`)
> ON DELETE NO ACTION
> ON UPDATE NO ACTION)
> ENGINE = InnoDB;

E os arquivos também foi colocado na pasta e alguns tem que ser substituídos?

Se fez tudo corretamente era pra funcionar.

**Comment by Delta7pgm** [comment]
apaguei toda a instalação e coloquei todos os arquivos novos e fiz a atualização do banco.

**Comment by Delta7pgm** [comment]
> > O BD foi atualizado e criei as tabelas para confirmar se estava tudo ok mais não deu certo.
> > CREATE TABLE SE NÃO EXISTE `garantias`( 
> > `idGarantias`INT NOT NULL AUTO_INCREMENT, 
> > `dataGarantia`DATA NULL, 
> > `refGarantia`VARCHAR (15) NULL, 
> > `textoGarantia`TEXTO NULL, 
> > `usuarios_id`INT (11) NULL, 
> > PRIMÁRIA CHAVE ( `idGarantias`), 
> > ÍNDICE `fk_garantias_usuarios1`( `usuarios_id`ASC), 
> > CONSTRANTE `fk_garantias_usuarios1`
> > CHAVE ESTRANGEIRA ( `usuarios_id`) 
> > REFERÊNCIAS `usuarios`( `idUsuarios`) 
> > SOBRE APAGAR NÃO AÇÃO 
> > SOBRE ATUALIZAÇÃO SEM AÇÃO) 
> > ENGINE = InnoDB;
> 
> E os arquivos também foi colocado na pasta e alguns tem que ser substituídos?
> 
> Se fez tudo corretamente era pra funcionar.

Vou refazer uma instalação do 0 para vê onde está o problema e posto caso consiga

**Comment by willph** [comment]
> 
> 
> > > O BD foi atualizado e criei as tabelas para confirmar se estava tudo ok mais não deu certo.
> > > CREATE TABLE SE NÃO EXISTE `garantias`(
> > > `idGarantias`INT NOT NULL AUTO_INCREMENT,
> > > `dataGarantia`DATA NULL,
> > > `refGarantia`VARCHAR (15) NULL,
> > > `textoGarantia`TEXTO NULL,
> > > `usuarios_id`INT (11) NULL,
> > > PRIMÁRIA CHAVE ( `idGarantias`),
> > > ÍNDICE `fk_garantias_usuarios1`( `usuarios_id`ASC),
> > > CONSTRANTE `fk_garantias_usuarios1`
> > > CHAVE ESTRANGEIRA ( `usuarios_id`)
> > > REFERÊNCIAS `usuarios`( `idUsuarios`)
> > > SOBRE APAGAR NÃO AÇÃO
> > > SOBRE ATUALIZAÇÃO SEM AÇÃO)
> > > ENGINE = InnoDB;
> > 
> > 
> > E os arquivos também foi colocado na pasta e alguns tem que ser substituídos?
> > Se fez tudo corretamente era pra funcionar.
> 
> Vou refazer uma instalação do 0 para vê onde está o problema e posto caso consiga

Ok, por favor não colocar o backup do BD, por conter dados sensíveis.
Por motivo de segurança
