### ISSUE TITLE
Mudar numero da OS

### ISSUE THREAD

**Issue by AlyssonCabral** [RamonSilva20/mapos#336]
É possivel alterar o numero da OS

tinha um outro programa para gerar minhas OSs gostaria de dar continuidade no numero que parei no outro programa

ex comecar com 3000 em vez de 1

obrigado

**Comment by willph** [comment]
Sim tem.
Usando o comando sql, onde TABELA é o nome da tabela que deseja alterar.

ALTER TABLE tabela AUTO_INCREMENT = 3000;

**Comment by willph** [comment]
Conseguiu?

**Comment by AlyssonCabral** [comment]
me desculpe a demora em responder

funcionou sim, muito obrigado pela ajuda

**Comment by phlopes1406** [comment]
amigo estou com o mesmo caso, porem nao consegui alterar.. eu fiz o SQL assim, ele aplica mais nao segue a seguencia que quero.

ALTER TABLE os AUTO_INCREMENT = 1240;

o que estou fazendo errado? kkkk

**Comment by TVANDRA** [comment]
Boa tarde a todos. Desculpem toda ignorância. Mas sou totalmente leigo em programação e gostaria de fazer o mesmo questionado, alterar o numero da os pra iniciar com outro numero ao invés de 01, é possível alguém postar um passo a passo por aqui? não sei se é o local correto mas... Obrigado desde já pela atenção. Abraços!

**Comment by Pr3d4dor** [comment]
@TVANDRA Você tem que alterar o AUTO_INCREMENT da tabela OS.

**Comment by TVANDRA** [comment]
Muitíssimo obrigado @Pr3d4dor , deu certo ! Obrigado mesmo pela ajuda !!! Grande abraço !

**Comment by almron** [comment]
Isso fica no Banco de Dados. Não sei como você está utilizando a sua aplicação. Se for em modo local, abra o PhPMyAdmin em  http://localhost:8080/

Segue um print abaixo como exemplo.

![image](https://user-images.githubusercontent.com/49542923/227669098-e90864e6-01b9-4cf1-90e2-8db8a421253f.png)
