### ISSUE TITLE
OS Não Carrega depois de atualizar para 3.5

### ISSUE THREAD

**Issue by Hidrobr** [RamonSilva20/mapos#338]
Bom dia Pessoal, .. 
Estou tendo problemas para carregar a OS depois de atualizar os arquivos modificados da ultima semana. Aparentemente o resto esta em ordem mas OS da o seguinte erro: 
Esta página não está funcionando drpcreparos.000webhostapp.com não consegue atender a esta solicitação no momento.
HTTP ERROR 500
Subi 3.4 para 3.5
Alguem poderia dar uma luz?

**Comment by Hidrobr** [comment]
Subi todos arquivos novamente, com a mesma database. 3.4 para 3.5

**Comment by Hidrobr** [comment]
@Pr3d4dor Consegue me ajudar?

**Comment by Hidrobr** [comment]
tenho uma outra plataforma que esta dando esse erro depois de alterar a pasta config 
An Error Was Encountered
Unable to load the requested file: helpers/audit_helper.php

**Comment by willph** [comment]
Já atualizou o BD?
E todos os arquivos modificados desta atualização já foram substituídos?

Se substituir o arquivo config.php, tera que editar e inserir os dados manualmente.

$config[base_url] = 'url do config anterior'

$config[encryption_key] = 'valor do config anterior'

Procura as linha citadas.

**Comment by willph** [comment]
E o arquivo database.php se substituir esse arquivo, também terá que editar manualmente e inserir os dados novamente.

**Comment by Hidrobr** [comment]
Então @willph ja fiz esse processo por isso achei estranho não funcionar mais uma base que tenho.

eoutra coisa que tambem achei muito estranh é reinstalar desdo 0 e nao abrir o link de OS todos abrem menos Ordem de Serviço...

**Comment by willph** [comment]
Instalação do zero não funciona?

Testou em localhost com o xampp?

**Comment by Hidrobr** [comment]
não funciona...... =( @willph  
nao testei em xampp porque sempre uso servidor web e vai de boa

**Comment by Hidrobr** [comment]
ja mandei mensagem para o ramons em PV, vou aguardar para ver se é problema de regras... porque é uma mensagem de não funcionar,..

**Comment by Hidrobr** [comment]
@willph vcd teria a versão do 3.4 ou alguem.. pois perdi todos dados que estavam em um HD externo..

**Comment by Hidrobr** [comment]
Resolvido, realmente quando fui aplicar o updade copiei a base errada aplicou mas nao fez a atualização. Falta de atenção.. Vlw -  RS, Willph

**Comment by willph** [comment]
Tranquilo. Acontece.
😁
