### ISSUE TITLE
Campo cliente e responsável, desconfigurado na hora de imprimir.

### ISSUE THREAD

**Issue by vivaldodt** [RamonSilva20/mapos#341]
Olá, na hora de imprimir a Ordem de serviço algumas informações  como telefone e celular estão mudando de lugar

**Comment by willph** [comment]
Já foi corrigido nesse último pull request, aguarde aprovar pra atualizar sua versão.

**Comment by willph** [comment]
Pull Request aprovado, baixar a atualização e verificar se resolveu o seu problema.
