### ISSUE TITLE
Programador para modificações no sistema

### ISSUE THREAD

**Issue by vinizanini** [RamonSilva20/mapos#343]
Bom dia, utilizo já um sistema Mapos modificado pelo @RamonSilva20 , gostaria de utilizar em uma outra empresa, porem faria modificações, se algum programador tiver interesse no projeto, podemos conversar, Obrigado

**Comment by maycon1977** [comment]
Boa noite.
Tem como descrever as alterações que precisa? Não sou programador, mas alterei bastante coisa no sistema MAPOS que estou usando aqui na minha empresa...
