### ISSUE TITLE
Problema ao utilizar plugin Select2

### ISSUE THREAD

**Issue by splinterxsr** [RamonSilva20/mapos#344]
Estou tentando aplicar o Select2 aos selects, porém o mesmo nao funciona de forma alguma (fica todo desconfigurado), em outras versoes do mapos funcionava perfeitamente, foi adicionado alguma coisa nessa versao nova que esta causando incompatibilidade, agradeço se alguem puder ajudar

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
