### ISSUE TITLE
Programador para alterações

### ISSUE THREAD

**Issue by omeggawebsolucoes** [RamonSilva20/mapos#345]
Procuro um programador que tenha interesse em fazer um freela  
Poucas alterações no sistema!
Coisas simples de configuração e alguma alterações.
É um projeto social sem fins lucrativos que visa desburocratizar a revitalização das escolas publicas! Simples... Com esse sistema eu consgui gerenciar toda a logistica da parte de obra e prestação de serviço da secretaria de educação da cidade,  ele é ótimo, parabéns aos desenvolvedores!!!
O sistema consiste em uma tentativa de automatizar  e informatizar toda a logistica causando assim um melhor resultado nas obras.

Apesar de ser um projeto sem fins lucrativos disponho me a pagar pelo serviço!
O sistema ja esta rodando e sendo alimentado diariamente, mas precisa urgentemente de algumas alterações. 

Fico no aguardo de alguma resposta!!! Obrigado.

**Comment by maycon1977** [comment]
Boa noite.
Tem como descrever as alterações que precisa? Não sou programador, mas alterei bastante coisa no sistema MAPOS que estou usando aqui na minha empresa...

**Comment by omeggawebsolucoes** [comment]
Oi Boa Noite muito obrigado pela atenção!
Estou um pouco perdido por ter pouco conhecimento em .php  mas aos poucos
esta fluindo!
O Sistema com havia dito n visa fins lucrativos, apenas agilizar de alguma
forma as reformas nas escolas da cidade!
Eu mais de 190 escolas agradecemos a ajuda!

bom eu gostaria de alterar a palavra ( CLIENTES ) para ( ESCOLAS)   .
 (C0MPRAS) para ( ALMOXARIFE )   .   (DASHBOARD) para ( ESCRITORIO)

Os relatorios tambem nao estao saindo  só d erro, vi em alguns posts q se
eu instalasse o plugin do pdf o erro sumiria  mas isso nao deu certo!

O Formulario de cadastro de clientes preciso alterar o campo (CELULAR )
para ( RESPONSAVEL )
E ( ESTADO ) para ( SETOR ) pois as escolas sao divididas por setor  ao
todo a cidade é composta por 198 escolas e seus anexos!


eu baixei uma versao nova disponivel aqui no site  queria atualizar os
arquivos mas tenho medo de perder os cadastros ja realizados!!!


[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua, 5 de jun de 2019 às 23:14, maycon1977 <notifications@github.com>
escreveu:

**Comment by fixeva2019** [comment]
77991924863 whatsapp
