### ISSUE TITLE
ERRO NA IMPORTAÇÃO DE BANCO DE DADOS

### ISSUE THREAD

**Issue by fixeva2019** [RamonSilva20/mapos#346]
Eu faço o backup do bd de boa mas quando vou importar no phpmyadmin da erro  #1005 - Can't create table `banco`.`anexos` (errno: 150 "Foreign key constraint is incorrectly formed") (Details…)

**Comment by RamonSilva20** [comment]
Olá. Adicione as seguintes linhas no início e a outra no final do arquivo de backup para desabilitar a verificação de chaves. 

SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
