### ISSUE TITLE
BACKUP

### ISSUE THREAD

**Issue by fixeva2019** [RamonSilva20/mapos#348]
ERRO DO BACKUP 

A Database Error Occurred

Unsupported feature of the database platform you are using.

Filename: /home/vol11_1/epizy.com/epiz_24042939/htdocs/os/controllers/mapos.php

Line Number: 172

COMO RESOLVER???

**Comment by edgarmeireles** [comment]
Verifica se não é a versão do banco ou do PHP.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
