### ISSUE TITLE
Adicionar Nova Receita/Despesa

### ISSUE THREAD

**Issue by Ronierick** [RamonSilva20/mapos#350]
Pessoal. Estou com problemas a lançar uma nova despesa ou receita, no campo [cliente], quando digitamos o nome do cliente, o sistema não está efetuando a busca no banco de dados. Alguém sabe como resolver essa situação ? Isso se aplica para receita e despesas.

**Comment by ramonsousa89** [comment]
Não tem essa função feita.

**Comment by micheldor** [comment]
É bem fácil na verdade, basta copiar este código que colocarei abaixo dentro do arquivo "lancamentos.php".
testei aqui e funcionou.

<script type="text/javascript">
    $(document).ready(function() {
        $("#cliente").autocomplete({
            source: "<?php echo base_url(); ?>index.php/vendas/autoCompleteCliente",
            minLength: 1,
            select: function(event, ui) {
                $("#clientes_id").val(ui.item.id);
            }
        });

    });
</script>
