### ISSUE TITLE
Problema com login

### ISSUE THREAD

**Issue by renansmec** [RamonSilva20/mapos#351]
Bom dia,

hoje fui fazer a instalação do sistema no byethost e me deparei com um problema quando fui efetuar o login, onde quando digito o usuário e senha, o sistema só fica carregando e não avança.
alguém poderia dar uma ajudinha?

Segue imagem do erro

![image](https://user-images.githubusercontent.com/50914071/59686694-a332e400-91aa-11e9-9388-f7baed939035.png)

**Comment by phlopes1406** [comment]
amigo eu tive este problema com a kinghost, eu resolvi alterando a versão do PHP nas configurações do servidor

**Comment by renansmec** [comment]
> amigo eu tive este problema com a kinghost, eu resolvi alterando a versão do PHP nas configurações do servidor

hmm vou verificar, qual versão do PHP vc colocou?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
