### ISSUE TITLE
NUMERO INICIAL DA OS

### ISSUE THREAD

**Issue by phlopes1406** [RamonSilva20/mapos#352]
bom dia pessoal, eu gostaria de uma ajuda pra alterar o numero da primeira OS, no caso o sistema está começando na 1,  e gostaria de começar de onde parei que é a 1240... alguem poderia me ajudar?
o cadastro de cliente também

obrigado

**Comment by willph** [comment]
Se sua instalação for do zero é só alterar a linha 219 onde tem escrito `AUTO_INCREMENT = 1` e no lugar do 1 colocar o valor desejado, salvar e depois efetuar a instalação do mapos

**Comment by willph** [comment]
Agora se for para alterar uma tabela já existente.
Usando o comando sql, onde TABELA é o nome da tabela que deseja alterar.

```ALTER TABLE tabela AUTO_INCREMENT = 1240;```

**Comment by phlopes1406** [comment]
então amigo, no caso a tabela que preciso altera é a tabela os? campo idOs correto? eu tentei de diversas formas mais sempre tenho este erro:
ALTER TABLE os.idOs AUTO_INCREMENT = 1240;

Mensagens do MySQL : Documentação
#1146 - Tabela 'os.idos' não existe

**Comment by willph** [comment]
Tentou desta forma.

```ALTER TABLE os AUTO_INCREMENT = 1240;```

**Comment by phlopes1406** [comment]
perfeito! deu certo! muito obrigado

**Comment by willph** [comment]
De nada!
