### ISSUE TITLE
Não é possível acessar esse site

### ISSUE THREAD

**Issue by danillosouzaa** [RamonSilva20/mapos#353]
Gente me desculpe talvez pela burrice, eu sou leigo e iniciante então talvez esteja comentendo algum erro grotesco e idiota, mas preciso muito de ajuda.
Eu configurei o sistema todo baseado em um vídeo no youtube, coloquei a hospedagem local, mas quando vou abrir, ele aparece o erro que está no print. Na barra de endereço aparece que ele não coloca o link inteiro que deveria ser "http://localhost/os", aparece apenas "os/". Quando coloco o link manualmente na barra de pesquisa, abre o sistema mas com o erro "Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente. 
http://prntscr.com/o3n8l4

Desde já agradeço imensamente.

**Comment by willph** [comment]
Vá na pasta onde está o seu Mapos e acesse a pasta "application/config/"
E abra o arquivo "config.php"

Linha 28 e verificar se está assim:

```$config['base_url'] = 'http://localhost/os';```

**Comment by danillosouzaa** [comment]
Está exatamente desse jeito, eu tento entrar manualmente colocando "localhost/os" no navegador, ele entra no sistema mas com dizendo "Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente."

**Comment by willph** [comment]
Nesse caso substitua os arquivos index.php na pasta raiz, e os arquivos config.php e database.php la na pasta application/config/
Pelos arquivos originais daqui do github, siga os passos da instalação novamente, colocando os mesmos dados.
E no local onde coloca o link, não se esqueça, `http://localhost/os`.

Depois diga o resultado

**Comment by danillosouzaa** [comment]
Segui esse passos, mas agora quando vou fazer a instalação e coloco meu usuário aparece "Access denied for user 'danillo'@'localhost' (using password: YES)"

**Comment by willph** [comment]
Tem senha se BD?

Se tiver colocado senha, terá que preencher a senha.

**Comment by danillosouzaa** [comment]
Não, eu segui as suas orientações e botei os arquivos originais database, config e index na raiz, não alterei nada. Apenas abri

**Comment by willph** [comment]
Eu falo o banco de dados.

MySQL se tem senha.

**Comment by danillosouzaa** [comment]
Não, ele não tem senha
