### ISSUE TITLE
Erro depois da instalação  v.4

### ISSUE THREAD

**Issue by victorblah** [RamonSilva20/mapos#354]
Parse error: syntax error, unexpected T_CONST in /home/megaa951/blahprint.com.br/mapos/system/core/CodeIgniter.php on line 58

**Comment by willph** [comment]
Qual versão de php está instalada?

**Comment by victorblah** [comment]
cpsrvd 11.78.0.30
Versão do cliente de base de dados: libmysql - 5.1.73
Extensão de PHP: mysqliDocumentação curlDocumentação mbstringDocumentação
versão do PHP: 7.2.7

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
