### ISSUE TITLE
ProxySQL Error: Access denied for user 'user' (using password: YES)

### ISSUE THREAD

**Issue by danillosouzaa** [RamonSilva20/mapos#355]
Não consigo fazer a instalação, esse erro diz que não tenho permissão com o meu usuário...

**Comment by willph** [comment]
Existe esse usuário no banco de dados?
Ele tem senha?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
