### ISSUE TITLE
Grupo

### ISSUE THREAD

**Issue by higorrocha11** [RamonSilva20/mapos#356]
https://chat.whatsapp.com/IvrpB5x38YtIw4Oi87zwKf

**Comment by willph** [comment]
Já existe um grupo.

https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
