### ISSUE TITLE
Adicionar informações sobre o produto na o.s.

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#357]
Olá pessoal o sistema é muito bom, notei que ele possui uma tabela equipamentos no banco de dados porem não encontrei uma função que utilize ela e seria ótimo cadastrar no banco as informações de marca modelo e numero de serie do aparelho associado a O.S.

Desde já agradeço a todos os desenvolvedores deste projeto...

**Comment by Hidrobr** [comment]
@lrochawl algumas funções são da versão 4. que esta em desenvolvimento. (repassando informação.)

**Comment by fixeva2019** [comment]
whatsapp 77991924863

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
