### ISSUE TITLE
Não esta aparecendo o valor Total em serviços em alguns status 

### ISSUE THREAD

**Issue by Hidrobr** [RamonSilva20/mapos#358]
Bom dia, Blz? pessoal, verifiquei o código e aparentemente esta correto mesmo em development não aparece erro, alguém pode dar uma luz?
Não esta imprimindo o valor total das OS
    OBS: Só aparece em status de orçamento e finalizado- como fazer aparecer em todos....

**Comment by Hidrobr** [comment]
Caso alguém mais ache necessário segue o código.. mapos\application\views\os - imprimirOs

if($result->status == "Finalizado" || $result->status == "Orçamento" || $result->status == "Faturado" || $result->status == "Andamento" || $result->status == "Aberto"){
                                echo "<h4 style='text-align: right'>Valor Total: R$". number_format($totalProdutos + $totalServico, 2, ',', '.')."</h4>";

**Comment by fixeva2019** [comment]
whatsapp 77991924863

**Comment by willph** [comment]
É só remover o if, mais fácil.

Apesar que com o status de aberto não vejo necessidade de aparecer o valor  total 0.

Apenas em finalizado e orçamento.

**Comment by Hidrobr** [comment]
o ruim é o cliente ligar, perguntar..e o status em aberto, ver rápido e só ver o valor dos serviços e passar para o cliente sem os produtos... imagina a confusão...

**Comment by willph** [comment]
Pra isso tem o status "orçamento", cabe ao administrador do sistema alterar o status e preencher os valores.

**Comment by willph** [comment]
Mas você pode personalizar ao seu gosto, se remover o if ele aparece normalmente.
Não precisa adicionar vários OU.

Mas fique a vontade para fazer suas alterações necessárias.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
