### ISSUE TITLE
CONTROLLERS E MODELS

### ISSUE THREAD

**Issue by fixeva2019** [RamonSilva20/mapos#360]
Eu quero adicionar uma página no sistema, está página não será preciso mexer com banco de dados, mesmo assim vou ter que criar um arquivo model???

**Comment by Pr3d4dor** [comment]
Não é necessário criar um novo model se não tiver interação com o banco de dados.

**Comment by Ricky097** [comment]
estou a ter um problema nao consigo adicionar uma nova pagina no sistema (4.11.2)
