### ISSUE TITLE
Bom dia, não funciona o link OS alguem pode me ajudar por favor Obrigado

### ISSUE THREAD

**Issue by papaiisac** [RamonSilva20/mapos#361]

**Comment by papaiisac** [comment]
Esta página não está funcionando adonay.com.br não consegue atender a esta solicitação no momento.
HTTP ERROR 500

**Comment by papaiisac** [comment]
deletei todos aquivos do site, baixei a pasta atualizada subi os aquivos, fiz a configuração, só não funciona o link OS continuei com o mesmo DB, alguem pode me ajudar por favor Obrigado Bom dia, não funciona o link OS alguem pode me ajudar por favor Obrigado

**Comment by RamonSilva20** [comment]
Olá. Você executou os arquivos de update do banco de dados? Teve alterações em algumas tabelas.

**Comment by papaiisac** [comment]
bom dia, não fiz, como posso fazer onde encontro? valeu

**Comment by papaiisac** [comment]
obrigado Ramon Silva fiz uma pesquisa depois que vc disse que tinha que atualizar o BD e deu tudo certo obrigado
