### ISSUE TITLE
Troca telefone fixo por Celular

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#364]
Poderiam deixar o telefone residencial como um campo opcional e quando não existir tal informação, o sistema imprima o celular, tanto nos cadastros quanto nos relatórios impressos.

**Comment by willph** [comment]
Tem, um `if` resolveria, quando um campo vier null ou vazio ele preencher com o outro número.

**Comment by bulfaitelo** [comment]
Sim, sim, eu vou fazer a alteração (ainda to me habituando com o codeigniter), porem é necessário alterar tanto o cadastro de cliente quanto o cadastro de técnico, quanto o relatório, para que não seja uma gambiarra.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
