### ISSUE TITLE
Configurar mapos multiplas base_url

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#365]
É possivel configurar múltiplas URL's de acesso? 
Por exemplo, localmente eu acessaria por `http://mapos.test` e remotamente acessaria por `http://mapos.dominio.com.br` 
**OBS.:** *O exemplo abstrai a configuração de apache que já está configurada.*

**Comment by RamonSilva20** [comment]
Olá. Sim, é possível. Seria preciso no entanto fazer uma alteração no arquivo config.php, trocando a linha 28 pelo código abaixo. 

https://www.codeigniter.com/user_guide/installation/upgrade_303.html?highlight=base_url

```
$dominios_permitidos = array('mapos.test', 'mapos.dominio.com.br');
$dominio_padrao  = 'mapos.test';

if (in_array($_SERVER['HTTP_HOST'], $dominios_permitidos, TRUE))
{
        $dominio = $_SERVER['HTTP_HOST'];
}
else
{
        $dominio = $dominio_padrao;
}

if ( ! empty($_SERVER['HTTPS']))
{
        $config['base_url'] = 'https://'.$dominio;
}
else
{
        $config['base_url'] = 'http://'.$dominio;
}
```

**Comment by bulfaitelo** [comment]
Perfeito, obrigadão mano, eu vou fazer as personalizações pro meu caso, aqui muito obrigado.
