### ISSUE TITLE
Campo CPF/CNPJ

### ISSUE THREAD

**Issue by ClaytonAmorimCS** [RamonSilva20/mapos#366]
Boa noite Pessoal!
O campo cpf/cnpj está com a máscara meio estranha.
No formulário de cadastrar cliente se tu colocar cpf fica certo, mas cnpj fica desconfigurado, com um dígito a mais.
No formulário editar cliente só tem jeito de colocar cpf.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
