### ISSUE TITLE
Erro ao adicionar produto

### ISSUE THREAD

**Issue by tiagoalmeida10** [RamonSilva20/mapos#367]
Boa tarde
Estou tentando adicionar produtos e ou serviços na OS porém aparece o erro:
Ocorreu um erro ao tentar adicionar produto.

Isso ocorre também quando vou adicionar produtos em uma venda.

Obrigado desde já

**Comment by tiagoalmeida10** [comment]
Resolvido Pessoal. Rodei o script da versão 3.6.0

**Comment by Silmans** [comment]
Qual script? Estou com esse mesmo erro
