### ISSUE TITLE
atualizar da 3.5 pra versao mais nova

### ISSUE THREAD

**Issue by AlyssonCabral** [RamonSilva20/mapos#369]
como atualizar da versao 3.5 pra versao atual?
preciso rodar o script como esta no tutorial?

obrigado

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
