### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by BrunoMichael** [RamonSilva20/mapos#372]
O script não está querendo funciona em uma hospedagem teste minha.

**Comment by edgarmeireles** [comment]
Manda um print do erro ou de mais informações... fica mais facilnentender o que está acontecendo para poder resolver...

**Comment by BrunoMichael** [comment]
Nada acontece, criei os Cron na hospedagem. 

 `Enviar emails pendentes a cada 2 minutos.
        - */2 * * * * php /var/www/index.php email/process
    Enviar emails com falha a cada 5 minutos.
        - */5 * * * * php /var/www/index.php email/retry`
Ele não consegue executar os scripts.
O cron retornou que não é possível acessar.

**Comment by RamonSilva20** [comment]
O comando que coloquei é somente um exemplo, você tem que colocar o caminho até o arquivo index.php da pasta raiz do sistema, cada hospedagem tem um caminho diferente.

**Comment by BrunoMichael** [comment]
Certo, eu já tinha colocado o caminho da host mais não fiquei atento na versão do PHP, agora funcionou parou de chegar erro no email.
Só que o email nunca enviar. Além dos arquivos de configurações tem mais algum.

**Comment by Claudiomfa** [comment]
Boas.

Tenho dois servidores com este software. um deles não tenho a opção de cron jobs no cpanel e no outro utilizo o xampp no windows, há alguma forma de criar os cron jobs?

**Comment by RamonSilva20** [comment]
> 
> 
> Certo, eu já tinha colocado o caminho da host mais não fiquei atento na versão do PHP, agora funcionou parou de chegar erro no email.
> Só que o email nunca enviar. Além dos arquivos de configurações tem mais algum.
> Eu percebi que agora os status mudar, pendente, enviando e falhou.

@BrunoMichael ative os logs para saber o motivo da falha no arquivo config.php, linha 228 ($config['log_threshold'] = 0;) para o valor 2, os erros devem aparecer na pasta logs.

**Comment by RamonSilva20** [comment]
> 
> 
> Boas. @RamonSilva20
> 
> Tenho dois servidores com este software. um deles não tenho a opção de cron jobs no cpanel e no outro utilizo o xampp no windows, há alguma forma de criar os cron jobs?

No Windows você pode criar pelo agendador de tarefas. Solicite a sua hospedagem a configuração do cron job, já que não te forneceram a opção pelo cpanel.

**Comment by BrunoMichael** [comment]
Eu conseguir resolver os erros, aparentemente a hospedagem estava bloqueando alguma coisa no enviou ou na conexão. Obrigado pelo o Auxilio.
