### ISSUE TITLE
Como usar o sistema de e-mail

### ISSUE THREAD

**Issue by legionariodassombras** [RamonSilva20/mapos#376]
Prezados, boa tarde.
Como configurar o cron jobs para envio de e-mail?
Não entendi muito bem o que está descrito no site. Poderiam simplificar, por favor?
 Obrigado.

**Comment by RamonSilva20** [comment]
Você precisa criar um cron job em sua hospedagem que execute os comandos abaixo de envio e reenvio dos e-mails com falha. Também é necessário configurar o e-mail que será usado para envio, faça isso no arquivo email.php dentro da pasta config. 

**php /var/www/index.php email/process**
**php /var/www/index.php email/retry**

**Comment by igoatier** [comment]
bom dia amigo, mais desculpe minha falta de habilidade.
teria como vc descrever esse processo no meu caso uso o xampp local como meu servidor web.
como devo proceder para realizar essa configuração.

Conforme vc cita abaixo.
Você precisa criar um cron job em sua hospedagem que execute os comandos abaixo de envio e reenvio dos e-mails com falha. Também é necessário configurar o e-mail que será usado para envio, faça isso no arquivo email.php dentro da pasta config.

php /var/www/index.php email/process
php /var/www/index.php email/retry

**Comment by RamonSilva20** [comment]
@igoatier se sua instalação local for no windows então você precisará criar uma tarefa pelo agendador de tarefas do Windows, se for no Linux então será um cron job. 
Links úteis para você entender o funcionamento -> https://pt.stackoverflow.com/questions/129554/executar-script-php-no-agendador-de-tarefas-do-windows
https://pt.stackoverflow.com/questions/225600/o-que-s%C3%A3o-cron-jobs-e-como-usa-los-com-php

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
