### ISSUE TITLE
Sugestão cadastro único de cliente

### ISSUE THREAD

**Issue by willsantos07** [RamonSilva20/mapos#377]
Bom dia utilizo o sistema mapos em meu estabelecimento a quase 4 anos efetuei umas modificações simples para uso, uma modificaçao que tentei inplementar porem sem sucesso seria a opção de um único cadastro por cpf ou cnpj caso ja tenha cadastro ele retorne com um aviso
obs ate consegui deixar o cadastro unico para um determinado documento porem nao consigo editar o mesmo caso tenha que fazer alguma alteração de cadastro
outra alteracao interessante seria a busca de de clientes pelo cpf e por nome buscando qualquer um dos campos.
creio que seria de grande ajuda pois evitaria uma duplicação de cadastro no sistema.

**Comment by odemarjr** [comment]
boa noite
alterar arquivos application/controllers/Clientes.php
basta adicionar na linha 77

        $this->form_validation->set_rules(
        'nomeCliente', 'Nome','required|is_unique[clientes.nomeCliente]',
        array(
                'required'      => 'Campo %s vazio.',
                'is_unique'     => 'Já tem Cliente com este %s cadastrado.'
        )
);

        $this->form_validation->set_rules(
        'documento', 'CPF/CNPJ','required|is_unique[clientes.documento]',
        array(
                'required'      => 'Campo %s vazio.',
                'is_unique'     => 'Já tem Cliente com este %s cadastrado.'
        )
);

**Comment by Claudiomfa** [comment]
alterar conforme o necessário no ficheiro application/config/form_validation.php

Eu alterei o campo label=>CPJ para NIF porque em portugal utilizo o contribuinte da pessoa.

$config = array('clientes' => array(array(
                                	'field'=>'nomeCliente',
                                	'label'=>'Nome',
                                	'rules'=>'required|trim'
                                ),
								array(
                                	'field'=>'documento',
                                	'label'=>'NIF',
                                	'rules'=>'required|trim|is_unique[clientes.documento]'
                                ),
								array(
                                	'field'=>'telefone',
                                	'label'=>'Telefone',
                                	'rules'=>'required|trim|is_unique[clientes.telefone]'
                                ),
								array(
                                	'field'=>'email',
                                	'label'=>'Email',
                                	'rules'=>'required|trim|valid_email|is_unique[clientes.email]'

**Comment by willsantos07** [comment]
Obrigado @odemarjr  e @Claudiomfa  pelas respostas apenas incluindo o script postado pelo @odemarjr  ja resolveu meu problema
sobre a pesquisa em varios campos consegui resolver modificando o arquivo application/models/Mapos_model.php

adiconando o codico abaixo
`    function pesquisar($termo)
    {
        $data = array();
        // buscando clientes
        $this->db->like('nomeCliente', $termo);
        $this->db->or_like('documento', $termo);
        $this->db->limit(5);
        $data['clientes'] = $this->db->get('clientes')->result();`
achei em uma rapida pesquisa no google caso queira adicionar outro campo basta adicionar outra linha contendo o mesmo 'or_like'
