### ISSUE TITLE
Falha na gravacao de OS

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#378]
Boa tarde
Instalei a utlima versao ontem e estou encontrando dificuldade pois a gravacao da OS retorna um erro dizendo para eu ver os campos com asterisco mesmo estando todos preenchidos... alguma ideia? o restante esta gravando e lendo normalmente...

**Comment by RamonSilva20** [comment]
> 
> 
> Boa tarde
> Instalei a utlima versao ontem e estou encontrando dificuldade pois a gravacao da OS retorna um erro dizendo para eu ver os campos com asterisco mesmo estando todos preenchidos... alguma ideia? o restante esta gravando e lendo normalmente...

Utilize o autocomplete para vincular corretamente o cliente e o responsável à OS, ambos devem estar previamente cadastrados.

**Comment by crimat06** [comment]
Excelente! resolvido...vai abrir outra sobre edição de dados gravados... Obrigado!!!
