### ISSUE TITLE
Edicao de dados gravados no banco de dados

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#379]
Bom dia

Ate o momento tudo resolvido exceto a edição de dados gravados no sistema que não consigo editar depois de gravados. Nem clientes, nem produtos, nem serviços. Alguma ideia?

Obrigado!

**Comment by crimat06** [comment]
Curioso é que depois de aberto um cliente para editar por exemplo, eu edito o mesmo direto no banco de dados mas a pagina continua mostrando a versão sem edição... onde esta ficando essa versão anterior? Porque so mostra a versao da gravacao nunca a da edicao...

**Comment by crimat06** [comment]
fizemos uns testes com o pessoal da kinghost e achamos que pode ser o cache do sistema...onde fica?

**Comment by RamonSilva20** [comment]
> 
> 
> fizemos uns testes com o pessoal da kinghost e achamos que pode ser o cache do sistema...onde fica?

O cache do banco por padrão vem desabilitado, mas dê uma conferida no arquivo database.php.

**Comment by crimat06** [comment]
Boa tarde, exclui a pasta cache e problema resolvido!

obrigado!
