### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#38]
Boa noite!
Fiz a substituição dos arquivos no servidor, atualizei o banco de dados da versao 2 para 3, porem quando tento fazer login usando a senha 123456 ele fica passando a barra inferior em azul e não faz login, se tento 
a senha antiga do administrador da senha errada. 
 Alguém ja fez essa atualização?

**Comment by hardbrasil** [comment]
No meu tbm deu isso só que parece que ao tentar efetuar o login ele chama uma página de verificação de login que não foi encontrada.Você conseguiu resolver seu caso creio que seja o mesmo do meu.

**Comment by hardbrasil** [comment]
Amigo Ac Informática se eu resolver o meu aqui posto a solução pra vc caso resoilva o seu e puder me ajudar tbm, grato.

**Comment by RamonSilva20** [comment]
Vou verificar o que está ocorrendo.

**Comment by acinformatica2004** [comment]
Não consegui resolver nada, o meu não redireciona pra nenhum lugar. Muito estranho

**Comment by hardbrasil** [comment]
O ramon disse que está verificando. parece que ao logar como administrador ele encaminha para uma página que eu creio que seria para você al.terar senha e usuário de acordo com as novas politicas implantadas. O Ramom me corrija se eu estiver errado.



Att;



Sérgio C Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 12:26:04 -0300 acinformatica2004 &lt;notifications@github.com&gt; wrote ----




Não consegui resolver nada, o meu não redireciona pra nenhum lugar. Muito estranho

**Comment by RamonSilva20** [comment]
Encontrei o problema, remova a pasta system e faça upload novamente, por algum motivo somente a substituição não funciona.

**Comment by acinformatica2004** [comment]
Farei o teste. Posto depois o resultado.

**Comment by hardbrasil** [comment]
Ok, testarei tbm e reporto aqui.



Att;



Sérgio Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 12:43:17 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Encontrei o problema, remova a pasta system e faça upload novamente, por algum motivo somente a substituição não funciona.

**Comment by hardbrasil** [comment]
Tentei testar por baixo do meu servidor oficial em um subdominio chamado os e deu erro no code igniter que é este:







Strict Standards: require_once() [function.require-once]: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Sao_Paulo' for '-03/-3.0/no DST' instead in /home/hardbrasil/public_html/os/system/core/CodeIgniter.php on line 58



Parse error: syntax error, unexpected T_CONST in /home/hardbrasil/public_html/os/system/core/CodeIgniter.php on line 58





Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 12:43:17 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Encontrei o problema, remova a pasta system e faça upload novamente, por algum motivo somente a substituição não funciona.

**Comment by hardbrasil** [comment]
Testado com linkl desta maneira abaixo ao inserir o usuario adm e a senha passa mas da o erro de result citado


https://oshb.000webhostapp.com/index.php/mapos/verificarLogin



{"result":false,"message":""}







Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 12:48:19 -0300 acinformatica2004 &lt;notifications@github.com&gt; wrote ----




Farei o teste. Posto depois o resultado.

**Comment by RamonSilva20** [comment]
Está utilizando a senha 123456 @hardbrasil? Acho que vou mudar o reset de senha para todos os usuários que estiverem no banco.

**Comment by acinformatica2004** [comment]
Acho que mudar a senha seria uma boa. Ai todos ficariam com a senha 123456

**Comment by hardbrasil** [comment]
usei 123456 somente sem o @.......









Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 15:56:35 -0300 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Está utilizando a senha 123456 @hardbrasil? Acho que vou mudar o reset de senha para todos os usuários que estiverem no banco.

**Comment by hardbrasil** [comment]
Tbm está duplicando o link: https://oshb.000webhostapp.com/oshb.000webhostapp.com/index.php/mapos/login






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Sex, 30 jun 2017 16:02:13 -0300 acinformatica2004 &lt;notifications@github.com&gt; wrote ----




Acho que mudar a senha seria uma boa. Ai todos ficariam com a senha 123456

**Comment by acinformatica2004** [comment]
Boa noite, consegui atualizar o sistema. Ao tentar mudar a senha do usuário da o seguinte erro.

Unable to access an error message corresponding to your field name Nome.(xss_clean)

Unable to access an error message corresponding to your field name RG.(xss_clean)

Unable to access an error message corresponding to your field name CPF.(xss_clean)

Unable to access an error message corresponding to your field name Rua.(xss_clean)

Unable to access an error message corresponding to your field name Número.(xss_clean)

Unable to access an error message corresponding to your field name Bairro.(xss_clean)

Unable to access an error message corresponding to your field name Cidade.(xss_clean)

Unable to access an error message corresponding to your field name Estado.(xss_clean)

Unable to access an error message corresponding to your field name Email.(xss_clean)

Unable to access an error message corresponding to your field name Telefone.(xss_clean)

Unable to access an error message corresponding to your field name Situação.(xss_clean)

Unable to access an error message corresponding to your field name Permissão.(xss_clean)

E também com erro de timezone.

Alguém enfrentando o mesmo problema?

**Comment by RamonSilva20** [comment]
Nova atualização do sistema para correção dos problemas com xss_clean, timezone e reset de senhas dos usuários da versão 2.x.

**Comment by acinformatica2004** [comment]
fiz a atualização e a tela de login ficou toda desconfigurada e ao tentar fazer login da pagina não encontrada e na barra de url duplica a url.

**Comment by acinformatica2004** [comment]
Bom dia! Alguém fez essa nova atualização? Só pra saber se deu o mesmo problema.

**Comment by hardbrasil** [comment]
Isso ocorreucomigo tbm.


Hard Brasil Assistência Multimarcas & Multiserviços
Eletrônica - Eletrodomésticos - Eletroportáteis - Informática
Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.
Atendimento ao público:
Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs

Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)
contato@hardbrasil.com.br   www.hardbrasil.com.br


---- On Sáb, 01 jul 2017 09:08:40 -0300 notifications@github.com wrote ----

fiz a atualização e a tela de login ficou toda desconfigurada e ao tentar fazer login da pagina não encontrada e na barra de url duplica a url.

**Comment by RamonSilva20** [comment]
Fiz a correção do problema na tela de login.

**Comment by acinformatica2004** [comment]
bom dia Ramon, fiz a atualização novamente e deu o mesmo problema, porem quando digito a url ela duplica. Ai excluo a duplicada ele cia na tela de login toda desconfigurada. Tento fazer login e da pagina não encontrada.
![login](https://user-images.githubusercontent.com/29789157/27792573-c66b6bd0-5fd0-11e7-9896-6715b8d6d984.png)
![pagina](https://user-images.githubusercontent.com/29789157/27792588-deff9bbc-5fd0-11e7-98cd-a728e6580c42.png)

**Comment by hardbrasil** [comment]
Tentei atualizar sabado e dá erros no PHP:



A PHP Error was encountered

Severity: Warning

Message: mysqli::real_connect(): (HY000/2002): Connection refused

Filename: mysqli/mysqli_driver.php

Line Number: 201


A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: controllers/Mapos.php

Line Number: 13












Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Seg, 03 jul 2017 09:20:42 -0300 acinformatica2004 &lt;notifications@github.com&gt; wrote ----




bom dia Ramon, fiz a atualização novamente e deu o mesmo problema, porem quando digito a url ela duplica. Ai excluo a duplicada ele cia na tela de login toda desconfigurada. Tento fazer login e da pagina não encontrada.

**Comment by hardbrasil** [comment]
Após atualizar a versão e rodar o script de atualização do BD com sucesso o próximo erro foi a duplicação do link: https://oshb.000webhostapp.com/oshb.000webhostapp.com/index.php/mapos/login

**Comment by hardbrasil** [comment]
Mesmo retirando a duplicação do link nota-=se que:

1- Tela de Login Desconfigurada
2- Nova Duplicação de Link: https://oshb.000webhostapp.com/index.php/mapos/oshb.000webhostapp.com/index.php/mapos/verificarLogin

**Comment by hardbrasil** [comment]
E no terceiro teste removendo a nova duplicação de links ele não encontra a página ao chamar o Verificar Login conforme abaixo:


https://oshb.000webhostapp.com/mapos/verificarLogin

404. That’s an error.
The requested URL was not found on this server.

**Comment by RamonSilva20** [comment]
Façam um teste por gentileza, excluam as pastas, application e system e façam o upload novamente. Fiz a atualização duas vezes depois das correções, não tive problemas. Anotem as configurações de banco de dados para não terem problemas.

**Comment by acinformatica2004** [comment]
Boa tarde Ramon! Tentei ver se solucionava o problema e não consegui. Vc viu as telas que postei? Conseguiu achar alguma solução? 
Obs.: não estou cobrando, apenas tentando ajudar, pois utilizo o sistema e é muito útil pra mim.

**Comment by acinformatica2004** [comment]
Eu fiz upload de td, apaguei o antigo e subi td. Mesmo assim deu erro.

**Comment by hardbrasil** [comment]
No meu caso tb apaguei tudo e refiz umas 5x ainda dá erro, vou fazer novamente. Por acaso vc está usando um servidor local ou remoto para os testes Ramon? Creio na minha ignorância que talves possa ter alguma influência sobre os erros.

**Comment by hardbrasil** [comment]
Sugestão: Seria bom tbm ativar a demo do site para que possamos ver as alterações feitas antes de atualizar ou alterar o sistema.

**Comment by hardbrasil** [comment]
Não deu certo o meu ainda apaguei as 2 partes citadas upei as pastas novamente e continua na mesma os erros.

**Comment by hardbrasil** [comment]
Testei em 3 servidores web diferentes e dá o mesmo erro nos 3

**Comment by hardbrasil** [comment]
Resolvido o primeiro problema da duplicação de links: Na pasta application/config edite o arquivo config php com o endereço completo até chegar ao arquivo index php exemplo: https://oshb.000webhostapp.com/index.php/mapos/login/index.php neste caso quando acessei meu servidor : https://oshb.000webhostapp.com  ele já caiu normalmente na tela de login:

Logo


Email
 
Senha
 Acessar
×
MapOS

Os dados de acesso estão incorretos, por favor tente novamente!

Fechar

Porém conforme pode-se verificar acima usando o login admin@admin.com senha 123456 cai na parte de verificação de login e não dá opção de criar nova senha ou entrar no sistema.
* Ressalto que baixei hoje a versão atual completa do sistema upei a mesma e os testes foram feitos por ela.
* Nota-se também que por algum motivo realmenter a tela de login também apresenta-se desconfigurada estando centralizada á esquerda da tela, não sei se este fator tem a ver coma falta da logo mas estarei testando e comunico aqui.

**Comment by hardbrasil** [comment]
Estou instalando no Xampp e posto o resultado aqui.

**Comment by acinformatica2004** [comment]
Boa noite, aqui continua o mesmo problema. Agora não sei como proceder. Tela de login desconfigurada e duplicação de url.

**Comment by RamonSilva20** [comment]
O base_url está preenchido no arquivo config.php acinformatica2004?

**Comment by acinformatica2004** [comment]
Esta sim, ordemservico.advancedcomputer.com.br. Esta desse jeito.

**Comment by RamonSilva20** [comment]
Tentei acessar agora esta url para ver o problema e está com dando erro, está faltando arquivos na pasta system. Tem como você corrigir para eu avalizar a questão da tela de login?

**Comment by acinformatica2004** [comment]
vou subir os arquivos novamente, pq havia tirado. ja te aviso

**Comment by acinformatica2004** [comment]
opa, se quiser fazer o teste pode. Já fiz upload com a atualização que acabou de fazer.

**Comment by RamonSilva20** [comment]
O base_url deve começar com http:// e terminar com a barra. No seu caso dever ficar como abaixo.
http://ordemservico.advancedcomputer.com.br/

**Comment by acinformatica2004** [comment]
Show de bola, acertou em cheio o erro. Valeu

**Comment by hardbrasil** [comment]
O meu agora a tela de login carregou ok mas apresenta o erro: A PHP Error was encountered

Severity: Notice

Message: Undefined variable: mimes

Filename: core/Output.php

Line Number: 107

**Comment by acinformatica2004** [comment]
O meu aqui rodou 100%, vc fez a última atualização que o ramon colocou do arquivo config.php?

**Comment by acinformatica2004** [comment]
Ramon, única coisa que aqui não está fazendo é procurar os clientes pra adicionar OS ou fazer venda, o tecnico responsavel tbm não esta listando.

**Comment by hardbrasil** [comment]
Como restauro o backup que esta em  sql zipado sendo que no backup ja faz backup automatico e n tem vopçao de restaurar nas versões anteriores eu restaurava direto pelo bd e dava certo agora da erros.

**Comment by RamonSilva20** [comment]
Já corrigi o problema de não estar pesquisando na OS acinformatica2004. O arquivo atualizado foi o Os_model.php

**Comment by RamonSilva20** [comment]
hardbrasil, para restaurar o banco de dados você precisará adicionar o código abaixo no início e no fim respectivamente do arquivo de backup. Em futuras atualizações vou corrigir isso. Grato.

SET FOREIGN_KEY_CHECKS=0;

SET FOREIGN_KEY_CHECKS=1;

**Comment by acinformatica2004** [comment]
Bom dia Ramon. O de vendas tbm foi corrigido?

**Comment by RamonSilva20** [comment]
Bom dia. Realmente deixei passar o de vendas, corrigi agora. Grato.  O arquivo atualizado foi o Vendas_model.php

**Comment by Totonho** [comment]
Esta dando o seguinte erro ao tentar cadastrar um novo usuario ou alterar a senha do admin. 


Fatal error: Call to undefined method CI_Encrypt::sha1() in C:\xampp2\htdocs\mapos\application\controllers\Usuarios.php on line 94
A PHP Error was encountered

Severity: Error

Message: Call to undefined method CI_Encrypt::sha1()

Filename: controllers/Usuarios.php

Line Number: 94

**Comment by acinformatica2004** [comment]
boa noite, a impressao de ordem de serviço e de venda é possivel diminuir o tamanho, pois ficou muito grande.

**Comment by acinformatica2004** [comment]
Ramon, na parte de ordem de serviço, quando vc coloca a opcao selecione status, ele mostra apenas a primeira pagina com o determinado status, ja na segunda ele volta ao normal, isso tem como corrigir?

**Comment by hardbrasil** [comment]
O meu com muito custo deu certo aqui.
A versão 3.1.4 comtempla ao certo quais alterações visíveis?
Percebi de cara apenas a área do cliente ao cadastrar OS ainda não tem n de seríe tipo e marca do equipamento não?

**Comment by RamonSilva20** [comment]
@acinformatica2004 não fiz alterações na impressão da OS. Sobre o problema da pesquisa e paginação vou deixar assim por enquanto, vou focar mais no desenvolvimento da nova versão.

**Comment by RamonSilva20** [comment]
@hardbrasil esta versão 3 teve o objetivo de atualizar o framework, além da área de cliente não adicionei nenhuma funcionalidade, pois estou trabalhando em uma nova versão. Estou somente colocando os itens principais e disponibilizarei aqui para que todos que queiram possa contribuir. Grato.

**Comment by hardbrasil** [comment]
Ok, obrigado.

**Comment by acinformatica2004** [comment]
Ramon, blz. Eu entendo seu foco e admiro o sistema que está fazendo. Teria como tirar uma dúvida sobre a área do cliente. Vc pretende do colocar um link para o cliente acessar na tela de login? Eu acessei a área do cliente e vi que ele pode adicionar ordem de serviço, acho isso ruim, pois ali seria mais pra ele acompanhar sua vida junto a empresa e autorizar as ordens de serviço. Estou errado na monha opinião?

**Comment by RamonSilva20** [comment]
@acinformatica2004 sobre a área do cliente vária muito, alguns preferem esta opção e outros não, o ideal é que tenha a opção de configurar a área de cliente e o administrador define se pode ou não. Vou me lembrar de adicionar isso na nova versão.

**Comment by acinformatica2004** [comment]
Isso seria ótimo se o administrador puder definir o que pode ou não. O site demo não está acessando, seria bom pra gente ver as atualizações feitas. Parabéns pelo seu trabalho e também pela preocupação em resolver os problemas encontrados.

**Comment by hardbrasil** [comment]
O meu sistema está Rodando sobre uma Hospedagem Gratuita Hostinger. Está OK. A Hostinger encerrou as hospedagens gratuitas e agora está cobrando mas taxas pequenas para as hospedagens. Testei em outros hosts gratuitos porém estes deram erros com os scripts de BD que no Hostinger tbm deu e que resolvi Pegando backup antigo somente do BD com as tabelas e depois peguei uma cópia do meu BD compactada e voltei esta . Daí deu certo. Vou testar em outros hosts e vou postando os resultados aqui. Se alguém puder comentar as experiências nesse sentido tbm na minha opinião acho bacana isso.

**Comment by hardbrasil** [comment]
Ah ia esquecendo de comentar. Fiz o Upload pelo metódo de importação do site inteiro automatico que tem disponível no Hostinger.

**Comment by acinformatica2004** [comment]
boa noite @RamonSilva20, é dificil alterar o tamanho da fonte da impressão da os e da venda? Tem como me dar uma dica? Obrigado

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004. Com algumas linhas de CSS é possível diminuir o tamanho da fonte. Os arquivos são visualizarOs e visualizarVenda.

**Comment by acinformatica2004** [comment]
Tem alguma linha de código pra alterar, tenho o dreamwaver aqui no pc?

**Comment by acinformatica2004** [comment]
Boa tarde Ramon, na parte financeiro, se coloco um pagamento futuro e depois coloco pra filtrar Todos/pendente esse lançamento não aparece.

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20, sobre a parte financeiro ai está com o mesmo erro? Obrigado

**Comment by RamonSilva20** [comment]
Bom dia @acinformatica2004, na demo está funcionando corretamente. Somente os pendentes estão com problemas?

**Comment by acinformatica2004** [comment]
Sim, somente os pendentes

**Comment by acinformatica2004** [comment]
Boa tarde @RamonSilva20, eu não consigo acessar o site demo. Já tentei subir os arquivos novamente e nada. Se quiser dar uma olhada no meu sistema te passo os dados para ver. Obrigado

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20, ja fiz upload dos arquivos novamente e nada de aparecer os pendentes. Alguém tem esse problema? Na parte financeira para mostrar todos os pendentes ele mostra só alguns? Obrigado desde já

**Comment by Leadership** [comment]
o meu apresanta o seguinte erro:
```
A PHP Error was encountered

Severity: Core Warning

Message: Module 'mcrypt' already loaded

Filename: Unknown

Line Number: 0
```

**Comment by rm1mar** [comment]
Prezado Ramom, muito prazer sou Roberto Meira.
Acho que já fiz e refiz o sistema umas 30 vezes sem exagero.
Não loga de jeito nenhum ....as vezes fica uma barra tipo processando....outras vezes já dá a mensagem de login incorreto.

**Comment by rm1mar** [comment]
![image](https://user-images.githubusercontent.com/36328785/36115775-459cd682-101b-11e8-96e7-b4ecae653555.png)

**Comment by RamonSilva20** [comment]
Boa tarde @rm1mar. Já verificou se os requerimentos de funcionamento do sistema estão de acordo?

Requerimentos:
- PHP = 5.4.0 <= 5.6.x
- Extensão Mcrypt ativada

**Comment by rm1mar** [comment]
Olá Ramon, somente para constar meu servidor é windows.
estou com a versão 7 do php.
no arquivo php.ini não encontro a estensão Mcrypt.
Poderia me dar mais esta dica?

**Comment by RamonSilva20** [comment]
O Mcrypt foi removido da versão 7, por isso que tem que ser até a versão 5.6.

**Comment by rm1mar** [comment]
Prezado Ramon, fiz conforme você me orientou, volteu pra versão 5.6.x, funcionou perfeitamente.
Quero aproveitar para agradecer e lhe parabenizar pela disponibilidade com que você me respondeu.
Forte abraço!

**Comment by rm1mar** [comment]
Prezado Ramon, somente para constar....sistema acesas normalmente fiz vários cadastros de clientes etc..
Porém toda vez que tento criar uma OS recebo a mensagem:
Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente e responsável.

**Comment by rm1mar** [comment]
Ramon, no próprio site da DEMO, também ocorre o problema ao preencher OS, será que estou fazendo algo errado?
abraços!

**Comment by rm1mar** [comment]
Peço desconsiderar as mensagens anteriores, era problema no chrome. fiz com o internet explorer e foi.
abraços!

**Comment by laumneto** [comment]
Boa tarde Ramon.
Estou utilizando tanto o 3.12 qto o 4 e sempre dá o erro do Message: mysqli::real_connect(): Headers and client library minor version mismatch. Headers:50173 Library:50312
Filename: mysqli/mysqli_driver.php

Como eu resolvo isso !????

**Comment by luizdeltasouza** [comment]
![mapos](https://user-images.githubusercontent.com/52639456/60808880-b7418400-a15f-11e9-8cc8-364b0730880a.jpg)

**Comment by RamonSilva20** [comment]
> Boa tarde Ramon.
> Estou utilizando tanto o 3.12 qto o 4 e sempre dá o erro do Message: mysqli::real_connect(): Headers and client library minor version mismatch. Headers:50173 Library:50312
> Filename: mysqli/mysqli_driver.php
> 
> Como eu resolvo isso !????

Isso é um problema no seu ambiente. Provavelmente seu PHP foi compilado para uma versão do MySQL, mas agora deve estar conectando uma biblioteca mysql com outra versão. Você tem que atualizar o PHP para uma versão com suporte ao MySQL instalado ou utilizar uma versão MySQL que sua versão do PHP suporte. Você está usando localmente?

**Comment by RamonSilva20** [comment]
> ![mapos](https://user-images.githubusercontent.com/52639456/60808880-b7418400-a15f-11e9-8cc8-364b0730880a.jpg)
> 
> ESTÁ DANDO ESTE ERRO date.timezone

Você precisa configurar o timezone no arquivo php.ini.

**Comment by Fernando-Martins-Leal** [comment]
Bom dia, Ramon. 

Apanhando aqui para achar onde fica o cron job para configurar disparo de e-mails. Não achei em nenhuma busca. Meu Mapos não está disparando os e-mails, todos ficam "pendentes".

Pode me dar uma força?

Obrigado.
Fernando

**Comment by FabianaBras** [comment]
Bom dia Ramom, teria um jeito de colocar vários itens para visualizar a venda ?

Adicionei linhas , mas quando lança não gera no relatório
