### ISSUE TITLE
Adicionar nome na aba do navegador

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#381]
Boa noite

Gostaria de saber onde editar para mudar a aba do navegador de "Map OS" para "TOPBOX - Map OS". 

Obrigado

**Comment by renato-ck** [comment]
application/views/tema/topo.php
linha 4

**Comment by crimat06** [comment]
deu certo!! mas ainda quando entra como cliente o nome da assitencia nao aparece em cima...
