### ISSUE TITLE
Contribuição e dúvida.

### ISSUE THREAD

**Issue by mikxingu** [RamonSilva20/mapos#383]
Bom dia!! Gostaria de agradecer primeiramente pelo trabalho de vocês e do Ramon por ter criado esse maravilhoso sistema. Uso ele a 1 ano e pouco, sempre me atendeu muito bem, a cada atualização são criadas ótimas funcionalidades, e eu tenho duas perguntas:
1º - Posso contribuir fazendo um manual para o sistema? Tava pensando em criar um manual em PDF ensinandoo a instalar no Linux, Windows, ensinando a atualizar o sistema, e explorar as funcionalidades dele.

2º - Por ser um sistema open source, sei que não posso vendê-lo. Mas por ser um sistema completo, fiquei pensando em explorar a implantação para clientes e aprender programação para customizar o sistema e cobrar por essa customização. Gostaria de saber se posso fazer isso.

Mais uma vez, agradeço pelo trabalho e pela atenção.

**Comment by RamonSilva20** [comment]
Boa tarde. Seria bem-vinda a contribuição, ajudaria bastante, mas acho que seria interessante outro formato. Sobre o segundo questionamento, a licença do MIT é bem permissiva e o que pretende fazer não tem nenhum problema.

**Comment by mikxingu** [comment]
Entendi. Obrigado pela resposta. Quanto ao manual, alguma sugestão de como seria melhor?

**Comment by RamonSilva20** [comment]
Estou considerando utilizar o BookStack. É uma ferramenta open source e acho que seria interessante para mantermos. O que acha?

https://github.com/BookStackApp/BookStack

**Comment by mikxingu** [comment]
Achei bacana. Vou dar uma fuçada e subir uma instância pra testar. Te mantenho informado sobre o progresso.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
