### ISSUE TITLE
HORA nos logs de auditoria

### ISSUE THREAD

**Issue by Silmans** [RamonSilva20/mapos#384]
Oi pessoal, gostaria de saber como faço para alterar a hora para atual nos logs de auditoria, pois o horário que aparece lá é de outro fuso horário, como altero o fuso horário do sistema?

**Comment by mikxingu** [comment]
Se nao me engano vc tem que alterar o Timezone na configuração do PHP.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
