### ISSUE TITLE
Problema com email

### ISSUE THREAD

**Issue by alexhackers** [RamonSilva20/mapos#387]
Eu tentei de tudo instalar email com cron mas infelizmente não tive sucesso, não executou cron nem nd, tem alguma forma de fazer o envio dos emails sem cron? só enviar direto qnd clicar na opção? ou algum tutorial bom para o cron

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
