### ISSUE TITLE
Contribuição com o código

### ISSUE THREAD

**Issue by silvanoxavier** [RamonSilva20/mapos#388]
gostaria de parabenizar pelo desenvolvimento
gostaria de efetuar algumas  algumas alterações e não estou conseguindo, teria como me ajudar?gostaria de saber como fazer para incluir uma tabela com os dados dos vendedores, e colocar um select box na parte de vendas para selecionar estes vendedores

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
