### ISSUE TITLE
Depois da Atualizacao para 3.8 OS nao abre... da que a pagina nao esta funcionando

### ISSUE THREAD

**Issue by AllysonFredMed** [RamonSilva20/mapos#389]
boa tarde, galera esperta... depois que atualizei para a versao 3.8 a pagina de OS nao abre... dis que a pagina nao esta funcionando. ja fiz de tudo. ja atualizei banco , arquivos,, verigfiquei as url e nada.... sera ue alguem poderia me ajudar com alguma dica.... o resto funfa legal menos a OS

**Comment by RamonSilva20** [comment]
@AllysonFredMed executou os arquivos de update do banco correspondente com a versão?

**Comment by AllysonFredMed** [comment]
Resolvido....
Como eu fiz... pode ajudar a outros.... fazendo a atualizacao normal conforme informado a aba OS nao abria...
Entao fiz o backup do banco , criei uma nova instalacao e depois importei o banco....

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
