### ISSUE TITLE
Novos Recursos de Versão - Após Atualização

### ISSUE THREAD

**Issue by hardbrasil** [RamonSilva20/mapos#39]

**Comment by hardbrasil** [comment]
Acesse o vídeo e veja a demonstração daárea do cliente onde o mesmo pode verificar o andamento de suas ordens, cadastrar pré ordem de serviços,. alterar dados, imprimir cópia das ordens.

https://youtu.be/yDILRt2u7uc

**Comment by hardbrasil** [comment]
Seria bacana se ao cadastrar nova ordem ou alterar o status da mesma o sistema "disparasse" um e-mail para o cliente que tivesse cadastrado e-mail.

**Comment by hardbrasil** [comment]
**# DADOS DE CONTATO DO CLIENTE NA IMPRESSÃO E VISUALIZAÇÃO DE OS.**

No momento ao imprimir as ordens não aparecem os dados de contato do cliente o que faz muita falta, ao imprimir ou consultar ordens deveria aparecer os dados de contato facilitando assim processos internos.

**Comment by marcelo9716** [comment]
magnifico!!!! muito bom!!!!!
