### ISSUE TITLE
Usuário ou senha invalido

### ISSUE THREAD

**Issue by darkstilo** [RamonSilva20/mapos#390]
Não consigo acessar o painel, está dando que o usuário ou senha estão incorretos.

Estou usando o padrão

Usuário email: admin@admin.com
Senha: 123456

**Comment by phsilvasantos** [comment]
tabem estou com mesmo problema

**Comment by phsilvasantos** [comment]
resolvido e a criptografia 
adm@adm.com  senha 123456 usar a linha de baixo toda	$2y$10$3.swAJFPAwWfi4YkIhngfuvWPtA5vbRxXqxAwbS5WG2mXL//eZ.Rq

**Comment by eduaraujothe** [comment]
Estou com o problema, está dando usuário expirado e as vezes os dados de usuários estão incorretos.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
