### ISSUE TITLE
Passo a passo de como fazer Cron Job no Windows?

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#392]
Pessoal, alguém poderia explicar um passo a passo ai de como configuro para mandar email para meu cliente?

Vi a explicação do Ramon mas não entendi onde coloco aqueles códigos, em que arquivo php para poder criar essa tarefa!

php /var/www/index.php email/process
php /var/www/index.php email/retry

**Comment by willph** [comment]
Via xampp?

**Comment by brtechst** [comment]
Isso, via Xampp.

Na verdade eu queria criar uma rotina no windows para todos os dias ele fazer um alerta para os cliente sobre o status da OS, e quando eu clicar naquele email dentro do sistema ele tbm enviar.

**Comment by willph** [comment]
Problema resolvido.

O @brtechst irá postar aqui como foi feito.

**Comment by brtechst** [comment]
@willph Você é fera e obrigado mais uma vez pela ajuda!

Seguinte, estava sem entender como enviar os emails mas após sucessivos testes junto com o Willph conseguir, para quem ainda não entendeu vai um breve resumo.

1º PASSO: No meu caso meu email é o Gmail e foi necessário desativar a segurança do Gmail para que os emails fossem enviados, se seu email for Gmail segue link para desativar: https://myaccount.google.com/u/0/lesssecureapps?pli=1

2º PASSO: Vá nas configurações para deixar seu email cadastrado dentro de application\config\email.php e faça a configuração do seu email, se for Gmail já estará pronto e será necessário só colocar email e senha, se for outro email tem que configurar de acordo com seu provedor.

3º PASSO: Vá nas configurações dentro do seu mapos aberto: configurações>permissões>editar opções administrador e marca a opção EMAIL, segue abaixo imagem:
![image](https://user-images.githubusercontent.com/53625745/62422474-c5fd5700-b689-11e9-85b3-a562cb4c296c.png)

4º PASSO: Dentro da pasta raiz do MAPOS execute o seguinte atraves do CMD comando: **php index.php email/process** e no mesmo instante ele fará os envios pendentes dos email que você tentou enviar.

5º PASSO: Vai nas configurações la no seu sistema MAPOS aberto no navegador: configurações>emails e verifica se o status está como ENVIADO, se tiver com falha siga o PASSO 6 abaixo. Segue print de como deve ficar ↓
![image](https://user-images.githubusercontent.com/53625745/62422526-69e70280-b68a-11e9-8878-799db19e504b.png)

6º PASSO: Fez tudo e ainda deu errado (era o meu caso) DESATIVA SEU ANTIVÍRUS OU FIREWALL (testa com um desativado e outro ativado e vice versa e ver quem ta bloqueando), após lá dentro do MAPOS aberto tenta enviar outro email e roda o comando do do passo 4 e veja se o status apareceu como enviado.

Isso foi o que fiz, ainda não aprendi a criar o script para colocar no AGENDADOR DE TAREFAS para que isso seja automático mas já foi 80% do caminho.

Créditos para @willph que me ajudou do começo ao fim.

**Comment by willph** [comment]
Tudo ótimo.

No passo 1 a caixa vem desativado e a pessoa tem que ativar.

No Gmail

**Comment by brtechst** [comment]
isso @willph muito bem lembrado.

No Gmail DESATIVAR a segurança significa que DESATIVAR = ATIVAR A OPÇÃO DENTRO DO GMAIL e ATIVAR = DESATIVAR A OPÇÃO DENTRO DO GMAIL.

Não esqueça tem que ta DESATIVADO a segurança mas la no Gmail tem que ta ATIVADO A OPÇÃO.

**Comment by brtechst** [comment]
> Pessoal, alguém poderia explicar um passo a passo ai de como configuro para mandar email para meu cliente?
> 
> Vi a explicação do Ramon mas não entendi onde coloco aqueles códigos, em que arquivo php para poder criar essa tarefa!
> 
> php /var/www/index.php email/process
> php /var/www/index.php email/retry

@willph como eu poderia gerar esse arquivo com esses código acima para que eu possa colocar no AGENDADOR DE TAREFAS?

tentei criar um .bat mas quando executo ele só abre o arquivo index.php. Queria preprar um para que eu coloque no agendador de tarefas do windows e para que eu execute sempre que necessário.

**Comment by Claudiomfa** [comment]
Utiliza este ficheiros. Modifica o caminho do php e do ficheiro .bat consoante a tua instalação.


[Email_send_files.zip](https://github.com/RamonSilva20/mapos/files/3464898/Email_send_files.zip)

**Comment by brtechst** [comment]
Vou testar, muitooooo obrigado. Postarei o resultado posteriormente.

**Comment by brtechst** [comment]
@Claudiomfa fiz os procedimentos citados, alterei o caminho como solicitado mas quando coloco o xml lá no programador de tarefas ele abre uma caixa pedindo qual programa deve executar a solicitação, o que eu faço? 

Executei o bat e deu certo manualmente, mas no agendador ta dando isso.

**Comment by Claudiomfa** [comment]
Coloca o ficheiro bat na raiz do mapos. Cria a tarefa para executar esse ficheiro bat consoante o tempo que pretende que ele execute a tarefa.

Se for preciso eu faço isso remotamente pelo teamviewer.

**Comment by brtechst** [comment]
@Claudiomfa Fiz isso, alterei o caminho no bat e no xml para meu mapos, coloquei o bat e o xml na raiz e dentro do agendador de tarefas coloquei só o xml, mas quando o agendador vai executar o xml ela pede para eu escolher qual programa desejo usar para executar a tarefa.

sobre o acesso se eu não conseguir certamente gostaria de sua ajuda.

**Comment by brtechst** [comment]
![image](https://user-images.githubusercontent.com/53625745/62494406-d4429480-b7a9-11e9-852a-241fa4827cf8.png)

![image](https://user-images.githubusercontent.com/53625745/62494420-e1f81a00-b7a9-11e9-8e29-eaff2db1ef3b.png)

**Comment by eduaraujothe** [comment]
Como fazer isso pra quem utiliza hospedagem compartilhada? uso o dialhost.

**Comment by jrtechsolution** [comment]
@willph como eu faço para fazer o 4º PASSO: Dentro da pasta raiz do MAPOS execute o seguinte atraves do CMD comando: php index.php email/process e no mesmo instante ele fará os envios pendentes dos email que você tentou enviar.

**Comment by newtechro** [comment]
Show de bola, muito obrigado, ajudou demais... agora entendi, amanha tento agendar a tarefa...

**Comment by newtechro** [comment]
Consegui rodar pelo agendador de tarefas no windows 7 com o bat

cd..
cd..
cd xampp
cd htdocs
cd mapos
php index.php email/process
exit

No agendados, deixei para executar como administrador, ao fazer logon e repitir a cada 5 minutos... deu certo..
