### ISSUE TITLE
Acesso ao MapOS em rede INTERNA e EXTERNA ao mesmo tempo!

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#393]
Pessoal, fiz todos os redirecionamentos, liberei as portas e mesmo assim não ta funcionando, o que acontece é o seguinte:

Ao acessar meu ip externo ja redirecionado http://186.236.200.160:3000 ele abre a tela do meu xampp, ou seja, teve comunicação e a porta ta liberada, mas quando tento acessar http://186.236.200.160:3000/mapos/ ele simplesmente demora.... quer acessar mas retorna meu ip local configurado que seria http://192.168.0.100/mapos/index.php/mapos/login e não abre a tela de login.

na minha rede local ta tudo 100%!

![redirecionamento servidor](https://user-images.githubusercontent.com/53625745/62414990-622b4d80-b5f9-11e9-88a3-1998f3f8090f.PNG)

![port trigger](https://user-images.githubusercontent.com/53625745/62414991-6ce5e280-b5f9-11e9-8264-e1669a01b97c.PNG)

![dmz hostt](https://user-images.githubusercontent.com/53625745/62414993-740cf080-b5f9-11e9-8cde-365533eb5b69.PNG)

NO MEU MODEM SÓ TEM ESSAS OPÇÕES ACIMA.

![xampp](https://user-images.githubusercontent.com/53625745/62415000-85ee9380-b5f9-11e9-96b5-e05e73b2daa8.PNG)

MEU XAMPP JA TA NA PORTA 3000 (liberada tbm)

![config mapos](https://user-images.githubusercontent.com/53625745/62415006-9acb2700-b5f9-11e9-8819-a36e0baf3d06.PNG)

MEU ARQUIVO CONFIG.PHP

![rede local mapos](https://user-images.githubusercontent.com/53625745/62415010-a9194300-b5f9-11e9-8f8e-6efe6fb8cec0.PNG)

NA REDE LOCAL O ACESSO TA FILÉ.

Alguma luz?

**Comment by willph** [comment]
Resolvido parcialmente.

Apenas faltando acesso localhost.

**Comment by willph** [comment]
Problema resolvido com @brtechst, o mesmo ira postar aqui, pra quem tiver a mesma dúvida.

**Comment by brtechst** [comment]
Resolvido o problema, meu nobre amigo @willph preparou o código necessário para resolver o problema.

Vá no arquivo config.php delete ou deixe a linha de comando: $config['base_url'] = 'http://localhost/mapos/'; desativada ou em forma de comentário e adicione o código abaixo ↓

$URL_ATUAL = "http://$_SERVER[HTTP_HOST]";

if($URL_ATUAL == 'http://IP_EXTERNO')
{
	$config['base_url'] = 'http://IP_EXTERNO/mapos';
}
else
{
	$config['base_url'] = 'http://IP_INTERNO/mapos';
}

e problema será resolvido, ou seja, você vai conseguir acessar localmente e ao mesmo tempo pela rede externa.

Obrigado @willph tu é FODAA!

**Comment by brtechst** [comment]
Onde IP_EXTERNO é seu IP externo do seu roteador e IP_INTERNO é seu IP fixo local.

**Comment by willph** [comment]
E não esquecendo que precisa configurar o roteador e ter um IP que seja real.

**Comment by brtechst** [comment]
Sim no meu caso eu mudei a porta do APACHE para 3000 e la no meu Roteador fui na opção VIRTUAL SERVERS e o redirecionamento do meu IP externo para o INTERNO  liberando a porta 3000 TCP/UDP, assim quando digito o endereço do IP EXTERNO automaticamente ele direciona para meu PC local onde o sistema ta instalado.

**Comment by willsantos07** [comment]
@willph obrigado pela ajuda estava procurando por isso porem em um dos acessos sempre o logo do emitente ficara indisponível teria alguma forma de contornar isso?

**Comment by brtechst** [comment]
@willsantos07 Aqui também acontecia isso, ficava meio bugado em um dos acessos as imagens, mas após fazer essa configuração acima os dois acessos normalizaram e as imagens não bugaram mais.

OBS: Para quem tiver alguma dúvida, você tbm pode colocar no lugar do IP_EXTERNO seu DDNS, no meu caso criei um gratuito no NO_IP pois meu ip fixo é o 186.236.200.160 já que ele vai mudar então adicionei ele ao meu DDNS: brtechst.ddns.net e para quem quiser testar o acesso segue: brtechst.ddns.net:3000/mapos/

Para quem ta com dúvida segue ai bem explicadinho.

**Comment by brtechst** [comment]
> @willph obrigado pela ajuda estava procurando por isso porem em um dos acessos sempre o logo do emitente ficara indisponível teria alguma forma de contornar isso?

eu resolvi isso tbm, é só adicionar no arquivo hosts do windows no caminho C:\Windows\System32\drivers\etc

![image](https://user-images.githubusercontent.com/53625745/64080929-1ccd6f00-ccd0-11e9-9182-c027233fede2.png)

**Comment by mmonzato** [comment]
@brtechst você poderia me informar quais as modificações que foram feitas no seu sistema, vc disse em algum tópico que seu sistema está com novas funcionalidades.

**Comment by magnatagamer** [comment]
@brtechst você conseguiria deixar um exemplo com ip? pois mudei e coloquei meu ip externo e não esta indo, quando coloco meu ip externo/mapos/index.php/login até aparece mas como se estivesse em html bem simples, então coloco o login e depois joga para meu ip interno que ai da erro

**Comment by drdan2021** [comment]
> @brtechst você conseguiria deixar um exemplo com ip? pois mudei e coloquei meu ip externo e não esta indo, quando coloco meu ip externo/mapos/index.php/login até aparece mas como se estivesse em html bem simples, então coloco o login e depois joga para meu ip interno que ai da erro

Estou com o mesmo problema aqui!

**Comment by Betauum2022** [comment]
Boa noite, e no caso do linux ubutu como devo proceder? não consigo acessa-lo com meu ip publico...

**Comment by diegofstbg** [comment]
@brtechst ola boa noite, segui toda sua dica de como acessar via rede local e rede externa 
ja fiz todo o redirecionamento da rede.
porem na rede local da certo fica tudo certinho, ja no acesso externo quando eu acesso fica como citado acima um html simples
oque sera que eu estou errado?

**Comment by diegofstbg** [comment]
@willph
ola boa noite, segui toda sua dica de como acessar via rede local e rede externa
ja fiz todo o redirecionamento da rede.
porem na rede local da certo fica tudo certinho, ja no acesso externo quando eu acesso fica como citado acima um html simples
oque sera que eu estou errado?

**Comment by Jarsonick** [comment]
Pessoal quem pode me ajudar? Estou com esse problema. A Vivo bloqueia a porta 80 e 443 e não consigo acessar o localhost pra instalar o Mapos. @brtechst @willph

**Comment by Jonathaf94** [comment]
Se quiser manter em localhost, e as mesmas portas, instalar um roteador depois da ONT da Vivo, pede para criarem uma DMZ para seu roteador e assim terá controle da rede, poderá usar as portas que quiser, até direciona-las para externo.

**Comment by maxjuniosantos** [comment]
C:\xampp\htdocs\crm\application\config

apague a linha:

$config['base_url'] = $_ENV['APP_BASEURL'] ?? 'http://localhost:8081/crm';

ADICIONE ESTA QUE IRÁ FUNCIONAR:

$host = $_SERVER['HTTP_HOST'];
$ipInterno = 'http://localhost:8081/mapos'; // Altere para seu IP interno
$ipExterno = 'http://meusite.com:8081/mapos'; // Ou IP público

if ($host == $ipExterno) {
    $config['base_url'] = "http://meusite.com:8081/mapos";
} else {
    $config['base_url'] = "http://meusite.com:8081/mapos";
}


======

SUGESTÃO: A sua maquina sera acessada de forma interna pela intranet: localhost e de forma ou publica usando ddns ou noip. No firewall, habilite as portas e checam se estão OPEN no sitee: https://www.yougetsignal.com/tools/open-ports/

Boa sorte. Seja feliz!

**Comment by tecnicaemail** [comment]
Amigo segui sua dica a cima tentando adicionar  esses linhas, mas se eu add meu Mapos para de dar acesso.

Com essa linha do outro amigo funcinou 

$URL_ATUAL = "http://$_SERVER[HTTP_HOST]";

if($URL_ATUAL == 'http://IP_EXTERNO')
{
$config['base_url'] = 'http://IP_EXTERNO/mapos';
}
else
{
$config['base_url'] = 'http://IP_INTERNO/mapos';
}

porem eu não consigo remoto, somente se eu acessar via VPN Wireguard minha ai tenho acesso.
Mas queria configurar meu ddns para ter acesso.
E se eu altero a porta do apache para 8888 ou 8081 tambem perco o acesso.
poderia me orientar?
