### ISSUE TITLE
Anexo de Imagens - Area do Cliente

### ISSUE THREAD

**Issue by ofaccioli** [RamonSilva20/mapos#394]
Olá.

Gostaria de saber como consigo anexar imagens na abertura da OS direto do meu HDD sem a necessidade de inserir por URL.

**Comment by brtechst** [comment]
Basta apenas dento da OS aberta ir em anexos e escolher a imagem desejada.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
