### ISSUE TITLE
Erro para excluir OS

### ISSUE THREAD

**Issue by igoatier** [RamonSilva20/mapos#395]
boa tarde.
 depois de atualizar para versão 3.8 o botão excluir das OS não estão funcionando.
gostaria de saber se os demais que atualizarão estão com o mesmo problema.

**Comment by willsantos07** [comment]
Boa noite acabei de efetuar o teste tanto na versao 3.8.0(original) quando em uma modificada que customizei e ambas funcionaram obs xampp versao 5.6.40 e testado em versao 7.3.7 ambas OK

**Comment by willph** [comment]
Fez atualização do Banco de dados?

**Comment by Triaca** [comment]
@willsantos07 estou com o mesmo problema dele, acredito que seja algo relacionado a direcionamento de página, porém ainda não encontrei nada.
![os](https://user-images.githubusercontent.com/21310068/64070650-5f8d3980-cc33-11e9-8f51-b4231080fcdd.png)

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
