### ISSUE TITLE
Coloca o ficheiro bat na raiz do mapos. Cria a tarefa para executar esse ficheiro bat consoante o tempo que pretende que ele execute a tarefa.

### ISSUE THREAD

**Issue by robertoreges** [RamonSilva20/mapos#396]
Coloca o ficheiro bat na raiz do mapos. Cria a tarefa para executar esse ficheiro bat consoante o tempo que pretende que ele execute a tarefa.

Se for preciso eu faço isso remotamente pelo teamviewer.

_Originally posted by @Claudiomfa in https://github.com/RamonSilva20/mapos/issues/392#issuecomment-518341716_

gostaria de saber também, mim ajuda?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
