### ISSUE TITLE
Como mudar o sistema para multilíngüe

### ISSUE THREAD

**Issue by waldemaris** [RamonSilva20/mapos#397]
Olá a todos, quero saber se o sistema Map O pode mudar para outros idiomas, por exemplo espanhol, ou se o sistema de estrutura codeigniter permite usar https://github.com/bcit-ci/codeigniter3-translations para fazer o traduções em qualquer idioma ou permitir que o console troque o idioma necessário

**Comment by Pr3d4dor** [comment]
É possível mas todas as views do sistema teriam que ser refatoradas, pois os textos estão hardcoded e teriam que ser transferidos para a pasta language.

Para fazer essa refatoração seria necessário um tempo considerável.

**Comment by waldemaris** [comment]
> 
> 
> É possível mas todas as views do sistema teriam que ser refatoradas, pois os textos estão hardcoded e teriam que ser transferidos para a pasta language.
> 
> Para fazer essa refatoração seria necessário um tempo considerável.

Obrigado pela informação, seria interessante ter alguma opção em algum futuro para fazer o swtich para outra linguagem, já que a programação do sistema parece sólida e funcional
