### ISSUE TITLE
Teria como automatizar o envio da OS quando o Cliente criar a OS?

### ISSUE THREAD

**Issue by allamcr** [RamonSilva20/mapos#398]
Por exemplo, o cliente 1 acessa o portal, cria um chamado e apertar o botão para adicionar.
No momento que adicionar essa OS, o sistema envia um e-mail alertando que uma nova OS foi criada.

**Comment by Pr3d4dor** [comment]
Sim, é possível, se eu tiver eu tempo eu conseguiria fazer essa implementação.

Apenas devem ser definidos alguns pontos:
- Deverá ser um configurado um email do Administrador do sistema para enviar essa notificação cada vez que uma OS for criada.
- Creio também que seria útil enviar essa notificação para o técnico que foi associado à OS.

O que acha?

**Comment by allamcr** [comment]
> Sim, é possível, se eu tiver um tempo livre eu conseguiria fazer essa implementação.
> 
> Apenas devem ser definidos alguns pontos:
> 
> * Deverá ser um configurado um email do Administrador do sistema para enviar essa notificação nesse email cada vez que uma OS for criada.
> * Creio também que seria útil enviar essa notificação para o técnico que foi associado à OS.
> 
> O que acha?

Exatamente como eu imaginei, configurar um usuário para sempre receber essa notificação e se possível, o técnico que for associado a OS.

**Comment by brtechst** [comment]
Cara se você conseguir fazer isso por nós seria ótimo!

**Comment by brtechst** [comment]
@allamcr joga ai para ver se alguém consegue resolver, seria muito bacana essa função.

**Comment by Triaca** [comment]
@Pr3d4dor se você conseguir fazer isso me avisa! estou precisando também.

**Comment by Pr3d4dor** [comment]
Olá, desculpa pela demora, fiz a implementação dessa feature, a única diferença é que o email é disparado sempre que é atualizado alguma coisa na OS ou é criada uma OS.

A implementação pode ser vista em #436.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
