### ISSUE TITLE
Como faço a atualização da versão 3.5.2 para a 3.8.0?

### ISSUE THREAD

**Issue by renansmec** [RamonSilva20/mapos#399]
Bom dia, alguem poderia me informar como eu faço a atualização da versao 3.5.2 para a versão 3.8.0 e proximas? estou com duvida referente a isso.

**Comment by vinnyparker** [comment]
man, eu atualizei agora, eu fiz backup do meu arquivo database.php, e substitui todos os arquivos pelos mais recentes.

**Comment by vinnyparker** [comment]
esqueça o que eu disse pq fiz tudo errado kkkk

**Comment by renansmec** [comment]
> esqueça o que eu disse pq fiz tudo errado kkkk

kkkkkkk. tentei fazer mais ou menos como o @RamonSilva20 disse em outro topico, porem nao consigo executar o script da versão 3.7 que está dentro da pasta update.
Também fiz o up de todos os arquivos da 3.8 na hospedagem, e estou recebendo um "HTTP ERROR 500".

**Comment by RamonSilva20** [comment]
Olá. Executou os arquivos sql de atualização do banco de dados? Arquivos dentro da pasta updates.

**Comment by renansmec** [comment]
> Olá. Executou os arquivos sql de atualização do banco de dados? Arquivos dentro da pasta updates.

Olá, tentei executar mas apresenta um erro #1044

**Comment by AllysonFredMed** [comment]
boa tarde galera.. tb faço tudo certinho mas da erro ao executar o script... e fica dando erro de loguin

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
