### ISSUE TITLE
Versão do sistema

### ISSUE THREAD

**Issue by eduardobelchior** [RamonSilva20/mapos#4]
Você já atualizou para a v3.1.0 do CodeIgniter? Caso não, por favor me adicione como contribuidor e terei prazer em ajudar a implementar mais coisas no sistema

**Comment by gugatxr** [comment]
Está na versão 2. Estava pensando em atualizar também

Em 23 de ago de 2016 18:30, "Eduardo Belchior" <notifications@github.com>
escreveu:

**Comment by phiterf** [comment]
Eu conversei com o Ramon por email, ele criou o branch **dev**. Falei que atualizaria e daria push porém não tive tempo, quem quiser fazer só precisa lembrar de testar direitinho. A função sha1 do codeigniter não existe mais, tem que usar a nativa do PHP. Dentre outras particularidades. Então quem for atualizar dê push no branch dev, talvez no futuro ele junte o dev com o master.

**Comment by RamonSilva20** [comment]
Adicionei vocês como colaboradores do projeto. Obrigado a todos pelo interesse em contribuir.

**Comment by eduardobelchior** [comment]
Por nada ramon, vou dar uma analisada aqui e ver se consigo atualiza ele pra v3.1.0, algumas coisas mudaram, vou ver o que faço...

**Comment by paulinhowoox** [comment]
Ramon quero colaborar também, posso ajudar na migração para a versão 3. tenho algumas melhorias que fiz aqui também e queria compartilhar!

**Comment by RamonSilva20** [comment]
Obrigado. Adicionei você como colaborador.

**Comment by ronna88** [comment]
Ao fazer a instalação aqui, não aparece a area do cliente. 
como ativá-la? gostaria de liberar um login para o cliente poder abrir a os e poder acompanhar o andamento dela

**Comment by paulinhowoox** [comment]
Olá ronna88, para acessar essa área você tem que colocar depois da url do site o "conecte", ex.: http://localhost:8080/conecte! Abraço

**Comment by wagnerfillio** [comment]
Ramon,
Bom dia!

Pode me adicionar como colaborador do projeto?

**Comment by hardbrasil** [comment]
Olá Ramom, boa tarde eu gostaria de colaborar também mas não como programador pois não sou "fera" como vcs mas sim com documentos e documentações sobre e para o sistema. Exemplo autorizadas e assistências sofrem com falta de termos e  pequenos contratos adequados nas ordens que os resguardam perante as leis brasileiras em caso de abandono de equipamento e má fé de clientes. Para que o mapos seja perfeito precisariamos inserir nele certos textos e modelos de contrato que profissionalizaria muito o trabalho e resguardaria quem o usasse de forma adequada.

**Comment by luizdeltasouza** [comment]
ramon na hora de imprimir a venda os dados do vendedor ficam asteristico

**Comment by luizdeltasouza** [comment]
ele está ocultando os dados dos vendedores e dos clientes  pondo asteristicos
