### ISSUE TITLE
Erro ao adicionar usuários  ou alterar a senha

### ISSUE THREAD

**Issue by Totonho** [RamonSilva20/mapos#40]
Ao tentar adicionar ou alterar a senha do usuario da o seguinte erro. 

Fatal error: Call to undefined method CI_Encrypt::sha1() in C:\xampp2\htdocs\mapos\application\controllers\Usuarios.php on line 94
A PHP Error was encountered

Severity: Error

Message: Call to undefined method CI_Encrypt::sha1()

Filename: controllers/Usuarios.php

Line Number: 94

**Comment by RamonSilva20** [comment]
Boa noite. Já foi corrigido, basta atualizar os arquivos da pasta application.

**Comment by Totonho** [comment]
Bom dia Ramon, a parte de cadastrar novo usuário foi corrigido. A alteração de senha continua com o erro.

**Comment by RamonSilva20** [comment]
Corrigido.
