### ISSUE TITLE
Erro ao emitir relatorios

### ISSUE THREAD

**Issue by vinnyparker** [RamonSilva20/mapos#400]
quando vou ao modulo de relatórios, nao consigo  emitir nenhum. aparece a msg q vou passar em um pdf anexo.
Eu gostaria de uma orientação pois posso estar fazendo algo errado.
[clientesCustom.pdf](https://github.com/RamonSilva20/mapos/files/3516392/clientesCustom.pdf)

**Comment by renato-ck** [comment]
Versão incompatível do PHP. Utilize a 5.4.x

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
