### ISSUE TITLE
Erro de url

### ISSUE THREAD

**Issue by gustavosilvani** [RamonSilva20/mapos#401]
![image](https://user-images.githubusercontent.com/23747845/63398596-79fa2400-c3a4-11e9-989f-261f3d6b36e7.png)

Em varias paginas quando faço uma ação e ele vai redirecionar acontece de bagunçar a url, pq disso?

**Comment by gustavosilvani** [comment]
Resolvido

**Comment by Triaca** [comment]
como você resolveu?

**Comment by gustavosilvani** [comment]
Eu botei o link completo como padrao
Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Triaca** [comment]
colocou o link completo como padrão onde?
Estou mexendo no servidor FTP e já testei como /ordemdeservico, /ordensdeservicos/ etc

**Comment by gustavosilvani** [comment]
Botei localhost/a

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Triaca** [comment]
Não consegui encontrar ainda onde por.

**Comment by gustavosilvani** [comment]
Tem no manual de instruções para instalação manualmente

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mariodarin** [comment]
Edite o arquivo ...applicarin/confi/config.php na linha 28:
$config['base_url'] = 'https://seu.domínio.com.br/mapos/;

Tem que colocar URL completa inclusive protocolo http ou https e terminar com um barra.
se colocar diferente, sistema entende que além da se há URL, ele está em uma subpasta, por exemplo, se colocar apenas domínio.com na instalação, sistema vai redirecionar para http[s]://seu.dominio.com/domínio.com/mapos/index.php

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
