### ISSUE TITLE
erro ao instalar em subdominio

### ISSUE THREAD

**Issue by vinnyparker** [RamonSilva20/mapos#402]
Alguem pode dar uma luz sobre isso? eu baixei a ultima versao, e instalei normalmente em uma pasta xhost.net.br/assistencia. 
porem ao instalar em subdominio villastec.xhost.net.br  da mensagemde arquivo nao encontrado.
sei q essa msg se refere ao arquivo seettings.json q fica dentro da pasta install. mas o arquivo ta la. 

![erromapos](https://user-images.githubusercontent.com/1207567/63466134-01917280-c439-11e9-9489-a29d6cd0ed8e.png)

**Comment by Triaca** [comment]
Eu estava com esse problema, o que eu fiz foi fazer um backup do banco de dados.
excluir todas as pastas do mapos do FTP ou se for localhost, apague toda a instalação do local onde foi feito.

Instale normalmente o mapos e vá na pasta de instalação mapos/aplication/config/config.php e procure a parte $config['base_url'] = 
quando achar, coloque assim: $config['base_url'] = 'https://subdominio.domínio.com.br/'

salve e espere 2 minutos, faça o teste e se der problema apague onde esta o link e deixe em branco, depois de dois minutos volte a adicionar o seu site.
o meu resolveu assim.

**Comment by vinnyparker** [comment]
> Eu estava com esse problema, o que eu fiz foi fazer um backup do banco de dados.
> excluir todas as pastas do mapos do FTP ou se for localhost, apague toda a instalação do local onde foi feito.
> 
> Instale normalmente o mapos e vá na pasta de instalação mapos/aplication/config/config.php e procure a parte $config['base_url'] =
> quando achar, coloque assim: $config['base_url'] = '[https://subdominio.domínio.com.br/](https://subdominio.dom%C3%ADnio.com.br/)'
> 
> salve e espere 2 minutos, faça o teste e se der problema apague onde esta o link e deixe em branco, depois de dois minutos volte a adicionar o seu site.
> o meu resolveu assim.

Deixa eu ver se entendi. vc instalou normal, tipo seudominio.com.br/mapos. e depois vc trocou o  o base_url? foi isso?

**Comment by Triaca** [comment]
Tipo, os arquivos do MapOs estão a onde?
No meu caso eu salvei no “www.sistema.triacainfo.com.br/“
Então na hora de instalação eu coloquei esse endereço aí, tentei entrar e deu erro, fui lá no config.php e removi esse site por 2 minutos e adicionei novamente e funcionou.

Porém você tem que ver se usou /MapOs/ na frente do seu site, isso depende das pastas que você usou.
Var/www/MapOs/

Se usou assim então você precisa usar /MapOs/ na frente do seu site na hora da instalação e siga o mesmo processo que eu disse

**Comment by vinnyparker** [comment]
ele esta em villastec.xhost.net.br no caso do meu cpanel aqui ele cria uma pasta villastec.xhost.net.br que é onde esta a instalação

**Comment by Triaca** [comment]
Ok, mas ele cria a pasta  villastec.xhost.net.br/MapOs/
Ou fica só  villastec.xhost.net.br

Se criar a pasta, então use o /MapOs/ na instalação.
O meu eu não criei a pasta no cpanel, deixei direto no link do domínio para não ter /MapOs/ na frente

**Comment by vinnyparker** [comment]
no meu caso fica na raiz de villastec.xhost.net.br

**Comment by vinnyparker** [comment]
qual versao do php vc ta usando?

**Comment by Triaca** [comment]
Se está na raiz então não deve usar /MapOs/ na instalação.
Php 5.6

**Comment by vinnyparker** [comment]
Consegui aqui, deixei o campo base_url em branco, e  e mudei a versao do php para 7.1. valeu

**Comment by Triaca** [comment]
Testa certinho aí e se funcionar perfeitamente fecha o issue aqui.
Se não funcionar, volta o nome para a base URL como eu disse.

Mas lembre-se de fechar a issue se funcionar.

**Comment by vinnyparker** [comment]
blzz

> Testa certinho aí e se funcionar perfeitamente fecha o issue aqui.
> Se não funcionar, volta o nome para a base URL como eu disse.
> 
> Mas lembre-se de fechar a issue se funcionar.

 to testando aqui. funcionando tudo eu volto pra fechar.
man, deixa te dar uma dica. troca tua senha de admin.....
