### ISSUE TITLE
Ordenar por data ou nº de OS (Na tela de OS)

### ISSUE THREAD

**Issue by renato-ck** [RamonSilva20/mapos#403]
Olá!
Como eu poderia ordenar por data inicial ou número da OS na tela de Ordens de Serviço?
Alguém pode indicar o arquivo que faz a chamada (Query - Select/Get) do BD para o preenchimento dessa tela?

**Comment by Triaca** [comment]
Também preciso disso

**Comment by maycon1977** [comment]
Se alguém implementar isso aí seria legal...
