### ISSUE TITLE
instalation at localhost

### ISSUE THREAD

**Issue by bmdaxx** [RamonSilva20/mapos#406]
hi, need help to install MAPOS at my computer.
view some tuoturial, already installed vertrigo, but can't install MAPOS.

**Comment by Pr3d4dor** [comment]
Hello, what are the problems that you are facing?

**Comment by bmdaxx** [comment]
hi,
First of all, i'm a not a programmer ( i'm noob).

i installed Vertrigo ( as i saw in a tuturial) for use the MAPOS at my local machine, tried to follows the steps by the automatic installer, but give me errors, see pictures:

THX for the help.
(if you speak Portuguese, please write in Portuguese)

________________________________

**Comment by Pr3d4dor** [comment]
Não consigo visualizar as imagens.

Já tentou usar WAMP ou MAMP no lugar do Vertrigo?

**Comment by bmdaxx** [comment]
Vou tentar hoje,
Tem msn ou whatsapp para lhe enviar as imagens?

Enviado do meu iPhone

No dia 30/08/2019, às 13:27, Gianluca Bine <notifications@github.com<mailto:notifications@github.com>> escreveu:


Não consigo visualizar as imagens.

Já tentou usar WAMP ou MAMP no lugar do Vertrigo?

**Comment by bmdaxx** [comment]
veja se consegue visualizar as imagens agora. Vai em winrar.
tentei com o wamo e dá o memso erro
com o MAMP, não me consegui entender com aquilo, lol

________________________________

**Comment by bmdaxx** [comment]
Este é o erro:
![installer](https://user-images.githubusercontent.com/54684923/64053921-876d9600-cb7c-11e9-9f92-e0b25d7bcf2d.jpg)
![step 2](https://user-images.githubusercontent.com/54684923/64053928-8e94a400-cb7c-11e9-860b-9786ffe19f5c.jpg)
![phpmyadmin](https://user-images.githubusercontent.com/54684923/64053931-918f9480-cb7c-11e9-9a12-af07348b9967.jpg)
![installed](https://user-images.githubusercontent.com/54684923/64053935-95bbb200-cb7c-11e9-9532-6c02e11c35b9.jpg)
![loggin menu](https://user-images.githubusercontent.com/54684923/64053939-981e0c00-cb7c-11e9-8085-299b027a543f.jpg)

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
