### ISSUE TITLE
Problemas na aba OS

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#407]
Boa noite senhores,
Fiz uma instalação limpa do MaPos em um subdominio e funcionou perfeitamente, menos a aba OS que não abre de jeito nenhum.
Então fiz a instalação em outro subdominio com uma versão anterior e um banco que completo.
após a instalação eu rodei a SQL de update do banco e também deu erro de página na aba O.S.

Alguém tem alguma solução para o problema?
![os](https://user-images.githubusercontent.com/21310068/64069869-7165e100-cc21-11e9-9437-006796ad32a2.png)

**Comment by robsonmeca** [comment]
Tente setar as permissões das pastas para 755, e dos arquivos para 644. Acredito que seja problema de permissão, pois instalei a ultima versão há cerca de 1 semana e não tive nenhum erro até o momento.

**Comment by Triaca** [comment]
@robsonmeca  já havia feito o teste anteriormente com esse nível de permissão.
no final das contas setei todos os arquivos e pastas com o 777, mesmo assim a aba OS não abre, as demais estão ok.
o mesmo problema ocorre quando entro pela página do cliente e crio uma OS, retorna o erro de página não existe e a OS não é criada.

**Comment by robsonmeca** [comment]
Na hora da instalação, o sistema verifica e solicita as dependências, chegou a verificar se algo estava faltando?

**Comment by Triaca** [comment]
@robsonmeca fiz uma instalação limpa sem meu BD e funcionou, porém sempre que subo o BD antigo ele dava erro, então fiz um "backup" direto do MaPos e subi ele e funcionou normalmente.

porém não sei onde mudar o nome do status "finalizado" pois o meu esta como "PAGO" como indica na print, e mesmo utilizando uma configuração de e-mail correta, não esta sendo enviado e-mail para o cliente.

![os2](https://user-images.githubusercontent.com/21310068/64071141-6d49bb80-cc41-11e9-95fe-63a67e701d12.png)

**Comment by Triaca** [comment]
No e-mail esta assim:

Essa configuração é padrão que utilizo em todos os sistemas para enviar, verifiquei e não tem nada de diferente.
![e-mail](https://user-images.githubusercontent.com/21310068/64071213-bbab8a00-cc42-11e9-88d0-23359021e08b.png)

**Comment by robsonmeca** [comment]
Configure o email de envio no arquivo email.php

Configurar cron jobs para envio de e-mail

Enviar emails pendentes a cada 2 minutos.
    */2 * * * * php /var/www/index.php email/process

Enviar emails com falha a cada 5 minutos.
    */5 * * * * php /var/www/index.php email/retry

**Comment by Triaca** [comment]
o problema @robsonmeca é que não utilizo servidor para hospedagem, é hospedagem locaweb.
então não tenho a pasta var/www.
tudo é feito em um servidor compartilhado, antigamente eu apenas tinha alterado dentro do e-mail.php mas agora não rolou
![hospedagem](https://user-images.githubusercontent.com/21310068/64071220-2fe62d80-cc43-11e9-94c5-968f7943a360.png)

**Comment by robsonmeca** [comment]
Utilize os caminhos abaixo na cron no cpanel:

public_html/mapos/index.php email/process 

public_html/mapos/index.php email/retry
