### ISSUE TITLE
Como participar no desenvolvimento do sistema?

### ISSUE THREAD

**Issue by marmattos** [RamonSilva20/mapos#408]
Olá Amigos, tenho conhecimento em codeigniter e vi o projeto Map-OS. Como faço para contribuir com novas funções?

**Comment by willph** [comment]
Eu faço enviado uma pull requests.

Mas o @Ramon pode explicar melhor.

**Comment by marmattos** [comment]
Ok, Obrigado

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
