### ISSUE TITLE
Alteração de nome campo "Status" da O.S

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#409]
Alguém sabe em qual local posso fazer essa alteração?
Quero mudar o "Finalizado" para "Pago"
![os2](https://user-images.githubusercontent.com/21310068/64071267-9fa8e800-cc44-11e9-97a2-85366d7905e2.png)

**Comment by brtechst** [comment]
É só ir na pasta do mapos no seguinte caminho: application\views\os

E alterar para o que você desejar.

![image](https://user-images.githubusercontent.com/53625745/64071299-c4ee2400-cc4d-11e9-81f0-631ed501eb2c.png)

**Comment by brtechst** [comment]
![image](https://user-images.githubusercontent.com/53625745/64071390-e94b0000-cc4f-11e9-9124-69f3994ad3a1.png)

**Comment by Triaca** [comment]
Valeu!!! resolveu meu problema!
