### ISSUE TITLE
Problema para envio de e-mail direto da O.S

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#410]
houve a configuração como padrão que utilizamos em outros sistemas, porém como utilizamos uma hospedagem compartilhada de e-mail locaweb com direito a BD, não temos acesso a pasta var/www/
É hospedagem de domínio, utilizando S.O Centus.
Porém só existe acesso via FTP dentro da pasta raiz/public_html/mapos ou seja é impossível rodar uma .bat ou o cronjob a menos que seja por SSH, isso se tornaria inviável pois o processo é manual a cada O.S criada. 

Como pode ser observado na print do FilleZilla o servidor não é local! é hospedagem.

![e-mail](https://user-images.githubusercontent.com/21310068/64071284-00d0bb80-cc45-11e9-87fb-8a6d8823d584.png)
![hospedagem](https://user-images.githubusercontent.com/21310068/64071732-6ecdb080-cc4e-11e9-997b-ac2d6525dd7f.png)

**Comment by brtechst** [comment]
Segue tutorial que eu fiz bem detalhado.

https://github.com/RamonSilva20/mapos/issues/392

**Comment by brtechst** [comment]
Depois que fizer os procedimentos do tutorial joga esses dois arquivos na raiz do seu mapos, abra cada um deles e edite o caminho apontando para sua pasta do mapos.

para enviar manualmente os email é só executar o .bat

Para o agendador de tarefas use o .xml


[enviaremail.zip](https://github.com/RamonSilva20/mapos/files/3563075/enviaremail.zip)

**Comment by Triaca** [comment]
@brtechst coloquei os arquivos e redirecionei, porém eu teria que ficar executando a .bat sempre pelo Fillezilla já que não tem conexão com o servidor e ele é na locaweb.
Sem falar que é Linux.
