### ISSUE TITLE
[Procuro programador] Ordenar Dashboard em ordem de número O.S

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#411]
Onde posso encontrar a pasta para alterar a ordem de decrescente para crescente ou por data das O.S, produtos etc que aparecem na dashboard?
![dashboard2](https://user-images.githubusercontent.com/21310068/64072725-caee0000-cc61-11e9-8d71-68f3335e37f2.png)

**Comment by mmonzato** [comment]
@Triaca ainda está precisando de alguém para fazer as modificações no sistema ?

**Comment by Triaca** [comment]
@mmonzato preciso sim!
Porém apenas para duas coisas no momento, uma seria enviar e-mail automaticamente sempre que alterar o status do pedido/venda e outra para ordenar as O.S no dashboard tanto meu quanto do cliente por ordens de número de O.S

**Comment by mmonzato** [comment]
@Triaca depois me manda e-mail detalhando exatamente o que você precisa. mmonzato@hotmail.com

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
