### ISSUE TITLE
pesquisa pelo número do celular

### ISSUE THREAD

**Issue by vaidamerda** [RamonSilva20/mapos#412]
olá pessoal! seria possível procurar um cliente pelo número de celular?

**Comment by willsantos07** [comment]
Bom dia application\models\mapos_model.php

`        // buscando clientes
        $this->db->like('nomeCliente', $termo);
        $this->db->or_like('documento', $termo);
        $this->db->or_like('telefone', $termo);
        $this->db->or_like('celular', $termo);
        $this->db->limit(10);
        $data['clientes'] = $this->db->get('clientes')->result();`

**Comment by vaidamerda** [comment]
Perfeito, muito obrigado will.
