### ISSUE TITLE
Dificuldade para fazer funcionar em acesso externo

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#413]
Funciona normalmente no acesso interno a instalação e o acesso mas ao tentar realizar o acesso externo sou redirecionado para o ip interno, mesmo iniciando o acesso através do IP externo. Poderia ajudar @RamonSilva20  🙏?

**Comment by brtechst** [comment]
Resolvi este problema neste tópico.

https://github.com/RamonSilva20/mapos/issues/393
