### ISSUE TITLE
[Procuro programador] Envio de e-mail automático na troca de status da O.S.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#414]
Olá amigos,
Eu tinha no meu MaPos a função que quando eu trocava o status da O.S, um e-mail era encaminhado automaticamente para meu cliente informando sobre.
Após a atualização da versão acabei perdendo e não lembro onde e qual função devo colocar.
Procurei nos issues fechados para ver se tinha algo sobre mas não encontrei.

**Comment by brtechst** [comment]
Você não tem o backup salvo do antigo (pastas, arquivos, bd, etc?)

**Comment by brtechst** [comment]
Tenho o contato do programador que modificou o meu, paguei 900 reais para ele fazer várias mudanças e ficou show meu sistema. O meu atualmente envia até status de atualização pelo zap, email, e tudo mais!

**Comment by Triaca** [comment]
@brtechst tenho o BD salvo, subi ele para utilizar o sistema porém o que preciso alterar acredito que não seja pelo BD, pois se não já estaria do jeito que era.

As pastas foi feito o backup, porém sempre dava erro na atualização então fiz uma instalação limpa.
Fui até uma usuária fazer o backup dela para formatar e meu HD estava zerado. (fiquei surpreso).

Para por o e-mail automático e ordenar as O.S por ordem numérica um cara cobrou R$ 50,00 porém não atende mais por estar muito ocupado.
Fiz várias alterações e acredito até conseguir, mas não estou achando o local onde fica o php para isso.
no mapos.php e painel.php não tem nenhuma função para ordenar ou exibir em ordens Idos ou os.

**Comment by mmonzato** [comment]
@Triaca ainda está precisando de alguém para fazer as modificações no sistema ?

**Comment by Pr3d4dor** [comment]
Olá, desculpa pela demora, fiz a implementação dessa feature, a única diferença é que o email é disparado sempre que é atualizado alguma coisa na OS ou é criada uma OS.

A implementação pode ser vista em #436.

**Comment by Triaca** [comment]
@Pr3d4dor no caso eu apenas altero/adiciono as linhas que você postou, as demais deixo como estão, correto?

Mesmo fazendo isso dá erro quando vai acessar as O.S, acredito que as numerações de linhas não estão batendo com as minhas.
Mas vou continuar tentando aqui

**Comment by Pr3d4dor** [comment]
Pode ser que seu código esteja diferente por isso as numerações das linhas não estão batendo.

As linhas em vermelho são as que foram removidas e as linhas em verde as adicionadas.

Você pode tentar comparar o arquivo inteiro com o seu e ver as diferença e realizar os ajustes.

**Comment by brennodornelas** [comment]
> Tenho o contato do programador que modificou o meu, paguei 900 reais para ele fazer várias mudanças e ficou show meu sistema. O meu atualmente envia até status de atualização pelo zap, email, e tudo mais!

Amigo voce poderia me passar o contato?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
