### ISSUE TITLE
Não realiza login, dados ok,  mas aparece mensagem de erro

### ISSUE THREAD

**Issue by wnjulio** [RamonSilva20/mapos#415]
![erro login](https://user-images.githubusercontent.com/42722761/64316626-be341980-cf8b-11e9-9981-e6f5006dc4f3.png)

**Comment by passalia** [comment]
Aconteceu a mesma coisa comigo quando fiz a instalação.
A solução que encontrei, foi criar um usuário direto no banco de dados manualmente. 
Procure dentro do seu banco de dados a tabela "usuários" e clique nela. Depois, clique em inserir, para criar o usuário. Aqui você pode criar um usuário seu do zero ou apenas colar os dados que contam nas instruções de instalação:

idUsuarios: 1
nome: Admin
rg: MG-25.502.560
cpf: 600.021.520-87
rua: Rua Acima
numero: 12
bairro: Alvorada
cidade: Teste
estado: MG
email: admin@admin.com
senha: $2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO
telefone: 0000-0000
situacao: 1
dataCadastro: 2018-09-09
permissoes_id: 1 Administrador

Se colocar esses dados acima, o usuário será admin@admin.com e senha 123456 como vem padrão do sistema. Depois quando acessar, não esqueça de trocar a senha do admin.

**Comment by juninho9494** [comment]
Boa tarde, tbm estou com esse problema de login.
Sou bem leigo em php, como crio esse usuário?
Dentro do phpmyadmin?

**Comment by brtechst** [comment]
Antes de criar usuário eu resolvi da seguinte maneira, deletei o BD criado e recriei do zero de novo e ele resolveu. Em segundo caso cria um usuário com senha no BD que resolve.

isso é BD bixado.

**Comment by robertoreges** [comment]
Remova do banco os dados e insere o cod:
INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES(1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);
    
- Email: admin@admin.com
 - Senha: 123456

**Comment by wnjulio** [comment]
Boa noite, tudo bom ?!

Continua dando o mesmo erro, executei o script do banco novamente, mas nada, a vs do php e 7.1.

 

Obg! 

 

 

 



 

 

De: robertoreges <notifications@github.com> 
Enviada em: segunda-feira, 9 de setembro de 2019 23:24
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: wnjulio <administrador@wn-software.com.br>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] Não realiza login, dados ok, mas aparece mensagem de erro (#415)

 

Remova do banco os dados e insere o cod:
INSERT INTO usuarios (idUsuarios, nome, rg, cpf, rua, numero, bairro, cidade, estado, email, senha, telefone, celular, situacao, dataCadastro, permissoes_id) VALUES(1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com <mailto:admin@admin.com> ', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);

*	Email: admin@admin.com <mailto:admin@admin.com> 
*	Senha: 123456

**Comment by wnjulio** [comment]
Galera, desconsidera  as mensagens anteriores, o erro foi humano, tanta correria que acabei esquecendo mt coisa, seguinte, estava com  5 bds e pensei agr, vou conferir o bd que estou usando, estava mexendo em um e o que era principal era outro, somente isso, desculpa a perda de tempo. 

E obg a todos.

**Comment by borgesjsb** [comment]
Se fosse so isso tava bom... 

![image](https://user-images.githubusercontent.com/55168713/64743775-9129be80-d4d7-11e9-9f01-740e5f3c32d2.png)

**Comment by rafaerigson** [comment]
Alguém conseguiu instalar no hostinger, ja instalei varias vezes e sempre da erro de usuário e senha, ja inseri as linhas com usuário admin, criei do zero com o admin, e nada, se alguém puder dar uma ajuda. 
obrigado.
