### ISSUE TITLE
Problemas com envio de e-mail

### ISSUE THREAD

**Issue by brunolafm** [RamonSilva20/mapos#417]
**Meus emails não estão sendo enviados, fica somente com o status processando...**

Uso a hospedagem Hostoo.io.
Fiz uma instalação limpa da ultima versão 3.8.0, instalei normalmente, configurei o arquivo `../application/config/email.php` com as minhas credenciais do Gmail e configurei o cron dessa forma com tempo de 1 min entre execuções para teste:
![cron](https://user-images.githubusercontent.com/11146567/64434752-a3e76200-d097-11e9-94ba-30252683e695.jpg)
No log por email, apresenta essa mensagem:
![email](https://user-images.githubusercontent.com/11146567/64434807-c5484e00-d097-11e9-960b-f49033256725.jpg)

_Obs: As já verifiquei credenciais, portas, endereço smtp e ativei a opção pra permitir acesso a apps menos seguros_

Alguém sabe o que preciso fazer?

**Comment by NATA-RMG** [comment]
Alguém resolveu ? estou com mesmo problema.

**Comment by brunolafm** [comment]
Até agora nada

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
