### ISSUE TITLE
Problema com uso do sistema

### ISSUE THREAD

**Issue by LucasPolli** [RamonSilva20/mapos#418]
Olá, estou fazendo alguns testes, faço a instalação, funciona corretamente, porem ao fazer qualquer cadastro ou alteração, quando efetuo a confirmação, sou redirecionado para um link tipo: meudominio/index.php/index.php/os toda vez ele coloca um índex.php a mais, o que estou fazendo de errado?

**Comment by Pr3d4dor** [comment]
No arquivo `application/config` a variável `$config['base_url']``está configurada corretamente com o domínio?

**Comment by LucasPolli** [comment]
boa noite, ja consegui resolver, obrigado...alguns posts abaixo tinha a
resposta

Em ter, 17 de set de 2019 às 20:36, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
