### ISSUE TITLE
Erros - Defeitos - Falhas do Sistema

### ISSUE THREAD

**Issue by hardbrasil** [RamonSilva20/mapos#42]
Proponho aqui a discussão de erros, falhas e defeitos encontrados.

**Comment by hardbrasil** [comment]
Erro de Demora excessiva no Campo Cidade e Estado.

O meu sempre apresentou este erro ao cadastrar a cidade e o estado, nos demais campos tudo OK. Esse erro já ocorria anteriormente. Alguém mais notou isso?

**Comment by hardbrasil** [comment]
Defeito Data Inicial = Data Final:   Ao Preencher uma OS ele já preenche a data inicial e coloca a mesma data na data final mesmo que a ordem não esteja fechada.

**Comment by alextdesouza** [comment]
Erro no login, a barra azul fica carregando infinitamente.
Erro na alteração de senha do administrador.

**Comment by cleytonasa** [comment]
Alguém ja percebeu que os clientes pode ser duplicados?

**Comment by hardbrasil** [comment]
Sim comigo já aconteceu umas 3x tbm.

**Comment by acinformatica2004** [comment]
Boa noite. Quando tento tirar um relatório de todas as OS da o seguinte erro.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 309176 bytes) in /home/advanced/public_html/ordemservico/application/helpers/mpdf/mpdf.php on line 14487

@RamonSilva20 é possível corrigir esse erro?
Obrigado

**Comment by RamonSilva20** [comment]
@acinformatica2004 Não é exatamente um erro, a geração de pdf consome muita memória do servidor e dependendo da quantidade de dados estoura a capacidade. O ideal seria utilizar outro formato para gerar este relatório, como csv, html ou xls.

**Comment by acinformatica2004** [comment]
Aqui só é possível gerar em pdf correto? Isso seria algo a ser incrementada? Obrigado

**Comment by RamonSilva20** [comment]
No novo sistema vou tentar inserir mais formatos de exportação.

**Comment by KokeroO** [comment]
Para quem tem problemas na tela de login em que a tela simplesmente não avança. O erro possa esta ocorrendo pela versão do PHP. O Mapos está usando uma extensão de criptografia que foi depreciada na versão 7.1. A extensão (mcrypt_encrypt). Talvez o Ramon possa até usar uma alternativa para a criptografia. 
Libsodium. Fica a dica.

**Comment by hardbrasil** [comment]
# **RELATÓRIO DE ORDENS DE SERVIÇO NÃO MOSTRA O N DA ORDEM!!!**

Ao gerar relatório de ordem de serviço o sistema nos mostra filtrado por status mas não mostra o n da ordem somente o cliente status, data e descrição.

**Comment by hardbrasil** [comment]
**# VISUALIZAÇÃO EDIÇÃO DE CLIENTE / OS:**

Por exemplo ao ir em Cliente e escolher o Cliente Cod 1 João da Silva Sauro quando ao clicar no ícone "olho" para visualizar o cliente e as respectivas ordens deste quase nunca abre daí eu tenho que ir em clientes visualizar qualquer um e trocar o n noa barra de endereços.

**Comment by pocapratica** [comment]
Em Vendas, ao incluir uma venda, na parte do produto, o sistema não busca os produtos cadastrados. Mesmo que eu digite o nome do produto exatamente igual ou mesmo o código do produto, ele não completa, e depois, ao adicionar, ele dá erro:
Ocorreu um erro ao tentar adicionar produto.

**Comment by RamonSilva20** [comment]
Olá @pocapratica, os produtos estão marcados com o tipo de movimento saída?

**Comment by pocapratica** [comment]
Vou conferir amanhã. Pode ser que seja isso, já que fiz a migração da versão antiga e os dados não foram modificados.
Amanhã aviso. Obrigado.

**Comment by pocapratica** [comment]
@RamonSilva20 era esse mesmo o problema!
Acho que como apenas atualizei o sistema, da versão antiga pra essa, ele não tinha esse campo entrada/saída na tabela, portanto, ficava com valor vazio.
Selecionei saída e agora já aparece na venda.

Um ponto pra observar na hora da atualização de versões. Informar isso no arquivo de ajuda da atualização.

Obrigado.

**Comment by randalrenye** [comment]
Quando gero qualquer relatórios, da o seguinte erro:

"Erro
Falha ao carregar documento PDF."

Como corrigi-lo?

**Comment by pocapratica** [comment]
@hardbrasil 
> Erro de Demora excessiva no Campo Cidade e Estado.
> O meu sempre apresentou este erro ao cadastrar a cidade e o estado, nos demais campos tudo OK. Esse erro já ocorria anteriormente. Alguém mais notou isso?

Sempre aconteceu isso comigo. Eu acho que pode ser o auto completar do Chrome. Porque ele puxa dados que eu já usei em outros formulários.

**Comment by ramonsousa89** [comment]
Quando gero qualquer relatórios, da o seguinte erro:

"Erro
Falha ao carregar documento PDF."

Como corrigi-lo?

**Comment by brennodornelas** [comment]
Alguem conseguiu resolver o problema do Mycrpt no xampp?

**Comment by RamonSilva20** [comment]
Bom dia @brennodornelas. Qual exatamente o problema que você está tendo?
