### ISSUE TITLE
Alguém configurou o envio de e-mail utilizando a  Hostgator?

### ISSUE THREAD

**Issue by dgcursino** [RamonSilva20/mapos#420]

**Comment by thiagoferreira14** [comment]
alguem ?
Estou com problemas para configurar tambem...
Ja tentei varios crons e nenhum deu certo

**Comment by BrunoMichael** [comment]
Questão do CRON esse deu certo no meu.
`*/2 * * * * /opt/php70/bin/php /home2/arpadeco/public_html/mapos/index.php email/process
*/5 * * * * /opt/php70/bin/php /home2/arpadeco/public_html/mapos/index.php email/retry`

1 - Observa se o home2 é semelhante ou se é apenas home.
2 - arpadeco substituir para seu usuario.
3- No lugar de mapos a raiz de sua pasta, se for mapos pode deixar.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
