### ISSUE TITLE
Boa tarde, tbm estou com esse problema de login.

### ISSUE THREAD

**Issue by passalia** [RamonSilva20/mapos#421]
Boa tarde, tbm estou com esse problema de login.
Sou bem leigo em php, como crio esse usuário?
Dentro do phpmyadmin?

_Originally posted by @juninho9494 in https://github.com/RamonSilva20/mapos/issues/415#issuecomment-529002792_

Isso, dentro do phpmyadmin você consegue criar o usuário. Daí é só seguir como comentei ali em cima. Ou fazer como o brtechst comentou, também funciona.

**Comment by juninho9494** [comment]
boa noite, consegui criar um usuário novo. Com o login admin@admin.com e senha 123456. blz até ai tudo certo!
Agora quando faço o login não dá erro, mas ele começa a carregar e volta pra tela de login.
Conseguem me ajudar??
Obrigado pessoal!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
