### ISSUE TITLE
Erro no login pelo celular

### ISSUE THREAD

**Issue by Diezare** [RamonSilva20/mapos#422]
Olá, estou com um pequeno problema ao acessar o sistema pelo celular. Ele fica com a barra azul rodando e não entra. O que tenho que fazer para entrar por ele?
Pelo PC entra normal

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
