### ISSUE TITLE
O módulo de vendas não preenche automaticamente o produto

### ISSUE THREAD

**Issue by waldemaris** [RamonSilva20/mapos#423]
Estou testando o sistema, e tenho um erro, no módulo de vendas ao adicionar o produto o preenchimento automático não aparece, verifique o código e aparentemente tudo está bem com alguém com esse problema, parabéns.

**Comment by waldemaris** [comment]
> 
> 
> Amigo, cadastra o produto, e coloca ele como saida, se ele tiver como entrada ele n aparece, tive essa duvida e resolvi assim.

Amigo, estou tentando fazer uma venda, por exemplo, nessa seção, quando vou adicionar o produto que o preenchimento automático não faz e não entendo por que, tudo está aparentemente bem, quando vou ao O.S. na guia do produto, se o preenchimento automático funcionar
![captura2](https://user-images.githubusercontent.com/53951088/64895276-4aec7080-d639-11e9-80ac-85eb713d630a.png)
![captura1](https://user-images.githubusercontent.com/53951088/64895280-4cb63400-d639-11e9-94d6-112806a6f172.png)

**Comment by waldemaris** [comment]
Verifique a visualização do MVC e o modelo do controlador, e não encontro nenhum problema no código, ambos no sistema operacional O.S. (Editar) como em Venda (Editar), imagem de código anexada
![captura3](https://user-images.githubusercontent.com/53951088/64896056-b20b2480-d63b-11e9-9836-5eab81371618.png)
![captura4](https://user-images.githubusercontent.com/53951088/64896057-b33c5180-d63b-11e9-9833-fdfc00ed0c49.png)

**Comment by mmonzato** [comment]
@waldemaris como foi dito pelo amigo acima, o problema não está no código e sim no cadastro do produto, provavelmente ele não está com a opção de saída marcada, com isso o autocompletar não vai funcionar na tela de vendas.

**Comment by waldemaris** [comment]
> como foi dito pelo amigo acima, o problema não está no código e sim no cadastro do produto, provavelmente ele não está com a opção de saída marcada, com isso o autocompletar não vai funcionar na tela de vendas.

Amigo, eu não entendo, porque o produto já está registrado no módulo do produto, o engraçado é que, ao editar a ordem de serviço na guia produto, quando você adiciona produtos se o preenchimento automático sair, e no módulo de vendas, quando você deseja fazer uma venda, o preenchimento automático não mostrado, imagens anexadas
![captura5](https://user-images.githubusercontent.com/53951088/64970106-68505300-d862-11e9-8c24-3f5fddbe19b5.png)
![captura6](https://user-images.githubusercontent.com/53951088/64970107-68505300-d862-11e9-877c-29164cb5be6a.png)
![captura7](https://user-images.githubusercontent.com/53951088/64970109-68505300-d862-11e9-9fcd-7692a1cb865d.png)

**Comment by mmonzato** [comment]
@waldemaris verifica se na tabela "produtos" da sua base de dados, as colunas entrada e saída estão com o número 1.
![image](https://user-images.githubusercontent.com/55327526/64970506-57acd680-d87c-11e9-8ca9-f11905826c04.png)

**Comment by waldemaris** [comment]
> 
> 
> @waldemaris verifica se na tabela "produtos" da sua base de dados, as colunas entrada e saída estão com o número 1.
> ![image](https://user-images.githubusercontent.com/55327526/64970506-57acd680-d87c-11e9-8ca9-f11905826c04.png)

verifique no banco de dados na entrada e saída estão com 0
![captura8](https://user-images.githubusercontent.com/53951088/64972748-0cd49400-d867-11e9-9cea-68e4c2d6a167.png)

**Comment by mmonzato** [comment]
@waldemaris por isso que não funciona o autocompletar como lhe disse na primeira resposta. O problema está no cadastro do produto, ele não está configurado para entrada e nem saída, como o valor da saida está 0, o autocompletar não vai funcionar na tela de vendas.

**Comment by waldemaris** [comment]
> 
> 
> @waldemaris por isso que não funciona o autocompletar como lhe disse na primeira resposta. O problema está no cadastro do produto, ele não está configurado para entrada e nem saída, como o valor da saida está 0, o autocompletar não vai funcionar na tela de vendas. Vai na tela de edição do produto e verifica se os tipos de movimento estão marcados como na imagem abaixo, provavelmente não estão pela imagem que vc mandou do seu banco..
> ![image](https://user-images.githubusercontent.com/55327526/64974632-91351000-d883-11e9-8731-7cfa2a7e8c33.png)

Amigo obrigado pela ajuda, estou percebendo que na edição do produto não tenho as opções de entrada e saída, a versão do MapOS que estou testando é a 3.8.0 será alguma nova modificação?

![captura9](https://user-images.githubusercontent.com/53951088/64975582-98045880-d86c-11e9-9680-d7471686c10d.png)

**Comment by mmonzato** [comment]
@waldemaris essa opção já tem a muito tempo, alguém modificou o sistema para você ? Provavelmente na sua tela de cadastro de produto também não tem essas opções. O seu sistema parece estar com as telas muito antigas onde não tinham essas opções. Parece estar mesclado a versão 3.8 com uma versão mais antiga.

**Comment by waldemaris** [comment]
@mmonzato , Amigo gracias por la ayuda, estaba revisando las lineas de codigo en la vista del editarProduto.php y el codigo esta asi 
`<div class="row-fluid" style="margin-top:0">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5>Editar Producto</h5>
            </div>
            <div class="widget-content nopadding">
                <?php echo $custom_error; ?>
                <form action="<?php echo current_url(); ?>" id="formProduto" method="post" class="form-horizontal" >
                     <div class="control-group">
                        <?php echo form_hidden('idProdutos',$result->idProdutos) ?>
                        <label for="descricao" class="control-label">Descripción<span class="required">*</span></label>
                        <div class="controls">
                            <input id="descricao" type="text" name="descricao" value="<?php echo $result->descricao; ?>"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="unidade" class="control-label">Unidad<span class="required">*</span></label>
                        <div class="controls">
                            <input id="unidade" type="text" name="unidade" value="<?php echo $result->unidade; ?>"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="precoCompra" class="control-label">Precio de Compra<span class="required">*</span></label>
                        <div class="controls">
                            <input id="precoCompra" class="money" type="text" name="precoCompra" value="<?php echo $result->precoCompra; ?>"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="precoVenda" class="control-label">Precio de Venta<span class="required">*</span></label>
                        <div class="controls">
                            <input id="precoVenda" class="money" type="text" name="precoVenda" value="<?php echo $result->precoVenda; ?>"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="estoque" class="control-label">Stock<span class="required">*</span></label>
                        <div class="controls">
                            <input id="estoque" type="text" name="estoque" value="<?php echo $result->estoque; ?>"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="estoqueMinimo" class="control-label">Stock Mínimo</label>
                        <div class="controls">
                            <input id="estoqueMinimo" type="text" name="estoqueMinimo" value="<?php echo $result->estoqueMinimo; ?>"  />
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="span12">
                            <div class="span6 offset3">
                                <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Modificar</button>
                                <a href="<?php echo base_url() ?>index.php/produtos" id="" class="btn"><i class="icon-arrow-left"></i> Volver</a>
                            </div>
                        </div>
                    </div>


                </form>
            </div>

         </div>
     </div>
</div>


<script src="<?php echo base_url()?>js/jquery.validate.js"></script>
<script src="<?php echo base_url();?>js/maskmoney.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $(".money").maskMoney();

        $('#formProduto').validate({
            rules :{
                  descricao: { required: true},
                  unidade: { required: true},
                  precoCompra: { required: true},
                  precoVenda: { required: true},
                  estoque: { required: true}
            },
            messages:{
                  descricao: { required: 'Campo Requerido.'},
                  unidade: {required: 'Campo Requerido.'},
                  precoCompra: { required: 'Campo Requerido.'},
                  precoVenda: { required: 'Campo Requerido.'},
                  estoque: { required: 'Campo Requerido.'}
            },

            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            }
           });
    });
</script>




`
faça o download das visualizações novamente e, na verdade, é diferente da que você tinha, substitua a visualização e já mostre as opções
O código original que mostra a opção de entrada e saída é o seguinte
`<style>
/* Hiding the checkbox, but allowing it to be focused */
.badgebox
{
    opacity: 0;
}

.badgebox + .badge
{
    /* Move the check mark away when unchecked */
    text-indent: -999999px;
    /* Makes the badge's width stay the same checked and unchecked */
	width: 27px;
}

.badgebox:focus + .badge
{
    /* Set something to make the badge looks focused */
    /* This really depends on the application, in my case it was: */
    
    /* Adding a light border */
    box-shadow: inset 0px 0px 5px;
    /* Taking the difference out of the padding */
}

.badgebox:checked + .badge
{
    /* Move the check mark back when checked */
	text-indent: 0;
}
</style>
<div class="row-fluid" style="margin-top:0">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5>Editar Produto</h5>
            </div>
            <div class="widget-content nopadding">
                <?php echo $custom_error; ?>
                <form action="<?php echo current_url(); ?>" id="formProduto" method="post" class="form-horizontal">
                     <div class="control-group">
                        <?php echo form_hidden('idProdutos', $result->idProdutos) ?>
                        <label for="descricao" class="control-label">Descrição<span class="required">*</span></label>
                        <div class="controls">
                            <input id="descricao" type="text" name="descricao" value="<?php echo $result->descricao; ?>" />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Tipo de Movimento</label>
                        <div class="controls">
                        <label for="entrada" class="btn btn-default" style="margin-top: 5px;">Entrada
                                <input type="checkbox" id="entrada" name="entrada" class="badgebox" value="1" <?= ($result->entrada == 1) ? 'checked' : '' ?>>
                                <span class="badge">&check;</span>
                            </label>
                            <label for="saida" class="btn btn-default" style="margin-top: 5px;">Saída
                                <input type="checkbox" id="saida" name="saida" class="badgebox" value="1" <?= ($result->saida == 1) ? 'checked' : '' ?>>
                                <span class="badge">&check;</span>
                            </label>
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="precoCompra" class="control-label">Preço de Compra<span class="required">*</span></label>
                        <div class="controls">
                            <input id="precoCompra" class="money" type="text" name="precoCompra" value="<?php echo $result->precoCompra; ?>" />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="precoVenda" class="control-label">Preço de Venda<span class="required">*</span></label>
                        <div class="controls">
                            <input id="precoVenda" class="money" type="text" name="precoVenda" value="<?php echo $result->precoVenda; ?>" />
                        </div>
                    </div>

                    <div class="control-group">
                    <label for="unidade" class="control-label">Unidade<span class="required">*</span></label>
                    <div class="controls">
                        <select id="unidade" name="unidade">
                        <option value="UN" <?= ($result->unidade == 'UN') ? 'selected' : '' ?>>Unidade</option>
                                <option value="KG" <?= ($result->unidade == 'KG') ? 'selected' : '' ?>>Kilograma</option>
                                <option value="LT" <?= ($result->unidade == 'LT') ? 'selected' : '' ?>>Litro</option>
                                <option value="CX" <?= ($result->unidade == 'CX') ? 'selected' : '' ?>>Caixa</option>
                        </select>                        
                    </div>
                    </div>                    

                    <div class="control-group">
                        <label for="estoque" class="control-label">Estoque<span class="required">*</span></label>
                        <div class="controls">
                            <input id="estoque" type="text" name="estoque" value="<?php echo $result->estoque; ?>" />
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="estoqueMinimo" class="control-label">Estoque Mínimo</label>
                        <div class="controls">
                            <input id="estoqueMinimo" type="text" name="estoqueMinimo" value="<?php echo $result->estoqueMinimo; ?>" />
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="span12">
                            <div class="span6 offset3">
                                <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Alterar</button>
                                <a href="<?php echo base_url() ?>index.php/produtos" id="" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                            </div>
                        </div>
                    </div>


                </form>
            </div>

         </div>
     </div>
</div>


<script src="<?php echo base_url() ?>assets/js/jquery.validate.js"></script>
<script src="<?php echo base_url(); ?>assets/js/maskmoney.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".money").maskMoney();
        
        $('#formProduto').validate({
            rules: {
                descricao: {
                    required: true
                },
                unidade: {
                    required: true
                },
                precoCompra: {
                    required: true
                },
                precoVenda: {
                    required: true
                },
                estoque: {
                    required: true
                }
            },
            messages: {
                descricao: {
                    required: 'Campo Requerido.'
                },
                unidade: {
                    required: 'Campo Requerido.'
                },
                precoCompra: {
                    required: 'Campo Requerido.'
                },
                precoVenda: {
                    required: 'Campo Requerido.'
                },
                estoque: {
                    required: 'Campo Requerido.'
                }
            },

            errorClass: "help-inline",
            errorElement: "span",
            highlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            }
        });
    });
</script> `
![captura10](https://user-images.githubusercontent.com/53951088/64976315-3349fd80-d86e-11e9-83f9-5290b0e0b6bb.png)

**Comment by waldemaris** [comment]
@mmonzato a única coisa que faço na modificação é a tradução do português para o espanhol latino, o sistema que estou testando para uso pessoal e para poder acompanhar as ordens de serviço e o inventário de produtos e vendas

**Comment by mmonzato** [comment]
@waldemaris não entendi muito bem o que você disse, vc alterou o view e agora aparece as opções de tipo de movimento é isso ? conforme na imagem que você mandou, veja que estão desmarcadas as opções, você teria que marcar para o autocompletar funcionar na tela de vendas.

**Comment by waldemaris** [comment]
> 
> 
> @waldemaris não entendi muito bem o que você disse, vc alterou o view e agora aparece as opções de tipo de movimento é isso ? conforme na imagem que você mandou, veja que estão desmarcadas as opções, você teria que marcar para o autocompletar funcionar na tela de vendas.

Quero dizer que a visualização que você tem é diferente da que eu tinha, baixe o mapos-master novamente copie o código de visualização do editProduto.php e os botões "Entrada e Saída" já aparecem

**Comment by mmonzato** [comment]
@waldemaris marca as opções de entrada e saída o item agora, clica em alterar, verifica se os campos entrada e saída no banco de dados estão com valor 1 e depois testa o autocompletar na tela de vendas.

**Comment by waldemaris** [comment]
> 
> 
> @waldemaris marca as opções de entrada e saída o item agora, clica em alterar, verifica se os campos entrada e saída no banco de dados estão com valor 1 e depois testa o autocompletar na tela de vendas.

e funciona, obrigado pela ajuda, selecionando a troca de opções no banco de dados de 0 a 1

**Comment by mmonzato** [comment]
@waldemaris o problema foi resolvido então ?

**Comment by waldemaris** [comment]
> 
> 
> @waldemaris o problema foi resolvido então ?

o problema foi resolvido graças

**Comment by marcosaquino34** [comment]
![image](https://user-images.githubusercontent.com/21271823/69497944-ff6c0380-0ec0-11ea-92f6-be1f52b788cd.png)

seria bom poder busca o produto pelo código de barra para realizar a venda!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
