### ISSUE TITLE
Problemas de login ** Os dados de acesso estão incorretos, por favor tente novamente!

### ISSUE THREAD

**Issue by borgesjsb** [RamonSilva20/mapos#424]
Mesmo com a senha 123456 e email corretos no banco de dados em usuarios ele nao loga

1 | Admin | MG-25.502.560 | 600.021.520-87 | Rua Acima | 12 | Alvorada | Teste | MG | skyler@skyler.net.br | 123456 | 0000-0000 |   | 1 | 2018-09-09 |

**Comment by Triaca** [comment]
a senha no BANCO DE DADOS tem que ser a chave criptografada e não 123456. se você alterou lá, fez errado!

mude a senha para essa, é 123456 mas criptografada.: $2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO

**Comment by Triaca** [comment]
Se der certo feche o Issue por favor.

**Comment by borgesjsb** [comment]
Só que não. 

![image](https://user-images.githubusercontent.com/55168713/64736364-d7bfee80-d4c0-11e9-8d5f-a8fa6b9492fa.png)


![image](https://user-images.githubusercontent.com/55168713/64736325-c545b500-d4c0-11e9-9f52-1f4320655320.png)

**Comment by borgesjsb** [comment]
Mesmo rodando o script, eu coloco a senha maior e não entra. Vai entender.

**Comment by Triaca** [comment]
cara, no login do site coloca 123456
a senha que te mandei é a CRIPTOGRAFADA ela só é usada no BD,

**Comment by borgesjsb** [comment]
![image](https://user-images.githubusercontent.com/55168713/64737900-494d6c00-d4c4-11e9-8d0d-c1b09d1aa182.png)

**Comment by Triaca** [comment]
Fecha o navegador e limpa os cookies, tente novamente.
Caso o problema persista, faça um backup do banco de dados casa tenha produtos, serviços etc cadastrados.
Faça uma instalação limpa sem alterar nada e suba o backup do banco de dados.

Provavelmente você alterou alguma função no FTP que perdeu o direcionamento da página.
Infelizmente nisso não consigo te ajudar.

**Comment by borgesjsb** [comment]
Vou reinstalar

**Comment by borgesjsb** [comment]
Infelizmente, continua. 

![image](https://user-images.githubusercontent.com/55168713/64741889-92a3b880-d4d0-11e9-8891-eb6c9ab30ef5.png)

**Comment by lagethomas** [comment]
Cara, altera a data de expiração ko banco para uma data mais a frente da
data de hoje, ela está vencida, com isso, o acesso expira.
Coloca "01-01-3000

Em sáb, 14 de set de 2019 07:39, borgesjsb <notifications@github.com>
escreveu:
