### ISSUE TITLE
Vincular opção do menu dentro do editar OS.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#425]
Bom dia,
Necessito vincular a opção "recebido" para quando for marcado dentro do faturar, automaticamente mudar o status da O.S para status "pago".
Procurei dentro do application/views/os e olhei todos os .php e não achei nada neles.
Lá existe o check box para recebimento porém não tem comando atrelando o status "faturado" ou quaisquer outros.

![Screenshot_1](https://user-images.githubusercontent.com/21310068/64697309-9141a400-d46e-11e9-8d94-6ceec10a2dd4.png)
![Screenshot_2](https://user-images.githubusercontent.com/21310068/64697315-956dc180-d46e-11e9-966b-79ef32b1ee6b.png)

**Comment by mmonzato** [comment]
@Triaca você precisar editar o seguinte arquivo \mapos-master\application\controllers\Os.php, quase no final do arquivo você vai encontrar a função faturar. Segue abaixo a função modificada para fazer o que você precisa.
`    public function faturar()
    {

        $this->load->library('form_validation');
        $this->data['custom_error'] = '';


        if ($this->form_validation->run('receita') == false) {
            $this->data['custom_error'] = (validation_errors() ? '<div class="form_error">' . validation_errors() . '</div>' : false);
        } else {


            $vencimento = $this->input->post('vencimento');
            $recebimento = $this->input->post('recebimento');

            try {

                $vencimento = explode('/', $vencimento);
                $vencimento = $vencimento[2] . '-' . $vencimento[1] . '-' . $vencimento[0];

                if ($recebimento != null) {
                    $recebimento = explode('/', $recebimento);
                    $recebimento = $recebimento[2] . '-' . $recebimento[1] . '-' . $recebimento[0];
                }
            } catch (Exception $e) {
                $vencimento = date('Y/m/d');
            }

            $data = array(
                'descricao' => set_value('descricao'),
                'valor' => $this->input->post('valor'),
                'clientes_id' => $this->input->post('clientes_id'),
                'data_vencimento' => $vencimento,
                'data_pagamento' => $recebimento,
                'baixado' => $this->input->post('recebido') ?: 0,
                'cliente_fornecedor' => set_value('cliente'),
                'forma_pgto' => $this->input->post('formaPgto'),
                'tipo' => $this->input->post('tipo')
            );

            if ($this->os_model->add('lancamentos', $data) == true) {

                $os = $this->input->post('os_id');
				
				$recebido = $this->input->post('recebido');
				

                $this->db->set('faturado', 1);
                $this->db->set('valorTotal', $this->input->post('valor'));
				if($recebido==0){
					$this->db->set('status', 'Faturado');
				}else{
					$this->db->set('status', 'Pago');
				}
                $this->db->where('idOs', $os);
                $this->db->update('os');

                $this->session->set_flashdata('success', 'OS faturada com sucesso!');
                $json = array('result' =>  true);
                echo json_encode($json);
                die();
            } else {
                $this->session->set_flashdata('error', 'Ocorreu um erro ao tentar faturar OS.');
                $json = array('result' =>  false);
                echo json_encode($json);
                die();
            }
        }

        $this->session->set_flashdata('error', 'Ocorreu um erro ao tentar faturar OS.');
        $json = array('result' =>  false);
        echo json_encode($json);
    }`

**Comment by Triaca** [comment]
@mmonzato deu certo Muito obrigado!!!
