### ISSUE TITLE
Configurações de produto

### ISSUE THREAD

**Issue by Gustelinha** [RamonSilva20/mapos#426]
Queria uma ajuda pra colocar um produto em M² do que no lugar de unidade kilo e etc...

**Comment by Pr3d4dor** [comment]
Olá, basta você editar o select nos arquivos `/application/view/produtos/adicionarProduto.php` e `/application/view/produtos/adicionarProduto.php`

No arquivo adicionarProduto:
```
<select id="unidade" name="unidade">
    <option value="UN">Unidade</option>
     <option value="KG">Kilograma</option>
     <option value="LT">Litro</option>
     <option value="CX">Caixa</option>
     <option value="M2">M²</option>
</select>
```

No arquivo editarProduto:
```
<select id="unidade" name="unidade">
    <option value="UN" <?= ($result->unidade == 'UN') ? 'selected' : '' ?>>Unidade</option>
    <option value="KG" <?= ($result->unidade == 'KG') ? 'selected' : '' ?>>Kilograma</option>
    <option value="LT" <?= ($result->unidade == 'LT') ? 'selected' : '' ?>>Litro</option>
    <option value="CX" <?= ($result->unidade == 'CX') ? 'selected' : '' ?>>Caixa</option>
    <option value="M2" <?= ($result->unidade == 'M2') ? 'selected' : '' ?>>M²</option>
    <option value="OT" <?= ($result->unidade == 'OT') ? 'selected' : '' ?>>Outro</option>
</select>
```

Logo vou fazer uma PR adicionando essa opção e também uma opção "Outro" para contemplar os demais casos.

**Comment by betocardos** [comment]
Boa tarde Pessoal,
GRAAANDEEE PROJETO, OBRIGADO #RamonSilva20!
 Preciso de ajuda, adicionei um campo ao produto e tá dando o erro: A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$Lote

Filename: produtos/produtos.php

Line Number: 73
agradeço se alguém puder me ajudar.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
