### ISSUE TITLE
Erro ao Incluir Produto em OS

### ISSUE THREAD

**Issue by flaviolear** [RamonSilva20/mapos#428]
Bom dia pessoal, estou com um problema na hora de inserir um produto na os retorna o erro "Ocorreu um erro ao tentar adicionar produto." e o mesmo está acontecendo com serviços

**Comment by Pr3d4dor** [comment]
Somente com essa descrição de erro fica difícil te ajudar.

Se você conseguir dar mais detalhes sobre o erro ficará mais fácil para podermos te ajudar.

**Comment by flaviolear** [comment]
Amigo, desculpa a demora em responder, mas consegui resolver, não sei porque mas havia algo errado no banco de dados, exclui e criei novamente e deu tudo certo

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
