### ISSUE TITLE
Pequisa nomes de clientes (clientes cadastrados) 

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#429]
Nao tenho um problema com o sistema em si, procuro fazer algumas modificação dentro do meu conhecimento para melhor me atender, só que agora com vários clientes cadastrados as vezes uns troca de telefone, endereço, etc. e não consigo localizá-los com facilidade, as vezes tenho que criar outro apenas por causa desse detalhe, poderia inserir um mecanismo de busca de clientes na guia "mapos/index.php/clientes" e tambem em "mapos/index.php/produtos" pois la acontece a mesma coisa quando tenho que alterar algo.

**Comment by Pr3d4dor** [comment]
Essa seria uma boa funcionalidade porém não é tão simples de implementar.

Quando eu tiver um tempo livre eu posso tentar.
