### ISSUE TITLE
Comentários Diversos Agradecimentos e Outros Assuntos.

### ISSUE THREAD

**Issue by BiecoTech** [RamonSilva20/mapos#43]
Olá, Ramon!

Parabéns pelo trabalho... Muito bom!

**Comment by RamonSilva20** [comment]
Bom dia. Obrigado pela mensagem.

**Comment by hardbrasil** [comment]
Amigo Bieco Tech alterei o Título do  Post pois estamos em colaboração com o Ramom para a Organização da Página do Projeto senão fica muito Tumultuado aqui.Para os comentários diversos use este post Demais assuntos verificar se já existe um issue relacionado.

Aproveito aqui também para agradecer ao Ramom pela criação deste projeto. Assim como o Linux projetos que tenham cooperação crescem pois "Juntos somos mais".

**Comment by BiecoTech** [comment]
Tranquilo. Tmj

**Comment by marcelo9716** [comment]
colega, indico como sugestao a criacao de um serviço que seja modificavel no ato da ordem do servico, podendo mudar seu  nome e/ou valor...

**Comment by P4R4G0N** [comment]
@marcelo9716 Isso é muito interessante na parte da inclusão de um serviço ou produto na ordem de serviço. Por isso tb já foi sugerido (#37 - ver desnormatização) que os dados do produto/serviço também sejam gravados na tabela/entidade __itens_de_venda ou produtos_os ou servicos_os__, para melhor documentação/histórico independentemente de alteração do produto ou serviço no seu respectivo cadastro.

**Comment by marcelo9716** [comment]
@P4R4G0N sim, seria o melhor a se fazer, pois da forma atual, se por exemplo aumentarmos o valor de um produto que esteja linkado a uma OS, mesmo que aquela OS esteja fechada o preço será alterado nela, oque não deveria ocorrer teoricamente...
