### ISSUE TITLE
Registros duplicados

### ISSUE THREAD

**Issue by BrunoMichael** [RamonSilva20/mapos#431]
Clientes duplicados, OS duplicadas e quando faturar duplica também. Porém não é toda hora e muito intermitente.

Verifiquei o código para verificar se não tinha algum submit a mais.

**Comment by Pr3d4dor** [comment]
Não consegui reproduzir esse erro.

Quais as configurações do seu ambiente (versão do PHP, sistema operacional, hospedagem, etc.)?

**Comment by willph** [comment]
@pr3d4dor acredito que a falha do cliente duplicado, seja porque da para cadastra a mesma pessoa 2 vezes.
Não tem validação de CPF e nem verificação do mesmo se já existe no BD.

**Comment by willph** [comment]
Você pode digitar qualquer número que passa.
Temos que colocar validação de CPF e CNPJ

**Comment by BrunoMichael** [comment]
Questão de clientes só aceita  um CPF/CNPJ até então não apareceu mais, só que a OS ainda duplica. Depois de tantos registros aparece 1 duplicado.

**Comment by mmonzato** [comment]
a questão do CPF/CNPJ é só editar o form_validation e colocar que o campo "documento' é único, da mesma forma que foi configurado o campo CPF da tabela de usuários.

**Comment by BrunoMichael** [comment]
Sim, a questão é como pode ser feito o bloqueio em OS e quando é faturado.

**Comment by mmonzato** [comment]
@BrunoMichael para entender melhor o seu problema, no caso se o sistema não permitisse a emissão de uma nova OS para o cliente enquanto tivesse uma OS com o status diferente de Faturado, resolveria seu problema ou hoje você pode ter mais de uma OS aberta para o mesmo cliente ?

**Comment by BrunoMichael** [comment]
O cliente pode ter mais de duas OS aberta, por exemplo pode ser uma empresa que tem dois equipamentos diferentes.

**Comment by crimat06** [comment]
Toda vez que insiro um cliente novo, produto ou serviço estão sendo salvos duplicados e apos salvar cai em uma pagina de erro 404, mas a inclusão se mantem normalmente...

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
