### ISSUE TITLE
Problema com email

### ISSUE THREAD

**Issue by wnjulio** [RamonSilva20/mapos#433]
os emails ficam sempre pendentes, preciso criar um trabalho realmente ou manualmente eles devem ser enviados com sucesso?
![Sem título](https://user-images.githubusercontent.com/42722761/65009968-db021280-d8e4-11e9-84a7-647f1a0b972c.png)

**Comment by Pr3d4dor** [comment]
Você precisa configurar um worker para enviar os emails a cada X minutos conforme documentação (REAME):

```
Configurar cron jobs para envio de e-mail
Enviar emails pendentes a cada 2 minutos.

    */2 * * * * php /var/www/index.php email/process

Enviar emails com falha a cada 5 minutos.

    */5 * * * * php /var/www/index.php email/retry

Obs: O path até o index.php (/var/www/) deve ser configurado conforme o seu ambiente
```

**Comment by wnjulio** [comment]
o caminho do meu é assim: www.dominio.com/os   
como eu faria ?!  eu teria de usar os  '*' ?  obg

**Comment by wnjulio** [comment]
consegui fazer ele disparar, porem chega mensagem falando:/usr/local/cpanel/bin/jailshell: /home3/wnsof762/public_html/os/index.php/email/process: **Not a directory**

**Comment by wnjulio** [comment]
Could not open input file: /home/wnsof762/public_html/os/index.php/email/process

**Comment by Pr3d4dor** [comment]
Sua hospedagem é linux?

Se os emails estiverem disparando mesmo com o erro, não tem problema

Os "*" são marcaçoes do cron, se vc quer saber mais pesquise no google sobre crontab.

**Comment by marceloccarmo** [comment]
Boa noite, desculpe a falta de conhecimento, mais não consigo enviar E-mail , e nao consigo configura os CRON, seria porque uso o servidor HOSTINGER?

**Comment by luizejessica** [comment]
Já tentei de todas as formas e não funciona... tem como dá uma ajuda.

http://consultoriaclick.com.br/index.php/email/process

**Comment by luizejessica** [comment]
Não aceita espaço depois do index.php 

Você deve informar apenas a URL. Por exemplo: http://meusite.com/cron.php.

**Comment by NATA-RMG** [comment]
Bom dia, nao envia email ?

**Comment by luizejessica** [comment]
Isso, não esta enviando tudo configurado conforme tutorial... se puder me
ajudar fico muito muito grato...

Esta hospedado no umbler.

Em ter, 19 de nov de 2019 10:16, NATA-RMG <notifications@github.com>
escreveu:

**Comment by NATA-RMG** [comment]
Bom dia, eu tambem nao estou conseguindo enviar e-mail o server é local.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.

**Comment by brtechst** [comment]
> Você precisa configurar um worker para enviar os emails a cada X minutos conforme documentação (REAME):
> 
> ```
> Configurar cron jobs para envio de e-mail
> Enviar emails pendentes a cada 2 minutos.
> 
>     */2 * * * * php /var/www/index.php email/process
> 
> Enviar emails com falha a cada 5 minutos.
> 
>     */5 * * * * php /var/www/index.php email/retry
> 
> Obs: O path até o index.php (/var/www/) deve ser configurado conforme o seu ambiente
> ```

![image](https://user-images.githubusercontent.com/53625745/83365770-0e0c0980-a381-11ea-8860-6ac3b96572c8.png)

Não estou sabendo se fiz certo, queria entender melhor como faço isso na hospedagem hostinger.

Fiz da forma abaixo, ta certo?

![image](https://user-images.githubusercontent.com/53625745/83365794-3562d680-a381-11ea-8d04-e5c363aea73f.png)

Não acho a opção de 2 minutos nem 5 minutos.

**Comment by brtechst** [comment]
"acesso" é o nome da pasta onde está meu sistema.

Caso eu esteja fazendo errado gostaria de saber se alguém pode explicar para eu fazer do jeito certo.

**Comment by Pr3d4dor** [comment]
Se não tem opção de 2 ou 5, vc terá que usar as que a tua hospedagem disponibiliza.

**Comment by brtechst** [comment]
> Se não tem opção de 2 ou 5, vc terá que usar as que a tua hospedagem disponibiliza.

Perfeito.

Na imagem que coloquei ai ta certo o caminho? Essa parte que estou confuso.

**Comment by Pr3d4dor** [comment]
Sim, está certo

**Comment by brtechst** [comment]
@Pr3d4dor tu é muito eficiente cara, responde muito rápido.

Amigo você faz serviço por fora? Tenho o mapos todo modificado (paguei um programador uma vez) e queria colocar as funcionalidades da nova versão na minha.

**Comment by brtechst** [comment]
> Sim, está certo

ah então show de bola, vou esperar aqui para ver se dispara o email.

**Comment by brtechst** [comment]
Estou tendo esse retorno la no cron jobs, sabe como posso resolver?

Could not open input file: /home/u987064415/public_html/acesso/index.php

**Comment by brtechst** [comment]
Minha hospedagem é da Hostinger acho que talvez uma das mais comuns.

**Comment by brtechst** [comment]
Dei permissão no arquivo index mas não deu certo

![image](https://user-images.githubusercontent.com/53625745/83367969-7cef5f80-a38d-11ea-81c5-4e69000a3316.png)

**Comment by paulosardinha** [comment]
estou com mesmo problema e nada funciona
