### ISSUE TITLE
Assinatura na tela

### ISSUE THREAD

**Issue by gsps2** [RamonSilva20/mapos#434]
Fala ai galera, bom dia! 
Estou achando esse projeto muito massa, ele está suprindo minhas necessidades totais. 
Há uma única coisa que se alguem pudesse implementar seria massa!
Não tenho a necessidade de imprimir a OS, gostaria de na tela mesmo o cliente assinar virtualmente, alguém ai fez isso e pode mandar os códigos que usou?
Abraços, galera ;)

**Comment by mmonzato** [comment]
@gsps2 fale um pouco mais da sua idéia, o cliente assinaria em um tablet, celular ?

**Comment by gsps2** [comment]
Opa, sim! Pensei em algo nesse tipo, quando setar "os finalizada", ter a opção de adicionar a assinatura dele ali mesmo, sem a necessidade de imprimir papel, saca?
isso na prática funciona bem, pois veja, ele terá uma cópia disso via e-mail.
Acredito que agilizaria os processos. 
#Sustentabilidade Brow :)

**Comment by wnjulio** [comment]
Estou fazendo separadamente, um aplicativo, que funciona no tablet, dai o cliente assina e  eu so coloco  o numero da o,s, a assinatura sobe como imagem e automaticamente vai pra assinatura do cliente.

**Comment by gsps2** [comment]
> Estou fazendo separadamente, um aplicativo, que funciona no tablet, dai o cliente assina e eu so coloco o numero da o,s, a assinatura sobe como imagem e automaticamente vai pra assinatura do cliente.

Você poderia disponibilizar isso pra gente, amigo? Não é exatamente como pensei, porém, vai ajudar com certeza!!!
Se já fizer a comunicação e subir na hora pra assinatura do cliente, seria ideal!
Pensei até em fazer algo em html5 com o canvas, mas não fui bem sucedido! :/

**Comment by giampaulo** [comment]
como ficou essa ideia?

**Comment by Pr3d4dor** [comment]
Está nos planos futuros para implementação.
