### ISSUE TITLE
PROBLEMA COM LOGIN

### ISSUE THREAD

**Issue by juninho9494** [RamonSilva20/mapos#435]
Bom dia, não consigo fazer login, já li todos os posts aqui pra ver se conseguia esclarecer meu problema mas até agora nada.
Bom vamos lá, já segui todos os passos. Instalação, atualização, tentei manualmente tanto instalar como atualizar. Agora em fim consegui instalar só que não realiza login. Fica carregando a barra azul infinitamente.

Por gentileza se puderem me ajudar ficarei muito grato!!

Obrigado pessoal!

**Comment by BESystemInfo** [comment]
Não é uma solução, mas já tive um problema parecido. O truque era após logar, quando ele ficar eternamente carregado, remover o que tiver após index.php no endereço da página. Não sei dizer o que era, pois acabei precisando reconfigurar todo o servidor e quando voltei a instalar, o erro não ocorreu.

**Comment by juninho9494** [comment]
Boa tarde muito obrigado pela dica @BESystemInfo!
Agora é até engraçado falar mas volta para a tela de login kkkkkkk

**Comment by juninho9494** [comment]
Boa tarde, consegui resolver meu problema e vim compartilhar com vocês!
Refiz a instalação do sistema por completo, com o instalador automatico. Ai quando fui logar deu dados inválidos, e segui a dica do amigo @passalia.
No banco de dados mapos no phpmyadmin eu fui em usuário e criei um com esses dados

idUsuarios: 1
nome: Admin
rg: MG-25.502.560
cpf: 600.021.520-87
rua: Rua Acima
numero: 12
bairro: Alvorada
cidade: Teste
estado: MG
email: admin@admin.com
senha: $2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO
telefone: 0000-0000
situacao: 1
dataCadastro: 2018-09-09
permissoes_id: 1 Administrador

Fechei ai pagina de login do mapos e loguei com admin@admin.com e senha 123456.
Agora funcionou normalmente! Muito obrigado pelas dicas e pela disposição de me ajudar! Valeu pessoal!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.

**Comment by Italo2k** [comment]
não aparace a tela de login, boa tarde!

**Comment by danidias78** [comment]
Estou com o mesmo problema. Instalei o sistema mas quando vou para log in aparece a página com erro 404.
Alguém pode ajudar por favor?

**Comment by Pr3d4dor** [comment]
Realizaram o processo de instalação corretamente?
