### ISSUE TITLE
Erro na edição de OS

### ISSUE THREAD

**Issue by mmonzato** [RamonSilva20/mapos#437]
Na gravação do log está sendo referenciado campo errado e inexistente.

`log_info('Alterou uma OS. ID: ' . $this->input->post('idGarantias'));`

o correto seria:

`log_info('Alterou uma OS. ID: ' . $this->input->post('idOs'));`

**Comment by Pr3d4dor** [comment]
Você pode fazer uma PR realizando a correção.

**Comment by cleytonasa** [comment]
Boa!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
