### ISSUE TITLE
O.S nao retorna estoque ao ser cancelada ou excluida

### ISSUE THREAD

**Issue by BrunoBernardes** [RamonSilva20/mapos#438]
Quando cria uma OS, e coloca o produto, ao cancelar ou finalizar a OS o estoque nao volta.

**Comment by Claudiomfa** [comment]
Se quer eliminar uma OS, primeiro tem de eliminar os produtos e os serviços para restaurar os stock e só depois é que pode eliminar ou dar como cancelada a OS.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
