### ISSUE TITLE
Ordem de Serviço -> Exibi valor 0,00 da OS.

### ISSUE THREAD

**Issue by Ronierick** [RamonSilva20/mapos#439]
Pessoal, boa noite, instalei a versão nova no meu servidor(para testes) e ao ir em ordem de serviço, notei que o sistema não exibi o valor total da OS, poderiam me ajudar a como solucionar isso? A coluna "Valor Total" aparece zerada 0,00.
![image](https://user-images.githubusercontent.com/51857445/65288947-2bfd4b00-db1f-11e9-955c-49a4fdd6273f.png)

**Comment by Claudiomfa** [comment]
esse valor aparece quando você factura a OS

**Comment by mmonzato** [comment]
@Ronierick o valor total só é exibido depois que você faturar a OS.

**Comment by Ronierick** [comment]
Existe alguma forma de exibir o valor da OS? Pois gostaria de visualizar sem precisar ter que executar a os.

**Comment by Claudiomfa** [comment]
Esse campo está programado para ir ler na base de dados o valor final, mas como esse valor só é gravado na base de dados após faturar a OS.

Teria de ser alterado para ir buscar a soma dos produtos e dos serviços da OS.

**Comment by BESystemInfo** [comment]
Eu nao manjo praticamente nada de programação, mas para quem manja, não tem alguma forma de fazer um If aí?
Tipo, SE status for faturado, lê o total os, se não, soma total produto + serviços?

**Comment by Ronierick** [comment]
> Eu nao manjo praticamente nada de programação, mas para quem manja, não tem alguma forma de fazer um If aí?
> Tipo, SE status for faturado, lê o total os, se não, soma total produto + serviços?

isso seria otimo, por que num volume de OS, a gente se perde facil sem o valor

**Comment by mmonzato** [comment]
@Ronierick fiz a modificação como na imagem abaixo, veja se é o que você precisa.

![image](https://user-images.githubusercontent.com/55327526/65654952-cf9f9d00-dff0-11e9-86e9-864b51953c48.png)

**Comment by Ronierick** [comment]
> @Ronierick fiz a modificação como na imagem abaixo, veja se é o que você precisa.
> 
> ![image](https://user-images.githubusercontent.com/55327526/65654952-cf9f9d00-dff0-11e9-86e9-864b51953c48.png)

seria isso mesmo valor total = serviço + produto?

obrigado! poderia nos passar a solução?

**Comment by Ronierick** [comment]
@mmonzato

**Comment by mmonzato** [comment]
@Ronierick eu tinha feito apenas somando os produtos, tinha esquecido dos serviços. Somando ambos o valor total fica errado, preciso rever o código.

**Comment by Ronierick** [comment]
@mmonzato se vc puder rever e passar eu agradeço muito!

**Comment by mmonzato** [comment]
@Ronierick me manda e-mail que lhe passo a solução. mmonzato@hotmail.com.
