### ISSUE TITLE
Problemas ao gerar relatório (PDF)

### ISSUE THREAD

**Issue by Vetam** [RamonSilva20/mapos#44]
Olá amigos, acabei de instalar o MapOS, e está funcionando tudo ok, estou fazendo os testes, porém ao tentar gerar relatório, o navegador retorna a mensagem "Falha ao carregar documento PDF" (no Chrome).
Fiz o mesmo teste no IE, e retorna o erro (já iniciando o Acrobat Reader) "O arquivo não começa com '%PDF-'  Local\EWH-1016-0". Alguém teve o mesmo problema, ou saberia como me ajudar nisso? Acredito que o arquivo PDF esteja gerando com nome incorreto ou não esteja gerando, ou algo parecido.

**Comment by KokeroO** [comment]
Amigo, no php 7 em diante está tendo este problema. Tente na versão 5.6 e anterior.

**Comment by Vetam** [comment]
Obrigado, KokeroO, farei isso!

**Comment by Vetam** [comment]
Confirmado, havia instalado a versão 7 do xampp, coloquei a 5.6 e tudo ok.
