### ISSUE TITLE
Bug ao inserir Emitente

### ISSUE THREAD

**Issue by jhonatheberson** [RamonSilva20/mapos#442]
estou com problemas ao inserir o emitente.

me retorna seguinte mensagem: The upload path does not appear to be valid.
ajuda ai galera

**Comment by mmonzato** [comment]
@jhonatheberson onde você está testando o sistema ? parece problema na permissão de pasta de upload. Tenta ir na opção de adicionar arquivos e veja se o mesmo erro é apresentado.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
