### ISSUE TITLE
Bug após a instalação Login carregando infinitamente

### ISSUE THREAD

**Issue by fernandoproglima** [RamonSilva20/mapos#443]
#Informações do Ambiente:

Windows 10 64
Xampp(PHP 7.3, MariaDB)

#Ocorrência:
Após realizar a instalação manual, seguindo as dicas do arquivo 'instrucoes.txt" o sistema fica carregando o loader azul na tela de login, ao validar o Console do navegador(Chromer), percebi que é feita uma chamada POST para a seguinte URL:
http://localhost/ordem-servico/index.php/mapos/verificarLogin?ajax=true 

No console retorna o erro de 500 (Internal Server Error).

![Sem título](https://user-images.githubusercontent.com/55922681/65818921-46d36c00-e251-11e9-8352-3e962d1394fd.png)

Observação: Percebi que vários usuários passaram pela mesma situação onde o erro aparentemente foi sanado, removendo o usuário do banco e criando novamente inserindo a seguinte T-SQL:
 INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
            (1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2019-09-28', 1);

No meu caso, já deletei o banco, recriei e mesmo assim o erro da chamada do método verificarLogin() não retornar nenhuma exception.

Alquém tem alguma sugestão?

**Comment by arielrsilveira** [comment]
> #Informações do Ambiente:
> 
> Windows 10 64
> Xampp(PHP 7.3, MariaDB)
> 
> #Ocorrência:
> Após realizar a instalação manual, seguindo as dicas do arquivo 'instrucoes.txt" o sistema fica carregando o loader azul na tela de login, ao validar o Console do navegador(Chromer), percebi que é feita uma chamada POST para a seguinte URL:
> http://localhost/ordem-servico/index.php/mapos/verificarLogin?ajax=true
> 
> No console retorna o erro de 500 (Internal Server Error).
> 
> ![Sem título](https://user-images.githubusercontent.com/55922681/65818921-46d36c00-e251-11e9-8352-3e962d1394fd.png)
> 
> Observação: Percebi que vários usuários passaram pela mesma situação onde o erro aparentemente foi sanado, removendo o usuário do banco e criando novamente inserindo a seguinte T-SQL:
> INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
> (1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', '[admin@admin.com](mailto:admin@admin.com)', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2019-09-28', 1);
> 
> No meu caso, já deletei o banco, recriei e mesmo assim o erro da chamada do método verificarLogin() não retornar nenhuma exception.
> 
> Alquém tem alguma sugestão?

Fernando,

Você chegou a olhar o error.log do xampp para ver qual o erro exato que está retornando do método? 
O arquivo encontra-se no caminho xampp\apache\logs\error.log, e olha no final dele para ver em detalhes qual o erro que gerou no momento do login.
Qualquer dúvida em relação ao erro, pode enviar aqui.

**Comment by lagethomas** [comment]
Vc apenas baixou e instalou ou fez alguma alteração? Campo na tabela do
banco ou algo do tipo?

Em qua, 2 de out de 2019 13:46, arielrsilveira <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
