### ISSUE TITLE
Request - Emitir recibo ao faturar

### ISSUE THREAD

**Issue by BESystemInfo** [RamonSilva20/mapos#446]
Seria possível incluir um esquema que, ao faturar a OS, fosse emitido um recibo de pagamento? Ou mesmo uma função em separado, onde pudessemos selecionar os dados do Cliente e a OS e imprimir um comprovante de pagamento?

**Comment by gustavooller** [comment]
poderia ser um popup na tela quando fecha a fatura, talvez...

**Comment by maycon1977** [comment]
No aguardo!

**Comment by BESystemInfo** [comment]
Boa noite. Já consegui isso editando o arquivo ImprimirTermica. Obrigado.

**Comment by MarceloGrass** [comment]
> 
> 
> Boa noite. Já consegui isso editando o arquivo ImprimirTermica. Obrigado.

Boa tarde amigo, poderia me passar quais mudanças você fez no arquivo? tenho interesse em transformar em recibo mas tenho duvidas de como fazer isso, muito obrigado!!!

**Comment by BESystemInfo** [comment]
> > Boa noite. Já consegui isso editando o arquivo ImprimirTermica. Obrigado.
> 
> Boa tarde amigo, poderia me passar quais mudanças você fez no arquivo? tenho interesse em transformar em recibo mas tenho duvidas de como fazer isso, muito obrigado!!!

Boa tarde colega. Vou colocar aqui o arquivo do recibo que eu editei. Não é perfeito, mas me atende. Lembrando que como não sou programador, fui fuçando até ficar como eu queria. Mudei tbm o ícone do botão imprimir térmica para um recibinho, e quando clica ali, ele já abre o recibo com a tela de impressão.
![ModeloRecibo](https://user-images.githubusercontent.com/48297443/125333280-6e110580-e320-11eb-83a5-ebb5d344b05b.png)
[imprimirRecibo.zip](https://github.com/RamonSilva20/mapos/files/6803408/imprimirRecibo.zip)
