### ISSUE TITLE
SUGESTÃO - Confirmação de cadastro

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#447]
Boa tarde
Gostaria de sugerir algo que meus clientes tem reportado ao se cadastrarem na area do cliente. Como muitos tem dificuldades com sistemas automatizados me diziam que estava dando erro na hora do cadastro por falta de uma confirmação de que o cadastro estava sendo efetuado com sucesso... muito difícil incluir isso?

Algo como: "CADASTRO EFETUADO COM SUCESSO!"
ou: "FALHA NO CADASTRO!"

Obrigado!

**Comment by Pr3d4dor** [comment]
Fiz a implementação.

Disponível em: #451

**Comment by mmonzato** [comment]
@Pr3d4dor vc poderia dizer exatamente o que vc fez ? Para mim parece que só alterou o texto da msg que já tinha. Obrigado!

**Comment by Pr3d4dor** [comment]
@mmonzato sim, ele só exibe uma mensagem em verde no topo se o cadastro foi executado com sucesso
