### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#448]
Fiz backup do banco de dados do sistema na versão 3.8 e atualize para a última a 3.10. Estou tendo problema em visualizar as OSs já gravadas, fica dando erro 500 de http. Foi gerado um novo arquivo de banco de dados e um novo usuário. Foi feita a instalação automatizada. Pode me ajudar?

**Comment by RamonSilva20** [comment]
Olá. Executou os arquivos sql de atualização do banco de dados que estão dentro da pasta updates?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
