### ISSUE TITLE
Request: criar método de pagamento parcelado.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#452]
Seria uma ótima ideia ter o método de pagamento parcelado/cartão de crédito ou crediário.

Assim quando selecionado um dos acima citados, abra a opção de quantas vezes será feito.
Após isso, a O.S ficaria em faturado/aguardando pagamento e não ficaria como fechada assim como é feito com as O.S que são recebidos os pagamentos.
Sempre que fosse pago uma parcela, abateria uma parcela ou em cima do valor total dependendo de como o cliente fosse pagar.

**Comment by Pr3d4dor** [comment]
Essa seria uma boa funcionalidade porém não é tão simples de implementar.

Quando eu tiver um tempo livre eu posso tentar.

**Comment by BrunoMichael** [comment]
Conseguir fazer no meu sistema da mapos, foi um pouco complexo.

**Comment by bneres** [comment]
> Conseguir fazer no meu sistema da mapos, foi um pouco complexo.

Contribui ai parceiro, seria realmente muito útil
