### ISSUE TITLE
Request - Aprovando ou Finalizando OS

### ISSUE THREAD

**Issue by aldemirjunior** [RamonSilva20/mapos#453]
Seria bom acrescentar um método do cliente aprovar a OS apenas com um aceita através de link na area do cliente ou por e-mail enviado solicitando aceite no orçamento.
Outra sugestão é de ter a possibilidade de salvar junto da OS um arquivo digitalizado em PDF com a ordem assinada pelo cliente e pelo técnico responsável pelo atendimento, quando está for impressa e assinada pelo cliente no ato da retirada do equipamento ou finalização do serviço realizado fora do estabelecimento.

**Comment by Pr3d4dor** [comment]
Essa seria uma boa funcionalidade porém não é tão simples de implementar.

Quando eu tiver um tempo livre eu posso tentar.

**Comment by aldemirjunior** [comment]
up
