### ISSUE TITLE
Boa noite!!

### ISSUE THREAD

**Issue by marceloccarmo** [RamonSilva20/mapos#454]

**Comment by marceloccarmo** [comment]
Boa noite. Teria como implantar um campo de desconto na ordem serviço?

**Comment by Pr3d4dor** [comment]
Olá, é possível fazer essa implementação.

Quando sobrar algum tempo livre eu posso fazê-la.

**Comment by marceloccarmo** [comment]
Boa noite, precisa implantar a campo de desconto na Ordem de serviço!

Em ter, 22 de out de 2019 18:04, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by maycon1977** [comment]
Eu criei um "Serviço" que custa "-R$1,00" e dessa forma quando preciso dar desconto, acrescento ele e multiplico da forma que preciso.

R$100,00 de desconto significa "100 x R$-1,00". Foi o que deu pra arrumar até que consigam implementar um campo específico para desconto!
