### ISSUE TITLE
Erro ao cadastrar produto

### ISSUE THREAD

**Issue by JefersonFilipe** [RamonSilva20/mapos#455]
Boa tarde!
Estou com MAP Os rodando hospedado, e o unico erro é na hora de cadastrar o produto.
Eu preencho os dados necessário e ao clicar em "Adicionar" a tela recarrega e traz os campos todos vazios. Não cadastra o produto e nem aparece nenhuma mensagem de erro.

Alguem sabe como prosseguir?

**Comment by Pr3d4dor** [comment]
Olá, somente com essas informações fica um pouco difícil de te ajudar.

O que você pode fazer é tentar cadastrar o produto e deixar o console do navegador aberto (normalmente tecla F12) e na aba Rede e/ou na aba Console verificar a mensagem de erro.

**Comment by JefersonFilipe** [comment]
> Olá, somente com essas informações fica um pouco difícil de te ajudar.
> 
> O que você pode fazer é tentar cadastrar o produto e deixar o console do navegador aberto (normalmente tecla F12) e na aba Rede e/ou na aba Console verificar a mensagem de erro.

Verdade. Descupla pela ignorancia.
Segue os 2 erros encontrados no console


 Uncaught TypeError: $(...).live is not a function
    at HTMLDocument.<anonymous> (matrix.js:161)
    at c (jquery-1.10.2.min.js:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js:4)
    at Function.ready (jquery-1.10.2.min.js:4)
    at HTMLDocument.q (jquery-1.10.2.min.js:4)


maskmoney.js:88 Uncaught TypeError: Cannot read property 'msie' of undefined
    at HTMLInputElement.blurEvent (maskmoney.js:88)
    at HTMLInputElement.dispatch (jquery-1.10.2.min.js:5)
    at HTMLInputElement.v.handle (jquery-1.10.2.min.js:5)

**Comment by Pr3d4dor** [comment]
Olha parece que o jQuery não está sendo carregado corretamente.

Tente reinstalar o mapos para ver se o problema persiste.

**Comment by JefersonFilipe** [comment]
Já reinstalei e persiste

**Comment by Pr3d4dor** [comment]
Tentou utilizar outro navegador?

Se puder passar o link hospedado e as credenciais para eu tentar lhe ajudar.

**Comment by JefersonFilipe** [comment]
Claro.

Newstatus.com.br/os

Login: Pr3d4dor@teste.com
Pass: 123456

**Comment by Pr3d4dor** [comment]
Parece que você está utilizando uma versão antiga do mapos, já tentou atualizar para uma versão mais recente?

Você removou o campo Entrada e Saída do formulário, então talvez esse seja o problema.

**Comment by JefersonFilipe** [comment]
Na verdade não tentei atualizar.
Mas não me recordo de ter removido esses Campos

**Comment by JefersonFilipe** [comment]
Daria pra recompor esses Campos ausentes pra ver se funciona?

**Comment by Pr3d4dor** [comment]
Eu recomendo você baixar a versão atualizada do mapos novamente deste repositório e instalar novamente.

**Comment by JefersonFilipe** [comment]
agora, depois de instalar a versão mais recente, do zero e seguir a instruções, não consigo logar

**Comment by Pr3d4dor** [comment]
Qual o conteúdo da linha exatamente pois olhando as linhas 527 e 528 temos apenas comentários:
- https://github.com/RamonSilva20/mapos/blob/master/banco.sql#L527
- https://github.com/RamonSilva20/mapos/blob/master/banco.sql#L528

**Comment by JefersonFilipe** [comment]
Na verdade, inseri o que pedia o arquivo de instruções.

Segue:

- Remova as linhas 527 e 528 do arquivo banco.sql e adicione o comando abaixo

        INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
            (1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);

**Comment by RamonSilva20** [comment]
> Na verdade, inseri o que pedia o arquivo de instruções.
> 
> Segue:
> 
> * Remova as linhas 527 e 528 do arquivo banco.sql e adicione o comando abaixo
>   ```
>     INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
>         (1, 'Admin', 'MG-25.502.560', '600.021.520-87', 'Rua Acima', '12', 'Alvorada', 'Teste', 'MG', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);
>   ```

Houve alteração neste arquivo e o tutorial ficou desatualizado, na verdade você deveria substituir as linhas 540 e 541. Essas instruções são somente no caso de você não utilizar o instalador.

**Comment by JefersonFilipe** [comment]
Pois é.
O instalador não carregou.
Vou refazer conforme a linha que vc indicou

**Comment by JefersonFilipe** [comment]
> 
> Houve alteração neste arquivo e o tutorial ficou desatualizado, na verdade você deveria substituir as linhas 540 e 541. Essas instruções são somente no caso de você não utilizar o instalador.

Resolvido conforme vc falou.
Muito obrigado!
