### ISSUE TITLE
Função Veiculos

### ISSUE THREAD

**Issue by PaulloRocha** [RamonSilva20/mapos#456]
olá, primeiramente parabéns pelo projeto, está cada dia melhor.

Estou usando o sistema algum tempo e resolvi adicionar uma nova janela para o gerenciamento de veículos, 
consegui implementar o CRUD, (adicionar,  visualizar,editar, remover ) dos veículos, porem gostaria que um determinado veiculo fosse associado a um determinado cliente.

alguém poderia me ajudar a implementar essa função ?

na foto abaixo criei um campo cliente, onde deverá aparece o nome do cliente. 
[https://ibb.co/RSn7Gny](url)

Paulo Rocha
Email: p_orf@hotmail.com
(63) 99203-5247

**Comment by Pr3d4dor** [comment]
Olá, na função que devolve o formulário de criação/edição você deve fazer uma consulta na tabela cliente e disponibiliza esses dados para que eles possam ser usados na view.

Após isso você pode fazer um select para que seja possível selecionar o cliente associado ao veículo.

Caso você não tenha feito ainda, será necessário colocar essa chave estrangeira de cliente na tabela de veículos.

**Comment by PaulloRocha** [comment]
Pr3d4dor  muito obrigado pela atenção, então tentei seguir essa linha de raciocínio porem estou encontrando algumas dificuldades. 
estou me baseando nos demais arquivos ("vendas,produtos") para desenvolver essa função. pois tenho pouco conhecimento em programação. 

 tentei da seguinte forma:
em Models-->Veiculos_model:
 
`$this->db->select($fields.', clientes.nomeCliente, clientes.idClientes');
        $this->db->from($table);
        $this->db->limit($perpage, $start);
        $this->db->join('clientes', 'clientes.idClientes = '.$table.'.clientes_id');
        $this->db->order_by('idVeiculos', 'desc');`
tentei dessa forma, porem quando tento acessar veiculos da HTTP ERROR 500. 

estou me baseando no arquivo de vendas, que já tem essa função de buscar o usuário porem não ta dando certo.

**Comment by PaulloRocha** [comment]
Abaixo segue o código de tudo que modifiquei. 
Controllers-->Veiculos.php
`<?php

class Veiculos extends CI_Controller
{

    /**
     * author: Ramon Silva
     * email: silva018-mg@yahoo.com.br
     *
     */

    function __construct()
    {
        parent::__construct();
        if ((!session_id()) || (!$this->session->userdata('logado'))) {
            redirect('mapos/login');
        }

        $this->load->helper(array('form', 'codegen_helper'));
        $this->load->model('veiculos_model', '', true);
        $this->data['menuVeiculos'] = 'Veiculos';
    }

    function index()
    {
        $this->gerenciar();
        
    }

    function gerenciar()
    {

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vVeiculo')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para visualizar Veiculos.');
            redirect(base_url());
        }

        $this->load->library('table');
        $this->load->library('pagination');


        $config['base_url'] = base_url() . 'index.php/veiculos/gerenciar/';
        $config['total_rows'] = $this->veiculos_model->count('veiculos');
        $config['per_page'] = 10;
        $config['next_link'] = 'Próxima';
        $config['prev_link'] = 'Anterior';
        $config['full_tag_open'] = '<div class="pagination alternate"><ul>';
        $config['full_tag_close'] = '</ul></div>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li><a style="color: #2D335B"><b>';
        $config['cur_tag_close'] = '</b></a></li>';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';
        $config['first_link'] = 'Primeira';
        $config['last_link'] = 'Última';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';

        $this->pagination->initialize($config);

        $this->data['results'] = $this->veiculos_model->get('veiculos', 'idveiculos,clientes_id,placa,imei,numero,name,tipo,modelo,marca,cor,ano,apelido', '', $config['per_page'], $this->uri->segment(3));

        $this->data['view'] = 'veiculos/veiculos';
        $this->load->view('tema/topo', $this->data);
    }

    function adicionar()
    {

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'aVeiculo')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para adicionar veiculos.');
            redirect(base_url());
        }

        $this->load->library('form_validation');
        $this->data['custom_error'] = '';

        if ($this->form_validation->run('veiculos') == false) {
            $this->data['custom_error'] = (validation_errors() ? '<div class="form_error">' . validation_errors() . '</div>' : false);
        } else {
            $data = array(                
                    'clientes_id' => $this->input->post('clientes_id'), 
                    'placa' => set_value('placa'),
                    'imei' => set_value('imei'),
                    'numero' => set_value('numero'),
                    'tipo' => set_value('tipo'),
                    'modelo' => set_value('modelo'),
                    'marca' => set_value('marca'),
                    'cor' => set_value('cor'),
                    'ano' => set_value('ano'),
                    'name' => set_value('name'),
                    'apelido' => set_value('apelido')
                    
            );
                    
            if ($this->veiculos_model->add('veiculos', $data) == true) {
                $this->session->set_flashdata('success', 'Veiculo adicionado com sucesso!');
                redirect(base_url() . 'index.php/veiculos/adicionar/');
            } else {
                $this->data['custom_error'] = '<div class="form_error"><p>An Error Occured.</p></div>';
            }
        }
        $this->data['view'] = 'veiculos/adicionarVeiculo';
        $this->load->view('tema/topo', $this->data);
    }

    function editar()
    {

        if (!$this->uri->segment(3) || !is_numeric($this->uri->segment(3))) {
            $this->session->set_flashdata('error', 'Item não pode ser encontrado, parâmetro não foi passado corretamente.');
            redirect('mapos');
        }

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'eVeiculo')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para editar veiculos.');
            redirect(base_url());
        }
        $this->load->library('form_validation');
        $this->data['custom_error'] = '';

        if ($this->form_validation->run('veiculos') == false) {
            $this->data['custom_error'] = (validation_errors() ? '<div class="form_error">' . validation_errors() . '</div>' : false);
        } else {
            $data = array(
                'clientes_id' => $this->input->post('clientes_id'),
                'placa' => $this->input->post('placa'),
                'imei' => $this->input->post('imei'),
                'numero' => $this->input->post('numero'),
                'tipo' => $this->input->post('tipo'),
                'modelo' => $this->input->post('modelo'),
                'marca' => $this->input->post('marca'),
                'cor' => $this->input->post('cor'),
                'ano' => $this->input->post('ano'),
                'name' => $this->input->post('name'),
                'apelido' => $this->input->post('apelido')
            );

            if ($this->veiculos_model->edit('veiculos', $data, 'idVeiculos', $this->input->post('idVeiculos')) == true) {
                $this->session->set_flashdata('success', 'Veiculo editado com sucesso!');
                redirect(base_url() . 'index.php/veiculos/editar/' . $this->input->post('idVeiculos'));
            } else {
                $this->data['custom_error'] = '<div class="form_error"><p>Ocorreu um erro</p></div>';
            }
        }

        $this->data['result'] = $this->veiculos_model->getById($this->uri->segment(3));
        $this->data['view'] = 'veiculos/editarVeiculo';
        $this->load->view('tema/topo', $this->data);
        $dados['clientes'] = $this->db->get('clientes')->result();
        $this->db->join('clientes','idClientes=clientes_id','inner' );
    }

      function visualizar()
    {

        if (!$this->uri->segment(3) || !is_numeric($this->uri->segment(3))) {
            $this->session->set_flashdata('error', 'Item não pode ser encontrado, parâmetro não foi passado corretamente.');
            redirect('mapos');
        }

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'vVeiculo')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para visualizar Veiculos.');
            redirect(base_url());
        }

        $this->data['result'] = $this->veiculos_model->getById($this->uri->segment(3));

        if ($this->data['result'] == null) {
            $this->session->set_flashdata('error', 'Veiculo não encontrado.');
            redirect(base_url() . 'index.php/veiculos/editar/' . $this->input->post('idveiculos'));
        }

        $this->data['view'] = 'veiculos/visualizarVeiculo';
        $this->load->view('tema/topo', $this->data);
    }

    public function autoCompleteCliente()
    {

        if (isset($_GET['term'])) {
            $q = strtolower($_GET['term']);
            $this->vendas_model->autoCompleteCliente($q);
        }
    }

    
    
    function excluir()
    {

        if (!$this->permission->checkPermission($this->session->userdata('permissao'), 'dVeiculo')) {
            $this->session->set_flashdata('error', 'Você não tem permissão para excluir veiculos.');
            redirect(base_url());
        }


        $id =  $this->input->post('id');
        if ($id == null) {

            $this->session->set_flashdata('error', 'Erro ao tentar excluir Veiculo.');
            redirect(base_url() . 'index.php/veiculos/gerenciar/');
        }

        $this->db->where('veiculos_id', $id);
        $this->db->delete('veiculos_os');


        $this->db->where('veiculos_id', $id);
        $this->db->delete('itens_de_vendas');

        $this->veiculos_model->delete('veiculos', 'idveiculos', $id);


        $this->session->set_flashdata('success', 'Veiculo excluido com sucesso!');
        redirect(base_url() . 'index.php/veiculos/gerenciar/');
    }
} `
    
===============================
models-->Veiculos_model.php
`<?php if (! defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Veiculos_model extends CI_Model
{

    /**
     * author: Ramon Silva
     * email: silva018-mg@yahoo.com.br
     *
     */
    
    function __construct()
    {
        parent::__construct();
    }

    
    function get($table, $fields, $where = '', $perpage = 0, $start = 0, $one = false, $array = 'array')
    {
        
        $this->db->select($fields);
        $this->db->from($table);
        $this->db->order_by('idVeiculos', 'desc');
        $this->db->limit($perpage, $start);
        if ($where) {
            $this->db->where($where);
        }
        
        $query = $this->db->get();
        
        $result =  !$one  ? $query->result() : $query->row();
        return $result;
    }

    function getById($id)
    {
        $this->db->where('idVeiculos', $id);
        $this->db->limit(1);
        return $this->db->get('veiculos')->row();
    }
    
    function add($table, $data)
    {
        $this->db->insert($table, $data);
        if ($this->db->affected_rows() == '1') {
            return true;
        }
        
        return false;
    }
    
    function edit($table, $data, $fieldID, $ID)
    {
        $this->db->where($fieldID, $ID);
        $this->db->update($table, $data);

        if ($this->db->affected_rows() >= 0) {
            return true;
        }
        
        return false;
    }
    
    function delete($table, $fieldID, $ID)
    {
        $this->db->where($fieldID, $ID);
        $this->db->delete($table);
        if ($this->db->affected_rows() == '1') {
            return true;
        }
        
        return false;
    }
       
public function autoCompleteCliente($q)
{

    $this->db->select('*');
    $this->db->limit(5);
    $this->db->like('nomeCliente', $q);
    $query = $this->db->get('clientes');
    if ($query->num_rows() > 0) {
        foreach ($query->result_array() as $row) {
            $row_set[] = array('label'=>$row['nomeCliente'].' | Telefone: '.$row['telefone'],'id'=>$row['idClientes']);
        }
        echo json_encode($row_set);
    }
}
function count($table)
{
    return $this->db->count_all($table);
}
}`

====================================

`<?php if ($this->permission->checkPermission($this->session->userdata('permissao'), 'aVeiculo')) { ?>
    <a href="<?php echo base_url(); ?>index.php/veiculos/adicionar" class="btn btn-success"><i class="icon-plus icon-white"></i> Adicionar Veículo</a>
<?php 
} ?>
<?php
if (!$results) { ?>
	<div class="widget-box">
     <div class="widget-title">
        <span class="icon">
            <i class="icon-truck"></i>
         </span>
        <h5>Veiculos</h5>
     </div>
<div class="widget-content nopadding">
<table class="table table-bordered ">
    <thead>
        <tr>
            <th>Cod.</th>
            <th>Cliente</th>
            <th>Placa</th>
            <th>Imei</th>
            <th>Número</th>
            <th>Tipo</th>
            <th>Modelo</th>
            <th>Marca</th>
            <th>Cor</th>
            <th>Ano</th>
            <th>Rastreador</th>
            <th>descrição</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="5">Nenhum Veículo Cadastrado</td>
        </tr>
    </tbody>
</table>
</div>
</div>
<?php 
} else { ?>
<div class="widget-box">
     <div class="widget-title">
        <span class="icon">
            <i class="icon-truck"></i>
         </span>
        <h5>Veiculos</h5>
     </div>
<div class="widget-content nopadding">
<table class="table table-bordered ">
    <thead>
        <tr style="backgroud-color: #2D335B">
            <th>Cod.</th>
            <th>Cliente</th>
            <th>Placa</th>
            <th>Imei</th>
            <th>Número</th>
            <th>Tipo</th>
            <th>Modelo</th>
            <th>Marca</th>
            <th>Cor</th>
            <th>Ano</th>
            <th>Rastreador</th>
            <th>descrição</th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($results as $r) {
            echo '<tr>';
            echo '<td>' . $r->idveiculos . '</td>';
            echo '<td>' . $r->clientes_id . '</td>';
            echo '<td>' . $r->placa . '</td>';
            echo '<td>' . $r->imei . '</td>';
            echo '<td>' . $r->numero . '</td>';  
            echo '<td>' . $r->tipo . '</td>';  
            echo '<td>' . $r->modelo . '</td>';  
            echo '<td>' . $r->marca . '</td>';  
            echo '<td>' . $r->cor . '</td>';  
            echo '<td>' . $r->ano . '</td>';
            echo '<td>' . $r->name . '</td>';  
            echo '<td>' . $r->apelido . '</td>';
                       
            echo '<td>';
            if ($this->permission->checkPermission($this->session->userdata('permissao'), 'vVeiculo')) {
                echo '<a style="margin-right: 1%" href="' . base_url() . 'index.php/veiculos/visualizar/' . $r->idveiculos . '" class="btn tip-top" title="Visualizar Veículo"><i class="icon-eye-open"></i></a>  ';
            }
            if ($this->permission->checkPermission($this->session->userdata('permissao'), 'eVeiculo')) {
                echo '<a style="margin-right: 1%" href="' . base_url() . 'index.php/veiculos/editar/' . $r->idveiculos . '" class="btn btn-info tip-top" title="Editar Veículo"><i class="icon-pencil icon-white"></i></a>';
            }
            if ($this->permission->checkPermission($this->session->userdata('permissao'), 'dVeiculo')) {
                echo '<a href="#modal-excluir" role="button" data-toggle="modal" veiculo="' . $r->idveiculos . '" class="btn btn-danger tip-top" title="Excluir Veículo"><i class="icon-remove icon-white"></i></a>';
            }                    
            echo '</td>';
            echo '</tr>';
} ?>
        <tr>         
        </tr>
    </tbody>
</table>
</div>
</div>
<?php echo $this->pagination->create_links();
} ?>



<div id="modal-excluir" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <form action="<?php echo base_url() ?>index.php/veiculos/excluir" method="post">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h5 id="myModalLabel">Excluir Veiculos</h5>
  </div>
  <div class="modal-body">
    <input type="hidden" id="idVeiculo" name="id" value="" />
    <h5 style="text-align: center">Deseja realmente excluir este Veiculo?</h5>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    <button class="btn btn-danger">Excluir</button>
  </div>
  </form>
</div>


<script type="text/javascript">
$(document).ready(function() {
   $(document).on('click', 'a', function(event) {   
        var veiculo = $(this).attr('Veiculo');
        $('#idVeiculo').val(veiculo);
    });
});
</script>

`

**Comment by Pr3d4dor** [comment]
Fica um pouco ruim de olhar os códigos por aqui, se você puder compactar toda a pasta e me mandar o zip para eu conseguir olhar o código de uma melhor forma para poder te ajudar.

**Comment by PaulloRocha** [comment]
claro, envio sim. pode me passar seu email ou whats por favor.

**Comment by Pr3d4dor** [comment]
Meu email é: gian_bine@hotmail.com
