### ISSUE TITLE
Controle de Mensalidade

### ISSUE THREAD

**Issue by PaulloRocha** [RamonSilva20/mapos#457]
olá, a muito tempo atrás baixei uma versão do mapos modificada que contia uma função de controle de mensalidade conforme imagem do link... 
estou tentando implementar essa função na versão mais atualizada do MapOs, porem não estou conseguindo fazer as requisições com o banco... devido algumas funções já terem sido depreciadas. 

alguém poderia me orientar como atualizar essa função ?
a ideia e deixar ela disponível para quem tiver interesse depois. 
[https://ibb.co/rpRg9kJ](url)

**Comment by brunaomessias** [comment]
Olá @PaulloRocha , você conseguiu colocar pra funcionar o controle de mensalidade? 
Eu coloquei um questão semelhante a sua e queria saber se é possível.!?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.

**Comment by brunaomessias** [comment]
Obrigado pelo retorno. Eu tenho um empresta de TI, presto consultoria, manutenção em computadores e tenho alguns clientes mensais e sempre o cliente quer incluir alguns equipamentos no contrato para controle de atendimentos. 
Como pediu pra detalhar um pouco mais vou mandar aqui...
Então, uma coisa que pensei sobre a mensalidade seria você ter a opção de adicionar o cliente e ir na opção de contratos, criar um novo, especificar o cliente, data do inicio, data faturamento, prazo contrato "1 mes, 3 meses, 6 meses e 1 ano". Ai, ter a opção de incluir os equipamentos do cliente que entraram em contrato.
E na parte financeira seria opção de data de vencimento da fatura... 
Aproveitando outra coisa, seria a opção de compra de produtos de fornecedores, podendo colocar numero da nota, data da compra para controle de garantia.
Sei que pode ser muito, mas se tiver alguém que possa fazer personalizado com as necessidades poderia entrar em contato comigo?
Obrigado e mais um vez parabéns pelo sistema, ficou top demais, dinâmico, leve e simples!
