### ISSUE TITLE
Relatório

### ISSUE THREAD

**Issue by mytusx** [RamonSilva20/mapos#458]
Boa tarde, como faço pra colocar um campo de "responsavel" pra pesquisar junto com nome e status na url "/index.php/os"?

Na verdade o campo já coloquei o campo só preciso programar ele..

Vi esta opção no arquivo Os_model.php

if (array_key_exists('pesquisa', $where)) {
    $this->db->select('idClientes');
    $this->db->like('nomeCliente', $where['pesquisa']);
    $this->db->limit(5);
     $clientes = $this->db->get('clientes')->result();

     foreach ($clientes as $c) {
     array_push($lista_clientes, $c->idClientes);
                }

            }

teria que mexer nessa parte? exemplo: onde está "nomeCliente" tenho que colocar como "nome"? 

Sou meio leigo estou aprendendo agora

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
