### ISSUE TITLE
ORDENAR RELATÓRIO POR DATA?

### ISSUE THREAD

**Issue by flaviolear** [RamonSilva20/mapos#459]
Bom dia a todos e parabenizar pelo trabalho com o MAP OS, fantástico!
gostaria de uma informação de como exibir os relatórios com as datas ordenadas em sequência dos dias de vencimento ou pagamento?

**Comment by maycon1977** [comment]
Isso seria interessante mesmo, porque os relatorios ficam meio desordenados...
