### ISSUE TITLE
ANSIOSO PELO MAP OS 4 <3

### ISSUE THREAD

**Issue by GustDM** [RamonSilva20/mapos#46]
Tem previsão mano? vi um screenshot que postou e achei mt show!

**Comment by RamonSilva20** [comment]
Olá @GustDM, sem previsão. Em breve colocarei o projeto aqui para quem tenha interesse possa auxiliar no desenvolvimento.

**Comment by dmffraxe** [comment]
Poxa seria ótimo disponibilizar a nova versão em desenvolvimento. Ainda pretende disponibilizar?
