### ISSUE TITLE
O SISTEMA FAZ ENTRADA DE PRODUTOS ONDE?

### ISSUE THREAD

**Issue by sanzone** [RamonSilva20/mapos#460]
OLA ESTOU COM DIFICULDADES PARA INSERIR ENTRADA DE PRODUTOS NO ESTOQUE POR EXEMPLO TENHO 10 PILHAS COMPREI MAIS 4 AGORA TENHO QUE TER 14, EU NAO ENCONTREI ONDE ATUALIZAR PARA 14 INSERINDO A COMPRA DAS PILHAS

**Comment by RamonSilva20** [comment]
Olá. Realmente é uma funcionalidade necessária, mas infelizmente não está implementado.

**Comment by sanzone** [comment]
Seria possivel?

**Comment by sanzone** [comment]
o Sistema é otimo sá falta isso

**Comment by trollfalgar** [comment]
Fiz um PR com essa funcionalidade.
Aguardando o @RamonSilva20 verificar.

**Comment by LipzyLipzy** [comment]
Ola eu implementei esta atualizacao de stock que partilhou. Mas proponho uma melhoria. Quando se clica em atualizacao de stock, aparece o stock disponivel e temos de somar o valor manualmente. O melhor seria aparecer a zero e o valor aplicado somar ao stock existente automaticamente. Obrigado pelo trabalho disponibilizado.

**Comment by trollfalgar** [comment]
> 
> 
> Ola eu implementei esta atualizacao de stock que partilhou. Mas proponho uma melhoria. Quando se clica em atualizacao de stock, aparece o stock disponivel e temos de somar o valor manualmente. O melhor seria aparecer a zero e o valor aplicado somar ao stock existente automaticamente. Obrigado pelo trabalho disponibilizado.

Adicionei um novo commit, mostrando o estoque atual e a opção de adicionar novos produtos. A soma é feita no controller antes de atualizar o estoque.

**Comment by LipzyLipzy** [comment]
Ja testei e ficou top. Obrigado

**Comment by LipzyLipzy** [comment]
Sera possivel dar uma ajuda. Queria meter o icon logo na primeira pagina quando se tem produtos abaixo de stock mas nao estou a conseguir. Pode ajudar? Obrigado

**Comment by trollfalgar** [comment]
> 
> 
> Sera possivel dar uma ajuda. Queria meter o icon logo na primeira pagina quando se tem produtos abaixo de stock mas nao estou a conseguir. Pode ajudar? Obrigado

Abre um novo tópico sobre o assunto, eu vou preparar o código.
