### ISSUE TITLE
Sistema não envia email.

### ISSUE THREAD

**Issue by jeisond23** [RamonSilva20/mapos#461]
Bom dia.
Realizei as configurações específicadas para o envio de email, mas o sistema não esta enviando nenhum. Já realizei vários testes, inclusive com as respostas que achei por aqui, mas até agora nada.
Sugestão: o codeiginiter possui uma "library" para envio de emails, vocês poderiam utiliza-lá no sistema. Até onde vi, não há dificuldades em utilizar a mesma.

**Comment by RamonSilva20** [comment]
Bom dia. Verifique se não existe algum tipo de bloqueio. 
Sobre o uso da library de e-mail, ela é utilizada, mas é uma versão extendida e customizada para funcionar com filas em background.

**Comment by jeisond23** [comment]
Realizei um teste com a biblioteca padrão em meu site, a mesma funcionou sem problemas, a configurção não foi muito difícil.

Obs.: o teste foi feito no mesmo servidor do sistema e com email próprio.

Não acho interessante trabalhar com filas de envio, pois geralmente o usuário deseja enviar o email de imediato.

Vocês possuem alguma dica de onde fazer as alterações para utilizar a biblioteca padrão? Pois não consegui localizar.

**Comment by felipepips** [comment]
Bom dia. Eu também nao estou conseguindo utilizar a funçao de disparar email.. No meu caso, ainda estou utilizando em ambiente local, tentei cadastrar com os dados do hotmail, conforme este link (tentei smtp e pop), mas nao rolou... https://support.office.com/pt-br/article/configura%C3%A7%C3%B5es-de-email-pop-e-imap-para-o-outlook-8361e398-8af4-4e97-b147-6c6c4ac95353

**Comment by Pr3d4dor** [comment]
No geral o ideal é trabalhar com filas de email pois se o mesmo for enviado quando o usuário clicar no botão o usuário irá ter que esperar o email ser enviado para depois a página ser atualizada.

Por isso é utilizado filas de email, onde ao ser executada uma ação que dispara o email, o mesmo é colocado na fila ao invés de ser disparado no momento que foi criado.

**Comment by NATA-RMG** [comment]
Bom dia,  ainda não envia e-mail de jeito nenhum !!!

**Comment by eduaraujothe** [comment]
> Bom dia.
> Realizei as configurações específicadas para o envio de email, mas o sistema não esta enviando nenhum. Já realizei vários testes, inclusive com as respostas que achei por aqui, mas até agora nada.
> Sugestão: o codeiginiter possui uma "library" para envio de emails, vocês poderiam utiliza-lá no sistema. Até onde vi, não há dificuldades em utilizar a mesma.



> Realizei um teste com a biblioteca padrão em meu site, a mesma funcionou sem problemas, a configurção não foi muito difícil.
> 
> Obs.: o teste foi feito no mesmo servidor do sistema e com email próprio.
> 
> Não acho interessante trabalhar com filas de envio, pois geralmente o usuário deseja enviar o email de imediato.
> 
> Vocês possuem alguma dica de onde fazer as alterações para utilizar a biblioteca padrão? Pois não consegui localizar.

OBS: Tenho o sistema rodando na hospedagem da dialhost porém não consigo configurar o envio de e-mail, pode me ajudar?

Um abraço. 

Eduardo Araújo

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
