### ISSUE TITLE
Parcelamento de Compras e Vendas 

### ISSUE THREAD

**Issue by AntonioCarlos1979** [RamonSilva20/mapos#463]
Olá a todos, parabéns pelo projeto! 
Gostaria de solicitar, caso possível, a implementação da função de parcelamento, tanto no faturamento de ordens de serviços, vendas diretas como nas compras, no caso, ao acrescentar despesas. 
Compro e vendo produtos relativamente caros (Smartfones) e geralmente preciso fazer vários lançamentos deixando aberto o faturamento, que ao ficar pendente nem sempre lista no campo busca (uso versão 3.8).
Esta implementação iria ajudar muita gente, acredito.
Agradeço a atenção.

**Comment by AntonioCarlos1979** [comment]
Pensei que esta funcionalidade seria útil a todos, mas ninguém respondeu ainda!  Peço desculpas por importunar os desenvolvedores deste projeto e não poder contribuir de nenhuma forma.

**Comment by RamonSilva20** [comment]
Olá, sim amigo, claro que é útil, mas é preciso reconhecer que as pessoas tem outras atividades, é um projeto colaborativo e nem sempre é possível contribuir. Sugestões são sempre bem vindas. Abraço.

**Comment by AntonioCarlos1979** [comment]
Boa tarde amigos, sei que é corrido para todos, mas existe uma previsão de implementação desta função? será que podemos esperar ela para este ano?
desculpe a ansiedade, obrigado...
