### ISSUE TITLE
TUTORIAL PARA INSTALAÇÃO MAPOS

### ISSUE THREAD

**Issue by viniciuslaguardia** [RamonSilva20/mapos#465]
OLÁ PESSOAL! SOU MEIO LEIGO NO ASSUNTO MAS GOSTARIA DE INSTALAR O MAPOS NO MEU SITE, JÁ O UTILIZAVA E SEMPRE GOSTEI DA INTERFACE E FUNCIONALIDADE DO SISTEMA. UPEI O PROGRAMA E FAÇO A INSTALAÇÃO AUTOMÁTICA DO MESMO, PORÉM, CREIO ESTAR FAZENDO ALGUM PROCEDIMENTO INCORRETO POIS LOGO APÓS A INSTALAÇÃO, AO RETORNAR A PAGINA INICIAL, O MESMO NÃO CARREGA A PÁGINA DE LOGIN. SE ALGUÉM PUDESSE FORNECER ALGUM PASSO A PASSO, OU ME AUXILIAR DE ALGUMA MANEIRA, FICARIA GRATO.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
