### ISSUE TITLE
Exibir valor da OS na tela "OS" mesmo antes de faturar

### ISSUE THREAD

**Issue by felipepips** [RamonSilva20/mapos#466]
Gostaria de visualizar o valor, mesmo sem ter faturado ainda... Pensei em criar uma outra coluna no DB e alterar o dado que é exibido na tela, mas não sei como fazer para o sistema calcular este campo durante a inclusão da OS (a coluna valortotal é calculada na função que é chamada pelo botão faturar)

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
