### ISSUE TITLE
Somatório de OS

### ISSUE THREAD

**Issue by AntonioCarlos1979** [RamonSilva20/mapos#468]
Ao criar ordem de serviço com serviços e produtos, o somatório ocorre apenas em cada modalidade e não na totalidade (serviços+produtos).
Estou agora usando V.3.12

**Comment by willph** [comment]
O somatório final Chamado de TOTAL só aparece em O.S. Quando o campo esta selecionado como Finalizado ou Orçamento.

Sua O.S. Esta como? ABERTO?

**Comment by AntonioCarlos1979** [comment]
Boa noite, sim, está como aberto.  O que acontece é que muitas vezes executo serviços a empresas e vai acumulando ao mês. Normalmente alguém me liga para saber os valores para pagamento. Tendo em vista esta situação, não posso considerar FINALIZADA pois de fato não está.  
Tem como eu fazer alguma alteração para resolver paliativamente a minha demanda?

**Comment by willph** [comment]
Mude para ORÇAMENTO.
Vai aparecer tranquilo
