### ISSUE TITLE
PROBLEMA NÂO CONSIGO IMPRIMIR UMA VENDA 

### ISSUE THREAD

**Issue by cleytonasa** [RamonSilva20/mapos#47]
A PAGE FICA BRANCA E NAO APARECE NADA, AI SE INSISTIR EM IMPRMIR AI APARECE !
SINISTRO

**Comment by willsantos07** [comment]
qual navegador utilizado?
caso for o Google Chrome aqui aconteceu a mesma coisa hoje pela manha depois de atualizar para a Versão 60.0.3112.90
unica solução que encontrei no momento foi usar o Firefox

**Comment by cleytonasa** [comment]
isso, foi o Google Chrome, tente de tudo no script javascript, acho que obtive sucesso removendo essas linhas.
`            mywindow.document.write("<link rel='stylesheet' href='<?php echo base_url();?>assets/css/bootstrap.min.css' />");
            mywindow.document.write("<link rel='stylesheet' href='<?php echo base_url();?>assets/css/bootstrap-responsive.min.css' />");
            mywindow.document.write("<link rel='stylesheet' href='<?php echo base_url();?>assets/css/matrix-style.css' />");
            mywindow.document.write("<link rel='stylesheet' href='<?php echo base_url();?>assets/css/matrix-media.css' />");`

**Comment by cleytonasa** [comment]
São as linhas que carrega o css, parece não ter sentido mas funcionou! porem fica sem estilo na page.

**Comment by cleytonasa** [comment]
bom pessoal, removendo essa linha resolveu meu problema no chrome,
mywindow.document.close(); // necessary for IE >= 10

**Comment by willsantos07** [comment]
qual arquivo devemos remover

**Comment by cleytonasa** [comment]
visualizarVenda.php e em visualisarOS.php se não me engano!

**Comment by hdarantes** [comment]
Após a linha:
 	mywindow.document.close(); // necessary for IE >= 10 
Adicionei o seguinte:
mywindow.document.print();

Voltou a funcionar como antes.

**Comment by RamonSilva20** [comment]
Boa noite. A forma de impressão foi alterada na versão 3.1.7, espero ter solucionado o problema definitivamente.
