### ISSUE TITLE
Alterar Descrição de Fatura

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#471]
Como alterar os valores padrões em:
Alterar OS > Faturar > (Caixa de diálogo (Faturar **Venda**)) e Descrição (Fatura de **Venda** - #000)
Para OS > Faturar > (Caixa de diálogo (Faturar **Serviço**)) e Descrição (Fatura de **Serviço** - #000)

**Comment by diegoandrade93** [comment]
a descricao pode ser alterada no proprio campo.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
