### ISSUE TITLE
Relatório de OS não consta "Faturadas" no filtro.

### ISSUE THREAD

**Issue by mikxingu** [RamonSilva20/mapos#472]
Bom dia!! Na parte de relatórios de ordens de serviço, não há a opção de selecionar apenas as OS com status "Faturado". Só consigo visualizá-las no relátorio de todas as OS. Como posso consertar isso?

**Comment by cleytonasa** [comment]
Pode crer !! percebi isso onten!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
