### ISSUE TITLE
email mapos

### ISSUE THREAD

**Issue by jrtechsolution** [RamonSilva20/mapos#473]
Dentro da pasta raiz do MAPOS execute o seguinte atraves do CMD comando: php index.php email/process e no mesmo instante ele fará os envios pendentes dos email que você tentou enviar.

**Comment by jrtechsolution** [comment]
Como eu faço isso acima descrito

**Comment by willph** [comment]
Usar qual software?

Xampp, WampServer, Laragon?

**Comment by jrtechsolution** [comment]
Boa noite amigo eu tenho domino proprio. weblink,


Funciona perfeitamente so nao consigo enviar as OS por email, ja fiz o crod no painel e jo aparece pendente pode me ajudar?
lhe passo o acesso se vc puder me avisa. grande abraço


ATT.


JRTECH SOLUTION ME

CNPJ 15.505.567/0001-97

RUA BARÃO DE MESQUITA, 72 - RIO DE JANEIRO - RJ

CEP 20540-006 - TIJUCA

TEL: (21) 98441-6212 / (21) 99858-2590

CELSO DE MELO JUNIOR

________________________________
De: Wilmerson <notifications@github.com>
Enviado: quinta-feira, 14 de novembro de 2019 20:52
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: jrtechsolution <jrtec123@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] email mapos (#473)


Usar qual software?

Xampp, WampServer, Laragon?

**Comment by brennodornelas** [comment]
> Usar qual software?
> 
> Xampp, WampServer, Laragon?

Boa noite,
Will eu uso wamp voce pode me ajudar?

**Comment by jrtechsolution** [comment]
Amigos, então não consigo configurar de jeito nenhum o email,ja fiz o cron jobs e vc falam em executar uma linha de comando no cmd e nao sei como fazer preciso muito. Se algum de vcs poderem me ajudar ficarei muito grato. 

passo algum acesso remoto se precisarem.

**Comment by jrtechsolution** [comment]
Nao consigo enviar o email de forma alguma, ja tentei varios forun e nao consegui

**Comment by NATA-RMG** [comment]
Bom dia, alguém conseguiu enviar e-mail ?

**Comment by gustavooller** [comment]
nope...
alguem?

**Comment by brennodornelas** [comment]
Bom dia pessoal! consegui resolver o problema de envio de EMAIL aqui eu uso o Wamp.

1 - colocar o patch do php conforme o video = https://www.youtube.com/watch?v=jB5TvzzggWw
2 - Dentro da raiz do mapos criar um arquivo .bat com o script = php -f index.php email/process
3 - Agendador de tarefas do windows colocar o arquivo .bat para executar de tempos em tempos.

**Comment by NATA-RMG** [comment]
Bom dia, Otimo que resolveu o problema do poller, mas a minha questão é que o e-mail nem sai :

na fila do Banco de dados fica como : pending , dai executo o comando "php index.php email/process", 
o mesmo vai para : failed , todos arquivos estao configurados conforme instruçoes.

**Comment by RamonSilva20** [comment]
@NATA-RMG você está utilizando smtp do Google? Se sim é preciso configurar os aplicativos menos seguros como ON.

**Comment by brennodornelas** [comment]
Boa tarde, nao estou usando o smtp do google, estou usndo do meu dominio

**Comment by RamonSilva20** [comment]
Na próxima versão vai sair uma correção para a opção de SMTP.

**Comment by gustavooller** [comment]
maravilha! tem alguma previsão?

**Comment by RamonSilva20** [comment]
Correção de envio de e-mail por smtp corrigido na versão 3.14.1.

**Comment by NATA-RMG** [comment]
> @NATA-RMG você está utilizando smtp do Google? Se sim é preciso configurar os aplicativos menos seguros como ON.

Podes me ajudar ? como faço isso? Obrigado.

**Comment by Fernando-Martins-Leal** [comment]
Boa tarde, 

Pelo que entendi, para quem hospeda na nuvem, tem que configurar no servidor. Tenho opção de criar o cron job no meu serviço de hospedagem, mas é serviço não incluído no meu plano.

Então configurei o arquivo config/email.php com minhas credenciais e parâmetros da conta de email. Como não estou rodando local, ou seja, com domínio próprio num serviço web da ATSPACE, incluí o comando:
        $this->email->send_queue();
por volta da linha 38, do arquivo controllers/mapos, função index().

Ao logar no sistema, ele chama o método send_queue, mas não consegue enviar e registra como "failed" na coluna 'Status' da tabela "email_queue".
 
Mapos Versão 3.14.2.

Complicado isso. Muitos se queixando dessa restrição. O ideal seria que, logo ao clicar em enviar email, registrasse na tabela e tentasse, no mesmo instante, realizar o envio, só deixando como pendente se falhasse no envio. 

Se alguém achar uma solução, me diga, por favor.

Fernando

**Comment by silviomeiguins** [comment]
Boa noite RamonSilva20, você desenvolvendo sistema! ser sim envia um email para silvio.meiguins@gmail.com.

**Comment by silviomeiguins** [comment]
Boa noite RamonSilva20, você está desenvolvendo sistema! ser sim envia um email para silvio.meiguins@gmail.com.

**Comment by RamonSilva20** [comment]
@silviomeiguins não amigo, estou envolvido em outro projeto, sem disponibilidade no momento.

**Comment by silviomeiguins** [comment]
Ok, obrigado pelo retorno e sucesso no seu projeto.

Em dom, 2 de mai de 2021 00:22, Ramon Silva ***@***.***>
escreveu:
