### ISSUE TITLE
Pesquisar

### ISSUE THREAD

**Issue by BrunoMichael** [RamonSilva20/mapos#475]
Alguém já enfrentou problemas ao pesquisar um nome. Ex: Pablo ele não retorna nada. Se coloca Pablo André ele retorna o valor.

**Comment by diegoandrade93** [comment]
pesquisando na onde? clientes?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
