### ISSUE TITLE
Bom dia, estou na versão 3.5.3, update do sql obrigado

### ISSUE THREAD

**Issue by papaiisac** [RamonSilva20/mapos#477]
Bom dia, estou na versão 3.5.3, update do sql posso fazer da 3.10 ou tenho que fazer todas as anteriores (update.sql), valeu obrigado

**Comment by AntonioCarlos1979** [comment]
quando eu mudei de versão, fiz todas uma a uma por garantia. Algumas deram erro mas tudo funcionou perfeitamente. Só lembre-se de fazer bakup da sua base antes por seguranca

**Comment by papaiisac** [comment]
ok, valeu muito obrigado, vou fazer aqui

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
