### ISSUE TITLE
Não faz login

### ISSUE THREAD

**Issue by felipe8764** [RamonSilva20/mapos#479]
Não consigo fazer login, a barra de login ficar carregando infinitamente. 
observei que só acontece no site de hospedagem 000webhost. Alguém Sabe como resolve?
![Sem título](https://user-images.githubusercontent.com/58047826/69383872-95bde080-0c99-11ea-9771-cd50f0bb72c6.png)

**Comment by Pr3d4dor** [comment]
Abra o console ou aperte F12 e verifique os erros na aba do console e na aba de requisições que estiverem em vermelho.

**Comment by felipe8764** [comment]
os erros foram esses.
![Sem título](https://user-images.githubusercontent.com/58047826/69386510-9ce8ec80-0ca1-11ea-9f7d-02ea553705f9.png)

**Comment by Pr3d4dor** [comment]
Primeiramente sempre acesse usando https senão irá dar problema de CORS igual eu estava testando aqui.

Está dando erro 500 no PHP.

A conexão com o banco de dados está funcionando corretamente?

**Comment by felipe8764** [comment]
Aparentemente sim.
Eu instalei no hostinger.com  e funciona normalmente. Já no 000webhost fica dando esse erro ai,  deve ser porque ele tem alguma configuração faltando no servidor por ser uma hospedagem grátis.

**Comment by BESystemInfo** [comment]
Tive o mesmo problema. Optei por mudar a hospedagem free. Instalei na AwardSpace e está funcionando lindamente, apesar de ser mais lento no carregamento. Eles dão os mesmos recursos da 000webhost, porém com maior liberdade de configuração por 1 ano. É uma alternativa provisória.

**Comment by bneres** [comment]
eu notei que no processo de cadastro do usuário inicial ele não está sendo gravado na tabela, outro erro que ele está apresentando é quando faz insert do usuário admin, no arquivo para configurar o BD

**Comment by trollfalgar** [comment]
Tive esse problema também.
O sistema utiliza AJAX para requisições, no **localhost** funciona perfeitamente, mas ao enviar para a hospedagem (paga), não funciona. Testei em duas hospedagens.
Tive que alterar o método de login.

**Comment by felipe8764** [comment]
> Tive esse problema também.
> O sistema utiliza AJAX para requisições, no **localhost** funciona perfeitamente, mas ao enviar para a hospedagem (paga), não funciona. Testei em duas hospedagens.
> Tive que alterar o método de login.

Como altero o método de login?

**Comment by trollfalgar** [comment]
> 
> 
> > Tive esse problema também.
> > O sistema utiliza AJAX para requisições, no **localhost** funciona perfeitamente, mas ao enviar para a hospedagem (paga), não funciona. Testei em duas hospedagens.
> > Tive que alterar o método de login.
> 
> Como altero o método de login?

Ultimamente eu tenho utilizado o Laravel ao invés do Codeigniter pela facilidade no uso depois que pega o jeito, ele já vem com sistema de autenticação incluso.
Mas pra esse projeto eu utilizei o que o Codeigniter já oferece. Criei o método no controller, a rota, fiz as devidas validações e funciona perfeitamente.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
