### ISSUE TITLE
Erro CodeIgniter.php

### ISSUE THREAD

**Issue by rafew** [RamonSilva20/mapos#48]
Boa tarde. Eu tinha o Map OS instalado na versão anterior, porém ao atualizar ocorreu o seguinte erro:

Parse error: syntax error, unexpected T_CONST in /home/storage/3/44/e3/brickimpressos/public_html/os3/system/core/CodeIgniter.php on line 58

Pesquisei sobre o erro e não achei nada. Alguém pode me ajudar a resolver?

**Comment by KokeroO** [comment]
Deve usar a versão do PHP igual ou superior a 5.4.
CONST não funciona em versões anteriores a 5.4.

**Comment by rafew** [comment]
Nossa, na mosca. Meu host tava no 5.2 ainda.
Muito obrigado!
