### ISSUE TITLE
bastante duvida no envio de email

### ISSUE THREAD

**Issue by reantotrucker** [RamonSilva20/mapos#481]
alguem pode me dar uma força, nao consigo msm configurar a opcao de enviar por email, nunca vir essa parte de cron. nao sei se tenho q fazer um scrips, sei q tem no cpanel uma opcao de fazer isso mas nao sei como

**Comment by NATA-RMG** [comment]
Boa tarde, nao consigo enviar e-mail vc consegue ?

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
