### ISSUE TITLE
Produtos

### ISSUE THREAD

**Issue by mozersedrez** [RamonSilva20/mapos#482]
Bom dia.
Estou com uma duvida a respeito a um erro que esta dando no sistema.
O mesmo estava instalado na pasta raiz e uma versão mais antiga (3.10.0)
Como estou para incluir uma pagina no domínio, resolvi instalar a versão mais atualizada dentro do diretório "/os/".
Configurei o BD tudo certo, puxou automático os dados ja cadastrado da versão anterior.
Porém o ao clicar em produtos, da erro (500 Erro interno no servidor).
O que pode ser isso?

**Comment by AntonioCarlos1979** [comment]
amigo, roda o update do banco de dados, apenas abra o phpmyadmin e importe o arquivo update_3.12_to_3.14.sql que se encontra na pasta Updates do mapos. apos isso a aba abrira normalmente. Não se preocupe seu dados nao serão perdido, porém recomendo backup.

**Comment by marcosaquino34** [comment]
seria interessante poder cadastrar o produto com codigo de barra e também poder localizar o produto com o codigo de barra cadastrado.
