### ISSUE TITLE
Versão [3.14.0] - 2019-11-22 

### ISSUE THREAD

**Issue by ADMTec** [RamonSilva20/mapos#484]
Nao esta aparecendo algumas imagens, como a do login e da senha. entre outras!
e tamnbem a pagina Produtos nao esta abrindo da erro 500!

![Captura de Tela (62)](https://user-images.githubusercontent.com/16466549/69486249-afd9f900-0e28-11ea-9cd8-2686fe3c240f.png)
![Captura de Tela (63)](https://user-images.githubusercontent.com/16466549/69486252-bbc5bb00-0e28-11ea-83cb-e23de99b9b24.png)

**Comment by BESystemInfo** [comment]
Acredito que falte você fazer o update do DB, que está na pasta de updates. Sobre as imagens, atualize a página com CTRL + F5. Aqui depois desses passos, deu certo.

**Comment by brennodornelas** [comment]
aqui o mesmo problema o botoes nao funcionam!

**Comment by vagnerlaiber** [comment]
> Não aparece algumas imagens, como fazer login e da senha. entre outras!
> e tamnbem a pagina Produtos não esta abrindo o erro 500!
> 
> ![Captura de tela (62)](https://user-images.githubusercontent.com/16466549/69486249-afd9f900-0e28-11ea-9cd8-2686fe3c240f.png)
> ![Captura de tela (63)](https://user-images.githubusercontent.com/16466549/69486252-bbc5bb00-0e28-11ea-83cb-e23de99b9b24.png)

No meu aconteceu parecido, mudei a versão do PHP para 5.6, resolveu.

**Comment by Pr3d4dor** [comment]
@vagnerlaiber Recomendo fazer o update para o PHP 7.2+ pois o PHP 7.1 pra baixo não tem mais suporte.

**Comment by vagnerlaiber** [comment]
> @vagnerlaiber Recomendo fazer a atualização para o PHP 7.2 ou superior ou PHP 7.1 para baixo não tem mais suporte.

OK
inclusive já coloquei PHP 7.2 e funcionou perfeitamente

**Comment by leandr0ferreir4** [comment]
Também estou com este mesmo problema dos ícones na versão 3.14.1, fiz a atualização do banco importando o arquivo _**update_3.12_to_3.14.sql**_ Limpei os dados completo dos navegadores, uso a hospedagem da Hostinger, fiz uma limpeza de cache que está disponível dentro da administração da hospedagem, atualmente está selecionado a versão do PHP 7.4, mas já testei com 7.3, 7.2, e outras disponíveis, refiz a instalação do mapos usando o instalador automático, revisei permissões, mas nada resolve, Firefox e Google Chrome persiste o problema, porém instalei o Opera e está funcionando normalmente.

---
Aproveitando, não sei se isso seria um bug ou o problema relacionado aos ícones, mas sempre que clico em Dashboard, sou redirecionado para a página de Login, notei também que ao repousar o mouse sobre o menu Dashboard o link que aparece é o **https://meudominio/mapos/** e acredito que que deveria ser **https://meudominio/mapos/index.php/mapos** já este possível problema ocorre em todos os navegadores que testei.
