### ISSUE TITLE
Acesso expirado

### ISSUE THREAD

**Issue by yasron** [RamonSilva20/mapos#486]
Como faço para ter acesso ao programa , fiz a instalação e depois do login aparece a mensagem de acesso expirado.
[<a href="https://imgur.com/74Du34D"><img src="https://i.imgur.com/74Du34D.png" title="source: imgur.com" /></a>](url)

**Comment by mmonzato** [comment]
@yasron leia o arquivo instruções.txt

**Comment by yasron** [comment]
@mmonzato, eu li para poder fazer a instalação e não achei nada, mais vou dar mais uma olhada, obrigado mais se tiver mais alguma dica.

**Comment by mmonzato** [comment]
@yasron está relacionado a uma modificação na base de dados, essa modificação está descrita no arquivo por isso sugeri a leitura.

**Comment by yasron** [comment]
@mmonzato obrigado pela dica mais não resolveu, fiz as alterações no arquivo banco.sql e o resultado foi o mesmo.

**Comment by BESystemInfo** [comment]
Tenta verificar no DB a validade do acesso do usuário. Tem um campo que indica até quando o usuário pode acessar, talvez a data lá esteja errada e ele entende que o usuário já não tem mais permissão de acesso.

**Comment by yasron** [comment]
@BESystemInfo verifiquei lá, esta com a data nula, então não seria para expirar.

**Comment by BESystemInfo** [comment]
Mas você chegou a testar colocar uma data posterior? Exemplo: no meu está com a data de janeiro de 3000 (3000-01-01).

**Comment by yasron** [comment]
@BESystemInfo muito obrigado pela tua ajuda, fiz com me sugeriu e alterei a data do DB de nula para outra data (3001/01/01), e funcionou.
