### ISSUE TITLE
Erro no financeiro

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#49]
Boa noite pessoal! Alguém está tendo problema na parte financeiro? Eu peço pra mostrar todos/pendentes ele me mostra alguns, sendo que tem muitos a vencer que nao mostra. Fiz um teste mudando a data de vencimento e mesmo assim não mostra.

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20, fiz o teste na demo do mapos e deu o mesmo problema, na versão 3.1.7 existe a possibilidade de ter consertado?

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004, não cheguei a verificar esta parte, fiz a correção somente do problema de impressão.

**Comment by acinformatica2004** [comment]
@RamonSilva20 é possível fazer essa verificação? Utilizo muito essa função e toda vez tenho que ficar procurando. Se tivesse a opção de busca igual da ordem de serviço que implantou, ficaria show. Obrigado

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20, achei o problema, a consulta procura na base de dados no campo baixado valores 0, porém quando se faz um faturamento ele lança no banco de dados como NULL,sendo assim o sistema não encontra os respectivos lançamentos.
Mudei manualmente na base de dados e o sistema encontrou.
Só não achei no codigo fonte a opção de lançar o campo como 0 na hora de faturar.

Caso consiga e puder me ajudar.
Obrigado

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004. Defina no banco de dados o valor default 0 para o campo baixado, adicionarei isto no arquivo sql.

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20, mudei o valor defaut para 0, porém o sistema não efetua o faturamento da o.s ou da venda. Se deixo null ele fatura normalmente.

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20! Vi que você fez alterações no sistema, como que posso fazer a atualização do banco de dados? 
Obrigado

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004. Basta executar o camando abaixo para colocar o valor default 0 no campo baixado, ou rodar o arquivo de update do banco para a versão 3.1.9.

ALTER TABLE `lancamentos` CHANGE `baixado` `baixado` TINYINT(1) NULL DEFAULT '0';

**Comment by acinformatica2004** [comment]
bom dia @RamonSilva20, só deixa te fazer uma pergunta, como que faço nos lancamentos que foram lançados e estao com valores null, qual comando sql que atualizo isso.
Obrigado

**Comment by acinformatica2004** [comment]
bom dia, ja consegui resolver.
se quiser atualizar na base segue o comando para adicionar.

update lancamentos set baixado = '0' where baixado is NULL

Obrigado

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20! Depois da atualização os lançamentos funcionaram legal, porém notei que alguns ele mostrava pendente e outros não, então fui no banco de dados e alguns estavam com o valor null ao invés de 0, o que poderia ser isso? Agora todos lançamentos entram novamente como null e não mostram no sistema.

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004. Mesmo estando com o valor default 0 quando inserido fica como null?

**Comment by acinformatica2004** [comment]
Mesmo estando, o que achei estranho foi que alguns lançamentos entrou com 0 e outros null. Muito estranho

**Comment by RamonSilva20** [comment]
Vou corrigir, já tenho uma ideia de onde pode estar o problema.

**Comment by acinformatica2004** [comment]
Blz, muito obrigado

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20! Você conseguiu achar o problema? Só estou perguntando pra tentar ajudar, não estou te cobrando. Obrigado

**Comment by marllonferreira** [comment]
to com o mesmo problema na parte do financeiro

E também achei um outro lá na área do cliente

**Comment by marllonferreira** [comment]
Previsão de quando vai está corrigido ?

**Comment by acinformatica2004** [comment]
Boa noite @RamonSilva20! Conseguiu achar no código onde está o problema? Abraços

**Comment by RamonSilva20** [comment]
Boa noite @acinformatica2004 . Problema corrigido. Abraços.

**Comment by marllonferreira** [comment]
Ei @RamonSilva20 tem como corrigir também a parte de exclui permissão 

Acredito que  seja o último erro faltando ate agora

**Comment by RamonSilva20** [comment]
Bom dia @marllonferreira. Vou verificar e corrigir o problema. Grato.

**Comment by acinformatica2004** [comment]
boa tarde @RamonSilva20, muito obrigado. Me ajudou muito.
