### ISSUE TITLE
Erro botão Dashboard v.3.14

### ISSUE THREAD

**Issue by michelfritsch** [RamonSilva20/mapos#491]
Botão Dashboard fazendo a função Sair/Logout quando acionado.

**Comment by willph** [comment]
Poderia colocar o print por favor?

**Comment by michelfritsch** [comment]
Não tem como, assim que acionado o botão Dashboard no menu esquerdo já
envia para a página de login.

Em ter, 26 de nov de 2019 16:24, Wilmerson <notifications@github.com>
escreveu:

**Comment by willph** [comment]
Coloca apenas uma seta apontado o local então.

**Comment by michelfritsch** [comment]
Em ter, 26 de nov de 2019 17:58, Wilmerson <notifications@github.com>
escreveu:

**Comment by willph** [comment]
Obrigado.
Amanhã vou analisar como está no meu.
E faço a correção

**Comment by willph** [comment]
No meu não está apresentando este erro mencionado.
Cliquei e voltou para o Dashboard normalmente. Testei no Chrome e no Firefox.

Agora se você passar um tempo sem atividade, ele automaticamente faz logout.

**Comment by michelfritsch** [comment]
Não é por tempo de inatividade, aqui ocorre tanto no Chrome quanto no Firefox.

**Comment by brennodornelas** [comment]
Bom dia! Estou com o mesmo problema!

**Comment by michelfritsch** [comment]
Resolvido com a instalação da v.3.14.1
