### ISSUE TITLE
Etiqueta sem cód. de barras

### ISSUE THREAD

**Issue by FlexoSol** [RamonSilva20/mapos#492]
Bom dia!
Antes de tudo, gostaria de agradeçer pelo belo trabalho ao qual é o MapOs. Estou usando em modo de teste a versão 3.14, fiquei muito feliz quando vi a inclusão da impressão de etiquetas com código de barras ou qrcode. 
Porém,  para mim, não estou conseguindo fazer que apareça o código de barras, ou seja, aparece apenas a descrição, código cadastro e valor. 
Há alguma ideia do que seria o problema???
Já vou avisando, minha experiencia com programação é mínima.
Obrigado.

**Comment by mmonzato** [comment]
@FlexoSol a versão 3.14 ainda está com alguns problemas, incluindo esse da etiqueta. A correção será disponibilizada em breve.

**Comment by FlexoSol** [comment]
Obrigado pelo retorno, não havía visto que estava sendo tratado e corrigido em post anterior #490 
Funcionando agora :)
