### ISSUE TITLE
Busca de CEP

### ISSUE THREAD

**Issue by augustocoletti** [RamonSilva20/mapos#493]
Bom dia, na versão 3.14 upada pelo Wilmerson na Pull #490, não está fazendo busca automática de cep e autocompletando campos de endereço. 
Obrigado

**Comment by willph** [comment]
Aqui está funcionando normalmente. Tanto em cadastro de usuários, como no cadastro de clientes e na área do cliente.

**Comment by augustocoletti** [comment]
Realmente estava funcionando... o problema estava na minha maquina... não sei por que mas apos Ctrl+F5  resolveu. 
Desculpe o transtorno e obrigado pela atenção.

**Comment by willph** [comment]
Sem problemas. Acontece
