### ISSUE TITLE
Página de Ordem de serviço não abre

### ISSUE THREAD

**Issue by SouzaDH91** [RamonSilva20/mapos#494]
Ao tentar clicar em Ordem de serviço da erro:

![Screenshot_1](https://user-images.githubusercontent.com/53587292/69744654-57a04100-111f-11ea-83ba-3d2379a50834.png)

**Comment by mmonzato** [comment]
@SouzaDH91 você fez os updates do banco de dados ?

**Comment by SouzaDH91** [comment]
> @SouzaDH91 você fez os updates do banco de dados ?

opa @mmonzato fiz sim cara, as outras páginas funcionam certinho, só ela que não

**Comment by mmonzato** [comment]
@SouzaDH91 edita o arquivo index.php, vai na linha 59 e troca define('ENVIRONMENT', 'production'); por define('ENVIRONMENT', 'development'); e veja qual o erro vai aparecer.

**Comment by SouzaDH91** [comment]
> @SouzaDH91 edita o arquivo index.php, vai na linha 59 e troca define('ENVIRONMENT', 'production'); por define('ENVIRONMENT', 'development'); e veja qual o erro vai aparecer.

ok amigo, vou alterar aqui. Uma pergunta, eu posso adicionar funcionalidades no sistema?

**Comment by mmonzato** [comment]
@SouzaDH91 você pode sim, depois entra no grupo do whatsapp para trocar uma idéia com a galera.

**Comment by SouzaDH91** [comment]
> @SouzaDH91 você pode sim, depois entra no grupo do whatsapp para trocar uma idéia com a galera.

opa pode deixar, é que eu sou desenvolvedor tambem e tive umas ideias, pois to desenvolvendo um site pra usar junto com o mapos

**Comment by SouzaDH91** [comment]
consegui resolver o problema aqui cara, valeu mesmo pela ajuda e principalmente atenção! O problema é que no relacionamento da tabela os com a de clientes, nas duas tem campo 'status' causando ambiguidade. Eu adicionei o campo status na de clientes, pois quero implementar algumas coisas

**Comment by mmonzato** [comment]
Blz, precisando estamos ai!

**Comment by SouzaDH91** [comment]
@mmonzato valeu mesmo

**Comment by SouzaDH91** [comment]
opa @mmonzato beleza cara? desculpa te incomodar, mas queria tirar umas dúvidas sobre o sistema, posso mandar aqui mesmo ou tem outro lugar que possar tirar essas dúvidas?

**Comment by mmonzato** [comment]
@SouzaDH91 cara manda lá no grupo do whatsapp.
