### ISSUE TITLE
Botão Enviar por WhatsApp Tela das OS erro na versão: 3.14.1

### ISSUE THREAD

**Issue by Kajueiro** [RamonSilva20/mapos#497]
Bom dia amigos!  Hoje atualizei para versão 3.14.1. Porém na tela das OS o botão do WhatsApp ficou com problema em algumas OS.
Vejam na imagem...

![tela-os](https://user-images.githubusercontent.com/48531892/69955726-145a1f80-14dd-11ea-8963-08a3058e8c04.jpg)

**Comment by RamonSilva20** [comment]
Obrigado por notificar @Kajueiro. Provavelmente algum caracter especial que está causando esse problema.

**Comment by vagnerlaiber** [comment]
Boa Tarde @Kajueiro no meu aqui, eu clico em visualizar a OS depois clico no ícone whatsapp funciona OK, mas naquela tela inicial da OS realmente não funciona.

**Comment by willph** [comment]
Eu fiz o teste no meu é na View OS.php está funcionando.
Agora em editarOs.php funciona, só não trás os dados do Emitente. Mas o resto do texto está pegando.

**Comment by Kajueiro** [comment]
Boa tarde amigos! O problema ocorre quando tem formatação html no texto do campo "Descrição Produto/Serviço".

**Comment by Kajueiro** [comment]
> Boa tarde amigos! O problema ocorre quando tem formatação html no texto do campo "Descrição Produto/Serviço".

Na verdade, um link no campo citado.

**Comment by willph** [comment]
Agora sim. Realmente acontece, eu testei aqui. Se criar um link em uma OS da esse bug. Como nunca coloquei link não tinha visto

**Comment by Triaca** [comment]
isso foi corrigido?
