### ISSUE TITLE
Problemas no módulo vendas versão: 3.14.1

### ISSUE THREAD

**Issue by brasileirodacosta** [RamonSilva20/mapos#498]
Olá, bom dia!

Estava testando o MAPOS na versão 3.14.1 e notei que ao tentar adicionar o produto que o cliente vai comprar, quando se digita o inicio do nome do produto, ele não mostra as opções de produtos com o mesmo nome para escolher qual produto ele vai comprar, e consequentemente ele não adiciona o preço do produto e na hora que inclui o produto com o mesmo nome e valor de venda, ele da erro.

Vou anexar o prints da situação.
![MAPOS-2](https://user-images.githubusercontent.com/55510222/70147362-cf6fed80-1682-11ea-8412-de2d4255ec67.png)
![MAPOS-3](https://user-images.githubusercontent.com/55510222/70147364-cf6fed80-1682-11ea-9904-f05694c4bee1.png)

**Comment by mmonzato** [comment]
@brasileirodacosta Bom dia, aqui está funcionando de boa, o autocompletar está configurado para as 2 primeiras letras do produto.

**Comment by brasileirodacosta** [comment]
Olá, boa tarde!
Não se atentei para a opção de saída.. depois que eu marquei o item apareceu normalmente. Obrigado por ajudar..
