### ISSUE TITLE
ERRO CSS DO SISTEMA

### ISSUE THREAD

**Issue by hdarantes** [RamonSilva20/mapos#50]
O sistema não está mais estilizando a página, os menus estão como tópico, totalmente desformatado o sistema.
Mais alguém está com o problema?

**Comment by hdarantes** [comment]
consegui resolver

**Comment by cleytonasa** [comment]
o que você fez hdarantes?

**Comment by hdarantes** [comment]
cleytonasa, eu tinha substituído os arquivos bootstrap.min.css, bootstrap-responsive.min.css, matrix-media.css e matrix-style.css PELOS MESMOS ARQUIVOS NOVOS QUE ESTÃO NO GUIT.

Peguei esses mesmos arquivos de uma versão antiga.
