### ISSUE TITLE
Acesso externo pelo xampp usando mapos

### ISSUE THREAD

**Issue by ferrazaddon** [RamonSilva20/mapos#506]
Oi Ramon, td bem??? gostaria de saber se tem como configurar o map os pelo xampp para funcionar fora da rede local. pois vi varios tutoriais, coloquei o xampp pelo noip, mas nao carrega o mapos, tenho uma outro programa mais simples com banco de dados carregada normalmente, ate phpmyadmin, nao sei se dar para resolver isso, ante q alguem fale em hospedar, na minha oficina cai muita a net, então nao posso ficar dependendo de acesso externo para acessar o sistema, isso seria para uma chamada tecnica, em vez de preencher a os em papel, iria direto no sistema.
Deus te abencoe muito

Marcus
Itararé-SP
zap15981159347

**Comment by diegoandrade93** [comment]
tem sim mano, 

tem que atualizar na config.php com o ip externo ou dns
$config['base_url'] = 'ipexterno';

é legal criar vhosts com o xamp fica legal tbm

**Comment by ferrazaddon** [comment]
> tem sim mano,
> 
> tem que atualizar na config.php com o ip externo ou dns
> $config['base_url'] = 'ipexterno';
> 
> é legal criar vhosts com o xamp fica legal tbm

Funcionou aki...

Vou pesquisar sobre esse vhosts e ve se consigo criar.

Muito obrigado

Deus te abençoe ricamente!!!!

**Comment by TecSecret** [comment]
Uma dica é vc usar no $config['base_url] isso aqui: 

$base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$base_url .= "://". @$_SERVER['HTTP_HOST'];
$base_url .=     str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
$config['base_url'] = $base_url;

ai já vai identificar o dominio ou ip do vhost e pronto

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
