### ISSUE TITLE
Procedimento correto para atualização V.3.8.0 para V.3.14.1

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#508]
Qual o procedimento correto para fazer a atualização da versão 3.8.0 para versão 3.14.1?

**Comment by AntonioCarlos1979** [comment]
rode uma a uma conforme consta na pasta UPDATES e não haverá problemas.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
