### ISSUE TITLE
dbprefix vs MapOS

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#509]
Tem possibilidade de utilizar dbprefix no MapOS?
Pelas configurações do codeigniter do banco de dados, sei que é possível, e até vi que no arquivo de configuração do BD, que tem essa opção, mais em testes não consegui fazer funcionar, sempre erro 500, talvez por falta de mais alguma configuração. Segue abaixo passo a passo como tentei configurar.

1 passo: Fiz backup do banco de dados para não perder as informações.
2 passo: Adicionei o prefixo c1_ para teste en todas tabelas utilizando o phpmyadmin, para fazer tudo automático, sem ter que fazer uma por uma das tabelas na unha.
3 passo: Setei em aplication/config/database.php oparametro dbprefix' => 'c1_'
4 passo: fui para tela de login e erro 500.

Desde já agradeço quem puder ajudar!

**Comment by RamonSilva20** [comment]
Olá. Altere no arquivo index.php da raiz, linha 59, para development, isso deve dar mais detalhes do erro.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
