### ISSUE TITLE
Adicionar mais um campo - celular

### ISSUE THREAD

**Issue by igoscarvalho** [RamonSilva20/mapos#511]
Boa noite pessoal, blz? Sou estudante de programação em PHP e estou aprendendo bastante com esse programa, porém alguém poderia me ajudar ou se já tiver esse mesmo sistema com mais uma informação? Exemplo: gostaria de criar mais uma relação, como se fosse uma cliente, porém queria adicionar o celular, com as mesmas propriedades do cliente, tipo cliente tal com celular tal, isso seria possível?

Obrigado!

**Comment by trollfalgar** [comment]
Eu não sei se o pessoal que desenvolve o sistema vai adicionar algo assim. Mas você pode criar esse controle.
Eu criei um controle a mais para APARELHOS CELULARES, devido ao nicho que vou atender com o sistema. Você pode fazer o mesmo.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.

**Comment by igoscarvalho** [comment]
> Eu não sei se o pessoal que desenvolve o sistema vai adicionar algo assim. Mas você pode criar esse controle.
> Eu criei um controle a mais para APARELHOS CELULARES, devido ao nicho que vou atender com o sistema. Você pode fazer o mesmo.

Poderia me passar esse controle atualizado para que eu possa ver? Ou alguma imagem, video, algo assim.
