### ISSUE TITLE
versão php

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#512]
Boa noite! Uso uma versão antiga do mapos, utilizo o php 5.6, porém só modificar para o 7.2 o sistema não faz login. O que pode ser? Há algo no código que possa mudar para aceitar essa versão?
Obrigado

**Comment by robsonmeca** [comment]
Estou utilizando a versão 7.2 do php sem problemas. Tenta limpar os logs do navegador.

**Comment by trollfalgar** [comment]
Tudo funcionando em localhost com PHP 7.4.
