### ISSUE TITLE
Área do cliente está funcionando ?

### ISSUE THREAD

**Issue by Douglas360** [RamonSilva20/mapos#513]
Boa tarde Pessoal, não estou conseguindo utilizar a "Área do cliente", eu preencho o email e CNPJ do meu cliente cadastrado, porém quando clico no botão Acessar, nada acontece.
Estou utilizando a versão 3.14.1

**Comment by robsonmeca** [comment]
Esta funcionando sim, porém percebi um bug no sistema que vai afetar cadastros mais antigos, pois na versão 3.8 que eu estava usando, os usuários cadastrados com cnpj eram cadastrados no banco de dados assim **xxx**.xxx.xxx/xxx-xx e agora esta assim **xx**.xxx.xxx/xxx-xx com apenas 2 algarismos antes do primeiro ponto. Para corrigir isso, basta ir no campo cnpj do cadastro do cliente em questão, apagar o cnpj, redigitar, salvar o cadastro e tudo volta ao normal para esse cliente. Esse Bug só afeta os cadastros com CNPJ, CPF esta tudo ok.

**Comment by Douglas360** [comment]
Opa, obrigado pelo retorno.
Mas mesmo eu cadastrando novo cliente, seja CNPJ ou CPF, nada acontece ao clicar no botão "Acessar", parece que o botão está sem função.

**Comment by TecSecret** [comment]
Estou com o mesmo problema. Não acessa a área do cliente ao clicar em acessar nada acontece.

**Comment by giovanne-oliveira** [comment]
Estou enviando a correção. Problemas em relação ao PHP 7.2 na lógica da função count.

**Comment by Douglas360** [comment]
Obrigado.

**Comment by bbonifacio** [comment]
Bom dia, amigos sou novo nesse mundo... 
Eu realizei uma instalação do Mapos com 7.2 php em uma hospedagem, rodou bem. 
Porem eu não consigo cadastrar clientes, aparece apenas: ocorreu um erro. 
Alguém pode me dar uma luz?

**Comment by willph** [comment]
> Bom dia, amigos sou novo nesse mundo...
> Eu realizei uma instalação do Mapos com 7.2 php em uma hospedagem, rodou bem.
> Porem eu não consigo cadastrar clientes, aparece apenas: ocorreu um erro.
> Alguém pode me dar uma luz?

Qual sua versão de Mapos?
