### ISSUE TITLE
Matriz e Filial

### ISSUE THREAD

**Issue by marcelinoac** [RamonSilva20/mapos#514]
Boa noite! Eu utilizo o sistema a algum tempo e tenho a necessidade de emitir relatórios de ordem de serviço com mais de uma empresa selecionada, seria possível?

Tenho um cliente que tem 06 lojas e gostaria de emitir um relatório constando as ordens de serviço de todas de uma vez, e também na área do cliente fosse possível com um login único ele visualizar todas as 06 lojas.

**Comment by RamonSilva20** [comment]
Olá @marcelinoac, o sistema não foi projetado para ser multiloja.

**Comment by marcelinoac** [comment]
Obrigado pelo retorno @RamonSilva20! Parabéns pela iniciativa, o sistema é muito bom.
