### ISSUE TITLE
Brasil Setup

### ISSUE THREAD

**Issue by RuiPereira70** [RamonSilva20/mapos#516]
Seria possível dizer-me qual o ficheiro que poderia desativar a formatação do telefone e  CPF.
Gostaria de utilizar este script para minha organização, mas em portugal o formato do telefone é diferente. Obrigado pela atenção

**Comment by trollfalgar** [comment]
> 
> 
> Seria possível dizer-me qual o ficheiro que poderia desativar a formatação do telefone e CPF.
> Gostaria de utilizar este script para minha organização, mas em portugal o formato do telefone é diferente. Obrigado pela atenção

Olá.
Você pode alterar a máscara do telefone ou CPF aqui: `assets/js/funcoes.js`.

**Comment by RuiPereira70** [comment]
obrigado pela ajuda, ficou perfeito
