### ISSUE TITLE
Alguém já usou o sistema em impressora não fiscal?

### ISSUE THREAD

**Issue by cleytonasa** [RamonSilva20/mapos#52]

**Comment by jacksonsoftplus** [comment]
tmb tenho interesse, possuo uma bematech mp4000 e uma elgin i9.
seria muito interessante o cliente levar um comprovante de recibo de entrega e recebido.

**Comment by jacksonsoftplus** [comment]
Eu ainda não, mas tenho uma aqui.
Esperando pra ser usada.

Em 7 de nov de 2017 09:32, "Daniel" <notifications@github.com> escreveu:

**Comment by drelldeveloper** [comment]
@jacksonsoftplus Você pode fazer o teste?

**Comment by jacksonsoftplus** [comment]
Claro.
Estou viajando, assim q chegar eu instalei e farei teste. É uma Elgin i9.

Em 7 de nov de 2017 09:43, "Daniel" <notifications@github.com> escreveu:

**Comment by drelldeveloper** [comment]
Okay.
