### ISSUE TITLE
Retorno

### ISSUE THREAD

**Issue by AntonioCarlos1979** [RamonSilva20/mapos#521]
Boa tarde a todos, alguma novidade referente as issues #460 e #463 ?
Desculpe a insistência, sei que todos tem seus afazeres e o sistema é distribuído e atualizado deforma gratuita não cabendo cobrança de implementações mas estas duas questões são de extrema utilidade e importância. Grato

**Comment by trollfalgar** [comment]
Essa funcionalidade não foi adicionada ainda pelo que percebi.
Vou tentar adicionar uma PR ainda esta semana, se o pessoal da equipe não adicionar primeiro. Vou precisar desse recurso também.

**Comment by trollfalgar** [comment]
Fiz um PR com a funcionalidade #460 .
Aguardando o @RamonSilva20 verificar.

**Comment by AntonioCarlos1979** [comment]
> Essa funcionalidade não foi adicionada ainda pelo que percebi.
> Vou tentar adicionar uma PR ainda esta semana, se o pessoal da equipe não adicionar primeiro. Vou precisar desse recurso também.

Amigo, grato pelo retorno e por se dispor a tal tarefa.

**Comment by AntonioCarlos1979** [comment]
@trollfalgar será que voce consegue dar uma olhada na issue #463 ? Estou usando sua ultima commit onde acrescentou o botão para atualizar estoque. Aquela que vc mencionou na issua #460 
Desde já agradeço o empenho

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
