### ISSUE TITLE
Faturar pela home

### ISSUE THREAD

**Issue by diegoandrade93** [RamonSilva20/mapos#523]
eae pessoal, to precisando e uma forcinha ...

em ordens de servico abertas tentei fazer a opcao de faturar pela home, mais ao clicar nao retorna os valores da o.s selecionada.

alguem da uma luz rs... valeu

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.

Estou fazendo uma limpa nas issues.
