### ISSUE TITLE
Login após auto instalação nao acessa

### ISSUE THREAD

**Issue by psydown** [RamonSilva20/mapos#524]
Boa tarde a todos !
Primeira mente gostaria de agradecer o esforço do pessoal envolvido nesse projeto .

   Estou com um problema na hora de logar pela primeira vez no sistema, ele fica carregando e não entra apos digitar e-mail e senha, mesmo digitando qualquer coisa nos compôs e-mail e senha não acessa. 
![Screenshot_2020-01-03 MAP OS](https://user-images.githubusercontent.com/59485658/71743888-70012b00-2e44-11ea-858f-d051f1d80bb4.png)
![Screenshot_2020-01-03 MAP OS](https://user-images.githubusercontent.com/59485658/71743916-80190a80-2e44-11ea-9a1c-7af752921602.png)

 A instalação esta sendo feita em um ubuntu 18.04 php 7.2 de forma automática, vou tentar a manual para ver se tenho exito . poderiam me dar algumas dicas do possível problema ?

**Comment by psydown** [comment]
Ao tentar fazer manual estou recebendo o seguinte erro no script banco.sql 

./banco.sql: line 1: SET: command not found
./banco.sql: line 2: SET: command not found
./banco.sql: line 3: SET: command not found
./banco.sql: line 7: --: command not found
./banco.sql: line 8: ci_sessions: command not found
./banco.sql: line 8: --: command not found
./banco.sql: line 9: --: command not found
./banco.sql: line 10: syntax error near unexpected token `('
./banco.sql: line 10: `CREATE TABLE IF NOT EXISTS `ci_sessions` ('

**Comment by diegoandrade93** [comment]
no upload do banco deu tudo certo? acho que faltou alguma tabela

**Comment by psydown** [comment]
na verdade ele não vez o upload das tabelas nem autonímico nem manualmente

**Comment by diegoandrade93** [comment]
tenta fazer upload do arquivo banco.sql no banco de dados mapos

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
