### ISSUE TITLE
fonte da data

### ISSUE THREAD

**Issue by felipe8764** [RamonSilva20/mapos#525]
Como faço para muda a fonte da data e corrigi esse erro? Ele não mostra letras acentuadas ou Ç.
![Sem título](https://user-images.githubusercontent.com/58047826/71773982-7d520e80-2f45-11ea-8e14-e2856f9eb4f5.png)

**Comment by AntonioCarlos1979** [comment]
Ja foi corrigido na v3.14.2

**Comment by trollfalgar** [comment]
Também corrigido o estilo de fonte e alinhamento num PR. Aguardando análise.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
