### ISSUE TITLE
[Ajuda] Reinstalação Limpa do Sistema

### ISSUE THREAD

**Issue by Bremyarck** [RamonSilva20/mapos#526]
Como faço a limpeza do sistema para reinstalação em uma nova maquina? o que tenho que remover ou alterar? seria bom atribuir a resolução dessa questão no README para futuros usuários. obrigado pela compreensão!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
