### ISSUE TITLE
Fuso horário incorreto na aba Anotações 

### ISSUE THREAD

**Issue by Kajueiro** [RamonSilva20/mapos#528]
Boa noite a todos!
Percebi que o Fuso horário não bate com America/Sao_Paulo na aba Anotações.
Já coloquei date_default_timezone_set('america/sao_paulo') direto nas páginas das OS, mesmo assim não funciona.
Alguém tem alguma sugestão?
Obrigado!

**Comment by TecSecret** [comment]
Bom dia,

Vai no php.ini e seta o time.zone para America/Sao_paulo. 

Isso resolve muitos problemas

**Comment by Fernando-Martins-Leal** [comment]
Bom dia Kajueiro. Se estiver rodando hospedado na nuvem e não tiver plano com servidor dedicado, você terá que setar a hora local manualmente nos scripts, como fiz nos scripts abaixo:

libraries->MY_Email.php (linhas 81 em diante)
            $hora = date("H")-3; // captura a hora do servidor e subtrai 3 horas para hora São Paulo
            $data = array(
                'anotacao' => $this->input->post('anotacao'),
                'data_hora' => date('Y-m-d '.$hora.':i:s'),
                'os_id' => $this->input->post('os_id'),
            );  


controllers->Os.php (linhas 765 em diante)
            $hora = date("H")-3; // captura a hora do servidor e subtrai 3 horas para hora São Paulo
            $data = array(
                'anotacao' => $this->input->post('anotacao'),
                'data_hora' => date('Y-m-d '.$hora.':i:s'),
                'os_id' => $this->input->post('os_id'),
            );

helpers/mpdf/audit_helper.php (linhas 8 em diante)
    $hora = date("H")-3; // captura a hora do servidor e subtrai 3 horas para hora São **Paulo**
    
    $data = array(
        'usuario' => $ci->session->userdata('nome'),
        'ip' => $ci->input->ip_address(),
        'tarefa' => $task,
        'data' => date('Y-m-d'),
        'hora' => date($hora.':i:s'),
 
Não estou certo se cerquei todos timestamps, mas basta buscar por 'date(' que encontrará. 

Boa sorte!

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
