### ISSUE TITLE
Produtos inacessíveis apos importação do banco de dados da versão anterior

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#529]
Quando atualizei para a versão 3.14.2 todas as opções funcionam normalmente exceto a aba produtos que vai p uma tela em branco.

**Comment by AntonioCarlos1979** [comment]
é necessario atualizar o banco de dados com o update "update_3.12_to_3.14".  Caso venha de uma versão anterior a 3.12, eu recomendo rodar as updates correspondentes.

**Comment by crimat06** [comment]
Perfeito! Funcionando 100% até o momento! Obrigado

**Comment by AntonioCarlos1979** [comment]
Ok, pode encerrar a issue
