### ISSUE TITLE
Impressão 

### ISSUE THREAD

**Issue by darouca** [RamonSilva20/mapos#53]
Boa tarde,

Quando acesso uma venda e/ou OS e clico em imprimir, sai apenas o título na folha. Existe algo que eu possa fazer?

Obrigado.

**Comment by RamonSilva20** [comment]
Olá, vou alterar a forma como é impressa a OS, a forma atual fica com problemas quando os navegadores são atualizados. Grato.

**Comment by darouca** [comment]
Olá,
Obrigado pela resposta.

Existe algo que eu possa fazer pata reverter isso momentaneamente?

Obrigado.

**Comment by cleytonasa** [comment]
Conseguir resolver fazendo esses procedimentos.
https://github.com/RamonSilva20/mapos/issues/47

**Comment by darouca** [comment]
Opa. Farei esse teste assim que possível e posto um retorno. Obrigado.

**Comment by RamonSilva20** [comment]
Boa noite. A forma de impressão foi alterada na versão 3.1.7, espero ter solucionado o problema definitivamente.

**Comment by darouca** [comment]
Acabei de aplicar as novidades e funcionou perfeitamente bem.

Muito obrigado.
