### ISSUE TITLE
Aplicar icon de atualizar Stock na primeira pagina (Dashboard)

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#530]
Queria meter o icon para acrescentar Stock também na primeira pagina, quando se tem produtos abaixo de stock seria util estar logo na primeira pagina. 
Pode ajudar? 

Obrigado

**Comment by trollfalgar** [comment]
Feito novo commit `[ce72b85](https://github.com/RamonSilva20/mapos/pull/519/commits/ce72b85292c478a4c46ddb408307c75e35a0d2d6)`.

**Comment by LipzyLipzy** [comment]
Eu tenho 2 problemas. 
Não sei se lhe acontece, quando actualizo ele mantém a mesma quantidade que tinha.  
O outro problema que tenho, quando tenho produtos com baixa de stock ele prende no Dashboard, se clicar em serviços, OS etc não tem problema se tentar clicar em configurações logo de seguida não é possível. 

Obrigado

**Comment by trollfalgar** [comment]
> Eu tenho 2 problemas.
> Não sei se lhe acontece, quando actualizo ele mantém a mesma quantidade que tinha.
> O outro problema que tenho, quando tenho produtos com baixa de stock ele prende no Dashboard, se clicar em serviços, OS etc não tem problema se tentar clicar em configurações logo de seguida não é possível.
> 
> Obrigado

Você atualizou também o controller e a model?
Esse novo commit com a atualização de estoque pelo dashboard é apenas uma cópia do código presente no arquivo de produtos. Não alterei nada do meu último commit.
Todos os produtos com baixo estoque (cada produto tem opção de configurar o estoque mínimo), vai aparecer no dashboard automaticamente, e só vai sair se aumentar o a quantidade do estoque.

**Comment by LipzyLipzy** [comment]
Eu já estava a usar o seu ultimo commit. Só acrescentei.

**Comment by trollfalgar** [comment]
Eu reproduzi o passo a passo. E deu tudo certo, veja as imagens:

[Imgur - Passo a Passo](https://imgur.com/a/piBGkpo)

**Comment by LipzyLipzy** [comment]
tente actualizar sem aplicar valor. no meu esta aceitar e depois fico com stock a 0

**Comment by trollfalgar** [comment]
Eu esqueci de add a library do jQuery Valitate pra validação da quantidade [commit `d4bde33`]'.
Mas eu testei e permaneceu a mesma quantidade em estoque.

No controller você pode verificar que ele soma o estoque atual com os novos produtos. Ele não substitui o atual.

```
  $novoEstoque = $this->input->post('estoque');
  $estoqueAtual = $this->input->post('estoqueAtual');
  $estoque = $estoqueAtual + $novoEstoque;
```

**Comment by LipzyLipzy** [comment]
Esta tudo OK.
Revi tudo de novo e faltou uma linha no controller. 

Obrigado esta muito bom :)

**Comment by trollfalgar** [comment]
Perfeito o/

**Comment by acinformatica2004** [comment]
boa noite, alguém tem os arquivos modificados para me arrumar, pois tentei adicionar o código e não esta atualizando.
Obrigado

**Comment by trollfalgar** [comment]
> boa noite, alguém tem os arquivos modificados,, somente os de atualiza o estoque, para me arrumar, pois tentei adicionar o código e não esta atualizando.
> Obrigado

Você pode pegar o código na minha PR #519 
Tem várias coisas atualizadas lá.

**Comment by acinformatica2004** [comment]
> > boa noite, alguém tem os arquivos modificados,, somente os de atualiza o estoque, para me arrumar, pois tentei adicionar o código e não esta atualizando.
> > Obrigado
> 
> Você pode pegar o código na minha PR #519
> Tem várias coisas atualizadas lá.

Eu apenas fui adicionando o código modificado no meu código, porém sem sucesso. Se puder me arrumar apenas a atualização de estoque vai me ajudar bastante. Obrigado

**Comment by trollfalgar** [comment]
São todos os últimos 5 commits que estão no PR #519 .
Abre cada commit e você vai ver o que foi adicionado/alterado.

**Comment by trollfalgar** [comment]
@acinformatica2004 você pode pegar os arquivos no meu repositório:
[MAPOS](https://github.com/trollfalgar/mapos)

**Comment by acinformatica2004** [comment]
> @acinformatica2004 você pode pegar os arquivos no meu repositório:
> [MAPOS](https://github.com/trollfalgar/mapos)

Obrigado, vou pegar

**Comment by acinformatica2004** [comment]
Obrigado, funcionou perfeitamente

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
