### ISSUE TITLE
Problema no botão atualizar

### ISSUE THREAD

**Issue by crimat06** [RamonSilva20/mapos#531]
Em qualquer tela quando clico o botão azul "ATUALIZAR" vai pra tela branca e recebo a seguinte mensagem:

404 Page Not Found
The page you requested was not found.

Mas mesmo assim o que estou fazendo é gravado ou atualizado normalmente.

O que pode ser?

**Comment by diegoandrade93** [comment]
qual pagina voce está adicionando estes dados?

**Comment by crimat06** [comment]
Na verdade em todas, clientes, produtos e ordem de serviço...eu vou editar e quando clico em atualizar isso ocorre...

**Comment by diegoandrade93** [comment]
Me adiciona no whats (13) 991769615

**Comment by crimat06** [comment]
resolvido com a ajuda do amigo diegoandrade93!
