### ISSUE TITLE
Diferenciação de Tipo de Pessoa

### ISSUE THREAD

**Issue by Bremyarck** [RamonSilva20/mapos#532]
No cadastro de clientes o sistema não diferencia uma pessoa física de uma jurídica, mesmo se usar CNPJ o sistema sempre estará acusando como pessoa física.

**Comment by diegoandrade93** [comment]
a minha solução não é a melhor, mais pode te ajudar por enquanto...

na pasta controllers/clientes.php adicione abaixo da linha 80

$pessoa = '';
if(strlen($this->input->post('documento')) >= 15){ $pessoa = '2'; }else{ $pessoa = '1'; }

abaixo de 'documento' => set_value('documento'), adicione 'pessoa_fisica' => $pessoa,

agora quando for cnpj vai ficar 2 e quando for cpf vai ficar 1.

espero ter ajudado. valeu

**Comment by Bremyarck** [comment]
Muito obrigado sua logica é funcional, fechando a issue!

**Comment by diegoandrade93** [comment]
> Muito obrigado sua logica é funcional, fechando a issue!

Fico feliz em ajudar.
