### ISSUE TITLE
[Ajuda] Cadastro com Relacionamento de Tabelas

### ISSUE THREAD

**Issue by Bremyarck** [RamonSilva20/mapos#533]
Olá bom dia, estou usando o sistema MAPOS para uma oficina mecânica e estou adaptando o sistema para o mesmo, criei a categoria veículos com tudo que fosse necessário (controlador, modelo e visualização), já realizei o relacionamento de tabela no banco de dados veículos com cliente, mas me deparei com uma situação que na qual não consigo fazer um cadastro do veiculo relacionando com o  nome do cliente assim como foi feito em ordem de serviço para obter êxito.

[Imagem #1](https://user-images.githubusercontent.com/44008062/72220795-3494e980-3533-11ea-8aba-f59558c98b84.jpg)
[Imagem #2](https://user-images.githubusercontent.com/44008062/72220796-3494e980-3533-11ea-8ef7-f34d748c0b64.jpg)
[Imagem #3](https://user-images.githubusercontent.com/44008062/72220797-3494e980-3533-11ea-8e71-88f91678c06d.jpg)

**Comment by mmonzato** [comment]
conseguiu resolver ?

**Comment by Bremyarck** [comment]
> conseguiu Não consegui ainda

> conseguiu resolver ?

Infelismente não consegui ainda.

**Comment by mmonzato** [comment]
Para te ajudar vc precisa me mandar seus arquivos ou hospedar em algum lugar para eu dar uma olhada.

**Comment by Bremyarck** [comment]
_Aqui está -> https://mega.nz/#!ys5GzAAQ!I3LajxUYpKGZWzmGXT0ooWmPc1sJvf8rqH5vjhgSgPk
Me ajudando nessa questão futuramente posso ajudar a comunidade com mais recursos no sistema._

**Comment by mmonzato** [comment]
@Bremyarck eu preciso da sua base de dados para entender o problema, o sql que esta no zip que você mandou é da base de dados original do mapos.

**Comment by Bremyarck** [comment]
Aqui está o banco de dados -> https://mega.nz/#!OhJlDKBb!eEuaIRr1j3UCwm2TMhRZr9YHKDyvWDOXc_4MJtTFcQ4

**Comment by mmonzato** [comment]
substitui os arquivos da sua versão e verifica se é essa modificação que você precisava.
https://mega.nz/#!nIpjgQpL!vKbMFX-YPTciAkFkj9f11PLucluqwB9dljGiY6N2-R8

**Comment by Bremyarck** [comment]
Muito obrigado essa sua ajuda foi de extrema importância, será lembrado por isso, resolvi esse e vários outros problemas!
