### ISSUE TITLE
Gerar Código Barras automático ao criar novo produto

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#534]
Esta funcionalidade seria muito útil, será que alguém consegue criar? 
Já esta implementado a possibilidade de escrever o código barras, o problema é que é manual.
Manual podemos criar repetidos, a possibilidade de ter os 2 seria perfeito. 
E nunca aceitar repetidos.
Já procurei na net como fazer, já tentei mas não consegui nada :( 

Obrigado

**Comment by lrochawl** [comment]
Outra funcionalidade interessante seria nas etiquetas etiquetas geradas, ter a possibilidade de direcionar com um link apontando para o produto da etiqueta no sistema para que seja feita a manutenção do estoque direta e que o próprio sistema pudesse fazer a leitura dos códigos através da câmera de um dispositivo móvel ou webcam no computador

**Comment by TecSecret** [comment]
Na verdade como cada peça ou produto já tem um código de barras, na minha opinião então seria interessante só adicionar suporte a leitor de código de barras, pois ai vc vai saber exatamente a peça que vc tem em estoque.
