### ISSUE TITLE
Recibo de pagamento e cadastro de equipamento

### ISSUE THREAD

**Issue by BESystemInfo** [RamonSilva20/mapos#535]
Bom dia colegas. 
Primeiramente gostaria de agradecer ao Ramon e aos colaboradores pelo excelente projeto. 
Bem, eu não manjo nada de programação (ainda) e por isso gostaria de pedir ajuda de algum dos amigos. 
Eu queria tentar criar duas implementações. Uma delas seria uma função no financeiro, onde eu possa imprimir recibos de pagamento, preenchendo apenas a data, nome do cliente, valor, número da OS e forma de pagamento. Se tiver como fazer de forma automatizada já puxando os dados pelo número da OS seria ainda melhor, mas se tiver como apenas inserir essa opção com preenchimento manual já seria de grande valia. 
A segunda implementação, creio ser a mais complicada, seria adicionar uma ABA na OS onde eu possa preencher os dados do equipamento, como o Tipo (Notebook, Computador, Celular...), Marca, Modelo, Número de Série e Observações (Como fontes, capas, caixas...), e que esse menu pudesse ter uma opção de ser ou não impresso na OS. Essa implementação também poderia entrar no campo de pesquisa, onde se pudesse digitar o Número de Série, por exemplo, e já puxar todas as OS's daquele equipamento. Isso facilitaria bastante para manutenções de um único equipamento. Hoje utilizo o Map OS para serviços externos e o OSVendas da FPQSystem para manutenções de bancada e queria centralizar tudo no MapOS.

Se tiver alguma boa alma que possa me dar dicas de como fazer ao menos a implementação do recibo, já vai me quebrar um galhão.

Obrigado a todos.

**Comment by diegoandrade93** [comment]
ola, irei realizar as implementacoes e posto aqui pra te ajudar.

**Comment by diegoandrade93** [comment]
se puder explicar um pouco melhor sobre a segunda implementação ajudaria .

**Comment by BESystemInfo** [comment]
@diegoandrade93  Agradeço imensamente a ajuda.
Sobre a segunda implementação, seria algo assim: Hoje no MapOS, quando abrimos OS, existem 5 abas (Detalhes da OS, Produtos, Serviços, Anexos e Anotações). Gostaria de implementar uma aba chamada Equipamentos, onde eu pudesse adicionar os equipamentos do cliente em campos separados, informando, por exemplo, Tipo, Marca, Modelo, Número de Série e Acessórios. Essas informações também seriam salvas no banco de dados, de forma que, em uma necessidade, eu possa inserir na pesquisa das OS's o Número de Série, e me sejam retornadas apenas as OS's abertas para aquele equipamento. Eu não sei como poderia explicar, então fiz um modelo mais ou menos do que seria no Paint (https://imgur.com/JjuCtf4). 
Neste modelo, cada vez que eu clicasse no botão Adicionar, ele deveria inserir uma linha com os mesmos campos para cadastrar outro equipamento.
E também, se eu não preencher nada nesse campo, essa parte não sai na impressão da OS, mas se preencher, deveria sair a tabela.
Não sei se ficou bem claro, mas a idéia principal dessa implementação seria ter uma forma de pesquisar as OS's através do número de série de determinado equipamento, além das opções já existentes de por nome ou data. E também ajudaria a ter controle sobre os retornos.

Espero ter conseguido explicar e, mais uma vez, obrigado pela ajuda, esse recurso do recibo me faz uma falta danada.

**Comment by diegoandrade93** [comment]
mais ou menos assim?

https://www.imagemhost.com.br/image/NQMfG

**Comment by BESystemInfo** [comment]
Exatamente isso. Só faltou um campo para informar acessórios no final, mas é isso aí mesmo. Será que é possível pesquisar OS's através do número de série depois de salvo?
Mais uma vez muitíssimo obrigado, isso vai me ajudar imensamente.

**Comment by AntonioCarlos1979** [comment]
Seria interessante o @RamonSilva20  integrar as funcionalidade da issue #460 e #530  implementadas pelo @trollfalgar e esta à versão oficial... ajudará a todos

**Comment by giovanne-oliveira** [comment]
@diegoandrade93 A funcionalidade já foi implementada ou foi somente a interface? Vi que no banco já existe uma tabela com o nome "equipamentos", mas a função não existe no código.

**Comment by diegoandrade93** [comment]
a função estava para ser implementada, mais parece apenas ter as tabelas mesmo, eu fiz a implementação, só estou finalizando, ela semana foi corrido para mim.

**Comment by TecSecret** [comment]
@diegoandrade93  você pode compartilhar a implementação que você fez?

Abraços

**Comment by mmonzato** [comment]
@TecSecret você não estava desenvolvendo uma customização do mapos ? parou com a implementação ?

**Comment by TecSecret** [comment]
Bom dia @mmonzato devido a problemas financeiros e pessoais tive que abandonar a customização e outros projetos grátis. 
Mas já está programado para o final de fevereiro/2020  contribuir com a comunidade novamente, pois vai ter inclusive hospedagem free do Mapos para quem quiser e muitas outras coisas novas.

**Comment by willph** [comment]
Adicionado o recibo para impressora não fiscal em OS e Vendas no Pull Request #515

**Comment by BESystemInfo** [comment]
@willph Grande implementação essa sua, vai ajudar bastante. Vi no grupo do Whatsapp que você enviou uma foto desse recibo para impressora não fiscal. Hoje eu utilizo esse site (https://www.reciboonline.com.br/recibo-prestacao-de-servico) para a criação dos recibos, porém em formato A4 (Sou autônomo e não tenho impressora térmica). É possível fazer algo parecido com o que você fez, porém com as escritas como saem nesse do site e em formato A4?

**Comment by willph** [comment]
> @willph Grande implementação essa sua, vai ajudar bastante. Vi no grupo do Whatsapp que você enviou uma foto desse recibo para impressora não fiscal. Hoje eu utilizo esse site (https://www.reciboonline.com.br/recibo-prestacao-de-servico) para a criação dos recibos, porém em formato A4 (Sou autônomo e não tenho impressora térmica). É possível fazer algo parecido com o que você fez, porém com as escritas como saem nesse do site e em formato A4?

Eu usei impressora térmica via Bluetooth.
Aquelas simples que vende no mercadolivre
Creio que qualquer impressora térmica funcione.
Apenas não testei em outros equipamentos.

**Comment by willph** [comment]
Vi recibo de pagamento, mas não foi dito se era em térmica não fiscal ou em A4. Fiz em cupom não fiscal kkkkk

Quando estiver com tempo analiso. 👍

**Comment by BESystemInfo** [comment]
Bom dia. 

Apenas como complemento, buscando aqui alguma forma de criar o recibo, encontrei esse projeto:
https://github.com/andrebalen/recibo2pdf
É basicamente esse tipo de recibo que eu queria implementar, porém de forma automatizada. Pensei em um botão junto ao Editar e Excluir lançamento, na parte financeira, onde eu clicando ele já criasse o PDF mais ou menos no modelo desse projeto acima, porém preenchendo os dados automaticamente com os dados da OS (O número do recibo pode ser o mesmo número da OS ou do registro de venda do financeiro).

Mais uma vez obrigado.

**Comment by eduaraujothe** [comment]
Pessoal eu vejo que seria interessante gerar o recibo automático sempre que a OS for marcada como faturada. E os dados do recibo pegos da OS faturada.

**Comment by chico24hs** [comment]
Gostaria de saber se tem cadastro de equipamento tipo: DESKTOP, NOTEBOOK, MARCA, MODELO, SERIE, OUTROS e etc... Mapos falta cadastro de equipamento

**Comment by xadun** [comment]
A implementação para equipamentos não será realizada de forma oficial? Alguém pode compartilhar a implementação?

**Comment by Pr3d4dor** [comment]
@xadun Verifique: https://github.com/RamonSilva20/mapos/issues/847#issuecomment-659431796

**Comment by andreptu** [comment]
**Pago o trampo!** Desculpe esta comentando aqui! mais alguém que entenda de programação de JAVA, gostaria de fazer **engenharia revessa de um APK aplicativo andoid, para fins de estudo, ja **consegui fazer 90%** porem tem uma pasta especific**a **S3DMain.smf** que não consigo por nada!

Andre Diniz (38) 99994-0410

**Comment by andreptu** [comment]
> Bom dia colegas.
> Primeiramente gostaria de agradecer ao Ramon e aos colaboradores pelo excelente projeto.
> Bem, eu não manjo nada de programação (ainda) e por isso gostaria de pedir ajuda de algum dos amigos.
> Eu queria tentar criar duas implementações. Uma delas seria uma função no financeiro, onde eu possa imprimir recibos de pagamento, preenchendo apenas a data, nome do cliente, valor, número da OS e forma de pagamento. Se tiver como fazer de forma automatizada já puxando os dados pelo número da OS seria ainda melhor, mas se tiver como apenas inserir essa opção com preenchimento manual já seria de grande valia.
> A segunda implementação, creio ser a mais complicada, seria adicionar uma ABA na OS onde eu possa preencher os dados do equipamento, como o Tipo (Notebook, Computador, Celular...), Marca, Modelo, Número de Série e Observações (Como fontes, capas, caixas...), e que esse menu pudesse ter uma opção de ser ou não impresso na OS. Essa implementação também poderia entrar no campo de pesquisa, onde se pudesse digitar o Número de Série, por exemplo, e já puxar todas as OS's daquele equipamento. Isso facilitaria bastante para manutenções de um único equipamento. Hoje utilizo o Map OS para serviços externos e o OSVendas da FPQSystem para manutenções de bancada e queria centralizar tudo no MapOS.
> 
> Se tiver alguma boa alma que possa me dar dicas de como fazer ao menos a implementação do recibo, já vai me quebrar um galhão.
> 
> Obrigado a todos.

Também tenho muito interesse em um aplicativo assim! de descobrir algum MAPOS com mais opções me avise, ficarei muito feliz!

**Comment by FlaviusR** [comment]
Olá. Eu vi que a função de 'equipamentos' não foi implementada ainda. mas, vi que existe uma tabela de 'equipamentos' e 'equipamentos_os', e suas FK linkadas com a OS e CLIENTES.
Acho que também poderia servir ao invés de equipamentos, utilizar para veículos, como se foss euma oficina mecanica,  o que acham? Quero colaborar.
