### ISSUE TITLE
D E S C A S O S 

### ISSUE THREAD

**Issue by TatianeVila** [RamonSilva20/mapos#537]
Já vi que o pessoal falou que o mapos é gratuito e aberto pra quem quer alterá-lo, mas o problema que vejo é que tem muita gente aqui que quer fazer parte do quadro de contribuidores e na verdade não acrescenta merda nenhuma! O único é um tal de Wilmerson que fez varias contribuições. A grande desculpa da maioria é "temos atividades particulares" e deixa de lado seu compromisso para com o sistema, ahhh, me perdoem mas parem de hipocrisia, querem alimentar o ego de ter o nome como apoiador/contribuidor/desenvolvedor do sistema? então façam algo ou vazem! pois quem realmente utiliza o sistema e gostaria de vê-lo melhorado e infelizmente não tem conhecimento para contribuir, fica a mercê da "boa vontade" desses egocêntricos! 
Sei mexer muito bem no sistema, ja fiz pequenas implementações para uso particular, mas não me sobra tempo para ajudar aqui, então eu tenho o bom senso de não me candidatar à equipe. Olhem as solicitações que ja fizeram, coisas relativamente simples e ninguém coça  a bunda pra ajudar! tem dois, talvez três que realmente aparecem aqui tentando fazer a diferença e ajudar o próximo. Façam algo útil e vejam as solicitações ou abandonem a equipe! Tem muitas issues abandonadas que ninguém respondeu ou prometeram algo e depois abandonaram e que eu contactei o user e ajudei com a dificuldade. Vocês não perceberam a proporção que o projeto tomou e continuam agindo com o pensamento pequeno! Só lamento...
Podem me xingar ou o que quiserem, ou melhor, demonstrem aqui o que realmente são! ou então não falem nada, como sinal de indiferença que já estão acostumados a fazer com muitos. Daqui alguns dias fecharei esta issue mas que a mensagem se grave na mente de vocês!!

**Comment by Pr3d4dor** [comment]
Olha, eu entendo a sua frustação mas eu acredito que ela não é justificada porque não existe uma "equipe" de desenvolvedores responsáveis. 

A definição de código aberto é a seguinte: É um modelo de desenvolvimento, que promove o licenciamento livre para o design ou esquematização de um produto, e a redistribuição universal desses, com a possibilidade de livre consulta, examinação ou modificação do produto, sem a necessidade de pagar uma licença comercial, promovendo um modelo colaborativo de produção intelectual.

Portanto a "equipe" é composta por todos nós utilizadores do mapos, onde qualquer um pode melhorá-lo fazendo sua contribuição. 

Você fala que usam a desculpa de "atividades particulares" mas você mesmo citou que nunca fez uma colaboração com o código pois "não sobra tempo para ajudar". Não existe uma equipe responsável, pois como eu disse anteriormente, qualquer um pode fazer contribuições para melhorar o código.

**Comment by TatianeVila** [comment]
Bom dia, grata pelo retorno e conotação da resposta. Entendo bem o significado de código aberto e não estou frustrada com o o sistema (nem de longe) ou a "equipe" mas sim desapontada, acho não ter me expressado de acordo pois fiquei um tanto nervosa ao redigir já esperando respostas já costumo ver em fóruns por aí. 
Deixa expor melhor, aqui sim existe uma "equipe" de colaboradores e veja só, o desapontamento se dá com a indiferença, (sei que é forte mas não que termo usar)  que estes colaboradores tem para com aqueles que não entendem de programação e PRECISAM de alterações para ajudar no seu dia a dia. Tambem sei que tal colabores não tem nenhuma obrigação, mas veja o que digo, ao assumir um problema como implementação, você assume um compromisso com o usuário e aqui tem 23 issues como request e isso desde 2018, sei que algumas ja foram atendidas e o solicitante não encerrou, porém outras nem sequer foram implementadas. Quanto ao meu conhecimento, não é nada que agregue aqui, pois faço poucas coisas. 
Só acho que as 15 pessoas que aparecem no final da pagina como colaboradores, se for como colaborador do projeto e não financeiro, podem revisar as issues e tentar ajudar ativamente pois como disse anteriormente, o MAPOS já tomou uma proporção enorme muita gente pode se beneficiar com ele (ja que é esta a intensão). 
Tem um amigo meu que está ajudando aqui, ativamente e por este motivo resolvi encher o saco de voces.
Não me entenda mal, não quero impor nada, apenas que as necessidades sejam atendidas para que quem precisa e tenha sua necessidade atendida. Minha intensão não é ser ofensiva e sim incisiva!
Grata

**Comment by Pr3d4dor** [comment]
A lista de colaboradores no final da página foi feita pelo criador Ramon. Nessa lista ele colocou todas as pessoas que fizeram alguma contribuíção para o sistema. Mas isso não quer dizer que todo mundo que fez uma contribuição terá que ficar responsabilizado por manter o sistema. Creio que deveria ser usado o bom senso.

Eu mesmo já realizei algumas implementações e eu tento responder issues sempre que posso. Algumas issues eu não respondo justamente porque não tenho nada para acrescentar que venha ajudar a encontrar a solução. Existem várias issues que não tem a ver com o código do mapos mas sim com a hospedagem e etc. Na minha opinião as issues deveriam somente ser referentes ao código como novas features, correção de bugs e etc.

Existe também um grupo do mapos no WhatsApp onde lá muitas pessoas se ajudam e compartilham melhorias e correções, mas muitas sempre essas pessoas não fazem PR's com a implementação e juntar isso ao código do mapos. Várias pessoas também precisam de coisas muito específicas, então nesse ponto eu creio que na hora de ser implementado no mapos deveria ser implementado do modo mais genérico possível para tentar atenter o máximo de casos possíveis.

Talvez você não concorde com minha opinião. Resumindo creio que dúvidas específicas e que não sejam muito relacionadas ao mapos deveriam ser esclarecidas no grupo do WhatsApp. Assim as issues aqui do repositório seriam somente referentes ao código do mapos em si.

Todo pedido de feature deve ser analisado, pois nem sempre é viável, ou é só para um caso bem específico. Essa questão de "PRECISAR" da implementação é complicada pois creio que todo mundo aqui tem seu emprego e não recebe nenhum retorno financeiro para manter o mapos. Tudo isso está relacionado ao modelo de sustentabilidade do código aberto que foi bem discutido nesse artigo: https://www.vice.com/en_us/article/43zak3/the-internet-was-built-on-the-free-labor-of-open-source-developers-is-that-sustainable

**Comment by BESystemInfo** [comment]
Eu não gosto muito de me envolver nessas discussões, mas como estou recebendo essas notificações, me vi na responsabilidade de adentrar. 
Entendo o ponto de vista da amiga Tatiane, mas concordo com o o colega Pred4d0r que a indignação é injustificada. 
Eu não entendo nada de programação, mas utilizo o sistema já há um bom tempo. Tive diversas necessidades e as duas que julguei mais importantes cheguei a solicitar aqui no fórum. A primeira vez não fui atendido, mas na segunda, um colega se propôs a fazer as alterações. 
Porém não cobro, pois entendo que, uma vez que o sistema seja código aberto e gratuíto, se eu tenho NECESSIDADE de uma função, cabe a mim correr atrás da implementação, seja aprendendo a fazê-la ou pagando alguém que o saiba. E entendo também que aqueles que se propõe a ajudar, não tem obrigação de fazê-lo. Imprevistos acontecem e cada um tem sua própria vida para viver.
No meu entender, uma vez que o sistema é livre e seu código pode ser alterado sem ônus ao desenvolvedor, eu não posso exigir, nem dele e nem das pessoas que o ajudam, que minha necessidade seja atendida. Posso até solicitar sua ajuda, mas não exigir que a mesma seja dada (Isso na minha visão como leigo).
Até compreendo a frustração da amiga, mas creio que, como disse o amigo abaixo, vale aqui o bom senso de entender que, uma vez que eu crio algo e disponibilizo de forma integral, não tenho responsabilidade sobre modificações e necessidades dos outros (salvo se eu cobro por isso). 
Estou fazendo cursos de programação justamente para tentar entender e fazer as modificações conforme necessitar, e quem sabe futuramente contribuir com o projeto, mas por hora, conto apenas com a colaboração, conforme disponibilidade, dos colegas aqui da comunidade. 
Desculpe me envolver, mas creio que esta discussão também não agrega nada ao projeto, apenas infla as issues que não são realmente solicitações. 

Abraços aos amigos.

**Comment by TecSecret** [comment]
Boa noite, 

Não querendo me envolver, mas assim se a colega acima fez uma modificação no sistema dela, compartilha como um pull request, o mesmo será analisado por alguém e testado. 

Mesmo sendo uma contribuição mínima, se for compartilhada vai beneficiar a comunidade.

Quando ao grupo do WhatsAPP @Pr3d4dor você pode fornecer o link.


Lembre-se cada um tem sua vida.

**Comment by giovanne-oliveira** [comment]
@Pr3d4dor Gostaria de participar desse grupo de WhatsApp.

**Comment by willph** [comment]
https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

Pra quem quiser :D

**Comment by TecSecret** [comment]
Obrigado pelo envio @willph

**Comment by willph** [comment]
De nada :+1:

**Comment by willph** [comment]
Pelo que eu entende, o intuito desta postagem se resume em **da uma sacudida na equipe**. E  um desabafo  pessoal.

Agora se surtiu efeito eu não sei :grin:

**Comment by Bremyarck** [comment]
_Aproveitando a questão sinceramente todos que estão aqui presente querem se beneficiar, portanto continuamos a manter o foco no que realmente interessa em vez de abrir issue pra "sacudir a equipe" vamos cada um contribuir com que puder, como já foi dito não tem equipe responsável, se não tem responsabilidade não terá obrigação, mas temos que ter a ética de ajudar uns aos outros._

**Comment by heliocristaldo** [comment]
Resumindo o conteúdo, acho que essa questão de um ajudar o outro é furada, digo por mim que não entendo muito mas me dedico ao mapos para fins de uso próprio sem intuito de qualquer fins lucrativos, o pessoal só me procura no Whatsapp e Telegran para pedir algo pronto, ninguém procura para discutir códigos ou ideias daquilo que alguém tenha duvidas, ou esteja fazendo errado. Mas gostei do conteúdo desse tópico, retrata um poucos os meus pensamentos.

**Comment by mariolucasdev** [comment]
@Bremyarck isso mesmo, o que temos aqui em comum fora esse que não contribuem em nada, e ainda reclamam dos que contribuem é o desejo de colaborar e melhora essa excelente iniciativa que é o mapOs. Quem quiser desenvolvedores trabalhando em tempo integral para satisfazer seus fins lucrativos, pague! Quem não tiver disposto tem que aguardar.

@TatianeVila quanto a seu discurso a única hipocresia que pode se notar é uma exigência nesse tom vindo de quem não contribuiu em nada até o momento. 

Aos demais que publicam issues "relevantes" obrigado por tudo e como contribuidor digo o mesmo que o @Pr3d4dor estamos sempre vendo e a medida do possível melhorando esse software porque acreditamos nessa iniciativa.

E repito quem quiser exigir velocidade no desenvolvimento e regras específicas que fujam do contexto do sistema, é só contratar um desenvolvedor.
