### ISSUE TITLE
qual xamp usa a nova verção do mapos

### ISSUE THREAD

**Issue by Jefeson0171** [RamonSilva20/mapos#538]

**Comment by Bremyarck** [comment]
_O xampp é um programa que tem como base realizar a emulação do sistema mapos escrita com a principal linguagem em php, recomendo que leia o artigo abaixo para melhor entendimento._

[https://pt.wikipedia.org/wiki/XAMPP](url)

**Comment by willph** [comment]
Eu uso a versão XAMPP for Windows 7.3.1.
Mas você pode testar a versão mais recente, antes de instalar o de forma definitiva. 😀

**Comment by TecSecret** [comment]
Boa tarde, qualquer versão, desde que suporte todos os requisitos do sistema.

**Comment by Bremyarck** [comment]
_Recomendo sempre usar a versão do xampp mais recente e atende a todos os requisitos encontrada no site oficial disponível em https://www.apachefriends.org/pt_br/download.html_

_Lembrando que o uso do xampp dispensa hospedagem online e depois de instalar o programa terá que instalar e executar os serviços desejados conforme sua necessidade._

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
