### ISSUE TITLE
Problemas para anexar arquivos na OS

### ISSUE THREAD

**Issue by pkrename** [RamonSilva20/mapos#54]
Boa tarde galera, estou com problemas para anexar arquivos junto com a OS, a minha ideia é colocar foto juntamente com a OS... será um problema de permissões? ele apresenta somente o erro "Atenção! Nenhum arquivo foi anexado."
Obrigado desde já

**Comment by RamonSilva20** [comment]
Olá. Verifique se as pastas anexos e arquivos dentro de assets estão com permissão de escrita.

**Comment by pkrename** [comment]
estão sim... ja deixei até com permissão de mais... ta com 0777 para usuario apache....
mas mesmo assim o problema persiste
Obrigado pela atenção Ramon

**Comment by drelldeveloper** [comment]
@pkrename Você conseguiu resolver seu problema?

**Comment by Henrique-Miranda** [comment]
Tive o mesmo problema, bastou adicionar permissão na pasta thumbs e foi solucionado.
que está em /mapos/assets/anexos/thumbs/

**Comment by RicardoPires20** [comment]
No teste local deu certo mas na cloud nao alguem pode me ajudar ?
