### ISSUE TITLE
Meios de Pagamento boleto/ cartão

### ISSUE THREAD

**Issue by melque123** [RamonSilva20/mapos#541]
Será que alguem consegue colocar um desses modulos gratis pagseguro, paghiper, mercado pago, etc... para que quando fizer a ordem de serviço o cliente já possa pagar? emitir boleto ou enviar um link para pagamento, seria bem legal e util.

**Comment by willph** [comment]
To vendo essa questão.
Só vai demorar um pouco. 👍

**Comment by TecSecret** [comment]
Boa tarde. Parece que teve um colega no grupo do whatsapp que já implementou o mercado pago.

**Comment by Claudiomfa** [comment]
Há possibilidade de implementar método de pagamento pelo ebay?

**Comment by ADMTec** [comment]
como faço para entra no grupo de whatsapp

**Comment by willph** [comment]
https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
