### ISSUE TITLE
Esta faltando os campos Quantidade e Preço, Na area de cliente

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#543]
![falta 2 campos](https://user-images.githubusercontent.com/60369684/73221915-cbbb8d00-4140-11ea-9249-82064d187935.jpg)

Na area de cliente esta faltando 2 campos, só tem campo serviço e sub-total, esta faltando  os campos Quantidade  e Preço.  Principalmente o campo quantidade faz toda a diferença.

Como faz pra por esses 2 campos ?

**Comment by Bremyarck** [comment]
_Olá parceiro essa questão já foi resolvida, você esta usando uma versão antiga do sistema, utilize essa versão mais recente se for assim do seu agrado. caso tenha resolvido favor feche essa questão._

https://github.com/RamonSilva20/mapos/archive/master.zip

**Comment by cftvseginfo** [comment]
Eu estou usando a versão 3.14.2

**Comment by cftvseginfo** [comment]
Olá, testei essa versão , que me enviou , esta a mesma coisa, é a mesma versão

**Comment by mmonzato** [comment]
@cftvseginfo vc já limpou o cache do seu navegador ? porque a versão 3.14.2 que você diz estar usando já possui esses campos. Você fez uma instalação limpa ou substituiu os arquivos ?

**Comment by cftvseginfo** [comment]
eu fiz instalação nova, no meu não aparece, só aparece quando eu faço a OS, mas se o cliente entrar pela area de cliente, ese campos Quantidade e Preço, como mostra a imagem que mostrei.

**Comment by mmonzato** [comment]
@cftvseginfo só substituir pelo arquivo que vou deixar o link:

https://mega.nz/#!vEpBmIbC!jhmjlkcetVLdk7MasBhVsDYEZ_PJjrAO-S5iniVHE_M

**Comment by cftvseginfo** [comment]
tem como mostrar o seu print , aparecendo esses 2 campos na area de cliente ?

**Comment by mmonzato** [comment]
@cftvseginfo como eu disse na mensagem anterior vc tem que baixar o arquivo que disponibilizei para esses campos aparecerem, eles realmente não eram exibidos.

![image](https://user-images.githubusercontent.com/55327526/73575131-4133a000-4456-11ea-8695-58626849e4a7.png)

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73575762-a1771180-4457-11ea-884d-a941769ec01d.png)
apareceu somente não apareceu o acamento da linha abaixo, e tambem não foi contabilizado na OS final, que o cliente ver, perceba na imagem abaixo.
![image](https://user-images.githubusercontent.com/60369684/73575925-fa46aa00-4457-11ea-9559-78af9450bf22.png)

**Comment by mmonzato** [comment]
@cftvseginfo baixe esses arquivos e atualiza:

https://mega.nz/#!qUZwBACD!rxj-enx41-BJs9lucUd2GNhZ4ir_jgpjAwinpLTkDhg

**Comment by cftvseginfo** [comment]
Show, perfeito, tudo funcionando

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
