### ISSUE TITLE
Verificação de Código

### ISSUE THREAD

**Issue by Claudiomfa** [RamonSilva20/mapos#544]
Boa tarde,

Preciso de fazer uma adaptação no mapos, o que queria era uma forma de fazer uma verificação de um código introduzido com o código na base de dados (campo randcode) que foi gerado aleatoriamente quando foi criado a ordem de serviço.

1º na abertura de uma nova OS o código php gera um código aleatório de 6 dígitos, este é gravado no campo randcode na tabela OS.
2º na impressão térmica (que é o talão que é entregue ao cliente no momento da abertura da OS) vai esse mesmo código visível.
3º no momento do cliente vir levantar o equipamento, este trás o talão (que foi entregue na abertura da OS) e quando vamos facturar a OS, devemos introduzir o código (que está no talão do cliente) num campo e o php deveria verificar se o código introduzido é o mesmo que esta gravado na base de dados. Caso a o código seja igual, o mapos deixa facturar a OS. Caso seja diferente, o mapos deveria rejeitar a facturação.

Isto para controle de saída dos equipamentos da assistência técnica.

**Comment by giovanne-oliveira** [comment]
Função interessante, mas não sei se tem aplicabilidade prática para um modelo geral de negócio. Não é muito complexo de fazer...

**Comment by TecSecret** [comment]
Essa função é interessante. Mas não tem muito aplicação a nível de mercado, pois o controle normalmente jé é feito via OS  na assistência.

**Comment by Claudiomfa** [comment]
Alguém me consegue ajudar a criar o código de verificação. Já tenho os campos na base de dados e a programação php para gerar o código aleatório. Apenas me falta alterar a parte de facturar para comparar o código introduzido com o código gravado na base de dados

**Comment by LipzyLipzy** [comment]
Ola, eu pretendo gerar o numero para o codigo de barras tal como fez. Pode partilhar esta parte do gerar o codigo aleatorio? Obrigado

**Comment by Claudiomfa** [comment]
Aqui tem o codigo de barra aleatorio.
Altere conforme a sua nexessidade.

[codDeBarra_Automatico_Manuel.zip](https://github.com/RamonSilva20/mapos/files/4134161/codDeBarra_Automatico_Manuel.zip)

**Comment by LipzyLipzy** [comment]
Muito Obrigado pela partilha.
Já alterei o meu código, ate ficou melhor do que tinha pensado em fazer.

Obrigado

**Comment by mmonzato** [comment]
@Claudiomfa me manda a versão que vc está utilizando e o banco de dados que vou te ajudar a implementar.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
