### ISSUE TITLE
sistema de tickets

### ISSUE THREAD

**Issue by gustavooller** [RamonSilva20/mapos#545]
existe algum plano de implementação?
att

**Comment by Pr3d4dor** [comment]
O que você quer dizer exatamente com "sistema de tickets"?

**Comment by vinnyparker** [comment]
ele n se referiu a tickets de atendimento nao?

**Comment by gustavooller** [comment]
exato... como se fosse um suporte de atendimento

**Comment by Pr3d4dor** [comment]
Você precisa ser mais específico e detalhar exatamente o que você precisa. Assim alguém poderá implementar, somente com uma definição vaga de "sistema de tickets" ele pode ser implementado de muitas maneiras.

**Comment by gustavooller** [comment]
sistema de tickets de helpdesk, ou tickets de suporte, ou tickets de atendimento...
