### ISSUE TITLE
Sugestão - Produto e relatorio

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#546]
Alguem teria um codigo pra adicionar mais um campo chamado CATEGORIA, na parte onde se adiciona o PRODUTOS.

E no relatorio poderia ter uma lista dos PRODUTOS por CATEGORIA em ordem alfabética.

**Comment by Pr3d4dor** [comment]
Isso poderia ser implementado, vou adicionar a label correspondente.
