### ISSUE TITLE
Como aumentar a capacidade de caracteres nesse campo , na parte de adicionar produtos

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#547]
![image](https://user-images.githubusercontent.com/60369684/73595499-303b6b00-44f8-11ea-9051-536dc4eb0c85.png)

**Comment by Claudiomfa** [comment]
Tem de ser diretamente na base de dados. tabela produtos, em estrutura da tabela editar o campo descricao e alterar o valor de 80 para o valor de caracteres que necessitam.

**Comment by cftvseginfo** [comment]
Ola´poderia me dizer o passo a passo, aonde eu encontro essa tabela?

**Comment by Claudiomfa** [comment]
Tens de utilizar o phpmyadmin para executar esses passos

**Comment by cftvseginfo** [comment]
eu  uso hostgator

**Comment by cftvseginfo** [comment]
entrei aqui, aonde eu iria agora 
![image](https://user-images.githubusercontent.com/60369684/73597193-3d605600-4508-11ea-8c02-a8b74d9ff306.png)

**Comment by Claudiomfa** [comment]
Abra a base de dados "vander"

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73597236-9c25cf80-4508-11ea-9123-d36d13a9e094.png)

**Comment by Claudiomfa** [comment]
seleccione a tabela produtos

**Comment by cftvseginfo** [comment]
mas tem 2 ali

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73597268-d8593000-4508-11ea-9494-ac04230e2218.png)

**Comment by Claudiomfa** [comment]
Só a que diz servicos

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73597287-0a6a9200-4509-11ea-9610-efbb83a16c35.png)

**Comment by Claudiomfa** [comment]
agora em cima ao lado de "procurar" seleccione "estutura"

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73597317-5e757680-4509-11ea-92ab-53ef4715fb20.png)

**Comment by Claudiomfa** [comment]
clique em "Mude" na linha do "nome"

**Comment by cftvseginfo** [comment]
![image](https://user-images.githubusercontent.com/60369684/73597336-a5636c00-4509-11ea-9b24-f5f3a243e660.png)

**Comment by Claudiomfa** [comment]
Agora é so alterar a campo "Tamanho/Valores" para o valor que desejar. O valor é o nr de caracteres. Depois é só guardar

**Comment by cftvseginfo** [comment]
sabe qual é o maximo permitidow

**Comment by Claudiomfa** [comment]
O máximo permitido é o que você lá colocar se colocar 1000 ou 2000 é o limite imposto por sí

**Comment by cftvseginfo** [comment]
Show, valeu funcionou, agradecido

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
