### ISSUE TITLE
Como aumentar a listagem aqui

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#548]
![image](https://user-images.githubusercontent.com/60369684/73599140-f0d44500-451e-11ea-9080-9c73b4bb7734.png)

esta aprecendo 5 linhas , como mudar pra aparecer 20 linhas

**Comment by Pr3d4dor** [comment]
Nessa linha: https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php#L245, mude o número 5 para a quantidade que desejar.

**Comment by cftvseginfo** [comment]
Olá deu certo, e nessa parte aonde é que aumenta
![image](https://user-images.githubusercontent.com/60369684/73611025-71954e80-45bc-11ea-8607-2b6fc1800b72.png)

**Comment by Pr3d4dor** [comment]
Esse campo nome não é um campo de autocomplete, está aparecendo essas opções pois você já cadastrou esses serviços e próprio autocomplete do navegador mostra.

**Comment by cftvseginfo** [comment]
OK, agradecido
