### ISSUE TITLE
Criar lista de compras.

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#549]
Pretendo criar uma lista de compras. 
Só que não estou a perceber como o vou fazer.
A parte da imagem aproveitei o das vendas. 
![Compras](https://user-images.githubusercontent.com/49565606/73857645-2040c580-482f-11ea-93d0-fba69b2b7c15.jpg)
Queria do mesmo género. Onde escrevo nome do produto o preço e quantidade, vou somando produtos. Para depois encomendar (produtos novos que não existe no stock) iria dar entrada mais tarde quando receber a encomenda.
Já tive a tentar mas nem consegui meter aceitar produtos e não consegui perceber a lógica de como vai guardar o nome dos produtos e o preço. 
Alguém pode dar uma ajuda?

Obrigado

**Comment by mmonzato** [comment]
https://github.com/rodrigoedu13/mapos-infotech

**Comment by LipzyLipzy** [comment]
Sim eu segui essa lógica. e esta tudo a trabalhar. 
O único problema é que é individual. Se quiser fazer como lista não consigo. 
Por exemplo tenho de comprar 5 produtos ao mesmo fornecedor, vou ter de criar 5 vezes. 
O que pretendo é criar lista para o mesmo fornecedor que pode conter vários produtos. 

Obrigado

**Comment by mmonzato** [comment]
@LipzyLipzy vc esta adaptando para controle de componentes eletrônicos ?

**Comment by LipzyLipzy** [comment]
Isso mesmo. Estou a fazer os possiveis.

**Comment by Pr3d4dor** [comment]
Parece que o problema foi resolvido e com isso vou fechar a issue.

Caso ainda precise de ajuda pode ainda comentar.
