### ISSUE TITLE
Excluir Permissão

### ISSUE THREAD

**Issue by paulinhowoox** [RamonSilva20/mapos#55]
Boa tarde! A função de excluir permissões está errada, está apontando para serviços, tanto da branch master como na dev, na master a função é excluir e na dev é desativar, eu acabei de baixar e modifiquei para desativar porque achei mais correto! É isso, abraço.

**Comment by marcus2vinicius** [comment]
Olá @paulinhowoox poderia por gentileza enviar o pull request das suas alterações assim sua contribuição ficará marcada no projeto.
Obrigado

**Comment by paulinhowoox** [comment]
Ok, assim que possivel eu envio a PR
