### ISSUE TITLE
Product Search box

### ISSUE THREAD

**Issue by RuiPereira70** [RamonSilva20/mapos#550]
Boa Tarde
Seria possivel ajudar-me numa duvida?
Gostaria de colocar uma barra de deslocação Vertical ou poder aumentar o numero de artigos do autocomplete quanto estou a adicionar artigos nas Ordens de Serviço.
Ao colocar as 2 ou mais primeiras letras só mostra uma caixa de 5 Produtos, e no caso por vezes são dezenas, por isso a barra seria muito util.
Poderia orientar-me onde devo alterar?
Cumprimentos
Rui Pereira

**Comment by mmonzato** [comment]
@RuiPereira70 você precisa alterar o seguinte arquivo application\models\Os_model.php
Procure pela função  "public function autoCompleteProduto($q)" e edite a linha "$this->db->limit(5);" onde 5 é a quantidade que foi definida.
