### ISSUE TITLE
Contratos de Mensalidades, é possível?

### ISSUE THREAD

**Issue by brunaomessias** [RamonSilva20/mapos#551]
Olá pessoal, eu sou novo no github e ví que que tem bastante ajuda aqui relacionadas ao script.
Queria saber se é possível criar a função para clientes de contratos que gera o lançamento de contas a receber automático, históricos de atendimentos, anexar contrato.. etc. 
O que acham?

**Comment by Pr3d4dor** [comment]
É possível, mas acho que talvez essa customização seria mais útil somente no seu caso.

Se puder formular uma descrição detalhada de como isso deveria ser implementado ficaria melhor.

Vou fechar a issue apenas para controle mas pode comentar aqui mesmo.
