### ISSUE TITLE
Erro ao acessar barra azul

### ISSUE THREAD

**Issue by gilbertoalmeida16** [RamonSilva20/mapos#552]
Olá pessoal conseguiram corrigir o erro que ao logar não entra no sistema fica com a barra azul ..

**Comment by brunaomessias** [comment]
Olá Gilberto, eu baixei, instalei e ta tudo funcionando.

**Comment by TecSecret** [comment]
Esse é um problema que até agora não tem uma solução definitiva.

**Comment by RamonSilva20** [comment]
Olá, nas versões anteriores do sistema e antes de fazer atualização do framework, deixando o sistema em modo de desenvolvimento ao efetuar login o sistema emitia um warning deprecated, atrapalhando a resposta em json, o sistema não funciona adequadamente. Faça a atualização do sistema quando possível.
