### ISSUE TITLE
Update de Banco de Dados

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#554]
Olá a todos.

Na pasta Updates, existem 8 scripts para serem usados para fazermos a atualização. Estão citados abaixo:

> update_v2_to_v3.sql
> update_v3.1.x_to_3.1.9.sql
> update_v3.1.9_to_3.2.x.sql
> update_v3.3.x_to_3.4.x.sql
> update_3.6.0.sql
> update_3.7.0.sql
> update_3.9_to_3.10.sql
> update_3.12_to_3.14.sql

Pessoal, estou saindo da versão 3.1.14 e instalando a versão mais atual que é a 3.14.2.

Tenho 2 perguntas:

1) Como executar esses scripts? Via PHPMyAdmin? FTP? Não entendi como fazer isso. 

2) Qual a sequencia lógica que devo seguir para migrar o banco de dados de forma correta?

Entendo que seria executando os scripts na ordem abaixo:

> update_v3.1.x_to_3.1.9.sql
> update_v3.1.9_to_3.2.x.sql
> update_v3.3.x_to_3.4.x.sql
> update_3.6.0.sql
> update_3.7.0.sql
> update_3.9_to_3.10.sql
> update_3.12_to_3.14.sql

É isso mesmo?

**Comment by mmonzato** [comment]
@maycon1977 no PHPMyAdmin vc vai na aba Importar, tem um botão para selecionar o arquivo e um outro para executar, você vai utilizar esse mesmo procedimento para cada um dos arquivos de update, não sei como esta a sua base de dados no momento por isso aconselho a executar todos os updates, caso apresente alguma mensagem de erro, é pq o arquivo já foi executado.

**Comment by maycon1977** [comment]
> @maycon1977 no PHPMyAdmin vc vai na aba Importar, tem um botão para selecionar o arquivo e um outro para executar, você vai utilizar esse mesmo procedimento para cada um dos arquivos de update, não sei como esta a sua base de dados no momento por isso aconselho a executar todos os updates, caso apresente alguma mensagem de erro, é pq o arquivo já foi executado.

Segui exatamente a ordem que coloquei acima e apesar de aparecer uns erros em alguns updates, me parece que no fim deu tudo certo. Consegui logar já com o banco de dados antigo, porém com as tabelas atualizadas.

Muito bom! valeu pela ajuda, cara!
