### ISSUE TITLE
Alterações.

### ISSUE THREAD

**Issue by Murataeduardo** [RamonSilva20/mapos#555]
Bom dia.
Alguém pode me ajudar a trocar o logo da aplicação?

**Comment by Claudiomfa** [comment]
\assets\img\logo.png

este é o ficheiro do logo do mapos

**Comment by Murataeduardo** [comment]
Valeu Claudio pela ajuda, tinha alterado e não mudava um CTRL+F5 e alteração surtiu efeito.
