### ISSUE TITLE
MAPOS x Certificado SSL

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#556]
Olá novamente pessoal...

Consegui configurar direitinho o MAPOS graças a varias dicas da galera e agradeço muito por isso...

Vamos ao novo problema:

Sempre que ativo o Certificado SSL do meu servidor, não consigo entrar corretamente no meu MAPOS online. Some toda a configuração das telas e aparecem somente os textos todos truncados...

Antes de recorrer ao servidor (Hostgator), estou vindo falar com vocês. Alguma sugestão para o MAPOS se entender com o Certificado SSL?

Desde já agradeço pelo tempo dos engenheiros de plantão!

**Comment by RamonSilva20** [comment]
Olá. Colocou https:// no início do base_url?

**Comment by TecSecret** [comment]
Adiciona isso no arquivo config.php que fica dentro de application/config. Aonde diz $base_url apaga e adiciona isso: 

$base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$base_url .= "://". @$_SERVER['HTTP_HOST'];
$base_url .=     str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
$config['base_url'] = $base_url;

**Comment by maycon1977** [comment]
> $base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
> $base_url .= "://". @$_SERVER['HTTP_HOST'];
> $base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
> $config['base_url'] = $base_url;

Lá está assim:

> $config['base_url'] = 'http://www.meusite.com.br/os';

Fiz da forma abaixo:

> $base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
> $base_url .= "://". @$_SERVER['HTTP_HOST'];
> $base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
> $config['base_url'] = 'https://www.meusite.com.br/os';

AGORA FUNFOU!

VCS SÃO FOD@!

**Comment by maycon1977** [comment]
> Olá. Colocou https:// no início do base_url?

Fiz o que o TecScret falou. Valeu mesmo, Ramon!
