### ISSUE TITLE
Erro update version 3.15.0

### ISSUE THREAD

**Issue by brunomontteiro** [RamonSilva20/mapos#557]
Boa tarde!
Já utilizo o sistema 3.14.2 Map-os  do Ramon a um tempo e nunca tive problemas na atualização e não tive problema no sistema em si, tudo funciona perfeitamente todas as funções e deixo meus parabéns pelo app @RamonSilva20 .

Porém, fui atualizar para a versão 3.15.0 e aparece a tela de login e quando faço login diz que a pagina não pode ser encontrada.

Realizei a instalação limpa com banco de dados zerado com o original e também não entra.

Alguém mais está com esse problema?

Aguardo.

**Comment by JulianoSavino** [comment]
Amigo, fiz aqui e deu certo. Tenta baixar novamente, pode ter corrompido algum arquivo

**Comment by brunomontteiro** [comment]
@JulianoSavino Qual foi o seu procedimento para atualização? 
Abraço!

**Comment by JulianoSavino** [comment]
apenas executei no phpmyadmin o update
no caso abra o phpmuadmin/selecione su banco do mapos / va em importar e selecione o arquivo update_3.14.2_to_3.15.0.sql que está na pasta updates

**Comment by brunomontteiro** [comment]
Obrigado Juliano, fiz exatamente o que você fez e não deu certo.

Problema estava na Versão do PHP, tive alterar para uma versão mais nova pois uso outros banco de dados. Voltei para 5.5 e funcionou, irei ver o que fazer agora pra usar os dois BD para usar os dois apps.
