### ISSUE TITLE
Controle estoque

### ISSUE THREAD

**Issue by JulianoSavino** [RamonSilva20/mapos#558]
Boa tarde pessoal, adorei a nova atualização, li o changelog e todos os demais descritivos dela mas não encontrei nada que me esclarecesse o que realmente é esta opção de controle de estoque que podemos ativar e desativar em configurações/sistema/controlar estoque (sim/não). 
Fiz varios testes e na pratica não vi nada. 
Para registro, fiz a atualização com sucesso do banco de dados. 
Obrigado pessoal

**Comment by RamonSilva20** [comment]
Boa tarde. Desativando o controle de estoque o sistema deixa de verificar se tem quantidade suficiente no cadastro de produtos.

**Comment by JulianoSavino** [comment]
Entendi, obrigado pelo retorno
