### ISSUE TITLE
Organização dos Anexos das O.S.

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#560]
Olá amigos, venho aqui deixar uma sugestão que acredito ser fácil de implementar e vai me ajudar (e provavelmente a outros) bastante... Seguinte:

Tenho por hábito tirar fotos dos equipamentos que chegam dos clientes na hora que entram na oficina, durante a execução do trabalho e na entrega e utilizo muito o whatsapp para centralizar tudo:

1) Tiro a(s) foto(s) com o celular e jogo no grupo da empresa.

2) Com o whatsapp logado no PC da empresa, copio as fotos para pastas específicas de cada cliente.

3) Renomeio os arquivos na base de "O.S. XXXX Foto-0X,jpg" e subo pra O.S. do Mapos.

Aí vc pergunta porque renomear? O que acontece é que o whatsapp zoneia os nomes dos arquivos anexos sem logica quase nenhuma e como a pasta "assets\anexos" do MAPOS recebe todos os arquivos anexados de qualquer coisa que se anexe, se não renomear, dá uma zona federal pra procurar (Caso precise) arquivos de imagem separados.

Daí me surgiu 2 idéias:

A Mais fácil (Crei eu): Ao anexar um arquivo por exemplo à O.S. 0453, dentro da pasta "assets\anexos", o sistema poderia criar uma pasta "O.S.0453" e assim despejar todos os anexos dela ali de forma automática.

A Mais difícil (?): Quando anexar os arquivos, acrescentar um Sufixo a qualquer um deles como "O.S.0453_jksdjkdjkhsdfgsjgjsgjlfgfuuure879686.jpg".

O que acham da idéia? Rola?

**Comment by Pr3d4dor** [comment]
Isso pode ser implementado futuramente. Se eu não implementar talvez outra pessoa implemente.

**Comment by TecSecret** [comment]
Não seria esse campo ai que vc tava querendo, eu uso ele para anexar fotos quando precisa.

![image](https://user-images.githubusercontent.com/6561517/74619326-e36cac80-5113-11ea-943d-ad362e9ecf71.png)

**Comment by Pr3d4dor** [comment]
Pelo que ele descreveu ele já utiliza dessa forma mesmo, mas a modificação que ele quer é separar os arquivos na pasta uploads em uma pasta para cada OS.

**Comment by TecSecret** [comment]
Hum, é uma função interessante, mas não sei como pode ser implantando isso

**Comment by maycon1977** [comment]
> Pelo que ele descreveu ele já utiliza dessa forma mesmo, mas a modificação que ele quer é separar os arquivos na pasta uploads em uma pasta para cada OS.

Exato.

**Comment by mmonzato** [comment]
@maycon1977 vc esta no grupo do whatsapp ?

**Comment by maycon1977** [comment]
> @maycon1977 vc esta no grupo do whatsapp ?

Eu estava há um tempo atrás, mas meu telefone bugou e depois troquei de aparelho. Acabou que perdi todas as msgs anteriores e não sei pq, mas não tô mais lá no grupo.

**Comment by RamonSilva20** [comment]
Estrutura alterada como sugerido na versão 4.1.0.

**Comment by maycon1977** [comment]
> Estrutura alterada como sugerido na versão 4.1.0.

Show de bola!
