### ISSUE TITLE
Orçamentos

### ISSUE THREAD

**Issue by ocrispim** [RamonSilva20/mapos#565]
** Quando A OS ainda esta em Orçamento o sistema ja deu baixa no estoque do que eu lancei mesmo ainda não estando vendido um orçamento não é garantia de venda.

** Solução que você desejo **
Gostaria que existisse uma forma de fazer orçamento sem que interfira no estoque queria poder utilizar os produtos cadastrado os serviços mas sem a alteração da quantidade do estoque.

** Alternativas que considerei **
A opção correta é que o orçamento fosse a parte da Ordem de serviço pois mesmo que o orçamento seja aprovado o serviço pode ser feito em etapas e os produtos serem usado ao poucos sendo criado pra cada etapa do serviço uma OS.

**Comment by Pr3d4dor** [comment]
Eu acho que a estrutura não deve ser modificada, apenas pode ser feiuto um ajuste para que seja descontado do estoque somente quando o status Aprovado for colocado na OS por exemplo.

O que acha?

**Comment by ocrispim** [comment]
pode ser desde que eu consiga adicionar produto com quantidade maior que meu estoque porque pode ser que eu não tenha todo o produto que precisarei caso o orçamento for aprovado.

**Comment by Pr3d4dor** [comment]
Eu acho que não vai trazer problemas pois o estoque ficará negativo, assim ficará evidente a quantidade que vc precisará comprar.

**Comment by ocrispim** [comment]
ok

**Comment by Lucasperezeu** [comment]
> Eu acho que a estrutura não deve ser modificada, apenas pode ser feito um ajuste para que seja descontado do estoque somente quando o status Aprovado for colocado na OS por exemplo.
> O que acha?

@Pr3d4dor Tambem preciso dessa função, a partir de quando estará funcionando?

**Comment by ADMTec** [comment]
alguém sabe se essa função foi implementada ?

**Comment by Pr3d4dor** [comment]
@ADMTec ainda não, estamos esperando o merge das PR's atuais e lançar a próxima versão e depois disso iremos realizar a implementação de novas features.
