### ISSUE TITLE
Alterar Texto da área do Cliente

### ISSUE THREAD

**Issue by endenson** [RamonSilva20/mapos#569]
Como eu altero os nomes dos campos que estão na area do cliente ? consegui modificar o PHP somente da area do administrador, mas na area do Cliente " Mine " Não consegui achar os arquivos para editar, por exemplo, trocar o nome Ordens de Serviço, que fica tanto no Dashboard como no Menu lateral, alterar o nome Compras etc...

onde eu faço essa alteração ?

**Comment by RamonSilva20** [comment]
Olá @endenson. Os arquivos de apresentação da área do cliente ficam dentro da pasta application/views/**conecte**.
