### ISSUE TITLE
Configurar Email de enviado de Ordens

### ISSUE THREAD

**Issue by endenson** [RamonSilva20/mapos#570]
Como eu realizo a configuração do email que vai ser usado para enviar as respostas da ordem de serviço ? pois os email nao estao chegando. 

obrigado!!!

**Comment by robsonmeca** [comment]
Configure o arquivo /application/config/email.conf

**Comment by brunaomessias** [comment]
Estou com este problema também... já preenchi com os dados e os e-mails não saem das "configurações/e-mails". O que pode ser?

**Comment by Pr3d4dor** [comment]
Realizaram o procedimento correto para que a fila de e-mails esteja sendo processada via crons?

**Comment by brunomontteiro** [comment]
Boa noite, pra quem está tendo problemas com o cron.
Eu utilizo o Map-os no meu cpanel, tive que encontrar o caminho correto, geralmente quando você vai no icone Trabalhos com cron, ele já te da um exemplo de como deve ser. No meu caso foi só adicionar o caminho correto e do cron no cpanel e depois adicionar o caminho correto do Map-os.

Abaixo a imagem como exemplo, o que está apagado é o local e nome do meu servidor o restante é só fazer igual caso o caminho esteja certo.

Abraço!

![image](https://user-images.githubusercontent.com/61118178/74891730-79981100-5366-11ea-8b50-7ae15c5a1e9c.png)

**Comment by Murataeduardo** [comment]
Bom dia pessoal.

Aproveitando o tópico, alguém já configurou pelo uolhost?

Com as instruções que veio não aceita como na imagem anexo, alguém consegue me dar um orientação?
![mapos](https://user-images.githubusercontent.com/61054643/74935899-de378800-53c7-11ea-869f-50db7601b344.png)

**Comment by endenson** [comment]
> Configure o arquivo /application/config/email.conf

Não existe esse diretorio

**Comment by brunaomessias** [comment]
Boa tarde, consegui colocar pra rodar mas os e-mails não conseguem ser enviados e fica dando falha.
configurei dentro do arquivo smtp tudo conforme o modelo. Podem dar uma ajuda?

**Comment by Pr3d4dor** [comment]
> > Configure o arquivo /application/config/email.conf
> 
> Não existe esse diretorio

É no arquivo `application/config/email.php`

> Boa tarde, consegui colocar pra rodar mas os e-mails não conseguem ser enviados e fica dando falha.
> configurei dentro do arquivo smtp tudo conforme o modelo. Podem dar uma ajuda?

Você precisa olhar os logs de erros para poder verificar qual erro está ocorrendo.
