### ISSUE TITLE
Estou tentando configurar o envio de email, para enviar emails somente na criação da OS e no envio da fatura, porem não encontrei tal configuração. Essa Configuração existe?

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#571]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
Essa configuração no momento não existe.
