### ISSUE TITLE
Erro cep Portugual

### ISSUE THREAD

**Issue by Bruno28121** [RamonSilva20/mapos#573]
** Descreva o bug **
Esta dando cepo invalido ainda
o que estou tentando usar este cep : 4700-206 ( portugual )

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'Clientes
2. Clique em '....'Cep
3. Role para baixo até '....'
4. Ver erro:  Cep Invalido

**Comportamento esperado**
Espero que ele encontre o cep correto de portugual
![0101](https://user-images.githubusercontent.com/44698317/75031778-c8889800-5485-11ea-9887-319d75318996.png)

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

Ja utilizei este codigo que foi enviado em um chamado retrasado e mesmo assim nao deu certo :+1:

**Comment by Bruno28121** [comment]
Usei este codigo :+1: e mesmo assim ainda deu o erro acima: ( Ceps devem ser o de Portugual )
$(function () {
    $("#celular").mask("(00)00000-0000")
    $("#telefone").mask("(00)0000-0000")
});

$(function () {
    // INICIO FUNÇÃO DE MASCARA CPF/CNPJ
    var cpfMascara = function (val) {
        return val.replace(/\D/g, '').length > 11 ? '00.000.000/0000-00' : '000.000.000-009';
    },
    cpfOptions = {
        onKeyPress: function (val, e, field, options) {
            field.mask(cpfMascara.apply({}, arguments), options);
        }
    };
    $('.cpfcnpj').mask(cpfMascara, cpfOptions);
    // FIM FUNÇÃO DE MASCARA CPF/CNPJ
});

$(document).ready(function () {
    function limpa_formulario_cep() {
        // Limpa valores do formulário de cep.
        $("#rua").val("");
        $("#bairro").val("");
        $("#cidade").val("");
        $("#estado").val("");
    }

    //Quando o campo cep perde o foco.
    $("#cep").blur(function () {

        //Nova variável "cep" somente com dígitos.
        var cep = $(this).val().replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {
            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{7}$/;

            //Valida o formato do CEP.

            if (validacep.test(cep)) {
                //Preenche os campos com "..." enquanto consulta webservice.
                $("#rua").val("...");
                $("#bairro").val("...");
                $("#cidade").val("...");

                //Consulta o webservice codigos postais
                $.ajax({
                    url: "https://codigospostais.appspot.com/cp7?codigo=" + cep,
                    dataType: 'JSONP',
                    jsonpCallback: 'callback',
                    type: 'GET',
                    success: function (dados) {
                        //Atualiza os campos com os valores da consulta.
                        $("#rua").val(dados.arteria);
                        $("#bairro").val(dados['local ou zona']);
                        $("#cidade").val(dados.localidade);
                        document.getElementById("numero").focus();
                    },
                    error: function() {
                        limpa_formulario_cep();
                        Swal.fire({
                            type: "warning",
                            title: "Atenção",
                            text: "CEP não encontrado."
                        });
                    }
                });
            } //end if.
            else {
                //cep é inválido.
                limpa_formulario_cep();
                Swal.fire({
                    type: "error",
                    title: "Atenção",
                    text: "Formato de CEP inválido."
                });
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulario_cep();
        }
    });
});

**Comment by Pr3d4dor** [comment]
Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.

**Comment by TecSecret** [comment]
Uma coisa interessante seria vc colocar para o cliente selecionar o país que reside e depois carregar o JS correto de CEP para aquele pais

**Comment by Bruno28121** [comment]
> Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.

entao no meu aqui mesmo copiando todos estes codigos que vc me passou , ele ainda  forca eu digitar os 8 numeros e nao carrega .
Se digitar este cep: 4700-206 ele nao vai: meu sistema esta hospedado via nuvem se quiser testar.
Usuario : admin@admin.com
Senha: 123456

Link: https://unireparacoes.com/chamado/

**Comment by Pr3d4dor** [comment]
> Uma coisa interessante seria vc colocar para o cliente selecionar o país que reside e depois carregar o JS correto de CEP para aquele pais

É interessante mas ainda não existe planos para o sistema ser internacional. Quando isso estiver sendo desenvolvido aí sim poderia ser adicionado este campo.



> > Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.
> 
> entao no meu aqui mesmo copiando todos estes codigos que vc me passou , ele ainda forca eu digitar os 8 numeros e nao carrega .
> Se digitar este cep: 4700-206 ele nao vai: meu sistema esta hospedado via nuvem se quiser testar.
> Usuario : [admin@admin.com](mailto:admin@admin.com)
> Senha: 123456
> 
> Link: https://unireparacoes.com/chamado/
Você está usando a versão 3.14.2, tente atualizar para a versão 3.15.0

**Comment by willph** [comment]
> 
> 
> > Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.
> 
> entao no meu aqui mesmo copiando todos estes codigos que vc me passou , ele ainda forca eu digitar os 8 numeros e nao carrega .
> Se digitar este cep: 4700-206 ele nao vai: meu sistema esta hospedado via nuvem se quiser testar.
> Usuario : [admin@admin.com](mailto:admin@admin.com)
> Senha: 123456
> 
> Link: https://unireparacoes.com/chamado/

1 APAGUE TODO O CÓDIGO QUE ESTIVER NO ARQUIVO. 
2 COLE ESSE ABAIXO.

```
$(function () {
    $("#celular").mask("(00)00000-0000")
    $("#telefone").mask("(00)0000-0000")
    $("#cep").mask("0000-000")
});

$(function () {
    // INICIO FUNÇÃO DE MASCARA CPF/CNPJ
    var cpfMascara = function (val) {
        return val.replace(/\D/g, '').length > 11 ? '00.000.000/0000-00' : '000.000.000-009';
    },
    cpfOptions = {
        onKeyPress: function (val, e, field, options) {
            field.mask(cpfMascara.apply({}, arguments), options);
        }
    };
    $('.cpfcnpj').mask(cpfMascara, cpfOptions);
    // FIM FUNÇÃO DE MASCARA CPF/CNPJ
});

$(document).ready(function () {
    function limpa_formulario_cep() {
        // Limpa valores do formulário de cep.
        $("#rua").val("");
        $("#bairro").val("");
        $("#cidade").val("");
        $("#estado").val("");
    }

    //Quando o campo cep perde o foco.
    $("#cep").blur(function () {

        //Nova variável "cep" somente com dígitos.
        var cep = $(this).val().replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {
            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{7}$/;

            //Valida o formato do CEP.

            if (validacep.test(cep)) {
                //Preenche os campos com "..." enquanto consulta webservice.
                $("#rua").val("...");
                $("#bairro").val("...");
                $("#cidade").val("...");

                //Consulta o webservice codigos postais
                $.ajax({
                    url: "https://codigospostais.appspot.com/cp7?codigo=" + cep,
                    dataType: 'JSONP',
                    jsonpCallback: 'callback',
                    type: 'GET',
                    success: function (dados) {
                        //Atualiza os campos com os valores da consulta.
                        $("#rua").val(dados.arteria);
                        $("#bairro").val(dados['local ou zona']);
                        $("#cidade").val(dados.localidade);
                        document.getElementById("numero").focus();
                    },
                    error: function() {
                        limpa_formulario_cep();
                        Swal.fire({
                            type: "warning",
                            title: "Atenção",
                            text: "CEP não encontrado."
                        });
                    }
                });
            } //end if.
            else {
                //cep é inválido.
                limpa_formulario_cep();
                Swal.fire({
                    type: "error",
                    title: "Atenção",
                    text: "Formato de CEP inválido."
                });
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulario_cep();
        }
    });
});
```

e me diga se funcionou ou não.

**Comment by willph** [comment]
Agora pra fica 100% precisamos saber o nome equivalente ai para:

Rua* = ?
Bairro* = ?
Cidade* = ?
Estado* = ?

**Comment by willph** [comment]
Pelo que vi só faltou a mascara para funcionar do jeito que queria.

`    $("#cep").mask("0000-000")`

**Comment by Bruno28121** [comment]
> Pelo que vi só faltou a mascara para funcionar do jeito que queria.
> 
> ` $("#cep").mask("0000-000")`

Agora ele deixar digitar qualquer quantidade de numeros mas nao procura automatico o endereço

**Comment by Bruno28121** [comment]
> Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.

Estranho o que pode ser , agora ele deixa digitar qualquer quantidade de numeros mais , nao puxa endereço automatico, o seu deu certo ?

**Comment by willph** [comment]
> > Eu fiz o teste com esse CEP usando o código que eu lhe passei e o mesmo está funcionando corretamente.
> 
> Estranho o que pode ser , agora ele deixa digitar qualquer quantidade de numeros mais , nao puxa endereço automatico, o seu deu certo ?

Você colou todo o código que eu coloquei na mensagem acima?

Esse, no arquivo 

```$(function () {
    $("#celular").mask("(00)00000-0000")
    $("#telefone").mask("(00)0000-0000")
    $("#cep").mask("0000-000")
});

$(function () {
    // INICIO FUNÇÃO DE MASCARA CPF/CNPJ
    var cpfMascara = function (val) {
        return val.replace(/\D/g, '').length > 11 ? '00.000.000/0000-00' : '000.000.000-009';
    },
    cpfOptions = {
        onKeyPress: function (val, e, field, options) {
            field.mask(cpfMascara.apply({}, arguments), options);
        }
    };
    $('.cpfcnpj').mask(cpfMascara, cpfOptions);
    // FIM FUNÇÃO DE MASCARA CPF/CNPJ
});

$(document).ready(function () {
    function limpa_formulario_cep() {
        // Limpa valores do formulário de cep.
        $("#rua").val("");
        $("#bairro").val("");
        $("#cidade").val("");
        $("#estado").val("");
    }

    //Quando o campo cep perde o foco.
    $("#cep").blur(function () {

        //Nova variável "cep" somente com dígitos.
        var cep = $(this).val().replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {
            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{7}$/;

            //Valida o formato do CEP.

            if (validacep.test(cep)) {
                //Preenche os campos com "..." enquanto consulta webservice.
                $("#rua").val("...");
                $("#bairro").val("...");
                $("#cidade").val("...");

                //Consulta o webservice codigos postais
                $.ajax({
                    url: "https://codigospostais.appspot.com/cp7?codigo=" + cep,
                    dataType: 'JSONP',
                    jsonpCallback: 'callback',
                    type: 'GET',
                    success: function (dados) {
                        //Atualiza os campos com os valores da consulta.
                        $("#rua").val(dados.arteria);
                        $("#bairro").val(dados['local ou zona']);
                        $("#cidade").val(dados.localidade);
                        document.getElementById("numero").focus();
                    },
                    error: function() {
                        limpa_formulario_cep();
                        Swal.fire({
                            type: "warning",
                            title: "Atenção",
                            text: "CEP não encontrado."
                        });
                    }
                });
            } //end if.
            else {
                //cep é inválido.
                limpa_formulario_cep();
                Swal.fire({
                    type: "error",
                    title: "Atenção",
                    text: "Formato de CEP inválido."
                });
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulario_cep();
        }
    });
});```

**Comment by willph** [comment]
Mande um print de como esta o seu código por favor.

**Comment by Bruno28121** [comment]
![0101](https://user-images.githubusercontent.com/44698317/75098908-6ec5c200-559a-11ea-8e11-048296263be1.png)

**Comment by Bruno28121** [comment]
![image](https://user-images.githubusercontent.com/44698317/75098920-91f07180-559a-11ea-86cc-afc3b4ee0535.png)

**Comment by Bruno28121** [comment]
> Mande um print de como esta o seu código por favor.

segue amigo....desde ja agradeço sua atenção para comigo

**Comment by Bruno28121** [comment]
![image](https://user-images.githubusercontent.com/44698317/75098940-bfd5b600-559a-11ea-9b14-237abb67a129.png)

**Comment by Bruno28121** [comment]
o que pode estar acontecendo ?

**Comment by Bruno28121** [comment]
> Mande um print de como esta o seu código por favor.

Consegue me ajudar ?

**Comment by willph** [comment]
Faça o teste em localhost por favor.
Estou suspeitando das hospedagem hostinger.
Mas 100% de certeza, só fazendo esse teste.
Porque se você copiou o meu código e colou no lugar do outro era pra funcionar.

**Comment by LipzyLipzy** [comment]
Eu também tenho estado a tentar aplicar esta funcionalidade no meu. 
Este código esta a trabalhar mas fica muito incompleto. 
Encontrei algo melhor mas não sei como fazer para o usar.
Alguém pode ajudar?
https://github.com/centraldedados/codigos_postais/

Estes códigos postais são só para  portugal
Obrigado

**Comment by LipzyLipzy** [comment]
Oi Bruno deixou o cep a trabalhar para portugal? 
Abraço

**Comment by Bruno28121** [comment]
> Oi Bruno deixou o cep a trabalhar para portugal?
> Abraço

nada ainda continuo com o mesmo problema
