### ISSUE TITLE
Mudanças nescessarias para utilização

### ISSUE THREAD

**Issue by djotabr** [RamonSilva20/mapos#574]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
- O sistema é muito bom porem não hora das pesquisas não é possível pesquisar por código de barras.
- No sistema de cadastros é necessário uma personalização dos campos obrigatórios, como telefone fixo CPF etc.
- O sistemas de vendas é excelente mas precisa de um novo modulo para vendas rápidas, pois uso aqui na loja mas quando preciso lançar vendas de balcão é honroso. Exemplo: lançar xerox, tempo de LAN House, baterias, etc.
- Na guia de produtos é necessário uma tabela dinâmica para filtros e pesquisas em ajax para consultas rápidas.
-Nas guias produtos seria interessante adição de fotos.
-No sistema de estoque é necessário um sistema que possamos buscar pelo código de barras ou nome para dar entrada nos produtos que chegam e já estão cadastrados pois nem sempre quem cadastrou vai dar entrada então ele não sabe se já foi cadastrado ou não

** Descreva a solução que você deseja **
-Eu já mudei aqui no meu sistema colocando o or_like nas classes de pesquisas.
`C:\xampp\htdocs\application\models\Mapos_model.php:
   68          // buscando produtos
   69          $this->db->like('descricao', $termo);
   70:         $this->db->or_like('codDeBarra', $termo);
   71          $this->db->limit(5);
   72          $this->db->order_by('estoque','DESC');

C:\xampp\htdocs\application\models\Os_model.php:
  183          $this->db->limit(5);
  184          $this->db->like('descricao', $q);
  185:         $this->db->or_like('codDeBarra', $q);
  186  
  187          $this->db->where('saida', 1);

C:\xampp\htdocs\system\database\DB_query_builder.php:
  900  	 * @return	CI_DB_query_builder
  901  	 */
  902: 	public function or_like($field, $match = '', $side = 'both', $escape = NULL)
  903  	{
  904  		return $this->_like($field, $match, 'OR ', $side, '', $escape);
  ...
  930  	 *
  931  	 * @used-by	like()
  932: 	 * @used-by	or_like()
  933  	 * @used-by	not_like()
  934  	 * @used-by	or_not_like()`

-Sobre sistemas de vendas eu não consegui ainda arrumar uma solução estou usando um cliente chamado balcão para vendas rápidas mas um sistema de caixa rápido seria o ideal.
- No sistema de cadastros eu ja alterei no meu manualmente mas é necessário isso no config ou na guia configurações.
- - Na guia de produtos o interessante seria implantar as tabelas dinâmicas do bootstrap e sobre as fotos alterei no meu sistema mas tenho que colocar o link das imagens manualmente no banco de dados por enquanto.

** Contexto adicional **
Desculpe o longo texto mas essas são minhas impressões do sistema mas ja está muito bom.
Com essas alterações que eu sugeri já dá para usar em muitos estabelecimento.

**Comment by JulianoSavino** [comment]
Realmente muito boas as colocações. Acho que o foco do sistema poderia ir um pouco mais para o financeiro, como fluxo de caixa, um fluxo mensal para acompanhar receitas e gastos mês a mês, parcelamento de compras e vendas e relatório de faturamento por vendedor...

**Comment by djotabr** [comment]
Reinstalei o sistema e ,es,o assim nao foi implementado as buscas pelo cod de barras.
Terei que alterar manualmente mas nao poderei atualizar o sistema pois perderi minhas alterações
