### ISSUE TITLE
Edição do Nome do Produto

### ISSUE THREAD

**Issue by carlaomegagitos** [RamonSilva20/mapos#576]
Gostaria de Editar o nome do produto lançado na venda. Tipo cadastrar o produto com o nome de  Produto X, e após lança-lo na venda clicar sobre seu nome e editar a descrição e/ou adicionar alguma coisa tipo um numero de série.

É possivel?
desde ja agradeço!!!

att.

Carlos FErreira 

** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by LipzyLipzy** [comment]
Também estou querendo o campo de adicionar produtos aberto.
Será possível?
Poderia ficar como no preço é possível ser alterado e guardado.
Assim poderíamos chamar um produto ou escrever um produto que não esteja ainda adicionado aos produtos, ou ate mesmo acrescentar alguma nota como o colega Carlao informa. 
ficaria mais versátil.
 
Obrigado

**Comment by carlaomegagitos** [comment]
Olá Ramon,
Voce quem pediu pra colocar essa issue para que lembrasse de desenvolver.
tá lembrado?

Em qua., 29 de abr. de 2020 às 21:06, github-actions[bot] <
notifications@github.com> escreveu:

**Comment by carlaomegagitos** [comment]
> Esta issue está obsoleta porque está aberta há 30 dias sem atividade. Remova o rótulo ou esse comentário ou essa issue será fechada em 5 dias

Olá Ramon,
Voce quem pediu pra colocar essa issue para que lembrasse de desenvolver.
tá lembrado?

**Comment by carlaomegagitos** [comment]
Acha que isso é possível ser desenvolvido?
