### ISSUE TITLE
Ajuda para tela de vendas.

### ISSUE THREAD

**Issue by Murataeduardo** [RamonSilva20/mapos#577]
Boa tarde.

Preciso adicionar dois campos na tela de venda.

Já consegui inserir na View, ja alterei a tabela adicionando as colunas, porem quando eu salvo os dados não vão para o banco.

![vendas](https://user-images.githubusercontent.com/61054643/75115676-97ec5e00-563f-11ea-80cd-e24051f5cc4e.png)

**Comment by mmonzato** [comment]
https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by Pr3d4dor** [comment]
Você pode pedir ajuda no grupo de whatsapp igual o @mmonzato colocou o link acima.

Vou fechar a issue pois não tem relação com algum problema ou funcionalidade nova para o mapos.
