### ISSUE TITLE
Colocar um botão de atualização automatica quando tiver uma nova versão

### ISSUE THREAD

**Issue by cftvseginfo** [RamonSilva20/mapos#578]
Eu sei instalar , mas quando é pra atualizar eu não sei, eu estou utilizando a versão 3.14.2, pois não sei atualizar, alguem poderia me passar os passos pra atualização da versão 3.14.2 pra versão 3.15.

**Comment by JulianoSavino** [comment]
Bom amigo, explicarei como eu faço, porém se houver uma forma mais "correta" que seja explicada.
Primeiro faço backup do meu banco, em seguida executo o update 3.14.2 para 3.15 que tem na pasta updates, no caso, apenas importe esse banco por cima do seu para que atualize as tabelas. 
Depois removo a minha pasta do sistema e com a pasta nova, faço como na instalação normal informando os meus dados conforme foi informado na versão anterior.

**Comment by Pr3d4dor** [comment]
Na #559 eu fiz uma implementação em que você pode clicar no botão "Atualizar Banco de Dados" em Configurações >> Sistema e assim o seu banco de dados irá ser atualizado automaticamente para o banco de dados da última versão.

Porém para isso acontecer você precisa atualizar o código manualmente. Posso no futuro verificar se é possível também colocar um botão para atualizar o código também.

**Comment by cftvseginfo** [comment]
> Bom amigo, explicarei como eu faço, porém se houver uma forma mais "correta" que seja explicada.
> Primeiro faço backup do meu banco, em seguida executo o update 3.14.2 para 3.15 que tem na pasta updates, no caso, apenas importe esse banco por cima do seu para que atualize as tabelas.
> Depois removo a minha pasta do sistema e com a pasta nova, faço como na instalação normal informando os meus dados conforme foi informado na versão anterior.

Se pudesse explicar com imagens , 
1- qual o banco de dados que preciso fazero backup, ondre ele fica ?
2- tambem não tenho ideia como fazer esse  upadate 3.14.2 pra 3.15
3- qual pasta remover

Estou com medo de perder os cadastro dos produtos e serviços que fiz.

**Comment by cftvseginfo** [comment]
> Na #559 eu fiz uma implementação em que você pode clicar no botão "Atualizar Banco de Dados" em Configurações >> Sistema e assim o seu banco de dados irá ser atualizado automaticamente para o banco de dados da última versão.
> 
> Porém para isso acontecer você precisa atualizar o código manualmente. Posso no futuro verificar se é possível também colocar um botão para atualizar o código também.

Teria como explicar com imagens , pra eu ver qual seria mais facil de fazer.

**Comment by Pr3d4dor** [comment]
Não foi lançado ainda, assim que seja lançada a próxima versão estará descrito no README.md

**Comment by cftvseginfo** [comment]
Ainda não consegui, continuo usanddo a versão 3.14.2

**Comment by wilkergrcv** [comment]
qual software de banco de dados esta usando??

**Comment by Pr3d4dor** [comment]
MySQL
