### ISSUE TITLE
Prestação de serviços

### ISSUE THREAD

**Issue by MMC227** [RamonSilva20/mapos#579]
O sistema eh muito bom, mas acredito que poderia ficar muito mais completo caso fosse incorporado a funcionalidade para prestação de serviços não como uma assistência técnica, onde os clientes precisam ir ate um estabelecimento para serem atendidos.

A funcionalidade que estou sugerindo implementar eh para a realização de serviços na casa do cliente,   ex: encanador, reparo de motor de portão, limpador de piscina, limpador de moveis e etc. Esse tipo profissional realiza o serviço na casa do cliente.

Caso deseje implementar esta funcionalidade no sistema fico a disposição para ajudar.

**Comment by Pr3d4dor** [comment]
Não daria para o encanador, e etc cadastrar o serviço no sistema e após isso ir na casa do cliente executá-lo?

**Comment by MMC227** [comment]
Na parte "RESPONSÁVEL" poderia ter mais de uma pessoa responsável?

Alem disso como eh possível criar serviços repetidos para o mesmo cliente ?
"Ex: Limpar a piscina da Casa X a cada 30 dias."

**Comment by Pr3d4dor** [comment]
Tudo isso que você disse pode ser resumido em:
- 1 ou mais responsáveis por cada OS.
- OS recorrente.
- Confirmação de serviço.

As  duas primerias funcionalidades eu acho interessante e poderiam ser implementadas. A confirmação que a OS foi executada já pode ser utilizada por meio dos "status" e também fotos podem ser anexadas na aba de anexos. Somente a parte do cliente assinar diretamente no sistema que eu creio que não possa ser implementada. O que pode ser feito é tirar uma foto da assinatura confirmando a execução e também fazer o upload da imagem em anexos.

**Comment by MMC227** [comment]
Quando uma OS eh classificada como Orçamento, eh possível converter-la em uma ordem de execução de fato?
Ex: Iniciou-se como Orçamento, foi aprovado e virou um serviço?

**Comment by Pr3d4dor** [comment]
"Orçamento" é um status da OS, ela já inicia nesse status. Então considerá-se que se você mudar do status "Orçamento" para "Aprovado" a OS será executada.

**Comment by MMC227** [comment]
Nesse caso gera-se um novo numero de OS, para manter-se o histórico?
Ex: Orçamento sempre tem inicia-se com '#00001', quando foi aprovado o orçamento gerou a OS 12318998 e na OS fica o histórico do dessa OS?

**Comment by Pr3d4dor** [comment]
Não é separado orçamento de OS, "Orçamento" é apenas um status.
