### ISSUE TITLE
Erro ao cadastrar produto

### ISSUE THREAD

**Issue by brunolafm** [RamonSilva20/mapos#58]
Estou com um erro ao visualizar/cadastrar um produto.

Entrada  
A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$entrada
Filename: produtos/editarProduto.php
Line Number: 57

**Comment by acinformatica2004** [comment]
Boa noite, vc atualizou o banco de dados?

**Comment by brunolafm** [comment]
Atualizei, obrigado.
