### ISSUE TITLE
ENVIAR EMAIL

### ISSUE THREAD

**Issue by britoriquegbi** [RamonSilva20/mapos#580]
**Solicitação:** Botão enviar queue na lista de Emails. Um ótimo escape para quem trabalha com servidores que cobram taxa adicional para utilizar cron jobs...

Alternativa para quem enfrenta esse problema de não conseguir utilizar cronjobs:
Adicionar no arquivo **application/controllers/Mapos.php** :
`$this->load->library('email');` --> Dentro da função **__construct()** (linha 16)
`$this->email->send_queue();` --> Dentro da função **index()** (linha 29)

Desse modo, sempre que você acessar a index irá enviar a fila de emails.

**Comment by Pr3d4dor** [comment]
Obrigado pela ajuda, estamos vendo a possibilidade de adicionar uma configuração em Configuracões >> Sistema para desabilitar a utilização de fila de e-mails e assim enviar o e-mail logo após sua criação e adição na fila.
