### ISSUE TITLE
Assinatura digital.

### ISSUE THREAD

**Issue by GabrielSk82020** [RamonSilva20/mapos#581]
Boa noite pessoal, tudo bem com vocês?!

   Uns anos atras eu trabalhei como terceiro em uma empresa de instalação de internet, e utilizava um APP que deixava eu pegar a assinatura do cliente no final do serviço, então eu não precisava lidar com papel.
  Eu descobri o projeto de vocês tem apenas dois dias, mas vi que é algo muito bem elaborado e que vem sendo construído e atualizado conforme a necessidade a anos
, eu já vi algumas pessoas pedindo para vocês adicionarem essa função, então pesquisei um pouco sobre o código que seria necessário e descobri esse vídeo no youtube que disponibiliza uma página para download, eu testei aqui e funciona muito bem, então vou compartilhar com vocês e quem sabe será possível adicionar essa função junto a plataforma que já temos hoje.

FONTE = https://www.youtube.com/watch?v=Gb8cgX_JQvQ

[HTML PHP Signature Pad.zip](https://github.com/RamonSilva20/mapos/files/4253097/HTML.PHP.Signature.Pad.zip)

**Comment by Pr3d4dor** [comment]
Obrigado pelas informações, estamos já trabalhando em algumas coisas e logo a versão v.4.0.0 será lançada. Então não podemos começar a o desenvolvimento de coisas que vão requer um certo tempo considerável para serem implementadas.

Após o lançamento podemos analisar realizar a implementação caso tudo ocorra dentro do esperado.

**Comment by maycon1977** [comment]
> Obrigado pelas informações, estamos já trabalhando em algumas coisas e logo a versão v.4.0.0 será lançada. 

Olá, amigo...
mas já temos uma previsão real da data de lançamento da versão 4?
pergunto porque estou para fazer a migração do meu MAPOS que é antigaço e ia migra pro 3.15.0, mas se o 4.0 estiver próximo vou esperar mais um pouco...

**Comment by Pr3d4dor** [comment]
> > Obrigado pelas informações estamos já trabalhando em algumas coisas e logo a versão v.4.0.0 será lançada.
> 
> Olá, Pr3d4dor...
> mas já temos uma previsão real da data de lançamento da versão 4?
> pergunto porque estou para fazer a migração do meu MAPOS que é antigaço e ia migrar pro 3.15.0, mas se o 4.0 estiver próximo vou esperar mais um pouco...

Não tem uma data exata, falta apenas fazer o merge de todas as PR's atuais e a versão v.4.0.0 será lançada.

Eu recomendo você realizar o update para a versão v.3.15.0 mesmo que talvez demore um pouco para sair a próxima versão pois você precisa realizar todos os updates em ordem.

**Comment by GabrielSk82020** [comment]
> > > Obrigado pelas informações estamos já trabalhando em algumas coisas e logo a versão v.4.0.0 será lançada.
> > 
> > 
> > Olá, Pr3d4dor...
> > mas já temos uma previsão real da data de lançamento da versão 4?
> > pergunto porque estou para fazer a migração do meu MAPOS que é antigaço e ia migrar pro 3.15.0, mas se o 4.0 estiver próximo vou esperar mais um pouco...
> 
> Não tem uma data exata, falta apenas fazer o merge de todas as PR's atuais e a versão v.4.0.0 será lançada.
> 
> Eu recomendo você realizar o update para a versão v.3.15.0 mesmo que talvez demore um pouco para sair a próxima versão pois você precisa realizar todos os updates em ordem.

Legal saber que teremos uma atualização do sistema, tem algum lugar aqui que consigo ver as novidades que virão nesse update?

**Comment by maycon1977** [comment]
> Eu recomendo você realizar o update para a versão v.3.15.0 mesmo que talvez demore um pouco para sair a próxima versão pois você precisa realizar todos os updates em ordem.

Eu já fiz um update alternativo pra testar e ficou de boa... O lance é que tem algumas personalizações que uso no meu sistema e que eu precisarei fazer no que vier a utilizar (e passarei pra vocês decidirem se vale a pena). se fizer isso no 3.15, terei instalar o "4.0 limpo" e fazer novamente as modificações ou vc acha que vai dar pra eu agregar ao meu 3.15 personalizado um update do 4.0?

Mais uma vez obrigado, @Pr3d4dor!

**Comment by Pr3d4dor** [comment]
> > Eu recomendo você realizar o update para a versão v.3.15.0 mesmo que talvez demore um pouco para sair a próxima versão pois você precisa realizar todos os updates em ordem.
> 
> Eu já fiz um update alternativo pra testar e ficou de boa... O lance é que tem algumas personalizações que uso no meu sistema (que podem ajudar o pessoal e algumas que são bem específicas) e que eu precisarei fazer no que vier a utilizar (e passarei pra vocês decidirem se vale a pena fazer um merge ao sistema novo). Se fizer isso no 3.15, terei que instalar o "4.0 limpo" e fazer novamente as modificações ou vc acha que vai dar pra eu agregar ao meu 3.15 personalizado um update do 4.0?
> 
> Mais uma vez obrigado, @Pr3d4dor!

Eu recomendo você esperar sair a próxima versão e fazer a atualização limpa e após isso aplicar suas modificações. Após isso se quiser compatilhar com os demais é só abrir PR's aqui no GitHub com suas contribuições.

**Comment by Pr3d4dor** [comment]
> > > > Obrigado pelas informações estamos já trabalhando em algumas coisas e logo a versão v.4.0.0 será lançada.
> > > 
> > > 
> > > Olá, Pr3d4dor...
> > > mas já temos uma previsão real da data de lançamento da versão 4?
> > > pergunto porque estou para fazer a migração do meu MAPOS que é antigaço e ia migrar pro 3.15.0, mas se o 4.0 estiver próximo vou esperar mais um pouco...
> > 
> > 
> > Não tem uma data exata, falta apenas fazer o merge de todas as PR's atuais e a versão v.4.0.0 será lançada.
> > Eu recomendo você realizar o update para a versão v.3.15.0 mesmo que talvez demore um pouco para sair a próxima versão pois você precisa realizar todos os updates em ordem.
> 
> Legal saber que teremos uma atualização do sistema, tem algum lugar aqui que consigo ver as novidades que virão nesse update?

Você consegue ver as novas coisas que foram implementadas na aba de PR's. No changelog.md existe a descrição do que exatamente foi implementado após a realização do merge.

**Comment by romerorigon** [comment]
Preciso muito de um campo de assinatura, ficaria perfeito nesse software
