### ISSUE TITLE
erro na pesquisa 

### ISSUE THREAD

**Issue by starkcel** [RamonSilva20/mapos#583]
Quando vou em pesquisar da erro 404

meudominio.com/sys/mapos/pesquisar?termo=teste

na versão antiga tudo esta funcionando normal

**Comment by tonisempa** [comment]
Aqui da pagina não encontrada tbm, se alguém conseguir resolver vai ajudar mt

**Comment by feerlucas** [comment]
https://github.com/RamonSilva20/mapos/issues/567 esse link resolve!

**Comment by jardeldint** [comment]
Na linha 80 do topo.php (temas), tem o código.
`<form action="<?= base_url('mapos/pesquisar') ?>">`
Eu resolvi colocando apenas o index.php... ficou assim...
`<form action="<?= base_url('index.php/mapos/pesquisar') ?>">`
Aqui deu tudo certo!

**Comment by Pr3d4dor** [comment]
Essa correção já foi aplicada, basta esperar o lançamento da próxima edição do mapos.
