### ISSUE TITLE
Adicionar Campo para cadastro de carros, para uso em oficinas mecânicas!

### ISSUE THREAD

**Issue by FilipeCm** [RamonSilva20/mapos#585]
Olá. Meu nome é Filipe C Martins, sou dono de uma pequena oficina de eletronica e GNV e eu achei incrível o trabalho feito aqui nessa plataforma.

Gostaria de deixara o meu pedido de que adicionem por gentileza uma opção de cadastros de caros que também tenha como ser lincado ao usuário cadastrado!

Muito obrigado!!!

**Comment by Bremyarck** [comment]
Já estou implementando essa funcionalidade, porem, não sei se agrada a todos publicar a atualização.

**Comment by Kajueiro** [comment]
Boa tarde @Bremyarck !
Eu também estou procurando por isso, vc poderia disponibilizar os arquivos com suas implementações?
Grato!

**Comment by mmonzato** [comment]
https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i

**Comment by Pr3d4dor** [comment]
Já foi feita uma PR com essa funcionalidade: #575

Vamos esperar a resposta do @RamonSilva20 quanto à utilidade do sistema.

**Comment by wnjinfo** [comment]
Olá, também estou a procura de algo assim, seria possivel adicionar o módulo de veiculo para criar OS para o veiculo e amarrar ao cliente, independente do número de placas, ja que pode ser um cliente corporativo com uma frota.
