### ISSUE TITLE
Não aparecem os icons quando esta no servidor

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#586]
Eu uso um raspberry pi 3+ para servir de servidor.
Tenho usado uma versão anterior sem qualquer problema.
Ontem fiz a alteração para a ultima versão que esta disponível com as minhas alterações, testo sempre tudo no PC com o Xampp, tudo esta a trabalhar.
Quando fui testar o mapos no servidor não me aparecem os icons. O site abre e é possível trabalhar mas sem icons. E a data em cima esta em inglês. 
Já aconteceu a mais alguém?
Aconteceu depois destas ultimas actualizações mais profundas. Logo no fim do dia vou testar o mapos tal como esta sem alterações e verificar se acontece o mesmo.
Obrigado

**Comment by LipzyLipzy** [comment]
Acabei de testar a versão original disponível e não aparecem os icons.
![mapos no servidor pi](https://user-images.githubusercontent.com/49565606/75576293-17bb6380-5a58-11ea-909b-ddeb3083a0b1.jpg)

Na versão 3.8 estava tudo OK
Alguém pode ajudar a resolver?
Obrigado

**Comment by RamonSilva20** [comment]
Olá. Fizeram a limpeza do cache? Ctrl + F5.

**Comment by LipzyLipzy** [comment]
Ramom obrigado ficou resolvido o problema. Não tinha feito.
Só permanece o dia em ingles, no meu mapos deixei ficar a informação do dia e mes.

Obrigado
