### ISSUE TITLE
Sistema de multi-empresa ou filial

### ISSUE THREAD

**Issue by britoriquee** [RamonSilva20/mapos#587]
Seria interessante adicionar uma opção de multi-empresa ou filial, onde o controle de ordem de serviços, estoque, etc seriam separados por filial

**Comment by Pr3d4dor** [comment]
Isso entra no tópico de multi tenancy e leva um grande tempo para ser implementado.

Vamos deixar aqui essa issue, analisar e se possível implementar no futuro.

**Comment by edgarmeireles** [comment]
Tenho um sistema em Java. No cadastro de empresas a empresa 1 é a matriz e as demais são as filiais. No banco, basicamente todas as tabelas tem o campo codFilial, ai na ordem de compra por exemplo, selecionamos a filial e no banco salva o ID dessa filial. 

Acredito que boa parte das tabelas tenham que ser editadas para esse padrão, mas não acredito que seja tão complicado de incluir isso nos controllers.
