### ISSUE TITLE
Erro ao restaurar banco

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#589]
Oi,

Não sei se é a área certa mas migrei de server na host, salvei o banco e copiei os mesmo arquivos e restaurei o banco e tá com seguinte erro apos login

"{"result":false,"message":"Os dados de acesso est\u00e3o incorretos."}"

**Comment by Pr3d4dor** [comment]
Acho que você esqueceu de configurar as credenciais do banco de dados no arquivo: `application/config/database.php`

**Comment by matheuscorteletti** [comment]
vou subir de novo os arquivos... e tentar novamente

**Comment by matheuscorteletti** [comment]
Os erros são os seguintes:
Na tela de login aparece:
"Os dados de acesso estão incorretos, por favor tente novamente!"
Coloco usuário e senha e fica uma página branca:
"{"result":true}" acabo entendendo que a senha e email tá ok
"index.php/servicos" fico logado!
![1](https://user-images.githubusercontent.com/61605704/75734941-113b1f00-5cd8-11ea-9e70-019a2879f2c8.png)
![2](https://user-images.githubusercontent.com/61605704/75734945-126c4c00-5cd8-11ea-980f-53d86c55d87e.png)
![3](https://user-images.githubusercontent.com/61605704/75734946-126c4c00-5cd8-11ea-8ba6-5340139830c1.png)

**Comment by matheuscorteletti** [comment]
e mesmo instalando do zero continua com esse erro na tela
![1](https://user-images.githubusercontent.com/61605704/75738968-6bd97880-5ce2-11ea-8ffb-d57184ae1921.png)

**Comment by matheuscorteletti** [comment]
Era só limpar o cache do navegador wtf kkkkk

**Comment by Pr3d4dor** [comment]
Eu ia sugerir isso mesmo, mas que bom que funcionou.

Vou fechar a issue, caso precise de mais ajuda pode comentar novamente.
