### ISSUE TITLE
Erro no cadastro de produto

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#59]
A Database Error Occurred

Error Number: 1054

Unknown column 'saida' in 'field list'

INSERT INTO `produtos` (`descricao`, `unidade`, `precoCompra`, `precoVenda`, `estoque`, `estoqueMinimo`, `saida`, `entrada`) VALUES ('Placa de Vídeo Usada', 'UN', '0.00', '60.00', '10', '1', '1', '1')

Filename: models/Produtos_model.php

Line Number: 38

**Comment by RamonSilva20** [comment]
Boa noite @SOROInfo. Atualize o banco de dados para a versão 3.1.9, com o arquivo update_v3.1.x_to_3.1.9.sql dentro de updates.
