### ISSUE TITLE
Inserção de campo no cadastro do cliente.

### ISSUE THREAD

**Issue by dintmktdb** [RamonSilva20/mapos#590]
No dia a dia de um cliente, foi percebido a necessidade de um campo, onde se cadastrasse algum ponto de referência, para assim, qdo for feito a ordem de serviço externa, também pudesse ver com mais detalhes onde é o endereço do atendimento.

** Descreva a solução que você deseja **
Nas views de cadastro e edição de clientes, criei mais um campo chamado ptoref (ponto de referência). Após, fiz a alteração da tabela cliente, inserindo o campo ptoref, como varchar 700, pois é um campo com bastante detalhes em sua maioria.
Em seguida eu fui em controllers e adicionei os campos na inserção e edição para que os dados fossem gravados no banco. E por último, fui na views/os e na visualização e impressão, adicionei as informações do campo criado, no local onde está os dados do cliente.
Para facilitar também, principalmente para emissão de laudos técnicos (para seguradoras e cias de energia), na views/os em visualizar e imprimir, adicionei tbm a impressão/visualização do cpf/cnpj do cliente, pois este campo é necessidade que apareça na ordem de serviços/laudo técnico.

** Contexto adicional **
Por questões do caso de meu cliente, eu fiz mais uma alteração na views/os/visualizar e editar, no qual tem um espaço com linhas, para que o cliente possa escrever os serviços executados, manualmente no atendimento in-loco.

**Comment by Pr3d4dor** [comment]
Você está pedindo essa feature ou consegui implementa-lá no seu mapos local?}

Se sim você pode fechar essa issue e abrir uma PR com a contribuição.

**Comment by jardeldint** [comment]
Olá Pr3d3dor.... esta implementação eu fiz. Está funcionando perfeitamente no cadastro, visualização e impressão.

**Comment by maycon1977** [comment]
> Você está pedindo essa feature ou consegui implementa-lá no seu mapos local?}
> 
> Se sim você pode fechar essa issue e abrir uma PR com a contribuição.

Dá pra colocar como opcional. Rola tb com aquela contribuição do amigo que queria cadastrar veiculos de clientes (ou equipamentos no meu caso que tb quero adaptar).

Eu fiz isso com alguns Campos no meu MAPOS. Se eu preencho os dados daquela célula, eles aparecem na impressão final, se eu não preencher, o espaço correspondente é surprimido... Dessa forma não fica aquele monte de campo em branco na impressão da O.S. Quando necessário maior espaço de impressão mexo na porcentagem de impressão e funfa de boa!

Tô aguardando ansiosamente o MAPOS 4.0 pra ir novamente personalizando e passando as PRs que vcs acharem legais... Eu mexi tanto no meu que já não sei mais o que era padrão, o que já foi efetivado pelos amigos e o que eu fiz que ainda pode virar PR.

**Comment by dintmktdb** [comment]
Quando eu faço atualizações para clientes, e as mesmas não tenham sido aprovadas pelos devs do mapos, eu apenas salvo as views (no meu caso) e após a atualização, apenas faço o upload das views antigas. Na real, algumas preciso tbm das controlers. Até agora não precisei fazer mudanças no models.

**Comment by maycon1977** [comment]
> Quando eu faço atualizações para clientes, e as mesmas não tenham sido aprovadas pelos devs do mapos, eu apenas salvo as views (no meu caso) e após a atualização, apenas faço o upload das views antigas. Na real, algumas preciso tbm das controlers. Até agora não precisei fazer mudanças no models.

Mexi pouco fora das views (Principalmente nas impressões), mas não fiz documentação alguma, fui fazendo de forma meio intuitiva (engenharia reversa, pois não sou programador). Trabalho muito com Ordens de Serviço, quase não uso o módulo de vendas, então essa parte pra mim já tá bem legal... Acredito que algumas coisas que fiz podem interessar, então na versão nova vou editando e passando aqui. Se for do interesse de todos, blz.

**Comment by Pr3d4dor** [comment]
@dintmktdb já que vc já realizou a implementação você poderia abrir uma PR para contribuir com o código agora que versão 4.0.0 foi lançada.

**Comment by dintmktdb** [comment]
Como faço isso? Não entendo de Github...

**Comment by Pr3d4dor** [comment]
Você precisa realizar um fork do projeto com sua conta no GitHub e após isso fazer suas modificações, enviar elas para o teu fork do projeto e após isso quando vc voltar no GitHub vai ter a opção para criar a Pull Request (PR) para o projeto do mapos.

https://imasters.com.br/desenvolvimento/como-contribuir-com-um-projeto-no-github
