### ISSUE TITLE
ATUALIZAÇÃO

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#591]
Pessoal tenho dúvidas rs
Não sou muito expert nessa área e preciso de ajuda. 
Tenho uma pasta no meu servidor com os arquivos do MAPOS e um banco de dados. 
O sistema já está online e rodando certinho, mas com a versão 3.14. 
Não sei como fazer a atualização e gostaria de saber se alguém tem um vídeo ou passo a passo com imagens de como fazer a atualização. 
Chego nesta etapa e travo:

> 3. Rode o comando composer install --no-dev a partir da raiz do projeto.

Vocês poderiam dar um auxílio se não for muito incomodo? 

Uma outra coisa importante também, tenho algumas modificações/acréscimo de informações nos códigos em alguns arquivos da pasta "Views" por exemplo, no " imprimirOs" . A atualização afetaria essas modificações?

Se alguém puder dar uma resposta eu agradeço imensamente.
Obrigado pessoal, parabéns pelo projeto, é fodamente fodástico!
Abrass!

**Comment by Pr3d4dor** [comment]
Você precisa atualizar para a versão 3.15 antes de atualizar para a versão 4.0.0.

Ao atualizar você poderá perder suas modficações.

Quando vc atualizar vc terá que realizar novamente essas modificações no seu código.

**Comment by guskid** [comment]
> Você precisa atualizar para a versão 3.15 antes de atualizar para a versão 4.0.0.
> 
> Ao atualizar você poderá perder suas modficações.
> 
> Quando vc atualizar vc terá que realizar novamente essas modificações no seu código.

Obrigado pela ajuda Pr3d4dor. 
E sobre fazer a atualização, tentei procurar em vários lugares, mas ainda estou empacado. 
Você poderia me dar um help cara?
Sei que deve ser super simples, mas sou muito leigo nessa parte de "rodar o comando no composer". Desculpe a pergunta besta... 
Obrigado cara, um abraço!

**Comment by JulianoSavino** [comment]
Eu tambem não consegui nessa parte do composer.
Na verdade estou confuso se posso fazer instalaçao limpa no 4.1 com minha base 3.15 e só depois processar o update?
tambem essa questão do composer, já até baixei um instalador e não resolveu. Uso no xampp e se vou pelo cmd como administrador, sempres recebo a mensagem:

c:\xampp\htdocs\mapos>composer install --no-dev
'composer' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Se conseguirem ajudar, agradecemos @Pr3d4dor @RamonSilva20 @willph

**Comment by BESystemInfo** [comment]
Aqui também tive dúvidas, mas com a ajuda dos comentários do pessoal e algumas fuçadas, consegui.
Primeiro instalie o Composer (https://getcomposer.org/download/) . Ele deve aparecer uma tela falando da versão do Xampp que você está utilizando. (Por via das dúvidas, reinicia o computador depois de instalado).
Depois disso abri o CMD como Administrador, naveguei até a pasta do mapos no Xampp e rodei o comando composer update.
Depois disso o sistema funcionou. 
Quanto a DB da versão anterior, o único detalhe é que se em Garantia nas OS vc colocou algo além de números (Ex. 30 Dias), tem que remover todos os "Dias" dos campos (No meu caso foi simples pois ainda tenho poucas OS's no Mapos.) Ele agora aparentemente ele só aceita números. Porém teve comentários de que iriam rever essa parte.
