### ISSUE TITLE
Parcelamento da fatura

### ISSUE THREAD

**Issue by dintmktdb** [RamonSilva20/mapos#592]
Tenho uma sugestão para os devs. 
Seria interessante criar uma rotina onde que no faturamento da os/venda o usuário pudesse parcelar a venda para o cliente. Por exemplo: fecho a venda e o cliente precisa parcelar em 3x. Então clico em uma checkbox chamada parcelamento e aparece ao lado a qtde de parcelas. Aí o mapos gera cobranças recorrentes daquela OS/venda, até o número máximo digitada.
Outra questão, que tbm faz parte do faturamento, seria na configuração do emitente, ter uma aba onde é configurada as formas de recebimento. Por exemplo: cadastrar a forma de cartão de crédito, onde possa editar o percentual de juros e taxas (ou já deixar configurado as formas comuns, como PagSeguro, mercadoPago, PayPal. etc). Assim, qdo for faturado alguma os/venda, e o cliente escolher como pagar no cartão de crédito, assim que faturar já cai o valor real (total menos taxas configuradas).

**Comment by Pr3d4dor** [comment]
Essa feature já foi requisitada e está na nossa lista de futuras implementações.

**Comment by dintmktdb** [comment]
Ótimo. showw.
