### ISSUE TITLE
Instalar composer com hospedagem hostinger

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#593]
Tenho o MapOs instalado em um servidor na hostinger, porém minha hospedagem é aquela mais baratinha, de R$109,00 por 4 anos de hospedagem, e não da acesso ao shell para instalação do composer. Tem alguma solução para isso nesse caso?
Não conheço o composer. Me desculpem se minha pergunta for muito noob.

**Comment by Pr3d4dor** [comment]
Você pode instalar o composer localmente e rodar o comando `composer install` localmente no seu computador.

Após isso você pode subir os arquivos da pasta `application/vendor` e também o arquivo de autoload.php para sua hospedagem.

**Comment by robsonmeca** [comment]
Maravilha! Muito obrigado!

**Comment by maycon1977** [comment]
Olá, pessoal.

Me perdi completamente nesse passo aí do "composer install --no-dev". Utilizo Hostgator e sempre instalei de boa as versões inferiores do MAPOS sem precisar desse passo. 

já li uns 3 tópicos diferentes aqui do pessoal tentando explicar mas não entendi nada. tenho acesso ao GERENCIADOR de ARQUIVOS da Hospedagem e ao FTP também. Já baixei um programa de PHP um outro COMPOSER e só consegui dar várias cabeçadas sem sair do lugar...

Alguém poderia colocar de forma bem noobie pra me ajudar (e quem sabe a outros amigos)?

**Comment by Pr3d4dor** [comment]
@maycon1977 você precisa entrar na pasta onde seu mapos está instalado.

Depois você precisa abrir um terminal dentro dessa pasta. No terminar você deve rodar o comando `composer install`. Após isso ele irá instalar todas as dependencias do projeto na pasta `vendor`.

Após realizar isso você deve pegar essa pasta `vendor` e upar ela na sua hospedagem via FTP.
