### ISSUE TITLE
INSTALAÇÃO MAPOS 4.1.0 EM DOMÍNIO PRÓPRIO

### ISSUE THREAD

**Issue by britoriquegbi** [RamonSilva20/mapos#594]
Estou tentando instalar o sistema em meu domínio (locaweb) mas sempre da erro de path, por gentileza, coloquem um arquivo explicando como instalar manualmente o sistema (virgem).

**Comment by mmonzato** [comment]
@britoriquegbi instala ele localmente com o composer e depois sobe as pastas que deve funcionar na sua hospedagem.

**Comment by Bremyarck** [comment]
## Ambiente Windows
* Baixe e instale o [composer](https://getcomposer.org/Composer-Setup.exe).
* Abra o cmd do windows e navegue até a pasta raiz do sistema usando o cmd ex: "cd c:\xampp\htdocs\mapos".
* Ainda no cmd execute o comando "composer update".
* Pronto o sistema já pode executar sem problema algum.

**Comment by rafaeldfoy** [comment]
> ## Ambiente Windows
> * Baixe e instale o [composer](https://getcomposer.org/Composer-Setup.exe).
> * Abra o cmd do windows e navegue até a pasta raiz do sistema usando o cmd ex: "cd c:\xampp\htdocs\mapos".
> * Ainda no cmd execute o comando "composer update".
> * Pronto o sistema já pode executar sem problema algum.

Fiz esse procedimento e funcionou... Obrigado!

**Comment by gilbertoalmeida16** [comment]
> Estou tentando instalar o sistema em meu domínio (locaweb) mas sempre da erro de path, por gentileza, coloquem um arquivo explicando como instalar manualmente o sistema (virgem).

opa amigo tenho um tutorial bacana lá no youtube acredito que ira te ajudar muito.
youtube.com/watch?v=mo7vn4ws03g

lá simulo alguns erros que podem acontecer, acredito que ira te ajudar muito, tambem tem como rodar o composer dentro da hospedagem... vai la e depois me da um feddback por lá mesmo ok abs
