### ISSUE TITLE
Menu não aparece corretamente no navegador de smartphone

### ISSUE THREAD

**Issue by CaramujoRei** [RamonSilva20/mapos#596]
Bom dia,

Tenho um redmi note 7, android 9.

Subi a ultima versão do sistema, está rodando tudo ok. Porém ao abrir pelo smartphone, as opções do menu (produto, vendas, etc) ficam apagadas conforme imagem em anexo ( https://1drv.ms/u/s!AlNtEsA8IMH-g40fdeUqwgGbpj8gcA?e=Xc0Pla ) aparecendo somente os icones.

**Comment by CaramujoRei** [comment]
https://photos.app.goo.gl/TdCrTtNYRmXeGhvA7

**Comment by Pr3d4dor** [comment]
Iremos verificar.

**Comment by CaramujoRei** [comment]
Problema estava na cor da fonte

**Comment by ludero** [comment]
> Problema estava na cor da fonte

Conseguiu achar a solução?

**Comment by delta7tecnologia** [comment]
Troquei para o navegador brave e solucionou o problema citado
