### ISSUE TITLE
Erro na tela de OS e Serviços

### ISSUE THREAD

**Issue by igoatier** [RamonSilva20/mapos#597]
** Descreva o bug **
atualizei para a versão 4.1.0 mais agora a tela de OS e Serviço não está mostrando nada imagem abaixo.
já revi todas as configurações e nada.

aguardo retorno sobre essa situação

![erro na tela os](https://user-images.githubusercontent.com/53308164/76087199-6d31cc00-5f94-11ea-8c4a-ecd6c1f8632b.JPG)

**Comment by BESystemInfo** [comment]
Amigo, tive um caso parecido. Verifique suas configurações de Garantia. No meu caso e de outro colega, as garantias estavam escritas "30 Dias", e este campo deve conter somente números (No caso, somente o 30). Verifique se não é o mesmo caso (Confirme na DB que a coluna Garantia contenha somente números).
Contudo, o Ramon já havia dito que na próxima atualização deve incrementar a correção para essa questão.

**Comment by igoatier** [comment]
Bom dia amigo.
Muito obrigado pelo retorno e realmente o erro erra esse, fiz a modificação
e funcionou corretamente



Igo Atiê

Graduado em GTI
Especialista em Governança de TI
MBA em Gestão de Processos
Analista de TI
(75)99849-3314
(94)99175-2239
Skype: igo.atier
Currículo Lattes: Igo Atie Oliveira Santos
http://lattes.cnpq.br/9231873335128937

Em sex, 6 de mar de 2020 10:49, BESystem Serviços de Informática <
notifications@github.com> escreveu:

**Comment by BESystemInfo** [comment]
Que bom que conseguiu. Não manjo de programação, sou apenas um fuçador, mas quando posso ajudar, ajudo. ;)

**Comment by romerorigon** [comment]
Tenho o mesmo problema ao visualizar uma OS Finalizada
Já busquei no DB e removi as entradas que continham "dias" escrito ao lado, deixei tudo em branco, mesmo assim o erro persiste 
![erromapos](https://user-images.githubusercontent.com/61893506/76133731-5ae97980-5ff8-11ea-9d16-d8e55a3ff31c.PNG)

**Comment by willph** [comment]
> Tenho o mesmo problema ao visualizar uma OS Finalizada
> Já busquei no DB e removi as entradas que continham "dias" escrito ao lado, deixei tudo em branco, mesmo assim o erro persiste
> ![erromapos](https://user-images.githubusercontent.com/61893506/76133759-7e142900-5ff8-11ea-8a50-b5b202a42bcb.PNG)

espaço também conta. Tem que ter apenas o número. Ex: "30" se tiver assim "30 " ou " 30". Tem que conter apenas números sem espaços.

**Comment by romerorigon** [comment]
> > Tenho o mesmo problema ao visualizar uma OS Finalizada
> > Já busquei no DB e removi as entradas que continham "dias" escrito ao lado, deixei tudo em branco, mesmo assim o erro persiste
> > ![erromapos](https://user-images.githubusercontent.com/61893506/76133759-7e142900-5ff8-11ea-8a50-b5b202a42bcb.PNG)
> 
> espaço também conta. Tem que ter apenas o número. Ex: "30" se tiver assim "30 " ou " 30" vai falhar. Tem que conter apenas números sem espaços.

Resolvi parcialmente voltando o visualizarOs.php da versão 3.14
