### ISSUE TITLE
divergencia no faturamento

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#599]
dai galera tudo certo ? entao, ao faturar uma OS com serviços e produtos, se eu alterar o valor manualmente pra dar um desconto pro cliente, na OS e no Relatorio de OS ele mostra o valor cheio e nao identifica que foi dado desconto. ai acaba nao trazendo o valor realmente pago pelo cliente. seria legal que de alguma forma tivesse um campo de desconto, ou ao menos identificasse nos relatorios e tambem na OS impressa e certamente na tela que esse valor foi alterado. pois se eu conferir o valor do caixa com o valor das OS impressas que foram faturadas com algum desconto nao ta batendo. infelizmente nao sei como resolver. gostaria muito de poder ajudar, mas meu conhecimento nao me permite.

**Comment by Pr3d4dor** [comment]
Iremos verificar isso

**Comment by giampaulo** [comment]
Alguma novidade referente a esse problema ?

**Comment by Pr3d4dor** [comment]
Ainda não, estamos resolvendo mais alguns problemas antes.

Se conseguir corrigir pode mandar uma pull request.

**Comment by giampaulo** [comment]
@Pr3d4dor desculpe. Mas infelizmente não sei como resolver. Se soubesse como ajudar prontamente o faria. Só perguntei pq meu cliente me cobrou.

**Comment by Pr3d4dor** [comment]
Até o desconto ser implementado de vez você pode criar um produto ou serviço chamado "Desconto" e manualmente ir no banco de dados e alterar o seu valor para -1.00.

Assim você pode adicionar esse produto ou serviço que quiser na sua OS e realizar o desconto necessário.

**Comment by giampaulo** [comment]
Excelente ideia. Obrigado
