### ISSUE TITLE
Campos de descrição da OS com poucos caracteres

### ISSUE THREAD

**Issue by atendeemcasa** [RamonSilva20/mapos#6]
A Database Error Occurred

Error Number: 1406

Data too long for column 'defeito' at row 1

INSERT INTO `os` (`dataInicial`, `clientes_id`, `usuarios_id`, `dataFinal`, `garantia`, `descricaoProduto`, `defeito`, `status`, `observacoes`, `laudoTecnico`, `faturado`) VALUES ('2016-09-07', '4', '1', '2016-09-07', '', 'Feito limpeza sistema de arrefecimento e troca de pasta termica do processador', 'CPU com superaquecimento\r\nCliente diz que maquina nao carrega bateria, foi verificado carregador e jack ac do aparelho, tudo OK. Provavelmente cliente fazendo algo de errado.', 'Aberto', '', '', 0)

Filename: D:\Wamp64\www\mapos\system\database\DB_driver.php

Line Number: 330

**Comment by RamonSilva20** [comment]
Altere o campo 'defeito' para o tipo TEXT no banco de dados.
