### ISSUE TITLE
impressao de NF

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#600]
existe a possibilidade de integrar de alguma forma com algum serviço pra poder emitir NFe, NFSe e NFCe?

**Comment by Pr3d4dor** [comment]
Provavelmente não iremos implementar isso porque as regras de notas fiscais mudam conforme a cidade.

Então cada um vai ter que realizar a sua implementação pois não podemos fazer uma implementação genérica que funcione em todas as cidades
