### ISSUE TITLE
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#603]
depois de instalado NOVO ou atualizado oque ja tenho da esse erro

Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by BESystemInfo** [comment]
Verifica essa Issue, deve ser o seu caso:
[https://github.com/RamonSilva20/mapos/issues/594](url)

**Comment by wesley020291** [comment]
> Verifique essas edições, execute o seu caso:
> [https://github.com/RamonSilva20/mapos/issues/594 ](url)
> [https://github.com/RamonSilva20/mapos/issues/598](url)

nao funciona mesmo testei em 2 hospedagem e da mesmo erro.
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by heraf250** [comment]
tbm estou nessa mesma situação

**Comment by BESystemInfo** [comment]
Você está utilizando hospedagem gratuíta? Se sim, já testou efetuar o update do composer localmente antes de subir para a hospedagem?
No meu caso uso a hospedagem da AwardSpace. Fiz o processo primeiramente no meu computador, com o Xampp como servidor, e depois subi na hospedagem e está funcionando perfeitamente. 
Faça o teste localmente para ver se também não resolve.

**Comment by wesley020291** [comment]
composer  oque E e onde esta isso?

**Comment by heraf250** [comment]
> Você está utilizando hospedagem gratuíta? Se sim, já testou efetuar o update do composer localmente antes de subir para a hospedagem?
> No meu caso uso a hospedagem da AwardSpace. Fiz o processo primeiramente no meu computador, com o Xampp como servidor, e depois subi na hospedagem e está funcionando perfeitamente.
> Faça o teste localmente para ver se também não resolve.

o meu configurei o composer e foi na hora
muito obrigado

**Comment by heraf250** [comment]
> composer oque E e onde esta isso?

copia e cola esse link https://github.com/RamonSilva20/mapos/issues/594
que vc vai ver a solução

**Comment by BESystemInfo** [comment]
> > Você está utilizando hospedagem gratuíta? Se sim, já testou efetuar o update do composer localmente antes de subir para a hospedagem?
> > No meu caso uso a hospedagem da AwardSpace. Fiz o processo primeiramente no meu computador, com o Xampp como servidor, e depois subi na hospedagem e está funcionando perfeitamente.
> > Faça o teste localmente para ver se também não resolve.
> 
> o meu configurei o composer e foi na hora
> muito obrigado

Que bom que conseguiu. Mais um colega ajudado :)

**Comment by BESystemInfo** [comment]
> composer oque E e onde esta isso?

Pra facilitar, segue os passos para fazer localmente:

Baixe e instale o  Composer: [https://getcomposer.org/Composer-Setup.exe](url).
Abra o cmd do windows e navegue até a pasta raiz do sistema usando o cmd ex: "cd c:\xampp\htdocs\mapos".
Ainda no cmd execute o comando "composer update".
Pronto o sistema já pode executar sem problema algum.

**Comment by wesley020291** [comment]
UFAAA deu certo. nao entendi porque tem que usar esse composer?

**Comment by BESystemInfo** [comment]
A explicacao mais simples que encontrei...

https://king.host/blog/2018/02/composer-o-que-e-como-instalar-como-usar/

**Comment by petersoncameras** [comment]
Pessoal, boa noite, instalei o composer na minha hospedagem da UMBLER, mas mesmo assim ainda aparece o erro:

**Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php**

Segue informações obtidas do GITBASH:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 37 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (1.0.2): Downloading (100%)
  - Installing doctrine/annotations (v1.4.0): Downloading (100%)
  - Installing doctrine/reflection (1.2.0): Downloading (100%)
  - Installing doctrine/event-manager (1.1.0): Downloading (100%)
  - Installing doctrine/collections (1.6.4): Downloading (100%)
  - Installing doctrine/cache (1.10.0): Downloading (100%)
  - Installing doctrine/persistence (1.3.7): Downloading (100%)
  - Installing doctrine/inflector (1.3.1): Downloading (100%)
  - Installing doctrine/common (2.12.0): Downloading (100%)
  - Installing mercadopago/dx-php (1.8.0): Downloading (100%)
  - Installing psr/log (1.1.3): Downloading (100%)
  - Installing paypal/rest-api-sdk-php (1.14.0): Downloading (100%)
  - Installing codeigniter/framework (3.1.11): Downloading (100%)
  - Installing myclabs/deep-copy (1.9.5): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Downloading (100%)
  - Installing setasign/fpdi (v2.3.2): Downloading (100%)
  - Installing mpdf/mpdf (v8.0.5): Downloading (100%)
  - Installing fzaninotto/faker (v1.9.1): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing symfony/service-contracts (v1.1.8): Downloading (100%)
  - Installing symfony/stopwatch (v4.4.5): Downloading (100%)
  - Installing symfony/process (v4.4.5): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.14.0): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.14.0): Downloading (100%)
  - Installing symfony/options-resolver (v4.4.5): Downloading (100%)
  - Installing symfony/finder (v4.4.5): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.14.0): Downloading (100%)
  - Installing symfony/filesystem (v4.4.5): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Downloading (connectDownloading (100%)
  - Installing symfony/event-dispatcher (v4.4.5): Downloading (100%)
  - Installing symfony/polyfill-php73 (v1.14.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.14.0): Downloading (100%)
  - Installing symfony/console (v4.4.5): Downloading (100%)
  - Installing php-cs-fixer/diff (v1.3.0): Downloading (100%)
  - Installing composer/xdebug-handler (1.4.1): Downloading (100%)
  - Installing composer/semver (1.5.1): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.16.1): Downloading (100%)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
setasign/fpdi suggests installing setasign/fpdf (FPDI will extend this class but as it is also possible to use TCPDF or tFPDF as an alternative. There's no fixed dependency configured.)
mpdf/mpdf suggests installing ext-bcmath (Needed for generation of some types of barcodes)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/event-dispatcher suggests installing symfony/http-kernel
symfony/console suggests installing symfony/lock
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-isidenticalstring (For IsIdenticalString constraint.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-xmlmatchesxsd (For XmlMatchesXsd constraint.)

**Comment by Pr3d4dor** [comment]
O composer realmente conseguiu instalar as dependências?

**Comment by petersoncameras** [comment]
Primeiramente agradeço a disponibilidade em ajudar.
Vou ser sincero, não tenho conhecimento sobre composer, segui os passos que encontrei na internet e nesta comunidade, acredito que tenha sido instalado sim.

Seria pedir muito para me ajudar com essa instalação ?, passo os dados da minha hospedagem para você se for o caso, é claro, se puder me ajudar.

**Comment by Pr3d4dor** [comment]
Antes de me passar as credenciais, peço para que vc exclua tudo e refaça todo o procedimento de instalação do zero.

Verifique se vc rodou o comando na pasta correta.

Caso ainda não dê certo eu posso tentar te ajudar.

**Comment by petersoncameras** [comment]
Vou detalhar para você o que fiz, e ai me diz se fiz algo errado, podemos começar assim ?.
Para mim o interessante mesmo seria aprender a rodar isso, estou desde ontem tentando, rsrs.

Apaguei tudo que tinha na minha hospedagem, dentro da pasta public joguei os arquivos do sistema mapos.

Os arquivos composer.json e composer.lock coloquei na raiz da hospedagem.
Após isso, conectei via ssh e rodei o comando composer update, o processo de download e instalação das dependências foi iniciado conforme postei o log mais acima.

Na minha hospedagem acabou ficando assim os diretórios:
.composer
.ssh
application
public
tmp
.bash_history
.bash_profile
composer.json
composer.lock
composer.phar

Tentei acessar meu domínio www.petersoncameras.com.br/app e o erro do título foi apresentado.
Movi os arquivos da pasta /public/app e deixei apenas dentro da pasta /public
Tentei acessar novamente meu domínio, mas dessa vez www.petersoncameras.com.br e o erro continua.

**Comment by petersoncameras** [comment]
Amigo, depois de muita luta, consegui realizar a instalação.

Realmente eu havia executado o composer update em uma pasta errada.
Peguei as pastas .composer e application que estava no diretório raiz da hospedagem, fora da public, movi para a public e deu certo.

Mais um aprendizado.
Agradeço imensamente por se dispor a me ajudar.

**Comment by Pr3d4dor** [comment]
De nada, fico feliz em ajudar.

**Comment by petersoncameras** [comment]
Boa noite, amigo.

Poderia me auxiliar em como fazer que o sistema envie a O.S por email?.

O envio do e-mail fica apenas com status de PENDENTE.

**Comment by heraf250** [comment]
> Boa noite, amigo.
> 
> Poderia me auxiliar em como fazer que o sistema envie a O.S por email?.
> 
> O envio do e-mail fica apenas com status de PENDENTE.

o meu ja ate removi a opçao email pq nao consegui ajeitar ele

**Comment by Pr3d4dor** [comment]
Vocês precisam configurar o cron corretamente e isso vai depender muito da hospedagem de vocês.

**Comment by petersoncameras** [comment]
E você poderia me explicar o que exatamente eu preciso configurar no cron ?.

**Comment by petersoncameras** [comment]
Deixei assim o arquivo email.php

$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.umbler.com';
$config['smtp_port']        = 587;
$config['smtp_user']        = 'meuemail@meudominio.com.br'; - obviamente inseri os dados aqui
$config['smtp_pass']        = 'minhasenha'; obviamente inseri os dados aqui
$config['validate']         = TRUE; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = FALSE;
$config['wordwrap']         = FALSE;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

**Removi as linhas:**
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['charset']          = 'utf-8';
Motivo: O servidor não tem certificação mas tem autenticação e não tem codificação.

**Comment by Pr3d4dor** [comment]
Passo 6 da instalação no README.md

**Comment by tecinfopi** [comment]
Estou com este mesmo erro hospedagem https://infinityfree.net/ e dominios  https://www.freenom.com/pt/index.html?lang=pt

**Comment by Pr3d4dor** [comment]
@tecinfopi Passo 6 da instalação no README.md caso você tenha cesso SSH no servidor.

Caso contrário, irá ter que rodar o composer na sua máquina e fazer o upload via ftp da pasta `aplication/vendor` para o servidor.

**Comment by tecinfopi** [comment]
boa noite não verdade me enganei estou tentando instalar é local
Obrigado pela atenção.... segue o print do erro.

att, valdecy 

    Em quarta-feira, 29 de abril de 2020 18:47:33 BRT, Gianluca Bine <notifications@github.com> escreveu:  
 
 


@tecinfopi Passo 6 da instalação no README.md caso você tenha cesso SSH no servidor.

Caso contrário, irá ter que rodar o composer na sua máquina e fazer o upload via ftp da pasta aplication/vendor para o servidor.

**Comment by Pr3d4dor** [comment]
@tecinfopi Desculpe mas não apareceu a print aqui.

**Comment by tecinfopi** [comment]
Boa tarde segue em anexo
    Em quarta-feira, 29 de abril de 2020 19:12:10 BRT, Gianluca Bine <notifications@github.com> escreveu:  
 
 


@tecinfopi Desculpe mas não apareceu a print aqui.

**Comment by Pr3d4dor** [comment]
@tecinfopi O GitHub não permite que você use imagens pelo email. Você precisa responder pelo GitHub para mostrar imagens.

**Comment by cefamigo** [comment]
Boa tarde! Fiz a instalação normal com composer , mas quando fui acessar o sistema ele deu usuário inexistente. Verifiquei no banco q nao havia usuário cadastro. Fiz um cadastro e ao executar ele reconhece o e-mail, mas não a senha. o que pode estar acontecendo? Desde já agradeço.

**Comment by Pr3d4dor** [comment]
@cefamigo depende de como você gravou a senha, pois ela é gravada criptografa e não em texto puro.

**Comment by cefamigo** [comment]
Foi em texto puro. Quando subi o banco ele foi sem usuário. Voce saberia me dizer como faço para gravar

**Comment by Pr3d4dor** [comment]
Você pode usar esse site e gerar o valor criptografado que tem que ser colocado no banco: https://passwordhashing.com/BCrypt

**Comment by cefamigo** [comment]
Obrigado. Vou testar aqui.

**Comment by cefamigo** [comment]
Pr3d4dor Muito obrigado. Gerou certinho. Deus abençoe
