### ISSUE TITLE
404 Page Not Found The page you requested was not found.

### ISSUE THREAD

**Issue by gasperpb** [RamonSilva20/mapos#604]
Após a configuração não loga e da esse erro.
detalhe a url fica assim.
http://localhost/mapos/index.php/index.php/login

**Comment by BESystemInfo** [comment]
Provavelmente ao instalar você colocou na url index.php, ao invés de terminar em mapos/. Tente alterar em application/config/config.php.

**Comment by gasperpb** [comment]
> Provavelmente ao instalar você colocou na url index.php, ao invés de terminar em mapos/. Tente alterar em application/config/config.php.

Obrigado era isso mesmo errei na configuração, agora aparece a mensagem.
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by BESystemInfo** [comment]
De uma olhada nessa Issue.
https://github.com/RamonSilva20/mapos/issues/603
