### ISSUE TITLE
Formatação na tela de OS

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#605]
** Descreva o bug **
A tela de OS aparece sem formatação CSS

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...' abra o programa
2. Clique em '....' Menu Ordens de Serviços
3. Role para baixo até '....' 
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [W10]
 - Navegador [Edge Chormium]
 - Versão [80
![formatacao-tela-os](https://user-images.githubusercontent.com/25686016/76327501-d97c3a80-62c8-11ea-8de1-939cea905ba0.PNG)
]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by BESystemInfo** [comment]
Este problema ocorre geralmente quando as garantias estão vazias, ou possuem dígitos que não sejam números, como letras e espaços. Verifique se é o seu caso e, caso positivo, remova tudo que não for número dos campos de garantia, inclusive espaços. Após isso, a visualização deve retornar ao normal.

**Comment by SOROInfo** [comment]
Que estranho. Na versão 3150 não tem disso rs. Mais vou verificar, obrigado.

Atenciosamente,

SOROInfo - Manutenção de Computadores
André Fernandes
Telefone 15 3222-0482 | WhatsApp 15 99619-6573

Website https://www.soroinfo.com.br



Em ter, 10 de mar de 2020 12:30, BESystem Serviços de Informática <
notifications@github.com> escreveu:

**Comment by BESystemInfo** [comment]
Foi alterado para que o sistema possa calcular o final da garantia. Disseram os devs que vão tentar fazer o sistema identificar isso sozinho, mas vai saber quanto tempo pode levar. =)

**Comment by SOROInfo** [comment]
Fiz a alteração sugerida. Resolveu o problema.
Obrigado!

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website https://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em ter., 10 de mar. de 2020 às 13:08, BESystem Serviços de Informática <
notifications@github.com> escreveu:
