### ISSUE TITLE
Ajuda, como adicionar nova view

### ISSUE THREAD

**Issue by britoriquee** [RamonSilva20/mapos#606]
Preciso de ajuda para adicionar uma nova view, e adicionala ao menu. Estou fazendo isso replicando o esquema de pastas e adicionando um novo link ao menu, mas sempre da erro 404

**Comment by willph** [comment]
Você terá que editar, view, models e controller, além de copiar, colar e renomear a pasta. Tem mais alguns detalhes, que vou deixar para o @Pr3d4dor lhe dizer ou outra pessoa com mais experiência.

**Comment by Pr3d4dor** [comment]
Você precisa fazer o que o @willph lhe disse.

**Comment by britoriquee** [comment]
Ola, obrigado pela resposta. Até ai tudo bem, a questão mesmo é só onde configuro para que no menu, conseguir encaminhar corretamente para a nova view

**Comment by Bremyarck** [comment]
recomendo fortemente que estude a linguagem de programação php e estrutura mvc.
