### ISSUE TITLE
Erro na pagina O.S.

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#607]
A pagina das O.S. esta aparecendo  toda destorcida, sem formatação. Acabeo de Reenviar or arquivos para o servidor, para ter certeza que não é nenhum arquivo corrompido ou faltando.
Segue abaixo print da tela: 
![Captura de tela de 2020-03-11 17-13-01](https://user-images.githubusercontent.com/936442/76459966-ecbc0280-63bb-11ea-965f-078c62cdf672.png)

**Comment by Bremyarck** [comment]
favor certifique-se de ler as questões já resolvidas, a solução desse problema já existe mas não foi sanado em atualização.
