### ISSUE TITLE
Solicitação de alteração em rotina

### ISSUE THREAD

**Issue by dintmktdb** [RamonSilva20/mapos#608]
Um de meus clientes está precisando de uma alteração na rotina (views) faturamento, onde que tenha as datepickers para que se possa escolher as datas para visualização exata do faturamento (sei q tem no relatório, mas não dá pra alterar algum registro de lá).
Resumindo, tendo este datepickers para filtrar melhor o faturamento, fica show.

**Comment by Pr3d4dor** [comment]
Iremos implementar para a próxima versão, fique no aguardo.

**Comment by dintmktdb** [comment]
Maravilha. Obrigado!
