### ISSUE TITLE
Bug na contagem do faturamento

### ISSUE THREAD

**Issue by dintmktdb** [RamonSilva20/mapos#609]
Percebi desde versões antigas do mapos (e ainda na versão 4.1.0), na contagem do faturamento, o total está apenas contando os valores da página atual.
Ou melhor, se tiver 30 registros de soma de 1 real cada e 20 registros de débito de 1 naquela página, irá aparecer o saldo de 10 reais. Porém se tiver 3 páginas (iguais por exemplo), o correto seria ter um saldo de 30, porém ele só calcula os 10 de cada página.
O que sugeria seria que na visualização de cada subtotal, o mapos não levar em conta a página atual, e sim, o resultado real da contabilidade da empresa.
Outra sugestão que faço seria o fato de neste subtotal e/ou total, não contar os valores pendentes. Sendo assim, somente aparecer os efetivados. Assim facilita os cálculos reais da saúde financeira da empresa.

**Comment by Pr3d4dor** [comment]
Obrigado pelos apontamentos, iremos realizar os ajustes.

**Comment by dintmktdb** [comment]
Gratidão!

**Comment by willph** [comment]
> Percebi desde versões antigas do mapos (e ainda na versão 4.1.0), na contagem do faturamento, o total está apenas contando os valores da página atual.
> Ou melhor, se tiver 30 registros de soma de 1 real cada e 20 registros de débito de 1 naquela página, irá aparecer o saldo de 10 reais. Porém se tiver 3 páginas (iguais por exemplo), o correto seria ter um saldo de 30, porém ele só calcula os 10 de cada página.
> O que sugeria seria que na visualização de cada subtotal, o mapos não levar em conta a página atual, e sim, o resultado real da contabilidade da empresa.
> Outra sugestão que faço seria o fato de neste subtotal e/ou total, não contar os valores pendentes. Sendo assim, somente aparecer os efetivados. Assim facilita os cálculos reais da saúde financeira da empresa.

Isso é em financeiro onde tem o Lançamento de receita?

Onde fica as despesas e receitas?

**Comment by willph** [comment]
> Gratidão!

Esse erro ainda persiste na versão mais recente?
