### ISSUE TITLE
Tabelas: Equipamentos e Equipamentos_os

### ISSUE THREAD

**Issue by Lukkasss** [RamonSilva20/mapos#61]
Boa noite.

Vi essas duas tabelas no banco de dados, gostaria de saber se elas são usadas no sistema, e onde eu consigo usá-las. Eu estava indo criar uma função para esse tipo de cadastro, ao abrir OS. Essas tabelas estão em standby ou elas são realmente usadas pelo sistema, na atual versão, 3.1.9?

Desde já, muito obrigado.

**Comment by RamonSilva20** [comment]
Boa noite @Lukkasss. Não estão sendo utilizadas, a ideia era fazer um cadastro de equipamentos e vincular à OS, farei isso na nova versão.

**Comment by Lukkasss** [comment]
@RamonSilva20 Muito obrigado pela resposta, ótimo projeto, estou aprendendo cada vez mais com ele. 
abraço.
