### ISSUE TITLE
Impressora térmica não fiscal

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#610]
Procurei, e não encontrei a informação. Gostaria de saber qual impressora térmica é compatível com o tamanho da impressão do MapOS, 58mm ou 80mm, e se tem algum lugar onde configuro esse tamanho de impressão, para ambas impressoras?

**Comment by Pr3d4dor** [comment]
Se eu não estou enganado é 80mm, mas o @willph pode confirmar melhor.

**Comment by willph** [comment]
Eu testei em 80mm 

Mas creio que vai funcionar em 72mm.

Não tem página de configuração para esta função .

**Comment by robsonmeca** [comment]
Complementando essa postagem, não funciona para impressora 58mm, mais para alterar é facil, basta alterar a linha "18  width: 72mm;" para "width: 48mm;".

**Comment by scriptkid30** [comment]
Aqui fica um espaço enorme em branco quando imprime, alguma correção?
