### ISSUE TITLE
Bug ao adicionar status na OS

### ISSUE THREAD

**Issue by delta7tecnologia** [RamonSilva20/mapos#612]
**Sempre que seleciona o status finalizado me deparo com uma tela desconfigurada ao visualizar a ordem de serviço mais quando seleciona outro status flui perfeitamente**

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Ordem de serviço'
2. Clique em 'Editar OS'
3. Clique em 'alterar status para finalizado'
4. Role para baixo até 'atualizar'
5. Clique em 'visualizar os'
6. Ver erro

**Comment by wilkergrcv** [comment]
o principal voce nao colocou... qual o erro, pois aqui no meu sistema nao aparece nenhum erro.

**Comment by CaramujoRei** [comment]
Estou com o problema acima.
Quando clico em visualizar OS fica tudo branco.. nao aparece nada

**Comment by Pr3d4dor** [comment]
Iremos verificar.

**Comment by delta7tecnologia** [comment]
[https://www.youtube.com/watch?v=nevCeZegHnI&feature=youtu.be](url)

**Comment by delta7tecnologia** [comment]
Link do erro: https://www.youtube.com/watch?v=nevCeZegHnI&feature=youtu.be

**Comment by giampaulo** [comment]
cara.. é algum bug em alguma coluna do banco, da uma conferida, quem sabe faz backup e cria o banco de novo depois upa de novo teus dados, provavelmente se tiver alguma coluna com erro vai te informar, ou talvez apaga essa OS direto no banco e tenta criar outra de novo, pode ser alguma coisa com essa OS em questao.
