### ISSUE TITLE
view OS problema layout

### ISSUE THREAD

**Issue by xiuris** [RamonSilva20/mapos#617]
Layout está dando erro, apenas o da view da OS

![image](https://user-images.githubusercontent.com/62359678/77011907-3b7d1580-6943-11ea-817a-5242936333b8.png)

**Comment by xiuris** [comment]
WINDOWS 10

**Comment by Pr3d4dor** [comment]
Esse problema já foi resolvido, por favor pesquise nos issues.

**Comment by xiuris** [comment]
Tentando localizar ! Obrigado !
