### ISSUE TITLE
Problema com Acesso a OS

### ISSUE THREAD

**Issue by accamargo1803** [RamonSilva20/mapos#620]
Olá amigos... 

fiz uma atualização do meu sistema para a 4.10, e tudo correu bem... as informações do banco foram importadas, login e etc. 

Porém ao acessar o menu "Ordem de Serviços" a tela fica conforme a image.
![Print MAPOS2](https://user-images.githubusercontent.com/62397481/77100741-e8fc3180-69f4-11ea-9f1e-d97ab6034457.JPG)

Os outros menus funcionam perfeitamente.

Obrigado!

**Comment by willph** [comment]
Campo garantia não pode conter espaço ou letra, apenas numero.
Por favor verifique se esse campo garantia tem algum caracteres sem ser numérico e remova.
E diga se o erro persiste.
