### ISSUE TITLE
Dificuldade de configurar este chamado: Emails automaticos de OS #436

### ISSUE THREAD

**Issue by Bruno28121** [RamonSilva20/mapos#621]
** Descreva a solução que você deseja **
Nao estou conseguindo configurar estes parametros : Emails automaticos de OS #436

**Comment by Pr3d4dor** [comment]
Qual é o problema que vc exatamente está tendo?

**Comment by xiuris** [comment]
email só fica pendente, já configurei e nada !

**Comment by Pr3d4dor** [comment]
Configurou o cron?

**Comment by Bruno28121** [comment]
como eu configuro o Cron ?

Em qui., 9 de abr. de 2020 às 21:20, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Depende da sua hospedagem.
