### ISSUE TITLE
Valor Total em estoque. 

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#623]
Tenho um cliente que pediu para que no relatório rápido de estoque tenha o valor total em estoque, é possível ? Se possível for e o pessoal estiver sem tempo e quiser me orientar e tb não for muito difícil eu até posso tentar.

**Comment by Pr3d4dor** [comment]
Iremos verificar.

**Comment by giampaulo** [comment]
Ok. Aguardando
