### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by thadeu220** [RamonSilva20/mapos#624]
alguns servidores não permitem alterar o timezone, e no meu caso, por usar em minha hosperdagem compartilhada o directadmin, se encaixa perfeitamente nisso...
seria interessante poder alterar o timezone a considerar, no próprio mapOS
e quando fui instalar a versão 4, dizia que, eu deveria corrigir algo no index.php, alegando que o caminho absoluto pro sistema estava incorreto.
não entendi... orque tudo estava certo, e consegui prosseguir a instalação normalmente.

**Comment by cleytonasa** [comment]
Procura o arquivo htdocs, e coloca essa linha 
php_value date.timezone 'America/Sao_Paulo'

**Comment by thadeu220** [comment]
EI MEU AMIGUINHO, no sistema mapos não tem esse arquivo, se tiver, me passa o caminho...
a única coisa seria o .htaccess da minha hospedagem, mas, estou sético de que seria aqui.
bem, se tiver o caminho que é dentro do mapos me avisa, já fiz até explore pelo SSH da hospedagem

**Comment by TecSecret** [comment]
Cria um php.ini na pasta raiz e adiciona a função time no php.ini

**Comment by cleytonasa** [comment]
Amigos já olhou dentro da pasta aplicativo?
Ou você mesmo pode criar esse arquivo com touch
