### ISSUE TITLE
Faturando uma OS

### ISSUE THREAD

**Issue by Rennancbr** [RamonSilva20/mapos#625]
Parabéns a todos os envolvidos na criação do sistema.

Gostaria de relatar que ao Faturar uma Ordem de Serviço, significa que a respectiva OS foi finalizada, concorda?!

Pois ao faturar, o status deveria ficar selecionado como FINALIZADO. Uma vez que quando realizamos o faturamento o mesmo é modificado para ORÇAMENTO.

**Comment by Pr3d4dor** [comment]
Não exatamente, pois pode ser faturada de forma parcial.

Somente poderá ser marcada como finalizada se for realizada o faturamento total.

Mas isso também é muito relativo.
