### ISSUE TITLE
Mascarar quantidade para inserir desconto

### ISSUE THREAD

**Issue by BESystemInfo** [RamonSilva20/mapos#626]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Não é exatamente um problema. Há tempos, um colega sugeriu uma idéia de criar um produto e um serviço com o nome Desconto e atribuir diretamente pela DB o valor R$ -1,00. Assim poderíamos dar desconto apenas colocando a quantidade. Seria legal ter um campo onde pudéssemos inserir o desconto diretamente, tanto para produtos quanto para serviços.

** Descreva a solução que você deseja **
No momento, a solução do Produto e Serviço com valor -1,00 tem me atendido, porém gostaria de mascarar a quantidade desse item na Impressão da tela do ADM, e na Visualização e Impressão da tela do cliente, de forma que, se eu colocar, por exemplo, um desconto de 70 reais, saia apenas escrito Produto Desconto, Quantidade 1, Valor 70, e não a Quantidade também como 70.

** Descreva as alternativas que você considerou **
Considerei a alternativa de criar valores de descontos mais comuns diretamente do banco, mas isso é um tanto trabalhoso, uma vez que acabam aparecendo diversos descontos no auto completar, o que acaba por mais atrapalhar do que ajudar.

**Comment by Pr3d4dor** [comment]
Obrigado, iremos fazer quando possível.

**Comment by BESystemInfo** [comment]
Desculpe a demora. Pode fechar a issue, já consegui resolver. Fiz com um IF na View da impressão. Se for util, posto o código,  se não, pode encerrar. Obrigado.
