### ISSUE TITLE
Sem formatação ao visualizar OS

### ISSUE THREAD

**Issue by BESystemInfo** [RamonSilva20/mapos#627]
** Descreva o bug **
Ao clicar em visualizar OS, a página é exibida sem formatação, somente como texto e com a Logotipo do Emitente. Problema ocorre somente em servidores de hospedagem. Localmente via Xampp, com os mesmos arquivos e o mesmo DB, a página é exibida normalmente.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Ordens de Serviço'
2. Clique em 'Visualizar OS'
3. Ver erro

**Comportamento esperado**
Página deveria vir com a formatação do restante do site.

** Capturas de tela **
https://imgur.com/KzJVOU3

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Chrome, Firefox, Opera e Edge Chromium
 - Versão Últimas disponíveis

** Servidores de Hospedagem testados:
Umbler (Conta Pro / Hospedagem oficial)
000Webhost (Versão free do Hostinger)
AwardSpace (Conta Free)

** Contexto adicional **
Imaginei primeiramente que pudesse se tratar de um erro de CSS, mas é estranho que testando localmente na máquina, ou mesmo em outra máquina da rede (Servidor Linux caseiro com Apache), o problema não ocorre. Somente quando subo os arquivos para uma hospedagem acontece esse erro. Já tentei limpar os caches de todos os navegadores, mas o problema persiste de qualquer máquina que eu testar acessar o sistema diretamente da hospedagem.

**Comment by Pr3d4dor** [comment]
Boa tarde, esse problema já foi reportado, se puder buscar na issues você irá encontrar a solução.

**Comment by BESystemInfo** [comment]
Desculpe a insatisfação, mas acredito que as issues deveriam ser verificadas com mais carinho. A "solução" que existe seria voltar o VisualizarOS.php para a de uma versão anterior a 4.0. Acredito que isso não seja solução, mas um paleativo, o que caracteriza que nas versões 4.0+ isso seria um bug ao meu ver. Apenas frisando que isso também ocorreu na versão 4.0. 
De todo modo, caso alguém venha a ter o problema, fica a mesma dica do outro post. Substitua a Applications\Views\OS\VisualizarOS.php por uma versão anterior a 4.0.

**Comment by RamonSilva20** [comment]
Foi feita uma atualização do sistema com essas correções. Versão 4.1.1 e está descrito no arquivo de descrição de mudanças (changelog). Desculpe se nossos esforços no tempo livre não tem sido suficientes.

**Comment by Pr3d4dor** [comment]
> Desculpe a insatisfação, mas acredito que as issues deveriam ser verificadas com mais carinho. A "solução" que existe seria voltar o VisualizarOS.php para a de uma versão anterior a 4.0. Acredito que isso não seja solução, mas um paleativo, o que caracteriza que nas versões 4.0+ isso seria um bug ao meu ver. Apenas frisando que isso também ocorreu na versão 4.0.
> De todo modo, caso alguém venha a ter o problema, fica a mesma dica do outro post. Substitua a Applications\Views\OS\VisualizarOS.php por uma versão anterior a 4.0.

Nós fazemos o máximo para responder da melhor maneira possível, porém muitas issues seriam evitadas se antes da mesma ser criada fosse pesquisada na sessão de issues sobre o problema.

Assim como @RamonSilva20 falou, esse problema já foi corrigido, então cabe a você sempre manter o seu sistema atualizado.

**Comment by BESystemInfo** [comment]
Amigos, primeiramente agradeço do fundo do coração à criação e colaboração do sistema, e aos esforços disponibilizados. 
Ramon, em momento algum reclamei deste item. Apenas fiquei triste de ver que a issue foi fechada sem ao menos se tentar entender o problema ou se ter a certeza se realmente era um problema já solucionado de forma definitiva.
Pr3d4dor, eu fiz a pesquisa. Sempre faço. Veja que meu problema é ao Visualizar UMA OS (independente de qual seja), não na tela de listagem das OS's.
Realmente o problema na tela de OS foi corrigido e reportado no Changelog, devido às mudanças na parte de garantias, mas este que tive não encontrei solução nas issues, apenas um paliativo encontrado pelo amigo romeroigon na issue 597, o que não vejo como solução, visto que ocorria na 4.0, 4.1 e 4.1.1.
Obs.: Sempre mantenho o sistema atualizado com a última versão, mesmo com bugs.
De qualquer forma continuarei tentando solucionar. Agradeço pelo tempo disponibilizado e peço perdão por fazê-los o perder comigo. 

Abraços.

**Comment by Pr3d4dor** [comment]
O problema estava relacionado, tanto na listagem, quanto na visualização.

Assim que tiver um tempo eu vou tentar arrumar.

**Comment by BESystemInfo** [comment]
Caro Pr3d4dor. Mais uma vez agradeço imensamente o apoio e peço desculpas pelo desabafo acima.
Reportei como Bug pq aconteceu com 3 servidores de hospedagem diferentes, inclusive não coloquei no report acima, mas tanto no 000Webhost quanto no AwardSpace, eu testei fazer instalação com DB limpos, criar uma OS de teste e ver se resolveria, pois aí mataria ser problema da minha DB, mas mesmo assim o problema ocorreu.
Meu conhecimento de programação é praticamente nulo, mas estou tentando comparar os arquivos VisualizarOs.php da versão 3.14 com o da 4.1.1 para ver se identifico algo e resolvo o problema. Se eu descobrir algo antes de ti, respondo nesta mesma Issue para referência futura.

Mais uma vez obrigado a todos.

**Comment by Pr3d4dor** [comment]
@BESystemInfo eu instalei o mapos da última versão na hospedagem 000Webhost e consegui visualizar uma OS normalmente:

![image](https://user-images.githubusercontent.com/13210429/77703871-942f5c80-6f9a-11ea-98bc-09d2e59e717e.png)

**Comment by willph** [comment]
> 
> 
> Caro Pr3d4dor. Mais uma vez agradeço imensamente o apoio e peço desculpas pelo desabafo acima.
> Reportei como Bug pq aconteceu com 3 servidores de hospedagem diferentes, inclusive não coloquei no report acima, mas tanto no 000Webhost quanto no AwardSpace, eu testei fazer instalação com DB limpos, criar uma OS de teste e ver se resolveria, pois aí mataria ser problema da minha DB, mas mesmo assim o problema ocorreu.
> Meu conhecimento de programação é praticamente nulo, mas estou tentando comparar os arquivos VisualizarOs.php da versão 3.14 com o da 4.1.1 para ver se identifico algo e resolvo o problema. Se eu descobrir algo antes de ti, respondo nesta mesma Issue para referência futura.
> 
> Mais uma vez obrigado a todos.

Seu BD tem algum caracteres não numérico ainda, no campo GARANTIA?

Letra, espaço?

**Comment by Pr3d4dor** [comment]
Corrigido @BESystemInfo, por favor verifique se irá funcionar para você.

**Comment by BESystemInfo** [comment]
Caro Pr3d4dor. 
Obrigado pelo apoio. Na versão 4.1.2 está funcionando normalmente.

**Comment by BESystemInfo** [comment]
Caro Pr3d4dor,

Agradeço imensamente o apoio. Com a versão 4.1.2 está funcionando normalmente. 

Obrigado mais uma vez e parabéns novamente à todos os envolvidos no projeto.
