### ISSUE TITLE
Envio de E-mail Desnecessário ao Editar OS

### ISSUE THREAD

**Issue by Bremyarck** [RamonSilva20/mapos#628]
**Descrição**

Problema detectado ao editar qualquer ordem de serviço existente, assim que a edição é realizada um e-mail desnecessário é adicionado a lista de e-mail pendentes para envio, causando possível spam na caixa de entrada do receptor.

**Reprodução**

1. Vá para ordens de serviço.
2. Clique em editar ordem de serviço.
3. Altere os campos se desejar ou apenas salve sem alterar.
4. Vá para "Configurações -> E-mails".

**Comportamento Esperado**

Ao editar qualquer ordem de serviço, recomenda-se que não envie e-mail.

**Ambiente**

- Sistema Operacional: Windows 10 Pro 1909 (18363.720)
- Navegador: Google Chrome
- Versão: 80.0.3987.149 64 Bits

**Comment by Pr3d4dor** [comment]
Essa questão é muito relativa, isso foi justamente implementado pois alguns usuários estavam pedindo para enviar e-mail automático quando a OS fosse criada/editada.

Creio então que o que pode ser feito é adicionar uma opção em Configurações >> Sistema para desativar/ativar essse envio automático.

Portanto não é um bug.
