### ISSUE TITLE
campo pesquisar 

### ISSUE THREAD

**Issue by marllonferreira** [RamonSilva20/mapos#63]
@RamonSIlva20 ou outra pessoa pode me ajuda queria a opção de fazer pesquisar de clientes por cpf / cnpj ou pelo nome mais nao sei como fazer 

Na tela inicial em pesquisar da pra pesquisar por nome mais ficaria melhor as duas opções 

Alguem ai pode me ajudar ei RamonSilva20 nao como colocar isso na versão oficial ?
Fico no aguardo.

**Comment by RamonSilva20** [comment]
Bom dia @marllonferreira. Eu estou querendo evitar ficar colocando novas funcionalidades neste versão para tentar fazer a nova versão, vou colocar pesquisa em todos os cadastros na próxima versão. Grato.

**Comment by marllonferreira** [comment]
@RamonSilva20 eu entendo faz so uma coisa pra mim na tela principal la em estatísticas do sistema os valores q esta mostrando ta errado 

Exemplo onde mostra numero de clientes 
Tenho 10 clientes mais lar em estatísticas so mostrar 9 
Falta um para cada opção 

Ajeita isso ai te agradeço muito
