### ISSUE TITLE
Gerenciamento de Horas na O.S.

### ISSUE THREAD

**Issue by persinando** [RamonSilva20/mapos#631]
Olá a todos! primeiramente gostaria de parabenizar a todos pelo esforço neste projeto. O trabalho de todos os desenvolvedores estão ótimos.

Gostaria de oferecer humildemente uma sugestão: 
Controle de Horas na O.S. para quem atende remotamente o controle horas utilizadas na Ordem de Serviço é uma ótima ferramenta.

Vinculado ao calculo do cadastro do serviço podemos faturar por hora também.

O que vocês acham ?

**Comment by Pr3d4dor** [comment]
Sim, é uma excelente funcionalidade, vamos adicionar na lista e implementá-la quando houver tempo.

**Comment by persinando** [comment]
Maravilha

Att.
Fernando Silva
Diretor técnico
Buildinginfra- Informática
Cel.: +55 11 97643-6250
Skype: fsilva.bi
www.buildinginfra.com.br
________________________________
De: Gianluca Bine <notifications@github.com>
Enviado: Friday, March 27, 2020 1:21:44 PM
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: PerSi <fsilva@fernandopesilva.com.br>; Author <author@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] Gerenciamento de Horas na O.S. (#631)


Sim, é uma excelente funcionalidade, vamos adicionar na lista e implementá-la quando houver tempo.

**Comment by persinando** [comment]
@Pr3d4dor  Bom dia! estou enviando esta mensagem para o sistema de bot do github não matar a issue.
