### ISSUE TITLE
Nao Consigo realizar a atualização  

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#633]
Ola, 

Estou tentando realizar a atualização do sistema, atualmente uso a versão  3.14.1. Tenho uma hospedagem na Hostinger. Entrei la, substitui os arquivos, configurei o config.php e database.php, apaguei a pasta Install do diretório, mas não consigo ter acesso ao index que apresenta erro  "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"

**Comment by Pr3d4dor** [comment]
Você precisa instalar as dependências do composer.

Por favor leia o README.md.

**Comment by willph** [comment]
Não esqueça de atualizar o BD também.
