### ISSUE TITLE
Bug Excluir Cliente

### ISSUE THREAD

**Issue by willsantos07** [RamonSilva20/mapos#637]
Ao Excluir um cliente o mesmo exclui todas as dependências relacionadas a ele (vendas, os e etc) porem não exclui o cliente em si o mesmo fica na lista.

**Comment by Pr3d4dor** [comment]
Para ajudar peço que dê mais detalhes: Versão do mapos, navegador, sistema operacional, prints, etc.

**Comment by willsantos07** [comment]
Xampp php 7.3.15
navegador chrome Versão 80.0.3987.149 (Versão oficial) 64 bits
W10 1909 compilaçao 18363.752

**Comment by willsantos07** [comment]
efetuei um outro teste caso o cliente não possua nenhuma venda ou o.s interligada a ele o sistema consegue excluir o mesmo caso tenha algum dos dois a venda ou o.s são excluídas mas o cadastro do cliente em si se mantem
obs. fiz umas modificações para meu uso ate achei que poderia ter editado algo script que possa ter ocasionado o erro porem restaurei para versão original do mapos e o erro continua.

**Comment by Pr3d4dor** [comment]
Não consegui reproduzir o erro aqui, então não tem como eu fazer uma correção.

**Comment by willph** [comment]
> 
> 
> Não consegui reproduzir o erro aqui, então não tem como eu fazer uma correção.

Realmente não exclui o cliente, apesar de aparecer a mensagem que excluiu com sucesso.
Faz o teste adicionando OS e Vendas também.

**Comment by willph** [comment]
> 
> 
> ![bug](https://user-images.githubusercontent.com/26683340/77975290-120fa280-72d0-11ea-9a55-511a82669aed.png)
> Xampp php 7.3.15
> navegador chrome Versão 80.0.3987.149 (Versão oficial) 64 bits
> W10 1909 compilaçao 18363.752

Tem Anexo nesse teste que você fez?

**Comment by willph** [comment]
Ou lançamento de receita?

Se tiver anexo, excluir e tenta excluir o cliente novamente.
Se tiver lançamento de receita relacionado a esse cliente, excluir e depois tenta excluir o cliente.

Ai me diz se o cliente foi excluído ou acontece o mesmo erro.

**Comment by willph** [comment]
> 
> 
> cliente contem apenas uma venda e uma o.s (ambas nao faturas) nos testes que fiz basta apenas adicionar uma o.s e uma venda para que o sistema nao exclua o mesmo
> obs na foto acima nao possui anexo apenas uma venda e uma o.s

Da forma simples, apenas com OS, e vendas feitas a exclusão do cliente funciona normalmente.
Aqui só não funcionou com Anexo e Lançamento de Receita vinculado ao cliente.

**Comment by rafalin** [comment]
Para excluir tbm os lançamentos, precisa adicionar as linhas de comando para excluir em Clientes.php em controllers e também em clientes_model.php em Model, é só copiar a parte de vendas ou OS e fazer as mudanças para lançamentos.

**Comment by Rodrigo-Novaes** [comment]
Fiz a inclusão de um cliente pra teste, porém ao exclir notei que num novo cadastro o numero do id cliente não começa pelo 1 e sim pela sequência, tem como zerar o banco para começar o cadastro pelo id 1?
