### ISSUE TITLE
Erro ao anexar arquivos

### ISSUE THREAD

**Issue by dcassios** [RamonSilva20/mapos#638]
Olá bom dia a todos.

Pessoal, nessa nova atualização está apresentando erro para anexar arquivos

![image](https://user-images.githubusercontent.com/29898540/78026237-a8c07b80-7331-11ea-90aa-57ed115bb9ca.png)

![image](https://user-images.githubusercontent.com/29898540/78026301-c2fa5980-7331-11ea-9edc-c0b5258d1fde.png)

**Comment by Pr3d4dor** [comment]
Assim que tiver um tempo irei verificar.

**Comment by willph** [comment]
> 
> 
> Olá bom dia a todos.
> 
> Pessoal, nessa nova atualização está apresentando erro para anexar arquivos
> 
> ![image](https://user-images.githubusercontent.com/29898540/78026237-a8c07b80-7331-11ea-90aa-57ed115bb9ca.png)
> 
> ![image](https://user-images.githubusercontent.com/29898540/78026301-c2fa5980-7331-11ea-9edc-c0b5258d1fde.png)

Aqui eu fiz uma instalação limpa, e funcionou tranquilamente. PNG, PDF foram os arquivos que testei. Windows 10 x64, Mozilla 74 x64, PHP Version 7.3.6.

Como foi feita sua atualização?

**Comment by dcassios** [comment]
Obrigado a todos pela gentileza em responder.

Fiz outros testes e percebi que esse erro aconteceu pois por algum motivo que eu não saberia explicar, o sistema faz logout mesmo com a tela aberta.

Como eu descobri esse erro, tentei anexar várias vezes o arquivo e não consegui, neste momento eu havia clicado em qualquer outro menu do sistema e ele voltou automaticamente para a tela de login.

Fiz o login novamente e ao tentar anexar, funcionou.
Vi que toda a vez que esse erro de anexo acontece é porque estou deslogado.

Obrigado pela ajuda de todos
