### ISSUE TITLE
Correção de Problema - Campo Vencimento de Garantia

### ISSUE THREAD

**Issue by Bremyarck** [RamonSilva20/mapos#641]
Vá para "application/views/os/os.php" na linha 110 e altere
de:
$vencGarantia = dateInterval(**$dataFinal**, $r->garantia);
para:
$vencGarantia = dateInterval(**$r->dataFinal**, $r->garantia);

_Obs: eu sei que podia enviar uma solicitação de recebimento._

**Comment by willph** [comment]
Isso é uma variável referente a linha 77 onde já tem `$r->dataFinal`.
Ele esta trazendo o dado desta linha.

Aqui está aparecendo normalmente.
Ai no seu não esta aparecendo?

**Comment by LipzyLipzy** [comment]
Boas, 
Estava com o mesmo problema. 
Ficou resolvido depois de alterar, como informou o Bremyarck.

Obrigado
