### ISSUE TITLE
Erro ao tentar acessar o sistema.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#642]
** Descreva o bug **
Olá senhores (as),
Até hoje as 13hrs o sistema estava funcionando normalmente, onde utilizei para fazer lançamentos de O.S e vendas.
Já neste momento, fui acessar para fechar o caixa e me deparo com esse erro abaixo.

Alguém tem alguma ideia de como resolver? funcionou por quase 1 semana.
OBS: não foi alterado nada no BD, FTP ou quaisquer outras informações na hospedagem.
![1](https://user-images.githubusercontent.com/21310068/78462844-2377f680-76a4-11ea-9a98-a78d0c6adebc.png)

**Comment by TecSecret** [comment]
@Triaca você deve verificar o arquivo application/config/database.php pois deve ter ter algum dado errado.

**Comment by Triaca** [comment]
@TecSecret fui buscar um café para conseguir mexer com mais calma e veja só.
cheguei e a página já estava ma tela de login do sistema, sem mexer em nada.
Abri e fechei várias vezes e nada do erro.

Olhei o /database.php e esta tudo certo
