### ISSUE TITLE
Ao cadastrar usuário, não salva no BD

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#644]
Olá bom dia,
criei um novo subdomínio e instalei o Mapos para minha mãe lançar as costuras dela para ter controle do que faz.
porém a instalação foi de um banco zerado (o que vem dentro da pasta mapos), foi configurado pela web e preenchido corretamente com o nome do banco, host etc...
ao acessar a página diz que o usuário cadastrado não existe.

já tentei com: 
admin@admin.com.br
teste@teste,com.br
entre outros, e sempre da o mesmo erro.

então eu mudo no index para refazer a instalação e cadastro um novo usuário porém nunca aparece no phpmyadmin que inclusive já tem um usuário adm por padrão e que não sei a senha para entrar por ele e cadastrar um novo dentro do mapos.

![1](https://user-images.githubusercontent.com/21310068/78553876-0b08f880-77d8-11ea-8aa6-e38db1726b04.png)
![2](https://user-images.githubusercontent.com/21310068/78553879-0c3a2580-77d8-11ea-899f-1082dda3367f.png)

**Comment by willph** [comment]
O arquivo banco.sql que esta na raiz não é pra ser importado.

Ele é usado no install do app, onde deveria ter inserido os dados com o banco vazio.

Refaça a instalação, crie um BD e não importe.
Use o install do mapos inserindo os dados e quando finalizar teste.

**Comment by Triaca** [comment]
@willph muito obrigado!
