### ISSUE TITLE
Adicionar recorrência na ordem de serviço.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#645]
Olá bom dia,
Gostaria de saber se há uma maneira de por recorrência de O.S dentro do mapos.

Na hora de lançar, marcar uma opção de recorrência e escolher quantas vezes seria a recorrência (quantos meses ocorreria aquela ordem de serviço)
Um exemplo seria um contrato de 12 meses, marcaria recorrencia de 12 vezes e assim todo mês haveria uma O.S aberta ref. aquele contrato (primeira O.S) sem a necessidade de criar 12, uma por uma.

**Comment by maycon1977** [comment]
> Olá bom dia,
> Gostaria de saber se há uma maneira de por recorrência de O.S dentro do mapos.
> 
> Na hora de lançar, marcar uma opção de recorrência e escolher quantas vezes seria a recorrência (quantos meses ocorreria aquela ordem de serviço)
> Um exemplo seria um contrato de 12 meses, marcaria recorrencia de 12 vezes e assim todo mês haveria uma O.S aberta ref. aquele contrato (primeira O.S) sem a necessidade de criar 12, uma por uma.

Achei legal a idéia e complemento com outra...

Essa recorrência poderia ser criada ao virar o mês de forma automática. Falo isso porque se criar de imediato, a numeração das O.S. ficará toda sequencial e não fará muito sentido ter 12 números em sequencia para O.S.s geradas ao londo de 12 meses no ano... Tem como?
