### ISSUE TITLE
Visualizar Anexo - Areá do Cliente

### ISSUE THREAD

**Issue by luiscadeira** [RamonSilva20/mapos#646]
Ola,

Na área do Cliente o anexo como imagem não abrem.
Poderiam me ajudar?

Erro 

[http://www.lc2studiocar.com/Area%20do%20cliente.jpg](http://www.lc2studiocar.com/Area%20do%20cliente.jpg)

**Comment by Pr3d4dor** [comment]
Qual versão do mapos você está utilizando?

**Comment by luiscadeira** [comment]
Ola, estou na 4.1

**Comment by Pr3d4dor** [comment]
Peço então que atualize para a versão 4.2.2

**Comment by luiscadeira** [comment]
Ok, obrigado.
