### ISSUE TITLE
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#648]
temtei em vários lugares e todos esse erro

Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by Pr3d4dor** [comment]
Por favor tente pesquisar nos issues antes de postar o seu problema.

Isso acontece porque não foram instaladas as dependencias do composer.

Está descrito no README e nas issues.

**Comment by wesley020291** [comment]
> Por favor tente pesquisar nos issues antes de postar o seu problema.
> 
> Isso acontece porque não foram instaladas as dependencias do composer.
> 
> Está descrito no README e nas issues.

Sim estou pesquisando mais ainda nao encontrei como coloco essas dependencias

**Comment by Pr3d4dor** [comment]
Passo 3 da instação/atualização no README.

**Comment by wesley020291** [comment]
C:\xampp\htdocs\mapos-master>composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/cache 1.10.0 -> satisfiable by doctrine/cache[1.10.0].
    - doctrine/cache 1.10.0 requires php ~7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/collections 1.6.4 -> satisfiable by doctrine/collections[1.6.4].
    - doctrine/collections 1.6.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/common 2.12.0 -> satisfiable by doctrine/common[2.12.0].
    - doctrine/common 2.12.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/event-manager 1.1.0 -> satisfiable by doctrine/event-manager[1.1.0].
    - doctrine/event-manager 1.1.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 5
    - Installation request for doctrine/inflector 1.3.1 -> satisfiable by doctrine/inflector[1.3.1].
    - doctrine/inflector 1.3.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 6
    - Installation request for doctrine/lexer 1.2.0 -> satisfiable by doctrine/lexer[1.2.0].
    - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 7
    - Installation request for doctrine/persistence 1.3.7 -> satisfiable by doctrine/persistence[1.3.7].
    - doctrine/persistence 1.3.7 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 8
    - Installation request for doctrine/reflection 1.2.0 -> satisfiable by doctrine/reflection[1.2.0].
    - doctrine/reflection 1.2.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 9
    - Installation request for myclabs/deep-copy 1.9.5 -> satisfiable by myclabs/deep-copy[1.9.5].
    - myclabs/deep-copy 1.9.5 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 10
    - Installation request for paragonie/random_compat v9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 11
    - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
    - doctrine/annotations v1.4.0 requires doctrine/lexer 1.* -> satisfiable by doctrine/lexer[1.2.0].
    - Installation request for doctrine/annotations v1.4.0 -> satisfiable by doctrine/annotations[v1.4.0].

**Comment by wesley020291** [comment]
deve ser isto?

**Comment by Pr3d4dor** [comment]
Você está usando o PHP versão 5.6 que não não tem mais suporte.

Atualize seu PHP para a versão 7.2 ou superior.

**Comment by wesley020291** [comment]
pi@inicialfacil:~ $ /var/www/clients/client1/web2
-bash: /var/www/clients/client1/web2: É um diretório
pi@inicialfacil:~ $ cd /var/www/clients/client1/web2
pi@inicialfacil:/var/www/clients/client1/web2 $ composer install --no-plugins --no-scripts ...
Invalid argument .... Use "composer require ..." instead to add packages to your composer.json.
pi@inicialfacil:/var/www/clients/client1/web2 $ composer require ...


  [ErrorException]
  file_put_contents(./composer.json): failed to open stream: Operation not permitted


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

pi@inicialfacil:/var/www/clients/client1/web2 $ composer update --no-plugins --no-scripts ...
Composer could not find a composer.json file in /var/www/clients/client1/web2
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
pi@inicialfacil:/var/www/clients/client1/web2 $ Getting Started
-bash: Getting: comando não encontrado

**Comment by wesley020291** [comment]
teria como me manda o link de um download dele ja feito isso?

**Comment by Pr3d4dor** [comment]
Infelizmente não tenho, o correto é vc instalar as dependencias assim mesmo.

**Comment by wesley020291** [comment]
> Infelizmente não tenho, o correto é vc instalar as dependencias assim mesmo.

tem algum outro comando para instalar essas dependências no debian? sou novo, atualmente uso a vesao 3.9.0 e quero atualizar. ainda que salvei. quando atualizei da esse erro

**Comment by Pr3d4dor** [comment]
Está dando um erro de permissão na pasta, ele não está conseguindo acessar o arquivo composer.json

Tente mover os arquivos para outra pasta que vc tenha permissão e depois mova a pasta de volta para a pasta web.

**Comment by wesley020291** [comment]
puxa queria tanto testa a versão nova mas no servidor nao consigo, no xamp tbm nao vai. no wamp tbm nao.
todo da essa mensagem
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by willph** [comment]
> 
> 
> puxa queria tanto testa a versão nova mas no servidor nao consigo, no xamp tbm nao vai. no wamp tbm nao.
> todo da essa mensagem
> Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

Você precisa do composer instalado no seu computador, depois disso so roda o **composer install --no-dev** via git bash ou terminal na pasta raiz do mapos.

Link do Composer
https://getcomposer.org/download/

Sem o COMPOSER instalado no pc não vai. E sem roda o comando também não vai funcionar, porque precisa das dependências.

**Comment by willph** [comment]
Instalação

    Faça o download dos arquivos.

    Extraia o pacote e copie para seu webserver.

    Rode o comando `composer install --no-dev` a partir da raiz do projeto.

    Acesse sua URL e inicie a instalação, é bem simples, basta preencher as informações no assistente de instalação MAPOS.

    Configure o email de envio no arquivo email.php

    Configurar cron jobs para envio de e-mail

Enviar emails pendentes a cada 2 minutos.

    */2 * * * * php /var/www/index.php email/process

Enviar emails com falha a cada 5 minutos.

    */5 * * * * php /var/www/index.php email/retry

    Obs: O path até o index.php (/var/www/) deve ser configurado conforme o seu ambiente
