### ISSUE TITLE
Algumas melhorias pequenas, simples e rápidas de fazer

### ISSUE THREAD

**Issue by pocapratica** [RamonSilva20/mapos#65]
Atualmente, os campos **Descrição**, **Defeito**, **Laudo Técnico** e **Observações** mostram os resultados sem quebra de linha. Fica difícil de compreender todos as informações na mesma linha.

Pra resolver esse problema, adicione o comando `nl2br` antes de mostrar as variáveis correspondentes.
Exemplo:
Para visualizar a OS corretamente, edite o arquivo /application/views/os/visualizarOs.php
Na linha 76, modifique o original por:
`<?php echo nl2br($result->descricaoProduto)?>`
Na linha 85:
`<?php echo nl2br($result->defeito)?>`
Na linha 92:
`<?php echo nl2br($result->laudoTecnico)?>`
Na linha 99:
`<?php echo nl2br($result->observacoes)?>`

Se quiser que fique correto também na hora de imprimir, edite também as linhas 82, 91, 98 e 105 do arquivo /application/views/os/imprimirOs.php

**Comment by pocapratica** [comment]
Ao imprimir a OS, o nome da página fica sempre como Map OS, o que dificulta na hora de gerar a impressão em PDF.

Altere o <title> da página para:
<title>OS: <?php echo $result->idOs?> | <?php echo $result->nomeCliente?></title>

Que o título vai aparecer como:
OS: <número da OS> | Cliente: <nome do cliente>

Ficando mais fácil para entender e ao salvar, já salva com o número da os e o nome do cliente, facilitando a localização e arquivamento.

**Comment by julianopp** [comment]
O meu acabou ficando assim:
<title>OS: <?php echo $result->idOs?>-<?php echo $result->nomeCliente?></title> 

Local: application/views/os/imprimirOs.php

**Comment by pocapratica** [comment]
@julianopp editei meu comentário anterior, eu não havia colocado o código dentro da tag _code_ aqui do Git.
O código completo e correto é esse:
`<title>OS: <?php echo $result->idOs?> | <?php echo $result->nomeCliente?></title>`
