### ISSUE TITLE
Reset de senha

### ISSUE THREAD

**Issue by flaviolear** [RamonSilva20/mapos#652]
Bom dia, estou tentado alterar a senha do ADMIN pelo banco de dados e não consigo, estou sem acesso ao sistema, preciso muito resetar a senha, alguém poderia me ajudar? 
O sistema já é o atualizado

**Comment by jardellnk** [comment]
1 - abra see phpmyadmin e localize a base de dados.
2 - selecione usuario e alterar senha.
3- cole essa senha criptografada:

$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO

4 execute a base de dados 

5 so logar com seu usuario e a senha 123456

**Comment by flaviolear** [comment]
@jardellnk cara fiz e deu certo não, já to doido aqui

**Comment by willph** [comment]
> 
> 
> @jardellnk cara fiz e deu certo não, já to doido aqui

Acesse phpmyadmin
Cuidado com espaços quando for copiar

Veja o campo email, e altere `admin@admin.com`

coloque no campo senha `$2y$10$w0hJp5lyokXHQIzQaKnUXOozZCiXIKcstmzdJjAIw6VJym1rvHSoG`

123456789

**Comment by flaviolear** [comment]
@willph muito obrigado pela dica, faço direto na tabela de usuários?

**Comment by willph** [comment]
> 
> 
> @willph muito obrigado pela dica, faço direto na tabela de usuários?

sim

**Comment by flaviolear** [comment]
@willph , também não deu certo irmão.
![image](https://user-images.githubusercontent.com/55195724/78911128-46b3f480-7a5c-11ea-97f5-4d1643d01151.png)

**Comment by willph** [comment]
> 
> 
> @willph , também não deu certo irmão.
> ![image](https://user-images.githubusercontent.com/55195724/78911128-46b3f480-7a5c-11ea-97f5-4d1643d01151.png)

senha era 123456789 digitou isso no login do toquinho?

**Comment by flaviolear** [comment]
@willph foi, copiei do comentário acima e coloquei

**Comment by flaviolear** [comment]
quando altero e coloca 123456789 direto tbm dá erro para logar

**Comment by willph** [comment]
> 
> 
> quando altero e coloca 123456789 direto tbm dá erro para logar

a senha no banco é criptografada, não adianta colocar o numero 123456789. 

Tenta esse agora, acho que o anterior foi faltando algum caracteres.
`$2y$10$v94kmwsSgLmzLNS18bg99OF1Hfg.ky1Hy4jr.x7Cn74O3ULWiiwou`

**Comment by flaviolear** [comment]
@willph, também não deu cara, coloquei em ttodos os usuários e não deu

**Comment by willph** [comment]
> @willph, também não deu cara, coloquei em ttodos os usuários e não deu

Olha o arquivo database.php em config.
Acredito que fica na pasta application.
Verifica se a conexão com o banco de dados está correta.

**Comment by jardellnk** [comment]
Use esse codigo e no campo idUsuarios vc deve colocar um valor disponivel .. exemploo numero**1** vc substitui por 2 ..3 ..4 assim por diante ...

usuario admin@admin.com 
senha 123456

esse codigo vc usa na opção  **Executa comando(s) SQL na base de dados**

-----------------------------------

    INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
            (**1**, 'Admin', '11111', '1111', '0000', '00', 'aaaa', 'Teste', 'SP', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);

**Comment by flaviolear** [comment]
@willph galera não dá para apagar a tabela, tentei não deu, não consigo apagar os usuário por serem 1 na hierarquia

**Comment by willph** [comment]
> Use esse codigo e no campo idUsuarios vc deve colocar um valor disponivel .. exemploo numero**1** vc substitui por 2 ..3 ..4 assim por diante ...
> 
> usuario [admin@admin.com](mailto:admin@admin.com)
> senha 123456
> 
> esse codigo vc usa na opção **Executa comando(s) SQL na base de dados**
> 
> ```
> INSERT INTO `usuarios` (`idUsuarios`, `nome`, `rg`, `cpf`, `rua`, `numero`, `bairro`, `cidade`, `estado`, `email`, `senha`, `telefone`, `celular`, `situacao`, `dataCadastro`, `permissoes_id`) VALUES
>         (1, 'Admin', '11111', '1111', '0000', '00', 'aaaa', 'Teste', 'SP', 'admin@admin.com', '$2y$10$lAW0AXb0JLZxR0yDdfcBcu3BN9c2AXKKjKTdug7Or0pr6cSGtgyGO', '0000-0000', '', 1, '2018-09-09', 1);
> ```

Não adianta ele inserir outros usuários.

O erro está parecendo mais conexão com o banco de dados que não está ocorrendo.

**Comment by willph** [comment]
> @willph galera não dá para apagar a tabela, tentei não deu, não consigo apagar os usuário por serem 1 na hierarquia

Olha o arquivo database.php na pasta config que está dentro da pasta application.
Verifica se a conexão com o banco de dados está correta em database.php

**Comment by flaviolear** [comment]
@willph sim o arquivo está se comunicando com o banco de dados normalmente

**Comment by flaviolear** [comment]
![image](https://user-images.githubusercontent.com/55195724/78933344-8f30d980-7a7f-11ea-9ab7-fd7850d087d6.png)

 veja se estou fazendo algo errado

**Comment by willph** [comment]
Tem condições de fazer uma instalação limpa. Sem importar BD. E usar o instalado do mapos?

Se sim. Faça o teste ok

**Comment by flaviolear** [comment]
@willph muito obrigado, consegui resolver porém agora o sistema não lista as ordens de serviço do banco de dados que importei

**Comment by willph** [comment]
> @willph muito obrigado, consegui resolver porém agora o sistema não lista as ordens de serviço do banco de dados que importei

Tá faltando algum campo não?
Análise os BDs

**Comment by flaviolear** [comment]
@willph mais uma vez agradecendo a atenção, descobri que como os usuários foram apagados teria que atribuir as os ao id de usuário existem, fiz esta alteração e foi lindo. Muito obrigado a todos que se dispuseram a me ajudar, grande abraço a todos
