### ISSUE TITLE
Atualiza;'ao sistema

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#655]
instalei sistema novo puro e quando vou atualizar o banco de dados aquela op;'ao no painel em configuração/sistema (SOME) e não consigo ver mais

oque pode ser

**Comment by Pr3d4dor** [comment]
A permissão de configuração de sistema está ativada para o seu usuário?

**Comment by wesley020291** [comment]
> A permissão de configuração de sistema está ativada para o seu usuário?

ISSO MESMO AMIGO, ERA ISSO. NOSSA BATI, BATI, BATI, E NÃO CONSEGUI. AGORA DEU CERTO. OBRIGADO
