### ISSUE TITLE
Produtos

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#656]
no cadastro da OS,ABA produtos nao faz a busca no banco de dados. não mostra os produtos

**Comment by Pr3d4dor** [comment]
Cadastrou algum produto no banco de dados?

Verificou se tem estoque do produto?

O produto está marcado como entrada e saída?

**Comment by wesley020291** [comment]
importei meu banco de dados que estava usando na vesão 3.9.0
tem produtos cadastrados
marcado entrada e saida 
tem em estoque

**Comment by willph** [comment]
> importei meu banco de dados que estava usando na vesão 3.9.0
> tem produtos cadastrados
> marcado entrada e saida
> tem em estoque

Faz um teste cadastrando um novo produto, preenchendo todos os campos e depois tentando importando em produtos OS.

**Comment by wesley020291** [comment]
quando vou cadastrar novo da esse erro
An Error Occured.
erro na instalação? excluo e faço a instalação de novo?

![image](https://user-images.githubusercontent.com/56301435/79159213-0cc15600-7dae-11ea-973d-cdbd8759d1c3.png)

**Comment by Pr3d4dor** [comment]
Abra o index.php e mude o environmente para development e tente cadastrar o produto para podemos ver o erro melhor.

**Comment by wesley020291** [comment]
apaguem e acabei de instalar novamente o sistema e esta funcionando certo sim. o problema é quando vou atualiza o banco de dados com os dados do meu backup da versão 3.9. ai nao cadastra produtos e nem clientes.
sera que vou ter que adicionar um por um de novo?

**Comment by Pr3d4dor** [comment]
Parece que dá versão 3.9 para a 4.4.0 foi adicionado o campo de código de barras na tabela produtos.

Creio então que você terá que fazer esse ajuste no SQL antes de importar.

**Comment by wesley020291** [comment]
> Parece que dá versão 3.9 para a 4.4.0 foi adicionado o campo de anotações e código de barras de barras na tabela produtos.
> 
> Creio então que você terá que fazer esse ajuste no SQL antes de importar.

DEU CERTO, peguei todos os INSERT INTO `servicos_os` e executei na opçao e tem no banco de dados SQL

![image](https://user-images.githubusercontent.com/56301435/79167702-734e7000-7dbe-11ea-80a1-b279a7ad849a.png)
