### ISSUE TITLE
Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.

### ISSUE THREAD

**Issue by romaidana** [RamonSilva20/mapos#657]
Olá, boa tarde! 

Baixei o MAPOS, criei a DB, Usuario e senha e Configurei o email.

em CONFIG, onde diz URL, coloquei http://127.0.0.1/pasta

enfim, transfiro os arquivos para o servidor ( hospedagem linux ) PHP 5.6 

e está dando essa mensagem.

Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.

Poderia me orientar, por gentileza!

**Comment by willph** [comment]
Faça o seguinte teste,
Crie um DB vazio, não importe nada e execute o instalador do MAPOS, 

Exemplo: http://localhost/mapos/install/index.php 

Preencha todos os dados que pedira o instalador.
Após isso teste.

**Comment by willph** [comment]
Se não me falhe a memória o requisito mínimo agora é PHP 7.2

E já ia esquecendo, tem que fazer o paço 3 que tem no READNAME.

**Comment by romaidana** [comment]
Obrigado! Irei tentar aqui.

**Comment by romaidana** [comment]
Acontece que não tenho acesso ao cmd da minha hospedagem para rodar o comando do passo 3.

**Comment by willph** [comment]
> Acontece que não tenho acesso ao cmd da minha hospedagem para rodar o comando do passo 3.

Nesse caso terá que roda esse comando localmente no PC e depois subir  a pasta para a hospedagem.
