### ISSUE TITLE
Bug no email enviado a Foto da OS nao aparece.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#658]
Pessoal bom dia a todos
Gostaria de perguntar se ao enviar o email a foto que colocamos nas OS. estão indo no email pq a minha esta ficando com falha depois dessa atualização alguem já percebeu isso?
Grato pela atenção e parabens pelo trabalho.

**Comment by willph** [comment]
Hospedagem ou localhost?

**Comment by cabralwms** [comment]
Eu tenho um servidor proprio, que tem dominio e site proprio. Estaria como hospedagem eu acredito então com IP fixo. Servidor Debian linux 9.

**Comment by cabralwms** [comment]
Percebi que ao tirar o relatorio por exemplo de OS tambem não está aparecendo a Imagem do emitente no campo la em cima da pagina.

**Comment by Pr3d4dor** [comment]
Não entendi, pode explicar com mais detalhes?

**Comment by willph** [comment]
> Não entendi, pode explicar com mais detalhes?

Ele fala da logomarca do Emitente que não aparece no email.
A imagem falha ao tentar carregar no email recebido.

Acredito que seja isso.

**Comment by cabralwms** [comment]
Ele fala da logomarca do Emitente que não aparece no email.
A imagem falha ao tentar carregar no email recebido.

Acredito que seja isso.
Sim é isso mesmo

**Comment by Pr3d4dor** [comment]
Assim que tiver tempo irei verificar o problema.

**Comment by Pr3d4dor** [comment]
O problema que o ocorre é que as imagems devem estar públicas e disponíveis na internet para quando o email for aberto em um lugar externo elas possam ser carregadas.

Então verifique as configurações do seu servidor.
