### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by eliseuchmod777** [RamonSilva20/mapos#659]
Bom dia, eu subi o MAPOS para nuvem, mas ele esta dando erro 500 alguém ai poderia me ajudar? 
ele esta hospedado no Hostgator.
Mensagem do navegador:
"Esta página não está funcionandosigasistemas.com não consegue atender a esta solicitação no momento.
HTTP ERROR 500"

**Comment by willph** [comment]
Vou enviou a pasta com as dependências para a hospedagem?

Via localmente tem que rodar o ```camposer install --no-dev``` e pegar a pasta vendor em aplication e enviar para o mesmo local na hospedagem.

Agora se você tiver o composer na sua hospedagem é só fazer direto lá.

O comando esta no passo 3 da Instalação no READNAME.

**Comment by TecSecret** [comment]
Isso é um problema de htaccess.
