### ISSUE TITLE
Telefone - Impressão da OS

### ISSUE THREAD

**Issue by edgarmeireles** [RamonSilva20/mapos#66]
Galera, depois que atualizei o sistema, a impressão da OS não saiu mais com o telefone do cliente.
antes eu tinha incluído o telefone fixo junto ao celular, mas agora o mesmo comando não serve.

Alguém poderia me dar um help nesse caso?

**Comment by chavezcr27** [comment]
Solo tienes que incluir el campo en el reporte en donde deseas que aparezca. Ejemplo $resultados-> as $r
<?php $r->telefone ;>?
