### ISSUE TITLE
Erro no Botão de Update

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#660]
estou tendo o segunte problema, fiz algumas personalizações nas paginas do sitema a meu gosto e sempre coloco uma coisa ou outra, e axei bem interessante a função de atualizar o sistema, pois bem, fiz um cadastro aki no github fiz tudo certinho e subi os arquivos para o repositorio, no arquivo de config de update application\config\github_updater.php fiz as alteraçoes nos campos "github_repo" e "github_branch" para a minha pasta no github,

Criei um release tudo certo, peguei o commit do release que eu fiz e coloquei no campo "current_commit" no arquivo application\config\github_updater.php

ate ai tudo certo

quando vou e clico no botão de update ele me retorna a mensagem "Seu sistema já está atualizado! " correto.

Mas quando eu gero outro release no github e clico no botão update ele vai para uma tela branca
e tenho a seguinte msg no arquivo de LOG

"Severity: error --> Exception: Error getting mapos version from GitHub! C:\wamp64\www\mapos-OnTech\application\libraries\Github_updater.php 253 "

Estou usando a vers 4.1.0 do MapOS

Como ja tinha feito varias personalizações no sistema apenas peguei os arquivos do update e coloquei nas devidas pastas no meu sistema, não quiz pegar a ultima vers oficial do MapOS pois ja tinha feito varias personalizações no meu e se atualizace teria de refazer tudo novamente

**Comment by Pr3d4dor** [comment]
Mudou também no `application\config\github_updater.php` o parâmetro github_user?

**Comment by hoshikawakun** [comment]
> 
> 
> Mudou também no `application\config\github_updater.php` o parâmetro github_user?

sim mudei em tudo
https://github.com/hoshikawakun/MasterOS
 se quiser verificar como esta so conferir

**Comment by hoshikawakun** [comment]
Hospedagem do sitema estou utilizando o WAMPSERVER 3.2.0
PHP 7.3.12
Apache 2.4.41
MariaDB 10.4.10
E o composer corretamente instalado

**Comment by Pr3d4dor** [comment]
O problema que está ocorrendo é que a release que vc fez está sem o atributo name.

Você pode ver aqui: https://api.github.com/repos/hoshikawakun/MasterOS/releases

Aí na função getCurrentVersion() ele pega a última versão pelo name e como não encontrou, dá o erro.

**Comment by hoshikawakun** [comment]
> 
> 
> O problema que está ocorrendo é que a release que vc fez está sem o atributo name.
> 
> Você pode ver aqui: https://api.github.com/repos/hoshikawakun/MasterOS/releases
> 
> Aí na função getCurrentVersion() ele pega a última versão pelo name e como não encontrou, dá o erro.

poderia me ajudar a como resolver esse problema?
oque tenho de fazer, onde devo ir pra ficar tudo correto

**Comment by Pr3d4dor** [comment]
No arquivo `https://github.com/hoshikawakun/MasterOS/blob/master/application/libraries/Github_updater.php` mude a linha 250 para:
```
$version = $latestRelease->tag_name;
```

**Comment by hoshikawakun** [comment]
> 
> 
> No arquivo `https://github.com/hoshikawakun/MasterOS/blob/master/application/libraries/Github_updater.php` mude a linha 250 para:
> 
> ```
> $version = $latestRelease->tag_name;
> ```

Fiz as alterações como falou, tanto no github como no que ja esta no PC,
quando clico em atualizar, ele fica carregando por um tempo e me retorna na mesma pag uma msg de aviso falando

"Erro ao atualizar o Sistema! "

oque posso estar fazendo de errado agora?
sera alguma config no servidor aki no PC?
alguma permissão?

**Comment by hoshikawakun** [comment]
quando abro a pasta onde estão os arquivos aki do sitema agora vejo que ele baixou um arquivo .zip
que o mesmo contem os arquivos da atualização mas oque me parece acontecer e que ele não esta conseguindo fazer a extração e substituição com os novos arquivos

**Comment by Pr3d4dor** [comment]
Aí o problema é no seu computador, você vai ter que debugar para verificar se é problema de permissão ou outra coisa.

**Comment by hoshikawakun** [comment]
uma alternativa que pra mim seria de bom tamanho e ao clicar no botão de atualizar ele baixar o arquivo da atualização e me perguntar onde desejo salvar ele e então fazer a subistituilção manual
isso e possivel?

**Comment by Pr3d4dor** [comment]
Tecnicamente ele já faz isso, pois se vc pegar o zip e extrair e substituir os arquivos ele já ira ficar atualizado.

O que você pode fazer é mudar as mensagens.

**Comment by hoshikawakun** [comment]
Uma ultima duvida
no arquivo "application\config\github_updater.php"
na linha 26
o comando "$config['current_commit'] ="
e onde fica a Hash da versão
sei que se a info que esta nesse campo no arquivo que esta no servidor for diferente do que esta no github na release ele efetua a atualização

a questão que so tenho essa info da release depois que eu a crio, e como alterar esse valor no arquivo para que ele ja fique com o valor da release quando for feito a atualização do sistema?

**Comment by Pr3d4dor** [comment]
Na função "_set_github_updater_config_hash" ele atualiza esse arquivo com o hash do último commit após baixar o zip com as atualizações.
