### ISSUE TITLE
Valor da OS na tela onde lista as OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#661]
Na tela onde osta a listagem das OS tem ja o campo Valor Total, mas o valor só aparece ali quando a mesma e faturada, uma dica que axo muito bom seria independente se a OS foi Faturada ou Não aparecer ali ja os valores da mesma, facilita pois como esta atualmente vc tem que abrir a OS para editar ou visualizar para saber o valor que a mesma se encontra

**Comment by willph** [comment]
> Na tela onde osta a listagem das OS tem ja o campo Valor Total, mas o valor só aparece ali quando a mesma e faturada, uma dica que axo muito bom seria independente se a OS foi Faturada ou Não aparecer ali ja os valores da mesma, facilita pois como esta atualmente vc tem que abrir a OS para editar ou visualizar para saber o valor que a mesma se encontra

Seguindo essa linha de raciocínio, então só seria interessante aparecer o valor só quando estivessem em orçamento, em finalizado e faturado também. O resto não.
Cancelado não tem interesse saber o valor. E em aberto também.

E os demais que não lembro.

**Comment by eduaraujothe** [comment]
Eu vejo da seguinte forma, o valor deveria aparecer independente do status da OS. Sem a necessidade de abri ou editar a OS pra ter acesso ao valor.

**Comment by JulianoSavino** [comment]
Concordo com o @eduaraujothe, pois muitas vezes apenas precisamos saber o valor dela, independente do status. Seria mais rapido pois não teriamos que abrí-la para saber.
