### ISSUE TITLE
Instalação mapos

### ISSUE THREAD

**Issue by otaviogithub** [RamonSilva20/mapos#663]
** Descreva o bug **
- Fiz o Download completo aqui no site
- subi para web
- fiz a descompactação
- Criei o Bd e Fiz a Importação
- o Sistema esta em um subdominio ( http://www.os.virtuabr.com.br)
- A index de instalação e configuração subiu normal...
- Ao terminar a instalação e voltar para index retorna o erro   (  Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php  )

Como corrigir esse erro, agradeço a atenção...
 
As configurações do meu servidor estao de acordo com as exigências do sistema...
 
** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by willph** [comment]
Falta a etapa 3 da Instalação.

```Composer install --no-dev```

Se não tiver como executar isso na sua hospedagem, vai ter que fazer isso localmente e depois subir a pasta.

**Comment by TecSecret** [comment]
Você precisa dos requisitos do composer que ficam na pasta application/vendor.

Recomendo executar Composer install --no-dev

**Comment by otaviogithub** [comment]
Ok, agradeço a todos...
Cheguei em um ponto da instalação, que na tela de login, ao digitar o e-mail e senha o sistema não sobe ....
Alguma sugestão

**Comment by otaviogithub** [comment]
Agradeço, consegui fazer a instalação, perfeito...

**Comment by maycon1977** [comment]
> Agradeço, consegui fazer a instalação, perfeito...

Oi amigo... Como fez o passo do "composer"?
Tô muito perdido nisso.
