### ISSUE TITLE
Dashboard - API GoogleMaps

### ISSUE THREAD

**Issue by eduaraujothe** [RamonSilva20/mapos#664]
Olá pessoal, parabéns pelo grande projeto que é o MAPOS estou utilizando a quase 1 ano e tem me ajudando muito na organização do meu trabalho.

Gostaria de sugerir que na "Dashboard" houvesse uma DIV pegando a API do google maps onde cada cliente cadastrado gerasse um ponto mostrando a localização dos clientes, isso facilitaria a tomada de decisões em vários aspectos.

1. Pra atendimento externo utilizaria a geolocalização para deslocamento;

2. Tomada de decisões pra futura captação de novos clientes, visto que pelos clientes já cadastrados poderiamos saber logo de cara onde estaria concentrado a maioria dos nossos clientes e assim montar uma estrategia para captação de novos clientes em áreas onde teriamos pouca atuação.

Um abraço a todos.

**Comment by Pr3d4dor** [comment]
O problema dessa abordagem é que a API do Google Maps agora é paga e não tem mais opção free.

**Comment by TecSecret** [comment]
@Pr3d4dor existe a api do Here Maps https://developer.here.com/ que eu acho ela muito melhor do que do google maps.

Detalhe é free.
