### ISSUE TITLE
Área para guardar arquivos diversos.

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#666]
Uma área para armazenar arquivos diversos, seja PDF, BIN, ROM, etc...

Podendo atrelar os arquivos a alguma OS mas não sendo necessário.

Seria ótimo para guardar registros diversos.

**Comment by Pr3d4dor** [comment]
No mapos já tem a opção de arquivos, essa funcionalidade não te atende?

![image](https://user-images.githubusercontent.com/13210429/79699233-9072bb00-8264-11ea-959e-676a137115b8.png)

**Comment by Doonine** [comment]
Eu me enganei, pensei que podia enviar apenas imagens, mas também pode PDF e TXT, seria possível remover a limitação de extensões?

**Comment by Pr3d4dor** [comment]
Creio que no mapos geral seria bom deixar somente essas extensões.

Porém você pode customizar o arquivo `application/controllers/Arquivos.php` na linha 226 conforme sua necessidade:

https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Arquivos.php#L226

**Comment by Doonine** [comment]
> Creio que no mapos geral seria bom deixar somente essas extensões.
> 
> Porém você pode customizar o arquivo `application/controllers/Arquivos.php` na linha 226 conforme sua necessidade:
> 
> https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Arquivos.php#L226

Verdade, não tinha pensado nisso, mas obrigado por me indicar o caminho para essa alteração.

**Comment by Doonine** [comment]
Desculpe, só para concluir, cheguei em um meio termo e autorizei arquivos .zip e .rar. dessa forma consigo upar oq quiser preservando a segurança.
