### ISSUE TITLE
Alterar obrigatoriedade de um telefone

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#667]
Opção de escolher o tipo de contato obrigatório (Celular ou Fixo)

Atualmente muitas pessoas não possuem telefone fixo (eu mesmo não tenho) mas celular, muitas vezes tem mais de um número.
Ao efetuar um cadastro, preciso colocar um número aleatório no telefone fixo pois alguns clientes e até mesmo eu não temos.
Nas OS aparece o telefone aleatório que cadastrei, e não aparece meu número de celular...

**Comment by Pr3d4dor** [comment]
Posso fazer esse ajuste, mas vou ter que olhar todos os lugares onde o telefone aparece e além de mudar o banco pois o campo é NOT NULL.

**Comment by Doonine** [comment]
Acho que apenas inverter a obrigatoriedade para o telefone celular ao invez do fixo já resolveria, mas muito obrigado pela atenção!
