### ISSUE TITLE
Anexos area do cliente não carregam

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#669]
Boa noite!
Não tenho certeza se é um bug ou algum problema de configuração.
Anexos de alguma OS não são visualizados na área do cliente.
Aparece os quadrados com o nome do arquivo, mas a imagem não carrega.
Ao clicar na imagem, uma barra azul fica "carregando" eternamente.
Ao clicar em Download, a pagina é redirecionada ao texto da OS e não baixa a imagem.

Servidor local (Localhost)
XAMPP Version: 7.4.4
PHP Version 7.4.4
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.4

**Comment by Pr3d4dor** [comment]
Irei verificar assim que tiver um tempo.
