### ISSUE TITLE
Botão gerar recibo 

### ISSUE THREAD

**Issue by turbonetlink** [RamonSilva20/mapos#670]
teria algum lugar no sistema que gere recibo na hora de receber o valor com numeração de cada recibo e possibilidade de alterar o layout e a numeração ? com opção  se possivel de assinatura digital já no recibo ?
e se possivel tannto para impressora comum quanto para termica segue os exemplos 
![CupomTermBema](https://user-images.githubusercontent.com/12984495/79742988-27c62580-82da-11ea-87c6-3963c2414d7b.png)
![modelo-recibo-imrecibo-imsistemas](https://user-images.githubusercontent.com/12984495/79742992-285ebc00-82da-11ea-8d8e-241594e4706f.jpg)

![cupom_nao_fiscal_zpsuevlbuha](https://user-images.githubusercontent.com/12984495/79743119-65c34980-82da-11ea-94b2-6a30209fc95a.png)
![recibo_impressora-termica3](https://user-images.githubusercontent.com/12984495/79743320-c6528680-82da-11ea-832e-16d45e20cc93.jpg)

**Comment by Pr3d4dor** [comment]
Ainda não existe essa funcionalidade no mapos.

**Comment by hoshikawakun** [comment]
se for imprementar isso coloque para impressoras termicas padrão e as 58mm
