### ISSUE TITLE
Erro ao atualizar o Sistema! 

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#672]
Toda vez que tento atualizar o sistema recebo essa msg de erro
"Erro ao atualizar o Sistema! "

ao abrir a pasta onde esta hospedado o sistema no PC o arquivo da atualização esta la 
Para gerar o servidor local tenho utilizado

WAMPSERVER 3.2.0 (X64)
Apache 2.4.41
PHP 7.3.12
MariaDB 10.4.10

No arquivo de LOG do apache tenho a seguinte info

[Mon Apr 20 17:47:56.549093 2020] [mpm_winnt:notice] [pid 2396:tid 436] AH00455: Apache/2.4.41 (Win64) PHP/7.3.12 configured -- resuming normal operations
[Mon Apr 20 17:47:56.549093 2020] [mpm_winnt:notice] [pid 2396:tid 436] AH00456: Apache Lounge VS16 Server built: Aug  9 2019 16:46:32
[Mon Apr 20 17:47:56.549093 2020] [core:notice] [pid 2396:tid 436] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.41\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.41'
[Mon Apr 20 17:47:56.549093 2020] [mpm_winnt:notice] [pid 2396:tid 436] AH00418: Parent: Created child process 2816
[Mon Apr 20 17:47:56.923493 2020] [mpm_winnt:notice] [pid 2816:tid 336] AH00354: Child: Starting 64 worker threads.
'unzip' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.

**Comment by Pr3d4dor** [comment]
Está faltando o unzip no teu sistema para poder realizar a extração dos arquivos compactados baixados na atualização.

**Comment by hoshikawakun** [comment]
> 
> 
> Está faltando o unzip no teu sistema para poder realizar a extração dos arquivos compactados baixados na atualização.

no meu sistema tem apenas os comandos

"gzip .gz .tgz"

e possivel utilizar ele no lugar do unzip?

**Comment by Pr3d4dor** [comment]
Teria que adaptar o código.

**Comment by hoshikawakun** [comment]
não seria tipo apenas substituir os comandos "unzip" por "gzip" ?

**Comment by Pr3d4dor** [comment]
Sim, porém o arquivo que é baixado do github é no formato .zip

**Comment by hoshikawakun** [comment]
Eu fiz todas as alterações substitui "unzip" por "gzip" e ".zip" por ".tgz"
o sistema fez o download normalmente um arquivo  ".tgz"
depois de algum tempo me foi dada uma tela branca
abri então o arquivo de LOG e tinha isso

"ERROR - 20-04-20 23:21:41 --> Severity: Error --> Maximum execution time of 120 seconds exceeded C:\wamp64\www\mapos-OnTech\application\libraries\Github_updater.php 180"

**Comment by Pr3d4dor** [comment]
Você tem aumenar o limite de tempo de execução do PHP no apache.
