### ISSUE TITLE
Valor Total e Valor Faturado

### ISSUE THREAD

**Issue by JulianoSavino** [RamonSilva20/mapos#673]
Boa tarde, a implementação da nova coluna em OS onde mostra valor Total ficou perfeita, infelizmente está aparecendo valores apenas para novas ordens abertas, não está puxando valores de ordens antigas, ja a coluna Valor Total (Faturado) está ok . Estava usando a Versão 4.2.2 (não sei se tem haver). Rodei o composer novamente mas não os Dokers.
Agradeço o empenho de todos

**Comment by Pr3d4dor** [comment]
Não consegui reproduzir o bug, ainda mais que é estranho pois a soma vem direto do banco de dados, então era pra funcionar.

**Comment by acinformatica2004** [comment]
Boa noite, o meu acontece o mesmo, porém algumas o.s antigas ele pegou o valor total, no faturado tá ok

**Comment by Pr3d4dor** [comment]
Algum de vcs pode me disponibilizar algum backup de vocês para que eu possa testar mais fácilmente?

**Comment by hoshikawakun** [comment]
No meu aki so aparece o valor na coluna Valor Total quando tem um serviço e um produto dentro da OS, se tem apenas um ou outro aparece 0
