### ISSUE TITLE
erro ao tentar alterar usuario do sistema

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#674]
Pessoal bom dia 
Fui fazer uma alteração em um usuário do sistema existente e da erro, alguém poderia me ajudar.
Vou tentar verificar o código do erro, mas não apareceu nada. apenas as alterações feitas não acontecem e volta como estava antes.

Aparece apenas erro la em cima.
no log do apache apareceu isso 
[Tue Apr 21 00:06:29.426517 2020] [ssl:warn] [pid 28529] AH01906: not-debian.casa.inet:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Apr 21 00:06:29.428383 2020] [mpm_prefork:notice] [pid 28529] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2u mod_wsgi/4.5.11 Python/2.7 configured -- resuming normal operations
[Tue Apr 21 00:06:29.428416 2020] [core:notice] [pid 28529] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 21 08:34:27.728713 2020] [wsgi:error] [pid 14955] [remote 192.168.1.1:55546] /usr/lib/python2.7/dist-packages/web/db.py:591: Warning: Data truncated for column 'delete_date' at row 4
[Tue Apr 21 08:34:27.728811 2020] [wsgi:error] [pid 14955] [remote 192.168.1.1:55546]   out = cur.execute(query, params)
[Tue Apr 21 08:34:27.728937 2020] [wsgi:error] [pid 14955] [remote 192.168.1.1:55546] /usr/lib/python2.7/dist-packages/web/db.py:591: Warning: Data truncated for column 'delete_date' at row 5
[Tue Apr 21 08:34:27.728963 2020] [wsgi:error] [pid 14955] [remote 192.168.1.1:55546]   out = cur.execute(query, params)

**Comment by cabralwms** [comment]
Testei sem o HTTPS deu a mesma coisa tanto com HTTP ou com HTTPS

**Comment by Pr3d4dor** [comment]
É algum problema com coluna a mais ou a menos `delete_date`

**Comment by cabralwms** [comment]
Eu sou meio Leigo em programacao com banco de dados sei o basico, eu fiz algo errado e deu esse erro?

**Comment by Pr3d4dor** [comment]
Está estranho pois está dando erro no python, não tem nada de python no mapos.
