### ISSUE TITLE
Configuração padrão de listegem OS

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#675]
Basicamente a ideia seria a criação de uma nova tela de em configuração para a OS, com isso criando um filtro para que o usuário consiga criar definir para que quando abri a tela de listagem de OS não apareça nativamente as OS configuradas. 
Por exemplo: não quero que apareça nativamente as OS que já foram finalizadas. Nessa nova tela de configurações, eu desmarcaria a OS finalizada, assim elas não apareceriam mais. 

A ideia é que depois de um tempo fica muita OS finalizada dificultando encontrar as OS que ainda estão abertas.

**Comment by Pr3d4dor** [comment]
Os filtros que já existem na tela de listagem de OS não resolvem?

**Comment by bulfaitelo** [comment]
> 
> 
> Os filtros que já existem na tela de listagem de OS não resolvem?

Sim mas não é produtivo, eu vou estudar um pouco mais o code3 e vou tentar implementar, o problema que eu uso muito o Laravel, e confunde bastante ficar alternando entre um e outro 😅

**Comment by Pr3d4dor** [comment]
Ok, se quiser fazer a implementação e contribuir, será sempre bem vindo.

O mapos está sendo refeito em Laravel também, se quiser contribuir:
- https://github.com/map-os/mapos

**Comment by bulfaitelo** [comment]
> 
> 
> Ok, se quiser fazer a implementação e contribuir, será sempre bem vindo.
> 
> O mapos está sendo refeito em Laravel também, se quiser contribuir:
> 
>     * https://github.com/map-os/mapos

Opa vou baixar, aqui. e levantar pra testar.

**Comment by Pr3d4dor** [comment]
@bulfaitelo por enquanto somente foi iniciado o CRUD de usuários.

**Comment by bulfaitelo** [comment]
> 
> 
> @bulfaitelo por enquanto somente foi iniciado o CRUD de usuários.

Eu acabei de levantar aqui, sim ele esta basicamente zero. vou fazer um fork aqui e vou tentando ajudar com correções nele.

**Comment by Pr3d4dor** [comment]
@bulfaitelo Importante, tudo que for desenvolvido deverá ter os testes.

O CRUD de usuário já foi implementado os testes também e vc pode conferir eles na pasta tests.
