### ISSUE TITLE
Erro ao tirar relatorio

### ISSUE THREAD

**Issue by agostinhodf** [RamonSilva20/mapos#681]
Boa noite fiz a instalação do MAPOS porém ao tentar tirar um relatório, o mesmo apresenta o seguinte erro segue em anexo, gostaria que alguém me ajudasse por gentileza, obrigado.

![Erro MAPOS](https://user-images.githubusercontent.com/64115613/79933511-9a441c00-8426-11ea-9cfc-268fe644c964.png)

**Comment by hoshikawakun** [comment]
Ja me aconteceu esse tipo de erro quando a vers do PHP era muito antiga ou quando algum componente do sistema estava ausente , tipo bibliotrca do composer

**Comment by Pr3d4dor** [comment]
Você precisa atualizar suas dependencias do composer.

**Comment by agostinhodf** [comment]
E como atualizo eu uso windows Fox a instalação do composer pelo instalador.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Roda o comando `composer update` dentro da pasta do mapos

**Comment by agostinhodf** [comment]
Dentro da raiz onde fica a Index o arquivo do banco ?

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Sim, a pasta onde fica o index.php

**Comment by agostinhodf** [comment]
Não deu certo, atualizei e continua o mesmo erro, no Power shell apareceu algo sobre mpdf.phpas muito obrigado pela dica.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Qual a versão do seu php?

Pode deletar o arquivo composer.lock e a pasta application/vendor e tentar novamente?

**Comment by agostinhodf** [comment]
Uso a versão 7 do php, vou tentar essa solução, obrigado.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Precis ser pelo menos a versão 7.2, então você precisa atualizar o seu PHP.

**Comment by agostinhodf** [comment]
Bom dia não deu certo, fiz isso que vc pediu, mas não funcionou.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by agostinhodf** [comment]
Usa a versão 7.4.2 do php.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Então o seu composer não está instalado corretamente ou outra coisa está errada.

**Comment by agostinhodf** [comment]
Vc pode me passar o passo a passo de instalação do composer, pq eu instalei através do instalador disponível para windows.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Pr3d4dor** [comment]
Basta seguir as instruções oficiais.

Recomendo você tentar reinstalar o mapos do zer na última versão o e importar um backup do seu banco.

Siga os passos listados no README.md

**Comment by neofln** [comment]
Instalei as versões 4.7.2 e 4.7.4 conforme orientações do README.md e ao terminar a instalação entrei com dados de teste e mandei gerar relatório, tudo correu bem, no entanto após importar o banco da versão 4.1.0 que recentemente comecei a usar, e mandar atualizar o banco no menu configurações/sistema, os relatórios deixaram de funcionar.

O erro apresentado é este abaixo para qualquer relatório rápido: 
Mpdf \ MpdfImageException (E_ERROR)
Error parsing image file - image type not recognised, and not supported by GD imagecreate

Tentei o "composer update" e nada mudou.

Meu banco atualmente é pequeno e caso nada possa ser feito para solucionar o problema posso cadastrar manualmente tudo de novo, no entanto me preocupa a possibilidade de ter de fazer isso quando o banco estiver enorme.
É algo que julgo deve ser avaliado para evitar aborrecimentos futuros. 

Independente de quaisquer problemas com ou sem soluções, quero deixar registrado meu muito obrigado por estarem trabalhando com tanto afinco no Map-OS, ele está nitidamente ficando melhor a cada versão. ;D

**Comment by Pr3d4dor** [comment]
@neofln para resolver esse erro basta você atualizar seu logo em Configurações >> Emitente.

**Comment by neofln** [comment]
Ficou funcionando perfeitamente atualizando o logotipo.
Muito grato. ;D
