### ISSUE TITLE
Sobre opção de impressão

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#682]
Uma dica que seria muito bem vinda no sistema e melhorar a questão da area de impressão de vendas, clientes, usuarios, OS, etc.

as impressões dos relatorios do sistema e apresentada em um documento estilo PDF

poderia ser todas as impress~oes do sistema seguir esse mesmo estilo?
prq quando vc clica para imprimir uma OS oque aparece na tela tem formatação diferente do que apresenta na impressão

**Comment by Pr3d4dor** [comment]
Creio que isso também possa estar relacionado à configuração da sua impressóra (página, cores, etc.)

Então acho que não seja viável realizar esse ajuste.

**Comment by hoshikawakun** [comment]
mas teria como fazer toda a area de impressão no estilo doc PDF?

**Comment by Pr3d4dor** [comment]
Ao invés de imprimir vc pode salvar em PDF.

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.
