### ISSUE TITLE
Erro Relatório da Auditoria

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#683]
Sobre o relatorio da area "Auditoria" o que se fala das "OS" tem um problema

Qualker que seja a informação que e dada ali não consta o Nº da OS consta apenas oque foi feito
![Screenshot_22](https://user-images.githubusercontent.com/1253576/80045396-a0e19a80-84dd-11ea-8e2f-a8696295120e.png)

**Comment by Pr3d4dor** [comment]
Vou revisar essa parte e adicionar o ID da OS nos logs.
