### ISSUE TITLE
Erro ao Add Anexo em OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#684]
Estou tendo um pequeno problema

Isso pelo Celular
Abri uma OS e fui ate a area de Anexos
selecionei "Escolher Arquivos"
Selecionei a opção de tirar uma foto na hora
fiz a foto e mandei anexar
as 2 primeiras fotos foram anexadas normalmente
Apartir da 3ª Foto so recebo a msg "Atenção! Nenhum arquivo foi anexado."
Mas se seleciono alguma foto da galeria ela e anexada sem nenhum problema
Oque pode estar Acontecendo

Cel: iPhone 5S
IOS: 12.4.5
Navegador: Safari
![C4C37190-3C69-4E37-ABEC-3D0AFE66ABC8](https://user-images.githubusercontent.com/1253576/80045352-7ee81800-84dd-11ea-8dc0-8a666030f7bd.png)

**Comment by hoshikawakun** [comment]
e depois disso qualker foto que eu coloco anexada na OS pelo PC a miniatura da foto não aparece, aparece apenas um quadrado cinza no cel, mas se clicar a foto abre
ja no cel, qualker outra imagem que eu seleciono para anexar ela na os, a mesma e anexada so que não aparece a miniatura apenas um quadrado cinza, ai ate no pc não aparece a miniatura

No arquivo de LOG tenho recebido essa info

"ERROR - 23-04-20 00:24:42 --> Severity: Warning --> unlink(C:\wamp64\www\mapos-OnTech\assets/anexos/04-2020/OS-303/thumbs/thumb_D8B8B6AF-FBB4-47F7-AD5B-318CD2D6771A.jp): No such file or directory C:\wamp64\www\mapos-OnTech\application\controllers\Os.php 665"

**Comment by Pr3d4dor** [comment]
Isso parece ter a ver com o wamp pois o caminho está com barras normais e invertidas
`C:\wamp64\www\mapos-OnTech\assets/anexos/04-2020/OS-303/thumbs/thumb_D8B8B6AF-FBB4-47F7-AD5B-318CD2D6771A.jp`

Por isso não encontra o arquivo.

**Comment by hoshikawakun** [comment]
> 
> 
> Isso parece ter a ver com o wamp pois o caminho está com barras normais e invertidas
> `C:\wamp64\www\mapos-OnTech\assets/anexos/04-2020/OS-303/thumbs/thumb_D8B8B6AF-FBB4-47F7-AD5B-318CD2D6771A.jp`
> 
> Por isso não encontra o arquivo.
mas no Banco de dados todos aparecem desse modo barras diferentes
C:\wamp64\www\mapos-OnTech\assets/anexos/04-2020/OS-303

mas somente os 2 primeiros anexos que funcionam normal no Cel

**Comment by hoshikawakun** [comment]
![índice](https://user-images.githubusercontent.com/1253576/80049031-3bdf7200-84e8-11ea-8741-1a83bd2655d7.png)
veja como esta o codigo original
as barras estão invertidas no final

**Comment by hoshikawakun** [comment]
Em resumo nenhuma das imagens que são anexadas pelo PC aparecem no Cell
e qualker imagem anexada pelo cel se ja tiver 2 imagens na OS elas não aparecem a miniatura

**Comment by Pr3d4dor** [comment]
Conseguiu resolver o problema?

**Comment by RamonSilva20** [comment]
> ![índice](https://user-images.githubusercontent.com/1253576/80049031-3bdf7200-84e8-11ea-8741-1a83bd2655d7.png)
> veja como esta o codigo original
> as barras estão invertidas no final

Melhor reescrever esse trecho usando DIRECTORY_SEPARATOR para evitar esse problema no Windows.
