### ISSUE TITLE
Area do cliente com acesso por senha

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#685]
Boa tarde, sugiro a opção do cliente incluir uma senha de acesso para a area do cliente.
Fico um pouco preocupado com a segurança das informações, com o e-mail e CPF do cliente, qualquer um pode  ter acesso a todas as outras informações pessoais e dados dos serviços / compras registradas no sistema.

**Comment by Pr3d4dor** [comment]
Assim que tiver tempo vou pensar em uma maneira de melhorar essa parte.

**Comment by hoshikawakun** [comment]
creio que isso seja relativamente facil de resolver, na tabela no DB Cliente colocar a coluna senha, e na area de cadastro de cliente e edição colocar o campo pra ele colocar a senha para acesso dele no sistema, não precisa ser senha codificada, e na area do clente altera o nome ali de CPF para senha e altera qual colçuna que o sistema vai usar para acessar que envez do CPF vai ser a Senha, oque axa da ideia? e uma implementação bem simples de se fazer
