### ISSUE TITLE
Novas configurações de emails

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#687]
Atualmente existe a possibilidade de configurar o sistema para automaticamente enviar e-mails ao adicionar ou editar a OS para clientes, para cliente, técnico, emitente, todos ou nenhum.
O problema é que para alguns clientes, isso acaba sendo chato, para outros, isso acaba sendo necessário, para outros, algumas coisas são boas, outras são ruins, então, sugiro algumas alterações.

Novas configurações:
1: "Envio Manual" Os e-mails somente serão enviados caso seja manualmente clicado no botão para enviar o e-mail.
2: "Perguntar antes" Uma janela pergunta se deseja enviar o e-mail antes de enviar.
3: "Cada OS decide" Ao cadastrar uma OS, será obrigado selecionar se o cliente recebe e-mails com alterações, adições ou tudo.

Toda vez que posto algo aqui, a resposta vem de forma rápida e objetiva, tem muitas empresas que vendem aplicativos que não tem um retorno tão rápido juntamente com a atualização ou pelo menos um motivo de não providenciar. Muito obrigado por isso!

**Comment by Doonine** [comment]
Também possibilitar o cliente a também poder marcar alguma OS para receber e-mail ou não na área do cliente.

**Comment by Pr3d4dor** [comment]
Acho que isso é muito "overkill", creio que as configurações já existentes de controle de e-mail já são suficientes.

Não estamos implementando muito novas funcionalidades pois estamos refazendo o mapos em Laravel. Por isso estamos com foco em correção de bugs e não em novas funcionalidades.
