### ISSUE TITLE
Gerar PDF da OS

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#688]
Uma forma de gerar um PDF da OS, talvez a possibilidade de enviar o PDF em an exo por e-mail e whatsapp.

**Comment by Pr3d4dor** [comment]
Não vejo vantagem nessa funcionalidade pois já é possível enviar a OS por e-mail.

Já é possível gerar a OS em pdf, se vc clicar para imprimir em formato A4 é possível salvar como PDF ao invés de imprimir.
