### ISSUE TITLE
Bug ao acessar pelo celular

### ISSUE THREAD

**Issue by DanielAraujo98** [RamonSilva20/mapos#690]
Utilizando sistema pelo navegador do smartphone, bug acontence ao tentar acessar opções do menu. Um exemplo quando tento acessar sub-menu de Configurações e rolo para baixo para visualizar as opções. O menu é fechado sem que tenha escolhido nenhuma opção..

Etapas para reproduzir o comportamento:
1. Clique em Menu -> Configurações
2. Role para baixo e/ou cima
3. Ver erro

 - Dispositivo: Motorola G7
 - SO: Android 9
 - Navegador Google Chrome

**Comment by Pr3d4dor** [comment]
Pode postar uma print para ficar mais fácil?

Iremos deixar anotado aqui e corrigir quando possível.

**Comment by DanielAraujo98** [comment]
Print não demostra o bug pois é apenas ações que acontece.

**Comment by mariodarin** [comment]
Acredito que o "bug" comentado é a respeito do tema "Neve" que a cor de texto das caixas ficam na mesma cor de fundo. Verifique os arquivos da pasta ../assets/css/ provavelmente em temas.css ou matrix-style.css e altere ou insira um parâmetro pra #sidebar>ul.li e o resto é contigo

**Comment by DanielAraujo98** [comment]
Não. Já testei nos dois temas. Não é a opacidade das letras, e sim uma reação que acontece como descrito.
