### ISSUE TITLE
Gráficos 

### ISSUE THREAD

**Issue by JulianoSavino** [RamonSilva20/mapos#692]
Boa tarde, incluí os gráficos de movimentação mensal no meu MapOS mas o curioso é que só funciona corretamente na versão 3.6,e quando vou pra uma superior, no caso a atual 4.5.3 não carrega nada. Não entendo muito de programação, sou mais auto-didata e os códigos puxei de outra variação do MapOS que foi customizada por um rapaz chamado Rodrigo Infotech.
Gostaria de ajuda para entender o que posso fazer (aprender) para consertar isso.
Agradeço a todos desde já.
segue link da versão 3.6 que está funcionando.
https://drive.google.com/open?id=1AOzizsWYKztVmfDbB3UQ7fGfmcciNSuR

**Comment by Pr3d4dor** [comment]
Preciso que vc defina exatamente o que vc quer dizer com "funciona corretamente na versão 3.6".

Qual é o comportamento esperado?

**Comment by JulianoSavino** [comment]
ok, na versão 3.6 os gráficos aparecem normalmente, já em qualquer outra versão, eles simplesmente não aparecem, como se não pudesse ser carregados ou se a origem dos dados não existisse.
se eu mudo a pasta Mapos para a que contem a versão 3.6, os gráficos são carregados normalmente.
Versão 3.6
![3 6](https://user-images.githubusercontent.com/61118829/80430952-88e78d80-88c6-11ea-836d-e40335201065.PNG)
Versão 4.5.3
![4 5](https://user-images.githubusercontent.com/61118829/80430953-89802400-88c6-11ea-8d30-893f794fd0cd.PNG)

Sei que dirá que os dados estão incorretos nas novas versões, ja verifiquei isso, porém ha uma curiosidade ainda maior. Aff, após os navegadores carregarem os gráficos na versão 3.6 eu posso mudar para a pasta 4.5.X que os mesmos funcionam perfeitamente, se adicionar qq receita ou despesa ele mostram sem erros, mas se eu pressionar F5 ou CTRL+F5 eles somem, inclusive os dados de OS. Já testei em todos os navegadores que confio (chrome, mozilla, edge, opera, ie...)
Não sei se tem algo errado nas bibliotecas, no caso incompatibilidade. Se for, estou ferrado pois não faco ideia de como arrumar. Só sei que seria ótima função para o MapOS, ao menos o ano vigente.

**Comment by Pr3d4dor** [comment]
Mas esses gráficos de Balanço não existem no mapos padrão.

Você está usando uma versão customizada?

**Comment by Pr3d4dor** [comment]
Implementei o gráfico se baseando na versão customizada que vc passou.

**Comment by JulianoSavino** [comment]
Agradeço imensamente a ajuda....
Obrigado mesmo!!!
