### ISSUE TITLE
Erro na Atualização

### ISSUE THREAD

**Issue by DanielAraujo98** [RamonSilva20/mapos#695]
Me deparei com esta mensagem após dar o comando de atualização pelas configurações do Sistema.

![image](https://user-images.githubusercontent.com/53981325/80437606-62325280-88d8-11ea-8417-67fb9e42741c.png)

**Comment by DanielAraujo98** [comment]
Dados de versões

Versão atual: 4.5.4
Versão de Atualização: 4.6

**Comment by Pr3d4dor** [comment]
Parece que ele não extraiu o zip com as atualizações, você precisa ter o zip instalado no seu computador e conseguir rodar o comando `unzip` no terminal.

**Comment by Pr3d4dor** [comment]
Vou melhorar essa parte de extração do arquivo.

**Comment by cabralwms** [comment]
Tambem tive erro ao atualizar e tenho o zip instalado. Fiz algumas atualizações utilizando esse novo botão atualizar tudo tinha dado certo e essa agora deu esse erro. tambem

**Comment by DanielAraujo98** [comment]
Consegui resolver fazendo a operação manualmente. Descompactei a pasta zipada com os arquivos da atualização e substituir os arquivos.

**Comment by cabralwms** [comment]
Tambem fiz a atualização do modo antigo e ai funcionou hahahahaa
