### ISSUE TITLE
Dúvidas sobre Bugs após atualização. Instalo ou Espero?

### ISSUE THREAD

**Issue by maycon1977** [RamonSilva20/mapos#697]
Olá, pessoal. Eu só queria esclarecer umas dúvidas que me ocorreram. Seguinte:

Utilizo uma versão antiga do Mapos (3.14.2) que customizei várias coisas e me atende relativamente bem. Sei que ao longo do tempo, implementaram várias idéias da galera e até algumas sugestões minhas (a organização das pastas dos anexos é uma delas). Estava adiando a minha migração entre as versões 3.xx pra ir logo pra 4.00 e documentar a posteriori todas as minhas customizações pra saber se vocês gostariam também delas...

Quando chegou a versão 4.00 eu me enrolei um pouco com essa nova etapa do composer e tenho me segurado pra instalar novamente do zero por causa não somente desse passo que ainda não me ficou bem claro, bem como as sucessivas atualizações da versão 4.xx que tem ocorrido nesses últimos 2 meses. É ótimo ter um sistema com sucessivas atualizações, personalizações, equipe colaborativa 0800 que está sempre ouvindo e ajudando os mais leigos como eu, porém esse monte de coisa que o pessoal tem relatado, tem me assustado e cada vez mais adio a instalação nova por temer que o sistema esteja instável (talvez por tanta perfumaria que a gente tem sugerido, aqui faço mea culpa tb). Então fica a dúvida:

Claro que a minha idéia é instalar a versão nova em outra pasta do servidor e utilizar as 2 versões em paralelo até migrar de vez (atualizando o banco de dados, etc), mas...

### **Gostaria de saber dos mais experientes que se instalar o sistema do zero ele está estável o suficiente já pra não afetar o meu trabalho ao utilizá-lo e esses problemas que o pessoal tem relatado são somente por não saberem instalar/utilizar ou se realmente corro o risco de instalar e ter que ficar 'escovando bits' aqui...?**

Desde já, agradeço por toda as dica, suporte e paciência.

**Comment by Pr3d4dor** [comment]
O que você pode fazer é instalar o mapos na versão mais recente e duplicar o seu banco de dados atual e conectar a versão mais nova nessa cópia pra testar.

Sobre as suas customizações não tem outro modo de fazer, você precisa replicar elas na nova versão. O mapos está estável, apenas algumas funcionalidades que apresentam alguns bugs como o por exemplo o atualizador automático. As demais coisas sempre permaneceram do mesmo modo e apenas contaram com adições.

Sobre o passo do composer, basta somente você instalar o composer no seu computador e abrir um terminal na pasta raiz do mapos e rodar o comando `composer install`. Não consigo entender a complexidade de rodar esse passo. O composer é o gerenciador de dependências padrão do PHP e praticamente qualquer projeto usa ele.

**Comment by maycon1977** [comment]
> O que você pode fazer é instalar o mapos na versão mais recente e duplicar o seu banco de dados atual e conectar a versão mais nova nessa cópia pra testar.

SIM! Isso aí eu já faria mesmo, pois vai que dá M***

> Sobre as suas customizações não tem outro modo de fazer, você precisa replicar elas na nova versão.

SIM! Tb sei desses passos. O lance é que tudo que fiz, não documentei, então nem sei mas o que eu "inventei", o que já tinha nas versões antigas e o que já foi implementado na versão atual. Customizando a versão atual, irei documentando e compartilhando pra verificar se vocês aprovam alguma(s).

> O mapos está estável, apenas algumas funcionalidades que apresentam alguns bugs como o por exemplo o atualizador automático. As demais coisas sempre permaneceram do mesmo modo e apenas contaram com adições.

ÓTIMO. Essa era minha preocupação principal mesmo, pois mesmo rodando em paralelo até eu acertar o que considerar OK pra mim, estava com receio de além de ter que recustomizar, ter que caçar BUGS que a galera tá relatando aí...

> Sobre o passo do composer, basta somente você instalar o composer no seu computador e abrir um terminal na pasta raiz do mapos e rodar o comando `composer install`. Não consigo entender a complexidade de rodar esse passo. O composer é o gerenciador de dependências padrão do PHP e praticamente qualquer projeto usa ele.

Embora seja curioso, não sou programador, uso Windows (quando falam em abrir terminal me dá até palpitação)... Teve uma época (uns 10 anos atrás) que eu trabalhava bastante com wordpress e instalei ele offline, apache, mysql, etc, pra fazer algumas orientações em temas para Blogs, mas com o tempo nunca mais 'brinquei com isso'.

> O seu servidor tem acesso SSH? Se sim é bem fácil instalar o composer e rodar. 

Olha, não sei... provavelmente sim. É Hostgator daqueles planos M, que dão direito à bastante coisa, acesso ilimitado, vários domínios, etc. Você saberia me dar um passo-a-passo ou algum link pra eu estudar como fazer?

> Se for só cpanel, você precisa rodar o comando do composer na pasta local e isso irá gerar a pasta `application/vendor` e você precisa fazer o upload dessa pasta via FTP para o teu servidor.

Esse passo que me assusta, pois vi que existe o "composer pra windows", mas a infraestrutura do que instalar antes (apache? mysql? etc,0 eu não tenho idéia... Baixei aqui a última versão do UBUNTU e tô pensando em rodar ele pelo pendrive pra ver se sigo o passo lá do terminal e tal...

@Pr3d4dor Muito obrigado por tudo, cara...

Se algum amigo mais experiente quiser e puder mais dicas sou todo ouvidos!

**Comment by Pr3d4dor** [comment]
Tutorial da HostGator para acessar o SSH:
https://suporte.hostgator.com.br/hc/pt-br/articles/115000390774-Como-acessar-o-SSH-

Tutorial do Composer:
https://suporte.hostgator.com.br/hc/pt-br/articles/115004145214-Como-instalar-o-Laravel-#composer

**Comment by maycon1977** [comment]
> Tutorial da HostGator para acessar o SSH:
> https://suporte.hostgator.com.br/hc/pt-br/articles/115000390774-Como-acessar-o-SSH-
> 
> Tutorial do Composer:
> https://suporte.hostgator.com.br/hc/pt-br/articles/115004145214-Como-instalar-o-Laravel-#composer

Conseguindo, prometo mandar um passo-a-passo aqui pra quem também está com dúvidas e/ou medo, de forma bem leiga (como eu) pra facilitar e se vocês acharem pertinente acrescentam lá nas instruções de incstalação na Home, blz?

Acho que vc salvou minha vida, cara... Tava me sentindo muito burro por empacar nesse passo!

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.

**Comment by maycon1977** [comment]
> Vou fechar a issue, se precisar de mais ajuda é só reabrir.

Tá ótimo!
