### ISSUE TITLE
Erro no relatorio financeiro

### ISSUE THREAD

**Issue by atendeemcasa** [RamonSilva20/mapos#7]
Quando se vende um produto, no cadastro de produto é informado o valor de custo e o valor de venda do produto. 
Quando se extrai um relatorio financeiro mensal por exemplo, no caso da venda de algum produto, o valor que aparece é bruto, ou seja o valor de venda, o que gera um relatorio impreciso, sendo que o sistema deveria mostrar o valor real de ganho, subtraindo o valor de custo do valor de venda.

**Comment by RamonSilva20** [comment]
Isso não necessariamente é um erro ou problema, o relatório existente pode sim ser útil em alguns casos. O que você necessita é de outro relatório, com um nível de detalhamento diferente.

**Comment by atendeemcasa** [comment]
Sim... Fiz aqui, pra acertas as coisas, lancei a despesa em separado.

Obrigado pelo retorno.

Bom dia!

Em 08/09/2016 11:07 AM, "Ramon Silva" <notifications@github.com> escreveu:
