### ISSUE TITLE
Problema após instalação

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#700]
Alguém pode me ajudar com a instalação?

Baixei a nova versão
Executei o composer e o docker composer, porém no docker composer ficou repedinto conforme a imagem abaixo:
![image](https://user-images.githubusercontent.com/64565246/80660472-2c20da00-8a62-11ea-89f0-8cc3961a48eb.png)

Em seguida importei o backup no phpmyadmim, fiz a pré instalação do mapos. Na hora de logar aparece este erro:
![image](https://user-images.githubusercontent.com/64565246/80660566-7a35dd80-8a62-11ea-9099-2d977275b584.png)

Alguem poderia me ajudar? Ou tenha algum vídeo explicando como fazer a hospedagem corretamente. 

Grato.

**Comment by Pr3d4dor** [comment]
Deu erro no container no banco de dados.

Abra a pasta docker e delete a pasta data.

Após isso tente iniciar novamente.

**Comment by jhonatanmoraiscosta** [comment]
Amigo é normal o comando  "docker-compose up --force-recreate" ficar repetindo conforme a primeira imagem?
Irei apagar a pasta data e tentar novamente e retorno em breve.

**Comment by willph** [comment]
> Alguém pode me ajudar com a instalação?
> 
> Baixei a nova versão
> Executei o composer e o docker composer, porém no docker composer ficou repedinto conforme a imagem abaixo:
> ![image](https://user-images.githubusercontent.com/64565246/80660472-2c20da00-8a62-11ea-89f0-8cc3961a48eb.png)
> 
> Em seguida importei o backup no phpmyadmim, fiz a pré instalação do mapos. Na hora de logar aparece este erro:
> ![image](https://user-images.githubusercontent.com/64565246/80660566-7a35dd80-8a62-11ea-9099-2d977275b584.png)
> 
> Alguem poderia me ajudar? Ou tenha algum vídeo explicando como fazer a hospedagem corretamente.
> 
> Grato.

É hospedagem Linux? Ou instalação em localhost? 
Hospedagem compartilhada ou Não?

**Comment by jhonatanmoraiscosta** [comment]
Amigo, apaguei a pasta data do docker e tentei rodar o comando (docker-compose up --force-recreate)  porem fica somente assim, é normal?
![image](https://user-images.githubusercontent.com/64565246/80779762-00295580-8b43-11ea-92f7-2ab73f559d65.png)

**Comment by Pr3d4dor** [comment]
Não é normal, ainda está com problema no mysql, tente reinstalar tudo do zero e também rode o comando `docker system prune -- all`
