### ISSUE TITLE
Pessoal. Fiz uma atualização de um Mapos 3.3 pra esse. Fiz o backup e importei pro banco novo mas ele não listou as OS. O estoque e clientes deu certo, no Dashboard no rodapé ele até mostra o número de OS abertas mas na tela das OS é como se não tivesse nenhuma OS. A tela está funcionando normal pra criar OS e etc. só não listou as que já tinha. 

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#701]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
Duplicado #702
