### ISSUE TITLE
Erro na atualização 

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#702]
Fiz uma atualização de um Mapos 3.3 pra essa ultima versão. Quase tudo ok. Somente não listou as OS na tela das OS abertas. Até no dashboard somou lá. Diz que tem o número certo de OS aberta. No banco De dados elas aparecem cadastradas Normal. Só na tela que não listou. A tela funciona normalmente. Para incluir nova os e etc. mas as antigas não apareceu

**Comment by Pr3d4dor** [comment]
Atualizou os devidos campos no banco de dados também?

**Comment by giampaulo** [comment]
> Atualizou os devidos campos no banco de dados também?

Desculpe. Mas quais Campos deveriam ser atualizados ? Não vi essa orientação.

**Comment by Pr3d4dor** [comment]
Na pasta updates tem todos os sqls que vc deve rodar autualizando de versão em versão.

**Comment by Pr3d4dor** [comment]
Vou fechar a issue por enquanto, caso precise de mais ajuda só reabrir.

**Comment by giampaulo** [comment]
Ok
