### ISSUE TITLE
Erro ao extrair relatório

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#703]
Instalei o mapos 4.6.2
Quando vou extrair qualquer um dos relatórios aparece este erro:
![image](https://user-images.githubusercontent.com/64565246/80813762-064e1f00-8ba1-11ea-8ed2-0649412861da.png)

**Comment by Pr3d4dor** [comment]
Não achou o logo do emitente, faça o upload novamente em Configurações >> Emitente

**Comment by jhonatanmoraiscosta** [comment]
> Não achou o logo do emitente, faça o upload novamente em Configurações >> Emitente

Muito obrigado amigo deu certo!
