### ISSUE TITLE
Erro ao editar/criar usuários.

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#704]
Não consigo adicionar ou editar algum usuário, alguém sabe o que pode ser?

![image](https://user-images.githubusercontent.com/64565246/80814985-3991ad80-8ba3-11ea-8fc8-a0c6bea9e8fe.png)

Preenchi todos dados corretamente e tentei diversas vezez.  Estou utilizando a nova versão 4.6.2

**Comment by Pr3d4dor** [comment]
Abra o arquivo index.php e mude a linha 69 para `define('ENVIRONMENT', 'development');` para poder conseguir ver o erro.

**Comment by jhonatanmoraiscosta** [comment]
Este foi o erro que apareceu amigo:
![image](https://user-images.githubusercontent.com/64565246/80815910-db65ca00-8ba4-11ea-9f0b-7bd0d58b24f5.png)

**Comment by Pr3d4dor** [comment]
Lembre que vc precisa colocar um CPF válido.

**Comment by jhonatanmoraiscosta** [comment]
Estou colocando um válido sim. Continua dando este erro.
