### ISSUE TITLE
imprimir não fiscal

### ISSUE THREAD

**Issue by kikonavega** [RamonSilva20/mapos#706]
Ao tentar imprimir uma ORDEM DE SERVIÇO na  A4 fica tudo ok, mas na impressora nao fiscal aparece apenas os dados da minha empresa.
o que nao aparece:

CLIENTE / RESPONSÁVEL / STATUS OS: / DESCRIÇÃO: / DEFEITO APRESENTADO: / Data Assinatura do Cliente 

tenho assistência de celular... quero dar uma via para o cliente

windows 10 64bits
xamp x64 7.4.5
localhost
compose  5.1.0.0

**Comment by willph** [comment]
O imprimirOsTermica.php é uma versão simples para imprimir em impressora tipo 56mm ou 80mm.

Mas você pode pegar os dados de imprimirOs.php e colocar em imprimir OsTermica.php

No imprimirOs.php tem o código referente ao CLIENTE / RESPONSÁVEL / STATUS OS: / DESCRIÇÃO: / DEFEITO APRESENTADO: / Data Assinatura do Cliente
Se tiver urgência.

Caminho dos arquivos 

```mapos/application/views/os/imprimirOsTermica.php```

```mapos/application/views/os/imprimirOs.php```

**Comment by kikonavega** [comment]
show meu amigo, obrigado por hr. Vou tentar aqui

**Comment by willph** [comment]
Ex:


                        <table class="table table-condensend">
                            <tbody>
                                <tr>
                                    <td style="width: 50%; padding-left: 0">
                                        <ul>
                                            <li>
                                                <span>
                                                    <h5><b>CLIENTE</b></h5>
                                                    <span><?php echo $result->nomeCliente ?></span><br />
                                                    <span><?php echo $result->rua ?>, <?php echo $result->numero ?>, <?php echo $result->bairro ?></span>,
                                                    <span><?php echo $result->cidade ?> - <?php echo $result->estado ?></span><br>
                                                    <span>E-mail: <?php echo $result->email ?></span><br>
                                                    <span>Celular: <?php echo $result->celular_cliente ?></span>
                                            </li>
                                        </ul>
                                    </td>
                                    <td style="width: 50%; padding-left: 0">
                                        <ul>
                                            <li>
                                                <span>
                                                    <h5><b>RESPONSÁVEL</b></h5>
                                                </span>
                                                <span><?php echo $result->nome ?></span> <br />
                                                <span>Telefone: <?php echo $result->telefone_usuario ?></span><br />
                                                <span>Email: <?php echo $result->email_responsavel ?></span>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

**Comment by Pr3d4dor** [comment]
Vou fechar a issue pois parece que foi resolvido. Caso consiga seria interessante você fazer uma PR com a melhoria na impressão.

**Comment by kikonavega** [comment]
Estou com outras duvidas

1. quando vou imprimir na 58mm em outros programas ou no teste do windows a impressora imprime bem, sai tudo ok, mas quando imprime no mapos as letras saem meio borradas, algumas serrilhadas, algumas negrito, parece ate que acabei de instalar o windows e nao liguei o ClearType. Nao sei explicar mas acredito que e porque preciso diminuir quase 50% da escala para caber na folha de impressão. o que posso fazer para melhorar isso?

2. como mencionei que preciso diminuir muito a escala para caber na folha, e mesmo colocando a margem no 0 sobra muito espaço do lado esquerdo... como faço para usar melhor esse espaço?

**Comment by eletrojunior** [comment]
Vish .... desde 2020 e nenhuma resposta
