### ISSUE TITLE
Duvida atualização.

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#707]
Pessoal o programa deve detectar as atualizações automaticamente? Como faço para não baixar tudo novamente e fazer o processo de intalação de novo.
Ele não está mostrando nova versão disponível em configurações.

![image](https://user-images.githubusercontent.com/64565246/80868929-d02d9f80-8c73-11ea-8f8f-c541f4156997.png)

**Comment by Pr3d4dor** [comment]
Talvez corrompeu algum arquivo no momento que você fez a atualização, se você estiver na última versão e não ter quebrado nada durante a atualização ele exibirá que já está atualizado.
