### ISSUE TITLE
Valor total no painel de OS errado

### ISSUE THREAD

**Issue by Doonine** [RamonSilva20/mapos#708]
No painel de OS o valor total aparece muito maior do que está na OS, parece que existe um fator multiplicador quando se tem mais de um serviço e mais de um produto na mesma OS

**Comment by Pr3d4dor** [comment]
A qual painel você se refere?

**Comment by Doonine** [comment]
O painel principal, onde lista todas as os e tem os botões para enviar email, whataspp, impressão, edição, etc...

**Comment by Pr3d4dor** [comment]
Corrigido em #709
