### ISSUE TITLE
Personalizar a visualização por permissão

### ISSUE THREAD

**Issue by mikxingu** [RamonSilva20/mapos#71]
Boa noite! Gostaria de saber se existe forma de ocultar alguns itens da Dashboard por permissão, pois por exemplo, criei um usuário com permissões de técnico, removi todos os itens de permissão, ele tira todos os menus do lado esquerdo, porém na dash ainda apresenta o faturamento, total de receitas, custo dos produtos e etc. Existe a possibilidade de ocultar certos itens dependendo da permissão? Se não, fica ai uma dica de implementação. Desde já agradeço, estou usando o sistema para fazer alguns testes e até agora, show de bola! Está de super parabéns.
Obrigado!

**Comment by drelldeveloper** [comment]
Você está dizendo, retirar alguns items da interface? Caso for, não é possível :(
