### ISSUE TITLE
Erro ao instalar composer - Primeira Instalacao

### ISSUE THREAD

**Issue by LucasPolli** [RamonSilva20/mapos#710]
Senhores, estou tentando efetuar a instalacao, uso hostgator compartilhado, no momento usando PHP 7.1
fiz o download, descompactei or arquivos, 
verificando a versao do PHP:

**# php --version
PHP 7.1.33 (cli) (built: Apr 28 2020 22:51:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.**

ao executar composer install --no-dev tenho o seguinte erro:

**# composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.**

  **Problem 1
    - Installation request for doctrine/annotations v1.4.0 -> satisfiable by doctrine/annotations[v1.4.0].
    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/cache 1.10.0 -> satisfiable by doctrine/cache[1.10.0].
    - doctrine/cache 1.10.0 requires php ~7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/collections 1.6.4 -> satisfiable by doctrine/collections[1.6.4].
    - doctrine/collections 1.6.4 requires php ^7.1.3 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/common 2.12.0 -> satisfiable by doctrine/common[2.12.0].
    - doctrine/common 2.12.0 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 5
    - Installation request for doctrine/event-manager 1.1.0 -> satisfiable by doctrine/event-manager[1.1.0].
    - doctrine/event-manager 1.1.0 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 6
    - Installation request for doctrine/inflector 1.3.1 -> satisfiable by doctrine/inflector[1.3.1].
    - doctrine/inflector 1.3.1 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 7
    - Installation request for doctrine/lexer 1.2.0 -> satisfiable by doctrine/lexer[1.2.0].
    - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 8
    - Installation request for doctrine/persistence 1.3.7 -> satisfiable by doctrine/persistence[1.3.7].
    - doctrine/persistence 1.3.7 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 9
    - Installation request for doctrine/reflection 1.2.1 -> satisfiable by doctrine/reflection[1.2.1].
    - doctrine/reflection 1.2.1 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 10
    - Installation request for filp/whoops 2.7.1 -> satisfiable by filp/whoops[2.7.1].
    - filp/whoops 2.7.1 requires php ^5.5.9 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 11
    - Installation request for mercadopago/dx-php 1.9.0 -> satisfiable by mercadopago/dx-php[1.9.0].
    - mercadopago/dx-php 1.9.0 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 12
    - Installation request for mpdf/mpdf v8.0.5 -> satisfiable by mpdf/mpdf[v8.0.5].
    - mpdf/mpdf v8.0.5 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 13
    - Installation request for myclabs/deep-copy 1.9.5 -> satisfiable by myclabs/deep-copy[1.9.5].
    - myclabs/deep-copy 1.9.5 requires php ^7.1 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 14
    - Installation request for paragonie/random_compat v9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 15
    - Installation request for setasign/fpdi v2.3.2 -> satisfiable by setasign/fpdi[v2.3.2].
    - setasign/fpdi v2.3.2 requires php ^5.6 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.**

como se eu ainda estivesse rodando a versao 5.4 do PHP, alguem tem alguma dica?

**Comment by Pr3d4dor** [comment]
O composer usa a versão do php resultante do comando `which php`.

https://stackoverflow.com/questions/45914104/composer-uses-wrong-php-version-but-php-v-shows-the-correct-one-ubuntu

**Comment by LucasPolli** [comment]
agradeço o rapido retorno
esse comando nao me retorna nada...

**Comment by Pr3d4dor** [comment]
Você pode instalar usando o comando `composer install --ignore-platform-reqs` mas não recomendo.

Recomendo corrigir a versão do PHP usada pelo composer.

**Comment by LucasPolli** [comment]
entendi.. vou tentar uma solucao com o suporte entao...obrigado
