### ISSUE TITLE
Bug ao tentar cadastrar cliente

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#711]
Pessoal boa tarde ao atualizar o Sistema deu erro ao tentar cadastrar um cliente agora alguem sabe me informar. Aparece esse erro no LOG do apache2 error.log.

192.168.1.1 - - [02/May/2020:14:52:47 -0300] "POST /sistemafw/index.php/clientes/adicionar HTTP/1.1" 200 3451 "https://www.firewarrior.com.br/sistemafw/index.php/clientes/adicionar" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
^C
not-debian:/var/www/sistemafw# tail -f /var/log/apache2/error.log 
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
                                                                                            

[Sat May 02 08:00:53.228657 2020] [php7:error] [pid 26515] [client 5.101.0.209:39686] script '/var/www/index.php' not found or unable to stat

                                                                                            
  [RuntimeException]                                                                        
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  

grato pela ajuda

**Comment by Pr3d4dor** [comment]
Atualizou a coluna clientes com as novas colunas?

**Comment by cabralwms** [comment]
Eu cliquei em atualizar tabelas no menu configuração/sistema. teria que fazer de outra forma?

**Comment by Pr3d4dor** [comment]
@cabralwms Verifique se a tabela de clientes contém as colunas `contato` e `complementto` e caso estiverem lá a tabela está atualizada. Caso contrário é outro problema.

**Comment by cabralwms** [comment]
entrei pelo PHPMYADMIN nao encontrei essas tabelas será que deu erro na atualização então?

**Comment by Pr3d4dor** [comment]
Acho que você leu errado, é na tabela `clientes` as colunas `contato` e `complemento`.

**Comment by cabralwms** [comment]
Eu fui ate a tabela clientes e dentro dela nao tem complemento nem contato

**Comment by Pr3d4dor** [comment]
Tente adicionar manualmente as colunas:
```
`contato` varchar(45) DEFAULT NULL,
`complemento` varchar(45) DEFAULT NULL,
```

**Comment by cabralwms** [comment]
Desculpa eu adiciono esses comando pelo mysql?

**Comment by Pr3d4dor** [comment]
Você pode fazer pelo phpmyadmin.

**Comment by Pr3d4dor** [comment]
Ou pelo mysql você pode rodar o comando:
```
ALTER TABLE `clientes` ADD `contato` varchar(45) DEFAULT NULL;
ALTER TABLE `clientes` ADD `complemento` varchar(45) DEFAULT NULL;
```

**Comment by cabralwms** [comment]
muito obrigado desculpa sou apenas curioso e não entendo muito de banco de dados mais consegui fazer pelo phmyadmin. Muito obrigado

**Comment by cabralwms** [comment]
Apareceu assim será que fiz corretamente?

ALTER TABLE `clientes` ADD `complemento` VARCHAR(45) NULL DEFAULT NULL AFTER `contato`;

**Comment by Pr3d4dor** [comment]
Se vc já fez pelo phpmyadmin não precisa fazer o comando no mysql.

**Comment by cabralwms** [comment]
Dessa vez cadastrou com sucesso e apagou tambem. Acredito que deu certo. Muito agradecido pela atenção.
