### ISSUE TITLE
impressora 58mm

### ISSUE THREAD

**Issue by kikonavega** [RamonSilva20/mapos#712]
boa noite

1. quando vou imprimir na 58mm em outros programas ou no teste do windows a impressora imprime bem, sai tudo ok, mas quando imprime no mapos as letras saem meio borradas, algumas serrilhadas, algumas negrito, parece ate que acabei de instalar o windows e nao liguei o ClearType. Nao sei explicar mas acredito que e porque preciso diminuir quase 50% da escala para caber na folha de impressão e esta acabado com a qualidade. o que posso fazer para melhorar isso?

no excel coloquei a (ARIAL) tamanho 20 e diminui a escala para caber na folha, imprimi e ficou ruim
mas com a mesma fonte coloquei tamanho 8 imprimi ficou perfeita
OBS: usando (small fonts) com a fonte em 2 consigo imprimir e ler com uma lupa rsrs

2. como mencionei que preciso diminuir muito a escala para caber na folha, e mesmo colocando a margem no 0 sobra muito espaço do lado esquerdo, como se ela estivesse enquadrada em uma tabela... como faço para usar melhor esse espaço?

3. pesquisei bastante e descobri a as fontes (small fonts) e (arial) sao as mais apropriadas para impressora nao fiscal, tem como mudar a fonte?

**Comment by Pr3d4dor** [comment]
Vou analisar e implementar os ajustes assim que possível.

**Comment by kikonavega** [comment]
muito obrigado Pr3d4dor,

o amigo tem essa impressora? 
pq acredito que vc vai conseguir ver o que estou falando somente na pratica

**Comment by Pr3d4dor** [comment]
@kikonavega Pior que não tenho essa impressora, mas vou implementar com os detalhes que você passou e pedir para o @willph testar. Ele tem uma impressora dessas.

**Comment by Pr3d4dor** [comment]
Melhorado com a PR #757
