### ISSUE TITLE
Bug de email imagem do emitente

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#713]
Bom dia a todos.
Novamente o bug da imagem do emitente não está aparecendo no email enviado. Já dei permissão na imagem logo.png e nao aparece. 
Grato pela atenção.

**Comment by Pr3d4dor** [comment]
Isso não é um bug do mapos, você tem que verificar as configurações do teu servidor, e precisa também ser um servidor online, pois localhost não irá aparecer imagens no e-mail.

**Comment by cabralwms** [comment]
Opa Pr3d4dor meu servidor e próprio com link dedicado, estava aparecendo normal, ai quando atualizou parou. Eu tinha colocado um link direto para a Imagem logo.png mais isso nao deveria ser automático quando tem um sistema online??

**Comment by cabralwms** [comment]
eu alterei no arquivo dentro de application/viewr/os/emails/os.php

coloquei direto o link da imagem no meu servidor e apareceu no email.

**Comment by Pr3d4dor** [comment]
A última vez que esse arquivo foi alterado foi há 10 meses atrás. Então creio que seja alguma permissão de pasta ou configuração do apache.
