### ISSUE TITLE
Instalação Xampp

### ISSUE THREAD

**Issue by tecmatheusr** [RamonSilva20/mapos#714]
Podem fazer um tutorial de como instalar em ambiente interno pelo xampp? tentei de tudo aqui e nada parece dar certo.

**Comment by Pr3d4dor** [comment]
Qual exatamente seria a sua maior dúvida?

**Comment by tecmatheusr** [comment]
Obrigado por me responder, na ultima opção, ele da um erro de conexão, no
caso não conecta, mas quero mesmo instalar ele na minha hospedagem web, é
só seguir os passos do tutorial?

Em seg., 4 de mai. de 2020 às 17:26, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Sim, só seguir os passos do tutorial, você pode acompanhar na issue #715 também.

**Comment by tecmatheusr** [comment]
agora estou tentando instalar na minha hospedagem e não consigo instalar o composer? existe algum video explicando como instalar o mapos? estou precisando muito
