### ISSUE TITLE
Ajude-me

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#715]
Ja estou algum tempo tentando algum tempo atualizar minha versao 3.14.1 para atual, no entanto não tenho nenhuma experiencia com composer, minha instalação e feita em um webserver. tem algum tutorial mais detalhado para que eu leigo possa seguir??

Obrigado e parabéns ao desenvolvimento pois vem me ajudado muito com gerenciamento de O.Ss.

**Comment by Pr3d4dor** [comment]
- Instale composer no seu computador local.
- Realize um backup do seu banco de dados atual.
- Crie um novo banco de dados usando o backup.
- Atualize o banco de dados que você criou por último conforme os arquivos SQL da pasta updates.
- Baixe o mapos na última versão, rode o comando `composer install` pelo terminal na pasta raiz do mapos. Coloque em outra pasta no webserver e configure para usar o banco de dados que você atualizou por último.
-  Teste para verificar se está tudo OK.

**Comment by fwsund** [comment]
**ok!**  Instale composer no seu computador local.
**ok!**  Realize um backup do seu banco de dados atual.
**ok!**  Crie um novo banco de dados usando o backup.
**ok!**  Atualize o banco de dados que você criou por último conforme os arquivos SQL da pasta updates.

**FALL**  Baixe o mapos na última versão, rode o comando composer install pelo terminal na pasta raiz do mapos. Coloque em outra pasta no webserver e configure para usar o banco de dados que você atualizou por último.
Teste para verificar se está tudo OK.

Não consigo passar desta parte pois não sei como funciona o composer, poderia me ajudar?

**Comment by Pr3d4dor** [comment]
Esse vídeo pode lhe ajudar: https://www.youtube.com/watch?v=gXQZlrbzesc

Mas basicamente o que você precisa fazer é entrar na pasta do mapos atualizado, com o terminal, e rodar o comando `composer install`. Esse comando irá baixar as dependências do projeto e criar uma pasta `application/vendor`. Essa pasta também precisa estar no seu webserver. Então se for uma hospedagem compartilhada, será necessário enviar essa pasta via FTP.

**Comment by fwsund** [comment]
neste momento esta baixando as dependências,  consigo ver também a pasta "application/vendor" neste caso 16 packages . Ao final devo enviar tudo ao servidor via FTP e configurar o novo banco de dados?

**Comment by Pr3d4dor** [comment]
Isso

**Comment by Pr3d4dor** [comment]
Também a coluna cep na tabela usuários:
```
ALTER TABLE `clientes` ADD `contato` varchar(9) DEFAULT `70005-115` NOT NULL;
```

**Comment by fwsund** [comment]
de clientes funcionou mas o de usuarios deu erro 
#1054 - Coluna '70005-115' desconhecida em 'DEFAULT'

**Comment by Pr3d4dor** [comment]
Editei o comentário

**Comment by fwsund** [comment]
fiz tudo conforme você me falou, mas esta dando tela branca, não carrega nada, por acaso tem apagar mais alguma coisa da raiz? apaguei a pasta install

**Comment by Pr3d4dor** [comment]
Configurou corretamente os arquivos `application/config/database.php` e `application/config/config.php`?

Também abra o arquivo index.php e mude o environmente para 'development' ou production' na linha 59.

**Comment by fwsund** [comment]
não consegui fazer a conexão, tela fica branca, me certifiquei que application/config/database.php e application/config/config.php estão corretos. sigo sem sucesso

**Comment by Pr3d4dor** [comment]
Arrumou o index.php?

**Comment by fwsund** [comment]
sim, editei para development, production e testing conforme descrito e em todos os casos acontece a mesma coisa

**Comment by Pr3d4dor** [comment]
Tentou olhar nos logs de erro do servidor (apache) ou do PHP? Talvez esteja com alguma configuração errada.

Outra coisa, qual a versão do PHP rodando na hospedagem?

**Comment by fwsund** [comment]
5.5 php neste momento

**Comment by Pr3d4dor** [comment]
Então esse é o problema, precisa do PHP 7.1 no mínimo agora.

O PHP 7.1 pra baixo perdeu o suporte.

**Comment by fwsund** [comment]
posso colocar 7.4? essa e a ultima versão diponivel para atualizar

**Comment by Pr3d4dor** [comment]
Sim, qualquer versão acima da 5.5.

**Comment by fwsund** [comment]
Muito Obrigado!!! deu certinho, pelo que posso verificar esta tudo ok! 

tem um erro ao visualizar O.S, mas vc me ajudou muito por hj.

**Comment by Pr3d4dor** [comment]
De nada, se puder criar uma issue separada para esse erro do visualizar OS seria bom. Assim poderemos corrigir se for um problema no mapos.

**Comment by fwsund** [comment]
Pode deixar irei criar se caso for o mapos.
