### ISSUE TITLE
Disparo de SMS para cliente com status de OS e/ou Aprovação de Orçamento.

### ISSUE THREAD

**Issue by eduaraujothe** [RamonSilva20/mapos#716]
Pessoal, blz? Seguinte sistema está excelente, me atendendo muito bem.

Imagino que seja interessante implementar uma API de disparo de SMS via sistema.

Ex: Cliente deixou equipamento pra orçamento, assim que concluir o sistema dispararia um SMS com o numero da OS, valor e link de acesso ao sistema no painel do cliente. 
O SMS aceitaria retorno, tipo: 1. Aprovar Serviço. 2. Não Aprovar.

Se a pessoa quiser utilizar esse serviços de SMS que contrate um pacote para está utilizando esse serviço de SMS. Quem olha e-mail uma vez por dia? Seria algo parecido com a opção de whatsapp já existente no sistema.

Valeu, um abraço a todos.

**Comment by Pr3d4dor** [comment]
A ideia é interessante, mas não é muito viável até porque integração com disparo via SMS não é tão barato. 

E não sei se todos iriam querer/utilizar isso.

Além de que fazer a interação sendo um bot também é complexa e exige que o sistema esteja online e disponível na web para recebere os webhooks de retorno. Muita gente usa o mapos local com xamp/wamp, então não seria possível usar essa funcionalidade.

Portanto não acho que ter isso no core do mapos traria muitos benefícios.

**Comment by eduaraujothe** [comment]
Entendo, mais se for vê unicamente por esse lado, então qual sentido teria o painel do cliente já que a grande maioria utiliza o sistema **OFFLINE**? Mais de qualquer forma agradeço a interação.
