### ISSUE TITLE
Nova instalação da versão atual.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#717]
Bom dia,
infelizmente não estou conseguindo fazer a instalação da nova versão.
Hoje utilizo a versão 4.2.1 e tentei tanto atualizar quanto instalar uma nova.
Alguém tem interesse de fazer ela como trabalho e por um custo baixo?
Tenho hospedagem compartilhada, Plataforma: CentOS 5.11 - 64 bits.

**Comment by Pr3d4dor** [comment]
Qual o passo da instalação que você está com dúvida.

Já olhou na issue #715?

**Comment by Triaca** [comment]
@Pr3d4dor olhei.
fiz todo o processo, o mesmo que fiz na versão 4.2.1.
copiei a pasta vendor para o application. e nada.

Porém agora a noite, fiz uma instalação limpa, copiei o vendor e atualizei o banco e funcionou.
Porém não entendi a parte do docker, nem para o que é e nem como utilizar.

**Comment by Pr3d4dor** [comment]
Você não precisa utilizar o docker, o docker é comose fosse um servidor como o wamp. É um método alternativo de instalar e usar.
