### ISSUE TITLE
Instalação do MAPOS na minha Hospedagem

### ISSUE THREAD

**Issue by tecmatheusr** [RamonSilva20/mapos#718]
Uso a hospedagem da hostgator e queria saber quanto cobrariam pra instalar o sistema pra mim pelo acesso remoto, ja tentei de tudo e não consegui. :/

**Comment by willph** [comment]
Se tiver o sistema em localhost funcionando, basta subir a pasta que fica em application, VENDOR e seguir o processo de instalação.
Você pode transferir a pasta via FTP.
Lembrando que a VENDOR tem que ficar dentro da pasta application na hospedagem também.

**Comment by Triaca** [comment]
@willph mas e o "Docker"?
eu fiz o processo de copiar o vendo e deu erro.
fiz esse processo na ver. 4.2.1 e lá funcionou

**Comment by fwsund** [comment]
Boa tarde, caso tenha alguma duvida sobre a instalação pode conferir esse tutorial 
[](https://github.com/RamonSilva20/mapos/issues/715)

**Comment by fwsund** [comment]
tem um tutorial para instalação em hospedagem compartilhada 
[Issues715](https://github.com/RamonSilva20/mapos/issues/715)

**Comment by tecmatheusr** [comment]
O localhost tbm dá um erro :/ queria muito instalar e se alguém puder me
ajudar nisso, pago pelo serviço.

Em ter, 5 de mai de 2020 13:19, Wilmerson <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Só você ler o REAME.md e também o que está descrito na issue #715.

**Comment by tecmatheusr** [comment]
Vou tentar, é que não entendo muito sobre a instalação :/

Em ter, 5 de mai de 2020 18:13, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by giampaulo** [comment]
se precisar posso ajudar, nao sei se é contra as politicas aqui mas se quiser podemos ver.

**Comment by Pr3d4dor** [comment]
Não é contra as políticas mas apenas ele poderia tentar ler o guia para tentar fazer sozinho.

**Comment by tecmatheusr** [comment]
Me chama no whatsapp é 62992571694, to precisando demais.

Em ter., 5 de mai. de 2020 às 19:11, giampaulo <notifications@github.com>
escreveu:

**Comment by tecmatheusr** [comment]
Ta ok, vou tentar ler o guia, qualquer coisa volto aqui.

Em ter., 5 de mai. de 2020 às 19:18, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by tecmatheusr** [comment]
Eu uso windows, como rodas os comandos de terminal que pedem la no windows?

Em ter., 5 de mai. de 2020 às 19:18, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by Pr3d4dor** [comment]
Só abrir o CMD que é o terminal do windows

**Comment by tecmatheusr** [comment]
A sim, vou tentar.

Em ter., 5 de mai. de 2020 às 19:29, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by tecmatheusr** [comment]
Desisto, é erro atras de erro.

Em ter., 5 de mai. de 2020 às 19:29, Gianluca Bine <notifications@github.com>
escreveu:

**Comment by giampaulo** [comment]
Entrei em contato e ofereci o serviço. Ele ficou de ver se consegue sozinho senão ele iria entrar em contato comigo. Acho que pode ser fechada
