### ISSUE TITLE
Erro ao Visualizar O.S 

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#719]
Boa tarde, estou desde ontem a tarde testando a nova versão do Mapos e o mesmo não carrega a visualização  de O.S. 
Realizei algumas modificações nas não encontrei o erro, neste momento subi o arquivo original visualizarOs.php para que vocês possam me ajudar a encontrar o problema (subi um arquivos mais antigo da versão 4.2 e deu o mesmo problema.)
Atualmente uso em uma hospedagem compartilhada, e faco envio via FTP e uso o PHP 7.4

Segue abaixo alguns detalhes do erro apresentado pelo navegador.

Error thrown with message "Call to a member function row() on bool"

Stacktrace:
#3 Error in /home/u274860390/public_html/server/mapos/application/models/Pagamentos_model.php:50
#2 Pagamentos_model:getPagamentos in /home/u274860390/public_html/server/mapos/application/controllers/Os.php:296
#1 Os:visualizar in /home/u274860390/public_html/server/mapos/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:532
#0 require_once in /home/u274860390/public_html/server/mapos/index.php:306

**Comment by Triaca** [comment]
já atualizou o banco de dados?

**Comment by Pr3d4dor** [comment]
Acho que está faltando a tabela pagamentos:
```
-- -----------------------------------------------------
-- Table `pagamento`
-- -----------------------------------------------------
CREATE TABLE `pagamento` (
  `idPag` INT NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) COLLATE utf8_bin NOT NULL,
  `client_id` varchar(200) COLLATE utf8_bin NOT NULL,
  `client_secret` varchar(200) COLLATE utf8_bin NOT NULL,
  `public_key` varchar(200) COLLATE utf8_bin NOT NULL,
  `access_token` varchar(200) COLLATE utf8_bin NOT NULL,
  `default_pag` int(1) NOT NULL,
   PRIMARY KEY (`idPag`)
) ENGINE=InnoDB;
```

**Comment by fwsund** [comment]
> já atualizou o banco de dados?

sim, tudo certo por la

**Comment by fwsund** [comment]
> Acho que está faltando a tabela pagamentos:
> 
> ```
> -- -----------------------------------------------------
> -- Table `pagamento`
> -- -----------------------------------------------------
> CREATE TABLE `pagamento` (
>   `idPag` INT NOT NULL AUTO_INCREMENT,
>   `nome` varchar(50) COLLATE utf8_bin NOT NULL,
>   `client_id` varchar(200) COLLATE utf8_bin NOT NULL,
>   `client_secret` varchar(200) COLLATE utf8_bin NOT NULL,
>   `public_key` varchar(200) COLLATE utf8_bin NOT NULL,
>   `access_token` varchar(200) COLLATE utf8_bin NOT NULL,
>   `default_pag` int(1) NOT NULL,
>    PRIMARY KEY (`idPag`)
> ) ENGINE=InnoDB;
> ```

pensei nisso, ja conferi, vou apagar a tabela tabela atual e vou inserir novamente por esse script

**Comment by vagnerlaiber** [comment]
Também estou com o msm problema, tanto para visualizar a OS quanto a parte dos relatórios.
![image](https://user-images.githubusercontent.com/58378184/81126623-3e8f8d80-8f12-11ea-8cff-a6bea59297b7.png)

**Comment by vagnerlaiber** [comment]
> Acho que está faltando uma tabela de pagamentos:
> 
> ```
> -- -----------------------------------------------------
> -- Table `pagamento`
> -- -----------------------------------------------------
> CREATE TABLE `pagamento` (
>   `idPag` INT NOT NULL AUTO_INCREMENT,
>   `nome` varchar(50) COLLATE utf8_bin NOT NULL,
>   `client_id` varchar(200) COLLATE utf8_bin NOT NULL,
>   `client_secret` varchar(200) COLLATE utf8_bin NOT NULL,
>   `public_key` varchar(200) COLLATE utf8_bin NOT NULL,
>   `access_token` varchar(200) COLLATE utf8_bin NOT NULL,
>   `default_pag` int(1) NOT NULL,
>    PRIMARY KEY (`idPag`)
> ) ENGINE=InnoDB;
> ```

Bom Dia, Criei a tabela funcionou nas OS mas os relatórios ainda não funcionarão

**Comment by fwsund** [comment]
Bem a visualização  da OS esta ok novamente, foi necessário remover e adicionar novamente a tabela "pagamentos" (CUIDADO FAÇA O BKP DO BANCO DE DADOS ANTES)se tiver dados lançados la ira perder

**Comment by fwsund** [comment]
Realmente nenhum relatório e possivel verificar 

segue os dados relatados 


Mpdf\MpdfImageException thrown with message "Error parsing image file - image type not recognised, and not supported by GD imagecreate (https://meu_domínio/home/u274860390/public_html/server/mapos/assets/uploads/ed86328d7469e7a0c53ca23b94e978d2.png)"

Stacktrace:
#8 Mpdf\MpdfImageException in /home/u274860390/public_html/server/mapos/application/vendor/mpdf/mpdf/src/Image/ImageProcessor.php:1409
#7 Mpdf\Image\ImageProcessor:imageError in /home/u274860390/public_html/server/mapos/application/vendor/mpdf/mpdf/src/Image/ImageProcessor.php:1045
#6 Mpdf\Image\ImageProcessor:getImage in /home/u274860390/public_html/server/mapos/application/vendor/mpdf/mpdf/src/Tag/Img.php:276
#5 Mpdf\Tag\Img:open in /home/u274860390/public_html/server/mapos/application/vendor/mpdf/mpdf/src/Tag.php:243
#4 Mpdf\Tag:OpenTag in /home/u274860390/public_html/server/mapos/application/vendor/mpdf/mpdf/src/Mpdf.php:13628
#3 Mpdf\Mpdf:WriteHTML in /home/u274860390/public_html/server/mapos/application/helpers/mpdf_helper.php:16
#2 pdf_create in /home/u274860390/public_html/server/mapos/application/controllers/Relatorios.php:71
#1 Relatorios:clientesCustom in /home/u274860390/public_html/server/mapos/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:532
#0 require_once in /home/u274860390/public_html/server/mapos/index.php:306

**Comment by Pr3d4dor** [comment]
@fwsund Atualize o logo lá em configurações >> emitente

**Comment by fwsund** [comment]
Perfeito! agora sim..rsrs obrigado mais uma vez!!! 

agora só falta... brincadeira... bem uma pesquisa de clientes cadastrados ficaria show!! Parabéns pela iniciativa e desenvolvimento

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda pode reabrir.

**Comment by Wallidantas** [comment]
Gente to com um problema que começou do nada, não consigo abrir as OS o resto funciona de boa.
da o seguinte erro:
![Captura de tela 2022-02-11 233557](https://user-images.githubusercontent.com/48001221/153693391-7f089987-26c5-43dd-a060-4a2531316f57.png)

alguém poderia me orientar?

**Comment by Pr3d4dor** [comment]
@Wallidantas verifique se seu banco de dados está atualizado.

**Comment by GGINFORSP** [comment]
meu comecçou um erro hoje apos a atualização
![mapós erro](https://user-images.githubusercontent.com/81050855/163654503-dd133ff4-87c2-4cbd-8b30-7b8d4e216c13.png)

**Comment by Pr3d4dor** [comment]
@GGINFORSP Você atualizou por dentro do sistema? Se sim recomendo atualizar manualmente porque o atualizador por dentro do sistema, tem alguns bugs.

**Comment by GGINFORSP** [comment]
sim pelo sistema agora daerros nao adiciono novos clientes

Em dom., 17 de abr. de 2022 às 19:39, Gianluca Bine <
***@***.***> escreveu:

**Comment by Pr3d4dor** [comment]
@GGINFORSP Refaça a atualização de forma manual e creio que voltará a funcionar normalmente.
