### ISSUE TITLE
erro alterar tema

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#720]
fala galera, ocorreu comigo hj, subi os arquivos pra hospedagem e o sistema abre tudo certo, fiz o esquema no banco pra nao perder os dados da versao antiga e etc.. tudo como esperado, mas o tema Neve nao aplica, vou nas configuraçoes do sistema e seleciono o tema neve, vou em salvar, ate da a mensagem de salvo com sucesso, mas nao aplica na tela. o que poderia ser?

**Comment by Pr3d4dor** [comment]
Veja se a tabela configurações está OK

**Comment by giampaulo** [comment]
> Veja se a tabela configurações está OK

solved!
