### ISSUE TITLE
venda com troca.

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#721]
fala pessoal, 
seria legal se tivesse a opção de venda com troca, por exemplo:
Vendendo um produto x cadastrado no estoque, no lançamento da venda ou na parte de faturamento poderia ter um campo pra incluir uma troca naquela transação,
tambem seria bom legal se tivesse mais de uma forma de pagamento na mesma venda, tipo uma parte em dinheiro e outra em cartao.

**Comment by Pr3d4dor** [comment]
A questão de venda com troca eu não acho tão interessante pois nem todos iriam utizar isso. A forma de pagamento múltipla é útil sim e já pediram isso em outras issues.

**Comment by giampaulo** [comment]
E se tiver um campo de observações na venda.  De simples texto pra poder fazer esse tipo de anotação seria possível ? Até para registrar outras informações referentes a negociação.

**Comment by Pr3d4dor** [comment]
Você está falando da venda ou da OS mesmo, pois na OS já existem as anotações.

**Comment by giampaulo** [comment]
Na venda.

**Comment by Pr3d4dor** [comment]
Ok, então talvez adicionar anotações na venda igual à OS seja suficiente.

**Comment by giampaulo** [comment]
É que eu posso ter uma venda sem necessariamente ter uma OS aberta. Aí seria interessante ter um campo de observações. Pra anotar informações sobre a venda, sobre a negociação ou até sobre o que foi vendido

**Comment by giampaulo** [comment]
> Ok, então talvez adicionar anotações na venda igual à OS seja suficiente.

Sim certamente
