### ISSUE TITLE
ERRO AO GERAR OS RELATÓRIOS 

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#722]
Quando vou gerar qualquer relatório esta direcionando pagina de erro

**Reproduzir**
Quando vou no menu relatório, Seleciono um relatório (exemplo produtos), clico em todos os produtos, logo apos já vai para pagina de erro.
Uso Hospedagem da EuroHost, com php 7.2 e estou executando do W10 com navegador Chrome mas tb fiz o teste no android deu mesma coisa. 
![image](https://user-images.githubusercontent.com/58378184/81166802-82ae7c80-8f6a-11ea-9c0b-d06383fa595b.png)
![image](https://user-images.githubusercontent.com/58378184/81166875-a245a500-8f6a-11ea-87c9-2100b85c2a4e.png)

**Comment by Pr3d4dor** [comment]
Atualize o logo lá em configurações >> emitente

**Comment by vagnerlaiber** [comment]
> Atualize o logo lá nas configurações >> emitente

Deu Certo obrigado, como eu fiz em cima do banco existente nem troquei
