### ISSUE TITLE
Falha Anexo (mkdir)4.7.2

### ISSUE THREAD

**Issue by FlexoSol** [RamonSilva20/mapos#723]
Olá Pessoal!
Assim que puderem gostaria que analisassem o problema que estou tendo ao tentar anexar imagens ou documentos nas Ordens de Serviços.

Erro = Atenção! mkdir(): Permissão negada

*Linux desktop-fx 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 
*Apache/2.4.41 (Unix) OpenSSL/1.1.1e PHP/7.4.4 mod_perl/2.0.8-dev Perl/v5.16.3 
*PHP 7.4.4
Obs.:Na versão 4.5.3 não ocorre este erro.Verifiquei as permissões e elas estão habilitadas.
Grato.

**Comment by Pr3d4dor** [comment]
Tem certeza que a permissão nas pastas (diretórios) no servidor está correta?

**Comment by FlexoSol** [comment]
Bom dia!!
Para o diretório "htdocs" permissões de leitura e escrita "777" e usuário www-data.
Há outro que deveria editar??
Nas configurações do MapOS o usuário é administrador e todas as alternativas estão marcadas.
Bem como apontei anteriormente, a versão anterior roda normal utilizando o mesmo Banco de dados.

**Comment by FlexoSol** [comment]
@Pr3d4dor, Através do seu comentários revisei todas as permissões internas do /assets e descobri alguns diretórios apresentavam permissão de leitura e escrita alterados. Possívelmente foram criados com as versões anteriores a atualização. 
Alterei manualmente e funcionou.
Obrigado. 
Obs.: Vosso trabalho no MapOs está cada dia Melhor.
