### ISSUE TITLE
Erro ao Adicionar Arquivo

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#724]
Estou tendo um problema no meu MapOS que esta me incomodando bastante
Estou utilizando o MapOS 4.4.1
Tem certos arquivos que ele adiciona normalmente um arquivo .bin por exemplo
E tem vez que da uns erros estranhos ao tentar Adicionar arquivo de mesmo formato
Esse arquivo por exemplo que eu tento adicionar
![Screenshot_0](https://user-images.githubusercontent.com/1253576/81360179-8c8ec780-90b1-11ea-9620-6937159b0f7a.png)
Me retorna esse erro
![Screenshot_1](https://user-images.githubusercontent.com/1253576/81360215-a4fee200-90b1-11ea-8146-c1c0daa9abb7.png)

E esse outro arquivo que tento Adicionar
![Screenshot_2](https://user-images.githubusercontent.com/1253576/81360240-b3e59480-90b1-11ea-9c57-d9579dd0d160.png)
Recebo esse erro
![Screenshot_3](https://user-images.githubusercontent.com/1253576/81360261-bcd66600-90b1-11ea-91fc-2c57a4a95464.png)

Não sei oque esta acontecendo
No arquivo de config esta tudo correto
![Screenshot_4](https://user-images.githubusercontent.com/1253576/81360282-d24b9000-90b1-11ea-9200-84480e3bf729.png)
Ja coloquei true e false nas opções "remove_space" e "encrypt_name"
e não adianta

e tem tmb algumas imagens que quando vou add pelo celular, tanto direto da camera como da galeria eu não consigo add a imagem

**Comment by FlexoSol** [comment]
Olá, já aconteceu comigo também algo parecido.
Solucionei alterando a linha 226 do controllers/Arquivos.php.

"$config['allowed_types'] = 'txt|jpg|jpeg|gif|png|pdf|PDF|JPG|JPEG|GIF|PNG';" 

Adicionei a extensão que eu necessitava carregar.

**Comment by hoshikawakun** [comment]
> 
> 
> Olá, já aconteceu comigo também algo parecido.
> Solucionei alterando a linha 226 do controllers/Arquivos.php.
> 
> "$config['allowed_types'] = 'txt|jpg|jpeg|gif|png|pdf|PDF|JPG|JPEG|GIF|PNG';"
> 
> Adicionei a extensão que eu necessitava carregar.

Eu ali coloquei o * que ai fica permitido qualker formato de arquivo, pelo que eu percebi o problema e creio e o tamanho dos arquivos, não estou sabendo aonde altero o limite permitido, que pelo que percebi esta limitado a apenas 2MB

**Comment by FlexoSol** [comment]
Verifique /controllers/Mapos.php
a partir de "public function do_upload()"

**Comment by hoshikawakun** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/1253576/81436191-6f083f00-913f-11ea-805a-363af82fd46a.png)

**Comment by Pr3d4dor** [comment]
Ainda está com o erro ou conseguiu arrumar?

**Comment by hoshikawakun** [comment]
> 
> 
> Ainda está com o erro ou conseguiu arrumar?

Ainda estou com o problema
ao que pude notar so consigo fazer o upload de arquivos e Imagens de no maximo 2Mb (2048k)
Procurei em tudo quanto a arquivo sobre o tamanho maximo do arquivo a fazer o upload mas não encontrei nada que surtisse efeito, o interessante seria se vc quisesse subir pra dentro do sistema digamos um arquivo de 2GB vc conseguir
E se o arquivo que tentar subir tiver mais que 2Mb ele da erros variados sendo "The nome field is required." e "Erro ao fazer upload do arquivo, verifique se a extensão do arquivo é permitida. "

**Comment by hoshikawakun** [comment]
se quiser conferir como esta os arquivos [Aqui estão eles](https://github.com/hoshikawakun/MasterOS)

**Comment by hoshikawakun** [comment]
Fazendo parte do mesmo problema referente a arquivos com mais de 2MB
Na area de Anexar uma foto a OS
Pelo Cell seja uma imagem direto da camera ou da galeria tenho esse erro
![80045352-7ee81800-84dd-11ea-8dc0-8a666030f7bd](https://user-images.githubusercontent.com/1253576/81461703-fe374600-9183-11ea-8749-c65e186a77ff.png)

e se tento anexar pelo PC Obtenho esse erro
![Screenshot_8](https://user-images.githubusercontent.com/1253576/81461718-16a76080-9184-11ea-8016-5f83e926cef2.png)

**Comment by Pr3d4dor** [comment]
Isso parece ser o limite configurado no Apache, pois existem configurações de tamanho máximo no servidor http Apache também além das configurações do PHP.

**Comment by hoshikawakun** [comment]
> 
> 
> Isso parece ser o limite configurado no Apache, pois existem configurações de tamanho máximo no servidor http Apache também além das configurações do PHP.

Saberia me informar onde que vou no Apache para alterar esses valores?

**Comment by Pr3d4dor** [comment]
https://devanswers.co/php-apache-set-max-file-upload-post-size/

**Comment by hoshikawakun** [comment]
Fiz as alterações no arquivo PHP.ini e alterei o limite de arquivo para 1024M
Estou conseguindo subir arquivos com um tamanho de ate 8Mb
Arquivos maiores ainda tenho erro
Fui subir um arquivo de cerca de 11Mb e obtive esse erro no arquivo de LOG do PHP
"[09-May-2020 03:14:50 UTC] PHP Warning:  POST Content-Length of 11559731 bytes exceeds the limit of 8388608 bytes in Unknown on line 0"

**Comment by hoshikawakun** [comment]
Consegui resolver o problema
Fiz as Seguintes Alterações no arquivo PHP.ini
upload_max_filesize = 1024M
max_file_uploads = 100
post_max_size = 1024M

Olhe o tamanho do arquivo que consegui subir sem nenhum problema
![Screenshot_12](https://user-images.githubusercontent.com/1253576/81462798-6fc6c280-918b-11ea-88c7-34a29035f58b.png)
