### ISSUE TITLE
Problema com o Update

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#725]
Estou tendo um pequeno problema com o Update.
Ao clicar no botão de atualizar, ele baixa normalmente o arquivo e o extrai em uma pasta, mas não consegue subistituir os arquivos antigos.
Ai dentro da pasta do servidor fica dessa maneira.
![Screenshot_5](https://user-images.githubusercontent.com/1253576/81427354-1631aa00-9131-11ea-866d-4afb1c97e252.png)

E tenho essa msg no arquivo de erro do Apache
![Screenshot_6](https://user-images.githubusercontent.com/1253576/81427572-5abd4580-9131-11ea-87fd-ede80105346e.png)

**Comment by Pr3d4dor** [comment]
O problema é que no windows não existe o comando `rm` para limpar os arquivos após a extração, vou ver o que consigo fazer para melhorar isso.

**Comment by Pr3d4dor** [comment]
Corrigido em #729

**Comment by hoshikawakun** [comment]
Agora ele esta quase funcionando como deveria
ele ja consegue baixar o arquivo
extrair, e apagar tanto o arquivo .zip quanto a pasta que foi extraida,
mas mesmo assim ele ainda não consegue fazer a subistituição dos aruivos do sistema pelos novos que foram baixados

**Comment by Pr3d4dor** [comment]
Creio que esse problema é específico do windows pois o método `extractTo` que está sendo utilizado sobrescreve os arquivos por padrão:

https://www.php.net/manual/en/ziparchive.extractto.php

**Comment by hoshikawakun** [comment]
Creio que o problema possa estar no arquivo baixado pois o ZIP que o sistema baixa ao abrir ele dentro tem uma pasta e dentro dessa pasta os arquivos, se o arquivo ZIP ja viesse com os arquivos diretamente dentro dele ao invez de estarem dentro de uma pasta resolveria o problema, agora so me resta saber como fazer isso

**Comment by Pr3d4dor** [comment]
Não tem como pois é do proprio GitHub isso.

**Comment by hoshikawakun** [comment]
fiz aki com que ele baixe e extraia e exclia apenas o zip, ai so abrir a pasta recortar o conteudo e depois subistituir manualmente, foi a solução que encontrei
