### ISSUE TITLE
Foto em Cadastro de Cliente/Usuário

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#726]
Algo que seria bem interessante no cadastro de Cliente e de Usuário tem uma opção para colocar uma foto

Essa imagem estaria visível ao clicar em "Visualizar mais Detalhes" do referido Cliente
e nas paginas onde fica listado os Clientes e  Usuários

**Comment by Pr3d4dor** [comment]
Na minha opinião só seria útil essa funcionalidade nos clientes. Porém como disse na outra issue, estamos dando prioridade à correção de bugs ao invés de novas features. Sinta-se livre para tentar implementar e mandar uma PR com essas adições.

**Comment by hoshikawakun** [comment]
Vou tentar fazer isso sim
Abrirei outra assim que tiver o recurso funcionando

**Comment by Pr3d4dor** [comment]
Pode deixar aberta para ficar na lista de features.

**Comment by hoshikawakun** [comment]
Já consegui evoluir bem aki, já coloquei uma nova coluna da DB, para as fotos, já organizei a página da listagem de clientes para aparecer as miniaturas. E já fiz o campo na área de editar cliente, já consigo escrever algo e essa vai pra a DB, falta só a questão de selecionar a foto e fazer o upload da mesma e sair na tabela da DB e aparecer a miniatura, concluindo volto para compartilhar
