### ISSUE TITLE
Mais Opções de tipo de Status da OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#727]
No meu MapOS as opções de tipos de OS conta com cerca de umas 15 opçoes diferentes
Queria saber como faço para ajudar no projeto e acrescentar essas opçoes
Veja algumas das Opçoes que coloquei amais e cores
![Screenshot_10](https://user-images.githubusercontent.com/1253576/81461854-e01e1580-9184-11ea-9fe8-1dc850c836ed.png)

**Comment by Pr3d4dor** [comment]
É interessante porém essa questão é muito relativa, cada pessoa tem os seus gostos e suas necessidades, então fica difícil generalizar.

O que poderia ser feito é permitir cadastrar os tipos de status das OS.

Porém isso vai exigir uma refatoração não tão pequena do código e não sei se iremos fazer isso pois estamos refazendo o Mapos em Laravel e estamos se dedicando mais na correção de bugs do que na adição de novas features.

**Comment by hoshikawakun** [comment]
Ok

**Comment by Pr3d4dor** [comment]
Pode deixar a issue aberta para ficar na lista de pedidos de feature.

**Comment by hoshikawakun** [comment]
> 
> 
> Pode deixar a issue aberta para ficar na lista de pedidos de feature.

BLZ, Desculpa por ter fexado

**Comment by fabianofvd** [comment]
eu editei o meu no código fonte, mas o que poderia fazer era direcionar o tipo de os a uma tabela, ai fixar as que não pode excluir e poder cadastrar as demais, a parte ruim que quando o pessoal fazer atualização, vc pode perder essas mudanças ou dar conflitos, ou seja vc não poderá atualizar

**Comment by acinformatica2004** [comment]
Boa noite! Poderia disponibilizar o código com essa modificação? Gostei dessa alteração.
Abraços.

**Comment by hoshikawakun** [comment]
> 
> 
> Boa noite! Poderia disponibilizar o código com essa modificação? Gostei dessa alteração.
> Abraços.

vou verificar todos os arquivos que tem as alteraçoes e coloco os links

**Comment by MarceloGrass** [comment]
Me sumo ao pedido. (Boa noite! Poderia disponibilizar o código com essa modificação? Gostei dessa alteração).
Abraços.
