### ISSUE TITLE
Miniaturas (Icones) na listagem de Arquivos

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#728]
Creio que seria bem interessante se no sistema na parte de arquivos quando se coloca um arquivo que não e uma Foto ele aparece a miniatura de uma pastinha rasgada, veja na imagem
![Screenshot_12](https://user-images.githubusercontent.com/1253576/81462862-d1872c80-918b-11ea-9335-ef1cbb5ea3ad.png)

Seria muito trabalhoso ao invez de ficar desse jeito ele apresentar um icone do formato do arquivo que foi colocado?
Ex: se colocar um arquivo PSD ele ao invez de apresentar esse icone
![Screenshot_14](https://user-images.githubusercontent.com/1253576/81462959-6e49ca00-918c-11ea-96c5-a8ad85715c1a.png)

Apresentar esse icone
![Screenshot_13](https://user-images.githubusercontent.com/1253576/81462966-77d33200-918c-11ea-81b5-a7f46368b6c9.png)

ou se for muito complicado colocar uma miniatura para cada tipo de formato de arquivo, usar uma miniatura padrão estilo essa 
![Screenshot_15](https://user-images.githubusercontent.com/1253576/81462998-a94bfd80-918c-11ea-9c87-6bbfc77692cb.png)

**Comment by Pr3d4dor** [comment]
Sinta-se a vontade para enviar um PR com essa melhoria.

**Comment by hoshikawakun** [comment]
Não tenho nem ideia por onde começar
poderia me informar quais arquivos devo trabalhar aki que vejo oque consigo fazer
Colocar pelomenos no sistema uma miniatura paradrão caso o arquivo add no sistema não seja uma imagem

**Comment by Pr3d4dor** [comment]
Você precisa mexer no arquivo `application/views/arquivos/arquivos.php`

**Comment by giampaulo** [comment]
eu tenho no meu aqui feito assim 
![image](https://user-images.githubusercontent.com/48699495/81972638-44aff900-95f9-11ea-9409-851944b7d591.png)

ate posso disponibilizar ai, mas seria interessante vc testar bem primeiro pra ver se atende as suas necessidades, pra mim atende bem aqui acho mais pratico usar esse esquema aqui. 
tenho certeza que com um pouco de tempo pode ser melhorado e ficar mais interessante para o projeto conforme seus idealizadores.

**Comment by giampaulo** [comment]
pra complementar, como é somente eu que uso nao tem definiçao de permissoes e etc.. mas sei que tem como fazer. tem como integrar com diversos programas ae

**Comment by giampaulo** [comment]
![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante

**Comment by hoshikawakun** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
> ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante
deixe-me intender, ao colocar os arquivos como exemplo um PDF, a miniatura sera de um arquio PDF, e se colocar um JPG vai aparecer a miniatura da foto, muito util isso, se puder compartilhar ajudaria muito

**Comment by giampaulo** [comment]
> ![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
> ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante
> deixe-me intender, ao colocar os arquivos como exemplo um PDF, a miniatura sera de um arquio PDF, e se colocar um JPG vai aparecer a miniatura da foto, muito util isso, se puder compartilhar ajudaria muito

Sim. E pode criar pastas e separar por pastas tb. Só precisamos ver como posso disponibilizar ae essa parada. @Pr3d4dor acha melhor eu passar apenas pro colega aí ou como fica melhor ?

**Comment by Pr3d4dor** [comment]
@giampaulo Você pode criar uma pull request com essa funcionalidade para o mapos, aí o que precisar ser alterado eu aponto na própria pull request.

**Comment by giampaulo** [comment]
@Pr3d4dor  @hoshikawakun  fiz assim, upei a pasta arquivos pro repo aqui do git, https://github.com/giampaulo/maposfilemanager
é so substituir a pasta arquivos por esta, testei com o chrome nao sei bem da funcionalidade com outros navegadores to meio sem tempo pra isso no momento. tentei criar uma PR mas nao sei pq nao to conseguindo fork no teu diretorio.

**Comment by giampaulo** [comment]
Ahhhh lembrei agora. Não estou usando a mesma pasta que era salvo os arquivos antes. Portanto o ideal é que faça backup dos arquivos e depois de substituir a pasta adicione novamente os arquivos

**Comment by giampaulo** [comment]
criei a PR

**Comment by hoshikawakun** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
> > ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante
> > deixe-me intender, ao colocar os arquivos como exemplo um PDF, a miniatura sera de um arquio PDF, e se colocar um JPG vai aparecer a miniatura da foto, muito util isso, se puder compartilhar ajudaria muito
> 
> Sim. E pode criar pastas e separar por pastas tb. Só precisamos ver como posso disponibilizar ae essa parada. @Pr3d4dor acha melhor eu passar apenas pro colega aí ou como fica melhor ?

Fiz assim como informou mas olha a tela que obtive
![Screenshot_28](https://user-images.githubusercontent.com/1253576/82168039-06823600-9894-11ea-8862-5cd92f36e6c2.png)

**Comment by giampaulo** [comment]
> > > ![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
> > > ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante
> > > deixe-me intender, ao colocar os arquivos como exemplo um PDF, a miniatura sera de um arquio PDF, e se colocar um JPG vai aparecer a miniatura da foto, muito util isso, se puder compartilhar ajudaria muito
> > 
> > 
> > Sim. E pode criar pastas e separar por pastas tb. Só precisamos ver como posso disponibilizar ae essa parada. @Pr3d4dor acha melhor eu passar apenas pro colega aí ou como fica melhor ?
> 
> Fiz assim como informou mas olha a tela que obtive
> ![Screenshot_28](https://user-images.githubusercontent.com/1253576/82168039-06823600-9894-11ea-8862-5cd92f36e6c2.png)

opa... seguinte.. eu upei a pasta Arquivos somente nesse link.
https://github.com/giampaulo/pastaarquivos
é a Pasta toda. 
renomeie ai a pasta arquivos para outro nome como por exemplo arquivos_old, e cole esta pasta arquivos. 
tem que ser no mesmo lugar. confira tbm se as permissoes dessa pasta estao liberadas

fico no aguardo .

**Comment by hoshikawakun** [comment]
> 
> 
> > > > ![image](https://user-images.githubusercontent.com/48699495/81973856-23500c80-95fb-11ea-85f3-46056432d4d8.png)
> > > > ficaria assim com os icones de cada tipo de arquivo. a organizaçao desse negocio é bem interessante
> > > > deixe-me intender, ao colocar os arquivos como exemplo um PDF, a miniatura sera de um arquio PDF, e se colocar um JPG vai aparecer a miniatura da foto, muito util isso, se puder compartilhar ajudaria muito
> > > 
> > > 
> > > Sim. E pode criar pastas e separar por pastas tb. Só precisamos ver como posso disponibilizar ae essa parada. @Pr3d4dor acha melhor eu passar apenas pro colega aí ou como fica melhor ?
> > 
> > 
> > Fiz assim como informou mas olha a tela que obtive
> > ![Screenshot_28](https://user-images.githubusercontent.com/1253576/82168039-06823600-9894-11ea-8862-5cd92f36e6c2.png)
> 
> opa... seguinte.. eu upei a pasta Arquivos somente nesse link.
> https://github.com/giampaulo/pastaarquivos
> é a Pasta toda.
> renomeie ai a pasta arquivos para outro nome como por exemplo arquivos_old, e cole esta pasta arquivos.
> tem que ser no mesmo lugar. confira tbm se as permissoes dessa pasta estao liberadas
> 
> fico no aguardo .
depois que add uma foto o problema foi resolvido,
e teria como utilizar os 2 sistemas de arquivos ao mesmo tempo?
tanto esse seu como o antigo?

**Comment by giampaulo** [comment]
Possível é.  Mas sei lá. Não faz muito sentido. Mas se quiser os dois pode fazer sim

**Comment by hoshikawakun** [comment]
> 
> 
> Possível é. Mas sei lá. Não faz muito sentido. Mas se quiser os dois pode fazer sim

Consegui colocar os 2 sistemas de gerenciamento de arquivos, com uma entrada na pag de config do sistema para escolher entre qual usar, se quiser listo oque foi que eu alterei para deixar os 2 completamente funcionais
