### ISSUE TITLE
Bug ao visualizar OS

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#730]
Gostaria de entender se esta correto, ao vizualizar uma OS aparece data de Emissao mais nao quando foi emitida a OS e sim o dia que esta sendo consultada. Esta correto isso?
Muito obrigado pela atencao de sempre.

**Comment by Pr3d4dor** [comment]
Sim, está correto, a data de emissão é data que você está visualizando ou imprimindo.
