### ISSUE TITLE
Erro ao cadastrar Clientes 

### ISSUE THREAD

**Issue by bulfaitelo** [RamonSilva20/mapos#731]
Após atualização está ocorrendo um erro ao cadastrar novos clientes. 

Para gerar o erro basta cadastrar um novo cliente que aparece o notificação de erro. "Ocorreu um erro"

Esse erro ocorre tanto em inclusão quanto edição de clientes. 

![image](https://user-images.githubusercontent.com/4989569/81485415-3d68a400-9223-11ea-851c-91672dedf8b9.png)

Erros testados no Firefox atualizado para a ultima versão, foi realizado atualização dos componentes com o composer. 

**OBS.:**
Eu removeria o validador de CPF tem casos que o cliente não passa e gera um trabalho maior para achar um cpf para fazer apenas um orçamento.

**Comment by Pr3d4dor** [comment]
Não é um bug, provavelmente sua tabela clientes está desatualizada sem os campos `contato` e `complemento`

**Comment by bulfaitelo** [comment]
> 
> 
> Não é um bug, provavelmente sua tabela clientes está desatualizada sem os campos `contato` e `complemento`

Sim realmente está sem porem não vi nenhum update de sql lá no diretório de updates o mudou a forma como é atualizado as tabelas ?

**Comment by bulfaitelo** [comment]
> 
> 
> Não é um bug, provavelmente sua tabela clientes está desatualizada sem os campos `contato` e `complemento`

Fiz a correção, vi que tinha um migration aqui,  uma questão na documentação diz que tem como fazer update pelo próprio mapos, em configuração >> sistema, isso foi descontinuado ?

obs: deletei o comentário anterior,

**Comment by Pr3d4dor** [comment]
A migration pelo sistema também funciona.

**Comment by bulfaitelo** [comment]
> 
> 
> A migration pelo sistema também funciona.

Como eu faria? aqui não aparece essa opção no menu 
![image](https://user-images.githubusercontent.com/4989569/81487612-2df25680-9235-11ea-8e8c-9efa1c99b40a.png)

**Comment by Pr3d4dor** [comment]
Em Configurações >> Sistema, verifique se o seu usuário está com as permissões de "sistema"

**Comment by bulfaitelo** [comment]
Aqui só tem permissão de Adm, de id 1
![image](https://user-images.githubusercontent.com/4989569/81487664-bf61c880-9235-11ea-8bf6-cc3b7bc42f87.png)

**Comment by bulfaitelo** [comment]
Achei Aqui nos seeds, e subistitui no meu perfil adm,  vlw conseguir aqui

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.
