### ISSUE TITLE
Adicionar imprimir recibo na tela da OS

### ISSUE THREAD

**Issue by heraf250** [RamonSilva20/mapos#732]
Boa noite comunidade, estou gostando muito desse sistema e tenho feito algumas modificações pessoais pra mim nele, alterei o botao que imprimi para impressora fiscal e coloquei ele pra imprimir orçamento( fiz uma alteração no modelo de impressao), agora perciso tbm inserir um botao que imprimi recibo, criei os botoes o modelo de impressao porém nao estou conseguindo fazer que o botao imprima, fica dando erro 404

**Comment by Pr3d4dor** [comment]
Você precisa criar um método novo no controller que retorne a sua nova view.

**Comment by heraf250** [comment]
> Você precisa criar um método novo no controller que retorne a sua nova view.

ah sim vi aqui, deu certo muito obrigado

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda pode reabrir.
