### ISSUE TITLE
Atualizacao 4.7.5 erro ao adicionar produro e servico na OS

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#735]
Apos essa ultima atualizacao nao consigo adicionar nem produto nem servico na OS.

**Comment by Pr3d4dor** [comment]
Eu testei e está funcionando normalmente, verifique se você atualizou realmente todos os arquivos.

**Comment by cabralwms** [comment]
Eu fiz a atualização pelo botão atualizar. E Entao apartir dai parou de adicionar produtos e servicos na OS. No log do apache error.log nao apareceu erro por isso nao consegui pegar o codigo do erro. Tem algum outro lugar . Aparece uma tela com atencao erro ocorreu um erro ao tentar adicionar o produto/servico.

**Comment by cabralwms** [comment]
Eu fiz a atualizacao atravez do modo antigo e voltou funcionar tudo. acredito ter dado algum erro na atualizacao pelo botao atualizar . eu utilizo sistema Debian 9 com sistema online IP fixo e site e dominio registrado.

**Comment by Pr3d4dor** [comment]
Eu ia perguntar isso em seguida, provavelmente teremos que melhorar o atualizador pois parece que essa lib que foi utilizada apresenta alguns problemas.

Se precisar de mais ajuda é só reabrir a issue.
