### ISSUE TITLE
Problema na hora de Visualizar OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#738]
No meu aki como vou trabalhar com assistencia e receber equip pelo correio eu add nas pag referentes a OS o campo para cod de rastreio, tmb foi feito a criação da coluna rastreio na DB "os"

nas telas de criar e editar OS ficaram dessa maneira
![Screenshot_23](https://user-images.githubusercontent.com/1253576/81752812-ab61d500-9488-11ea-9ede-f2652b53461c.png)
![Screenshot_24](https://user-images.githubusercontent.com/1253576/81752818-aef55c00-9488-11ea-9ec7-0a746b2dbcff.png)

Ate aki tudo funcionando perfeitamente, inclusive o botão rastreio que redireciona para o site do correio ja com o codigo caso esteja cadastrado

agora que vem o problema
Nas pag de Visualizar OS

o campo onde ira aparecer o codigo do rastreio eu coloquei junto aos 
"Descrição Produto/Serviço"
"Defeito"
"Observações"
"Laudo Técnico"

fiz todas as adições referentes ali para caso não tivesse o codigo de rastreio cadastrado ele não exibiria a linha referente a informação

se tem um cod ja cadastrado na OS aparece perfeito
Veja
![Screenshot_25](https://user-images.githubusercontent.com/1253576/81753437-2bd50580-948a-11ea-9d93-49fe6911f935.png)

mas se tento visualizar uma OS que não tem o codigo de rastreio aparece dessa maneira
![Screenshot_27](https://user-images.githubusercontent.com/1253576/81753805-fa106e80-948a-11ea-9ffc-3991a84793d6.png)

[Veja como esta o meu arquivo Visualizar OS](https://github.com/hoshikawakun/MasterOS/blob/master/application/views/os/visualizarOs.php)

Os campos referente ao Codigo de Rastreio estão todos como "rastreio"

**Comment by Pr3d4dor** [comment]
Como é uma customização isso não é um bug do mapos, então peço para que não coloque a label de bug.

Sobre o problema, você tem que verificar o motivo desse campo estar quebrando a página.

**Comment by hoshikawakun** [comment]
Consegui resolver o problema, era um BUG na DB, zerei a Tabela OS e recadastrei tudo novamente e resouveu
