### ISSUE TITLE
Erro ao alterar senha de Admim

### ISSUE THREAD

**Issue by Simaops** [RamonSilva20/mapos#74]
Após tentar alterar a senha de Minha conta de Administrador aparece a mensagem:

"Ocorreu um erro ao tentar alterar a senha!"

e não altera, como proceder?

**Comment by RamonSilva20** [comment]
Olá, vou dar uma verificada, enquanto isso altere a senha na tela de edição de usuário.

**Comment by Simaops** [comment]
![sem titulo](https://user-images.githubusercontent.com/33043800/32071313-aabb568c-ba6d-11e7-94ef-4f12026c69aa.png)

**Comment by Simaops** [comment]
// Tela com a mensagem de erro.

Consegui alterar a senha na tela de edição do Usuário, como sugerido.
Obrigado RamonSilva20.

**Comment by Simaops** [comment]
![sem titulo2](https://user-images.githubusercontent.com/33043800/32071766-0490bfde-ba6f-11e7-956f-120f1a1cd87f.png)

**Comment by Simaops** [comment]
// Tela pra galera que tbm precisar
