### ISSUE TITLE
Linguagen PT-PT

### ISSUE THREAD

**Issue by arslopes** [RamonSilva20/mapos#740]
Boa noite, é possível traduzir o programa para PT-PT? 
Ou caso seja possível, conseguem indicar-me como proceder à troca de linguagem? 
Tenho alguns campos R$, trocar para € 
Cep- Código Postal 
Entre outros..
Obrigado

**Comment by Pr3d4dor** [comment]
Como eu disse, o mapos é hard coded em PT-BR, se você quiser usar em PT-PR você terá que modificar e você fazer a tradução.
