### ISSUE TITLE
Respostas vazias no modulo de pesquisa.

### ISSUE THREAD

**Issue by fwsund** [RamonSilva20/mapos#742]
Boa tarde, 
Não sei se realmente e um bug, mas acho que se não for atrapalha bem o uso do modulo de pesquisa de O.S. 

No arquivo // \application\views\os o arquivo os.php na linha 19 esta desta forma originalmente:

select name="status[]" id="status" class="span12"

Acontece que o modulo não funciona adequadamente, algumas vezes não encontra a O.S mesmo selecionando o status. E quando sabemos apenas o primeiro nome fica mais difícil ainda. Então quando desobrigo o sistema a procurar a O.S sem preencher o status no meu uso diário não acontece erros mais (respostas vazias). então eu mudo a linha referida para:

select name="status" id="status" class="span12"

sem o [] no "status"

**Comment by Pr3d4dor** [comment]
Não entendi exatamente o problema que você descreveu.

Tem como explicar com mais detalhes?

**Comment by fwsund** [comment]
editei o comentário

**Comment by Pr3d4dor** [comment]
O status[] significa para o PHP que é um array de status, então a intenção é filtrar por mais de um status.

**Comment by fwsund** [comment]
mas com [] se eu não definir o status da O.S que estou procurando a resposta e vazia, já sem [] ele pesquisou todas as O.S de um cliente que tem vários status diferentes. 

Tenho clientes com varias O.S feitas, com status diferentes, ou seja sem com o [] na pesquisa tenho que colocar o come do cliente e o status que estou procurando ou a resposta da pequisa e vazia. Ja sem [] faço a mesma pesquisa e obtenho vários resultados do mesmo cliente com status diferentes.

Ao meu ver o [] esta limitando a pesquisa sem selecionar o status que procuro, ou seja, nao esta filtrando por mais de um status.

**Comment by RamonSilva20** [comment]
Eu fiz alguns testes, está funcionando normalmente, se não especifico o status e pesquiso pelo nome traz todas as OS com diferentes status, se filtro por um ou mais status, retorna o que especifiquei.
@fwsund o problema ocorre sempre ou ocasionalmente?

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.
