### ISSUE TITLE
Filtro Financeiro

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#743]
Quando entro em financeiro, vou pesquisar periodo TODOS e situação PENDENTE, não aparece nada, mas quando coloco ambos os filtros TODOS ele aparece.

![image](https://user-images.githubusercontent.com/58378184/81833329-f4139f80-9515-11ea-9b5b-296402aac981.png)

![image](https://user-images.githubusercontent.com/58378184/81833222-d5ada400-9515-11ea-8039-41305781d690.png)

**Comment by brunolafm** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/11146567/81844947-3d6beb00-9526-11ea-8c94-ff5d6a822665.png)

Adicione  `  ?: 0, ` ao final da linha 354 em ` /application/controllers/Vendas.php ` como na imagem, ao faturar novas vendas irão aparecer corretamente na listagem pendente.

**Comment by vagnerlaiber** [comment]
Pode me mandar o arquivo, estou modificando, porem depois a modificação não encontra o cliente na venda.

**Comment by cleytonasa** [comment]
Mas já está aí na foto...

**Comment by cleytonasa** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/11146567/81844947-3d6beb00-9526-11ea-8c94-ff5d6a822665.png)
> 
> Adicione ` ?: 0,` ao final da linha 354 em `/application/controllers/Vendas.php` como na imagem, ao faturar novas vendas irão aparecer corretamente na listagem pendente.

O que seria esse comando no final da linha ?!

**Comment by Pr3d4dor** [comment]
@brunolafm Eu fiz o teste aqui e na última versão não ocorre esse problema, então esse ajuste não é necessário.

@vagnerlaiber Eu fiz o teste aqui também e os filtros estão funcionando corretamente. Você está usando a última versão do mapos?

**Comment by brunolafm** [comment]
> > ![Screenshot_1](https://user-images.githubusercontent.com/11146567/81844947-3d6beb00-9526-11ea-8c94-ff5d6a822665.png)
> > Adicione ` ?: 0,` ao final da linha 354 em `/application/controllers/Vendas.php` como na imagem, ao faturar novas vendas irão aparecer corretamente na listagem pendente.
> 
> O que seria esse comando no final da linha ?!

Ele adiciona um 0 no campo recebido, quando não tem um 0, no banco é salvo como null, o que não funciona no filtro das versões antigas.
Nesses que não aparecem, se vc for no banco e colocar um 0 onde está null, na coluna baixado ele volta a aparecer quando filtrado por pendente

**Comment by brunolafm** [comment]
> @brunolafm Eu fiz o teste aqui e na última versão não ocorre esse problema, então esse ajuste não é necessário.
> 
> @vagnerlaiber Eu fiz o teste aqui também e os filtros estão funcionando corretamente. Você está usando a última versão do mapos?

Sim, nas novas versões isso foi corrigido de uma forma diferente, se não me engano, como na minha produção ainda uso uma versão bem antiga (que por acaso estou com problemas pra migrar o banco pra nova versão, no caso o problema é a preguiça msm) fiz dessa forma, copiando do faturamento de O.S. e deu bom

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.
