### ISSUE TITLE
Adicionar serviço

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#744]
Boa tarde, Estou tentando adicionar um serviço que eu tenho com empresas e não está dando certo. Eu percebi que se colocar valor da certo, mas no meu caso temos contrato então eu cadastrei visita tecnica dentro do contrato sem valores. E agora está dando erro ao adicionar.

**Comment by cleytonasa** [comment]
Qual erro dar ?

**Comment by Pr3d4dor** [comment]
Qual o erro, não entendi exatamente o problema?

**Comment by cabralwms** [comment]
Aparece aquela tela ATENÇÃO ocorreu um erro ao adicionar o serviço. Eu percebi que se eu colocar um valor o servico e adicionado. Mas eu cadastrei o servico como visita tecnica dentro do contrato, e deixei sem valor pq combinei com a empresa visitas sem adicionar valores no contrato. Entao se eu colocar por exemplo 0,01 centavo o servico e adicionado.

**Comment by FlexoSol** [comment]
Bom dia, na adição de produtos tambem.

**Comment by FlexoSol** [comment]
![Captura de tela_2020-05-14_09-13-33](https://user-images.githubusercontent.com/63417461/81933132-419a1600-95c3-11ea-999a-0107fbbdd5fb.png)

**Comment by cabralwms** [comment]
Exatamente essa tela pra mim,

**Comment by cabralwms** [comment]
Você fez a Atualização pelo botão atualizar? Eu fiz no modo antigo extraindo a pasta e configurando do zero. ai resolve isso ai dos produtos, o erro esta em algum arquivo na atualização.

**Comment by Pr3d4dor** [comment]
@cabralwms Precisa colocar 0,01 porque não faz sentido ter um produto ou serviço com valor zerado, na minha opinião. Você pode customizar isso no seu mapos se quiser.

@FlexoSol Atualize manualmente o mapos pois a lib do atualizador tem alguns problemas e provavelmente terá que ser refeita.
