### ISSUE TITLE
Status O.S e venda após pago

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#745]
Boa noite, como posso fazer para mudar o status da o.s e da venda para pago somente depois do cliente pagar no faturar?

Obrigado

* Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
Na OS o status faturado já não serve?

**Comment by acinformatica2004** [comment]
Faturado já aparece quando faturo, agora queria pago quando efetuasse o pagamento dessa fatura

**Comment by Pr3d4dor** [comment]
No Faturamento você pode adicionar um ajuste verificando o campo `recebido` e atualizar a OS ou Venda ligada com aquele lançamento.

**Comment by acinformatica2004** [comment]
Complicou, rsrs.

**Comment by cabralwms** [comment]
Eu pensei no seguinte mas não consegui resolver. Assim que eu termino a O.S. estou colocando finalizada. Pq alguns clientes olham via web meu sistema é online, Ai quando clico para faturar acho interessante o lançamento em financeiro, seria dificil ao clicar em recebido ele retornar pago no registro da O.S. e Venda. acho que seria uma solução legal pelo menos para mim não sei se para todos.

**Comment by Pr3d4dor** [comment]
Na minha opinião ao marcar o lançamento como recebido é o modo correto a se fazer e também adicionando um novo status "Pago" na OS.

**Comment by JulianoSavino** [comment]
Então, @Pr3d4dor, oponto é justamente esse, veja só:
Lembro que no ano passado vi uma issue que relatava um bug no faturamento, não recordo exatamente qual era, mas, suponho que já esteja resolvido, contando com isso irei direto ao que entendi dos relatos acima e opinarei.
Vejamos com um exemplo:
EX.: possuo 10 ordens mensais via boleto, faturo elas via banco e posteriormente no MapOS e deixo em aberto a opção pago pois não sei se o cliente vai pagar ou não.
Para saber o que ha de pendente ou em aberto, preciso emitir relatório e selecionar o período de busca ou colocar nos primórdios da humanidade kkkk. Isso toma tempo (não muito eu sei) mas é um controle que pode ser esquecido, ainda mais quando não é apenas uma pessoa responsável na empresa.  
Pensemos na praticidade, digamos que essar ordens de serviço aparececem na dashboard do mesmo jeito que os produtos com estoque baixo ou aguardando peças aparecem? seria uma mão na roda. Sei que nesses exemplos que citei aqui, ele busca pelo status, mas se fosse possível buscar por recebido ou não, independente da forma de pgto, seria pratico e também já seria um começo para quando implementarem a opção de parcelamento pois se eu receber em 4x no cartão, efetivamente não recebi o dinheiro e logica se aplicará igualmente como exemplifiquei no meu caso hipotético. 
Espero que tenha conseguido ser claro em meu raciocínio.
Parabéns a todos os colaboradores do projeto, está fantástico!!

**Comment by Pr3d4dor** [comment]
É uma boa opção, quem quiser fazer a implementação e fazer a pull request, será aceito.

Eu estou focado mais na correção de bugs do que na adição de features porque o mapos está sendo refeito em Laravel.

**Comment by maycon1977** [comment]
> É uma boa opção, quem quiser fazer a implementação e fazer a pull request, será aceito.
> 
> Eu estou focado mais na correção de bugs do que na adição de features porque o mapos está sendo refeito em Laravel.

No caso nessa versão em Laravel, vai ter que reinstalar tudo novamente ou rola update direto? A linguagem é muito diferente?

Mais uma vez, obrigado!

**Comment by Pr3d4dor** [comment]
Vai ter que instalar normalmente igual qualquer sistema. A linguagem é a mesma, que é PHP, o que muda é o framework.

Penso que na versão 1.0 vai ter que começar do zero, porém temos na ideia de fazer uma funcionalidade para migrar banco de dados desse mapos.
