### ISSUE TITLE
Componente do PDF

### ISSUE THREAD

**Issue by fabianofvd** [RamonSilva20/mapos#746]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.
ola, primeiramente parabéns pelo sistema, vai me ajudar muito em controlar minha vida.
em paralelo eu hospedei na locaweb e ao gerar um relatorio (pdf) da esse erro abaixo
http://fabiano.net.br/os/erro.jpg

até entendi que esse componente é para o ultimo php 7 porem na locaweb é mais antigo, tem ideia de como conseguiria instalar o componente antigo ?

![erro](https://user-images.githubusercontent.com/56846706/81877145-c1d86100-955a-11ea-95f3-6ff46c4722f6.jpg)

**Comment by Pr3d4dor** [comment]
Esse problema ocorre porque você está utilizando PHP numa versão anterior ao PHP 7, então você precisa atualizar para o PHP 7 ou superior

**Comment by fabianofvd** [comment]
sim, vou ver se a locaweb faz isso, mas se caso não tiver como acontecer pela locaweb , vi que o componente tem para versões mais antigas de php, mas boiei nos procedimentos de instalação. de qualquer forma show de bola o trabalho de vc's

**Comment by Pr3d4dor** [comment]
Leia essa issue para ver se ajuda com as suas dúvidas na instação: #715

**Comment by fabianofvd** [comment]
resolvido, é fácil migrar a versão do php na locaweb, 

muito obrigado !!!!

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda pode reabrir.
