### ISSUE TITLE
Modal Adicionar produtos, serviços, cliente

### ISSUE THREAD

**Issue by CaramujoRei** [RamonSilva20/mapos#748]
Gostaria de dar uma sugestão em relação a uma modal para incluir novos produtos, serviços ou clientes.
Exemplo: Ao adicionar uma nova OS, no campo cliente, ao colocar o nome de um cliente que ainda não exista no banco, ele dê a opção numa modal pra adicionar e iniciar a nova OS. Bem como no momento de adicionar produtos e serviços, caso não tenha cadastrado dê a opção de adicionar um novo. 
No meu ponto de vista é bem interessante esse tipo de recurso.

**Comment by Pr3d4dor** [comment]
Realmente é interessante, sinta-se libre para abrir uma pull request com essas melhorias se quiser.
