### ISSUE TITLE
Erro ao Adicionar Serviço/Produto

### ISSUE THREAD

**Issue by DanielAraujo98** [RamonSilva20/mapos#749]
Ao tentar adicionar um Serviço/Produto me deparo com a seguinte mensagem: 

"Ocorreu um erro ao tentar adicionar serviço."

![image](https://user-images.githubusercontent.com/53981325/82014686-7ce42580-9653-11ea-900c-45b61134e5e6.png)

**Comment by vagnerlaiber** [comment]
Bom Dia, aconteceu o mesmo comigo depois de clicar em configuração => Sistema => Atualizar mapos, ai fiz o update no ftp com os arquivos novamente ai voltou ao normal.
![image](https://user-images.githubusercontent.com/58378184/82057359-9ad47900-9699-11ea-9d3a-297ed115271c.png)

**Comment by Pr3d4dor** [comment]
Basta fazer a atualização manual como @vagnerlaiber comentou.
