### ISSUE TITLE
ajuda editar campo extra de visualização

### ISSUE THREAD

**Issue by Leadership** [RamonSilva20/mapos#75]
Pessoal preciso de ajuda a edita 👍 
Deixa visivel esses campos nos detalhes da venda
![vendas 1](https://user-images.githubusercontent.com/5593786/32136469-1b74ebc4-bbed-11e7-9c8f-288782fca4c8.jpg)
Deixa visivel nas vendas:
![vendas 1](https://user-images.githubusercontent.com/5593786/32136511-a40387de-bbed-11e7-94fd-f16f4f1d3cf5.jpg)

**Comment by fontebasso** [comment]
O campo vencimento coletamos do campo de mesmo nome ao faturar uma venda, mas o que quer que seja exibido nesse novo campo "venda"?

**Comment by Leadership** [comment]
no campo venda a data da venda no outro campo vencimento a data de vencimento no meu caso eu nao queria uma data de vencimento do pagamento mas sim de um serviço por exemplo no meu caso eu tenho uma comunidade de Counter - Strike e uso o gerenciado mapos para fazer um controle das vendas, eu vendo um determinado produto por um determinado prazo de tempo.

**Comment by fontebasso** [comment]
Então nesse caso você precisa de uma ordem de serviço, que possuí data inicial e data final. Claro que dados como defeito, laudo técnico, são campos que você não vai utilizar, mas você associa um serviço e utiliza a função de faturar para controlar suas receitas também.

Eu achei útil a idéia de ter o vencimento de uma venda e estou trabalhando em um PR com isso. Em sequência posso trabalhar na adição do campo data final de uma OS, assim suas necessidades serão atendidas :)

**Comment by Leadership** [comment]
muito obrigado
