### ISSUE TITLE
Email - Erro no Cron

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#750]
Boa Tarde, Atualmente uso hospedagem da EuroHost, criei um e-mail, fui ate a configuração de Cron coloquei o comando, porem chega um e-mail para mim dando erro **Could not exec shell '/bin/bash' with errno = 2** 
![image](https://user-images.githubusercontent.com/58378184/82066924-6f0bc000-96a6-11ea-80cb-dfe050260c24.png)

Segue as configuração no Cron
![image](https://user-images.githubusercontent.com/58378184/82066820-4a174d00-96a6-11ea-9541-1077213948ec.png)

**Comment by Pr3d4dor** [comment]
Isso não é um problema do mapos, esse erro significa que a sua hospedagem não tem a shell "/bin/bash".

**Comment by brtechst** [comment]
Para mim ocorre erro parecido e minha hospedagem é na Hostinger.

Alguém sabre como posso resolver?

 Minha configuração está assim:

![image](https://user-images.githubusercontent.com/53625745/88455146-60c9e500-ce49-11ea-8512-1d0f6007f4e7.png)

O erro é este aqui: 

![image](https://user-images.githubusercontent.com/53625745/88455165-8951df00-ce49-11ea-9495-9febc2924aca.png)

Alguém pode ajudar sendo mais específico de como resolver?

**Comment by Pr3d4dor** [comment]
O caminho até o arquivo index.php está incorreto.

**Comment by brtechst** [comment]
E como seria o caminho correto? meu index está na pasta public/acesso
