### ISSUE TITLE
Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.

### ISSUE THREAD

**Issue by fomezero** [RamonSilva20/mapos#751]
Bom dia, ja fiz todos os procedimentos que foi dito aqui no grupo. Inclusive li outras perguntas.
Porem, quando modifico a linha 59: trocando pre_installation por production ou development. Vi que diz que não é para trocar a linha 61.
Mesmo assim o problema continua, desinstalei e instalei mais de 10 vezes.
E mesmo quando termina a instalação fala para apagar a pasta install, quando faço isso ai pior mais ainda erro:(The requested URL /os/install/index.php was not found on this server.)

PHP:7.3
MySQL 5.6

Onde estou errando vlw!!

**Comment by Pr3d4dor** [comment]
Você está instalando em uma hospedagem ou localmente?

**Comment by duuhmenezes** [comment]
o meu estava dando erro ao adicionar produto na OS. 
ai fiz o update manual para hospedagem CPANEL. ai começou dar esse aviso também.. "parece que este aplicativo já está instalado.

**Comment by Pr3d4dor** [comment]
Provavelment você sobrescreveu o arquivo `index.php`, você precisa mudar a linha 59 de: `define('ENVIRONMENT', 'pre_installation');` para `define('ENVIRONMENT', 'production');`

**Comment by fomezero** [comment]
Esta instalado. O provedor do uolhost, antes estava na Locaweb, funcionava redondo agora não mais!! A linha 59 já fiz as modificações e nada..

**Comment by Pr3d4dor** [comment]
Tem certeza que salvou as alterações no servidor?

**Comment by fomezero** [comment]
Fiz isso algumas vezes inclusive, refiz todo o procedimentos utilizando 2 pastas distintas, e tomo todo o cuidado para colocar exatamente o arquivo modificado. :(

**Comment by fomezero** [comment]
Infelizmente não funciona de forma alguma, estou desistindo de utilizar.
Como expliquei anteriormente, li muito sobre o erro aqui no forum mesmo, antes de postar os meus problemas.

Não funciona modificar a linha 59 define('ENVIRONMENT', 'production'), a linha 61 tem que se feita a mesma modificação, se deixar como (if (ENVIRONMENT == 'production'). Da erro  ( Your system folder path does not appear  to be set correcly. Please  open  the  following file and  correct  this: index.php).

Não funciona seguir o que as telas do sistema informa, Parabéns!  Você instalou o  MAPOS......., 
Não esqueça de deletar seu diretório de instalação. Quando faço isso o erro que da Not Found
The requested URL /os/install/index.php was not found on this server.


Já não sei mais nem o que falar, estou a mais de 2 semanas tentando utilizar o sistema novamente e não consigo. Tenho um bom conhecimento de TI, a minha empresa da suporte. 
Sei o que é para ser modificado no sistema, mesmo assim as informações todas não estão surtindo efeito algum.

Me ajudem, estou precisando muito.

**Comment by fomezero** [comment]
esqueci de falar, quando eu coloco as modificações, o que eu percebi que sempre que faço qualquer modificação, sou redirecionado para a pasta install.
www.meudominio.com.br/pastasistema/install/index.php

**Comment by Pr3d4dor** [comment]
Pelo que eu estou vendo você não está realizando a instalação corretamente.

O erro: `Your system folder path does not appear to be set correcly. Please open the following file and correct this: index.php` acontece quando as dependências do composer não foram instaladas.

Para saber se elas foram instaladas você pode verificar se a pasta `application/vendor` está criada.

Recomendo você fazer a instalação do zero, sem editar o arquivo `index.php` usando o instalador, mas pra isso você precisa ter instalado as dependências corretamente com o composer.

Leia atentamente o que está descrito no arquivo `README.md`.

**Comment by fomezero** [comment]
Entendi, o problema do composer é: Como vou instalar em um servidor que esta na nuvem e eu tenho acesso a um painel de controle do cliente, e o ftp para disponibilizar os arquivos para utilização online. Não tenho acesso a executar comandos no servidor.

**Comment by fomezero** [comment]
Este comando que não sei como executar

### Instalação

1. Faça o download dos arquivos.
2. Extraia o pacote e copie para seu webserver.
3. Rode o comando `composer install --no-dev` a partir da raiz do projeto.
4. Acesse sua URL e inicie a instalação, é bem simples, basta preencher as informações no assistente de instalação **MAPOS**.
5. Configure o email de envio no arquivo email.php.
6. Configurar cron jobs para envio de e-mail:


Eu não faço idéia de como executar este comando:

### Comandos de terminal

Para listar todos os comandos de terminal disponíveis, basta executar o comando `php index.php tools` a partir da raiz do projeto, após feita todo o processo de instalação.

**Comment by Pr3d4dor** [comment]
O que você pode fazer é instalar o composer localmente e rodar o comando para instalar as dependências e depois disso enviar a pasta `application/vendor` via ftp.

**Comment by fomezero** [comment]
Esta é uma outro tentativa que ainda não fiz, estou tentando acessar o servidor com o PUTTY, e ver se consigo foi uma saida que pensei. Caso não de certo terei que fazer a instalação local e subir todos os arquivos. Vou tentar não fazer assim vai ser bem estressante.

**Comment by fomezero** [comment]
INFELIZMENTE.

Com muito pesar eu desisto do programa, e aconselho a todos que estão entrando pela primeira vez não utilizem, alias, se conseguirem executar o processo de instalação pode utilizar. POREM, eu desaconselho é MUITO complexo e dependerá de MUITA paciência e tem que saber BEM o que esta fazendo.

Vamos lá:

Fiz todos os processos para instalar, mudei a linha 59, não deu certo como informei a cima.
Fiz várias vezes a desinstalação e instalação.
Fiz a instalei localmente, foi aqui que desisti do programa.
      - Instalei o xampp (para excutar localmente), Quando vai abrir diz a mesma coisa informado acima, Parece que este aplicativo já esta instalado.......
      - Baixei o Docker instalei
     - Composer no proprio site não baixa, vai direto para o docker

Esta atualização deve ter ficado muito boa, como o sistema já era. POREM só para quem conseguir fazer funcionar e tem algum caminho iluminado que mostre como ser feito, o arquivo README.md, não ajuda em nada, pq fala para executar os comandos mais não fala como executar.

Entendo PERFEITAMENTE, que este sistema é gratuito, e PARABENIZO, a todos os envolvidos em disponibilizar um sistema que todos possam utilizar algo ótimo e gratuito. Porem não é mais um sistema simples de instalar e utilizar.

**Comment by willph** [comment]
> INFELIZMENTE.
> 
> Com muito pesar eu desisto do programa, e aconselho a todos que estão entrando pela primeira vez não utilizem, alias, se conseguirem executar o processo de instalação pode utilizar. POREM, eu desaconselho é MUITO complexo e dependerá de MUITA paciência e tem que saber BEM o que esta fazendo.
> 
> Vamos lá:
> 
> Fiz todos os processos para instalar, mudei a linha 59, não deu certo como informei a cima.
> Fiz várias vezes a desinstalação e instalação.
> Fiz a instalei localmente, foi aqui que desisti do programa.
> - Instalei o xampp (para excutar localmente), Quando vai abrir diz a mesma coisa informado acima, Parece que este aplicativo já esta instalado.......
> - Baixei o Docker instalei
> - Composer no proprio site não baixa, vai direto para o docker
> 
> Esta atualização deve ter ficado muito boa, como o sistema já era. POREM só para quem conseguir fazer funcionar e tem algum caminho iluminado que mostre como ser feito, o arquivo README.md, não ajuda em nada, pq fala para executar os comandos mais não fala como executar.
> 
> Entendo PERFEITAMENTE, que este sistema é gratuito, e PARABENIZO, a todos os envolvidos em disponibilizar um sistema que todos possam utilizar algo ótimo e gratuito. Porem não é mais um sistema simples de instalar e utilizar.

Estava tentando instalar na hospedagem?

**Comment by fomezero** [comment]
Sim tentei na hospedagem, UOLHOST, e depois fiz como moderador Pr3d4dor sugeriu, instalar localmente. Porem tem que fazer muitos passos, com o Docker entre outros e não deu certo.

**Comment by Pr3d4dor** [comment]
Desculpa, talvez a documentação tenha que ser melhorada. Porém você instala manualmente ou você usa com o Docker, você não tem que realizar as duas coisas simultaneamente.

Sobre a instalação ser difícil, esse argumento não é plausível pois temos um grupo no WhatsApp co quase 100 pessoas e todas estão utilizando e conseguiram instalar normalmente.

Mas ainda sobre a instalação (na hospedagem) faça os seguintes passos:
- Baixe o mapos.
- Entre na pasta que você baixou o mapos e rode o comando `composer install`.
- Envie a pasta contendo o mapos que você acabou de baixar e rodou o comando via FTP para sua hospedagem.
- Acesse o mapos na sua hospedagem no navegador.
- Siga os pasos do instalador.

Basta somente isso para instalar e usar o mapos.

**Comment by fomezero** [comment]
Cara eu peço um milhão de desculpas, mas eu já fiz isso novamente baixei o arquivo.

coloquei no caminho: c:\mapos-master (mesmo mudando para outro nome qualquer)
abro o prompt de comando e executo c:\mapos-master\composer install
retorna que não é um comando reconhecido interno ou externo.

O grande problema com certeza esta em saber como e onde rodar este comando!

**Comment by willph** [comment]
> Cara eu peço um milhão de desculpas, mas eu já fiz isso novamente baixei o arquivo.
> 
> coloquei no caminho: c:\mapos-master (mesmo mudando para outro nome qualquer)
> abro o prompt de comando e executo c:\mapos-master\composer install
> retorna que não é um comando reconhecido interno ou externo.
> 
> O grande problema com certeza esta em saber como e onde rodar este comando!

Você instalou xampp foi isso?

Caso sim a pasta do mapos tem que esta nesse caminho C:\xampp\htdocs\
Ai colar nessa pasta, o MAPOS.

No navegador digita http://localhost/mapos

Lembrando que Pra acessar o Xampp tem que estar funcionando.
Senão vai da falha de carregamento.

Preciso saber se você tem o XAMPP no seu PC e se você sabe executar?
Se tem o Composer instalado também?

Vou te ajudar.

**Comment by fomezero** [comment]
Eu fiz a instalação do XAMPP e do COMPOSER, o xampp estava funcionando, iniciei e o MYSQL e o APACHE que tem nele.
O composer já não sei se estava funcionando pq dava erro de HYPER-V, e não sei se estava executando. Como tive os problemas eu desinstalei os 2. Mais isso seria o mínimo instalaria novamente.

**Comment by willph** [comment]
> Eu fiz a instalação do XAMPP e do COMPOSER, o xampp estava funcionando, iniciei e o MYSQL e o APACHE que tem nele.
> O composer já não sei se estava funcionando pq dava erro de HYPER-V, e não sei se estava executando. Como tive os problemas eu desinstalei os 2. Mais isso seria o mínimo instalaria novamente.

O composer que falo é esse.
https://getcomposer.org

Download nesse link.
https://getcomposer.org/Composer-Setup.exe

Depois dele instalado me avisa.

Não é o docker. Pode desinstalar ele.

Vou te ajudar na forma tradicional usando xampp.

**Comment by fomezero** [comment]
Já instalado os programas.

**Comment by willph** [comment]
> Já instalado os programas.

Colocou a pasta mapos em htdocs que fica dentro do xampp?

**Comment by willph** [comment]
Depois que fizer isso vai ter que acessa a pasta mapos pelo Power shell ou CMD. Pra que fique assim Ex: C:\xampp\htdocs\mapos\

**Comment by willph** [comment]
Depois que estiver dentro da pasta mapos, executar o comando `composer install  --no-dev`

**Comment by willph** [comment]
Obs: Vou colocar as imagens pra tentar facilitar.

**Comment by willph** [comment]
LEMBRANDO QUE ESSES PASSO A PASSO É PARA QUEM USA **XAMPP** E TEM **WINDOWS** COMO SISTEMA OPERACIONAL. CASO NÃO TENHA O COMPOSER E O XAMPP INSTALADOS, POR FAVOR BAIXAR E INSTALAR ANTES PARA EVITAR ERRO.

DOWNLOAD COMPOSER LINK:` https://getcomposer.org/Composer-Setup.exe`

DOWNLOAD DO XAMPP LINK: `https://www.apachefriends.org/xampp-files/7.4.6/xampp-windows-x64-7.4.6-0-VC15-installer.exe
`
INSTALAÇÃO DO COMPOSER E DO XAMPP É SIMPLES, ESTILO NEXT, NEXT, FINISH.

PRÓXIMOS PASSOS:

PRIMEIRO DEIXE O SERVIDOR RODANDO(ATIVO). EXECUTANDO O XAMPP QUE FICA EM `C:\xampp` DE **DUPLO CLIQUE** EM `xampp-control` QUE ESTA DENTRO DA PASTA. QUANDO ELE ABRIR VOCÊ CLICARA EM **START** REFERENTE A **APACHE** E A **MYSQL** FEITO IMAGEM ABAIXO
![executar-xampp](https://user-images.githubusercontent.com/17226802/82738715-3b690f80-9d10-11ea-895a-ad48d80e3d3b.jpg)

SE TUDO OCORRER OK FICARA **VERDE** TODOS DOIS, FEITO IMAGEM ABAIXO
![executar-xampp-ok](https://user-images.githubusercontent.com/17226802/82738728-563b8400-9d10-11ea-9e95-b0e2d8bf3390.jpg)

AGORA BAIXE O MAPOS ATRAVÉS DO LINK: https://github.com/RamonSilva20/mapos/releases
![mapos-down](https://user-images.githubusercontent.com/17226802/82736980-e9ba8800-9d03-11ea-8bf3-d3c10debd8c1.jpg)

EXTRAIR O ARQUIVO E RENOMEAR A PASTA PARA **MAPOS** E COLAR ESSA PASTA NO **HTDOCS** QUE SE ENCONTRA DENTRO DA PASTA XAMPP: `C:\xampp\htdocs`
![pasta-mapos-htdocs](https://user-images.githubusercontent.com/17226802/82737098-ad3b5c00-9d04-11ea-94d2-fcec7c7d5a26.jpg)

ENTRE NA PASTA **MAPOS** E DENTRO DELA FAÇA O SEGUINTE PARA ABRIR O POWER SHELL **SEGURAR SHIFT + BOTÃO DIREITO DO MOUSE**, E CLICAR EM **ABRIR JANELA DO POWER SHELL AQUI** FEITO A TELA ABAIXO.
![powerShell](https://user-images.githubusercontent.com/17226802/82736684-fa69fe80-9d01-11ea-8ec0-bf5906d552b2.jpg)

APÓS ABRIR A JANELA DO POWER SHELL É SO DIGITAR O COMANDO `composer install --no-dev` FEITO A IMAGEM ABAIXO
![powerShell2](https://user-images.githubusercontent.com/17226802/82736696-0ce43800-9d02-11ea-8d32-87ffcd8a3669.jpg)

SE O COMPOSER ESTIVER INSTALADO CORRETAMENTE VAI ACONTECER ALGO SIMILAR A IMAGEM ABAIXO, AGUARDE A FINALIZAÇÃO.
![composer-install-comand](https://user-images.githubusercontent.com/17226802/82737208-a103ce80-9d05-11ea-9b93-61c2ec28be76.jpg)

OBS: Na imagem acima esta escrito CACHE....... porque eu já fiz esse procedimento, então ele aproveita os arquivos em CACHE para instalar as dependências.

AGORA É HORA DE CRIAR UM BANCO DE DADOS PARA O MAPOS PELO PHPMYADMIN, PARA ISSO DIGITE A URL NO NAVEGADOR: `http://localhost/phpmyadmin/` E DENTRO DELE CRIE UM BD COM O NOME DE SUA PREFERÊNCIA.
![bd-mapos](https://user-images.githubusercontent.com/17226802/82737644-da8a0900-9d08-11ea-9b47-321843078ef5.jpg)

APÓS BD CRIADO ACESSAR LINK `http://localhost/mapos/` E APERTAR **ENTER** A URL MUDARA PARA `http://localhost/mapos/install/index.php` NESSA TELA DE INSTALAÇÃO SO CLICAR EM **PRÓXIMO**
![install-mapos-inicio](https://user-images.githubusercontent.com/17226802/82737718-6c921180-9d09-11ea-8d12-f63aaea2266d.jpg)

NA PRÓXIMA TELA VEM A CONFIGURAÇÕES, **ENDEREÇO DO BD, NOME DE USUÁRIO DO BD, SENHA(_xampp por padrão vem sem senha, deixar em branco nesse caso_), NOME DO BANCO DE DADOS QUE DEU PARA USAR NO MAPOS, SEU NOME, SEU LOGIN E SUA SENHA PARA ACESSAR O MAPOS APÓS INSTALAÇÃO **  DEPOIS DE TUDO PREENCHIDO É SO CLICAR EM **INSTALAR** E AGUARDAR. EXEMPLO NA IMAGEM ABAIXO.
![config-mapos-instalacao](https://user-images.githubusercontent.com/17226802/82737856-2be6c800-9d0a-11ea-9154-8f32448f7b86.jpg)

FINALIZADA A INSTALAÇÃO SO CLICAR EM **IR PARA PAGINA DE LOGIN**
![install-mapos-full](https://user-images.githubusercontent.com/17226802/82737956-c3e4b180-9d0a-11ea-9660-16753ca1da94.jpg)

IRA PARA A PAGINA DE LOGIN `http://localhost/mapos/index.php/login` ONDE O EMAIL FOI **ADMIN@ADMIN.COM** E SENHA **123456**, _LEMBRANDO QUE AS CREDENCIAS FICAM A SUA ESCOLHA NA HORA DA CONFIGURAÇÃO, ESSAS FORAM AS QUE ESCOLHE PARA ESSE EXEMPLO._
![primeiro-acesso](https://user-images.githubusercontent.com/17226802/82738082-9815fb80-9d0b-11ea-8227-d7c2c82b12a3.jpg)

DEPOIS QUE CLICAR EM **ACESSAR**, VOCÊ ESTÁ PRONTO PARA USAR O SISTEMA, SEJA BEM-VINDO AO MAPOS :D
![acesso-concluido](https://user-images.githubusercontent.com/17226802/82738126-e1664b00-9d0b-11ea-9684-024f8a740cf8.jpg)

**Comment by neofln** [comment]
Acabei de atualizar da versão 4.7.5 para a 4.8.0 ao término da atualização deu uma bugada e me redirecionou para a instalação, e dava esse erro descrito, aí foi só editar para production no index.php novamente e voltou a funcionar. define('ENVIRONMENT', 'production');

**Comment by neofln** [comment]
Quanto a hospedagem, se não for impossível, sugiro migrar para o hostinger, já tem tudo que precisa instalado e pronto pra usar, o composer por exemplo já está instalado e funcionando assim que cria a hospedagem, bem como todo o restante de aplicativos que é necessário para o Map-OS funcionar redondinho. 
Aí é só usar o putty pra executar o composer via ssh.

Tive bem poucos problemas com o Map-OS, todos que não resolvi sozinho consegui resolver lendo as dicas aqui no git ou solicitando ajuda dos desenvolvedores quando foi o caso, recomendo fortemente o sistema pois está ficando cada vez melhor a cada incremento na versão.

**Comment by fomezero** [comment]
Aleluia!!! Após esta explicação tudo ficou mais fácil e funcionou.
INFELIZMENTE!! Tem mais 1 porem. Referente a importar o baco antigo.
Entrei no MYSQL, importei o banco funcionando tudo, até que: Fui abrir uma OS e deu o erro.
![image](https://user-images.githubusercontent.com/38925645/82836675-5b7a0980-9e9d-11ea-8246-1a38466dc080.png)

**Comment by neofln** [comment]
Chegou a clicar em "Configurações" -> "Sistema" -> "Atualizar Banco de Dados"?

**Comment by fomezero** [comment]
Não tem esta opção! a versão do sistema que estou usando é a 4.8.1
![image](https://user-images.githubusercontent.com/38925645/82840877-828b0800-9eaa-11ea-84f9-1fecc90da609.png)

**Comment by willph** [comment]
> Não tem esta opção! a versão do sistema que estou usando é a 4.8.1
> ![image](https://user-images.githubusercontent.com/38925645/82840877-828b0800-9eaa-11ea-84f9-1fecc90da609.png)

tem, mas para aparecer tem que ativar em PERMISSÕES, 

Editando a permissão do usuário que tiver lá.

**Comment by fomezero** [comment]
Continua dando o mesmo erro, cliquei em atualizar salvei, cliquei em atualizar o Mapos. Fiz todas as formas, porem continua.

![banco](https://user-images.githubusercontent.com/38925645/82848426-c5100d00-9ec9-11ea-8da5-a01f2ad58793.JPG)
![erra](https://user-images.githubusercontent.com/38925645/82848455-e3760880-9ec9-11ea-9448-f06bc4649639.JPG)
Notei tb que quando clico em arquivo da o "mesmo" problema.
![image](https://user-images.githubusercontent.com/38925645/82848571-6f883000-9eca-11ea-98a4-3e86f45e6743.png)

**Comment by willph** [comment]
> Continua dando o mesmo erro, cliquei em atualizar salvei, cliquei em atualizar o Mapos. Fiz todas as formas, porem continua.
> 
> ![banco](https://user-images.githubusercontent.com/38925645/82848426-c5100d00-9ec9-11ea-8da5-a01f2ad58793.JPG)
> ![erra](https://user-images.githubusercontent.com/38925645/82848455-e3760880-9ec9-11ea-9448-f06bc4649639.JPG)
> Notei tb que quando clico em arquivo da o "mesmo" problema.
> ![image](https://user-images.githubusercontent.com/38925645/82848571-6f883000-9eca-11ea-98a4-3e86f45e6743.png)

Esses erros aconteceu depois de importar um BD antigo?

Como foi feita essa importação?

**Comment by fomezero** [comment]
Sim esta com o banco antigo, eu entrei no sql, e fiz a importação por la!

**Comment by willph** [comment]
> Sim esta com o banco antigo, eu entrei no sql, e fiz a importação por la!

Já fez sem importa o seu BD, com a instalação limpa?

Se não fez, faça por favor, instalação limpa, sem importa BD antigo.

Teste as opções, e diga se teve erro.

Após sua resposta vou analisar.

**Comment by fomezero** [comment]
Refiz todo o processo, consegui acessar o sistema, normalmente. OS esta funcionando normalmente, porem não esta com a minha base de dados antiga e não sei como importar para o sistema. Já que não encontrei a opção de importar BD.

**Comment by willph** [comment]
> Refiz todo o processo, consegui acessar o sistema, normalmente. OS esta funcionando normalmente, porem não esta com a minha base de dados antiga e não sei como importar para o sistema. Já que não encontrei a opção de importar BD.

Verifique se o campo garantia, lá em OS tem letra ou caracteres sem ser apenas número.
Caso tenha letra ou outra coisa sem ser apenas número, remova e deixe apenas número, sem espaço também. E me da retorno se erro ainda persiste.

**Comment by fomezero** [comment]
existia no campo garantia 3 lugares que tinha "3 meses" escritos, apaguei os campos mesmo assim esta dando erro.

**Comment by willph** [comment]
> existia no campo garantia 3 lugares que tinha "3 meses" escritos, apaguei os campos mesmo assim esta dando erro.

dataFinal em todos estão preenchidos ou tem campo em branco?
Antigamente era permitido deixar em branco, mas depois passou a ser obrigatório.
Preencher se tiver campo em branco.

**Comment by fomezero** [comment]
Os campos estão todos preenchidos, esta é uma linha que esta preenchida.
INSERT INTO `os` (`idOs`, `dataInicial`, `dataFinal`, `garantia`, `descricaoProduto`, `defeito`, `status`, `observacoes`, `laudoTecnico`, `valorTotal`, `clientes_id`, `usuarios_id`, `lancamento`, `faturado`) VALUES ('124', '2019-08-19', '2019-08-19', '', 'Instalação de Certificado no computador do laboratório. | * |\r\nFonte de Notebook ACER', '', 'Aberto', 'O certificado no computador do laboratório não foi instalado devido a dúvidas no processo de instalação e utilização do mesmo. | * |\r\nA fonte foi deixada com o funcionário da área Técnica Paulo', '', NULL, '2', '3', NULL, '0');

**Comment by fomezero** [comment]
Acabei desistindo de importar o banco, não havia mais o que eu fizesse. Fiz a instalação dos 2 bancos, o mais antigo e o mais novo. Comparei as tabela vi que tem mais campos, e tb removi a garantia. Como eram muitas modificação acabei desistindo de atualizar o banco antigo. Acabei utilizando o sistema e refazendo tudo. Pelo menos consigo utilizar, uma pena que não consegui trazer o histórico porem da para usar.
MUITO OBRIGADO pela ajuda.

**Comment by willph** [comment]
> Acabei desistindo de importar o banco, não havia mais o que eu fizesse. Fiz a instalação dos 2 bancos, o mais antigo e o mais novo. Comparei as tabela vi que tem mais campos, e tb removi a garantia. Como eram muitas modificação acabei desistindo de atualizar o banco antigo. Acabei utilizando o sistema e refazendo tudo. Pelo menos consigo utilizar, uma pena que não consegui trazer o histórico porem da para usar.
> MUITO OBRIGADO pela ajuda.

Fico feliz em saber que conseguiu uma alternativa. Uma pena não ter conseguido lhe ajudar de uma maneira que seu sistema ficasse 100%.
Tem como fazer o update do bd, mas não é tão simples de ser feito, pois será manualmente.
