### ISSUE TITLE
Adicionar prouto em OS

### ISSUE THREAD

**Issue by duuhmenezes** [RamonSilva20/mapos#753]
** Olá, após atualizar para o 4.7.5 fui criar uma nova OS, e ao tentar adicionar o produto ele me retorna "Atenção
Ocorreu um erro ao tentar adicionar produto." **

**Comment by Pr3d4dor** [comment]
Duplicado #749, basta você atualizar manualmente, ao invés de usar o botão de atualização do sistema. A funcionalidade de atualização no sistema irá ser refeita.
