### ISSUE TITLE
Termos de Garantia vinculados a OS

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#754]
Seria interessante ao imprimir conter no termo de garantia o numero de os quando para os e de venda quando para venda...

**Comment by Pr3d4dor** [comment]
Não é possível fazer isso porque o mesmo termo de garantia pode estar associado a varias OS ou vendas.

**Comment by lrochawl** [comment]
Concordo e no sistema também podemos criar varios termos com varios conteudos e selecionar o termo ao abrir uma os por exemplo, imaginei a possibilidade de apenas incluir no topo do documento impresso o numero da OS ao ser acionado o comando de impressão a partir de uma OS ou caso fosse a partir de uma venda o codigo de uma venda. 

![image](https://user-images.githubusercontent.com/49371821/82731934-6fc4d780-9ce0-11ea-8bf5-498633b7b71b.png)
