### ISSUE TITLE
Algumas observações

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#755]
Boa tarde

Na estrutura do e-mail enviado
Logo no inicio nas informações de status e garantias, parecem desordenadas

Ao exibir os na área do cliente
E-mail do responsável não aparece

Esse não sei se estaria errado, mas aqui eu removi
na visualização da os na área administrativa existe uma barra a mais na exibição do subtotal

O plano de fundo das áreas de impressão (impressão sai normal) de os do cliente e administrativa
estão com fundo escuro

No acesso mobile o hamburger menu some com facilidade

**Comment by Pr3d4dor** [comment]
@lrochawl Se você quiser fazer uma pull request com ajustes mencionados ficariamos agradecidos, caso contrário iremos fazer os ajustes quando for possível.
