### ISSUE TITLE
Instalação com erro

### ISSUE THREAD

**Issue by faustinotv** [RamonSilva20/mapos#756]
Fiz a instalação limpa da versão 4.7.5, em uma hospedagem, (um subdominio criado para testes)
Instalação ocorreu sem erros, mas após tentar abrir a página de login, retorna com o seguinte erro:
"Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"

Refiz por 3 vezes a instalação, pensando que teria feito algo de errado, mas realmente não sei o que é

**Comment by Pr3d4dor** [comment]
Você não executou todos os passos de instalação descritos no `README`, faltou instalar as dependências com o composer:

```
3. Rode o comando composer install --no-dev a partir da raiz do projeto.
```
