### ISSUE TITLE
Como fazer o processo de instação/atualização num servidor 

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#759]
Como fazer o processo de instação/atualização num servidor online (uso o hostgator com cpanel), não sei rodar comando "composer install --no-dev" la no servidor.. 

Agradeço a atenção.

**Comment by Pr3d4dor** [comment]
Se você não tem acesso SSH, basta você instalar o composer localmente no seu computador e realizar o comando no seu computador. Após isso basta enviar a pasta `application/vendor` para lá via FTP.

**Comment by tibjunior** [comment]
Grato pela resposta.. :) essa parte funcionou... agora estou com um erro de login.. clico em logar e ele não faz nada.. vi que tem uma issue relacionada.. mas fiz o que fala lá e não funciona... penso que tenha relação com o SSL, pois no site principal tem SSL válido mas no sistema fica como "não seguro"..


jquery-1.12.4.min.js:4 Mixed Content: The page at '**endereço do site**/index.php/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '**endereço do site**/index.php/login/verificarLogin?ajax=true'. This content should also be served over HTTPS.
send @ jquery-1.12.4.min.js:4

login:1 Access to XMLHttpRequest at '**endereço do site**/index.php/login/verificarLogin?ajax=true' from origin '**endereço do site**' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**endereço do site**/index.php/login/verificarLogin?ajax=true:1 Failed to load resource: net::ERR_FAILED


sabe o que posso fazer a respeito?

Ja configurei php para 5.6, o banco ta ok.. carreguei o da própria versão. a versão anterior funciona.. essa atualizada da isso.

**Comment by Pr3d4dor** [comment]
Não pode usar PHP 5.6, é necessário usar o PHP 7.1 no mínimo.

**Comment by tibjunior** [comment]
Problemas resolvidos... Grato pela atenção.
