### ISSUE TITLE
erro ao adicionar serviço ou produto a uma os.

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#760]
![image](https://user-images.githubusercontent.com/48699495/82241596-d037cb80-9912-11ea-8984-4c679877473b.png)

estou com esse probleminha ao tentar incluir um produto ou serviço a uma os. 
alguma ideia?

**Comment by gdinizcastro** [comment]
![20 May  18](https://user-images.githubusercontent.com/65564593/82249298-ebf59e80-991f-11ea-9ad5-87b5368fd143.jpg)

Mesma coisa por aqui =(

**Comment by Pr3d4dor** [comment]
Basta reinstalar sem utilizar o atualizador.

**Comment by gdinizcastro** [comment]
> Basta reinstalar sem utilizar o atualizador.

Realmente resolveu! Boa lek!

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.

**Comment by cefamigo** [comment]
Desculpe a minha ignorância. Estou com o meso erro. Como faço para reinstalar sem atualizador?

**Comment by Pr3d4dor** [comment]
Basta vc instalar o mapos na última versão normalmente e configurar para usar o seu banco antigo.

**Comment by giampaulo** [comment]
funcionou.

**Comment by cefamigo** [comment]
Fiz o procedimento Pr3d4dor e mesmo asssim esta dando o mesmo problema.

**Comment by Pr3d4dor** [comment]
Então você fez alguma coisa errada durante a instalação, porque várias pessoas já fizeram o mesmo e funcionou.

**Comment by cefamigo** [comment]
Acredito nessa hipótese estou aprendendo ainda. Teria um tutorial

**Comment by Pr3d4dor** [comment]
Você está instalando no local ou em uma hospedagem?

**Comment by cefamigo** [comment]
Nesse momento local.
