### ISSUE TITLE
Financeiro - Opção de retirada do caixa.

### ISSUE THREAD

**Issue by fmikola** [RamonSilva20/mapos#761]
Gostaria de sugerir colocar no item Financeiro, a opção de retirada do caixa.

Por exemplo, quando vai se fazer o pagamento de um funcionário ou uma retirada de dinheiro para o uso pessoal mesmo, que isso constasse no relatório financeiro.

Acho que isso iria facilitar bastante no controle do caixa.

Não sei se já existe essa solicitação, caso exista, por favor desconsiderar.

Grato;
Fabrício

**Comment by maycon1977** [comment]
Então...

Primeiramente vc vai em NOVA DESPESA:

![image](https://user-images.githubusercontent.com/47214174/82276475-c25a6880-995b-11ea-9132-a0f8c69132fc.png)

Depois pode preencher assim, por exemplo:

![image](https://user-images.githubusercontent.com/47214174/82276545-f3d33400-995b-11ea-8c16-2e6d85e7b4fa.png)

Não funciona pra vc dessa forma?

**Comment by fmikola** [comment]
vou tentar fazer dessa forma...
Obrigado

**Comment by Pr3d4dor** [comment]
Vou fechar a issue, se precisar de mais ajuda é só reabrir.
