### ISSUE TITLE
caminho das pedras

### ISSUE THREAD

**Issue by fabianofvd** [RamonSilva20/mapos#762]
ola, tudo bem? espero que sim :)

então que queria aprender mais sobre mysql e php, mas no entanto em especifico gostaria de saber por onde começar a editar o menu principal, tipo quero colocar um modulo de recados, uma tabela para controlar numero de serie nos produtos.

por exemplo, vou mandar um produto para concerto, eu gostaria de alguma forma identificar e diferenciar dos demais.

ou seja, tem algum modulo ou programa que facilite isso ?

**Comment by Pr3d4dor** [comment]
Se você não tem experiência com programação não será tão fácil.

Porém você pode comear lendo nesse site: http://br.phptherightway.com/

Depois você deverá pesquisar e entender o padrão MVC que é usado.

Por fim você deverá pesquisar sobre o code igniter 3 que é o framework usado no mapos.
