### ISSUE TITLE
Validação de CPF (Desativar)

### ISSUE THREAD

**Issue by JulianoSavino** [RamonSilva20/mapos#763]
Boa noite pessoal, estou com uma penca de clientes que preciso cadastrar no sistema para lançar as OS e não consigo pois muitos deles não querem passar o CPF nem nenhum documento. A questão não é de certo ou errado pois não vou obrigar o cliente a fazer algo que não quer mesmo sendo contra as politicas da empresa e correr o risco de perder o serviço.
Nas versões anteriores a 4.7.5 (que estou usando) eu até conseguia colocar um numero aleatório que passava, desde que não conflitasse com outro, mas agora não rola mais, já tenho uns 15 clientes para cadastrar e preciso saber como fazer para desativar essa função que me obriga a colocar CPF valido. Não quero recorrer aos geradores de CPF.
Agradeço a ajuda...

**Comment by Pr3d4dor** [comment]
Basta você mudar a linha: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php#L13 para: `required|trim` e remover as linhas 14 à 16.
