### ISSUE TITLE
Cadastro de cliente não aparece o campo para digitar "número"

### ISSUE THREAD

**Issue by r3zend3** [RamonSilva20/mapos#765]
Qdo vou cadastrar o cliente o campo "número" do endereço não é habilitado, porém qdo vou finalizar o cadastro aparece "The Número field is required." O campo para digitação não aparece. 
Se alguem puder ajudar, desde já agradeço. obrigado

**Comment by Pr3d4dor** [comment]
Qual versão do mapos você está utilizando?

**Comment by r3zend3** [comment]
4.8.0

**Comment by Pr3d4dor** [comment]
Você fez atualização ou instalou do zero?

Se sim, recomendo reinstalar do zero pois o atualizador algumas vezes apresenta alguns problemas.
