### ISSUE TITLE
Dificuldade em Atualizar do 3.8 para 4.8 em LocalHost

### ISSUE THREAD

**Issue by 1rks** [RamonSilva20/mapos#766]
Uso o Mapos em minha assistência técnica a muito tempo, em LocalHost e sempre reinstalo ele para atualizar a versão, pois não consigo atualizá-lo, Porem desta vez meu BD esta meio grande, se for recadastrar tudo novamente vai dar muita dor de cabeça, ainda sou iniciante na faculdade de sistemas por isso a dificuldade. Se alguém puder me orientar sera de grande ajuda.

**Comment by Pr3d4dor** [comment]
O que vc pode fazer é criar um backup do banco de dados atual e realizar todos os updates contidos dentro da pasta updates.

Após isso baixa baixar o mapos na última versão e conectar no backup do banco de dados.

**Comment by 1rks** [comment]
O meu esta dando este erro, tentei o comando composer update pelo cmd mas continuou o mesmo erro.
.
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by Pr3d4dor** [comment]
Leia bem as instruções no `README.md`, agora é necessário usar o `composer` que é gerenciador de dependências do PHP.

```
```

**Comment by 1rks** [comment]
não sei nada sobre composer, mas vou tentar aqui.
 estou usando o wampserver tem alguma diferença ?

**Comment by 1rks** [comment]
como você disse anteriormente como faço para executar o update do 3.8 para 4.8, antes tenho que pular para o 4.0? como seria.

**Comment by Pr3d4dor** [comment]
Você tem que executar todos os .sql que estão dentro da pasta updates a partir da versão que você está pra frente.

**Comment by 1rks** [comment]
Na hora que eu tento fazer o update do composer pelo cmd aparece um erro.
.
Problem 1
    - symfony/var-dumper v5.0.8 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.7 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.6 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.5 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.4 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.3 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.2 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.1 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - symfony/var-dumper v5.0.0 requires php ^7.2.5 -> your PHP version (5.6.40) does not satisfy that requirement.
    - Installation request for symfony/var-dumper ^5.0 -> satisfiable by symfony/var-dumper[v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8].

**Comment by Pr3d4dor** [comment]
Você está usando versão do PHP ultrapassada (5.6). Você precisa atualizar para o PHP 7.1 pra cima.

**Comment by 1rks** [comment]
estou na 7.3.5, antes estava na 7.0 e o mesmo erro.

**Comment by 1rks** [comment]
como que eu faço para executar as .sql, tentei pelo cmd mas deu erro

**Comment by 1rks** [comment]
tentei este comando mas deu que a tabela ja existe.
.
CREATE TABLE `migrations` (
    `version` BIGINT(20) NOT NULL
);

INSERT INTO `migrations`(`version`) VALUES ('20121031100537');

**Comment by Pr3d4dor** [comment]
Não está na 7.3 não, provavelmente você está com múltiplas versões instaladas no seu computador e a que está rodando no terminal é a antiga.

Se a tabela já existe, não precisa criar.

**Comment by 1rks** [comment]
mas se a tabela já existe como vou mudar a versão. esta rodando a 7.3

**Comment by Pr3d4dor** [comment]
Se a tabela já existe, não precisa fazer nada, quanto ao PHP, como eu disse pelo erro que você postou está rodando o PHP 5.6 no terminal.

**Comment by 1rks** [comment]
como eu verifico isto? se esta na 5.6

**Comment by 1rks** [comment]
tem outra forma de usar o composer

**Comment by Pr3d4dor** [comment]
Só digitar php -v no terminal.

Não, não tem outra forma de usar.

**Comment by giampaulo** [comment]
o direcionamento do composer deve estar pra versao antiga, altere a versao do php no composer ou desinstale e reinstale novamente apontando para versao certa do php.

**Comment by 1rks** [comment]
Aparece isso quando coloco pra buscar a versão do php 

PHP 7.0.33 (cli) (built: Dec  5 2018 21:22:29) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by 1rks** [comment]
> o direcionamento do composer deve estar pra versao antiga, altere a versao do php no composer ou desinstale e reinstale novamente apontando para versao certa do php.

vou tentar reinstalar

**Comment by 1rks** [comment]
> o direcionamento do composer deve estar pra versao antiga, altere a versao do php no composer ou desinstale e reinstale novamente apontando para versao certa do php.

estava apontado para versão 7.0, agora apontei para 7.3

**Comment by giampaulo** [comment]
preste atençao no passo a passo da instalaçao, ali tem uma parte que pede para direcionar para qual versao do php vc deseja, se tem multiplas versoes rodando tenha certeza que esta apontando para versao certa

**Comment by 1rks** [comment]
> preste atençao no passo a passo da instalaçao, ali tem uma parte que pede para direcionar para qual versao do php vc deseja, se tem multiplas versoes rodando tenha certeza que esta apontando para versao certa

como vou saber a versão correta, aparece todas as versões, a 5.6, 7.1, 7.2, e versão 7.3 apontei para a 7.3

**Comment by giampaulo** [comment]
vai listar as versoes instaladas ai, selecione a que satisfaz os requisitos minimos

**Comment by 1rks** [comment]
> vai listar as versoes instaladas ai, selecione a que satisfaz os requisitos mini

**Comment by 1rks** [comment]
desinstalei e estou reinstalando tudo aqui

**Comment by 1rks** [comment]
Apos instalar tudo novamente o update do composer foi de executado. porem o programa fica desconfigurado só em html.

**Comment by Pr3d4dor** [comment]
Você usou o instalador para realizar a configuração?

Caso contrário, recomendo utilizar ele pois já configura todos os arquivos necessários.

**Comment by giampaulo** [comment]
Isso. Faz uma instalação nova dessa ultima versão. Depois importa o banco

**Comment by 1rks** [comment]
Estou tentando, fiz assim desinstalei tudo e reinstalei o wampserver,
Depois fiz a instalação limpa do mapos, usando o instalador, na primeira ver ficou só em html, ai reinstalei o mapos e deu erro 404, reinstalei mais uma vez, funcionou porem na hora que fui importar o BD o sistema não logava, 
ai desinstalei e instalei novamente, porem esta dando erro talvez seja alguma informação que estou colocando no instalador. tipo URL etc

**Comment by giampaulo** [comment]
tem certeza que essa versão do wamp é a que contém a versão correta do php ?

**Comment by 1rks** [comment]
> tem certeza que essa versão do wamp é a que contém a versão correta do php ?

Sim, Agora consegui, não sei como, mas foi, desinstalei tudo que dava na minha maquina e reinstalei varias vezes. sempre utilizando o instalador. 
Agora parece que foi.

**Comment by 1rks** [comment]
consegui fazer a instalação aqui, porem quando entra no sistema, os atalhos da dashboard tipo f1,f2,etc não aparece os ícones nos botoes.
 Isso é normal?

**Comment by 1rks** [comment]
outra coisa quando seleciono o BD e mando Importar o meu BD antigo, algumas coisas some, a Configuração do sistema que muda o tema também some. quando executo as .sql fala que já existe.
como proceder?
