### ISSUE TITLE
Erro ao pesquisar relatórios.

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#768]
Ao tirar relatórios de O.S apresenta este erro em anexo.
![erro 1](https://user-images.githubusercontent.com/21310068/82519999-19457680-9af1-11ea-9c79-6e5491617532.png)
![erro 2](https://user-images.githubusercontent.com/21310068/82520003-1a76a380-9af1-11ea-84cf-5dd1c2499842.png)

**Comment by cabralwms** [comment]
Verifica se a Imagem do Emitente esta aparecendo no lugar aonde cadastra o emitente as vezes se vc atualizou precisa carregar a imagem novamente. E confere as permissões também das pastas e arquivos aonde esta hospedado.

**Comment by Pr3d4dor** [comment]
Faça como o @cabralwms comentou, vou fechar a issue e se continuar com problemas pode reabrir.
