### ISSUE TITLE
Cadê a demonstração?!

### ISSUE THREAD

**Issue by drelldeveloper** [RamonSilva20/mapos#77]
Olá Ramon, Tudo bom?
Os endereços que você deixou, [Demo](https://www.sistemamapos.esy.es/mapos) e [Sistema](https://www.sistemamapos.esy.es) eles não existe :(
Notei também que, você é o único desenvolvedor do projeto. Caso você quiser, desejo poder contribuir.

**Comment by RamonSilva20** [comment]
Olá @drelldeveloper, esperar o que de hospedagem gratuita kkkk, de vez em quando funciona. Sempre bem vinda qualquer ajuda, estou trabalhando em uma nova versão no Laravel, mas não estou muito satisfeito com o resultado, framework muito grande e não adequado para hospedagens compartilhadas. Estou analisando outras opções, talvez CakePHP ou aguardar o CI4.

**Comment by heaccioly** [comment]
Ramon, não está valendo a pena trabalhar com o CI 3?

**Comment by RamonSilva20** [comment]
@heaccioly Sim, com certeza, mas como meu objetivo é de contribuir, mas também de me atualizar e aprender novas coisas, acho que seria interessante.

**Comment by heaccioly** [comment]
Ah sim! Entendí Ramon!
Perguntei, pois, eu gostaria de desenvolver um sistema simples de controle. A pesar de não ser programador, mas me aventuro na área.
Dei uma pesquisada sobre o Laravel, e vi que parece muito bom. Mas só pelo fato dele não funcionar em hospedagem compartilhada, já me desanimou.

**Comment by RamonSilva20** [comment]
Com Laravel eu mal iniciei o projeto e já está com 190 MB, como é um sistema de pequeno e médio porte e muita gente utiliza em hospedagem compartilhada não acho compatível. O Laravel é excelente, vale muito a pena aprendê-lo, mas para este projeto não acho interessante.

**Comment by heaccioly** [comment]
Realmente o mesmo parece ser um excelente framework, mas como você disse, para um propósito diferente, voltado à grandes sistemas, com maior complexidade. Sendo assim, vou continuar estudando o CI mesmo na versão 3.

Fiz diversas customizações no seu atual sistema, que talvez seja interessante para o resto do pessoal aqui. Mas como algumas coisas não estão funcionando corretamente, e ando com uma rotina de trabalho bem acelerada, acabei dando um tempo do estudo.

Mas pretendo contribuir em breve.
Parabéns pelo sistema, e obrigado pelas informações acima.

**Comment by drelldeveloper** [comment]
Verdade, ainda mais Hostiger KKKKK Ramon, você tem alguma documentação do projeto, alguma quadro no Trello, alguma coisa que eu posso ter acesso para contribuir no desenvolvimento?

**Comment by RamonSilva20** [comment]
Perdi a documentação do sistema, possivelmente está no meu e-mail. Assim que tiver um tempo vou criar um roadmap da nova versão para quem tiver interesse de contribuir.

**Comment by drelldeveloper** [comment]
Okay, você quer meu e-mail para me notificar sobre isso?

**Comment by drelldeveloper** [comment]
Beleza, você quer meu e-mail para me notificar sobre isso?

**Comment by adallberto** [comment]
Se precisar de uma hospedagem pra rodar a demo pode falar comigo

**Comment by drelldeveloper** [comment]
Sim, irá precisar de uma hospedagem. Essa sua é gratuita?

**Comment by julianopp** [comment]
Se precisarem, tenho uma hospedagem no one.com para uma demo.

**Comment by adallberto** [comment]
@drelldeveloper não ela é paga!

**Comment by drelldeveloper** [comment]
Hum, eu não dou o braço á torcer.

**Comment by drelldeveloper** [comment]
Eu vou ver o que posso fazer! Obrigado pessoal.
