### ISSUE TITLE
Criação de relatório pela entrada "área do cliente"

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#770]
Olá,
Existe uma maneira de liberar a opção "relatório de O.S, financeiro, compras etc..." na entrada "área do cliente"?

Possuo um cliente que quer tirar os relatórios todo mês para agilizar os pagamentos, muitas vezes estou viajando e sem acesso a internet, assim gerando atrasos e descontentamento para meu contratante.
Sem contar que isso aliviaria para muitos, sendo assim os clientes não olhariam apenas as O.S e compras abertas uma por uma, mas sim um relatório completo por periodo.
![erro 1](https://user-images.githubusercontent.com/21310068/82616385-07b8a900-9b9b-11ea-84de-aa39cf09d200.png)

**Comment by Pr3d4dor** [comment]
Obrigado, ficará na lista de espera para ser implementado.

**Comment by Triaca** [comment]
@Pr3d4dor posso dar outra ideia também referente ao relatórios aqui, ou devo criar outra request?

**Comment by Pr3d4dor** [comment]
Acho que é melhor deixar separado, uma ideia por request.
