### ISSUE TITLE
Desconto das OS

### ISSUE THREAD

**Issue by leandr0ferreir4** [RamonSilva20/mapos#771]
Gostaria de uma sugestão de desconto nas Ordens de Serviços, antes eu aplicava com um serviço chamado "Desconto" adicionava este "serviço" na O.S com uma quantidade negativa, assim o Mapos calcularia a soma total dos produtos e serviços subtraindo do "Serviço de desconto", depois da última atualização não consigo mais aplicar "desconto" desta maneira, sei que ao inserir um produto ou serviço eu consigo alterar o valor, porém seria interessante mesmo descrever o quanto de desconto foi dado, pois antes do outro método eu inseria os produtos e serviços já com o valor descontado e ocorria que quando eu ia entregar o equipamento com a O.S o cliente ficava questionando se eu tinha dado desconto ou não.

**Comment by Pr3d4dor** [comment]
Obrigado, ficará na lista de espera para ser implementado.
