### ISSUE TITLE
Erro nos anexos das OSs

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#772]
O sistema não exclui os anexos que enviei na os.

Sugestão: exibir o nome dos anexos, pois só aparecem os icones..

caso eu encontre algo atualizo aqui..

**Comment by Pr3d4dor** [comment]
Não entendi, pode explicar melhor?

**Comment by tibjunior** [comment]
Após criar uma OS do cliente, anexei as notas fiscais geradas para ter um controle das mesmas. Porém tive dois problemas, um é que não tem como identificar as notas, pois não aparecem nomes, apenas icones. O segundo é que na hora de excluir o anexo, nada acontece.. fica apenas carregando a "exclusão".

**Comment by cabralwms** [comment]
O Meu tambem deu esse problema. Anexei um foto do equipamento e agora nem da pra ver a foto, nem baixar, nem excluir.

**Comment by Pr3d4dor** [comment]
Eu coloquei os nomes do anexo abaixo do ícone do mesmo e vou fazer uma pull request colocando isso. Porém a exclusão ocorre normalmente aqui. Se puder apertar o F12 e ir na opção de rede puder colocar o erro aqui facilitaria.

**Comment by rafaerigson** [comment]
No meu caso com a versão 4.8.1 não esta aparecendo o nome do arquivo e o cliente não consegue fazer download do arquivo, o cliente loga no sistema ve a OS entra nela e clica em anexo e quando ele clica no arquivo e depois em download a pagina é direcionada para a pagina de login do administrador, alguém com o mesmo problema que possa me dar uma luz?

**Comment by tibjunior** [comment]
> Eu coloquei os nomes do anexo abaixo do ícone do mesmo e vou fazer uma pull request colocando isso. Porém a exclusão ocorre normalmente aqui. Se puder apertar o F12 e ir na opção de rede puder colocar o erro aqui facilitaria.

POST https://muambeiros.tech/sosmec/index.php/os/excluirAnexo/2 500
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
(anonymous) @ 2:475
dispatch @ jquery-1.12.4.min.js:3
r.handle @ jquery-1.12.4.min.js:3
