### ISSUE TITLE
Erro ao importar banco de dados !

### ISSUE THREAD

**Issue by 1rks** [RamonSilva20/mapos#773]
Estava na versão 3.8. Reinstalei o sistema na versão 4.8, 
Ao importar o BD antigo algumas funcionalidades do sistema somem, como as configurações de sistema,tipo tema.
Depois de importar o bd antigo, na hora de fazer uma venda o produto não aparece.
Executei os updates e sempre aparece a mensagem que já exite a tabela. como proceder?

**Comment by tibjunior** [comment]
Tive alguns erros ao atualiza, pois a estrutura do banco antigo é diferente da do novo... a sorte é que tinha pouca informação.. ai transferi tabela por tabela..

**Comment by 1rks** [comment]
> Tive alguns erros ao atualiza, pois a estrutura do banco antigo é diferente da do novo... a sorte é que tinha pouca informação.. ai transferi tabela por tabela..

Quando mudei para 3.8 fiz a mudança manual também, porem tem muito tempo que uso, agora tenho muitos dados se for recadastrar tudo manual vai dar muita dor de cabeça.

**Comment by 1rks** [comment]
Como faço para voltar a aparecer a configuração do sistema no menu?

**Comment by cabralwms** [comment]
Acredito que seja apenas as perminssoes vc precisa ir em configuracoes/permissoes e colocar para aparecer sistema e coloca tudo para seu usuario administrador.

**Comment by 1rks** [comment]
> Acredito que seja apenas as perminssoes vc precisa ir em configuracoes/permissoes e colocar para aparecer sistema e coloca tudo para seu usuario administrador.

Muito Obrigado. Realmente era isto, e eu perdi um tempão, procurando soluções difíceis e o obvio estava na minha cara. mas o programa ainda esta dando alguns problemas!.

**Comment by 1rks** [comment]
Ao fazer uma venda, ou acrescentar produto pela OS, ao digitar o nome do produto não aparece nenhum item. sendo que exite e da pra cadastrar produtos.

**Comment by 1rks** [comment]
Outro erro é na hora de cadastrar cliente, aparece uma mensagem de erro. OBS: todos os problemas só aparecem quando importo o BD antigo que rodava na Versão 3.8.

**Comment by 1rks** [comment]
> Ao fazer uma venda, ou acrescentar produto pela OS, ao digitar o nome do produto não aparece nenhum item. sendo que exite e da pra cadastrar produtos.

**Comment by 1rks** [comment]
Minha tabela cliente esta faltando o campo Contato e Complemento isso faz com que de erro, porem se eu importo somente o contato e complemento perco todos os clientes.

**Comment by 1rks** [comment]
> Acredito que seja apenas as permissores vc precisa ir em configuracoes/permissoes e colocar para aparecer sistema e coloca tudo para seu usuario administrador.

Tive o mesmo problema que vc teve, preciso acrescentar na tabela clientes os campos 

`contato` varchar(45) DEFAULT NULL,
`complemento` varchar(45) DEFAULT NULL,

tentei mas deu erro como vc fez ?

**Comment by 1rks** [comment]
> Outro erro é na hora de cadastrar cliente, aparece uma mensagem de erro. OBS: todos os problemas só aparecem quando importo o BD antigo que rodava na Versão 3.8.

A questão de não cadastrar Cliente, é que a tabela cliente estava faltando estes dois campos, acrescentei manualmente e deu certo. 

`contato` varchar(45) DEFAULT NULL,
`complemento` varchar(45) DEFAULT NULL,
