### ISSUE TITLE
Icones do sistema

### ISSUE THREAD

**Issue by 1rks** [RamonSilva20/mapos#774]
E normal os ícones do sistema estarem bem pequenos ? exemplo ícones que ficam em ações em OS. Podendo identificá-los somente quando passa o mouse em cima ou pelas cores, porem é muito difícil clicar neles, ou esperar a mensagem relacionada com o ícone. 
.
Na imagem que tem do sistema no Git aparece os botoes superiores, f1,f2,ect do Dashboard com ícones neles, poem quando instala só aparece os botoes com cores solidas isso e normal?

**Comment by Pr3d4dor** [comment]
Isso parece configuração incorreta do teu servidor, ou configurações do teu navegador.
