### ISSUE TITLE
atualização automática da v4.7.5 para v4.8.0

### ISSUE THREAD

**Issue by Ronierick** [RamonSilva20/mapos#775]
senhores, boa noite, efetuei a atualização via sistema e agora, ele me retorna para a página de install, informa que o app já está instalado e fica em loop. alguem passou por isso? soube como resolver? obrigado.

**Comment by Pr3d4dor** [comment]
Provavelmente sobrescreveu a página index.php, atualize a linha 59 de "install" para "production".

**Comment by dcassios** [comment]
@Ronierick  Após a atualização da linha 59 o problema foi resolvido. Grato @Pr3d4dor
