### ISSUE TITLE
Relatorios de OS

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#777]
Não sei se realmente e um BUG ou sei la
quando gero um relatorio a ordem das OS ficam misturadas (Relatorio geral de todas as OS)
tipo começa pela os 20 e vai em sequiencia ate a 35
depois entra da 1 a 5 depois da 15 a 20

os clientes ficam misturados
as datas nãi ficam em sequencia
vem aparecendo na ordem correta do dia 25/03/2019 ate 30/08/2019
depois vem uma do dia 20/02/2019 depois volta a ordem apartir do dia 30/08/2019
e tmb não ficam agrupádas pelo status das OS

em resumo a ordem ali e feita por qual das informações ?
e possivel escolher se a listagem vai agrupar na ordem o numero das OS, Nome dos Clientes, data de entrada, status das OS?
![Screenshot_30](https://user-images.githubusercontent.com/1253576/82739960-ae778380-9d1a-11ea-8492-c852ed1046a5.png)

Veja como esa apresentado, nenhum dos campos fica agrupado em ordem

**Comment by Pr3d4dor** [comment]
Não tem nenhuma ordem específica, na query não foi colocado nenhum `ORDER_BY`.

**Comment by hoshikawakun** [comment]
> Não tem nenhuma ordem específica, na query não foi colocado nenhum `ORDER_BY`.

Em que parte do código que eu coloco e como ficaria por exemplo pra ordenar pela data das os, mais antigas primeiro

**Comment by hoshikawakun** [comment]
Que se no geral ela saísse na ordem dos mais antigos primeiro ajudaria muito quando pra todo mundo, e em qual arquivo devo mecher para poder organizar

**Comment by Pr3d4dor** [comment]
Basta você ir no `application/models/Relatorios_model.php` na função `osRapid` e antes do returno adicionar a linha `$this->db->order_by('os.idOs', 'DESC');` ou `$this->db->order_by('os.dataInicial', 'DESC');`.

A mesma coisa vale para outros relatórios.

**Comment by hoshikawakun** [comment]
Muito obrigado por organizar dessa maneira, alterei aki o comando com "climb" e esta aparecendo em ordem certinha agora da mais antiga pra mais nova sem nenhuma data fora
