### ISSUE TITLE
Criação de campo de valor total nos relatórios de O.S

### ISSUE THREAD

**Issue by Triaca** [RamonSilva20/mapos#779]
Acredito que seria uma ótima ideia criar ao fim do relatório de O.S o valor total dos serviços.
Hoje os valores são unitários e não possui um campo com a soma.
![Screenshot_1](https://user-images.githubusercontent.com/21310068/82744015-15a82e80-9d41-11ea-9aea-da880f6c8082.png)

**Comment by heraf250** [comment]
Olá realmente seria bom, não deve ser dificil a implementação.
