### ISSUE TITLE
CORES DA AREA DE IMPRESSAO

### ISSUE THREAD

**Issue by cleytonasa** [RamonSilva20/mapos#78]
![image](https://user-images.githubusercontent.com/27841859/32203403-3fde85cc-bdca-11e7-9ae4-f6aaf997cfb0.png)

gostaria de saber porque fica assim, quando pedimos para imprimir!!

**Comment by drelldeveloper** [comment]
Bom, eu não sei exatamente o porque, mas vamos tentar. Ali encima está dizendo que você precisa configurar algum. Tente, e me diga o que acontece.

**Comment by julianopp** [comment]
Apague a 11 linha do imprimirOS.php

"<link rel="stylesheet" href="<?php echo base_url();?>assets/css/matrix-media.css" />"
