### ISSUE TITLE
Erro na atualização automática para Versão 4.8.1

### ISSUE THREAD

**Issue by TK2KMG** [RamonSilva20/mapos#780]
Após clicar no em Configurações -> Sistema -> Atualizar Mapos. Sistema aprece uma tela informando que o Sistema não pode ser reinstalado novamente.
Após isso o sistema não volta mais a funcionar, ficando em loop informando que não pode ser reinstalado.
Navegador utilizado Google Chrome Versão 81.0.4044.129 (Versão oficial) 64 bits.

Etapas para reproduzir o comportamento:

1. Vá para '. Configurações..'
2. Clique em '..Sistema..'
3.  '. Atualizar Mapos...'

**Comment by willph** [comment]
Alterar linha 59 do arquivo index.php na pasta raiz do mapos 

```//set the environment to production after installation
define('ENVIRONMENT', 'production');```

Colocando `production`  no lugar do que estiver escrito nesta linha.

**Comment by TK2KMG** [comment]
Perfeito Wiliph, funcionou . 

Obrigado pela contribuição !
