### ISSUE TITLE
Erro ao tentar instalar o composer

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#781]
Bom dia a Todos.
Fiz uma nova instalacao antes de atualizar o sistema e quando tentei instalar o composer aparece esse erro. ERROREXCEPTION "Continue" targeting swtich is equivalent to "break". Did you mean to use "continue 2"?

**Comment by Pr3d4dor** [comment]
Isso não é um problema do mapos, e sim um problema no seu composer. Tente rodar o comando `composer selfupdate`
