### ISSUE TITLE
Erro genérico ao adicionar serviços ou produtos nas O.S. V: 4.8.1

### ISSUE THREAD

**Issue by neofln** [RamonSilva20/mapos#782]
Ao adicionar produtos ou serviços na OS aparece um erro genérico:
"Ocorreu um erro ao tentar adicionar produto/serviço."

![2020-05-25 17_33_11-Greenshot](https://user-images.githubusercontent.com/61734888/82841999-6be6b000-9eae-11ea-81b2-76b95105d360.png)

 - SO: [windows 7]
 - Navegador [chrome]
 - Versão [80.0.3987.132]
 - Versão Map-OS 4.8.1

**Comment by Pr3d4dor** [comment]
Atualize manualmente o sistema ao invés de usar o atualizador.

**Comment by neofln** [comment]
Resolvido da forma sugerida.
