### ISSUE TITLE
erro impressora térmica 

### ISSUE THREAD

**Issue by 1rks** [RamonSilva20/mapos#784]
Na Hora que mando imprimir em impressora não fiscal, não aparece a garantia,descrição,defeito, e observações.

**Comment by Pr3d4dor** [comment]
Esses campos não aparecem mesmo.

**Comment by 1rks** [comment]
> Esses campos não aparecem mesmo.

Pensei que sim, pois no código fonte tinha ai achei que erra erro no meu, mas porque foi tirado esse itens? tem como eu voltar eles ?

**Comment by 1rks** [comment]
> > Esses campos não aparecem mesmo.
> 
> Pensei que sim, pois no código fonte tinha ai achei que erra erro no meu, mas porque foi tirado esse itens? tem como eu voltar eles ?

o Google traduz oque escrevo ai fica tudo errado kkk.
