### ISSUE TITLE
Erro de login no banco de dados em site de hospedagem na internet.

### ISSUE THREAD

**Issue by borgesjsb** [RamonSilva20/mapos#786]
Esse é um conteúdo explicativo quanto a dificuldade que eu encontrei e resolvi para a configuração de banco de dados que caracteriza na "busca não encontrada do banco de dados dentro de um site de hospedagem. 

Após fazer um banco de dados dentro do gerador de mysql do seu site de hospedagem, alguns sites de hospedagem colocam prefixo no banco de dados. O prefixo é sua assinatura no site da hospedagem. 

Caminho na hospedagem Hostinger.com.br
Banco de dados
Banco de dados MySql
                        Nome da base de dados MySQL:     u723080811_ (seu numero de usuario prefixo)
                                             (aqui voce digita o nome do banco: mapos)
                        username MySQL: u723080811_ 
                                             (aqui voce digita o nome de login: mapos)
                         senha           (aqui voce digita a senha do banco: mapos)

Entre no mysql editor e importe o banco de dados. Até aí não tem segredo. 

Não é recomendado deixar root e senha em branco como quando se é feito via xamp

***** FAZER A LIGAÇÃO COM O BANCO DE DADOS

Configuração do database.php para funcionar em Banco de dados Hospedados na Internet

É preciso editar este arquivo a seguir.

domains/seudominio.com.br/public_html/mapos/application/config/database.php

Nota: base httpdocs subida na pasta publica /mapos

Alguns sites de hospedagem colocam prefixo no banco de dados. 
Configure o database para acesso. Faça um banco de dados chamado mapos. O prefixo é sua assinatura no site da hospedagem. Vai ficar assim

 'username' => 'u723080811_mapos',    ******usuariodohost+mapos para o username
    'password' => 'mapos',
    'database' => 'u723080811_mapos',   ******usuariodohost+mapos para a database

Aponte o hostname para a base do site que tem o MYSQL ou seja é lá no host que esse caminho deve apontar, cada site de hospedagem tem o seu.
Exemplo    'hostname' => 'mysql.hostinger.com.br',

Conteúdo do arquivo database.php

<?php
defined('BASEPATH') or exit('No direct script access allowed');

$active_group = 'default';
$query_builder = true;

$db['default'] = array(
    'dsn'   => '',
    **'hostname' => 'mysql.hostinger.com.br',**
    **'username' => 'u723080811_mapos',**
    'password' => 'mapos',
    **'database' => 'u723080811_mapos',**
    'dbdriver' => 'mysqli',
    'dbprefix' => '',    // esse prefixo não deve ser usado
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,

Qq coisa estou à disposição.

**Comment by Pr3d4dor** [comment]
Obrigado, vou fechar a issue porque não é realmente um problema, mas um informativo como vc mesmo disse.
