### ISSUE TITLE
Erro na produção de relatório - Leitura de PDF 

### ISSUE THREAD

**Issue by borgesjsb** [RamonSilva20/mapos#787]
https://meusite.com.br/mapos/index.php/relatorios/vendasRapid

** Descreva o bug **
Não abre o PDF 

**Reproduzir**
Etapas para reproduzir o comportamento:
1.Crie um usuario, crie um produto, faça um orçamento, efetue uma venda
2. menu Relatorio
3. submenu vendas
4. ver todos 

**Comportamento esperado**
um relatorio com pdf

*
** Contexto adicional **
Falha ao carregar o documento PDF.

**Comment by Pr3d4dor** [comment]
Pode dar mais detalhes e colar o log de erro?
