### ISSUE TITLE
Instalação.

### ISSUE THREAD

**Issue by Onilba** [RamonSilva20/mapos#788]
Jovens, bom dia.

Estou tentando instalar essa aplicação agora, inclusive por ter experiencia bastante com OS, garantias, gostaria se possivel ajudar nos processo.

Porem não estou conseguindo instalar, tenho MYSQL 8, PHP 7 e ao clicar em avançar me é apresentado o seguinte erro:
The server requested authentication method unknown to the client

Alguem pode me ajudar?

**Comment by Pr3d4dor** [comment]
Provavelmente o problema é o MySQL 8, tente usar o MySQL 5.7 ou pesquise em como configurar o MySQL 8 para usar a autenticação mais antiga.

**Comment by Andrefiel** [comment]
Por favor alguém sabe como instalar em hospedagem? sempre que tento instalar a versão nova acontece esse erro "Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada."

**Comment by Pr3d4dor** [comment]
Basta você resolver exatamente o problema que está escrito na mensagem, você não executou todos os passos da instalação, leia bem o README. Faltou instalar as dependências com o composer.

**Comment by Andrefiel** [comment]
Desculpa mais nao tem como chamar o composer na hospedagem cloud sem ser vps, queria instalar no hostgator da vida

**Comment by Pr3d4dor** [comment]
O que você pode fazer é instalar o composer localmente e rodar o comando `composer install` no seu computador e após isso enviar os arquivos da pasta `application/vendor` via FTP para a hospedagem.

**Comment by Onilba** [comment]
Essa solução é muito interessante, no meu caso o problema é um ero na instalação do composer:Docker Desktop requires Windows 10 Pro/Enterprise (15063+) or Windows 10 Home (19018+).

    Em sábado, 30 de maio de 2020 18:21:41 BRT, Gianluca Bine <notifications@github.com> escreveu:  
 
 


O que você pode fazer é instalar o composer localmente e rodar o comando composer install no seu computador e após isso enviar os arquivos da pasta application/vendor via FTP para a hospedagem.

**Comment by Pr3d4dor** [comment]
Esse erro `Docker Desktop requires Windows 10 Pro/Enterprise` é um erro que não tem relação com o composer. Você não precisa instalar o docker pra usar o mapos localmente.

Ou você faz a instalação manual usando xamp ou outro servidor ou você utiliza o docker que realiza a mesma coisa.

Sobre o erro de instalação no composer basta você baixar o instalador oficial no site e executar.

**Comment by Onilba** [comment]
sem querer abusar muito, mas nao consigo instalar na minha maquina nem tenho acesso a ssh no servidor, tem como disponibilizar esses arquivos não.
Lino Almeida
    Em sábado, 30 de maio de 2020 18:21:41 BRT, Gianluca Bine <notifications@github.com> escreveu:  
 
 


O que você pode fazer é instalar o composer localmente e rodar o comando composer install no seu computador e após isso enviar os arquivos da pasta application/vendor via FTP para a hospedagem.

**Comment by Pr3d4dor** [comment]
Nesse link tem a pasta vendor que vc pode fezer upload para o servidor: https://github.com/TecSecret/TSOS/tree/master/application

**Comment by Onilba** [comment]
Ola.
bem, antes tava assim:Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

depois que copiei a pasta vendor esta assim:
Esta página não está funcionando

valnautica.com.br não consegue atender a esta solicitação no momento.
HTTP ERROR 500
    Em sábado, 30 de maio de 2020 20:51:02 BRT, Gianluca Bine <notifications@github.com> escreveu:  
 
 


Nesse link tem a pasta vendor que vc pode fezer upload para o servidor: https://github.com/TecSecret/TSOS/tree/master/application

**Comment by Andrefiel** [comment]
> O que você pode fazer é instalar o composer localmente e rodar o comando `composer install` no seu computador e após isso enviar os arquivos da pasta `application/vendor` via FTP para a hospedagem.

Fiz esse passo realmente apareceu tela para login e senha mais quando coloco os dados ele nao passa para tela do sistema

**Comment by Onilba** [comment]
No meu caso não aparece nada.
Lino

Enviado do Yahoo Mail no Android 
 
  <div>Em sáb, 30 30e mai 30e 2020 às 23:32, Andrefiel</div><div><notifications@github.com> escreveu:</div>   



O que você pode fazer é instalar o composer localmente e rodar o comando composer install no seu computador e após isso enviar os arquivos da pasta application/vendor via FTP para a hospedagem.


Fiz esse passo realmente apareceu tela para login e senha mais quando coloco os dados ele nao passa para tela do sistema

**Comment by brtechst** [comment]
Aconteceu comigo também esse erro.

É só ir lá nas configurações do PHP e selecionar a versão 7.0 que ele vai rodar.

**Comment by Onilba** [comment]
Infelizmente comigo nao deu crto. estou pensando em migrar para hostinger, vale a pena???
Lino
    Em segunda-feira, 1 de junho de 2020 10:08:43 BRT, brtechst <notifications@github.com> escreveu:  
 
 


Aconteceu comigo também esse erro.

É só ir lá nas configurações do PHP e selecionar a versão 7.0 que ele vai rodar.

**Comment by Andrefiel** [comment]
> Aconteceu comigo também esse erro.
> 
> É só ir lá nas configurações do PHP e selecionar a versão 7.0 que ele vai rodar.

comigo ja foi ao contrario fiz duas alterações a mesma em dois sites e outra somente em uma uma delas e trocar a versao do PHP para 5.6 a outra que eu fiz nos dois sites foi mudar uma linha na configuração da base da dados

application\config\database.php ai você muda essa linna 'stricton' = para TRUE

**Comment by LucasPolli** [comment]
tenho instalado em hostgator, precisei solicitar ao suporte mudar o php do subdomínio para 7.2 para poder rodar o composer, nao consegui fazer via Cpanel, levou 2 dias pra eles atualizarem

**Comment by thiagoferreira14** [comment]
> Desculpa mais nao tem como chamar o composer na hospedagem cloud sem ser vps, queria instalar no hostgator da vida

Da para chamar sim 
Segue tutorial para instalar o composer  no hostgator
https://suporte.hostgator.com.br/hc/pt-br/articles/115004145214-Como-instalar-o-Laravel-#composer

**Comment by gilbertoalmeida16** [comment]
Amigo me chama que te ajudo a instalar. apanhei mais consegui depois de ter inumeros erros.
gilbertoalmeida16@gmail.com

**Comment by tvonline672** [comment]
Olá se ainda estiver com problemas entra em contato comigo tenho o Mapos aqui atualizado e pronto pra instalação sem erro Whats: 87991202231 Chama lá que te mando o arquivo já pronto pra você iniciar o Instalador do Mapos.

**Comment by gilbertoalmeida16** [comment]
Pode mandar por aqui!

Em ter, 13 de jul de 2021 01:49, Erick Matheus Alves Campos Campos <
***@***.***> escreveu:
