### ISSUE TITLE
Parcelamento

### ISSUE THREAD

**Issue by drwdos** [RamonSilva20/mapos#79]
Poderia ter em faturar, opção para colocar se é parcelado, boleto, cartão etc. quantas vezes, as datas de vencimentos

**Comment by drwdos** [comment]
também na impressão de orçamentos, poderia acrescentar campo de assinatura que o cliente está deixando o equipamento, no caso para ordem de serviço em assistências técnicas. em que o cliente fica ciente que entregou o equipamento em tal estado de conservações ou com os detalhes descritos.

**Comment by drelldeveloper** [comment]
Concordo. Eu vou adicionar o seu pedido á observações, espero que o Ramon, concorde também ;)
