### ISSUE TITLE
erro ao salvar cadastro de clientes

### ISSUE THREAD

**Issue by softcia** [RamonSilva20/mapos#790]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.
![erro_cad_cli](https://user-images.githubusercontent.com/15114014/83319232-ea2ab580-a212-11ea-9ae9-5b82d8bc8f58.png)

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
Whoops\Exception\ErrorException thrown with message "idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated"

Stacktrace:
#6 Whoops\Exception\ErrorException in /home2/softc539/public_html/bellponto/application/vendor/codeigniter/framework/system/libraries/Form_validation.php:1243
#5 idn_to_ascii in /home2/softc539/public_html/bellponto/application/vendor/codeigniter/framework/system/libraries/Form_validation.php:1243
#4 CI_Form_validation:valid_email in /home2/softc539/public_html/bellponto/application/vendor/codeigniter/framework/system/libraries/Form_validation.php:775
#3 CI_Form_validation:_execute in /home2/softc539/public_html/bellponto/application/vendor/codeigniter/framework/system/libraries/Form_validation.php:478
#2 CI_Form_validation:run in /home2/softc539/public_html/bellponto/application/controllers/Clientes.php:56
#1 Clientes:adicionar in /home2/softc539/public_html/bellponto/application/vendor/codeigniter/framework/system/core/CodeIgniter.php:532
#0 require_once in /home2/softc539/public_html/bellponto/index.php:306

**Comment by Pr3d4dor** [comment]
Qual banco de dados vc está utilizando?

**Comment by Pr3d4dor** [comment]
Ao que parece esse erro é por causa da versão do PHP, tente atualizar para a versão 7.4.

**Comment by microreis** [comment]
![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)


Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.

**Comment by Pr3d4dor** [comment]
@microreis Qual a versão do MySQL, PHP que você está usando?

**Comment by microreis** [comment]
@Pr3d4dor Não tem nada haver com relação as versões, encontrei o erro e já foi corrigido.
O banco de dados não estava sendo migrando corretamente, mantendo a verão antiga e atualizando manualmente corrigiu o erro.

**Comment by glbservicos** [comment]
> ![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)
> 
> Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.

tem como postar passo a passo o que vc fez? estou com o mesmo problema

**Comment by willph** [comment]
> > ![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)
> > Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.
> 
> tem como postar passo a passo o que vc fez? estou com o mesmo problema

A atualização de banco de dados fica na pasta UPDATES. 


O seu é atualização?

**Comment by glbservicos** [comment]
> > > ![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)
> > > Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.
> > 
> > 
> > tem como postar passo a passo o que vc fez? estou com o mesmo problema
> 
> A atualização de banco de dados fica na pasta UPDATES.
> 
> O seu é atualização?

consegui direto pelo sistema na opção ( CONFIGURAÇÕES / SISTEMA/ATUALIZAÇÕES E EM SEGUIDA ATUALIZAR BANCO DE DADOS.....DEU CERTO!!!!!   agradeço

**Comment by willph** [comment]
> > > > ![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)
> > > > Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.
> > > 
> > > 
> > > tem como postar passo a passo o que vc fez? estou com o mesmo problema
> > 
> > 
> > A atualização de banco de dados fica na pasta UPDATES.
> > O seu é atualização?
> 
> consegui direto pelo sistema na opção ( CONFIGURAÇÕES / SISTEMA/ATUALIZAÇÕES E EM SEGUIDA ATUALIZAR BANCO DE DADOS.....DEU CERTO!!!!! agradeço

Pensei que já tinha usado está opção, por isso não sugerir 😁

**Comment by glbservicos** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/23633030/85412228-befc6300-b53f-11ea-9084-5c4d090a61d6.png)
> > > > > Toda a vez que vai fazer um cadastro somente da essa mensagem, mesmo todos os campos preenchidos corretamente. e não realiza o cadastro.
> > > > 
> > > > 
> > > > tem como postar passo a passo o que vc fez? estou com o mesmo problema
> > > 
> > > 
> > > A atualização de banco de dados fica na pasta UPDATES.
> > > O seu é atualização?
> > 
> > 
> > consegui direto pelo sistema na opção ( CONFIGURAÇÕES / SISTEMA/ATUALIZAÇÕES E EM SEGUIDA ATUALIZAR BANCO DE DADOS.....DEU CERTO!!!!! agradeço
> 
> Pensei que já tinha usado está opção, por isso não sugerir 😁

valeu!!!!
