### ISSUE TITLE
ERRO ao instalar o MAPOS na hospedagem web.

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#791]
Olá pessoal, eu ja tinha instalado na minha máquina local, só que precisei formatar minha máquina e achei mais prudente colocar online meu sistema. Inicialmente vou colocar na gratuita para testar (000webhost), mas dando certo faço upgrade.

Estou tendo o seguinte erro e não sei mais o que fazer.

Se alguém quiser acessar minha máquina eu disponibilizo para ver se consegue.

![image](https://user-images.githubusercontent.com/53625745/83338158-db3a1680-a297-11ea-843f-5fce294c1ba3.png)

**Comment by brtechst** [comment]
OBS: Eu tenho backup salvo, adicionei ele lá no banco de dados (configurei a senha, usuário, etc) mas mesmo assim está dando esse erro.

**Comment by Pr3d4dor** [comment]
Isso não é erro do mapos, a conexão com o banco de dados não está funcionando, verifique usuário e senha em `config/database.php`

**Comment by brtechst** [comment]
Vou verificar aquiEm hostname coloco "localhost"?

**Comment by Pr3d4dor** [comment]
Não porque a hospedagem não vai conseguir acessar o seu banco de dados local, você precisará hospedar um banco também.

**Comment by brtechst** [comment]
Conseguir fazer o sistema rodar na web como o amigo falou, só surgiu mais um problema, agora quando coloco usuário e senha ele fica processando e não entra! Será o PHP?

Está marcado a versão 7.2.

![image](https://user-images.githubusercontent.com/53625745/83355511-433f3a00-a336-11ea-81df-2fe9e42d3245.png)

**Comment by brtechst** [comment]
Resolvido, problema era o PHP mesmo. Voltei para versão 7.0 e foi.
