### ISSUE TITLE
Erro ao cliente tentar fazer download do anexo da OS

### ISSUE THREAD

**Issue by rafaerigson** [RamonSilva20/mapos#793]
Com versão 4.8.2 quando o cliente entra na sua área, não consegue fazer download do arquivo,  quando clica em download a pagina é direcionada para a pagina de login do administrador, alguém com o mesmo problema que possa me dar uma luz? 
E isso ja vem acontecendo nas outras versões anteriores, mas talvez seja alguma erro nas minha configurações pq não encontrei ninguém com esse mesmo problema.
Nas observações em modo desenvolvedor no chrome recebo esse erro.

Request URL: http://31.220.50.89/suporte/index.php/os/downloadanexo/2
Request Method: GET
Status Code: 307 Temporary Redirect
Remote Address: 31.220.50.89:80
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sun, 31 May 2020 21:14:54 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Location: http://31.220.50.89/suporte/index.php/login
Pragma: no-cache
Server: Apache/2.4.29 (Ubuntu)
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Cookie: app_session=jev8hj7t2a1l2ptdbkvafdmjef2qc9gf
Host: 31.220.50.89
Referer: http://31.220.50.89/suporte/index.php/mine/detalhesOs/1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

Parece que ele não salva a sessão e não loga, eu não entendi, se alguém puder me orientar, eu agradeço.

**Comment by cabralwms** [comment]
Para mim tambem acontece a mesma coisa volta para login.

**Comment by allanalcantara** [comment]
da para alterar a formula onde é se pega o formulário para download.
preciso do código fonte da tela onde o mesmo acessou

**Comment by Pr3d4dor** [comment]
Iremos verificar.

**Comment by rafaerigson** [comment]
> 
> 
> da para alterar a formula onde é se pega o formulário para download.
> preciso do código fonte da tela onde o mesmo acessou

<!DOCTYPE html> <html lang="pt-br"> <head> <title>Área do Cliente - Map-OS</title> <meta charset="UTF-8"/> <meta name="viewport" content="width=device-width, initial-scale=1.0"/> <meta name="description" content="Map-OS - Sistema de Controle de Ordens de Serviço"> <link rel="shortcut icon" type="image/png" href="http://31.220.50.89/suporte/assets/img/favicon.png"/> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/css/bootstrap.min.css"/> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/css/bootstrap-responsive.min.css"/> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/css/matrix-style.css"/> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/css/matrix-media.css"/> <link href="http://31.220.50.89/suporte/assets/font-awesome/css/font-awesome.css" rel="stylesheet"/> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/css/fullcalendar.css"/> <link href="http://31.220.50.89/suporte/assets/css/bootstrap-responsive.min.css" rel="stylesheet"> <script type="text/javascript" src="http://31.220.50.89/suporte/assets/js/jquery-1.12.4.min.js"></script> <link rel="shortcut icon" href="http://31.220.50.89/suporte/assets/img/fav.png"> </head> <body>  <div id="header"> <h1><a href="dashboard.html"> Map-OS</a></h1> </div>   <div id="user-nav" class="navbar navbar-inverse"> <ul class="nav"> <li class=""><a title="" href="http://31.220.50.89/suporte/index.php/mine/conta"><i class="icon fas fa-user"></i> <span class="text"> Minha Conta</span></a></li> <li class=""><a title="" href="http://31.220.50.89/suporte/index.php/mine/sair"><i class="icon fas fa-sign-out-alt"></i> <span class="text"> Sair</span></a></li> </ul> </div> <div id="sidebar"><a href="#" class="visible-phone"><i class="icon fas fa-bars"></i> Menu</a> <ul> <li class=""><a href="http://31.220.50.89/suporte/index.php/mine/painel"><i class="icon fas fa-home"></i> <span>Painel</span></a></li> <li class=""><a href="http://31.220.50.89/suporte/index.php/mine/conta"><i class="icon fas fa-user"></i> <span>Minha Conta</span></a></li> <li class=""><a href="http://31.220.50.89/suporte/index.php/mine/os"><i class="icon fas fa-diagnoses"></i> <span>Ordens de Serviço</span></a></li> <li class=""><a href="http://31.220.50.89/suporte/index.php/mine/compras"><i class="icon fas fa-shopping-cart"></i> <span>Compras</span></a></li> <li class=""><a href="http://31.220.50.89/suporte/index.php/mine/sair"><i class="icon fas fa-sign-out-alt"></i> <span>Sair</span></a></li> </ul> </div> <div id="content"> <div id="content-header"> <div id="breadcrumb"><a href="http://31.220.50.89/suporte/index.php/mine/painel" title="Painel" class="tip-bottom"><i class="fas fa-home"></i> Painel</a></div> </div> <div class="container-fluid"> <div class="row-fluid"> <div class="span12"> <link rel="stylesheet" href="http://31.220.50.89/suporte/assets/trumbowyg/ui/trumbowyg.css"> <script type="text/javascript" src="http://31.220.50.89/suporte/assets/trumbowyg/trumbowyg.js"></script> <script type="text/javascript" src="http://31.220.50.89/suporte/assets/trumbowyg/langs/pt_br.js"></script> <style> .ui-datepicker { z-index: 9999 !important; } .trumbowyg-box { margin-top: 0; margin-bottom: 0; } </style> <div class="row-fluid" style="margin-top:0"> <div class="span12"> <div class="widget-box"> <div class="widget-title"> <span class="icon"> <i class="fas fa-diagnoses"></i> </span> <h5>Detalhes OS</h5> </div> <div class="widget-content nopadding"> <div class="span12" id="divProdutosServicos" style=" margin-left: 0"> <ul class="nav nav-tabs"> <li class="active" id="tabDetalhes"><a href="#tab1" data-toggle="tab">Detalhes da OS</a></li> <li id="tabProdutos"><a href="#tab2" data-toggle="tab">Produtos</a></li> <li id="tabServicos"><a href="#tab3" data-toggle="tab">Serviços</a></li> <li id="tabAnexos"><a href="#tab4" data-toggle="tab">Anexos</a></li> </ul> <div class="tab-content"> <div class="tab-pane active" id="tab1"> <div class="span12" id="divCadastrarOs"> <div class="span12" style="padding: 1%; margin-left: 0"> <div class="span6" style="margin-left: 0"> <h3>#Protocolo: 1 </h3> <input id="valorTotal" type="hidden" name="valorTotal" value="" /> </div> <div class="span6"> <label for="tecnico">Técnico / Responsável</label> <input disabled="disabled" id="tecnico" class="span12" type="text" name="tecnico" value="admin" /> </div> </div> <div class="span12" style="padding: 1%; margin-left: 0"> <div class="span3"> <label for="status">Status<span class="required"></span></label> <input disabled="disabled" type="text" name="status" id="status" value="Finalizado"> </div> <div class="span3"> <label for="dataInicial">Data Inicial<span class="required">*</span></label> <input id="dataInicial" disabled="disabled" class="span12 datepicker" type="text" name="dataInicial" value="29/05/2020" /> </div> <div class="span3"> <label for="dataFinal">Data Final</label> <input id="dataFinal" disabled="disabled" class="span12 datepicker" type="text" name="dataFinal" value="04/06/2020" /> </div> <div class="span3"> <label for="garantia">Garantia</label> <input id="garantia" disabled="disabled" type="text" class="span12" name="garantia" value="" /> </div> </div> <div class="span12" style="padding: 1%; margin-left: 0"> <label for="descricaoProduto">Descrição Produto/Serviço</label> <textarea class="span12 editor" name="descricaoProduto" id="descricaoProduto" cols="30" rows="5" disabled>TESTE</textarea> </div> <div class="span12" style="padding: 1%; margin-left: 0"> <label for="defeito">Defeito</label> <textarea class="span12 editor" name="defeito" id="defeito" cols="30" rows="5" disabled></textarea> </div> <div class="span12" style="padding: 1%; margin-left: 0"> <label for="observacoes">Observações</label> <textarea class="span12 editor" name="observacoes" id="observacoes" cols="30" rows="5" disabled></textarea> </div> <div class="span12" style="padding: 1%; margin-left: 0"> <label for="laudoTecnico">Laudo Técnico</label> <textarea class="span12 editor" name="laudoTecnico" id="laudoTecnico" cols="30" rows="5" disabled></textarea> </div> </div> </div>  <div class="tab-pane" id="tab2"> <div class="span12" id="divProdutos" style="margin-left: 0"> <table class="table table-bordered" id="tblProdutos"> <thead> <tr> <th>Produto</th> <th>Quantidade</th> <th>Sub-total</th> </tr> </thead> <tbody> <tr> <td colspan="2" style="text-align: right"><strong>Total:</strong></td> <td><strong>R$ 0,00<input type="hidden" id="total-venda" value="0.00"></strong></td> </tr> </tbody> </table> </div> </div>  <div class="tab-pane" id="tab3"> <div class="span12" style="padding: 1%; margin-left: 0"> <div class="span12" id="divServicos" style="margin-left: 0"> <table class="table table-bordered"> <thead> <tr> <th>Serviço</th> <th>Sub-total</th> </tr> </thead> <tbody> <tr> <td colspan="1" style="text-align: right"><strong>Total:</strong></td> <td><strong>R$ 0,00<input type="hidden" id="total-servico" value="0.00"></strong></td> </tr> </tbody> </table> </div> </div> </div>  <div class="tab-pane" id="tab4"> <div class="span12" style="padding: 1%; margin-left: 0"> <div class="span12" id="divAnexos" style="margin-left: 0"> <div class="span3" style="min-height: 150px; margin-left: 0"><a style="min-height: 150px;" href="#modal-anexo" imagem="2" link="http://31.220.50.89/suporte/assets/img/icon-file.png" role="button" class="btn anexo span12" data-toggle="modal"><img src="http://31.220.50.89/suporte/assets/img/icon-file.png" alt=""></a></div> </div> </div> </div> </div> </div> . </div> </div> </div> </div>  <div id="modal-anexo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> <h3 id="myModalLabel">Visualizar Anexo</h3> </div> <div class="modal-body"> <div class="span12" id="div-visualizar-anexo" style="text-align: center"> <div class='progress progress-info progress-striped active'> <div class='bar' style='width: 100%'></div> </div> </div> </div> <div class="modal-footer"> <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button> <a href="" id-imagem="" class="btn btn-inverse" id="download">Download</a> </div> </div>  <div id="modal-faturar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> <form id="formFaturar" action="http://31.220.50.89/suporte/index.php/mine/detalhesOs/1" method="post"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> <h3 id="myModalLabel">Faturar Venda</h3> </div> <div class="modal-body"> <div class="span12 alert alert-info" style="margin-left: 0"> Obrigatório o preenchimento dos campos com asterisco.</div> <div class="span12" style="margin-left: 0"> <label for="descricao">Descrição</label> <input class="span12" id="descricao" type="text" name="descricao" value="Fatura de Venda - #1 " /> </div> <div class="span12" style="margin-left: 0"> <div class="span12" style="margin-left: 0"> <label for="cliente">Cliente*</label> <input class="span12" id="cliente" type="text" name="cliente" value="RAFAEL ERIGSON" /> <input type="hidden" name="clientes_id" id="clientes_id" value="1"> <input type="hidden" name="os_id" id="os_id" value="1"> </div> </div> <div class="span12" style="margin-left: 0"> <div class="span4" style="margin-left: 0"> <label for="valor">Valor*</label> <input type="hidden" id="tipo" name="tipo" value="receita" /> <input class="span12 money" id="valor" type="text" name="valor" value="0.00 " /> </div> <div class="span4"> <label for="vencimento">Data Vencimento*</label> <input class="span12 datepicker" id="vencimento" type="text" name="vencimento" /> </div> </div> <div class="span12" style="margin-left: 0"> <div class="span4" style="margin-left: 0"> <label for="recebido">Recebido?</label> &nbsp &nbsp &nbsp &nbsp <input id="recebido" type="checkbox" name="recebido" value="1" /> </div> <div id="divRecebimento" class="span8" style=" display: none"> <div class="span6"> <label for="recebimento">Data Recebimento</label> <input class="span12 datepicker" id="recebimento" type="text" name="recebimento" /> </div> <div class="span6"> <label for="formaPgto">Forma Pgto</label> <select name="formaPgto" id="formaPgto" class="span12"> <option value="Dinheiro">Dinheiro</option> <option value="Cartão de Crédito">Cartão de Crédito</option> <option value="Cheque">Cheque</option> <option value="Boleto">Boleto</option> <option value="Depósito">Depósito</option> <option value="Débito">Débito</option> </select> </div> </div> </div> </div> <div class="modal-footer"> <button class="btn" data-dismiss="modal" aria-hidden="true" id="btn-cancelar-faturar">Cancelar</button> <button class="btn btn-primary">Faturar</button> </div> </form> </div> <script type="text/javascript">
    $(document).ready(function() {
        $('.editor').trumbowyg({
            lang: 'pt_br'
        });
    });

    $(document).on('click', '.anexo', function(event) {
        event.preventDefault();
        var link = $(this).attr('link');
        var id = $(this).attr('imagem');
        $("#div-visualizar-anexo").html('<img src="' + link + '" alt="">');
        $("#download").attr('href', "http://31.220.50.89/suporte/index.php/os/downloadanexo/" + id);
    });
</script> </div> </div> </div> </div>  <div class="row-fluid"> <div id="footer" class="span12"> 2020 &copy; Map-OS - Versão: 4.8.2 </div> </div>  <script src="http://31.220.50.89/suporte/assets/js/bootstrap.min.js"></script> </body> </html>

**Comment by rafaerigson** [comment]
Alguém conseguiu ?

**Comment by Pr3d4dor** [comment]
Boa tarde, desculpa a demora mas realizei a correção do problema em: #813.

Basta esperar o review, merge e a nova versão do mapos 4.8.3.
