### ISSUE TITLE
Automatizar envio para o Whatsapp cadastrado?

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#794]
Gostaria de saber se é possível automatizar o envio da mesma forma que é feito para o e-mail se seria possível para automatizar para o WhatsApp dos clientes toda vez que houver uma modificação da OS.

Porque ai não precisaríamos nos preocupar de lembrar e sempre que o cliente recebesse a atualização ele iria lá e olhava.

**Comment by Pr3d4dor** [comment]
Somente usando a API paga do whatsapp ou alguma API de terceiros.
