### ISSUE TITLE
colocar hora nas OS - 

### ISSUE THREAD

**Issue by fabianofvd** [RamonSilva20/mapos#795]
Ola, mais uma vez parabéns pelo trabalho de vc's.

eu estou querendo colocar horário nas OS, tanto na abertura quanto no fechamento, tentei colocar o tadatime  no BD e mudei o arquivos de adicionar os mudando a forma de cadastrar o formato da data, porem meus conhecimentos ainda estão pequenos para me virar sozinho, mas por se tratar de OS, e tem gente que cobra por hora, seria legal colocar a hora de abertura e fechamento e um total de horas gastas no tratamento da OS, ainda diria para colocar tipo o horário de atendimento do local para poder somar essas horas quando tem mais de um dia aplicado no trabalho, e com o horário de abertura e fechamento do estabelecimento cadastrado pode se subtrair o tempo que o local fica fechado.

Me perdoe a despretensão de querer opinar no sistema, eu deveria era me virar sozinho :P, mas com toda a humildade faço essa sugestão.

**Comment by Pr3d4dor** [comment]
Boa noite, a implementação dessa funcionalidade iria requerer um número considerável de mudanças, além de alterar o banco.

Assim que tiver um tempo livre eu poderia implementar ou te ajudar caso você tenha feito algo.
