### ISSUE TITLE
Erro ao Adicionar Produtos ou Serviços na OS.

### ISSUE THREAD

**Issue by eduaraujothe** [RamonSilva20/mapos#796]
![image](https://user-images.githubusercontent.com/53988117/83457727-bf6d7680-a437-11ea-9a26-e25b9d95828b.png)

![image](https://user-images.githubusercontent.com/53988117/83457834-d7dd9100-a437-11ea-842b-23771e8990a6.png)

**Comment by Pr3d4dor** [comment]
Atualize o seu mapos manualmente e não pelo atualizador.
