### ISSUE TITLE
Valor variável valor de entrada e de saída de produto na Guia de Vendas

### ISSUE THREAD

**Issue by borgesjsb** [RamonSilva20/mapos#797]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Não consigo fazer um acrescimo ou um desconto na venda de produtos. Como o cadastro tem que por o valor de compra e o de venda, não há um campo para dar um desconto no produto, na hora da venda. 

** Descreva a solução que você deseja **
Dois campos na hora de vender o produto. 
Um com o preço de compra e outro com o preço de venda. 
Sugiro que eles fiquem variáveis naquela venda. Pois nem sempre eu tenho os produtos no estoque e nem sempre pago o mesmo valor para o mesmo produto. 
As vezes eu compro do mercado livre por exemplo, no valor diferente do que eu cadastrei.  

Se tiver um campo para por o valor que eu vendi, mesmo por que para cada negociação sai um preço, seria bem melhor. 

** Descreva as alternativas que você considerou **
Por exemplo: Se eu paguei registrei um produto por 200 reais, e a venda dele é 300, pode ser que eu nao tenha ele no estoque, entao eu vou fazer um pedido dele, pois eu pego os valores num distribuidor, entao eu posso estar fazendo o pedido por um valor maior ou menor, e estar vendendo num valor maior ou menor. diferente do cadastrado. Fazendo a venda ser uma unica e não exclusivamente no mesmo valor do produto cadastrado. 

** Contexto adicional **
Obrigado.

**Comment by Pr3d4dor** [comment]
O que você pode fazer é adicionar um produto/serviço com valor -1.00 no banco e adicionar ele na hora da venda/OS.
