### ISSUE TITLE
Instalação Docker Windows

### ISSUE THREAD

**Issue by gladuriel** [RamonSilva20/mapos#798]
Senhores, estou tendo dificuldades de instalar e executar o Docker no Windows. Minha pergunta é: as versões mais recentes requerem o Docker, ou tem como atualizar apenas usando o composer mesmo? 

Agradeço demais!
Valeuuu

**Comment by Pr3d4dor** [comment]
Você pode usar o docker ou não, o docker funcionaria da mesma forma que o XAMP funciona e você instando manualmente, portanto não é obrigatório, é apenas uma outra forma de usar.
