### ISSUE TITLE
Uma forma mais fácil de faturar.

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#799]
Um botão na lista de os seria perfeito.. :(
quando tem 4 ou 5 os pra faturar tem q entrar uma de cada vez.. se pudesse fazer da lista de os ao invés de entrar em cada um pra faturar seria ótimo.. :) vlww..

**Comment by Pr3d4dor** [comment]
Obrigado, iremos implementar assim que possível.

**Comment by tibjunior** [comment]
Nós que agradecemos pela incrível ajuda que vocês tem nos dado... :D
