### ISSUE TITLE
Impossível excluir permissão.

### ISSUE THREAD

**Issue by phiterf** [RamonSilva20/mapos#8]
Ao tentar excluir uma permissão, a função chamada do controller é `/permissoes/desativar`.

Essa função não existe dentro do controller, e a função excluir existente é copiada do controller de serviços.

```
function excluir(){


        $id =  $this->input->post('id');
        if ($id == null){

            $this->session->set_flashdata('error','Erro ao tentar excluir serviço.');            
            redirect(base_url().'index.php/servicos/gerenciar/');
        }

        $this->db->where('servicos_id', $id);
        $this->db->delete('servicos_os');

        $this->servicos_model->delete('servicos','idServicos',$id);             


        $this->session->set_flashdata('success','Serviço excluido com sucesso!');            
        redirect(base_url().'index.php/servicos/gerenciar/');
    }
```

Acho que seria interessante alterar a função de exclusão a ser implementada para que sempre precise ter pelo menos um tipo de permissão,

ex: Existe só a permissão de administrador, então ao tentar excluir diz que é impossível pois só existe essa.

Também não há opção para excluir usuários do sistema, apenas desativar.

A função de exclusão existe no sistema, porém não é chamada pela view.

Seria bacana aplicar a mesma regra citada acima quando for excluir e só existir um.

**Comment by RamonSilva20** [comment]
Concordo com praticamente tudo que disse, exceto a exclusão de usuários. É importante manter o histórico, se o usuário fosse excluído, seria necessário excluir tudo que está relacionado a ele, levando-se em consideração o projeto e as regras do banco.

**Comment by phiterf** [comment]
É, olhando por esse ponto de vista, apenas desativar o usuário é mais prático mesmo.
