### ISSUE TITLE
Impressão de OS - Chrome

### ISSUE THREAD

**Issue by rafalinpg** [RamonSilva20/mapos#80]
Bom dia,

Gostaria, de uma ajuda, pois não consigo imprimir os a partir do chrome, a tela fica em branco, no mozilla e explorer sai normal, o que pode ser?

**Comment by drelldeveloper** [comment]
Pode ser o seu browser. Me lembro de um contribuidor que reportou isso, ele disse o mesmo sobre o Chrome.

**Comment by drelldeveloper** [comment]
@rafalinpg Eu testei em todos os meus navegadores, não há nada de errado.
