### ISSUE TITLE
Etiquetas

### ISSUE THREAD

**Issue by acinformatica2004** [RamonSilva20/mapos#800]
Boa noite. Ao gerar etiquetas, teria como colocar vários códigos dos produtos para gerar etiquetas só invés de colocar um intervalos.
Se puderem me ajudar ou dar uma dica de como fazer.

Obrigado

** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by maycon1977** [comment]
Olá...
As minhas O.S. eu personalizei de forma que gerem no fim delas 03 números para etiquetas.
Daí, ao imprimir a via do cliente, destaco o canhoto inferior e colo no(s) equipamento(s) e/ou peça(s)

![image](https://user-images.githubusercontent.com/47214174/83698451-d4810b80-a5d7-11ea-9c66-7e6b6663be92.png)

No arquivo "imprimirOs.php" é só acrescentar na posição deseja o código abaixo:

`<table class="table table-condensed">
                                <tbody>
                                <tr>
                                <td style="width: 33%; text-align: center">
                                <strong><span style="font-size: 9px;"> <?php echo $result->idOs?> - <?php echo $result->nomeCliente?></strong></span>
                                </td>
                                <td style="width: 33%; text-align: center">
                                <strong><span style="font-size: 9px;"> <?php echo $result->idOs?> - <?php echo $result->nomeCliente?></strong></span>
                                </td>
                                <td style="width: 33%; text-align: center">
                                <strong><span style="font-size: 9px;"> <?php echo $result->idOs?> - <?php echo $result->nomeCliente?></strong></span>
                                </td>
                                </tr>
                                </tbody>
                                </table>`
