### ISSUE TITLE
Erro na parte de vendas

### ISSUE THREAD

**Issue by tibjunior** [RamonSilva20/mapos#801]
Quando vou realizar uma venda, não carrega os produtos. Já tentei adicionar novos produtos mas não aparecem...

Seria legal poder adicionar na parte de venda.. por exemplo: quando a busca não retornar nada ele abre um pop-up pra adicionar ao invés da mensagem de que não existe.

uma outra coisa que queria sugerir era a opção de trabalhar assinaturas pelo Map-os, um serviço que possuo e ele ter um pagamento mensal pelo sistema (pode ate ser na parte de vendas mesmo.) Dês de já obrigado pela atenção..

**Comment by tibjunior** [comment]
Mais alguém tendo este problema? os produtos não aparecem na parte de vendas.. :(

**Comment by valmors** [comment]
olá, também estou tendo mesmo problema do tibjunior, alguma solução? 
o mesmo acontece na tela  para adicionar receita, não mostra o nome do cliente!! 
alguém sabe como resolver?

**Comment by tibjunior** [comment]
Nada ainda amigo.. ja tentei revisar o código.. mas meu php não é dos melhores, fico meio perdido.. rsrs

**Comment by tibjunior** [comment]
Alguém tem a solução? desisti de tentar reparar.. kkkk ja tentei de tudo q eu achava saber.. rsrs

**Comment by valmors** [comment]
alguém interessado em receber para resolver este problema? estou disposto a pagar pois esta funcionalidade seria muito útil. Se tiver alguém interessado entre em contato.

**Comment by Pr3d4dor** [comment]
Qual é a versão que vocês estão utilizando do mapos?

Podem postar o log de erro do console do navegador após a listagem estar em branco?

**Comment by Pr3d4dor** [comment]
Outra pergunta, na hora de cadastrar o produto vocês estão marcando a opção de produto de saída e o produto está em estoque?

Eu não consegui reproduzir esse erro aqui.

**Comment by tibjunior** [comment]
SHOOOW.. esse era o erro.. me passou despercebido a questão da "Saída".. estamos tão habituados a achar que o erro ta no código que as partes mais simples passam sem perceber... muito obrigado Pr3d4dor... tu é o cara..

**Comment by willph** [comment]
> olá, também estou tendo mesmo problema do tibjunior, alguma solução?
> o mesmo acontece na tela para adicionar receita, não mostra o nome do cliente!!
> alguém sabe como resolver?

Não existe está função em lançamento de receita!

**Comment by valmors** [comment]
Era só marcar mesmo o item para entrara e saída na tela de cadastro. 
Top, sistema OK funcionando.
Obrigado Galera!!
