### ISSUE TITLE
Como ser colaborador ?

### ISSUE THREAD

**Issue by Edivandro** [RamonSilva20/mapos#805]
Como fazer parte da equipe de desenvolvimento ?

**Comment by Pr3d4dor** [comment]
Não precisa fazer nada, basta criar a pull request quando quiser contribuir.

**Comment by Edivandro** [comment]
Como a equipe se organiza ? Existi um projeto ? Objetivo do sotfware ? Como ele vai sendo construido ?
Se alguém poder responder alguma pergunta ?
Gostaria de entender melhor como funciona, vejo que o próprio Git ajuda a organizar o projeto.

**Comment by Edivandro** [comment]
Como a equipe se organiza ? Existi um projeto ? Objetivo do sotfware ? Como ele vai sendo construido ? Lista de taferas/recurso da aplicação a serem feitas ? 

Gostaria de entender melhor como funciona, vejo que o próprio Git ajuda a organizar o projeto.

**Comment by Pr3d4dor** [comment]
Você pode ler o que as outras pessoas comentarem e implementar, o git ajuda nessa organização.

**Comment by Edivandro** [comment]
Blz.
