### ISSUE TITLE
Status de Ordem de Serviço

### ISSUE THREAD

**Issue by 1rks** [RamonSilva20/mapos#807]
Seria muito útil um status de "Garantia". 
Quando um serviço tem retorno, abro uma nova OS. escrevo em obs, de qual OS anterior vem uma Garantia. 

Um campo de cadastro de garantia seria muito útil. 
EX: Buscar pelo cliente aparece OS, em seguida indica qual OS voltou para garantia, como se fosse uma nova OS mas de Garantia.

**Comment by Pr3d4dor** [comment]
Obrigado pelos comentários, iremos analisar e implementar se possível.
