### ISSUE TITLE
LISTAR APENAS ORDENS DE UM USUARIO LOGADO

### ISSUE THREAD

**Issue by mytusx** [RamonSilva20/mapos#808]
Olá, na verdade procurei e nao achei, mas existe alguma forma do usuario logar e visualizar apenas as ordens correspondentes a ele??

EX: usuario joao loga no sistema e aparece apenas as ordens deste usuario pra visualização pra ele

existe alguma forma implementada?

**Comment by Pr3d4dor** [comment]
É possível sim com níveis de permissão.

**Comment by cabralwms** [comment]
Gostaria de entender como fazer dessa forma com as permissões pq nao consegui fazer assim. Poderiam me ajudar?

**Comment by mytusx** [comment]
eu tambem nao consegui... como posso criar esse tipo de permissao??? alguem pode me ajudar?

**Comment by Pr3d4dor** [comment]
@mytusx não existe somente uma maneira de implementar, você pode tentar usar alguma pacote do code igniter que disponibilize isso, implementar você mesmo ou contratar alguém para fazer.
