### ISSUE TITLE
Como retornar resultado da busca quando não encontrado?

### ISSUE THREAD

**Issue by JCMF85** [RamonSilva20/mapos#809]
Olá pessoal!

Deixa eu tentar explicar o que eu estava precisando adptar aqui ^^

Seguinte, eu gostaria que quando eu pesquisar um número de celular, quando não for encontrado(cadastrado)...

Que retornasse a mensagem de não encontrado + o número de celular digitado na pesquisa.

Por exemplo, quando eu busco um número: 6299999-9999 
A busca não encontra nada no banco de dados, ele retorna a mensagem:
**Não foi encontrado.**

O que eu gostaria, era que aparecesse o resultado da busca, mesmo não encontado junto com a mensagem:
**Não foi encontrado 6299999-9999**

Desde já agradeço quem puder ajudar.

Abraço!

**Comment by Pr3d4dor** [comment]
@JCMF85 Basta você pegar o parâmetro da pesquisa (que provavelmente está na query string) e concatenar com a mensagem de não encontrado.

**Comment by JCMF85** [comment]
> @JCMF85 Basta você pegar o parâmetro da pesquisa (que provavelmente está na query string) e concatenar com a mensagem de não encontrado.

Me desculpa, mas sou leigo em programação. Eu consigo até adptar no código, quando já pronto. 🙆🏻‍♂️

Por gentileza, você poderia me dar um exemplo de como fazer? Se não for muito incômodo.

Obrigado.

**Comment by JCMF85** [comment]
Consegui @Pr3d4dor 😉

' . $this->input->get('termo') . '

Não sei se está no modo correto, mas funcionou aqui. Coloquei depois da frase de não encontrado.

Obrigado.
