### ISSUE TITLE
Alterar informações 

### ISSUE THREAD

**Issue by heraf250** [RamonSilva20/mapos#810]
Boa tarde, modifiquei bastante o mapos conforme minha necessidade, mas agora to travado em uma alteração, gostaria que na tela inicial onde aparece "ordens de serviços aguardando peças" fosse alterada para "Ordens de serviços finalizados", ja mexi muita coisa mas sempre que altero algo a tela inicial fica toda branca, gostaria qual arquivo que tenho que alterar para poder colocar essa informação.
Desde ja agradeço

**Comment by Pr3d4dor** [comment]
@heraf250 Você está com dúvida em relação à consulta que deve ser feita para preencher os valores ou com o texto da página?

**Comment by heraf250** [comment]
> @heraf250 Você está com dúvida em relação à consulta que deve ser feita para preencher os valores ou com o texto da página?

Boa tarde consegui  resolver aqui, era acrescentar na tela principal o texto e a informações que queria.

Obrigado ai .

**Comment by maycon1977** [comment]
> > @heraf250 Você está com dúvida em relação à consulta que deve ser feita para preencher os valores ou com o texto da página?
> 
> Boa tarde consegui resolver aqui, era acrescentar na tela principal o texto e a informações que queria.
> 
> Obrigado ai .

Olá, @heraf250 .

Essa modificação me interessa. Já tentei fazer tb e não consegui.

Poderia me dar o "pulo do gato"?

**Comment by heraf250** [comment]
Qual modificação exatamente que vc esta querendo fazer ?

**Comment by maycon1977** [comment]
> Qual modificação exatamente que vc esta querendo fazer ?

Eu já fiz algumas modificações, entre elas os STATUS das ordens de Serviço...

Então eu tenho vários níveis de STATUS e gostaria de inserir esses novos STATUS lá no RESUMO INICIAL.

![image](https://user-images.githubusercontent.com/47214174/84836756-c5a14c80-b00c-11ea-8969-264a3fb89e15.png)

Aí por exemplo, consegui adaptar as "Ordens de Serviço A Receber", mas queria inserir as "Autorizadas", as "Faturadas a Entregar", etc. e já mexi pra cacete e não cheguei em resultado eficaz... Pode ser que usando alguma dica sua eu consiga...

**Comment by heraf250** [comment]
O arquivo principal que editei que deu tudo ok foi o Mapos_model.php
ai acrescentei as funções das OS ai, 

public function getOsFinalizado()
    {
        $this->db->select('os.*, clientes.nomeCliente');
        $this->db->from('os');
        $this->db->join('clientes', 'clientes.idClientes = os.clientes_id');
        $this->db->where('os.status', 'Finalizado');
        $this->db->limit(10);
        return $this->db->get()->result();
    }

Depois editei o arquivo mapos.php dentro da pasta controllers

$this->data['ordens2'] = $this->mapos_model->getOsFinalizado();

e para finalizar editei o arquivo painel.php em views --> Mapos

 <div class="widget-box">
        <div class="widget-title">
            <span class="icon"><i class="fas fa-diagnoses"></i></span>
            <h5>Ordens de Serviço Finalizado</h5>
        </div>
        <div class="widget-content">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>N° OS</th>
                        <th>Data Inicial</th>
                        <th>Data Final</th>
                        <th>Cliente</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($ordens2 != null) : ?>
                        <?php foreach ($ordens2 as $o) : ?>
                            <tr>
                                <td>
                                    <?= $o->idOs ?>
                                </td>
                                <td>
                                    <?= date('d/m/Y', strtotime($o->dataInicial)) ?>
                                </td>
                                <td>
                                    <?= date('d/m/Y', strtotime($o->dataFinal)) ?>
                                </td>
                                <td>
                                    <?= $o->nomeCliente ?>
                                </td>
                                <td>
                                    <?php if ($this->permission->checkPermission($this->session->userdata('permissao'), 'vOs')) : ?>
                                        <a href="<?= base_url() ?>index.php/os/visualizar/<?= $o->idOs ?>" class="btn">
                                            <i class="fas fa-eye"></i> </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="3">Nenhuma OS Finalizada.</td>
                        </tr>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>

ai consigo criar a quantidade de status na tela na minha acrescentei os finalizadas e um status que eu mesmo criei

**Comment by maycon1977** [comment]
> O arquivo principal que editei que deu tudo ok foi o Mapos_model.php
> ai acrescentei as funções das OS ai,
> 
> public function getOsFinalizado()
> {
> $this->db->select('os.*, clientes.nomeCliente');
> $this->db->from('os');
> $this->db->join('clientes', 'clientes.idClientes = os.clientes_id');
> $this->db->where('os.status', 'Finalizado');
> $this->db->limit(10);
> return $this->db->get()->result();
> }
> 
> Depois editei o arquivo mapos.php dentro da pasta controllers
> 
> $this->data['ordens2'] = $this->mapos_model->getOsFinalizado();
> 
> e para finalizar editei o arquivo painel.php em views --> Mapos
> 
> `< div class="widget-box"> <div class="widget-title"> <span class="icon"><i class="fas fa-diagnoses"></i></span> <h5>Ordens de Serviço Finalizado</h5> </div> <div class="widget-content"> <table class="table table-bordered"> <thead> <tr> <th>N° OS</th> <th>Data Inicial</th> <th>Data Final</th> <th>Cliente</th> <th>Ações</th> </tr> </thead> <tbody> <?php if ($ordens2 != null) : ?> <?php foreach ($ordens2 as $o) : ?> <tr> <td> <?= $o->idOs ?> </td> <td> <?= date('d/m/Y', strtotime($o->dataInicial)) ?> </td> <td> <?= date('d/m/Y', strtotime($o->dataFinal)) ?> </td> <td> <?= $o->nomeCliente ?> </td> <td> <?php if ($this->permission->checkPermission($this->session->userdata('permissao'), 'vOs')) : ?> <a href="<?= base_url() ?>index.php/os/visualizar/<?= $o->idOs ?>" class="btn"> <i class="fas fa-eye"></i> </a> <?php endif ?> </td> </tr> <?php endforeach ?> <?php else : ?> <tr> <td colspan="3">Nenhuma OS Finalizada.</td> </tr> <?php endif ?> </tbody> </table> </div> ``
> 
> ai consigo criar a quantidade de status na tela na minha acrescentei os finalizadas e um status que eu mesmo criei

Show de bola, parceiro...

Vou tentar adaptar aqui no meu. Vai demorar um pouco ainda pq tô enrolado com outras coisas mas vc me ajudou bastante, me deu um "norte".

Muito obrigado!
