### ISSUE TITLE
Pesquisar por Numero da O.S.

### ISSUE THREAD

**Issue by LeandroBressan** [RamonSilva20/mapos#811]
Pesquisar pelo numero da O.S.

**Comment by Pr3d4dor** [comment]
@LeandroBressan consegue explicar melhor?

Em pesquisar no canto superior direito você já consegue pesquisar pelo número da OS.

**Comment by LeandroBressan** [comment]
na pesquisa geral do sistema sim, mas_na_guia_ordem_de_serviço _não_tem_essa_opção, seria_bom_ter_um_campo_pra_pesquisar_pelo_número_da_OS_e_quando _mandar_pesquisar_mostrar_só_essa_OS_entendeu!
![mapos](https://user-images.githubusercontent.com/66843202/84844442-b5936800-b020-11ea-8c6d-15ab7b3497b9.PNG)
