### ISSUE TITLE
Imprimir Venda ou O.S 

### ISSUE THREAD

**Issue by Jaysonlive** [RamonSilva20/mapos#812]
Você clica em imprimir venda ou o.s não acontece nada e se clicar com botão direito e tentar imprimir a pagina , fica toda bugada.

aparece essa informação no fim da pagina "); mywindow.document.close(); // necessary for IE >= 10 return true; } });

Alguem sabe como reparar?

**Comment by Pr3d4dor** [comment]
Qual versão do mapos, navegador e sistema operacional você está utilizando?

**Comment by Pr3d4dor** [comment]
@Jaysonlive vou fechar a issue, se ainda precisar de ajuda pode reabrir.
