### ISSUE TITLE
Baixa parcial de despesas lançadas no financeiro

### ISSUE THREAD

**Issue by eletrokoczenski** [RamonSilva20/mapos#815]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Costumo lançar as despesas de compra de insumos de fornecedores no financeiro porém não consigo ir realizando pagamentos parciais e o valor ir diminuindo. Para isto ainda tenho que usar uma planilha em paralelo

** Descreva a solução que você deseja **
Um botão pagamento parcial nas despesas do modulo financeiro. Onde entraria com a data e o valor o qual iria diminuindo do montante total Esta prática é comum em nosso meio.

** Descreva as alternativas que você considerou **
Um botão pagamento parcial nas despesas do modulo financeiro. Onde entraria com a data e o valor o qual iria diminuindo do montante total Esta prática é comum em nosso meio.

** Contexto adicional **
talvez para ficar mais claro colocar esta função em uma parte específica nova como contas a receber e contas a pagar

**Comment by TK2KMG** [comment]
Muito relevante sua requisição. Me atenderia também.

**Comment by cabralwms** [comment]
Tambem achei interessante, alem de vendas parceladas e OS parceladas tambem.
