### ISSUE TITLE
api maecado pago

### ISSUE THREAD

**Issue by tombeira** [RamonSilva20/mapos#818]
Ola parabens pelo trabalho divulgo muito seu sistema, faço varias instalaçoes remotas, uma duvida é sobre a api do mercado pago até agora nao entendi direito, pois ela somente aparece na OS do tecnico responsavel e só abre no modo caixa aí nao possibilita gerar um link,será que estou fazendo alguma coisa errada? ou como configurar esse botão para aparecer na área do cliente

**Comment by Pr3d4dor** [comment]
Você configurou os parâmetros corretamente?

**Comment by glbservicos** [comment]
Olá , primeiramente venho agradecer o belo trabalho que esta sendo feito com relação ao MAPOS, top demais. E com relação a minha duvida em qual momento o cliente vai visualizar a forma de pagamento com referencia ao mercado pago.  obs: ja esta configurado devidamente conforme instrução do mercadopago.

**Comment by tombeira** [comment]
isso extamante como glbserviços comentou ja foi colocada 
Editar Credencias de Pagamentos
Nome

Mercado Pago
Client Id
8608496xxxxxxxxx
Client Secret
qzUESamEQzNpE3V1gxxxxxxxxxxxxxx
Public Key
TEST-ed8c1df7-3138-4a95-8ef4-xxxxxxxxxxxx
Access Token
TEST-8608496155949308-051022-7574fae292cc3fcc8c7dbafc304e30b9-xxxxxxxxxx

**Comment by willph** [comment]
> Ola parabens pelo trabalho divulgo muito seu sistema, faço varias instalaçoes remotas, uma duvida é sobre a api do mercado pago até agora nao entendi direito, pois ela somente aparece na OS do tecnico responsavel e só abre no modo caixa aí nao possibilita gerar um link,será que estou fazendo alguma coisa errada? ou como configurar esse botão para aparecer na área do cliente

A forma como foi feito não gera link para enviar via Whatsapp ou outro local que queira.

**Comment by willph** [comment]
> Olá , primeiramente venho agradecer o belo trabalho que esta sendo feito com relação ao MAPOS, top demais. E com relação a minha duvida em qual momento o cliente vai visualizar a forma de pagamento com referencia ao mercado pago. obs: ja esta configurado devidamente conforme instrução do mercadopago.

Ainda não foi implementado o botão de pagamento na área do cliente.
