### ISSUE TITLE
Todos os report estão dando erro na nova atualização.

### ISSUE THREAD

**Issue by microreis** [RamonSilva20/mapos#819]
`Mpdf \ MpdfImageException (E_ERROR) Could not find image file .../assets/uploads/88da46de25921bc63ecdb177a5fb13b0.jpg)`

`Mpdf\MpdfImageException …\vendor\mpdf\mpdf\src\Image\ImageProcessor.php1409`

Fiz a atualização da 4.8.2 para 4.9.0 e aparentou este erros em todos o relatórios.

**Comment by Pr3d4dor** [comment]
Basta você ir em Configurações >> Emitente e atualizar seu logo.
