### ISSUE TITLE
Cadastro de produtos por kilograma dando problema

### ISSUE THREAD

**Issue by ReiDaNet** [RamonSilva20/mapos#82]
Boa tarde, quando escolhemos a opção de valor por kilograma no cadastro de produtos e vamos no menu de vendas e escolhemos a quantidade em kilo e gramas o valor não calcula corretamente, só quando o peso é em kilo sem gramas, aí ele calcula, mas por exemplo, se colocarmos 4,10 ou 4,100 ele não calcula, o valor, o resultado que dá é em cima do valor em kilos, ou seja, o que tá antes da vírgula

**Comment by drelldeveloper** [comment]
Está funcionando normalmente. O que está acontecendo é que ele está transforma os números decimais em inteiros, por exemplo: 1,2 para 2.

**Comment by ReiDaNet** [comment]
Não tem como ele salvar em decimal não?

Em 20/12/2017 09:26, "Daniel" <notifications@github.com> escreveu:

Está funcionando normalmente. O que está acontecendo é que ele está
transforma os números decimais em inteiros, por exemplo: 1,2 para 2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RamonSilva20/mapos/issues/82#issuecomment-353038516>,
or mute the thread

**Comment by drelldeveloper** [comment]
Desculpe-me, mas não.
