### ISSUE TITLE
Upar Arquivo .rar

### ISSUE THREAD

**Issue by MatheusRoas** [RamonSilva20/mapos#820]
Pode upar arquivos rar dentro da O.S ou dentro da tabela Arquivos

**Comment by Pr3d4dor** [comment]
Só você configurar as extensões que você quer em:

https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php#L630
e
https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Arquivos.php#L226
