### ISSUE TITLE
Implementação Mapos 

### ISSUE THREAD

**Issue by felipecesarl** [RamonSilva20/mapos#821]
Prezados, na utilização do mapos identifiquei um ponto que seria muito essencial nas novas atualizações. Primeiramente o sistema está show, parabéns aos idealizadores! Bom, a parte de relatórios creio que foi a parte menos trabalhada nesse sistema. Quando extraímos relatório de vendas, o mesmo não vem a informação do item que foi vendido na data x. Creio que se tivesse um filtro de pesquisa de relatório por produto e que nesse relatório mostrasse o item vendido por tal usuário no dia x valor x, seria muito bom! Outra observação e no relatório de produto (quantidade em estoque, poderia criar um filtro para mostrar apenas o produto que queremos e não todos conforme atualmente é. Bom, seria apenas uma customização de relativos de vendas e produtos. Espero ter ajudado em ideias. Seria perfeito! Ah, uma observação. Quando realizamos vendas no mapos ele obriga o cadastro de um cliente, porém sabemos que no mundo real existem aqueles que não querem cadastros em estabelecimentos. Poderia ser opcional essa informação.  Realizei um teste agora é percebi que ao cancelar uma venda o produto não volta pro estoque automaticamente. Poderia rever isso também.

**Comment by Pr3d4dor** [comment]
Obrigado pelos comentários, iremos implementar assim que possível.
