### ISSUE TITLE
Limite de itens na lista de venda [RESOLVIDO]

### ISSUE THREAD

**Issue by scriptkid30** [RamonSilva20/mapos#822]
Quando você tem, por exemplo 6 ou mais itens com o mesmo nome, tipo "Fone de ouvido modelo tal", e você vai pesquisar o produto, o sistema só exibe 5 itens, impossibilitando de ver os demaos se não colocar o nome completo. Queria alterar isso urgente, se você me falar onde é o código para alterar eu ficarei grato!

Repito, é urgente...

**Comment by scriptkid30** [comment]
![image](https://user-images.githubusercontent.com/20694769/84955659-0ad98300-b0ce-11ea-98f3-7bf82a3cc011.png)

**Comment by scriptkid30** [comment]
![image](https://user-images.githubusercontent.com/20694769/84955697-1af16280-b0ce-11ea-9a31-6ce7991c9c3d.png)

**Comment by scriptkid30** [comment]
![Sem título](https://user-images.githubusercontent.com/20694769/84955862-6d328380-b0ce-11ea-8870-a173b39b9500.png)

**Comment by Pr3d4dor** [comment]
Só você editar para a quantidade que você quer:
https://github.com/RamonSilva20/mapos/blob/master/application/models/Os_model.php#L166

**Comment by scriptkid30** [comment]
em que linha?

**Comment by scriptkid30** [comment]
já editei essa linha para 10 e continua mostrando apenas 5

**Comment by scriptkid30** [comment]
Resolvido, só alterar a linha 176
