### ISSUE TITLE
Preciso de um suporte técnico para o programa, quero pagar!! 

### ISSUE THREAD

**Issue by diegoker** [RamonSilva20/mapos#823]
Trabalho com o sistema e tenho varias ordens de serviço lançadas e queria saber se tem algum técnico com conhecimento avançado para me dar suporte sempre que eu precisar ? meu telefone é 27988480070

**Comment by Pr3d4dor** [comment]
@diegoker Se quiser, existe um grupo do mapos do whatsapp onde você pode pedir ajuda sempre que precisar.

**Comment by diegoker** [comment]
obrigado por responder, quero sim !!

Enviado do Outlook Mobile<https://aka.ms/blhgte>

**Comment by Pr3d4dor** [comment]
O link para entrar no grupo do whatsapp é: https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
