### ISSUE TITLE
Aba de Agenda

### ISSUE THREAD

**Issue by MatheusRoas** [RamonSilva20/mapos#824]
Seria Muito Bom uma Aba de agenda para deixar salvo atendimentos futuros,.

Parabéns aos desenvolvedores, Ótimo Programa. !!!

**Comment by Pr3d4dor** [comment]
Obrigado, iremos analisar implementar assim que possível.

Se você puder mais detalhes mais específicos de como gostaria que ficasse essa agenda, seria bom.

**Comment by MatheusRoas** [comment]
> Obrigado, iremos analisar implementar assim que possível.
> 
> Se você puder mais detalhes mais específicos de como gostaria que ficasse essa agenda, seria bom.

Uma Aba agenda, com as datas do calendário. clicando em um dia especifico para par marcar na agenda alguma visita ou tarefa. 
Assim tendo o controle do que fazer em tal dia.
Referenciando o técnico e o  cliente.

**Comment by acinformatica2004** [comment]
Muito bom mesmo!

**Comment by cabralwms** [comment]
Achei a Ideia legal, agenda com mes, dia dividido com horários, estou atendendo com horário marcado assim facilitaria o controle tambem para saber se já tem algo para tal horário.

**Comment by JulianoSavino** [comment]
Seria possível talvez o Google agenda? que assim poderia ser gerenciado pelo Smartphone também...
assim ficaria perfeito, conseguiríamos ver novos agendamentos em tempo real.

**Comment by hoshikawakun** [comment]
isso ajudaria bastante

**Comment by monutb91** [comment]
Tentei implementar com o Fullcalendar mas, estou tendo problemas para fazer com que os eventos sejam gravados por MODAL.

**Comment by Pr3d4dor** [comment]
Eu irei implementar essa funcionalidade assim que possível, peço desculpas pela demora, mas estou bem ocupado com o trabalho.

**Comment by JulianoSavino** [comment]
Alguém conseguiu alguma evolução nesse topico?

**Comment by MatheusRoas** [comment]
> Alguém conseguiu alguma evolução nesse topico?

Eu até abri uma nova kkk, Mas acho que jájá eles implementa
