### ISSUE TITLE
Relatório de OS e Histórico de OS

### ISSUE THREAD

**Issue by gladuriel** [RamonSilva20/mapos#825]
Bom dia senhores!
De antemão gostaria de deixar registrado que gosto muito da estrutura e funcionamento do sistema, inclusive implementei para usar no meu trabalho como controle de OS (já que não trabalhamos com vendas) e nesse uso senti falta de um detalhe no relatório de OS: o que era o problema e o que foi feito. Aqui para o nosso uso, dependendo da situação, é avaliado o que foi feito. Inclusive ficaria como banco de conhecimento se houvessem essas opções.
Outra coisa que senti falta (mas não é algo que impeça o uso de forma alguma, é apenas uma sugestão) é a existência de um histórico de atualizações da OS informando data e hora quando é adicionada alguma informação. Exemplo, se eu pego uma OS que vai demandar mais de uma atualização e em dias distintos, seria o máximo ter a informação de quando foi feita a última atualização.

Agradeço demais aos senhores a atenção! O sistema é maravilhoso!
Valeu! [ ]'s

**Comment by Pr3d4dor** [comment]
Obrigado pelas sugestões, iremos analisar e implementar quando possível as que forem possíveis.

**Comment by maycon1977** [comment]
> Bom dia senhores!
> De antemão gostaria de deixar registrado que gosto muito da estrutura e funcionamento do sistema, inclusive implementei para usar no meu trabalho como controle de OS (já que não trabalhamos com vendas) e nesse uso senti falta de um detalhe no relatório de OS: o que era o problema e o que foi feito. Aqui para o nosso uso, dependendo da situação, é avaliado o que foi feito. Inclusive ficaria como banco de conhecimento se houvessem essas opções.
> Outra coisa que senti falta (mas não é algo que impeça o uso de forma alguma, é apenas uma sugestão) é a existência de um histórico de atualizações da OS informando data e hora quando é adicionada alguma informação. Exemplo, se eu pego uma OS que vai demandar mais de uma atualização e em dias distintos, seria o máximo ter a informação de quando foi feita a última atualização.
> 
> Agradeço demais aos senhores a atenção! O sistema é maravilhoso!
> Valeu! [ ]'s

Chefia...

Segue uma O.S. de exemplo minha pra ver se te atende...

![image](https://user-images.githubusercontent.com/47214174/85336260-b743ac80-b4b4-11ea-87db-2cf6eaee6a85.png)

Se for mais ou menos isso que procura, te passo o arquivo que modifiquei, blz?
