### ISSUE TITLE
Funcao codigo de barra

### ISSUE THREAD

**Issue by gdinizcastro** [RamonSilva20/mapos#826]
Ola desculpa a falta de acentuacao e erros de pt, meu teclado esta com problemas. Gostaria de entender a real utilidade da funcao dos codigos de barra, achei que ao utilizar tal recurso na hora de lancar uma venda bastaria fazer a leitura do produto pelo codigo e ele j[a apareceria, polpando o trabalho de ter que buscas pelo produto digitando o nome do mesmo, comprei um leitos de codigo de barra fiz o cadastro de alguns produtos porem o sistema nao funcionou como achei que fosse fundionar. Gostaria de entender qual e a real utilidade desse recurso dentro do sistema?

**Comment by Pr3d4dor** [comment]
Bom dia a função de código de barra serve basicamente para impressão de etiquetas para sem colocadas nos produtos.

Porém ainda não existe um módulo de PDV e nem de leitura de código de barras.

**Comment by gdinizcastro** [comment]
Obrigado pelo feedback! Sabe se existe alguma previsão ou intensão de implantação de uma função onde ao lancar uma venda ele faca a identificação do produto pelo código de barra previamente cadastrado?
