### ISSUE TITLE
Botão para finalizar OS e Fazer a mesma ficar invisível ou ser movido para outra pasta (Os's Finalizadas")

### ISSUE THREAD

**Issue by MatheusRoas** [RamonSilva20/mapos#827]
Um botão para finalizar a OS no final da mesma.
E quando for finalizada ser movido para uma pasta "Os's Finalizadas" para deixar a área de ordem de serviços mais CLEAN.

**Comment by acinformatica2004** [comment]
Seria muito bom essa funcionalidade.

**Comment by BESystemInfo** [comment]
Não manjo de programação, mas acredito que isso poderia ser resolvido colocando um filtro padrão que não traga as finalizadas e/ou faturadas na tela principal de OS. Assim essas OS's só apareceriam em uma pesquisa ou alterando o filtro (Mais ou menos o que tem na tela de financeiro, que só aparecem por padrão os lançamentos com vencimento naquele dia).

**Comment by MatheusRoas** [comment]
> Esta issue está obsoleta porque está aberta há 30 dias sem atividade. Remova o rótulo ou esse comentário ou essa issue será fechada em 5 dias

.

**Comment by MatheusRoas** [comment]
**"So para manter a issue"**
