### ISSUE TITLE
RELATÓRIO OS - COLOCAR SOMA DAS OS FINAL RELATÓRIO.

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#828]
PRIMEIRAMENTE PARABENIZAR AOS DESENVOLVEDORES, 

O RELATÓRIO DE OS PODERIA VIR COM UMA SOMA DE VALORES NO FINAL DO RELATÓRIO, AI FICA MAIS FÁCIL DE SABER QUANTO EM OS FOI FEITO NO MÊS, POIS PELO FINANCEIRO, AS VEZES É COLOCADO O VENCIMENTO PARA O MÊS SEGUINTE, FICA MAIS DIFÍCIL PARA CONTROLAR. OBRIGADO PELA ATENÇÃO.

**Comment by Pr3d4dor** [comment]
@vagnerlaiber a qual relatório você se refere? ao relatório de OS.

**Comment by vagnerlaiber** [comment]
@Pr3d4dor Sim Gostaria que na hora que eu tira-se o relatório de Ordem de Serviço, aparece-se o Somatório das OS no Final.
![image](https://user-images.githubusercontent.com/58378184/89051684-00481580-d32b-11ea-96f7-e224026f1bf8.png)
