### ISSUE TITLE
Bug - Faturar

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#832]
Bom dia  a todos.
Eu percebi que ao criar uma O.S. faturar, ela vai para o financeiro. Se eu alterar a O.S. o valor alterado não altera no financeiro. Alguem saberia se é bug ou tem alguma forma que resolva isso?

**Comment by Pr3d4dor** [comment]
Não é bug, pois teoricamente depois de faturado uma OS não é interessante alterar a mesma.

**Comment by cabralwms** [comment]
Obrigado pelo retorno. Vou me atentar a isso.
