### ISSUE TITLE
A.

### ISSUE THREAD

**Issue by ricardopetroli** [RamonSilva20/mapos#833]

**Comment by maycon1977** [comment]
> [https://imgur.com/u8TWv0K](url)
> 
> Acredito que pra empresas que tem poucos serviços como a minha fica bem melhor já listar todos ali de uma vez pra seleção ao invés de ter que fazer a busca e aguardar o resultado, gostaria de alterar aqui mas não tenho o conhecimento infelizmente =/

Uma gambiarra pra vc...

Na descrição dos serviços coloque um caractere em comum...
Acrescente no fim um "*", por exemplo. Assim, se vc digitar "*" no campo de busca, ele listará todos os serviços que tiverem esses caractere.
