### ISSUE TITLE
Não consigo finalizar a instalação!

### ISSUE THREAD

**Issue by pepehend** [RamonSilva20/mapos#835]
Quando vou concluir a instalação, aparece o erro "php_network_getaddresses: getaddrinfo failed: Name or service not known"

O que fazer?
![Screenshot_6](https://user-images.githubusercontent.com/67608911/86055795-b7065c80-ba32-11ea-9022-b13ff25483fa.png)

**Comment by Pr3d4dor** [comment]
Tem certeza que esse é o host do banco de dados?

Não pode começar com https.

**Comment by Welder01** [comment]
Boa tarde a todos, utilizo o sistema de ordem de serviço MAPOS e fui atualizar para ultima versar, segui tudo o que constava como orientação "documentação", mas ocorre erro de composer, como posso proceder ?

Podem me ajudar, utilizo o sistema para uma organização social !

![image](https://user-images.githubusercontent.com/67652692/86158097-add2c980-bade-11ea-9023-e7abe20e5fb8.png)

**Comment by Pr3d4dor** [comment]
@pepehend vou fechar a issue, se precisar de ajuda ainda pode reabrir.

**Comment by erivaltonoliveira** [comment]
boa tarde!
nao consigo finalizar a instalacao pelo mesmo motido relatado acima

**Comment by Pr3d4dor** [comment]
@erivaltonoliveira o host você deve estar digitando o valor errado, confira bem no seu cPanel qual é a URL do host do seu banco de dados. Ela não pode conter https:// ou http:// e nem www.
