### ISSUE TITLE
Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.

### ISSUE THREAD

**Issue by Welder01** [RamonSilva20/mapos#837]
Olá a todos, ao cumprimenta-los, compartilho um erro para tentar com a ajuda de vocês solve-lo !

Ocorreu por minha parte a atualização do MAPOS para a ultima versão,  foi seguido todos os protocolos, entretanto, há um erro declarado no Composer, om a seguinte mensagem, como mostra o print de tela. poderiam me ajudar?

![image](https://user-images.githubusercontent.com/67652692/86174180-918f5680-baf7-11ea-808b-bd8bcb86bbda.png)

**Comment by Pr3d4dor** [comment]
@Welder01, faltou instalar as dependências pelo composer, basta rodar o comando `composer install` dentro da pasta raiz do mapos.

**Comment by Welder01** [comment]
Obrigado Amigo, rodei o comando e correu tudo bem, mas, agora surge novo erro; **Usuário expirado**, poderia ajudar?


![image](https://user-images.githubusercontent.com/67652692/86270292-65c8ab00-bba1-11ea-8d59-8e504df8114a.png)

**Comment by Pr3d4dor** [comment]
@Welder01 verifique na tabela usuários a data de expiração do usuário admin.

**Comment by lidamojose** [comment]
nao consigo instalar n  WEB e nem local.
poderiam me ajudar?
como rodar o comando composer install na web?
a instalacao mostra incompleta
19 992101419 se quizerem me adicionar no whatsapp

**Comment by Welder01** [comment]
> @Welder01, USUÁRIO EXPIRADO !

Prezado amigo,



> nao consigo instalar na WEB e nem local.
> pode me ajudar?
> como rodar ou comando compositor instalar na web?
> a instalação mostra incompleta
> 19 992101419 se você me adicionar no whatsapp

Caro amigo, consegui resolver da forma seguinte 👍 
1 º Baixei um Softeare de conexão SSH, em específico este que anexo a seguir: 
[putty.zip](https://github.com/RamonSilva20/mapos/files/4864849/putty.zip)

2º Loguei em minha hospedagem

3º Autorizei minha hospedagem a executar o SSH.

4º Coletei os dados de IP de conexão na mesma tela de autorização e também a porta.

5º Determinei o Putty para conectar.

6º Basta colar o nome de usuário no shell, vai pedir em seguida a senha, então, a digite !

7º Navegue através do comando sem aspas e mais:  "cd + pasta de publicação " tecle enter.

8º dê um comando "LS" para listas todo o conteúdo da pasta, detectando que esta junto na pasta raiz de instalação MAPOS, basta rodar o comando "composer install".

assim que finalizar basta rodar "EXIT" mais enter e fechará o shell.

Resolvi desta forma !

espero ter ajudado !

**Comment by lidamojose** [comment]
> > @Welder01, USUÁRIO EXPIRADO !
> 
> Prezado amigo,
> 
> > nao consigo instalar na WEB e nem local.
> > pode me ajudar?
> > como rodar ou comando compositor instalar na web?
> > a instalação mostra incompleta
> > 19 992101419 se você me adicionar no whatsapp
> 
> Caro amigo, consegui resolver da forma seguinte 
> 1 º Baixei um Softeare de conexão SSH, em específico este que anexo a seguir:
> [putty.zip](https://github.com/RamonSilva20/mapos/files/4864849/putty.zip)
> 
> 2º Loguei em minha hospedagem
> 
> 3º Autorizei minha hospedagem a executar o SSH.
> 
> 4º Coletei os dados de IP de conexão na mesma tela de autorização e também a porta.
> 
> 5º Determinei o Putty para conectar.
> 
> 6º Basta colar o nome de usuário no shell, vai pedir em seguida a senha, então, a digite !
> 
> 7º Navegue através do comando sem aspas e mais: "cd + pasta de publicação " tecle enter.
> 
> 8º dê um comando "LS" para listas todo o conteúdo da pasta, detectando que esta junto na pasta raiz de instalação MAPOS, basta rodar o comando "composer install".
> 
> assim que finalizar basta rodar "EXIT" mais enter e fechará o shell.
> 
> Resolvi desta forma !
> 
> espero ter ajudado !

Muito Obrigado.. 
Funcionou.

**Comment by benevides-cmd** [comment]
Boa Noite! fiz todos os processo acima descrito, resolvi a questão da instalação do composer, porém apresenta o error HTTP ERROR 500, Pode me ajudar?

![image](https://user-images.githubusercontent.com/68758872/88441043-398dfc00-cde6-11ea-8392-56ce22a50bd2.png)

**Comment by LouanJuliels** [comment]
estou com o mesmo problema
mas quando tento instalar as dependências  não vai
![image](https://user-images.githubusercontent.com/82371113/114382185-75c6df80-9b62-11eb-8fc6-24bccca57c6a.png)

**Comment by ebssolucoescorporativas** [comment]
Pessoal, eu baixei aqui, instalei o banco de dados e rodei o composer, mas deu essa mensagem ao rodar o composer:
**Your requirements could not be resolved to an installable set of packages.**
Quando executei o sistema, fez a instalação do banco de dados normal, mas ao eu tentar abrir o sistema ocorre essa mensagem:
**Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada.**
A versão do meu composer é 1.6.3 pode ser esse o problema?

**Comment by Pr3d4dor** [comment]
@ebssolucoescorporativas Qual a versão do PHP?

**Comment by eduardob-younner** [comment]
> @ebssolucoescorporativas Qual a versão do PHP?
7.4.18

**Comment by eduardob-younner** [comment]
Eu até consegui fazer ele funcionar, mas apenas loga e aparece o dashboard, não aparece o menu completo.

**Comment by eduardob-younner** [comment]
> > @ebssolucoescorporativas Qual a versão do PHP?
> > 7.4.18

Eu até consegui fazer ele funcionar, mas apenas loga e aparece o dashboard, não aparece o menu completo.

**Comment by ebssolucoescorporativas** [comment]
> @ebssolucoescorporativas Qual a versão do PHP?

7.4.18
Eu até consegui fazer ele funcionar com o composer, mas ele abre a tela mostrando apenas o dashboard não aparece os menus completos.

**Comment by tvonline672** [comment]
Olá se ainda estiver com problemas entra em contato comigo tenho o Mapos aqui atualizado e pronto pra instalação sem erro Whats: 87991202231 Chama lá que te mando o arquivo já pronto pra você iniciar o Instalador do Mapos.

**Comment by guskid** [comment]
> Olá se ainda estiver com problemas entra em contato comigo tenho o Mapos aqui atualizado e pronto pra instalação sem erro Whats: 87991202231 Chama lá que te mando o arquivo já pronto pra você iniciar o Instalador do Mapos.

manda no email, se possivel?
guskid@gmail.com
obrigado!

**Comment by diegorcampos** [comment]
Boa noite.
Tenho dificuldades de instalar no infinityfree.
Pois o server não dá acesso ao putty e quando acabo a instalação, dá a mensagem do título do post.
Alguém pode me ajudar ?

**Comment by Pr3d4dor** [comment]
@diegorcampos Vai ter que enviar a pasta vendor via ftp.

**Comment by jeftedamaceno** [comment]
quando tento rodar o código exibe esse erro alguém poderia mi ajudar


Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.1.12) does not satisfy that requirement.
  Problem 2
    - piggly/php-pix is locked to version 1.2.8 and an update of this package was not requested.
    - piggly/php-pix 1.2.8 requires php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.

**Comment by gilbertoalmeida16** [comment]
Procure la por Giba Informatica no You tube eu explico

**Comment by joaoricardobr** [comment]
Sistema Completo sem Erros 
Arquivo Retirado do Video 
https://www.youtube.com/watch?v=CqCoq9-asBQ

https://drive.google.com/drive/folders/1X56smT6fA3tjiCalJTg0mfDxJTq7ydyH
