### ISSUE TITLE
Bug nos metodos dos models Mapos_model.php e Os_model.php

### ISSUE THREAD

**Issue by robsonmeca** [RamonSilva20/mapos#838]
Já faz um tempo que estou na batalha para habilitar o dbprefix no mapos, porem não funciona e eu não estava com tempo para analisar possíveis motivos, mais agora com a quarentena, tempo esta sobrando. Nessas classes foram criados métodos alguns manualmente, sem usar os métodos internos do codeigniter, e por esse motivo, esses métodos não reconhecem o dbprefix das configurações do banco de dados. Abaixo segue um dos exemplos, e a correção logo em seguida.

-----------------------------------------------------------------------------------------------------------------------------------------------------
 // Codigo Bugado

public function getProdutosMinimo() {

        $sql = "SELECT * FROM produtos WHERE estoque <= estoqueMinimo AND estoqueMinimo > 0 LIMIT 10";

        return $this->db->query($sql)->result();

    }
-----------------------------------------------------------------------------------------------------------------------------------------------------
// Correção

public function getProdutosMinimo() {

        $this->db->select('*');
        $this->db->from('produtos');
        $this->db->where('estoque <= estoqueMinimo AND estoqueMinimo > 0');
        $this->db->limit(10);

        return $this->db->get()->result();

    }
------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Pr3d4dor** [comment]
@robsonmeca Obrigado pela observação, caso você consiga arrumar em todo o sistema, seria muito bom se você mandasse uma PR com as correções.
