### ISSUE TITLE
Atualizado para versão 4.10.0 = erro 500

### ISSUE THREAD

**Issue by Ronierick** [RamonSilva20/mapos#839]
boa noite, fui atualizar o sistema e agora só aparece erro 500, nenhum código, além desse.

**Comment by RamonSilva20** [comment]
@Ronierick para visualizar qual o erro altere o arquivo index.php da raiz, linha 59, para developlment.

https://github.com/RamonSilva20/mapos/blob/master/index.php#L59

**Comment by robsonmeca** [comment]
Tive problemas na atualização também, mais acho que no meu caso é pouca memoria no servidor. Atualize o composer com o comando "composer update --no-dev" dentro da pasta do mapos e envie os arquivos por ftp, sobrescrevendo os que estão no servidor, que tudo voltara ao normal. Quando abrir vai solicitar, como se fosse uma instalação nova, entra com os dados do Banco de dados e o email e senha cadastrado, que estará tudo normal novamente.

**Comment by matheuscorteletti** [comment]
Aqui tive o mesmo problema atualizei do 3.1.5 ai instalei o composer mas deu erro e fiz esse update tb 
https://prnt.sc/td1l7k

**Comment by matheuscorteletti** [comment]
Resolvido foi editei o arquivo database e config e deu certo, eu estava usando o antigo
