### ISSUE TITLE
Da água para o vinho

### ISSUE THREAD

**Issue by drelldeveloper** [RamonSilva20/mapos#84]
Olá Ramon, tudo bom?
O seu trabalho com o desenvolvimento está um pouco confuso. Essa mudança de framework, que tem um grande impacto para nós desenvolvedores, torna o sistema um pouco rígido de se trabalhar. Ramon, o que você acha de começarmos uma nova versão, separada deste repositório, com o framework desejado?

**Comment by RamonSilva20** [comment]
Olá. Eu acabei voltando atrás e continuando o projeto com o Codeigniter, mas ainda estou estruturando o projeto, por exemplo utilizando o HMVC ao invés de MVC, com suporte a tradução, template e utilização do Composer para quando utilizarmos bibliotecas de terceiros. Caso prefira, podemos mudar o repositório, não vejo problemas nenhum nisso. Grato.

**Comment by drelldeveloper** [comment]
Concordo, vamos começar um novo projeto demo?

**Comment by gugatxr** [comment]
Um framework muito flexível é o [Yii](yiiframework.com). É rápido e tem todos recursos citados pelo Ramon. 
 Ele vem com o Gii, que gerá o crud rapidamente, que ajuda muito a desenvolver mais rápido. 
Acho que seria interessante continuar nesse repositório para não perder quem já acompanha aqui. 
Pode trocar a branch para outra e deixar a nova como master.

**Comment by drelldeveloper** [comment]
@gugatxr Eu estava pensando em fazer uma versão separada, uma demo, para que possa testar o desempenho e construir novas funcionalidades com base no framework. Mas como você mesmo disse, acho melhor continuar nesse repo mesmo hehehe
