### ISSUE TITLE
Erro na att v4.10.0

### ISSUE THREAD

**Issue by duuhmenezes** [RamonSilva20/mapos#840]
![ERRO ORDENS](https://user-images.githubusercontent.com/65459189/86377103-480d4b80-bc5e-11ea-95be-435c1795abad.png)
tentei atualizar pelo proprio sistema..

**Comment by Pr3d4dor** [comment]
Recomendo atualiza manualmente pois o atualizador está com alguns problemas.

**Comment by matheuscorteletti** [comment]
Eu atualizei aqui manualmente os arquivos da 3.1.5 e att o banco com o update estou com o mesmo erro oq faço?

**Comment by TK2KMG** [comment]
matheus , te aconselho a fazer um backup pelo sistema, depois faça  a instalação do zero da nova versão 4.10, Logo após instalar a nova versão, abra o navegador, digite localhost, vá em phpMyAdmin e faça a importação do banco de dados através do backup que você gerou. Funcionou para mim , menos complicado. Daí em diante só fazer as novas atualização, mas no momento estão com problema para fazer via Mapos, somente manual.
