### ISSUE TITLE
Valor Negativo Para dar Desconto

### ISSUE THREAD

**Issue by AllysonFredMed** [RamonSilva20/mapos#842]
Boa tarde, antes de atualizar eu tinha um produto cadastrado chamado DESCONTO e quando eu queria dar desconto eu colocava o valor dele negativo... e o Sistema subraia do valor total... Porem depois que atualizei esse processo da erro... tentei alterar no banco mas sem sucesso... alguem sabe me dizer como faço para voltar...
Atemão ja agradeco o apoio e a oportunidade de usar o MAPOS

**Comment by Pr3d4dor** [comment]
@AllysonFredMed pode dar mais detalhess sobre o erro?

Se puder colocar o log ou a imagem do erro que acontece ficaria mais fácil para ajudarmos.

**Comment by marllonferreira** [comment]
> @AllysonFredMed pode dar mais detalhess sobre o erro?
> 
> Se puder colocar o log ou a imagem do erro que acontece ficaria mais fácil para ajudarmos.

to na mesma situação

e o seguinte o mapos não tem opção de desconto o jeito fácil de resolver isso era cadastra um produto ou um serviço com o nome desconto e deixa o valor negativo dessa forma vc teria o desconto, na hora de adicionar era só altera o valor de acordo com a necessidade 

agora quando vai fazer essa alteração o sistema fala q ocorreu um erro ao tenta adicionar o serviço (produto)

**Comment by Pr3d4dor** [comment]
@marllonferreira Basta você abrir o o arquivo form_validation: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php e remover `|greater_than[0]` de todos os lugares.

**Comment by marllonferreira** [comment]
> @marllonferreira Basta você abrir o o arquivo form_validation: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php e remover `|greater_than[0]` de todos os lugares.

valeu amigo deu certinho muito obrigado 

teria como fazer com que o campo de quantidade já entrasse com o valor 1 pq a maior partes dos serviços a quantidade e um serviço de cada dai quando necessárioa ai alterar assim ganhando tempo

**Comment by Pr3d4dor** [comment]
@marllonferreira abra o arquivo https://github.com/RamonSilva20/mapos/blob/master/application/views/os/editarOs.php

E mude as linhas 540 à 559 para:
```
        $("#produto").autocomplete({
            source: "<?php echo base_url(); ?>index.php/os/autoCompleteProduto",
            minLength: 2,
            select: function(event, ui) {
                $("#idProduto").val(ui.item.id);
                $("#estoque").val(ui.item.estoque);
                $("#preco").val(ui.item.preco);
                $("#quantidade").val(1);
                $("#quantidade").focus();
            }
        });

        $("#servico").autocomplete({
            source: "<?php echo base_url(); ?>index.php/os/autoCompleteServico",
            minLength: 2,
            select: function(event, ui) {
                $("#idServico").val(ui.item.id);
                $("#preco_servico").val(ui.item.preco);
                $("#quantidade_servico").val(1);
                $("#quantidade_servico").focus();
            }
        });

```

**Comment by marllonferreira** [comment]
> @marllonferreira abra o arquivo https://github.com/RamonSilva20/mapos/blob/master/application/views/os/editarOs.php
> 
> E mude as linhas 540 à 559 para:
> 
> ```
>         $("#produto").autocomplete({
>             source: "<?php echo base_url(); ?>index.php/os/autoCompleteProduto",
>             minLength: 2,
>             select: function(event, ui) {
>                 $("#idProduto").val(ui.item.id);
>                 $("#estoque").val(ui.item.estoque);
>                 $("#preco").val(ui.item.preco);
>                 $("#quantidade").val(1);
>                 $("#quantidade").focus();
>             }
>         });
> 
>         $("#servico").autocomplete({
>             source: "<?php echo base_url(); ?>index.php/os/autoCompleteServico",
>             minLength: 2,
>             select: function(event, ui) {
>                 $("#idServico").val(ui.item.id);
>                 $("#preco_servico").val(ui.item.preco);
>                 $("#quantidade_servico").val(1);
>                 $("#quantidade_servico").focus();
>             }
>         });
> ```

No caso a mudança seria o acréscimo de 
$("#quantidade_servico").val(1);
$("#quantidade").val(1);

Deu certinho muito obrigado agradeço muitíssimo
Inclusive recomendo a integração no mapos

**Comment by AllysonFredMed** [comment]
> @marllonferreira Basta você abrir o o arquivo form_validation: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php e remover `|greater_than[0]` de todos os lugares.

Cara, valeu mesmo.... muito boa e didatica as dicas... e funcionais.... sucesso para toda a equipe do mapos....

**Comment by JulianoSavino** [comment]
Não teria como colocar um campo de desconto em R$ e ou % na hora de faturar a OS ou uma venda?
