### ISSUE TITLE
ERRO depois de atualizar

### ISSUE THREAD

**Issue by matheuscorteletti** [RamonSilva20/mapos#843]
Atualizei da 3.1.5 para 4.10.0 e quando clico para visualizar a OS da o seguinte  erro
![Screenshot_34](https://user-images.githubusercontent.com/61605704/86666482-ff8bc000-bfc6-11ea-8f7e-a8986600d0fc.png)

**Comment by matheuscorteletti** [comment]
O interessante que eu entrei como cliente e consigo observar a OS

**Comment by Pr3d4dor** [comment]
@matheuscorteletti você está utilizando mysql, veja se estão corretas as tabelas.

**Comment by matheuscorteletti** [comment]
![Screenshot_35](https://user-images.githubusercontent.com/61605704/86669984-8bebb200-bfca-11ea-9988-3c8671eb5098.png)

**Comment by matheuscorteletti** [comment]
Pelo que vi tudo ok aqui

**Comment by matheuscorteletti** [comment]
E não consegui encontrar o erro

**Comment by matheuscorteletti** [comment]
Atualizei o banco com o arquivo banco.sql, na raiz do mapos e o caso resolvido..
