### ISSUE TITLE
Adorei seu Projeto.

### ISSUE THREAD

**Issue by jonataspro** [RamonSilva20/mapos#844]
Ramon, adorei seu projeto 

Foi indicado e um grupo de informatica onde perguntei quem sabia de um programa para administrar uma empresa de informatica, ai um rapaz sitou se programa, ai instalei me apaixonei por ele. 

Tomei a liberdade de fazer algumas mudança e incluir algumas telas como manjo pouco de php, e de logica. 
porem algumas das linguagem que vc esta usando não conheço ate coloquei na minha grade de estudo. 

Não sei se consegue me ajudar não estou achando ele faz os select e os insert update na tabela qual local esta esta função. 
exemplo a regra de permissão estou apanhando para entender a logica dela mas estou descobrindo muita coisa. legal.

**Comment by RamonSilva20** [comment]
Olá @jonataspro, grato pela mensagem. 

As manipulações com a base de dados ficam nos models, mas não é SQL puro e sim uma coisa chamada Query Builder.
Você escreve código PHP e gera o sql de acordo com o banco que você está utilizando.

Ex: $this->db->get('usuarios');

O código acima gera o sql => 'SELECT * FROM usuarios';

Documentação: https://codeigniter.com/userguide3/database/query_builder.html
