### ISSUE TITLE
tela branca após instalação

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#845]
Contratei uma HOSPEDAGEM para deixar o sistema online
transferi todos os arquivos para o servidor via FTP
Executei a instalação sem problemas
mas ao invez de aparecer a tela de login aparece simplismente uma tela branca
https://ontechgames.000webhostapp.com/

**Comment by RamonSilva20** [comment]
Olá @hoshikawakun, você precisa alterar uma opção no arquivo index.php para que o sistema mostre qual o erro. 
https://github.com/RamonSilva20/mapos/blob/master/index.php#L59 altere para **development**.
