### ISSUE TITLE
Alterar nome do produto no lançamento do iten no orçamento

### ISSUE THREAD

**Issue by carlaomegagitos** [RamonSilva20/mapos#846]
Gostaria de Editar o nome do produto lançado na venda. Tipo cadastrar o produto com o nome de Produto X, e após lança-lo na venda clicar sobre seu nome e editar a descrição e/ou adicionar alguma coisa tipo um numero de série.

É possivel?
desde ja agradeço!!!

att.

Carlos FErreira

** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
@carlaomegagitos é possível, porem levariamos um pouco de tempo para implementar.

**Comment by carlaomegagitos** [comment]
Isso seria muito importante pra mim.
Obrigado

Em sáb, 18 de jul de 2020 16:13, Gianluca Bine <notifications@github.com>
escreveu:
