### ISSUE TITLE
Adicionar campos

### ISSUE THREAD

**Issue by chico24hs** [RamonSilva20/mapos#847]
Prezados, tem como criar os campos que eu queria essa. Espero que se voce consegue atualizar. 
![WhatsApp Image 2020-07-08 at 12 55 38](https://user-images.githubusercontent.com/60976863/86949066-81453000-c124-11ea-9f94-17d1656efe5d.jpeg)

**Comment by Ricky097** [comment]
Optima ideia se possivel adicionar mais que um equipamento.
Fico à espera

**Comment by chico24hs** [comment]
Alguém sabe fazer isso? Por favor, eu preciso de sua ajudar. Obrigado

**Comment by Pr3d4dor** [comment]
@chico24hs não é tão simples de implementar pois equipamentos é uma tabela separada.

**Comment by monutb91** [comment]
> 
> 
> @chico24hs não é tão simples de implementar pois equipamentos é uma tabela separada.

No caso, seria incluir os campos na tabela de equipamentos e apontar nas views, models esses novos campos, seria isso?

**Comment by hoshikawakun** [comment]
> 
> 
> Prezados, tem como criar os campos que eu queria essa. Espero que se voce consegue atualizar.
> ![WhatsApp Image 2020-07-08 at 12 55 38](https://user-images.githubusercontent.com/60976863/86949066-81453000-c124-11ea-9f94-17d1656efe5d.jpeg)

onde conseguiu essa imagem, creio eu que talvez eu consiga implementar

**Comment by Pr3d4dor** [comment]
@monutb91 sim, seria isso mesmo.

**Comment by hoshikawakun** [comment]
Estou tentando fazer essa implementação aki, vou criar outra tabela pra não dar conflito com a ja existente e tmb não sei como a mesma esta construida, prefiro criar eu mesmo

**Comment by hoshikawakun** [comment]
Consegui fazer todas as alteraçoes necessarias, agora como faço para compartilhar tudo oque eu editei
![Screenshot_38](https://user-images.githubusercontent.com/1253576/87595543-16b46700-c6c5-11ea-8160-6a8f73ddb422.png)
![Screenshot_39](https://user-images.githubusercontent.com/1253576/87595561-1c11b180-c6c5-11ea-9838-4ed1674ea381.png)
![Screenshot_40](https://user-images.githubusercontent.com/1253576/87595587-25028300-c6c5-11ea-8f0f-1199e31b3d80.png)

**Comment by Pr3d4dor** [comment]
@hoshikawakun Você pode criar uma pull request, ou se você não conseguir, pode me passar todo o projeto do mapos zipado que aí eu faço.

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun Você pode criar uma pull request, ou se você não conseguir, pode me passar todo o projeto do mapos zipado que aí eu faço.

Nesse arquivo tem todas as alteraçoes que foram feitas, separadas em pasta e cada arquivo
nos arquivos tem apenas as alterações que foram feitas
e junto tem o arquivo SQL da tabela que criei
[Equipamentos OS](https://github.com/hoshikawakun/MasterOS/blob/master/application.rar)

**Comment by Ricky097** [comment]
Seria possivel implementar este sistema de forma oficial num proximo release?

**Comment by chico24hs** [comment]
Fui resolvido! Obrigado por tudo. Amei seu projeto.

**Comment by MarceloGrass** [comment]
Tenho muito interesse em implementar essas mudanças, entendo que teria que substituir os arquivos modificados, e a base de dados que esta junto devo adicionar essas linhas na minha base de dados ou não precisa?

**Comment by xadun** [comment]
@chico24hs conseguiu inserir a parte de equipamentos?

**Comment by chico24hs** [comment]
> @chico24hs conseguiu inserir a parte de equipamentos?

Desculpe, foi mal eu pensei que deu certo mas deu erro. Espero que se equipe consegue atualizar. Eu queria muito equipamentos
