### ISSUE TITLE
Existe alguma forma de organizar as OS para as que estão aberto ficarem sempre em cima?

### ISSUE THREAD

**Issue by isabelladeassis** [RamonSilva20/mapos#848]
Então, gostaria de organizar as Ordens de Serviços de forma que as que estão abertas ficassem sempre em cima para uma melhor visualização. Dessa forma seria mais rápido do que pesquisar.

**Comment by Pr3d4dor** [comment]
Você pode mudar a query que pega as OS do banco e colocar um order by.

**Comment by isabelladeassis** [comment]
Entendi
