### ISSUE TITLE
Falha ao carregar documento PDF."

### ISSUE THREAD

**Issue by ramonsousa89** [RamonSilva20/mapos#85]
Quando gero qualquer relatórios, da o seguinte erro:

"Erro
Falha ao carregar documento PDF."

Como corrigi-lo?

**Comment by drelldeveloper** [comment]
Qual navegador que você está usando?

**Comment by ramonsousa89** [comment]
Chrome, tem a ver com navegador?

**Comment by drelldeveloper** [comment]
Sim. Mas neste caso eu não posso fazer nada, desculpe-me.
