### ISSUE TITLE
Tem como importar os clientes de outra base de dados? consigo salvar em planilha excel do programa atual

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#850]
**Importar lista de clientes **
Gostaria de importar a minha lista de clientes, são 1.500 é muito para fazer manual, no programa atual OS Plus 4 consigo salvar em formato excel. Tem alguma forma de fazer isso? não achei no programa.

**Comment by marllonferreira** [comment]
amigo vc ta usando qual versão ?

**Comment by MarceloGrass** [comment]
A ultima, versão 4.10.0

**Comment by Pr3d4dor** [comment]
@MarceloGrass não existe essa funcionalidade, você teria que fazê-la.

**Comment by marllonferreira** [comment]
> amigo vc ta usando qual versão ?

Achei q tinha uma versão antiga do mapos e queria muda pra o mapos 4
