### ISSUE TITLE
Login de primeiro acesso não funciona

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#853]
Pessoal, boa tarde a todos!
Realizei a instalação do sistema, estou tentando realizar o primeiro login, logo após a instalação e ou fica carregando na barra azul ou apresenta modal de "dados incorretos". 
Não utilizava o sistema, vim a conhecer agora, por tanto esta é a primeira instalação.

Tentei instalar algumas vezes, apresentou alguns erros. primeiro foi "nao localizou a pasta system", instalei o Composer na pasta raiz e carregou a pagina de login (ainda não estou vendo a pasta System no diretorio). Porem não acessa o sistema.

email e senha estão OK.
database.php esta com os dados corretos.
instalação em localhost (xampp).
URL (http://localhost/mapos)

Alguém saberia o que pode ser?

**Comment by Pr3d4dor** [comment]
Recomendo utilizar o instalador ao invés de instalar manualmente.

**Comment by monutb91** [comment]
Qual instalador? Esta havendo a conexão com o banco de dados pois, se eu remover ou atrasar a data no campo "dataExpiracao" na tabela de usuarios, retorna um modal de erro dizendo que o usuario expirou. Não esta aceitando a minha senha e login para acesso. pode me ajudar?

**Comment by Pr3d4dor** [comment]
https://github.com/RamonSilva20/mapos/blob/master/Instalacao_xampp_windows.md

**Comment by monutb91** [comment]
Segui exatamente este passo a passo e agora apresenta a mensagem de que a pasta system não foi localizada, inclusive ela não aparece na pasta raiz. Instalei o composer pelo power shell como no tutorial e o meu resultado foi o mesmo, tudo OK. Mas o sistema não executa. :(
Onde ou como instalo a pasta system?

**Comment by Pr3d4dor** [comment]
@monutb91 Se deu esse erro as dependências do composer não foram instaladas, verifique isso.
