### ISSUE TITLE
TROCA DA COR DOS BOTÕES ENVIAR DO LOGIN E DO PAINEL DO CLIENTE

### ISSUE THREAD

**Issue by gilbertoalmeida16** [RamonSilva20/mapos#854]
Já consegui trocar o fundo da primeira pagina login, porem os botões tanto da primeira pagina como a pagina do cliente (area do cliente não consigo trocar a cor azul e verde do botão alguem conseguiu? muito obrigado

**Comment by Pr3d4dor** [comment]
Qual a sua dificuldade exatamente?

**Comment by gilbertoalmeida16** [comment]
Queria trocar as cores do botões acessar na pagina inicial, e no area do cliente trocar tambem as cores do botão acessar e cadastre.. pois o fundo já consegui.

**Comment by MarceloGrass** [comment]
Como você trocou o fundo da pagina de login?

**Comment by gilbertoalmeida16** [comment]
Vai lá ! na pasta do seu sistema ex: mapos/assets/css/matrix-login.css    SEGUE O CODIGO. COM OS COMENTARIOS.

html, body {    width: 100%;    height: 100%;}
/*Bootstrap-overlay*/

body {
 overflow-x: hidden;
 margin-top: -10px;  font-family: 'Open Sans', sans-serif; font-size:12px; color:#666;
}
a{color:#666;}
a:hover, a:focus {
 text-decoration: none; color:#28b779;
}
.dropdown-menu .divider{ margin:4px 0px;}
.dropdown-menu{ min-width:180px;}
.dropdown-menu > li > a{ padding:3px 10px; color:#666; font-size:12px;}
.dropdown-menu > li > a i{ padding-right:3px;}
.userphoto img{ width:19px; height:19px;}
select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input, .label, .dropdown-menu, .btn, .well, .progress, .table-bordered, .btn-group > .btn:first-child, .btn-group > .btn:last-child, .btn-group > .btn:last-child, .btn-group > .dropdown-toggle, .alert{ border-radius:0px;}
.btn, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input{ box-shadow:none;}
.progress, .progress-success .bar, .progress .bar-success, .progress-warning .bar, .progress .bar-warning, .progress-danger .bar, .progress .bar-danger, .progress-info .bar, .progress .bar-info, .btn, .btn-primary{background-image:none;}
.accordion-heading h5{ width:70%; }
.form-horizontal .form-actions{ padding-left:20px; }
#footer{ padding:10px; text-align:center;}
hr{ border-top-color:#dadada;}
.carousel{ margin-bottom:0px;}
.fl { float:left}
.fr {float:right}
.label-important, .badge-important{ background:#f74d4d;}

/*Metro Background color class*/
.bg_lb{ background:#4F4C4C;} /* TROCAR COR DO BACKGROUNG DO CADEADO LOGIN */
.bg_db{ background:#000000;}
.bg_lg{ background:#FA0000;} /* TROCAR COR DO BACKGROUNG DO BONECO LOGIN */
.bg_dg{ background:#28b779;}
.bg_ly{ background:#000000;} /* TROCAR COR DO BACKGROUNG AREA DO CLIENTE CARTAO CNPJ */
.bg_dy{ background:#da9628;}
.bg_ls{ background:#2255a4;}
.bg_lo{ background:#da542e;}
.bg_lr{ background:#f74d4d;}
.bg_lv{ background:#603bbc;}
.bg_lh{ background:#b6b3b3;}

body { background-color:#000000;    padding: 0;    margin-top:10%;} /* TROCAR COR DO BACKGROUNG EM TORNO DO LOGIN */
#logo, #loginbox {    width: 32%;    margin-left: auto;    margin-right: auto;    position: relative;}
#logo img {  margin: 0 auto;    display: block;}
#loginbox { overflow: hidden !important;    text-align: left;    position: relative; }
#loginbox form{ width:100%; background:#00000; position:relative; top:0; left:0; }  /* TROCAR COR DO BACKGROUNG EM TORNO DO LOGIN USER E SENHA */
#loginbox .form-actions { padding: 14px 20px 15px;}
#loginbox .form-actions .pull-left { margin-top:0px;}
#loginbox form#loginform { z-index: 200; display:block;}
#loginbox form#recoverform { z-index: 100;     display:none;}
#loginbox form#recoverform .form-actions {    margin-top: 10px;}
#loginbox .main_input_box { margin:0 auto; text-align:center; font-size:13px;}
#loginbox .main_input_box .add-on{  padding:9px 9px; *line-height:31px; color:#fff;  width:30px; display:inline-block;}
#loginbox .main_input_box input{ height:30px; border:0px; display:inline-block; width:75%; line-height:28px;  margin-bottom:3px;}
#loginbox .controls{ padding:0 20px;}
#loginbox .control-group{ padding:20px 0; margin-bottom:0px;}
.form-vertical, .form-actions {  margin-bottom: 0; background:none; border-top:1px solid #fa0000; }  /* TROCAR COR DA LINHA EM CIMA E BAIXO LOGIN */
#loginbox .normal_text{ padding:15px 10px; text-align:center; font-size:14px; line-height:20px; background:#000000; color:#fff; } /* TROCAR COR DO BACKGROUNG EM TORNO DO LOGOTIPO */
@media (max-width:800px){
#logo { width: 60%; }
#loginbox{ width:80%}
}
@media (max-width: 480px){
#logo { width: 40%; }
#loginbox{ width:90%}
#loginbox .control-group{ padding:8px 0; margin-bottom:0px;}
}

**Comment by cleytonasa** [comment]
#666 da medo!!
