### ISSUE TITLE
Não consigo instalar o script em meu host

### ISSUE THREAD

**Issue by ktnckws** [RamonSilva20/mapos#855]
Ao tentar rodar as versões 4.4.0 ou 4.9.0 em um host da um erro e não consegue completar a instalação,
![Captura de tela de 2020-07-13 07-57-29](https://user-images.githubusercontent.com/68227393/87298141-1313bb00-c4e0-11ea-9bbc-1c88169ffb43.png)
 segue em anexo.

**Comment by Pr3d4dor** [comment]
Esse erro não parece erro do mapos.

Como vc realizou a instalação?

**Comment by ktnckws** [comment]
Tentei fazer a instalação da mesma maneira que fiz na versão 2 a alguns anos. Subindo o banco mysql no host e levando os arquivos a uma pasta especifica modificando os arquivos config e database com os dados do host.
Perdoe-me por não entender muito sobre os erros. Sou um pouco leigo nesta área mais uso o Mapos a alguns anos, e estava querendo instalar essa nova atualização em um host que fica meu site.

**Comment by Pr3d4dor** [comment]
@ktnckws veja se esse tutorial consegue te ajudar: https://github.com/RamonSilva20/mapos/blob/master/Instalacao_xampp_windows.md

Você tem que usar o banco de dados no formato atual, ou seja, usar um banco de dados do mapos 2 não irá funcionar.

**Comment by ktnckws** [comment]
Então parceiro eu estou subindo ele em uma hospedagem de um site e não no windows. La não consigo fazer funcionar como fazia na versão antiga. A hospedagem usa Cpanel para controle.

**Comment by Pr3d4dor** [comment]
@ktnckws o que você tem que fazer é instalar o composer localmente e rodar o comando de instalar as dependências localmente.
Após isso você ira pegar a pasta `application/vendor` e enviar via FTP no seu servidor.

**Comment by ktnckws** [comment]
Muito obrigado pelo auxilio. Vou tentar dessa maneira hoje a noite e ver como fica.

**Comment by mandruuuu** [comment]
Consegui faze roda no cpanel.

Fiz o seguinte:

1º Instalei o xammp.

- Descompactei a pasta do sitema dentro da "htdocs".
- Instalei o Composer (https://getcomposer.org/download/)
- Rodei o Composer, antes de começar a instalação do script.
_____ shift + botão direito na pasta raiz do script ___ (C:\xampp\htdocs\mapos -> no meu caso)__
        "Abrir janela do PowerShell aqui".
- Na janela que abre, colei o seguinte comando: " composer install --no-dev ".

Esperei executar e finalizar.

Voltei ao xammp, e compactei a pasta "mapos" - que esta o sistema - em formato *.zip.
Uplei no meu cpanel.

Fiz o banco de dados novo, novo usuário e senha.

Caso queira, pode se fazer também um subdomínio para o teu sistema. Só não esqueça de mover todos os arquivos para dentro da pasta que o teu cpanel irá criar.

Após esse processo, abri o meu subdomínio e segui os passos solicitados.

Fiz assim, pq ao invés de subir via ftp, demoraria mais, e usando o instalador do sistema, creio que terá menos risco de corromper algo, do que importar banco de dados depois, modificar config e afins.
