### ISSUE TITLE
Sugestão de adição de itens.

### ISSUE THREAD

**Issue by FlexoSol** [RamonSilva20/mapos#858]
Bom dia a todos. Deixo em anexo uma simples sugestão de adicionar às futuras versões
[Mudanças Mapos.txt](https://github.com/RamonSilva20/mapos/files/4918974/Mudancas.Mapos.txt)
 alguns campos de código em ImprimirVendas/OS e pesquisar Produtos. Mudanças estas que necessitei realizar para uso próprio.
Por favor, analisem.
Obrigado.

**Comment by Pr3d4dor** [comment]
@FlexoSol você não gostaria de fazer uma pull request com essas melhorias? Assim você teria créditos e seu nome entre os contribuidores do projeto.

**Comment by FlexoSol** [comment]
Não sei se foi corretamente aberto a pull request, mas, está aberta.
