### ISSUE TITLE
Erro ao Excluir Anexo

### ISSUE THREAD

**Issue by eternogold5** [RamonSilva20/mapos#86]
Bom dia, estou com um problema em excluir os anexos da aba OS, quando aperta o botao excluir do modal anexos ele nao faz nada, apenas ativa a progress bar, ja tentei varias coisas mas nao consegui resolver. 
Grato

**Comment by RamonSilva20** [comment]
Bom dia. Sabe dizer se está excluindo do banco de dados ou da pasta?

**Comment by eternogold5** [comment]
Bom dia Ramon, estou utilizando o xampp, na aba das Os onde fica anexos tento excluir como na figura abaixo

![image](https://user-images.githubusercontent.com/34897030/34608663-a23e88f6-f200-11e7-89aa-25a72f87169d.png)

apos o botao excluir ele fica rodando essa barra azul e nao sai disso.
![image](https://user-images.githubusercontent.com/34897030/34608676-b3a3a946-f200-11e7-9545-9fc54a20c5ce.png)

verifiquei seu codigo nessas seguintes partes abaixo

![image](https://user-images.githubusercontent.com/34897030/34608790-2d3d2700-f201-11e7-8a98-87a679edf64f.png)

![image](https://user-images.githubusercontent.com/34897030/34608818-4ae0799c-f201-11e7-9d81-c77951774c41.png)

quando eu faço essa modificacao ele exclui e me retorna a seguinte pagina

![image](https://user-images.githubusercontent.com/34897030/34608919-c2f32dbc-f201-11e7-9792-c819be150a44.png)

![image](https://user-images.githubusercontent.com/34897030/34608958-fd322848-f201-11e7-95c4-d9515f0467dc.png)

as imagens do anexo continuam na pasta e os thumbs sao excluidos
desculpe pela ignorancia pois estou comecando a pouco tempo a programar em php e codeiginiter.

**Comment by eternogold5** [comment]
so complementando, so é exluido apos aquela modificacao, no banco de dados ele exclui tmb apos a modificacao

**Comment by visaotec** [comment]
Bom dia,
esse sistema está ficando perfeito,precisa fazer algumas implantações pra ficar melhor,isso irá deixa ele mais top,tipo fazer uma mascara como se fosse um site normal e colocar no cabeçalho um link pra acessar o sistema,mas sem ser link externo.
abraços

**Comment by pocapratica** [comment]
Fui olhar agora a minha instalação.
Ele também não exclui. Além disso, eu tinha anexado arquivos em pdf. Ele renomeou (ou compactou) pra .zip e ele está com tamanho 0 bytes.

**Comment by MMSAKA** [comment]
Boa Noite, 

Alguém tem alguma posição em relação a este problema....
Não consegui resolver...

Desde de já obrigado

**Comment by drelldeveloper** [comment]
@RamonSilva20 Você corrigiu este erro? :cry:

**Comment by MMSAKA** [comment]
Não consegui ainda.... já tentei de tudo   😢 😢 😢 😢

**Comment by jocieldo** [comment]
=> Primeiro, o campo do banco de dados para o nome do anexo está limitado para 45 caracteres, então se você tentar subir com um arquivo com o nome maior, ele vai recortar o nome para 45, ai o sistema não vai conseguir encontrar o arquivo especificado. 

- Primeira Solução:
Aumentar o tamanho do campo ex: de 45 para 120.
_ALTER TABLE anexos CHANGE COLUMN anexo anexo VARCHAR( 120 );_

- Segunda solução:
Alterar o campo para TEXT, ai fica ilimitado (mas não é o recomendado).
_ALTER TABLE anexos CHANGE COLUMN anexo anexo TEXT;_

=> Agora o segundo problema, o erro que não excluir. 

- O problema está no javascript na associação do link ao botão, pois o link informado está errado, faltando o index.php/. 
- Deverá ser alterado a linha 701 do aquivo: _application\views\os\editarOs.php_

Atualmente está assim:
`var url = '<?php echo base_url(); ?>os/excluirAnexo/';`

Deverá ficar assim:
`var url = '<?php echo base_url(); ?>index.php/os/excluirAnexo/';`

**Comment by MMSAKA** [comment]
Muito obrigado Jocieldo e Ramon... vou fazer as correções ainda hj... 👍🏼




Em 19 de mar de 2018, à(s) 18:27, Jocieldo Abreu <notifications@github.com<mailto:notifications@github.com>> escreveu:


=> Primeiro, o campo do banco de dados para o nome do anexo está limitado para 45 caracteres, então se você tentar subir com um arquivo com o nome maior, ele vai recortar o nome para 45, ai o sistema não vai conseguir encontrar o arquivo especificado.

  *   Primeira Solução:
Aumentar o tamanho do campo ex: de 45 para 120.
ALTER TABLE anexos CHANGE COLUMN anexo anexo VARCHAR( 120 );

  *   Segunda solução:
Alterar o campo para TEXT, ai fica ilimitado (mas não é o recomendado).
ALTER TABLE anexos CHANGE COLUMN anexo anexo TEXT;

=> Agora o segundo problema, o erro que não excluir.

  *   O problema está no javascript na associação do link ao botão, pois o link informado está errado, faltando o index.php/.
  *   Deverá ser alterado a linha 701 do aquivo: application\views\os\editarOs.php

Atualmente está assim:
var url = '<?php echo base_url(); ?>os/excluirAnexo/';

Deverá ficar assim:
var url = '<?php echo base_url(); ?>index.php/os/excluirAnexo/';

**Comment by MMSAKA** [comment]
Tudo certo.. Corrigido . Parabéns e Obrigado
