### ISSUE TITLE
 real para Euro o sistema como faco ?

### ISSUE THREAD

**Issue by Bruno28121** [RamonSilva20/mapos#860]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
@Bruno28121 fazer esse ajuste não é trivial, pois o sistema está `hard-coded` em real brasileiro, então a última alternativa é sair caçando todos os lugares onde aparecem valores monetários e fazer o ajuste.

**Comment by Bruno28121** [comment]
> @ Bruno28121 fazer esse ajuste não é trivial, pois o sistema está no `hard-coded`real brasileiro, então a última alternativa é sair caçando todos os lugares onde aparecem valores monetários e fazer o ajuste.

E qual a pagina responsável para eu apenas trocar o simbolos , nao saindo o R$ ja vai ajudar

**Comment by Ricky097** [comment]
basta com o notepad ++ ou similar abrir os ficheiros que contêm esse símbolo da pasta VIEWS e susbtituir R$  por €
