### ISSUE TITLE
Posso modificar os campos para que sejam ou não obrigatorios?

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#862]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Fico sempre frustrado quando [...]

** Descreva a solução que você deseja **
Uma descrição clara e concisa do que você deseja que aconteça.

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Pr3d4dor** [comment]
@MarceloGrass sim, basta vc olhar o arquivo form_validation.php

**Comment by MarceloGrass** [comment]
Muito obrigado pela ajuda!!!

**Comment by gasperpb** [comment]
Como faz para modificar?

**Comment by SMARTNOTETB** [comment]
precisava tbm remover obrigatoriedade de email

**Comment by gasperpb** [comment]
Eu configurei o arquivo e depois salvei mas não funcionou?
<?php defined('BASEPATH') or exit('No direct script access allowed');

$config = [
    'clientes' => [
        [
            'field' => 'nomeCliente',
            'label' => 'Nome',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'documento',
            'label' => 'CPF/CNPJ',
            'rules' => 'trim|verific_cpf_cnpj',
            'errors' => [
                'verific_cpf_cnpj' => "O campo %s não é um CPF ou CNPJ válido."
            ],
        ],
        [
            'field' => 'telefone',
            'label' => 'Telefone',
            'rules' => '',
        ],
        [
            'field' => 'email',
            'label' => 'Email',
            'rules' => 'trim|valid_email',
        ],
        [
            'field' => 'rua',
            'label' => 'Rua',
            'rules' => 'trim',
        ],
        [
            'field' => 'numero',
            'label' => 'Número',
            'rules' => 'trim',
        ],
        [
            'field' => 'bairro',
            'label' => 'Bairro',
            'rules' => 'trim',
        ],
        [
            'field' => 'cidade',
            'label' => 'Cidade',
            'rules' => 'trim',
        ],
        [
            'field' => 'estado',
            'label' => 'Estado',
            'rules' => 'trim',
        ],
        [
            'field' => 'cep',
            'label' => 'CEP',
            'rules' => 'trim',
        ]
    ],
    'servicos' => [
        [
            'field' => 'nome',
            'label' => 'Nome',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'descricao',
            'label' => '',
            'rules' => 'trim',
        ],
        [
            'field' => 'preco',
            'label' => '',
            'rules' => 'required|trim',
        ]
    ],
    'produtos' => [
        [
            'field' => 'descricao',
            'label' => '',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'unidade',
            'label' => 'Unidade',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'precoCompra',
            'label' => 'Preço de Compra',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'precoVenda',
            'label' => 'Preço de Venda',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'estoque',
            'label' => 'Estoque',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'estoqueMinimo',
            'label' => 'Estoque Minimo',
            'rules' => 'trim',
        ]
    ],
    'usuarios' => [
        [
            'field' => 'nome',
            'label' => 'Nome',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'rg',
            'label' => 'RG',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'cpf',
            'label' => 'CPF',
            'rules' => 'required|trim|verific_cpf_cnpj|is_unique[usuarios.cpf]',
            'errors' => [
                'verific_cpf_cnpj' => "O campo %s não é um CPF válido."
            ],
        ],
        [
            'field' => 'rua',
            'label' => 'Rua',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'numero',
            'label' => 'Numero',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'bairro',
            'label' => 'Bairro',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'cidade',
            'label' => 'Cidade',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'estado',
            'label' => 'Estado',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'cep',
            'label' => 'CEP',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'email',
            'label' => 'Email',
            'rules' => 'required|trim|valid_email|is_unique[usuarios.email]',
        ],
        [
            'field' => 'senha',
            'label' => 'Senha',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'telefone',
            'label' => 'Telefone',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'situacao',
            'label' => 'Situacao',
            'rules' => 'required|trim',
        ]
    ],
    'os' => [
        [
            'field' => 'dataInicial',
            'label' => 'DataInicial',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'dataFinal',
            'label' => 'DataFinal',
            'rules' => 'trim|required',
        ],
        [
            'field' => 'garantia',
            'label' => 'Garantia',
            'rules' => 'trim|numeric',
            'errors' => [
                'numeric' => 'Por favor digite apenas número.'
            ],
        ],
        [
            'field' => 'termoGarantia',
            'label' => 'Termo Garantia',
            'rules' => 'trim',
        ],
        [
            'field' => 'descricaoProduto',
            'label' => 'DescricaoProduto',
            'rules' => 'trim',
        ],
        [
            'field' => 'defeito',
            'label' => 'Defeito',
            'rules' => 'trim',
        ],
        [
            'field' => 'status',
            'label' => 'Status',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'observacoes',
            'label' => 'Observacoes',
            'rules' => 'trim',
        ],
        [
            'field' => 'clientes_id',
            'label' => 'clientes',
            'rules' => 'trim|required',
        ],
        [
            'field' => 'usuarios_id',
            'label' => 'usuarios_id',
            'rules' => 'trim|required',
        ],
        [
            'field' => 'laudoTecnico',
            'label' => 'Laudo Tecnico',
            'rules' => 'trim',
        ]
    ],
    'tiposUsuario' => [
        [
            'field' => 'nomeTipo',
            'label' => 'NomeTipo',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'situacao',
            'label' => 'Situacao',
            'rules' => 'required|trim',
        ]
    ],
    'receita' => [
        [
            'field' => 'descricao',
            'label' => 'Descrição',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'valor',
            'label' => 'Valor',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'vencimento',
            'label' => 'Data Vencimento',
            'rules' => 'required|trim',
        ],

        [
            'field' => 'cliente',
            'label' => 'Cliente',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'tipo',
            'label' => 'Tipo',
            'rules' => 'required|trim',
        ]
    ],
    'despesa' => [
        [
            'field' => 'descricao',
            'label' => 'Descrição',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'valor',
            'label' => 'Valor',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'vencimento',
            'label' => 'Data Vencimento',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'fornecedor',
            'label' => 'Fornecedor',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'tipo',
            'label' => 'Tipo',
            'rules' => 'required|trim',
        ]
    ],
    'garantias' => [
        [
            'field' => 'dataGarantia',
            'label' => 'dataGarantia',
            'rules' => 'trim',
        ],
        [
            'field' => 'usuarios_id',
            'label' => 'usuarios_id',
            'rules' => 'trim',
        ],
        [
            'field' => 'refGarantia',
            'label' => 'refGarantia',
            'rules' => 'trim',
        ],
        [
            'field' => 'textoGarantia',
            'label' => 'textoGarantia',
            'rules' => 'required|trim',
        ]
    ],
    'pagamentos' => [
        [
            'field' => 'Nome',
            'label' => 'nomePag',
            'rules' => 'trim',
        ],
        [
            'field' => 'clientId',
            'label' => 'clientId',
            'rules' => 'trim',
        ],
        [
            'field' => 'clientSecret',
            'label' => 'clientSecret',
            'rules' => 'trim',
        ],
        [
            'field' => 'publicKey',
            'label' => 'publicKey',
            'rules' => 'trim',
        ],
        [
            'field' => 'accessToken',
            'label' => 'accessToken',
            'rules' => 'trim',
        ]
    ],
    'vendas' => [
        [
            'field' => 'dataVenda',
            'label' => 'Data da Venda',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'clientes_id',
            'label' => 'clientes',
            'rules' => 'trim|required',
        ],
        [
            'field' => 'usuarios_id',
            'label' => 'usuarios_id',
            'rules' => 'trim|required',
        ]
    ],
    'anotacoes_os' => [
        [
            'field' => 'anotacao',
            'label' => 'Anotação',
            'rules' => 'required|trim',
        ],
        [
            'field' => 'os_id',
            'label' => 'ID Os',
            'rules' => 'trim|required|integer',
        ]
    ],
    'adicionar_produto_os' => [
        [
            'field' => 'idProduto',
            'label' => 'idProduto',
            'rules' => 'trim|required|numeric',
        ],
        [
            'field' => 'quantidade',
            'label' => 'quantidade',
            'rules' => 'trim|required|numeric|greater_than[0]',
        ],
        [
            'field' => 'preco',
            'label' => 'preco',
            'rules' => 'trim|required|numeric|greater_than[0]',
        ],
        [
            'field' => 'idOsProduto',
            'label' => 'idOsProduto',
            'rules' => 'trim|required|numeric',
        ],
    ],
    'adicionar_servico_os' => [
        [
            'field' => 'idServico',
            'label' => 'idServico',
            'rules' => 'trim|required|numeric',
        ],
        [
            'field' => 'quantidade',
            'label' => 'quantidade',
            'rules' => 'trim|required|numeric|greater_than[0]',
        ],
        [
            'field' => 'preco',
            'label' => 'preco',
            'rules' => 'trim|required|numeric|greater_than[0]',
        ],
        [
            'field' => 'idOsServico',
            'label' => 'idOsServico',
            'rules' => 'trim|required|numeric',
        ],
    ]
];

**Comment by Salc59** [comment]
@gasperpb Você tem que entrar em dois arquivos diferentes para tirar a obrigatoriedade dos campos.

Procure na pasta application>views, nessa pasta você vai no arquivo que você que fazer a alteração, exemplo adicionar OS (Ordem de Serviço) 

**LOCAL: mapos-4.13.0/application/views/os** (O mesmo serve para clientes, produtos, serviços, etc)

Arquivo 1 encontrado vamos para o próximo passo...

Abra o arquivo e procure por **<span class="required">*</span>**
_Essa tag faz com que o HTML torne o item obrigatório. Apague-a onde você quer tirar a obrigatoriedade. 

Salve as alterações antes de sair.

Primeiro arquivo alterado com sucesso!




Agora sim vamos pro 2º arquivo que é o form_validation.php

LOCAL: /mapos-4.13.0/application/config

Abra o arquivo e apague os **required'** deixando somente o 'trim'

_Obs_: só apague os required's dos campos que você tirou la no primeiro arquivo.


Pronto!! salve e faça o teste para ver se funciona.

abç

**Comment by Salc59** [comment]
@gasperpb Você tem que entrar em dois arquivos diferentes para tirar a obrigatoriedade dos campos.

Procure na pasta application>views, nessa pasta você vai no arquivo que você que fazer a alteração, exemplo adicionar OS (Ordem de Serviço)

LOCAL: mapos-4.13.0/application/views/os (O mesmo serve para clientes, produtos, serviços, etc)

Arquivo 1 encontrado vamos para o próximo passo...

Abra o arquivo e procure por * <span class="required">*</span> *
_Essa tag faz com que o HTML torne o item obrigatório. Apague-a onde você quer tirar a obrigatoriedade._

Salve as alterações antes de sair.

Primeiro arquivo alterado com sucesso!

Agora sim vamos pro 2º arquivo que é o form_validation.php

**LOCAL: /mapos-4.13.0/application/config**

Abra o arquivo e apague os required' deixando somente o 'trim'

**Obs:** só apague os required's dos campos que você tirou la no primeiro arquivo.

Pronto!! salve e faça o teste para ver se funciona.

abç

**Comment by Salc59** [comment]
@gasperpb Você tem que entrar em dois arquivos diferentes para tirar a obrigatoriedade dos campos.

Procure na pasta application>views, nessa pasta você vai no arquivo que você que fazer a alteração, exemplo adicionar OS (Ordem de Serviço)

LOCAL: **mapos-4.13.0/application/views/os** (O mesmo serve para clientes, produtos, serviços, etc)

Arquivo 1 encontrado vamos para o próximo passo...

Abra o arquivo e procure por **<span class="required"</span>**
Essa tag faz com que o HTML torne o item obrigatório. Apague-a onde você quer tirar a obrigatoriedade.

Salve as alterações antes de sair.
Primeiro arquivo alterado com sucesso!

.......................................


Agora sim vamos pro 2º arquivo que é o **form_validation.php**

LOCAL: **/mapos-4.13.0/application/config**


Abra o arquivo.
No campo equivalente ao que você quer fazer a alteração, Exemplo **OS** apague os _required_ deixando somente o 'trim'

Obs: só apague os required's dos campos que você tirou la no primeiro arquivo.

Pronto!! salve e faça o teste para ver se funciona.

</Aloha>

**Comment by gasperpb** [comment]
> @gasperpb Você tem que entrar em dois arquivos diferentes para tirar a obrigatoriedade dos campos.
> 
> Procure na pasta application>views, nessa pasta você vai no arquivo que você que fazer a alteração, exemplo adicionar OS (Ordem de Serviço)
> 
> LOCAL: **mapos-4.13.0/application/views/os** (O mesmo serve para clientes, produtos, serviços, etc)
> 
> Arquivo 1 encontrado vamos para o próximo passo...
> 
> Abra o arquivo e procure por **<span class="required"**
> Essa tag faz com que o HTML torne o item obrigatório. Apague-a onde você quer tirar a obrigatoriedade.
> 
> Salve as alterações antes de sair.
> Primeiro arquivo alterado com sucesso!
> 
> .......................................
> 
> Agora sim vamos pro 2º arquivo que é o **form_validation.php**
> 
> LOCAL: **/mapos-4.13.0/application/config**
> 
> Abra o arquivo.
> No campo equivalente ao que você quer fazer a alteração, Exemplo **OS**, apague os _required_ deixando somente o 'trim'
> 
> Obs: só apague os required's dos campos que você tirou la no primeiro arquivo.
> 
> Pronto!! salve e faça o teste para ver se funciona.
> 
> /Aloha;

Deu certo Obrigado

**Comment by TVANDRA** [comment]
Boa noite a todos! 
Fiz exatamente o que foi descrito pelo @SalcThy , editei os dois arquivos e não deu certo.
Os campos que editei passaram a não exibir mais o * de campo obrigatório, porém ao tentar seguir para a inclusão de um cliente por exemplo, exibe a mensagem : "campo requerido"
Podem me ajudar ? Obrigado !!!!
