### ISSUE TITLE
Aprovação de OS pelo cliente e Finalização da OS com PDF assinado

### ISSUE THREAD

**Issue by aldemirjunior** [RamonSilva20/mapos#863]
Seria bom acrescentar um método do cliente aprovar a OS apenas com um aceita através de link na area do cliente ou por e-mail enviado solicitando aceite no orçamento ou até mesmo dando aceite de finalização da OS.
Outra sugestão é de ter a possibilidade de salvar junto da OS um arquivo digitalizado em PDF com a ordem assinada pelo cliente e pelo técnico responsável pelo atendimento, quando está for impressa e assinada pelo cliente no ato da retirada do equipamento ou finalização do serviço realizado fora do estabelecimento.

**Comment by hoshikawakun** [comment]
Sobre o arquivo PDF da os assinado pelo cliente e pelo técnico vc poderia ao cliente fazer a retirada do aparelho e assinar a os vc escanear e anexar a mesma nos anexos da referida OS

**Comment by Pr3d4dor** [comment]
Assinatura direto no sistema não é trivial de fazer, recomendo fazer como o @hoshikawakun disse.

**Comment by hoshikawakun** [comment]
mas seria interessante na area do cliente ter na OS 2 Botões
Aprovar em verde
Recusar em vermelho
que ao cliente clicar em um desses botões abrirt um PopUp perguntando se ele tem certeza de estar Cancelando ou Aprovando
e apos confirmar o Status da OS e alterado e os botões somem para aquela OS, igual ao botão faturar, que apos a OS estar Faturada o botão some

**Comment by Gabrielhantoll** [comment]
> mas seria interessante na area do cliente ter na OS 2 Botões
> Aprovar em verde
> Recusar em vermelho
> que ao cliente clicar em um desses botões abrirt um PopUp perguntando se ele tem certeza de estar Cancelando ou Aprovando
> e apos confirmar o Status da OS e alterado e os botões somem para aquela OS, igual ao botão faturar, que apos a OS estar Faturada o botão some

Isso seria excelente =D

**Comment by cabralwms** [comment]
Tambem gostei da ideia. Muito util para facilitar para os clientes e para nos que estamos fazendo tambem todo serviço.
