### ISSUE TITLE
Data e hora da OS

### ISSUE THREAD

**Issue by aldemirjunior** [RamonSilva20/mapos#864]
Uma idéia que talvez não seja tão dificil de ser implementada, é incluir a hora de abertura da OS e depois de finalização da OS. Exibindo também na tela e na impressão a quantidade de horas gastas para realizar o serviço.
É muito útil para serviços de atendimento a clientes que pagam por hora técnica.

**Comment by Pr3d4dor** [comment]
Obrigado, iremos implementar quando possível.

**Comment by aldemirjunior** [comment]
Me disponho até a patrocinar algumas horas para desenvolver. Incluindo também um meio para controle de contrato por hora.
Por exemplo, a empresa me contrato para prestar serviços pelo numero X de horas mensal e as O.S. vão sendo geradas e descontando desse saldo de horas mensais, quando estiver prestar a esgotar as horas, ele avisa e permite serem consumidas horas além do contratado com faturamento a parte dessas horas extras contrato.

**Comment by Pr3d4dor** [comment]
@aldemirjunior Iniciei a implementação do mesmo em #867, apenas gostaria de saber onde você acha que seria interessante exibir quantas horas foram gastas naquela OS (impressão, visualuzarOs, etc).

Sobre a parte de controtado por hora, creio que seja melhor implementar em uma outra pull request, após essa primeira parte estar OK e também se outros usuários precisarem dessa funcionalidade.

Eu mudei as colunas `dataInicial` e `dataFinal` no banco de dados para de `DATE` para `DATETIME` e também ajustei os campos nos formulários para permitir a escolha da hora. Assim é possível calcular quantas horas foram gastas naquela os.

**Comment by aldemirjunior** [comment]
@Pr3d4dor Agradeço muito a iniciativa e disponibilidade. Quanto a visualização de horas gastas é interessante que fique registrado tanto da OS, como em um possível relatório que pode ser gerado filtrando o cliente e o consultor que realizou o atendimento, assim poderíamos ao final de cada mês ter o quantitativo de horas gastas para aquele cliente especifico e o técnico que atendeu também poder receber suas comissões, caso seja esse o cenário que o fornecedor de serviços tem.
Um ponto que não me atentei que pode fazer parte dessa funcionalidade é ter um campo para registrar as horas de intervalo, por exemplo para almoço e essas serem descontadas do resultado final de cada OS.
Só nisso já se tem boa parte do controle que a questões dos contratos necessita.
Quando for gerar outro modulo a partir de nova pull request, já tem o resultado das horas para serem descontadas do controle de contratos por hora de serviço.
Acredito que tudo isso que estou colocando aqui é muito útil para vários prestadores de serviços.

**Comment by aldemirjunior** [comment]
![image](https://user-images.githubusercontent.com/56769618/87861639-27a7e700-c916-11ea-91db-ea6f867e7403.png)

Exemplo de OS com controle de cliente/tecnico/tipo de atendimento(projeto)/hora.

**Comment by Pr3d4dor** [comment]
@aldemirjunior Adicionei a parte de intervalo, gostaria de saber se lhe atenderia:
![image](https://user-images.githubusercontent.com/13210429/88116459-fc7bfc80-cb8e-11ea-8834-072972787557.png)

**Comment by aldemirjunior** [comment]
@Pr3d4dor ficou perfeito. Eu consigo ver um relatório com essa informação de total de horas para um cliente específico e em período específico?

**Comment by Pr3d4dor** [comment]
@aldemirjunior Esses são os próximos passos, ainda vou implementar o relatório de horas. Mas antes disso vou colocar na impressão a parte de horas.

**Comment by aldemirjunior** [comment]
Boa noite. Não conseguimos evoluir?

**Comment by Pr3d4dor** [comment]
Boa noite @aldemirjunior, conseguimos sim, só estou esperando a última PR que o tonny fez ser atualizada e feita o merge para não dar conflito na parte que eu fiz.

Fora isso só falta o relatório de horas e vai estar ok.

**Comment by aldemirjunior** [comment]
Deu certo?

**Comment by Pr3d4dor** [comment]
@aldemirjunior Deu certo sim, infelizmente vou ter que seguir sem a parte do tonny, a parte de salvar o horário na OS já está pronto. Vou apenas finalizar o relatório e vai estar OK.

Queria as melhorias que o tonny fez também, mas ele não atualizou mais a PR, então vou seguir sem elas.

**Comment by Fmpa2k20** [comment]
.

**Comment by aldemirjunior** [comment]
@Pr3d4dor Novidades?

**Comment by Pr3d4dor** [comment]
@aldemirjunior Tudo parado ainda, a PR não foi atualizada, no fim das contas terei que fazer o merge sem espera ela. Apenas preciso corrigir os demais bugs das outras issues antes.
