### ISSUE TITLE
Após Atualização versão 4.11.0 Relatorios nao funcionam.

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#866]
Fiz a Atualização atravez do modo antigo. Baixei o arquivo zip, instalei normal fiz as alterações e então nenhum dos relatorios estão sendo gerados. Será que aconteceu algo no pacote.?

**Comment by RamonSilva20** [comment]
Olá @cabralwms, é necessário atualizar também via composer, foi adicionada uma nova dependência.

**Comment by cabralwms** [comment]
Eu Fiz a instalação do zero, baixei a pasta, extrai e então configurei. Mas nada dos relatorios. vou fazer o teste com banco de dados sem informação. fazer do zero mesmo.

**Comment by cabralwms** [comment]
Eu fiz a instalacao do zero com banco de dados sem os dados e funcionou. como verifico o problema agora?

**Comment by Pr3d4dor** [comment]
@cabralwms configurou corretamente os dados do emitente, inclusive a logo?
