### ISSUE TITLE
Atualização 4.11.0

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#868]
Pessoal fiz a atualização do sistema, quando eu utilizo o banco de dados que já esta em uso no 4.10.0 da erro nos relatorios, se eu deixar o banco de dados sem o backup funciona. Alguem mais teve algum problema nessa atualização. como verifico os logs de erros. No meu apache2 nao mostra erros nos logs.

**Comment by Pr3d4dor** [comment]
Recomendo realizar a instalação limpa do zero, sem utilizar o atualizador e após isso importar o backup.

Após isso, abra o arquivo `index.php` e mude a linha 59 de: `define('ENVIRONMENT', 'production');` para `define('ENVIRONMENT', 'development');`. Assim você irá poder ver o erro que está acontecendo.

**Comment by cabralwms** [comment]
O Backup como arquivo ele não importa, dá um erro, eu faço o backup pelo phpmyadmin so que ai os relatorios nao funcionam

**Comment by cabralwms** [comment]
eu instalei no modo antigo sem o atualizador

**Comment by Pr3d4dor** [comment]
Faça o que eu disse sobre o arquivo `index.php` para poder ver o erro.

**Comment by cabralwms** [comment]
Devo Realizar o backup pelo painel do sistema em configurações?
esse eu tentei tambem nao importa da erro dizendo que já existe a tabela OS

**Comment by cabralwms** [comment]
vou fazer e já retorno aqui obrigado meu amigo

**Comment by Pr3d4dor** [comment]
@cabralwms para usar o backup de dentro do painel você apenas precisa criar o banco de dados (sem nenhuma tabela), por isso que ao importar ele dá o erro de tabela já existente.

**Comment by cabralwms** [comment]
Predador, o erro era que eu nao atualizei o logo, tipo aparecia para mim como o logo estivesse lá, mais quando eu cliquei em atualizar o logo e ai enviei o arquivo ai funcionou. Obrigado pelo apoio
