### ISSUE TITLE
Arquivos em anexo no sistema

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#870]
Bom dia pessoal. Apos atualizar o sistema eu apaguei todas as pastas e entao os arquivos em anexo estao dando erro. nao consigo excluir para colocar de novo. como devo proceder?

**Comment by Pr3d4dor** [comment]
@cabralwms delete tudo que tem na tabela arquivos pelo phpmyadmin

**Comment by Pr3d4dor** [comment]
@cabralwms você precisa manter a pasta anexos, senão os valores no banco ficam errados.
