### ISSUE TITLE
Rodapé e Cabeçalho na impressão

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#871]
Olá pessoal!
Eu gostaria de remover o cabeçalho e o rodapé da impressao (pdf/A4) não quero que o PDF leve o endereço da pagina, nem data e hora, nem nada ... somente o conteúdo da OS.

É possível fazer essa alteração? 
Se sim, como faço? ^^"

**Comment by aldemirjunior** [comment]
Cabeçalho e rodapé em impressão é configuração do Navegador de Internet que estiver usando.
