### ISSUE TITLE
Campo equipamento não aparece

### ISSUE THREAD

**Issue by SMARTNOTETB** [RamonSilva20/mapos#872]
Instalei rodou mais o campo equipamento não aparece

**Comment by Gabrielhantoll** [comment]
No meu também não. gostaria muito =/

**Comment by cabralwms** [comment]
Foi adicionado campo equipamento? aqui tambem nao aparece isso.

**Comment by Pr3d4dor** [comment]
Vou esperar o @hoshikawakun compartilhar o que ele fez e fazer o merge assim que possível.
