### ISSUE TITLE
Usuário expirado 

### ISSUE THREAD

**Issue by Welder01** [RamonSilva20/mapos#873]
Bom dia a todos, alguém teria o arquivo sql já corrigido o problema de usuário expirado ?

Agradeço muito se alguém compartilhar .. obrigado !!

**Comment by hoshikawakun** [comment]
use o phpMyadmin e vai na tabela dos usuarios, coluna dataExpiracao e coloque 3000-01-01

**Comment by Welder01** [comment]
Obrigado !!! 

Consegui, UPPP !!
