### ISSUE TITLE
Erro : Email Falha

### ISSUE THREAD

**Issue by Bruno28121** [RamonSilva20/mapos#874]
** Descreva o bug **
Falha no envio de email

!

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

![image](https://user-images.githubusercontent.com/44698317/88071980-e1879900-cb4a-11ea-8cbb-7d2c2873b1c7.png)

** Contexto adicional **
Versao do sistema: 4.2.2

$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;
$config['smtp_user']        = 'unireparacoes@gmail.com';
$config['smtp_pass']        = '*************';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

**Comment by willph** [comment]
Por motivo de segurança editei seu password.

Mas por via das dúvidas, alterar a senha deste email que você colocou.

**Comment by Bruno28121** [comment]
> Por motivo de segurança editei seu password.
> 
> Mas por via das dúvidas, alterar a senha deste email que você colocou.

Muito Obrigado e voce sabe como devo ajustar o e-mail para que possa funcionar ?

**Comment by Pr3d4dor** [comment]
@Bruno28121 você precisa alterar as configurações de segurança no gmail para permitir aplicativos menos seguros de acessar.

**Comment by Bruno28121** [comment]
> @Bruno28121 você precisa alterar as configurações de segurança no gmail para permitir aplicativos menos seguros de acessar.

Oi entao eu configurei mas mesmo assim agora esta ficando como pendente e nao vai .
$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;
$config['smtp_user']        = 'admin@unireparacoes.com';
$config['smtp_pass']        = '*********';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

**Comment by Bruno28121** [comment]
$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;
$config['smtp_user']        = 'admin@unireparacoes.com';
$config['smtp_pass']        = '********';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

**Comment by Bruno28121** [comment]
> @Bruno28121 você precisa alterar as configurações de segurança no gmail para permitir aplicativos menos seguros de acess

Ainda estou precisando de ajuda , neste caso , ja configurei como voce me informou, mas nao vai os e-mails

**Comment by Pr3d4dor** [comment]
@Bruno28121 preciso de um log mais detalhado dos erros para poder te ajudar.

**Comment by GuilhermeDischer** [comment]
Estou com o mesmo problema do envio, ele fica parado em pendente

**Comment by Bruno28121** [comment]
> @Bruno28121 preciso de um log mais detalhado dos erros para poder te ajudar.

![image](https://user-images.githubusercontent.com/44698317/89308465-aad07900-d648-11ea-98bb-f801e47a5356.png)

<?php

$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;
$config['smtp_user']        = 'unireparacoes@gmail.com';
$config['smtp_pass']        = '*********';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.


Onde posso pegar algo mais ?

**Comment by Bruno28121** [comment]
> @Bruno28121 preciso de um log mais detalhado dos erros para poder te ajudar.

<?php

$config['protocol']         = 'smtp';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_crypto']      = 'tls'; // tls or ssl
$config['smtp_port']        = 587;
$config['smtp_user']        = 'unireparacoes@gmail.com';
$config['smtp_pass']        = 'tecreparacao2020';
$config['validate']         = true; // validar email
$config['mailtype']         = 'html'; // text ou html
$config['charset']          = 'utf-8';
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = false;
$config['wordwrap']         = false;
$config['priority']         = 3; // 1, 2, 3, 4, 5 | Email Priority. 1 = highest. 5 = lowest. 3 = normal.

![image](https://user-images.githubusercontent.com/44698317/89324572-e0cc2800-d65d-11ea-8883-884e084f3fd1.png)


Se precisar lhe passar os acessos para verificar pra mim eu lhe passo , isso este me trazendo grandes problemas e precisava muito de ajuda mas nao consigo resolver.

**Comment by GuilhermeDischer** [comment]
Voce fez as configurações de cron?

**Comment by Bruno28121** [comment]
> Voce fez as configurações de cron?

onde eu configuro o cron ?
onde fica o arquivo ? e o que preciso colocar la  ?

**Comment by GuilhermeDischer** [comment]
No cpanel, va em configurar cron, no campo comando copie e cole o comando que esta no readme, o que fica atras da palavra php você deve apagar, e depois da palavra php você deve colocar o caminho para o index.php do mapos

**Comment by GuilhermeDischer** [comment]
Nos campos acima de comando você deve colocar o tempo

**Comment by Bruno28121** [comment]
> Nos campos acima de comando você deve colocar o tempo

![image](https://user-images.githubusercontent.com/44698317/89344097-b9845380-d67b-11ea-85f9-b29140d3b8aa.png)
a minha hospedagem so me da opcao de 30 minutos tanto retry , quanto process.

mesmo assim nao sai o e-mail

**Comment by Bruno28121** [comment]
> Então não sei. Preenchi o meu mais ta do mesmo jeito que o seu, sem o envio.

que coisa , e nao tem um outro grupo em o pessoal ajude , porque faz dias que postei aqui e sem sucesso .

**Comment by Bruno28121** [comment]
> Por motivo de segurança editei seu password.
> 
> Mas por via das dúvidas, alterar a senha deste email que você colocou.

consegue nos ajudar com esta solução do email ?

**Comment by Pr3d4dor** [comment]
Olhe os erros na pasta appplication/logs

**Comment by GuilhermeDischer** [comment]
Acehi no emu este erro aqui 
![InkedSem título_LI](https://user-images.githubusercontent.com/66499880/89351772-10dcf080-d689-11ea-9833-c65c06359986.jpg)

**Comment by GuilhermeDischer** [comment]
No mwu encontrei isto:
![Sem título](https://user-images.githubusercontent.com/66499880/89352109-c8720280-d689-11ea-8838-8a6067a4b93b.png)
E ele está sendo executado entre 15 em 15 minutos, como eu fiz a minha configuração

**Comment by Pr3d4dor** [comment]
Esse é o problema, dando erro na coluna ip_address

**Comment by GuilhermeDischer** [comment]
E como eu resolvo?

**Comment by Bruno28121** [comment]
> Esse é o problema, dando erro na coluna ip_address

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2020-08-06 00:30:03 --> 220 smtp.gmail.com ESMTP i7sm2811019qkb.131 - gsmtp
<br /><pre>hello: 250-smtp.gmail.com at your service, [2a02:4780:1:8::2a]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [2a02:4780:1:8::2a]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i7sm2811019qkb.131 - gsmtp
<br />Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br /><pre>From: geral@tecrepara.com
Subject: Ordem de Serviço
To: brunoprojetostecnologias@gmail.com
Reply-To: &lt;geral@tecrepara.com&gt;
User-Agent: CodeIgniter
X-Sender: geral@tecrepara.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;5f2b4f0ad5e3b&gt;
Mime-Version: 1.0

**Comment by Bruno28121** [comment]
Caso Resolvido !! 
Obrigado , liberei o acesso de app menos seguro nas configurações do gmail e funcionou.
Obrigado a todos pelo apoio e dedicação
