### ISSUE TITLE
Ideia do projeto é ótimo, mas...

### ISSUE THREAD

**Issue by tonnybarros** [RamonSilva20/mapos#875]
Olá, eu trabalho há 20 anos com eletrônica, e vou deixar algumas sugestões de quem usa software há vários anos.
1- A mais importante, dá mais atenção no que é o principal, ORDEM DE SERVIÇO, eu testei, achei bacana, mas o formulário de abertura da ordem de serviço é muito básico, levando qualquer atendente que usa o sistema a fazer um verdadeira bagunça e deixar tudo fora do padrão.
Peço que a abertura deveria ser por MARCA, MODELO, NÚMERO DE SERIE e ALGUM CAMPO CUSTOMIZA.
Também já li que o desenvolvedor não quer fazer grandes modificações no código, eu entendo, mas isso tornaria o uso profissional.

2- consulta simples online por parte do cliente por ordem de serviço, nem todos ao abrir ordem de serviço gostam de dá cpf ou cnpj.

3- Possibilidade de customizar o número da ordem de serviço, imagina quem já tem um sistema com mais de 10000 OSs, e querer usar esse sistema, e voltar a usar OS, 1, 2 3...

4- Diferentes de muitos aqui, a data final da ordem de serviço é um erro se obrigatória na abertura da OS, porque essa data tem que simbolizar a saída do aparelho. E deveria ser gravada pelo sistema no encerramento, se a possibilidade do usuário alterar.

5- Para lojas de manutenção, onde o preço é dado junto mão de obra e peça, o sistema não entende, porque é exigi o produto e/ou serviço é obrigatório ser cadastrado ANTES, e o certo seria na aba serviços ter a possibilidade de colocar o serviço sem precisar ser cadastrado antes.

Tenho várias indicações de melhoria, mas sei que não vão levar em conta por conta de modificações no código.
Eu vou tentar alterar aqui o que for possível porque gostei do projeto, tem tudo para ser grandioso.

Parabéns ao desenvolvedor.

**Comment by tonnybarros** [comment]
Veja 
![os](https://user-images.githubusercontent.com/68646516/88188381-27f1fc00-cc0e-11ea-9afc-c81d8c0103a2.png)

**Comment by xadun** [comment]
Boa tarde @tonnybarros,

Gostei das suas idéias.
Estou me aventurando em programação a algum tempo (hobby) e um amigo solicitou criarmos um sistema de OS. Por sorte encontramos o Mapos e não precisaremos começar do zero.
A questão é que nós também temos bastante sugestão de "melhorias" e, conforme já foi dito pelo desenvolvedor do sistema, eles estão focando no desenvolvimento do MAPOS no framework Laravel (este utiliza Codeigniter) e não irão mais implementar novos features nesse framework, apenas correções de bugs, sendo assim, eu e meu amigo decidios nós mesmos irmos impementando algumas coisas.

Fique a vontade para postar mais ideias por aqui.

Só uma dúvida: que sistema é esse que você mandou o print?

**Comment by tonnybarros** [comment]
Esse eu uso, é shoficina, é bom o sistema, e tem acesso online, mas só para informação, veja:
https://loja.tectonny.com.br/FERYWLCHYJ/CSWZIK

Eu modifiquei acessar pelo meu site, originalmente só pelo site do desenvolvedor.

Eu vi que um usuário chegou perto do que precisamos
https://github.com/RamonSilva20/mapos/issues/164

Mas não achei as fontes, acredito que para separar, aparelho, marca, modelo, série, vamos precisar criar novas tabelas no banco.

**Comment by tonnybarros** [comment]
Estou adicionando os campos que preciso, mas não sei se fica confiável para futura atualizações.
![os](https://user-images.githubusercontent.com/68646516/88349429-67ac0700-cd26-11ea-97b4-fe47d598cfe8.png)

**Comment by hoshikawakun** [comment]
> 
> 
> Estou adicionando os campos que preciso, mas não sei se fica confiável para futura atualizações.
> ![os](https://user-images.githubusercontent.com/68646516/88349429-67ac0700-cd26-11ea-97b4-fe47d598cfe8.png)

bem legal essas alterações que fez, mas como ficaria no caso do cliente levar de uma vez varios equipamentos diferentes?

**Comment by tonnybarros** [comment]
Nesse caso não muda o que o projeto já tem, é só abri várias OS para o mesmo cliente.
O exemplo acima é de uma aparelho cadastrado.
Tela de edição, também modifiquei a de entrada, e visualização.

Adicionei também na pesquisa, a resposta para pesquisa por modelo e série do aparelho, que no projeto original não tem.

Dá para fazer muita coisa.

Estou no momento tentando fazer a pesquisa do cliente por OS, no momento está por CPF e EMAIL, o que não acho legal

**Comment by tonnybarros** [comment]
Quem quiser ajudando nas idéias.
https://loja2.tectonny.com.br/

Cliente
https://loja2.tectonny.com.br/index.php/mine
Quero remover cpf e e-mail e colocar por celular e OS

**Comment by hoshikawakun** [comment]
> 
> 
> Nesse caso não muda o que o projeto já tem, é só abri várias OS para o mesmo cliente.
> O exemplo acima é de uma aparelho cadastrado.
> Tela de edição, também modifiquei a de entrada, e visualização.
> 
> Adicionei também na pesquisa, a resposta para pesquisa por modelo e série do aparelho, que no projeto original não tem.
> 
> Dá para fazer muita coisa.
> 
> Estou no momento tentando fazer a pesquisa do cliente por OS, no momento está por CPF e EMAIL, o que não acho legal

Eu fiz desse modo

![Screenshot_39](https://user-images.githubusercontent.com/1253576/88438918-20824c80-cde0-11ea-93fe-ae338aab66a8.png)

![Screenshot_40](https://user-images.githubusercontent.com/1253576/88438953-3abc2a80-cde0-11ea-8141-2fe9dfd559f8.png)

**Comment by hoshikawakun** [comment]
assim vc cria a OS com infos basicas, depois vai e coloca os equipamentos na mesma OS, axo mais facil

**Comment by hoshikawakun** [comment]
> 
> 
> Quem quiser ajudando nas idéias.
> https://loja2.tectonny.com.br/
> E-mail: [admin@admin.com](mailto:admin@admin.com)
> Senha: admin
> 
> Cliente
> https://loja2.tectonny.com.br/index.php/mine
> Quero remover cpf e e-mail e colocar por celular e OS

colocar por celular e OS axo que seria um pouco complicado pois a OS o cliente pode ter varias
e CPF o cliente tem apenas 1
oque seria realmente interessante e se fosse o Email e uma senha para o cliente acessar a area dele

**Comment by tonnybarros** [comment]
Vdd, ou celular e senha, muitas pessoas mas velhas se enrola com e-mal.

Gostei do método de add OS, compartilha conosco

**Comment by tonnybarros** [comment]
O que sinto falta também, é um botão na tela de OS, para encerrar essa OS, informando o novo status, é como eu tenho no meu sistema atual

**Comment by tonnybarros** [comment]
> > Nesse caso não muda o que o projeto já tem, é só abri várias OS para o mesmo cliente.
> > O exemplo acima é de uma aparelho cadastrado.
> > Tela de edição, também modifiquei a de entrada, e visualização.
> > Adicionei também na pesquisa, a resposta para pesquisa por modelo e série do aparelho, que no projeto original não tem.
> > Dá para fazer muita coisa.
> > Estou no momento tentando fazer a pesquisa do cliente por OS, no momento está por CPF e EMAIL, o que não acho legal
> 
> Eu fiz desse modo
> 
> ![Screenshot_39](https://user-images.githubusercontent.com/1253576/88438918-20824c80-cde0-11ea-93fe-ae338aab66a8.png)
> 
> ![Screenshot_40](https://user-images.githubusercontent.com/1253576/88438953-3abc2a80-cde0-11ea-8141-2fe9dfd559f8.png)

Tem mais campos para adicionar.

**Comment by BESystemInfo** [comment]
> > Nesse caso não muda o que o projeto já tem, é só abri várias OS para o mesmo cliente.
> > O exemplo acima é de uma aparelho cadastrado.
> > Tela de edição, também modifiquei a de entrada, e visualização.
> > Adicionei também na pesquisa, a resposta para pesquisa por modelo e série do aparelho, que no projeto original não tem.
> > Dá para fazer muita coisa.
> > Estou no momento tentando fazer a pesquisa do cliente por OS, no momento está por CPF e EMAIL, o que não acho legal
> 
> Eu fiz desse modo
> 
> ![Screenshot_39](https://user-images.githubusercontent.com/1253576/88438918-20824c80-cde0-11ea-93fe-ae338aab66a8.png)
> 
> ![Screenshot_40](https://user-images.githubusercontent.com/1253576/88438953-3abc2a80-cde0-11ea-8141-2fe9dfd559f8.png)

Teria como compartilhar essa modificação? É exatamente o que eu havia solicitado mas não consegui implementar (Não sou programador =( )

**Comment by hoshikawakun** [comment]
> 
> 
> O que sinto falta também, é um botão na tela de OS, para encerrar essa OS, informando o novo status, é como eu tenho no meu sistema atual

Para isso vc tem que abrir a OS em Editar, e clicar no botão Faturar, assim que a mesma e faturada ela ja muda o status dela

**Comment by tonnybarros** [comment]
Bom analisando bem aqui, eu vou tentar modificar o sistema para usar no lugar do meu software offline.

1- adicionar cliente sem CPF ou CNPJ
2- adicionar OS diretamente da tela do cliente
3- adicionar nova OS diretamente da tela de OS do cliente
4- adicionar OS sem a obrigatoriedade de pré cadastrar o serviço.
5- remover data final para OS
6- adicionar nova OS por tela modal direto da tela do cliente
7- adicionar  histórico de alterações e/ou contato da OS
8- Modificar a tela de cliente para verificar sua OS apenas por número da OS e celular
9- Aceitar a OS pelo cliente online
10- reformulação da tela de OS
11- adicionar informação de data de entrega da OS
12- Criar um calendário mostrando a data prevista de entrega de cada OS

**Comment by borgesjsb** [comment]
> Esse eu uso, é shoficina, é bom o sistema, e tem acesso online, mas só para informação, veja:
> https://loja.tectonny.com.br/FERYWLCHYJ/CSWZIK
> 
> Eu modifiquei acessar pelo meu site, originalmente só pelo site do desenvolvedor.
> 
> Eu vi que um usuário chegou perto do que precisamos
> #164
> 
> Mas não achei as fontes, acredito que para separar, aparelho, marca, modelo, série, vamos precisar criar novas tabelas no banco.

Shoficina é top mas é pago, eu até tenho ele craqueado mas nao vem ao caso, não é bom por isso. Entendo ser completo. Eu coloquei o mapos no meu site pq eu sinto que nao devo ficar com um programa que me é cobrado sendo que eu posso ter um free. Este desenvolvedor é muito bom. Se tiver alguem que consiga prosseguir com esse legado ficará muito legal. Hoje com essa pandemia me ferrou pq eu sou analista de TI até queria programar mas sem trampo nao posso estudar pra implementar essas OS. Ta tenso pra todo mundo. Tem tambem uma tabela de desconto no final que poderia ser implementada. Tipo quero dar 50 reais de desconto. Abate no valor e pronto. Mas isso é uma idéia e vou ser sincero brasileiro usa muito. "se for a vista fica quanto?" nossa isso me corroi por dentro. kkkk

**Comment by tonnybarros** [comment]
Eu sou usuário pago do shoficina, e vou usar ele como exemplo para modificar o mapos para ficar próximo das funções que eu uso na última versão do shoficina.

O descontos tem no shoficina, posso trazer como função para esse.

**Comment by tonnybarros** [comment]
![os2](https://user-images.githubusercontent.com/68646516/88755490-ab907900-d137-11ea-8a25-b82505f9a4d9.png)
Fixei os dados do cliente no topo, mesmo mudando de aba, os dados estarão sempre ali

**Comment by tonnybarros** [comment]
Na tela de cliente eu removi o acesso por cpf e coloque por chave (ou senha).
https://loja2.tectonny.com.br/index.php/mine

**Comment by tonnybarros** [comment]
Na tela de cadastrar OS, eu aproveitei o código de autocomplete que busca o nome conforme escreve, para o campo marca e aparelho, para agilizar o cadastro, e pode também cadastrar nova marca ou aparelho sem a necessidade de usar o que aparece na buscar.

**Comment by kalukramer** [comment]
Eu alterei toda a estrutura do programa, incluindo as tabelas da base de dados para suportar mais registos, alterei o acesso aos clientes, agora podem interagir com a OS e receberem mails e enviarem, podem fazer pedidos de recolhas e aprovar orçamentos.
![image](https://user-images.githubusercontent.com/17726525/88860243-34201f80-d1f3-11ea-99e4-bc5a7ff62905.png)

**Comment by MarceloGrass** [comment]
Gostei das alterações feitas no https://loja2.tectonny.com.br/ parabéns!!!
Principalmente nas OS.
Para levar essas alterações para a minha instalação teria que substituir alguns arquivos? quais seriam? poderiam disponibiliza-los?

**Comment by tonnybarros** [comment]
Olá, eu ainda não terminei, mas posso enviar os arquivos alterados sem problemas, quais alteração exatamente quer no momento?

**Comment by BESystemInfo** [comment]
@tonnybarros parabéns pelas alterações. Eu também gostaria, se possível, da parte de equipamentos.

**Comment by MarceloGrass** [comment]
> 
> 
> Olá, eu ainda não terminei, mas posso enviar os arquivos alterados sem problemas, quais alteração exatamente quer no momento?

A parte das OS, os detalhes de equipamentos, o nome do cliente que aparece nas OS já criadas quando vai na edição.

(Tela de edição, também modifiquei a de entrada, e visualização)
(Fixei os dados do cliente no topo, mesmo mudando de aba, os dados estarão sempre ali)
(Na tela de cadastrar OS, eu aproveitei o código de autocomplete que busca o nome conforme escreve, para o campo marca e aparelho, para agilizar o cadastro, e pode também cadastrar nova marca ou aparelho sem a necessidade de usar o que aparece na buscar.)

Essas alterações são as mais relevantes, achei top. 

O fato do cliente entrar com CPF, telefone ou e-mail já vai na opinião de cada um, na minha experiência o CPF se formos analisar hoje em dia nos é solicitado para praticamente tudo, então não vejo isso como algo invasivo, faz umas semanas tive um inconveniente com um cliente que não deu nome somente o telefone e precisei do nome completo ou CPF dele e não tinha, nem no Whatsapp aparecia o nome, então no meu caso acho muito interessante a partir de agora solicitar o CPF e a boa desculpa é que ele serve para acessar o Sistema. 
Qualquer pessoa que queira nos dar um golpe ou até se um equipamento for roubado ou solicitado por outra pessoa nos temos a identidade da pessoa que entregou o equipamento para o reparo. 
Infelizmente não tenho muito conhecimento de php somente de html e worpress mas no que puder ajudar contem comigo, abraço.

**Comment by tonnybarros** [comment]
![noos](https://user-images.githubusercontent.com/68646516/89100790-8ff3cf80-d3d0-11ea-9a87-36fb12978e1a.png)
Eu parei na modificação da OS, porque estava editando a tela de info de cliente, o mapos usa jquery e bootstrap muito antigo, por hora fiz assim, vou voltar para as modificações de uso, e no futuro temos que pensar em um novo tema com jquery e bootstrap atualizado.

**Comment by tonnybarros** [comment]
> Eu alterei toda a estrutura do programa, incluindo as tabelas da base de dados para suportar mais registos, alterei o acesso aos clientes, agora podem interagir com a OS e receberem mails e enviarem, podem fazer pedidos de recolhas e aprovar orçamentos.
> ![image](https://user-images.githubusercontent.com/17726525/88860243-34201f80-d1f3-11ea-99e4-bc5a7ff62905.png)

Eu penso em algo assim, mas criar uma nova aba para VISITA TÉCNICA, para fazer um pré cadastro, e preencher os dados de visita para retirar na casa do cliente.
Tem o teste do seu?

**Comment by kalukramer** [comment]
> > Eu alterei toda a estrutura do programa, incluindo as tabelas da base de dados para suportar mais registos, alterei o acesso aos clientes, agora podem interagir com a OS e receberem mails e enviarem, podem fazer pedidos de recolhas e aprovar orçamentos.
> > ![image](https://user-images.githubusercontent.com/17726525/88860243-34201f80-d1f3-11ea-99e4-bc5a7ff62905.png)
> 
> Eu penso em algo assim, mas criar uma nova aba para VISITA TÉCNICA, para fazer um pré cadastro, e preencher os dados de visita para retirar na casa do cliente.
> Tem o teste do seu?

Boas.
Eu só trabalho para empresas, eles já estão, cadastrados, só tem que pedir a recolha via aplicação no acesso do cliente, removi a faturação, pois em Portugal você necessita de um programa certificado pelo governo, das nem ter separador no menu nem botão de faturar. Não tenho teste. Todas as semanas acrescentamos funcionalidades novas na aplicação, a pedido dos clientes. Agora estamos a introdusir a possibilidade de o cliente cadastrar o equipamento entes da recolha, ao recebermos, validamos o registo e acrescentamos promenores do pc, do tipo, teclado sem teclas, sem carregador, etc

**Comment by tonnybarros** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/68646516/89115579-4fdc2d80-d460-11ea-83fe-1ac9b3a0231e.png)
![Screenshot (1)](https://user-images.githubusercontent.com/68646516/89115581-5074c400-d460-11ea-8c8e-580fbf92443e.png)
![Screenshot](https://user-images.githubusercontent.com/68646516/89115582-510d5a80-d460-11ea-9836-71915ff3f549.png)

Para quem quiser ir acompanhando.

Modificações de layout, ainda vou pensar em funcionalidades

**Comment by MarceloGrass** [comment]
> 
> 
> ![Screenshot (2)](https://user-images.githubusercontent.com/68646516/89115579-4fdc2d80-d460-11ea-83fe-1ac9b3a0231e.png)
> ![Screenshot (1)](https://user-images.githubusercontent.com/68646516/89115581-5074c400-d460-11ea-8c8e-580fbf92443e.png)
> ![Screenshot](https://user-images.githubusercontent.com/68646516/89115582-510d5a80-d460-11ea-9836-71915ff3f549.png)
> 
> Para quem quiser ir acompanhando.
> 
> Modificações de layout, ainda vou pensar em funcionalidades

Muito bom amigo parabéns!!! grande melhora nos detalhes, pode compartilhar essas alterações?

**Comment by tonnybarros** [comment]
Eu devo terminar essa semana, vou disponibilizar os views da pasta os, e controle com as alterações do banco.

**Comment by MarceloGrass** [comment]
> 
> 
> Eu devo terminar essa semana, vou disponibilizar os views da pasta os, e controle com as alterações do banco.

Muito obrigado amigo!!!

**Comment by Alexarciol** [comment]
Bom dia @tonnybarros !

Desculpe a pergunta: Você vai liberar essas alterações que está realizando acima para todos aqui?

Agradeço desde já e ficou ótimo essas alterações que estão sendo realizadas.

Parabéns.

Alexandre Arcieri

**Comment by tonnybarros** [comment]
Sim, com certeza, para todos, estou fazendo por conta do que eu acho ideal, mas vcs podem sugerir melhorias.

**Comment by Alexarciol** [comment]
> Sim, com certeza, para todos, estou fazendo por conta do que eu acho ideal, mas vcs podem sugerir melhorias.

Valeu amigo! Abraços! E se eu tiver alguma sugestão, compartilho com vc.

**Comment by melezinf** [comment]
> ![Screenshot (2)](https://user-images.githubusercontent.com/68646516/89115579-4fdc2d80-d460-11ea-83fe-1ac9b3a0231e.png)
> ![Screenshot (1)](https://user-images.githubusercontent.com/68646516/89115581-5074c400-d460-11ea-8c8e-580fbf92443e.png)
> ![Screenshot](https://user-images.githubusercontent.com/68646516/89115582-510d5a80-d460-11ea-9836-71915ff3f549.png)
> 
> Para quem quiser ir acompanhando.
> 
> Modificações de layout, ainda vou pensar em funcionalidades

Bom dia, compartilha essa modificação nas ações abrir opções, achei muito boa ideia!

**Comment by tonnybarros** [comment]
Todas as modificações feitas até agora na pasta application.

https://github.com/tonnybarros/application

Lembrando que precisam criar novas colunas na tabela 'os' e 'clientes'

**Comment by Alexarciol** [comment]
Bom dia @tonnybarros !

Na tabela de 'clientes', quais as colunas precisam serem criadas? 

Abraços!

**Comment by tonnybarros** [comment]
Perdão, seria a  'chaveweb'

Mas isso somente se for querer o acesso do cliente por senha e não cpf

**Comment by tonnybarros** [comment]
Se tiverem dúvidas ou deu algum erro, manda foto do erro para mim 21-979123851

Nem sempre respondo na hora, mas sempre respondo.

**Comment by tonnybarros** [comment]
Pessoal, postei o projeto todo original com as modificações

https://github.com/tonnybarros/mapos


Quem for usar, atenção no arquivo database.php (editar os dados do banco de dados) e o arquivo config.php (configura a url)

**Comment by willph** [comment]
> Pessoal, postei o projeto todo original com as modificações
> 
> https://github.com/tonnybarros/mapos
> 
> Quem for usar, atenção no arquivo database.php (editar os dados do banco de dados) e o arquivo config.php (configura a url)

Desse projeto da pra criar a Pull request. 

Basta clicar em PULL REQUEST 
![20200806_205354](https://user-images.githubusercontent.com/17226802/89594061-43245480-d827-11ea-8d12-f93f31dea310.jpg)

Depois em CREATE PULL REQUEST 
![Screenshot_20200806-205312_Chrome](https://user-images.githubusercontent.com/17226802/89594099-59321500-d827-11ea-8483-1bc1dcf351bb.jpg)

Aí só aguardar a análise e aprovação.

Lembrando que os arquivos index.php, config.php e database.php não pode ser alterados do original. 

Por fim, seja bem vindo e obrigado pela contribuição.

**Comment by willph** [comment]
Lembrando que tem que finalizar a criação da Pull request. Tem mais um passo após clicar em create Pull request.
Mais é coisa simples.

**Comment by tonnybarros** [comment]
Legal, fiz o procedimento mostrado acima.

**Comment by tonnybarros** [comment]
Deu algum erro
![error](https://user-images.githubusercontent.com/68646516/89642747-c2973f80-d88a-11ea-938e-617a28f4e521.png)
