### ISSUE TITLE
syntax error, unexpected '='

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#876]
depois de tofo procedimento feito deu esse erro
syntax error, unexpected '='
![image](https://user-images.githubusercontent.com/56301435/88203568-6b556600-cc20-11ea-94d3-8e0944718059.png)

**Comment by melezinf** [comment]
Resolvi o mesmo problema atualizando o composer.

**Comment by Pr3d4dor** [comment]
@wesley020291 Qual versão do PHP você está utilizando?
