### ISSUE TITLE
ERRO na consulta de Lançamentos por Situação

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#877]
Ao cadastrar uma venda, não estava inserindo o ZERO na coluna baixado da tabela "lancamentos". Mesmo estando como DEFAULT '0'. por isso, alterei o controller Vendas incluindo as linhas abaixo:

MOTIVO: ao filtrar os lançamentos por situação, estava me gerando "erro" (tabela vazia) pois o campo baixados em "lancamentos" estava NULL. Mesmo com o DEFAULT '0' configurado no campo.

334:            $baixado = $this->input->post('recebido');
335:
336:            if ($baixado != null) {
337:                $baixado = $baixado;
338:            } else {
339:                $baixado = '0';
340:            }

363: 'baixado' => $baixado,

recomendo para a proxima atualização.
**Estou finalizando a inclusão da opção desconto por produto ao lançar os itens na Venda. Queria compartilhar aqui, alguém sabe me dizer como faço? ^^"

**Comment by Pr3d4dor** [comment]
@monutb91 Está usando qual versão do MySQL?
