### ISSUE TITLE
relatório rápido de produtos com estoque mínimo

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#878]
Ao tentar gerar um relatório Rápido de estoque mínimo me retorna uma pagina em branco

**Comment by tonnybarros** [comment]
Como simulo esse erro?
Aqui parece funcionar, entra no meu demo e veja

**Comment by Pr3d4dor** [comment]
Qual exatamente é o erro que está ocorrendo?

**Comment by hoshikawakun** [comment]
> 
> 
> Qual exatamente é o erro que está ocorrendo?

quando clico em relatorio rapido com estoque minimo me abre uma pagina simplismente em branco, sem nenhuma informação

notei que o codigo dessa parte do relatorio foi muito alterado

**Comment by Pr3d4dor** [comment]
Mude para o modo development para poder ver o erro.

**Comment by hoshikawakun** [comment]
O erro foi resolvido, e que faltava alguns arquivos que não tinham dado erro na transferencia
