### ISSUE TITLE
Como fazer uma Pull request

### ISSUE THREAD

**Issue by hoshikawakun** [RamonSilva20/mapos#879]
Eu fiz umas alterações bem interessantes na minha versão que uso do MapOS, 
Essas alterações são na area de OS acrescentando o campo equipamentos
![Screenshot_39](https://user-images.githubusercontent.com/1253576/88449078-6d831480-ce1a-11ea-933b-1bec4b41ee45.png)
![Screenshot_40](https://user-images.githubusercontent.com/1253576/88449081-72e05f00-ce1a-11ea-8ace-dd160d8dd86f.png)

fiz também algumas alterações na area do cliente
Achei por bem remover o botão de excluir anexo da area do cliente mantendo apenas o botão de Download
Achei por bem remover a opção do cliente mesmo criar uma OS
Na fiz algumas alterações nas paginas da area do cliente para que as tabelas aparecessem corretamente e não faltando a linha da parte de baixo
Na pag inicial e na pag de OS coloquei os nomes dos Status das OS para aparecerem coloridos
![Screenshot_44](https://user-images.githubusercontent.com/1253576/88449238-9d7ee780-ce1b-11ea-9764-010498e5b3b1.png)
![Screenshot_45](https://user-images.githubusercontent.com/1253576/88449243-a5d72280-ce1b-11ea-9326-5bc6bdc89e42.png)

E por fim acrescentei mais alguns tipos de Status para se usar nas OS
que no total agora conta com 19 tipos diferentes de status de OS

Editei a tela de Config do sistema e acrescentei mais algumas configurações
dentre elas de personalizar algumas das mensagem que vai de padrão pelo WhatsApp
![Screenshot_46](https://user-images.githubusercontent.com/1253576/88449376-d4093200-ce1c-11ea-8bf4-1e5a609a7845.png)

Toda a pag de impressão tanto do principal no sistema quanto a que o cliente imprime pela area dele
Acrescentei vários campos referentes aos campos novos dos equipamentos
Termo de uso Que vc altera o que será apresentado na tela de config do sistema
Campo de Assinatura que apresenta o nome do Técnico e do Cliente

e gostaria de compartilhar essas alterações que fiz

**Comment by Ricky097** [comment]
seria fantástico se conseguisse partilhar esta modificação

**Comment by TK2KMG** [comment]
Também achei interessantes as modificações. Seria muito bom se pudesse  disponibilizar para os demais. 
Excelente trabalho Hoshlkawakun.

**Comment by acinformatica2004** [comment]
Muito interessante as modificações!! Excelente trabalho!

**Comment by Pr3d4dor** [comment]
@hoshikawakun, você pode tentar criar a PR, porém tem que se atentar que nas últimas, tinha muitas modificações (mais de 120mil linhas) então fica impossível fazer review.

Se você não conseguir, pode tentar me enviar o zip, que eu tento fazer.

**Comment by tonnybarros** [comment]
Aguardando também

**Comment by hoshikawakun** [comment]
> 
> 
> @hoshikawakun, você pode tentar criar a PR, porém tem que se atentar que nas últimas, tinha muitas modificações (mais de 120mil linhas) então fica impossível fazer review.
> 
> Se você não conseguir, pode tentar me enviar o zip, que eu tento fazer.

Aki esta o meu projeto
https://github.com/hoshikawakun/MasterOS/
Tinha perguntado sobre como criar a PR que assim eu entraria no time dos Colaboradores, mas ai acima esta tudo oque eu ja fiz no meu, a base do meu e o 4.1.1, mas toda alteração interessante que tinha no sistema eu consegui implementar na minha versão
 essas foram as ultimas que eu acrescentei/Modifiqei
Alteração em Status de OS
Melhoria na msg do WhatsApp
Adequação para exibir valor de total de OS em home
Adicionando relatório de clientes em xls
Adicionando suporte a HMVC
Atualização Area do Cliente
Adicionando opção Pagamento
Espaçamento no Pagamento da OS
Alterando Posição da listagem de Orçamento
Correção de Espaçamento em Impressão de OS

**Comment by willph** [comment]
Tem o fork do projeto?

Com o projeto no seu github, só baixar ele, adicionar as modificações e depois que subi essas alterações, tem um botão chamado Pull request. Clica nela, criar Pull request e pronto.

Mas você pode pesquisar sobre fork e Pull request.

**Comment by LipzyLipzy** [comment]
Olá hoshikawakun obrigado pela partilha. 
Reparei que está a usar responsável filemanager. Ele está a trabalhar bem no seu projecto? 

Obrigado, abraço

**Comment by acinformatica2004** [comment]
Vc tem ai a base de dados, pois tentei colocar os equipamentos mais da erro, queria ver se as tabelas estão iguais.
Obrigado
