### ISSUE TITLE
Duplicidade de cadastros como resolver?

### ISSUE THREAD

**Issue by brtechst** [RamonSilva20/mapos#880]
Bom dia, estou usando a versão 3.8 do Mapos e gostaria de saber como resolvo esse problema de duplicidade de cadastros. queria que ao colocar qualquer informação do cadastro que ja conste cadastrado ele ou pelo menos o nome do cliente e CPF para evitar pois de vez em quando percebo que aparece cadastros duplicados e até triplicados.

**Comment by Pr3d4dor** [comment]
Você está usando uma versão muito antiga do mapos, por favor atualize para a versão mais recente.

**Comment by brtechst** [comment]
Alguém sabe como resolver para quem está na antiga?

É que minha versão tem muitas modificações e se eu migrar para a nova certamente vai dar problema.

por isso vou tentando resolver os bugs mais simples e depois pagar um programador para fazer tudo isso para mim.

@Pr3d4dor tu consegue fazer essa migração e outra coisas para mim ja que está habituado ao sistema? Eu te pago meu amigo porque sei que tu é fera demais!

me chama no zap 84996008631 e combinamos valores.

Quero lhe pagar porque sei que é competente, aceite minha proposta por favor......

**Comment by Pr3d4dor** [comment]
Não precisa me pagar nada, mas sobre esse problema de duplicidade de cadastros, é somente no cadastro de clientes?

Pois se for isso, é fácil de resolver, basta adicionar a regra unique no campo de CPF do cliente e no nome.

**Comment by brtechst** [comment]
É só nos clientes.

**Comment by brtechst** [comment]
Queria te pagar porque queria unir o meu com as modificações com o novo disponibilizado por vocês que tem muita coisa boa. Além disse queria fazer algumas coisas novas que não tem em nenhuma das versões.

**Comment by brtechst** [comment]
Me chama la no zap depois sem compromisso para pelo menos gerar um orçamento, te agradeço demais se ajudar ai nessas pendências.

**Comment by brtechst** [comment]
qual dessas opções??

![image](https://user-images.githubusercontent.com/53625745/88463404-f9338a00-ce88-11ea-8484-5514898f2959.png)

ou essa?

![image](https://user-images.githubusercontent.com/53625745/88463438-25e7a180-ce89-11ea-8e96-059084cb819e.png)

**Comment by Pr3d4dor** [comment]
Você pode mudar a linha: https://github.com/RamonSilva20/mapos/blob/master/application/config/form_validation.php#L10 à 17, de
```
[
            'field' => 'documento',
            'label' => 'CPF/CNPJ',
            'rules' => 'required|trim|verific_cpf_cnpj',
            'errors' => [
                'verific_cpf_cnpj' => "O campo %s não é um CPF ou CNPJ válido."
            ],
        ],
```
para:
```
[
            'field' => 'documento',
            'label' => 'CPF/CNPJ',
            'rules' => 'required|trim|verific_cpf_cnpj|is_unique[clientes.documento]',
            'errors' => [
                'verific_cpf_cnpj' => "O campo %s não é um CPF ou CNPJ válido.",
                'is_unique' => "Documento já cadastrado."
            ],
        ],
```

**Comment by Pr3d4dor** [comment]
@brtechst, você customizou os campos, mas a regra é `is_unique`

**Comment by Pr3d4dor** [comment]
@brtechst sim, é usando o `is_unique`

**Comment by Pr3d4dor** [comment]
@brtechst não precisa colocar a `verific_cpf_cnpj` pois não tem nessa versão do mapos.

**Comment by brtechst** [comment]
ótimo, vou mudar agora!!

Mas por favor me passa seu número só para eu falar contigo sem compromisso.
