### ISSUE TITLE
Numeração OS

### ISSUE THREAD

**Issue by senefix** [RamonSilva20/mapos#883]
Gostaria de saber se tem como imprimir a OS com o numero dela. Também gostaria de saber se tem como dividir a OS em duas partes, via da loja e via do cliente.

Seria interessante que na impressão saisse o numero da OS em dois pontos, na via do cliente e na via da loja, para localizar com facilidade no deposito de aparelhos prontos.

A seguir um exemplo

![osPADRAO](https://user-images.githubusercontent.com/68816600/88728572-6e60c280-d108-11ea-87d0-57e048b8a802.png)

**Comment by tonnybarros** [comment]
É possível, basta usar o $idOs para pegar o número da OS.Usa echo para colocar onde achar melhor

**Comment by senefix** [comment]
@tonnybarros eu nao manjo de php kkkk vou começar a estudar, porem do inicio, se puder me passar as coordenadas, qual arquivo editar e onde editar, eu ficarei grato

**Comment by tonnybarros** [comment]
Beleza, para mostrar o número da OS é só usar esse código <?php echo $result->idOs ?>
Por padrão já aparece, no seu não apareceu pq vc não configurou o emitente.
Veja o exemplo https://loja2.tectonny.com.br/index.php/os/imprimir/200808
Usuário: admin@admin.com
Senha? admin

**Comment by senefix** [comment]
@tonnybarros bacana, vou configurar agora o emitente, e sobre o echo para fazer a via do cliente, onde eu edito o codigo fonte pra mudar?

**Comment by senefix** [comment]
@tonnybarros é possivel preencher a data automaticamente na impressao da os tb? ou precisa colocar a mão?

queria tirar a obrigatoriedade do campo data final e técnico responsavel. garantia e termos de garantia.

**Comment by tonnybarros** [comment]
> @tonnybarros bacana, vou configurar agora o emitente, e sobre o echo para fazer a via do cliente, onde eu edito o codigo fonte pra mudar?

Nesse caso depende de como é sua nota.
Se vai gerar duas notas em uma folha, basta duplicar o código todo

**Comment by tonnybarros** [comment]
> @tonnybarros é possivel preencher a data automaticamente na impressao da os tb? ou precisa colocar a mão?
> 
> queria tirar a obrigatoriedade do campo data final e técnico responsavel. garantia e termos de garantia.

Já tem no código data de emissão do nota, não seria essa data?

**Comment by senefix** [comment]
@tonnybarros queria saber onde editar o codigo? ja tentei editar alguns codigos porem quando eu abro o mapos4 da algum tipo de erro, e a data é pra aparecer automatico, na impressao parece que tem que preencher a mao, queria saber qual lugar editar para enviar pro servidor, sempre que eu mudo algo da erro na hora de subir pra database do mapos no myphpadmin

**Comment by tecnobeach** [comment]
legal esse seu projeto, como faço para utilizar igual esse, vc disponibiliza? gostaria e saber como alterar o numero de inicio da o.s ao  inves de começar pelo 1 eu queria que começasse com 2008001, poderia dar uma luz, não manjo nada de php
