### ISSUE TITLE
Fiz a atualização via sistema e agora da erro 

### ISSUE THREAD

**Issue by MarceloGrass** [RamonSilva20/mapos#884]
Fiz a atualização via sistema clicando no botão "Atualizar Mapos" em Sistema >> Configurações;

    (Serão baixados e atualizados todos os arquivos exceto: config.php, database.php e email.php;)

e agora da o erro " Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente."

vai pro endereço http://os.notebookcia.com.br/install/index.php automaticamente

MAPOS - Sistema de Controle de Ordens de Serviço

Parece que este aplicativo já está instalado! Você não pode reinstalá-lo novamente.

IR PARA PÁGINA DE LOGIN

 - SO: Windows 10
 - Navegador Firefox
 - Versão 78.0.2

Entendo que não deveria ter acontecido isso, como posso resolve-lo?

**Comment by willph** [comment]
Por favor verifique se a linha 59 do arquivo index.php está ```define('ENVIRONMENT', 'production');```

Caso esteja essa ```define('ENVIRONMENT', 'pre_installation');```

Favor alterar para a que mencionei.

**Comment by MarceloGrass** [comment]
Muito obrigado amigo era isso mesmo. 💯
