### ISSUE TITLE
numero com 9 digitos

### ISSUE THREAD

**Issue by tecnobeach** [RamonSilva20/mapos#885]
no campo de cadastro como posso atualizar o campo de telefone para aceitar 9 digitos? obrigado!

**Comment by tonnybarros** [comment]
Olá, para celular já está assim, mas deseja modificar o fixo?

**Comment by tonnybarros** [comment]
Se precisar realmente trocar do telefone fixo, modifica a máscara no arquivo funcoes.js em assets/js

**Comment by Negan-tec** [comment]
@tonnybarros salvando o dia novamente, bjus. Vlw.
