### ISSUE TITLE
Mapos nao abre aba O.S

### ISSUE THREAD

**Issue by cleyton1408** [RamonSilva20/mapos#886]
** mapos nao abre a aba O.S**
A aba os do meu mapos nao consegui ser carregada

eu tentei trocar o nome do campo 'defeito' para 'modelos do arquivo'

agora a aba os não abre mais!😫

tem como resolver isso sem perder as os que já estão cadastradas lá ?

**Comment by Pr3d4dor** [comment]
@cleyton1408 você mudou esse campo no banco de dados ou somente no código?

**Comment by cleyton1408** [comment]
ola Pr3d4dor!

Eu fui ate a hostinger, -onde o meu mapos esta hospedado-. 

cliquei em banco de dados MySQL

entrei no banco de dados onde o meu mapos esta instalado.

entre em phpMyAdmin, 

então, eu cliquei na 'os' abriu uma aba com todos os campos que estão em OS. estrutura de tabela.

e foi ali que eu tentei mudar o nome de 'defeitos' para 'modelos do arquivo'. 

cliquei + abriu todos os campos, dei dois cliques em defeitos.

apareceu um campo com nomes - títulos - tamanhos/valores - predefinido

foi assim então que eu mudei o nome. clique em 'pre visualizar SQL' apareceu os códigos então eu cliquei em guardar.

percebi que o nome não mudava então, resolvi fazer tudo novamente. 

só que dessa vez que cliquei tambem em 'executar' que esta abaixo. 

da ih pra frente não abriu mais.

todos o mapos abre certinhos mas quando eu clico em 'os' a mensagem que aparece no meu navegador é a seguinte:

ESTA PAGINA ESTA FUNCIONANDO
 corescomamor.com.br não consegue atender a esta solicitação no momento.
HTTP ERROR 500.

depois disso eu cliquei em normalizar, na tentativa de reverter a situação

passei por todos os processos, e nada!

será que eu consigo reverter isso sem perder as 'os' que estão salvas? são muitos clientes!

**Comment by Pr3d4dor** [comment]
@cleyton1408 você pode abrir novamente o PhpMyAdmin e realizar o processo inverso, ou seja, renomear o campo 'modelos do arquivo' para 'defeitos'.

**Comment by cleyton1408** [comment]
já fiz isso mas não resolveu!

**Comment by cleyton1408** [comment]
puxa não sie por que eu fui mexer nisso!

**Comment by cleyton1408** [comment]
na segunda a equipe virá para trabalhar não terá 'os' para se guiarem

**Comment by Pr3d4dor** [comment]
@cleyton1408 você alterou algo a mais além dessa coluna no banco de dados? você por um acaso não alterou também o tipo da mesma?

**Comment by cleyton1408** [comment]
Bom dia Predador... 

Então fera, se eu fiz, fiz de forma inconsciente pois não sei como trocar a conta ainda... 

Não sei como resolver essa questão... acho que vou ter que instalar tudo de novo... mas vou perder todos os dados dos clientes já cadastrado...

E outra coisa esse sistema de vocês e muito bom, tem como eu ajudar vocês financeiramente? Não posso com muito mas gostaria de ajudar!

**Comment by cleyton1408** [comment]
Se eu te der o login você consegui resolver pra mim? Vê quanto custa que eu transfiro pra sua conta...

**Comment by Pr3d4dor** [comment]
@cleyton1408 se puder me enviar o banco de dados compactado eu posso tentar olhar pra você, não precisa me pagar nada.

Além disso, qual versão do mapos você está utilizando?

**Comment by cleyton1408** [comment]
Puxa vida muito obrigado...

Vou te explicar... eu sou Pastor na igreja internacional da graça de Deus do Missionário RR SOARES...

Estou no culto hoje. Assim que eu chegar em casa vou verificar isso pra você... 

Como eu te envio o banco de dados?

**Comment by Pr3d4dor** [comment]
@cleyton1408 Talvez seja mais fácil você me enviar os dados para acessar o PhpMyAdmin ou o mapos, se quiser me envie no e-mail: gian_bine@hotmail.com, porém eu trabalho das 08 às 17:30, então só poderei ver de noite.

**Comment by tonnybarros** [comment]
Conseguiram resolver?

**Comment by cleyton1408** [comment]
Oi meu amigo ainda não...

**Comment by cleyton1408** [comment]
O predador está no trabalho agora só poderá me ajudar na parte da noite...

**Comment by tonnybarros** [comment]
Eu estou no trabalho também, mas faça o seguinte, vai no seu host e cria um novo banco de dados, importa uma base nova do mapos, em /application/config/database.php
Altere os dados do banco atual (salve para colocar de volta quando resolver), e coloque os dados do novo banco de dados, junto com o usuário do banco com as permissões devidamente configurada.

Responda se assim o seu mapos volta a funcionar,

**Comment by cleyton1408** [comment]
tonny, eu tentei aqui mas não consegui, me perdoa cara! eu sei muito pouco sobre esse assunto! eu na época 
paguei a um rapaz para hospedar o mapos pra mim! mas não consigo falar com ele novamente!

ele fez pelo anydesk! 

me desculpa mas mesmo sendo tão obvia sua explicação eu não consegui!

**Comment by tonnybarros** [comment]
21979123851 me chama no zap

**Comment by Pr3d4dor** [comment]
boa noite @tonnybarros e @cleyton1408, ainda precisam da minha ajuda? Só consegui sair agora do trabalho.

**Comment by tonnybarros** [comment]
Foi resolvido, tinha uma tabela errada no banco de dados.
O MapOS dele já está funcionando

**Comment by cleyton1408** [comment]
Pessoal consegui resolver aqui! o amigo Tonny descobriu o erro! Muito obrigado tonnybarros!

Predador vlw por todo empenho! voces são feras! 

Que Deus abençoes a obra das mãos de cada um de vocês!

RESOLVIDOOO!
