### ISSUE TITLE
Como reativar o assistente de instalação?

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#887]
Fiz a instalação, modifiquei conforme minha necessidade e, agora quero reativar o assistente de instalação.
tentei apenas mudar os valores dos campos conforme abaixo, nos arquivos _config.php_ e _database.php_, mas não deu certo :|
`$config['base_url'] = 'enter_baseurl';`

` 'hostname' => 'enter_hostname',

    'username' => 'enter_db_username',
    'password' => 'enter_db_password',
    'database' => 'enter_database_name',
`

**Comment by Pr3d4dor** [comment]
@monutb91 você precisa abrir o arquivo index.php e mudar a linha 59 para: 
```
define('ENVIRONMENT', 'pre_installation');
```

**Comment by monutb91** [comment]
PUTZ! super simples!!! Valeeeu!!! ;)
