### ISSUE TITLE
Pr3d4dor pegar o cliente pelo ID

### ISSUE THREAD

**Issue by tonnybarros** [RamonSilva20/mapos#888]
@Pr3d4dor eu queria pegar o cliente pela a url /index.php/os/adicionar/IDCLIENTE

Tem como me ajudar nessa questão?

Minha ideia é abrir o cliente primeiro, e só depois add OS, na tela de editar isso acontece /index.php/os/editar/2

**Comment by Pr3d4dor** [comment]
Você tem que usar a função `$this->uri->segment(3)` igual a https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php#L176

**Comment by tonnybarros** [comment]
Beleza, tem como criar um box de pesquisa na tela de cliente?

Vou olhar o link

**Comment by Pr3d4dor** [comment]
@tonnybarros Sim, só você verificar como foram feitos os outros autocompletes.

**Comment by tonnybarros** [comment]
> Você tem que usar a função `$this->uri->segment(3)` igual a https://github.com/RamonSilva20/mapos/blob/master/application/controllers/Os.php#L176

Consegui, obrigado.
