### ISSUE TITLE
Erro no login: Os dados de acesso estão incorretos.

### ISSUE THREAD

**Issue by eudinhoaroeira** [RamonSilva20/mapos#889]
Olá boa, estou com problema na hora de logar, o erro é: Os dados de acesso estão incorretos. 
No banco de dados o usuários como e-mail e senha está correto, mais fica constantemente dando esse erro,
Eu troco o email, ai certifico que está lendo o banco de dados, o sistema avisa que está errado.
isso está acontecendo apartir do momento que hospedei no servidor.

**Comment by tonnybarros** [comment]
Olá, enviou sua pasta vendor para sua instalação no host?

**Comment by eudinhoaroeira** [comment]
Sim, acabei de verificar está dentro da pasta application.

**Comment by tonnybarros** [comment]
Como verificou no banco a senha? Criptografado

**Comment by eudinhoaroeira** [comment]
não estou entendendo, a pasta vendor eu verifiquei esta dentro da pasta application, a senha eu vi no banco de dados

**Comment by tonnybarros** [comment]
Vai em seu phpmyadmin, no banco do mapos, tabela usuários, seleciona seu usuário para editar, e altere a senha por lá, colocando isso
`$10$S9ft9y7ODoEcuctGR2R.z.2oezFTyV.okD9RYP1uwN/nBPefj6Dw.`

Salve, sua senha vai ser "admin" sem aspas.

**Comment by tonnybarros** [comment]
admin
`$2y$10$j9KyqKUsCIW./R1lKpvw7.Yfrnlx2IX5c2WEUUdJ.q0Ht1ZJWP9tq`

**Comment by eudinhoaroeira** [comment]
Obrigado,consegui troca a senha está funcionando, mas ao logar as opções todas do menu foram apagado, ou não aparece...
