### ISSUE TITLE
Botão editar - anotações

### ISSUE THREAD

**Issue by Ricky097** [RamonSilva20/mapos#890]
Boas, gostaria de saber como adicionar a funcionalidade de editar uma anotação, visto que está nao existe. poderia ser atraves de um modal se for mais simples.

Se alguém souber ajudar agradeço, obrigado

**Comment by Ricky097** [comment]
Alguem consegue ajudar?

**Comment by Pr3d4dor** [comment]
Boa noite @Ricky097, você pode tentar seguir o exemplo de outros controllers como por exemplo o de OS e vc terá que preencher a modal com os valores ao clicar em editar.

Não é tão trivial para quem não é programador.
