### ISSUE TITLE
Email não envia

### ISSUE THREAD

**Issue by GuilhermeDischer** [RamonSilva20/mapos#891]
** Descreva o bug **
OEmail fica em Pendente

**Comportamento esperado**
Esperava que ele enviasse os emails

** Capturas de tela **
![Inkedprint_LI](https://user-images.githubusercontent.com/66499880/89303682-e405ea80-d642-11ea-9871-3cec330a121b.jpg)

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo Windows]
 - Navegador [por exemplo Chrome]
 - Versão [por exemplo 4.11.2]

** Contexto adicional **
Alguem poderia me Ajudar?

**Comment by monutb91** [comment]
você preencher o arquivo email.php com seus dados de envio? (email, senha, porta, serviço e etc)

**Comment by GuilhermeDischer** [comment]
> você preenche o arquivo email.php com seus dados de envio? (email, senha, porta, serviço e etc)

Já fiz a configuração

**Comment by Pr3d4dor** [comment]
Olhe os erros na pasta appplication/logs

**Comment by GuilhermeDischer** [comment]
https://user-images.githubusercontent.com/66499880/89352109-c8720280-d689-11ea-8838-8a6067a4b93b.png

Como eu Resolvo?

**Comment by Pr3d4dor** [comment]
@GuilhermeDischer tente reinstalar o mapos.

**Comment by GuilhermeDischer** [comment]
Já tentei

**Comment by Negan-tec** [comment]
@GuilhermeDischer  resolvi meu problema de uma forma muito simples: Todo servidor de e-mails tem a opção de senhas exclusivas para aplicativos, gerei uma especial para o uso no mapos, que dispensa verificação em duas etapas e uso da senha principal, não tive mais problemas.

**Comment by GuilhermeDischer** [comment]
Onde eu gero isto?

**Comment by Negan-tec** [comment]
@GuilhermeDischer qual seu servidor de e-mails? gmail, hotmaisl, etc?

**Comment by GuilhermeDischer** [comment]
eu uso o de minha hospedagem

**Comment by Negan-tec** [comment]
Então terá que ver com seu provedor. No meu caso, por exemplo, uso hospedagem da godaddy mas não uso o serviço de e-mails deles, uso o Zoho Mail, e na area administrativa do Zoho tenho a opção de gerar senhas especiais para aplicativos. Eu gero a senha e uso ela, então no primeiro acesso ele atribui a senha no app em questão e trava ela para não ser usada em mais nenhum dispositivo/app. Gmail tem, Live tem, com certeza seu servidor de hospedagem tem.

**Comment by Negan-tec** [comment]
Lembre-se de se atentar as portas, se está usando SSL ou TSL, pra não gerar conflito.

**Comment by sminovacao** [comment]
Gente, ja tentei diversas formas possíveis de configuração, com ssl ou tls, email da hostking, gmail configurado para dispositivos menos confiável, etc...

no Map-OS, em configurações > email mostra que o email foi enviado mas não recebo de forma alguma.

é algum bug conhecido? procurei aqui no forum e nada me ajudou...

obrigado

**Comment by GuilhermeDischer** [comment]
> Então terá que ver com seu provedor. No meu caso, por exemplo, uso hospedagem da godaddy mas não uso o serviço de e-mails deles, uso o Zoho Mail, e na area administrativa do Zoho tenho a opção de gerar senhas especiais para aplicativos. Eu gero a senha e uso ela, então no primeiro acesso ele atribui a senha no app em questão e trava ela para não ser usada em mais nenhum dispositivo/app. Gmail tem, Live tem, com certeza seu servidor de hospedagem tem.

Minha empresa de hospedagem não possui este recurso

**Comment by GuilhermeDischer** [comment]
Recebo um email do resultado dos cron jobs com esta resposta:

No input file specified.
