### ISSUE TITLE
Erro na Datatable

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#892]
Adicionei data table as tabelas principais (clientes, serviços, os, etc) porem quando há apenas 1 ou nenhum registro na tabela, apresenta o erro "DataTables warning (table id = 'DataTables_Table_0'): Requested unknown parameter '1' from the data source for row 0"

Alguem sabe como tratar este erro? :/

**Comment by jhantenas** [comment]
Recentemente refiz minha instalação, estava funcionando a 1 ano, com clientes produtos e tal, fui atualizar testei funcionou perfeito, quando importo o banco de dados o sistema da pau, não consigo cadastrar clientes 'ocorreu um erro' , nao faz auto completar de produtos na hora da venda, se puderem de dizer oq eu estou fazendo de errado ajudaria bastante.
obrigado.

**Comment by Pr3d4dor** [comment]
@monutb91 talvez esse link consiga te ajudar: https://datatables.net/manual/tech-notes/4

**Comment by Pr3d4dor** [comment]
@jhantenas Verifique se o banco de dados está OK e não está corrompido. Você também pode olhar na pasta application/logs para ver os logs de erro.

**Comment by monutb91** [comment]
> 
> 
> @monutb91 talvez esse link consiga te ajudar: https://datatables.net/manual/tech-notes/4

Vlw Pr3d4dor, vou dar uma olhada!
