### ISSUE TITLE
Estou na versao mapos 4.11.2 nao inseri produutos em vendas e ao cadastrar novo produto da 'An Error Occured.',  e ao pesquisar alguma coisa na caixa na parte superior 'Erro Chamar para uma função de membro result () em bool'

### ISSUE THREAD

**Issue by jhantenas** [RamonSilva20/mapos#893]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '.adicionar produto..'
2. Clique em '.adicionar..'
3. Role para baixo até '....'
4. Ver erro 
'An Error Occured'

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Pr3d4dor** [comment]
@jhantenas Verifique se seu banco de dados está correto e com todas as tabelas criadas, aparecente está faltando tabelas.

**Comment by jhantenas** [comment]
@Pr3d4dor realmente estava faltando algo, descobri gracas a vc, n era uma tabela sim uma coluna em produtos código de barras. obrigado
Uma dica aos amigos que faziam vendas com clientes sem estar cadastrado em clientes cuidado pois pode ocorrer erros tambem.
