### ISSUE TITLE
O Menu Lateral está com duas opções

### ISSUE THREAD

**Issue by eudinhoaroeira** [RamonSilva20/mapos#895]
Ao logar o sistema só aparace no menu lateral a opção Dashboard e Sair, até os menus em cima que apertav f1, f2 não aparece mais

**Comment by TK2KMG** [comment]
Olá Edinhoaroeira.
Se você fez  o backup do banco de dados, faça o download do Mapos, extraia, copia e cole na pasta, irá fazer uma nova instalação. Deve resolver. 
Se não há dados nenhum inserido, faça uma nova instalação do zero. É bem rapidinho.

**Comment by eudinhoaroeira** [comment]
erro era que alterei o numero do administrador no banco de Dados na permissão, mas já corrigi... obrigado
