### ISSUE TITLE
Área do Cliente - valor da OS incorreto (serviços cujo a quantidade é maior que 1, aparece apenas 1)

### ISSUE THREAD

**Issue by neofln** [RamonSilva20/mapos#896]
** Descreva o bug **
Dentro do Sistema tudo funcionando como deveria no que é relativo valores das OS, no entanto na área do cliente quando ele entra numa OS qualquer em que a quantidade de um serviço for maior que 1, é mostrado apenas 1 serviço, o que gera incongruência nos valores. 
EX:
Serviço (Hora técnica notebooks - Referente 1 hora técnica em reparo de placa mãe de notebook.) 
Na OS dentro do sistema colocamos em quantidade 2 x Hora técnica notebooks, e o valor aparece 300,00
Na OS dentro da área do Cliente o valor da OS aparece como 150,00

Eu havia encontrado esse problema já na versão 4.8.1, mas por estafa mental, acabei esquecendo de relatar (achei que já tinha feito isso, devo ter feito durante algum sonho haeuhuhae), estou na última versão disponível 4.11.2 e o problema persiste. 

Parabéns pelo trabalho pessoal, o Map-OS continua ficando ainda melhor a cada incremento na versão. ;D 

Existe alguma opção para contribuir financeiramente para o projeto?

**Comment by neofln** [comment]
Outro problema que encontrei nesta última versão e que não existia na versão 4.8.1 que estávamos usando até então, é um limite de 45 caracteres na descrição dos serviços.

**Comment by Pr3d4dor** [comment]
@neofln Obrigado por reportar o bug, iremos corrigir assim que possível.

Sobre a contribuição ao projeto o que você acha de iniciar um projeto no Patreon para quem quiser contribuir qualquer valor consiga?

**Comment by neofln** [comment]
> @neofln Obrigado por reportar o bug, iremos corrigir assim que possível.
>
> Sobre a contribuição ao projeto o que você acha de iniciar um projeto no Patreon para quem quiser contribuir qualquer valor consiga?

Fico grato por providenciar as correções meu caro, sobre o Patreon acho que já passou da hora de criarem ;D, eu sozinho certamente não vou deixar vocês ricos, mas se todos que utilizam e gostam do Map-OS começarem a contribuir quem sabe né? ;D

**Comment by TK2KMG** [comment]
Eu sou um, que contribuiria financeiramente sem problema. O Map OS, com toda sua simplicidade reorganizou meu negócio.

**Comment by neofln** [comment]
Sei que estão re-escrevendo o Map-OS em laravel e que estão dando mais atenção a correções do que a implementações nesta versão do projeto, no entanto se for possível nesta ou quem sabe na nova versão laravel desvincular o responsável técnico do usuário que abre as OS seria de grande valia também. 
Como exemplo, na nossa empresa eu atuo como técnico e sou portanto o técnico responsável, mas as OS são abertas na recepção por outra pessoa, portanto todas as OS que ela abre com o Usuário dela, acaba ela ficando como responsável sendo que não tem como assinar um laudo técnico na prática. 
Atualmente estamos compartilhando o mesmo usuário para evitar este problema, mas acredito que não é uma boa solução. ;D

**Comment by willph** [comment]
> Sei que estão re-escrevendo o Map-OS em laravel e que estão dando mais atenção a correções do que a implementações nesta versão do projeto, no entanto se for possível nesta ou quem sabe na nova versão laravel desvincular o responsável técnico do usuário que abre as OS seria de grande valia também.
> Como exemplo, na nossa empresa eu atuo como técnico e sou portanto o técnico responsável, mas as OS são abertas na recepção por outra pessoa, portanto todas as OS que ela abre com o Usuário dela, acaba ela ficando como responsável sendo que não tem como assinar um laudo técnico na prática.
> Atualmente estamos compartilhando o mesmo usuário para evitar este problema, mas acredito que não é uma boa solução. ;D

Na hora que ela(e) abri a OS ela(e) pode colocar outro nome em responsável técnico. 

Basta digitar seu nome que o autopreencher vai completar com seu nome. E na hora que imprimir aparecerá seu nome.

Faça o teste, acesse o seu Mapos e na hora de preencher a OS coloque o nome dela.

**Comment by neofln** [comment]
Willph Perfeito, nós é que estávamos comendo mosca aqui então. ;D

**Comment by Pr3d4dor** [comment]
@neofln Corrigi o bug na versão 4.12.1, sobre as contribuições para o mapos elas podem ser feitas nesse link (mensalmente, qualquer valor): https://www.catarse.me/mapos

**Comment by neofln** [comment]
Final de semana que vem eu já instalado a versão nova se tudo correr bem. ;D

"Valeu! Seu apoio está sendo processado.
Assim que o pagamento for concluído, enviaremos a confirmação do seu apoio para o email cadastrado..."
Sugiro que disponibilizem este link na página principal do projeto se é que ainda não o fizeram. ;D

**Comment by Pr3d4dor** [comment]
@neofln Só repassando que esse link que eu mandei é assinatura mensal, ou seja, todo mês ele vai cobrar o valor que você escolheu. Então se você quer doar só uma vez recomendo cancelar para não cobrar todo mês.

Ainda vou criar outro projeto para doações exporádicas.

Caso queira o dinheiro de volta é só entrar em contado que eu vejo se no catarse é possível realizar a devolução.

**Comment by neofln** [comment]
Meus caros, vou continuar escrevendo aqui pois não sei se há alguma forma mais adequada de contato, no entanto se houver e quiserem que doravante eu utilize peço que por gentileza me orientem.
Vou deixar aqui algumas considerações que tenho sobre o Map-OS atual, apenas para que saibam e reflitam sobre elas quando por ventura tiverem tempo, sem qualquer pressão da minha parte para que concordem com elas e implementem, nada de cobranças. 

Algo que julgo seria muito bem vindo caso for possível adicionar em algum momento, é um "Pesquisar" no menu lateral, quando se usa o mapos num telefone se não marcar a opção "versão para pc" o campo de pesquisas que normalmente fica no canto superior direito da página e que atualmente é o mecanismo que traz os resultados que normalmente busco, não aparece.
Uma guia de pesquisas avançadas na base de dados portanto seria de grande valia na minha opinião, ainda que fosse rudimentar e exigisse conhecimento de SQL já seria muito útil.

Não sei se é fácil de implementar mas acredito que seja possível, utilizar algum mecanismo de compressão para os anexos, a ideia seria que fotos e documentos fossem enviados no formato natural mas que fossem tratados durante o upload para ficar com extensão .zip ou outra qualquer, com a finalidade de não ocupar tanto espaço na hospedagem e apesar disto manter a qualidade das imagens que no meu caso são de alta resolução, sendo assim para exibir as imagens elas precisariam ser tratadas novamente, algo similar ao que o google drive faz permitindo a visualização de imagens dentro de arquivos compactados.

Sobre as "Configurações" acho que o sub menu "Emails" que consta lá poderia ter o conteúdo movido para relatórios ou para uma nova categoria (Logs por exemplo) e que lá ("Configurações->"Emails") deveria constar as configurações de e-mail mesmo.

Penso também que repassar ao utilizador o controle sobre os nomes dos estados das OS e a possibilidade de adicionar outros estados seria muitíssimo bem vindo, mas acredito que deva ser muitíssimo complicado mexer nisto, em virtude de alguns relatos que li anteriormente na seções de Issues. 

Certamente há outras coisas que ainda podem ser melhoradas, no entanto no momento eu não recordo de mais nada que tenha observado recentemente, e de maneira geral estou deveras satisfeito com o Map-OS.

Sobre sua última resposta Gian Luca, eu pretendo doar este valor pelo menos durante alguns meses com o intuito de ajudar o projeto a seguir em frente da forma como acharem melhor, e como agradecimento pelo vosso empenho em manter esta bela peça de código livre funcionando cada vez melhor.

Abraço.

**Comment by Pr3d4dor** [comment]
@neofln Obrigado pelas suas sugestões e palavras, iremos levar todas em consideração e implementar todas as que forem possíveis.
