### ISSUE TITLE
ERRO DE SESSÃO

### ISSUE THREAD

**Issue by wnjulio** [RamonSilva20/mapos#897]
Whoops\Exception\ErrorException thrown with message "session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/cpanel/php/sessions/ea-php73)"

Stacktrace:
#2 Whoops\Exception\ErrorException in Unknown:0
#1 Whoops\Run:handleError in [internal]:0
#0 session_write_close in [internal]:0
![image](https://user-images.githubusercontent.com/42722761/89741460-f085ab00-da67-11ea-91f1-69a6da3baaf6.png)
![Sem título](https://user-images.githubusercontent.com/42722761/89741483-127f2d80-da68-11ea-9d16-e1307c82a6a3.png)

**Comment by Pr3d4dor** [comment]
@wnjulio parece ser problema de permissões na pasta do mapos, sugiro que tente verificar isso. Aí ele não consegue criar os arquivos quando inicia sessão e aparece esse erro.

**Comment by wnjulio** [comment]
@Pr3d4dor  boa noite!
 consegui resolver,  o banco não estava criando a tabela session, não sei pq, era somente isso! mt obrigado

**Comment by cleitoncavaaa** [comment]
eu tbm msm erro alguem me ajuda pf

**Comment by Pr3d4dor** [comment]
@cleitoncavaaa Verifique se sua conexão com o banco e as tabelas estão criadas corretamente.
