### ISSUE TITLE
Colocar numeração em cada serviço na OS

### ISSUE THREAD

**Issue by eudinhoaroeira** [RamonSilva20/mapos#899]
Nossa empresa é prestadora de serviços de recarga de toner, e cada cartucho recebe uma numeração para identifica-lo, poderia criar um espaço na OS. em cada serviço para identificar, pq para quando voltar sabemos quando foi o ultimo serviço ou quantas recarga recebeu o cartucho. ou poderia colocar em outro lugar, tipo colocar o numero da OS, e a identificação dos serviços:

Ex:
OS. 02
 Numero   |          Serviço            |           Quantidade    |            Preço             |     
45002       -      Carga toner 285 -                1                -         R$ 50,00
45003       -      Carga toner 435 -                1                -         R$ 50,00
45005       -      Carga toner 285 -                1                -         R$ 50,00
                                                           Total: 3          Sub Total: R$ 150,00

**Comment by tonnybarros** [comment]
Olá, o número da OS já existe, é o ID dela, também existe a aba serviço.
Quanto a numeração do serviço, poderia tentar capturar o id do serviço (idServicos), e usar como a numeração que deseja.

**Comment by tonnybarros** [comment]
Algo mais ou menos assim
![service](https://user-images.githubusercontent.com/68646516/89908004-c2b57900-dbc3-11ea-8ad3-79a10bbe7dbd.png)

**Comment by tonnybarros** [comment]
Com algumas alterações, pode acrescentar isso nas pesquisas da OS

**Comment by eudinhoaroeira** [comment]
Não amigo, como no meu exemplo cima... cada cartucho que recebo para fazer a recarga, numa unica OS. eu poderia identicar cada cartucho com o numero de entrada, assim caso voltasse eu identificaria ele , quanto foi feito e qual OS.
