### ISSUE TITLE
Desconto em Ordem de Serviço e Vendas

### ISSUE THREAD

**Issue by RamonSilva20** [RamonSilva20/mapos#9]
Adicionar funcionalidade para aplicar descontos em vendas e ordens de serviço.

**Comment by hardbrasil** [comment]
Olá Ramon eu sou iniciante e Leigo em PHP mas tenho vivência em sistemas de Ordem de serviço Documentações e treinamentos. Gostaria de Colaborar com o projeto do jeito que eu puder desenvolvendo os textos e documentações para o mesmo.

**Comment by hardbrasil** [comment]
Uma pergunta como implemento esta alteração pois sempre preciso desta no sistema aqui?

**Comment by RamonSilva20** [comment]
Vou adicioná-lo como colaborador do projeto para que possa contribuir.

**Comment by gugatxr** [comment]
@hardbrasil eu posso adicionar os textos e o que precisar, só passar.

**Comment by hardbrasil** [comment]
Ok Segue o Primeiro. Este deve ser inserido no Cabeçalho da OS para resguardar os prestadores de eventuais problemas futuros  com os aparelho deixados "abandonados" na assistência.
Ressalto que Infelismente não há Leis que protejam fornecedores de serviço pois o CDC em muitas vezes protege muitos entre áspas Pilantras ditos consumidores.

Artigo único da OS Sobre a destinação/Abandono do aparelho:
Declaro estar ciente que após a aprovação do Orçamento enviado por Telefone, e-mail,ou por escrito e tendo autorizado o orçamento de serviço(s) referente(s) a este documento de OS (Ordem de Serviços) estou ciente que deverei pagar o valor passado cujo qual foi autorizado por mim ou pessoa por mim Preposta e  então após o prazo de 30 dias após o aviso para retirada  pagar o valor de 1,50 ( Hum Real e cinquenta centavos por dia) referentes a despesas com a guarda do aparelho. Caso não haja a retirada no período de 90(noventa) dias, após as devidas notificações para que este bem seja retirado , será considerado depósito abandonado, a <Nome da Empresa>, está autorizada a dispor da melhor forma que lhe convier, conforme o ARTIGO 1275,sem prejuízo do disposto do ART. 1278  do CÓDIGO CÍVEL BRASILEIRO, a fim de resarcir-se dos eventuais prejuizos havidos.
* Deve conter campo para assinatura do Cliente conforme Documento, RG e CPF do mesmo.
* Acvonselha-se explicar verbalmente ao cliente sobre estes termos no ato da abertura da Ordem.







Instruções ao Prestador (Não deve aparecer na OS para o Cliente)
Este documento é um modelo feito para ajudar e ter alguma defesa tendo em vista que a Lei do Brasil só favorece os “pilantras” que agem de má fé e causam transtornos e prejuízos aos lojistas, use e documente-se de todas as formas assim terá pelo menos possibilidades de defesa contra estes ditos cidadãos que agem de má fé.


Ao ser impresso em 2 vias deve o Prestador explicar ao Cliente e Coletar a Assinatura do mesmo como na Identidade e guardar este documento na sua assistência pelo tempo que o aparelho estiver em sua posse para evitar problemas Judiciais. A Lei entende que não existe o abandono do bem porém deve-se ser observado que o Bom senso deve predominar e que o combinado não sai caro, mas em toda forma da Lei, documente-se para evitar transtornos.

**Comment by hardbrasil** [comment]
Seria Interessante se o sistema Incluísse também Modelos de documentos para assistências e Autorizadas criei muitos e vou compartilha-los aqui caso achem interessante e queiram trabalhar na inserção destes documentos no sistema para que os usuários possam fazer um uso qualitativo e proveitoso dos mesmos.

**Comment by hardbrasil** [comment]
Um, dos documentos mais importantes em uma assistência, Principalmente autorizada é um comprovante que ateste a retirada do aparelho por parte do Cliente ou pessoa pelo mesmo preposta.



Modelo do documento:

Aqui seria o Logotipo e os dados da Empresa.
Declaração de Entrega do Produto


Declaro para os fins a que se fizerem necessários que retirei na assistência técnica (Nome da Empresa) o aparelho Marca: (Exemplo Mondial)  Modelo: ( Exemplo B54321)  Tipo: (Exemplo : Air Frier, TV, Computador, Notebook, Microsystem, DVD Player....)
Referente a Ordem de serviços do Fabricante de n: ( No caso de autorizada os da Fábrica) ou Interna (Exemplo Protocolo 1022) .Declaro também que o aparelho foi testado em minha presença nesta data e o visualizei em funcionamento e apto ao uso.Ou também declaro através deste que não quis que o mesmo fosse testado. Declaro ainda ter conferido os ítens e o aparelho neste ato dando ciência que o mesmo está como no ato da entrega e não poderei reclamar posteriormente da falta de acessórios e/ou componentes.
Por ser verdade firmo o presente.
_____________________________________________________________________
Responsável pelo recebimento (Cliente ou representante Preposto)
________________________________________________         ________________________________________________
CPF			                             RG
_____________________________________________________________________________________________________
Nome Legível


_________________________________________________________________________________
Responsável Pela Assistência Técnica -  Cidade : ______/______/______  Hora: ______:____

**Comment by hardbrasil** [comment]
* Este abaixo serve para quando principalmente em casos de o Cliente querer retirar o aparelho sem reparo do mesmo e precisar documentar este fato, ocorre muito com serviços autorizados onde  quando o cliente não esperar a peça ou o reparo deseja retirar o aparelho do jeito que se encontra no momento. É muito importante documentar tal retirada.

Logo e dados da Empresa AQUI.


Declaração de Retirada de Equipamento sem Reparo:


Eu: ____________________________________________________
Declaro para os fins a que se fizerem necessários que o equipamento referente a ordem de serviços de n:______________ foi retirado na data de: _____/_____/_____  ás _____:_____ hs pelo motivo de: ________________________________________________________________________________________________________________________________________________________________________________________________________________
**Sem o reparo em garantia assegurado a mim ter sido realizado por motivo de que não quis que o mesmo seja efetuado atestando a veracidade da retirada deste aparelho.**


Por ter ciência deste atesto a verdade:


Nome: ____________________________________________
Assinatura: ________________________________________
N CPF:_____________________________________________

* Importante explicar ao cliente verbalmente o motivo pelo qual não está reparado o aparelho até a presente data se possível anexando documentos do fabricante de acordo com as normas do mesmo. Manter a guarda do documento por no mínimo 90 dias após a retirada do aparelho para se resguardar juridicamente.

**Comment by hardbrasil** [comment]
Bem espero ter ajudado por Hoje e em breve postarei mais modelos de documentos referentes a Ordens de serviço. Qualquer dúvida vamos discutir os assuntos. Agradecemos o Ramon por sua iniciativa e sei que juntos podemos Criar uma bela iniciativa Just do It para controles de ordens de serviços de forma qualitativa. Creio que assim como Linus o Ramom deu um grande passo para um Excelente Projeto Colaborativo que podemos transformar juntos em um grande projeto/sucesso.

**Comment by hardbrasil** [comment]
Estes documentos são de Livre distribuição, compartilhar é ajudar só peço que no projeto citemos o nome de todos os colaboradores neste.

**Comment by leocampbel** [comment]
Olá pessoal.
Eu não consegui colocar um campo de desconto e um outro de acrecemos de valores da OS.
Se alguém conseguir me avisa por favor.
Obrigado

**Comment by hardbrasil** [comment]
No meu também não consegui, eu consegui atualizar aparece abaixo os dados do Ramon Silva e 2016 mas não aparece campos para inserir descontos ou acréscimos em produtos e os. Alguém sabe como resolver isso?

**Comment by hardbrasil** [comment]
Modelo de Documento Autorização para abandono de equipamento:


COLOCAR AQUI DADOS E LOGOMARCA DA EMPRESA

AUTORIZAÇÃO PARA DESCARTE - VENDA - DOAÇÃO
Eu: ____________________________________________________
Declaro para os fins a que se fizerem necessários que o equipamento referente a ordem de
serviço  de n:______________ não foi retirado até esta data: _____/_____/_____ ás _____:_____ hs pelo motivo de:
______________________________________________________________________________
Por não ter interesse no aparelho declaro estar abandonando, descartando o mesmo e declaro
estar ciente de não mais poder reclamar a propriedade do aparelho posteriormente pois neste ato conforme citado anteriormente estou abandonando o mesmo por motivos pessoais.
Declaro ainda que pode a empresa Citada neste documento dar ao aparelho o fim que lhe
convier, inclusive vender para custear despesas com armazenamento e outras despesas
referentes a este (s) aparelho(s).
Por ter ciência deste atesto a verdade:
Nome Legível: ____________________________________________
Assinatura: ________________________________________
N CPF:_____________________________________________
N RG: _____________________________________________
● Gentileza ler e concordando, assinar, escanear e enviar por e-mail.
● Assinatura deve ser como a do documento de identidade.

**Comment by DGdeOliveira** [comment]
Boa tarde amigos.
O campo desconto é a última alteração para termos um sistema perfeito. Já mexi bastante no sistema. Tentei implementar o campo, mas como sou iniciante em CodeIgniter foi um esforço em vão. Tentei fazer esse desconto percentual direto no php. Tentei fazer vir do banco porque o sistema soma até na tela de impressão, mas nada. Realmente é coisa pro Ramon mesmo...   
Obrigado a todos pela iniciativa e contem comigo!

**Comment by gugatxr** [comment]
Tô implementando o desconto também @DGdeOliveira. Tá sendo feito na branch dev, logo logo estará a nova versão funcionando :smile:

**Comment by DGdeOliveira** [comment]
GugaTXR tem uma previsão de quando poderá sair o desconto ? Desde já, muito obrigado!

**Comment by RamonSilva20** [comment]
Vou tirar um tempo e tentar implementar esta semana.

**Comment by hardbrasil** [comment]
Tive mito trabalho para fazer os Lançamentos de clientes e alimentar o sistema com os dados da minha empresa a mão.Mas infelismente por não saber implementar os filtros e poucas coisas para este sistema ficar perfeito.

Estarei retornando ao check os: http://pt-br.checkos.com.br/



* Falta Muito pouco para o MAP os ficar perfeito mas teria de implementar os filtros e campos n de série tipo de aparelho e estas coisas.



Abraços a todos e valeu.



Att;



Sérgio C Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Ter, 24 Jan 2017 13:31:47 -0200 Ramon Silva &lt;notifications@github.com&gt; wrote ----




Vou tirar um tempo e tentar implementar esta semana.

**Comment by DGdeOliveira** [comment]
Estou desenvolvendo pro Map OS uma espécie de front-page pros clientes consultarem suas OS's e Compras apenas digitando seu CPF. Assim que ficar pronto posto os arquivos aqui.

**Comment by gugatxr** [comment]
@DGdeOliveira Já está funcionando o desconto na branch dev. Falta somente alterar o código do gerar pdf dos relatórios que não estão funcionando ainda

**Comment by DGdeOliveira** [comment]
Muito obrigado Guga!
Eu vi lá na branch, só não consegui fazer rodar pra ver como ficou
`Warning: require(C:\xampp2\htdocs\mapos-dev\vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp2\htdocs\mapos-dev\index.php on line 328`

Desde já, muito obrigado!

**Comment by RamonSilva20** [comment]
@gugatxr muito bom, vou dar uma olhada na branch dev, ver se posso ajudar com algo.

**Comment by gugatxr** [comment]
@DGdeOliveira retirei o require do composer. Dá um git pull para atualizar.Adicionei um firula na página inicial hahahahah

**Comment by gugatxr** [comment]
@RamonSilva20  se tiver como verificar a geração de pdf nos relatórios. Não estão sendo gerados. 
A página fica carregando e não gera. 
Valeu

**Comment by DGdeOliveira** [comment]
Guga agora dá Objeto Não Encontrado. Database, config, tudo ok, mas, não funciona.
Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
@gugatxr gostei da firula na página inicial... rs Útil, mas, na tela de vendas ou OS  não está inserindo produtos nas vendas nem nas OS's. Existe algum outro "pulo do gato" ? 
Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
@gugatxr gostei da firula na página inicial... rs Útil, mas, na tela de vendas ou OS ainda não existe o campo desconto.
Desde já, muito obrigado!

**Comment by hardbrasil** [comment]
Seria muito difícil inserir os campos de n de serie tipo de aparelho. Na impressão aparecer telefone e-mail do cliente.









Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qui, 26 Jan 2017 15:49:49 -0200 Diego de Oliveira &lt;notifications@github.com&gt; wrote ----




@gugatxr gostei da firula na página inicial... rs Útil, mas, na tela de vendas ou OS ainda não existe o campo desconto.

 Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
@hardbrasil isso é muito simples, vou encontrar um tempinho aqui pra fazer pra você, mas de bate-pronto você poderia usar o campo observação pra isso, uma vez que seria inútil incluir em filtros tipo e número de série pois ninguém filtra por esses termos...

**Comment by hardbrasil** [comment]
Trabalho com Assistência ha anos, usei diversos sistemas. Acredito Muito no Map os mas as buscas para encontrar na Oficina os aparelhos ficam meio fracas as vezes por falta de campos e filtros, exemplos:



Cadastro:

Tipo de Aparelho:  (Onde se coloca, computador, Notebook, DVD Player, Impressora, Air Frier, Liquidificador etc...)

Marca: ( CCE, Phillips, AOC, LG, Samsung, Cadence, Canon etc..)

Modelo: ( Modelo de acordo com o fabricante numerico, alfanumerico ou outro)

* Isso é indispensável em uma oficina, o sujeito liga mas não sabe a os mas sabe marca e modelo, você pesquisar direto pelo nome do cliente número de série tipo do aparelho data de entrada estas coisas.

* Muitos dos sistemas também utilizam de campos de multipla escolha onde já se marca o que deseja exemplo marca do aparelho, tipo, defeito.

Cadastra-se no BD estes dados e depois é só escolher e acho que vcs dizem vincular me perdoem se estiver errado.


Quando da os já impressa não saem os dados de contato do cliente.

Seria bom inserir também um campo Box ou Prateleira onde saberia em qual prateleira o aparelho se encontra.





Att;



Sérgio C Coelho






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qui, 26 Jan 2017 17:12:35 -0200 Diego de Oliveira &lt;notifications@github.com&gt; wrote ----




@hardbrasil isso é muito simples, vou encontrar um tempinho aqui pra fazer pra você, mas de bate-pronto você poderia usar o campo observação pra isso, uma vez que seria inútil incluir em filtros tipo e número de série pois ninguém filtra por esses termos...

**Comment by hardbrasil** [comment]
Bom dia.



Alguém consegue implementar estes campos e filtros?



Att;






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qui, 26 Jan 2017 17:30:23 -0200 Contato Hard Brasil &lt;contato@hardbrasil.com.br&gt; wrote ----




Trabalho com Assistência ha anos, usei diversos sistemas. Acredito Muito no Map os mas as buscas para encontrar na Oficina os aparelhos ficam meio fracas as vezes por falta de campos e filtros, exemplos:



Cadastro:

Tipo de Aparelho:  (Onde se coloca, computador, Notebook, DVD Player, Impressora, Air Frier, Liquidificador etc...)

Marca: ( CCE, Phillips, AOC, LG, Samsung, Cadence, Canon etc..)

Modelo: ( Modelo de acordo com o fabricante numerico, alfanumerico ou outro)

* Isso é indispensável em uma oficina, o sujeito liga mas não sabe a os mas sabe marca e modelo, você pesquisar direto pelo nome do cliente número de série tipo do aparelho data de entrada estas coisas.

* Muitos dos sistemas também utilizam de campos de multipla escolha onde já se marca o que deseja exemplo marca do aparelho, tipo, defeito.

Cadastra-se no BD estes dados e depois é só escolher e acho que vcs dizem vincular me perdoem se estiver errado.



Quando da os já impressa não saem os dados de contato do cliente.

Seria bom inserir também um campo Box ou Prateleira onde saberia em qual prateleira o aparelho se encontra.





Att;



Sérgio C Coelho







Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qui, 26 Jan 2017 17:12:35 -0200 Diego de Oliveira &lt;notifications@github.com&gt; wrote ----











@hardbrasil isso é muito simples, vou encontrar um tempinho aqui pra fazer pra você, mas de bate-pronto você poderia usar o campo observação pra isso, uma vez que seria inútil incluir em filtros tipo e número de série pois ninguém filtra por esses termos...

**Comment by gugatxr** [comment]
@hardbrasil criei um novo issue #13 para adicionar esses campos, tentarei realizar essa semana.

**Comment by hardbrasil** [comment]
Ok.



Obrigado por nos manter informados e precisando estamos aí tbm.



Att;






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Seg, 06 Fev 2017 10:24:01 -0200 Gus &lt;notifications@github.com&gt; wrote ----




@hardbrasil criei um novo issue #13 para adicionar esses campos, tentarei realizar essa semana.

**Comment by DGdeOliveira** [comment]
Ramon e Guga, eu entendo muito pouco, mas estou estudando muito pra tentar implementar o campo desconto. Teria alguma dica que facilitasse ? O campo desconto é algo primordial dentro do MapOS, ou seja, o item final da construção completa do sistema.
Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
@RamonSilva20 e @gugatxr, eu entendo muito pouco, mas estou estudando muito pra tentar implementar o campo desconto. Teria alguma dica que facilitasse ? O campo desconto é algo primordial dentro do MapOS, ou seja, o item final da construção completa do sistema.
Desde já, muito obrigado!

**Comment by RamonSilva20** [comment]
Eu ia implementar semana passada, mas meu computador deu problema na placa mãe, assim que consertá-lo vou adicionar. Desculpem pela demora.

**Comment by DGdeOliveira** [comment]
Tudo bem Ramon. Obrigado!

**Comment by gugatxr** [comment]
@DGdeOliveira implementei o desconto em os e vendas. Se puderem testar também.
Abraço.

**Comment by DGdeOliveira** [comment]
Obrigado pelos esforços @gugatxr mas, não dá pra instalar. Está dando erro no DB Driver.

Desde já, muito obrigado!

**Comment by hardbrasil** [comment]
Alguém trabalhou nos Filtros e novos campos separados de forma organizada?



Exemplo : N de Série, Marca , Modelo, Tipo De Aparelho

* Ao fazer busca numa assistência técnica é essencial buscar por marca, modelo, tipo, n de série, nome do cliente etc....



Abraços a todos.



Att;






Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qua, 15 Fev 2017 17:10:47 -0200 Diego de Oliveira &lt;notifications@github.com&gt; wrote ----




Obrigado pelos esforços @gugatxr mas, não dá pra instalar. Está dando erro no DB Driver.

Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
@hardbrasil o @gugatxr tá trabalhando nisso, mas estamos com alguns problemas pra instalar...

**Comment by hardbrasil** [comment]
Dê uma olhada quando der em: www.checkos.com.br











Hard Brasil Assistência Multimarcas &amp; Multiserviços

Eletrônica - Eletrodomésticos - Eletroportáteis - Informática

Reparamos: Air Friers, Fornos, TV's, DVD's, Aparelhos de Som, Ventiladores e muito mais.

Atendimento ao público:

Segunda de 13 ás 18 hs e terça a sexta de 9 ás 18 hs



Tels:(31)31536664 (Vivo Fixo) 9913675-07 (Tim Móvel) 991367507 (Whatsapp)

contato@hardbrasil.com.br   www.hardbrasil.com.br








---- On Qua, 15 Fev 2017 18:42:47 -0200 Diego de Oliveira &lt;notifications@github.com&gt; wrote ----




@hardbrasil o @gugatxr tá trabalhando nisso, mas estamos com alguns problemas pra instalar...

**Comment by DGdeOliveira** [comment]
@gugatxr cara eu sou meio leigo e não entendendo, mas um exemplo: Na branch o arquivo editarOs.php está faltando muitas linhas inclusive a da Status da OS e eu não consigo de jeito nenhum instalar a versão disponível na branch, baixando os arquivos em zip, dá uma série de erros. Tentei mesclar com a master, mas não adianta não roda... 
Desculpe a ignorância amigos!
Desde já, muito obrigado!

**Comment by DGdeOliveira** [comment]
Acho que realmente será impossível fazer o sistema ter o campo desconto, pois teria que desmontar toda sua arquitetura. Agradeço os esforços dos amigos. Obrigado a todos!

**Comment by TecSecret** [comment]
Conforme consta no site: http://sistemamapos.esy.es/ o projeto foi descontinuado.

Mas nós da TecSecret vamos manter o projeto ativo com uma equipe focada em sempre proporcionar atualizações constantes e correção de bugs, inclusive no suporte a instalações existentes.

Acesse o novo Git do Projeto: https://github.com/TecSecret/TSDC-Assistencia

**Comment by darouca** [comment]
Bom dia. Acabei de perdendo nos comentários. A funcionalidade de desconto já foi implantada? 

Obrigado.

**Comment by brunods** [comment]
olá! como ficou a questão do **desconto**?

**Comment by DEIVYDAMORIMDESOUZA** [comment]
> Adicionar funcionalidade para aplicar descontos em vendas e ordens de serviço.

ESSA FUNCIONALIDADE ESTÁ IMPLEMENTADA NA ÚLTIMA VERSÃO ?
DESCONTO PARA VENDAS E PARA ORDEM DE SERVIÇOS
