### ISSUE TITLE
Alteração/Cadastro de usuário

### ISSUE THREAD

**Issue by KansasMyers** [RamonSilva20/mapos#90]
Então na tela de administração de Usuários tem o seguinte problema ele permite gravar dois usuários com o mesmo e-mail. Eu gostaria de contribuir para o projeto, mas gostaria de saber qual a melhor maneira de fazer isso. Mudar o banco de dados para o e-mail ser uma UNIQUE Constraint ou fazer uma validação antes da Alteração/Cadastro do usuário?

**Comment by RamonSilva20** [comment]
O Codeigniter fornece validação para isso, mas existe um problema para a edição dos registros, por isso seria preciso fazer uma validação própria ao editar o usuário.

https://codeigniter.com/user_guide/libraries/form_validation.html?highlight=validation

**Comment by KansasMyers** [comment]
Ok, vou realizar as alterações e fazer o pull se tudo der certo eu fecho a issue

**Comment by RamonSilva20** [comment]
Ok. Obrigado por sua contribuição.

**Comment by fabiolucasdasilva** [comment]
Boa tarde !
Gostaria de informar o horário da abertura da OS no programa mapos vocês sabem me informar se é possível ?

Obrigado

Fábio
