### ISSUE TITLE
Envio de e-mails automático (Windows 10/Agendador de Tarefas)

### ISSUE THREAD

**Issue by Negan-tec** [RamonSilva20/mapos#900]
Pessoal, como não encontrei nenhuma resposta e muita gente com dúvidas, consegui realizar o agendamento de um .BAT sendo configurável de várias formas, e está rodando perfeitamente.

Como acabei de fazer e estou correndo aqui gostaria de saber se mais alguém está passando por essa dificuldade, assim que eu liberar um tempinho aqui posto detalhes.

**Comment by Pr3d4dor** [comment]
@Negan-tec se você puder compartilhar esse .BAT, poderia até colocá-lo no repositório ou você mesmo fazer a PR.

**Comment by chico24hs** [comment]
Show! pode compartilhar?

**Comment by Negan-tec** [comment]
Bora lá para o mini tutorial minha gente 👍 

1) Crie um arquivo .bat: Abra o bloco de notas > digite **php index.php email/process** > em seguida salve o arquivo com a extensão .bat ( No meu caso coloquei o nome **e-mail-process**

2) Abra o gerenciador de tarefas do windows: no teclado digite as teclas **windows+R** para abrir o executar > digite **taskschd.msc** > a tela a seguir deve ser exibida:

![image](https://user-images.githubusercontent.com/69531043/90354272-35d54a00-e01f-11ea-8398-54cf32416991.png)

**Comment by Paul0Silva** [comment]
@Negan-tec fiz seu tutorial os e-mails mudaram do status "pendente" para "enviando", mas não sai disso.
![image](https://user-images.githubusercontent.com/62789556/93665779-abce3600-fa4f-11ea-9947-0dff5f6fab09.png)

**Comment by Pr3d4dor** [comment]
@Paul0Silva Provavelmente tem alguma configuração incorreta nos emails, o seu serviço está bloqueando, etc.

Só vendo os logs de erro para saber.

**Comment by Paul0Silva** [comment]
@Pr3d4dor só tem isso no meu log.
![image](https://user-images.githubusercontent.com/62789556/93706809-759cbf00-fb00-11ea-9550-ad69e2756cbf.png)
