### ISSUE TITLE
number_format() expects parameter 1 to be float, string given

### ISSUE THREAD

**Issue by duarteadi** [RamonSilva20/mapos#901]
![Capturar](https://user-images.githubusercontent.com/69591796/90032494-cfee6880-dc94-11ea-874c-fdfdecb13acf.JPG)

Ao acessar financeiro/lancamentos, e filtrar com, "Ano" ou "todos", aparece essa mensagem;

![image](https://user-images.githubusercontent.com/69591796/90032587-ec8aa080-dc94-11ea-82eb-f23de92356b8.png)
![Capturar2](https://user-images.githubusercontent.com/69591796/90032721-0fb55000-dc95-11ea-949e-5e9de5945cb6.JPG)

**Comment by tonnybarros** [comment]
Testei no meu, não aconteceu isso.
https://loja2.tectonny.com.br/
Simula vc mesmo
admin@admin.com
Senha: admin
