### ISSUE TITLE
erro ao atualizar de 4.8 para ultima versao.

### ISSUE THREAD

**Issue by giampaulo** [RamonSilva20/mapos#902]
atualizei direto no mapos e tive esse retorno
![image](https://user-images.githubusercontent.com/48699495/90057221-77c85e00-dcb6-11ea-9352-0e52a38a5262.png)

**Comment by Pr3d4dor** [comment]
@giampaulo o atualizador está com algum bugs, recomendo atualizar manualmente.

**Comment by 1rks** [comment]
> @giampaulo o atualizador está com algum bugs, recomendo atualizar manualmente.

Atualizei do 4.4 e deu este erro, como faço para acessar todos os arquivos de modo seguro, voltar o sistema
