### ISSUE TITLE
Relatorio de vendas

### ISSUE THREAD

**Issue by ricardorpco** [RamonSilva20/mapos#903]
Tentei tirar um relatorio de vendas e esta me apresentando este erro. Alguem consegue me ajudar?
![Sem título](https://user-images.githubusercontent.com/69605325/90071395-d815ca80-dccb-11ea-8c97-0d1b6007643c.png)

**Comment by Pr3d4dor** [comment]
@ricardorpco Vá em Configurações >> Emitente, preencha todos os campos e atualize o logo da sua empresa.

**Comment by ricardorpco** [comment]
Deu certo, muito obrigado.!!
