### ISSUE TITLE
relatório financeiro

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#905]
então senhores, estou com uns problemas de conciliação financeira por meio do mapos, o relatório financeiro, apenas em PDF, eu tenho que imprimir e ir ticando manualmente, pois tem clientes que pagam metade em um cartao metade em outro, atrasando bastante minha conciliaçao, queria ter uma opçao de tirar o relatorio em excel pra facilitar a minha vida, posso remunerar caso necessario essa customizaçao, e acredito que vai ajudar muitos usuários....

**Comment by Pr3d4dor** [comment]
Obrigado, @vksaghaz iremos implementar assim que possível.
