### ISSUE TITLE
Hora errada na OSs - sistema e impressa

### ISSUE THREAD

**Issue by Negan-tec** [RamonSilva20/mapos#906]
A hora sempre fica errada. Como arrumar isso?

 - SO: Win 10
 - Navegador: Chrome, Canary, Firefox, qualquer um deles
 - Versão 4.8.1 e 4.11

**Comment by Pr3d4dor** [comment]
@Negan-tec creio que isso é problema de timezone no servidor, abra o arquivo index.php na raiz e adicione `date_default_timezone_set('America/Sao_Paulo');` ou `date_default_timezone_set('America/Fortaleza');`  logo após a tag `<?php`

**Comment by Negan-tec** [comment]
@Pr3d4dor muito obrigado, funconou perfeitamente, já havia mudado algumas configurações em outros arquivos mas sem sucesso. Vlw
