### ISSUE TITLE
Agenda para Marcar horario.

### ISSUE THREAD

**Issue by MatheusRoas** [RamonSilva20/mapos#907]
uma aba agenda, para pode marcar horário quando técnicos tiverem q sair ou atender alguém em uma hora especifica. 

[https://uploaddeimagens.com.br/images/002/830/093/full/5-digical-agenda-calendario.jpg?1597428041](url)

**Comment by MatheusRoas** [comment]
[https://www.meupositivo.com.br/doseujeito/wp-content/uploads/2018/12/5-digical-agenda-calendario.jpg](url)

**Comment by Pr3d4dor** [comment]
Obrigado, @MatheusRoas iremos analisar e implementar se possível.
