### ISSUE TITLE
Erro no importa, banco de dados.

### ISSUE THREAD

**Issue by taylorfeliip** [RamonSilva20/mapos#91]
Como faço para esta, conseguindo arruma esse erro.

http://prntscr.com/igjzts

**Comment by taylorfeliip** [comment]
erro acontece com base do (Versão 4.0), outras versões funcionam perfeitamente.

**Comment by drelldeveloper** [comment]
@taylorfeliip Como a própria imagem sugere, o seu usuário não tem privilégios suficientes para manipular o banco de dados Mapos.
