### ISSUE TITLE
Envio de e-mails excessivos

### ISSUE THREAD

**Issue by Negan-tec** [RamonSilva20/mapos#910]
Pessoal, sempre que damos entrada em uma OS e clicamos em continuar, geram um e-mail, faz uma alteração gera um e-mail, resumindo, toda hora gera um e-mail, já desabilitei as notificações na área de sistema mas ai nem o botão enviar e-mail funciona pois retorna a mensagem que a função está desabilitada.

Qual arquivo posso alterar para enviar o e-mail somente quando eu clicar no botão?

Já alterei vários arquivos e seus dependentes mas quando não buga, fica do mesmo jeito. Desde já obrigado. Vlw

**Comment by Pr3d4dor** [comment]
Em Configurações >> Sistema você pode configurar essa questão de envio de emails:

![image](https://user-images.githubusercontent.com/13210429/90341063-c33e7d00-dfd2-11ea-9d6d-2585f783a28b.png)

Ali na parte "Notificações de OS".

**Comment by Negan-tec** [comment]
Ja fiz isso, mas como escrevi, quando desativo o botão de envio retorna uma mensagem que não é possível usar a função

**Comment by Negan-tec** [comment]
@Pr3d4dor

**Comment by Negan-tec** [comment]
![image](https://user-images.githubusercontent.com/69531043/90355589-2f48d180-e023-11ea-8606-f303b0029c2d.png)

**Comment by Negan-tec** [comment]
Consegui, obrigado.
