### ISSUE TITLE
melhoria pagina de vendas

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#911]
na parte de vendas, faturamento uma ideia interessante e colocar a forma de pagamento da venda,pois essa opçao apenas ew habilitada quando e marcado flag "foi pago?"

![faturamento](https://user-images.githubusercontent.com/69607468/90418376-6f439f00-e08b-11ea-9363-8ef649688254.png)

**Comment by Pr3d4dor** [comment]
@vksaghaz Obrigado pela sugestão, iremos implementar se possível.
