### ISSUE TITLE
Cadastro de cliente com registro do usuário que o cadastrou

### ISSUE THREAD

**Issue by guskid** [RamonSilva20/mapos#913]
Boa noite pessoal. 
Estou com o sistema online e colocando aos poucos para funcionar. 
O que eu tinha necessidade é o seguinte. 
Na hora de tirar, por exemplo, o relatório de clientes onde está escrito " NOME / DOCUMENTO / TELEFONE / EMAIL / CADASTRO " não teria como colocar quem foi usuário que cadastrou aquele cliente?  
Tipo este exemplo que estou postando abaixo? 
![image](https://user-images.githubusercontent.com/61772592/90457286-78eff580-e0d1-11ea-845d-c6b3cbb16ef7.png)

Se tiver uma alma caridosa que possa talvez mandar o código que eu acho que não deve ser muito complicado, eu mesmo implanto aqui pra funcionar e agradeceria muito!
Obrigado!

**Comment by Pr3d4dor** [comment]
@guskid Isso não é tão complicado de fazer, porém iria requerer mudança no banco de dados para associado o id do usuário que cadastrou na tabela clientes.

**Comment by guskid** [comment]
> @guskid Isso não é tão complicado de fazer, porém iria requerer mudança no banco de dados para associado o id do usuário que cadastrou na tabela clientes.

Sério cara, não conseguiria me dar uma ajuda brother?

**Comment by Pr3d4dor** [comment]
Consigo, porém não é uma modificação que eu poderia colar o código aqui e você pegar e usar. Tem que modificar vários arquivos.

Eu não acho essa modificação interessante para todos do mapos pois você foi o primeiro a pedir.

Mas basicamente no cadastro de cliente você precisa salvar o usuario_id na tabela cliente, numa nova coluna. Aí no relatório de clientes você iria fazer um join para buscar o usuário que cadastrou o cliente e exibir.
