### ISSUE TITLE
como faço para retornar o produto ao estoque caso eu exclua uma venda?qual arquivo esta esse codigo e como ficaria?obrigado.

### ISSUE THREAD

**Issue by felipeoliveira92** [RamonSilva20/mapos#914]
eu alugo objetos e como crio uma venda o estoque sempre diminui, como posso alterar para que quando eu exclua minha venda o estoque retorne?

**Comment by Pr3d4dor** [comment]
@felipeoliveira92 Na exclusão da venda você precisa passar nos produtos dessa venda antes de excluir e realizar a adição da quantidade dos mesmos no estoque.
