### ISSUE TITLE
Pesquisa por cliente financeiro>lancamentos

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#915]
atualmente fica trabalhaso fazer uma baixa de cobrança a um cliente quando voce tem muitos cliente,pensando nisso
a ideia de colocar pesquisa por clientes em lançamentos>financeiro

![image](https://user-images.githubusercontent.com/69607468/90551808-447b4880-e168-11ea-9e77-8fb7f8576c69.png)

**Comment by Pr3d4dor** [comment]
@vksaghaz Obrigado pela sugestão, iremos implementar quando possível.
