### ISSUE TITLE
Erro ao Imprimir Relatórios

### ISSUE THREAD

**Issue by Welder01** [RamonSilva20/mapos#916]
** Descreva o bug **
Olá a todos, estou com o seguinte erro ao gerar relatórios, desperta a seguinte tela.

![erro de relatorio mapos](https://user-images.githubusercontent.com/67652692/90576836-a56d4580-e195-11ea-9b9d-d5bb3cfcd9a1.png)

Versão utilizada:
MAPOS V4.12.1.

**Comportamento esperado**
Gerar Relatórios em PDF.

Alguém poderia me ajudar?

**Comment by Pr3d4dor** [comment]
Vá em Configurações >> Emitente e atualize o logo de sua empresa. Caso o problema persista, será necessário usar outro formato de imagem.

**Comment by Welder01** [comment]
Obrigado !

Correu tudo bem !!!
