### ISSUE TITLE
Erro 404 ao acessar relatorio

### ISSUE THREAD

**Issue by Bruno28121** [RamonSilva20/mapos#920]
** Descreva o bug **
Erro ao acesso relatorios

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Nao acessa nenhum relatorio da erro 404

**Comment by Pr3d4dor** [comment]
Vá em Configurações >> Emitente e atualize o logo de sua empresa. Caso o problema persista, será necessário usar outro formato de imagem.

Caso não funcionar acesse a pasta application/logs e verifique os logs de erro.

**Comment by Bruno28121** [comment]
Coloque imagem 130x130 e mesmo assim ainda esta dando erro

**Comment by Bruno28121** [comment]
[log.txt](https://github.com/RamonSilva20/mapos/files/5219361/log.txt)
Segue log

**Comment by Bruno28121** [comment]
Alguma solução ?

**Comment by Pr3d4dor** [comment]
```
ERROR - 2020-09-14 14:52:22 --> 404 Page Not Found: Relatorios/servicos
ERROR - 2020-09-14 15:00:19 --> 404 Page Not Found: Relatorios/clientes
ERROR - 2020-09-14 15:00:32 --> 404 Page Not Found: Relatorios/os
ERROR - 2020-09-14 15:05:12 --> 404 Page Not Found: Relatorios/os
ERROR - 2020-09-14 15:07:43 --> 404 Page Not Found: Relatorios/os
ERROR - 2020-09-14 15:08:04 --> 404 Page Not Found: Relatorios/clientes
```

Parece que tem alguma coisa configurada incorretamente na sua hospedagem.

Tudo está configurado corretamente?

**Comment by Bruno28121** [comment]
esta sim , o sistema esta rodando normal

Em qua., 16 de set. de 2020 às 18:06, Gianluca Bine <
notifications@github.com> escreveu:

**Comment by Bruno28121** [comment]
> ```
> ERROR - 2020-09-14 14:52:22 --> 404 Page Not Found: Relatorios/servicos
> ERROR - 2020-09-14 15:00:19 --> 404 Page Not Found: Relatorios/clientes
> ERROR - 2020-09-14 15:00:32 --> 404 Page Not Found: Relatorios/os
> ERROR - 2020-09-14 15:05:12 --> 404 Page Not Found: Relatorios/os
> ERROR - 2020-09-14 15:07:43 --> 404 Page Not Found: Relatorios/os
> ERROR - 2020-09-14 15:08:04 --> 404 Page Not Found: Relatorios/clientes
> ```
> 
> Parece que tem alguma coisa configurada incorretamente na sua hospedagem.
> 
> Tudo está configurado corretamente




Poderia me ajudar , se precisar te passo ate os acessos , pois esta me dando um dor de cabeça muito grande este problema.

**Comment by Pr3d4dor** [comment]
@Bruno28121 Posso sim, envie os acessos para: gian_bine@hotmail.com, porém vou poder olhar somente de noite pois eu trabalho em horário comercial.
