### ISSUE TITLE
Pesquisa por numero de OS

### ISSUE THREAD

**Issue by marquinhomaquinas** [RamonSilva20/mapos#922]
O programa esta muito bom, ja faz um tempo que estou usando e hj ao consulta um numero de OS notei que poderia ter o nome do cliente, apos a os no campos de pesquisa, ex: OS:2000 para saber o cliente tenho q clicar em visualizar ou editar, se alguem sabe como implementar na div, ficarei muito agradecido.

Novamente muito obrigado pelo programa

**Comment by Pr3d4dor** [comment]
Obrigado pela sugestão, iremos implementar se possível.
