### ISSUE TITLE
erro ao adicionar cpnj 

### ISSUE THREAD

**Issue by turbonetlink** [RamonSilva20/mapos#925]
estou tendro problema ao cadastrar cliente com cnpj aparece cnpj invalido 
![image](https://user-images.githubusercontent.com/12984495/90992151-31abae00-e584-11ea-930a-e4e2598aef33.png)
mais o cnpj é de uma escola e é valido

**Comment by Pr3d4dor** [comment]
@turbonetlink Pode postar o CNPJ aqui, para conferir se o problema é no CNPJ ou na validação.

**Comment by turbonetlink** [comment]
CNPJ: 008.517.397/0001-03

**Comment by Pr3d4dor** [comment]
Esse CNPJ é inválido
Você pode conferir em: https://www.4devs.com.br/validador_cnpj e http://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/cnpjreva_solicitacao.asp

**Comment by turbonetlink** [comment]
pois é esta dando erro no sistema o que pode ser ?

**Comment by Pr3d4dor** [comment]
O sistema não está com erro, o CNPJ é realmente inválido, você pode conferir nos links que eu passei

**Comment by latosinski** [comment]
Para mim está acontecendo o mesmo, tanto com cnpj ou cpf, quando vou cadastrar um novo cliente aparece a mensagem ocorreu um erro ou cnpj inválido.

**Comment by Pr3d4dor** [comment]
@latosinski se você está cadastro um CPF ou CPNJ inválido o erro vai aparecer mesmo.

**Comment by latosinski** [comment]
Já validei o cpf e cnpj neste site, https://www.4devs.com.br, inclusive testei com o meu e o problema persiste, qualquer cpf ou cnpj que tento cadastrar acontece o mesmo erro.

**Comment by latosinski** [comment]
Consegui resolver o problema atualizando o banco de dados pelo terminal com o comando php index.php tools migrate.
Obrigado.
