### ISSUE TITLE
configuração de email sem criptografia

### ISSUE THREAD

**Issue by turbonetlink** [RamonSilva20/mapos#926]
como faço para deixar sem criptografia o email ?

![image](https://user-images.githubusercontent.com/12984495/90996487-49d7f900-e595-11ea-8933-c80a52364276.png)

**Comment by Pr3d4dor** [comment]
Não entendi em qual sentido seria o sem criptografia, já conseguiu arrumar?

**Comment by RamonSilva20** [comment]
Olá @turbonetlink, não é possível de acordo com a documentação do Codeigniter, você tem que usar uma das duas opções: ssl ou tls.
