### ISSUE TITLE
ERRO MPDF NA VERSÃO DO PHP 7.4

### ISSUE THREAD

**Issue by hdarantes** [RamonSilva20/mapos#927]
Boa tarde a todos, tenho uma versão do mapos mais antiga que para a geração dos relatórios utiliza os arquivos já baixados do mpdf, exemplo no arquivo mpdf_helper utilizo: require_once(APPPATH . 'helpers/mpdf/mpdf.php');, porém a versão do PHP do servidor está na 7.4 e deixou de funcionar, baixei o mapos atual e vi que agora o arquivo está utilizando require_once __DIR__ . '/../vendor/autoload.php'; substitui os arquivos da pasta application\helpers pelo novos arquivos do mapos atual, porém, da o seguinte erro 

vendor/autoload.php): failed to open stream: No such file or directory

Filename: helpers/mpdf_helper.php

Pesquisei na internet e vi que tem que instalar o compose para funcionar, porém, não estou sabendo corrigir.

Alguém, poderia por gentileza me informar quais arquivos devo copiar/corrigir para o MPDF voltar a funcionar?

**Comment by Pr3d4dor** [comment]
@hdarantes tente seguir o tutorial: https://github.com/RamonSilva20/mapos/blob/master/Instalacao_xampp_windows.md
