### ISSUE TITLE
Como personalizar sem perder atualizações

### ISSUE THREAD

**Issue by alannsiqueira** [RamonSilva20/mapos#928]
Existe alguma forma de modificação que não interfica no processo de atualização?
No caso quero remover alguns campos obrigatórios e também adicionar outros..

Se não existir e for passível de modificação, se tiver alguma instrução básica posso implementar.

O  form_validation.php é sobrescrito quando é feito a atualização?

**Comment by tonnybarros** [comment]
Todos os arquivos são atualizados, logo o ideal é fazer a atualização manual.
