### ISSUE TITLE
Melhoria relatorio financeiro

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#929]
o relatorio financeiro do mapos e muito bom, queria adicionar uma coisa que me ajudaria muito, e ajudaria todos os contribuintes,
a data da venda, pois fica mais facil de acompanhar, pois ja tem data de vencimento, falta a data da venda.

Atenciosamente, parabéns a todos pelo otimo trabalho !

**Comment by Pr3d4dor** [comment]
Iremos implementar se possível.
