### ISSUE TITLE
Relatorio de vendas

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#930]
uma sugestao de relatorio de  vendas, eu chamo de relatorio de SKU, eu uso pra acompanhar as vendas, dos produtos, e tirar um ticket medio, falta esse tipo de relatorio no MAPOS, onde saia "cliente,numero da venda ex: fatura #01,produto,quantidade , valor vendido, de preferencia em excel, pois com isso fica facil criar um gerenciamento de ticket medio.

Atenciosamente,

**Comment by Pr3d4dor** [comment]
Iremos implementar se possível.
