### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by italorrodrigues** [RamonSilva20/mapos#931]
Ao instalar e configurar o banco de dados em meu servidor web, aparece a seguinte mensagem:

"Sua instalação está incompleta, por favor instale as dependências utilizando o composer. A pasta system não foi localizada."

**Comment by tonnybarros** [comment]
Precisa instalar a pasta vendor e suas dependecias, rodando o composer, ou instale localmente, conforme a descrição do projeto, e suba a pasta vendor para o seu host.
