### ISSUE TITLE
relatorio rapido financeiro

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#932]
encontrei um bug no relatorio rapido financeiro, onde ele pula algumas vendas, isso nao ocorre no custom

![issui 1](https://user-images.githubusercontent.com/69607468/91446530-f47a4100-e84d-11ea-8a5b-ad3e664676a0.png)
![issu 2](https://user-images.githubusercontent.com/69607468/91446545-f6dc9b00-e84d-11ea-8161-07fcd4112c76.png)

**Comment by Pr3d4dor** [comment]
@vksaghaz Obrigado por reportar, iremos corrigir assim que possível.
