### ISSUE TITLE
Adicionar mais um casa depois da virgula Preço Custo e Venda

### ISSUE THREAD

**Issue by eduardjoseph** [RamonSilva20/mapos#934]
Boa tarde Pessoal,
Estou usando o Mapos para um projeto da minha pequena empresa e gostaria de adicionar mais uma casa depois da virgula nos preços de custo e venda de produtos.
Meus produtos são contabilizados com preços por exemplo R$ 0.205, onde o meio centavo faz diferença.

Fiz a alteração no banco de dados para 3 decimais, porem quando coloco o valor no field ele puta para duas casas somente.
Alguma ideia onde possa alterar isso sem dar problema no calculo na venda de multiplos produtos?

**Comment by marcelinoac** [comment]
Bom dia,

Segue exemplo:

Você vai precisar alterar na view o parâmentro echo number_format($var, 2, ',', '.').

O número 2 representa a quantidade de casas, no seu caso é só alterar para 3.

**Comment by eduardjoseph** [comment]
Bom dia marcelinoac, obrigado pela ajuda.

Fiz as alterações no view>produtos>produtos.php
No visual ele mostra os 3 digitos, mas quando vou alterar ele meu terceiro digito e "empurra" a casa para depois da virgula.
Essa "auto correção" do mapos tem como alterar?

**Comment by willph** [comment]
> 
> 
> Bom dia marcelinoac, obrigado pela ajuda.
> 
> Fiz as alterações no view>produtos>produtos.php
> No visual ele mostra os 3 digitos, mas quando vou alterar ele meu terceiro digito e "empurra" a casa para depois da virgula.
> Essa "auto correção" do mapos tem como alterar?

va na pasta **assets** linha 38 e coloque `precision:3`, do arquivo **maskmoney.js**

**Comment by seiscordas** [comment]
e ai pessoal!
eu estou precisando disso tbm no meu caso 4 dígitos depois da virgula, se eu fizer esta alteração no sistema, vou perde quando eu atualizar o sistema, daria pra fazer uma opção nas configurações do sistema pra escolher quantas casas decimais vou precisar, no valor do produto.
