### ISSUE TITLE
Cores do tema

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#935]
** Sua solicitação de feature está relacionada a um problema? Por favor descreva.**
Cores do sistema. Gostaria de ter a possibilidade de voltar para o antigo esquema de cores escuras, como na imagem em anexo.

** Descreva a solução que você deseja **
Apenas mudar a cor do sistema, poderia ser colocada uma opção no menu configurações

** Descreva as alternativas que você considerou **
Uma descrição clara e concisa de qualquer solução ou recurso alternativo que você tenha considerado.

** Contexto adicional **
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.
![dashboard](https://user-images.githubusercontent.com/25686016/91985976-fa1acf80-ed02-11ea-9956-f635566cae45.png)

**Comment by willph** [comment]
Já tem, Fica em Configuração > Sistema.

tem o campo "Tema do Sistema" só mudar de NEVE para Padrão

**Comment by willph** [comment]
![15990523870676242930500417978071](https://user-images.githubusercontent.com/17226802/91987930-0c960880-ed05-11ea-8cc5-b2f285bf76cb.jpg)

Depois que muda para padrão e clicar Salvar Configuração ele muda.

![15990525205062006038674490731311](https://user-images.githubusercontent.com/17226802/91988084-3fd89780-ed05-11ea-817b-48caaeba723c.jpg)

**Comment by SOROInfo** [comment]
No meu sistema não tem essa opção no menu configurações. Estou na última
versão.
Pode me ajudar?

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website https://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qua., 2 de set. de 2020 às 10:12, Wilmerson <notifications@github.com>
escreveu:

**Comment by SOROInfo** [comment]
No meu menu configurações não tem a opção sistema.
Pode me ajudar?

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website https://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qua., 2 de set. de 2020 às 10:16, Wilmerson <notifications@github.com>
escreveu:

**Comment by willph** [comment]
Resolvido no issues #936
