### ISSUE TITLE
Menu configurações

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#936]
** Descreva o bug **
Sistema atualizado para última versão (4.13) mais o menu configurações não apresenta a opção sistema.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'dashboard'
2. Clique em 'configurções'
3. Role para baixo até '....'
4. Ver erro: Não apresenta a opção sistema.

**Comportamento esperado**
O menu configurações deveria apresentar a opção sistema.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [W10]
 - Navegador [Edge Chromium]
 - Versão [85
![dash](https://user-images.githubusercontent.com/25686016/92000575-0b200c80-ed14-11ea-853d-20d09184e0cc.png)
![conf](https://user-images.githubusercontent.com/25686016/92000615-17a46500-ed14-11ea-876d-a6e3929888cf.PNG)

]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by willph** [comment]
Provavelmente não está ativo em permissão. 

Ative em configuração > permissão

**Comment by SOROInfo** [comment]
Resolveu.
Muito obrigado.

Atenciosamente,


*André Fernandes *
*Telefone 15 3222-0482 | WhatsApp 15 99619-6573*

*Website https://www.soroinfo.com.br <http://www.soroinfo.com.br/>*


Em qua., 2 de set. de 2020 às 12:06, Wilmerson <notifications@github.com>
escreveu:
