### ISSUE TITLE
Erro ao Logar

### ISSUE THREAD

**Issue by jetec2112** [RamonSilva20/mapos#937]
Ao tentar logar,dar o erro, Usuário não encontrado, verifique se suas credenciais estão corretass.
sendo que ja coloquei usuario e senha corretos

**Comment by SalcThy** [comment]
@jetec2112 , você tem que cadastrar o usuário manualmente conforme o @RamonSilva20 especificou aqui nessa issue aqui. https://github.com/RamonSilva20/mapos/issues/371 

Veja se você consegue. :)
