### ISSUE TITLE
Centro de Custo

### ISSUE THREAD

**Issue by mfreitasjr** [RamonSilva20/mapos#939]
Bom dia, estou utilizando o sistema em uma empresa de engenharia no qual vendemos alguns serviços.
gostaria de solicitar a criação da aba "CENTRO DE CUSTO" na qual poderemos cadastras as obras/clientes acrescentar o valor orçado e ao longo da obra ir adicionando os custos , seja ele uma fita isolante, ou custo de cabos cimento etc, para que possamos controlar o quanto gastamos com cada obra e no final ter um relatório do valor orçado com o valor gasto para ver o real lucro em cima da obra. basicamente seria isso 
![WhatsApp Image 2020-09-04 at 14 51 30](https://user-images.githubusercontent.com/70962054/92491989-406fa300-f1c9-11ea-880a-ef8f3677a832.jpeg)
![WhatsApp Image 2020-09-04 at 14 50 59](https://user-images.githubusercontent.com/70962054/92491994-41a0d000-f1c9-11ea-80a3-816dc2830ee5.jpeg)
![WhatsApp Image 2020-09-04 at 14 50 24](https://user-images.githubusercontent.com/70962054/92491998-42396680-f1c9-11ea-8e59-46a0d92c69fc.jpeg)

**Comment by Pr3d4dor** [comment]
@mfreitasjr Essa função é interessante, mas creio que não seria útil no geral para todos os usuários do Mapos, pois parece ser mais utilizada na Engenharia mesmo.

Então não posso implementar isso no mapos geral. Pode ser implementada como uma customização específica somente no teu mapos mesmo, porém atualmente não tenho tempo suficiente para realiza-lá. Se outro colaborador/programador quiser pode entrar em contato na issue.

Também se quiser posso te adicionar no grupo do mapos para você tentar encontrar alguém que implemente essa customização.

**Comment by mfreitasjr** [comment]
@Pr3d4dor obrigado pela resposta, se possível poderia me adicionar no grupo ? 21980615412

**Comment by Pr3d4dor** [comment]
@mfreitasjr O link para entrar no grupo do whatsapp é: https://chat.whatsapp.com/BBtir3aBALeDrGsZKZqU1i
