### ISSUE TITLE
Anexo na área do cliente

### ISSUE THREAD

**Issue by Zaanol** [RamonSilva20/mapos#94]
Boa tarde, comentei a linha do código que verifica se o Cliente tem permissão de anexo na ordem de serviço.
Porém após selecionar uma imagem não é possível anexar, o botão não possui nenhuma funcionalidade.
Consegue me ajudar?
Muito Obrigado.

**Comment by drelldeveloper** [comment]
A sua resposta está na sua pergunta. Retire o comentário feito, assim tudo voltará a funcionar.

**Comment by heliocristaldo** [comment]
Coloca seu código "detalhes_os.php" que corrijo para você.

**Comment by Zaanol** [comment]
Olá, agradeço muito sua ajuda.
Coloquei o arquivo aqui como .log para poder anexar.
[detalhes_os.log](https://github.com/RamonSilva20/mapos/files/1766900/detalhes_os.log)

Obrigado.
