### ISSUE TITLE
ADICIONAR PARA IMPRIMIR CUPOM NAO FISCAL NO ATO DA VENDA

### ISSUE THREAD

**Issue by allexsiilva** [RamonSilva20/mapos#941]
Ola meus amigos programadores, o sistema é incrível e estar mim atendendo muito bem.
queria so que o sistema tivesse uma opção de adicionar e configurar impressora e configurar tamanho, tipo como uma venda, queria efetuar a venda e imprimir em uma impressora nao fiscal.
se possivel teria como deixar o sistema totalmente responsivel para que possa usar pelo smarphone?

obg!

**Comment by Pr3d4dor** [comment]
@allexsiilva A opção atual de imprimir não fiscal da OS não te atende?

Ou você quer essa funcionalidade para vendas também?

A questão do responsivo pode ser feita, mas levaria um tempo considerável.

**Comment by allexsiilva** [comment]
A opção atual de imprimir não fiscal da OS não te atende?
 R:  Sim estar otimo a ordem de serviço.

Eu queria para imprimir no ato da venda o cupom nao fiscal tinha como?

A questão do responsivo pode ser feita, mas levaria um tempo considerável.
R: Tudo bem, questao do responsivo posso esperar, o principal queria so que imprimisse cupom nao fiscal em impressora termica todos os tamanhos.

vc acha que tem como adicionar essa função para imprimir cupom na hora de efetuar a venda?

**Comment by Pr3d4dor** [comment]
@allexsiilva É possível, mas vai levar um tempo. Iremos implementar se possível.
