### ISSUE TITLE
[XLSXWriter()] Erro ao gerar XLS 

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#942]
![image](https://user-images.githubusercontent.com/68172360/92526197-7463bc00-f1fb-11ea-9072-c240fcde9258.png)

Tenho problemas ao imprimir em XLS. o erro sempre é apresentado.
Como resolver?

**Comment by Pr3d4dor** [comment]
@monutb91 Essa dependências é instalada pelo composer, recomendo rodar o comando `composer install` novamente.

**Comment by monutb91** [comment]
> 
> 
> @monutb91 Essa dependências é instalada pelo composer, recomendo rodar o comando `composer install` novamente.

Estou usando pelo servidor da hostgator. Rodei o composer na minha maquina (XAMPP) e importei tudo pra lá. Sabe me dizer onde salva essa dependência para que eu consiga pegar só ela?

**Comment by Pr3d4dor** [comment]
Todas as dependencias são salvas na pasta `application/vendor`

**Comment by Pr3d4dor** [comment]
A dependencia é essa: https://github.com/mk-j/PHP_XLSXWriter

Então provavelmente ficará dentr de `application/vendor` em uma pasta chamada `mk-j`.

**Comment by monutb91** [comment]
> 
> 
> A dependencia é essa: https://github.com/mk-j/PHP_XLSXWriter
> 
> Então provavelmente ficará dentro de `application/vendor` em uma pasta chamada `mk-j`.

Sim, consegui instalar no xampp com o composer. Ai copiei a posta e joguei no mesmo caminho, mas no meu servidor hostgator. Porem no hostgator não funcionou. no xampp sim.

**Comment by Pr3d4dor** [comment]
Não adianta jogar somente a pasta, precisa ser a pasta `vendor` inteira por causa do autoload.php

**Comment by monutb91** [comment]
No meu composer não constava a instrução "mk-j/php_xlsxwriter": "^0.38.0" atualizei conforme os diretorios daqui e agora foi ^^
