### ISSUE TITLE
api maecado pago 

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#943]
![image](https://user-images.githubusercontent.com/68172360/92528280-e38edf80-f1fe-11ea-8b28-d5961c13acc1.png)

Fiz a configuração do mercado pago, mas não estou sabendo onde ela é utilizada.
Não encontro o botão para realizar pagamento. 

alguém saberia ajudar?

**Comment by Pr3d4dor** [comment]
Se eu não me engano é no Faturamento que você consegue utilizar, mas o @willph pode te ajudar melhor.

**Comment by willph** [comment]
O botão está por enquanto apenas em Visualizar os.

**Comment by monutb91** [comment]
> 
> 
> O botão está por enquanto apenas em Visualizar os.

Pela Area do cliente ou pelo principal? Não consegui localizar este botão. :(

**Comment by willph** [comment]
Área do admin.
Ainda falta adaptar em outras áreas.

**Comment by Paul0Silva** [comment]
Também estou procurando e não encontrei. Alguém pode demonstrar onde é exatamente?

**Comment by BESystemInfo** [comment]
Ao clicar em visualizar OS, fica praticamente no rodapé da pagina

![20200918_095154](https://user-images.githubusercontent.com/48297443/93599603-c4c5e100-f994-11ea-95b7-415c30d1d2f9.jpg)

**Comment by Paul0Silva** [comment]
@BESystemInfo firmeza? Quando vamos adicionar uma credencial de pagamento, tem que ser uma valida? Pois se sim, acho que esse é o problema. Preenchi a credencial com valores aleatórios só pra testar e acho que por esse motivo essa opção "Gerar Pagamento" não está aparecendo.

**Comment by monutb91** [comment]
> 
> 
> @BESystemInfo firmeza? Quando vamos adicionar uma credencial de pagamento, tem que ser uma valida? Pois se sim, acho que esse é o problema. Preenchi a credencial com valores aleatórios só pra testar e acho que por esse motivo essa opção "Gerar Pagamento" não está aparecendo.

Acredito que não seja isto. Pois há uma condição que se as credenciais estiverem vazias, o botão não é mostrado. Não há verificação de validação. Ao menos eu não encontrei e, verifiquei o codigo inteiro. 

Quanto a replicar a outras paginas, é bem simples. Alterando Controller, Model e View.

**Comment by robertonfaustino** [comment]
onde eu coloco essas credenciais de pagamento? nao encontrei essa tela
