### ISSUE TITLE
Despesas e Receitas recorrentes

### ISSUE THREAD

**Issue by leokart78** [RamonSilva20/mapos#944]
Minha sugestão é habilitar um campo de recorrência para lançamento de receitas e despesas, inicialmente pelo menos mensal depois poderia pensar em outros períodos.
Pois para funcionar o fluxo de caixa essa informação é fundamental, e tornando os lançamentos recorrentes facilitaria a vida de todos tanto para lançamento de despesas fixas como despesas variáveis.

![image](https://user-images.githubusercontent.com/70982067/92532218-391aba80-f206-11ea-8bde-29711e81b6c2.png)

**Comment by Pr3d4dor** [comment]
@leokart78 Obrigado pela sugestão, iremos implementar se possível.

**Comment by leokart78** [comment]
> @leokart78 Obrigado pela sugestão, iremos implementar se possível.

Obrigado pelo retorno, vejo muito potencial nesse aplicativo e gostaria de patrocinar horas de desenvolvimento para essa função e outras.
