### ISSUE TITLE
E-mail não envia e fica pendente.

### ISSUE THREAD

**Issue by WBV-CWB** [RamonSilva20/mapos#945]
Boa noite a todos, tudo bem ?

Primeiro adoro o MAPOS e essa versão é bacana de mais a nova.

Bom, primeiro, não consigo mandar a OS para o e-mail eu vi que tem que configurar um tal de cron jobs e não entendi NADA, sou bem leigo na parte de programação ( larguei a faculdade no ultimo ano, não achei trampo e virei motoboy, depois voltei a ser técnico ... é a vida haha.)

Sei bem o basico e essa parte de cron jobs não entendi nada, tenho que configurar algo ali no localhost antes de mandar para hospedagem? isso? que bem sinceramente to o dia todo e não achei nada sobre isso. =/ 

E ele fica só em pendente mesmo configurando o EMAIL.PHP.

**Comment by Pr3d4dor** [comment]
Você está rodando localmente?

Se sim, veja se esse tutorial lhe ajuda: https://github.com/RamonSilva20/mapos/blob/master/Instalacao_xampp_windows.md

**Comment by WBV-CWB** [comment]
Por enquanto localmente, mas queria subir para hospedagem, não sei se seria melhor fazer isso por lá. .. Vou ver aqui..

**Comment by WBV-CWB** [comment]
Cara, ali tudo já fiz... ele ta rodando, só não manda e-mail XD...

o meu email.php ta assim, já posto imagem vou logar na máquina windows ali e já posto aqui haha

**Comment by WBV-CWB** [comment]
![image](https://user-images.githubusercontent.com/70992721/92551475-6f6f2e80-f234-11ea-9129-af7ba6cb9d32.png)


![image](https://user-images.githubusercontent.com/70992721/92551525-9a598280-f234-11ea-8405-0366f6f34c8d.png)


Ta assim e não sai do pendente a logo ta cortada, do msmo tamanho e só ali que ficou assim haha... mas da nada.

**Comment by Pr3d4dor** [comment]
Você precisa criar um arquivo bat e usar o gerenciador de tarefas para enviar o email.

O arquivo bat precisa executar os comandos:
```
Configurar cron jobs para envio de e-mail:
Enviar emails pendentes a cada 2 minutos.

    */2 * * * * php /var/www/index.php email/process

Enviar emails com falha a cada 5 minutos.

    */5 * * * * php /var/www/index.php email/retry

```

**Comment by WBV-CWB** [comment]
Puts cara... como disse nessa parte de programação sou meio perdido, sei o que aprendi no tecnlogo que é o basico..

Não entendi ainda, mas já tenho um nome que é o arquivo, vou ver aqui e ... me viro daqui para frente, não quero ficar ocupando o forum com algo que eu acho que deve ser ridiculamente simples ...

**Comment by Pr3d4dor** [comment]
@WBV-CWB Na hospedagem você tem essa opção?

Lá é mais fácil de configurar.

**Comment by WBV-CWB** [comment]
Opa, pelo que andei lendo desse  "CRON JOB" vi que tem algo assim:


![Screen Shot 2020-09-11 at 01 14 30](https://user-images.githubusercontent.com/70992721/92858241-310c7780-f3cc-11ea-873e-ed8e3a70e9c1.png)

![Screen Shot 2020-09-11 at 01 16 18](https://user-images.githubusercontent.com/70992721/92858457-76c94000-f3cc-11ea-913e-3d60d454f38a.png)


![Screen Shot 2020-09-11 at 01 16 25](https://user-images.githubusercontent.com/70992721/92858481-7b8df400-f3cc-11ea-8f02-b7b57d489208.png)


Mas confesso que não tive tempo de ver algo a fundo, mas confesso que to meio boiando nisso aqui haha

**Comment by Pr3d4dor** [comment]
@WBV-CWB É usando esse cron job mesmo, onde você coloca o caminho completo da pasta na hospedagem contendo o mapos e o index.php igual está no README.md

**Comment by rohanbernartt** [comment]
Não usava o envio de email. Ontem resolvi testar. 
O meu ele roda o Cron, porque o email sai do status de Pendente pra Enviado.

Porém não chega email nas caixas de entrada.
Nem do cliente, nem minha, nem do téccnico.

**Comment by Pr3d4dor** [comment]
@rohanbernartt Já verificou na caixa de spam?

**Comment by rohanbernartt** [comment]
Verifiquei, não chegou nada. 
E tentei envio para vários emails de dominio proprio, gmail, e nenhum chegou

**Comment by visaotec** [comment]
> Verifiquei, não chegou nada.
> E tentei envio para vários emails de dominio proprio, gmail, e nenhum chegou



> Verifiquei, não chegou nada.
> E tentei envio para vários emails de dominio proprio, gmail, e nenhum chegou

eu também já tentei de tudo e o meu sistema está online e os e-mail  nao enviam ...

**Comment by WBV-CWB** [comment]
Galera, desculpa o sumiço... mas esse mês foi corrido de mais =/... só consegui sentar na frente do pc agora.

cara, nem entendi como configura esse corn job ainda 0,0... foi mau a burrice ta?

mas vou ver se vou atrás essa semana, mas eu não consegui isso ainda.

**Comment by rohanbernartt** [comment]
@WBV-CWB usa as configurações comuns, que já vai te carregar os Horários que precisa.  _Só não pode o mesmo cron no mesmo tempo, no caso o Retry_

Minha dificuldade ainda é sobre a saída desse emails que não estão chegando nos Destinatários.

**Comment by Pr3d4dor** [comment]
@rohanbernartt Tem como você postar os logs que ficam em application/logs para que eu tente ajudar?

Lá ficam os logs também quando dispara email.

**Comment by visaotec** [comment]
> @WBV-CWB usa as configurações comuns, que já vai te carregar os Horários que precisa. _Só não pode o mesmo cron no mesmo tempo, no caso o Retry_
> 
> Minha dificuldade ainda é sobre a saída desse e-mails que não estão chegando nos Destinatários.

eu já revirei sobre o assunto e não acho nada que resolve o problema do envio do e-mail e não vejo ninguém  falando que deu certo ... meu sistema está online ... tudo configurado e não envia... só fica pendente....

**Comment by Pr3d4dor** [comment]
@visaotec Se só fica pendente, então talvez o cron não está conseguindo executar o PHP para realizar o envio do e-mail. Tente olhar também o log dos crons.

**Comment by visaotec** [comment]
> @visaotec Se só fica pendente, então talvez o cron não está conseguindo executar o PHP para realizar o envio do e-mail. Tente olhar também o log dos crons.

Qual seria o passo a passo  certo pra configurar o crons na hospedagem online?

**Comment by Pr3d4dor** [comment]
@visaotec Depende da sua hospedagem.

**Comment by visaotec** [comment]
> @visaotec Depende da sua hospedagem.

Cpanel que uso

**Comment by Pr3d4dor** [comment]
@visaotec Mesmo sendo Cpanel, apresenta diferenças dependendo da hospedagem (Locaweb, Hostinger, etc). Aqui tem um exemplo: https://www.hostinger.com.br/tutoriais/tarefas-cron-cpanel/

**Comment by visaotec** [comment]
> @visaotec Depende da sua hospedag

> @visaotec Mesmo sendo Cpanel, apresenta diferenças dependendo da hospedagem (Locaweb, Hostinger, etc). Aqui tem um exemplo: https://www.hostinger.com.br/tutoriais/tarefas-cron-cpanel/

Acabei de fazer o processo e foi sem sucesso ....
https://www.youtube.com/watch?v=huFYEcPS8hg

**Comment by Pr3d4dor** [comment]
@visaotec Como disse anteriormente, já olhou nos logs do cron para ver os erros?

**Comment by visaotec** [comment]
> @visaotec Como disse anteriormente, já olhou nos logs do cron para ver os erros?

já sim .. eu tenho mais sistemas hospedado na mesma e funciona os e-mail normalmente

**Comment by Pr3d4dor** [comment]
@visaotec De qualquer forma, coloque os logs do cron e da pasta application/logs aqui, assim fica mais fácil pra ajudar.

**Comment by rohanbernartt** [comment]
A minha pasta application/logs só tem um arquivo: `index.html`.
Tem algum lugar pra habilitar os logs?

**Comment by Pr3d4dor** [comment]
@rohanbernartt Você está usando a última versão do mapos?

Os logs são habilitados por padrão.

**Comment by rohanbernartt** [comment]
Sim, estou na versão 4.17.1

**Comment by WBV-CWB** [comment]
Só me tirem uma duvida sobre esse comando, o que vai ficar isso no caso :

/usr/local/bin/php /home2/alter237/public_html/mapos4/application/config/email.php 

Isso?

que lá ta README.MD
ta assim :

php /var/www/index.php email/process

não entendi esse var/www ai o index.php e depois outra pasta?


Se alguém puder me indicar esse caminho certinho eu agradeço, que não entendi não.

**Comment by WBV-CWB** [comment]
Pois é ... agora to igual o amigo de cima kkk 

o E-mail VAI, mas nunca chega xD.

Se perder no limbo da net.

Caminho ficou:
/usr/local/bin/php /home2/alter237/public_html/sistemaAlter/index.php email/process

e não da arquivo de log nem nada, recebi uma vez só um e-mail ENORME com vários códigos, mas depois não recebi nada, porém o e-mail não chega =/

 o que pode ser será?
