### ISSUE TITLE
OPÇÃO DE TIPO DE PRODUTO.

### ISSUE THREAD

**Issue by WBV-CWB** [RamonSilva20/mapos#946]
Uma dica para abertura de OS tipo dar opção de o pessoa add o tipo de produto por exemplo:

SMARTPHONE
PC
NOTE 
VIDEO-GAME 

E por ai vai... dependendo da Opção abrir uma caixa pedindo Serial ou IMEI do aparelho.

Não sei se todos acham uma boa, mas eu acho que ajudaria, tentei por aqui... mas sou muito bisonho com programação XD... se tivesse me dedicado na época não tava tão ruim assim talvez haha 

Mas parabéns, programinha é show de bola ajuda muito.

**Comment by Pr3d4dor** [comment]
@WBV-CWB Não consegui entender muito bem a sua sugestão, pode explicar melhor?

**Comment by WBV-CWB** [comment]
Opa tudo bem amigo? foi mau a demora, dia corrido, sabe como é.

![EXEMPLO](https://user-images.githubusercontent.com/70992721/92860110-42568380-f3ce-11ea-998a-11b115218803.png)


Ignora a PHOTOSHOPADA PÉSSIMA AQUI haha 

Tipo colocar uma caixa de seleção como a de status, mas com "PC", "Notebook" e por aí vai ... da seleção aparecer tipo digite o IMEI ou serial number da máquina/celular ( seja qual for).

Não sei se ficou mais claro agora e nem se é uma boa dica... Eu acho uma boa para organizar bem na assistência pro pessoal, pelo menos tem ali o SN e tal ( duro se a máquina não tem como pc, mas é bom para organizar.)

Bom, obrigado desde já ^^

**Comment by marquinhomaquinas** [comment]
Boa tarde, neste caso vc tem q alterar o banco, ou seja criar as colunas na tabela os e depois adicionar os campos
 aqui vc muda o q deseja

/var/www/html/mapos-master4/application/config/form_validation.php:
  224          ],
  225          [
  226:             'field' => 'osequipamento',
  227              'label' => 'Equipamento',
  228              'rules' => 'trim',
-------------------------
/var/www/html/mapos-master4/application/views/os/adicionarOs.php:
   92  
   93                                          <div class="span3">
   94:                                             <label for="osequipamento">Equipamento</label>
   95:                                             <input id="osequipamento" type="text" class="span12" name="osequipamento" value="" />
---------------------------------------
/var/www/html/mapos-master4/application/views/os/editarOs.php:
  148  
  149                                          <div class="span3">
  150:                                             <label for="osequipamento">Equipamento</label>
  151:                                             <input id="osequipamento" type="text" class="span12" name="osequipamento" value="<?php echo $result->osequipamento ?>" />
  152  
------------------------
assim por diante, vc copia com cuidado, e sempre no lugar do meu exemplo osequipamento vc colocar o q deseja, como numeromei ou equipamento, vai de vc, tem q ser igual ao nome da coluna do banco

**Comment by WBV-CWB** [comment]
> Boa tarde, neste caso vc tem q alterar o banco, ou seja criar as colunas na tabela os e depois adicionar os campos
> aqui vc muda o q deseja
> 
> ## /var/www/html/mapos-master4/application/config/form_validation.php:
> 224 ],
> 225 [
> 226: 'field' => 'osequipamento',
> 227 'label' => 'Equipamento',
> 228 'rules' => 'trim',
> ## /var/www/html/mapos-master4/application/views/os/adicionarOs.php:
> 92
> 93
> 
> 94: Equipamento
> 95:
> ## /var/www/html/mapos-master4/application/views/os/editarOs.php:
> 148
> 149
> 
> 150: Equipamento
> 151:
> 152
> assim por diante, vc copia com cuidado, e sempre no lugar do meu exemplo osequipamento vc colocar o q deseja, como numeromei ou equipamento, vai de vc, tem q ser igual ao nome da coluna do banco
> 
> eu coloquei o codigo, mas nao ficou visivel, nao sei pq





Cara, fiz tudo como falou, mas ele não salva no banco de dados =/... Não tem mais nada para modificar não ?
