### ISSUE TITLE
lançamento de financeiro

### ISSUE THREAD

**Issue by vksaghaz** [RamonSilva20/mapos#947]
Porfavor,
adicionar a opção de busca por clientes no lançamento financeiro, leva muito tempo procurando um titulo...

Atenciosamente,

**Comment by Pr3d4dor** [comment]
@vksaghaz Obrigado pela sugestão, iremos implementar assim que possível.

**Comment by acinformatica2004** [comment]
Boa noite, eu tenho uma aba no vizualizar do cliente que tem os lançamentos deste cliente. Se quiser envio o código pra vc.

**Comment by vksaghaz** [comment]
opa quero sim !!!

________________________________
De: acinformatica2004 <notifications@github.com>
Enviado: sábado, 12 de setembro de 2020 20:43
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: vksaghaz <dhiego_55@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] lançamento de financeiro (#947)


Boa noite, eu tenho uma aba no vizualizar do cliente que tem os lançamentos deste cliente. Se quiser envio o código pra vc.

**Comment by acinformatica2004** [comment]
Me passa o email que te envio o meu arquivo.

**Comment by vksaghaz** [comment]
dhiego_55@hotmail.com

________________________________
De: acinformatica2004 <notifications@github.com>
Enviado: quarta-feira, 16 de setembro de 2020 22:41
Para: RamonSilva20/mapos <mapos@noreply.github.com>
Cc: vksaghaz <dhiego_55@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [RamonSilva20/mapos] lançamento de financeiro (#947)


Me passa o email que te envio o meu arquivo.
