### ISSUE TITLE
Bug ao digitar na ordem de servico no Celular

### ISSUE THREAD

**Issue by cabralwms** [RamonSilva20/mapos#950]
Boa noite pessoal. Quando estou tentando editar a ordem de servico pelo celular a cada palavra que dou espaco ele fecha o teclado.
Alguem mais ja percebeu isso? Seria problema no codigo do sistema?

**Comment by Pr3d4dor** [comment]
Tentou utilizar outro navegador?

**Comment by cabralwms** [comment]
utilizei 2 o chrome para celular e o da propria samsung.

**Comment by marcelinoac** [comment]
Boa tarde, 

Começou a acontecer isso comigo também. Uso uma versão personalizada baseada na versão 3.8.
Não fiz nenhuma alteração e há dois dias começou a acontecer isso.

**Comment by Pr3d4dor** [comment]
Alguém de vocês consegue postar um vídeo reproduzindo o erro?

**Comment by marcelinoac** [comment]
Assim como começou do nada, parou do nada também. Hoje já está funcionando normalmente a edição de OS pelo smartphone.
