### ISSUE TITLE
Erro ao atualizar sistema

### ISSUE THREAD

**Issue by SOROInfo** [RamonSilva20/mapos#952]
** Descreva o bug **
Erro ao utilizar sistema interno de atualização do sistema.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'CONFIGURAÇÕES'
2. Clique em 'SISTEMA'
3. Role para baixo até 'ATUALIZAR MAPOS'
4. Ver erro

**Comportamento esperado**
TELA DE ERRO, PRINT EM ANEXO.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [W10]
 - Navegador [EDGE, CHROMIUM]
 - Versão [85]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
![erro-mapos-update](https://user-images.githubusercontent.com/25686016/93207951-21759180-f732-11ea-99a4-1a1083d49155.png)

**Comment by Pr3d4dor** [comment]
@SOROInfo O atualizador está com alguns bugs, por isso por enquanto recomendo atualizar manualmente ao invés de atualizar pelo sistema.
