### ISSUE TITLE
MAPOS OS

### ISSUE THREAD

**Issue by rhormens-81** [RamonSilva20/mapos#953]
Pessoal, no campo de OS (adicionar os), tem como retirar a trava de somente colocar cliente cadastrado. As vezes loja lotada, não da tempo de cadastrar naquele momento .. somente abrir a ordem e imprimir em duas vias. Ai depois vou no historico de ordem e cadastro esse cliente

**Comment by Pr3d4dor** [comment]
@rhormens-81 Essa modificação é possível mas iria quebrar várias partes do sistema, então não ẽ tão simples de implementar.

**Comment by BESystemInfo** [comment]
Uma sugestão. Cadastra um cliente coringa, e coloca as informações no campo de anotações. É uma alternativa para o que vc descreveu.

**Comment by mandruuuu** [comment]
Coloquei a opção de cadastrar um cliente ao abrir o "ADD OS" por modal, mas não estou conseguindo fazer cadastrar, ao invés de fechar o modal e retornar na "digitação" do nome do cliente, ele da erro, como se tivesse tentando salvar a OS sem informar o cliente.
[adicionarOs.txt](https://github.com/RamonSilva20/mapos/files/5235562/adicionarOs.txt)

**Comment by rhormens-81** [comment]
@Pr3d4dor   vi que ele tem um  banco mysql  so para os ... ele  precisaria colocar la o  nome  que eu escrever independente do cadastro. As  travas de cadastrar telefone | cpf | endereço no cadastro de cliente ja removi e deu certo.
Agora preciso que na OS eu coloque qq nome e ele aceite

**Comment by Pr3d4dor** [comment]
@rhormens-81 Não é tão simples assim, o cliente é relacionado à OS via chave estrangeira e em todo o sistema é carregado o cliente da OS fazendo join, então não é só "salvar o nome lá".

O que você pode fazer mesmo é usar um cliente coringa como comentado acima.

**Comment by trollfalgar** [comment]
Acho que seria fácil add um botão para add um novo cliente, ao lado do campo de escolher o cliente.
Ao clicar, abre-se uma modal com o formulário básico de cadastro de cliente.

Ao cadastrar o cliente, retorna os dados, e add no campo.

**Comment by rhormens-81** [comment]
Nossa .. isso seria fantástico ....

Em ter, 22 de set de 2020 16:09, Tiago Oliveira <notifications@github.com>
escreveu:
