### ISSUE TITLE
Erro após atualizar o mapos 4.11.2

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#954]
Pessoal bom dia,

Alguem pode me ajudar? Atualizei o Mapos via sistema, da versão 4.11.2 e assim que finalizou não consigo retornar para o login.

Informa que o sistema já está instalado.
![Capturar](https://user-images.githubusercontent.com/64565246/93612835-66a1f980-f9a6-11ea-9cc6-d152b46a1c1d.PNG)

**Comment by TK2KMG** [comment]
Veja na página index.php, atualize a linha 59 de "install" para "production".

**Comment by jhonatanmoraiscosta** [comment]
Obrigado pela dica, consegui resolver exportando o banco de dados e instalando novamente o sistema.
