### ISSUE TITLE
Erro 404  Página não encontrada

### ISSUE THREAD

**Issue by lsaandrade** [RamonSilva20/mapos#955]
Preciso ajuda. Efetuei a instalação local através do Xampp e fui tudo bem. Subi uma nova aplicação para o web server Kinghost e apareceu a tela inicial de instalação onde aparentemente preenchi tudo corretamente. Após instalar, apresenta a mensagem de página não encontrada. Alguém poderia ajudar-me? Uma luz do que poderia estar acontecendo?

**Comment by Pr3d4dor** [comment]
@lsaandrade Tem como postar os logs de erro?

**Comment by lsaandrade** [comment]
@Pr3d4dor Tem o arquivo php_erro no diretório raiz mas está vazio.

**Comment by Pr3d4dor** [comment]
@lsaandrade Tente instalar tudo novamente do zero ou talvez foi configurado algo incorretamente.

**Comment by lsaandrade** [comment]
@Pr3d4dor Já instalei 3 vezes. Instalei na raiz, na pasta www, com outro nome e deu o mesmo. Mas vou zerar tudo e instalar tudo novamente e reporto se dará o mesmo erro.

**Comment by Pr3d4dor** [comment]
@lsaandrade Se vc conseguir postar os logs da pasta `applicaiton/logs` ajudaria. Também se possível os logs de erro na hospedagem.

**Comment by lsaandrade** [comment]
Boa noite @Pr3d4dor só consegui mexer hoje no sistema. Segue os logs.
INFO - 2020-09-23 23:45:07 --> Config Class Initialized
INFO - 2020-09-23 23:45:07 --> Hooks Class Initialized
DEBUG - 2020-09-23 23:45:07 --> UTF-8 Support Enabled
INFO - 2020-09-23 23:45:07 --> Utf8 Class Initialized
INFO - 2020-09-23 23:45:07 --> URI Class Initialized
DEBUG - 2020-09-23 23:45:07 --> No URI present. Default controller set.
INFO - 2020-09-23 23:45:07 --> Router Class Initialized
INFO - 2020-09-23 23:45:07 --> Output Class Initialized
INFO - 2020-09-23 23:45:07 --> Security Class Initialized
DEBUG - 2020-09-23 23:45:07 --> Global POST, GET and COOKIE data sanitized
INFO - 2020-09-23 23:45:07 --> Input Class Initialized
INFO - 2020-09-23 23:45:07 --> Language Class Initialized
INFO - 2020-09-23 23:45:07 --> Language Class Initialized
INFO - 2020-09-23 23:45:07 --> Config Class Initialized
INFO - 2020-09-23 23:45:07 --> Loader Class Initialized
INFO - 2020-09-23 23:45:07 --> Helper loaded: url_helper
INFO - 2020-09-23 23:45:07 --> Helper loaded: audit_helper
INFO - 2020-09-23 23:45:07 --> Helper loaded: date_helper
INFO - 2020-09-23 23:45:07 --> Helper loaded: dd_helper
INFO - 2020-09-23 23:45:07 --> Helper loaded: validation_helper
INFO - 2020-09-23 23:45:07 --> Helper loaded: general_helper
INFO - 2020-09-23 23:45:07 --> Database Driver Class Initialized
INFO - 2020-09-23 23:45:07 --> Session: Class initialized using 'database' driver.
DEBUG - 2020-09-23 23:45:07 --> Permission Class Initialized
INFO - 2020-09-23 23:45:07 --> Controller Class Initialized

Log do WebServer:
[21-Sep-2020 21:22:53 America/Sao_Paulo] PHP Warning:  require_once(/home/pontualinformatica/www/mapos/master/application/vendor/codeigniter/framework/system/core/CodeIgniter.php): failed to open stream: No such file or directory in /home/pontualinformatica/www/mapos/master/index.php on line 306
[21-Sep-2020 21:22:53 America/Sao_Paulo] PHP Fatal error:  require_once(): Failed opening required '/home/pontualinformatica/www/mapos/master/application/vendor/codeigniter/framework/system/core/CodeIgniter.php' (include_path='.:/usr/local/php/7.2/lib/php') in /home/pontualinformatica/www/mapos/master/index.php on line 306

**Comment by Pr3d4dor** [comment]
@lsaandrade Parece que as dependências do composer não foram instaladas corretamente. Consegue verificar?

**Comment by lsaandrade** [comment]
@Pr3d4dor Era a plataforma, estava no NGINX, o suporte do Kinghost mudou para o apache e deu tudo certo. Obrigado a todos.

**Comment by MattiasBn** [comment]
😭😭😭😭😭 eu também estou passando por isso tento hospedar um sit q esta no meu repositório só vem erro me ajudem😭😭😭
