### ISSUE TITLE
Erro ao tentar faturar uma OS

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#956]
Bom dia,

Alguem poderia me dizer oq pode ocasionar este erro ao faturar uma OS? Versão 4.13.1 hospedada no 000webhost.
![image](https://user-images.githubusercontent.com/64565246/93668335-1e481180-fa62-11ea-803b-4a46f961b32d.png)

**Comment by Pr3d4dor** [comment]
Tente verificar os logs de erro e postar aqui para que possamos ajudar melhor.

**Comment by jhonatanmoraiscosta** [comment]
Onde consigo ver os logs dos erros irmao?

**Comment by Pr3d4dor** [comment]
Na pasta `application/logs` na hospedagem.

**Comment by jhonatanmoraiscosta** [comment]
Segue o erro:

![image](https://user-images.githubusercontent.com/64565246/93812142-96abff80-fc27-11ea-8f31-7864fa33e303.png)

**Comment by Pr3d4dor** [comment]
@jhonatanmoraiscosta Pelo que consta nos erros está tentando inserir um lançamento com um valor incorreto para a coluna `data_pagamento`. Tente verificar se seu banco de dados está atualizado ou se por ser hospedagem free a versão do MySQL está ultrapassada.

**Comment by jhonatanmoraiscosta** [comment]
Descobri que ele não deixa faturar se não marcar a caixa (RECEBIDO?) ou seja ele não aceita faturar algo que você vai receber no futuro. O que consegui fazer é faturar como se já tivesse recebido, e somente depois ir nos lançamentos e alterar desmarcando a opção recebido, assim ele vai para a o gráfico Estatísticas financeiras - Pendente.

Os passos que fiz:

1 marcar como recebido para faturar
![image](https://user-images.githubusercontent.com/64565246/93829204-81dd6500-fc43-11ea-804d-01ecf6e9b0be.png)

2 editar o lançamento e remover a opção recebido.
![image](https://user-images.githubusercontent.com/64565246/93829261-a3d6e780-fc43-11ea-8bab-5f25df811233.png)

3 assim o lançamento aparecem no gráfico correto.
![image](https://user-images.githubusercontent.com/64565246/93829307-bfda8900-fc43-11ea-965e-ec555906022f.png)

Pode ser um BUG do sistema?

**Comment by Pr3d4dor** [comment]
@jhonatanmoraiscosta Pode ser bug sim, vou tentar reproduzir o erro aqui. Caso seja, farei a correção e lançarei a correção nos próximos dias.

**Comment by jhonatanmoraiscosta** [comment]
@Pr3d4dor  obrigado irmão. Me avise por favor se este erro é só na minha instalação. 

Att,

**Comment by cabralwms** [comment]
No meu servidor eu consigo lançar sem erro com campo recebido em branco. e ele vai para o pendente

**Comment by Pr3d4dor** [comment]
@jhonatanmoraiscosta Não consegui reproduzir o erro, então creio que está ocorrento só na sua instalação, então pode ser a versão do MySQL, PHP ou outra coisa que esteja ocasionando isso.
