### ISSUE TITLE
versões novas cada vez mais de difícil de instalar.

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#961]
![image](https://user-images.githubusercontent.com/56301435/93768680-259d2580-fbf0-11ea-9a4d-8de61bf78bd4.png)

**Comment by Pr3d4dor** [comment]
@wesley020291 Esse erro está ocorrendo por causa da sua versão do PHP, recomendo usar a última versão sempre que é a 7.4

Caso contrário basta apagar vírgula (",") na linha 421 e deixar somente `$status`.

**Comment by wesley020291** [comment]
![image](https://user-images.githubusercontent.com/56301435/93790101-06f75880-fc09-11ea-91d9-5b1a148ad28a.png)
 pq da esse erro toda vez que entra? troque o php agora esta PHP/7.4.10

**Comment by Pr3d4dor** [comment]
Consegue postar os logs de erro que ficam dentro da pasta `application/logs`?

**Comment by willph** [comment]
Na linha 695 do arquivo painel.php que se encontra na pasta application/view/mapos edite a linha que mencionei para ```url:"<?= base_url(). "index.php/mapos/calendario"; ?>```

Vai resolver esse problema. Mas tem outro identificado que carrega um mesmo evento a mesma quantidade de vezes de produtos e serviços inseridos.

No mais vai funcionar tranquilo.

**Comment by wesley020291** [comment]
> Consegue postar os logs de erro que ficam dentro da pasta `application/logs`?

só tem o index e mais nada nesta pasta

**Comment by Pr3d4dor** [comment]
@wesley020291 Peço desculpas pelos erros, fiz a correção dos problemas lancei a nova versão que corrige: https://github.com/RamonSilva20/mapos/releases/tag/v4.14.1
