### ISSUE TITLE
Agenda falha

### ISSUE THREAD

**Issue by luiscadeira** [RamonSilva20/mapos#962]
Ola,

seria um erro essa mensagem?

[http://www.lc2studiocar.com/admin/application/views/errors/Screenshot_1.jpg](url)

http://www.lc2studiocar.com/admin/application/views/errors/Screenshot_1.jpg

**Comment by Pr3d4dor** [comment]
@luiscadeira Esse erro apenas mostra que não conseguiu carregar as OS para mostrar no calendário, qual versão do PHP você está usando?

Seria bom se conseguir postar os logs de erro que ficam dentro da pasta `application/logs`. Mas esse erro só afeta o calendário/agenda que foi adicionado recentemente.

Hoje a noite irei lançar uma correção.

**Comment by luiscadeira** [comment]
Obrigado,

estou PHP 7.4

esse Log

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2020-09-21 17:01:46 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:02:11 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:02:28 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:02:40 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:02:51 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:03:09 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:03:46 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:04:05 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:04:24 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:04:48 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:04:51 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:04:54 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:05:15 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:05:18 --> Severity: error --> Exception: Call to undefined function convertUrlToUploadsPath() /home/u892492387/domains/lc2studiocar.com/public_html/admin/application/views/relatorios/imprimir/imprimirTopo.php 5
ERROR - 2020-09-21 17:05:18 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:05:26 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:05:30 --> Severity: error --> Exception: Call to undefined function convertUrlToUploadsPath() /home/u892492387/domains/lc2studiocar.com/public_html/admin/application/views/relatorios/imprimir/imprimirTopo.php 5
ERROR - 2020-09-21 17:05:30 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:08:41 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:08:46 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:09:17 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:09:21 --> Severity: error --> Exception: Call to undefined function convertUrlToUploadsPath() /home/u892492387/domains/lc2studiocar.com/public_html/admin/application/views/relatorios/imprimir/imprimirTopo.php 5
ERROR - 2020-09-21 17:09:21 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:09:46 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:14:41 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0
ERROR - 2020-09-21 17:14:59 --> Severity: Core Warning --> Module 'sqlite3' already loaded Unknown 0

**Comment by willph** [comment]
Na linha 695 do arquivo painel.php que se encontra na pasta application/view/mapos edite a linha que mencionei para ```url:"<?= base_url(). "index.php/mapos/calendario"; ?>```

Vai resolver esse problema. Mas tem outro identificado que carrega um mesmo evento a mesma quantidade de vezes de produtos e serviços inseridos. 

No mais vai funcionar tranquilo.

**Comment by luiscadeira** [comment]
@willph  funcionou, mas assim

`url:"<?= base_url(). "index.php/mapos/calendario"; ?>` **Não funcionou**

`url: "<?= base_url() . "index.php/mapos/calendario"; ?>",`    **Sim ok**  

- [ ] [Ficou assim carregamento](http://www.lc2studiocar.com/admin/application/logs/1/agenda1.jpg)

- [ ] [Quando clicar aparece essa tela](http://www.lc2studiocar.com/admin/application/logs/1/agenda2.jpg)

**Comment by willph** [comment]
> @willph funcionou, mas assim
> 
> `url:"<?= base_url(). "index.php/mapos/calendario"; ?>` **Não funcionou**
> 
> `url: "<?= base_url() . "index.php/mapos/calendario"; ?>",` **Sim ok**
> 
> * [ ]  [Ficou assim carregamento](http://www.lc2studiocar.com/admin/application/logs/1/agenda1.jpg)
> * [ ]  [Quando clicar aparece essa tela](http://www.lc2studiocar.com/admin/application/logs/1/agenda2.jpg)

É que mandei pelo celular, deve ter faltado espaçamento.

**Comment by willph** [comment]
E esqueci de fechar aspas

**Comment by luiscadeira** [comment]
Muito obrigado pela ajuda..😀🙌

**Comment by Pr3d4dor** [comment]
@luiscadeira Logo irei disponibilizar mais uma atualização corrigindo o erro:

Sobre esse log:
```
ERROR - 2020-09-21 17:09:21 --> Severity: error --> Exception: Call to undefined function convertUrlToUploadsPath() /home/u892492387/domains/lc2studiocar.com/public_html/admin/application/views/relatorios/imprimir/imprimirTopo.php 5
```

Você precisa rodar o comando `composer dump-autoload` para corrigir e fazer o upload da pasta vendor para a sua hospedagem caso não tiver composer lá.

**Comment by Pr3d4dor** [comment]
@luiscadeira  Peço desculpas pelos erros, fiz a correção dos problemas lancei a nova versão que corrige: https://github.com/RamonSilva20/mapos/releases/tag/v4.14.1
