### ISSUE TITLE
ERRO AO ATUALIZAR PARA VERSÃO MAIS RECENTE PELO SITE 

### ISSUE THREAD

**Issue by turbonetlink** [RamonSilva20/mapos#964]
Boa Noite tentei atulizar diretamente pelo sistema da versão 4.12.1 para mais atual 4.14.1 mais aparece estes erros nas imagens

**
![image](https://user-images.githubusercontent.com/12984495/93830318-442e0b80-fc46-11ea-869a-2d67334651a0.png)
**
![image](https://user-images.githubusercontent.com/12984495/93830235-016c3380-fc46-11ea-883d-dae757d445e8.png)

**Comment by Pr3d4dor** [comment]
@turbonetlink Boa noite, como dito em outras issues, o atualizador está com alguns bugs e eu ainda estou tentando corrigir. Então recomendo atualizar manualmente enquanto não estiver corrigido.
