### ISSUE TITLE
ERRO NA ATUALIZAÇÃO ONLINE 

### ISSUE THREAD

**Issue by jhonatanmoraiscosta** [RamonSilva20/mapos#966]
Não estou conseguindo atualizar da versão 4.13.1 para a nova de 4.14.1 via sistema. O que pode causar?

![image](https://user-images.githubusercontent.com/64565246/93921507-046b3080-fce7-11ea-87ec-92e3b4e6101e.png)

**Comment by Pr3d4dor** [comment]
@jhonatanmoraiscosta Como dito em outras issues o atualizador via sistema está com alguns bugs e estamos tentando corrigir ainda. Por isso peço que por enquanto realize a atualização de forma manual.

**Comment by WBV-CWB** [comment]
O meu baixei a ultima versão hoje, cliquei em atualizar para ver o que rolava e aparece isso :

![Screen Shot 2020-10-19 at 16 19 40](https://user-images.githubusercontent.com/70992721/96501628-fd243d80-1226-11eb-9bfd-2cdba7059fd0.png)


Ai tu clica em ir para pagina de login e só fica nisso =/...

**Comment by Pr3d4dor** [comment]
@WBV-CWB Como comentado em outras issues, o atualizador tem alguns problemas, por isso recomendo realizar a atualização manualmente.

Mas no seu caso, só arrumar index.php e o application/config.php
