### ISSUE TITLE
Erro ao Editar Usuario. Documento já cadastrado.

### ISSUE THREAD

**Issue by Pedott** [RamonSilva20/mapos#968]
Bom dia amigos, Apenas uma duvida, a algum tempo atrás editei o arquivo config/form_validation. onde adicionei o seguinte parâmetro
'field' => 'documento',
            'label' => 'CPF/CNPJ',
            'rules' => 'required|trim|verific_cpf_cnpj|is_unique[clientes.documento]',
            'errors' => [
                'verific_cpf_cnpj' => "O campo %s não é um CPF ou CNPJ válido.",
                'is_unique' => "Documento já cadastrado.". 

Isso foi feito justamente para eu não cadastrar duas pessoas com o mesmo CPF
Porem junto com isso vem o problema de eu não conseguir "editar" mais o Cliente, pois ao clicar em Atualizar aparece o erro:
"Documento já cadastrado."
Será q é possível corrigir este pequeno erro alterando alguma linha de codigo?
Pois pelo que entendi, ao clicar em Atualizar o Mapos se baseia nos Cpf cadastrado, e entende como se fosse um novo cadastro.
Agradeço desde ja. Obrigado

**Comment by Pr3d4dor** [comment]
@Pedott Obrigado por reportar o bug, iremos corrigir assim que possível.

**Comment by Pr3d4dor** [comment]
@Pedott basta você editar o arquivo: `application/helpers/validation_helper.php`

Colocando a função abaixo no final:
```
if (!function_exists('unique')) {
    function unique($value, $params)
    {
        $CI = &get_instance();
        $CI->load->database();

        $CI->form_validation->set_message('edit_unique', "Sorry, that %s is already being used.");

        list($table, $field, $current_id, $key) = explode(".", $params);

        $query = $CI->db->select()->from($table)->where($field, $value)->limit(1)->get();

        if ($query->row() && $query->row()->{$key} != $current_id) {
            return false;
        } else {
            return true;
        }
    }
}
```

No arquivo: `application/config/form_validation.php`:

Você deixa a linha 13 assim:
```
'rules' => 'required|trim|verific_cpf_cnpj|unique[clientes.documento.' . $this->uri->segment(3) . '.idClientes]'
```

As linhas 15 e 16 você muda para:
```
'verific_cpf_cnpj' => "O campo %s não é um CPF ou CNPJ válido.",
'unique' => "O campo %s já está cadastrado.",
```
