### ISSUE TITLE
oque pode ser esse erro

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#969]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Desktop (preencha as seguintes informações): **
 - SO: [por exemplo iOS]
 - Navegador [por exemplo cromo, safari]
 - Versão [por exemplo 22]

** Smartphone (preencha as seguintes informações): **
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo navegador de ações, safari]
 - Versão [por exemplo 22]

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
![image](https://user-images.githubusercontent.com/56301435/94084196-51303380-fddb-11ea-8f1f-399f01801e49.png)

**Comment by Pr3d4dor** [comment]
@wesley020291 Parece ser um problema de espaço/disco na hospedagem, não conseguiu criar o arquivo de sessão na pasta.

**Comment by vagnerlaiber** [comment]
no meu site, e instalei primeiro local na maquina e depois joguei via ftp no filezilla, confere tb a Versão do PHP
