### ISSUE TITLE
Erro ao atualizar para a versão 4.14

### ISSUE THREAD

**Issue by p-francelino** [RamonSilva20/mapos#970]
Boa tarde a todos.

Fiz a atualização da versão 3,11 que uso desde de 2018 para a atual versão. Instalei tudo correto, o primeiro problema ocorreu quando fiz o upload do banco antigo, ao logar recebi a mensagem: conta do usuário expirada, resolvi pegando  estrura da tabela atual e colando na estrutura do backup antigo jo posso logar. O grande problema foi ao chamar a pagina de OS.
![mapos](https://user-images.githubusercontent.com/71839236/94170991-1a9ffa80-fe67-11ea-9c02-e2441674eec2.jpg)
Alguém poderia me ajudar!!!

**Comment by Pr3d4dor** [comment]
@p-francelino Qual versão do MySQL você está usando?

Provavelmente faltou atualizar outras tabelas.

**Comment by vagnerlaiber** [comment]
Tenta Fazer esse procedimento,
Cria o Banco do zero sem nada, fazendo a instalação padrão do Map-OS depois que tiver abrindo certinho restaura o Backup.
