### ISSUE TITLE
Colar CNPJ no cadastro do Cliente

### ISSUE THREAD

**Issue by rohanbernartt** [RamonSilva20/mapos#971]
** Descreva o bug **
Ao colocar um numero de CNPJ no respectivo, no cadastro do cliente, o mesmo não coloca os 03 ultimos caracteres "-00"
(o traço e os dois digitos

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá em Clientes > Adicionar clientes
2. O cursor já ficará piscando no campo de CNPJ
3. Cole o CNPJ **29.376.432/0001-83**

**Comportamento esperado**
Só irá colar 29.376.432/0001

** Capturas de tela **
![Screenshot_4](https://user-images.githubusercontent.com/7140026/94222785-b9a70f80-fec4-11ea-94bb-142ed84af7c4.png)

**Comment by maycon1977** [comment]
Já tentou colocar só os números?

Até onde percebi vc diz que não inserem 3 caracteres, sendo que você colocou 2 "." e 1 "-" que já são 3 caracteres...

**Comment by rohanbernartt** [comment]
Sim,
Já tentei colar só com números "ex: 29376432000183" e ele cola só até no ...0001

**Comment by Pr3d4dor** [comment]
@rohanbernartt Obrigado po reportar o bug, iremos tentar realizar a correção assim que possível.
