### ISSUE TITLE
RELATORIO DE ORDEM DE SERVIÇO EM XLSX

### ISSUE THREAD

**Issue by vagnerlaiber** [RamonSilva20/mapos#974]
Ola colegas, a equipe que vem desenvolvendo o Map-OS está de parabéns.

VAMOS LÁ, O RELATORIO DE ORDEM DE SERVIÇO PODERIA VIR COM A SOMA TOTAL NO FINAL OU COLOCAR A OPÇÃO DO RELATÓRIO EM XLS, QUE AI FICA MAIS FÁCIL PARA SOMAR.

DESDE JÁ AGRADEÇO A ATENÇÃO.

**Comment by Pr3d4dor** [comment]
@vagnerlaiber Obrigado pela sugestão, iremos implementar assim que possível. Somente uma dúvida: Você quer o relatório em XML ou XLSX pois ficou diferente do título e descrição.

**Comment by vksaghaz** [comment]
amigo acho que voce quis dizer XLS...

**Comment by vagnerlaiber** [comment]
> @vagnerlaiber Obrigado pela sugestão, implementaremos assim que possível. Somente uma dúvida: Você quer o relatório em XML ou XLSX pois ficou diferente do título e descrição.

Sim Xlsx Desculpe a Confusão
