### ISSUE TITLE
não aceita "gramas"

### ISSUE THREAD

**Issue by seiscordas** [RamonSilva20/mapos#976]
Olá!
Eu vendo tecidos e geralmente o peso não redondo.
Na hora de cadastrar, editar e/ou vender um produto, ele não aceita gramas, eu digito em quilograma 2.6 ele arredonda para 3 e se eu digitar 2.4 ele arredonda para 2.

Eu acho que me equivoquei, tenho que tratar o peso em gramas e não e em quilos, é isso?
ex: 1kg = 1000g

Porem ainda encontro problema ao lidar com quilogramas, se 1 quilo do meu tecido é R$31,50 eu não consigo colocar em centavos ou décimos de centavos na grama, não posso colocar 0,0315 o campo de valor não aceita.

aguem tem alguma sugestão?

vlw

**Comment by seiscordas** [comment]
Pra quem quiser uma solução. Eu consegui resolver dessa forma
eu adicionei os seguintes códigos:

Models
Mapos_model.php na lina 121

    public function getProduto($id = null)
    {
        $this->db->select('produtos.*');
	$this->db->from('produtos');
        $this->db->where('idProdutos', $id);
        return $this->db->get()-row();
    }

Controllers

Vendas.php na linha 20

	$this->load->model('mapos_model');

Vendas.php na linha 273

	$dados_produto = $this->mapos_model->getProduto($produto);
		if($dados_produto->unidade == "KG"){
			$subtotal = $subtotal / 1000;
		}
------------------------------------------------------------------------------------
só teria que colocar um aviso de que o preço é por quilo.
tem que vasculhar os arquivos pra saber dos códigos, mas tá muito corrido
vlw

**Comment by Pr3d4dor** [comment]
@seiscordas Eu recomendaria você a utilizar em gramas mesmo, pois senão vc terá que manter esse código seu e pode conflitar quando tiver atualizações no mapos. Por isso recomendo manter o código mais próximo do original possível.

**Comment by seiscordas** [comment]
Então Pr3d4dor, se usar o valor em gramas não consego calcular os décimos de centavos e os cálculos ficariam errado, essa foi a forma mais simples q encontrei. Pra não comprometer muito o código e quando tiver atualização e faço as alterações novamente.

Vlw brother 👍
