### ISSUE TITLE
Adicionar imagem aos produtos.

### ISSUE THREAD

**Issue by MatheusRoas** [RamonSilva20/mapos#977]
Seria possível adicionar a imagem nos orçamentos.
cadastrando ela quando se cadastra o produto.
Grato

**Comment by Pr3d4dor** [comment]
@MatheusRoas Obrigado pela sugestão, iremos implementar assim que possível.

**Comment by visaotec** [comment]
> Seria possível adicionar a imagem nos orçamentos.
> cadastrando ela quando se cadastra o produto.
> Grato

Esse projeto eu vou acrescente por esses dias, os produtos vão ser cadastrados com fotos e vai sair no relatório também...
abraços
