### ISSUE TITLE
Erro no AutoComplete

### ISSUE THREAD

**Issue by monutb91** [RamonSilva20/mapos#978]
Primeiramente, boa noite ^^"
Então, estou fazendo a mudança do layout "[matrix old" ](https://demo.themewagon.com/preview/free-html5-bootstrap-4-admin-dashboard-template-matrix-admin )para o "[material able](http://html.codedthemes.com/material-able/bootstrap/default/index.html)"
As conexões com o banco, sendo consultas, editar, adicionar, deletar, etc funcionam perfeitamente. Porêm o autocomplete parou de funcionar ><"
Sei que em algumas paginas do sistemas há link para arquivos CSS e JS que seriam usados unicamente na pagina (eles continuam lá), não sei o que pode estar dando conflito com o autocomplete...

Enfim ... alguém a fim de ajudar? :)

**Comment by Pr3d4dor** [comment]
@monutb91 Verifique se no console do navegador não aparecem os erros de JavaScript.

**Comment by luiscadeira** [comment]
@monutb91 conseguiu resolver?

**Comment by monutb91** [comment]
> 
> 
> @monutb91 conseguiu resolver?

não consegui. Desisti de mudar o layout ><" Me deu muita dor de cabeça

**Comment by luiscadeira** [comment]
Eu também tente arrumar todo o Mapos 4.
Deu problemas no autocomplete tambem
