### ISSUE TITLE
Gente, não consigo logar!!

### ISSUE THREAD

**Issue by douglasld2** [RamonSilva20/mapos#98]
Não há nada que eu faça que seja possível o login, ja alterei a senha, tentei sem alterar, coloco o codigo q vem na pasta, la em up v2 for v3 da senha criptografada, e tento logar com 123456 mas não da!!! meu ajudem eu não sei oq fazerr!

**Comment by RamonSilva20** [comment]
Olá. Por favor verifique se o os requerimentos do sistema estão sendo atendidos pelo seu ambiente.


    PHP >= 5.4.0 < 7.0
    Extensão Mcrypt
    MySQL

**Comment by drelldeveloper** [comment]
A sua pergunta foi respondida na Issue #45.

**Comment by altairdantas** [comment]
Pessoal, quem pode me ajudar, não consigo logar, a tela de login só fica carregando. Já instalei o Mcrypt, já fiz bastante coisa e nada!.

![image](https://user-images.githubusercontent.com/50056972/56854975-8f3ed480-6915-11e9-86bc-6a6a005cd249.png)

**Comment by davibm2018** [comment]
boa tarde! alguém pode me ajuda 

não consigo logo pois só fica carregando o sistema.


![image](https://user-images.githubusercontent.com/54105222/64879206-df4fd680-d62b-11e9-8043-a200fdea50da.png)
