### ISSUE TITLE
Calendário não pesquisa (não filtra)

### ISSUE THREAD

**Issue by LipzyLipzy** [RamonSilva20/mapos#983]
Eu já atualizei o meu Mapos e esta tudo a trabalhar bem.
Mas eu tive de fazer umas alterações porque eu aproveitei o método de aplicar status no próprio sistema.
acrescentar, editar, apagar, consegui aplicar nas OS e no relatório das OS, segui o mesmo método mas não ficou a trabalhar no calendário.
já fiz varias tentativas para corrigir e não estou a conseguir resolver.
![image](https://user-images.githubusercontent.com/49565606/95130476-8d0cb680-0754-11eb-9b1a-996bdc7c8cbf.png)

como se pode ver na imagem depois de acrescentar os status eles aparecem se apagar desaparecem da lista. tudo ok.
se escolher algum ele não filtra, aparecem sempre todos.

alterações feitas em painel.php
![image](https://user-images.githubusercontent.com/49565606/95130811-060c0e00-0755-11eb-9f16-09051b2a3e19.png)

em controllers/mapos.php acrescentei
![image](https://user-images.githubusercontent.com/49565606/95131064-613e0080-0755-11eb-8f38-f016e4ae278e.png)

alguém me consegue dar uma ajuda?
Obrigado

**Comment by Pr3d4dor** [comment]
@LipzyLipzy Na tabela de OS como são salvo os status?

Você tem que alterar o código da função calendário que fica em: 
- https://github.com/RamonSilva20/mapos/blob/de6006b4e1cc929fec0bf770f50ccdafe4c09aa4/application/models/Mapos_model.php#L141
Para contemplar os seus "status" dinâmicos. O valor passado para o parâmetro "status" dessa função precisa ser o mesmo que fica na tabela os, para ele conseguir filtrar. E esse valor é dado pelo atributo value do select dos status dessa tela que vc modificou.

**Comment by LipzyLipzy** [comment]
Nas OS é salvo no status.
![image](https://user-images.githubusercontent.com/49565606/95185258-61bfb100-07c0-11eb-9b4f-b9bf92c85b7f.png)

ele é dinâmico na escolha mas depois guarda o nome em status.

**Comment by LipzyLipzy** [comment]
Estava a pensar! Se usar o sistema como foi criado (original) trabalha bem filtra e tudo aparece correcto. 
Então significa que o problema está na tabela dinâmica. Não está apanhar o nome que escolho para depois fazer o filtro. 
Como posso fazer para ele agarrar o nome da tabela dinâmica e fazer a procura com esse nome? 
Obrigado

**Comment by Pr3d4dor** [comment]
O value do select dentro do form tem que ser o mesmo valor da coluna status em OS. Então por exemplo o o value da option "Faturado" deve ser "Faturado", para que ele consiga realizar o filtro corretamente. Tem que ver como esse form_dropdown está gerando os valores do select.

**Comment by LipzyLipzy** [comment]
sim o que é guardado nas OSs tem o mesmo nome das option.

esta assim o dropdown.
![image](https://user-images.githubusercontent.com/49565606/95248736-aaeb2180-080f-11eb-8014-67df11258945.png)

peço desculpa estar a ser chato. 
ando aprender com o tempo e ainda não consigo interpretar bem o código. tenho seguido sempre exemplos nas minhas alterações.

**Comment by Pr3d4dor** [comment]
@LipzyLipzy Conseque me mandar o código completo do seu mapos e um dump do seu banco de dados?

Email: gian_bine@hotmail.com

**Comment by LipzyLipzy** [comment]
muito obrigado, já partilhei

**Comment by LipzyLipzy** [comment]
uma outra sugestão no calendário!
aparecer as cores que questão defendidas nas OS.

Não sei se será muito complicado!
