### ISSUE TITLE
Preventivas

### ISSUE THREAD

**Issue by hromanosp** [RamonSilva20/mapos#985]
É possível implementar no sistema algo como preventivas?
Inserção de equipamentos, periodicidade (mensal, bimestral e etc...), itens a ser coletadas informações para registro (medição de corrente e tensão).
Vi o sistema e gostei muito. Prático e fácil. 
Caso eu mesmo queira fazer essa implementação, quais arquivos devo modificar ou acrescer essas informações?

**Comment by Pr3d4dor** [comment]
@hromanosp É possível, porém estamos priorizando a correção de bug e não a adição de novas funcionalidades pois estamos refazendo o sistema em Laravel. Porém poderia dar mais detalhes dessa funcionalidade que você está sugerindo?
