### ISSUE TITLE
Adicionar descricao do produto na tela inicial de listas de OS

### ISSUE THREAD

**Issue by leandroperussolo** [RamonSilva20/mapos#986]
olá pessoal, eu trabalho com muitos clientes recorrentes, entao é comum ter o mesmo cliente em diferentes OS. seria possivel adicionar a descricao da OS, ou pelo menos um resumo, na tela de listas de OS?  

desde ja, obrigado

**Comment by Pr3d4dor** [comment]
@leandroperussolo Sim, é possível, iremos adicionar assim que possível.
