### ISSUE TITLE
Mudar status para "faturado" sem precisar entrar em "editar os"

### ISSUE THREAD

**Issue by leandroperussolo** [RamonSilva20/mapos#987]
ola pessoal, seria possivel uma funcionalidade para mudar status para faturado sem precisar em editar os e mudar uma por uma?  eu realizo a conferencia do faturamento em um dia especifico do mes, entao fica bem trabalhoso mudar status de uma por uma. Se fosse possivel facilitar esse processo somente com um clique na propria tela inicial de os, facilitaria muito a vida dos empresarios. abraco

**Comment by visaotec** [comment]
Olá leandroperussolo !
eu fiz essa condição no Mapos, caso queira me chama que te passo o código ok
eu consigo editar OS em massa sem precisar editar uma por uma ....
abraços

**Comment by leandroperussolo** [comment]
muito obrigado meu amigo, se puder me passar eu agradeco. meu email é lbperussolo@hotmail.com. abraco

**Comment by Pr3d4dor** [comment]
@visaotec Se você se quiser você poderia fazer uma PR disponibilizando isso para o mapos em geral. Senão eu tentarei em pensar em alguma forma de implementar isso.

**Comment by acinformatica2004** [comment]
Se puder enviar pra mim, cristianofcsm@yahoo.com.br. Obrigado

**Comment by visaotec** [comment]
Bom dia,
@Pr3d4dor Eu quero disponibilizar o código para todos, preciso que alguém me ajuda a fazer uma RP pra deixar visível para todos
aguardo retorno

**Comment by visaotec** [comment]
Eu quero muito contribuir. Mas é só quem tem conta paga que consegue criar uma RP,como nao tenho ...então nao consigo
abraços

**Comment by acinformatica2004** [comment]
Teria como enviar por email pra mim? Obrigado

**Comment by visaotec** [comment]
Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by visaotec** [comment]
> Teria como enviar por email pra mim? Obrigado

Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by visaotec** [comment]
> ola pessoal, seria possivel uma funcionalidade para mudar status para faturado sem precisar em editar os e mudar uma por uma? eu realizo a conferencia do faturamento em um dia especifico do mes, entao fica bem trabalhoso mudar status de uma por uma. Se fosse possivel facilitar esse processo somente com um clique na propria tela inicial de os, facilitaria muito a vida dos empresarios. abraco

Quem quiser testar o sistema segue o link e usuário e senha abaixo
https://nacionalsistemas.000webhostapp.com/index.php/login
usuário: convidado@gmail.com
Senha: 123456
abraços

**Comment by LipzyLipzy** [comment]
Podem partilhar comigo também? 
Obrigado
