### ISSUE TITLE
Produtos sem estoque aparecendo em relatório de produtos

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#988]
Olá tudo bem com vocês parceiros...
Alguém sabe como colocar uma condição pra produtos sem estoque  não sair no relatórios de produtos ... no PDF ?
desde já agradeço

**Comment by visaotec** [comment]
Problema resolvido.... consegui resolver, agora se o estoque estiver zerado. Já não aparece mais em relatório.
infelizmente não tive nenhuma ajuda aqui do projeto....

**Comment by Pr3d4dor** [comment]
@visaotec Peço desculpas, mas eu estava muito atarefado no trabalho e por isso demorei para responder. Mas que bom que você conseguiu resolver, eu ia apenas sugerir para mudar a consulta para pegar a quantidade em estoque > 0.
