### ISSUE TITLE
Usabilidade

### ISSUE THREAD

**Issue by gustavomellocosta** [RamonSilva20/mapos#989]
Boa tarde, achei esse sistema no youtube, e me interessei por ele ser personalizavel e com diversas atualizações, tenho uma loja de pequeno porte e usaria para controlar estoque e ordens de serviços, é confiavel ?

**Comment by leandroperussolo** [comment]
sim, eu uso para ordens de servico de laboratorio de protese e estou satisfeito. apos personalizacoes ficom muito bom trabalhar. é confiavel sim, mas na duvida eu faco backup todo dia. é bem facil

**Comment by gustavomellocosta** [comment]
> sim, eu uso para ordens de servico de laboratorio de protese e estou satisfeito. apos personalizacoes ficom muito bom trabalhar. é confiavel sim, mas na duvida eu faco backup todo dia. é bem facil

Obrigado pela indicação amigo, vou estudar o sistema e tentar adequar ao que eu preciso !
