### ISSUE TITLE
@visaotec Se você se quiser você poderia fazer uma PR disponibilizando isso para o mapos em geral. Senão eu tentarei em pensar em alguma forma de implementar isso.

### ISSUE THREAD

**Issue by visaotec** [RamonSilva20/mapos#990]

**Comment by Pr3d4dor** [comment]
@visaotec Você precisa criar um fork do projeto, colocar suas modificações e cria a Pull Request (PR) aqui no GitHub.

https://imasters.com.br/desenvolvimento/como-contribuir-com-um-projeto-no-github
