### ISSUE TITLE
Erro ao gerar relatório em PDF

### ISSUE THREAD

**Issue by robertonfaustino** [RamonSilva20/mapos#991]
Pessoal desculpe minha ignorância, mas estou com o seguinte erro:

Quando vou gerar qualquer relatório, seja do financeiro, os, produtos... Todos, se gerar em XML ele abre normal, mas se gerar em PDF ele retorna com o erro que está em anexo (screenshot)

O sistema está hospedado em uma hospedagem compartilhada, composer instalado, php 7.2

Pode ser que seja algo simples, porém até o momento não encontrei a solução.
Desde ja agradeço, se algém tiver uma dica.

![índice](https://user-images.githubusercontent.com/38968509/95639659-ae7ce380-0a6f-11eb-8f8b-1a7e1be2932e.png)

**Comment by rohanbernartt** [comment]
Quando instalou, rodou o comando ` composer install --no-dev`?

As permissões nas pastas que pede no momento da instalação, estão OK?

**Comment by robertonfaustino** [comment]
> 
> 
> Quando instalou, rodou o comando ` composer install --no-dev`?
> 
> As permissões nas pastas que pede no momento da instalação, estão OK?
> 
> Estou usando a ultima versão, e não tenho nenhum problema com os Relatórios

Sim, rodei o comando, as permissoes todas corretas.... esse problema me persegue a muito tempo, pensei que poderia sel algum erro do sistema, mas mesmo depois de varias atualizações o erro continua.

Eu sei que não é no sistema, só nao sei onte está o erro, se é algo do php ou da própria hospedagem

**Comment by Pr3d4dor** [comment]
@robertonfaustino Vá em configurações >> emitente e faça upload do logo em outro formato (jpg, png, etc)

**Comment by robertonfaustino** [comment]
> 
> 
> @robertonfaustino Vá em configurações >> emitente e faça upload do logo em outro formato (jpg, png, etc)

Caramba, vc é um gênio, o problema nao era especificamente o a extensão do arquivo, pois ja estava em jpg, eu apenas diminui o tamando (largura x altura) pq tava muito grande, depois que fiz isso abriu os relatórios normalmente.

Valeu, muito obrigado
