### ISSUE TITLE
atualizações e banco de dados

### ISSUE THREAD

**Issue by wesley020291** [RamonSilva20/mapos#993]
Gostaria de pedir que nas novas atualizações não alterassem as colunas e a quantidade do banco de dados.
vou atualizar aqui e perco muitas informações por erro de Contagem de colunas não confere com a contagem de valores na linha.
muitas das vezes tenho que adiciona manualmente.

**Comment by Pr3d4dor** [comment]
@wesley020291 Lamento, mas as isso não é um problema e sim um processo normal no desenvolvimento de qualquer sistema. O banco de dados pode e vai ser sim alterado conforme o sistema vai evoluindo. Para isso em Configurações >> Sistema existe a opção "Atualizar Banco de Dados". Se não quiser utilizar a atualização do banco de dados pelo sistema, além disso na pasta updates também fica o SQL que contém a atualização das tabelas. Portanto não é um bug e sim um processo natural no desenvolvimento de um sistema.

**Comment by wesley020291** [comment]
entendi, devo estar fazendo errado. primeiro faço bcap do anterior e depois atualizo com o novo sistema. depois de pronto funcionando vo la direto no banco e aplico o bcap. mas da erro de tabelas e tal. isso é certo ou estou errado?

**Comment by wesley020291** [comment]
entendi, devo estar fazendo errado. primeiro faço bcap do anterior e depois atualizo com o novo sistema. depois de pronto funcionando vo la direto no banco e aplico o bcap. mas da erro de tabelas e tal. isso é certo ou estou errado?

**Comment by Pr3d4dor** [comment]
@wesley020291 Você precisa aplicar as atualizações no banco de dados após ter restaurado o backup, pois o backup não conterá as novas colunas.

**Comment by wesley020291** [comment]
mas no sistema antigo ou ja no novo?

**Comment by Pr3d4dor** [comment]
@wesley020291 No sistema novo.
