### ISSUE TITLE
Classificação de Despesas e Receitas (Financeiro)

### ISSUE THREAD

**Issue by lrochawl** [RamonSilva20/mapos#994]
Para quem utiliza o sistema em uma empresa é sempre conveniente ter um bom controle financeiro. Talvez se fosse possível incluir  a classificação de despesas e receitas dentro do sistema de forma a organizar melhor a visualização das mesmas.

**Comment by Pr3d4dor** [comment]
@lrochawl Obrigado pela sugestão, poderia detalhar melhor como você pensa que isso poderia ser implementado?

**Comment by lrochawl** [comment]
Talvez algo parecido com isto
![image](https://user-images.githubusercontent.com/49371821/96322838-10e65e80-0ff1-11eb-817a-f0e77774dc79.png)
Me refiro ao campo (conta gerencial)
